### ISSUE TITLE
 [DEBUG] got HTTP error code: 500 (Internal Server Error)

### ISSUE THREAD

**Issue by Ako0ri** [sqlmapproject/sqlmap#1118]
I want to inject some site
I got this error at start to end from sqlmap
[17:06:01] [WARNING] the web server responded with an HTTP error code (500) which could interfere with the results of the tests
[17:06:24] [DEBUG] got HTTP error code: 500 (Internal Server Error)
I did open my site in opera internet explorer and firefox and I did not get this error
What is problem?

**Comment by stamparm** [comment]
Most probably leftover SQLi inside provided parameters

**Comment by stamparm** [comment]
Or generally erroneous request. Check response traffic

**Comment by Ako0ri** [comment]
How I should do that? Give me option of sqlmap please

**Comment by stamparm** [comment]
-v 6
or
-t traffic.txt
or
--proxy="http://127.0.0.1:8080"  # with Burp being run

**Comment by MoTechStore** [comment]
ok stamparm let me try that
