### ISSUE TITLE
using '; ### instead of '; -- 

### ISSUE THREAD

**Issue by Viss** [sqlmapproject/sqlmap#1128]
I ran sqlmap against a known vulnerable host serveral times, gradually increasing the risk and the level until they reached the top, having zero luck. 

By hand, several days later, I was able to get past the login page of the site in question by issuing basically ' or 1=1; ###   instead of the typical ' or 1=1;-- 

I thought it would be prudent for you guys to add this into the list of attempts that sqlmap makes

**Comment by stamparm** [comment]
And we already do that. Something else was wrong in your case. Does that `;` needed to be there in your case?

![pp](https://cloud.githubusercontent.com/assets/921555/5852704/5e8b7124-a21b-11e4-9bc7-74b6dc494d7e.png)

**Comment by Viss** [comment]
one hash mark didn't work, three did.
And yes, that semicolon was required.

**Comment by stamparm** [comment]
So you really had a special case. We already have tons of payloads/boundaries. Also, we have a special option for this kind of special cases: `--suffix`
