### ISSUE TITLE
Tamper script's kwargs is empty?

### ISSUE THREAD

**Issue by misterjyu** [sqlmapproject/sqlmap#1156]
Hi,

I am trying to make a custom tamper script, and I looked at the existing x-forwardedfor.py which demonstrates adding a new entry to the header to kwargs.  However, printing kwargs to console indicates it remain empty.

def tamper(payload, **kwargs):
    """
    Append a fake HTTP header 'X-Forwarded-For' to bypass
    WAF (usually application based) protection
    """

    headers = kwargs.get("headers", {})
    headers["X-Forwarded-For"] = randomIP()
    return payload

Am I doing something wrong? 
I am using sqlmap-0.9-4022-g66c2a79

**Comment by stamparm** [comment]
Yes, you are doing something wrong. You haven't stated how you `print` kwargs. With this:

```
def tamper(payload, **kwargs):
    """
    Append a fake HTTP header 'X-Forwarded-For' to bypass
    WAF (usually application based) protection
    """

    headers = kwargs.get("headers", {})
    headers["X-Forwarded-For"] = randomIP()
    print kwargs
    print headers
    return payload
```

you would get something like this:

```
{'headers': {'X-Forwarded-For': '30.222.57.120'}}
{'X-Forwarded-For': '30.222.57.120'}
````

Also, when using `-v 5` you would see an output similar to:
```
...
Accept-encoding: gzip,deflate
X-forwarded-for: 30.222.57.120
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-agent: Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.2 Safari/532.0
...
```
