### ISSUE TITLE
command sql-query just read 'SELECT'

### ISSUE THREAD

**Issue by mrozzzz** [sqlmapproject/sqlmap#1159]
Hello im trying, and trying any consult with sql-query and dont get nothing, sqlmap just read SELECT and not more... anyone can help me? maybe is a configuration...

http://prntscr.com/60yosz

repeat this not a problem of sql consult, im trying in another machine the same consults and working fine..

**Comment by stamparm** [comment]
So, you are trying to run SQL statement `SELECT` without any parameters?

**Comment by mrozzzz** [comment]
with parameters, and sqlmap just read SELECT...

**Comment by stamparm** [comment]
And what are the parameters. I've just tried it and everything works fine.
![www](https://cloud.githubusercontent.com/assets/921555/6042548/139d9f8c-ac86-11e4-94ed-58b0bb2f244c.png)

**Comment by mrozzzz** [comment]
Look i have inject from a database, And try to get information from a database for example im try to get  --sql-query="select password from dba_users" and the sql query just ready "SELECT" the other words dont ready.

**Comment by stamparm** [comment]
Look, you haven't given anything useful for this Issue request. I have to pull out information from you.

**Comment by stamparm** [comment]
Why I need to beg from people to write down anything remotelly useful for recognition of problem???

**Comment by stamparm** [comment]
Now it should work
