### ISSUE TITLE
sqlmap --start=1000 problem

### ISSUE THREAD

**Issue by onlygilang** [sqlmapproject/sqlmap#1164]
hi i just confused, 

its about Microsoft SQL Server/Sybase stacked queries, i can get table and columns about 150000 entry in table User, 
but how can i dump only from 75000, and it was automatic getting Pivot from what sqlmap choice 
"getting USER_ID as pivot", but the problem its start from raw 100000 instead of 1
 and after dumping till 100120 it was automatic getting to  50000 ?? how do i specifie a raw data for dumping table/column?

**Comment by stamparm** [comment]
It skips first N entries for chosen pivot column. If it starts with `75000` it will skip to the entry having `75000 + N`. Also, MsSQL doesn't have a classic `LIMIT m,n` mechanism. That means that you can't just skip to whatever you want. sqlmap has to manually skip N entries for chosen pivot column so it could start dumping rows starting with N+1th pivot value.

**Comment by onlygilang** [comment]
so how to get alternative,

i have 150000 entry and the value was assigned to column USER_ID (1-150000)

but first 750000 is junk, i need to dump only 750001-150000

is it posible in mssql? ,

**Comment by stamparm** [comment]
Have you tried `--where="USER_ID>75000"`?

**Comment by onlygilang** [comment]
wow,. :+1:   thanks i dont know if sqlmap has --where options ,
its works perfectly while i using --where="user_id=75000" it give me correct,
and when i use --where="user_id>100112" its give me also correct, its start dumping from 100113,
but while i use --where="user_id>75000" why it start from 100000 instead of 75001,?

:( :( :(

**Comment by stamparm** [comment]
Don't know. Please don't use --where in combination with --start on MsSQL if you want to skip any problems.
