### ISSUE TITLE
How to count columns entries in sqlmap?

### ISSUE THREAD

**Issue by pillsmgh** [sqlmapproject/sqlmap#1165]
Hello,

i want to know that how to count column entries like we can do with tables..

Ex:-

suppose table1 have 2 column named email/pass and now i want to know that how many entries in each column.

any switch or command to know this?

Thanks in advance.

**Comment by stamparm** [comment]
--sql-query="SELECT COUNT (colname) FROM tblname"

**Comment by pillsmgh** [comment]
Thanks for fast reply sir but as i'm seeing that i can use it for one by one url.
but i want to use it for when i'm using -m option (bulk file check).
following is the command which i'm using..

-m C:/Users/admin/Desktop/Sql/1st.txt --ignore-proxy -o --keep-alive --null-connection --threads=10 --timeout=3 --retries=5 --no-cast --batch --dbs --tables --columns --exclude-sysdbs --eta --smart

i have 100 url in my file for scan and i don't want to go and check each url database->table>column one by one.

waiting for your reply.

Thanks.

**Comment by stamparm** [comment]
Too specific case. Adapt to existing functionality
