### ISSUE TITLE
File write on PostgreSQL 9.1.15 fails

### ISSUE THREAD

**Issue by inquisb** [sqlmapproject/sqlmap#1170]
File write operations (hence takeover) fails on PostgreSQL 9.1.5 with an error on lo_export():
```
[20:47:01] [PAYLOAD] 1;SELECT lo_export(2008, '/tmp/test123.txt')--
[20:47:01] [WARNING] parsed DBMS error message: 'ERROR:  pg_largeobject entry for OID 2008, page 0 has invalid data field size 2378'
```

This happens also if connected as `postgres` with psql to the database locally. Same statements worked on PostgreSQL 9.1.11.

Check documentation on http://www.postgresql.org/docs/9.1/static/catalog-pg-largeobject.html.

**Comment by RicterZ** [comment]
Hello, I read the document and found: 

     The amount of data per page is defined to be LOBLKSIZE (which is currently BLCKSZ/4, or typically 2 kB).

It means that every block of the data inserted into `pg_largeobject` less than 2kb.  
So, I think you should split the data:   

     SELECT lo_create(12345);
     INSERT INTO pg_largeobject VALUES (12345, 0, decode('7f454c4...0000', 'hex')); //less than 2kb
     INSERT INTO pg_largeobject VALUES (12345, 1, decode('0000000...0000', 'hex'));  //less than 2kb
     INSERT INTO pg_largeobject VALUES (12345, 2, decode('f604000...0000', 'hex')); //less than 2kb
     INSERT INTO pg_largeobject VALUES (12345, 3, decode('0000000...7400', 'hex')); //less than 2kb
     SELECT lo_export(12345, '/tmp/test.so');
     SELECT lo_unlink(12345);

**Comment by inquisb** [comment]
@RicterZ thanks for trouble-shooting this.

**Comment by Kamulha** [comment]
Hi!
I encountered this problem with PostgreSQL 9.1.16 and 9.1.18 (64 bit).
The strange thing is that SQLMap doesn't output any problem, it says the right file size on the server (8136 bytes).
But obliviously nothing is working, --os-shell gives no output and --os-pwn encounters a timeout with all of the available options.
Are you going to fix this soon?
Thanks in advance.
Kamulha

**Comment by stamparm** [comment]
Will deal with it these days

**Comment by Kamulha** [comment]
Thank you very much for the (instant) answer :smile:
I will wait for the fix and report here the results :wink:

**Comment by stamparm** [comment]
Couple of related screenshots:

![1](https://cloud.githubusercontent.com/assets/921555/8874765/46695230-3214-11e5-839d-e9f8ca3ad070.png)
![2](https://cloud.githubusercontent.com/assets/921555/8874769/4690a74a-3214-11e5-81b7-4c94090855d8.png)
![3](https://cloud.githubusercontent.com/assets/921555/8874768/46908846-3214-11e5-972d-7ba01f22d048.png)
![4](https://cloud.githubusercontent.com/assets/921555/8874767/468defa0-3214-11e5-9a9d-9ff0341d3d8a.png)
![5](https://cloud.githubusercontent.com/assets/921555/8874766/468d1a9e-3214-11e5-981d-48993f2e4f9d.png)
![6](https://cloud.githubusercontent.com/assets/921555/8874770/4693437e-3214-11e5-92c2-3eb27d297ff9.png)

**Comment by RicterZ** [comment]
:+1:

**Comment by stamparm** [comment]
still have some stuff to do :)

**Comment by stamparm** [comment]
Now it should work on both PostgreSQL 8 and >=9 ;)

**Comment by Kamulha** [comment]
I tested it right now and it works, thank you very much for your work :smile:
But I have a "problem": command output retrieving is very slow, because I have only a time based injection associated to the stacked queries; I have a boolean-based blind injection, but it's associated to the other parameter.
So I had a beautiful idea: I have the DBMS credentials and I can upload any pages on the server: I want to upload a totally vulnerable page.
There are a lot of pages in "testenv", but I don't know which one is the "best".

**Comment by stamparm** [comment]
Maybe you'll have problems with WRITE permissions, but that's maybe.

Combination of https://raw.githubusercontent.com/sqlmapproject/testenv/master/libs/pgsql.inc.php and https://raw.githubusercontent.com/sqlmapproject/testenv/master/pgsql/get_int.php should suffice. You'll have to modify them though (username, password, ...).

**Comment by Kamulha** [comment]
Thank you, I'm going to try this right now :smile:

**Comment by stamparm** [comment]
@Kamulha no. `pgsql.inc.php` also contains function `dbQuery`. Concatenate those two files (`get_int.php` and `pgsql.inc.php`), modify settings (username, password, port, etc.) and upload them as one file.

**Comment by Kamulha** [comment]
Done, the problem is that SQLMap doesn't upload the file properly.
It says the right file size when checking if the file has successfully been uploaded, but if I go on the page with the browser there is a 404 error.
I tried to use --file-read and it doesn't output anything...

**Comment by stamparm** [comment]
file size check is broken. its from independent of this issue. will check later.

**Comment by Kamulha** [comment]
Ok, thank you :smile:
I just tried to read a file on the server and it works... is there a problem with --file-write?

**Comment by stamparm** [comment]
I am not sure if I follow. Can you please explain what you meant with this last message?

**Comment by Kamulha** [comment]
I concatenated the two files you linked me in one file (with the right credentials) and I tried to upload it with --file-write; it says the right file size when it checks the file (as you said file size check is broken), but if I go on the page with my browser there's a 404 error: the file hasn't been uploaded.
After, I tried to use --file-read to read the file that should have been uploaded, but there isn't any output, so I tried to read a file that exists on the server and SQLMap retrieved it successfully.
This is why I think there's a problem with --file-write :wink:

**Comment by stamparm** [comment]
I would say that you have write permission problems. Have you tried to write to e.g. directory `/tmp`. I've warned you about this

**Comment by Kamulha** [comment]
I'm trying now to upload the file to /tmp directory.
Anyway, that's the first DB error: pg_query(): Query failed: ERROR:  table "sqlmapfile" does not exist
And this is the same error happened with --os-shell before the patch...

**Comment by stamparm** [comment]
`table "sqlmapfile" does not exist` is a standard error. Its just cleaning (if exists) the old table

**Comment by Kamulha** [comment]
Oh, sorry, I didn't know... I tried to upload the file in the /tmp/ directory.

Errors:
pg_query(): Query failed: ERROR:  table "sqlmapfile" does not exist
pg_query(): Query failed: ERROR:  table "sqlmapfilehex" does not exist
pg_query(): Query failed: ERROR:  table "sqlmapfile" does not exist
pg_query(): Query failed: ERROR:  large object 3296 does not exist

And a lot of these errors:
Uncaught exception 'PDOException' with message 'SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(255)' in /var/www/.../....php:2
Stack trace:
#0 /var/www/.../....php(2): PDOStatement->execute()
#1 /var/www/.../....php(2): MT\Logger\om\BaseActivity->doInsert(Object(PropelPDO))
#2 /var/www/.../....php(2): MT\Logger\om\BaseActivity->doSave(Object(PropelPDO))
#3 /var/www/.../....php(2): MT\Logger\om\BaseActivity->save()
#4 /var/www/.../....php(2): MT\Logger\Logger->log(Array)
#5 {main}

Next exception 'PropelException' with message 'Unable to execute INSERT statement [INSERT INTO "activity" ("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13") VALUES (:p0, :p1, :p2, :p3, :p4, :p5, :

How can I know if the file has been successfully uploaded into /tmp/?

**Comment by stamparm** [comment]
@Kamulha this really doesn't look like a generic case. Not sure how to help you here

**Comment by Kamulha** [comment]
This is a different vulnerable php file than the one I used before. I used this one only to log the errors, I think that the other file doesn't have any "string truncate" problem.
Anyway, I used --file-read to read the file I uploaded in the /tmp/ directory and it doesn't output anything... I can't understand why, because SQLMap uses the /tmp/ directory successfully for the UDF...

**Comment by Kamulha** [comment]
Nothing to do even with a small file...
