### ISSUE TITLE
SSL connection error occurred

### ISSUE THREAD

**Issue by vietnguyen09** [sqlmapproject/sqlmap#1174]
I have this error, I used --force-ssl but still got error!

[03:06:37] [DEBUG] SSL connection error occurred ('[Errno 1] _ssl.c:492: error:14094410:SSL routines:SSL3_READ_BYTES:ssl
v3 alert handshake failure')

**Comment by stamparm** [comment]
That just means that SSL3 is not supported by your end server. sqlmap should try other SSL protocols too (("PROTOCOL_SSLv3", "PROTOCOL_TLSv1", "PROTOCOL_SSLv23", "PROTOCOL_SSLv2")). 

Please disregard that specific debug message. It just says what I've told you this moment.

**Comment by stamparm** [comment]
What does e.g. https://www.ssllabs.com/ssltest say for that site in the "Protocols" part?

**Comment by vietnguyen09** [comment]
Thanks so much for your support, I have updated my SSL to v3 and now SQLMAP is work fine :) :+1:

**Comment by maguaweb** [comment]
I have this error:

 SSL connection error occurred for 'PROTOCOL_TLSv1_2' ('ConnectionResetError: 远程主机强迫关闭了一个现有的连接。')
