### ISSUE TITLE
Windows usage starting problem

### ISSUE THREAD

**Issue by gitclone** [sqlmapproject/sqlmap#1177]
Tested last commit in last Kali, and no issues, but on Win - sqlmap says: [CRITICAL] --union-cols must be a range of integers
No difference between attack sites or DB or Techiques usage, allways same CRITICAL.
Fixya plz.

**Comment by stamparm** [comment]
I believe that you use an old version/revision. Can you please check?

**Comment by gitclone** [comment]
Yep, I believe too, and cleanup TEMP of LOCALMACHINE and sqlmap folders, and now all is allright. Thanks man. Hope, if any others have a same issue, can read this top.
