### ISSUE TITLE
problem extracting data

### ISSUE THREAD

**Issue by ashee69** [sqlmapproject/sqlmap#1180]
hello team,
i have mentioned this problem somewhere else too but it is kinda pathetic now
so i m explaining here again
i have a injectable url with these details
Parameter: item (GET)
    Type: AND/OR time-based blind
    Title: MySQL > 5.0.11 AND time-based blind (SELECT)
    Payload: item=105 AND (SELECT * FROM (SELECT(SLEEP(5)))QRnu)
    Vector: AND (SELECT * FROM (SELECT(SLEEP([SLEEPTIME]-(IF([INFERENCE],0,[SLEEPTIME])))))[RANDSTR]

and the command i followed after reading so many issues about it
sqlmap  --banner --safe-url=2 --safe-freq=3  --tamper=between -v 2  -D database_name --tables --no-cast --fresh-queries --binary-fields --time-sec=30

[23:41:29] [DEBUG] declared web page charset 'utf-8'
and it extracting 1 entry name in about 1000 sec after i am doing it without burp and tor.
is there any way to speed it up and in database names 'blob' term is coming too frequently.
please help me here and suggest me some document to understand these kind of issue as i am reading extensively these days.
thank you as always.

**Comment by ashee69** [comment]
and it is not extracting entry name correctly, like "informakpn_schema"
i get it now that it is latency issue but how to get over this.
plz help

**Comment by stamparm** [comment]
Please don't use time-based SQLIA to dump everything, especially databases/tables with names like blob. Time-based SQLIA should be used in only basic data retrieval as its highly unstable (because of network latency).

How to get over the latency issues? Lease a (no the cheapest) VPS server. That should give you good starting point.

**Comment by ashee69** [comment]
okey, so shall i switch over to another technique when i found the injection point ? or some other way ?
please give some hint. 
thanks for ur response.

**Comment by stamparm** [comment]
I've already given a hint in last reply.

Please understand that there is no silver bullet in timing attacks
