### ISSUE TITLE
Error finding Column that was discovered 

### ISSUE THREAD

**Issue by onlygilang** [sqlmapproject/sqlmap#1183]
hello , i find a bug with microsoft time based, i was using dumping data 4 second/char in mssql , 
im using mutiple console dumping another columns, sometime it was disconnected, and i need to use ctrl+c , but while i back to previous command that i used, it was resumed with error

 sqlmap was discovered the columns name before but sometimes i got this while dumping column:

unable to fetch column '  '  /// blank instead of column name:
unable to fetch column '/t' /// and this 
unable to fetch column '[]' /// also this

i thing the problem was on sessions so i remove the file session.sqlite. after i remove , yes it was work fine, but the problem is i need to dumping data back from 0, since i was dumping 4second/char along more than 12hours, so i lost data that was dummped in 12 hours,

how to prevent this error?

**Comment by stamparm** [comment]
`im using mutiple console dumping another columns,`
please don't do this. you are warned at least couple of times through run to not disrupt the network connection
