### ISSUE TITLE
some oracle error-based injection payloads

### ISSUE THREAD

**Issue by jhdxr** [sqlmapproject/sqlmap#1184]
![payload](http://static.wooyun.org/upload/image/201503/2015030307085177417.jpg)

from http://zone.wooyun.org/content/18877

**Comment by stamparm** [comment]
We already do have:
```
XMLType
UTL_INADDR.GET_HOST_ADDRESS
CTXSYS.DRITHSX.SN
```
for Oracle error-based. I (personally) am aware of more similar Oracle functions for years, but I am not quite sure wether we need to include them all.

**Comment by stamparm** [comment]
I'll close this one down. With the latest patch we have 4 Oracle's error-based SQLi payloads. In majority of cases, if DBMS errors are turned on all of them would suffice. We really don't need more.
