### ISSUE TITLE
"unhandled exception occurred in sqlmap/1.0-dev-nongit-20150308

### ISSUE THREAD

**Issue by adzon** [sqlmapproject/sqlmap#1189]
sqlmap version: 1.0-dev-nongit-20150308\nPython version: 2.7.9
Operating system: nt
Command line: sqlmap.py --pickled-options gAJjbGliLmNvcmUuZGF0YXR5cGUKQXR0cmliRGljdApxACmBcQEoVQdvc1NoZWxscQKJVQhnZXRVc2Vyc3EDiVURZ2V0UGFzc3dvcmRIYXNoZXNxBIlVDWV4Y2x1ZGVTeXNEYnNxBYlVBXVDaGFycQZOVQdyZWdEYXRhcQdOVQtjcHVUaHJvdHRsZXEISwVVBnByZWZpeHEJTlUEY29kZXEKTlUKZ29vZ2xlUGFnZXELSwFVBHNraXBxDE5VBXF1ZXJ5cQ1OVQtyYW5kb21BZ2VudHEOiFUFb3NQd25xD4lVCGF1dGhUeXBlcRBOVQpjcmF3bERlcHRocRFOVQtyZXF1ZXN0RmlsZXESTlUNcHJlZGljdE91dHB1dHETiVUGd2l6YXJkcRSJVQhzdG9wRmFpbHEViVUFZm9ybXNxFolVBnRhc2tpZHEXVRAzY2QzZjQ0ODc5MWY4ODFlcRhVC3Bpdm90Q29sdW1ucRlOVQ1kcm9wU2V0Q29va2llcRqJVQVzbWFydHEbiVUEcmlza3EcSwFVB3NxbEZpbGVxHU5VBnJQYXJhbXEeTlUOZ2V0Q3VycmVudFVzZXJxH4hVCW5vdFN0cmluZ3EgTlUIZ2V0Um9sZXNxIYlVDWdldFByaXZpbGVnZXNxIolVDXRlc3RQYXJhbWV0ZXJxI05VA3RibHEkTlUHY2hhcnNldHElTlULdHJhZmZpY0ZpbGVxJk5VBW9zU21icSeJVQVsZXZlbHEoSwFVC3NlY29uZE9yZGVycSlOVQlvdXRwdXREaXJxKk5VB3RpbWVvdXRxK0seVQlmaXJzdENoYXJxLE5VB3RvclBvcnRxLU5VB3JlZ1JlYWRxLolVDGJpbmFyeUZpZWxkc3EvTlUIY2hlY2tUb3JxMIlVDGNvbW1vblRhYmxlc3ExiVUGZGlyZWN0cTJOVQZzYUZyZXFxM0sAVQd0bXBQYXRocTROVQZ0aXRsZXNxNYlVCWdldFNjaGVtYXE2iVULaWRlbnRpZnlXYWZxN4lVCHBhcmFtRGVscThOVQZyZWdLZXlxOU5VCmxpbWl0U3RhcnRxOk5VDGZsdXNoU2Vzc2lvbnE7iVULbG9hZENvb2tpZXNxPE5VB2Ruc05hbWVxPU5VBmNzdkRlbHE+VQEscT9VBm1ldGhvZHFATlUFb3NCb2ZxQYlVDmludmFsaWRMb2dpY2FscUKJVQxnZXRDdXJyZW50RGJxQ4hVCmhleENvbnZlcnRxRIlVCXByb3h5RmlsZXFFTlUHYW5zd2Vyc3FGTlUEaG9zdHFHTlUMZGVwZW5kZW5jaWVzcUiJVQZjb29raWVxSU5VBXByb3h5cUpOVQdyZWdUeXBlcUtOVQhvcHRpbWl6ZXFMiVUJbGltaXRTdG9wcU1OVQltbmVtb25pY3NxTk5VBXVGcm9tcU9OVQZub0Nhc3RxUIlVCnRlc3RGaWx0ZXJxUU5VA2V0YXFSiVUJY3NyZlRva2VucVNOVQd0aHJlYWRzcVRLClUHbG9nRmlsZXFVTlUCb3NxVk5VA2NvbHFXTlUFckZpbGVxWE5VCXByb3h5Q3JlZHFZTlUHdmVyYm9zZXFaSwFVBWlzRGJhcVuJVQl1cGRhdGVBbGxxXIlVB3ByaXZFc2NxXYlVCGZvcmNlRG5zcV6JVQZnZXRBbGxxX4lVA2FwaXFgiFUDdXJscWFYLgAAAGh0dHA6Ly9tYWlsMi5rYmZpLmVlL2luZGV4LnBocD9pZD02OTQmbGFuZz1lbmdxYlUNaW52YWxpZEJpZ251bXFjiVUGcmVnZXhwcWROVQZnZXREYnNxZYlVDGZyZXNoUXVlcmllc3FmiVUFdUNvbHNxZ05VCXNtb2tlVGVzdHFoiVUFd0ZpbGVxaU5VCXVkZkluamVjdHFqiVUNaW52YWxpZFN0cmluZ3FriVUDdG9ycWyJVQhmb3JjZVNTTHFtiVUJaWdub3JlNDAxcW6JVQRiZWVwcW+JVQtzYXZlQ21kbGluZXFwiVUKY29uZmlnRmlsZXFxTlUFc2NvcGVxck5VB2R1bXBBbGxxc4lVB3RvclR5cGVxdFUESFRUUHF1VQZyZWdWYWxxdk5VBWR1bW15cXeJVQZzZWFyY2hxeIlVDXNraXBVcmxFbmNvZGVxeYlVB3JlZmVyZXJxek5VCGxpdmVUZXN0cXuJVQtwdXJnZU91dHB1dHF8iVUHcmV0cmllc3F9SwNVC2F1dGhQcml2YXRlcX5OVQtleHRlbnNpdmVGcHF/iVUJZHVtcFRhYmxlcYCJVQhkYXRhYmFzZXGBVTVjOlxkb2N1bWV+MVxhZG1pbml+MVxsb2NhbHN+MVx0ZW1wXDFcc3FsbWFwaXBjLTM1dWNkanGCVQViYXRjaHGDiFUHaGVhZGVyc3GETlUIYXV0aENyZWRxhU5VBW9zQ21kcYZOVQZzdWZmaXhxh05VCGRibXNDcmVkcYhOVQZyZWdEZWxxiYlVBXNoTGlicYpOVQpzaXRlbWFwVXJscYtOVQd0aW1lU2VjcYxLBVUHbXNmUGF0aHGNTlUIbm9Fc2NhcGVxjolVC2dldEhvc3RuYW1lcY+JVQtzZXNzaW9uRmlsZXGQTlUPZGlzYWJsZUNvbG9yaW5ncZGIVQlnZXRUYWJsZXNxkolVBWFnZW50cZNOVQhsYXN0Q2hhcnGUTlUGc3RyaW5ncZVOVQRkYm1zcZZOVQlkdW1wV2hlcmVxl05VBnRhbXBlcnGYTlUDaHBwcZmJVQdydW5DYXNlcZpOVQVkZWxheXGbSwBVCGV2YWxDb2RlcZxOVQdjbGVhbnVwcZ2JVQdjc3JmVXJscZ5OVQlnZXRCYW5uZXJxn4lVB3Byb2ZpbGVxoIlVC2dldENvbW1lbnRzcaGJVQhidWxrRmlsZXGiTlUGc2FmVXJscaNOVQJkYnGkTlUKZXhjbHVkZUNvbHGlTlUKZHVtcEZvcm1hdHGmVQNDU1Zxp1UFYWxlcnRxqE5VDm51bGxDb25uZWN0aW9ucamJVQR1c2VycapOVQtwYXJzZUVycm9yc3GriVUIZ2V0Q291bnRxrIlVBWRGaWxlca1OVQRkYXRhca5OVQZyZWdBZGRxr4lVC2lnbm9yZVByb3h5cbCJVQpnZXRDb2x1bW5zcbGIVQZtb2JpbGVxsolVCmdvb2dsZURvcmtxs05VCHNxbFNoZWxscbSJVQhwYWdlUmFua3G1iVUEdGVjaHG2VQZCRVVTVFFxt1UIdGV4dE9ubHlxuIlVCWNvb2tpZURlbHG5TlUNY29tbW9uQ29sdW1uc3G6iVUJa2VlcEFsaXZlcbuJdX1xvChVGF9BdHRyaWJEaWN0X19pbml0aWFsaXNlZHG9iFUJYXR0cmlidXRlcb5OdWIu
Technique: BOOLEAN
Back-end DBMS: MySQL (fingerprinted)

**Comment by stamparm** [comment]
p.s. sqlmap.py --pickled-options is not meant to be run as a standalone
