### ISSUE TITLE
-g, --crawl and dumping data issues

### ISSUE THREAD

**Issue by franx47** [sqlmapproject/sqlmap#1191]
Hi, 

I have several issues, such as:

#1. -g command seems to be not working with --crawl

eg: 

./sqlmap.py -g "intext:something" --random-agent --batch --hex --crawl=2 --dbs

When it found a URL link, for example: http://urlsample.com/products/

Sqlmap supposed to crawl the URL "http://urlsample.com" to the depth 2. But, it did not crawl. Sqlmap keeps trying to inject the URL as is, without crawling.

Does it working like that?

#2. It seems that SQLMap didn't use a previous session for data "dumping". 

eg: 

./sqlmap.py -u "http://urlsample.com/products.php?pid=10" --random-agent --batch --hex --dbs

Found database: 

db1
db2

Injection method = BET

./sqlmap.py -u "http://urlsample.com/products.php?pid=10" --random-agent --batch --hex -D db1 -T user --dump --start=1 --stop=10000

Suppose, in the middle of dumping process, the target server suddenly disconnected the connection, but SQLMap has successfully dumped data from table "user" starting from row 1 to row 5,000. 

When I retry to dump the data with the same command like above, SQLMap dumps the data from table "user" re-starting from row 1, not row 5001. This ofcourse spend lot of time.

Is it true that SQLMap does not use the previous "dump" session?

Thank you.

**Comment by stamparm** [comment]
`Is it true that SQLMap does not use the previous "dump" session?` - sqlmap doesn't make redundant requests afterwards. if it sees that there is a (non-NULL/None) RESULT for a QUERY inside the session it uses that same previously stored result to reconstruct the results in resume. you should inspect the sqlmap's traffic in resume to get the feeling what's going on.

i'll take a look into `-g --crawl` problem later

**Comment by franx47** [comment]
Thank you very much for your reply. 

I think I understand what's going on with the session.


Regards,
