### ISSUE TITLE
Beep when done or when input is needed

### ISSUE THREAD

**Issue by BabyBit** [sqlmapproject/sqlmap#1197]
I have an ideea /feature request; besides the --beep which is nice ...

--done-beep Beeps when command was completed
--input-beep Beeps when user needs to input something or select an option

And maybe it works better if the beeping tone is a bit different than the normal --beep, or make 2/3 short beeps in the above situations. 

Since some commands take a very long time, it is nice to be alerted in these situations.

**Comment by stamparm** [comment]
Beep is beep. There is no loooonger beep or shorter beep, at least this is not possible to be done to work accross all platforms. Also, we won't make new switches for sure as there are tons of unused switches already inside.

**Comment by BabyBit** [comment]
If beep is beep, then how about ```--beep-beep``` ?! Just kidding. OK.
