### ISSUE TITLE
Add sql injection of websocket support for sqlmap

### ISSUE THREAD

**Issue by RicterZ** [sqlmapproject/sqlmap#1198]
If sql injection on a websocket server, it's hardly to use sqlmap.
I write a [proxy](https://github.com/RicterZ/websocket-injection) for it, but I think the best way is that add websocket support for sqlmap.

**Comment by inquisb** [comment]
Pull requests are very much welcome :)
We can help with the sqlmap code if you need guidance.

**Comment by RicterZ** [comment]
@inquisb 
Thanks for your reply :D 
If I want to add a third-party library([websocket-client](https://github.com/liris/websocket-client)), what should I do? Should I clone it to `thirdparty/` folder or else?

**Comment by inquisb** [comment]
@RicterZ as far as I can tell, the library is packaged for for easy_install and pip so no need to add it to `thirdparty/`

**Comment by RicterZ** [comment]
I found websocket-client is not processing errors completely, so I will improve error handling of websocket.
But now, for websocket, sqlmap already working:)

I don't think my code is prefect, so if somewhere I should modify the code, please tell me, thank you very much :D

**Comment by RicterZ** [comment]
@inquisb 
I think I had finished it, please review, thx :)

**Comment by inquisb** [comment]
@RicterZ in `lib/core/options.py` write a function that checks for the websocket library if the target URL starts with `ws:/`, make sure the check is also performed when `--dependencies` switch is provided, check the source code for example.

**Comment by RicterZ** [comment]
@inquisb Got it, in fact, websocket protocol is `ws://` and `wss://` :D

**Comment by RicterZ** [comment]
@inquisb fixed, please review.

**Comment by RicterZ** [comment]
Now I can use sqlmap to sql injection:

    python sqlmap.py --url="ws://localhost?data=[sqli]" # sqli in get parameters

or 

    python sqlmap.py --url="ws://localhost" --data="*" # sqli in messages

But I think the best way is:

    python sqlmap.py --url="ws://localhost" # sqli in messages

Any way can implement it?

**Comment by inquisb** [comment]
@RicterZ make a pull request of your changes and we will review it. Thanks.

**Comment by stamparm** [comment]
Pull request 1206
