### ISSUE TITLE
running in a single-thread mode even with --threads=4

### ISSUE THREAD

**Issue by BabyBit** [sqlmapproject/sqlmap#1199]
I ran this command with URLs loaded from file, I specified --threads=4, at first it mentions "starting 4 threads", but after it runs for hours I see these on screen: ```[WARNING] running in a single-thread mode``` 

I think in some situations it should automatically go into single-thread mode, but this is not one of them, is it ?

```
sqlmap --random-agent --dbms=MySQL --threads=4 -m '/home/my list.txt' --batch --forms --crawl=2 --beep --eta --answers='sitemap=N'
```

```
[22:45:31] [INFO] 246/706 links visited (35%)
do you want to check for the existence of site's sitemap(.xml) [Y/n] N
[22:45:31] [INFO] starting crawler for target URL 'http://www.example.com'
please enter number of threads? [Enter for 1 (current)] 1                                                                                                                                                                        
[22:45:32] [WARNING] running in a single-thread mode. This could take a while
[22:55:18] [INFO] 247/706 links visited (35%) 
```

**Comment by stamparm** [comment]
Unreproducible. 

You are doing something wrong. Also, you've faked the command and/or results, as in the original command you use --batch, while in the output part there is a question for "enter the number of threads".
![screenshot - 03232015 - 11 15 43 am](https://cloud.githubusercontent.com/assets/921555/6777881/17e3a31a-d14e-11e4-92f6-b84b463e3b31.png)

**Comment by BabyBit** [comment]
I didn't fake the command or output, that is why it looks strange to me too. 

But I might have more info ... 

It was a large test, loading urls from text file, then I wanted to stop it to change the command (maybe this time I forgot about --threads), I press CTRL+C to stop it, it doesn't stop because it just moves to next URL, I press again few times, then I finally close the terminal window. Then I ran the command again in a new window, this time I make sure to specify --threads, it starts with "starting X threads" but after a few hours I notice in same window "running in single thread mode". 

Does that make sense ? Maybe old command still runs in background and the output text is shown in the new window ? 

I only see one process if I try ``ps -x | grep 'my list.txt'

I hope it doesn't sound confusing.

**Comment by stamparm** [comment]
Could be. Thing is that I can't reproduce it in normal circumstances.
