### ISSUE TITLE
Use plugin_dir rather than basedir + /lib/plugin"

### ISSUE THREAD

**Issue by newsoft** [sqlmapproject/sqlmap#1200]
https://github.com/sqlmapproject/sqlmap/blob/260643241a9373c0bdb8bd0d68df26cf1e1a3449/plugins/dbms/mysql/takeover.py#L53

Plugin directory can be customized through plugin_dir option:
http://dev.mysql.com/doc/refman/5.1/en/server-system-variables.html#sysvar_plugin_dir

You should use the output of "SELECT @@plugin_dir" which is always available, even if the user did not configure anything.

Would you like me to prepare a pull request?

**Comment by inquisb** [comment]
Go for it, but please keep in mind that plugin_dir was introduced in MySQL 5.0.67 as per https://dev.mysql.com/doc/refman/5.0/en/server-system-variables.html#sysvar_plugin_dir. See comment on https://github.com/sqlmapproject/sqlmap/blob/260643241a9373c0bdb8bd0d68df26cf1e1a3449/plugins/dbms/mysql/takeover.py#L62.

**Comment by newsoft** [comment]
Confirmed working, thank you!
