### ISSUE TITLE
[BUG]  sqlmap merge http header cookie has a bug in cookie injection

### ISSUE THREAD

**Issue by hysia** [sqlmapproject/sqlmap#1202]
ENV：
target url ： set-cookie：admin＝abc
sqlmap： --cookie "admin=abc" -p admin --level 2

in  `lib.request.basic.forgeHeaders`
when `kb.mergeCookies` is set `True` by default,
payloads in cookie will be override in code below:
```python
if kb.mergeCookies:
    _ = lambda x: re.sub(r"(?i)\b%s=[^%s]+" % (re.escape(cookie.name), conf.cookieDel or DEFAULT_COOKIE_DELIMITER), "%s=%s" % (cookie.name, getUnicode(cookie.value)), x)
    headers[HTTP_HEADER.COOKIE] = _(headers[HTTP_HEADER.COOKIE])
```
payload will not in `headers[HTTP_HEADER.COOKIE] `  and sql injection check will be failed.

Try merge cookie with default input 'N' can detect the injection

**Comment by stamparm** [comment]
Can you please explain it a bit more please?

Merge cookies should not be set by default to Y, while you say it is. You
are asked to choose whether you want Y or N.

Maybe you are just complaining that default answer for merge cookies should
be N instead of Y?

**Comment by hysia** [comment]
I mean when choose Merge cookies by default Y， payload in http header such as  `Cookie: admin=abc'  and 9527 = 9527 ...`  will be override by "Set-Cookie" value "admin=abc" .  request with payload never send to the server and the sql injection will not be identified.

**Comment by hysia** [comment]
```python
 message = "you provided a HTTP %s header value. " % HTTP_HEADER.COOKIE
 message += "The target URL provided its own cookies within "
 message += "the HTTP %s header which intersect with yours. " % HTTP_HEADER.SET_COOKIE
 message += "Do you want to merge them in futher requests? [Y/n] "
  _ = readInput(message, default="Y")
  kb.mergeCookies = not _ or _[0] in ("y", "Y")
```
