### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by mathiasbynens** [sqlmapproject/sqlmap#1203]
v0.9 (the latest tagged release) was tagged on Jul 22, 2012. Please consider tagging and releasing a new version asap.

**Comment by giveen** [comment]
Um.....He is on version 1.0

![sqlmap](https://cloud.githubusercontent.com/assets/1180939/6829497/766311be-d2d9-11e4-9ad8-62ec80f76816.PNG)

**Comment by mathiasbynens** [comment]
@giveen That’s not a tagged version.

**Comment by giveen** [comment]
@mathiasbynens I see your point, I guess, there was nothing recent listed under the "releases" section, but it doesnt take much to download the newest version.

**Comment by mathiasbynens** [comment]
That’s beside the point.

[Homebrew formulae](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/sqlmap.rb) require tagged versions, and for good reason. `brew install sqlmap` still installs v0.9 because there hasn’t been a release since then. Simply tagging a new release every now and then makes it possible to update these formulae so that even Homebrew users can get a recent `sqlmap` version.

**Comment by stamparm** [comment]
We can do this. But, we always liked the sound of never ending v1.0-dev. If
we do this, we'll loose it.

**Comment by inquisb** [comment]
@mathiasbynens we will cut the release probably in June 2015 and 1.0 stable will see the light, hopefully.

**Comment by anthraxx** [comment]
sounds great. please consider making faster releases in the future as I'm currently considering to package sqlmap for a distribution. However to be honest I only want to do this if you can provide a bit more frequent releases in the future :smile:
Simply as suggested by @mathiasbynens creating a new git tag every now and then would satisfy my concerns to ship this.

@inquisb we have July now :yum:

**Comment by inquisb** [comment]
@anthraxx and I've not yet cut 1.0 because there are still a number of pending tasks we want to have closed before we do it, like for instance user's manual update. Feel free to put through your pull requests :)

**Comment by anthraxx** [comment]
@inquisb sure, not problem, take your time to finalize 1.0 :smile:
As much as I like your project but unfortunately my TODO list is too long to be able to contribute actively :cry:
Just wanted to make sure that you consider making minor/patch releases more frequently in the future (after final 1.0 release is finished). I would really love to move your project into the repositories... and I think you may also like that :grinning:

**Comment by rhertzog** [comment]
+1 from me. sqlmap is in Kali and we update the package when new upstream releases are tagged. This has not happened for ages and in fact someone in Kali got confused by the 1.0-dev and the Kali package now pretends to be a snapshot that happened after the 1.0 release...

So you might want as well to release 1.1 directly and skip 1.0 :-)

**Comment by inquisb** [comment]
@rhertzog why would we want to do that? sqlmap is distribution independent and does not need Kali - it's the other way round last time I checked :) To be honest, I couldn't care less how Linux distributions tag/release sqlmap. The next release will be 1.0, when we release it.

**Comment by inquisb** [comment]
@anthraxx what repository? I take your point and yes, we will look at releasing sqlmap more frequently going forward.

**Comment by anthraxx** [comment]
@inquisb from my point of view i don't care about how you name the version, 1.0 is fine :yum: 
I'm planning to move sqlmap into the Arch Linux repositories but for that I would like to see a more up-to-date release version before I do so :smile:

**Comment by derlaft** [comment]
+1 to releasing, having troubles with packaging it into distro

**Comment by hickford** [comment]
The latest release at https://github.com/sqlmapproject/sqlmap/releases  dates back to July 2012

**Comment by BrentonEarl** [comment]
A new release would be very helpful.  The tools used to package for my distro require that the tarball be downloaded directly from upstream.  Cloning it and creating a snapshot makes things far more complicated than they need to be.  I recently became the maintainer of sqlmap for Slackware's third party repository SlackBuilds.org.

**Comment by LocutusOfBorg** [comment]
@BrentonEarl this is a non-issue, github allows you to directly download the tarball of the master branch
```
https://github.com/sqlmapproject/sqlmap/tarball/master
```

however a release would be appreciated :+1:

**Comment by LionNatsu** [comment]
[Jul. 2012] -- 3 years and 7 months --> [Feb. 2016]

**Comment by stamparm** [comment]
In a bit, I promise. We'll change this and put tags/minors more often

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/releases

**Comment by LocutusOfBorg** [comment]
*thanks* uploading in debian in a few seconds

**Comment by erwinsalarda** [comment]
Hello sir. Sorry for disturbance. I just want to ask. What is the best
tamper script for cloudflare protected website. Because according to
cloudflare they are unhackable and also sir. Do i need a tamper script when
attacking https? Thankd

**Comment by mathiasbynens** [comment]
https://github.com/Homebrew/homebrew/pull/49654 \o/
