### ISSUE TITLE
Payload injected in referer, not in uri

### ISSUE THREAD

**Issue by jeroen-80** [sqlmapproject/sqlmap#1205]
I found a GET parameter that seems to be vulnerable. I feed it to sqlmap like this:
/sqlmap.py -r header.txt 
header.txt contains:

GET /script.php?data=xyz&(**)=1 HTTP/1.1
Host: myapp.com
..

I expect sqlmap to inject URL encoded payloads in between the "(" and ")". This is not the case. Instead the payload is injected in the referer header(!?). Output generated with -v4:

[17:44:36] [PAYLOAD] 2&('UYfa<'">MvyD
[17:44:36] [TRAFFIC OUT] HTTP request [#6]:
GET /script.php?data=xyz&()=1 HTTP/1.1
Host: myapp.com
..
Referer: https://myapp.com/script.php?data=xyz&('UYfa<'">MvyD)=1

Is this a bug or is there a way to leave the characters in the original request alone? Thanks!

**Comment by stamparm** [comment]
Can you please give all switches/options used together with request file
(you can obfuscate host, don't delete it). I would say that you have a
problem in usage of options.

**Comment by jeroen-80** [comment]
Miroslav Stampar wrote:

> Can you please give all switches/options used

Hi Miroslav,

Thanks for the quick reply.

./sqlmap.py --risk=3 --level=5 --dbms=mysql -r data.txt -v4

> together with request file
> (you can obfuscate host, don't delete it). I would say that you have a
> problem in usage of options.

Please let me know if this is good enough:

GET /<removed>/jeroen?<obfuscated>=<removed>;<obfuscated>=<removed>&(**)=1 HTTP/1.1
Host: <removed>:443
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36
DNT: 1
Referer: http://<removed>/?<obfuscated>=<removed>&<obfuscated>=<removed>
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Cookie: <removed>


Cheers,

Jeroen

**Comment by jeroen-80** [comment]
Miroslav Stampar wrote:

> Can you please give all switches/options used

Hi Miroslav,

Thanks for the quick reply.

./sqlmap.py --risk=3 --level=5 --dbms=mysql -r data.txt -v4

> together with request file
> (you can obfuscate host, don't delete it). I would say that you have a 
> problem in usage of options.

Please let me know if this is good enough:

GET /<removed>/jeroen?<obfuscated>=<removed>;<obfuscated>=<removed>&(**)=1 HTTP/1.1
Host: <removed>:443
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36
DNT: 1
Referer: http://<removed>/?<obfuscated>=<removed>&<obfuscated>=<removed>
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Cookie: <removed>

Perhaps also relevant: below you'll find the questions asked by sqlmap and my responses (all default, like --batch):

custom injection marking character ('*') found in option '-u'. Do you want to process it? [Y/n/q]Y

you provided a HTTP Cookie header value. The target URL provided its own cookies within the HTTP Set-Cookie header which intersect with yours. Do you want to merge them in futher requests? [Y/n]Y

[19:06:44] [WARNING] target URL is not stable. sqlmap will base the page comparison on a sequence matcher. If no dynamic nor injectable parameters are detected, or in case of junk results, refer to user's manual paragraph 'Page comparison' and provide a string or regular expression to match on
how do you want to proceed? [(C)ontinue/(s)tring/(r)egex/(q)uit]C


Cheers,

Jeroen

**Comment by stamparm** [comment]
Why do you use two asterisks and parentheses where you want sqlmap to inject (**)? This is not regular way how to tell sqlmap where to inject.

Please use a valid value there

**Comment by stamparm** [comment]
You are the first person that used formation (**) to tell sqlmap where to inject. Where did you find this???

**Comment by jeroen-80** [comment]
Miroslav Stampar wrote:

> You are the first person that used formation (**) to tell sqlmap where to
> inject. Where did you find this???

Can't remember, I guess on a forum or in a blog post.

Anyway: nothing changes if a single * is used: injection does not take place in the uri but in the referer header. Can you please re-open the issue? Thanks!

Cheers,

Jeroen

**Comment by stamparm** [comment]
So, you are using sqlmap in totally invalid way and at the end you say "anyway" :)

Also, totally unreproducible:

```
> python sqlmap.py -u "http://testphp.vulnweb.com/artists.php?artist=1*" -v 5
         _
 ___ ___| |_____ ___ ___  {1.0-dev-ac74184}
|_ -| . | |     | .'| . |
|___|_  |_|_|_|_|__,|  _|
      |_|           |_|   http://sqlmap.org
...
[23:56:06] [TRAFFIC IN] HTTP response [#6] (200 OK):
X-powered-by: PHP/5.3.10-1~lucid+2uwsgi2
Transfer-encoding: chunked
Content-encoding: gzip
Uri: http://testphp.vulnweb.com:80/artists.php?artist=1...%2C%27%29%22%29..
Server: nginx/1.4.1
Connection: close
Date: Wed, 25 Mar 2015 22:56:11 GMT
Content-type: text/html
[23:56:06] [INFO] heuristic (basic) test shows that URI parameter '#1*' might be injectable (possible DBMS: 'MySQL')
[23:56:06] [PAYLOAD] 1'CpdS<'">Wxfq
[23:56:06] [TRAFFIC OUT] HTTP request [#7]:
GET /artists.php?artist=1%27CpdS%3C%27%22%3EWxfq HTTP/1.1
Accept-language: en-us,en;q=0.5
Accept-encoding: gzip,deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-agent: sqlmap/1.0-dev-ac74184 (http://sqlmap.org)
Accept-charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7
Host: testphp.vulnweb.com
Pragma: no-cache
Cache-control: no-cache,no-store
Connection: close
...
```

**Comment by jeroen-80** [comment]
Miroslav Stampar wrote:

> So, you are using sqlmap in totally invalid way and at the end you say "anyway" :)
> Also, totally unreproducible:
>
> python sqlmap.py -u "http://testphp.vulnweb.com/artists.php?artist=1*" -v 5

You're not testing what I reported. It is reproducible. Please check the GET requests and "Referer" header starting at request #4:

bofh@scanner:/opt/sqlmap$ cat test
GET /artists.php?artist=* HTTP/1.1
Accept-language: en-us,en;q=0.5
Accept-encoding: gzip,deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-agent: sqlmap/1.0-dev-05a496c (http://sqlmap.org)
Accept-charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7
Host: testphp.vulnweb.com
Pragma: no-cache
Cache-control: no-cache,no-store
Connection: close

bofh@scanner:/opt/sqlmap$ ./sqlmap.py --risk=3 --level=5 --dbms=mysql -r test -v4
         _
 ___ ___| |_____ ___ ___  {1.0-dev-05a496c}
|_ -| . | |     | .'| . |
|___|_  |_|_|_|_|__,|  _|
      |_|           |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting at 00:09:42

test
[00:09:42] [INFO] parsing HTTP request from 'test'
[00:09:42] [DEBUG] not a valid WebScarab log data
[00:09:42] [DEBUG] cleaning up configuration parameters
test
[00:09:42] [DEBUG] setting the HTTP timeout
[00:09:42] [DEBUG] creating HTTP requests opener object
[00:09:42] [DEBUG] forcing back-end DBMS to user defined value
[00:09:42] [DEBUG] setting the HTTP Referer header to the target URL
[00:09:42] [DEBUG] setting the HTTP Host header to the target URL
custom injection marking character ('*') found in option '-u'. Do you want to process it? [Y/n/q]Y
[00:09:43] [WARNING] it seems that you've provided empty parameter value(s) for testing. Please, always use only valid parameter values so sqlmap could be able to run properly
[00:09:43] [DEBUG] resolving hostname 'testphp.vulnweb.com'
[00:09:43] [INFO] testing connection to the target URL
[00:09:43] [TRAFFIC OUT] HTTP request [#1]:
GET /artists.php?artist= HTTP/1.1
Accept-language: en-us,en;q=0.5
Accept-encoding: gzip,deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-agent: sqlmap/1.0-dev-05a496c (http://sqlmap.org)
Accept-charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7
Host: testphp.vulnweb.com
Referer: http://testphp.vulnweb.com:80/artists.php?artist=
Pragma: no-cache
Cache-control: no-cache,no-store
Connection: close

[00:09:44] [DEBUG] declared web page charset 'iso-8859-2'
[00:09:44] [WARNING] there is a DBMS error found in the HTTP response body which could interfere with the results of the tests
[00:09:44] [DEBUG] heuristically checking if the target is protected by some kind of WAF/IPS/IDS
[00:09:44] [PAYLOAD] scHu=6294 AND 1=1 UNION ALL SELECT 1,2,3,table_name FROM information_schema.tables WHERE 2>1-- ../../../etc/passwd
[00:09:44] [TRAFFIC OUT] HTTP request [#2]:
GET /artists.php?artist= HTTP/1.1
Accept-language: en-us,en;q=0.5
Accept-encoding: gzip,deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-agent: sqlmap/1.0-dev-05a496c (http://sqlmap.org)
Accept-charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7
Host: testphp.vulnweb.com
Referer: http://testphp.vulnweb.com:80/artists.php?artist=
Pragma: no-cache
Cache-control: no-cache,no-store
Connection: close

[00:09:44] [INFO] testing if the target URL is stable. This can take a couple of seconds
[00:09:45] [TRAFFIC OUT] HTTP request [#3]:
GET /artists.php?artist= HTTP/1.1
Accept-language: en-us,en;q=0.5
Accept-encoding: gzip,deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-agent: sqlmap/1.0-dev-05a496c (http://sqlmap.org)
Accept-charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7
Host: testphp.vulnweb.com
Referer: http://testphp.vulnweb.com:80/artists.php?artist=
Pragma: no-cache
Cache-control: no-cache,no-store
Connection: close

[00:09:45] [INFO] target URL is stable
[00:09:45] [INFO] testing if (custom) HEADER parameter 'Referer #1*' is dynamic
[00:09:45] [PAYLOAD] 4569
[00:09:45] [TRAFFIC OUT] HTTP request [#4]:
GET /artists.php?artist= HTTP/1.1
Accept-language: en-us,en;q=0.5
Accept-encoding: gzip,deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-agent: sqlmap/1.0-dev-05a496c (http://sqlmap.org)
Accept-charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7
Host: testphp.vulnweb.com
Referer: 4569
Pragma: no-cache
Cache-control: no-cache,no-store
Connection: close

[00:09:45] [WARNING] (custom) HEADER parameter 'Referer #1*' does not appear dynamic
[00:09:45] [PAYLOAD] http://testphp.vulnweb.com:80/artists.php?artist=".,(,,('.'
[00:09:45] [TRAFFIC OUT] HTTP request [#5]:
GET /artists.php?artist= HTTP/1.1
Accept-language: en-us,en;q=0.5
Accept-encoding: gzip,deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-agent: sqlmap/1.0-dev-05a496c (http://sqlmap.org)
Accept-charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7
Host: testphp.vulnweb.com
Referer: http://testphp.vulnweb.com:80/artists.php?artist=".,(,,('.'
Pragma: no-cache
Cache-control: no-cache,no-store
Connection: close
<SNAP>

Cheers,

Jeroen

**Comment by stamparm** [comment]
You've reported invalid header.txt (request file) that contains invalid custom injection parameter.

GET /script.php?data=xyz&(**)=1 HTTP/1.1      <-invalid

I thought that you understood this part.

**Comment by jeroen-80** [comment]
>You've reported invalid header.txt (request file) that contains invalid custom injection parameter.
>
>GET /script.php?data=xyz&(**)=1 HTTP/1.1 <-invalid

Correct.

>I thought that you understood this part.

I do.

Please check the message above, based on your example. To me it looks like

sqlmap.py -u "http://testphp.vulnweb.com/artists.php?artist=1*" -v 5

is doing (as expected: altering the artist in the GET) something else then 

sqlmap.py --risk=3 --level=5 --dbms=mysql  -r test -v4 -p artist

which seems to alter the referer and not artist in the uri. If that is correct the test contains similar data but different results when loaded with -r instead of -u.

**Comment by stamparm** [comment]
I'll repeat. Please send one valid request file (without that funky `(**)`) where you think that this is happening so I could reproduce it. I am currently not able to reproduce this.

**Comment by jeroen-80** [comment]
>I'll repeat. Please send one valid request file (without that funky (**)) where you think that this is happening so I could reproduce it. I am currently not able to reproduce this.

https://github.com/sqlmapproject/sqlmap/issues/1205#issuecomment-86249673
