### ISSUE TITLE
406 by black list char '%'

### ISSUE THREAD

**Issue by vietnguyen09** [sqlmapproject/sqlmap#1214]
Hi guy,

I'm working at a moment and found a injection website but this website had a firewall which blacklist % character.

![Image of proof](https://c4.staticflickr.com/8/7606/17027113521_d137c210af_b.jpg)

How can I bypass this firewall please?

Thanks for your times.

**Comment by stamparm** [comment]
This doesn't necessarily have to mean that the WAF is blacklisting it. Also, we can't offer help on this kind of issues.
