### ISSUE TITLE
Any way (or plugin) to avoid logout.php while crawling ?

### ISSUE THREAD

**Issue by BabyBit** [sqlmapproject/sqlmap#1215]
Is there a way/technique/trick/plugin to avoid triggering logout.php while crawling the site ? 
Because reaching logout.php will kill the logged user session on the site.

**Comment by vietnguyen09** [comment]
Can you give more detail? What do you want to do and some commands do you use?

**Comment by BabyBit** [comment]
If you try a command like this to test pages behind a login screen:

```sqlmap -u 'http://example.com/my-profile' --forms --crawl=2 --cookie='LOGGED_USER=oi9fd329'```

that crawling might reach the url logout.php and will logout the user, right ? So any pages tested after that will redirect to a login page.

**Comment by stamparm** [comment]
--crawl-exclude=..  Regexp to exclude pages from crawling (e.g. "logout")
