### ISSUE TITLE
Older Version of sqlmap  able to make injection however newer version flags injection point as a false positive 

### ISSUE THREAD

**Issue by HVolker** [sqlmapproject/sqlmap#1223]
Strange issue I am having with false positive detection. I am using an antiquated version of sqlmap (1.0-dev-nongit-20140820) from an old laptop that successfully got me a valid stack-based SQLi via MSSQL. However; when I upgraded to  the github version of sqlmap (1.0-dev-05a496c) & ran the same exact parameters it detected the injection point as a false positive.

**Comment by stamparm** [comment]
Maybe you have a laggy connection. Are you able to reproduce it with
--flush-session on both versions?
