### ISSUE TITLE
WAF

### ISSUE THREAD

**Issue by Shadowz3n** [sqlmapproject/sqlmap#1224]
Hi,

The tool is detecting the waf: ASP.NET RequestValidationMode (Microsoft)

sqlmap -u 'http://localhost/?id=42' --random-agent --batch --answers 'follow=N' -v3 --risk 1 --level 1 --parse-errors --identify-waf

[14:32:23] [CRITICAL] WAF/IDS/IPS identified 'ASP.NET RequestValidationMode (Microsoft)'. Please consider usage of tamper scripts (option '--tamper')

and I'm using the appropriate tamper (charunicodeencode) for this situation ?
no other combination ?

thank you

**Comment by Shadowz3n** [comment]
--parse-errors:

[14:39:06] [WARNING] parsed DBMS error message: 'System.Data.SqlClient.SqlException: Error converting data type nvarchar to int.'

**Comment by stamparm** [comment]
This last message (...error converting...) most probably mean that variable values are being bind (i.e. casted) to proper variable types (read: no SQLi). As said, most probably (don't have the whole error message to see).

First message was about "ASP.NET RequestValidationMode" means that requests are being checked for not having "suspicious" content. There is no proper tamper script for that.
