### ISSUE TITLE
sqlmap can not detect blind sql injection

### ISSUE THREAD

**Issue by sirsharif** [sqlmapproject/sqlmap#1225]
I have blind sql injection
I use acunetix to detect it and it give me below detail at the point

gpjbhlws' AND 2+1-1-1=0+0+0+1 AND '000DbyK'='000DbyK => TRUE
gpjbhlws' AND 3+1-1-1=0+0+0+1 AND '000DbyK'='000DbyK => FALSE
gpjbhlws' AND 3*2<(0+5+0+0) AND '000DbyK'='000DbyK => FALSE
gpjbhlws' AND 3*2>(0+5+0+0) AND '000DbyK'='000DbyK => FALSE
gpjbhlws' AND 2+1-1-1=1 AND '000DbyK'='000DbyK => TRUE
gpjbhlws' AND 3+1-1-1=1 AND '000DbyK'='000DbyK => FALSE
gpjbhlws' AND 3*2=5 AND '000DbyK'='000DbyK => FALSE
gpjbhlws' AND 3*2=6 AND '000DbyK'='000DbyK => TRUE
gpjbhlws' AND 3*2*0=6 AND '000DbyK'='000DbyK => FALSE
gpjbhlws' AND 3*2*1=6 AND '000DbyK'='000DbyK => TRUE

Back-end database is postgresql
How I can detect this blind sql injection with sqlmap?

**Comment by stamparm** [comment]
It should be detected out of box. maybe something is blocking its request.

Please try to use `--tamper=between --random-agent --text-only`. In case of fail please send me the url to `miroslav@sqlmap.org` (if you are allowed to).

**Comment by stamparm** [comment]
after a short private correspondence now i see that i'll need to have a stronger filter for this kind of requests FFS.

please don't either open new issues or send email requests if they are based on "acunetix said so"

**Comment by stamparm** [comment]
i am admiring people today that know how to send HTTP request manually and inspect the response.

**Comment by sirsharif** [comment]
Hi stamparm
I dont know what you realy mean because my english is not good
But If you mean I'm lying to you, You are wrong
You can download acunetix trial and test my target
You will see acunetix give you Blind Injection
You can check it your self
Also you words is not pretty to your users

**Comment by stamparm** [comment]
acunetix gave you false positive. please don't open any new issues that are based on "acunetix told me so". please learn how to test your targets manually and skip the need for me to test your targets instead of you.

**Comment by stamparm** [comment]
my words are not pretty as i am sad that majority of users don't know anything than to run automated tools. raising hundreds of "false positive" issues based on shitty scanners makes me a sad panda

**Comment by sirsharif** [comment]
Yes you are true But I give you some injection tests with acunetix that can proof there is injection at point
gpjbhlws' AND 2+1-1-1=0+0+0+1 AND '000DbyK'='000DbyK => TRUE
gpjbhlws' AND 3+1-1-1=0+0+0+1 AND '000DbyK'='000DbyK => FALSE
gpjbhlws' AND 32<(0+5+0+0) AND '000DbyK'='000DbyK => FALSE
gpjbhlws' AND 32>(0+5+0+0) AND '000DbyK'='000DbyK => FALSE
gpjbhlws' AND 2+1-1-1=1 AND '000DbyK'='000DbyK => TRUE
gpjbhlws' AND 3+1-1-1=1 AND '000DbyK'='000DbyK => FALSE
gpjbhlws' AND 32=5 AND '000DbyK'='000DbyK => FALSE
gpjbhlws' AND 32=6 AND '000DbyK'='000DbyK => TRUE
gpjbhlws' AND 320=6 AND '000DbyK'='000DbyK => FALSE
gpjbhlws' AND 321=6 AND '000DbyK'='000DbyK => TRUE

What does it mean?

**Comment by stamparm** [comment]
it means that acunetix gave you junk. you have to learn the basics of SQLi to see that it is a junk.

for example,

` gpjbhlws' AND 32=5 AND '000DbyK'='000DbyK => FALSE`
and
` gpjbhlws' AND 32=6 AND '000DbyK'='000DbyK => TRUE`

are utterly shitty requests as both of those should result with `FALSE`.

**Comment by sirsharif** [comment]
Yes you right
Dont be angry
SQLMap is very usefull tool and I think need good support for users that you always here and answer our problems
So I should say you thanks for anything and for your time
And I am realy sorry for that I got your time
Regards
