### ISSUE TITLE
a question not issue

### ISSUE THREAD

**Issue by blink2014** [sqlmapproject/sqlmap#1229]
can i run Sqlmap against list of post or Get parameter texts not only one by one

**Comment by giveen** [comment]
Yes, you can.
You'll want to use the option like this

-m "DIRECTORY_TO_FILE.TXT"

**Comment by blink2014** [comment]
thanks , but i meant  i have a list  post requests in a different list of texts but the -p , dbms and every other thing are the same , the only difference is the Host
eg : sqlmap -r text1 text2 text3 etc .... -p id --dbs

**Comment by stamparm** [comment]
You can't. That's why there are batch shell scripts for. Please write one
for your needs.
