### ISSUE TITLE
Problem about func

### ISSUE THREAD

**Issue by cankaptan1976** [sqlmapproject/sqlmap#1231]
Hi There

When i try to use --check-waf option it gives me err0r anymore i don't why or how used to was working after i updated my sqlmap it has started the err0r dealing with 

"--check-waf is deprecated"

How can i solve this i wanna use that parameter

**Comment by giveen** [comment]
Use --identify-waf

**Comment by inquisb** [comment]
The heuristic WAF check is now done automatically when you run sqlmap. For a thorough assessment of the WAF use `--identify-waf`.
