### ISSUE TITLE
request search.disconnect.me feature like google dork

### ISSUE THREAD

**Issue by a-gjylbegu** [sqlmapproject/sqlmap#1237]
* There is trouble using google and duckduckgo dork feature while using it with tor, but the new search.disconnect.me which is advised now by torproject to be used from its users cuz it doesn't use captcha because of the traffic and would made the sqlmap dork feature to be more effective as search.disconnect.me uses various search engines by just changing the ses parameter. I tried to add this myself but something goes wrong. 
* I used google dork file  **/lib/utils/google.py** and changed the following lines:
 * line 47: conn = self.opener.open("https://search.disconnect.me/searchTerms") 
 * starting from line 65: url = "https://search.disconnect.me/searchTerms/search?&start=nav&option=Web"
 * url += "&query=%s&" % urlencode(dork, convall=True)
 * url += "ses=Google&location_option=US"
 * url += "&nextDDG=/search?q=&hl=en" 
 * url += "&start=%d" % ((gpage - 1) * 10) 
 * url += "&sa=N&showIcons=false&filterIcons=none&js_enabled=1"
* Also changed the regex from **/lib/core/settings.py**
 * line 73: GOOGLE_REGEX = r"(http|ftp|https)://([\w+?\.\w+])+([a-zA-Z0-9\~\!\@\#\$\%\^\&\*\(\)_\-\=\+\\\/\?\.\:\;\'\,]*)?"
* With these changes sqlmap load the search results but its unable to process it, maybe due to wrong regex value, I placed it on a  online site to check if the regular expression filters only url's and it does but in sqlmap they fail, but maybe the mistake is somewhere else, i'm new to this

**Comment by stamparm** [comment]
```
$ python sqlmap.py -g "inurl:?id=1" --gpage=2
         _
 ___ ___| |_____ ___ ___  {1.0-dev-d70215a}
|_ -| . | |     | .'| . |
|___|_  |_|_|_|_|__,|  _|
      |_|           |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting at 10:24:23

[10:24:23] [INFO] first request to Google to get the session cookie
[10:24:23] [INFO] using Google result page #2
[10:24:27] [INFO] heuristics detected web page charset 'ISO-8859-2'
no usable links found. What do you want to do?
[1] (re)try with DuckDuckGo (default)
[2] (re)try with Disconnect Search
[3] quit
> 2
[10:24:33] [INFO] sqlmap got 20 results for your Google dork expression, 7 of them are testable targets
[10:24:33] [INFO] sqlmap got a total of 7 targets
URL 1:
GET www.ventrilo.com/dlprod.php?id=1
do you want to test this URL? [Y/n/q]
> 
```
