### ISSUE TITLE
sqlmap time based sql injection

### ISSUE THREAD

**Issue by crossedz** [sqlmapproject/sqlmap#1238]
There are cases where using the sleep function it will turn out to be really really slow but since sqlmap supports the BENCHMARK feature which can speed the injection up, how can i tell sqlmap to skip any payloads which include the sleep function and skip to the benchmark tests?

There are also cases where if sqlmap gets an invalid character it keeps on increasing and increasing until it has increased by 10 seconds, how can i set a limit as to how much it can increase? Like say if i set --time-sec=2 and i want the maximum time sec to increase by 2, to lead to --time-sec=4 and then return back to --time-sec=2 once it returns another invalid character, how do I do this?

Thanks.

**Comment by stamparm** [comment]
A) ```--test-filter=SLEEP```

B) If you say a hard value on ```--time-sec``` sqlmap shouldn't change its value (e.g. ```--time-sec=4``` will restrain it to the value of ```4```). Also, you are being asked: ```do you want sqlmap to try to optimize value(s) for DBMS delay responses (option '--time-sec')? [Y/n]```. If you answer N here, sqlmap shouldn't change the value. Other than that, there are no more restrain mechanisms (we can't make another option just for this)

**Comment by crossedz** [comment]
@B You're wrong, it still increases when an invalid character is obtained....

**Comment by stamparm** [comment]
@crossedz with last patch it won't be the case anymore
