### ISSUE TITLE
sqlmapapi.py ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr

### ISSUE THREAD

**Issue by LxiaoGirl** [sqlmapproject/sqlmap#1243]
Window 7 x64 python 2.7.8
use sqlmapapi.py 
post:
r = requests.post("http://127.0.0.1:8775/scan/8f2e5cb5894bc2bc/start",data=json.dumps({'url':"http://code.net/index.php?app=home&mod=Public&act=doSendPassword"}), headers={'Content-Type':'application/json'})
ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr

**Comment by stamparm** [comment]
Reference: https://docs.python.org/2/library/subprocess.html#popen-constructor:

`Note that on Windows, you cannot set close_fds to true and also redirect the standard handles by setting stdin, stdout or stderr`
