### ISSUE TITLE
os-shell can't find uploaded stager when writable directory is a subfolder of wwwroot

### ISSUE THREAD

**Issue by jeffmcjunkin** [sqlmapproject/sqlmap#1245]
In an example LAMP application, if /var/www is the webroot and /var/www/upload is a writable directory, sqlmap will, when using brute force [1], treat each suffix as a unique wwwroot folder, instead of specifying the suffix in the GET request.

In the above example, if sqlmap generates /var/www as the wwwroot and uses the "upload" folder as the writable location, the resulting check will still be "GET /tmpXXXXX.php", instead of "GET /upload/tmpXXXXX.php". As a result, sqlmap will receive a 404 error and fail to confirm that the file stager is uploaded successfully (even though it was).

It's a non-trivial change, but I'd probably recommend setting the getManualDirectories function [2] to return not only the directories, but the relative path. Then, around [3] in web.py, include the same relative path (or BRUTE_DOC_ROOT_SUFFIXES, rather) in the check that makes sure the uploaded stager was successfully written.

[1] https://github.com/sqlmapproject/sqlmap/blob/7517db76d1dc915b1cb9b51a4a29c3da4c245541/lib/core/common.py#L688

[2] https://github.com/sqlmapproject/sqlmap/blob/7517db76d1dc915b1cb9b51a4a29c3da4c245541/lib/core/common.py#L638
[3] https://github.com/sqlmapproject/sqlmap/blob/260643241a9373c0bdb8bd0d68df26cf1e1a3449/lib/takeover/web.py#L239

**Comment by stamparm** [comment]
@jeffmcjunkin can you please check if this is now fixed with the latest commit? There was a related bug with #1248 that I believe is related to this problem you are experiencing.

**Comment by jeffmcjunkin** [comment]
I should be able to test again and get back in a day or two. Thanks for the response!

**Comment by stamparm** [comment]
@jeffmcjunkin ping?

**Comment by jeffmcjunkin** [comment]
Pong. 

Sorry, I don't have direct access to the affected webapp, so I'm trying to get a copy today. I can do testing at that point.

**Comment by jeffmcjunkin** [comment]
Sorry, I had to wait for a copy of the VM to be shipped. Sneakernet latency is high.

I should be able to at least start downloading the VM today, and then I'll be able to test this again with the then-current and HEAD versions of sqlmap.

**Comment by stamparm** [comment]
Closing this one down because of inactivity.
