### ISSUE TITLE
Support for Postgres UUID data type

### ISSUE THREAD

**Issue by apolloclark** [sqlmapproject/sqlmap#1249]
I noticed that sqlmap is not able to successfully attack unsanitized Postgres SQL involving UUID column types, ex in Python w/ Flask:

sql = "SELECT * FROM tbl WHERE uuid = '" + request.form['uuid'] + "::uuid';"

Is this a known issue, or an unsupported feature, since the UUID is an optional plugin for Postgres? I've been seeing more projects use UUID as the primary lookup key, particularly SQL+NoSQL systems.

**Comment by stamparm** [comment]
Can you please specify one valid SQLi payload in that case? Doesn't regular
' AND 1=1-- work? Or there should be a prefix ::uuid in the SQLi itself?

**Comment by apolloclark** [comment]
Tthe valid payload would be:
A0EEBC99-9C0B-4EF8-BB6D-6BB9BD380A11'::uuid OR 1=1; --

Documentation here:
http://www.postgresql.org/docs/9.4/static/datatype-uuid.html

To be successful, the payload needs to be formatted as a UUID string, and preferably add a typecast. The default payload gives this error:
ERROR:  invalid input syntax for uuid:

**Comment by stamparm** [comment]
I currently have access only to 8.3 and 8.4. Don't have access to >=9.0 where UUID is supported.

I could make a proper prefix/suffix boundaries (e.g. prefix '::uuid together with suffix --) that would produce something like this, but the user is still required to provide valid uuid parameter value to the sqlmap (as in all other cases). Does that sound ok? If yes, I can make the commit and you could test it.

**Comment by apolloclark** [comment]
Yeah, that would work. Sure, I'll gladly help with testing. The UUID value can be anything, it just needs the correct format:  AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE

**Comment by stamparm** [comment]
@apolloclark just two things to make it sure we are on the right track.

1) User is supposed to provide the correct UUID value, not the sqlmap (e.g. you have to provide the for example `?uuid=AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE` and not the something like `?uuid=<blank>`
2) What do you get for a SQLi payload like: `?uuid=A0EEBC99-9C0B-4EF8-BB6D-6BB9BD380A11' OR 1=1-- -`

Thing is that if 2) works there is no need to include this all into sqlmap. Then sqlmap already supports this kind of injection. Only requirement (as IN ALL CASES) is to provide valid parameters to sqlmap (as stated in 1))

**Comment by stamparm** [comment]
@apolloclark ping? can you please respond to the latest message?

**Comment by apolloclark** [comment]
Sorry, I am on vacation in France. I will verify next weekend. I believe the prefix will work.

**Comment by stamparm** [comment]
Closing this one down. I believe that user (@apolloclark) used empty value (for UUID parameter) when performing test(s).

![screenshot - 06162015 - 10 27 01 am](https://cloud.githubusercontent.com/assets/921555/8178850/4065062e-1412-11e5-9044-f7a58c99e1b0.png)
