### ISSUE TITLE
support pip install

### ISSUE THREAD

**Issue by est** [sqlmapproject/sqlmap#1250]
Hello,

Support `pip install sqlmap` would be nice!

A tutorial is listed here 

https://packaging.python.org/en/latest/distributing.html

See the "Uploading your Project to PyPI" part.

Thank you!

**Comment by killswitch-GUI** [comment]
That would great!

**Comment by jorisroovers** [comment]
+1
This is really preventing us from using it in our project.

**Comment by hickford** [comment]
Hi. Would you consider publishing a package to PyPI?

https://pypi.python.org/pypi/sqlmap

**Comment by brunoamancio** [comment]
+1

**Comment by chrisantonellis** [comment]
oya +1

**Comment by ValHook** [comment]
This would be insanely great indeed!

**Comment by guigomesa** [comment]
+1

**Comment by stamparm** [comment]
![sqlmap_pip](https://cloud.githubusercontent.com/assets/921555/17311750/f60cea48-584d-11e6-8545-2d628c0b857b.png)

![sqlmap_pip_2](https://cloud.githubusercontent.com/assets/921555/17311771/164b6f8c-584e-11e6-9faa-c984d68f062c.png)

**Comment by stamparm** [comment]
Please test and report back first impressions

**Comment by 2xyo** [comment]
Some thoughts:
- [Upload a wheel package to pypi](https://packaging.python.org/distributing/#pure-python-wheels)
- [Use a standard python package structure](https://github.com/pypa/sampleproject)
 - Why a
- [Use the standard python dependencies system](https://packaging.python.org/requirements/#install-requires)

**Comment by stamparm** [comment]
@2xyo I don't want to screw the current structure. There won't be a dumb sqlmap module directory with setup.py in root, at least not in the repository. It is ugly and majority of people are actually not pulling sqlmap through pip/pypi

**Comment by walterdolce** [comment]
> majority of people are actually not pulling sqlmap through pip/pypi
Just adding my thoughts to the conversation..what if people wanted to use sqlmap as a dependency of their project?

**Comment by stamparm** [comment]
Now they can do that with pip. Proper packaging is done and new tagged version is pushed each month to PyPI. Thing is that repository code will not conform to ugly setup.py requirements. People want to download current repository code and start using it OUT OF BOX. Without running setup.py each time.

**Comment by Mikecoon** [comment]
![image](https://cloud.githubusercontent.com/assets/5504685/18027496/aff0f89a-6c6d-11e6-98ab-b66802c52813.png)

Is the latest version in repo now?..

**Comment by stamparm** [comment]
@Mikecoon with the latest patch that "problem" should be fixed. Though, you should wait for couple of days when there will be a new `pip` version available (`1.0.9`)
