### ISSUE TITLE
http parameter pollution

### ISSUE THREAD

**Issue by crossedz** [sqlmapproject/sqlmap#1255]
There's a particular injection where I need to make use of http parameter pollution to bypass the waf as it is an ASP site, how can i make sqlmap do this?

The vector looks something like this:

`uid=union all select 1,2,3,4,table_name/*&uid=*/ from information_table.schema`

**Comment by stamparm** [comment]
--hpp

**Comment by stamparm** [comment]
`--hpp               Use HTTP parameter pollution method`
