### ISSUE TITLE
Two Accept-Encoding in requests

### ISSUE THREAD

**Issue by italy2010** [sqlmapproject/sqlmap#1260]
Hello why sqlmap send two accept-encoding in one request?

sqlmap.py -r "test.txt" --user-agent="Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0"  --referer="http://10.0.0.1/pw.php" --keep-alive --cookie="PHPSESSID=2ad2c05cafac69b101958f3938768eb1"   -p user-agent --dbms mysql

request >

POST /pw.php HTTP/1.1
Host: 10.0.0.1
Accept-Encoding: identity
Content-length: 138
Accept-language: en-GB,en;q=0.5
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-agent: Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0') AND (SELECT 4597 FROM(SELECT COUNT(*),CONCAT(0x7171627071,(SELECT (ELT(4597=4597,1))),0x71626a6a71,FLOOR(RAND(0)*2))x FROM INFORMATION_SCHEMA.CHARACTER_SETS GROUP BY x)a) AND ('NxIQ'='NxIQ
Accept-charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7
Referer: http://10.0.0.1//pw.php
Pragma: no-cache
Cache-control: no-cache,no-store
Cookie: PHPSESSID=2ad2c05cafac69b101958f3938768eb1
Content-type: application/x-www-form-urlencoded
Accept-encoding: gzip,deflate

token=FD4CB26D795C0396BBF47C6D171F208115721FF416D1C5BB404DD17CEF4A6C16&username=test&email=test%40gmail.com&captcha_code=&submit=Submit

**Comment by stormwin** [comment]
if you have Accept-encoding in your file test.txt, try to change to Accept-Encoding or remove that line

Sqlmap try to find Accept-Encoding and in your case Accept-Encoding !== Accept-encoding

**Comment by stamparm** [comment]
As @stormwin said, you've put some extra headers in your request file.

Nevertheless, with last patch(es) sqlmap should not duplicate such headers
