### ISSUE TITLE
Enumerating columns/tables with already guessed columns/tables

### ISSUE THREAD

**Issue by the-st0rm** [sqlmapproject/sqlmap#1264]
I have a boolean based blind Sql injection vulnerability. I have managed to use the --common-columns options to guess number of columns. The total number of columns was 31. I successfully guessed 12 columns. Then I wanted to retrieve the rest of the columns through enumeration. When I started the enumeration process it didn't take into consideration it has already found 12 columns through guessing. However, it did start from the beginning to enumerate the entire 31 columns. I think an enhancement should be added to the code so that when it enumerates the files. It should exclude the ones already guessed. 

I have a fix in my mind and I will implement in the following days. I can understand that the sqlmap doesn't know the name of the table unless it enumerate the table but I think it can be fixed from the query level. 
Let's say the query that show the table names like this
select table_name from tables limit 1,1;  //and the sqlmap keep increasing the limits ... 
The query should be edited to be like this 
select table_name from tables where table_name not in [LIST_OF_GUEST_TABELS] limit 1,1;
I will try to implement this enhancement in the following days

**Comment by stamparm** [comment]
You are not clear now. You guessed some columns and then wanted sqlmap to
do the rest. How can sqlmap exclude the already guessed columns from
enumeration while it tries to retrieve them all. It would require a really
long WHERE, potentially breaking the payload.

Bye

**Comment by stamparm** [comment]
Closing it down. Its not an option to lengthen the payload for potentially thousands of chars
