### ISSUE TITLE
Could somebody hack a site for me

### ISSUE THREAD

**Issue by MaxiBillion** [sqlmapproject/sqlmap#1266]
Could you somebody hack this site and create an account for me http://www.remitone.com as I want the banking software but don't want to pay their high prices as well as the fact that their system takes ages to deploy. So if you could hack it for me it would be much appreciated and I'll pay you as much as you want with the method of your choice for helping

**Comment by giveen** [comment]
LOL, this is funny.

**Comment by darryllane** [comment]
hahah had to read that twice

**Comment by coldalfred** [comment]
pastebin?

**Comment by machak10** [comment]
Jesus Christ....are you serious?

2015-06-12 18:32 GMT+02:00 coldalfred <notifications@github.com>:

**Comment by coldalfred** [comment]
hahaha this guy has balls of steel :8ball:
