### ISSUE TITLE
[question] limit character comparison in time-bases mode

### ISSUE THREAD

**Issue by milboy** [sqlmapproject/sqlmap#1267]
Hi

because of low speed of time-based method I need a way to limit character comparison in SELECT injection.
like I'm reading two columns, 1. id 2. md5 password. ID column is just number and MD5 password are just 0-9 a-f characters, 
Its better to limit character to these , in default sqlmap use bit to bit comparison? i'm not a professional.
I read some tutorials to limit possible character to Speed up injection but I want use sqlmap first.

another question.
in default time-based injection to mysql, for example to determind a character like "Z" how much http request must use? if column value be just A-Z characters, its better to use a loop to use 26 char max to detect values?

thanks for any help or info

**Comment by stamparm** [comment]
1) sqlmap uses cca. 6 requests per char (binary search), and not sequential as you insinuate.
2) please use -v 3 to learn more about how sqlmao works
3) such option wouldn't be much of a use in binary search. It would potentially drop down number of requests from 6 to 4-5, while nobody would use it. Also, it would be clumsy to use it. 
4) Your premise of sqlmap doing the sequential search is all wrong, so closing this one down
