### ISSUE TITLE
[question] DNS exfiltration in MySql/Apache without LOAD_FILE()

### ISSUE THREAD

**Issue by milboy** [sqlmapproject/sqlmap#1269]
Hi
my target is apache/mysql I can't use DNS exfiltration.because I have not access FILE privilege.

Its possible to request DNS request in mysql without LOAD_FILE() ?

"[ERROR] data retrieval through DNS channel failed. Turning off > DNS exfiltration support"

normal blind time-based injection working.

**Comment by stamparm** [comment]
Currently there is no known way how to do it. If you find it feel free to
share it.

**Comment by stamparm** [comment]
`my target is apache/mysql I can't use DNS exfiltration.because I have not access FILE privilege.`
-> LOAD_FILE method works only on Windows/MySQL platform :)

**Comment by milboy** [comment]
Yes, I means --dns-domain options  for Linux/MySql platform, I'm searching for any other method to exfiltration datas via mysql/linux query without file privilege ,but no result :)
