### ISSUE TITLE
statement --prefix problem

### ISSUE THREAD

**Issue by cheng1999** [sqlmapproject/sqlmap#1270]
when --prefix set to '\' , my burpsuite catched '\\' not '\'
why it automatically add more backslash

**Comment by stamparm** [comment]
I would suggest you read the: http://stackoverflow.com/questions/8254120/how-to-escape-a-single-quote-in-single-quote-string-in-bash

You are not experiencing problem with sqlmap, but with the system

**Comment by stamparm** [comment]
I would suggest you to use `--prefix="'"` instead

**Comment by stamparm** [comment]
![1](https://cloud.githubusercontent.com/assets/921555/8182254/fc9ba008-142d-11e5-8f35-66715acc3db9.png)
![2](https://cloud.githubusercontent.com/assets/921555/8182255/fc9bbbe2-142d-11e5-97f1-37ff7d616858.png)

**Comment by cheng1999** [comment]
that was a special situation I must use a backslash

WHERE id = 'trim(lcase($_POST['id']))'

lcase() convert ' in $POST['id']  to double ' like this : '' , it is not quote
so I can bypass it by a backslash, but sqlmap automatic add more backslash

**Comment by stamparm** [comment]
What do you need at the end. I am really not sure. Can you please write detailed here a prefix that you want sqlmap to use because in previous messages its really not clear what you are up to.

![1](https://cloud.githubusercontent.com/assets/921555/8183928/a4051cea-143b-11e5-9446-2651cbe9b416.png)

**Comment by stamparm** [comment]
You want sqlmap to send a single `\`, right?

**Comment by stamparm** [comment]
@cheng1999 I've found what's causing the problem. On it.

**Comment by stamparm** [comment]
@cheng1999 you've stumbled upon one ancient "bug"/"feature" that's inside sqlmap for a very long time (https://github.com/sqlmapproject/sqlmap/blob/master/lib/core/agent.py#L182-L188). We are automatically doing this replacement (`\`->`\\`) because it was easier for us to handle (DBMS required) automatic escaping of character `\` from here than to do it everywhere.

Now we have a problem :)

**Comment by stamparm** [comment]
Running with the latest commit:

`python sqlmap.py -u www.test.com/?id=1 --random-agent --prefix='\' --proxy="http://127.0.0.1:8080"`

will result with the:

![screenshot - 06162015 - 10 21 07 pm](https://cloud.githubusercontent.com/assets/921555/8193578/16ba45c8-1476-11e5-83ae-29bccaa42fad.png)
