### ISSUE TITLE
Htaccess bypassing

### ISSUE THREAD

**Issue by italy2010** [sqlmapproject/sqlmap#1272]
Hello
is there any tamper in sqlmap to bypass this htaccess?

thanks

http://pastebin.com/raw.php?i=qm4zyxgz

**Comment by stamparm** [comment]
No.

`SecFilter "select.+from"` denies all queries. You have to use `SELECT` and `FROM` in all (dumping) queries.

p.s. usage of intra-keyword comments (e.g. `SE/**/LECT`) is a fallacy that started year ago by someone without any knowledge on SQLi. It breaks queries altogether.
