### ISSUE TITLE
utf8 data retervial

### ISSUE THREAD

**Issue by anasri** [sqlmapproject/sqlmap#1273]
Hello , I used this switch  --charset=utf8 to get Persian data from sql . 

also I run query with --sql-shell  ( set charset set uft8 ) .  still I have problem and get this symbolic ???? data .

Database: educ
Table: GradeList
C:\Python27\sqlmapproject-sqlmap-9e5ef09>sqlmap.py -u "http:/xxxxgate
xxx/xxxx.php?rand=844775027" --data "title=%D8%B4%D9%86%D8%A7%D8%B3%D9%8
7+%DA%A9%D8%A7%D8%B1%D8%A8%D8%B1+%D9%BE%DB%8C%D8%AF%D8%A7+%D9%86%D8%B4%D8%AF%21&
UserID=" UserID -D educ -T grades --columns --charset=utf8 

could you check I use the switch in correct place ?

**Comment by stamparm** [comment]
`set charset set uft8` won't work from `--sql-shell`. As I know, you can't change connection's charset/collation on the fly.

`Hello , I used this switch --charset=utf8 to get Persian data from sql` - I can see that you use Windows. Windows has problems displaying Unicode characters. Please take a look into the dump files or try to use Linux

I believe that `--charset=utf8` won't help you here.

**Comment by anasri** [comment]
ok thanks you should close this ticket
