### ISSUE TITLE
where to save configuration file?

### ISSUE THREAD

**Issue by LocutusOfBorg** [sqlmapproject/sqlmap#1275]
Hi, I see in the root of sqlmap git tree an sqlmap.conf file.

Since in Debian we install sqlmap into /usr/share/sqlmap, I would like to install the configuration file in /etc/sqlmap/sqlmap.conf

Does the code reconize automatically such path?

thanks

**Comment by stamparm** [comment]
sqlmap is being set up through command line options and switches. It is not automatically loading `sqlmap.conf`. You have to use the `-c /etc/sqlmap/sqlmap.conf` to load options from such config file.

**Comment by LocutusOfBorg** [comment]
seems legit, thanks!
I uploaded a Debian sqlmap with the configuration stored in etc.

maybe some documentation in the help might be good to let users know about the file, but meh... they can find it, because it is the best directory for a conf file :)
