### ISSUE TITLE
UPDATE MSSQL

### ISSUE THREAD

**Issue by crossedz** [sqlmapproject/sqlmap#1276]
If there is a stacked query injection through MSSQL and using --sql-shell doesn't work, what feature does sqlmap have to allow the update of mssql columns?

On the target I've tried:
`http://www.example.com/test.asp?id=2;UPDATE Databasename.users SET email = 'test@test.com' WHERE UserName = 'test'--`

I've also tried in sqlmap in --sql-shell running that update command, no results, even when `'` is replaced with *`*

How can I do this?

**Comment by stamparm** [comment]
sqlmap has to be able to find `stacked` SQLi. If not, then it won't be able to run updates.

You've said that you've tried to run `http://www.example.com/test.asp?id=2;UPDATE Databasename.users SET email = 'test@test.com' WHERE UserName = 'test'--`, but you haven't said whether it worked?

Maybe stacking is not supported. Maybe some characters are filtered out.

If you are not able to run that `UPDATE` manually then you most probably won't be able to run it in sqlmap too

**Comment by crossedz** [comment]
`;waitfor delay '0:0:10'--` -> works

The database name is:
`testdatabase`

The table name is:
`users`

The column name i want to change the value of for user with username `bob` is:
`email`

What is the correct syntax to change the email of user `bob` to test@test.com?
No characters are filtered because I've already been able to extract any data i want with sqlmap.

The problem may be that the mssql user has no write permission? That makes no sense, it should be able to edit column data seeing it's also vulnerable to stacked query injection.

**Comment by crossedz** [comment]
Also, sqlmap says table name is:
`Database: testdatabase.users`
`Table: users`

Then it says:
Database: testdatabase
+---------------+---------+
| Table         | Entries |
+---------------+---------+
| dbo.users | 22 |
+---------------+---------+

What should the syntax be then?
`http://www.example.com/test.asp?id=2;UPDATE testdatabase.users SET email = 'test@test.com' WHERE UserName = 'bob'--`

or:
`http://www.example.com/test.asp?id=2;UPDATE testdatabase.dbo.users SET email = 'test@test.com' WHERE UserName = 'bob'--`

?

**Comment by crossedz** [comment]
Neither of what i listed above worked.

**Comment by stamparm** [comment]
@crossedz both of those `UPDATE`s should work in normal scenario. You have some filtering there or the current user can't do `UPDATE`s
