### ISSUE TITLE
unhandled exception 2

### ISSUE THREAD

**Issue by gitclone** [sqlmapproject/sqlmap#1279]
[CRITICAL] unhandled exception occurred in sqlmap/1.0-dev-nongit-2015
0626. It is recommended to retry your run with the latest development version fr
om official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'. If t
he exception persists, please open a new issue at 'https://github.com/sqlmapproj
ect/sqlmap/issues/new' with the following text and any other information require
d to reproduce the bug. The developers will try to reproduce the bug, fix it acc
ordingly and get back to you
sqlmap version: 1.0-dev-nongit-20150626
Python version: 2.7.10
Operating system: nt
Command line: sqlmap.py --url=**************************************************
************************************************************************* --rand
om-agent --ignore-proxy --level=5 --risk=3 --text-only --dbms=mysql --drop-set-c
ookie --no-cast --is-dba -* 2 -f --banner --parse-errors --identify-waf
Technique: STACKED
Back-end DBMS: MySQL (fingerprinted)
Traceback (most recent call last):
  File "sqlmap.py", line 102, in main
    start()
  File "lib/controller/controller.py", line 514, in start
    injection = checkSqlInjection(place, parameter, value)
  File "lib/controller/checks.py", line 390, in checkSqlInjection
    boundPayload = agent.suffixQuery(boundPayload, comment, suffix, where)
  File "lib/core/agent.py", line 275, in suffixQuery
    expression += comment
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

**Comment by stamparm** [comment]
@gitclone are you using the latest revision (updated couple of hours ago)? I can't see this from report as you are running sqlmap on Windows OS.

There has been a change b212321c07e6fe02da720cf1b8034990d76f495c that should fix this behavior. If this (latest revision) doesn't solve the problem I'll make other patch.

**Comment by gitclone** [comment]
I use latest b212321 sqlmap/1.0-dev-nongit-20150626

**Comment by gitclone** [comment]
I try on clear vm win with latest build. This is the result:
[CRITICAL] unhandled exception occurred in sqlmap/1.0-dev-nongit-20150627. It is recommended to retry your run with the latest development version from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'. If the exception persists, please open a new issue at 'https://github.com/sqlmapproject/sqlmap/issues/new' with the following text and any other information required to reproduce the bug. The developers will try to reproduce the bug, fix it accordingly and get back to you sqlmap version: 1.0-dev-nongit-20150627
Python version: 2.7.10
Operating system: nt
Command line: sqlmap.py --url=**************************************************
********************************* --tamper space2mysqldash.py --random-agent --i
gnore-proxy --level=5 --risk=3 --text-only --dbms=mysql --drop-set-cookie --no-c
ast --is-dba -* 2 -f --banner --parse-errors
Technique: STACKED
Back-end DBMS: MySQL (fingerprinted)
Traceback (most recent call last):
  File "sqlmap.py", line 102, in main
    start()
  File "lib/controller/controller.py", line 514, in start
    injection = checkSqlInjection(place, parameter, value)
  File "lib/controller/checks.py", line 390, in checkSqlInjection
    boundPayload = agent.suffixQuery(boundPayload, comment, suffix, where)
  File "lib/core/agent.py", line 275, in suffixQuery
    expression += comment
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
