### ISSUE TITLE
 Metasploit Framework path invalid

### ISSUE THREAD

**Issue by MattJacob1981** [sqlmapproject/sqlmap#1280]
I know this issue has come up before, but I'm not sure how to fix it... I'm running:
Windows 7 64bit
Metasploit Community 4.11.3
SQLMap 1.0-dev-nongit-20150626

with the following command:
sqlmap.py -u ****** --check-tor --tor --tor-port=9150 --tor-type=SOCKS5 --os-pwn --msf-path C:\metasploit\apps\pro\msf3

And I keep getting the error:
 [WARNING] the provided Metasploit Framework path 'C:/metasploit/apps/pro/msf3' is not valid. The cause could be that the path does not exists or that one or more of the needed Metasploit executables within msfcli, msfconsole, msfencode and msfpayload do not exist
[CRITICAL] unable to locate Metasploit Framework installation. You can get it at 'http://www.metasploit.com/download/'

Both  msfcli, msfconsole are in the C:\metasploit\apps\pro\msf3 directory but msfencode and msfpayload do not exist... What am I doing wrong? I'm new SQLMap

**Comment by gitclone** [comment]
It's ONLY Kali future.

**Comment by stamparm** [comment]
@MattJacob1981 you've answered it: "but msfencode and msfpayload do not exist...". This moment sqlmap requires those two to be there.

**Comment by stamparm** [comment]
Have to update msfencode and msfpayload to msfvenom

**Comment by stamparm** [comment]
Done with the latest patch
