### ISSUE TITLE
sqlmap can not detect injection on SOAP

### ISSUE THREAD

**Issue by jackrechard** [sqlmapproject/sqlmap#1281]
I have vulnerable soap service that is vulnerable with this  :
CheckName.CheckNameSoap.CheckaRecord.name was set to '+convert(int,CHAR(52)+CHAR(67)+CHAR(117)+CHAR(55)+CHAR(87)+CHAR(108)+CHAR(108)+CHAR(80)+CHAR(102)+CHAR(70)+CHAR(49))+'
And the HTML response is :
soap:ServerServer was unable to process request. ---> Conversion failed when converting the varchar value '4Cu7WllPfF1' to data type int.

It mean target is vulnerable

I use sqlmap like this : ./sqlmap.py -r soap.txt -p name -v3
But at the end sqlmap said me target is not vulnerable

**Comment by stamparm** [comment]
And what's the content of request file (soap.txt)? I can't do anything here if I don't have any usable data.

**Comment by jackrechard** [comment]
The soap.txt is like below :
POST /SOAP/CheckName.asmx HTTP/1.1
Content-Type: text/xml
SOAPAction: "http://tempuri.org/CheckaRecord"
Content-Length: 882
Host: localhost
Connection: Keep-alive
Accept-Encoding: gzip,deflate
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.63 Safari/537.36
Accept: */*

<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"  xmlns:xsd="http://www.w3.org/1999/XMLSchema"  xmlns:xsi="http://www.w3.org/1999/XMLSchema-instance"  xmlns:m0="http://tempuri.org/"  xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:urn="http://tempuri.org/">
     <SOAP-ENV:Header/>
     <SOAP-ENV:Body>
        <CheckaRecord>
           <Name>aaxgpjan</Name>
           <family>1</family>
           <ID>1</ID>
           <BirthYear>01/01/1967</BirthYear>
           <Issue>1</Issue>
           <UserId>aaxgpjan</UserId>
        </CheckaRecord>
     </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

**Comment by jackrechard** [comment]
<CheckaRecord>
           <Name>aaxgpjan</Name>
           <family>1</family>
           <ID>1</ID>
           <BirthYear>01/01/1967</BirthYear>
           <Issue>1</Issue>
           <UserId>aaxgpjan</UserId>
        </CheckaRecord>

**Comment by jackrechard** [comment]
The soap.txt is like below :
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"  xmlns:xsd="http://www.w3.org/1999/XMLSchema"  xmlns:xsi="http://www.w3.org/1999/XMLSchema-instance"  xmlns:m0="http://tempuri.org/"  xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:urn="http://tempuri.org/">
     <SOAP-ENV:Header/>
     <SOAP-ENV:Body>
        <CheckaRecord>
           <Name>aaxgpjan</Name>
           <family>1</family>
           <ID>1</ID>
           <BirthYear>01/01/1967</BirthYear>
           <Issue>1</Issue>
           <UserId>aaxgpjan</UserId>
        </CheckaRecord>
     </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

**Comment by jackrechard** [comment]
<CheckaRecord>
           <Name>aaxgpjan</Name>
           <family>1</family>
           <ID>1</ID>
           <BirthYear>01/01/1967</BirthYear>
           <Issue>1</Issue>
           <UserId>aaxgpjan</UserId>
        </CheckaRecord>

**Comment by jackrechard** [comment]
Check soap.txt from here : http://pastebin.com/9S221430

**Comment by stamparm** [comment]
You've put that dummy whitespace line in between headers and POST body. I've pushed a minor change to handle those kind of cases now.

Can you please update and pastebin your console output (you get with sqlmap's run)?

**Comment by jackrechard** [comment]
When I delete whitespace line between headers and POST body, sqlmap give me this response :
[16:35:05] [CRITICAL] HTTP POST method depends on HTTP data value to be posted

But with witespace line I have no error

**Comment by stamparm** [comment]
Please update to latest revision and retry again with your old request file

**Comment by jackrechard** [comment]
http://pastebin.com/NPwwqUAf
sqlmap version is : 1.0-dev-nongit-20150627
If you can try yourself I can send you real post request

**Comment by stamparm** [comment]
@jackrechard please send request file to `miroslav@sqlmap.org`

**Comment by stamparm** [comment]
WAF/firewall is at the user's site (removing whitespaces, blacklisting keywords `AND`, `OR`, etc.). Closing this one down.

**Comment by stamparm** [comment]
![screenshot - 06292015 - 01 35 52 pm](https://cloud.githubusercontent.com/assets/921555/8407141/080615d2-1e64-11e5-8cc7-4b7d4f764488.png)
![screenshot - 06292015 - 01 37 40 pm](https://cloud.githubusercontent.com/assets/921555/8407142/0827a832-1e64-11e5-9392-7debb07c5205.png)
