### ISSUE TITLE
sqlmapapi task limitation feature

### ISSUE THREAD

**Issue by pnigos** [sqlmapproject/sqlmap#1282]
Could u add a switch like --max-task=n for sqlmapapi.py to restrict the concurrent scan task number.Because the bottle the sqlmapapi server used is not very stable when large numbers of task running concurrently,error always raised.Thanks.

**Comment by stamparm** [comment]
Total number of tasks (even non running) or just the active ones? Literally maximum number of tasks would include also the inactive (just created) tasks.

**Comment by pnigos** [comment]
Total number of tasks,including pending and scanning status :) With this switch the upper layer can wait until the sqlmap scan task queue is available.

**Comment by hysia** [comment]
you can do it with a wrapper to control maximum number of tasks

**Comment by pnigos** [comment]
@hysia 我用token busket写了个wrapper，潮哥么么哒。

**Comment by stamparm** [comment]
There is an option `--adapter` available for some time. You can choose a better WSGI server (e.g. any of `aiohttp, bjoern, cgi, cherrypy, diesel, eventlet, fapws3, flup, gae, gevent, geventSocketIO, gunicorn, meinheld, paste, rocket, tornado, twisted, waitress, wsgiref`).

Maybe you could try to use (C based) `python sqlmapapi.py -s --adapter bjoern` (Note: for installing `sudo apt-get install libev-dev && sudo pip install bjoern`)
