### ISSUE TITLE
skip url stable test and connection

### ISSUE THREAD

**Issue by crossedz** [sqlmapproject/sqlmap#1286]
Where can I skip the tests that sqlmap does on whether url is stable or not and where it tests the connection?

There are some sql injections that are extremely noisy, I'd like to see a feature where this is possible.

**Comment by stamparm** [comment]
`There are some sql injections that are extremely noisy, I'd like to see a feature where this is possible.`

->

testing SQLi is noisy. Testing the connection or url stability is the LEAST noisy thing that you can do. Those are the plain non-SQLi requests

**Comment by crossedz** [comment]
You are an absolute fucking moron.
There are cases where when testing the parameter with its default values e.g with a feature that sends abuse reports to the web admin, the report is actually sent, where as if you send:
`parameter=12 and sleep(2)`, no report is sent, thus you are able to extract data WITHOU sending:
`parameter=12` 50 fucking times and sending 50 abuse reports to the administrator which WILL be noisy and fuck and get your issue patched.
You are clearly retarded and have no real world experience, hence why you talk so much shit.
