### ISSUE TITLE
Add option to save the payload in a file

### ISSUE THREAD

**Issue by rodrigozanatta** [sqlmapproject/sqlmap#1289]
The sqlmap is a very good tools to find vulnerable variable. I want use it as a tool to help-me in another project. 

I can save the config that I want with a simple `--save` so I can read it in my program and do a lot of thing. 

But, after I run the program and it find a valid method to inject SQL, there is no east way to save the working method. The best I can do is read the `log` file. But this can cause **a lot of error** because, well, a lot of things is saved in this file. 

Why not create a method like `--save-payload` to save all the methods the sqlmap found to inject sql? Can use the format as it show to user. 

My program will test this working method more advanced and see more things. 

Can you create it?

**Comment by stamparm** [comment]
But sqlmap uses also lots of stuff that is not shown by payload. By simple payload you won't be able to retrieve data, know how to dump tables,..

**Comment by rodrigozanatta** [comment]
Well... I want to do something automatically. 

The sqlmap use some logics. Somethings are good, others not. I just want to do something more complex to dump table. But I don't want my program find a vulnerable place. The sqlmap is the state-of-art to FIND a vulnerable place, but not to dump it.  And I don't want to change it. 

If I know the payload, and know the place is vulnerable, I can try another things. 

For example, in a union place, sqlmap test only ONE place. I found a place that use a union with 15 places. 10 of this 15 places is vulnerable and can return some text. So I can create a logic to use every place and dump fast. But, in another way, this can make is slow in the server. So I am studying the possibilities. 

I just want to interpret the payload the sqlmap send and work with it. This is really complex because all the possibilities. For now I will restrict it to a subset that I want.

**Comment by stamparm** [comment]
Log files are enough. Can't make a new switch if this can be already done with simple parsing of log files

**Comment by rodrigozanatta** [comment]
ok, this true already... Maybe I am making the things more difficult..
