### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by anasri** [sqlmapproject/sqlmap#1291]
Hi .

I know this site http://www.xxxxx.ir/search/result/1/'/def/Fa  has injectable with apostrophe .
but sqlmap says its false positive . 
 I think its not false positive

**Comment by stamparm** [comment]
But apostrophe is not the proof of SQLi. In many cases there is a casting going on producing formatting errors which have nothing to do with SQLi

**Comment by stamparm** [comment]
If you are able to find a single working SQLi let me know. Apostrophe is a sign of potential SQLi, but not the proof of SQLi.

**Comment by anasri** [comment]
Date Database Is MSSQl and you can see the error . 
http://img.majidonline.com/pic/316749/kac.JPG
