### ISSUE TITLE
Accept -H parameter like CURL

### ISSUE THREAD

**Issue by steelbrain** [sqlmapproject/sqlmap#1293]
Almost all of the major browsers copying as curl of network requests in dev tools, sqlmap already supports `--data` parameter just like curl, it would be great to have it accept `-H` as well.
It'll reduce the effort we have to do when converting curl requests into sqlmap commands

**Comment by stamparm** [comment]
Done. Now you can use both `-H` and `--user-agent`

**Comment by steelbrain** [comment]
:heart:

**Comment by steelbrain** [comment]
I am not sure you understood correctly :sweat_smile:
-H isn't for UserAgent, it's for headers
`curl -H "User-Agent: Something" -H "Conten-Type: text/plain"`

**Comment by stamparm** [comment]
It should be OK now

**Comment by steelbrain** [comment]
Thanks :clap:
