### ISSUE TITLE
POST sql injection with 'or 1=1#

### ISSUE THREAD

**Issue by Frank-en-stein** [sqlmapproject/sqlmap#1295]
Hi,
I've been really confused lately trying 'or 1=1# on a login username field. It immediately gives me access if i type it in manually but sqlmap doesn't seem to recognize it no matter what (not even at --level=5 --risk=3).  I also tried creating manual payloads at boolean based blind xml file but nothing.
Did i miss something crucial?
Thanks in advance.

**Comment by stamparm** [comment]
What commands (request file?) have you used?

**Comment by stamparm** [comment]
Traffic file (`-t traffic.txt`) would be most helpful here

**Comment by Frank-en-stein** [comment]
command: sqlmap -u "http://mist.ac.bd/app/webroot/alumni/login.php" --data "rt_admin_username=admin&rt_admin_password=asd" -p "rt_admin_username" -o --level=5 --risk=3 --dbs  -v 3 -t traffic.txt

**Comment by stamparm** [comment]
and the content of traffic file? can you paste it somewhere?

**Comment by Frank-en-stein** [comment]
It's way too big to comment and looks like i can't upload a txt file. so, please download:
https://drive.google.com/file/d/0ByshdaInIDmYbUFGTHF1enJ0dm8/view?usp=sharing

**Comment by stamparm** [comment]
`python sqlmap.py -u "http://[REDACTED]/app/webroot/alumni/check_login.php" --data "rt_admin_username=admin&rt_admin_password=asd" -p "rt_admin_username" -o --level=5 --risk=3 --dbs --string location --random-agent`

**Comment by stamparm** [comment]
You should really learn to use parameter `--string` in this kind of situations and `--proxy`. With proxy you would see that the data is being posted to `check_login.php`

**Comment by Frank-en-stein** [comment]
Thanks, I'm working on it.

**Comment by Frank-en-stein** [comment]
Hi, if you are still able to hear from it, please know that i learned about all that you suggested and analyzed the traffic file too. What I found out is whether i use the string option or not, the response always end up being the very same page where i started. No changes in the response page whatsoever. so the --string option doesn't really come into play.

**Comment by stamparm** [comment]
Lol. They removed the page after your attacks :)

**Comment by stamparm** [comment]
In future I'll immediatelly remove all LIVE target requests like this one. This kind of user issues/requests have NOTHING to do with sqlmap.

**Comment by Frank-en-stein** [comment]
Actually I happen to be one of "them". That was an already hacked obsolete page, not in use. We are doing it clean-slate so, i thought a little experimenting shouldn't hurt. :)

**Comment by Frank-en-stein** [comment]
Thank you for your support though. Your tool screwed our site every way possible except the 1=1# case.
