### ISSUE TITLE
Why now allow using dorks from duckduckgo?

### ISSUE THREAD

**Issue by brunoamancio** [sqlmapproject/sqlmap#1296]
DuckDuckGo uses dorks, just like google. Scanning from google makes them suspicious and temporarily ban by IP. If using proxy is not wanted, having DuckDuckGo as option 2 would be nice.

What do you guys think?

**Comment by stamparm** [comment]
It seems that they have a pretty harsh anti-scrapping/robot policy. Trying:

`curl --data "q=foobar" "https://duckduckgo.com/html/"`

or

`curl "https://duckduckgo.com/d.js?q=inurl%3A%22%3Fid%3D1%22"`

cut me out after <10 requests.

**Comment by brunoamancio** [comment]
Indeed. I hadn't noticed that.

**Comment by stamparm** [comment]
Also, automatically being used in case of failing with Google:

https://github.com/sqlmapproject/sqlmap/blob/master/lib/utils/google.py#L111-L159
