### ISSUE TITLE
file-read brokes binary files

### ISSUE THREAD

**Issue by sqlmapper** [sqlmapproject/sqlmap#1299]
Problem:
file-read brokes binary files, in downloaded file all bytes with value >=128 (0x80) are replaced by \?XX

Versions:
sqlmap 1.0-dev-fdc8e66
back-end DBMS: MySQL 5.0.12
sqli Type: boolean-based blind

How to reproduce:
Remote binary file chr130 contains 1 byte with ascii code 130 (0x82):
xxd chr130
0000000: 82                                       .

sqlmap -u "test-url" --file-read=/chr130

Downloaded local file _chr130 contains 4 bytes:
xxd _chr130
0000000: 5c3f 3832                                \?82
but should contain 1 byte as original.

**Comment by stamparm** [comment]
Which SQLi technique? (boolean, union...)

**Comment by sqlmapper** [comment]
Type: boolean-based blind

**Comment by sqlmapper** [comment]
fix https://github.com/sqlmapproject/sqlmap/pull/1300

**Comment by stamparm** [comment]
Its not so simple. Give me some time to take a look into this.

**Comment by stamparm** [comment]
@sqlmapper sorry for closing #1300. There was also the case of MsSQL (with prefix `0x`), so I had to use the sqlmap's functionality for this one

**Comment by stamparm** [comment]
@sqlmapper anyway, thank you for your report and contribution :)
