### ISSUE TITLE
sqlmap injecting payload inside cookies

### ISSUE THREAD

**Issue by nlk12345** [sqlmapproject/sqlmap#1310]
syntax:
`sqlmap.py -u "http://www.example.com/user.php" --data="id=2" -P id --cookie="P_cookie=xxxx;P_username=bobby;P_remember=2;P_test=x" --D database -T table -C email --where="username='admin'" --dump -v 4`

this results in an additional cookie being added (named P_id) containing the payload contents triggering the waf and causing a complete mess, so the cookies then look like this (value of P_id cookie matches EXACTLY what the post parameter id contains [depending what payload sqlmap uses]):
`P_cookie=xxxx;P_username=bobby;P_remember=2;P_test=x;P_id=sqlmappayload`

Please fix this, this is so frustrating.

Thanks.

**Comment by stamparm** [comment]
Option `-P` doesn't exist

**Comment by stamparm** [comment]
Option `--D` doesn't exist

**Comment by stamparm** [comment]
Trying just as an example: `python sqlmap.py -u "http://testphp.vulnweb.com/artists.php" --data="id=2" -p id --cookie="P_cookie=xxxx;P_username=bobby;P_remember=2;P_test=x" -D database -T table -C email --where="username='admin'" --dump -v 4` and I really can't reproduce this kind of behavior. Find screenshot attached.

![screenshot - 07202015 - 11 19 20 pm](https://cloud.githubusercontent.com/assets/921555/8787703/e3b44180-2f35-11e5-8225-cc646a512b2d.png)

**Comment by stamparm** [comment]
p.s. Please, be sure that you run the latest revision from this Github repository.
