### ISSUE TITLE
sqlmap creates table 'sqlmapfile'?!

### ISSUE THREAD

**Issue by rwy38017** [sqlmapproject/sqlmap#1326]
Stacked query injection for MYSQL, i noticed sqlmap creates a table named sqlmapfile inside one of the databases,

Does this table get dropped after sqlmap is done with the testing or does it stay there (that would be insanely stupid)?

If it does get dropped, what is the original purpose of it anyway?

**Comment by stamparm** [comment]
It is being dropped at the end of sqlmap's run when being used. It is used
for extraction/transfer of data (e.g. when doing the
--file-read/--file-write).
