### ISSUE TITLE
Encoding issue while parsing Raw request from file - Patch for an Issue #360 not working

### ISSUE THREAD

**Issue by mak93129** [sqlmapproject/sqlmap#1327]
Hello,

As per the patch #360, the '+' sign won't be changed to space ' '.  But still when I am trying to run sqlmap on multipart POST request that contains viewstate, the sqlmap is changing each '+' sign in viewstate value to ' ', thus the server responses back with '500 - Internal Server Error'.

Please guide how can I avoid sqlmap to change the + sign in viewstate value to ' '.

**Comment by stamparm** [comment]
Can you please write an example of request file you used?

**Comment by mak93129** [comment]
Please check the figure:

![sqlmap request issue](https://cloud.githubusercontent.com/assets/13721587/9222168/055e16a0-4109-11e5-9908-f5096d3b67c7.png)

The left one shows the request that sqlmap is sending. We can see that the '+' sign is being replaced to space ' '. Compare it with the one at right - which is the actual request of application.

**Comment by stamparm** [comment]
Two things:

1) Please retry with the latest revision
2) I've asked you to write an example of request file (if you have one). Also, in your case, if you provided that screenshot then headers (especially "Content-Type") would be utterly helpful.

**Comment by mak93129** [comment]
Below is the request:
___________________
POST /abc/abc.aspx HTTP/1.1
Content-Length: 30593
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip,deflate
Host: vulnerable-site.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0
Connection: close
Referer: https://vulnerable-site.com/abc/aaa.aspx
Cookie: Site-Cookie=SoUPcq4C0QEkAAAAM2YxNDQxNWEtNjI0ZS00OTEyLWE0NjEtNTJkNWZlYTcwNTQ20
Content-Type: multipart/form-data; boundary=---------------------------31163119519056
