### ISSUE TITLE
ImportError: No module named site

### ISSUE THREAD

**Issue by alexoslabs** [sqlmapproject/sqlmap#1329]
The error ImportError: No module named site was displayed after of the git pull.

System Info:
Windows 7 x86_64
Python 2.7

Regards,

Alexos

**Comment by stamparm** [comment]
But sqlmap doesn't import site module. Can you please write down the complete command used and the complete stack trace

**Comment by stamparm** [comment]
Reference: https://docs.python.org/2/library/site.html

`This module is automatically imported during initialization. The automatic import can be suppressed using the interpreter’s -S option.`

I would say that you have a broken Python installation

**Comment by alexoslabs** [comment]
c:\Tools\sqlmap>python sqlmap.py -u "http:\\xxxx.com" --random-agent --risk "3" --level "5" --threads "10" -dbms "MySQL" --technique "BEUS"
ImportError: No module named site

**Comment by alexoslabs** [comment]
Hi stamparm,

The tool was working before the update.

Regards,

**Comment by stamparm** [comment]
sqlmap doesn't have anything to do with that module. Also, latest commits are unrelated to this.

As said, take a look into that link I've sent to you. You'll see that that module is automatically included by Python.

Try to run python as a standalone (without sqlmap.py) and report back

**Comment by alexoslabs** [comment]
c:\Tools\sqlmap>python 
ImportError: No module named site

Apparently is a Python´s flaw.  I will investigate more about that.

Thanks for the help;

Regards,

Alexos

**Comment by alexoslabs** [comment]
Solved!

Python 2.7.10 fix the error.

Thanks again.
