### ISSUE TITLE
information required to reproduce the bug

### ISSUE THREAD

**Issue by GalileoZeroDay** [sqlmapproject/sqlmap#1358]
sqlmap version: 1.0-dev
Python version: 2.7.3
Operating system: posix
Command line: ./sqlmap -u ***************** --crawl=6 -v2
Technique: None
Back-end DBMS: None (identified)

**Comment by stamparm** [comment]
I need the whole bug message. Including the stack trace

**Comment by stamparm** [comment]
@GalileoZeroDay ping?
