### ISSUE TITLE
output folder location?

### ISSUE THREAD

**Issue by heska77240** [sqlmapproject/sqlmap#1361]
hello i'm on kali 2.0 and i can't find the output folder location....

where is it please thank you

**Comment by stamparm** [comment]
have you looked into `~/.sqlmap/output`?

**Comment by stamparm** [comment]
also, at the end of sqlmap run you should have a message like this:

```
[12:30:00] [INFO] testing MySQL
[12:30:00] [INFO] confirming MySQL
[12:30:00] [INFO] the back-end DBMS is MySQL
web application technology: Nginx, PHP 5.3.10
back-end DBMS: MySQL >= 5.0.0
[12:30:00] [INFO] fetched data logged to text files under '/home/stamparm/.sqlmap/output/testphp.vulnweb.com'
```

**Comment by heska77240** [comment]
Yes it is in root/.sqlmap/output, 

But when i want to go here manually i don't find the .sqlmap folder ....why? It is hidden??

**Comment by btw7shny** [comment]
+1

**Comment by Ekultek** [comment]
+1 controlling the output directory could be really useful

**Comment by stamparm** [comment]
```
--output-dir=OUT..  Custom output directory path
```

**Comment by adamshecht** [comment]
you cant find it cause the folder is hidden. because it has the " . " in front of the name of the fold it makes it hidden. so when searching for the folder and want to list all the files in the directory, do ls -a to include all files including hidden files with the . in front of the name

**Comment by sonu8726k** [comment]
I face the same problem .please provide any solution on how to fetch the logged data 
from root/.sqlmap/output

**Comment by stamparm** [comment]
@sonu8726k after each run you get the (default/set) location of output:

`[XX:XX:XX] [INFO] fetched data logged to text files under '...'`

If you are not able to access those files, please provide the exact console output you get and **EXACT** commands you are trying to use when accessing those files. I have a feeling that you have some basic Linux usage problems here

**Comment by ifconfig-me** [comment]
**If you guys still looking for output folder, here it is:** 
![Screenshot from 2019-08-28 13-30-19](https://user-images.githubusercontent.com/25315805/63878913-37070480-c9d3-11e9-93bb-aa245586e171.png)

**Comment by invisible0ofc** [comment]
obg

**Comment by manzoo16** [comment]
same here can't sqlmap output file even after ticking the "show hidden files" option.

**Comment by stamparm** [comment]
@manzoo16 This is my last post for similar "problems". sqlmap says loud and clear what's the "output folder" location at the end of the program's run (no matter the OS type):

![screenshot_3](https://user-images.githubusercontent.com/921555/69906500-c6ea8f00-13c4-11ea-94ed-b3d14816577d.png)

**Comment by FkeyboardM** [comment]
/home/"user"/.local/share/sqlmap/output

**Comment by stamparm** [comment]
@FkeyboardM yup. I stand corrected. That's the "new" scheme used for last couple of months. I haven't deleted my old one in that previous reply, thus, it was (automatically) preferred over the new one.

So, this should be the "new" location:

![1](https://user-images.githubusercontent.com/921555/99946731-26307480-2d77-11eb-837f-3d5cfdf9ce2d.png)

**Comment by ashimmohanto1989** [comment]
/root/.local/share/sqlmap/output/results-10172022_0238am.csv'

**Comment by gigglebits** [comment]
It was a while ago so I'm sure you don't need it anymore, but if anyone finds this thread from google or something and you're on your own machine you can try the command. Normally it will be under the users's home directory in the .local/share/sqlmap/output/<target>/ directory. 

Command:
find -name 'session.sqlite' 

The log should be in the same folder as it.

**Comment by stamparm** [comment]
@0000day yup, it is all tiresome.

`export SQLMAP_OUTPUTDIR=/tmp`

![image](https://github.com/user-attachments/assets/2080ea47-5114-4fac-9013-02beeb6d28ce)

**Comment by noqtor** [comment]
on windows : C:\Users\Username\AppData\Local\sqlmap\output\

**Comment by mam54jdu645-max** [comment]
python sqlmap.py -u "http://172.16.0.1login" --data="user=admin&pass=admi
