### ISSUE TITLE
Command not found on Skipping tests payloads

### ISSUE THREAD

**Issue by Cypaubr** [sqlmapproject/sqlmap#1380]
I am testing my website for vulnerabilities and when sqlmap asks me if I want "to skip test payloads specific for other DBMSes? [Y/n]" I type "y" and press ENTER.
At this moment sqlmap crashes and I got this message : "bash: y : command not found".

The error appears both on the no-git and the git version of sqlmap...

**Comment by stamparm** [comment]
Enclose your url with either single or double quotes
