### ISSUE TITLE
Request: Adapting payload

### ISSUE THREAD

**Issue by giveen** [sqlmapproject/sqlmap#1381]
http://labs.detectify.com/post/74374001055/the-ultimate-sql-injection-payload

I have a request for a feature.
Is there anyway for this to be implimented?

**Comment by stamparm** [comment]
This is just a "show off" payload without any practical value. sqlmap uses
(and it has to use to cover wide spectrum) hundreds of different boundary
combinations, so incorporating one such "hybrid" would not make any sense.

**Comment by giveen** [comment]
Thank you!
