### ISSUE TITLE
sqlmap could not get the data with UNION QUERY version 1.0-dev-fb5a75c

### ISSUE THREAD

**Issue by KaiyiZhang** [sqlmapproject/sqlmap#1382]
Today, I pull the sqlmap to version "1.0-dev-fb5a75c", and test sqlmap in my sql env.

when I use "UNION QUERY" technique, sqlmap could not get the data.

sqlmap.py -u "http://TARGET/show.php?id=33" -v 5  --technique=U  -f -b --current-user --current-db
![qq 20150902111745](https://cloud.githubusercontent.com/assets/1725575/9622344/65769b96-5164-11e5-9866-bc0bd4ef9e17.png)
Only use --hex it get it, i think it's a problem.

Myenv:
OS: Windows Server 2003(Chinese)
APP: Appserv + PHPCMS

**Comment by stamparm** [comment]
And it worked before, or?

If it didn't work before too, then this is a known problem (not bug) in
some setups where (e.g.) CAST makes problems. That's why you are warned to
use one of those auxiliary switches at the end of such futile run.
