### ISSUE TITLE
TOR auto NEWNYM

### ISSUE THREAD

**Issue by geolado** [sqlmapproject/sqlmap#1386]
I think it would be very helpfull if the sqlmap automaticly detects when a server is blocking your "TOR-ip" and sends a NEWNYM to the TOR control port ( http://superuser.com/questions/138262/how-to-flush-tor-circuit ) . 

What do you guys think ?

**Comment by stamparm** [comment]
Not bad idea, but how to make the workflow to be "as easy as possible" and "automatic" when that same NEWNYM requires authentication password. Keep in mind that users really like to use `--batch` and that some of them wouldn't want to get stuck with some `authenticate` prompt coming from sqlmap.

In plainspeak, please give couple of ideas how to incorporate this as easy as possible

**Comment by stamparm** [comment]
@geolado ping?

**Comment by geolado** [comment]
Sorry for the delay .

Well , the authentication enabled isn't the default scenario . I've rarely seen some one using it .
Anyway , it should work with something like "--auth-cred" type of option , no ?

**Comment by stamparm** [comment]
`Well , the authentication enabled isn't the default scenario`

My `/etc/tor/torrc`:

```
...
## The port on which Tor will listen for local connections from Tor
## controller applications, as documented in control-spec.txt.
ControlPort 9051
## If you enable the controlport, be sure to enable one of these
## authentication methods, to prevent attackers from accessing it.
#HashedControlPassword 16:872860B76453A77D60CA2BB8C1A7042072093276A3D701AD68........
#CookieAuthentication 1
...
```

and when I connect to 9051:

```
$ telnet localhost 9051
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
NEWNYM
514 Authentication required.
Connection closed by foreign host.
```

I think that you are wrong here

**Comment by stamparm** [comment]
I've done the auto NEWNYM couple of times in last couple of years and as I recall I couldn't do this in non-auth manner

**Comment by littlegrizmin** [comment]
You could just execute service tor reload which forces NEWNYM... Just an idea... :)

**Comment by stamparm** [comment]
And on Windows?

I'll leave this unimplemented as it looks far from "batchable"
