### ISSUE TITLE
sqlmap doesn't detect stacked query injection

### ISSUE THREAD

**Issue by tiedot1** [sqlmapproject/sqlmap#1388]
```
sqlmap.py -u ***********************  --eval="import base64; x=base64.b64encode(****)" -v3 -p id --dbms=mysql --technique=S --random-agent -v3

[INFO] testing 'MySQL > 5.0.11 stacked queries (SELECT - comment)'
[PAYLOAD] 1);(SELECT * FROM (SELECT(SLEEP(5)))JEHh)#
[WARNING] time-based comparison requires larger statistical model, please wait.
[CRITICAL] considerable lagging has been detected in connection response(s). Please use as high value for option '--time-sec' as possible (e.g. 10 or more)
```

This is a payload that I tested personally which works, I even replayed the exact request sent by sqlmap and it works, if I do SLEEP(15), I get response in 16-17 seconds, if I do SLEEP(5), I get response in 6-7 seconds.

I tried setting time-sec manually, still failed to detect injection point

**Comment by stamparm** [comment]
Please help here as I believe that here is a problem with the setup. Can you please provide parameter values here and complete eval.

**Comment by tiedot1** [comment]
?req=[base64 encoded request]
the request is value1=FOO&value2=1000
if you decode base64 it becomes ?req=value1=FOO&id=1000

eval code: import base64; req=base64.b64encode(req). I checked the requests using Fiddler and they were correct. I had verbose set to 3, and I could see sqlmap pausing for X amount of seconds when sending the correct request, then it just ignored it and moved on to another payload

**Comment by stamparm** [comment]
So, you are doing something like this (or at least this should be the proper way):

```
python sqlmap.py -u "http://testphp.vulnweb.com/artists.php?artist=value1=FOO" --eval="import base64; artist=base64.b64encode(artist + '&id=1000')"
```

**Comment by tiedot1** [comment]
```
sqlmap.py -u "http://test.com/?req=value1=FOO&id=123" -p id --eval="import base64; req=base64.b64encode(req + '&id=' + id')"
```
This does add another unneeded parameter when request is sent, but it is ignored by the server.

**Comment by stamparm** [comment]
Have I written `"http://test.com/?req=value1=FOO&id=123"` or `"http://www.test.com/?req=value1=FOO"` ??

You've said in your original Issue that you have both `value1` and `id` inside the `req` parameter as base64 encoded value(s). When you run my provided command (without `&id=123` inside the `-u`) you'll see that there is no `unneeded parameter`
