### ISSUE TITLE
sqlmap bulkfile and post data to all urls?

### ISSUE THREAD

**Issue by romanthiel** [sqlmapproject/sqlmap#1392]
hello. when inserting urls without get parameters in the bulkfile and then let sqlmap go for search for injections, why can't i use the --data  POST option on all urls in the bulkfile?
I know there is an sql injection in on a php page on 2 sites for exampe
bulkfile looks like:
http://www.site1.com/vuln.php
http://www.site2.com/vuln.php
now i want sqlmap.py -m bulfille.txt --data="id=1*" but always tell me couldn't find any GET Parameters..
any ways to make it work with POST?

**Comment by stamparm** [comment]
@romanthiel it should be ok now
