### ISSUE TITLE
Tor not working 

### ISSUE THREAD

**Issue by Pablossoo** [sqlmapproject/sqlmap#1417]
can someone tell me, why I gets this error, when I use tor? In normal connecting without tor, all working.

using python version 2.7         
sqlmap {1.0-dev-nongit-20150919}

https://gyazo.com/e3ab8127d02ed761fe4723d2b17d43c4

I use 
sqlmap.py  -u "host" --dbs --tor --tor-type=SOCKS5 --tor-port=9150 --random-agent

**Comment by stamparm** [comment]
Which tor application/bundle do you use?

**Comment by Pablossoo** [comment]
Hey, Tor browser 5.2  64x on windows.

**Comment by stamparm** [comment]
You would be presented with:

[09:07:25] [WARNING] increasing default value for option '--time-sec' to 10 beca
use switch '--tor' was provided
[09:07:25] [INFO] setting Tor HTTP proxy settings
[09:07:27] [CRITICAL] can't establish connection with the Tor proxy. Please make
 sure that you have Vidalia, Privoxy or Polipo bundle installed for you to be ab
le to successfully use switch '--tor' (e.g. https://www.torproject.org/projects/
vidalia.html.en)

in case that Tor is not used. You are probably being blocked by the remote server.

**Comment by stamparm** [comment]
What do you get for:

sqlmap.py -u "http://testphp.vulnweb.com/artists.php?artist=1" --dbs --tor --tor-type=SOCKS5 --tor-port=9150 --random-agent --check-tor

p.s. some hosts are blocking any access to Tor IPs (IP lists are publicly available)

**Comment by Pablossoo** [comment]
Hey,  I gets

https://gyazo.com/3fa4a753c9faae2a4a89b94385779d86

**Comment by stamparm** [comment]
And if you scan some other random site?

**Comment by Pablossoo** [comment]
Yes,  i tried   some  sites and on the each it same.

**Comment by stamparm** [comment]
This moment tried the following (on WinXP VM):

1) Downloaded and installed Tor Browser from https://www.torproject.org/projects/torbrowser.html.en#downloads
2) Downloaded latest sqlmap revision from https://github.com/sqlmapproject/sqlmap/archive/master.zip
3) Ran the: `sqlmap.py -u "http://testphp.vulnweb.com/artists.php?artist=1" --tor --tor-type=SOCKS5 --tor-port 9150 --check-tor`

Everything works as expected:
![test](https://cloud.githubusercontent.com/assets/921555/9988673/e122e342-6052-11e5-9a76-3562f15f8e1f.PNG)

**Comment by Pablossoo** [comment]
Ya,  now it's working, Thanks mate!!

**Comment by zverbeta** [comment]
Not work for me.

3) Ran the: sqlmap.py -u "http://testphp.vulnweb.com/artists.php?artist=1" --tor --tor-type=SOCKS5 --tor-port 9150 --check-tor

Output:  [CRITICAL] it seems that Tor is not properly set. Please try using options '--tor-type' and/or '--tor-port'

**Comment by stamparm** [comment]
@zverbeta which sqlmap revision and which Python version?

**Comment by zverbeta** [comment]
Python 2.7.11
Sqlmap yours

**Comment by bb1ox1bb** [comment]
sqlmap version please run xxx@xxx:~$ sqlmap --version


2015-12-21 8:51 GMT+00:00 zverbeta <notifications@github.com>:

**Comment by bb1ox1bb** [comment]
из гитхуба скациал ?

2015-12-21 8:57 GMT+00:00 Boom Box <bb1ox1bb@gmail.com>:

**Comment by zverbeta** [comment]
да, по ссылке выше

**Comment by bb1ox1bb** [comment]
на какои ситеме та? ubuntu debian или на чем та запускаеш

2015-12-21 9:01 GMT+00:00 zverbeta <notifications@github.com>:

**Comment by zverbeta** [comment]
windows 8.1

**Comment by zverbeta** [comment]
sqlmap version 0.9

**Comment by zverbeta** [comment]
Все, решил. Как оказалось я порт перепутал. Спасибо!

**Comment by bb1ox1bb** [comment]
ne za chio :D udachi :)

2015-12-21 9:08 GMT+00:00 zverbeta <notifications@github.com>:

**Comment by Analyst1981** [comment]
sqlmap -g "inurl:.php?id=1" --random-agent  --time-sec 15 --tor --tor-type=SOCKS5
…
[CRITICAL] unable to find results for your search dork expression

**Comment by stamparm** [comment]
@Analyst1981 
![1](https://user-images.githubusercontent.com/921555/31059555-798372e2-a704-11e7-9192-831deb3e5e2f.png)

**Comment by Analyst1981** [comment]
sqlmap -g "inurl:.php?id=1" --random-agent --time-sec 15 --tor --tor-type=SOCKS5 --check-tor --tor-port=9150
*] starting at 12:56:15

[12:56:15] [INFO] setting Tor SOCKS proxy settings
[12:56:15] [INFO] fetched random HTTP User-Agent header from file '/usr/share/sqlmap/txt/user-agents.txt': 'Mozilla/5.0 (X11; Linux x86_64; rv:28.0) Gecko/20100101 Firefox/28.0'
[12:56:24] [INFO] using search result page #1
[12:56:33] [WARNING] Google has detected 'unusual' traffic from used IP address disabling further searches
no usable links found. What do you want to do?
[1] (re)try with DuckDuckGo (default)
[2] (re)try with Disconnect Search
[3] quit

**Comment by stamparm** [comment]
@Analyst1981 you have a WARNING message "Google has detected 'unusual' traffic from used IP address disabling further searches no usable links found" which explains everything
