### ISSUE TITLE
using --forms trimes the url

### ISSUE THREAD

**Issue by bararchy** [sqlmapproject/sqlmap#1418]
my URL: 
```
https://*.*.*.*/login.aspx?folderType=1&sType=SMFT&sGID=8d2c1be9b744fa1&fGID=0&&&eGID=Y9Zpq829FoOdHh%2byUWEj3XvB6XBqHse%2f0xYEW7z0pFk%3d&getPubPac=PlVIIJC04YxaCAFCqraLbg%3d%3d&eURL=safe
```
When using --forms, SQLMAP will look for forms using only /login.aspx instead of calling the URL with all object, thous disallowing me to get the forms that resides in the full "path"
Using -u without --forms will initiate get requests to the full URL, as expected.

**Comment by stamparm** [comment]
I've just (re)tried:

1) `python sqlmap.py -u "http://127.0.0.1/login.aspx?folderType=1&sType=SMFT&sGID=8d2c1be9b744fa1&fGID=0&&&eGID=Y9Zpq829FoOdHh%2byUWEj3XvB6XBqHse%2f0xYEW7z0pFk%3d&getPubPac=PlVIIJC04YxaCAFCqraLbg%3d%3d&eURL=safe" --forms`

generates (at the 127.0.0.1's SimpleHTTPServer):

```127.0.0.1 - - [06/Oct/2015 14:34:58] "GET /login.aspx?folderType=1&sType=SMFT&sGID=8d2c1be9b744fa1&fGID=0&&&eGID=Y9Zpq829FoOdHh%2byUWEj3XvB6XBqHse%2F0xYEW7z0pFk%3d&getPubPac=PlVIIJC04YxaCAFCqraLbg%3d%3d&eURL=safe HTTP/1.1" 404 -```

2) `python sqlmap.py -u "http://xxx.yyy.zzz/login.aspx?folderType=1&sType=SMFT&sGID=8d2c1be9b744fa1&fGID=0&&&eGID=Y9Zpq829FoOdHh%2byUWEj3XvB6XBqHse%2f0xYEW7z0pFk%3d&getPubPac=PlVIIJC04YxaCAFCqraLbg%3d%3d&eURL=safe" --forms`

generates (at the xxx.yyy.ttt's Apache):

```
85.114.40.90 - - [06/Oct/2015:12:29:39 +0000] "GET /login.aspx?folderType=1&sType=SMFT&sGID=8d2c1be9b744fa1&fGID=0&&&eGID=Y9Zpq829FoOdHh%2byUWEj3XvB6XBqHse%2F0xYEW7z0pFk%3d&getPubPac=PlVIIJC04YxaCAFCqraLbg%3d%3d&eURL=safe HTTP/1.1" 404 465 "-" "sqlmap/1.0-dev-78bbf5d (http://sqlmap.org)"
```
