### ISSUE TITLE
Charset for Chinese characters not properly shown

### ISSUE THREAD

**Issue by isopropyx** [sqlmapproject/sqlmap#1423]
Hello,

I am having this issue where dumping a db made of a mix of Chinese and alphabetic letters.
When not specifying a --charset, I am getting some weird results (just like this guy: https://security.stackexchange.com/questions/41411/sqlmap-extracts-weird-chars-in-one-column).

When using charsets for chinese language it is not better. I have tested every single chinese ones from: https://docs.python.org/2/library/codecs.html#standard-encodings
The only one that seems to get close is --charset=gb18030 ((but it only partially works (mix of chinese characters and alphabetic letters)).

I am not getting the "unknown charset '     '. Please report by e-mail..."

What charset should I be using then?

Thank you

**Comment by stamparm** [comment]
When only one column is "strange", especially if its called `pwdlogin` like in that case, then you can be 100% sure its a binary password hash. You should extract it by using the `--binary-fields=pwdlogin` (hidden feature)
