### ISSUE TITLE
Add feature to manipulate session data

### ISSUE THREAD

**Issue by tampe125** [sqlmapproject/sqlmap#1436]
Is there a way to manipulate session data? More specifically, add/delete injection points and tables
I know this could seem a weird request, but please consider this real use case.

I was performing some pen tests vs a customer, and I found an injection point in a url like this:
`param1=foobar&param2=dummy&param3=xxx&param4=xxx`

`param1` was injectable, so I started to retrieve the table list (700+ tables). Sadly (or luckily for them), when I was half way done, they patched `param1` vulnerability. 
Is there a way to tell sqlmap to "forget" a specific injection point? I know I could simply flush the whole session, but that means that I'll have to dump all the results I have accomplished so far.
I tried to manually connect to the sqllite database, but I couldn't understand the logic on how data is stored (and I don't really want to mess around with raw data).

For the same reason it could be awesome if we could export/import the list of the tables.
Do you have any thoughts on this?

**Comment by stamparm** [comment]
@tampe125 it goes like this. "Session" is a basically hash-table. Idea is that data for lots of different "targets" could be stick into it (via option `-s`).

Now, hash-table requires "hashing" :). Also, one target can have different injection points pointing to different DBMSes and/or DBs all-together (e.g. different queries for different systems and/or different SQLite DBs on different pages). Hence, the "hash" for each entry (e.g. query result) is bound (inhashed) with the vulnerable URL itself. I am afraid that this is not going to be changed.

Now, as of extracting data from the session itself. You can open the session in a SQLite (or some related tool) and see what's inside (and probably extract some useful information yourself). There is no way how to correlate the values to "keys" - so, no way how to reconstruct what has been i.e. the result of table retrieval and what has been a result of banner retrieval. Thats how hash-tables work. Storing the non-hashed keys would be the overkill (especially in case of HUGE dbs with thousands of queries -> and we have to support resuming of each of query)

**Comment by tampe125** [comment]
Yep, that makes sense. Thank you very much for the detailed explanation!
