### ISSUE TITLE
So I know what's the version, how do I skip all the tests that are for above versions?

### ISSUE THREAD

**Issue by Irikdn** [sqlmapproject/sqlmap#1442]
Hi there,

I am 100% sure of the version of the database which is MySQL 4.1.21 in this case. ((from php info or from previous sqli points (time-based)).

How do I make slqmap skips all tests that are specifically dedicated to above version of MySQL 4.1.21?

--dbms let me choose a specific db management system which is really great and time saving. But I don't see anything that would let me choose a version for a specific dbms.

Thank you much

**Comment by stamparm** [comment]
Upload to the latest revision and do the following:

`python sqlmap.py ... --test-skip='(MySQL > 5)|(MySQL >= 5)'`

or just

`python sqlmap.py ... --test-skip='MySQL >=? 5'`

**Comment by Irikdn** [comment]
Well, what can I say?
Thank you so much for taking time to reading everyone's "problems" and answering it. 
I love you
