### ISSUE TITLE
Manually supply query length

### ISSUE THREAD

**Issue by tampe125** [sqlmapproject/sqlmap#1448]
Sometimes while extracting data I already know the length of the query.
For example this happens with hashed password fields: I already know that a md5 hashed password will be 32 chars long.
In this way we could reduce the amount of required queries.

As a final word, please remember that we can not trust the columns specification for its length: several times I saw `CHAR(255)` fields containing only 32 chars :(

Do you think it would be possible to manually supply the length of the query?

**Comment by stamparm** [comment]
`As a final word, please remember that we can not trust the columns specification for its length: several times I saw CHAR(255) fields containing only 32 chars :(`
- we are not using column specification for anything than for showing the type of data. When sqlmap shows you the current item length its based on CURRENT query result length, nothing else. Also, this is used only in cases when you are using `--threads` as we can't run multithreaded runs on results where we don't know the number of result chars

`Sometimes while extracting data I already know the length of the query.`
- as already said, this is only being extracted/queried in multi-threaded cases. This could save some queries, but I am not sure that anybody would know about this option nor that anybody would use it in correct manner (i.e. only usable in multithreaded cases, against boolean-based SQLi when you know the constant length for a certain column)

**Comment by tampe125** [comment]
Ok, thank you very much for your explanation; yep that really is an edgy case ;)
