### ISSUE TITLE
Temporary (1 week) hidden switch for nnc5ed

### ISSUE THREAD

**Issue by stamparm** [sqlmapproject/sqlmap#1450]
Just as a gratitude for the nnc5ed conference organization

p.s. removing it on 13th of this month :)

**Comment by plutec** [comment]
Thanks for your talk and cheer up with this great project!

**Comment by stamparm** [comment]
For the history (I'll remove it in few mins):

![nnc5ed](https://cloud.githubusercontent.com/assets/921555/10455334/f4ea8848-71ba-11e5-9feb-e5cc05b25113.png)

**Comment by kidol** [comment]
@stamparm Where to see the talk?

**Comment by stamparm** [comment]
@kidol as I know, talks weren't recorded

**Comment by kidol** [comment]
OK. Keep it up.
