### ISSUE TITLE
Kali Linux integration

### ISSUE THREAD

**Issue by tampe125** [sqlmapproject/sqlmap#1455]
Sorry for being a PITA, but I'm having some troubles with the Metasploit integration.
I'm using a Kali Linux system, patched to the last update.
When I try to use the `--os-pwn` option, SQLmap complains about not being able to find all the required executables.

However, looking at the error message, it seems it is looking for executables that were removed from the MSF project: msfcli, msfencode, msfpayload

Is that correct or am I missing something while launching sqlmap?

**Comment by stamparm** [comment]
Please update and retry it again.

Currently it goes through all environment paths (if `--msf-path` not set) inside the `PATH` and searches for the directory that contains either the `msfcli` or `msfconsole`. Inside of that same (found) directory it searches for either `msfvenom` (newer versions of Metasploit) or `msfencode`/`msfpayload` (older versions of Metasploit)
