### ISSUE TITLE
Simple SQL error confirmed with Burp repeater but not detected in sqlmap

### ISSUE THREAD

**Issue by Isa047** [sqlmapproject/sqlmap#1468]
Hello,
I have this POST request with 2 parameters that are showing an SQL error when using payload '
dbms=MSSQL
Shouldn't this error should be detected by sqlmap right at the beginning in heuristic search?
I also can see the error in traffix.txt from request #4 and no WAF seems to be in use.

HTTP request [#1]:
POST /clients/login.php HTTP/1.1
Accept-language: en-US,en;q=0.5
Accept-encoding: gzip, deflate
Accept-charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.2.1
DNT: 1
Host: www.testsite.com.au
Referer: http://www.testsite.com.au/public/about-us
Pragma: no-cache
Cache-control: no-cache,no-store
Cookie: e945f29f457988c069627e0d44b379c6=qhdpifkkpu2veo83kifbu3eco8; _ga=GA1.3.; PHPSESSID=40pmd; AJSTAT_ok_pages=13; AJSTAT_ok_times=1
Content-type: application/x-www-form-urlencoded
Content-length: 44
Connection: close

testing=123&password=123&lat=3&x=4&y=11

HTTP redirect [#1] (302 Found):
Content-length: 20
X-powered-by: PHP/5.3.20
Content-encoding: gzip
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Vary: Accept-Encoding
Server: Apache/2.2.22 (Fedora)
Connection: close
Location: /public/index.php?option=com_content&view=article&id=98&Itemid=0
Pragma: no-cache
Cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Date: Thu, 15 Oct 2015 04:21:55 GMT
Content-type: text/html; charset=UTF-8

############################################################################

HTTP request [#2]:
POST /clients/login.php HTTP/1.1
Accept-language: en-US,en;q=0.5
Accept-encoding: gzip, deflate
Accept-charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.2.1
DNT: 1
Host: www.testsite.com.au
Referer: http://www.testsite.com.au/public/about-us
Pragma: no-cache
Cache-control: no-cache,no-store
Cookie: e945f29f457988c069627e0d44b379c6=qhdpifkkpu2veo83kifbu3eco8; _ga=GA1.3.; PHPSESSID=40pmd; AJSTAT_ok_pages=13; AJSTAT_ok_times=1
Content-type: application/x-www-form-urlencoded
Content-length: 44
Connection: close

testing=123&password=123&lat=3&x=4&y=11

HTTP redirect [#2] (302 Found):
Content-length: 20
X-powered-by: PHP/5.3.20
Content-encoding: gzip
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Vary: Accept-Encoding
Server: Apache/2.2.22 (Fedora)
Connection: close
Location: /public/index.php?option=com_content&view=article&id=98&Itemid=0
Pragma: no-cache
Cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Date: Thu, 15 Oct 2015 04:21:59 GMT
Content-type: text/html; charset=UTF-8

############################################################################

HTTP request [#3]:
POST /clients/login.php HTTP/1.1
Accept-language: en-US,en;q=0.5
Accept-encoding: gzip, deflate
Accept-charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.2.1
DNT: 1
Host: www.testsite.com.au
Referer: http://www.testsite.com.au/public/about-us
Pragma: no-cache
Cache-control: no-cache,no-store
Cookie: e945f29f457988c069627e0d44b379c6=qhdpifkkpu2veo83kifbu3eco8; _ga=GA1.3.; PHPSESSID=40pmd; AJSTAT_ok_pages=13; AJSTAT_ok_times=1
Content-type: application/x-www-form-urlencoded
Content-length: 44
Connection: close

testing=123&password=123&lat=3&x=4&y=11

HTTP redirect [#3] (302 Found):
Content-length: 20
X-powered-by: PHP/5.3.20
Content-encoding: gzip
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Vary: Accept-Encoding
Server: Apache/2.2.22 (Fedora)
Connection: close
Location: /public/index.php?option=com_content&view=article&id=98&Itemid=0
Pragma: no-cache
Cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Date: Thu, 15 Oct 2015 04:22:01 GMT
Content-type: text/html; charset=UTF-8

############################################################################

HTTP request [#4]:
POST /clients/login.php HTTP/1.1
Accept-language: en-US,en;q=0.5
Accept-encoding: gzip, deflate
Accept-charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.2.1
DNT: 1
Host: www.testsite.com.au
Referer: http://www.testsite.com.au/public/about-us
Pragma: no-cache
Cache-control: no-cache,no-store
Cookie: e945f29f457988c069627e0d44b379c6=qhdpifkkpu2veo83kifbu3eco8; _ga=GA1.3.; PHPSESSID=40pmd; AJSTAT_ok_pages=13; AJSTAT_ok_times=1
Content-type: application/x-www-form-urlencoded
Content-length: 68
Connection: close

testing=123&password=123.%22%2C%29%22..%27%29%28&lat=3&x=4&y=11

HTTP redirect [#4] (302 Found):
Content-length: 324
X-powered-by: PHP/5.3.20
Content-encoding: gzip
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Vary: Accept-Encoding
Server: Apache/2.2.22 (Fedora)
Connection: close
Location: /public/index.php?option=com_content&view=article&id=98&Itemid=0
Pragma: no-cache
Cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Date: Thu, 15 Oct 2015 04:22:03 GMT
Content-type: text/html; charset=UTF-8

<br />
<b>Warning</b>:  mssql_query() [<a href='function.mssql-query'>function.mssql-query</a>]: message: Incorrect syntax near ')'. (severity 15) in <b>/var/www/htdocs/clients/login.php</b> on line <b>96</b><br />
<br />
<b>Warning</b>:  mssql_query() [<a href='function.mssql-query'>function.mssql-query</a>]: General SQL Server error: Check messages from the SQL Server (severity 15) in <b>/var/www/htdocs/clients/login.php</b> on line <b>96</b><br />
<br />
<b>Warning</b>:  mssql_query() [<a href='function.mssql-query'>function.mssql-query</a>]: message: Unclosed quotation mark after the character string ''. (severity 15) in <b>/var/www/htdocs/clients/login.php</b> on line <b>96</b><br />
<br />
<b>Warning</b>:  mssql_query() [<a href='function.mssql-query'>function.mssql-query</a>]: General SQL Server error: Check messages from the SQL Server (severity 15) in <b>/var/www/htdocs/clients/login.php</b> on line <b>96</b><br />
<br />
<b>Warning</b>:  mssql_query() [<a href='function.mssql-query'>function.mssql-query</a>]: Query failed in <b>/var/www/htdocs/clients/login.php</b> on line <b>96</b><br />
<br />
<b>Warning</b>:  mssql_fetch_assoc() expects parameter 1 to be resource, boolean given in <b>/var/www/htdocs/clients/login.php</b> on line <b>97</b><br />

############################################################################

HTTP request [#5]:
POST /clients/login.php HTTP/1.1
Accept-language: en-US,en;q=0.5
Accept-encoding: gzip, deflate
Accept-charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.2.1
DNT: 1
Host: www.testsite.com.au
Referer: http://www.testsite.com.au/public/about-us
Pragma: no-cache
Cache-control: no-cache,no-store
Cookie: e945f29f457988c069627e0d44b379c6=qhdpifkkpu2veo83kifbu3eco8; _ga=GA1.3.; PHPSESSID=40pmd; AJSTAT_ok_pages=13; AJSTAT_ok_times=1
Content-type: application/x-www-form-urlencoded
Content-length: 68
Connection: close

testing=123&password=123.%22%2C%29%22..%27%29%28&lat=3&x=4&y=11

HTTP redirect [#5] (302 Found):
Content-length: 324
X-powered-by: PHP/5.3.20
Content-encoding: gzip
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Vary: Accept-Encoding
Server: Apache/2.2.22 (Fedora)
Connection: close
Location: /public/index.php?option=com_content&view=article&id=98&Itemid=0
Pragma: no-cache
Cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Date: Thu, 15 Oct 2015 04:22:04 GMT
Content-type: text/html; charset=UTF-8

############################################################################

**Comment by stamparm** [comment]
Can you please retry it now?

**Comment by Isa047** [comment]
Solved. Thanks a lot!
