### ISSUE TITLE
Post method / Blind

### ISSUE THREAD

**Issue by hencesar** [sqlmapproject/sqlmap#1507]
Guys, i have my target with blind sql vulnerability(POST) and i tried these ways:

1)
sqlmap.py -r PraCha_Ok.txt --method=POST -p CodAutoriz
Result: "All tested parameters appear to be no injectable" 
Acunetix say yes:
![pracha_acunetix](https://cloud.githubusercontent.com/assets/15571552/10870100/23f634fa-80a9-11e5-9cf5-8641e4539edd.png) )

2) 
SqlMap.py -u "https://www.pradochaves.com.br:443/pcmaster/enviasenha.asp" --data "CodAutoriz=1&CodCli=-1);%20waitfor%20delay%20'0:0:0'%20--%20&submit2=Confirmar%20Envio" - p "CodAutoriz"
Result: "It appears that you have provided tainted parameter values ('CodCli=-1) waitfor delay '0:0:0' -- ') with most problably leftover char/statments from .... Please, always use only valid parameters values so sqlmap ..."

3) 
SqlMap.py -u "https://www.pradochaves.com.br:443/pcmaster/enviasenha.asp" --data "CodAutoriz=&CodCli=&submit2=Confirmar%20Envio" - p "CodAutoriz"
Result: All tested parameters appear to be no injectable

I am forgetting or doing something wrong?
The attached file was obtained with Acunetix scan.

Thanks and hugs.

**Comment by hencesar** [comment]
POST /pcmaster/enviasenha.asp HTTP/1.1
Content-Length: 86
Content-Type: application/x-www-form-urlencoded
X-Requested-With: XMLHttpRequest
Referer: https://www.pradochaves.com.br:443/pcmaster/Login.htm
Cookie: ASPSESSIONIDSQBSRDSR=PFILAIMCDDFFFKCNLCMDKGPH
Host: www.pradochaves.com.br
Connection: Keep-alive
Accept-Encoding: gzip,deflate
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.63 Safari/537.36
Accept: */*

CodAutoriz=1&CodCli=-1);%20waitfor%20delay%20'0:0:0'%20--%20&submit2=Confirmar%20Envio

**Comment by stamparm** [comment]
1) `It appears that you have provided tainted parameter values ('CodCli=-1) waitfor delay '0:0:0' -- ') with most problably leftover char/statments from .... Please, always use only valid parameters values so sqlmap ..` -> this means that you have to use ORIGINAL (non-SQLi) values. For example: `...CodCli=1`
2) Acunetix results do not prove anything. Have you considered them to be false positives? Especially as it is a time-based SQLi

**Comment by hencesar** [comment]
Miroslav interesting! Thanks for the comment ...
I will try again and repeat test with BurnSuite .. maybe i have other
result!

Tks again!

2015-11-01 19:15 GMT-02:00 Miroslav Stampar <notifications@github.com>:
