### ISSUE TITLE
Session management

### ISSUE THREAD

**Issue by Hipapheralkus** [sqlmapproject/sqlmap#1516]
First of all, great tool, keep up the good work:)

Now to the point - I'm unable to find any "session management" within this tool. When I want to evaluate security of a site, where I first need to log in (with supplying parameters "txtusername=user&txtpassword=password" in POST to /login URL); and after WAF detects SQL injection attack, it destroys my session cookie and redirects me to Pleas log in page.

I see there is a "--safe-url" parameter which I can set to /login page. However, I can't add data to POST so it always behaves as GET (and the website doesn't allow transforming POST to GET). Hence I can't send login which would in return give me a new session cookie. Could you please add something like "--safe-data" to allow logging in?

Or maybe some other approach could work. For example if you would allow some string to detect whether I'm still within the session (e.g. "Welcome, user123") or outside of the session (e.g. "please log in to continue"); and only after I'm authenticated into the website again and I have a fresh session cookie, tainted data would be sent.

Thanks:)

**Comment by stamparm** [comment]
However, I can't add data to POST so it always behaves as GET:

```
    --safe-post=SAFE..  POST data to send to a safe URL
```

**Comment by Hipapheralkus** [comment]
Thanks:) Could you please list this hidden feature among all other parameters as well (https://github.com/sqlmapproject/sqlmap/wiki/Usage)? As it is not listed there. Are there some special commands for cookie setting of safe URL?

**Comment by Hipapheralkus** [comment]
Ok, what I wanted to achieve is working. However, from some reason the cookie from successful login is used in request only limited number of times.
Each time (because I have --safe-freq=1) it sends POST to login page with login credentials (correct behavior); then receive a Session cookie by "Set-cookie: " mechanism from a response. Then it uses this valid session cookie in the next attack request.
However, based on the logfile I can see that it only happens until the request 10. From request 11, it won't use obtained fresh cookie any longer. See numbers 11 and 12 from the logfile which I generated. After this 11th step, it loops and valid session cookie is never used again.
```
HTTP request [#1]: (login, gets SessionID=1 from response)
HTTP request [#2]: (attack, uses SessionID=1 in request)
HTTP request [#3]: (uses SessionID=1; login, gets SessionID=2 from response)
HTTP request [#4]: (attack, uses SessionID=2 in request)
HTTP request [#5]: (uses SessionID=2; login, gets SessionID=3 from response)
HTTP request [#6]: (attack, uses SessionID=3 in request)
HTTP request [#7]: (uses SessionID=3; login, gets SessionID=4 from response)
HTTP request [#8]: (attack, uses SessionID=4 in request)
HTTP request [#9]: (uses SessionID=4; login, gets SessionID=5 from response)
HTTP request [#10]: (attack, uses SessionID=5 in request)
HTTP request [#11]: (doesn't use SessionID any longer; login, gets SessionID=6 from response)
HTTP request [#12]: (attack, doesn't use SessionID in request any longer)
```

**Comment by stamparm** [comment]
Its very important for you to state whether that same behaviour has been happening in `testing` phase or later.

Also, please describe whether sqlmap asked you `do you want to merge cookies`?

**Comment by Hipapheralkus** [comment]
This behavior occurs when I enter command 
`-u "https://myVulnerableSite.com:443/blabla/page.aspx?Parameter1=1&parameter2=2" -p "parameter2" --threads=1 --safe-url="https://myVulnerableSite.com:443/login.aspx" --safe-post="username=name1&password=name2" --safe-freq=1 -t logfile.txt --user-agent="Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0"`
I'm asked whether I want to be redirected to "/welcome" page; I say no. I'm asked whether I want to detect WAF, I select no. After that, it starts testing and I already sent you sample of logfile. So yes, it is happening at the beginning of test - only few test vectors are sent with session cookie, others (vast majority) are not.
I'm not asked if I want to merge cookies.
It does not matter if I use `--dbms="" --os=""` to technologies used, the result is the same.

**Comment by stamparm** [comment]
Problem is that testing phase automatically drops any cookies provided by
the web server, other than user provided. Have to see what can be done in
your case

**Comment by stamparm** [comment]
@Hipapheralkus Sorry for waiting.

Can you please update to the latest revision and retry everything from the start?

**Comment by Hipapheralkus** [comment]
Many thanks, it is working perfectly:)
