### ISSUE TITLE
Use pymssql

### ISSUE THREAD

**Issue by hencesar** [sqlmapproject/sqlmap#1520]
Dear, how i can install pymssql in sqlmap? I sought documents in the GIT and google to no avail.

Sitema: Windows running python.

Thanks again!

**Comment by stamparm** [comment]
You haven't written which Python version.

You can take a look here: https://pypi.python.org/pypi/pymssql/2.0.1

Scroll down until you see something like:
pymssql-2.0.1.win32-py2.7.exe

Download the appropriate version (depending on your Python version) and install
