### ISSUE TITLE
sqlmap can't find injection point

### ISSUE THREAD

**Issue by thomja** [sqlmapproject/sqlmap#1536]
Hello

The parameter looks like this

u='OR(0)OR'

So in there 0 is the injection point. The injection type is boolean based blind so while I could do it manually it's gonna take a shit load of time. Even with sqlmap it's gonna take a very long time.

I have tried to use u='OR(*)OR' is the parameter in sqlmap but it still can't find it. I'm really not sure on how to continue.

As usual, thanks for any help!

**Comment by stamparm** [comment]
Hi.

Can you please be more specific. Please write down `True` and `False` requests as from your `u=OR(0)OR` its really not clear how to make one.

Also, why do you have to remove the spaces. If there is a WAF involved, then I believe that sqlmap could fail here

**Comment by thomja** [comment]
Sure

Please keep in mind that I'm still trying to learn a lot. So what I do to generate a true or false statement is basically setting the parameter to

    u=OR(if(now()=sysdate(),sleep(3),0))OR

Works great while I do it manually. And yes I also believe that a waf is causing some issues as I have been recieving some 403 errors.

I'm not sure I'm following you with "removing the spaces"? Could elaborate some?

Thanks for the help, I have used sqlmap before and it's really a wonderful tool.

**Comment by stamparm** [comment]
This doesn't make sense. You say that your injection starts with boolean
operator OR without any prefix/value. I can't imagine that without the
usage of original value (e.g. 1 OR...) or some prefix (e.g. ' OR...).

Please run sqlmap with --risk=3 to turn on OR injections. Maybe that will
solve your case. Also, please make sure that you provide original value of
parameter u to the sqlmap

**Comment by thomja** [comment]
The problem seems to be the WAF. I haven't managed to bypass it even with using a combination of tor and tampers... F***ing cloudflare

**Comment by stamparm** [comment]
Well, CloudFlare properly does its job
