### ISSUE TITLE
Please add git tags to your interim releases

### ISSUE THREAD

**Issue by offensive-security** [sqlmapproject/sqlmap#1544]
Firstly, thanks for sharing your code with the open-source world. 

As you may or may not be aware, we have included your tool in our [Kali Linux](https://www.kali.org/) penetration testing distribution so it can be easily installed by our large user-base. 

As the distribution includes hundreds of tools, keeping them updated is a significant undertaking. We would like to ensure that your tool is always kept as current as possible so that our users can benefit from the latest features and fixes. You could help us in this task immensely by [tagging](https://git-scm.com/book/en/v2/Git-Basics-Tagging) your releases here on GitHub. Tagging releases allows us to automate the process of checking for new releases, ensuring that tools get updated far more quickly. We noticed that your last tags are from 2012.

Tagging can be included in your workflow very easily and would go a long way to helping us keep your tool updated in our distribution. The most common type of tag is the "lightweight" version as follows (where 0.3 is the new version number):

`git-tag v0.3`
`git push --tags`

Thanks!

**Comment by stamparm** [comment]
@offensive-security we'll soon change our versioning system. i hope that you don't think that we don't know how do the tagging.

thing is that there are two moments here:
1) we wanted to make a perfect v1.0, which made us postpone this
2) sqlmap is changed on daily basis, sometimes on hourly basis. my personal objection toward your side (distribution maintainers) is that you stick with one number while ignoring the "development" part of the projects. if we do the version changing can i be assured that you'll keep up to date your packages (with latest tagged sqlmap)? also, which version increment do you take into account. major, minor, development revisions???

**Comment by offensive-security** [comment]
Our current system polls the default git repository and checks for release tags. On every updated tag that is reported, we trigger a build on our side, which then gets pushed to our kali-rolling repositories. This would be a much better solution that we have now with your project, which is just randomly taking git snapshots every so often to keep sqlmap current. This way, you could control when you consider something to be release worthy, and when not. Essentially, we would like to hand the control of when  an updated snapshot of sqlmap should be pushed to Kali, to your side.

**Comment by stamparm** [comment]
After a short internal discussion we decided to release the official v1.0 at January 2016. After that tagging will be done regularly.

**Comment by stamparm** [comment]
`This way, you could control when you consider something to be release worthy, and when not. Essentially, we would like to hand the control of when an updated snapshot of sqlmap should be pushed to Kali, to your side` <- every commit is important in sqlmap :)

**Comment by offensive-security** [comment]
Thanks for the update, and the good news! 
Every project has a different development culture, and no two projects are alike. Tagging is the one constant that allows the world to understand "this version is release worthy"... which is what we look for in a distribution. If you feel every commit is important, by all means, tag minor versions as well, such as v0.9999980. All this does is say that your commits are not partial, and the tool / project is functional at a given state.

Thanks again for the update - and on a personal note, thanks for your awesome tool.

**Comment by stamparm** [comment]
@offensive-security please take a look into https://github.com/sqlmapproject/sqlmap/issues/1765#issuecomment-197951156

**Comment by stamparm** [comment]
p.s. from this moment there will be automatic tagging of first commit in the month :)
