### ISSUE TITLE
Downloading a table when the pivot don't get all

### ISSUE THREAD

**Issue by rodrigozanatta** [sqlmapproject/sqlmap#1545]
When you try to get a table, the sqlmap use

DISTINCT(COUNT(columnName))

But, what happens when NONE column have the exact number of distinct in the table? Well, it will NOT download all data. How solve it?

Why not use more than one column? And it worked for me. If I use:

DISTINCT(COUNT(SELECT (CAST(columnName AS VARCHAR(4000))+CHAR(100)+(CAST(secondColumn AS VARCHAR(4000))  )))

You can use more columns as pivot until it get all elements.

In the select, I just get the two column plus more data and use it as a pivot. You can use some good logic, but the idea is it.

**Comment by stamparm** [comment]
I'll just leave here also your comment on ML:

http://sourceforge.net/p/sqlmap/mailman/sqlmap-users/?viewmonth=201511&viewday=14

**Comment by rodrigozanatta** [comment]
a final coment. the LTRIM(RTRIM())  was my error. I was having bad times with string encoding, but I did see a (stupid) function that give-me a lot of headache. 

This work really great for me. I just concatenate various column as pivot and use the previous value to get the next. With it I can get 100% of line in table where a pivot with one column don't work.

**Comment by stamparm** [comment]
Revisiting this issue. More than one columns as a pivot doesn't make any sense. Pivoting with one column is easy and works. Pivoting with more than one columns would require either A) multiple comparison in a single query or B) comparison of concatenated columns with concatenated pivoting values.

Also, dummy `DISTINCT(COUNT(SELECT (CAST(columnName AS VARCHAR(4000))+CHAR(100)+(CAST(secondColumn AS VARCHAR(4000)) )))` doesn't return anything meaningful without a modification in row retrieval mechanism (too).
