### ISSUE TITLE
Path concat invalid for windows

### ISSUE THREAD

**Issue by steelbrain** [sqlmapproject/sqlmap#1557]
```
[15:02:12] [INFO] retrieving MySQL plugin directory absolute path
[15:02:12] [INFO] resumed: [[u'C:\\Program Files (x86)\\Parallels\\Plesk\\Databases\\MySQL51\\lib/plugin']]...
```
^ notice the invalid slash at the end for plugin

**Comment by stamparm** [comment]
Which revision you've used?

**Comment by steelbrain** [comment]
I am using the master branch

**Comment by stamparm** [comment]
That what you see in `resumed` is a valid result coming from MySQL installation on Windows. Here is an example query output coming from one such installation:

![mysql_plugin_dir](https://cloud.githubusercontent.com/assets/921555/11332610/72b0676c-91c7-11e5-99f7-6a5c75e74673.png)

Nevertheless, I've made a related patch (it will not change your message) that should make this more stable
