### ISSUE TITLE
Help enumerating tables(maybe WAF issue?)

### ISSUE THREAD

**Issue by projex** [sqlmapproject/sqlmap#1571]
Using:
`sqlmap.py -r xxx.txt -p yyy -D zzz  --tables -v3`

Requests are being dropped when `-1 OR ORD(MID((SELECT IFNULL(CAST(COUNT(table_name) AS CHAR),0x20) FROM INFORMATION_SCHEMA.TABLES WHERE table_schema=0xabcd),1,1))>51` is sent. I played around with the requests and I found out that the hex value `0xabcd` was causing the errors.

Can anyone suggest solutions/alternatives? I checked the tamper scripts but I haven't found anything that would help :cry:

**Comment by stamparm** [comment]
And how is this a sqlmap issue? You can try --no-escape, but I would not be
optimistic

**Comment by projex** [comment]
That didn't work.

Can you give me any ideas on how to enumerate tables another way without bruteforcing them?
Or maybe an idea for a tamper script? I'll write it.

**Comment by stamparm** [comment]
That is your work to do. Closing this down
