### ISSUE TITLE
Headers added when using -r

### ISSUE THREAD

**Issue by jeroen-80** [sqlmapproject/sqlmap#1578]
I'm testing a web service that is not using some commonly seen headers like User-Agent. When using the -r option (./slqmap.py -r replay.txt) a number of headers is added to the original request. This causes the target server to refuse the request ('unknown headers found'). I was expecting that sqlmap was just passing headers and not inserting new ones. Is this assumption incorrect or is it a bug? Data:

Original header (saved in replay.txt):

POST /**removed** HTTP/1.1
MIME-Version: 1.0
Content-Type: multipart/related; type="application/xop+xml";start="<http://tempuri.org/0>";boundary="uuid:e5db47e8-23b8-447e-b4e1-5289afe3a758+id=12";start-info="application/soap+xml"
InstanceId: d072886c-c4d7-4560-911d-5d293c6ccc77
Host: **removed**:443
Content-Length: 6550
Expect: 100-continue

Headers seen when sqlmap sends out its first request:

POST /**removed** HTTP/1.1
Content-Length: 6535
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip,deflate
InstanceId: d072886c-c4d7-4560-911d-5d293c6ccc77
Host: **removed**:443
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: sqlmap/1.0-dev-80d3ff6 (http://sqlmap.org)
Accept-Charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7
Connection: close
Expect: 100-continue
Pragma: no-cache
Cache-Control: no-cache,no-store
Content-Type: multipart/related; type="application/xop+xml";start="<http://tempuri.org/0>";boundary="uuid:e5db47e8-23b8-447e-b4e1-5289afe3a758+id=12";start-info="application/soap+xml"
MIME-Version: 1.0

Thanks,

Jeroen

**Comment by stamparm** [comment]
Your Host header value is a total junk. I would point my finger on it

**Comment by stamparm** [comment]
If you just removed the value of Host for obfuscation purposes, I would ask
you to help and pinpoint which header was a problem here. Just out of
curiosity.

I'll make sure that sqlmap doesn't send unnecessary headers like in your
case

**Comment by jeroen-80** [comment]
sqlmap header - original header =

Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip,deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,/;q=0.8
User-Agent: sqlmap/1.0-dev-80d3ff6 (http://sqlmap.org)
Accept-Charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7
Connection: close
Pragma: no-cache
Cache-Control: no-cache,no-store

**Comment by stamparm** [comment]
@jeroen-80 python enforces couple of header values on its own (no matter if sqlmap provides it).

To be exact: `User-Agent`, `Connection` and `Accept-Encoding`

Here would be great to know the answer to my previous asked question: `I would ask you to help and pinpoint which header was a problem here`

**Comment by stamparm** [comment]
@jeroen-80 please try to rerun with the latest revision. I am afraid that those 3 will need to stay

**Comment by stamparm** [comment]
@jeroen-80 ping? have you tried the latest revision?

**Comment by jeroen-80** [comment]
In the version I initially used the following headers were added to the saved request:

Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip,deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,/;q=0.8
User-Agent: sqlmap/1.0-dev-80d3ff6 (http://sqlmap.org)
Accept-Charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7
Connection: close
Pragma: no-cache
Cache-Control: no-cache,no-store

After an update some but not all extra headers removed:

Accept-Encoding: identity
User-Agent: sqlmap/1.0-dev-7517e64 (http://sqlmap.org)
Connection: close

So the update seems to be doing what you're describing (not removing User-Agent, Connection and Accept-Encoding). Please note that the content of Accept-Encoding changed.

<quote>I would ask you to help and pinpoint which header was a problem here</quote>
It seems that sqlmap / Python is added the three headers as soon as not all three are set. I've checked some older testdata. In all samples the User-Agent is set, in most the Accept-Encoding, in some the Conection header. However the main difference between this case and all others I've used before is that the backend spits out http 400's in case of too many headers: all other backends didn't care.

**Comment by stamparm** [comment]
`Please note that the content of Accept-Encoding changed` <- i am fully aware of this. Using `Accept-Encoding: identity` is safer than original. Also, its the defacto standard in case of missing `Accept-Encoding` header value
