### ISSUE TITLE
Data Retrieve are Invalid Characters

### ISSUE THREAD

**Issue by elvinguitar** [sqlmapproject/sqlmap#1580]
I'm wondering why the database that I retrieve is not readable and contains invalid characters. 

![untitled](https://cloud.githubusercontent.com/assets/16131223/11555438/31733240-99db-11e5-9cb1-39d4fe33c4bb.png)

**Comment by stamparm** [comment]
False positive (time-based SQLi is prone to this). Please rerun with `--flush-session`.

**Comment by stamparm** [comment]
@elvinguitar just in case. Do you get junk for also the `--banner`?

**Comment by elvinguitar** [comment]
@stamparm I tried --banner and --flush-session but unfortunately I'm still getting junked/invalid characters.

**Comment by stamparm** [comment]
Can you please send a screenshot of: python sqlmap.py -u....
--flush-session --banner --time-sec 10

**Comment by elvinguitar** [comment]
@stamparm here's the screenshot using `<sqlmap -u http://website.com/ --data="Country=US&Language=EN" -p Country --level=5 --risk=3 --flush-session --dbms=mysql --banner --time-sec 10>`

![capture](https://cloud.githubusercontent.com/assets/16131223/11650975/45564de2-9dc8-11e5-974d-fa02fbf4e044.PNG)

**Comment by stamparm** [comment]
I've asked for `python sqlmap.py -u.... --flush-session --banner --time-sec 10`, not `--level=5 --risk=3 --dbms=mysql`.

Also, which version do you use?

**Comment by elvinguitar** [comment]
Sorry about that. Anyway, I'm still getting the same result when using `<sqlmap -u http://www.website.com/ --data="Country=US&Language=EN" -p Country --flush-session --banner --time-sec 10>`

I'm using version 1.0-dev-nongit-20151123

![capture](https://cloud.githubusercontent.com/assets/16131223/11651486/00b9fa18-9dcc-11e5-975d-84570ba5fcc5.PNG)

**Comment by stamparm** [comment]
Can you please do the following:

```
cd /tmp
git clone https://github.com/sqlmapproject/sqlmap.git
cd sqlmap
python sqlmap.py -u .... --flush-session --banner --time-sec 10
```

Also, if this continues, I can only guess that something is messing the results. In that case, please send me more details (privately) to `miroslav@sqlmap.org`
