### ISSUE TITLE
How would I change this url so that it's accepted by sqlmap?

### ISSUE THREAD

**Issue by Snipercatz** [sqlmapproject/sqlmap#1586]
How would I change this url so that it's accepted by sqlmap?  Obviously sqlmap is not going to take the ''' and '"' characters.  Thanks for your help.

http://targeturl.com/forums/1'"(Restricted-Posting)_c11/

**Comment by stamparm** [comment]
First of all, please don't use such characters in sqlmap provided URLs, especially if they are NOT VALID application input. sqlmap requires valid data (not some random giberish).

If that's really a valid part of URL (which I doubt), you can provide it to sqlmap (if using bash):
```
python sqlmap.py -u http://targeturl.com/forums/1\'\"\(Restricted-Posting\)_c11/
```
