### ISSUE TITLE
Pause feature

### ISSUE THREAD

**Issue by ghost** [sqlmapproject/sqlmap#159]
A useful feature would be "Pause" command. Sometimes you need to disconnect for a while and it would save you some time if you could just pause, wait for the threads to finish and resume later instead of running sqlmap all over again because it stops from all the connection errors.

**Comment by squarefractal** [comment]
@stamparm
Would it be possible to trap a specific signal and have that act as the pause functionality? For example, one could send `kill -s $SIGNAL $sqlmap_pid`, which would be handled by sqlmap to pause its activity.

**Comment by stamparm** [comment]
@squarefractal no OS independent. Also, signal handler(s) would just break out of the current thread's block (no way to go back)

**Comment by xShahRukh** [comment]
you can try doing it with process hacker to pause the process

**Comment by SweetSoul** [comment]
What If sqlmap handle the situation doing a sleep defined by the user? Something like the next parameter but before it goes to the next param it sleeps for X seconds

**Comment by xShahRukh** [comment]
@SweetSoul  There is --delay=DELAY       Delay in seconds between each HTTP request

**Comment by SweetSoul** [comment]
The topic is about pausing the sqlmap, what in the world lead you to think that i want delay the reqs?

**Comment by xShahRukh** [comment]
you typed 

> before it goes to the next param it sleeps for X seconds

for pausing i already said... you can use process hacker. 
You can right click on the python.exe and click on suspend.
And then Click on resume at what time you want to resume it.

**Comment by fredhagedorn** [comment]
Yeah, when I want pause anything in sqlmap, I always do ctrl + z and in terminal. Then &&. Its quite simple.
