### ISSUE TITLE
data retrieving problem

### ISSUE THREAD

**Issue by ashee69** [sqlmapproject/sqlmap#1609]
hello team,
i'm having a MSSQL database here.
on issuing --count it give count for a table say 'customers'
and when i try to --dump there comes 0 entries.
i tried with --dbms-cred too (i put username:password of admin which i got from this very db ) but still no entries.
this may the problem i guess
[14:44:53] [WARNING] no proper pivot column provided (with unique values). It won't be possible to retrieve all rows

how could i overcome with this ?

and some more questions 
if i have url with multiple parameters then how i could i specify the parameter in sqlmap
like if i have this url
site.com/item.asp?par1=val1&par2=val2&par3=val3
i m getting error in par1 and par2
if i start with whole url sqlmap shut down.

another question is that
is there any way to fingerprint a WAF on the site ?
with http responses or cookies we can get clear idea about the WAF then we can use specific tamper scripts.
i used to put all DBMS specific tamper scripts so the URI becomes too long.

please suggest me any tutorial about WAF bypassing because i feel today no site is there which is not behind WAF.

                                                                                                              --thanking you

**Comment by stamparm** [comment]
1) you can try to force the "pivot column" to some (good looking) column name (from the same table you are trying to dump). For example, `--pivot-column=id`.
2) you must enclose URLs containing character '&' with quotes (e.g. `-u "site.com/item.asp?par1=val1&par2=val2&par3=val3"`)
3) you can try to identify WAF by using `--identify-waf`. In lots of situations you won't be able to easily fingerprint it. If sqlmap is not able to fingerprint it and you know the obvious "trails" (e.g. cookie names or specific HTML responses), then please share. I'll gladly add a new `waf` script
4) no good tutorials. bypassing WAFs is hard nowadays. if you don't have complete picture of what is being filtered/blocked (e.g. by manually testing what can ) you won't be able to bypass it. sometimes this requires couple of hours of work if its doable and if its being done by someone that really knows majority of ways how it could be done (please read all tamper scripts to get the basic knowledge)

**Comment by ashee69** [comment]
i'm sorry that i'm replying here. because it's noob question.i face with this problem frequenty.


[19:54:36] [WARNING] multi-threading is considered unsafe in time-based data retrieval. Going to switch it off automatically
[19:54:36] [WARNING] it's highly recommended to avoid usage of switch '--tor' for time-based injections because of its high latency time
[19:54:36] [WARNING] time-based comparison requires larger statistical model, please wait..............................
[19:55:28] [INFO] heuristics detected web page charset 'ascii'
[19:55:28] [WARNING] it is very important not to stress the network adapter during usage of time-based payloads to prevent potential errors 
then...it retrieves data super slowly. is there anyway to speed it up. i tried hex/no-cast but no improvement.
 


    On Tuesday, 15 December 2015 3:38 PM, Miroslav Stampar <notifications@github.com> wrote:
 

 Closed #1609.—

**Comment by stamparm** [comment]
`then...it retrieves data super slowly. is there anyway to speed it up. i tried hex/no-cast but no improvement.`
-> its a time-based SQL injection. No (normal) way to speed it up. I would suggest to skip such targets if its too long for you to wait
