### ISSUE TITLE
Prefix and suffix does not work as expected

### ISSUE THREAD

**Issue by cdaller** [sqlmapproject/sqlmap#1613]
I have a parameter that looks like `foo%FFbar%FFbaz`. The application parses the param and splits the value by `%FF`. Only the first part of the param is injectable, the later must not be changed.
I used `--prefix=foo`and `--suffix="%FFbar%FFbaz` and expected that sqlmap will append the payload to `foo` (resulting in something like `foo or 1=1%FFbar%baz`).

But the result was like
```
[INFO] testing 'AND boolean-based blind - WHERE or HAVING clause (Generic comment)'
[14:48:17] [PAYLOAD] foo%FFbar%FFbazfoo AND 5985=2501%FFbar%FFbaz
```

This results in the application parser always extracts `foo` and will never read the real payload.

What is wrong in my usage of prefix and suffix?

**Comment by stamparm** [comment]
This was a bug fixed a month ago. Which revision do you use?

![3333](https://cloud.githubusercontent.com/assets/921555/11901332/65034772-a5ab-11e5-973f-2cf2d752fb1d.png)

**Comment by stamparm** [comment]
p.s. this should be the proper behaviour (as in above picture). right after the original value `prefix` is prepended just before the payload and `suffix` is appended just after the payload

**Comment by stamparm** [comment]
@cdaller ping?

**Comment by cdaller** [comment]
Hi,

Probably I did not use the latest version. I will test on Monday. Do not have access to a computer before. But seems to be solved!

Thanks for your quick reaction!

Cheers
Christof 

--
Christof Dallermassl
christof@dallermassl.at

**Comment by cdaller** [comment]
> p.s. this should be the proper behaviour (as in above picture). right after the original value prefix is 
> prepended just before the payload and suffix is appended just after the payload

The problem is that the original value is always used as first part in the parameter value. In my case the original param `foo%FFbar%FFbaz` must not be used as part of the payloaded parameter as otherwise the parser in the application only uses the first `foo` in the sql. Everything else will not be used. Like this, the sqlmap payload will never be inserted into the sql query by the application.

I would like to send only the payload without using the original parameter. But when trying with an empty param I get the warning 

`
[10:02:10] [WARNING] provided value for parameter 'TT_PARAMETER1' is empty. Please, always use only valid parameter values so sqlmap could be able to run properly
`

I would something like `--skip-original-param` (bad param name, but cannot find a better one!)

I am using the latest git version now: 1.0-dev-ae74810

**Comment by stamparm** [comment]
@cdaller now i am confused. I believe that you can do everything with current option set.

You want `foo%FFbar%FFbaz` to be used as an original value, but not used as an original value. Then you want `foo` to be used as an original value, but not used as an original value.

**Comment by cdaller** [comment]
I only want as parameter value `foo<payload>%FFbar%FFbaz`. What I get now is `foo%FFbar%FFbazfoo<payload>FFbar%FFbaz` as the original param is always added as first part of the param value.

**Comment by stamparm** [comment]
Original value will always be prepended to the prefix/payload/suffix in case of SQLi payloads that require this (e.g. for AND boolean based blind). That's by the definition. In case of parameter replacement it will be completely replaced by (prefix/payload/suffix). In case of OR boolean based and partial union it will be negated.

**Comment by stamparm** [comment]
p.s. I still think that you overcomplicate something here. There won't be a new option here for sure.
