### ISSUE TITLE
How to POST "html characters" with SQLMAP

### ISSUE THREAD

**Issue by iwantaturboman** [sqlmapproject/sqlmap#1629]
Hi all,
for testing purposes, i need to test a sql vulnerabity in a website.
A script named "cart.asp" contains a vulnerable field which name is "Quantity".
The submit form is called ">> Send My Request" on page ; BUT the same form is written differently on page source code due to ">" character.
So, i would like to know how to write my sqlmap request 
sqlmap.py -u http://www.url.com --data "Quantity=1&submit=>> Send My Request" --current-db
or
sqlmap.py -u http://www.url.com --data "Quantity=1&submit=(same syntax with HTML characters) --current-db

Thanks for the help.

**Comment by stamparm** [comment]
Safest way is to use some MiTM proxy (e.g. Burp) and take a look into one regular request.

Nevertheless, I think that the proper command should be (in your case):

`sqlmap.py -u http://www.url.com --data "Quantity=1&submit=%3E%3E%20Send%20My%20Request" -p Quantity`

**Comment by iwantaturboman** [comment]
Thanks for this. I will try.
Regards,
