### ISSUE TITLE
not sure what this is, but its annoying

### ISSUE THREAD

**Issue by plaguewolf** [sqlmapproject/sqlmap#1631]
installed sqlmap from git, made bash script in /usr/local/bin to launch it from path, launched, and it does weirdness, drops from shell, but still keeps running

![screenshot at 2015-12-30 02 23 20](https://cloud.githubusercontent.com/assets/7838485/12048175/252f9c22-ae9d-11e5-85ba-aabb729c3d6f.png)

EDIT: also, connection timeout...

**Comment by plaguewolf** [comment]
nm, fixed it. stupid me, bash file was wrong

**Comment by stamparm** [comment]
:)
