### ISSUE TITLE
Web vulnerability scanner and sqlmap request

### ISSUE THREAD

**Issue by iwantaturboman** [sqlmapproject/sqlmap#1638]
Hi all,
for security testing purposes, i've scanned a website with the help of a WVS (Web Vulnerability Scanner). It finds a BLIND SQL Injection.
Scanner log says : URL (http://www.mywebsite.com/folder/mypage.php) encoded GET input *id* was set to : <code>if(now()=sysdate(),sleep(0),0)/*'XOR(if(now()=sysdate(),sleep(0),0))OR'"XOR(if(now()=sysdate(),sleep(0),0))OR"*/</code>

I would like to know some more about this, so i tried to test *id* parameter with sqlmap with this command line : 
<code>sqlmap.py -u http://www.mywebsite.com/folder/mypage.php?id=* --current-db --threads=5 --level=5 </code>
But, sqlmap found that *id* parameter was not injectable.
Maybe my sqlmap request doesn't correspond to the scanner payload ?
If this is the case, there is any way to inject directly that payload <code>if(now()=sysdate(),sleep(0),0)/*'XOR(if(now()=sysdate(),sleep(0),0))OR'"XOR(if(now()=sysdate(),sleep(0),0))OR"*/</code> on *id* parameter with sqlmap ? If yes, how ?
Thanks for your help.
Regards,

**Comment by stamparm** [comment]
1) You should put valid value into id while running in sqlmap (e.g. `sqlmap.py -u http://www.mywebsite.com/folder/mypage.php?id=1`)
2) I would say that you are dealing with a false positive (time-based SQLi) with rather uncoventional payload

**Comment by iwantaturboman** [comment]
Thanks for your help, stamparm.
