### ISSUE TITLE
Microsoft Access and sqlmap

### ISSUE THREAD

**Issue by iwantaturboman** [sqlmapproject/sqlmap#1646]
Hi again,
for educational purposes, i'm working in some ways to POST data in sqlmap.
With the help of Burp Suite (Free Edition), i must admit it's easier.
In my case, i have found a vulnerability in a parameter called "email".
After capturing "post data" in a text file, i try this command line : 
<code>sqlmap.py -r postdata.txt -p email --current-db --threads=5</code>
Sqlmap found that "email" is vulnerable but i'm surprised about log results : 
<code>[WARNING] on Microsoft Access it is not possible to get name of the current database
current database:       None</code>
Could it be a FALSE positive ?
I tried also with <code>--dbms="Microsoft Access"</code> but without success.
Thanks for the help.
Regards,

**Comment by stamparm** [comment]
Microsoft Access is one big file. There are no "current database"(s) there.

This just means that you can't use `--current-db` on Microsoft Access

**Comment by iwantaturboman** [comment]
Still learning. Thanks again. Closed.
