### ISSUE TITLE
Problem with Microsoft SQL.

### ISSUE THREAD

**Issue by Tardis07** [sqlmapproject/sqlmap#1659]
When I dump a database from Microsoft SQL server, It can not save the csv with correct name. For example, "dbo.出入港入库" will be saved as "_____-acb90cf2.csv". I've already tried different kind of CHARSET, but it doesn't work. Is this a bug of the program?

**Comment by stamparm** [comment]
This is not a bug. You can't expect everyone to have a support for storing `出入港入库.csv` kind of files. Also, not all filesystems support this. sqlmap just filters non-ASCII chars in output filenames to prevent trashing of user filesystem space

**Comment by stamparm** [comment]
@Tardis07 now sqlmap will try to create appropriate database/table in ORIGINAL form and afterwards fallback to the neutralization of problematic characters
