### ISSUE TITLE
Ignore CTRL-C when in a meterpreter session

### ISSUE THREAD

**Issue by steelbrain** [sqlmapproject/sqlmap#1664]
It produced unexpected results with both the meterpreter and sqlmap. I expected it to terminate the command I'd run in meterpreter.

**Comment by stamparm** [comment]
With the latest commit 4458a44:

![current](https://cloud.githubusercontent.com/assets/921555/24498942/67c97cc8-1540-11e7-89ad-9e7ceadd9791.png)
