### ISSUE TITLE
Microsoft Access Comments

### ISSUE THREAD

**Issue by AresS31** [sqlmapproject/sqlmap#1665]
When running sqlmap with the --dbms="Microsoft Access" parameter, sqlmap first test all the payloads using the Generic comments. 
In my opinion this is just a waste of time and processing power since the user already defined the target dbms and we know for sure that we need to comment with %16 or %00.
Therefore, I suggest to simply discard all the steps involving the Generic comments, it will save the life of a lot of people who are using the --level 5 parameter. 
Best regards,
Alexandre

**Comment by stamparm** [comment]
Generic comments are now replaced with MsAccess %16 in those kind of cases
