### ISSUE TITLE
Binary datatype retrieval with MYSQLv.4

### ISSUE THREAD

**Issue by AresS31** [sqlmapproject/sqlmap#1666]
I am trying to dump a table and in this table there are binaries entries. 
After investigations, I saw that the usual workaround is to use --hex. However, when working on an MYSQL database version 4.1 the --hex feature is not implemented yet.
Does anyone have a custom script or an idea on how to solve this issue?
Best regards,
Alexandre

**Comment by stamparm** [comment]
I am closing this down (nobody has any practical ideas)
