### ISSUE TITLE
WAF dropping parentheses during test phase

### ISSUE THREAD

**Issue by worldvision2003** [sqlmapproject/sqlmap#1668]
I have a particular site with a built-in WAF that drop the connection when there are parentheses in the URL, but this only happen during the sqlmap tests phase.

Ex.:
index.php?id=123 and 1=1 			        [OK]
index.php?id=123 and 1=2 			        [OK]
index.php?id=123 and (select 2)=2 		[OK]
index.php?id=123 and chr(61)=chr(61) 		[OK]
index.php?id=123) and 4353=4353 and (9796=9796 	[WAF DROPS CONNECTION]
index.php?id=123) and 8902=5677 and (1062=1062 	[WAF DROPS CONNECTION]

Have any way to skip payloads with parentheses, during the sqlmap tests phase?
I already did with --prefix=123, and even a tamper replacing the parentheses in the payload, but without success.

**Comment by stamparm** [comment]
If parentheses are dropped then you'll have a hard time doing any data dumping (subqueries required). Hence, the answer is no.

**Comment by worldvision2003** [comment]
Please take a look at this

WAF may ignore this:
http://www.eloimendes.mg.gov.br/cont_pag11.asp?pag=125+and+(select+count(email)+from+acesso)+between+0+and+10

WAF may drop this:
http://www.eloimendes.mg.gov.br/cont_pag11.asp?pag=125)+and+4353+like+4353+and+(9796+like+9796

Maybe a parameter like "--type=single quote|double quote|integer" could
help in cases like this. Any solution?
Thanks in advance



2016-01-16 22:42 GMT-02:00 Miroslav Stampar <notifications@github.com>:

**Comment by stamparm** [comment]
I don't see a pattern here. I can only suggest for you to take a look into `--prefix` and `--suffix` to fulfil your idea of restraining prefix and suffix for used SQLi payloads

**Comment by worldvision2003** [comment]
I solved it using --suffix, thanks for attention
