### ISSUE TITLE
sqlmapapi  zombie process and Broken pipe 

### ISSUE THREAD

**Issue by dozysun** [sqlmapproject/sqlmap#1676]
our app use sqlmapapi -s run server,  with max 200 concurrent to visit the server it lead a lot of broken pipe  and indirectly lead zombie process in memory,   i find out that  bottle server  support variety of server   adapter  but sqlmapapi only use the default one wsgiref which is limit on concurrent, so i suggest sqlmapapi add a option  --servername  to support the server adapter name that bottle support  and  also should modify api.py  /task//delete , /admin//flush which just reset the DataStore.task, dosen't clean the subprocess yet, it may lead zombie too .
 i'm sorry for my bad english, hope you guys can understand these sentence, 
 i have change the sqlmapapi source already  do i need to send a pull request?

**Comment by stamparm** [comment]
You can do the pull request or you can send it directly to `miroslav@sqlmap.org`

**Comment by stamparm** [comment]
`delete` is for task deletion, `kill` is for deletion and cleaning of started subprocess. Hence, there is no need for change there.

Also, `flush` should be used to `delete` all

Now, there are two ways to deal with this issue:

either 1) leave `delete` and `flush` as they are, and introduce `killall` to do the `flush` and task killing
or 2) remove `delete` and `flush` and stick with `kill` and (e.g.) `killall` (or `flush`)

**Comment by dozysun** [comment]
i think if you want to delete the task you also want to kill the task's subprocess since  it' not useless for me and  may lead zombie    , delete or flush method not only to delete task  but also need to kill the task's subprocess which is running .  according to task.process.returncode to judge if the subprocess need to kill ,

**Comment by dozysun** [comment]
yeah, plan A very good , i should add another api  to do the delete and kill thing, i'll send a pull request later

**Comment by stamparm** [comment]
`flush` now also kills everything (like you wanted originally)
