### ISSUE TITLE
--eval doesn't work for XML parameters. 

### ISSUE THREAD

**Issue by awhitehatter** [sqlmapproject/sqlmap#1679]
The eval flag will not work with XML parameters (unless I'm mistaken). 

My request looks like:

``` xml
POST /server HTTP/1.1
[general headers]

<?xml version="1.0" encoding="UTF-8"?>
<note>
  <to>Tove</to>
  <from>Jani</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
</note>
```

and if I run something like `sqlmap.py -r request --eval="body=1"`, SQLmap just appends `&body=1` to the end of the request. 

Like so:

``` html
POST /server HTTP/1.1
[general headers]

<?xml version="1.0" encoding="UTF-8"?>
<note>
  <to>Tove</to>
  <from>Jani</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
</note>&body=1
```

**Comment by stamparm** [comment]
You are right. Haven't implemented it (nobody asked until now :)

I'll implement when I catch time

**Comment by awhitehatter** [comment]
@stamparm Awesome, thank you very much!
