### ISSUE TITLE
Oracle DBA False positive?

### ISSUE THREAD

**Issue by dorsec** [sqlmapproject/sqlmap#1680]
I'm running the following command (scrubbed of course):
/opt/sqlmap/sqlmap.py -r InterestingRequest.txt --level=5 --risk=3 -v 3 --time-sec=10 -p "InterestingParameter" --all --random-agent

I'm running checks against 4 individual injection points returned by sqlmap as injectable. I don't get any results back for things like the database, tables, etc. I do get back the following:

current user: '?'
current schema: '?'
hostname: None
current user is DBA: True

Is the DBA is false positive?

I have also done the --sql-shell option and gotten the shell, but no query performed returned any results including queries to return the schema and tables out of Oracle. I feel like this is injectable but something is not quite right. Thoughts?

**Comment by dorsec** [comment]
I have also run the same command above using every tamper script and received the same results for every single one of them.

**Comment by stamparm** [comment]
False positive. Please rerun with `--flush-session`
