### ISSUE TITLE
How to extract data to a specific name.csv file ?

### ISSUE THREAD

**Issue by iwantaturboman** [sqlmapproject/sqlmap#1682]
Hi, official documentation of sqlmap doesn't tell how to chose a specific name for a dump/extracted data. 
I tried with (and other command lines) without success : 
<code>sqlmap.py -u myurl.com -D database -C user,city,phone --dump users.csv</code>

Thanks for the help.

**Comment by shadowfolder** [comment]
command --dump just doing dump, not dump in specific filename) the file what you dumping will be the name of table what you dumping

**Comment by iwantaturboman** [comment]
So, any command exists to specify a file target ; something like <code>--filename=users.csv</code> ?
Regards.

**Comment by stamparm** [comment]
Nope. You are probably the first one to ask this in ten years. Everybody else are ok with the current approach. I'll need to close this one down
