### ISSUE TITLE
problem with dump chinese password

### ISSUE THREAD

**Issue by amirmagic** [sqlmapproject/sqlmap#1688]
hi friends , i have a issue and that is i've inject a website with sqlmap and when i try to dump password unfortunately i can't dump correct password filed . ( but my target is arabic and site language arabic )

for example : 
+-------+-----------+------------------------------------------+
| U_id  | U_Name    | U_Password                               |
+-------+-----------+------------------------------------------+
| O0007 | adeela    | ????????\x01\x00????????????????         |

i look into csv output file and i watched this : 
U_id,U_Name,U_Password
U001,Admin,阀ᦚ诡䟥亅鐢盖隃\x01\x00₧罔⻋괇꼼ꇐ먡❫�汥覰ﻧ宾ᖘ�

now i try to use a few trick like : --dump-type=HTML or use tamper like unicode or i set --charset into sqlmap but not one of them can usefull for me !!! please help me for fix this problem .

thanks dude

**Comment by amirmagic** [comment]
oh one more thing ! i'm sorry for my weakness in my language ;) :x

**Comment by stamparm** [comment]
It seems to be the binary hash dump. Please rerun with `--fresh-queries --binary-fields=U_Password`

**Comment by amirmagic** [comment]
@stamparm ok dude thanks for your helping ! i'm dumping data with ( --fresh-queries --binary-fields=U_Password ) and show me data like this : 0x00969a19e18be547854e2294d676839601000000a679bed505bc3a665c5f114e66b10da98edc503fe6aa4fe54cac9e03ea94d231 now i have a question !!! ? this code isn't "binary code" ! how can i decode this data ?! thanks ! * i know this problem isn't connected to sqlmap ! please help me ! thanks

**Comment by stamparm** [comment]
This code isn't "binary code" :)

No comment

**Comment by h3llboy** [comment]
@amirmagic my dear friend any data has been stored in database base on binary code ok ?
and now i have another question from @stamparm a few days ago a have a issue same as this , and i can't decoded like this data . :D so i greatful to you please explain how to decode data like this ?
best regards

**Comment by stamparm** [comment]
@h3llboy this looks like a custom binary format. sqlmap provided you with the hexadecimal representation (you can use python like: `data.decode("hex")` to decode it) but sqlmap can't guess what standard admins used to store their binary hashes

**Comment by h3llboy** [comment]
haaa thanks a lot :-* so i guess you can close this issue ( because with your answer @amirmagic can be solved the problem ) .

thanks again ;)
