### ISSUE TITLE
Question How to specify dynamic fields in a complex POST payload

### ISSUE THREAD

**Issue by Dynom** [sqlmapproject/sqlmap#1694]
Hi,

I'm testing my own webservice for vulnerabilities, but I'm having difficulties to specify what to test with sqlmap. My service uses the [JSON-RPC](http://www.jsonrpc.org/specification) protocol for communication and sqlmap can't identify the dynamic fields. 

To give an example, this is what a payload looks like:
```
{"jsonrpc":"2.0","method": "product.searchByName" ,"id":1,"params":[ "ecs-10 blaster", 40 ]}
```
The dynamic fields here are the elements in `params`. The rest are static. They represent:

0. The query to search on (string)
0. The limit (numerical)
 

This is a command I tried:
```
python sqlmap.py -u http://172.17.8.101:3006 -a -f --headers="Content-Type: application/json" --data='{"jsonrpc":"2.0","method": "product.searchByName" ,"id":1,"params":[ "ecs-10 blaster" ]}' --dbms=pg --risk=3 --level=5
```
But none of the automatically identified fields seemed dynamic, which I get as it's pretty much impossible to figure out without a (format) description.

So how can I specify what element to define dynamic?

**Comment by stamparm** [comment]
Please try:

`...{"jsonrpc":"2.0","method": "product.searchByName" ,"id":1,"params":[ "ecs-10 blaster*", 40* ]}...`

p.s. not the usage of custom injection mark `*`

**Comment by Dynom** [comment]
Excellent! It works quite nicely. However I'd like to influence the escaping a bit. Since the payload is wrapped in double-quotes, the quotes within the payload need to be extra escaped. Is there a way to accomplish that?

One of the payloads is, for example:
```
{"jsonrpc":"2.0","method": "product.searchByName" ,"id":1,"params":[ "-7768") AS Hwkt WHERE 8949=8949 UNION ALL SELECT 8949,8949,8949,8949,8949,8949,8949,8949-- -", 1 ]}
```

Where it should be:
```
{"jsonrpc":"2.0","method": "product.searchByName" ,"id":1,"params":[ "-7768\") AS Hwkt WHERE 8949=8949 UNION ALL SELECT 8949,8949,8949,8949,8949,8949,8949,8949-- -", 1 ]}
```

I've seen flags to disable escaping, but I kinda need the opposite.

**Comment by stamparm** [comment]
Please update to the latest revision and retry with `...--tamper=escapequotes`

**Comment by Dynom** [comment]
Excellent, thanks!
