### ISSUE TITLE
Database without tables ?

### ISSUE THREAD

**Issue by iwantaturboman** [sqlmapproject/sqlmap#1695]
Database without tables

Hi all,
i found a vulnerability in a website.
For the same injectable parameter, 2 attacks are possible : 
Type: boolean-based blind
Title: AND boolean-based blind - WHERE or HAVING clause
Type: error-based
Title: MySQL >= 5.1 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (EXTRACTVALUE)
I just found a database (db01) but sqlmap isn't able to find any table on.
I even tried with "**common table existence check**" without success.
Same result with : `--no-cast` and `--no-hex` options.
No WAF either as `--identify-waf` gives [WARNING] no WAF/IDS/IPS product has been identified.
Command` --banner` shows :
```
web application technology: Apache 2.2.29, PHP 5.4.42
back-end DBMS: MySQL 5
banner:    '5.5.47-cll'
```
I'm a bit lost cause i'm sure that db01 contains some tables.
Thanks for your help

**Comment by stamparm** [comment]
Please rerun everything with --parse-errors and report if you see any new WARNINGS.

Also, please rerun with -D...  --tables --fresh-queries -t traffic.txt and send resulting traffic.txt to miroslav@sqlmap.org

**Comment by Alfredasss** [comment]
Try to run sqlmap with switch --sql-shell  and then `SELECT table_name FROM information_schema.tables WHERE table_schema = `db01`  ` this must work!!!

**Comment by iwantaturboman** [comment]
Hi guys and thanks for your help.
1) i don't see what `--parse-errors` command gives more... There are the warnings messages : 
```
[WARNING] the SQL query provided does not return any output
[WARNING] in case of continuous data retrieval problems you are advised to try a switch '--no-cast' or switch '--hex'
[WARNING] running in a single-thread mode. Please consider usage of option '--threads' for faster data retrieval
[WARNING] time-based comparison requires larger statistical model, please wait..........................
[WARNING] it is very important not to stress the network adapter during usage of time-based payloads to prevent potential errors
[10:02:32] [WARNING] unable to retrieve the number of tables for database 'db01'
```
2) It's strange because that command line `-t traffic.txt` doesn't create any text file in sqlmap folder. I searched for it in the specific folder (where log and session.sqlite are) but found nothing.

3) To Alfredasss : that sql command doesn't work either. Same warnings messages that above.

Regards,

**Comment by stamparm** [comment]
`-t traffic.txt` should create a file in current folder (or any folder set by the running environment).

that file IS written somewhere if there is a traffic coming from sqlmap (hence the necessity of usage of `--fresh-queries`)

**Comment by iwantaturboman** [comment]
Ok, from what i've seen, traffic.txt was in the same directory than sqlmap.py. I send you the file right now.
Thanks again.

**Comment by stamparm** [comment]
Please learn to read basics (sniff traffic, watch request/response). You'll make my work easier.

Your site replaces ` WHERE ` in all requests with <blank> (i.e. it removes all those `WHERE` occurrences).

Hence, you get replies for regular `SELECT..FROM..WHERE..` queries like:

```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INFORMATION_SCHEMA.TABLES  table_schema IN (0x73706972697476695f616d6b616e6577))' at line 2
```

**Comment by stamparm** [comment]
p.s. this is the reason why I tend to close this kind of issues really fast. Because I know that at the end I'll need to do the users work

**Comment by iwantaturboman** [comment]
Thanks for your patience, stamparm.
In fact, i don't know how to read traffic.txt. I need to learn how.
I don't either understand the fact that "our site replaces WHERE in all requests with (i.e. it removes all those WHERE occurrences)."
