### ISSUE TITLE
403 when trying to retrieve anything, though banner, hostname ok and current user is dba 

### ISSUE THREAD

**Issue by bernig** [sqlmapproject/sqlmap#1696]
Hi, 
I have an boolean-based blind injection point from which I can retrieve banner, current_user, hostname, and current user IS DBA. Though no current database is shown, and for any data I try to retrieve (users, databases), I get a 403 (Forbidden) error.

DBMS is MariaDB (i.e. MySQL)

By the way, I had to use the tamper "greatest" to get banner info, etc.
When not using it, every field where showing "None".

Do you know any reason why I can't get any data ? Current user being DBA, I have a hard time figuring this one out.

Thank you in advance for your help. If this post does not belong here, or if more info is needed, just tell me.

**Comment by stamparm** [comment]
There is a WAF there making that site more secure. Hence the problems and 403s. There is no out-of-box solution here. You should manually find what works and try to appropriately use (if it can be done in the first place) tamper scripts that work
