### ISSUE TITLE
Tamers manuals

### ISSUE THREAD

**Issue by Alfredasss** [sqlmapproject/sqlmap#1697]
Where i can find information how many tampers exist in sqlmap and what every tamper do?

Like this http://www.forkbombers.com/2013/05/sqlmaps-tamper-scripts.html
but it is too old i think?

**Comment by shadowfolder** [comment]
In folder where located sqlmap.py there are folder with name "tamper". https://github.com/sqlmapproject/sqlmap/tree/master/tamper 
You can find what tamper do inside, in example **between.py**


> Replaces greater than operator ('>') with 'NOT BETWEEN 0 AND #'
>     Replaces equals operator ('=') with 'BETWEEN # AND #'
>     Tested against:
>         * Microsoft SQL Server 2005
>         * MySQL 4, 5.0 and 5.5
>         * Oracle 10g
>         * PostgreSQL 8.3, 8.4, 9.0
>     Notes:
>         * Useful to bypass weak and bespoke web application firewalls that
>           filter the greater than character
>         * The BETWEEN clause is SQL standard. Hence, this tamper script
>           should work against all (?) databases


P.S. Guys, how you mixing tamper scripts? In example i exclude every tamper for MySQL, and running every time with various combinations. :smile:
