### ISSUE TITLE
Sql-i over a parameter's xml value

### ISSUE THREAD

**Issue by appingmap** [sqlmapproject/sqlmap#1699]
How can sqlmap try payloads to the parameter X in below request. is there any way?

POST /detailPage.ashx HTTP/1.1
Host: www.mysite.com
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 225
Cookie: SessionId=dkkhvsp30ax0fslkustvpw0s;
Connection: close

`num=81&transaction=<transaction xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance" xsi:type="xsd:Object"><operations xsi:type="xsd:List"><param xsi:type="xsd:Object"><id xsi:type="xsd:long">X</startRow></param></operations></transaction>&num1=100`

**Comment by stamparm** [comment]
Have you tried putting the custom injection mark * after the X (e.g. X*)
