### ISSUE TITLE
Sqlmap Information

### ISSUE THREAD

**Issue by cacaocaca** [sqlmapproject/sqlmap#1705]
Hi sorry for my english i m italian man .. I would like ask one question . For example if i want see email and password i do that   -C email,password --dump the extraction is 
0780500255@blabla,0fee5dab9532939af11e0e1dcb49594c:3nxIH3YhH40cmhp4mraS1sQxwxUSmJp4
It ok up to there but if afther i want for example decrypt hash i cant becouse the file saved contains email and password and if i run again -C password --dump is begins  at  the start and if the list is of 10000 for example i need to wait 1 day .. Is possible have right email and hash and afther when i run -C password --dump get the list of the hash fast   and not having to wait for the whole process again at the beginning? If not how i can copy  the hash on sort with  the right email on other file.txt ?

**Comment by IUsual** [comment]
-s(session-file) switch may help. You can load session information form a stored (.sqlite) file that saved on ~/.sqlmap/output/url-domain/session.sqlite by default.

**Comment by cacaocaca** [comment]
Yes but the session think saved file as i have set  
0780500255@blabla,0fee5dab9532939af11e0e1dcb49594c:3nxIH3YhH40cmhp4mraS1sQxwxUSmJp4
and is impossible copy just a hash file of 100000 string .

**Comment by stamparm** [comment]
@cacaocaca it is really hard to understand what you want to do. I guess that you want to dump for example a password for some email. You can do that by doing:

`...--dump -T ... --where="email=0780500255@blabla"`

**Comment by cacaocaca** [comment]
Yes but when i dump email and password the list is 
a.shaffragra@voktech.com,$P$BtuVfTnD8sd2YBiH64VXUSr29kZQ3B0K0
euginedref@asdfmail.net,$P$B4zFgTcfdhoG.byA2saO.3uBatTn1my/0
jc12mongdue@gmail.com,$P$BVuXgTDQt081af5KH3YsYxudvMt0JeE.
So now i have file.cvs for example if i want crack now just the hash i can t why the list is of  email and password  now if i want list just of password i can do -C password --dump but so i lose 1 day  if the list is of 100000.Practically I want to do only one extraction process .. only once .. but with the capacity to be able to decrypt the hash at the end .

**Comment by cacaocaca** [comment]
I can t decrypt hash becouse sqlmap can t start decryption  automatic for Blowfish(OpenBSD) for that afther i need just hash alone for decrypt

**Comment by stamparm** [comment]
So, basically, it is a problem for you to extract the second column from dumped CSV file? Well, I won't comment on this issue any more.

**Comment by cacaocaca** [comment]
Yes is problem for extraction but is of sqlmap  why is more easy any people  if you  can run -C password --dump and dump all fast and no wait again all process .. Good work the same ;)

**Comment by cacaocaca** [comment]
The solucion is dump  -C password,email and no dump email,password afther open file.cvs with mono develop  position itself  in the first line and press ctrl + alt after click  left mouse button and copy all the hashes and save a new document ..
