### ISSUE TITLE
Mysql query search a string in all columns of a table

### ISSUE THREAD

**Issue by Alfredasss** [sqlmapproject/sqlmap#1707]
How to search string in table ?
 switch --search works only for dbsnames, tablesnames, columnnames

How to do 

Select * FROM table WHERE username LIKE '%alex%'
???

--sql-query and from --sql-shell queries always return `none` but normaly -D dba -T users --dump-all can enumerate this username.

**Comment by stamparm** [comment]
You can do this only with `--dump`. You can try `--where="username LIKE '%alex%'"
