### ISSUE TITLE
Sqlmap dumping technique

### ISSUE THREAD

**Issue by Alfredasss** [sqlmapproject/sqlmap#1712]
How Sqlmap dump entries?
Is sqlmap technique is only use LIMIT to dump dbs? Is it quick enought to dump 1.000.000 entries over LIMIT 1.000.000,1 ?
Does it have something like dump by looping IDs from 1 to 1.000.000 ?

**Comment by stamparm** [comment]
Sqlmap uses different techniques to dump data and it uses most optimal depending on the case. In some situations it uses LIMIT if e.g. full UNION is not available
