### ISSUE TITLE
Bypass Mod Security

### ISSUE THREAD

**Issue by cskgilakthe** [sqlmapproject/sqlmap#1716]
I use "id=1%0aunion%0aall%0aselect%0a1,null,null,null,null,null,null,null,null,null--" on browser is working but slow and hard.
I use sqlmap not working. Error "[CRITICAL] all tested parameters appear to be not injectable. Try to increase '--level'/'--risk' values to perform more tests. Also, you can try to rerun by providing either a valid value for option '--string' (or '--regexp') If you suspect that there is some kind of protection mechanism involved (e.g. WAF) maybe you could retry with an option '--tamper' (e.g. '--tamper=space2comment')"
Server modsecurity. I must replace char ' => ", CONCAT => C%4FNCAT, COUNT => C%4FUNT, * => %2A, SPACE => %0A it work.
How to bypass on sqlmap?

**Comment by stamparm** [comment]
Make your own tamper script. Please take a look into really lots of examples in tamper directory
