### ISSUE TITLE
CSV results

### ISSUE THREAD

**Issue by Alfredasss** [sqlmapproject/sqlmap#1718]
How to understand CSV result after scaning with options --crawl=3 --forms

Result....csv contains

Target URL,Place,Parameter,Techniques
http://mysite.com/form.php,POST,curpass,B

But problem is that curpass not exist in any forms in my site, how to check why sqlmap write this parameter to csv file? There i can see full request with vulnarable data?

**Comment by stamparm** [comment]
sqlmap hasn't randomly put that parameter there. You should rerun --forms with --crawl and answer each question with N (for scanning results). One of those will contain your parameter
