### ISSUE TITLE
Only one scan result data returned from the IPC database.

### ISSUE THREAD

**Issue by Aikes** [sqlmapproject/sqlmap#1719]
I type command `--random-agent --beep --threads=3 --risk=3 --level=3 --time-sec=30 --retries=1 --output-dir="D:/Temp/test/" -u "http://testphp.acunetix.com" --flush --fresh --crawl=2 --technique=BT --batch --answers="skip further=N"` through sqlmapapi

file [results-02212016_1218am.csv] data follows:
`Target URL,Place,Parameter,Techniques
http://testphp.acunetix.com:80/listproducts.php?cat=1,GET,cat,BT
http://testphp.acunetix.com:80/artists.php?artist=1,GET,artist,BT
`

but, there are one record data returned for the taskid in `/scan/44a06c2a706645c0/data`

**Comment by stamparm** [comment]
Same thing is returned as when you run the sqlmap regularly. You are being presented with the CURRENT injection point, not all ever found by sqlmap for that target.
