### ISSUE TITLE
timeout problem

### ISSUE THREAD

**Issue by EnDe** [sqlmapproject/sqlmap#1720]
When using Basic Auth, I get following error

[09:42:42] [ERROR] not authorized, try to provide right HTTP authentication type and valid credentials (401), skipping to the next form
[09:42:42] [WARNING] HTTP error codes detected during run:
401 (Unauthorized) - 1 times

The logfile with the requests and responses contains:
   HTTP response [#759] (401 basic auth failed):

  None

The reason is **not** wrong credentials as this happens reproducable with the same set of parameters run again and again at different states of sqlmap.
So I guess it is some kind of timeout problem server-side. When using --delay=1 the error occours later in sqlmap (means more tests are performed). So --delay is a cumbersome workaround at the moment.

Would be nice to have options  --delay-error and --retries-error to handle such situations. I guess this is not related to Basic Auth but may happen in other situations too.

**Comment by stamparm** [comment]
401 is not randomly generated by sqlmap but with the server itself. Please run the MiTM proxy (e.g. Burp) and debug the problem before raising an issue

**Comment by EnDe** [comment]
> 401 is not randomly generated by sqlmap ...
That's exactly what I said: server issue.
The title of this issue contains "timeout", that's related to sqlmap.

I 've seen another strange behaviour when using Basic Auth while looking at my proxy. Should I open a new issue or descibe it in this one? I'm not yet sure if they are retated.

The workaround is to add the "Authorization: Basic ..." header to the list of extra HTTP headers (--headers) instead of using --authType and --authCred.
This workaround solves the "timeout" problem (this issue) as well as the starnge behaviour.

Please let me know how to proceed. Can do more debugging, if you like.
