### ISSUE TITLE
Response line in logfile

### ISSUE THREAD

**Issue by EnDe** [sqlmapproject/sqlmap#1722]
In the logfile containing the requests and responses, the first response line looks like
  HTTP response [#5] (200 OK):

It would be nice if this line is the original one from the response, then add the sqlmap internal information at end. For example:
  HTTP/1.1 200 OK ; response [#5] 

This would make it easier to pass the logfiles to other tools for further examination or processing.

**Comment by stamparm** [comment]
Closing this down. Traffic file is used strictly for debugging purposes. Also, changing this format would produce a far more unreadable results

**Comment by EnDe** [comment]
> strictly for debugging ...
ok, agreed ;-)
