### ISSUE TITLE
[CRITICAL] missing a mandatory option

### ISSUE THREAD

**Issue by EnDe** [sqlmapproject/sqlmap#1723]
When using sqlmap with the sqlmap.ini file like
   sqlmap -c sqlmap.ini --url=http://....
you get follwoing error:

[09:59:59] [CRITICAL] missing a mandatory option in the configuration file (url, logFile, bulkFile, googleDork, requestFile or wizard)

This only happens if there is no
   url =
line in the sqlmap.ini. So the workaround is to have an empty url= in the file.

**Comment by LionNatsu** [comment]
I provided a PR just now :)

**Comment by stamparm** [comment]
![rrr](https://cloud.githubusercontent.com/assets/921555/13248352/14260e96-da1e-11e5-9477-16a820901d50.png)
