### ISSUE TITLE
using authentication sends wrong requests

### ISSUE THREAD

**Issue by EnDe** [sqlmapproject/sqlmap#1724]
When using Basic Auth, wether with --auth-type and --auth-cred option, or with authType and authCred setting in sqlmap.ini, sqlmap sends wrong requests.
sqlmap sends 2 requests as follows:
1. GET /mypath HTTP/1.1
    without Authorization header
2. GET http://some.tld/mypath HTTP/1.1
    Authorization: bWVhOmN1bHBhCg==

The first request fails always, obviously. The second one passes successful. However, if the webserver is configured pedantically it shoud fail to, as http:// urls should not be allowed in the verb line of GET and POST requests.
This issue is realted to #1720 .
Also note that only the first request is stored in the log file (see issue #1721 ).

The workaround to get Basic Auth working proper (means sending the correct requests) is to use "Authorization: ..." as additional HTTP header (--header option).

Hope this description shows clearly the issue, also in the other two referenced issues. I also provded a workaround, so it's not urgend ;-)

**Comment by stamparm** [comment]
401 should be returned in step 1). No matter the "pedantry". If it doesn't do that (but timeouts), you have a non-standard web server. Use the HTTP header then (as you've mentioned)

**Comment by EnDe** [comment]
Step 1 sends a 401.
In the proxy you can see that sqlmap definitely sends 2 requests. Both are wrong formatted according what I expect.
And yes, it seems to be a non-standard web server, one with good natureness,  which accepts the second request most the time (what I already said;-)

> a standard way how Python web tools work
Hmm, does this mean any security issue somewhere must be detectable by the way python works? I'd not comment this.
No offence meant anyhow.

**Comment by stamparm** [comment]
1) Can't reproduce the `However, if the webserver is configured pedantically it shoud fail to, as http:// urls should not be allowed in the verb line of GET and POST requests.`

![1](https://cloud.githubusercontent.com/assets/921555/13670804/5856d52c-e6cc-11e5-9974-9aec6658b9c0.png)
![2](https://cloud.githubusercontent.com/assets/921555/13670805/5857a3ee-e6cc-11e5-98da-73a775000371.png)

2) "Hmm, does this mean any security issue somewhere must be detectable by the way python works?" <- this is something to ignore. sqlmap is doing a normal job like any other browser. Until there is no need for authorization the same won't be used. You don't want sqlmap to spread around plain Basic authentication credentials in case of any redirects
