### ISSUE TITLE
request HTTP DELETE 

### ISSUE THREAD

**Issue by kos76** [sqlmapproject/sqlmap#1725]
this command  doesn`t work
 python sqlmap.py -u "http://mysite/api/v1/photos/50*"  --DELETE -b --level 1 --risk 1 --random-agent  -H 'Authorization:Bearer d5d7eaa165500f479fa260fb25137cad8b99f17c'
i get  error : "sqlmap.py: error: no such option: --DELETE"

sqlmap with method DELETE doesnt work ?

**Comment by stamparm** [comment]
`--method=DELETE`

**Comment by yanislong** [comment]
sqlmap -u "http://***.***.***/shopping/order/destroy/17051235356766963" --method=DELETE --cookie="dev_session=sb636scci7u085dpf1s3nd1ke4" --headers='X-Requested-With:XMLHttpRequest' --dbms mysql   is ok!
