### ISSUE TITLE
invalid post parameter

### ISSUE THREAD

**Issue by amirmagic** [sqlmapproject/sqlmap#1739]
hi to dear @stamparm . i need to help .

i want to test a link for inject but my link like this :

URL : http://xxx.com/Index.aspx/Login
Post : {sqlExp:'123123123123123,12312312312312312'}

there is my problem how i enter this post data into sqlmap ?!
first i enter command like always : sqlmap.py -u "http://xxx.com/Index.aspx/Login" --data "{sqlExp:'123123123123123,12312312312312312'}" --dbs but sqlmap show me : 
[CRITICAL] no parameter(s) found for testing in the provided data (e.g. GET parameter 'id' in 'www.site.com/index.php?id=1')

so i tested other ways : sqlmap.py -u "http://xxx.com/Index.aspx/Login" --forms but not working fine !

so please help me :d 
thanks a lot  :+1:

**Comment by stormwin** [comment]
try this:
--data "{sqlExp:'*,12312312312312312'}"

or this:
--data "{sqlExp:'123123123123123,*'}"

**Comment by amirmagic** [comment]
@stormwin thanks a lot ! this work fine ! of course i came the value of data is url encode like this : 
%7BsqlExp%3A%27123123123123123%2C12312312312312312%27%7D
and this working ! but your help very best of my way ;)

thanks again ;)
