### ISSUE TITLE
sqlmap new release?

### ISSUE THREAD

**Issue by LocutusOfBorg** [sqlmapproject/sqlmap#1765]
Hi, I'm not asking for a new release, just it would be nice if you can tell me what is your plan about a release schedule.

For backbox I have an issue, somebody before me called it
"1.0.160227-1"
so I can't upload the 1.0 as-is (as it is on Debian and Ubuntu), but I have to do a special upload for backbox.

From version 1.1 the situation will be automatically fixed.
Do you plan to release more and often your package?
thanks,

G.

**Comment by stamparm** [comment]
Plan is:

`1.1` in January 2017.
`1.2` in January 2018.
etc.

**Comment by LocutusOfBorg** [comment]
thanks, so no minor releases in the meanwhile?
fine for me, I was used to update it each month to the new snapshot :)

**Comment by stamparm** [comment]
There should be couple of "micro" versions (1.0.1, 1.0.2...) through out a year. Most probably the last number will represent the month. But I am not sure that this helps you until the 1.1 :-)

**Comment by stamparm** [comment]
Just implemented automatic update of "micro" version depending on the current month. Hence, from now on that third number will represent the month and the last number the commit/revision in that same month. Current VERSION string can be seen in https://github.com/sqlmapproject/sqlmap/blob/master/lib/core/settings.py#L23

**Comment by LocutusOfBorg** [comment]
thanks a lot!

**Comment by LocutusOfBorg** [comment]
but please don't forget to tag from time to time, and I'll upload on debian :)

**Comment by stamparm** [comment]
Done for the moment (https://github.com/sqlmapproject/sqlmap/tags). Will automate this (for all micro/month changes -> e.g. 1.0.3, 1.0.4, ...)

**Comment by LocutusOfBorg** [comment]
uploading in debian in a few minutes, thanks!

**Comment by stamparm** [comment]
With the last update first commit in the month will be automatically tagged. E.g., for this April, first commit will set the VERSION to `1.0.4.0`, tag it to `1.0.4` and push (tags) to this repository

**Comment by stamparm** [comment]
p.s. I hope that this will result in some happy (packaging) faces around :)

**Comment by LocutusOfBorg** [comment]
sure :)
