### ISSUE TITLE
the remote file '/xampp/htdocs/tmpujbvw.php' is larger (716 B) than the local file "local directory"

### ISSUE THREAD

**Issue by mahsimsx** [sqlmapproject/sqlmap#1771]
hello,

i need help to fix this issue i try to find this same issue before but still not receive answer
i use new version sqlmap at windows (using python) 
and i try to use --os-shell at sqlmap

but this not same with what i get in my old sqlmap. same site tester but different result

in new sqlmap case is when i try remote with --os-shell i got this warn :

[12:37:33] [INFO] the remote file '/xampp/htdocs/tmpujbvw.php' is larger (716 B) than the local file

can somebody help me ?

**Comment by stamparm** [comment]
This is normal in most situations. Part of results from original query went into the output file. You can't expect clean output file in all situations.
