### ISSUE TITLE
DNS Exfiltration - Setup help!

### ISSUE THREAD

**Issue by BlackLz** [sqlmapproject/sqlmap#1788]
Hi, sorry for making a request for this but i'm stuck for weeks.
I have a domain and a CentOS7 hosted on godaddy.
No matter what I do, I just cant make this work well. I have added a 'A' record on the domain pointing to the CentOS IP which have a BIND9 Server pointing to the machine using sqlmap... 

I dont know if this is right and cant find anything about setting this up... can you help me please?

**Comment by stamparm** [comment]
So, you need a DNS server and you registered A record? What about the NS record? Do you believe that you should register it too?

**Comment by BlackLz** [comment]
I already done this
![screenshot_25](https://cloud.githubusercontent.com/assets/17723374/14189399/68d50818-f763-11e5-94cc-f5b8db977614.png)
![screenshot_26](https://cloud.githubusercontent.com/assets/17723374/14189398/68d33146-f763-11e5-9c1b-60c755f91589.png)

![screenshot_23](https://cloud.githubusercontent.com/assets/17723374/14189328/13c37cce-f763-11e5-832c-4c0561963e33.png)
![screenshot_24](https://cloud.githubusercontent.com/assets/17723374/14189329/13c79f3e-f763-11e5-9cc5-3f0c97809731.png)

**Comment by stamparm** [comment]
Stop the iodined and run on the server where you run sqlmap the:

`sudo tcpdump -n -i any port 53`

On some other box run the:

`dig foobar.com @yourdomain.com`

(<- where `yourdomain.com` should be the same that you try to use in `--dns-domain`)

Do you get the `A? foobar.com.` in the `tcpdump` output?

**Comment by stamparm** [comment]
p.s. in one message you say: `I have added a 'A' record on the domain pointing to the CentOS IP` in the other (after I point you to setting the NS record) you said `I already done this but it isnt working yet`. I tend to close this kind of issues really fast

**Comment by BrunoWHT** [comment]
No. Nothing comes out

![screenshot_186](https://cloud.githubusercontent.com/assets/9045233/14228907/8cc479fe-f8fb-11e5-97fe-268cf93b9147.png)

DNS Records
![screenshot_187](https://cloud.githubusercontent.com/assets/9045233/14228909/c8ffc176-f8fb-11e5-96b9-a24d75d87284.png)

**Comment by BlackLz** [comment]
No :/, Nothing comes out
I Think I set something wrong on DNS Records...

![screenshot_186](https://cloud.githubusercontent.com/assets/9045233/14228907/8cc479fe-f8fb-11e5-97fe-268cf93b9147.png)

![screenshot_187](https://cloud.githubusercontent.com/assets/9045233/14228909/c8ffc176-f8fb-11e5-96b9-a24d75d87284.png)

**Comment by stamparm** [comment]
Now, take a look into the request/payload that sqlmap uses (`-v 3`). Until you get anything at the tcpdump with that same or similar payload, sqlmap won't work. Target has to provoke the DNS request itself.

**Comment by Aasron** [comment]
@BlackLz  Brother, did you solve this problem? I now have the same problem as you. I need your answers and help. Thank you.

**Comment by Natz-ft** [comment]
sometimes ok，sometimes not work
