### ISSUE TITLE
sqlmap incorrectly identifies a paramater as non-injectable in certain (unknown) cases

### ISSUE THREAD

**Issue by wesdxc** [sqlmapproject/sqlmap#1798]
Hello,

I noticed something and am having a hard time troubleshooting it.  I believe it may be a bug in sqlmap but cannot tell for sure.  I was working on a vulnhub VM [1] and when I got to the SQL injection part, of course I fired up sqlmap.  It scanned and claimed that all tested parameters appear to be not injectable.  I consulted several walkthroughs trying to figure another way around, and all of them had successfully used sqlmap to dump database information ([2], [3], [4], [5], [6], [7], [8], [9]).  Here are several different command line invocations I have tried:

`sqlmap  --url=http://192.168.1.182:1337/978345210/index.php --method POST --data 'username=&password=&submit=%20Login%20' --not-string='Username or Password is invalid' --dbs 
`

`sqlmap -u http://192.168.1.182:1337/978345210/index.php --data='username=poop&password=dildo&submit= Login ' --method POST --risk=3 --level=3 --threads=5 --not-string="Username or Password is invalid" --tamper="between,equaltolike"`

`sqlmap  -u http://192.168.1.182:1337/978345210/index.php --forms --dbs
`

I also tried the first and third invocations against [10] when adjusted as necessary (POST data) and they performed as expected (read: flawlessly).  

I have tried using sqlmap versions 1.0-dev, 1.0+git20150214-0kali1, 1.0-dev-nongit-20160324, 1.0.4.0#dev and even 0.8, all with identical results.  I could not locate a copy of the version used in many of the walkthroughs (1.0-dev-nongit-20150826) - otherwise I would have tried that as well.

I am using Kali Linux 1.0.7 (kernel 3.14-kali1-amd64) in a Parallels 8 VM on Mac OS X 10.9.2 as the attack machine.  The vulnerable VM is Ubuntu 14.04 LTS running in VMWare Fusion 7.1.2 on the same Mac OS X 10.9.2.  

Thanks for any time you can spare for this - I know it's a lot.  If you need any other information or tests to be run please let me know and I'll report back with whatever you need.

Thanks again,

Wes

[1] https://www.vulnhub.com/entry/lord-of-the-root-101,129/
[2] https://highon.coffee/blog/lord-of-the-root-walkthrough/
[3] https://trickster0.wordpress.com/2015/10/08/lord-of-the-root-1-0-1-write-up/
[4] http://dook.biz/2015/10/vulnhub-lord-of-the-root-writeup/
[5] http://bullsecurity.blogspot.com.au/2015/09/lord-of-root-rooted.html
[6] http://ejtaal.net/infosec/lordoftheroot/
[7] https://research.g0blin.co.uk/lord-of-the-root-vulnhub-writeup/
[8] http://kooksec.blogspot.com/2015/09/hacking-lord-of-root.html
[9] http://www.bommachine.co.uk/vulnhub-lord-of-the-root-challenge/
[10] http://testasp.vulnweb.com/Login.asp

**Comment by stamparm** [comment]
Sqlmap by default doesn't use OR boolean SQLi payloads (loosing of data could be a problem in real life situations) and I believe that you require it for login pages (e.g. to turn them on you can try --level=3 --risk=3).

Also, you are warned in ALL sqlmap runs when you use empty parameters to not do that because sqlmap can't yet read your mind in search for valid parameter values (important for proper finding of SQLi). In case of login pages username foobar and password foobar would suffice

**Comment by wesdxc** [comment]
Hello,

You can see clearly I tried with --level=3 and --risk=3 as well as specific passwords in the second invocation.  I also tried using exact command lines from the walkthroughs but was unable to get the same successful result.  Respectfully, I believe you may be dismissing this a tad quickly.

Kind regards,

Wes

**Comment by stamparm** [comment]
Have you examined the traffic going in and out? Payloads and responses? I tend to dismiss issues very quickly if I don't see that user examined what was the problem in the first place.

**Comment by wesdxc** [comment]
Okay, so then I'm looking in the wrong place (old versions, command line arguments).  That's not the same as not looking.  I'll take some captures later and try and understand the traffic.  I'll be honest in that I am completely out of my depth here - I'd really like to help but may need some guidance.  Please tell me - what should I be looking for?   

Thanks,

Wes

**Comment by stamparm** [comment]
You should take a look into used payloads and triggered responses. You've raised an issue that sqlmap doesn't find a SQLi so I would expect you to be able to find it yourself and pinpoint what is the problem.
