### ISSUE TITLE
sqlmap tamper script

### ISSUE THREAD

**Issue by kings215** [sqlmapproject/sqlmap#1799]
hi

how to baypass 

[WARNING] CloudFlare response detected 

and

[CRITICAL] previous heuristics detected that the target is protected by some kind of WAF/IPS/IDS

**Comment by stamparm** [comment]
In most cases you can't. Also, this is like raising an issue how to bypass everything. Nowadays it is really hard, especially if you skip the manual inspection part (which user is supposed to do)
