### ISSUE TITLE
"[WARNING] there was a problem decoding value '2' from expected hexadecimal form"

### ISSUE THREAD

**Issue by Lumikor** [sqlmapproject/sqlmap#1803]
two days ago a problem started with sqlmap, suddenly I'm getting the error above and the data dump becomes corrupted, I haven't changed anything in my code, system or sqlmap version. 

this is my code 
sqlmap -u "http://" --level=5 --risk=3 --dump -T users -o "/home//" --dbms=MySQL  --random-agent --dump-format=CSV --threads=10 --where="user_id=1" --timeout=120 --hex
running sqlmap 1.0.3.1#dev

**Comment by stamparm** [comment]
Maybe some wrong data value stuck into the session file. Please rerun with --fresh-queries (so the query causing it could retrieve a new value)

**Comment by Lumikor** [comment]
still the same, also didn't worked with several --charset

**Comment by stamparm** [comment]
Some value is returned in non-hexadecimal form, while the sqlmap expects it to be in hexadecimal form.

Which SQLi technique is being used here in the first place?

**Comment by Lumikor** [comment]
boolean-based blind

**Comment by stamparm** [comment]
Can you give any useful information how to debug it?

**Comment by Lumikor** [comment]
starting new session worked
