### ISSUE TITLE
Ability to manually guess data during blind time-based SQLi

### ISSUE THREAD

**Issue by strawp** [sqlmapproject/sqlmap#1808]
It would be very cool to be able to just hit a key to interrupt the current bsqli process and guess the whole string that is being constructed. Often it'll be obvious what the rest of something like a column name is, but sqlmap still has to work it out. 

Potentially, guesses could even automatically come from a dictionary of common words, but I don't think it needs to be that complicated.

**Comment by stamparm** [comment]
Already asked tens of times from other users. Though, closed all those requests because Python doesn't have (standard and/or any all-OS hack) for non-blocking capture of keyboard presses

**Comment by stamparm** [comment]
To rephrase, you can't perform standard work (e.g. dumping) and wait for user keyboard press (in standard or all around OS hack)

**Comment by strawp** [comment]
Thought you might say that! No worries

**Comment by strawp** [comment]
However, I would be happy to have dumping grind to a halt if that's the effect that it has

**Comment by strawp** [comment]
Would it still not be possible to use the common-* files to guess a certain number of chars into an output?

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/blob/master/txt/common-outputs.txt is already being used in case of `--predict-output`. Though, in table dumps that list is not of great use (only useful in specific enumeration cases - e.g. --banner)

Bye

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/blob/master/txt/common-outputs.txt is already being used in case of `--predict-output`. Though, in table dumps that list is not of great use (only useful in specific enumeration cases - e.g. --banner)

Bye

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/blob/master/txt/common-outputs.txt is already being used in case of `--predict-output`. Though, in table dumps that list is not of great use (only useful in specific enumeration cases - e.g. --banner)

Bye

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/blob/master/txt/common-outputs.txt is already being used in case of `--predict-output`. Though, in table dumps that list is not of great use (only useful in specific enumeration cases - e.g. --banner)

Bye

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/blob/master/txt/common-outputs.txt is already being used in case of `--predict-output`. Though, in table dumps that list is not of great use (only useful in specific enumeration cases - e.g. --banner)

Bye

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/blob/master/txt/common-outputs.txt is already being used in case of `--predict-output`. Though, in table dumps that list is not of great use (only useful in specific enumeration cases - e.g. --banner)

Bye

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/blob/master/txt/common-outputs.txt is already being used in case of `--predict-output`. Though, in table dumps that list is not of great use (only useful in specific enumeration cases - e.g. --banner)

Bye

**Comment by strawp** [comment]
Thanks!
