### ISSUE TITLE
Strange thing : can dump 1 or 2 columns but not more...

### ISSUE THREAD

**Issue by iwantaturboman** [sqlmapproject/sqlmap#1814]
Hi all,
i have a problem trying to dump a database from a website (for testing purposes).
url : `http://www.mytarget.com`
target : `http://www.mytarget.com/*`
injection type : Union-query based (U)

database name : db01
table name : users
columns names : id, email, username, password

Here we go, this command (for example) works : 
`python sqlmap.py -u http://www.mytarget.com/* -D db01 -T users -C id,email --dump --threads=5`
As if i try to dump only one column.

But when i try this command : 
`python sqlmap.py -u http://www.mytarget.com/* -D db01 -T users -C id,email,password,username --dump --threads=5`
SQLmap is completly frozen. I mean i answer "Y" to these 2 questions like above : 
```
custom injection marking character ('*') found in option '-u'. Do you want to process it? [Y/n/q] Y
 [INFO] starting 5 threads
sqlmap got a 301 redirect to 'http://www.mytarget.com/error.shtml'. Do you want to follow? [Y/n] Y
```
Then nothing happens.
Python process looks like working heavily in my task manager but no visual.
Any idea ?
Regards,

**Comment by erwinsalarda** [comment]
--nocast

**Comment by iwantaturboman** [comment]
Hi,
same problem with `--no-cast` added.

**Comment by erwinsalarda** [comment]
Try ur threads lower than 5. Then try dont follow.  Must be N.

I have same experienceD before. I dont know if THEY redireted the attack to
their trap.

**Comment by erwinsalarda** [comment]
Is that access?

**Comment by iwantaturboman** [comment]
Same problem with : 
- no redirection,
- threads lower than 5.

**Comment by erwinsalarda** [comment]
-o

**Comment by erwinsalarda** [comment]
In this case try to use havij.
I have experiece before. Sqlmap cant dump but havij can.
On 15 Apr 2016 00:11, "erwin salarda" <erwincsalarda@gmail.com> wrote:

-o

**Comment by iwantaturboman** [comment]
Let's see what stamparm thinks. I don't like Havij at all.

**Comment by erwinsalarda** [comment]
Right.

**Comment by stamparm** [comment]
Probable causes:

1) Too many threads used. Some platforms really don't like this (especially with MsSQL DBMS)
2) Keyword `password` is blacklisted by some outer-layer protection (e.g. WAF)
3) Too long HTTP parameter values (e.g. longer than some threshold length)
4) One of those columns don't exist in the first place at the table of interest

p.s. please inspect if you could identify any of those causes in your case. If you fail please send me more details to `miroslav@sqlmap.org`

**Comment by iwantaturboman** [comment]
Ok, i'll try all of this tonight. Thanks.

**Comment by iwantaturboman** [comment]
Hi again, just to specify some things : 
1) back-end DBMS is mysql,
2) i can retrieve easily id+passwords columns for example (so not an issue)
3) don't know how to check this (if it's possible)
4) all columns of `users` have been found with "columns guessing".
Regards,

**Comment by stamparm** [comment]
Well, maybe the 4) is the one to blame. I would flush everything and try from start. I you get the same results, please contact me privately

**Comment by iwantaturboman** [comment]
Hi all,
something interesting : i've just tried this morning to find (again) columns names of `users` table.
With this :` python sqlmap.py -u http://www.mytarget.com/* -D db01 -T users --columns --threads=1 --fresh-queries` ; sqlmap "answers" : 
```
[INFO] fetching columns for table 'members' in database 'db01'
sqlmap got a 301 redirect to 'http://www.mytarget.com/error.shtml'. Do you want to follow? [Y/n] y
[WARNING] the SQL query provided does not return any output
[WARNING] in case of continuous data retrieval problems you are advised to try a switch '--no-cast' or switch '--hex'
[WARNING] unable to retrieve column names for table 'users' in database 'db01'
do you want to use common column existence check? [y/N/q] n
[INFO] fetched data logged to text files under (...)
```

Now with this : ` python sqlmap.py -u http://www.mytarget.com/* -D db01 -T users --columns --threads=1 --fresh-queries --no-cast` ; sqlmap "answers" : 
```
[INFO] fetching columns for table 'users' in database 'db01'
[INFO] the SQL query used returns 18 entries
sqlmap got a 301 redirect to 'http://www.mytarget.com/error.shtml'. Do you want to follow? [Y/n] y
[WARNING] unable to retrieve column names for table 'users' in database 'db01'
do you want to use common column existence check? [y/N/q] n
[INFO] fetched data logged to text files under (...)
```

So, with `--no-cast` sqlmap finds columns number (18) but enable to list them.
As you know, if i use common column existence check, sqlmap finds "only" 4 columns.
How can sqlmap exactly find columns number of a table and be not enable to list them ?

**Comment by stamparm** [comment]
This is all not related to the sqlmap but to the target. It seems like a protection mechanism. To make things worse, you have a UNION technique while sqlmap had to use column existence check. This is really not so normal behavior. I've asked for couple of times for details in private and haven't got. Closing this down
