### ISSUE TITLE
Sqlmap always shutdown without information schema ecc

### ISSUE THREAD

**Issue by cacaocaca** [sqlmapproject/sqlmap#1817]
Hi sorry for my english i m italian guy i have problem for returning of database practically first some month ago work normally but now no more now no work more  with any site is my problem i think becouse i have talk with my friend to do same command and for he work and for me no .. The output  is always for example databe sql windows 7 for example afther " shutdown " and afther ask for see log on sqlmap but i can do nothing becouse i don t know the tables for continue . Thanks i hope you can resolve my problem i don t think that the problem is now becouse i use another usb wireless and change mac .

**Comment by stamparm** [comment]
Don't run by double clicking on sqlmap.py. Open a command prompt and type commands there. Also, google for "sqlmap tutorial"

**Comment by cacaocaca** [comment]
i use kali linux i dont do double click and sorry i don t need tutorial why first it work good

**Comment by stamparm** [comment]
And I still can't understand what is your problem. Just to state couple of things from your original issue post:

1) `becouse i use another usb wireless and change mac`
2) `The output is always for example databe sql windows 7 for example afther " shutdown "`
3) `no work more with any site is my problem i think becouse i have talk with my friend`

How can anybody help you here if there is nothing useful being written here. I really don't understand a thing what is going on.

**Comment by cacaocaca** [comment]
1. I want try another wirelles usb
2. The output is always of name of server but dont  show information schema ecc 
3. My friend try the same site for look if work and work but for me no work .

**Comment by stamparm** [comment]
`The output is always of name of server but dont show information schema` <- really don't know what this means. Have you written anywhere the command you are trying to use?

**Comment by cacaocaca** [comment]
sqlmap --tor --tor-type=SOCKS5 --check-tor -u "www.site.com" --dbs --level=3 --risk=3 --beep --timeout=25 --time-sec=25 --banner --random-agent --no-cast

**Comment by stamparm** [comment]
Sorry, but I honestly don't understand what is the problem here.

**Comment by cacaocaca** [comment]
When i choose y/N "N" sqlmap shutdown but i cant continue i can t do -D blabla becouse i dont see the name of this part
