### ISSUE TITLE
''--start'' command from a specific column

### ISSUE THREAD

**Issue by nathanlian** [sqlmapproject/sqlmap#1824]
Hi,
Went back to an old dump and wanted to update it with recent changes.
The table contained 2500 rows and now contains 3000.
Using command "--start=2501" I can skip what was already dumped before.
However, sqlmap is starting from row 2501 of what appears the be the first column in that table. In my case, column "email" which is organized from 0 to Z.
I would like to make it start from row 2501 in a specific column. In my case, column "registration_date". So it will actually dump the new entries.
Command ''--where'' seems to be what I need but it does not work in my case (using command "where=registration_date>21/08/2015 1:42". Does this command only takes numerical value to work?

**Comment by erwinsalarda** [comment]
I like the question. I never used  the --start command. Can you give me and
example. How to use this command.

**Comment by nathanlian** [comment]
Let's you are in database olol and in table koko and that tables contains 3000 entries and that you only are interested in dumping the last half of that table, you would do:
... -D olol -T koko --start=1500 --dump

this way, it skips the first 1500 entries that you are not interested in dumping. (useful if you lost your session file for example)

**Comment by stamparm** [comment]
There is no way how to recognize what was old and what is new. Also, there could be deleted and/or updated entries. You can't expect from a SQLi tool to be one with the DBMS.

You can try to use `--where` option in your case (if it suits your needs)

**Comment by nathanlian** [comment]
--where option does not work in my case
I don't care about deleted or updated entries from previous rows.
I just want the ones from row 2501 in column "registration_date"
With command --start=2501, I am getting exactly what I want but from column "email" 
"email" is the first column of my table which contains 10 other columns.

Would that be possible to have a command like: "start=C registration_date, 2501"
Start=C, x
C=specify column name, x= specify row number.

**Comment by stamparm** [comment]
"I don't care about deleted or updated entries from previous rows." <- no comment. Closing this down

**Comment by stamparm** [comment]
"I just want the ones from row 2501 in column "registration_date"" <- I would highly suggest you to learn something about databases in the first place. Also, after a comment like " I don't care about deleted or updated entries from previous rows" I can only conclude that you don't have any idea what is going on there. Really can't help you.
