### ISSUE TITLE
Sqlmap will not dump data from a table with 53029 entries

### ISSUE THREAD

**Issue by vxnuke** [sqlmapproject/sqlmap#1827]
Sqlmap will not dump data from a table with 53029 entries.

If i use --sql-shell and run "select * from table" it works fine but using --dump command it just keeps displaying the text below over and over again and goes no where.

[09:57:11] [INFO] retrieved: 53029
[09:57:30] [INFO] retrieved: 53029

**Comment by stamparm** [comment]
Have you tried to run sqlmap with `--dump -v 3` to see if it sends any queries. Also, it is likely that those entries are not dumped (because of xyz problem).

Are you able to GET FULL dump in `--sql-shell` mode, or you are just guessing that it should work?

**Comment by vxnuke** [comment]
verbose shows 
vxnuke' AND ORD(MID((SELECT IFNULL(CAST(COUNT(card_categoryid) AS CHAR),0x20) FROM database1.mytable),1,1))>48 AND 'ItFj'='ItFj

it loops through grabs 53029 using the command above first number 5 then 3 etc.. then once it completes it starts again and grabs 5 with the same command only part that changes through loops is AND 'ItFj'='ItFj' 

I have tried --sql-shell and doing "select * from mytable" works and prints data like it is suppose to

**Comment by stamparm** [comment]
Does it send just 10 queries or 10000 queries

**Comment by vxnuke** [comment]
it sends random amount of queries i think it maybe checking columns to see if they have any data in them ill just let it run for a bit as there are a few columns and ill get back to you

**Comment by vxnuke** [comment]
it is working now. looks like it was checking columns weird though that it prints out 53029 for every column that it checks
