### ISSUE TITLE
Information of tamper

### ISSUE THREAD

**Issue by cacaocaca** [sqlmapproject/sqlmap#1830]
Hi where  i can study the tamper of sqlmap?How i can know what tamper i need to choose for every site ? Becouse for some site i have slow result and when i do --identify-waf slqmap don t see waf detected at the end the resuld of dumper is very very slow and i think maybe is problem of firewall for it i ask that

**Comment by stamparm** [comment]
For tamper scripts you have to manually check what works and what doesn't work against the site. There is no magic bullet here. There are tons of different WAFs (or similar protections) today and each of those has some strengths and weaknesses.

In short, without manual checking of site's protection rules you won't be able to properly choose tamper script(s)

**Comment by cacaocaca** [comment]
Thanks for your answer what i need to do for check that for example if i do --identify-waf sqlmap dont  detected waf so what i need to becouse  the output of information schema is very slow 1 minute for each letter so what is this problem firewall or other ? How i can resolve i need choo se the right tamper or the problem is other ? If i can resolve that manually tell me the command so i can see what tamper i can choose . Thanks .

**Comment by stamparm** [comment]
1) `--identify-waf sqlmap dont detected waf` <- this is not true. sqlmap doesn't IDENTIFY waf, not DETECT (even the switch says `--identify-waf`)
2) `output of information schema is very slow 1 minute for each letter so what is this problem firewall or other` <- in lots of cases this depends on the affected SQL statement itself. In some cases affected part of the SQL statement is performing injected payload multiple times (e.g. INNER JOIN). Also, if lowering down `--time-sec` to e.g. `1` doesn't help in most cases you'll just have to deal with it
3) `If i can resolve that manually tell me the command so i can see what tamper i can choose` <- I am constantly repeating to other users too. There is no magic bullet here. If you want to use tamper scripts you'll have to know how is vulnerable web application (and/or WAF) is dealing with the injected payload. You have to MANUALLY find what is the proper way to bypass the protection. If you are not able to do it, no automated tool will help you
