### ISSUE TITLE
Option to continue in case of "too many 4xx and/or 5xx HTTP error codes"?

### ISSUE THREAD

**Issue by jeroen-80** [sqlmapproject/sqlmap#1834]
Hi,

I want to test an application that uses a username and password as inputs. Based on the credentials the http response codes change:

- correct username AND correct password = http 200
- incorrect username OR incorrect password = http 401

If I run sqlmap on the username field it obviously generates a lot of 401s. This is a reason for the tool to stop:

too many 4xx and/or 5xx HTTP error codes

However I'd like to continue the test. Is there a option to to this? If not: is it possible to add such a flag? Thanks!

Cheers,

Jeroen

**Comment by stamparm** [comment]
`--ignore-401        Ignore HTTP Error 401 (Unauthorized)`
