### ISSUE TITLE
Strange characters on data retrieval...

### ISSUE THREAD

**Issue by iwantaturboman** [sqlmapproject/sqlmap#1836]
Hi all, sorry if it was already asked but can someone explain what sort of characters are : 
`\x04A\x08\x04A\x04A\x83p8\x04AA\`
It happens only on a `password` column. Binary data ?

Regards,

**Comment by stamparm** [comment]
It is binary data. With the latest commit I've unhide an option `--binary-fields` where you can mark columns containing binary values and the retrieved values will be presented in hexadecimal format. Afterwards you can try to crack those values with some other tool (e.g. john) if sqlmap won't be able to recognize it

**Comment by stamparm** [comment]
```
    --binary-fields=..  Result fields having binary values (e.g. "digest")
```

**Comment by iwantaturboman** [comment]
Hi all, thanks for your answer.
If i understand well, this command line : 
`sqlmap.py -u www.target.com -D database -T user -C username,password --dump`
give me this : 
username : `admin`
password :  `\x04A\x08\x04A\x04A\x83p8\`
Then i launch this ?
`sqlmap.py -u www.target.com -D database -T user -C password --binary-fields=\x04A\x08\x04A\x04A\x83p8\`

I thought it was something like : 
`sqlmap.py -u www.target.com -D database -T user -C password --binary-fields=password'

**Comment by stamparm** [comment]
.. --binary-fields password --fresh-queries
