### ISSUE TITLE
ICMP shell possible DLL hijacking, LoadLibraryA

### ISSUE THREAD

**Issue by davidsilveiro** [sqlmapproject/sqlmap#1850]
**LoadLibraryA
extra/icmpsh/icmpsh-s.c:161
extra/icmpsh/icmpsh-s.c:169
extra/icmpsh/icmpsh-s.c:178**

DLL paths could be exact to mitigate? ^^

**Comment by stamparm** [comment]
Not sure that I understand what are you talking about. This is a standard way to call `LoadLibraryA`

**Comment by davidsilveiro** [comment]
Hey @stamparm 

Basically, when LoadLibraryA is called without an exact path to the DLL in this case, and assuming that SafeDllSearchmode is enabled on the windows host.

It searches for it in this order:

1.The directory from which the application loaded.
2.System directory (C:\Windows\System32).
3.The 16-bit system directory (C:\Windows\System).
4.The Windows directory (C:\Windows).
5.The Current Directory.
6.Directories that are listed in the PATH variables.

Allowing for a different DLL to be loaded in its place, and executed.

**Comment by stamparm** [comment]
Ok. So, I guess that you are suggesting to use absolute `C:\Windows\System32` paths. Can I just ask why? I don't see a real threat in "DLL hijacking" of sqlmap's ICMP server executable, or am I wrong?

**Comment by stamparm** [comment]
http://stackoverflow.com/a/18553661

"On 64-bit editions of Windows, 64-bit DLLs go in System32 folder, and 32-bit DLLs go in the SysWOW64 folder" -> so, as `icmpsh-s` is a 32-bit application, to prevent potential DLL hijacking you are suggesting to automatically adjust the loading path according to the backend platform architecture. As said before, I don't see a real threat here to mess with the absolute paths here

**Comment by davidsilveiro** [comment]
@stamparm Thought I'd mention it anyway, thanks for taking the time dude!
