### ISSUE TITLE
sqlmap escape uri that should not escape

### ISSUE THREAD

**Issue by chouex** [sqlmapproject/sqlmap#1852]
for example:
```
/index.php?/action
```
where `/action` will be escape as `%2Faction`, which cause codeigniter response 404 not found.

**Comment by stamparm** [comment]
Please show me the documentation which says otherwise

**Comment by chouex** [comment]
i tried remove the `?` after `index.php` is work, sqlmap did not escape the `/`, seems sqlmap force escape `/` after `?` which chrome did not. chrome will only escape other special char like space(`%20`).

see
https://tools.ietf.org/html/rfc3986#section-3.4
```
 The query component is indicated by the first question
   mark ("?") character and terminated by a number sign ("#") character
   or by the end of the URI.
query       = *( pchar / "/" / "?" )
```
query string support `/` and even another `?`


https://www.codeigniter.com/userguide3/general/urls.html

`/` and `%2F` have different behavior,


this is the header which chrome send
```
POST /index.php?/action HTTP/1.1
```
this is the header which sqlmap send
```
[03:19:56] [TRAFFIC OUT] HTTP request [#1]:
POST /index.php?%2Faction HTTP/1.1
```
`sqlmap -u "https://hostname/index.php?/action" --data="payload=a" -v 3`

you should be able to reproduce it.

**Comment by stamparm** [comment]
It is not a problem of reproducibility (I know what it does), the problem is your case/example. It is invalid. I can't find inside https://www.codeigniter.com/userguide3/general/urls.html any mention of using `/action` after the character `?`. So, query starts with character `?` and everything afterwards has to be properly urlencoded.

**Comment by stamparm** [comment]
p.s. neither of your provided references proves your point/claim

**Comment by chouex** [comment]
some website will set url based proxy to cgi backend

for example:
`http://www.laozistudies.org/index.php?/category/26`
this website will not proxy_pass to php-fpm backend if url without `?`

if sqlmap escape uri, web application will receive different query string which cause 404
`http://www.laozistudies.org/index.php?%2fcategory%2f26`

i think sqlmap should process `?` as-is since `?` is a valid url charater

**Comment by stamparm** [comment]
`?` is processed as is (not URL escaped). `?` in all normal applications represent a start of query, and inside a query parameter names and parameter values should be url encoded

**Comment by stamparm** [comment]
Nevertheless, find it "patched" now with the latest revision

**Comment by chouex** [comment]
sorry for my wrong expression, i mean query string that **after** `?` . eg `?/segment/in/some/web/framework`
