### ISSUE TITLE
how to bypass imperva waf 

### ISSUE THREAD

**Issue by Ays4R-H4rB** [sqlmapproject/sqlmap#1858]
i try a lot of ways and tamper scripts etc securesphere.py , but all useless , is that any ideas to bypass it ?

**Comment by stamparm** [comment]
Please don't open this kind of issues. You should research yourself and come back with results, if any

**Comment by 0000x0** [comment]
securesphere.py in sqlmap located at /tamper. ... AND 1=1 * Output: AND 1=1 and '0having'='0having' 

 Useful for bypassing Imperva SecureSphere
