### ISSUE TITLE
Specify parameter when using request file?

### ISSUE THREAD

**Issue by pr0letariat** [sqlmapproject/sqlmap#1859]
This is the command I am using:

`sqlmap -r sqli -p id --dbms=MySQL --force-ssl --proxy=http://127.0.0.1:8080`

But it injects into parameters other than `id`. Is there a way to specify the parameter when using a request file?

I also tried putting a `*` after the `id` parameter in the file but this also didn't work.

The request is a `POST` request if that makes any difference.

**Comment by stamparm** [comment]
![1](https://cloud.githubusercontent.com/assets/921555/15210131/1e2f8764-1835-11e6-90da-98c4262046a7.png)
