### ISSUE TITLE
Can you add supporting for json and xml format vaule for specified parameter?

### ISSUE THREAD

**Issue by KibodWapon** [sqlmapproject/sqlmap#1861]
Hi:
As far as I know sqlmap only support the http request which conent type is json.,but does not support param value of json or xml formmat.
for example:
htttp://test.com/?a={"p":"v"}
htttp://test.com/?a=<xm><a>1</a></xm>

burp has already add these feather,I found it's very usefull .
So,Can you add  these functionality.

**Comment by KibodWapon** [comment]
the second example is `htttp://test.com/?a=<xml><b>111</b></xml>`
github's web editor filtered out xml

**Comment by stamparm** [comment]
![1](https://cloud.githubusercontent.com/assets/921555/15219188/0f39ce62-1863-11e6-920c-cc8c17f0b1fe.png)

**Comment by stamparm** [comment]
Also, with the latest revision:

![1](https://cloud.githubusercontent.com/assets/921555/15219802/6c702d68-1865-11e6-80c8-d2d023c41ea7.png)

**Comment by KibodWapon** [comment]
Great!! thanks for your reply
