### ISSUE TITLE
sqlmap presents a false positive as vulnerable after identifying it as a false positive.

### ISSUE THREAD

**Issue by sternma** [sqlmapproject/sqlmap#1863]
![image](https://cloud.githubusercontent.com/assets/16885220/15229319/7a042eae-185e-11e6-9acc-696abf2c7dd6.png)
Why does it present it as vulnerable? If I were to not test the rest of the parameters, it ends the test but acts like it found no vulnerabilities (understandably, because it is a false positive).  Why does it seem to offer it as an option for an injection point regardless of identifying it as not possible?

**Comment by stamparm** [comment]
This should be fixed 6 hours ago

**Comment by sternma** [comment]
Ah ok my bad, my most recent revision was the one from yesterday.  Haven't updated to the one earlier today yet.
