### ISSUE TITLE
Can't retrieve password of database administrator

### ISSUE THREAD

**Issue by iwantaturboman** [sqlmapproject/sqlmap#1869]
hi all,
recently i found a vulnerability on a website. After some queries, i was able to : 

1. ☑ list all databases with `--dbs` command

1. ☑ list all `tables` and `columns` of databases

1. ☑ identify back-end DBMS with `--banner` command

1. ☑ list current user "administrator" who is DBA

I'm very frustrated 'cause i was not able to retrieve password of "administrator".
Here is the log of command line `--passwords` : 
```
[INFO] fetching number of password hashes for user 'administrator'
[ERROR] detected invalid data for declared content encoding 'gzip' ('size too large')
[WARNING] turning off page compression
[CRITICAL] unable to connect to the target URL or proxy. sqlmap is going to retry the request(s)
............................. (done)
[WARNING] it is very important to not stress the network adapter during usage of time-based payloads to prevent potential disruptions
[WARNING] in case of continuous data retrieval problems you are advised to try a switch '--no-cast' or switch '--hex'
[WARNING] unable to retrieve the number of password hashes for user 'administrator'
[ERROR] unable to retrieve the password hashes for the database users (probably because the session user has no read privileges over the relevant system database table)
```
Tried also with `--no-cast` then `--hex` options without success.
About target : 
- debian server
- sqli POST DATA
- Type : AND/OR time-based blind

**Comment by stamparm** [comment]
Why do you raise issues where it is obvious that either permissions or some protection is behind. I'll start to close this kind of issues, from anybody, no questions asked in future

**Comment by stamparm** [comment]
When you have a crazy large gzip responses this is usually a third party protection. In lots of cases this can be found on Russian sites

**Comment by iwantaturboman** [comment]
Hi, the "crazy large gzip response" was only due because of i refused a redirection. When i accepted the redirection but refused to post DATA on redirected page, this message disappears.
But seriously, how is it possible, if current user is database administrator, to not extract its password ?

**Comment by stamparm** [comment]
How? There are lots of cases. In some cases dummy blacklisting is used by the web apps (e.g. `password`). In some cases there are no password hashes at predefined locations (maybe the authentication is not password based at all). In some cases, all users (even DBA) can have revoked read privileges on critical system tables. There are really lots of combinations.
