### ISSUE TITLE
Performace issues when using time based blined sql injection

### ISSUE THREAD

**Issue by fabianfrz** [sqlmapproject/sqlmap#1870]
Some values of some tables are predictable if a blind sql injection is used.

for example if you read the privileges of the database users or if the host part of a user starts with "127" - a next guess could be "127.0.0.1".

Can sqlmap be extended so it can use some files for this predictions or make it possible to enter a hint on the keyboard.

**Comment by stamparm** [comment]
1) You can try to use `--predict-output` and fill the `txt/common-outputs.txt` with common output
2) You are not the first one that asks this. There is no (cross-platform) mechanism in Python that could do the job and in non-blocking mode read keys one by one

**Comment by fabianfrz** [comment]
Is it possible to add '--predict-output' to the help page it will show when -h is used?

**Comment by stamparm** [comment]
No, because it is already there

**Comment by stamparm** [comment]
```
$ python sqlmap.py -h
         _
 ___ ___| |_____ ___ ___  {1.0.5.27#dev}
|_ -| . | |     | .'| . |
|___|_  |_|_|_|_|__,|  _|
      |_|           |_|   http://sqlmap.org

Usage: python sqlmap.py [options]

Options:
  -h, --help            Show basic help message and exit
  -hh                   Show advanced help message and exit
...
```

Have you noticed the option `-hh`? By using it you get:

```
$ python sqlmap.py -hh
...
  Optimization:
    These options can be used to optimize the performance of sqlmap

    -o                  Turn on all optimization switches
    --predict-output    Predict common queries output
...

**Comment by fabianfrz** [comment]
Thanks for your help - have not seen the -hh flag
