### ISSUE TITLE
New password hash types to incorporate

### ISSUE THREAD

**Issue by stamparm** [sqlmapproject/sqlmap#1881]
http://www.passwordtool.hu/

**Comment by stamparm** [comment]
https://hashcat.net/wiki/doku.php?id=example_hashes

**Comment by stamparm** [comment]
http://cgit.drupalcode.org/drupal/tree/includes/password.inc?id=a584af62514ba7ec37b82b0c7b17081fcca4c5e0

**Comment by stamparm** [comment]
https://pythonhosted.org/passlib/lib/passlib.hash.md5_crypt.html

**Comment by stamparm** [comment]
MD5_CRYPT:
http://www.sabren.net/code/python/crypt/md5crypt.py

**Comment by davidtavarez** [comment]
Sometime sqlmap get the MD5 password through a --binary-field but is not recognized it as a MD5 field. I guess it could be great if sqlmap could do it.

**Comment by stamparm** [comment]
@davidtavarez true. I just wouldn't want the situation where random garbage (e.g. coming from time-based SQLi) is recognized as MD5

**Comment by stamparm** [comment]
@Ekultek it is not problem for me to (e.g.) treat 16 bytes of garbage as MD5. Problem is that people having false-positives or some strange problems with time-based SQLi will start to report back that they have a positive of a (e.g.) MD5 hash, while in reality it is most probably still a garbage data

**Comment by Ekultek** [comment]
@stam yeah that makes sense man, it'd be super cool to do though.

**Comment by stamparm** [comment]
http://zonesite.tk/index.php?sub=hash_calculator
