### ISSUE TITLE
Better CSV escaping

### ISSUE THREAD

**Issue by maaaaz** [sqlmapproject/sqlmap#1882]
Hello,
I would like to report a bug related to the default CSV output, having the `,` delimiter: any column containing data with `,` inside (for instance, passwords) is not escaped in the output and then gives a hard time to the user :)

Please use the python CSV module which handles all those corner cases perfectly.
Cheers.

**Comment by stamparm** [comment]
```
$ python sqlmap.py -u "http://debiandev/sqlmap/mysql/get_int.php?id=1" --dump -T users -D testdb
...
Database: testdb
Table: users
[6 entries]
+----+--------+---------------------------------------------+
| id | name   | surname                                     |
+----+--------+---------------------------------------------+
| 1  | luther | blissett                                    |
| 2  | fluffy | bunny                                       |
| 3  | wu     | ming                                        |
| 4  | NULL   | nameisnull                                  |
| 5  | heeej  | 179ad45c6ce2cb97cf1029e212046e81 (testpass) |
| 6  | foobar | password with , comma                       |
+----+--------+---------------------------------------------+

[20:36:27] [INFO] table 'testdb.users' dumped to CSV file '/home/stamparm/.sqlmap/output/debiandev/dump/testdb/users.csv'
[20:36:27] [INFO] fetched data logged to text files under '/home/stamparm/.sqlmap/output/debiandev'
stamparm@Laptop:~/Dropbox/Work/sqlmap$ cat /home/stamparm/.sqlmap/output/debiandev/dump/testdb/users.csv
id,name,surname
1,luther,blissett
2,fluffy,bunny
3,wu,ming
4,NULL,nameisnull
5,heeej,179ad45c6ce2cb97cf1029e212046e81 (testpass)
6,foobar,"password with , comma"
```

**Comment by stamparm** [comment]
Please do the proper testing before raising an issue.

Cheers

**Comment by maaaaz** [comment]
Sorry I forgot to mention that I encountered this bug not using the `dump` option but rather inside an `sql-shell` as I couldn't dump the entire DB.

Sorry for being a noob but tell me how could I execute an arbitrary query (`--sql-query`?) AND having a proper CSV output file ?

**Comment by stamparm** [comment]
But, `--sql-shell` was never meant to be used for (proper) CSV output. It just gives you nice formatted output

**Comment by stamparm** [comment]
You can't expect it to give you CSV as people use it for all sorts of "garbage" queries

**Comment by maaaaz** [comment]
For sure, but for `sql-query` (which aims to have a unique reliable query to be executed), wouldn't it be possible to have a nice CSV output ?
