### ISSUE TITLE
all tested parameters appear to be not injectable.

### ISSUE THREAD

**Issue by Kamerabuilt** [sqlmapproject/sqlmap#1883]
Hi, 

I have raised the **level and risk** to 3 on sqlmap, with the same result. 

This seems all fine and the site might as well be secure, however, when I send manually the commands SLEEP(seconds) or BENCHMARK(command), the server waits for 15 to 25 seconds before replying. 

Are there further tests or methods I could try to validate if the login form is truly vulnerable or not? 

I have tried the following options as well:

--hpp 
--identify-waf -v 3

**Comment by stamparm** [comment]
You haven't stated the sqlmap command (with options and switches) that you used. Also, you haven't stated how you tested `SLEEP` and `BENCHMARK` against the site (URL?)

Generally, when you are dealing with login forms you should use higher level and risk (e.g. `--level=3 --risk=3`)

**Comment by Kamerabuilt** [comment]
Hi, I did mention that I have tried level 3 and risk 3, but here is the exact command used: 
sqlmap -u "URL" --data "k_username=abc&k_password=def&submit=Submit" --level 5 --risk 3 --hpp --dbs --time-sec 25

Originally BurpSuite found an SQL injection in the following parameters for the same URL: 
k_username=ee'(select*from(select(sleep(20)))a)'&k_password=ee&submit=Submit

I did the manual tests through Burp's repeater using the following: 
ee'(select*from(select(sleep(20)))a)'
ee'(select*from(BENCHMARK(100000000, rand()))a)'

The website takes 20 seconds or more when replying back. However if I submit the form without the sleep or benchmark commands, it takes on average 500ms. 

Any suggestions?

**Comment by stamparm** [comment]
This is something that sqlmap doesn't have problems with.

Also, usage of `--hpp` in this case is something that potentially includes the problem. If the web site is not written in ASP I am not sure why have you decided to use it.

If everything fails, please send me private details to `miroslav@sqlmap.org`. As said, sqlmap doesn't have problems with things like this.

**Comment by stamparm** [comment]
User forgot to mention that sqlmap detected some form of protection

**Comment by phplbw** [comment]
``` bash
[04:11:09] [CRITICAL] all tested parameters do not appear to be injectable. Try to increase values for '--level'/'--risk' options if you wish to perform more tests. If you suspect that there is some kind of protection mechanism involved (e.g. WAF) maybe you could try to use option '--tamper' (e.g. '--tamper=space2comment')
```

**Comment by umerk257** [comment]
> User forgot to mention that sqlmap detected some form of protection

Hello stamparm I tried 100 time MySQL but I get same issue (e.g. WAF) maybe you could try to use option '--tamper' (e.g. '--tamper=space2comment') please guide me I am very thankful to you I use Burpsuit too please guide me ASAP!

**Comment by Aran276** [comment]
> ```shell
> [04:11:09] [CRITICAL] all tested parameters do not appear to be injectable. Try to increase values for '--level'/'--risk' options if you wish to perform more tests. If you suspect that there is some kind of protection mechanism involved (e.g. WAF) maybe you could try to use option '--tamper' (e.g. '--tamper=space2comment')
> ```

i got seems like this too

**Comment by Aran276** [comment]
> > User forgot to mention that sqlmap detected some form of protection
> 
> Hello stamparm I tried 100 time MySQL but I get same issue (e.g. WAF) maybe you could try to use option '--tamper' (e.g. '--tamper=space2comment') please guide me I am very thankful to you I use Burpsuit too please guide me ASAP!

i have try it but it same

**Comment by sbtcoles** [comment]
Was a solution ever found or did you give up like I'm about to do?  Any suggestions for a sqlmap alternative that works?

**Comment by ZeroHero77** [comment]
Are you using wireless or plugging into the ethernet cable?
