### ISSUE TITLE
tamper for time based

### ISSUE THREAD

**Issue by jackpit110** [sqlmapproject/sqlmap#1897]
I need a tamper or trick to use tamper scripts for words like WAITFOR, DELAY, INFORMATION_SCHEMA and ...
For example when I use tamper=randomcomments.py sqlmap will use this tamper for words like SELECT and FROM like below
`S/**/LEC/**/T FR/**/M`
But for WAITFOR DELAY sqlmap does not use this tamper
How should I do this?

**Comment by stamparm** [comment]
That technique you use is invalid. Somebody made a false "claim"/"research" claiming that it works, while it doesn't. DBMS replaces `/**/` with whitespace, hence it is INVALID way how to bypass blacklisted keywords

**Comment by stamparm** [comment]
I would just like to know which bright mind first started with this crap of bypassing WAFs this way

**Comment by jackpit110** [comment]
This is not matter, I have a way to bypass waf
I just want to know how I should change this or from which xml file I can change this

**Comment by stamparm** [comment]
My last comment on this issue:

`txt/keywords.txt`
