### ISSUE TITLE
Characters are being filtered out that I need in

### ISSUE THREAD

**Issue by Snipercatz** [sqlmapproject/sqlmap#1910]
I'm working on a tricky sql injection (cause that's what i do on friday nights sighhh) anywho sqlmap is having a difficult time identifying the vulnerability due to the way the input is being handled (I'm assuming).  
Long story short I found that by adding '&pagination_sort_by[1]=1'' at the end of any query on a particular site will trigger the vulnerability.  However, sqlmap isn't recognizing it.  The brackets are being filtered I'm guessing?  Without the brackets around the '1', the response remains true even with the asterisks correctly provided so obviously sqlmap can't detect it.   Does anyone know how I can tweak my request in a way which would keep the brackets around the 1 like needed?  Thanks in advance for the advice.

**Comment by stamparm** [comment]
I can't reproduce. Those brackets are left:

```
$ python sqlmap.py -u "testphp.vulnweb.com/artists.php?artist=1&pagination_sort_by[1]=1" -v 5
...
[01:40:55] [TRAFFIC OUT] HTTP request [#7]:
GET /artists.php?artist=1%27Yzdpin%3C%27%22%3EqMDSpD&pagination_sort_by%5B1%5D=1 HTTP/1.1
Accept-language: en-us,en;q=0.5
...
```

url decoded:
```
&pagination_sort_by%5B1%5D=1 -> &pagination_sort_by[1]=1
```

**Comment by stamparm** [comment]
ping?
