### ISSUE TITLE
--autotamper

### ISSUE THREAD

**Issue by xinghuacai** [sqlmapproject/sqlmap#1911]
I wish there would be an optional argument,--autotamper,I have done some work myself,this --autotamper means sqlmap will auto select a good combination of tamper scripts to anti waf,
my own script here:
https://github.com/xinghuacai/bypass_waf/blob/master/bypass_waf.py
hope this will come true,actually,I would like to do the job to mantain "--autotamper" optional argument to make it follow the anti-waf tamper scripts and make it better and better  if I could get some payment support from sqlmap official orgnize group:)

**Comment by stamparm** [comment]
Payment? Closing this down

**Comment by stamparm** [comment]
Code is pretty bad so please don't do it freely neither. Make a new project (e.g. autosqlmap or something) on your own, put a donate button and cross your fingers.
