### ISSUE TITLE
wheres the docs for api?

### ISSUE THREAD

**Issue by Dj-jom2x** [sqlmapproject/sqlmap#1913]
wheres the docs for api?

**Comment by stamparm** [comment]
Currently nowhere. What are you interested about?

**Comment by Dj-jom2x** [comment]
im done :) i figure it out by my self ...

about interest ... i want to re create havij :) i dont like copy paste thingy xD so i think i need to create a user friendly one ... btw good job with this script :)

**Comment by tampe125** [comment]
I'm curious about it, too.
Can we have some info about it (or at least some README to read)?

**Comment by stamparm** [comment]
@tampe125 which part are you interested in? In calling sqlmap's functionality from other programs or plain remote calls of sqlmap?

p.s. I'll write the README when I catch time for it.

**Comment by stamparm** [comment]
p.p.s.: using `sqlmapapi.py` for remote calls

#### A) server:

![server](https://cloud.githubusercontent.com/assets/921555/15715101/863a9f2c-281d-11e6-8d61-af533e31edd3.png)

#### B) client:

![client](https://cloud.githubusercontent.com/assets/921555/15715108/915e0920-281d-11e6-85d4-12163edbc428.png)

**Comment by cherehapa** [comment]
Hello. 

I wont a dirty check for SQL injections in a buffer directly from my python script.
is it possible to use sqlmap with python in QA scripts injecting code into a string? 

I.e. something  like:
`
#!/path/to/python
from sqlmap import GenerateInjectionSample
StringWithSQLiAttempt=[]
# get an array w/ strings with diffrent variants of injection attemps
# (i.e. one appended with ";" + SQLCodeToInject  , 
# second with '1 ==1 AND ' + SQLCodeToInject and so on...  )
StringWithSQLiAttempt=GenerateInjectionSample(MyString,InjectionType,SQLCodeToInject)
passThisToMy_API_endpoint(StringWithSQLiAttempt,other_params_i_use)
`
If yes - where to look for a usage samples?

**Comment by stamparm** [comment]
@cherehapa no, it is not possible nor we tend to implement it. Though, you can inspect payloads in numerous ways. By 1) running sqlmap with `-v 3` or 2) by using a proxy in between (e.g. `--proxy`) or 3) inspecting complete traffic dump with `-t traffic.txt`

**Comment by cherehapa** [comment]
Thank  you for clear answer. Pity that I have to prepare injection samples myself when similar work has been already done in a few tools.  May be you're aware of any library w/ similar functionality? I've spent half day googling, but got only a lot of howtos/samples/scanners, but not in a library form. :(

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/Usage#api-rest-json
