### ISSUE TITLE
sqlmap and privoxy proxychain - Cant Establish SSL Connection

### ISSUE THREAD

**Issue by padjodev** [sqlmapproject/sqlmap#1926]
Hi Stamparm, love this tool. I have been away from it for a while but I have been messing with it on a test basis and I have a target which is most certainly vulnerable on my server. The only issue is that it keeps giving a critical error after pulling some data and basically fails with either cant establish ssl connection or if I am in the dumping phase it states "[CRITICAL] connection exception detected in dumping phase (cant establish SSL connection)

Much obliged for any feedback but I thought I should report it.. I am running it on Kali - version is 1.0-dev-nongit-201601030a89

I am running the commands by preceeding them with proxychains - if that makes a difference

**Comment by stamparm** [comment]
Can you please provide options used? Did you used multi-threading? Has sqlmap nagged about any WAF/IDS/IPS? Are you using latest revision?

p.s. You could also send me a target url to `miroslav@sqlmap.org` (if sqlmap hasn't nagged about WAF/IDS/IPS)

**Comment by padjodev** [comment]
I simply used the following and no there was no issues with waf etc:
proxychains sqlmap -u http://example.com/page.php?id=2 --dbs--dbms=mysql

Apologies but I can't disclose the URL.

**Comment by stamparm** [comment]
Well, I am not sure how to help you here :). Can you give anything useful? Like, have you tried to debug it yourself (e.g. Wireshark). This way I am pretty limited

**Comment by stamparm** [comment]
p.s. maybe one of proxies is causing problems. Have you tried changing them? Also, you could try to rerun with `--disable-precon` just in case

**Comment by tr4nscr1pt** [comment]
remove https:// from your link , put www.website.domain
