### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by seabird1992** [sqlmapproject/sqlmap#1929]
i am using sqlmap to test sql injection,when testing mysql union query it mentions that sqlmap is using "1 to 10 column",but the testing site is vulnerable for 11 column,and using sqlmap can't detect the injection site,how to solve this problem?

**Comment by kidol** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/Usage#number-of-columns-in-union-query-sql-injection

**Comment by gavz** [comment]
for me , after update sqlmap=1.0.6.0#dev not dumped sql database

**Comment by seabird1992** [comment]
i see it,thks a lot~
