### ISSUE TITLE
CSRF Different name in Header and Form Field

### ISSUE THREAD

**Issue by nikhil-pandey** [sqlmapproject/sqlmap#1953]
Currently, is there any way to define different names for CSRF Header and form field?

**Comment by stamparm** [comment]
Nope. Why would you need this?

**Comment by nikhil-pandey** [comment]
@stamparm Need to perform test on a website that has different cookie name and form field name

**Comment by stamparm** [comment]
Out of curiosity, what are their names?

**Comment by nikhil-pandey** [comment]
Cookie name: SOMEPREFIX_SITENAME_csrf_cookie_name
Form Field: SITENAME_csrf_token_name

**Comment by stamparm** [comment]
Closing this down as it is too specific. If anybody else comes with the similar problem I'll consider some workaround or a new option (though I am not a fan of new options)
