### ISSUE TITLE
sqlmap doesn't work on nethunter

### ISSUE THREAD

**Issue by Doveyang** [sqlmapproject/sqlmap#1969]
![screenshot_20160619-004346](https://cloud.githubusercontent.com/assets/19889990/16172258/7638e104-35b7-11e6-904d-53ceeedcd77b.png)

**Comment by stamparm** [comment]
Not sqlmap's issue. Those are standard python libraries. Somebody did a bad job on that Python port

**Comment by Doveyang** [comment]
@stamparm   So how can I fix it?

**Comment by stamparm** [comment]
You should contact those responsible for that Python port. I don't know who they are

**Comment by Doveyang** [comment]
@stamparm oh thanks
