### ISSUE TITLE
Data refreshing

### ISSUE THREAD

**Issue by mitros123** [sqlmapproject/sqlmap#1971]
Hello. Sorry if this issue has been reported before, but I searched and I didn't find it.
Please add an option for sqlmap to retrieve the data that have been downloaded again, should the users request that.
For example, when sqlmap has retrieved a table and the user changes something afterwards, when sqlmap is asked to retrieve that table again, it reads it from the disk and does not download it. Please include an option to download it.

**Comment by stamparm** [comment]
`--fresh-queries`
