### ISSUE TITLE
How to use --where on sqlmap

### ISSUE THREAD

**Issue by yingbrooke7** [sqlmapproject/sqlmap#1975]
Dear,
I don't know why i can use --where for my issers.
example: i have column id,name on table person
id counted is 30000.
now, if i use -D abc -T person -C id,name --dump, sqlmap showed for me approximately 2000, can not get more.
So now, i will use --where. i type:
-D abc -T person -C id,name --where="id>2000" --dump or -D abc -T person -C id,name --where="id>2000 and id<2002" --dump, oh no. sqlmap can not get it, i think it's not understand charater ">" or "<" because if i to try --where="id=2000", it is OK.
Can you help me my issues
Thanks!

**Comment by yingbrooke7** [comment]
@stamparm

**Comment by iwantaturboman** [comment]
Hi yingbrooke7. I don't know why your first count is "30000" but this command line : 
`sqlmap -u www.target.com -D abc -T person -C id,name --where "id>2000" --dump`
is the right one.

Regards,

**Comment by yingbrooke7** [comment]
because when i command line:

> sqlmap -u www.target.com -D abc -T person -C id,name --dump

it's only show 2000 value (not show full 30000)
so, i to try command line 

> sqlmap -u www.target.com -D abc -T person -C id,name --where "id>2000" --dump
for get more which id > 2000, but command not work. but i to try id=2000, it's show value which id=2000. 
i think because have big data (~30000) so sqlmap can not show, so i to try with another command is:

> sqlmap -u www.target.com -D abc -T person -C id,name --where "id>2000 and id<2002" --dump
unfornaturely, it's not work. So i think sqlmap not understand command with characters ">" or "<". it's only understand command with "="
Help me plz, tks

**Comment by yingbrooke7** [comment]
i think because my data i want to get is BIG, so sqlmap can not work

**Comment by yingbrooke7** [comment]
when i use command with --where="id>2000". sqlmap show note:

> [WARNING] something went wrong with full UNION technique (could be because of limitation on retrieved number of entries). Falling back to partial UNION technique
[WARNING] the SQL query provided does not return any output
[WARNING] (case) time-based comparison requires larger statistical model, please wait.........(done)

But, when i to command where with another TARGET, it's OK.

**Comment by iwantaturboman** [comment]
1) I suggest you to dump only "id" column of table "person" to see if there are some duplications. Or maybe you have some id with <blank> content. Then open your cvs file to see what happens.
2) If sqlmap doesn't return any output with `--where "id>2000"` command, it's because there are none imo.

**Comment by yingbrooke7** [comment]
thanks.
i to try:

> sqlmap -u www.target.com -D abc -T person -C id --where "id>2000" --hex --dump

It's still don't run
and i to try -start 1 --stop 5 (small value), it's don't work.
I don't why???

However, to try 

> sqlmap -u www.target.com -D abc -T person -C id,name --hex --dump

it's OK, but show only 2000 value. i want to get more (because have 30000 value)
@iwantaturboman

**Comment by stormwin** [comment]
--pivot-column id

**Comment by yingbrooke7** [comment]
@stormwin 
Thank you, but can you help me explain for this example. because i have never use --pivot

**Comment by yingbrooke7** [comment]
i to try:

> sqlmap -u www.target.com -D abc -T person -C id --where "id>2000" --pivot-column=orders_id --hex --dump 

it's still not work

**Comment by stamparm** [comment]
@yingbrooke7 your `--where="id>2000 and id<2002"` should be the right command. This is under assumption that there is data for `id=2001` (while you mentioned there is data for `id=2000` !!!)

in your case I would suggest you to try `--start` and `--stop` first and only if those fail to try to use `--where`

you haven't mentioned which DBMS are you targeting and which sqlmap version do you use (there has been important fixes related a month ago)

**Comment by yingbrooke7** [comment]
Thank @stamparm 
my target have 30000 value. i to try --where="anyvalue" (not only 2000) it,s OK. RUN GOOD.
but i to try --where="id>2000", it's NOT RUN. and if i to try --where=column>value on another target. it's RUN.
i think because my target have big value (30000), i to try --start 1 --stop 5, it's NOT RUN.

**Comment by yingbrooke7** [comment]
i to try --sql-shell for get via database. but it's very slow.

**Comment by iwantaturboman** [comment]
30000 entries doesn't mean you will find 30000 "id" imo.

**Comment by yingbrooke7** [comment]
Thank for all answer and support. My target not accept < or > so sqlmap can not run. I use where BETWEEN for get ALL DATA.
Thanks very much!

**Comment by sharifulgeo** [comment]
Can I use like operator inside where clause e.g. --where "Id like '*AHWR43*'"

**Comment by sharifulgeo** [comment]
Can I use like operator inside where clause e.g. `--where "Id like '*AHWR43*'" `

**Comment by stamparm** [comment]
@sharifulgeo answer at https://github.com/sqlmapproject/sqlmap/issues/750#issuecomment-1282993745
