### ISSUE TITLE
how to DELETE data on target by sqlmap

### ISSUE THREAD

**Issue by yingbrooke7** [sqlmapproject/sqlmap#1979]
Dear,
I have data id,name,email from table person.
So, can you help me command for delete content on all column NAME on tables. And, what's command delete all id,name,email from table.
But, after delete, if have new register, i still get it ok.

Thanks

**Comment by stamparm** [comment]
This doesn't have anything to do with sqlmap. These are basics of SQL injection. Please don't create junk issues.

DELETE only works if there is a possibility of "stacking" (e.g. MsSQL and PgSQL). In those cases you can `--sql-query="DELETE ... FROM ... WHERE"`

**Comment by salwaalem** [comment]
Is there any way to apply this query to mssql please ?
