### ISSUE TITLE
symbol characters in url invalidate scan

### ISSUE THREAD

**Issue by w1ngs** [sqlmapproject/sqlmap#1981]
The following URL for example hosted on aws cloudfront causes problems because of the "#!"

sqlmap -u 'https://app.domain.com/#!/deal/introduction?projectId=9989 -p projectId

It gives the error "all testable parameters you provided are not present within the request data.

If the #! is removed or if I attempt to change it to URL encoding it fails, (It fails in a browser as well), aws cloudfront drops a 404 error about an invalid key.

**Comment by stamparm** [comment]
Everything behind a hash sign is not being transmitted to the target. It is supposed to be handled by browser which can subsequently do further requests (e.g. ajax). All in all you are doing it wrong

**Comment by w1ngs** [comment]
So what is the recommended right way? seems sqlmap doesn't support any url
with a hash in it then? you don't consider this a feature to be fixed?

**Comment by stamparm** [comment]
There is nothing to be fixed. You are supposed to find a valid HTTP request that sqlmap should scan with (e.g.) Burp.

**Comment by stamparm** [comment]
In plainspeak. Turn on browser, turn on Burp, visit that link and see what is going on inside the Burp (there should be some Ajax-like call). Save that request into the request file and provide it to sqlmap with option -r
