### ISSUE TITLE
is it just me or the new version of sqlmap can't detect sql error

### ISSUE THREAD

**Issue by zaidosama** [sqlmapproject/sqlmap#1982]
i have updated my sqlmap to last version 1.0.6.56#dev and it can't detect the error of website and its obvious that the specific sites ( not one site ) is vulnerable with error or blind but i don't know why sqlmap can't detect it 
ps i have tried vulnerable test of these specific sites such vega and other apps and it approves that the website is vulnerable

**Comment by stamparm** [comment]
Please don't compare other scanners to sqlmap as they are only dummy error parsers.

Please make a traffic file with -t traffic.txt and take a look into it. If there is an obvious DBMS error inside while sqlmap doesn't show any WARNING message related, please send that file to miroslav@sqlmap.org. In other cases (such as WAF detected) I'll close this issue as invalid
