### ISSUE TITLE
SQL MSSQL cannot dump DB due to captcha 

### ISSUE THREAD

**Issue by mekoki88** [sqlmapproject/sqlmap#1983]
[14:51:36] [ERROR] potential CAPTCHA protection mechanism detected
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: Cookie #1* ((custom) HEADER)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause

**Comment by stamparm** [comment]
Please don't open junk issues

**Comment by mekoki88** [comment]
what just i cannot bypass captcha ?

**Comment by stamparm** [comment]
People do PhD researches on how to bypass captcha(s) and you are asking this kind of question. No comment

**Comment by imran13298** [comment]
>>>New way of solving ReCaptcha V2<<<
Hello Guys.This method allows passing captchas without the need to emulate browser and sending us images, also it gives 100% solving accuracy.Visit https://2captcha.com/newapi-recaptcha-en.
I'm writing some intro bellow..
1. User enters the page and the recaptcha form is uploaded from google
2. User clicks the checkbox and solves the captcha
3. When the captcha is solved, google checks the answer and returns code to the user in the field <textarea id="g-recaptcha-response"
4. User fills all the forms on the page
5. User sends these forms. At the same time code is sent from the field "g-recaptcha-response"
6. Site receives data from the users and sends a request to google to check code's validity from the field "g-recaptcha-response"
7. Google checks the validity of the code. If the code is valid the site continues processing user's data

Price:1000 for $2,99

Just visit https://2captcha.com/newapi-recaptcha-en
thank you

**Comment by sharoj** [comment]
You can Solve  ReCaptcha By Different way And most easy way.

Very easy way and simple. Save your money and save your Time. 

In one word its an unique and Awesome Recaptcha Solving System.
 its way of solve recaptcha without the use of the browser emulation.
 Here seven benefits  of this 

1. User enters the page and the recaptcha form is uploaded from google
2. User clicks the checkbox and solves the captcha
3. When the captcha is solved, google checks the answer and returns code to the user in the field <textarea id="g-recaptcha-response"
4. User fills all the forms on the page
5. User sends these forms. At the same time code is sent from the field "g-recaptcha-response"
6. Site receives data from the users and sends a request to google to check code's validity from the field "g-recaptcha-response"
7. Google checks the validity of the code. If the code is valid the site continues processing user's data


Its Very cheap Price  only at 2.99 $ 

For More visit:   https://2captcha.com/newapi-recaptcha-en

i like this very much . i think you also like this . So enjoy this Awesome recaptcha Solving

**Comment by Nero935** [comment]
I had the same issue, i needed to make a private server with a full working website and an anti-spam solution but it got bypassed and while i was investigating i found this website https://2captcha.com/newapi-recaptcha-en
It certainly pissed me off but i think you can try to use it.
In my experience it was relatively easy to use, all you have to do is to just follow the instructions given and you will be good to go.
If you need any help you can PM me, i have tried several tools for solving captcha automatically but they were inaccurate, and this one seems to be less of a resource hog than the others.

**Comment by duraidqr** [comment]
if you want to bypass captcha(s) ?and you don't know how to do it !
don't worry i'll tell your it's easy !very easy!
know a days every one is facing this and evry one want to know how it is done so you can do this by going to this link : 
https://2captcha.com/newapi-recaptcha-en (it's a solving recaptcha nocaptcha website where they can earn money or can do automatization solve recaptcha nocaptcha via software)
Only the service can solve nocaptchas.
just visit is and you'll understand every thing one of my friend told me this link and i found it very useeful ,i recommend you to visit it and it'll help you out .
thankyou

**Comment by Nero935** [comment]
if you want to bypass captcha(s) ?and you don't know how to do it !
don't worry i'll tell your it's easy !very easy!
know a days every one is facing this and evry one want to know how it is done so you can do this by going to this link :
https://2captcha.com/newapi-recaptcha-en (it's a solving recaptcha nocaptcha website where they can earn money or can do automatization solve recaptcha nocaptcha via software)
Only the service can solve nocaptchas.
just visit is and you'll understand every thing one of my friend told me this link and i found it very useeful ,i recommend you to visit it and it'll help you out .
thankyou

**Comment by apollo5** [comment]
This is an informative and useful piece of post. The product will contribute much to the formulation of appropriate planning for implementation.[ Nocaptcha bypass](https://2captcha.com/newapi-recaptcha-en) will be helpful

https://2captcha.com/newapi-recaptcha-en
