### ISSUE TITLE
how to get coutine data after the last before

### ISSUE THREAD

**Issue by yingbrooke7** [sqlmapproject/sqlmap#1986]
example:
today, i command a run:

> sqlmap.py -u http://target.com -D data -T table -C columns --where="abc" --dump

If columns in this tables has update daily. so, on tomorrow. i stil use above command, but it get out the OLD DATA (YESTERDAY DATA) not get new??
can u help me?

**Comment by stamparm** [comment]
run `--fresh-queries`
