### ISSUE TITLE
Hi everyone,help me please with SQLmap

### ISSUE THREAD

**Issue by bustudo** [sqlmapproject/sqlmap#1997]
[16:15:25] [WARNING] on PostgreSQL you'll need to use schema names for enumeration as the counterpart to database names on other DBMSes

[WARNING] on PostgreSQL it is not possible to enumerate the hostname  

explain me please , what should i do to dump a information from DB if it cant enumerate, what kind of technique i should to use?

**Comment by stamparm** [comment]
You are using `--hostname` which is not available on PostgreSQL. This is just a name of a host, nothing else. You should be able to `dump a information from DB`

**Comment by bustudo** [comment]
but i am not using  "--hostname" option

**Comment by stamparm** [comment]
Should I guess what are you using?

**Comment by bustudo** [comment]
--level 5 --risk 3   --random-agent   --threads=5 --all --dbms=PostgreSQL  --no-cast

**Comment by stamparm** [comment]
`--all` turns on the `--hostname`

**Comment by stamparm** [comment]
I'll "patch" it

**Comment by stamparm** [comment]
There is nothing to patch here. That is only a WARNING message, not interrupting the retrieval of other data

**Comment by bustudo** [comment]
[WARNING] schema names are going to be used on PostgreSQL for enumeration as the counterpart to database names on other DBMSes
[ERROR] unable to retrieve the number of databases 
[WARNING] on PostgreSQL you'll need to use schema names for enumeration as the counterpart to database names on other DBMSes
now this messages, i use this --level 5 --risk 3   --random-agent   --threads=5 --dbs --dbms=PostgreSQL  --no-cast

**Comment by stamparm** [comment]
Something is blocking your retrieval of "schema names". Nothing to do with sqlmap.

**Comment by stamparm** [comment]
... and especially with `--hostname`

**Comment by bustudo** [comment]
thank you

**Comment by bustudo** [comment]
good luck

**Comment by abhisheksdp** [comment]
hey i am getting the same error can anybody help
