### ISSUE TITLE
no tag 1.0.7?

### ISSUE THREAD

**Issue by LocutusOfBorg** [sqlmapproject/sqlmap#1999]
Not a big deal, I'm just wondering about what broke the crontab that automatically tags the code :)

**Comment by stamparm** [comment]
It is semi-automatic :) (post-commit hook). First commit in month is tagged. As I haven't got anything to commit yesterday, there was no tagging. But, just for you I am going to make one dummy commit (and do the tagging with it)

**Comment by LocutusOfBorg** [comment]
oh!!! sweet, I wasn't aware :)
thanks!

**Comment by LocutusOfBorg** [comment]
BTW not needed to tag it right now, I was just wondering about something broken in the process :)

**Comment by stamparm** [comment]
Okie dokie ;)
