### ISSUE TITLE
Implement anti-CSRF protection bypass

### ISSUE THREAD

**Issue by bdamele** [sqlmapproject/sqlmap#2]
I think that this can be done taking advantage of the object that handles --forms (forms parsing) switch.

**Comment by pich4ya** [comment]
how about csrf token in either javascript  
```
<script>
window.csrf = 'aaaabbbbcccc';
</script>
```
or in JSON response

```
{"csrf":"bf4676dc51856f01"}
```

and how about csrf token which required POST data?
I request the option to extract token using user's regex

**Comment by stamparm** [comment]
@pich4ya those would be non-standard (custom) CSRF protection methods. In those kind of cases you would need to run either Burp or similar tool.

I can make that "regex", but how to know (as it's non-standard), where the end point expects the token to appear? If the answer is "make the option for that too", I'll need to deny as it would become one of those options/switches that nobody uses

**Comment by nu11secur1ty** [comment]
--csrf-url="https://www.blabal.com/tarator/kokazako/?page=8" --csrf-token="token"

;)
