### ISSUE TITLE
again "unable to access item ..."

### ISSUE THREAD

**Issue by tbmn** [sqlmapproject/sqlmap#2015]
sqlmap version: 1.0.7.5#dev
Python version: 2.7.9
Operating system: nt
Command line: sqlmap.py --tor --tor-port=9150 --tor-type=SOCKS5 -u *************
********************************************************************************
********************************** --dbms=Oracle --dbs --technique=B
Technique: None
Back-end DBMS: Oracle (identified)
Traceback (most recent call last):
  File "sqlmap.py", line 142, in main
    start()
  File "lib/controller/controller.py", line 522, in start
    injection = checkSqlInjection(place, parameter, value)
  File "lib/controller/checks.py", line 154, in checkSqlInjection
    configUnion(test.request.char)
  File "lib/core/datatype.py", line 44, in __getattr__
    raise AttributeError("unable to access item '%s'" % item)
AttributeError: unable to access item 'char'

**Comment by tbmn** [comment]
occurs without using tor either

**Comment by stamparm** [comment]
Have you made any changes to xml files? What do you get when you run: git diff?

**Comment by stamparm** [comment]
This doesn't have anything to do with tor

**Comment by stamparm** [comment]
It seems that I'll need to implement integrity checks to prevent invalid user modifications

**Comment by tbmn** [comment]
> Have you made any changes to xml files? 
No.

> What do you get when you run: git diff?
Didn't try. Don't know how to either, sorry. New to github, but the error pissed me off. Trying a lot..

**Comment by tbmn** [comment]
running on windows

**Comment by stamparm** [comment]
Please zip the whole sqlmap directory and send it to miroslav@sqlmap.org

**Comment by stamparm** [comment]
One question. Does it happen for all sites or here and there?

**Comment by tbmn** [comment]
not always but I face much. Couldn't send the rar file to your email because of gmail restrictions. I sent you google drive link. could you access?

**Comment by stamparm** [comment]
I'll access in couple of hours and let you know. Can you give more details how to reproduce it (e.g. command line). You can give it to me privately

**Comment by tbmn** [comment]
I use with * inside the url. because there are no parameters. parameters are in the url like siteurl/news/category/*/forum/

**Comment by tbmn** [comment]
sent the command line, keep it ;) thanks

**Comment by tbmn** [comment]
After clearing/deleting the sqlmap directory, "unable to access item ..." error and also sqli detection has gone. weird. after you crosscheck you can close the issue, sorry for inconvenience.
thanks for your effort and interest. 
best wishes.

**Comment by stamparm** [comment]
For the record, this was PURELY your fault. You had a shitty `xml/payloads/00_payloads.xml` that had tons of garbage inside.

Also, you had a tweet where you nagged when we should "fix" this issue, when this was your fault all along. Now I see that you've deleted the tweet while I really had an urge to reply to your "unpleasant user experience

**Comment by stamparm** [comment]
p.s. this is the WTF file
![1111](https://cloud.githubusercontent.com/assets/921555/16703588/25821308-456f-11e6-95c0-c0945ebb9c92.png)
p.p.s. i am really unhappy that you deleted that nagging tweet

**Comment by stamparm** [comment]
p.p.p.s. raging over. everything is cool. no problem. though, i really wanted to reply to that tweet :)

**Comment by tbmn** [comment]
sorry for that :( apologize. it is all my fault. 
thanks for your understanding.
best wishes
