### ISSUE TITLE
dump mysql error

### ISSUE THREAD

**Issue by zaidosama** [sqlmapproject/sqlmap#2018]
hey i need any help
i'm trying to dump some coloumns but i can't
when i type --parse-error it gives me this error
please help

`[WARNING] parsed DBMS error message: 'mysql_fetch_array(): supplied argument is not a valid MySQL result resource in <b>/usr/local/psa/home/vhosts/xxx.com/httpdocs/image_big.php</b> on line <b>24</b>'

already tried --hex and --no-cast
`

**Comment by stamparm** [comment]
This is generic MySQL warning that query failed. Closing this down
