### ISSUE TITLE
tamper script "bigip" [CRITICAL] missing function

### ISSUE THREAD

**Issue by web-site-audit** [sqlmapproject/sqlmap#2032]
[06:40:05] [CRITICAL] WAF/IDS/IPS identified as 'BIG-IP Application Security Manager (F5 Networks)'. Please consider usage of tamper scripts (option '--tamper')

root@svn1790:~/sqlmap-dev# ./sqlmap.py -u "http://****" --random-agent -f --banner --is-dba --dbs --current-user --password --threads=1 --tor --tor-type=SOCKS5 --risk=3 --level=5 --check-tor --time-sec=30 --tamper=bigip

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting at 06:42:26

[06:42:26] [INFO] setting Tor SOCKS proxy settings
[06:42:26] [INFO] loading tamper script 'bigip'
[06:42:26] [CRITICAL] missing function 'tamper(payload, **kwargs)' in tamper script '/root/sqlmap-dev/tamper/bigip.py'

[*] shutting down at 06:42:26

root@svn1790:~/sqlmap-dev#

==========
root@svn1790:~/sqlmap-dev# ./sqlmap.py -v
1.0.7.34#dev
root@svn1790:~/sqlmap-dev# uname -a
Linux svn1790.pw 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
root@svn1790:~/sqlmap-dev# cat /proc/version
Linux version 3.19.0-25-generic (buildd@lgw01-20) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015
==============================

**Comment by stamparm** [comment]
There is no official tamper script bigip. Closing as invalid

**Comment by web-site-audit** [comment]
(((
