### ISSUE TITLE
Fetching problems

### ISSUE THREAD

**Issue by LucasRoot** [sqlmapproject/sqlmap#2035]
Hi guys, I'm suffering from a bug.
I have a table with 4 columns, and I want to drop them all, so I use this command 
`python sqlmap.py -u "http://www.site.com/page.php?cod=4" --dump -D database -T table`
And this happens: http://pastebin.com/raw/QTWrQ0DD so I can't dump the table.
But when I use the -C parameter and select **only** a column, the sqlmap drops the column.
`python sqlmap.py -u "http://www.site.com/page.php?cod=4" --dump -D database -T table -C column`
http://pastebin.com/raw/8AcGaJNR
But if I select more columns in the -C parameter, happens the samething when I don't select any.
`python sqlmap.py -u "http://www.site.com/page.php?cod=4" --dump -D database -T table -C column,column2`

Thanks a lot

**Comment by stamparm** [comment]
In most cases this is because of restrictions on reading of data from `information_schema` (read restrictions or some kind of blacklisting mechanism)
