### ISSUE TITLE
-os-shell problims

### ISSUE THREAD

**Issue by 0z3ro** [sqlmapproject/sqlmap#2036]
every time am trying to use os shell, i see it cant get the right usage, i mean file uploaded but not executed, and today i fall into this :

[00:20:03] [WARNING] unable to retrieve automatically the web server document root
what do you want to use for writable directory?
[1] common location(s) ('/var/www/, /var/www/html, /usr/local/apache2/htdocs, /var/www/nginx-default') (default)
[2] custom location(s)
[3] custom directory list file
[4] brute force search
> 1
[00:20:09] [WARNING] unable to automatically parse any web server path
[00:20:09] [INFO] trying to upload the file stager on '/var/www/' via LIMIT 'LINES TERMINATED BY' method
sqlmap got a 302 redirect to 'http://xxxxxx:80/var/index.php'. Do you want to follow? [Y/n] n

which make me come to post this echo, the case is the script execute data, and try to get the local bath "/var/" and try to open it remotely, 

i think the os-shell should a back look on it again to get better results

**Comment by stamparm** [comment]
```
which make me come to post this echo, the case is the script execute data, and try to get the local bath "/var/" and try to open it remotely, 
```

this doesn't make any sense. You want to write to the remote path `/var/` while it most certainly is not the location of the web server document root. You are supposed to find a web server document root path, not some random writeable location.

Everything is written in those questions/WARNINGs you get there.

**Comment by stamparm** [comment]
```
every time am trying to use os shell, i see it cant get the right usage, i mean file uploaded but not executed, and today i fall into this
```

Those are basics of any kind of shell upload. It is not enough to write anywhere. You have to find a location that is both writeable and reachable via the web browser.

**Comment by 0z3ro** [comment]
but in my case this 
/var/www/ is local path every where, the script trys browsing it as u see. http://xxxxxx:80/var/
/var/ not even a directory on this host, its a system directory

**Comment by stamparm** [comment]
it says `sqlmap got a 302 redirect to 'http://xxxxxx:80/var/index.php'`. your target responded with redirect to a WEB DIRECTORY `/var/`, not the local directory `/var/`. sqlmap didn't choose anything

**Comment by stamparm** [comment]
before you respond anything, please debug the problem throughly, find what is the web server's web root directory and say exactly where sqlmap did wrong. until then there is no need to further respond to this issue
