### ISSUE TITLE
 inline query - 250 Tables

### ISSUE THREAD

**Issue by dtsrwnis** [sqlmapproject/sqlmap#2037]
Hello there!  I have an injection with  inline query but with "--tables" i got only one table name from 250. I think i got this error because of many tables....

Is there any option or optimization to bypass this error? 

Thanks!

**Comment by stamparm** [comment]
Is there a way to contact me privately with more details?

**Comment by dtsrwnis** [comment]
You have email at @sqlmap.

Thanks @stamparm

**Comment by stamparm** [comment]
I didn't get anything at `miroslav@sqlmap.org`. Can you please resend?
