### ISSUE TITLE
is it possible to inject 2 variables ?

### ISSUE THREAD

**Issue by 0z3ro** [sqlmapproject/sqlmap#2041]
i wonder if there is possible way to inject 2 perimeters of the given link at the same time, it would help for login bypass

like:
username=x&password=y

this issue  couse i fall with same case wish give positive or not inject able when i give the script to execute automatic inject like
--data="username=x&password=y" 

but when i make like this:
--data="username=x&password=' OR ''=' " -p username 
its gose for blind injection, and works fine

any suggestions ?
thank you

**Comment by stamparm** [comment]
It is not possible, but I believe that you are doing something wrong.

Please run all cases where `OR` SQLi is required with (e.g.) `--level=5 --risk=3`, because those cases are not covered by default (i.e. on lower `--risk` values) as they are dangerous in some (non-SELECT) situations

**Comment by stamparm** [comment]
p.s. please don't use any leftovers of manual SQLi inside provided parameter values (like your `password=' OR ''='`)
