### ISSUE TITLE
sqlmapapi support for --method?

### ISSUE THREAD

**Issue by garthoidQlik** [sqlmapproject/sqlmap#2044]
I am trying to use SQLiPy in Burp suite for a PUT request against a sqlmap server started using sqlmapapi -s -H <host> -p <port>. Normal GET and POSTs work fine but whenever I attempt to send a PUT request using --method=PUT I get a 404 error code from the server. Manual verb tampering (changing the PUT to a POST) results in the same error which leads me to suspect that sqlmap is not getting the --method command. Using the --method=PUT with sqlmap manually on the same host work perfectly.

So, does sqlmapapi pass on --method?

Or am I missing something here?

Thanks in advance

**Comment by stamparm** [comment]
Tried this moment the following:

1) `python sqlmapapi.py -s`
2) `new -u "http://testphp.vulnweb.com/artists.php?artist=1" --method=PUT --flush-session`
3) wireshark -i any

Got the following results in wireshark:
![123](https://cloud.githubusercontent.com/assets/921555/16968115/24d91900-4e0d-11e6-8db3-42f95d7642d3.png)
