### ISSUE TITLE
mysql where case bind inject output error result

### ISSUE THREAD

**Issue by sincoder** [sqlmapproject/sqlmap#2047]
Parameter:  Type (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: Type=1') AND 4284=4284 AND ('TOcI'='TOcI&Page=0

[16:46:16] [INFO] the back-end DBMS is MySQL
web application technology: Apache
back-end DBMS: MySQL >= 5.0.12

I user --sql-shell  and exec select host,user,password from mysql.user. sqlmap run with no serious error, but the result just not  correct ，the mysql hash are not in the right format  (has invalid chars)   maybe  some result check mechanism is need
![image](https://cloud.githubusercontent.com/assets/1122670/16980650/ace13210-4e99-11e6-8227-906a2a71e760.png)

**Comment by stamparm** [comment]
There is some dinamicity there causing problems. Use --text-only or --string in this kind of cases. Also, rerun with --flush-session

**Comment by stamparm** [comment]
Also, use lower --threads if you are using multithreading
