### ISSUE TITLE
Time based injection and dump validation

### ISSUE THREAD

**Issue by p4r4d0x86** [sqlmapproject/sqlmap#2063]
Hi all,

First, many thanks for this excellent tool :)

I used recently sqlmap to dump the first 10 entries of a table through a time-based SQL injection very unstable. Once finished, I spotted some dump error (normal). I have to erase some data in the session.sqlite to redump the wrong value(s).

Did I miss something/an option? Or could it be possible to get a "--check-dump-time-based" option which will:
1 - retest the length of the value in DB (twice ?) and compare to value retrieved length
1.1 - if it is incorrect, retest character one by one to redump bad char and of course complete the value.
1.2 - if it is correct, validate the value retrieved with one query (twice ?).
1.2.1  - if the value retrieved is incorrect, retest character one by one to redump bad char ?

With a sub-param to set the level of validation/paranoïa? (to do multiple times some tests)
With a question asking if redump have to be done when a corruption is detected?

Kind regards,
Nico

**Comment by stamparm** [comment]
Hiw about --fresh-queries once your connection gets stable?

**Comment by p4r4d0x86** [comment]
Hi,

If I understand well the option, it will ignore completely the value already retrieved.
Like it is super slow, I would prefer a check option : it will be faster to correct some mistake than to redump everything no ?

When SQLmap say "resumed: xxx"; it could do a check first if the option is enable ?

Kind regards,
Nico

**Comment by stamparm** [comment]
Super slow, while you want super fast validation. Good bye. Closing thia down

**Comment by p4r4d0x86** [comment]
The server is super slow so I would like to optimize with a check operation in place of "fresh-queries", nothing more.
If it is not possible or you don't want, that's ok. Not sure to interpret well your last message ...

Have a good day
Nico
