### ISSUE TITLE
Can not get user and pass

### ISSUE THREAD

**Issue by BilloTango** [sqlmapproject/sqlmap#2065]
Hello All i have problem now i try to find user and password from database but i cant find user and pass, Site have so many users but the issue is i cant find why ? any hidden data ?

**Comment by stamparm** [comment]
I don't understand a thing here. Can you please explain it more clearly

**Comment by BilloTango** [comment]
Today i am try to get the database i mean i found vulnerable link after i am trying to get user and pass from database but i can nt find user and pass columns, i mean i see table name is: logins after inside i can not find user and password columns ? why ?

**Comment by stamparm** [comment]
Maybe there are no such columns there. Also, username/password are called differently in different languages

**Comment by BilloTango** [comment]
i find every columns but i can't see user and passwords can any one help me privately ?

**Comment by BilloTango** [comment]
Can i send you you site with user and pass ?
