### ISSUE TITLE
Can not get data on SQLMAP

### ISSUE THREAD

**Issue by yingbrooke7** [sqlmapproject/sqlmap#2067]
Dear,
Usually, i get data is normal on this link.
But, today, i to try get it, result is same picture (file attached). Get on tables different on same target, it's OK. Can u help me?

Thank you!
<img width="426" alt="untitled" src="https://cloud.githubusercontent.com/assets/20071224/17161278/0fb34176-53a4-11e6-9cc1-fa9717c8f3e6.png">

**Comment by stamparm** [comment]
Sorry, but I couldn't understand what's the problem here. You are referring to the picture, while the picture looks ok.

**Comment by yingbrooke7** [comment]
@stamparm 
The picture run OK, but not get any data (it's have data). i dump data from columns on tables in database

**Comment by stamparm** [comment]
And which command you are trying to run? You haven't stated anywhere

**Comment by yingbrooke7** [comment]
sqlmap.py -u http://target.com -D database -T tables -C columns --dump --hex 
Yesterday, i'm run it OK. but now, it's not get any data.
And i to try get dump on tables different, it,s OK => target is OK. Is error by sqlmap?

**Comment by stamparm** [comment]
You are doing something really wrong. This works out of box
