### ISSUE TITLE
ignore 403 (treat as 200)

### ISSUE THREAD

**Issue by hecodesalot** [sqlmapproject/sqlmap#2069]
I have been playing with a web-server that returns a 403 status code but contains the page in the response data (basically the web-server treats a 403 request as a 200). 

I noticed that there isn't an --ignore-403 an option for a custom status code (ie: 403 = 200).

Is this at all possible?

**Comment by stamparm** [comment]
Will implement

**Comment by stamparm** [comment]
Checked this moment. Only two HTTP codes that are not being treated as 200 (except if not set by the user to ignore) are 401 (unauthorized) and 404 (not found). Others are normally being processed (no exceptions raised) - there is only a single warning in such cases. Hence, there is nothing to implement here.
