### ISSUE TITLE
Blocked by Varnish FireWall (OWASP) using Tamper

### ISSUE THREAD

**Issue by krlo-s** [sqlmapproject/sqlmap#2074]
Greetings Sqlmap community,

First of all i would like to thank for this magnificent, pretty solid project named SQLMap.
I found a SQLi in a site using Varnish FireWall, it blocks both SQLMap and me when i try to inject manual. The SQLMap input was:

sqlmap.py -u "vuln.site"  --identify-waf --tamper="between,varnish" -v 3 --random-agent --level=5 --risk=3 --dbs

And the output is:

"[19:47:24] [INFO] testing connection to the target URL
sqlmap got a 302 redirect to 'http://errors.stablehost.com/406.php'. Do you want
 to follow? [Y/n] n
[19:47:34] [INFO] using WAF scripts to detect backend WAF/IPS/IDS protection
[19:47:37] [CRITICAL] WAF/IDS/IPS identified as 'Varnish FireWall (OWASP) '. Ple
ase consider usage of tamper scripts (option '--tamper')
are you sure that you want to continue with further target testing? [y/N] y
[19:47:41] [INFO] testing if the target URL is stable
[19:47:42] [INFO] heuristics detected web page charset 'ascii'
## **[19:47:42] [WARNING] it appears that you have been blocked by the target server**
[19:47:42] [WARNING] URI parameter '#1*' does not appear dynamic
[19:47:45] [WARNING] HTTP error codes detected during run:
403 (Forbidden) - 1 times

[19:47:45] [ERROR] user aborted

[*] shutting down at 19:47:45"

I canceled it as it ends to a non injectable point (even if i know it is). When i inject manually in my browser i get:

"Your connection to this server has been blocked in this server's firewall due to multiple failed logins.

Your IP will automatically removed from the firewall within 30 minutes. Please contact our support department if you are still blocked within 30 minutes and provide the following information:

Your blocked IP address is XXX.XXX.XXX.XXX
This server's hostname is ssd11.stablehost.com"

My question is even if i used tamper scripts how can this firewall be bypassed?.

Many thanks for your help,
Regards

**Comment by stamparm** [comment]
Community is just asking this kind of questions without contributing back. I would suggest you to do a proper research and report back. Until then I am closing this down.

**Comment by krlo-s** [comment]
So it's not possible?
