### ISSUE TITLE
DATA BINARY

### ISSUE THREAD

**Issue by tgrl5000** [sqlmapproject/sqlmap#2081]
SQLMAP haven't got --data-binary parameter.In curl i test this url.
`curl 'http://www.sorcial.com/settings' -H 'Cookie: PHPSESSID=0d1b410b17493b807b19fba0dbab48e0; _ga=GA1.2.1066959656.1470333050' -H 'Origin: http://www.sorcial.com' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/51.0.2704.79 Chrome/51.0.2704.79 Safari/537.36' -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryyr8s77H8RFJ1CNtD' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Cache-Control: max-age=0' -H 'Referer: http://www.sorcial.com/settings' -H 'Connection: keep-alive' --data-binary $'------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="imgmobile"; filename=""\r\nContent-Type: application/octet-stream\r\n\r\n\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_title_mobile"\r\n\r\nBat\u0131kan To\u011fna\u015f \r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_about_mobile"\r\n\r\nWrite something about yourself\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_facebook"\r\n\r\nbatikan.tognas\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_twitter"\r\n\r\nateistsokak\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_instagram"\r\n\r\nkamkam50\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_snapchat"\r\n\r\nsorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_tumblr"\r\n\r\nsorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_youtube"\r\n\r\nsorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_linkedin"\r\n\r\nsorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_pinterest"\r\n\r\nsorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_googleplus"\r\n\r\nsorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_skype"\r\n\r\nsorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_mail"\r\n\r\nbkpwifihack@gmail.com\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_web"\r\n\r\nhttp://ateistsokak.com\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="oldpassword"\r\n\r\n123456789s\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="newpassword"\r\n\r\n123456789s\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="img"; filename=""\r\nContent-Type: application/octet-stream\r\n\r\n\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_title"\r\n\r\nBat\u0131kan To\u011fna\u015f sorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_about"\r\n\r\nWrite something about yourself sorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="SaveSubmit"\r\n\r\n\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD--\r\n' --compressedcurl 'http://www.sorcial.com/settings' -H 'Cookie: PHPSESSID=0d1b410b17493b807b19fba0dbab48e0; _ga=GA1.2.1066959656.1470333050' -H 'Origin: http://www.sorcial.com' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/51.0.2704.79 Chrome/51.0.2704.79 Safari/537.36' -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryyr8s77H8RFJ1CNtD' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Cache-Control: max-age=0' -H 'Referer: http://www.sorcial.com/settings' -H 'Connection: keep-alive' --data-binary $'------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="imgmobile"; filename=""\r\nContent-Type: application/octet-stream\r\n\r\n\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_title_mobile"\r\n\r\nBat\u0131kan To\u011fna\u015f \r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_about_mobile"\r\n\r\nWrite something about yourself\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_facebook"\r\n\r\nbatikan.tognas\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_twitter"\r\n\r\nateistsokak\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_instagram"\r\n\r\nkamkam50\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_snapchat"\r\n\r\nsorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_tumblr"\r\n\r\nsorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_youtube"\r\n\r\nsorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_linkedin"\r\n\r\nsorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_pinterest"\r\n\r\nsorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_googleplus"\r\n\r\nsorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_skype"\r\n\r\nsorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_mail"\r\n\r\nbkpwifihack@gmail.com\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_web"\r\n\r\nhttp://ateistsokak.com\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="oldpassword"\r\n\r\n123456789s\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="newpassword"\r\n\r\n123456789s\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="img"; filename=""\r\nContent-Type: application/octet-stream\r\n\r\n\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_title"\r\n\r\nBat\u0131kan To\u011fna\u015f sorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_about"\r\n\r\nWrite something about yourself sorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="SaveSubmit"\r\n\r\n\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD--\r\n' --compressedcurl 'http://www.sorcial.com/settings' -H 'Cookie: PHPSESSID=0d1b410b17493b807b19fba0dbab48e0; _ga=GA1.2.1066959656.1470333050' -H 'Origin: http://www.sorcial.com' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/51.0.2704.79 Chrome/51.0.2704.79 Safari/537.36' -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryyr8s77H8RFJ1CNtD' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Cache-Control: max-age=0' -H 'Referer: http://www.sorcial.com/settings' -H 'Connection: keep-alive' --data-binary $'------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="imgmobile"; filename=""\r\nContent-Type: application/octet-stream\r\n\r\n\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_title_mobile"\r\n\r\nBat\u0131kan To\u011fna\u015f \r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_about_mobile"\r\n\r\nWrite something about yourself\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_facebook"\r\n\r\nbatikan.tognas\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_twitter"\r\n\r\nateistsokak\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_instagram"\r\n\r\nkamkam50\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_snapchat"\r\n\r\nsorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_tumblr"\r\n\r\nsorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_youtube"\r\n\r\nsorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_linkedin"\r\n\r\nsorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_pinterest"\r\n\r\nsorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_googleplus"\r\n\r\nsorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_skype"\r\n\r\nsorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_mail"\r\n\r\nbkpwifihack@gmail.com\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_web"\r\n\r\nhttp://ateistsokak.com\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="oldpassword"\r\n\r\n123456789s\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="newpassword"\r\n\r\n123456789s\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="img"; filename=""\r\nContent-Type: application/octet-stream\r\n\r\n\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_title"\r\n\r\nBat\u0131kan To\u011fna\u015f sorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="user_about"\r\n\r\nWrite something about yourself sorcial\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD\r\nContent-Disposition: form-data; name="SaveSubmit"\r\n\r\n\r\n------WebKitFormBoundaryyr8s77H8RFJ1CNtD--\r\n' --compressed`

but in sqlmap i can't test it.So how i test binary request data

**Comment by stamparm** [comment]
Use option -r
