### ISSUE TITLE
Incompatible Python version-not working in 3.5.2

### ISSUE THREAD

**Issue by adhi1234** [sqlmapproject/sqlmap#2099]
When setting the enviroment this tool will not be taken by ver
![python_error](https://cloud.githubusercontent.com/assets/11091122/17629744/962f280e-60d9-11e6-9477-fe734824f98b.PNG)
sion 3.5.2

**Comment by stamparm** [comment]
Everywhere you search for sqlmap compatibility you can find that it only supports python 2.x. Also, that message itself is from sqlmap. I am not sure what's the issue here? Python 3 is a totally different language
