### ISSUE TITLE
Tamper for Kona

### ISSUE THREAD

**Issue by moku23** [sqlmapproject/sqlmap#2113]
Hello,
which is the best tamper to bypass this kind of firewall?
KONA Security Solutions (Akamai Technologies)

I'm searching on G, but nothing.
Thanks

**Comment by stamparm** [comment]
Currently none. It is based on ModSecurity and there are no usable tamper scripts for effectively bypass it. You should assess the target manually

**Comment by TNierman** [comment]
This topic is closed, but for those that come afterwards, I recently received this error when pen-testing a site with KONA Security Solutions.

I haven't been able to enumerate the database names, but using the --common-names switch, I was able to see some of the tables present on the current database.

**Comment by Ekultek** [comment]
Depending on the web server, low level Unicode encoding should work, mixed with modsec bypassing

**Comment by TNierman** [comment]
Sorry, --common-tables and/or --common-columns

**Comment by shahzad261** [comment]
Hey @TNierman
Would you elaborate.
I found a Kona firewall which allow the following query and showing blind sqli exisit, but blocking = sign and some other function to extract information.
email=admin'+AND+1=1 --       true (customize page)
email=admin'+AND+1=0 --         normal page 
email=admin'+OR+1=1 --        true (customize page)
email=admin'+OR+1=0 --         normal page 
email=admin'+HAVING+1=1 --        true (customize page)
email=admin'+OR+1=0 --          normal page
