### ISSUE TITLE
how to choose attack method(when there are two attack methods you can choose)?

### ISSUE THREAD

**Issue by seabird1992** [sqlmapproject/sqlmap#2117]
hi everyone.Just now i have sccessfully injected  one website database using sqlmap.but the problem is that this website have two database flaws.One is and-boolean based error attack,another is time-based error attack.but when trying to use sqlmap to get usernames and passwords,the sqlmap use time-based error defaultly.but this is waste time seriousely.I want to use another method(and-boolean based method) to injected databse,could anyone konw how to select?thanks a lot!

**Comment by SweetSoul** [comment]
Use --technique=BEUS...
For further instructions search the help for that option.

**Comment by seabird1992** [comment]
i see it.thank you very much

**Comment by SweetSoul** [comment]
Please close the topic if the issue was solved.
