### ISSUE TITLE
Batch behaviour

### ISSUE THREAD

**Issue by noavs** [sqlmapproject/sqlmap#2118]
I noticed that when you enable the '--batch' option there is no way to avoid redirects. How do you actually do that? Is there a way? If not that would be a nice feature to add.

**Comment by stamparm** [comment]
```
    --answers=ANSWERS   Set question answers (e.g. "quit=N,follow=N")
```
https://github.com/sqlmapproject/sqlmap/wiki/Usage#set-answers-for-questions

p.s. in your case it would be something like `...--batch --answer="redirect=N"`
