### ISSUE TITLE
Can't run app. "sqlmap.py: error: missing a mandatory..."

### ISSUE THREAD

**Issue by DocGreenRob** [sqlmapproject/sqlmap#2135]
So, I downloaded the .zip with the source files, then download and installed Python 2.7.12 and launched sqlmap.py and got the error that says:

`sqlmap.py: error: missing a mandatory option (-d, -u, -l, -m, -r, -g, -c, -x, --
wizard, --update, --purge-output or --dependencies), use -h for basic or -hh for
 advanced help`

then I press "Enter" and it closes

**Comment by SweetSoul** [comment]
First of all, welcome to our community, as i can see for your question you are new here... :laughing: 

Read the readme.md at [here](https://github.com/sqlmapproject/sqlmap)
Or use it like that for further instructions: 
sqlmap.py --help 
 or 
sqlmap.py -h

**Comment by Martinezyoni** [comment]
necesito saber por que me salta este error 
C:\sqlmap>sqlmap.py -u https://serviciosilimitados.net/viaje.php?id=25 --dbs
"sqlmap.py" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

**Comment by anongrunge** [comment]
Could it be do to no root priv

**Comment by rootcode143** [comment]
sqlmap.py: error: missing a mandatory option

**Comment by uZueirassempre** [comment]
Também estou com o mesmo problema, ja tentei de tudo usar esse tipo de có
![2019-04-21 18_23_50-Prompt de Comando - sqlmap py  -u http___testphp vulnweb com_search php_test=que](https://user-images.githubusercontent.com/49872133/56503049-e0e8f880-64ea-11e9-8230-406a4b066806.png)
digo -hh ou -h não funciona! Ja tentei usar até os próprios códigos que o erro oferece de sugestão para ajuda mais não funciona também, não sei oque eu faço. Me ajudem!

**Comment by wajih220** [comment]
جرب sqlmap بدون .py
