### ISSUE TITLE
Applications behind multiple WAFs

### ISSUE THREAD

**Issue by inquisb** [sqlmapproject/sqlmap#2137]
The `--identify-waf` stops as soon as one WAF is detected. It would be nice to ask the user if (s)he wants to continue after a first WAF is detected.
For example, I've seen apps protected on the host by UrlScan and behind the CloudFlare infrastructure with CloudFlare filters enabled.

**Comment by stamparm** [comment]
You are being asked the following question:

`are you sure that you want to continue with further target testing? [y/N] `
