### ISSUE TITLE
CRITICAL not authorized, try to provide right HTTP authentication type and valid credentials (401)

### ISSUE THREAD

**Issue by DocGreenRob** [sqlmapproject/sqlmap#2139]
So, I got this message... What next?

Scenario:

At work, testing app. Url is localhost... Is a .NET app.  I am behind firewall.  (Is an intranet site)

How can I provide my credentials?

**Comment by stamparm** [comment]
Have you read the manual?

**Comment by DocGreenRob** [comment]
Yes, it there is nothing there that infers on how to handle these situations. Can you help?

**Comment by SweetSoul** [comment]
Stamparm let me try here :smile:

First: you need to show your command... What you ran that lead to this error...
Maybe try to `-v 3` or `--parse-errors`

**Comment by DocGreenRob** [comment]
I am running...
`> python sqlmap.py -u "http://localhost/path?id=x" -- dbs`

**Comment by DocGreenRob** [comment]
To access the site via the browser I have to login using my Active Directory credentials. So is there some way I can specify userName/password with the `-u` request?

**Comment by SweetSoul** [comment]
**-- dbs** 
You have to write the double slashen together with the option like: `--dbs`
If it is a post data you can specify the parameter sent trough http in `--data="anything=1&anythingelse=2"` and so on...

**Comment by DocGreenRob** [comment]
I know that part, but the issue is, as the subject states, that I need to "try to provide right HTTP authentication type and valid credentials (401)".  Can you assist me with this?

**Comment by DocGreenRob** [comment]
Oops, that was a typo, I am writing the double slashes together with dbs like `--dbs`

**Comment by SweetSoul** [comment]
Bruh u need to f*ing think...
But i'll assist you...

How the credentials are sent?

Through a header? cookie? post-data?

**Comment by SweetSoul** [comment]
Take a very good look at this: https://en.wikipedia.org/wiki/Kerberos_(protocol)#Protocol

**Comment by stamparm** [comment]
@DocGreenRob straight from manual: https://github.com/sqlmapproject/sqlmap/wiki/Usage#http-protocol-authentication

**Comment by DocGreenRob** [comment]
Thanks.

**Comment by ron190** [comment]
Your IIS application returns header `WWW-Authenticate` when protected by an authentication protocol. You can know the specific protocol from the Authentication panel in IIS or from the header's value:

- if it starts with Basic, it's Basic Authentication,
- if it's equal to NTLM, it's NTLM Authentication,
- if it starts with Digest, it's Digest Authentication,
- if it's equal to Negotiate, it's Negotiate Authentication,
- or else it may be Kerberos authent, check this in the Authentication panel in your IIS.

If sqlmap is not compatible with Kerberos protocol you can ask stamparm and Bernardo to include it in the roadmap.
