### ISSUE TITLE
Count Rows --search

### ISSUE THREAD

**Issue by entropyideas** [sqlmapproject/sqlmap#2142]
My setup is sqlmap.py -u "http://localhost/index.php?id=1" --search -C 'password' and was wondering if there is a way to count the amount of rows and display it for the columns containing "password" and if not possibly adding this on in the future. Thank you!

**Comment by SweetSoul** [comment]
You can do something like:
`--sql-query="SELECT COUNT(*) FROM TABLE WHERE PASSWORD IS NOT NULL"`

i think this would work for you...

**Comment by entropyideas** [comment]
Wouldn't this only work if column or table exactly matches what you are searching for? In example if you are searching for "pass" but the column or table found came back as password, admin_pass,user_pass, etc then the SQL query wouldn't be able to give you counted row because it is looking for an exact match of "pass"?

**Comment by SweetSoul** [comment]
Yes... but lets assume that you ran `-D database --tables` ... cuz you better do it, to know better your target database and select the rightful command that will attend to your needs...

**Comment by stamparm** [comment]
@entropyideas too much hassle (for no obvious gain) because of different modes of `--search` for `-C` and `-T`
