### ISSUE TITLE
INSERT INTO (how do I guide sqlmap)

### ISSUE THREAD

**Issue by Insertintosqlmap** [sqlmapproject/sqlmap#2159]
First, to show my appreciation for all the good work that's been done for sqlmap.
I donated $100:

https://blockchain.info/address/1AUrrKYsamBEThdruYTQmUfMfLF7aaxU6x

Now to my problem;

Manually, I know how to construct the SQL Injection, for more background information, the query is as such:

INSERT INTO profiles (userid, photoid, id, value_int, type, id2) VALUES (155, 5, 'dev.app', '1', 2, **injectiongoesrighthere**)

The way to extract version() manually is through (decoded so easier to read)

``http://www.example.com/?id='' *(select*from(select(name_const(version(),1)),name_const(version(),1))a)* ''``

Which returns with:

``Duplicate column name '5.5[redacted]``

So, my question is, how do I guide sqlmap for this injection?

I ask because if I run sqlmap with --dbms=mysql --risk=3 it just returns "target is not injectable".

Perhaps something close to this will help?

`sqlmap.py -u "http://www.example.com/?id=" -p "id" --prefix="''" --suffix="''" --dbms=mysql --technique=E --risk=3`

Thanks!

**Comment by Insertintosqlmap** [comment]
Right so.. there seems to be a totally different issue beyond just detecting the technique of the injection.

To begin with since I found that this syntax works too:

**'aa' or updatexml(1,concat(0x7e,(version())),0) or ''**

I set sqlmap to perform with the appropriate settings, where it then used this payload (which by the way 100% works on the application) 

**'aa' OR UPDATEXML(8019,CONCAT(0x2e,0x7170626b71,(SELECT (version())),0x7162787a71),8533) or ''**

However, the main issue is, since the application is over HTTPS and it uses a custom port let's say it is port 15000, the URL looks like so:

https://example.com:15000/view.php?id=2

This leads to sqlmap having SSL errors, the exact ones are:

**[DEBUG] SSL connection error occurred ('[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)')
[DEBUG] SSL connection error occurred ('[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)')**

Although it has SSL errors, sqlmap still continues, which means that it literally receives no useful response from view.php apart from "error, you are not authorized" as I saw from -v 6.

How can that be fixed? It seems it is a bug in sqlmap afterall.


Thanks!

**Comment by stamparm** [comment]
This last "bug" is most probably not a bug at all. sqlmap tries to use the highest possible SSL protocol when establishing the connection for the first time. Hence the multiple protocol mismatch DEBUG message.

Could you please send me the complete console output of a regular sqlmap run against the target along with the traffic file (-t traffic.txt) to miroslav@sqlmap.org?

**Comment by stamparm** [comment]
ping?

**Comment by Insertintosqlmap** [comment]
Hi, apologies for not getting back to you on this, I was quite busy.
This was not a bug in sqlmap, I was just so tired that day I forgot to include --cookie, hence the authorization errors.
