### ISSUE TITLE
What is \xdd\xdd\xdd ... ?

### ISSUE THREAD

**Issue by samiux** [sqlmapproject/sqlmap#2161]
What is the meaning about for the following message?

available databases [1]:
[*] \xdd\xdd\xdd\xdd\xdd\xdd\xdd\xdd\xdd\xdd\xdd\xdd\xdd\xdd\xdd\xdd\xdd\xdd\xdd\xdd\xdd?

Why is \xdd\xdd\xdd ...?

**Comment by stamparm** [comment]
Maybe a false positive or WAF blocking blind SQLi requests. You are not mentioning whether there were HTTP codes enlisted at the end of the sqlmap run (e.g. 500 - forbidden or similar). Also, if sqlmap nagged about the WAF.

If not protection, then it could be a false-positive. In that case you should rerun with `--flush-session`. There is also a possibility that the "dynamicity" is causing problems. In that case you should rerun with (e.g.) `--string`
