### ISSUE TITLE
can't upload file through os-shell when i knowing the absolute path

### ISSUE THREAD

**Issue by seabird1992** [sqlmapproject/sqlmap#2167]
hi,i have seccessfully injected the website,when prompt the command --os-shell to upload file,it lets me input absolutely file,i get the path through  www.xxx.com/phpinfo.php.it shows the SERVER["DOCUMENT_ROOT"] is /usr/local/bbs,so i input /usr/local/bbs.but it shows that [WARNING] unable to upload the file stager on '/usr/bin/' and get 404 (Not Found) - 3 times errors.does anyone know how this happen? thks a lot~

**Comment by SweetSoul** [comment]
Maybe it's because the user of the database isn't the DBA... check with `--is-dba`

**Comment by stamparm** [comment]
DBA is not enough. The process user itself (e.g. `mysql) has to have the privileges too to write to arbitrary file locations. @seabird1992 I would suggest you to run with `--parse-errors`. If you don't get anything more with it, then you are stuck. I would bet that your target doesn't have write privileges to that same directory

**Comment by Tejpandya** [comment]
hi , i've successfully injected my website and its working llike a charm but is-dba returns false , i've  only usage access , is there any way  from sqlmap , i can get DBA accesss , i could not upload file stager to the server because of privileges . it would be better if you just show me the direction , how can i get DBA access ?

**Comment by Ekultek** [comment]
Find the database admin and login as him.

**Comment by Ekultek** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/Usage

**Comment by Tejpandya** [comment]
So . i have to use **--auth-cred** to pass my admin credentials in my injection , @Ekultek

**Comment by Ekultek** [comment]
@Tejpandya if that's what it says man.

**Comment by Tejpandya** [comment]
i can' t get DBA  with this --auth-cred .  i've admin credentials  , how can i pass this admin credentials in sqlmap command  to get root privilege and upload a stager ?  @stamparm  @Ekultek

**Comment by selluk** [comment]
> i can' t get DBA with this --auth-cred . i've admin credentials , how can i pass this admin credentials in sqlmap command to get root privilege and upload a stager ? @stamparm @Ekultek

hello please you have found the solution ?? i  have the same problem.
