### ISSUE TITLE
Unable to find usable request in provided file

### ISSUE THREAD

**Issue by Siddharth28m** [sqlmapproject/sqlmap#2189]
I am trying to run SQLMap by providing request file path (-r /etc/sqlmap/request) this request was captured using burp suite and pasted in the file.

However I am getting error saying **[CRITICAL] unable to find usable request(s) in provided file** This was running absolutely fine sometime back and without any change it stopped. I even tried by giving --method

**Comment by stamparm** [comment]
And what's the content of request file?

**Comment by Siddharth28m** [comment]
It has a POST request with header, cookie, parameters, referrer, content-type etc.

**Comment by SweetSoul** [comment]
OMG... Post it here genius... Change the host info and whatever u like, but every fucking POST req has this info..

**Comment by stamparm** [comment]
@SweetSoul please don't use foul language
@Siddharth28m i require some basic structure, not your description. Obfuscate what's sensitive and post it here or privately to me

**Comment by Siddharth28m** [comment]
Due to confidentiality I have sent you email, kindly check.

**Comment by stamparm** [comment]
@Siddharth28m can't reproduce
![11111](https://cloud.githubusercontent.com/assets/921555/18853006/6cd6d3fc-8443-11e6-8835-e428eba3c348.png)

**Comment by Siddharth28m** [comment]
@stamparm to my surprise this is working absolutely fine on Windows but not on Kali, it was working fine couple of days back is there anything I am missing?

**Comment by stamparm** [comment]
I am running it on Ubuntu/Debian without any problems. Kali should be the same. Yup, you are missing something

**Comment by Siddharth28m** [comment]
Any help you can recommend? I am trying the same method which I was used previously to run, I tried changing file location too.

**Comment by stamparm** [comment]
What do you get with --version?

**Comment by Siddharth28m** [comment]
1.0.9.1#dev

**Comment by stamparm** [comment]
Made a checkout of that particular tag this moment and retried.
![1111111111](https://cloud.githubusercontent.com/assets/921555/18904887/9f24cd8c-8560-11e6-97d4-5ba30b05e35e.png)

**Comment by stamparm** [comment]
Retried with the official sqlmap from PyPi repository too:

![pip](https://cloud.githubusercontent.com/assets/921555/18904944/ffcc8b70-8560-11e6-989b-b0a2f0922bf8.png)

**Comment by Siddharth28m** [comment]
Hey I'm still stuck here I tried using different file too POST/GET still no luck, can you please help or suggest any solution? I'm on Kali rolling if that helps

**Comment by stamparm** [comment]
Are you able to reproduce anywhere else (windows?). I've tried on more than
few platforms and everything works as expected. Also, you are the only one
that reports this kind of a problem

**Comment by SweetSoul** [comment]
I had this issue before... but i was learning so i don't have the file anymore... Sorry for not be able to help you here.

**Comment by usermame123** [comment]
i have this issue too, the same request (from burp) work just fine in kali but doesn't work in windows.

**Comment by stamparm** [comment]
And no details provided

**Comment by Siddharth28m** [comment]
I'm not sure how and what happened it started working for me :)
