### ISSUE TITLE
VARCHAR (250) = NULL

### ISSUE THREAD

**Issue by AVR1234** [sqlmapproject/sqlmap#2190]
Hi i want to ask you, what parametr of sqlmap try to add if date in column get 'NULL' (or ""), TYPE COLUMN varchar(250)?

**Comment by stamparm** [comment]
sorry, couldn't understand you. if something is retrieved as NULL why do you think that it is not NULL?

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/issues/2178#issuecomment-249712478
