### ISSUE TITLE
undefined symbol: XML_SetHashSalt

### ISSUE THREAD

**Issue by GeoffreyVDB** [sqlmapproject/sqlmap#2194]
I get the following output when trying to start sqlmap:

```
Traceback (most recent call last):
  File "/usr/bin/sqlmap", line 35, in <module>
    from lib.controller.controller import start
  File "/usr/share/sqlmap/lib/controller/controller.py", line 66, in <module>
    from lib.core.target import initTargetEnv
  File "/usr/share/sqlmap/lib/core/target.py", line 71, in <module>
    from lib.core.xmldump import dumper as xmldumper
  File "/usr/share/sqlmap/lib/core/xmldump.py", line 18, in <module>
    from xml.parsers.expat import ExpatError
  File "/usr/lib/python2.7/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: /usr/lib/python2.7/lib-dynload/pyexpat.x86_64-linux-gnu.so: undefined symbol: XML_SetHashSalt
```

This is on Kali after doing an upgrade, don't really know what is causing this one though

**Comment by stamparm** [comment]
Have you messed with the `LD_LIBRARY_PATH`?

Also, take a look at:
https://askubuntu.com/questions/546654/python-error-when-opening-software-center
https://askubuntu.com/questions/601106/trying-to-run-hp-toolbox-from-hplip-but-gives-python-errors

**Comment by eisenbass** [comment]
**stamparm commented on 28 Sep 2016**
_Have you messed with the LD_LIBRARY_PATH?_
--
- I get have the same issue and I did mess a little with LD_LIBRARY_PATH?
Any advises?

**Comment by stamparm** [comment]
@eisenbass please take a look into those two links I've posted in previous message. You either have to correct the `LD_LIBRARY_PATH` (e.g. try to remove last entries from it as those last entries should be those last added to it), or try to fix the `libexpat` library location (https://askubuntu.com/a/601178)
