### ISSUE TITLE
How do I guide sqlmap?

### ISSUE THREAD

**Issue by Insertintosqlmap** [sqlmapproject/sqlmap#2205]
The SQL Query is:

`$conditions .=' AND created_on >= DATE_SUB(NOW(), INTERVAL ' . $days_ahead . ' DAY)';`

I've gotten up to this point:

`http://www.example.com/profile.php?days_ahead=2%20DAY) <inject here> --+`

But i'm not sure how to proceed, what would be the best way to inject here?
I tried some tricks with updatexml but no luck.
When you break the query, it just returns a 500 internal server error, there is no output on the page that says you have an error in your SQL Syntax, so I doubt error based sql injection is possible here.

Can you give me the manual syntax, for both blind and error based so I can guide sqlmap better?

thanks.

**Comment by stamparm** [comment]
Communicated with user privately on this one. Closing it down
