### ISSUE TITLE
hi all my scans are stuck at the mssql Database

### ISSUE THREAD

**Issue by yf007** [sqlmapproject/sqlmap#2215]
Hey
I do not know how to explain it
But all my scans are stuck at the mssql Database Search
All the mssql!
More than that? Also scans once done successfully,
Now they have that annoying error message
possible server trimmed output detected
the sql query provided does not return any output
Anyone else having this problem?
Thanks
![mssql](https://cloud.githubusercontent.com/assets/18291801/19136295/14edd8ec-8b74-11e6-9d7d-7505ac4b819e.png)

**Comment by yf007** [comment]
![mssql2](https://cloud.githubusercontent.com/assets/18291801/19136331/727520e2-8b74-11e6-992b-ad6f7f6c8c67.png)

**Comment by yf007** [comment]
![mssql2](https://cloud.githubusercontent.com/assets/18291801/19136363/b7adccae-8b74-11e6-8fba-78f7ad7cc0d6.png)

**Comment by yf007** [comment]
no tampers help...

**Comment by stamparm** [comment]
Please contact me privately to miroslav@sqlmap.org
