### ISSUE TITLE
unable to retrieve the table names for any database

### ISSUE THREAD

**Issue by waploaj** [sqlmapproject/sqlmap#2217]
`sqlmap -u "https://aris2.udsm.ac.tz/academics/student_year_infos.php?intStudentID=365355&intStudyYearID=1193526&intYearID=26" -D aris2_database -T auth_user -C name,surname,uname,passwd --dump
![screenshot 2016-10-08 13 15 55](https://cloud.githubusercontent.com/assets/21229790/19212421/89a59530-8d59-11e6-8756-2861d19e831e.png)
`

**Comment by fredhagedorn** [comment]
How the fuck you find a vulnerability there? Only seeing the URL, nobody here can tell anything. The first thing you should do is # (1) RTFM and (2) figure out to log-in, take the respective cookie and put it in `--cookie switch` and try again (but remember: RTFM first).

**Comment by SweetSoul** [comment]
Tried `--no-cast`?

**Comment by stamparm** [comment]
@waploaj false positive. Rerun with `--flush-session` (and please update to the latest revision)
@fredhagedorn please restrain from foul language

**Comment by fredhagedorn** [comment]
Sorry m8. I sent you a mail, hope you received it. Thanks in advance.

**Comment by fredhagedorn** [comment]
@waploaj Dude, srsly, sorry about my previous comment. You see, you cant try to dump the stuff with "only" using the URL in such way. You were testing an address which requires previous login (or else it will always show n o t h i n g). I do not agree about @stamparm (he probably just saw the screenshot). Maybe ISNT a false positive, but you need to login first, take the cookie (google firefox javascript cookie button) and put it in `--cookie` switch. Only when you have done this we can finally see if your address have any SQL vulnerability. And, in practical terms, I (almost) never dump information.schema. Why you would do this? Also, like our croatian master said, UPDATE sqlmap _incontenti_.

And, yeah... You really should read the (fugging) manual. Its huge, I know, but, damn, you can see how sqlmap is strong and smart. 

@stamparm The mail i mentioned before was to you. Your uneducated friend here would be glad if you answer it. I mean, I like you, you created the _fucki-SWEETEST THING CALLED_ sqlmap, the devil's favorite web tool.

**Comment by stamparm** [comment]
`I do not agree about @stamparm (he probably just saw the screenshot)` <- nope. Can't say, but I am sure it is a false-positive.
