### ISSUE TITLE
Idea for preventing duplicate issues

### ISSUE THREAD

**Issue by stormwin** [sqlmapproject/sqlmap#2220]
Doing some searches on GitHub issues on sqlmap, i found out that ~31% ([261](https://api.github.com/search/issues?q=repo:sqlmapproject/sqlmap%20Unhandled%20Exception+in:title%20Duplicate%20in:comments) out of [826](https://api.github.com/search/issues?q=repo:sqlmapproject/sqlmap%20Unhandled%20Exception+in:title)) of reported issues from @sqlmapreporter are/were duplicates

I saw an app (can't remember the name) that uses Github API to check whether issue was already opened on GitHub. Something similar can be implemented in sqlmap

**_Why to implement this?_**

1. To prevent user spamming with same unhandled exception
2. To help developers to concentrate on real issues, not duplicates
3. Users with **rss feed** and **watch** on this repository are also spammed with lot of duplicate issues

**_How to implement?_**

Using [GitHub Search API](https://developer.github.com/v3/search/)

**_Scenarion_**
When exception appear in sqlmap, a question pop on the screen asking user whether want to report this exception as an issue or not. If user enter Y, then sqlmap should check for already open issue with same title (ex. Unhandled Exception (#abcdefgh)), then, if there is an open issue, show that to user with link, (ex: Issue was already reported. Check here: (link to issue)). Optionally, if issue is closed and there is a fix, show message to user that Issue was fixed, and user should update to latest commit

**_Example Link for issue check:_**
https://api.github.com/search/issues?q=repo:sqlmapproject/sqlmap%20Unhandled%20Exception+in:title

**Comment by stamparm** [comment]
@stormwin this is an example of great Issue, having good arguments and proper research being made. Everybody should follow your steps :)

**Comment by stamparm** [comment]
p.s. now, in case of a duplicate issue:
```
issue seems to be already reported
```

while in case of duplicate and closed:
```
issue seems to be already reported and resolved. Please update to the latest development version from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'
```
