### ISSUE TITLE
Propose for implementation of ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by stormwin** [sqlmapproject/sqlmap#2221]
Everything is described in this [link](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)

I think this is very useful to be implemented because sqlmap devs can set some sort of rules/questions which users must answer. It will be some sort of guide to write a correct and helpful issue. Devs will save time, knowing additional info about issue, and no need to ask a user with additional questions about (for example) OS, version....

Examples from other project on GitHub:

[Example of ISSUE_TEMPLATE file](https://github.com/primus/primus/blob/master/ISSUE_TEMPLATE.md)
[How it shows to users when creating new issue](https://github.com/primus/primus/issues/new)
How it looks like when issue is created:
`https://github.com/primus/primus/issues/489`

**Comment by stamparm** [comment]
With the latest commit New Issue (templated) page should look like:

![issue_template](https://cloud.githubusercontent.com/assets/921555/19277140/0176ba4a-8fd9-11e6-9401-eb0cc96e8bcc.png)
