### ISSUE TITLE
bad performance via REST

### ISSUE THREAD

**Issue by andyschmidt** [sqlmapproject/sqlmap#2236]
Hi,

I experienced a huge performance impact when I run a sql-query via the REST interface. It's almost 4 times slower. 2 minutes via command-line vs 7.5 minutes via REST. In both cases the configuration is done with the same config file.

The configuration files looks like this:
```
[Target]
requestFile = /tmp/sqlmap-1476804666.req
[Request]
cookie = BadCookie*
skipUrlEncode = True
[Detection]
level = 4
risk = 2
[Techniques]
tech = T
[General]
batch = True
freshQueries = True
outputDir = /tmp/
[Enumeration]
query = select mycol from mytable limit 1
```

To not stress the REST server too much I polled the status only every 10s.

Is this a known issue?
Or is there a 'secret' performance switch?

regards,
andy

**Comment by andyschmidt** [comment]
Btw, I'm running sqlmap version 1.0.10.16#dev on Ubuntu 15.10 amd64

**Comment by stamparm** [comment]
So, technique is time-based SQLi and we are talking here about bad performance?

**Comment by andyschmidt** [comment]
No, we are talking about "bad performance via REST".
I could reproduce the performance impact of REST (5 of 5) with similar the same time diffs (4x slower via REST).

**Comment by SweetSoul** [comment]
> When you add complexity the code will run slower. Introducing a REST service if it's not required will slow the execution down as the system is doing more.
> 
> Abstracting the database is good practice. If you're worried about speed you could look into caching the data in memory so that the database doesn't need to be touched to handle the request.
> 
> Before optimizing performance though I'd look into what problem you're trying to solve and the architecture you're using, I'm struggling to think of a situation where the database options would be direct access vs REST.

Source: http://programmers.stackexchange.com/questions/286788/what-is-faster-using-rest-api-or-querying-a-database-directly

**Comment by stamparm** [comment]
Ok people, this doesn't have anything to do with "performance". Will patch.

**Comment by stamparm** [comment]
(--time-sec) auto-adjustment mechanism has been turned-off in REST-API

**Comment by stamparm** [comment]
@andyschmidt please wait a sec. Have to find a better patch. Will let you know.

**Comment by stamparm** [comment]
@andyschmidt done. Please retry with latest revision. I've tested and now it works properly

**Comment by andyschmidt** [comment]
@stamparm looks very good :) great work! 
thanks a lot
