### ISSUE TITLE
Headers not substituted correctly when using --eval and custom injection points

### ISSUE THREAD

**Issue by McBartok** [sqlmapproject/sqlmap#2238]
When I attempt to use --eval on a cookie/header value, it only makes to correct substitutions when checking the stability of the URL. Once the payloads start being inserted, the evals value is no longer applied.

So if I run the following:
`./sqlmap.py -v 6 -r req.txt --eval="import base64;SessionID=base64.b64encode(SessionID.encode('latin1'))"`

against the following sample request:

> GET /index.php HTTP/1.1
> Host: 127.0.0.1:9000
> Cookie: SessionID=blah*
> Connection: close

So I would expect that all this value should always be substituted, but perhaps I am using it incorrectly :P

I tested this against the latest commit which was, at the time of testing: 38d74cf61ca2383ed78359847411020c912e173a

**Comment by stamparm** [comment]
Fixed :)

**Comment by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [comment]
Sorry to post in this thread, but on a related issue, does this fix allow modifying headers such as "Host". Specifying "Host" in the eval code did not update the HTTP host headers when tested.

**Comment by stamparm** [comment]
@DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K nope. For such stuff you can access the special dictionary `_locals`. With it you can modify any local variable inside the `lib/request/connect.py`->`queryPage()`. For example, in your case you could try:

```
python sqlmap.py -u "..." --eval="_locals['auxHeaders']['Host'] = 'foo.com'" -v 5
```

**Comment by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [comment]
Thanks worked perfectly, thx! :dancer:
