### ISSUE TITLE
Random Delay in seconds between one or multiple HTTP request

### ISSUE THREAD

**Issue by s3c1t** [sqlmapproject/sqlmap#2256]
i want use sqlmap for random delay seconds between one or multiple http request.
for example:
i used following command for each http request. but not worked
python sqlmap.py -u "http://example.com/info.aspx?id=1" --delay=$(shuf -i 1-10 -n 1)

**Comment by stamparm** [comment]
`...--eval="import time; import random; time.sleep(random.randint(1,10))"`
