### ISSUE TITLE
--skip-urlencode changes Content-Type

### ISSUE THREAD

**Issue by jeroen-80** [sqlmapproject/sqlmap#2259]
## What's the problem (or question)?
I'm testing an XML-alike backend. With a -r <request>, sqlmap URL encodes the data. This breaks the backend code. To prevent URL encoding I use --skip-urlencode. The XML content looks ok now. However, the content-type is changed from the original "Content-Type: application/x-www-form-urlencoded" (which it isn't, I know, but I'm not the dev) to "Content-type: text/plain; charset=utf-8" (correct). However this results in another error at the backend, rejecting the now well-formed XML content. As far as I can see I cannot override this behavior (e.g. by using "--header 'Content-Type: application/x-www-form-urlencoded'").

## Do you have an idea for a solution?
Not automatically changing the "Content-Type" header or adding an option to override default change of "Content-Type" header.

## How can we reproduce the issue?
Use -r <request> with --skip-urlencode where <request> contains header "Content-Type: application/x-www-form-urlencoded".

## What are the running context details?
IMO irrelevant for this issue.

**Comment by stamparm** [comment]
You are doing invalid stuff here. Content-type says that the body contains urlencoded data while you don't want it urlencoded. This is not an issue of sqlmap. If it says urlencoded sqlmap will urlencode it. No discussion here

**Comment by jeroen-80** [comment]
I fully agree that it's weird to state in the header that the content is URL encoded while it isn't and the code doesn't even accept URL encoded content.

However... sqlmap is a hacking / security testing tool right? I guess it might be handy to support non-compliant targets since developers create non-perfect code :)

**Comment by stamparm** [comment]
Sqlmap automates cleaning of lots of junk that regular users just don't know what it is. Also, sqlmap here tried to clean your junk. Now, you want me to turn it off in expense that other users won't be able to run their stuff, while sqlmap just wants to stay standard compliant?

**Comment by jeroen-80** [comment]
Fair enough, I've already pathed it myself in my local copy and there won't be an update so other folks cannot use this - IMHO - useful feature. Thanks for the quick response!
