### ISSUE TITLE
Sqlmap retrieving wrong characters

### ISSUE THREAD

**Issue by tdias25** [sqlmapproject/sqlmap#2267]
i'm retrieving users password, but at the first retrive i realized that the password came with wrong chars, something, for example, like this **"6BB4837EB94=29105EE4568QDA7DC67ED2CA2AD9"**, then i tried again and came another password **"6BB4837EB74329105EE4568DDA7DC67ED2CA2qD9"**, and it continue to happen with other users passwords with alot of wrong chars, what can i do in cases like this? 

i've tried with --hex, but in this case the query returned empty

**ps: the site uses ModSecurity.**
here's my query:

sqlmap.py -r c:/xxx.txt -p email --random-agent --level=5 --risk=3 -v 3 --threads=10 --tamper "unmagicquotes.py,between.py,modsecurityzeroversioned.py,charencode.py" --passwords --fresh-queries

sorry for bad english.

**Comment by stamparm** [comment]
Site uses ModSecurity :). I am not sure how is this a sqlmap's Issue then.

**Comment by stamparm** [comment]
I am closing this one down as many before like this. You should manually inspect what's triggering the ModSecurity here (most probably `... FROM mysql.user` in `--passwords`), try to bypass it manually and then try to adjust the sqlmap (if possible). Please don't open this kind of Issues any more.
