### ISSUE TITLE
hi i heav another problem with mssql 

### ISSUE THREAD

**Issue by yf007** [sqlmapproject/sqlmap#2269]
## What's the problem (or question)? 

* Installation method (e.g. `pip`, `apt-get`, `git clone` or `zip`/`tar.gz`):
* Client OS (`kali`) !!!!!!!!!!!
* Program version (last): 
* Target DBMS (`Microsoft SQL Server`): 
* Detected WAF/IDS/IPS protection (`unknown`):
* SQLi techniques found by sqlmap (`error-based`):
* Results of manual target assessment (e.g. found that the payload `query=test' AND 4113 IN ((SELECT 'foobar'))-- qKLV` works):
* Relevant console output (if any):
* Exception traceback (if any):

**Comment by yf007** [comment]
![screenshot from 2016-11-01 19-36-13](https://cloud.githubusercontent.com/assets/18291801/20148737/a0b18466-a6b6-11e6-8095-c2b913f4790b.png)

**Comment by yf007** [comment]
![screenshot from 2016-11-01 20-11-25](https://cloud.githubusercontent.com/assets/18291801/20149516/4c05af74-a6ba-11e6-8fe2-055454dc6ec8.png)

more from this problem

**Comment by yf007** [comment]
wehn i put threads to 1 is ok
but wehn is on 10 is same problem

**Comment by stamparm** [comment]
WAF/IPS/IDS detected. Please don't open this kind of issues anymore
