### ISSUE TITLE
I'm sorry about the previous post is a mistake

### ISSUE THREAD

**Issue by yf007** [sqlmapproject/sqlmap#2270]
Hey
I'm sorry about the previous post is a mistake
I was going to open it up a bit more professional
In the present case there is no server protection
mssql
And yet her problem

**Comment by yf007** [comment]
![screenshot from 2016-11-01 20-57-16](https://cloud.githubusercontent.com/assets/18291801/20158180/775c189e-a6e1-11e6-86c5-2b5f1dcc2291.png)
![screenshot from 2016-11-01 20-53-12](https://cloud.githubusercontent.com/assets/18291801/20158178/7759c918-a6e1-11e6-8525-0710c1e985f8.png)
![screenshot from 2016-11-01 20-52-16](https://cloud.githubusercontent.com/assets/18291801/20158179/775a9bf4-a6e1-11e6-91df-2d3d3cc707cf.png)

**Comment by stamparm** [comment]
Output is trimmed and you are being warned about that. That basically means that data is missing from the error message.

Also, it would be helpful for yourself to run it with `--parse-errors`.

One more thing. You are opening this issue, referencing to the #2269, while it has ABSOLUTELY nothing to do with the #2269. In this case you have `PID` while in that case you have `SAVE` parameter. How to not close this Issue too?

**Comment by stamparm** [comment]
Basically, you have an Issue on your target having limited output, while you are blaming the sqlmap by raising pointless issues one by one. Also, you have spent 0 minutes of manual analysis what is going on at that same target. How to not close this issue?

**Comment by yf007** [comment]
thank you for the answer
The problem begins almost any server that uses mssql I encountered this problem
Is there a new protection that exists on the server with mssql?

**Comment by stamparm** [comment]
Has sqlmap warned about the existence of any kind of protection (even unknown)? Have you invested any time in debugging what's going on (by manual SQLi)? Have you tried to run `--parse-errors`?
