### ISSUE TITLE
size differs from remote file

### ISSUE THREAD

**Issue by jeroen-80** [sqlmapproject/sqlmap#2272]
## What's the problem (or question)?
I want to download files using a time based blind injection ("--file-read"). For small files this works perfect. For larger files, there's an issue in virtually all cases: "size differs from remote file". A full re-run with "--fresh-queries" (that takes hours - days in this specific case) typically also results in an incomplete file ("size differs from remote file") with a different size.

## Do you have an idea for a solution?
Re-run "--file-read" with an offset in bytes. Without an auto-merge of different downloads would be excellent, auto-merge or something like "--resume" even better :)

## How can we reproduce the issue?
Don't know how to reproduce without leaking client info, but I guess the feature request is clear. If not please let me know.

## What are the running context details?
AND time-based blind injection, "--time-sec 3"

**Comment by stamparm** [comment]
You are forcing the `--time-sec` to a lower value than default one. Why? Also, sqlmap automatically optimizes the value based on network latency. I would blame that decision to make data retrieval worse in your case. It is like you are raising an issue with the `--time-sec 1` while the network latency is greater than 1 second.

**Comment by stamparm** [comment]
One more thing. You are retrieving file content with time-based SQLi and you are expecting perfect 1 to 1 copy. That's impossible to expect. Closing this down

**Comment by jeroen-80** [comment]
> You are forcing the --time-sec to a lower value than default one. Why?

Because auto optimize switches to 2s and gets me reliable results for all non-large files + auto switches from 2s to 3s quite often. So for me that's a safe default.

> One more thing. You are retrieving file content with time-based SQLi and you are expecting perfect 1 to 1 copy. That's impossible to expect. 

I'm not expecting perfect results, especially not for time bases injections. That's why I propose an *improvement* so I can make the result even better than they are now.

**Comment by jeroen-80** [comment]
Just to be sure I ran a new download last night with auto optimize: same result.

So back to my original feature request: can a fileread with a given offset or a resume function me implemented? Thanks!

**Comment by stamparm** [comment]
Get the latest revision and try the `--fresh-queries --file-read=... --first=...`. By setting that option `--first` (in combination with `--fresh-queries` if you had previous problems) you can retrieve the file from given offset. This is just for retrieval of file starting from given offset. There won't be any merge-alike option. To merge it you should do something like `cat A B > C`.
