### ISSUE TITLE
--crawl-exclude skips URLs but still posts data to them ?

### ISSUE THREAD

**Issue by BabyBit** [sqlmapproject/sqlmap#2273]
I specified --crawl=3 --forms --crawl-exclude="logout|password" to avoid logout.htm and password-reset.htm

and log says that it skips /password-reset.htm from crawling, but lower in log I see that it posts data to that URL, is this because other URLs can have the forms send the data to /password-reset.htm ? 
If so, can sqlmap have a --post-url-exclude or --post-exclude ? 

In my case it logs the user out when reaching password-reset.htm

Thanks.

**Comment by BabyBit** [comment]
I just found the options --safe-url, --safe-post, etc now, so these might help me get over the session issue mentioned above. 
So I don't want to ask for new options into sqlmap if admins don't feel this is needed :)

**Comment by stamparm** [comment]
Fixed. From now on `--crawl-exclude` will be taken into the consideration in this kind of cases too.
