### ISSUE TITLE
Sqlmap not detecting simple Error based SQL inection

### ISSUE THREAD

**Issue by 000-Copernicus-000** [sqlmapproject/sqlmap#2274]
Sqlmap version 1.0.11.10#dev is not able to detect simple Error based SQL injection.

![screen shot 2016-11-11 at 11 15 04 am](https://cloud.githubusercontent.com/assets/21128810/20206241/c82cd78e-a800-11e6-9c8c-2857f693ea6c.png)

![screen shot 2016-11-11 at 11 15 38 am](https://cloud.githubusercontent.com/assets/21128810/20206288/1398a892-a801-11e6-9961-e22aa253efc6.png)

1. Goto to the site www.kabeline.at/index.php?lang=2 or any site with Error based SQL injection
2. Put a **single quote** at the end of "lang" parameter as shown in pic.Site throws an error regarding wrong sql syntax.
3. Fireup sqlmap and feed the url to it and sqlmap shows that the parameter lang is not injectable

**Comment by stamparm** [comment]
1. Error message is not a proof of SQL injection
2. Please learn basics of SQL injection. Just google for "SQL injection" and read a lot
3. Please don't post real URLs here
4. That same site is backslash escaping special characters (single quotes and maybe some more). This means that it could be injectable, but you should on your OWN find which characters are filtered/escaped and fine tune the sqlmap
5. Please don't open this kind of issues any more
