### ISSUE TITLE
& in URL causing sqlmap to go into the background

### ISSUE THREAD

**Issue by thecarterb** [sqlmapproject/sqlmap#2276]
## What's the problem (or question)?
If there is a `&` in the url, like: `https://www.target.com/example.php?id=1&p=2`, sqlmap will go into the background(in an unkillable) and pass everything else past the `&` as a bash command

## How can we reproduce the issue?

1. run `sqlmap -u https://target.com/example.php?id=1&p=2 -f`
2. sqlmap starts, and gives you a process number. Something like `[1] 10841`, but then says `-bash: -f: command not found`
3. ^C out but it is still running in the background in an unkillable state. 

## What are the running context details?

* Installation method (e.g. `pip`, `apt-get`, `git clone` or `zip`/`tar.gz`): pip(Raspbian), apt(Kali)
* Client OS (e.g. `Microsoft Windows 10`): Kali and Raspbian
* Program version (`python sqlmap.py --version` or `sqlmap --version` depending on installation): 1.0.11
* Target DBMS (e.g. `Microsoft SQL Server`): Firebird, but it shouldn't be relevant to the issue
* Relevant console output (if any): `sqlmap -u https://ww.url.com/page/?lang=en&p=2 -f`

**Comment by stormwin** [comment]
Put in quotes that url 
-p "https://www.target.com/example.php?id=1&p=2"

**Comment by thecarterb** [comment]
@stormwin thanks, that worked
