### ISSUE TITLE
How to use sqlmap with double quotes injection?

### ISSUE THREAD

**Issue by Comancheroo** [sqlmapproject/sqlmap#2278]
Hello,

I found a sql injection in the cookies. I tested manuel and this vulnerability true.
But I want use the sqlmap for automatic processing.

Cookie Name: comparison
Cookie Value: 161=161
161 and 2=2 **=** 161 and 2=2 | True.
-161 union select db_name() = -161 union select db_name() | True and db name it seems.
161 **=** 161 and 2=2 | False.
I need same double quotes, possible by sqlmap?
Example: 161+query=161+query

I tested: --cookie="comparison=161*=161*" but not working.

Thanks.

**Comment by stamparm** [comment]
You've put "double quotes injection" in the title of this "issue", while there is no trace of double-quotes injection in your provided payloads. Also, it is not clear what is the original value for the cookie `comparison` (in half of cases it appears that `161` is the original value while in the other half it appears that the `161=161` is the right value).

**Comment by Comancheroo** [comment]
Hi Stamparm,
Thank you for interest.

This is a complicated problem.
http://www.site.com/c.aspx?id=160 GET **>** insert "comparison = 160=160" in cookies.
http://www.site.com/products.aspx **<** show item 160. "comparison = 160=160" in cookies.

I used "--second-order" for products.aspx but the cookies are making a problem and redirected to home page.

**Comment by stamparm** [comment]
Please use some custom approach here as this doesn't look like something
automation friendly
Bye

**Comment by Comancheroo** [comment]
Thanks Stamparm,
Bye.
