### ISSUE TITLE
How to ignore redirects (302)?

### ISSUE THREAD

**Issue by VK102** [sqlmapproject/sqlmap#2286]
Is there a configuration for sqlmap that ignores redirects (302)?

**Comment by stamparm** [comment]
First of all, you are being asked for that, so this Issue is pointless.

```
[13:20:46] [INFO] testing connection to the target URL
sqlmap got a 302 redirect to 'http://www.foobar.xyz/'. Do you want to
follow? [Y/n]  <- here press N!!
```

---

If you wanted to ask how to do it automatically, use `... --batch --answer="redirect=N"`

**Comment by stamparm** [comment]
p.s. with the latest commit you can also use switch `--ignore-redirects`

```
$ python sqlmap.py -hh | grep redirect
    --ignore-redirects  Ignore redirection attempts
```

**Comment by drequil** [comment]
Thank you!
