### ISSUE TITLE
http://example/users/id/111/blablabla how test this type URL's

### ISSUE THREAD

**Issue by vah13** [sqlmapproject/sqlmap#2288]
Hi, guys.
I have this situation.
Some a website has this URL's
http://example/users/id/111/blablabla

How can I use crawl mode for sqlmap start test 111 value in automation type?
When I use --crawl = 5 sqlmap says - not found any get parameter and was stopped (--forms also don't help). 

tnx

**Comment by stormwin** [comment]
put * instead of 111

**Comment by vah13** [comment]
yes, but I want to use crawl mode

**Comment by vah13** [comment]
he, also, can't test directory name?

**Comment by stamparm** [comment]
In crawling mode, those kind of links are ignored. GET and POST parameters are being taken into the consideration, non-parameter links are not (like in your case). sqlmap can't recognize all custom in-path parameter schemes, hence those are ignored.
