### ISSUE TITLE
Hotkeys for sqlmap while running

### ISSUE THREAD

**Issue by kwalters94** [sqlmapproject/sqlmap#2292]
## What's the problem (or question)?
Currently there is no way to disable certain arguments such as batch or technique on the fly.
## Do you have an idea for a solution?
What I am proposing is a hotkey or pause argument that would allow changing of the parameters on batch jobs.
## How can we reproduce the issue?

1. launch sqlmap against a list of target pages
2. add the batch command
3. attempt to disable batch command after starting
4. ?? profit?

## What are the running context details?

* Installation method (e.g. `pip`, `apt-get`, `git clone` or `zip`/`tar.gz`):
* Client OS (e.g. `Microsoft Windows 10`)
* Program version (`python sqlmap.py --version` or `sqlmap --version` depending on installation): 
* Target DBMS (e.g. `Microsoft SQL Server`): 
* Detected WAF/IDS/IPS protection (e.g. `ModSecurity` or `unknown`):
* SQLi techniques found by sqlmap (e.g. `error-based` and `boolean-based blind`):
* Results of manual target assessment (e.g. found that the payload `query=test' AND 4113 IN ((SELECT 'foobar'))-- qKLV` works):
* Relevant console output (if any):
* Exception traceback (if any):

**Comment by stamparm** [comment]
Python doesn't support hotkeys. End of discussion :(

**Comment by Ekultek** [comment]
@stamparm http://schurpf.com/python/python-hotkey-module/

**Comment by stamparm** [comment]
@Ekultek "I used to program quite a bit using AutoHotKey to automate several tasks in Windows."

**Comment by Ekultek** [comment]
@stamparm aww, okay. Thought I found something cool lol.
