### ISSUE TITLE
Can't  retrieve the columnd data

### ISSUE THREAD

**Issue by kleiden** [sqlmapproject/sqlmap#2296]
python sqlmap.py -u "http://www.target.com/go.php?find=e" -D example -T login -C email,password --dump
Sqlmap can not retrieve the email and length of query and output is Null
however havij can enumerate length but can't retrieve how can i retrieve the length of data, however for password not have this problem

**Comment by stamparm** [comment]
Please use Havij if it suits your needs. If you see that both programs fail, then you should ask yourself, WHY?
