### ISSUE TITLE
sqlmap cloud based?

### ISSUE THREAD

**Issue by s3c1t** [sqlmapproject/sqlmap#2305]
Does it exist cloud based sqlmap Commercial or free(open source)?
i want to crawling and scanning a list of domains by sqlmap. but both the crawling and scanning too late to result.
or
does it exist distributed sqlmap tool?(open source)(for example Dsqlmap tool)
thanks

**Comment by stamparm** [comment]
Sorry, there is no such thing. Although, you could take a look into `sqlmapapi` (https://github.com/sqlmapproject/sqlmap/wiki/Usage#api-rest-json) and make your own

**Comment by s3c1t** [comment]
thank you for your replay
