### ISSUE TITLE
injection mariadb via sqlmap

### ISSUE THREAD

**Issue by Ays4R-H4rB** [sqlmapproject/sqlmap#2307]
hi , i have this error in some website :

 there is error : You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'f1290186a5d0b1ceab27f4e77c0c5d68'' at line 1

how can i inject mariadb via sqlmap ?

**Comment by stamparm** [comment]
MariaDB is automatically supported by sqlmap via MySQL engine. Except for that error you haven't provided any other useful information.

**Comment by Ays4R-H4rB** [comment]
ok look , you mean i use 
--dbms "MySQL"  and this will work or what ?

**Comment by stamparm** [comment]
Just provide the url as in any other case. None need for forcing --dbms
