### ISSUE TITLE
404 on canonical URI

### ISSUE THREAD

**Issue by JonhSilver** [sqlmapproject/sqlmap#2316]
Something wrong with response on canonical URIs. Always retur 404 status as in browser same request got 200 status. And sql map in verbose 6 mode showing strange response Transfer-encoding: chunked which not exist in browser

[10:19:39] [TRAFFIC OUT] HTTP request [#3]:
GET http://canonical.name/index/order/0-34 HTTP/1.1
Host: canonical.name
Referer: http://canonical.name/index/order/0-34
Accept-encoding: gzip,deflate
Accept: */*
User-agent: Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.3) Gecko/20061201 F
irefox/2.0.0.1 (Ubuntu-feisty)
Connection: close

[10:19:40] [TRAFFIC IN] HTTP response [#3] (404 Not Found):
Content-encoding: gzip
Transfer-encoding: chunked
Vary: Accept-Encoding
Uri: http://xn----bba7acd1aag7l.n--ai:80/index/order/0-34  'uri hidden
Server: nginx
Connection: close
Date: Fri, 23 Dec 2016 07:19:47 GMT
Content-type: text/html; charset=utf-8

<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Страница не на

**Comment by stamparm** [comment]
How to reproduce this?

**Comment by JonhSilver** [comment]
just use any canonical site i think

**Comment by stamparm** [comment]
Canonical? Ubuntu?

**Comment by JonhSilver** [comment]
User agent does not matter i think not tested

**Comment by stamparm** [comment]
This is very confusing. What do you call canonical? Please help to reproduce this issue or I'll need to close it down?

**Comment by JonhSilver** [comment]
http://виагру-заказать.рф

**Comment by stamparm** [comment]
![1234](https://cloud.githubusercontent.com/assets/921555/21450953/980ab118-c8fb-11e6-929c-f45404c1909c.png)

**Comment by stamparm** [comment]
My last comment here. You are most probably using some LANG_C terminal while copy-pasting the UTF-8 (alike) URL into it. Please don't do that. Google how to properly set your terminal before raising this kind of issues

**Comment by JonhSilver** [comment]
![image](https://cloud.githubusercontent.com/assets/24619483/21451033/95d32282-c904-11e6-8411-26aefbc7399f.png)

python.exe sqlmap/sqlmap.py -u "http://виагру-заказать.рф/index/zakazat_tadasip/0-34" --tor --tor-port=9150 --tor-type=socks5 --check-tor --batch --random-agent --level=5 --risk=3 --answers="redirect=y" --threads=10 --drop-set-cookie  --answers="sitemap=y" --crawl=1 --forms -v6

**Comment by JonhSilver** [comment]
Poblem with --tor without it status is 200
