### ISSUE TITLE
Sqlmap  not coming up at all

### ISSUE THREAD

**Issue by kepingaeh** [sqlmapproject/sqlmap#2317]
<img width="338" alt="capturesqlmap" src="https://cloud.githubusercontent.com/assets/24739397/21463475/8803d632-c91e-11e6-97bc-47eed346c0cc.PNG">
<img width="428" alt="captureenvironmental" src="https://cloud.githubusercontent.com/assets/24739397/21463683/7a8eb0aa-c921-11e6-84cb-f7e857411f41.PNG">

As you can see in the image it's not responding to the usual command I have been using for a month or so. It was working fine yesterday then it suddenly doesn't responds anymore in the middle of a session.

I have also posted a picture of enviromental vriables. I think nothing changed? What should I do to make it work again?

**Comment by Ekultek** [comment]
Tell me both these Windows issues are jokes right..?

**Comment by kepingaeh** [comment]
I'm new at this,please just answer instead of being mean.

**Comment by Ekultek** [comment]
Windows does not use shebangs in order for it to work like that you'd have to assosicate the file type with the exe, however that's a pain in the butt to do so all you'll have to do is run `python sqlmap.py` just make sure you call the exe before you run the program

**Comment by kepingaeh** [comment]
It did not work either ..I got ..[errno 2] No such file or directory

**Comment by Ekultek** [comment]
Then your in the wrong directory or the file doesn't exist

**Comment by kepingaeh** [comment]
how could it not exist if I have been using it just fine for the last month? Perhaps change something in the variables or uninstall and reinstall program? Also theres very little space in my laptop left...do you think it has to do with that fact?

**Comment by Ekultek** [comment]
Well first you'd need to provide the full error message secondly run `dir` and post a picture of the output thirdly type just `Python` and see what happens

**Comment by stamparm** [comment]
I would say that you either broke: A) Python environment or B) downloaded sqlmap. Hence, you should reinstall the Python and re-download the sqlmap from this repository. You can be sure that sqlmap hasn't stopped because it felt that it shouldn't work anymore
