### ISSUE TITLE
sqlmap does not work on Windows 10

### ISSUE THREAD

**Issue by PekaFat** [sqlmapproject/sqlmap#2318]
Even if i enter: 
`sqlmap.py --wizard`

It's says:
`sqlmap.py: error: missing a mandatory option`

On Windows 7 all was fine.

sqlmap 1.0.12.14#dev
Win10 10.0.14393.576 x64 Enterprise LTSB
Python 2.7.13

![default](https://cloud.githubusercontent.com/assets/13280748/21463798/1caf8722-c988-11e6-9721-e4b028054a33.PNG)

**Comment by Ekultek** [comment]
@stamparm hope you don't mind but I saw this in my email..

Try this: `python sqlmap.py -u http://www.bible-history.com/subcat.php?id=5 --wizard`

**Comment by PekaFat** [comment]
This works now, sorry and thanks.
