### ISSUE TITLE
One more error from #2316

### ISSUE THREAD

**Issue by JonhSilver** [sqlmapproject/sqlmap#2319]
So if URI has Unicode simbols (canonical) then
1. using switch --tor always return 404 status
2. output folder always create folder called "-" but not with URI name, also overwrite previous one folder with everething inside this folder

**Comment by stamparm** [comment]
![111](https://cloud.githubusercontent.com/assets/921555/21472994/ec64c970-caf3-11e6-9d49-445f332de44e.png)
