### ISSUE TITLE
Sqlmap don't see time-based sql injection

### ISSUE THREAD

**Issue by airatkazan** [sqlmapproject/sqlmap#2321]
I found time-based sqli with Burp Suite pro (scanner module). I check this vuln with Burp Suite repeater module (change time argument in payload) - vuln work.
But if i run sqlmap, he don't see this sqli.

Request and response unusual:
I send request with POST -> get response with 303 http code (303 code - redirect with GET method) -> get request with GET method to new location.

SQLi work in first stage: POST->303 code

Standard POST request
POST /xxx HTTP/1.1
Host: www.ZZZ.com
User-Agent: ....
.....
arg1=1&arg2=2'%2b(select*from(select(sleep(20)))a)%2b'&arg3=3........

Response:

HTTP/1.1 303 See other
Date: Sat, 24 Dec 2016 18:35:28 GMT
Server: Apache/x.x.xx (Unix) 
Set-Cookie: cookie=XXXXXXXXXXXXXXXXXX ; expires=Sun, 29-Dec-2017 04:35:48 GMT; path=/
Location: https://www.ZZZ.com/new-location
Cache-Control: max-age=3600
Content-Length: 4
Connection: close
Content-Type: text/html; charset=utf-8

Burp Suite payload: **and (select*from(select(sleep(20)))a)--**
Also Burp found another sqli and in error i found, what database - MySQL

sqlmap -r post.txt --beep --dbs --dbms=mysql --level=5 --risk=3 
and i say No to sqlmap answer about redirect.
Sqlmap don't see sqli..... 
maybe I'm doing something wrong?
Or sqlmap don't search injection in 303 code response?

**Comment by stamparm** [comment]
Have you tried tamper scripts?

**Comment by airatkazan** [comment]
No, i don't use tamper script.

**Comment by stamparm** [comment]
What's the content of your request file?

**Comment by airatkazan** [comment]
standard html page with data created from POST args

**Comment by airatkazan** [comment]
POST /xxx HTTP/1.1
Host: www.ZZZ.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://www.ZZZ.com/yyyy
Cookie: hjhjg35b34b545bjk4b53k5bkj435kjh345j34j5hjh45jh
DNT: 1
Connection: close
Upgrade-Insecure-Requests: 1
Content-Type: application/x-www-form-urlencoded
Content-Length: 471

arg1=AAA*&arg2=5&arg3=10&arg4=BBB........ >20 args

arg1 - vulnerable

**Comment by stamparm** [comment]
Please try to use tamper scripts. Also, issue can't be based on "Burp
works, sqlmap doesn't". In those kind of cases, if you are not able to find
what's causing that, I'll close it down and tell you "Please use Burp then
as I am not able to reproduce"

**Comment by airatkazan** [comment]
ок, but i don't understand which tamper script i must use in this situation....?

**Comment by stamparm** [comment]
Well, go to the tamper script directory and start reading tamper scripts in
some editor. There are descriptions included. Also, you could Google for
"sqlmap tamper". If not sure, try and learn. If that doesn't help nothing
can help you

**Comment by airatkazan** [comment]
may be sqlmap don't search injection if response not  with 200 code? don't search if response content redirect and try sqli in end URL?

**Comment by stamparm** [comment]
Not true. It searches. Also, you are mentioning time-based sqli and now
status codes. You lack fundamental knowledge. Closing this as invalid
