### ISSUE TITLE
How to make it show the full code in a small window?

### ISSUE THREAD

**Issue by oomrymtn** [sqlmapproject/sqlmap#2324]
## **How to make it show the full code in a small window?**

![1](https://cloud.githubusercontent.com/assets/7460182/21521877/4d38523a-cd33-11e6-80d5-dee31107b2d8.png)

**Comment by erwinsalarda** [comment]
you can customize it in cmd.

**Comment by erwinsalarda** [comment]
you use alt+shift+properties

**Comment by oomrymtn** [comment]
Thanks, Bro!
