### ISSUE TITLE
latest version sqlmap not detect Stacked Queries

### ISSUE THREAD

**Issue by mdaiezatt** [sqlmapproject/sqlmap#2325]
Previously, i was using sqlmap version 1.0.6.65#dev. After i update to the latest version, the SQLi at that particular  page was not successful even though it is the same command i used in the old version.

When i come back to other computer, which still using the old version 1.0.6.65#dev, the vulnerability  was still there. Just that new sqlmap did not detect it. Type of injection at that time was :

Type: stacked queries
Title: MySQL > 5.0.11 stacked queries (comment)

The current version i have now 1.0.12.16#dev. Is anyone got the same issue?

**Comment by stamparm** [comment]
Are you able to get the banner with old version if you run ...
--flush-session --banner?

**Comment by mdaiezatt** [comment]
stamparm,

I just try as you suggested. My website using https and test it on specific parameter (in my case: -p data[User][token]. My command in sqlmap as below:

`sqlmap.py -r myfile --random-agent --dbms=mysql --force-ssl -p data[User][token]  --flush-session --banner`

> [15:43:59] [INFO] POST parameter 'data[User][token]' appears to be 'MySQL > 5.0.11 stacked queries (comment)' injectable 
for the remaining tests, do you want to include all tests for 'MySQL' extending provided level (1) and risk (1) values? [Y/n] Y

with old version, output show : banner:    '5.6.34'

with new version it suggest me to tamper=space2comment. With the same source file, it just show unsuccessful.

> [15:52:48] [WARNING] POST parameter 'data[User][token]' does not seem to be injectable

Other information:
old version , i used Ubuntu 16.04 with python version 2.7.12
new version, i used MacOS with python version 2.7.11

is there any possible the problem occur because of that?

**Comment by stamparm** [comment]
I need more data here. Can you share the target details privately (`miroslav@sqlmap.org`)? If not, I would really need something tangible here (e.g. run with `-v 3` in both old version and new version of sqlmap and compare the used payloads).

p.s. there should not be any "critical" changes in between those two versions, at least from the "stacked" detection part
