### ISSUE TITLE
sqlmap --where="table_name <> 'tbllog%'"

### ISSUE THREAD

**Issue by nininono** [sqlmapproject/sqlmap#2329]
hi 
my target have 9 database
a database named "Account"
account database have 1300 tables!
i want dump 800 tables its
my queri is:
sqlmap -u "target.com" --batch -D Account  --tables --where="table_name <> 'tbllog%'"
but it is't working, because it dump all tables again... but i don't want all tables..
please help me...

**Comment by nininono** [comment]
i wrote script : 
 sqlmap -u "target.com" --batch -D Account --tables --start 20 --stop 400
but i want to know sqlmap tools can  filter tables with condition "--where"??
thank you

**Comment by stamparm** [comment]
`--where` is usable only for table dumping. If sqlmap would use `--where` in all queries everything would simply stop working. For example, while performing table dump sqlmap has to check whether the table exists, what are its column names and types and start dumping it. If `--where` would be used in all queries majority of queries would just stop working as given `WHERE` condition will evaluate to false.
