### ISSUE TITLE
http post request with encoding data

### ISSUE THREAD

**Issue by s3c1t** [sqlmapproject/sqlmap#2335]
I have a target that http post request from that encoded As follows:
data request post first url encoded and then base64 encoded.
example request post from mentioned target As follows:
```
POST /test/test-page.php HTTP/1.1
Host: target.com
bmFtZTElM0R2YWx1ZTElMjZuYW1lMiUzRHZhbHVlMg==
```
for decoding data request post first must base64 decode and then url decode. actualy after decoding Something like the following:
```
POST /test/test-page.php HTTP/1.1
Host: target.com
name1=value1&name2=value2
```
Now my question is: how to run sqlmap on this target while injected queries in parameter values from data request post and then encode Similar as mentioned and then send to server target

**Comment by wufeifei** [comment]
`python sqlmap.py -r you/request/file/path --dbs --tamper=base64encode`

**Comment by stamparm** [comment]
Currently, there is no way to do it (you have a specific case).

I would suggest you to make a modification as suggested:
1) Provide non-base64 encoded data to the sqlmap (e.g. with option `-r`) as you would do in a normal case
2) Put to the line 1075 of `lib/request/connect.py`:
```
...
        post = post.encode("base64") if post else post
        if timeBasedCompare:
...
```
