### ISSUE TITLE
on back-end DBMS Microsoft SQL Server 2012 not working

### ISSUE THREAD

**Issue by ic3z** [sqlmapproject/sqlmap#2341]
this command can get current-db
```python sqlmap.py -r 1.txt --risk 3 --current-db```

but --tables not working
```python sqlmap.py -r 1.txt --risk 3 -D dbname --tables```

![image](https://cloud.githubusercontent.com/assets/24785607/21758180/10dd84f0-d674-11e6-9f9c-bf6139c5e80c.png)

the web error info :
```The SELECT permission was denied on the object \u0027sysobjects\u0027, database \u0027mssqlsystemresource\u0027, schema \u0027sys\u0027 ```

**Comment by stamparm** [comment]
You have everything in that error message and you are raising the issue :). For retrieval of database names non-problematic function DB_NAME() is used, while you can see that SELECT from system tables is restricted. Closing this down

**Comment by ic3z** [comment]
I am curious about that the option --dbs is working
This command is working,I can get the database number
```python sqlmap.py -r 1.txt --risk 3 --dbs```

This sql `SELECT name FROM master..sysdatabases` is working well

Perhaps the environment is too complicated.

**Comment by stamparm** [comment]
You've copy pasted the "permission denied" error message that says it all. If that is not clear to you, no other comment will help you either
