### ISSUE TITLE
Multiple Scanning // Vulnerability Database

### ISSUE THREAD

**Issue by user1114** [sqlmapproject/sqlmap#2343]
I dont know if you would consider this as usefull. 
Im sorry for my bad english.
_____________________________________________________________________________
**Multiple Scanning:**
When scanning a Url list, you can only do 1 by 1. 
I would love it to scan 2,5,10,X Urls at the same time.
This would keep my worktime shorter sometimes.
I dont know if this would be possible without changing all code,
but even dropping "Co-Workers" on other Servers (Clustering) seems to be interesting (for me).
____________________________________________________________________________
**Vulnerability Database:**
I think it would be a great feature, if it would be possible to write down all found Vulnerabilities
in a Database or Text/Csv File. It could be filled with Data like: Url, Parameter, WAF, Number
of Databases, Injection Method and Date.
I know we could do it by Hand, but it would be nice to get it done with an option like "--output=Vulnerability_Database.csv".
______________________________________________________________________________
I would love to discuss with you about my ideas.

**Comment by Ekultek** [comment]
I second the multiple scanning for bulk files, that would be amazing

**Comment by stamparm** [comment]
1) `I would love it to scan 2,5,10,X Urls at the same time.` <- you have the `sqlmapapi.py` for this kind of things. Also, you can easily run the `sqlmap.py` in parallel just from your shell. Not sure why to complicate sqlmap if there are doable workarounds just from your console. This is like saying "I would like curl to retrieve X web page retrievals" and I would ask you why??? when you can do that in a loop. Why do you have a shell at the first place

2) When doing a multiple URL scan (option `-m`) you are already getting something similar in the file which you are informed about while sqlmap run `[INFO] using '.../.sqlmap/output/results-01102017_1044am.csv' as the CSV results file in multiple targets mode`. Also, you are warned about it at the end of a multiple URL scan (`[INFO] you can find results of scanning in multiple targets mode inside the CSV file '.../.sqlmap/output/results-01102017_1044am.csv'`)
![1](https://cloud.githubusercontent.com/assets/921555/21801496/31351138-d722-11e6-9ceb-25e4d7103e88.png)
![2](https://cloud.githubusercontent.com/assets/921555/21801497/3135592c-d722-11e6-9381-4225ab299edd.png)
