### ISSUE TITLE
Blocking Ip

### ISSUE THREAD

**Issue by hamedrajabpour** [sqlmapproject/sqlmap#2344]
Hi
I really Need Help
My Target Use FortiGate 311B (IPS & Webfiltering) And Limited To Specific Ip Country
So I Can't Use Proxy For Bypass
And When I Start I'll Block

Can You Help Me To Bypass ?
Best Regards

**Comment by stamparm** [comment]
Manual SQL injection along with Tor (with country preferences set) or proxy with choosen country. This is not an issue for sqlmap
