### ISSUE TITLE
injection mysql 4 

### ISSUE THREAD

**Issue by Ays4R-H4rB** [sqlmapproject/sqlmap#2352]
hi all ,
i found an injection and the db version is mysql <= 5 , its 4 , and i cant fetch all db coz there is no schema on it , 
how can i fetch db name ?

**Comment by stamparm** [comment]
yo man. yu cant fetch tablz namez and columnz namez, not db namez. `DATABASE()` is alwayz availably (used by sqlmapz), even on MySQL 4. clozing dis down, ya dog

https://downloads.mysql.com/docs/refman-4.1-en.a4.pdf
![1111](https://cloud.githubusercontent.com/assets/921555/22000038/675916f4-dc3d-11e6-9490-b6b9a41fbb09.png)
