### ISSUE TITLE
--os-shell , can i upload my own shell ?

### ISSUE THREAD

**Issue by Ays4R-H4rB** [sqlmapproject/sqlmap#2354]
hello there 
i found site that vuln SQLi and i use --os-shell and i upload the sqlmap web shell , now the question is -
i can upload my own shell insted of sqlmap webshell ?

**Comment by stamparm** [comment]
sqlmap tries to upload its own shell at various locations using various techniques. Also, it is searching for specific sqlmap shell "trails" to see if it has been uploaded to the vulnerable site. There is no way how to make this automatic for some generic user provided shell and do it "user friendly" in the same time.

I would suggest you to inspect the content of payload that works while sqlmap tries to upload the shell and "reuse" it with your own shell.
