### ISSUE TITLE
SQLInjection how i can inject this target

### ISSUE THREAD

**Issue by nininono** [sqlmapproject/sqlmap#2355]
my target is: target.com/n=2&b=exam&c=ABC' (Inject Here)

so then i put ' in URL's end i see this error:

Error accrues:

SQL Query: SELECT Level, Code, Name FROM `tbl_field` WHERE Level<3 ORDER BY Code ASC ORDER BY Year DESC LIMIT 0 , 10
Error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY Year DESC LIMIT 0 , 10' at line 1
Code: 42000
File: /var/www/vhosts/target.com/httpdocs/db/db.php
Line: 98

now help me i can not inject its... i try with sql but not working... i know first must my query be balance.. but i can't... help me

**Comment by stamparm** [comment]
Google for `"ORDER BY" sql injection`
