### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by cacaocaca** [sqlmapproject/sqlmap#2363]
Linux kali 4.8.0-kali1-686-pae #1 SMP Debian 4.8.5-1kali1 (2016-11-04) i686 GNU/Linux
Sqlmap get reposity kali linux
So my information that i would like  ask is for example if on one database do no find anyone columns with name password maybe the columns name is with another name i have already happen it but the problem is for example if the database of user is big example 444.444 and i want see if the password is on "nickname" columns  but when i dump username,"nickname" the columns nickname show me always empty result for much minutes do no exsist one method for starting the dump for "nickname " from 10.000 words ?

**Comment by stamparm** [comment]
It is not comprehensible what you want. Please rewrite this.

**Comment by cacaocaca** [comment]
For example when do you dump username,nickcame  and the cound is big as 444.444 but the username showthe right output  but the "nickname" out is empy on the start dump  maybe is possible that the real output of "nickname" start when the count is example "10.000" so  i can set sqlmap to start the count of "nickname" at 10.000 word   ?

**Comment by cacaocaca** [comment]
No answer ?

**Comment by stamparm** [comment]
Not sure if you are trolling because I can't understand a thing you are talking about

**Comment by cacaocaca** [comment]
I can text on italian launguage but i doubt you understand it

**Comment by stamparm** [comment]
i can also text on croatian and i doubt that you understand it. that's why we have english on internet. please don't open this kind of issues any more because we obviously have a language barrier.

**Comment by cacaocaca** [comment]
What type of answer is that "please don't open this kind of issues any more because we obviously have a language barrier." Lol  . If you do no understand me other people can understand me i always have text on english and always have get answer lol  we are not all equal and i  understand you dont  worry if you text on croatian language but the problem is " you do no understand my english " and you  can't text on croatian language if first do no understand my question lol what do you say ? O_o ... And " this kind of issue" again is just one information no is one "issue "I think that your problem not is about  language but you does not think before writing ..
