### ISSUE TITLE
about time-based blind

### ISSUE THREAD

**Issue by seabird1992** [sqlmapproject/sqlmap#2365]
Hi,today i use sqlmap to inject a website.using level 1.then the it reminds that GET parameter 'bulletinId' appears to be 'Microsoft SQL Server GET parameter 'bulletinId' appears to be 'Microsoft SQL Server,and shows it looks like the back-end DBMS is '['Microsoft SQL Server', 'Sybase']'...but then i click "y",the end is that this parameter can't injectable,and how to solve this problems?thks for replying.

**Comment by stamparm** [comment]
Use higher values for `--level` and/or `--risk`. Also, if there is a IDS/IPS/WAF at the other end try to manually asses the target and use appropriate `--tamper` scripts. Anyway, you should do your part of the job in this kind of cases
