### ISSUE TITLE
Cookie value is changed

### ISSUE THREAD

**Issue by AlexAlexandru** [sqlmapproject/sqlmap#2370]
## What's the problem (or question)?

sqlmap.py -u "google.ro" --cookie="dd=%DB%11b%C5dy%B9%BA%A4%928%CA%A9%3D%ECl%0C%17%E8%8B_%02%F07%2C%18j%9C%95%95X%28%3B%02j%05W%21%81%C5%C1%2F%96%B4%DE5%19%25%AAw%A8%40x%CD%EB%D0%9D%3C%9C%02%17%89%D4%0A%9EWzT%94a%A5%3E%C3%C8%D3%DEf%9F+%EB%91%EAO%B4%D1%F5%FB%81%94%5Dn%7C%99%60%95%D6%28%5E%B4f%0Di%80%04" -v 6

I want to use that cookie but C:\Python is being added  here is a screenshot

![image](https://cloud.githubusercontent.com/assets/5292321/22247072/98dd38be-e240-11e6-98df-74aedb3f63ec.png)

## Do you have an idea for a solution?
No

## How can we reproduce the issue?
Use the sqlmap that I postent

## What are the running context details?
1.1.1.16

**Comment by stamparm** [comment]
This is the Windows command prompt "feature" explained here: https://github.com/sqlmapproject/sqlmap/issues/2370

Basically, that `%CD%` is expanded to the "current directory" value. One way to bypass that "problem" is to do this kind of stuff:

```
set percent=%
python sqlmap.py ... %A8%40x%percent%CD%percent%EB%D0%...
```
