### ISSUE TITLE
How can I rename the file log to log.txt

### ISSUE THREAD

**Issue by ajalvesneto** [sqlmapproject/sqlmap#2375]
## What's the problem (or question)?

I am working using the SQL Map in my application PHP.

I need remove only the log file, but, because the file has not a extension, the unlink function not working.

Has any way to add a extension in log file?

Can you help me?

## How can we reproduce the issue?
1. Execute a test
2. Generate a execution file log 
3. Try use a php file using the unlink function to remove the log file generated

**Comment by stamparm** [comment]
![unlink](https://cloud.githubusercontent.com/assets/921555/22466716/d43321c2-e7c1-11e6-847d-aedfa11f8c8f.png)

**Comment by ajalvesneto** [comment]
The unlink function does not work on files without extension.
I tried this function, but unsuccessful

**Comment by stamparm** [comment]
It is not true. Please take a look at attached screenshot

**Comment by ajalvesneto** [comment]
Well, i will wanna try again.

I call this function in a server, not in command line.

I don't know what is happening

**Comment by ajalvesneto** [comment]
My friend, I'm using XAMPP for local development.

And the unlinking function does not work in any way

Can you help me? I can't find something that fix my problem.

**Comment by ajalvesneto** [comment]
I got it, thanks buddy :)
