### ISSUE TITLE
hello gays I have problem with sqlmap 1.1.1.17#dev when i test a link i see  [CRITICAL] unable to connect to Google ('The read operation timed out')  help meplease I'm a beginer

### ISSUE THREAD

**Issue by bass0** [sqlmapproject/sqlmap#2376]
## How can we reproduce the issue?

1.
2.
3.
4.

## What are the running context details?

* Installation method (e.g. `pip`, `apt-get`, `git clone` or `zip`/`tar.gz`):
* Client OS (e.g. `Microsoft Windows 10`)
* Program version (`python sqlmap.py --version` or `sqlmap --version` depending on installation): 
* Target DBMS (e.g. `Microsoft SQL Server`): 
* Detected WAF/IDS/IPS protection (e.g. `ModSecurity` or `unknown`):
* SQLi techniques found by sqlmap (e.g. `error-based` and `boolean-based blind`):
* Results of manual target assessment (e.g. found that the payload `query=test' AND 4113 IN ((SELECT 'foobar'))-- qKLV` works):
* Relevant console output (if any):
* Exception traceback (if any):

**Comment by stamparm** [comment]
![dork](https://cloud.githubusercontent.com/assets/921555/22542257/3ebcff1c-e92b-11e6-9295-4ab786d6cc8e.png)
