### ISSUE TITLE
How to test an api having dynamic json keys(Key that require unique values every time)?

### ISSUE THREAD

**Issue by arthuragnar** [sqlmapproject/sqlmap#2377]
The attached file contains the request provided to SQLMAP.
[request.txt](https://github.com/sqlmapproject/sqlmap/files/747030/request.txt)

Command Used: sqlmap -r requests.txt 

As the above request has json that contain key named **person_no**(dynamic i.e it needs to change for every request). But as SQLMAP is taking person_no from request.txt which is static. So whenever SQLMAP is sending any request to the server, it is getting **500 error because of duplicate person_no**.
 Is there any way by which I can tell SQLMAP to take different value for person_no or any other dynamic json key? 
**How to test an api having dynamic json keys?**  
I have tested it manually and getting 500 error(due to duplicate values). I think because of this SQLMAP is not able to produce any error.

Result: 1652 times 500 internal error.
Is there any way I can see the actual payloads sent by SQLMAP ?

**Comment by stamparm** [comment]
Just pushed the rudimentary support for this kind of cases.

```
... --data='{"foo":1, "bar":2}' --eval "import random; bar=random.randint(1,100000)" --batch -v 6
```

![rand](https://cloud.githubusercontent.com/assets/921555/22647970/740f08da-ec74-11e6-858c-fed20d6b8ffc.png)

**Comment by arthuragnar** [comment]
Thanks for the enhancement.  
Is there any provision to provide whitelist i.e parameters I don't want to inject. If yes then how to do it ? If not then please add this enhancement.

**Comment by stamparm** [comment]
There is no such feature for JSON (though there is for `--skip` for others). Won't do the "enhancement" as you can always open your JSON request and just put the `*` mark to places where you want to do the testings.
