### ISSUE TITLE
API is missing target URL

### ISSUE THREAD

**Issue by nmalcolm** [sqlmapproject/sqlmap#2382]
## What's the problem (or question)?
The API, specifically the `/scan/{$taskid}/data` endpoint, returns the vulnerable parameter, but not the target URL. This is an issue when using a Google dork because you can't know which URL is vulnerable. 

Response: http://pastebin.com/raw/SW2BL90f

## Do you have an idea for a solution?
Return the URL along with the rest of the data.

## How can we reproduce the issue?
Simply launch the API with `python sqlmapapi.py -s`, start a new task with the `googleDork` parameter, wait for it to finish, and send a request to the `/scan/{$taskid}/data`. The target URL won't be included.

## What are the running context details?
Version `1.1.1.20#dev`.

**Comment by stamparm** [comment]
With latest revision:

![123](https://cloud.githubusercontent.com/assets/921555/22643144/94ac8976-ec5d-11e6-8cd7-7efd9d4d1899.png)
