### ISSUE TITLE
hi how can injection md5 paramater

### ISSUE THREAD

**Issue by MtucX** [sqlmapproject/sqlmap#2385]
hi how can i inject md5 paramater with sqlmap
example
ctf.com/index.php?id=1&pid=c4ca4238a0b923820dcc509a6f75849b

the vuln paramater is id
but you need to change the pid paramater like the id parm 
like this >>
ctf.com/index.php?id=1' union select 1,2--+-&pid=(in md5  >> 1' union select 1,2--+-)

**Comment by stamparm** [comment]
`...--eval="import hashlib; pid=hashlib.md5(id).hexdigest()"`
