### ISSUE TITLE
Oracle ROWNUM doesn't force column match

### ISSUE THREAD

**Issue by benlbroussard** [sqlmapproject/sqlmap#2387]
Feb, 6, 2017:
## What's the problem (or question)?
When running sqlmap against an Oracle database (Boolean blind AND-based), trying to pull back two columns (-C USER_NAME,PASSWORD), sqlmap returns valid data for each column but incorrectly matches the columns together. I believe the problem is that sqlmap is using ROWNUM to get specific rows, but it is doing separate queries for each column, so the row order returned from each query is different (there's no ORDER BY in these sqlmap queries).

## Do you have an idea for a solution?
An optional --order-by argument would have solved this issue for me because there was unique column that I could have ordered by. Alternatively, being able to return concatenated columns (ideally with a delimiter) instead of one at a time would force the columns to match up row-by-row and could improve multi-threaded efficiency by decreasing the number of times you get to the end of a column cell and have to wait for one of the threads to finish before starting on the next column (in fact, with row grouping this could be improved even more by just trying to get one long delimited string, and checking for the delimiter first might improve the end-of-column speed).

## How can we reproduce the issue?
I can't provide a good reproduction, because the ROWNUM behavior is based on default row ordering which is not guaranteed to be anything. Usually, it seems that rows are returned in insert order, but that wasn't the case for this database (optimization is crazy).

Base Query: sqlmap -u "https://example.com" --data "parm1=vulnerable" --dbms=Oracle -p parm1 -D EXAMPLE_DB -T TABLE1 -C USER_NAME,PASSWORD  --dump -v 3

Output snippet showing queries getting one column at a time and using ROWNUM for ordering:
PASSWORD:
[10:00:59] [PAYLOAD] vulnerable' AND ASCII(SUBSTRC((SELECT NVL(CAST(ENTRY_VALUE AS VARCHAR(4000)),CHR(32)) FROM (SELECT PASSWORD AS ENTRY_VALUE,ROWNUM AS LIMIT FROM EXAMPLE_DB.TABLE1) WHERE LIMIT=1),13,1))>112 AND 'YeVZ'='YeVZ

USER_NAME:
[10:01:32] [PAYLOAD] vulnerable' AND ASCII(SUBSTRC((SELECT NVL(CAST(ENTRY_VALUE AS VARCHAR(4000)),CHR(32)) FROM (SELECT USER_NAME AS ENTRY_VALUE,ROWNUM AS LIMIT FROM EXAMPLE_DB.TABLE1) WHERE LIMIT=1),10,1))>110 AND 'HHVr'='HHVr

## What are the running context details?

* Installation method (e.g. `pip`, `apt-get`, `git clone` or `zip`/`tar.gz`): Default Kali install
* Client OS (e.g. `Microsoft Windows 10`): unkown
* Program version (`python sqlmap.py --version` or `sqlmap --version` depending on installation): 1.0-stable
* Target DBMS (e.g. `Microsoft SQL Server`): Oracle Database 11g Release 11.2.0.2.0 - 64bit Production
* Detected WAF/IDS/IPS protection (e.g. `ModSecurity` or `unknown`): no waf
* SQLi techniques found by sqlmap (e.g. `error-based` and `boolean-based blind`): boolean-based blind
* Results of manual target assessment (e.g. found that the payload `query=test' AND 4113 IN ((SELECT 'foobar'))-- qKLV` works):
* Relevant console output (if any):
* Exception traceback (if any):

**Comment by stamparm** [comment]
The easiest solution seems to be to make "same (sub)query" for each column request and pray to the "SQL caching gods" :). So, in plainspeak, previously, subqueries have been different for each column enumeration (as you noticed), while now they are made the same. SQL caching gods should be merciful and just reuse that same subquery results for different column requests.

p.s. I couldn't reproduce your behavior, but could imagine what could go wrong. Also, query result "caching" is pretty solid mechanism to rely on
