### ISSUE TITLE
DB2 optimization ideas

### ISSUE THREAD

**Issue by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [sqlmapproject/sqlmap#2394]
## What's the problem (or question)?
DB2 sqli not optimized.

## Do you have an idea for a solution?
https://www.defcon.org/images/defcon-19/dc-19-presentations/Kornbrust/DEFCON-19-Kornbrust-Hacking-and-Securing-DB2.pdf

**Comment by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [comment]
http://www.sqlinjectionwiki.com/Categories/7/ibmdb2-sql-injection-cheat-sheet/

**Comment by stamparm** [comment]
Sorry, I don't see anything new here that is not already supported in sqlmap. As of those DoS attacks from Defcon presentation, they won't be part of sqlmap ever.
