### ISSUE TITLE
An ELF error occurred when I used udf\mysql\linux\64\lib_mysqludf_sys.so_ 

### ISSUE THREAD

**Issue by LeeHDsniper** [sqlmapproject/sqlmap#2399]
I copied lib_mysqludf_sys.so_  file into my mysql plugin directory,and:
`mysql> create function sys_eval returns string soname "lib_mysqludf_sys.so_";
`
But mysql throwed an error like this:
`ERROR 1126 (HY000): Can't open shared library 'lib_mysqludf_sys.so_' (errno: 0 /usr/lib/mysql/plugin/lib_mysqludf_sys.so_: invalid ELF header)`

Do I need compile this file by myself？If yes，can you tell me how to compile?
I have tried this at ubuntu 14.04.1 and centos6.

**Comment by stamparm** [comment]
`.so_` files are not `.so`. It is like mixing `.zip` with `.rar` and complaining why it doesn't work.

The solution can be seen at the attached screenshot:

![decloak](https://cloud.githubusercontent.com/assets/921555/23058638/49a6e0c4-f4f6-11e6-9c04-99e14ceb2c6b.png)
