### ISSUE TITLE
not authorized, try to provide right HTTP authentication type and valid credentials (401)

### ISSUE THREAD

**Issue by gudewolu** [sqlmapproject/sqlmap#2400]
hey
command:
 ./sqlmap.py --random-agent -u "http://xxx.aspx" --forms -p "xxx" --auth-type=Basic --auth-cred=xxx:xxx

i thought it was basic than i did v6

> `[13:35:35] [TRAFFIC OUT] HTTP request [#1]:
> GET /xxxxxx.aspx HTTP/1.1
> Host: xxxx
> Cache-control: no-cache
> Accept-encoding: gzip,deflate
> Accept: */*
> User-agent: Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_7; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/3.0.196 Safari/532.0
> Connection: close
> 
> [13:35:36] [TRAFFIC IN] HTTP response [#1] (401 Unauthorized):
> Content-length: 0
> X-powered-by: ASP.NET
> Microsoftsharepointteamservices: 14.0.0.4762
> Uri: http://xxxxx.aspx
> Sprequestguid: 7e7e77e2-07a7-4801-82e4-71c1c17ad2b4
> Server: Microsoft-IIS/7.5
> Connection: close
> Date: Fri, 17 Feb 2017 13:34:21 GMT
> Www-authenticate: NTLM`

so i changed it to NTLM still an error and got this

> ./sqlmap.py --random-agent -u "xxxx.aspx" --forms -p "xxxx" --auth-type=NTLM --auth-cred="xxxx\xxxx:xxxx4" -v6

> [13:48:23] [DEBUG] setting the HTTP authentication type and credentials
[13:48:23] [DEBUG] creating HTTP requests opener object
[13:48:23] [DEBUG] resolving hostname 'xxxxx'
[13:48:23] [INFO] testing connection to the target URL
[13:48:23] [TRAFFIC OUT] HTTP request [#1]:
GET /xxxx.aspx HTTP/1.1
Host: xxxx
Cache-control: no-cache
Accept-encoding: gzip,deflate
Accept: */*
User-agent: Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.1) Gecko/20090612 Firefox/3.5
Connection: close

[13:48:24] [TRAFFIC IN] HTTP response [#1] (401 Unauthorized):
Content-length: 0
X-powered-by: ASP.NET
Microsoftsharepointteamservices: 14.0.0.4762
Uri: http://xxxxx.aspx
Sprequestguid: xxxx
Server: Microsoft-IIS/7.5
Connection: close
Date: Fri, 17 Feb 2017 13:47:10 GMT
Www-authenticate: NTLM

[13:48:24] [INFO] searching for forms
[13:48:24] [TRAFFIC OUT] HTTP request [#2]:
GET /xxxx.aspx HTTP/1.1
Host: xxxxx
Cache-control: no-cache
Accept-encoding: gzip,deflate
Accept: */*
User-agent: Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.1) Gecko/20090612 Firefox/3.5
Connection: close

[13:48:24] [TRAFFIC IN] HTTP response [#2] (401 Unauthorized):
Content-length: 0
X-powered-by: ASP.NET
Microsoftsharepointteamservices: 14.0.0.4762
Uri: http://xxxx.aspx
Sprequestguid: xxx
Server: Microsoft-IIS/7.5
Connection: close
Date: Fri, 17 Feb 2017 13:47:10 GMT
Www-authenticate: NTLM

[13:48:24] [CRITICAL] can't parse forms as the page content appears to be blank

**Comment by stamparm** [comment]
`--forms` obviously doesn't work because of `401`.

Please make a traffic file (`-t traffic.txt`) and inspect the content in search of what is wrong. If you need help (after your inspection) please contact me to `miroslav@sqlmap.org`
