### ISSUE TITLE
how to inject mysqli via sqlmap

### ISSUE THREAD

**Issue by Ays4R-H4rB** [sqlmapproject/sqlmap#2402]
hello there , i found a SQL-injection in some site , and they used " MySQLi " how can i inject it via sqlmap ?
i mean if they use mysql , i just type --dbms "MySQL" , but now what ? i also try to type this option 
--dbms "MySQL" but no result .

**Comment by zarat** [comment]
Just type MySQL. MySQLi is just an extension as far as i know.

**Comment by Ekultek** [comment]
- Thomas Perkins

**Comment by stamparm** [comment]
Google for: `MySQLi "sql injection"`. MySQLi is generally a good protection against SQLi. If sqlmap doesn't work out of box (targeting MySQL), then it is most probably not injectable
