### ISSUE TITLE
Minor typo in wiki

### ISSUE THREAD

**Issue by tjgerot** [sqlmapproject/sqlmap#2407]
Should be **further** not **furter**.

![image](https://cloud.githubusercontent.com/assets/9205510/23151461/4b4da3fa-f7c0-11e6-98aa-f114e0ced6d1.png)

**Comment by tjgerot** [comment]
Another here:
![image](https://cloud.githubusercontent.com/assets/9205510/23152483/fb127e8a-f7c7-11e6-81e2-5281c21d8f78.png)

**Comment by stamparm** [comment]
Thank you for your report. With the latest commit (https://github.com/sqlmapproject/sqlmap/wiki/Usage/49292310d4593036a84ec7ef33135b6bbf89a6c4) it should be ok now.
