### ISSUE TITLE
hello , can i have some suggest decode password use sqlmap

### ISSUE THREAD

**Issue by vitural** [sqlmapproject/sqlmap#2408]
Hello

i have get some password , but its encode like that

### # eÝ>l;\x90\x9e(qNCDbf]_LÇa\x04\x0bTZZ
\x8aW\x8flëL\x03Z[esc]\x8e`R*\x87\\,LÇa\x04\x0bTZZ
a\x9c[ff]\x04RýÎ\x03,ÔJANetáLÇa\x04\x0bTZZ

can i use sqlmap to decode them ? and please let me know which statements i should use ?  thank you so much

**Comment by Ekultek** [comment]
That's not a hash, or base64. It almost looks like their encoded in a different encoding, I doubt you'll be able to use sqlmap to decrypt them, unless you can enforce the encoding to UTF-8 or something.

**Comment by vitural** [comment]
Thank for your reply  , Ekuted  
so can you give me some suggest with this one ? :

**Comment by Ekultek** [comment]
My advice to you, would be to decode the strings one by one and then try to decrypt them.

**Comment by Ekultek** [comment]
something like this should be sufficient:

```
# ~ coding=utf-8 ~ #
import chardet


unknown_string_list = [
    "eÝ>l;\x90\x9e(qNCDbf]_LÇa\x04\x0bTZZ",
    "\x8aW\x8flëL\x03Z[esc]\x8e`R*\x87\,LÇa\x04\x0bTZZ",
    "a\x9c[ff]\x04RýÎ\x03,ÔJANetáLÇa\x04\x0bTZZ"
]  # Unknown encoded strings


def find_encoding(string):
    """ Find the encoding of a string
    >>> find_encoding("test")
    ascii """
    encoding = chardet.detect(string)
    return encoding["encoding"]


if __name__ == '__main__':
    for s in unknown_string_list:
        print(find_encoding(s))

```

**Comment by vitural** [comment]
Thank you so much Ekultek  . 
you're help me so much ? i want paid for you , for this help 
sorry can i have your contact ,like :Skype , facebook ,icq.......?  
and  , im programmer , i have many skills , i want discusss more than that with you bro

**Comment by stamparm** [comment]
Use --binary-fields in this kind of situations. It will retrieve and display hashes in hexadecimal format

**Comment by vitural** [comment]
thank you alot stamparm  ,
i like your service so much , can i donate to your service ?   so can  i have your contact like : facebook, skype,icq , if possible bro ?
