### ISSUE TITLE
help to get started in the sqlmap

### ISSUE THREAD

**Issue by fritori** [sqlmapproject/sqlmap#2409]
hello, 
I finished my studies on SQL database, and  recently I discovered sqlmap on my kali. I'm interesed to go deeper and search more about this program, therefore, if someone has anything where I can read about sqlmap please send to me.

PS: I have already read the topic here, on GitHub, about this plataform, so please don't send the link of the page.

**Comment by stamparm** [comment]
1) You don't have to just read, you have to understand what is going on https://github.com/sqlmapproject/sqlmap/wiki/Usage. Reading without comprehension, like in your case when you have a need to ask this kind of questions, doesn't make any sense
2) Test options/switches on http://testphp.vulnweb.com/ and http://testasp.vulnweb.com/
3) Recommended https://www.slideshare.net/stamparm/f-sec-2011miroslavstamparitallstartswiththesinglequote-9311238, https://www.slideshare.net/stamparm/ph-days-2013miroslavstamparsqlmapunderthehood and https://www.slideshare.net/stamparm/f-sec-2013miroslavstamparheuristicmethodsusedinsqlmap
4) ...and last, but most important http://bfy.tw/9ynv

**Comment by fritori** [comment]
ok, thank you very much!
