### ISSUE TITLE
Incapsula WAF

### ISSUE THREAD

**Issue by fritori** [sqlmapproject/sqlmap#2414]
I scanned a MySQL database and I got a [WARNING] message saying that the URL might have a WAF, therefore I used wafw00f to know which WAF was: it's Incapsula. So I ask you gentlemen, is there a way I can bypass an Incapsula WAF with sqlmap or I need to use another tool?

**Comment by stamparm** [comment]
You can use something else

**Comment by fritori** [comment]
but can I se sqlmap, I mean it's possible with sqlmap? And if sqlmap doesn't work with this, which tool should I use?

**Comment by stamparm** [comment]
You've asked whether to use another tool, I've replied go for it. I was assure that you know what is the other tool. I am not aware of any tool that will automagically do that for you

**Comment by Ekultek** [comment]
I think what he's asking is if there is a script in sqlmap that will bypass the WAF for him?

**Comment by stamparm** [comment]
Out of box, no. Tamper scripts are just a help for advanced pen testers which know how to bypass the protection (e.g. WAF) in the first place. They are not meant to be used in automagic way. Without user's indepth knowledge of what is going on and why they are useless.

As said, user asked (I thought in authoritative way) whether he should "use another tool" and I replied yes.

**Comment by fritori** [comment]
alright, thanks you anyway. I've made a search and so far there isn't any tool that can bypass Incapsula WAF. I thought sqlmap could with the tamper scripts and I apolagise the question, I've asked it wrongly.
