### ISSUE TITLE
unbypassable BIG-IP Application Security Manager (F5 Networks)

### ISSUE THREAD

**Issue by gosupifiya** [sqlmapproject/sqlmap#2416]
hey,
there's a waf on the server called "BIG-IP Application Security Manager (F5 Networks)" , and no matter what i tried i always seems to fail to bypass it via sqlmap , in the other hand im 100% capable if injecting  the target via "netsparker"
my command

>  ./sqlmap.py --random-agent -u "zzzzz" --data="zzzz -p p_ads_year --method POST --dbs  --dbms=Oracle --tamper=between,randomcase,space2comment --flush-session --technique=BEUS

i keep getting this:

> `[16:22:08] [WARNING] turning off pre-connect mechanism because of connection time out(s)
> [16:22:08] [WARNING] there is a possibility that the target (or WAF/IPS/IDS) is dropping 'suspicious' requests
> [16:22:08] [CRITICAL] connection timed out to the target URL. sqlmap is going to retry the request(s)
> [16:22:08] [WARNING] most probably web server instance hasn't recovered yet from previous timed based payload. If the problem persists please wait for few minutes and rerun without flag 'T' in option '--technique' (e.g. '--flush-session --technique=BEUS') or try to lower the value of option '--time-sec' (e.g. '--time-sec=2')

`

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/FAQ#tool-xyz-works-against-the-target-while-sqlmap-doesnt
