### ISSUE TITLE
how to upgrade python on SqlMap

### ISSUE THREAD

**Issue by mantis-le-sin** [sqlmapproject/sqlmap#2423]
Hi guys,
I had an issue with a scan: "[CRITICAL] can't establish SSL connection"
After googling a bit I know I need to use a newer version of python on salmap.
Now I already installed on my kali python3 but Sqlmap is still using python< 2.7

Can you please help me out and tell me how I can upgrade the python version on Sqlmap?
Cheers,
mantis

**Comment by stamparm** [comment]
Basically, if Python < 2.7.9 is used, there is a high chance that SSL connection will broke (just go to https://docs.python.org/2/library/ssl.html and grep for 2.7.9 <- you'll see that lots of SSL features got implemented with that same version).

You can get any latest decent Linux distro (e.g. Ubuntu) and when you type `python` you'll get the latest Python 2. For example, on Ubuntu 16.04 latest available Python (2) version is `2.7.12`
