### ISSUE TITLE
How often does sqlmap hop proxies given as a file?

### ISSUE THREAD

**Issue by Ekultek** [sqlmapproject/sqlmap#2427]
## What's the problem (or question)?

How often does sqlmap hop proxies given as a proxy file list, also is there a way to set the amount of time to spend on each proxy for further anonymity? 

## Do you have an idea for a solution?

If there is no solution, make a flag for time spent on each proxy (in seconds)

## How can we reproduce the issue?

n/a

## What are the running context details?

* Installation method (e.g. `pip`, `apt-get`, `git clone` or `zip`/`tar.gz`): clone
* Client OS (e.g. `Microsoft Windows 10`) windows 7
* Program version (`python sqlmap.py --version` or `sqlmap --version` depending on installation): 1.1.3.2
* Target DBMS (e.g. `Microsoft SQL Server`): n/a
* Detected WAF/IDS/IPS protection (e.g. `ModSecurity` or `unknown`): n/a
* SQLi techniques found by sqlmap (e.g. `error-based` and `boolean-based blind`): n/a
* Results of manual target assessment (e.g. found that the payload `query=test' AND 4113 IN ((SELECT 'foobar'))-- qKLV` works): n/a
* Relevant console output (if any): just connecting to the first proxy:
```
        ___
       __H__
 ___ ___[,]_____ ___ ___  {1.1.3.2#dev}
|_ -| . [.]     | .'| . |
|___|_  [.]_|_|_|__,|  _|
      |_|V          |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user'
s responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting at 19:32:35

[19:32:35] [INFO] loading proxy 'http://97.**.1**.***:8*' from a supplied proxy list file
[19:32:35] [INFO] testing connection to the target URL
```

* Exception traceback (if any): n/a

**Comment by stamparm** [comment]
Idea of proxy list is to skip the proxy in case of any problems with the current one. There are gazillion potential problems with using different proxy with each request. I can guess that you would at least raise 5 new issues. First is the different latencies between proxies, hence, time-based SQLi would "suffer". Second is that different proxy potentially introduces/filters different content. Some proxies even tend to misbehave and just not return the originally requested data.

In case that you want to randomize "hopping" please use `proxychains`

**Comment by Ekultek** [comment]
Cool thank you 

- Thomas Perkins

**Comment by stamparm** [comment]
@mr-m0nst3r:

A) after a connection problem with first proxy from a list (provided with `--proxy-file`), sqlmap jumps to the second, then afterwards to third...

B) it is being set inside `_setHTTPHandlers()` ([code](https://github.com/sqlmapproject/sqlmap/blob/master/lib/core/option.py#L949-L958)) at the start of sqlmap OR after any kind of connection problems ([code](https://github.com/sqlmapproject/sqlmap/blob/master/lib/request/connect.py#L148))

C) I am not really sure what are you trying to do, so best of luck with modifications

**Comment by mr-m0nst3r** [comment]
@stamparm 
Thank you, mate. I think `_setHTTPHandlers()` is what I should do some coding with.

Actually, what I need to do is, I wish to provide a url, which is an API, to sqlmap commandline, when sqlmap decides to switch to another proxy, it should make a request to the API, resolve the returned data, and get the IP and PORT inside.

It would be a great help if you've got time for some reviewing. I'm not good at programming. 😂

**Comment by mr-m0nst3r** [comment]
@stamparm 
Hi there, I did some coding.
haven't checked.

There're three changed to the `options.py`.
Should work, I think.

![image](https://user-images.githubusercontent.com/38524240/46239972-04274b80-c3d3-11e8-8c9e-390878da0c90.png)
![image](https://user-images.githubusercontent.com/38524240/46239980-1d2ffc80-c3d3-11e8-9804-2d673b24970c.png)

**Comment by stamparm** [comment]
ok. looks fine at first glance
