### ISSUE TITLE
Results CSV file shows all tested targets, not just positives ?

### ISSUE THREAD

**Issue by BabyBit** [sqlmapproject/sqlmap#2428]
```
sqlmap --version
1.1#stable"

```
I am running this command:

`sqlmap --random-agent --dbms=MySQL --batch --beep --crawl=2 --forms --timeout=5 --retries=1 --threads=4 -m "/home/user/my_sites.txt" --dbs `

And after it is done testing, I look at the .csv file and the result contains many URLs, even more from same site, and many of them only have url but the other columns are empty: Place, Parameter, Technique(s),Note(s)
Next to them I also see the positives, where some show the param and technique.

Is this a feature / update or a bug ? I if is normal, is there a way to switch back and only write positives to file ?

**Comment by stamparm** [comment]
Pure `grep` would do this. Other users requested that they wanted to know if specific targets haven't resulted in positives. If you want to get only the "positives":

```
$ cat ~/.sqlmap/output/results-03062017_1153am.csv | grep -v ",,,,"
Target URL,Place,Parameter,Technique(s),Note(s)
http://testphp.vulnweb.com/artists.php?artist=1,GET,artist,BU,
```
