### ISSUE TITLE
sqlmap: error: missing a mandatory option

### ISSUE THREAD

**Issue by tijnar33** [sqlmapproject/sqlmap#2429]
I am having this issue.. 
I tried my all effort but unable to solve this problem. How can I solve this issue ? 
It is saying ..
sqlmap: error: missing a mandatory option (-d, -u, -l, -m, -r, -g, -c, -x, --wizard, --update, --purge-output or --dependencies), use -h for basic or -hh for advanced help

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/Usage#target
