### ISSUE TITLE
GET param injection [y/n] not parsed properly

### ISSUE THREAD

**Issue by m47r14rch** [sqlmapproject/sqlmap#2430]
## What's the problem (or question)?
When running from the command line, if prompted with the option of injecting into GET parameters
```
it appears that provided value for GET parameter 'parametername' has boundaries. 
Do you want to inject inside? ('{someparametervalue*}') [y/N]
```
Typing `y` or `n` returns `bash: y: command not found` or `bash: n: command not found`, respectively.

It then stops any remaining processes, instead of taking `y` or `n` as input and continuing with the process as seen when running `sqlmap --wizard`

```
[11:53:12] [INFO] starting wizard interface
Please enter full target URL (-u): https://someurl/somepath?parametername=someparametervalue*moretothevalue
POST data (--data) [Enter for None]: 
Injection difficulty (--level/--risk). Please choose:
[1] Normal (default)
[2] Medium
[3] Hard
> 3
Enumeration (--banner/--current-user/etc). Please choose:
[1] Basic (default)
[2] Intermediate
[3] All
> 2

sqlmap is running, please wait..

it appears that provided value for GET parameter 'parametername' has boundaries. Do you want to inject inside? ('{someparametervalue*}') [y/N] N
```

## Do you have an idea for a solution?
User input (y/n/return) from the command should be passed back into sqlmap.

## How can we reproduce the issue?
1. Setup `sqlmap` with some url that includes a potentially injectable parameter and any other parameters, in my case this included: `-p` `--cookie` `--level` `--current-user` `--current-db`, however these are not required
2. When prompted with:
```
it appears that provided value for GET parameter 'parametername' has boundaries. Do you want to inject inside? ('{someparametervalue*}') [y/N]
```
Type `y`, `n`, or some valid bash command such as `ls`
3. `y` or `n` should return `bash: y: command not found` or `bash: n: command not found`, respectively. `ls` should return a listing of the current directory.

**Example:**
![sqlmap](https://cloud.githubusercontent.com/assets/26315084/23777982/11cdb672-058c-11e7-961f-0c6bb741b945.png)

## What are the running context details?
Kali OS version 
```
root@starshipheartofgold:~# cat /etc/*-release
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2016.2"
VERSION_ID="2016.2"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.kali.org/"
SUPPORT_URL="http://forums.kali.org/"
BUG_REPORT_URL="http://bugs.kali.org/"
```
SQLmap version:
```
root@starshipheartofgold:~# sqlmap --version
1.1.2#stable
```

**Comment by stamparm** [comment]
You have run a command with one option having & inside, while not enclosing that same parameter with quotes (e.g.... you should do this  -u "...&id=1")
