### ISSUE TITLE
Problem to retrieve tables data 

### ISSUE THREAD

**Issue by nitescence69** [sqlmapproject/sqlmap#2433]
Hello, sorry for my bad and poor English.

I have a problem to retrieve data on tables.
The website have a WAF ( modsec OWASP CRS)
Sqlmap found GET parameter '...' appears to be 'AND boolean-based blind - WHERE or HAVING clause' injectable (with --string="du").
Sqlmap found 2 database name : [INFO] the back-end DBMS is MySQL
web application technology: Apache, PHP 5.6.19
back-end DBMS: MySQL 5
[06:11:11] [INFO] fetching database names
[06:11:11] [INFO] fetching number of databases
[06:11:11] [INFO] resumed: 2
[06:11:11] [INFO] resumed: information_schema
[06:11:11] [INFO] resumed: j.....site.com

But when i try to retrieve data of tables database i have these errors : 
[WARNING] unexpected HTTP code '403' detected. Will use (extra) validation step in similar cases
[06:11:12] [INFO] retrieved:   
[06:11:12] [WARNING] unable to retrieve the number of tables for database

I want to understand the problem.
:)

If i'm not clear i can send a picture
Thanks for your comprehensly.
:)

Edit : I used tamper script " space2morehash " 
i tried a many other tamper, but it's the only tamper who read the database name.

**Comment by stamparm** [comment]
1) For bypassing the WAF take a look at: https://github.com/sqlmapproject/sqlmap/wiki/FAQ#which-tamper-script-to-use-to-bypass-a-wafidsips-protection
2) To understand what is going on you should run with `-v 3`. That way you could use what is triggering the WAF. As sqlmap has a fall back for database names in query `SELECT db FROM mysql.db` which is not regularly blacklisted, while for retrieval of table names `INFORMATION_SCHEMA` has to be used, I can make an educated guess and say that WAF in your case drops all payloads with `INFORMATION_SCHEMA` inside. This is fairly common scenario

**Comment by nitescence69** [comment]
Thx Bro ;-)

2017-03-12 9:25 GMT+01:00 Miroslav Stampar <notifications@github.com>:
