### ISSUE TITLE
Error , too slow retrieve anything from database after passing into it

### ISSUE THREAD

**Issue by Geeky00** [sqlmapproject/sqlmap#2434]
im using this command to try 
it took lots of time 
![sqlmap](https://cloud.githubusercontent.com/assets/10381128/23830464/0d77296c-0714-11e7-9f46-f0e15487073d.png)

python sqlmap.py -r b.txt --tamper="between,randomcase,space2comment" --random-agent --no-cast --time-sec=10 -D <databasename> -T <tablename> --columns --threads=10

it keeps give me this 
`[02:06:17] [WARNING] reflective value(s) found and filtering outr statistical model, please wait
.............................. (done)
[02:06:29] [WARNING] it is very important to not stress the network connection during usage of time-based payloads to prevent potential disruptions
30
[02:07:24] [WARNING] (case) time-based comparison requires larger statistical model, please wait`

anyone have any idea how to pass it

**Comment by stamparm** [comment]
You have a problem with the WAF, not the sqlmap. It is natural that WAF is either DROPing your requests or making your life miserable. My best answer for this kind of cases is described here: https://github.com/sqlmapproject/sqlmap/wiki/FAQ#which-tamper-script-to-use-to-bypass-a-wafidsips-protection
