### ISSUE TITLE
What does “Resend original POST data to a new location”?

### ISSUE THREAD

**Issue by virtueless** [sqlmapproject/sqlmap#2435]
Hello,

Can anyone explain what does the following question after a redirect mean?

**redirect is a result of a POST request. Do you want to resend original POST data to a new location?**

If this is an incorrect support issue, can you please remove it and reply to my StackOverflow question instead?

http://stackoverflow.com/questions/42742265/what-does-resend-original-post-data-to-a-new-location-mean-in-sqlmap

Thank you.

**Comment by Ekultek** [comment]
POST data is posting something to a site GET data is getting something from a site. So if you have a request to follow the POST content then you'll be sending data to the website if you follow it. So in your case, sending the data to a different location, such as from http://google.com#?=10 to http://google.com#?=17. Your sending the data to a different parameter (redirect)

Btw don't ask questions like that on stackoverflow, that question has nothing to do with programming.

**Comment by stamparm** [comment]
@virtueless you are doing a POST request which results with a redirect to a different location. sqlmap just asks whether you want to resend the POST data (e.g. `id=11&foo=bar`) to the location where you are being redirected.
