### ISSUE TITLE
Find link admin page , user Sqlmap

### ISSUE THREAD

**Issue by vitural** [sqlmapproject/sqlmap#2436]
Hello
can i have some suggest to find link admin login from sqlmap ? 
thank for your reply so much :)

**Comment by stamparm** [comment]
There is no such functionality from within sqlmap. You should use some
other tool for this (dirbuster or similar)

**Comment by vitural** [comment]
Thank for your reply Stamparm :)

**Comment by minado22** [comment]
hii can i have the anwser too ?
