### ISSUE TITLE
walk die loop

### ISSUE THREAD

**Issue by wilson9x1** [sqlmapproject/sqlmap#2440]
https://github.com/sqlmapproject/sqlmap/blob/master/lib/core/common.py

![beb4ebee-f304-4b11-a7b0-1aade61b9aa4](https://cloud.githubusercontent.com/assets/9835472/23954158/7e8a1802-09d1-11e7-9c63-a3f7d77b5316.png)

dict like:'{"id":"xxxxx","itemIds":[]}' 
then,go to a die loop。

so,do like this:
if isinstance(value, (list, tuple, set, dict)):
    if len(value):
        walk(head, value)

**Comment by stamparm** [comment]
Thx :)

**Comment by wilson9x1** [comment]
dict like {u'times': [1, 0, 1], u'objectId': u'xxx', u'objectType': u'xxxxx'}
then,go to a die loop,too...........


change:
current = current or head

to:
if current is None:
      current = head

sad.....this func not surport put payload list，such as:{u'times': ["paylaod", 0, 1], u'objectId': u'xxx', u'objectType': u'xxxxx'}
