### ISSUE TITLE
Page Comparison needs Wiki update

### ISSUE THREAD

**Issue by 0x6368** [sqlmapproject/sqlmap#2442]
@stamparm, I think the wiki about [page comparison](https://github.com/sqlmapproject/sqlmap/wiki/Usage#page-comparison) is outdated. It says, that it compares the injected page with a non-injected one. But as I have seen in the code, sqlmap creates two payloads (for example `Book') AND 5729=1695 AND ('UhBA'='UhBA` and `Book') AND 1026=1026 AND ('UhBA'='UhBA`), from which one should return the true page and the other one should return the false page. Only if they are different, the parameter is considered injectable.

**Comment by stamparm** [comment]
I am copy pasting what it says:

```
By default the distinction of a True query from a False one (rough concept behind boolean-based blind SQL injection vulnerabilities) is done by comparing the injected requests page content with the original
```

It means this. True injected page is compared with original page (to get something called `ratio`), then False injected page is compared to original page (to also get the `ratio`) and then those two ratios are compared together. It compares those two ratios and they should be clearly distinct. So, technically, nothing is "outdated".
