### ISSUE TITLE
Problem retrieving data from a table named #__table

### ISSUE THREAD

**Issue by neofito** [sqlmapproject/sqlmap#2452]
## What's the problem (or question)?
I've found a sqli on a url and sqlmap is not able to retrieve the content of tables starting with #__

## Do you have an idea for a solution?
I think that sqlmap is crashing internally but catching the exception because using a proxy I'm not seeing any request exiting from my desktop.

## How can we reproduce the issue?

```
python sqlmap.py --threads 10 --force-ssl --dbms mysql --technique E -r request -D database -T #__table --columns
```
The request file content:
```
POST /url/vulnerable* HTTP/1.1
Host: www.host.com
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,es-ES;q=0.8,es;q=0.5,en;q=0.3
Cookie: cookie=cookie
Connection: close
Upgrade-Insecure-Requests: 1
Content-Type: application/x-www-form-urlencoded
Content-Length: 90

field1=content1&field2=content2
```

## What are the running context details?

I'm using the latest version from github and I'm getting a generic error:
```
[WARNING] unable to retrieve column names for table '#__table' in database 'database'
```

**Comment by neofito** [comment]
The problem has gone!

sqlmap is working like a charm. The real problem is that # is an special character in MySQL. The solution: '**Quote your ambiguous or "special" table names with a back tick**'

http://stackoverflow.com/questions/10443050/special-characters-in-mysql-table-name

I apologize for the inconvenience

**Comment by dcianciulli** [comment]
It seems that using back ticks is a solution only if you make your own query from the sql-shell. However, the problem is still present when using the -T parameter with a table like "#__tablename", even with -T '`#__tablename`'. How can I resolve?

**Comment by stamparm** [comment]
@dcianciulli can't reproduce. Now tried with both ``-T `#__tablename`'`` and `-T '#__tablename'` and I am seeing proper usage of `WHERE table_name='#__tablename'` and ``FROM database.`#__tablename` `` inside payloads
