### ISSUE TITLE
use -p[or * mark] and --eval at the same time，XML parameters doesn't work。

### ISSUE THREAD

**Issue by 4bug** [sqlmapproject/sqlmap#2455]
## use -p[or * mark] and --eval at the same time，XML parameters doesn't work
I'm glad [this problem](https://github.com/sqlmapproject/sqlmap/issues/1679)is solved these days.

My request looks like:
`<message type="login"><condition req="login" Type="loginCheck" 
user="admin" password="123456" csrf_token="abcd"/></message>`
The user parameter  is injection point，csrf_token must update every time.
so，I use --eval  parameters and python deal with csrf_token.

if i use -p user  and --eval parameters，it will return fllow:
`SOAP/XML data found in POST data. Do you want to process it? [Y/n/q] y
all testable parameters you provided are not present within the given request data`

if i mark user parameter with *:
`<message type="login"><condition req="login" Type="loginCheck" 
user="admin*" password="123456" csrf_token="abcd"/></message>`
It will just ruturn 
`custom injection marking character ('*') found in option '--data'. Do you want t
o process it? [Y/n/q] y`
**Do't ask "SOAP/XML data found in POST data. Do you want to process it?"!**
The actual POST data:
`<message type="login"><condition req="login" Type="loginCheck" 
user="admin[pyaload]" password="123456" csrf_token="abcd"/></message>&csrf_token=dabc`
XML parameters doesn't work! like [issues 1769](https://github.com/sqlmapproject/sqlmap/issues/1679)

if i do't use -p parameter,sqlmap can't find post parameter and can't find SQL injection。

**Comment by stamparm** [comment]
Why so many ! ??

**Comment by 4bug** [comment]
@stamparm Can you understand what I say？

**Comment by stamparm** [comment]
Nope, I am stupid. Closing this down as invalid

**Comment by stamparm** [comment]
@4bug you can't write Issue requests with exclamation marks. If you want me to help you you can't be a pissed user. In that case you are provoking myself to be a bastard administrator and to just ignore all your future requests.

**Comment by 4bug** [comment]
@stamparm I'm sorry,My english is poor,I wasn't unaware of  this is rude.
Please forgive me for being impolite.

**Comment by 4bug** [comment]
@stamparm hello! 
I want delete "&" in
`<message type="login"><condition req="login" Type="loginCheck" user="admin[pyaload]" password="123456" csrf_token="abcd"/></message>&csrf_token=dabc`
let it become 
`<message type="login"><condition req="login" Type="loginCheck" user="admin[pyaload]" password="123456" csrf_token="abcd"/></message>csrf_token=dabc`
I change sqlmap/master/lib/request/connect.py line 1090
`post += "%s%s=%s" % (delimiter, name, value)`
let it become
`post += "%s=%s" % (name, value)`
but,find it don't work.
I change sqlmap/lib/core/settings.py  line 537
change
`DEFAULT_GET_POST_DELIMITER = '&'`
to 
`DEFAULT_GET_POST_DELIMITER = ''`
it's also.
Can you help me? Thanks!
