### ISSUE TITLE
Suggestion to make sqlmap slighty "interational" when executed with bulkfile (-m).

### ISSUE THREAD

**Issue by fredhagedorn** [sqlmapproject/sqlmap#2456]
## What's the problem (or question)?

Its a problem and a situation and a question: Users, when do the python sqlmap.py -m BULKFILE.txt cannot change any of initial parameters -- when different sites have different ways to pentest.
Its hard to explain, but I know BASED Stam will get what I mean. I'll try to exemplify:

python sqlmap.py -m 700_websites_to_test.txt --random-agent --threads=10 --flush-session --text-only --no-escape --schema --exclude-sysdbs --technique=BEUS

Well, lets imagine we have, at 74th URL:

_`[CRITICAL] WAF/IPS/IDS identified as 'Varnish'`_

And at 126th URL:

_`[CRITICAL] WAF/IPS/IDS identified as 'ModSecurity'`_

## Do you have an idea for a solution?

When sqlmap faces with any critical message detecting any WAF/IPS/IDS, shows an option to user add a new parameter. Using "Varnish"/"ModSecurity IDS as examples again, instead of giving the **sad** message:

_`are you sure that you want to continue with further target testing? [y/N] `_

Sqlmap should show something like:

## **` do you want to add a tamper script and retest this website? [Y/n] `**

And then, when user selects "Y" option,

## **`Insert filename of the tamper you want to use:`**

(In such case, sqlmap would use only tampers located in /tamper/ directory).

It would be PERFECT, dear Miroslav.

Can we have such implementation m8? **Many - many - thanks in advance to you and sqlmap community.**

**Comment by stamparm** [comment]
Thank you for your praises.

As of your problems/proposal with/for `-m`. Tampering is maybe not the best example here because of its complexity. Usage of tampering scripts require a through familiarity with the target, while this is not possible in such mode as `-m` (i.e. bulk scanning). Blind usage of tampering scripts will most probably not produce any results

**Comment by fredhagedorn** [comment]
Yeah, but sqlmap have its patterns to detect many of WAF/IDS/IPS. Therefore, with my proposal to enhance `sqlmap -m `command -- as I said in original post --, we wouldnt have a blind usage of tamper scripts at all.

**Comment by stamparm** [comment]
Ok. Now, for example you get `CloudFlare Web Application Firewall (CloudFlare)` or `Anquanbao Web Application Firewall (Anquanbao)`. What's the expected user<->sqlmap workflow? I mean, what do you expect from sqlmap in such case(s) and what from the user(s)?

p.s. I'll just leave this link here: https://github.com/sqlmapproject/sqlmap/wiki/FAQ#which-tamper-script-to-use-to-bypass-a-wafidsips-protection

**Comment by fredhagedorn** [comment]
I read entire FAQ. No "RTFM" for me m8 hahaha.
Well, in such cases sqlmap could not do anything, except something like:

```
[WARNING] CloudFlare Web Application Firewall (CloudFlare) Detected.
[WARNING] Use of tampering scripts in CloudFlare Web Application Firewall (CloudFlare) may be not useful. Do you want to insert a tamper script [y/N]? 
```

Since `N` would be default, in a bulk pentesting, the user just need to press Enter or `--"answers=may be not useful=N"` combined with `--batch`. Easy as being sqlmap fanboy (like me).

The question is, Stam, varnish, modsecurity and 99,9% of "Generic" WAFs are "bypassable" with one (or 2 or 3) tamper we have at /tamper/ directory. If you implement a way to user select one of tamper scripts in bulkfile -- as I said in Original Post --, sqlmap would become 20% more nice (totalizing 120% of niceness).

**Comment by stamparm** [comment]
@fredhagedorn don't get me wrong, but I am not convinced here. Incorporating new question in bulk file scanning, especially with tampering scripts, would introduce new level of "confusion". As said, tamper scripts should be used per target basis. Usage of tamper scripts in bulk file scanning, from my point of view, wouldn't introduce anything new and useful that is not already available in standard approach

**Comment by fredhagedorn** [comment]
:( sob
But I got your point -- and I understand it clearly.
Thanks for being (not only) the creator of sqlmap, but also a nice person.

Greetings from Brazil.
