### ISSUE TITLE
guide

### ISSUE THREAD

**Issue by miladkheirkhah** [sqlmapproject/sqlmap#2458]
Hi,
I want to start project like sqlmap please help me , how to start to write a tool like sqlmap??

**Comment by machak10** [comment]
You are joking,right?

2017-04-02 22:46 GMT+02:00 miladkheirkhah <notifications@github.com>:

**Comment by stamparm** [comment]
@miladkheirkhah read and write lots of code. There is no guide for this. If you are asking for a guide you are doing it wrong.
