### ISSUE TITLE
SQLmap url (character) injection !!!

### ISSUE THREAD

**Issue by andreas1900** [sqlmapproject/sqlmap#2465]
Ok, so here is the problem.
I got url like https://www.site.com/someparametar#bla/search=0&bla='6.4.2017'
So sqlmap cant recognize url because it has strange chars like # and '

"[WARNING] you've provided target URL without any GET parameters (e.g. 'http://www.site.com/article.php?id=1') and without providing any POST parameters through option '--data'"

Any sugestions ?

**Comment by stamparm** [comment]
Everything after a '#' is not considered as part of URL. You should sniff traffic with (e.g.) Burp and see what is really being sent to the server.
