### ISSUE TITLE
Code integrity check failed

### ISSUE THREAD

**Issue by jhhd88** [sqlmapproject/sqlmap#2467]
![image 2](https://cloud.githubusercontent.com/assets/15847202/24866771/bd4235b8-1e3d-11e7-9171-9fb13d42f25f.jpg)

**Comment by stamparm** [comment]
@jhhd88 something caused the exception, while the "automatic" creation of issue has been turned off. I've pushed one modification this moment which could solve the "wrong checksum" problem. I would be grateful If you could retrieve the latest revision and retry.

**Comment by stamparm** [comment]
If you are still getting the "wrong checksum error" please copy-paste the exact command you are trying to run (e.g. `sqlmap.py ...`), content of `1.txt` (you can mask the `Host:`) and the info how you've retrieved the sqlmap version that you are trying to run.

or

you could ZIP everything (sqlmap directory and 1.txt) and send it to `miroslav@sqlmap.org`

**Comment by jhhd88** [comment]
sqlmap.py -r 1.txt --dbs

`POST /login.do?dispatch=login HTTP/1.1
Host: *.*.*.*
Connection: keep-alive
Content-Length: 70
Cache-Control: max-age=0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Origin: http://*.*.*.*
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
Content-Type: application/x-www-form-urlencoded
DNT: 1
Referer: http://*.*.*.*/login.jsp
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.8
Cookie: JSESSIONID=DB441BFECD9D3CC2799898094E2EAC5D

username=admin&password=111111&submin.x=24&submin.y=9&isLoginGui=false`

**Comment by jhhd88** [comment]
![image 4](https://cloud.githubusercontent.com/assets/15847202/24870504/134b83aa-1e49-11e7-8014-caea4f737775.jpg)

**Comment by stamparm** [comment]
Last image doesn't prove anything than that you've changed something in provided parameters. With original parameters (from original post) sqlmap should generate Unhandled exception (causing the checksum check in the first place)

**Comment by jhhd88** [comment]
I would like to say is that version 11 no problem, can run normally, version 12 will appear to enter any -- parameters, will be an error.

**Comment by jhhd88** [comment]
![image 1](https://cloud.githubusercontent.com/assets/15847202/24871092/1476ceae-1e4b-11e7-99ce-e44219edcb31.jpg)

**Comment by stamparm** [comment]
Ok. Going to check in half an hour when I get home

**Comment by stamparm** [comment]
Please retry with the latest revision. Major issue #2471 fixed this moment

**Comment by stamparm** [comment]
p.s. how are you retrieving sqlmap versions? .zip or ...?

**Comment by jhhd88** [comment]
fixed,thx
