### ISSUE TITLE
How long to wait for new output/log line ?

### ISSUE THREAD

**Issue by BabyBit** [sqlmapproject/sqlmap#2474]
Sometimes sqlmap seems to be blocked because it prints no output for ~5 hours ...

> [06:40:28] [INFO] testing 'MySQL inline queries'
[06:40:23] [INFO] testing 'MySQL >= 5.0.12 AND time-based blind'
[06:40:22] [INFO] testing 'Generic UNION query (NULL) - 1 to 10 columns'
[07:34:41] [WARNING] reflective value(s) found and filtering out

// at `12:00` same output, no new line, network indicator shows some constant traffic ~10KB/s

I don't know if I should leave it or wait more ?

Maybe as a feature request it would be nice to show some kind of progress every 30 minutes (some unique current command/task that indicates it is not blocked). For me I would also find date useful (next to time) because sometimes it runs for a few days.

**Comment by stamparm** [comment]
If it runs for few days -> blocked
If it runs for few hours -> blocked
...

Lets say that all your requests are DROPed (no RST coming back). If you run with (e.g.) `--level 5 --risk 3` over number of parameters you'll need to wait for over 10k requests with 3 retries for each request with 30 second timeout. That's lots of time to wait.

Now, if it is not enough that sqlmap says with big red letters that you have lots of timeouts then no other "nice feature" will help

**Comment by stamparm** [comment]
p.s. If you don't get big red ugly "timeouts" and sqlmap just waits at that `[07:34:41] [WARNING] reflective value(s) found and filtering out` then something is wrong. In that case please send me url to `miroslav@sqlmap.org`
