### ISSUE TITLE
--wizard problem

### ISSUE THREAD

**Issue by Kuhitacop** [sqlmapproject/sqlmap#2477]
Hello, I think I found a bug:
When I'm running a --wizard I get the following error:

**sqlmap is running, please wait..

[18:21:53] [CRITICAL] heuristics detected that the target is protected by some kind of WAF/IPS/IDS
do you want sqlmap to try to detect backend WAF/IPS/IDS? [y/N] N**

And it get stuck there.
When detects a protection it  writes by default N but it doesn't continue, I try to enter and write N and enter and doesn't work.

**Comment by stamparm** [comment]
Your further requests are most probably DROPed. `TCP DROP` is an enemy of scanners. It makes them wait for long time (timeouting + retrying) before they fail. That is not a bug, just target playing with you
