### ISSUE TITLE
Delete load files

### ISSUE THREAD

**Issue by AVR1234** [sqlmapproject/sqlmap#2482]
Hello, just want to ask if i loaded some files how now am i deleting with file from folder? Could you write example parametr sqlmap.

And other questions if current user is DBA:  Fasle but by uniscan finding folder which rules read/write. Can i change rules user to True?

**Comment by stamparm** [comment]
* For doing that, you should be able to run the `--os-shell` and inside of it find and delete those files.
* As of DBA: False. Being a DBMS admin is not a prerequisite for reading/writing to filesystem, though, in majority of cases that's the case. Also, `uniscan` is not a reliable scanner as any of similar scanners

**Comment by AVR1234** [comment]
Tanks a lot for help!
