### ISSUE TITLE
SQLMAP OUTPUT DIRECTOR

### ISSUE THREAD

**Issue by AmericanY** [sqlmapproject/sqlmap#2484]
Hi There,

how can i change the output directory of sqlmap which is /root/.sqlmap/output/ to another location which is /root/var/www/html/output/

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/Usage#custom-output-directory-path

**Comment by AmericanY** [comment]
using Option: --output-dir it's gonna be for current session only and i will need to type it each time using sqlmap. i need to configure it to print the output on my specific location without define it each time.

**Comment by AmericanY** [comment]
any updates.

**Comment by stamparm** [comment]
Just for the record, nowhere in the original Issue request there is a mention of persistent change of that same option.

To do that, set environment variable `SQLMAP_OUTPUTDIR`.

![output](https://cloud.githubusercontent.com/assets/921555/25102766/28492f70-23ba-11e7-846b-b6c0e263f3f8.png)
