### ISSUE TITLE
Find tables and columns names with a specific .TXT file

### ISSUE THREAD

**Issue by iwantaturboman** [sqlmapproject/sqlmap#2485]
## Specify a specific .txt file to search tables or colums ?
* As i think it's not necessary to edit natives sqlmap text files ; i would like to know if a command like that could be implemented : 
`sqlmap.py -u "http://www.target.com/index.php?id=1*" -D database --specific-tables mydictionary.txt `
_(of course, mydictionary.txt would be in txt/ slqmap folder)_

Thanks.

**Comment by stamparm** [comment]
Done with latest revision (for both tables and columns):

![screen](https://cloud.githubusercontent.com/assets/921555/25178969/38a83240-2508-11e7-9805-5f9a1a99b658.png)

**Comment by iwantaturboman** [comment]
Great. Thanks so much @stamparm !
