### ISSUE TITLE
How to Ignore prompts asking confirmation (Y/N), eg. "Target URL is not Stable" ?

### ISSUE THREAD

**Issue by CobraL0rd** [sqlmapproject/sqlmap#2486]
I'm running a batch file with many urls. I've read in this question: https://github.com/sqlmapproject/sqlmap/issues/1603 to use `--text-only` which isn't clear to me what it does. Is there such an option? Thanks.

**Comment by klensy** [comment]
```--batch``` will ignore all [prompts](https://github.com/sqlmapproject/sqlmap/wiki/Usage#act-in-non-interactive-mode).

**Comment by CobraL0rd** [comment]
Thanks!
