### ISSUE TITLE
Bug found while using TOR

### ISSUE THREAD

**Issue by hack4net** [sqlmapproject/sqlmap#2502]
sqlmap version: 1.1.4.34#dev
Python version: 2.7.13
Operating system: posix
Command line: /usr/bin/sqlmap --tor --tor-type=SOCKS5 -u ***************************************** --forms --random-agent --tamper=charencode --no-cast --threads=10 --dbs
Technique: None
Back-end DBMS: None
Traceback (most recent call last):
  File "sqlmap", line 150, in main
    start()
  File "share/sqlmap/lib/controller/controller.py", line 356, in start
    elif test[0] in ("n", "N"):
UnboundLocalError: local variable 'test' referenced before assignment

**Comment by stamparm** [comment]
Duplicate of #2489 (fixed)
