### ISSUE TITLE
Pause on general internet connection fail ? e.g fail to ping 8.8.8.8

### ISSUE THREAD

**Issue by BabyBit** [sqlmapproject/sqlmap#2505]
When testing many targets in bulk, in case of internet connection failure, it might skip targets one after another until it reaches end, and it is a bit hard to resume from correct location/progress. 

It would be nice if it can ping 8.8.8.8 before each command (or major command) and in case of failure it would pause and resume again when ping reply is received. 

Maybe there is an existent switch / command that can achieve this ?

```
~OR --pause-if-output="ping 8.8.8.8=timeout_or_something" --resume-if-output="ping 8.8.8.8=ms"

~OR --test-internet="8.8.8.8" --test-internet-interval=5 
```
I like the second one :)

For me personally it would make a huge difference, I hope for others too. 
Thank you.

**Comment by stamparm** [comment]
Is there any other (infosec) tool that has something like this included?

**Comment by Ekultek** [comment]
I second this

**Comment by stamparm** [comment]
Generally, sqlmap fails when there is no connection. Pausing because of no connection won't be implemented, at least if you show me one other tool that has this kind of behavior.

**Comment by BabyBit** [comment]
stamparm , I am confused, can you tell us why not ? 
Did you meant it generally fails in a way that it is unable to continue or perform a ping ?

Also, I think many users are behind VPN when experimenting, so internet connection drop should be common. 

Maybe a general command that can also be used for various things, e.g pause when hdd is full.
``=`` could be a search/grep and not an exact match:

``-pause-if-output "df -h = 100%"``
``-pause-if-output "date =  2017"``

pause if vpn connection dropped and geoip country changed
``-pause-if-output "wget -foo www.some-geoip-service.com/get_geoip = UK"``

``-pause-if-output "ping 8.8.8.8 = timeout"``
``-pause-if-output "python my_custom_script.py = pause"``

no ? :)

**Comment by Ekultek** [comment]
I think he's looking more towards professional grade tools, I don't think I've ever seen one with a pause command for VPN config changes, it'd be a cool feature for sure, but that's just it, it'd be a feature. Which means more coding, more bugs, and more time consumed to keeping it afloat. Having said that, he should defiantly take VPN ip hops into consideration. Or as he told me you could use proxy strings instead, they're about as reliable as a VPN

**Comment by BabyBit** [comment]
I understand, but to clarify: by the VPN I only written a sample use of a possible general command (accept a command and read output), no need to integrate VPN specific commands.

**Comment by Ekultek** [comment]
I didn't say anything about vpn specific commands, I said it'd be a lot of work to get it running

**Comment by stamparm** [comment]
With latest revision:

```
$ python sqlmap.py -hh | grep check-internet
    --check-internet    Check Internet connection before assessing the target
```

**Comment by stamparm** [comment]
![checkinternet](https://cloud.githubusercontent.com/assets/921555/25785200/20421730-337b-11e7-8710-b5008e5c89ee.png)

**Comment by Ekultek** [comment]
That's awesome, nice job man, so if I'm using a proxy file and one of them fails to connect it will skip to the next?

**Comment by stamparm** [comment]
@Ekultek As in original Issue text, focus is to test Internet connection on start of a target scan (e.g. in bulk mode). It is not something really useful to the proxy file feature - in proxy file feature in case of connection fail, sqlmap already (should) skip to the next proxy in list

**Comment by BabyBit** [comment]
Thank you stamparm

**Comment by BabyBit** [comment]
I tested it and it worked very nice :+1: this is awesome.

When it detects no internet connection it pauses and keeps trying while printing dot character on screen, then resumes automatically when connection is back online.

On one instance I noticed that it resumed directly with this note, I found it strange, maybe something to look out for in case others mention it:

```
.......................................................................................................................................................................................................
SQL injection vulnerability has already been detected against [target_name]. Do you want to skip further tests involving it? [Y/n] Y
Skipping [some_url]
Skipping [some_url]
```
