### ISSUE TITLE
Specify charecters 

### ISSUE THREAD

**Issue by bufferz** [sqlmapproject/sqlmap#2509]
hey 
i got to bypass a Firewall by adding a specific characters to the query on a manual inject try . 
how can i be able to add this characters on Sqlmap commande ?
something like 
`http://example.com/info.php?id=-10+**(character)**union+**(character)**select+,1,2,3,4+--+`
i want to add the (character) in the query using sqlmap

**Comment by stamparm** [comment]
Make your own tamper scripts. There are really lots of examples in `tamper/` directory (https://github.com/sqlmapproject/sqlmap/tree/master/tamper). Or, you could try to use some of already included (e.g. `--tamper=space2comment`)
