### ISSUE TITLE
File "./sqlmap.py", line 79     _ = sys.executable if weAreFrozen() else __file__                         ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by eidelweiss** [sqlmapproject/sqlmap#2512]
[root@pentestsystems sqlmap-dev]# ./sqlmap.py --help
  File "./sqlmap.py", line 79
    _ = sys.executable if weAreFrozen() else __file__
                        ^
SyntaxError: invalid syntax

## What are the running context details?

* Installation method :  git clone --depth 1 https://github.com/sqlmapproject/sqlmap.git sqlmap-dev
* Client OS (e.g. `Microsoft Windows 10`): CentOS release 5.11 (Final)
* Python 2.4.3

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap#installation:

```
