### ISSUE TITLE
Bug when different POST on the same URL

### ISSUE THREAD

**Issue by ThePirateWhoSmellsOfSunflowers** [sqlmapproject/sqlmap#2515]
Hi !
I have the following setup : 

- The application is only one URL : http://example.com/app/router
- The frontend POSTs JSON data to the URL, examples
    - `{"action":"externalCall","method":"searchID","data":"123"}`
    - `{"action":"externalCall","method":"getID","data":"456"}`
- I use `sqlmap.py -u "http://example.com/app/router" --data="{"action":"externalCall","method":"searchID","data":"123"}" --cookie="XXXX"`

I've found that the first request is vulnerable to injection. However when I want to test the second request (by just modifying the content of the `--data` parameter) , sqlmap says the call is already vulnerable and print the result of the first request (`sqlmap resumed the following injection point(s) from stored session:`). The only way to really test is to set `--flush-session`, but it's not really what I want and `--fresh-queries` has no effect.

sqlmap version : 1.1.4.18#dev (git clone) on Debian 8.7 against Oracle 12c

Thanks for your tool, really useful :syringe: 

TPWSOS.

**Comment by stamparm** [comment]
Currently, "injection" is recognized as "unique" based on URI_PATH, PLACE (e.g. `POST`) and PARAMETER (e.g. `data`). This means that in your case (I assume that the vulnerable parameter is `data`) sqlmap sees those as same, which you obviously disagree with.

In lots of cases, users tend to copy-paste different URL parameters (e.g. appending some auxiliary params) or use different values for same parameters inside the POST request. Now, those users previously nagged that they want sqlmap to be more "flexible" and not restart the scan if some trivial change has been made in provided parameters.

So, my real question is how to combine your request with current flexible approach. From sqlmap point of view, that different XYZ parameter (in your case `method`) value inside the POST request, which by the way is not the vulnerable parameter, is just ignored in the whole resuming logic

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Ok, I thought that my issue was a bug not a deliberate choice, I did not see the whole picture. It's the first time I face this problem with sqlmap so maybe my issue is just a corner case and the flexible way is fine for the most of the time.

So, the good solution might be to add an arg `--force-rescan` in order to force the scan but keep the session.

**Comment by stamparm** [comment]
Session is fixed to exactly those values I mentioned. Hence, rescanning everything, while keeping the session, doesn't make much sense as I am not sure to which injection point should that session data point to

**Comment by klensy** [comment]
In this case u can use ```--flush-session``` with ```-p data``` to scan only interesting params, to save some time.

**Comment by stamparm** [comment]
As workaround is possible (`--flush-session`) and current session workflow will not be changed (session determination done as explained in last couple of comment), I'll close this down
