### ISSUE TITLE
--tables --count allways problem

### ISSUE THREAD

**Issue by JonhSilver** [sqlmapproject/sqlmap#2522]
Allways problem to count entries count

[14:21:11] [WARNING] missing table parameter, sqlmap will retrieve the number of
 entries for all database management system databases' tables

etries not well enumerated, and not for all tables, half of tables missing after count

**Comment by stamparm** [comment]
That is just a WARNING. sqlmap prefers that you put `-T` when using `--count`. Also, issues having `always problem` inside with zero provided useful data will always be closed as invalid
