### ISSUE TITLE
Mod rewrite question

### ISSUE THREAD

**Issue by Ekultek** [sqlmapproject/sqlmap#2524]
I actually just have a question, according to your documentation: 

`Append an asterisk, *, to the place where sqlmap should check for injections in URI itself. For example, ./sqlmap.py -u "http://target.tld/id1/1*/id2/2", sqlmap will inject its payloads at that place marked with * character. This feature also applies to POST data. Multiple injection points are supported and will be assessed sequentially.`

So to clarify this, I could use `-u https://testsuite.com/php?id=1&account=*&self=*` and sqlmap will attempt to inject both `account=*&self=*` at the same time? Or one after the other?

**Comment by stamparm** [comment]
sqlmap will test one after another. So, first `account` and then `self`. One note though. You should always use valid parameter values. So, instead of `account=*&self=*` use something like `account=admin&self=admin*`

**Comment by Ekultek** [comment]
Okay, thank you
