### ISSUE TITLE
So i have a problem folks with sintax

### ISSUE THREAD

**Issue by jordandark** [sqlmapproject/sqlmap#2528]
So when i was triying to trigger a vulnerability from a webapp mmhh. Sqlmap go crazy and fu** up all.
With this simple (Yeah this >) & (<) word or character whatever (i dont speak english that good)  example:
www.whatever.com/Yeh/why.php?c=misc&id=.
i was wondering if this already have a solve or is only me that havin this cuz i was reading all the help in the terminal and i don´t found a solution
Sorry for my fu***** bad english

**Comment by stamparm** [comment]
Enclose parameter values having `&` with quotes. That's the basics of shell/console running programs. Closing this down as invalid because of to much f***
