### ISSUE TITLE
How operate sqlmaps, first time

### ISSUE THREAD

**Issue by gh0z4ly** [sqlmapproject/sqlmap#2533]
I am already installing phyton 2.7 in windows 10. But why when I press Sqlmap.py the output become this
![image](https://cloud.githubusercontent.com/assets/28677129/26028472/4596d212-384b-11e7-94ee-455292145264.png)

Why it's different with other that I see on the internet and where the place to run the code ?

**Comment by klensy** [comment]
Read [FAQ](https://github.com/sqlmapproject/sqlmap/wiki/FAQ#how-do-i-execute-sqlmap).
