### ISSUE TITLE
[WARNING] heuristic (basic) test shows that GET parameter 'pid' might not be injectable

### ISSUE THREAD

**Issue by rickeyganeshan** [sqlmapproject/sqlmap#2544]
##  Actually i tried to get database of a website but it say that [WARNING] heuristic (basic) test shows that GET parameter 'pid' might not be injectable

i used tamper and technique BU but the results are same 

## What are the running context details?

* Client OS (kali linux 2017.1
* Program version (`sqlmap
* Target DBMS (e.g. `Microsoft SQL Server`): 
* Detected WAF/IDS/IPS protection (e.g. `.ASP NET `):
* SQLi techniques found by sqlmap (e.g. `error-based` and `boolean-based blind`):
* Results of manual target assessment ([WARNING] heuristic (basic) test shows that GET parameter 'pid' might not be injectable
((SELECT 'foobar'))-- qKLV` works):

**Comment by stamparm** [comment]
No comment
