### ISSUE TITLE
Help me and get reward

### ISSUE THREAD

**Issue by anonex95** [sqlmapproject/sqlmap#2545]
Is there any software in Kali Linux that can help to see detail of contents of credit card number in censorship on amazon.com site and payumoney.com like picture below ??
I will give $ 500 to someone who can help me.
 
WWW.AMAZON.COM
![amazon](https://cloud.githubusercontent.com/assets/28605820/26328205/42426158-3f6c-11e7-90fa-36048dd5deb6.png)
----------------------------------------------------------------------------------------------------------------------------------
WWW.PAYUMONEY.COM

![payumoney1](https://cloud.githubusercontent.com/assets/28605820/26328207/42438970-3f6c-11e7-982a-d9bde9b04928.png)
![payumoney2](https://cloud.githubusercontent.com/assets/28605820/26328206/4242c44a-3f6c-11e7-8f14-95cb5e77cec2.png)

**Comment by Ekultek** [comment]
That's not how that works.. The "x" is literally just an "x". The only way you'd ever get that info is to hack into amazon, even then it's unlikely.

- Thomas Perkins

**Comment by anonex95** [comment]
thank you for answer
