### ISSUE TITLE
Multipart 'no parameter found'

### ISSUE THREAD

**Issue by treusfam** [sqlmapproject/sqlmap#2546]
hi well, im trying to use sqlmap with a multipart form, i got the response with burp and saved.
running sqlmap -r scan.txt --dbs 
[00:47:44] [INFO] parsing HTTP request from 'scan.txt'
[00:47:44] [WARNING] detected empty POST body
[00:47:45] [INFO] testing connection to the target URL
[00:47:48] [INFO] testing if the target URL is stable
[00:47:49] [INFO] target URL is stable
[00:47:49] [CRITICAL] no parameter(s) found for testing in the provided data (e.g. GET parameter 'id' in 'www.site.com/index.php?id=1')

running sqlmap -r scan.txt -p "username" --dbs
[00:48:42] [INFO] parsing HTTP request from 'scan.txt'
[00:48:43] [WARNING] detected empty POST body
[00:48:43] [CRITICAL] all testable parameters you provided are not present within the given request data

also i try with * inside the .txt, marking the parameter.. 
this is how scan.txt looks like
POST /panel/index.php HTTP/1.1
Host: localhost.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://localhost.com/panel/index.php
Cookie: misesion=98829c3cf0395fa302dc069bfba76c1e
Connection: close
Content-Type: multipart/form-data; boundary=---------------------------14578663391894691676875374150
Content-Length: 414

-----------------------------14578663391894691676875374150
Content-Disposition: form-data; name="username"

test*
-----------------------------14578663391894691676875374150
Content-Disposition: form-data; name="userpass"

pass
-----------------------------14578663391894691676875374150
Content-Disposition: form-data; name="boton"

Ingresar
-----------------------------14578663391894691676875374150--

thank you for any tip or comment you have!

**Comment by stamparm** [comment]
You are doing something completely wrong. The main clue is: `[00:47:44] [WARNING] detected empty POST body`

I am not able to reproduce neither the first nor second case:

![3](https://cloud.githubusercontent.com/assets/921555/26494895/5bdad12e-4221-11e7-8712-e35b814de157.png)
![1](https://cloud.githubusercontent.com/assets/921555/26494899/5ea98508-4221-11e7-9e26-163ae6d65ad8.png)
![2](https://cloud.githubusercontent.com/assets/921555/26494903/613686fe-4221-11e7-88b7-cbfff0cb05df.png)

**Comment by treusfam** [comment]
Thank you stamparm, the problem is i dont give sqlmap full path of .txt file...... but thanks to your screenshots i was able to fix it! dont judge me :3
