### ISSUE TITLE
Outputing Injection Query to Test in Manual Injection

### ISSUE THREAD

**Issue by putuoka** [sqlmapproject/sqlmap#2550]
Hi, i found latest version of SQLMap fail to retrieved banner information and list of database https://imgur.com/a/gqwi4. I want to know what is the issue but i don't know what query injection used by sqlmap to retrieved banner and database. how to outputting it so i can test the injection manually and trace what's wrong with sqlmap and why it's failed ?

**Comment by klensy** [comment]
Add ```-v X``` where ```X``` in [0;6], read [usage](https://github.com/sqlmapproject/sqlmap/wiki/Usage#output-verbosity). U're wanna use 3 or higher.

**Comment by putuoka** [comment]
sorry but i mean outputting into txt file because if use -v (verbosity) it written in cmd window and hard to read

**Comment by klensy** [comment]
Really, read [usage](https://github.com/sqlmapproject/sqlmap/wiki/Usage#log-https-traffic-to-a-textual-file).

**Comment by stamparm** [comment]
As @klensy pointed out, use `-t traffic.txt` to get the complete traffic into a text file
