### ISSUE TITLE
XPath Injection w/ ExtractValue & UpdateXML

### ISSUE THREAD

**Issue by Dithey95** [sqlmapproject/sqlmap#2558]
I think it would be very useful if XPath Injection was added to SQLMap using ExtractValue and UpdateXML. I've tried looking for other scripts/tools that would automate XPath Injection in that way, but haven't found anything.

**Comment by stamparm** [comment]
XPath injection into SQL injection tool? Sorry, but no. sqlmap is not going to be an AIO tool as AIO tools tend to loose the focus
