### ISSUE TITLE
Captcha flag for sqlmap

### ISSUE THREAD

**Issue by mitros123** [sqlmapproject/sqlmap#2560]
Hello. I know this has been asked before. I would like to propose a captcha flag for sqlmap, that may be enough to break some weak captchas.

So, some captchas are we weak and a user may have the ability to break them programmatically (perhaps by using an OCR engine against a captcha image). Could sqlmap include a flag that denotes the captcha image, the captcha box where the correct string should be put, and the user's command that would try to decode the captcha?

Thanks in advance.

**Comment by stamparm** [comment]
Please give a feasible example (captcha system's (demo) url with working tool)

**Comment by mitros123** [comment]
No I'm afraid I do not have any.It occured to me during a recent CTF whose captcha could be easily beater by tesseract-ocr. No real life examples though.

**Comment by Ekultek** [comment]
@stamparm https://github.com/ptigas/simple-captcha-solver

It's possible

**Comment by stamparm** [comment]
I don't like putting things that are not from real life. Just asked for one real life example and adequate tool to solve it

**Comment by Ekultek** [comment]
@stamparm yeah I gotcha man. It'd be a cool thing to have for sure, if I can find an example would you consider it, like actually consider it? I don't think it would be capable to break somewhat sophisticated captchas, but I'm sure there there's probably a tool that has a captcha breaker in it.

**Comment by stamparm** [comment]
So, what should be the workflow here? User option to mark the proper location of captcha image (e.g. some regex), option to mark where to put the answer (e.g. some GET/POST parameter), option to set proper OCR command and of course, regex to recognize the answer from OCR command itself (if successful).

I would say that this is something unusable from my point of view. One more thing. Non-shitty captcha systems are not so easy to bypass. Also, shitty ones could be bypassed, while in lots of cases you have to train your OCR system itself.

All in all, closing this down

**Comment by theblazehen** [comment]
Found an IRL use case, SQL injection on the login form, but requires a CAPTCHA to login. Could be useful to have support for something like 2captcha.com

**Comment by stamparm** [comment]
Please write a command that cracks that same captcha. Also, please describe
the workflow (new options) that would be used by sqlmap

**Comment by stamparm** [comment]
I believe that you are really underestimating the problem of captcha.
Hence, please give a complete workflow together with usable tool that would
do solving of captcha together with SQLi ( in real time, ofcourse)

On Aug 10, 2017 16:58, "Miroslav Stampar" <miroslav.stampar@gmail.com>
wrote:

Please write a command that cracks that same captcha. Also, please describe
the workflow (new options) that would be used by sqlmap
