### ISSUE TITLE
Need to figure the data size and time.

### ISSUE THREAD

**Issue by Yousayiloveu** [sqlmapproject/sqlmap#2563]
When I am dumping a very large database, it's awful that I can not see the information displayed, I just can run lsof or netstat to see if sqlmap goes well. But I think if Sqlmap could figure out the size of the data (just a easy calculation based on the structure of table and counting the entries ). If Sqlmap find it will spend a long time, it's better that Sqlmap could figure the speed.

**Comment by stamparm** [comment]
You haven't stated anything about the case. For example, in case of "full UNION SQLi", whole table is retrieved in one go (request), hence, there is no way how to make a meaningful estimation.

**Comment by stamparm** [comment]
p.s. I believe that in your case there was a "full UNION SQLi". In those kind of cases just wait for sqlmap to finish. As said, in one request whole table dump is retrieved.
