### ISSUE TITLE
Can not upload any files

### ISSUE THREAD

**Issue by AVR1234** [sqlmapproject/sqlmap#2565]
Hello, i have a one problem, I found a very large base. If i used union technique i can download only 36k value - no more but base have 600k value. For different techniques="BET" i can download but very very slowly if i used 10 threads. So i tried to use --write-file or use comannad --os-cmd -v l but show me in display 
web server operating system: Linux Debian 7.0 (wheezy)
web application technology: PHP 5.4.45, Apache 2.2.22
back-end DBMS: Oracle
[21:06:06] [CRITICAL] File system write access not yet implemented for Oracle

Could you help me and give me advice on how to speed up the download of the database?
if have:
    Type: boolean-based blind
    Type: error-based
    Type: AND/OR time-based blind
    Type: UNION query
And is-dba - TRUE

Thank you for help!

**Comment by shadowfolder** [comment]
Sqlmap can't read/write in Oracle inection, that very sadly. :(

**Comment by stamparm** [comment]
Currently there is no known way how to do it from SQLi (please don't give references to PL/SQL file writes as those would require stacking - not available in vast majority of Oracle cases)

There is no way how to speed up your case except trying to takeover the server with some other technique than SQLi. For example, password reusage while trying to login to some other page

**Comment by AVR1234** [comment]
Already read(( Thanks. But i cant understand somietime dump very fast, then close change socks, and start dump again... But sometimes, like today, server dont want to dump by any socks and by any tichniques...

**Comment by stamparm** [comment]
Can be really lots of things. You should find out this by yourself. For example, too many connections problem when using greater number of threads (e.g. in case of MsSQL), some server side protection dropping too many connection requests in short period of time, cloudflare (browser challenge or captcha) activation, DBMS/server session going into "waiting" mode before the last DBMS query ends, etc.

**Comment by AVR1234** [comment]
Have some question which i am not understand. Why sometimes for same database i can to dump by --start and --stop but sametime if i swich on start and stop i cant see line download and sqlmap download fixed values. For example table have 100k value, but i can dump only 38k no more, but after 1 week and change socks5 i cant dump start=1 stop=100000. Help me pls?
