### ISSUE TITLE
Retrieving and duplication

### ISSUE THREAD

**Issue by Victorilo** [sqlmapproject/sqlmap#2566]
Dear owner, this issue (#2557) still not resolved, if you check the dump file during injection you will find out that : 
sqlmap.py -u "http://taget.com/target.php?ID=1" -D database -T table -C column --dump --start 1000
if you press ctrl+c during the injection an error occured and the dump file will not appear in the sqlmap folder and either in log file

**Comment by stamparm** [comment]
So, #2557 has nothing to do with `Ctrl-C` in middle of dump, right?

**Comment by stamparm** [comment]
With latest commit (revision), you can also do the Ctrl-C

**Comment by Victorilo** [comment]
dear in former sqlmap version if during the dumping stage press crtl+c the injected data will store in sqlmap folder however in edited version which edit last 2 hours ago i encountered with this error:
[06:58:01] [WARNING] HTTP error codes detected during run:
404 (Not Found) - 1 times, 500 (Internal Server Error) - 171 tim
and dumped file will not stored in neither log file and dump folder 
this problem occur with the case problem have the same feature of #2557

**Comment by stamparm** [comment]
@Victorilo please, in future just reply with YES. I've kindly referred that there was no mention of Ctrl-C in last Issue request (#2557). Please, just help me out here and don't play the deaf phone.
