### ISSUE TITLE
sqlmap:error: missing a mandatory option

### ISSUE THREAD

**Issue by mahdialiverdi** [sqlmapproject/sqlmap#2571]
hi 
i installed sqlmap on ubuntu and run it when i type any mandatory option like -h or -hh that give me this answer: command not found
how can i fix it?

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap#installation

**Comment by mahdialiverdi** [comment]
i read it and done it but still have that problem..

**Comment by stamparm** [comment]
you've provided 0 data here. Screenshots, cmd outputs, used options, etc. Nothing.

**Comment by mahdialiverdi** [comment]
ok
how can i do these things

**Comment by mahdialiverdi** [comment]
please help me i am amatuer

**Comment by stamparm** [comment]
Please, just google for: how to run sqlmap

**Comment by Mderra** [comment]
you have to type
sqlmap.py -h

**Comment by Mderra** [comment]
and if it doesnt work type 
python sqlmap.py -h
