### ISSUE TITLE
Bypass a captcha protection

### ISSUE THREAD

**Issue by riless** [sqlmapproject/sqlmap#2573]
I've made a little script in python that can fill a captcha parameter before each `sqlmap` request.

Can I plug it to the `sqlmap` command line ?

maybe something like this ?

`python sqlmap.py -u http://target.com/index.php?captcha_ans=<captcha_solver.py>&username=foo&password=bar`

**Comment by stamparm** [comment]
Sorry, but no. Also, you are oversimplifying the task. You are not mentioning neither how sqlmap should send the original response (carrying the captcha task), nor where to store the (if any) image, nor anything.

Anyway, this workflow doesn't look promising and sqlmap doesn't support it
