### ISSUE TITLE
SQLMap re-encoding / corrupting __VIEWSTATE and other ASP.NET params?

### ISSUE THREAD

**Issue by ah8r** [sqlmapproject/sqlmap#2575]
## What's the problem (or question)?

I have copied a request out of Burp. The request has a few ASP.NET params like __VIEWSTATE, __EVENTVALIDATION, etc. These are checked by the application so cannot be removed / modified. They both contain Base64 encoded values, which are then URL encoded. So for example, one ends with %3D%3D (==).

When I run SQLmap with the saved request, and give it a completely separate parameter to test, for some reason it re-encodes and corrupts the __VIEWSTATE and __EVENTVALIDATION parameters, so %3D%3D becomes %5C=%5C=.

The server rejects the request. I'm not sure why this is happening, and it happens after the 2nd request that SQLMap sends. I proxied SQLMap and the initial "testing connection to the target URL" request is sent with no issues, no modifications. The next request ("testing if the target URL is stable") then starts modifying the parameter values in the way I described, and all subsequent requests do the same thing.

Is there a flag I can use to stop this, or a way I should be encoding the request to prevent this weird encoding?

## How can we reproduce the issue?

Not sure how to reproduce other than finding a similar request that uses a Base64 encoded value. I cannot unfortunately copy the request I am using.

**Comment by davidtavarez** [comment]
@ah8r what I do is intercept the request and copy the decoded values. This is how I do it.

### Method 1.

Using Firefox, open the Developer tools, then go to the Network tab. Select the request that you want to test, then click on "Edit and resend". Go down to the "Request body" box and copy everything. 

The go to http://meyerweb.com/eric/tools/dencoder/ and paste the copy values and make click on "Decode". Remove the Content-Type and Content-Length headers and use the rest to pass it as parameter using --data. 

ASP.NET developers normally use __VIEWSTATEGENERATOR and __VIEWSTATE to validate the request in a dump way. You can decode the Base64 and see that's nothing more than a date and time.

## Method 2.

Using Firefox, open the Developer tools, then go to the Network tab. Select the request that you want to test, then click on "Edit and resend". Copy everything, remove the Content-Type and Content-Length headers and paste it on a file an use "-t file" with sqlmap. The file should be something like this.

```
GET [URL]?id=X HTTP/1.1
Host: [HOST]
User-Agent: Mozilla/5.0 (Windows NT 6.2; rv:20.0) Gecko/20121202 Firefox/20.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: [REFERER]
Cookie: [COOKIES]
Connection: keep-alive

__EVENTTARGET=&__EVENTARGUMENT=&__VIEWSTATE=/[REALLYLARGESTRING]&__VIEWSTATEGENERATOR=[GENERATOR]&__EVENTVALIDATION=[VALIDATOR]=&txtField1=blahblah&txtField2=blahblah&btnSubmit=Edit
```

Then sqlmap -r file -p txtField1,txtField2.

**Comment by stamparm** [comment]
@ah8r Sorry for waiting. I am not able to reproduce.

Dummy request.txt file:

```
POST / HTTP/1.1
Host: testphp.vulnweb.com

__VIEWSTATE=foobar%3d%3d&id=1
```

Dummy run:

```
python sqlmap.py -r /tmp/request.txt --flush-session -t /tmp/traffic.txt -p id
```

Content of traffic.txt:

```
HTTP request [#16]:
POST / HTTP/1.1
Host: testphp.vulnweb.com
User-agent: sqlmap/1.1.6.19#dev (http://sqlmap.org)
Content-length: 79
Connection: close

__VIEWSTATE=foobar%3d%3d&id=1%25%27%20AND%208566%3D7976%20AND%20%27%25%27%3D%27
...
```

![6](https://user-images.githubusercontent.com/921555/27695748-16ab6e4e-5cf0-11e7-999b-44c58addd1d0.png)

**Comment by stamparm** [comment]
@ah8r ping?

**Comment by 0x6d69636b** [comment]
I have another example with the same issue as ah8r:

Request in Burp:
```
POST /index.aspx HTTP/1.1
Host: 192.168.0.116
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Referer: http://192.168.0.116/
Connection: close
Upgrade-Insecure-Requests: 1
Content-Type: application/x-www-form-urlencoded
Content-Length: 241

__VIEWSTATE=%2FwEPDwUJODMxNDc4MDEwZBgBBQlHcmlkVmlldzEPZ2QtXxOOo5a7ORqyUSD1T%2Fo7Fz6Abg%3D%3D&TextBoxUsername=user&TextBoxPassword=pass&ButtonLogin=Login&__EVENTVALIDATION=%2FwEWBALIp%2FufDALt8L%2B0AQKpzpH0DQKWrKCPD7i7EsKIMWb5tRGoOr7BdMOjb6KM
```

sqlmap run:
`python sqlmap.py -r /tmp/request.txt -p TextBoxUsername --flush-session -t /tmp/traffic.txt`

Content of traffic.txt:
```
HTTP request [#2]:
POST /index.aspx?OLYL%3D1277%20AND%201%3D1%20UNION%20ALL%20SELECT%201%2CNULL%2C%27%3Cscript%3Ealert%28%22XSS%22%29%3C%2Fscript%3E%27%2Ctable_name%20FROM%20information_schema.tables%20WHERE%202%3E1--%2F%2A%2A%2F%3B%20EXEC%20xp_cmdshell%28%27cat%20..%2F..%2F..%2Fetc%2Fpasswd%27%29%23 HTTP/1.1
Host: 192.168.0.116
Accept-language: en-US,en;q=0.5
Referer: http://192.168.0.116/
User-agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
Content-type: application/x-www-form-urlencoded
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Upgrade-Insecure-Requests: 1
Content-length: 360
Connection: close

__VIEWSTATE=%5C%2FwEPDwUJODMxNDc4MDEwD2QWAgIDD2QWBAIFDw8WAh4EVGV4dAUhTG9naW4gZmFpbGVkOiBJbnZhbGlkIGNyZWRlbnRpYWxzZGQCDw8PFgIeB0VuYWJsZWRoZGQYAQUJR3JpZFZpZXcxD2dkS%5C%2BZJzwe3IfBLnVl40JOU7VC0opU%5C=&TextBoxUsername=user&TextBoxPassword=pass&ButtonLogin=Login&__EVENTVALIDATION=%5C%2FwEWBAKJqpOqCgLt8L%5C%2B0AQKpzpH0DQKWrKCPD6MTboD0fUe%5C%2BKF%5C%2BWedTHZZsujdSb
```

**Comment by stamparm** [comment]
@0x6d69636b please update to the latest revision. I am not able to reproduce the issue, even with your data and command:

![1](https://user-images.githubusercontent.com/921555/29493103-fe225b12-858f-11e7-87df-8e0dfb52044c.png)

**Comment by 0x6d69636b** [comment]
I used already the latest version. I tried today "1.1.8.8#dev" and "1.1.8.8#dev" on Kali Linux with the same result as in my initial post.

**Comment by stamparm** [comment]
@0x6d69636b how to reproduce it? Please upload the request file somewhere and give me exact commands to run it

**Comment by 0x6d69636b** [comment]
The request file is here: https://github.com/0x6d69636b/file_upload/blob/master/request.txt
I used the command `python sqlmap.py -r ~/request.txt -p TextBoxUsername --flush-session -t ~/traffic.txt

The python version on Kali Linux is Python 2.7.13, I'm not sure if that matters.

**Comment by stamparm** [comment]
@0x6d69636b just tried and nothing. As said, unable to reproduce (used latest revision on Ubuntu 16.04):

![1](https://user-images.githubusercontent.com/921555/29767213-ec0c9890-8be1-11e7-905a-c31427915516.png)
