### ISSUE TITLE
sqlmapapi:SQLite objects created in a thread can only be used in that same thread

### ISSUE THREAD

**Issue by wilson9x1** [sqlmapproject/sqlmap#2576]
python sqlmapapi.py -s --adapter=paste

I run 3 sqlmapapi client, error info:
![image](https://user-images.githubusercontent.com/9835472/27019307-f629bf38-4f69-11e7-8917-88fac7a43aee.png)

**Comment by wilson9x1** [comment]
in addition，how can I test  url param JSON deserializable in sqlmapapi？

there is no option to set JSON deserializable true...

**Comment by stamparm** [comment]
@wilson9x1 to test JSON data just put HTTP request having JSON data into a request file and pass it with `-r` to sqlmap. sqlmap should automatically recognize it as JSON and ask you whether you want to test it as a JSON

**Comment by wilson9x1** [comment]
@stamparm but I test in **sqlmapapi.py**, not sqlmap.py

**Comment by stamparm** [comment]
@wilson9x1 then you have a problem :). Currently at conference. Will think of something later

**Comment by stamparm** [comment]
@wilson9x1 related to the second "problem". Currently there is no way how to send POST data (request) to the sqlmapapi server than to use the `--data` (e.g. `--data='{"foo":"bar"}'`)

**Comment by wilson9x1** [comment]
@stamparm  Ok, thank you !
