### ISSUE TITLE
Progress Bar Inquiry For Full ETA of selected columns dump

### ISSUE THREAD

**Issue by AmericanY** [sqlmapproject/sqlmap#2578]
Hello,

I would like to know if there's any way to show the ETA Of All selected columns dump from an table ?

since am using --eta and it's only show ETA per output.

even if there's a way using sql statement by --sql-query please let me know.

web application technology: PHP 5.4.45, Apache
    Type: boolean-based blind
    Title: MySQL >= 5.0 boolean-based blind - Parameter replace

**Comment by stamparm** [comment]
In case of error-based and (partial) union based SQLi `--eta` shows dumping progress for the whole table, while in all inference-based SQLi cases `--eta` shows the progress of only that single entry being dumped that moment
