### ISSUE TITLE
injecting paramter inside base64 encoded paramater

### ISSUE THREAD

**Issue by balhadj47** [sqlmapproject/sqlmap#2584]
hello everyone i'm new in sqlmap i have a problem
this is a simple get:
https://localhost/img.php?q=aWQ9MSZmb3JtPTEmaGFzaD0x
after decoding 'q' pramater you'll see 
"id=1&form=1&hash=1"
i found an sql injection at id paramater
so that's mean it a paramater inside paramater
now i want is inject 'id' paramater

**Comment by Ekultek** [comment]
This might help https://github.com/sqlmapproject/sqlmap/issues/2242

**Comment by balhadj47** [comment]
not resovled yet
and i found a temporary solution
i creaed a php file with this content:
<?php
readfile("https://localhost/img.php?q=".base64_encode("id=".$_REQUEST['a']."&form=1&hash=1"));
?>
and i uploaded it into my local server with name sql.php
so all what i have to do is injecting a paramater in "http://localhost/sql.php?a="

**Comment by stamparm** [comment]
Duplicate of #25
