### ISSUE TITLE
Run Failed! Some code Shutting down the app

### ISSUE THREAD

**Issue by stanislav-web** [sqlmapproject/sqlmap#2589]
Please look. It happening with any arguments
```
python sqlmap.py -u "http://example.com/?test=123" --batch
```

```
 ___
       __H__
 ___ ___["]_____ ___ ___  {1.1.6.13#dev}
|_ -| . [,]     | .'| . |
|___|_  [)]_|_|_|__,|  _|
      |_|V          |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting at 02:36:37

[02:36:37] [INFO] testing connection to the target URL
('example.com', 80)
(<object object at 0x7fc92bd110c0>, None)

[*] shutting down at 02:36:38
```

**Comment by stamparm** [comment]
Not able to reproduce:

![2](https://user-images.githubusercontent.com/921555/27305516-2d6a53da-5542-11e7-8a67-376b95ebc3a9.png)

**Comment by stanislav-web** [comment]
I got the same error from standalone git clone and Last Kali distributive

**Comment by stamparm** [comment]
For any target? If so, then you have some installation issue. Anyway, I am not able to reproduce. As you can see I've run exactly the same command (on Ubuntu 16.04)

**Comment by Ekultek** [comment]
@stam, I've been having some weird installation issues with distros lately too. Not this one but something similar. I noticed that completely reinstalling sqlmap helps

- Thomas Perkins

**Comment by stanislav-web** [comment]
@stamparm  
[sqlmap](https://sc-cdn.scaleengine.net/i/6d1d1e2b91aeb2e1e305e682402e9fb2.png)

**Comment by stanislav-web** [comment]
It seems that some of my installed dep packages contained  debug ... After the updates of the python packages everything works as it should. So, no worries! And sorry for disturb
