### ISSUE TITLE
bug with ``-p for JSON @  non-flat JSON``

### ISSUE THREAD

**Issue by drwetter** [sqlmapproject/sqlmap#2602]
Hi,

I was under the impression that I can specify parameters to test also if there are non-GET/-POST params.

With JSON in my case it doesn't seem to work correctly:

./sqlmap.py --ignore-proxy $alertstr --force-ssl $LOGCMD \
  --output-dir=$PFAD \
  --ignore-401 -p zipstart \
  --banner --current-user --current-db  --hostname  --is-dba  --dbs \
  --keep-alive --threads=$THREADS -v $VERB --parse-errors --timeout=$TIMEOUT \
  --level=$LEVEL --risk=$RISK -r $REQUEST "

output:
```
[..]
JSON data found in POST data. Do you want to process it? [Y/n/q] 
[16:35:59] [CRITICAL] all testable parameters you provided are not present within the given request data

[*] shutting down at 16:35:59
```

Request is like

```
POST /api/AAAAAAAAAA/BBBBBBBBBBB HTTP/1.1
Host: HOST.TLD
Connection: close
Content-Length: 894
Accept: application/json, text/plain, */*
Origin: https://HOST.TLD
User-Agent: Mozilla/5.0 foobar
Authorization: Bearer eyJhbGciOi[yougottabekiddingme]
content-type: application/json
Referer: https://HOST.TLD/
Accept-Language: en-US,en;q=0.8,de;q=0.6

{
  "DDDDDsearch": {
    "DDDDDaaaa": [],
    "costumer": [],
    "DDDDDNo": "",
    "firstname": "",
    "surname": "",
    "zipstart": "10000",
    "zipstop": "30000",
    "dob": "",
    "DDDDDstart": "",
    "DDDDDend": "",
  },
  "xySearchParameter": {
    "resultSetPageSize": 15,
    "resultSetStartIndex": 0,
    "resultSetOrderings": "",
  }
}
```

but larger.  ``-p <param>`` works if I specify a key from the **second** JSON object (like ``resultSetPageSize``):, it does not if it's from the **first** one (like ``zipstart``).

Does the JSON parser cause trouble?

Cheers, Dirk

**Comment by stamparm** [comment]
Fixed recently (along with other JSON Issues):

![1](https://user-images.githubusercontent.com/921555/31439307-f488ec22-ae8b-11e7-804d-f1bcf33b3908.png)

![2](https://user-images.githubusercontent.com/921555/31439308-f4a2af04-ae8b-11e7-9b17-8795fd6120f7.png)

**Comment by drwetter** [comment]
cool, thx!

**Comment by kbroughton** [comment]
I also hit this with a complex json dict when trying multiple parameters with -p 'param1 param2'
It worked when I tested only one param at a time.
