### ISSUE TITLE
Feature  request for --dbms switch

### ISSUE THREAD

**Issue by drwetter** [sqlmapproject/sqlmap#2603]
In order to save time it would be great  to either specify a number of possible DBMS like ``--dbms=postgres,Oracle`` or maybe to exclude certain DBS like ``--dbms='!postgres'`` or  ``--dbms='!postgres,!Oracle'`` (or with sth like ``--notdbms=postgres,Oracle``).

At least from my experience often I either know the architecture but don't have a clue in which DB which parameter ends up. In other cases I know that for sure it is not ``IBM DB2, Informix, Microsoft Access, MSSQL`` etc.

**Comment by stamparm** [comment]
`--dbms` already worked that way, then some users misused it (not on purpose) and I unknowingly turned off that feature (multiple DBMS statement). Will patch accordingly

**Comment by drwetter** [comment]
Hi Miro, 

have you found the time? Cheers, Dirk

**Comment by stamparm** [comment]
Currently on vacation. Will find time next week. Sorry for waiting

**Comment by drwetter** [comment]
don't worry, enjoy your time off

**Comment by stamparm** [comment]
With latest revision, something like (your first proposition) `--dbms=postgres,Oracle` will restrict all tests to ONLY PostgreSQL and Oracle. Haven't implemented `!` logic as I believe that it wouldn't be used as much.

**Comment by drwetter** [comment]
thx!
