### ISSUE TITLE
JSON values "true, false, null" ignored

### ISSUE THREAD

**Issue by drwetter** [sqlmapproject/sqlmap#2604]
Hello,

it's me again. :)

If I have a single JSON object in the POST body , keys having a value without a value in quotes -- in my cases ``true``, ``false``, ``null`` are not being tested.

```
{
   "myval": "1"
   "groupByAAAA": true
}
```

First one is being tested, second one and others as described not.
 
Thx, Dirk

**Comment by stamparm** [comment]
`true` and `false` are ignored to save scanning time as it is assumed that (e.g.) JSON parameters having boolean values should not accept string values (SQLi payloads). I'll patch the workflow for `null`, though, we could further discuss for (e.g.) boolean values.

**Comment by drwetter** [comment]
Hmm, _should not_ is different to _does not._ From my point as a tester I rather would like to make sure that there's no injection vector hidden. I understand the scanning time argument though thus a cmd line switch or a q asking the user (as for JSON in general) could come in handy

**Comment by drwetter** [comment]
👍

**Comment by stamparm** [comment]
@drwetter please take a look at #2692
