### ISSUE TITLE
OS X Install Issues

### ISSUE THREAD

**Issue by iPredictable** [sqlmapproject/sqlmap#2619]
Hi, I'm on a 10.12 Sierra OS X machine and I've tried to use the git clone command but it gives given error:
nobody:~ Kasra$ git clone --depth 1 https://github.com/sqlmapproject/sqlmap.git sqlmap-dev
Cloning into 'sqlmap-dev'...
remote: Counting objects: 618, done.
remote: Compressing objects: 100% (560/560), done.
error: RPC failed; curl 56 SSLRead() return error -9806      
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

and when I tried to download zip and unzip this happened, I've never experiences this message(s)
<img width="385" alt="screen shot 2017-07-20 at 3 58 35 pm" src="https://user-images.githubusercontent.com/22254866/28416336-a167bd60-6d64-11e7-90a0-b0303443f679.png">

**Comment by stamparm** [comment]
You have some non-sqlmap problem. Something is breaking your connection with github.com. You should inspect you connection settings. At least the ZIP should work without any problems, while you have problems downloading it properly too.
