### ISSUE TITLE
How to set HTTP2 headers?

### ISSUE THREAD

**Issue by mma** [sqlmapproject/sqlmap#2623]
## What's the problem (or question)?
How to set this headers https://http2.github.io/http2-spec/#HttpRequest
:authority:
:method:
:path:
:scheme:
I tried --headers but it seems to be some problems bacause of the starting : in the header field.

**Comment by stamparm** [comment]
sqlmap, like majority of Python projects, (still) doesn't support HTTP/2.
Hence, support for those headers doesn't make sense as the underlying HTTP
connection is still HTTP/1.1
