### ISSUE TITLE
Add "next target/url" to user aborted prompt ?

### ISSUE THREAD

**Issue by BabyBit** [sqlmapproject/sqlmap#2624]
When testing many urls from a list with `-m list.txt` hitting `ctrl+c` says
```
user aborted during detection phase
[(S)kip current test/(e)nd detection phase/(n)ext parameter/(c)hange verbosity/(q)uit] s
``` 
Can any of these options switch to next target / main URL in the provided `-m` list ? 
If not, can an option be added ? 

Since url from `-m` list could have additional sub-urls detected with `--crawl`, would be useful to skip whole target/domain from `-m` list; now I am getting confused because the provided list could contain multiple URLs from same domain. Maybe `skip (D)omain` or `(I)gnore domain`?

// If anyone else finds this useful, please vote.

**Comment by Ekultek** [comment]
Doesn't ending the detection phase basically do the same thing you're asking?

**Comment by BabyBit** [comment]
I think `end detection` would stop `--crawl` for all urls in the list and not just the current one ...

**Comment by Ekultek** [comment]
@BabyBit you think, or you know? Just because you think it does something doesn't mean that's what it does, test it and see what it does.

**Comment by stamparm** [comment]
@BabyBit new prompt in multiple-target cases:
```
how do you want to proceed? [ne(X)t target/(s)kip current test/(e)nd detection phase/(n)ext parameter/(c)hange verbosity/(q)uit]
```

**Comment by BabyBit** [comment]
I appreciate the updates, but I am not sure it works as expected .... notice same `example.com` before and after pressing `ne(X)t target` ....

Is it a bug or I didn't understand the update ? Maybe it moves to next URL found by `--crawl` and not next url/domain in `-m` list 

Just wanted to report it in case is a bug 

	[#4] form:
	GET https://example.com/?search=
	do you want to test this form? [Y/n/q] 
	> Y
	Edit GET data [default: search=]: search=
	do you want to fill blank fields with random values? [Y/n] Y
	...
	[21:22:02] [WARNING] there is a possibility that the target (or WAF/IPS/IDS) is dropping 'suspicious' requests
	[21:22:02] [CRITICAL] connection timed out to the target URL. sqlmap is going to retry the request(s)
	[21:22:10] [WARNING] user aborted during detection phase
	how do you want to proceed? [ne(X)t target/(s)kip current test/(e)nd detection phase/(n)ext parameter/(c)hange verbosity/(q)uit] X
	[21:22:12] [WARNING] HTTP error codes detected during run:
	403 (Forbidden) - 1 times
	[21:22:12] [INFO] [INFO] checking for Internet connection
	[#5] form:
	POST https://example.com/archives/
	POST data: EMAIL=foo&form_element_id=foo
	do you want to test this form? [Y/n/q] 
	> Y
	Edit POST data [default: EMAIL=...] (Warning: blank fields detected): EMAIL=foo&form-1
	do you want to fill blank fields with random values? [Y/n] Y

**Comment by stamparm** [comment]
@BabyBit It moves to the next target in list, which doesn't need to be the different host. In this case, next target was URL/form found by the `--crawl`

**Comment by BabyBit** [comment]
ok
