### ISSUE TITLE
json with sqlmap

### ISSUE THREAD

**Issue by z3ro** [sqlmapproject/sqlmap#2625]
hi i have the following issue 
after executing -r file.txt

python sqlmap.py -r file.txt

        ___
       __H__
 ___ ___["]_____ ___ ___  {1.1.7.21#dev}
|_ -| . [)]     | .'| . |
|___|_  [(]_|_|_|__,|  _|
      |_|V          |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual
 consent is illegal. It is the end user's responsibility to obey all applicable
local, state and federal laws. Developers assume no liability and are not respon
sible for any misuse or damage caused by this program

[*] starting at 03:43:50

[03:43:50] [INFO] parsing HTTP request from 'file.txt'
custom injection marker ('*') found in option '--data'. Do you want to process it? [Y/n/q] y
JSON data found in POST data. Do you want to process it? [Y/n/q] y
[03:43:54] [INFO] testing connection to the target URL
[03:43:55] [INFO] heuristics detected web page charset 'ascii'
[03:43:55] [INFO] testing if the target URL is stable
[03:43:56] [INFO] target URL is stable
# [03:43:56] [CRITICAL] no parameter(s) found for testing in the provided data (e.g. GET parameter 'id' in 'www.site.com/index.php?id=1')

[*] shutting down at 03:43:56

my file.txt content

POST /router.php HTTP/1.1
Host: xxxxx
User-Agent: Mozilla/5.0 (Windows NT 6.1; rv:54.0) Gecko/20100101 Firefox/54.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Referer: http://xxxxx/
Content-Length: 89
Cookie: PHPSESSID=onb7qlp4pra5lau3baoe5r0d03
Connection: close

{"action":"FUNCTIONS","method":"login","data":["*","xx"],"type":"rpc","tid":1}

what i can do if there is no get request and already declared on the request its a post request
help please

**Comment by stamparm** [comment]
@z3ro fixed with latest commit

**Comment by z3ro** [comment]
good work,
seems good for me

thank you
