### ISSUE TITLE
What's the correct syntax for supplying domain with NTLM credentials?

### ISSUE THREAD

**Issue by selman92** [sqlmapproject/sqlmap#2627]
We can supply credentials with **--auth-cred** argument in the **username:password** format, since the sqlmap supports NTLM authentication, how can we supply a domain in this format? Is this the correct usage or is it not supported:

`domain\username:password`

**Comment by Ekultek** [comment]
NTLM hashes use the syntax `USERNAME:SID:LM_HASH:NTLM_HASH:::` for a full hash, I'm assuming sqlmap will use just the NTLM hash because that's the only part that will be authenticated as a password from the server.

**Comment by stamparm** [comment]
![1](https://user-images.githubusercontent.com/921555/28695108-7a9c9998-732d-11e7-949d-d782c8a0f841.png)

**Comment by Ekultek** [comment]
So do you use the full ntlm hash or just the server auth part?

- Thomas Perkins

**Comment by stamparm** [comment]
password, as can be seen from attached screenshot, not the hash

**Comment by Ekultek** [comment]
Awh okay thanks man

- Thomas Perkins
