### ISSUE TITLE
Complex injection in URL?

### ISSUE THREAD

**Issue by davidtavarez** [sqlmapproject/sqlmap#2633]
I'm just wondering how to test an URL with this structure:

http://www.DOMAIN.com/path/subpath/some-text-just-nothing-important-ID

The param to test (ID) is after the last dash (-)

How can we use sqlmap to test it?

**Comment by stamparm** [comment]
```
python sqlmap.py -u "http://www.DOMAIN.com/path/subpath/some-text-just-nothing-important-ID*"
```

p.s. notice the usage of custom injection marking char `*`
