### ISSUE TITLE
Help in Decryption the HexaDecimal

### ISSUE THREAD

**Issue by smfai200** [sqlmapproject/sqlmap#2637]
I used --binary-fields and got 0xff2902a2b61535ac9b6d61f82dc2a095, Can Anyone tell me how to decode this ?

**Comment by smfai200** [comment]
Or the Tutorial on how to decrypt it! As i really can't Understand how to do it with hashcat!

**Comment by Ekultek** [comment]
0xff2902a2b61535ac9b6d61f82dc2a095 is a hash. As a rule of thumb hashes cannot be decoded, or decrypted. They can be cracked though, https://github.com/ekultek/dagon try with that

**Comment by smfai200** [comment]
Can you Tell me the Type of Hash this is ? @Ekultek

**Comment by Ekultek** [comment]
Go to that link and make an issue

**Comment by stamparm** [comment]
@smfai200 so, basically, you just have to Google a bit. That looks like a 128-bit hash. Out of those commonly used, it is most probably an MD5
