### ISSUE TITLE
Possible to get garbage binary using the binary field flag?

### ISSUE THREAD

**Issue by Ekultek** [sqlmapproject/sqlmap#2638]
Not an issue, just a question, using sqlmap and trying to grab hashes, is it possible to get garbage binary using the binary field flag? What I mean is it possible that sqlmap will pull data that it assumes is a hash because it matches the length on complexity of a hash, without it actually being a hash?

**Comment by stamparm** [comment]
Hex is hex. Sqlmap doesn't assume anything, it just retrieves data with --binary-fields in hexadecimal format. If you get non-hex data in that kind of data retrieval, you are getting garbage, especially in case of time-based SQLi.

**Comment by Ekultek** [comment]
Thank you
