### ISSUE TITLE
Hex Garbage!

### ISSUE THREAD

**Issue by smfai200** [sqlmapproject/sqlmap#2639]
–Êö¯'Í“{0ù#                                |
| \x13\xc0ʰ\xf6\x00\xaf\x00'\x00\xcd\x00\x1c |
| ?                                          |
| 0x                                         |
| \x13 \xca\x00\xf6\x00\xaf                  |
| –Êö¯'Í“       

I tried to retrive dump from column with --hex and i get the above, now i am not able to decrypt password from this! Any help! also tried --binary-fields ==> garbage too!
0x1320ca00f600af002700cd001c207b003000f90 (hex)
this was changed to –Êö¯'Í“{0ù#  !!!

**Comment by stamparm** [comment]
I warned you on previous issue

**Comment by smfai200** [comment]
Yes but you did not told me any solution! I have been stuck around it for quite long, if you can do, i would send you the request file :/
