### ISSUE TITLE
bash: --method=get: command not found

### ISSUE THREAD

**Issue by FailGecko9800** [sqlmapproject/sqlmap#2641]
hi how are you my name is nick and i am using SQLMAP 
but i have 2 parameters they are the following

https://twitter.com/login/error?username_or_email=failgecko9800&redirect_after_login=%2F
(twitter know that i am trying to get in because i am on hackerone.com)
but when i paste the url into sqlmap i get the error 

sqlmap -u https://twitter.com/login/error?username_or_email=failgecko9800&redirect_after_login=%2F --method=get --force-ssl --random-agent --threads=5 --current-user --passwords --risk=3 --level=5 --os-shell --os-pwn --os-smbrelay --os-bof --comments --users --roles --privileges --fingerprint --dbs
[6] 2917
bash: --method=get: command not found

and then it will say url is not stable i will press C and then it says this
bash: c: command not found

[6]+  Stopped                 sqlmap -u https://twitter.com/login/error?username_or_email=failgecko9800

can you please help me (the method is GET so i can not use the --data command)

Thanks

**Comment by stamparm** [comment]
You have a character `&` inside the URL which is a special character inside the bash ("go to background process"). You've run sqlmap along with illegal command after the character `&`. You should always enclose the parameters having `&` inside with quotes
