### ISSUE TITLE
sqlmapapi prot question

### ISSUE THREAD

**Issue by M7lrv** [sqlmapproject/sqlmap#2647]
I would like to ask, sqlmapapi if activated will open a port, if I think this port can only visit a ip, sqlmap can be set up?If the port has been scanned, it means that others can access and use.

**Comment by stamparm** [comment]
Yup. There is no authentication/authorization

**Comment by M7lrv** [comment]
If I want to set the need to modify the source code?Or whether you can update this question.

**Comment by stamparm** [comment]
Code is located at `lib/utils/api.py`. Feel free to customize it for your needs

**Comment by stamparm** [comment]
@M7lrv implementing basic authentication support this moment. Please wait a bit

**Comment by stamparm** [comment]
Added two new (optional) options `--username` and `--password`

![1](https://user-images.githubusercontent.com/921555/28967259-9fb76bfc-791a-11e7-889c-ba340b4abed7.png)
![2](https://user-images.githubusercontent.com/921555/28967260-9fba6154-791a-11e7-90af-eba57a29e2a1.png)
![3](https://user-images.githubusercontent.com/921555/28967261-9fbd1cb4-791a-11e7-970e-317930feb6b7.png)

**Comment by M7lrv** [comment]
Thank you very much, this problem solves the use of api security risks.

**Comment by M7lrv** [comment]
Set up the username, password, how to set up the request?
`D:\workspace\python_workspace\sqlmap-master>python sqlmapapi.py --username=root
--password=root -s
[20:05:17] [INFO] Running REST-JSON API server at '127.0.0.1:8775'..
[20:05:17] [INFO] Admin ID: 7ffea9b1990d06f7098b6a8d530cced6
[20:05:17] [DEBUG] IPC database: 'c:\users\admin\appdata\local\temp\sqlmapipc
-slmuwz'
[20:05:17] [DEBUG] REST-JSON API server connected to IPC database
[20:05:17] [DEBUG] Using adapter 'wsgiref' to run bottle
`

**Comment by stamparm** [comment]
`python sqlmapapi.py --username=root --password=root -c`

**Comment by M7lrv** [comment]
`D:\workspace\python_workspace\sqlmap-master>python sqlmapapi.py --username=root
--password=root -c
[20:28:50] [DEBUG] Example client access from command line:
        $ taskid=$(curl http://127.0.0.1:8775/task/new 2>1 | grep -o -I '[a-f0-9
]\{16\}') && echo $taskid
        $ curl -H "Content-Type: application/json" -X POST -d '{"url": "http://t
estphp.vulnweb.com/artists.php?artist=1"}' http://127.0.0.1:8775/scan/$taskid/st
art
        $ curl http://127.0.0.1:8775/scan/$taskid/data
        $ curl http://127.0.0.1:8775/scan/$taskid/log
[20:28:50] [INFO] Starting REST-JSON API client to 'http://127.0.0.1:8775'...
[20:28:50] [DEBUG] Calling http://127.0.0.1:8775
[20:28:51] [CRITICAL] There has been a problem while connecting to the REST-JSON
 API server at 'http://127.0.0.1:8775' (<urlopen error [Errno 10061] >)

D:\workspace\python_workspace\sqlmap-master>
`
As if there is an error

**Comment by stamparm** [comment]
I would say that:

1) Either your server is not being run while accessing it with client
or
2) Your machine is blocking access to localhost:8775

Tried this moment on my Windows 7 Virtual Machine and it works without any problems

![1](https://user-images.githubusercontent.com/921555/28968886-76f67af2-7922-11e7-8f00-8eae2c37431f.png)

**Comment by M7lrv** [comment]
I closed the firewall, but still have this problem, I look at the.

**Comment by stamparm** [comment]
How can I reproduce this? Also, I have a feeling that you have never run `sqlmapapi.py`, right?

**Comment by M7lrv** [comment]
Sqlmap I just downloaded, I was python2.7.3, python sqlmapapi.py-s can be directly activated, but added the username, password, -c that wrong.

**Comment by stamparm** [comment]
So, how to reproduce this? Step by step. I've tried on both Ubuntu 16.04 and Windows 7 and it works out of box

**Comment by M7lrv** [comment]
I started the api command is: python sqlmapapi.py --username = root --password = root-p 12345 -c

**Comment by stamparm** [comment]
Please copy paste both server and client commands. I can see that you've concatenated `--password` with `-p` option: `--password = root-p` and I am not sure why

**Comment by M7lrv** [comment]
All my orders
`D:\workspace\python_workspace\sqlmap-master>python sqlmapapi.py --username=root
--password=root -p 12345 -c
[20:41:44] [DEBUG] Example client access from command line:
        $ taskid=$(curl http://127.0.0.1:12345/task/new 2>1 | grep -o -I '[a-f0-
9]\{16\}') && echo $taskid
        $ curl -H "Content-Type: application/json" -X POST -d '{"url": "http://t
estphp.vulnweb.com/artists.php?artist=1"}' http://127.0.0.1:12345/scan/$taskid/s
tart
        $ curl http://127.0.0.1:12345/scan/$taskid/data
        $ curl http://127.0.0.1:12345/scan/$taskid/log
[20:41:44] [INFO] Starting REST-JSON API client to 'http://127.0.0.1:12345'...
[20:41:44] [DEBUG] Calling http://127.0.0.1:12345
[20:41:45] [CRITICAL] There has been a problem while connecting to the REST-JSON
 API server at 'http://127.0.0.1:12345' (<urlopen error [Errno 10061] >)

D:\workspace\python_workspace\sqlmap-master>python sqlmapapi.py -s
[20:43:26] [INFO] Running REST-JSON API server at '127.0.0.1:8775'..
[20:43:26] [INFO] Admin ID: 9a2e23a38d1adea97fda97326129d273
[20:43:26] [DEBUG] IPC database: 'c:\users\admini~1\appdata\local\temp\sqlmapipc
-sy_c5e'
[20:43:26] [DEBUG] REST-JSON API server connected to IPC database
[20:43:26] [DEBUG] Using adapter 'wsgiref' to run bottle

D:\workspace\python_workspace\sqlmap-master>python sqlmapapi.py --username=root
--password=root -p 12345 -c

`
I am also very curious about how this is going, if still not, I intend to change the computer to try

**Comment by stamparm** [comment]
So, basically, you are running client before running the server instance. I really don't have proper words to say

**Comment by M7lrv** [comment]
I'm sorry, it should be my question, sorry

**Comment by stamparm** [comment]
p.s. Also, I can see that you are running server instance without any options (like `-p`, `--username` and `--password` used in client instance)

**Comment by M7lrv** [comment]
Finally, I would like to ask, how is the authentication inside http?

**Comment by stamparm** [comment]
```
$ python sqlmapapi.py -h
Usage: sqlmapapi.py [options]

Options:
  -h, --help            show this help message and exit
  -s, --server          Act as a REST-JSON API server
  -c, --client          Act as a REST-JSON API client
  -H HOST, --host=HOST  Host of the REST-JSON API server (default "127.0.0.1")
  -p PORT, --port=PORT  Port of the the REST-JSON API server (default 8775)
  --adapter=ADAPTER     Server (bottle) adapter to use (default "wsgiref")
  --username=USERNAME   Basic authentication username (optional)
  --password=PASSWORD   Basic authentication password (optional)
```

**Comment by stamparm** [comment]
Notice ..**Basic authentication**..

**Comment by M7lrv** [comment]
http://127.0.0.1:8775/task/new?username=root&password=root ?

**Comment by Duanexiao** [comment]
@stamparm could you tell how to use the authentication in get/post method?

**Comment by M7lrv** [comment]
You can set the header,The best you look at the source code。`authentication:base64(username|password)`

**Comment by M7lrv** [comment]
@Duanexiao You can set the header,The best you look at the source code。authentication:base64(username|password)

**Comment by Duanexiao** [comment]
@M7lrv Thank you! I‘ve read the source code, set header is ok. I changed the api.py source code: get("/task/new/<apikey>"),then check if the apikey is legal.
