### ISSUE TITLE
suggestion about GUI

### ISSUE THREAD

**Issue by z3ro** [sqlmapproject/sqlmap#2650]
am one of sqlmap nation
like it, expert developers ..
but always there is missing ..
i wounder why not make gui sqlmap with live report 
and store sessions with dbs and tables ..
if not gui, to make a database to store each sessions in db file which in one click can retrieve what u want , which could help in future (2 - 3) years to get back where u ware. 

its a suggestion

**Comment by fiht** [comment]
Hackers never use GUI. :-D
Write GUI code is boring and could spend a lot of time.

**Comment by stamparm** [comment]
GUI is something that is currently not an option. It works perfectly from a command line and it will stay like that for some time. Until then, you can check projects like https://github.com/Hood3dRob1n/SQLMAP-Web-GUI (I haven't tried it, but based on stars, it seems that people like it on Github)
