### ISSUE TITLE
How to change the options? 【start > stop】【Reverse order】

### ISSUE THREAD

**Issue by wenre** [sqlmapproject/sqlmap#2653]
## What's the problem (or question)?
--start 10000 --stop 1  
**I want to store in reverse order...**
but does not seem to support?

## Do you have an idea for a solution?
no!
I do not know where the control point is in the source code.

## How can we reproduce the issue?
Do not need to reproduce.

## What are the running context details?
[options] start > stop

**Comment by wenre** [comment]
@stamparm

**Comment by stamparm** [comment]
`--start 1 --stop 10000 --where="ORDER BY <some_id_column> DESC"`

**Comment by stamparm** [comment]
Problem in (general) implementation is that lots of DBMSes don't have regular `LIMIT m, n` functionality, like in (e.g.) MySQL. Therefore, something called "pivoted dumping" is used where to reach the offset `m` you have to know the first `m` values (which is straightforward in sequential dumping order). In reverse order, like you want, would require reading of all those `m` values before so sqlmap would read those rows once more in backwards

**Comment by stamparm** [comment]
Done with latest revision, but consider it unstable (on non-MySQL DBMSes) because of already written reasons

**Comment by wenre** [comment]
thanks  you!
