### ISSUE TITLE
SQLMap Always Say Error Missing Mandatory

### ISSUE THREAD

**Issue by faxeface** [sqlmapproject/sqlmap#2657]
I have a problem with my sqlmap, i already install and i think the progress is success..
but, when i'm use sqlmap always say Error Missing Mandatory
I already add command: sqlmap.py -h
but error still appear
I hope u can help me please

![image](https://user-images.githubusercontent.com/31045313/29328941-87f54114-81f4-11e7-8807-b9d9b0d151d5.png)

i'm windows 10 user

**Comment by faxeface** [comment]
i want to open help with command -h
![image](https://user-images.githubusercontent.com/31045313/29329693-faed5e02-81f6-11e7-8021-7c2755182666.png)

that my target, to open help

**Comment by Ekultek** [comment]
Sqlmap.py --help or sqlmap.py -hh 

- Thomas Perkins

**Comment by stamparm** [comment]
In original Issue request screenshot there has been option `h` used without `-` (hence, invalid Issue request). In later screenshot I guess that user copy-pasted some unicode minus-alike character from web.

To deal with this issue, user should properly type in a minus character (`-`) before a `h` option. Closing this down as invalid
