### ISSUE TITLE
Maby this will be helpful to this project or not

### ISSUE THREAD

**Issue by heascle** [sqlmapproject/sqlmap#2658]
## Do you have an idea for a solution?

First,I want to ask one question. (and my english is poor,I'm sorry about this)
sqlmap's time-based sql injection use "binary search" to reflect the data and it need so much time,it is right?

Do you konw a technique to reflect the data in time-based injection,it's more fast~!Maybe you are already know...  .  According to my known, sqlmap seems havn't using this technique,at least this will work
well in mysql time-based injection,I know little about other db

Explain:
ascii   max value is 127  ,it's binary value is 111 1111, seven columns.
 bin(ascii(substr(version(),1,1)))  #turn the  db version's ascii value to binarys
 mid(lpad(bin(ascii(substr(version(),1,1))),7,0),1,1); #padding zero if need,get the first binary
 select if(0=mid(lpad(bin(ascii(substr(version(),1,1))),7,0),1,1),sleep(10),null); #..judge

And we can make it works with seven threads ,  each thread aim to one binary ...

Thank you for reading.

**Comment by stamparm** [comment]
You are Nth user that recommends this approach without knowing what sqlmap does in the first place. sqlmap already uses binary search, but with comparison greater-than operation. Please do a more research
