### ISSUE TITLE
[DEBUG] got HTTP error code: 500 (Internal Server Error)

### ISSUE THREAD

**Issue by dtsrwnis** [sqlmapproject/sqlmap#2662]
I can read database/tables/columns but i can't dump....

I get "[DEBUG] got HTTP error code: 500 (Internal Server Error)" when i "--dump" 

"[WARNING] the SQL query provided does not return any output"

Any help ?

**Comment by stamparm** [comment]
Use `-t traffic.txt` or `--proxy` to see what is going on. You should debug the traffic going in and out before raising this kind of issues
