### ISSUE TITLE
how can i bypass addslashes() funciotn?

### ISSUE THREAD

**Issue by LeetDemon** [sqlmapproject/sqlmap#2668]
Hi , i face site that use addslashes() function in php , so i put in the field this " 1%bf%5c' " and give me error like this : 
Error Number: 1366

Incorrect string value: '\xBF\'' for column 'last_name' at row 1

so how can i bypass this function using sqlmap ?

**Comment by LeetDemon** [comment]
?

**Comment by stamparm** [comment]
You should do a research and make a tamper script
