### ISSUE TITLE
DPI-1047: Oracle Client library cannot be loaded: libclntsh.so

### ISSUE THREAD

**Issue by FabioNevesRezende** [sqlmapproject/sqlmap#2677]
## What's the problem (or question)?
Error when running sqlmap

## Do you have an idea for a solution?
no

## How can we reproduce the issue?
Just running sqlmap, version 1.1.8-1 on blackarch (arch linux)

## What are the running context details?
- Installed using archlinux pacman which was run through blackarch script installation: - https://www.blackarch.org/downloads.html#install-repo
- Arch linux
[fabio@fabio-pc ~]$ sqlmap
Traceback (most recent call last):
  File "sqlmap.py", line 39, in <module>
    from lib.controller.controller import start
  File "/opt/sqlmap/lib/controller/controller.py", line 12, in <module>
    from lib.controller.action import action
  File "/opt/sqlmap/lib/controller/action.py", line 8, in <module>
    from lib.controller.handler import setHandler
  File "/opt/sqlmap/lib/controller/handler.py", line 32, in <module>
    from plugins.dbms.oracle.connector import Connector as OracleConn
  File "/opt/sqlmap/plugins/dbms/oracle/connector.py", line 9, in <module>
    import cx_Oracle
cx_Oracle.DatabaseError: DPI-1047: Oracle Client library cannot be loaded: libclntsh.so: cannot open shared object file: No such file or directory. See https://oracle.github.io/odpi/doc/installation.html for help

That's strange because never before I had to have oracle installed in order to run sqlmap

**Comment by stamparm** [comment]
@FabioNevesRezende `cx_Oracle` seems to be installed, though, in non-valid state. Nevertheless, find sqlmap "patched" with the latest revision

**Comment by ChrisFernandez** [comment]
I have the same issue

**Comment by stamparm** [comment]
@ChrisFernandez with latest HEAD revision. I don't think so

**Comment by maxcr** [comment]
Also having this issue.

**Comment by stamparm** [comment]
Oracle Client library should be installed (as per message) manually

**Comment by stamparm** [comment]
Also, as `cx_Oracle` installation is messed up altogether, most probably you'll need to install: `sudo apt-get install libaio1 libaio-dev`

**Comment by cikavladimir** [comment]
libaio1 and libaio-dev is not enough - needs libclntsh.so at least more..

**Comment by stamparm** [comment]
`cx_Oracle` installation instructions can be found at https://cx-oracle.readthedocs.io/en/latest/installation.html

**Comment by gnubyte** [comment]
This is still an issue and is not fixed. 
`pip install cx_oracle` 
when this doesn't do anything

That means that the package is broken IMO and the readTheDocs is not covering the solution at this time. Can we please continue to investigate?

**Comment by stamparm** [comment]
@gnubyte can you please describe what is going on in your place?
