### ISSUE TITLE
How to ignore 401 response

### ISSUE THREAD

**Issue by shadowfolder** [sqlmapproject/sqlmap#2681]
Hello there! I have injection in page with 401 response, but i can't process it. I've tried --code=401 but with no luck. I'm still getting 
[21:31:04] [INFO] testing connection to the target URL
[21:31:06] [CRITICAL] not authorized, try to provide right HTTP authentication type and valid credentials (401)
[21:31:06] [WARNING] HTTP error codes detected during run:
401 (Unauthorized) - 1 times
I don't need to add creds, i just need to process request with 401 response.

**Comment by shadowfolder** [comment]
Damnit! :D I've figure it out: --ignore-code=401

**Comment by P1kAju** [comment]
> 该死的！：D我弄清楚了---ignore-code = 401

啥问题啊？ 状态401 可能是开发自己搞得。。

**Comment by 687766616e** [comment]
> > 该死的！：D我弄清楚了---ignore-code = 401
> 
> 啥问题啊？ 状态401 可能是开发自己搞得。。

chi...Chinese.......😮

**Comment by Haxel0rd** [comment]
For me it was --ignore-401 
Syntax: --ignore-<http_response_code_here>

**Comment by stamparm** [comment]
@Haxel0rd in recent versions (for more than a year), that switch is replaced with `--ignore-code`
