### ISSUE TITLE
Randomize don't working with JSON

### ISSUE THREAD

**Issue by shadowfolder** [sqlmapproject/sqlmap#2682]
POST /ui/auth/login?_spring_security_remember_me=false HTTP/1.1
Content-Length: 58
Host: localhost
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3
Request-Agent: artifactoryUI
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0
Connection: close
Cookie: 
serial: 37
Content-Type: application/json

{"user":"user1","password":"test123","type":"login"}

my request is:
sqlmap.py -r req.txt -v 3 --level 3 --risk 2 --force-ssl --ignore-code=401  --randomize="user"

but user always is "user1" so --randomize parameter doesnt work with json

**Comment by huitc** [comment]
--randomize don't working? @stamparm

**Comment by huitc** [comment]
@stamparm sorry, it's working, but you can't see the different by using `-v 3`。。。
