### ISSUE TITLE
A small problem, Coding problem

### ISSUE THREAD

**Issue by M7lrv** [sqlmapproject/sqlmap#2683]
When I os-shell, in China, the default code is gb2312 or GBK, I in your file "lib \ core \ convert.py" which found hexencode this method, the default parameters are UTF-8, in China Chinese characters on the path becomes garbled, the default encoding of the server GBK, os-shell can not be used. In general, the Chinese language coding is a bit small problem, the best os-shell can be set hex encoding.I can only modify the code to avoid this problem, I think you can add a parameter, for example: "- os-shell-hexencoding = utf-8"

**Comment by stamparm** [comment]
With latest revision you can just use `--charset=gbk` in those kind of cases

**Comment by M7lrv** [comment]
Thank you very much for your updates.
