### ISSUE TITLE
Time-based inject failed in 1.1.9, but works at 1.1.8

### ISSUE THREAD

**Issue by aploium** [sqlmapproject/sqlmap#2693]
## What's the problem (or question)?
for the following command, it works normally at 1.1.8, but fails in 1.1.9

```bash
sqlmap -u "http://testphp.vulnweb.com/artists.php?artist=1" --tech T --flush-session --batch
```

## Do you have an idea for a solution?
in 1.1.9, it completely skip the time-based Injection test, which may due to some bugs in dbms version detecting.
if we force the backend dbms, it can works normally
```bash
sqlmap -u "http://testphp.vulnweb.com/artists.php?artist=1" --technique=T --flush-session --dbms mysql
```

after increase verbose, I found it just skipped the time-based inject(1.1.9):
```
[10:11:19] [DEBUG] skipping test 'MySQL AND time-based blind (ELT)' because it is different than provided
```

## How can we reproduce the issue?
1. `pip install sqlmap==1.1.9`
2. `sqlmap -u "http://testphp.vulnweb.com/artists.php?artist=1" --tech T --flush-session --batch` (fails)
3. `pip install sqlmap==1.1.8`
3. `sqlmap -u "http://testphp.vulnweb.com/artists.php?artist=1" --tech T --flush-session --batch` (success)

## What are the running context details?

* Installation method:  pip
* Client OS: reproduced in Ubuntu16.04, MacOSX, CentOS 6.9, it may be OS-independent
* Program version: 1.1.9#pip
* Target DBMS  MySQL
* Detected WAF/IDS/IPS protection: No
* Results of manual target assessment:  `boolean-based`, `AND/OR time-based` `UNION query`
* Relevant console output (if any):
```
[10:11:19] [DEBUG] skipping test 'MySQL AND time-based blind (ELT)' because it is different than provided
```

**Comment by stamparm** [comment]
@aploium thank you for your report. At first I was skeptical :). Pushed patch to master (will be part of `1.1.10#pip`)
