### ISSUE TITLE
DBMS Type not supported (please add)

### ISSUE THREAD

**Issue by FailGecko9800** [sqlmapproject/sqlmap#2698]
hi how are you, i hope you are well

i was just wondering, if you could add more supported database types, because there are some database types that sqlmap does not support

they are:
FlockDB
Memcached
Cassandra
Gizzard
Apache Lucene
HBase and Hadoop
Redis

it would be great if you could add these databases in. Because i am doing some SQL work for Twitter but the Back-end DBMS is not supported, so please have a think about it. :)

i am thanking you profusely, and would absolutely love it if you could

Thanks Again

Your pal, FailGecko
 #https://twitter.com/failgecko9800

**Comment by stamparm** [comment]
FlockDB - Deprecated code at least (https://github.com/twitter-archive/flockdb - last update 6 years ago)
Memcached - not a DBMS
Apache Lucene - ???. sqlmap is a DBMS/SQL centric tool, not any kind of storage support
...
