### ISSUE TITLE
No Input file specified

### ISSUE THREAD

**Issue by emilyanncr** [sqlmapproject/sqlmap#2703]
My target has the following setup:

ASP.net IIS 6, ASP
Windows Server 2003 Standard x64 Edition
OS Version: 5.2.3790 Service Pack 2 Build 3790

I am dba and able to call an os-shell, however am unable to use --os-pwn. Even though I granted my user F permissions under the C:\Program Files\Microsoft SQL Server folder, I get a message that the mount was unsuccessful likely because I do not have write access to the specified folder.
I used icacls to grant myself full read and write access to the C:\Inetpub\wwwroot folder and successfully used --file-write to write an upload script that would be accessible from the web.  When I browsed to the file however, I got a message 'no input file was specified'.  I'm assuming this is why I'm not able to use --os-pwn.  I did a ton of research and learned this was an issue common to IIS 6 and php.  The solution said to comment out a line in the php.ini file like so:
; doc_root = "C:\Inetpub\wwwroot"
Using sqlmap's --file-read command, I read the targets php.ini file onto my computer and verified this line was, in fact, not commented.  I deleted the php.ini file on the target and replaced it with the edited copy of php.ini.

Even after alllll that, I still get the message 'no input file specified'. AHHHH!

Alternatively, rather than writing the file to the MSSQL folder, can I write the payload to somewhere else, like C:\Windows\temp?  I know for sure I can write there.  But then I obviously wouldn't be able to access it from the browser so how would that work?

I refuse to believe I'm the only one to have run into this issue with regards to the 'no input file specified' message when compromising the same type of system, but can't find anything online that talks about it from a perspective of hacking.  Thank anyone who's able to provide me with advice.  I'm about to take a gun to my head.

I'm using sqlmap 1.1.9#stable
on Kali Linux OS

**Comment by Ekultek** [comment]
This might help you https://bugs.php.net/bug.php?id=48776

**Comment by emilyanncr** [comment]
Thank you so much for taking the time to help.  Those instructions tell me to comment out open_redir line but it's already commented out on the php.ini file I uploaded.  Sigh.  I really don't understand why I can't get some type of shell using metasploit.  If I can get an os shell with sqlmap, why not msf? It makes no sense to me.

**Comment by stamparm** [comment]
sqlmap's `--os-shell` is totally different from msf's `--os-pwn`. For `--os-shell` you just have to be able to upload a (e.g.) PHP shell and execute it. For `--os-pwn` you have to have `--os-shell` ability together with ability for an executable (which must not be blocked by the AV at the other side) to connect back to your machine. I can think of couple of reasons why this could fail.
