### ISSUE TITLE
[Resolved] How to inject a parameter like: "user@email.com[INJECT]"?

### ISSUE THREAD

**Issue by reillychase** [sqlmapproject/sqlmap#2705]
How can I inject a parameter which has some server side validation, for example, an email address.

If I send user@email.com' the vulnerable app returns an SQL error. However if I just send ' as the email address it returns a message saying the email address is invalid. How can I get SQLmap to inject with the email address before the injection

**Comment by reillychase** [comment]
Watched sqlmap's requests with burpsuite and saw that the default behavior is to inject after the argument supplied to the parameter, so it should be working

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/Usage#arbitrary-injection-point

**Comment by reillychase** [comment]
Thanks!
