### ISSUE TITLE
registration form

### ISSUE THREAD

**Issue by maro2017** [sqlmapproject/sqlmap#2706]
i have encountered a new injection entry in registration form 
when i submit a payload in each parameter alone i receive no error 
but when i submit  the payload in all of the parameter i receive the error message 
"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '..a.'' at line 1"
the payload used " '''''''''''''''''''''''''''''''''''''''''''''''..a. "  
i tried this command in sqlmap 
" sqlmap -u www.example.com  --level=5 --risk=3 --random-agent --dbms=MySQL --forms  -v3 --dbs "
but sqlmap couldn't identify anything  
what should i do in that case ?

**Comment by stamparm** [comment]
It is possible that you have SQL injection, but unusable. You should try to find a working SQL payload inside one of parameters to know what to do with the sqlmap. Blind observations won't help here. Also, as said, this could be unusable.
