### ISSUE TITLE
Blind-based charset dump

### ISSUE THREAD

**Issue by Annihilat0r** [sqlmapproject/sqlmap#2709]
Time-based dump algorithm is pretty good now. But for dumping on a sha-1 hash it takes 600 sec for me. Is it possible to add custom charset for dumping? For example `--custom-charset='1234567890abcdef'`. This will be useful also for duping integer values.

**Comment by stamparm** [comment]
Initial support done:

```
$ python sqlmap.py -hh | grep charset
    --charset=CHARSET   Blind SQL injection charset (e.g. "0123456789abcdef")
```

More work to be done (to make less requests)

**Comment by stamparm** [comment]
A) Regular run (**242 queries**): `$ python sqlmap.py -u "..." --sql-query="SELECT '3858f62230ac3c915f300c664312c63f'" -v 3`

![1](https://user-images.githubusercontent.com/921555/30802038-8921f7f6-a1e5-11e7-9f98-ab3372d65355.png)

B) Using `--charset` feature (**168 queries**): `$ python sqlmap.py -u "..." --sql-query="SELECT '3858f62230ac3c915f300c664312c63f'" --charset="0123456789abcdef" -v 3`

![2](https://user-images.githubusercontent.com/921555/30802137-cdd96c8a-a1e5-11e7-8041-389ebca4c357.png)

30% less queries :)
