### ISSUE TITLE
python library usage

### ISSUE THREAD

**Issue by javixeneize** [sqlmapproject/sqlmap#2710]
Hi

I have seen there is a python sqlmap library that can be installed with pip

Is there any documentation around on how to use this library? There is plenty of info about the CLI but i have not found anything about the python library

Thanks

**Comment by stamparm** [comment]
For starter, you haven't stated which "library" it is available via pip.

```
$ pip search sqlmap
sqlmap (1.1.9)    - Automatic SQL injection and database takeover tool
sqlmapcli (0.10)  - Simplify your operations for sqlmapapi
$
```

`sqlmap` is official package of sqlmap, coming from us on monthly basis
`sqlmapcli` doesn't have anything to do with us. As I can see from bad written code, it is just a rip off of official `sqlmapapi.py` (part of sqlmap in the first place)
