### ISSUE TITLE
Sqlmap type always default Single quoted string

### ISSUE THREAD

**Issue by OTEx911** [sqlmapproject/sqlmap#2712]
I tried much as I can, but the result is still like the following pic.
I have tried download the latest version, but it didn't work.
I have tried --flush-session, but failed. Who can tell me what happened here?
![image](https://user-images.githubusercontent.com/27736585/30727435-c884a0f6-9f83-11e7-96a9-f8a2f5fed898.png)
![image](https://user-images.githubusercontent.com/27736585/30727491-194844de-9f84-11e7-8e69-6eb7da36f94b.png)

**Comment by stamparm** [comment]
Have you been asked whether you want to test for all parameters, no matter if single POST parameter has been found to be injectable? You answered yes. Now, I don't see what's the issue then?

**Comment by stamparm** [comment]
So, you are worried that it is a single-quoted string SQLi, while in your case there has to be a single quote to make it successful. Closing this down as you need to catch some fundamentals of SQLi
