### ISSUE TITLE
Usage of pip package

### ISSUE THREAD

**Issue by javixeneize** [sqlmapproject/sqlmap#2714]
Hi

If you close the issues, i don't have any chance to answer on that

My question is... Using the pip package, what would be the equivalent to -u option?

 -u URL, --url=URL   Target URL (e.g. "http://www.site.com/vuln.php?id=1")

In the python package there is no option, url, or similar method

I just need to know how a basic python sqlmap.py -u "http://www.target.com/vuln.php" would be using the pip package

Thanks

**Comment by stamparm** [comment]
Please don't open new issues. Will close all further as invalid. You have been asked in opening issue template to provide any information on issue itself. Now I am learning from third issue that you want to run pip package called sqlmap (not library) and that you don't know how to run it.

pip install sqlmap
sqlmap -u ....
