### ISSUE TITLE
Use of pip package

### ISSUE THREAD

**Issue by javixeneize** [sqlmapproject/sqlmap#2715]
## What's the problem (or question)?
How to use in a python program the imported sqlmap package

## Do you have an idea for a solution?
No

## How can we reproduce the issue?
In the python code i have

from sqlmap import sqlmap

Now, which method should i call to start using sqlmap and send the relevant options? Eg: sqlmap.url('url.to.attack')

Thanks

**Comment by stamparm** [comment]
You have been warned in #2714

**Comment by javixeneize** [comment]
This is not about warning, this is about support.

Is this how you support people and how you take recommendations? There is no information about how to use the pip library and it only takes 10 seconds to write an example

Good tool but the support is horrible

**Comment by stamparm** [comment]
It takes a minute to write a good Issue request, but you were too lazy. Without a good triage of Issues there would be a bunch of requests like yours which would require a full time job just to ask users what seems to be a problem in an endless thread.

Please, don't even run a tool because of your dislike, as my primary function is not the support. Just go to git commit statistics.

Also, in future don't be lazy on other projects like you've been here.

**Comment by javixeneize** [comment]
I get your point that you probably receive hundreds of requests from scriptkiddies asking how to hack a page etc... But this is not the case

We have started really bad, but lets go to the good path.

I am trying to build something in python that calls internally several tools automatically. One of them is sqlmap

The best way for me to do it is importing the sqlmap package (from sqmap import sqlmap)

My problem is that i have not found any information about how to use this package. 

I have tried to call some methods but i cant see any method that seems to run a sqlmap scanner (the most basic thing, sqlmap -u url)

I think that creating a small doc for this should be useful (see wfuzz doc here -- http://wfuzz.readthedocs.io/en/latest/library/guide.html#fuzzing-a-url)

So, how should i nicely ask for support to know which method in the pip package runs what

Hvala!

**Comment by Ekultek** [comment]
Use the API, it would be the easiest way to use sqlmap within another tool.

- Thomas Perkins

**Comment by stamparm** [comment]
@javixeneize currently you can import `sqlmap` as a module (not intended to be used in such way), though, there is no way how to communicate with it. I could implement for example a push-options and run feature, but there is no way how to further extract and/or communicate with the program itself. Thus, as @Ekultek mentioned, you should use API (https://github.com/sqlmapproject/sqlmap/wiki/Usage#api-rest-json)

**Comment by javixeneize** [comment]
Ok. It makes more sense now. I will try the api

Thanks for the help!
