### ISSUE TITLE
Support for using PROCEDURE ANALYSE (EXTRACTVALUE) on Url ?  

### ISSUE THREAD

**Issue by Hanik0v** [sqlmapproject/sqlmap#2716]
## I've been looking into this one URL and I know that a PROCEDURE ANALYSE (EXTRACTVALUE) based injection at least gets me results when done manually, but I was wondering why sqlmap never does it on URLs 
that's the payload that i used to get result :

**(host)\vuln.php?id=0,1 procedure analyse(extractvalue(0,concat(0x27,version())),1)-- -**

**Comment by stamparm** [comment]
Neither you have filled the Issue request in a valid manner, neither you have added any useful information here, neither you have stated which SQLi is it (time-based or error-based), neither you've written how you debugged the problem (if you have done any kind of work here to find out what is going on)
