### ISSUE TITLE
BETWEEN tamper script issue

### ISSUE THREAD

**Issue by SecurityAddicted** [sqlmapproject/sqlmap#2719]
I just had a problem with the BETWEEN tamper script. It seems to create invalid SQL when substituting the '=' character:

`1 AND 5195 BETWEEN IF AND IF((ORD(MID((IFNULL(CAST(VERSION() AS CHAR),0x20)),1,1))!=53),SLEEP(7),5195)`

Clearly "BETWEEN IF AND" is invalid, if I change the IF with a number the query works as expected.
Database: MySQL

**Comment by stamparm** [comment]
@SecurityAddicted are you using latest revision as there have been changes in `between` script lately? Also, I am trying to reproduce with `--banner --tamper=between` but without luck

**Comment by SecurityAddicted** [comment]
Yes I'm using the latest revision. I used Burp to debug the problem. POST request.
At the moment I removed the last lines from the script as I need only to tamper the '>' character and it's working flawlessly (dumping stuff at the minute... thanks for the amazing software ;) )
