### ISSUE TITLE
Help create a new tamper

### ISSUE THREAD

**Issue by mobius07** [sqlmapproject/sqlmap#2720]
![1](https://user-images.githubusercontent.com/20757829/30808080-cab69744-a226-11e7-85ab-a96952f371cb.jpg)
Hello. I want to create a new tamper that replaces the "%" character with another. The code was copied from apostrophenullencode.py. 

`#!/usr/bin/env python`

`from lib.core.enums import PRIORITY`

`__priority__ = PRIORITY.LOWEST`

`def dependencies():`
`    pass`

`def tamper(payload, **kwargs):`
`    return payload.replace('%', "\45") if payload else payload`

But why is it not possible - displays:

`[18:58:13] [PAYLOAD] verify_account%' AND 2061=4628 AND '%'='`
`[18:58:14] [DEBUG] got HTTP error code: 400 (Bad Request)`

Although on the idea instead of the sign "%" should be "\45".
The problem in the priority of `__priority__ = PRIORITY.LOWEST` may be, since I need that already at the end of all the transformations and substitutions, before sending the request to the server, tamper searched for the payload sign "%" and replaced it. Thank you

**Comment by mobius07** [comment]
Another addition.
I create the procent.py file with this code and throw it into the /tampers/ directory and call it --tamper=procent. Yet am I doing the right thing? Or this file is needed somewhere else in configurations to prescribe?

**Comment by stamparm** [comment]
1) `.replace('%', "\45")` doesn't make any sense as `"\45"` is just another way how to write `'%'`:
```
$ python
>>> print '%' == "\45"
True
```

2) You can call tamper with absolute filepath too (e.g. `--tamper=/tmp/procent.py`). Just make sure to put empty `__init__.py` in same directory
