### ISSUE TITLE
About speed with multithreads

### ISSUE THREAD

**Issue by shadowfolder** [sqlmapproject/sqlmap#2721]
Hi! 😺 
I'm dumping a huge database (300k records).
I'm trying with --threads=20! and --threads=100! But dump speed is the same with 20 and 100 threads. :(
I have i7 and 64GB ram, so my system can handle with this.
P.S. Target can recieve full 100mbps requests in once and respnse them all without lagging or errors.

**Comment by stamparm** [comment]
And why do you think there is a hard cap (you modified) to 10 threads. You can't expect N speed up if you run N threads. Basics of computer science. Server is over stressed and can't run 1000 queries in a same time

**Comment by shadowfolder** [comment]
Targer server can run 20 000 queries(get or post) in same time. :) I've tested it by myself. So is there a tips, how i can modify sqlmap script to run on high threads(100-200)?

**Comment by stamparm** [comment]
You've obviously already changed `MAX_NUMBER_OF_THREADS` to more than 10. If you can't get speed-up like that, than I am pretty sure that it is not sqlmap's fault. There is nothing to discuss here.

**Comment by stamparm** [comment]
Just two things to show that this discussion doesn't have solid grounds:

1) "I have i7 and 64GB ram, so my system can handle with this"
2) "Targer server can run 20 000 queries(get or post) in same time"

I can't discuss if your best claims are these
