### ISSUE TITLE
403 FORBIDDEN and false positive

### ISSUE THREAD

**Issue by FailGecko9800** [sqlmapproject/sqlmap#2722]
hi how are you, quick question...

what tamper scripts do i use to bypass the error 403 forbidden, if there are no tamper scripts that could do that. Do you think that you could make a feature to try and bypass WAF/403 http error code

also sometimes SQLMap won't detect the false positive for injection, then when it gives me the DBMS it says "Unable to retrieve the number of databases" and names of databases as well

for example i would do "sqlmap -u www.site.com/?parameter=1 --random-agent --threads=5 --risk=3 --level=5 --invalid-string --invalid-logical --invalid-bignum --tamper=between,informationschemacomment,charencode,bluecoat --force-ssl -v2 --parse-errors --current-db --dbs"
it will do the injection but the injection is a false positive and SQLMap does not pick it up as a false positive (i can tell its a false positive because when doing SQL Injection for Twitter it said the DBMS is oracle, Twitter don't use oracle)

Thanks for your help, i love SQLMap
if you want you can add me on skype my skype is "FailGecko9800"
Thanks again

**Comment by stamparm** [comment]
It is your job to inspect if there is a way to bypass the WAF. Use Burp amd try to manually inject. Once done, use appropriate tamper script. Forbidden is a generic way how to block your requests
