### ISSUE TITLE
Problems with keys inside JSON array

### ISSUE THREAD

**Issue by Costly** [sqlmapproject/sqlmap#2723]
Hey, 

I've got some problems specifying a JSON key with the -p option.

I have a JSON array inside my POST body which looks like this one:

{
  "id": 1,
  "aaa": "xxx",
  "bbb": "yyy",
  "ccc": "52",
  "ddd": null,
  "eee": false,
  "fff": {
    "id": 2,
    "name": "Standard"
  },
  "ggg": {
    "id": 1,
    "name": "xxxyyy"
  },
  "hhh": {
    "id": 3,
    "name": "yxyxyx"
  }
}

When i specify "-p id" It always scans the "deepest"/"latest" id, which is inside "hhh". Is there a way to tell sqlmap that it should take the very first "id" in the very first layer or the second one in the "ggg" layer?

I know i can workaround this problem with a requestfile and a *, but it think this scenario isn't that uncommon that it shouldn't be covered by the -r option.

Maybe something like -p id[0], id[1] ?

Regards

**Comment by stamparm** [comment]
Well, that feature wouldn't be noticed or used (IMO). As you noticed, in case like yours, you can always use custom injection marker `*`.
