### ISSUE TITLE
how can i perform insert query on DB  with --sql-shell ? Stacked queries aren't supported in  PHP+MySQL.

### ISSUE THREAD

**Issue by Tejpandya** [sqlmapproject/sqlmap#2726]
I am exploring a vulnerability in one PHP website that is basically riddled with SQL injections. I managed to dump all the tables and get some basic information (username, DB name, hostname). My goal is to modify data in a specific table.

 I have tried SQLmap's --sql-shell , but I found out I cannot do anything beyond SELECT because PHP+MySQL combination disallows stacked queries. Moreover i've got no luck with LOADFILE/INTO OUTFILE. 

So i can't upload a shell and also cant have a sql shell.

I am not a DBA on this host.  How to resolve this problem with SQLmap . Is there any way around provided by SQLMAP tool to dealt with this ?

**Comment by stamparm** [comment]
Simple, if there is no stacking you won't be able to modify data
