### ISSUE TITLE
Tamper script usage

### ISSUE THREAD

**Issue by MrShhh** [sqlmapproject/sqlmap#2729]
## What's the problem (or question)?

I'm in the process to understand which tamper script to use. So, I look through the content of the script. 
For example commalesslimit.py:

"""
    Replaces instances like 'LIMIT M, N' with 'LIMIT N OFFSET M'

    Requirement:
        * MySQL

    Tested against:
        * MySQL 5.0 and 5.5

    >>> tamper('LIMIT 2, 3')
    'LIMIT 3 OFFSET 2'
    """

The definition of requirement above means that this script can ONLY be used if the targeted website use MySQL as DBMS?

**Comment by stamparm** [comment]
Because MySQL is the only one that has `LIMIT m,n` syntax which can be transposed to `LIMIT m OFFSET n`. No other DBMS can do that
