### ISSUE TITLE
Using sqlmap without interaction (seamless)

### ISSUE THREAD

**Issue by javixeneize** [sqlmapproject/sqlmap#2736]
Hi

I want to use sqlmap in a totally automated way, without any customer interaction.  I have sent as parameter the values of risk, and level. I have also sent the --all option, but, however when it finds a vulnerable parameter it keeps doing questions

for the remaining tests, do you want to include all tests for 'MySQL' extending provided level (1) and risk (1) values? [Y/n]

Is there any way to skip completely this? I just want it to write in the log if the app is vulnerable to SQLi and thats all

Thanks

**Comment by stamparm** [comment]
--batch

**Comment by javixeneize** [comment]
Thank you!
