### ISSUE TITLE
port 80 is blocked.  

### ISSUE THREAD

**Issue by TheHmadQureshi** [sqlmapproject/sqlmap#2739]
Hi, I am trying to run sqlmap against a web application, which has blocked port 80. Only 443 is opened. plus there's no redirect from HTTP to HTTPS. The request is going over POST method with json body. When i try to run sqlmap, it shows the attached error. 
![sqlmap](https://user-images.githubusercontent.com/9057459/31387915-a0fc5824-ade5-11e7-916f-cc92a7164c26.JPG)

My understanding is, i have given sqlmap just the file which includes HTTP request, which sqlmap does not know to send over HTTPS. Here's the sample request:

~~~
POST /Some-file HTTP/1.1
Host: test.com
User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Referer: 
Content-Length: 20
Cookie: ; JSESSIONID=
Connection: close

{"POST-DATA"}

~~~

sqlmap tries to target test.com over HTTP which is blocked plus no redirect.How do i make sqlmap to attack test.com over HTTPS?

**Comment by stamparm** [comment]
```
...
Host: test.com:443
...
```
or
```
...
Host: https://test.com
...
```

**Comment by TheHmadQureshi** [comment]
didn't work. however --force-ssl did work. Thank you for your time.
