### ISSUE TITLE
sqlmap oracle dump returns in a strange encoding

### ISSUE THREAD

**Issue by Kichee** [sqlmapproject/sqlmap#2740]
Hello.

I have a website with Oracle database vulnerable to injection attack. The strange thing is - each time I try to dump or enumerate it, I recive strange encoding answer.

When I executing --banner flag i receive:

`sqlmap resumed the following injection point(s) from stored session:`
`Parameter: N (GET)`
`    Type: boolean-based blind`
`    Title: AND boolean-based blind - WHERE or HAVING clause`
`    Payload: N=%' AND 2835=2835 AND '%'='&some=Some`

`[23:12:34] [INFO] the back-end DBMS is Oracle`
`[23:12:34] [INFO] fetching banner`
`[23:12:34] [INFO] resumed: \x1c65`
`web application technology: Nginx`
`back-end DBMS: Oracle`
`banner:    '65'`

And all the data i get from --tables or any other output flag seems to look the same:
`[12:06:30] [INFO] resumed: .I;yԨ\x18MI~Ԩ\n<mt`

My sqlmap execution is:
`python sqlmap.py -u "https://someurl.web/?N=2&some=Some" --random-agent --banner`

**Comment by stamparm** [comment]
False positive. Please rerun with `--flush-session`
