### ISSUE TITLE
Threads not working properly in data Retrieval 

### ISSUE THREAD

**Issue by gu4rdi4n** [sqlmapproject/sqlmap#2743]
Hi 
i set threads from 10 to 100 i use 75 threads in Bsqli OR boolean-based blind . 
They are not working even i use 1 thread or 50 it is giving data in same speed with same ms i am analyzing with -v 5 as it is giving data in same speed with same time frame. it need to give data faster than 1 thread but i am getting same results as in 1 thread while it is working in union and error based.
Please confirm me if need modifying some other files except "lib/core/settings.py"

**Comment by stamparm** [comment]
Well, why you haven't tried 1000000 threads? Maybe it could work.

I am going to close this kind of issues in speed of light in future. Scaling doesn't work the way you expect. There is a reason why I've put a hard cap to 10 in the first place. Network layer, target's database, target's HTTP server, etc.
