### ISSUE TITLE
Specify a test on a target using --technique and maybe another parameter ?

### ISSUE THREAD

**Issue by iwantaturboman** [sqlmapproject/sqlmap#2745]
## What's the problem (or question)?
I would like to test a known vulnerability on a website but using the less queries as possible. Today we are able to tell sqlmap to concentrate an attack by specifying some parameters like  `--dbms`, `--level` and `--risk`. But, can we go further ?

## Do you have an idea for a solution?
The best for me it's avoid such synthax : 
`sqlmap.py -r target.txt -p email --current-db --risk=3 --level=5`
If i have some infos concerning the target : 
- the back-end dbms is mysql
- the vulnerability is a time-based blind
- email parameter is vulnerable via a query SLEEP

Can i avoid all these tests **except the one mentioned in bold caracters** ?
```
testing 'MySQL >= 5.0.12 AND time-based blind (comment)'
testing 'MySQL >= 5.0.12 AND time-based blind (query SLEEP)'
testing 'MySQL >= 5.0.12 AND time-based blind (query SLEEP - comment)'
testing 'MySQL >= 5.0.12 RLIKE time-based blind'
testing 'MySQL >= 5.0.12 RLIKE time-based blind (comment)'
```
=> **testing 'MySQL >= 5.0.12 RLIKE time-based blind (query SLEEP)**'
```
testing 'MySQL >= 5.0.12 RLIKE time-based blind (query SLEEP - comment)'
testing 'MySQL AND time-based blind (ELT)'
testing 'MySQL AND time-based blind (ELT - comment)'
testing 'PostgreSQL > 8.1 AND time-based blind'
testing 'PostgreSQL > 8.1 AND time-based blind (comment)'
testing 'Microsoft SQL Server/Sybase time-based blind (IF)'
testing 'Microsoft SQL Server/Sybase time-based blind (IF - comment)'
testing 'Oracle AND time-based blind'
testing 'Oracle AND time-based blind (comment)'
testing 'MySQL >= 5.0.12 time-based blind - Parameter replace'
testing 'MySQL >= 5.0.12 time-based blind - Parameter replace (substraction)'
testing 'MySQL time-based blind - Parameter replace (bool)'
testing 'MySQL time-based blind - Parameter replace (ELT)'
testing 'MySQL time-based blind - Parameter replace (MAKE_SET)'
testing 'PostgreSQL > 8.1 time-based blind - Parameter replace'
testing 'Oracle time-based blind - Parameter replace (DBMS_LOCK.SLEEP)'
testing 'Oracle time-based blind - Parameter replace (DBMS_PIPE.RECEIVE_MESSAGE)'
testing 'MySQL >= 5.0.12 time-based blind - ORDER BY, GROUP BY clause'
testing 'PostgreSQL > 8.1 time-based blind - ORDER BY, GROUP BY clause'
testing 'Oracle time-based blind - ORDER BY, GROUP BY clause (DBMS_LOCK.SLEEP)'
testing 'Oracle time-based blind - ORDER BY, GROUP BY clause (DBMS_PIPE.RECEIVE_MESSAGE)'
```
## A possible command line with a new parameter ?
`sqlmap.py -r target.txt -p email --dbms=mysql --technique=T --test="query SLEEP"`

Maybe i'm wrong ?

**Comment by stamparm** [comment]
This is already in for LONG time (option `--test-filter`):

```
$ python sqlmap.py -hh | grep test-filter
    --test-filter=TE..  Select tests by payloads and/or titles (e.g. ROW)
```

More info at: https://github.com/sqlmapproject/sqlmap/wiki/Usage#select-or-skip-tests-by-payloads-andor-titles

**Comment by iwantaturboman** [comment]
Oh, sorry mate. Thanks again.
