### ISSUE TITLE
Change output name?

### ISSUE THREAD

**Issue by javixeneize** [sqlmapproject/sqlmap#2748]
Hi

I am sending the parameter --output-dir to store this in a folder i have selected, but, inside that folder it creates a folder with the domain of the request, and files (target, log etc...)

I would like to store the log file directly in the folder i have created, and also rename it as i want (eg logtest1, logtest2 etc..)

Can this be done?

Thanks

**Comment by stamparm** [comment]
Output directory contains many different files (logs, dumped table content, session file, dumped file content, etc.). Log file is just one of many. Hence, creating one option (for log file) would require N new options (for all output files), which is not something I am keen on

**Comment by javixeneize** [comment]
Makes sense

Let me repeat this in a different way... as part of an automated scan, i want to know if sqlmap has detected anything. The way i am using to check it is check if the log file has been created

Is there any flag that sqlmap can return for this?

**Comment by stamparm** [comment]
Log file is created even if there was no SQLi. It is empty, but it is there. Also, simple searching of "sqlmap identified" inside a file should suffice, so, I am not sure why you want to complicate

**Comment by javixeneize** [comment]
Its not as easy as that :) Let me explain

I am running a batch of sqlmap tests automatically based on some urls i have.
