### ISSUE TITLE
help me solve Sqlmap.py error

### ISSUE THREAD

**Issue by SyamelDmz** [sqlmapproject/sqlmap#2754]
hey guys,

i'm using sqlmap on win 10 with python2.7 .. before this there is no problem with my sqlmap when run 
"sqlmap.py -u http://testsite.com --dbs" . now i have a problem when i want to run the command, this message appear "sqlmap.py: error: missing a mandatory option (-d, -u, -l, -m, -r, -g, -c, -x, --wizard, --update, --purge-output or --dependencies), use -h for basic or -hh for advanced help".

i'm already search the solving but i cannot found any fix to the problem.

Do you have an idea for the solution?

**Comment by klensy** [comment]
What exact command u run (mask target)?

**Comment by stamparm** [comment]
Closing this down as you've been warned inside the Issue template to provide anything useful to deal with this issue. You haven't provided anything at all. Stating that this basic stuff doesn't work all of a sudden without any options/switches, screenshots, anything doesn't make sense to solve.
