### ISSUE TITLE
sqlmap got a 302 redirect to 'https://ipinfo.io/' ...

### ISSUE THREAD

**Issue by BabyBit** [sqlmapproject/sqlmap#2755]
Is it ok to get this message while using the --check-internet switch ?

`sqlmap got a 302 redirect to 'https://ipinfo.io/'. Do you want to follow?`

It seems to be the host used by sqlmap to test the connection, but I am not sure that redirect should happen, should I disable the switch if I get that ?

**Comment by BabyBit** [comment]
@stamparm maybe it would work to test a host like 8.8.8.8 (google's DNS), it seems to handle huge amounts of requests and it is reliable. 
Or maybe the --check-internet can have a value of our own:
`--check-internet="8.8.8.8"`

**Comment by stamparm** [comment]
@BabyBit nope. It stays as it is. In situations with proxy servers you won't get direct UDP/IP connection to 8.8.8.8. Also, making a DNS request toward it (or default DNS server) would (in case of --tor or SOCKS --proxy) induce a dns leakage.
