### ISSUE TITLE
ignore-code is not working on ubuntu

### ISSUE THREAD

**Issue by shadowfolder** [sqlmapproject/sqlmap#2757]
Hi! i have ubuntu16.04-x86_64_isp_lite5 but --ignore-code is not working.

./sqlmap.py -r request.txt --force-ssl -v 1 --level 5 --risk 3 --ignore-code=401 --dbms=mssql --dbs
Usage: python sqlmap.py [options]

sqlmap.py: error: no such option: --ignore-code

Any help please?

**Comment by shadowfolder** [comment]
Fixed. Now is new parameter --ignore-401 and not --ignore-code=401

**Comment by stamparm** [comment]
Actually, in recent revisions it is `--ignore-code`. Hence, you were using two different revisions.

With latest revision:

```
$ python sqlmap.py -hh | grep 401
    --ignore-code=IG..  Ignore HTTP error code (e.g. 401)
```
