### ISSUE TITLE
Hi there! Is it possible to use some list of tumpers in file, like we use proxyfile?

### ISSUE THREAD

**Issue by user345123** [sqlmapproject/sqlmap#2758]
It takes a long time to try each tamper manual. Thanks!

**Comment by stamparm** [comment]
There is nothing for "tumpers in file". Also, automation for "tumpers" is something that would be contra-productive, especially in case of non-expert users. I've seen tons of sh*tty advices on Internet how to run "tumpers" and in couple of cases I got a really bad headache.

User should know basics of bypassing WAF or at least detection of protection mechanism's workflow. Random usage of "tumpers" will always produce "long time to try", even in automation mode

**Comment by user345123** [comment]
thanks for anwer! Is is problem in tumper if i can see tables in databases, but cant take rows? Sorry for my stupid questions. Thank you!

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/FAQ#which-tamper-script-to-use-to-bypass-a-wafidsips-protection
