### ISSUE TITLE
lines scramble / overlap in results csv file

### ISSUE THREAD

**Issue by BabyBit** [sqlmapproject/sqlmap#2772]
I am not complaining about these, just reporting them thinking developers might want to know :) ...

When testing with --batch and results are logged as `results-04092016_0208am` I sometimes have lines oferlapping inside the file, two urls are written on same line and I get a scrambled line like this:

`http://www.site1.com/imaghttp://www.site2.com/contact,GET,ID,from`

I am thinking it is because I run more multiple tests in two windows, started at same minute; or is this the "found date" and not "test start date" ?!

As solution I am thinking one of these ...

-  add seconds or microtime or a random string for each session to file name ? One new csv for each second would not be great eider. 
- add an option to only save positives instead of all tested items 
- rewrite the way lines are saved in the csv so two lines can never overlap

**Comment by stamparm** [comment]
Will fix it. I guess you run lot of parallel tests :)
