### ISSUE TITLE
Could anyone guide me on integration code of cfscrape with sqlmap

### ISSUE THREAD

**Issue by evering7** [sqlmapproject/sqlmap#2789]
## What's the problem (or question)?

I have found the CloudFlare-scrape / cfscrape could let sql injection bypass the CloudFlare waf.

## Do you have an idea for a solution?

So I want to by myself to make a private version of sqlmap, which would send out injection code by the wrapper of cfscrape.

## The core of my problem
My problem is that I found it is hard to locate the code in sqlmap that directly and really issues the injection code out to target machine. And sqlmap did not use module of Requests, which is compatible with cfscrape. So I am worried on whether I could integrate the cfscrape into sqlmap. I need your guides. Thank you in advance.

## What are the running context details?

SQLmap 1.1.10#stable version

**Comment by stamparm** [comment]
sqlmap uses `urllib2`. Code is located at `lib/request/connect.py` (https://github.com/sqlmapproject/sqlmap/blob/master/lib/request/connect.py). `getPage()` is the main method used for sending HTTP requests. You should take a look there and try to incorporate that script.
