### ISSUE TITLE
problem dump csv from rest api

### ISSUE THREAD

**Issue by badboy-nt** [sqlmapproject/sqlmap#2796]
## What's the problem (or question)?
I can not do a dump of CSV files by using api rest. Is this possible? Which options are required in a mandatory way?

## How can we reproduce the issue?
1. donwload zip
2. use with reference the usage
3. 

## What are the running context details?
* config path of python on enviroment variables
* Installation method download zip
* Client OS `Microsoft Windows 7`
* The lab is local machine

C:\sqlmap>sqlmap.py -api -u http://192.168.6.106/owaspbricks/content-2/index.php?user=harry
        ___
       __H__
 ___ ___[)]_____ ___ ___  {1.1.11.28#dev}
|_ -| . [(]     | .'| . |
|___|_  ["]_|_|_|__,|  _|
      |_|V          |_|   http://sqlmap.org

* Target DBMS Mysql (but, I have also been able to try with other appweb .net & MSSQL
* Detected WAF/IDS/IPS protection NO

I've also tried in kali linux with sqlmap and the behavior is the same, it does not dump the CSV files.

In both laboratories, it only shows me:

dump (directory that does generate, but does not generate the database / CSV files)
log
session.sqlite
target.txt

-----------------------------------------------------------------------------

Other probes...

curl http://127.0.0.1:8775/task/new

curl -H "Content-Type: application/json" -d '{"testParameter":"id","batch":true,"threads":10,"getBanner":true, "getTables":true,"getColumns":true,"db":"acuforum","tbl":"dbo.forums","dumpTable":true}' http://127.0.0.1:8775/option/3acb7d7c960d1080/set

curl -H "Content-Type: application/json" -d '{"url": "http://testasp.vulnweb.com/showforum.asp?id=0"}' http://127.0.0.1:8775/scan/3acb7d7c960d1080/start

I appreciate the support or experiences of someone from the repo, I am doing a GUI as a project that integrates with the api rest of SQLmap

Regards,
CA

**Comment by Ekultek** [comment]
Have you tried starting the API first and sending requests from the client side instead?

python sqlmapapi.py -s

python sqlmapapi.py -c

**Comment by badboy-nt** [comment]
Thanks for you response.  I commented that if I have done the tests in that way, but neither does the dump in CSV, or at least with the options I sent him.

For this reason, I also check if there is any mandatory parameter for the rest api can do the dump?
Do you have any tests that worked for you? I would be very useful to be like that, thanks again.

**Comment by stamparm** [comment]
@badboy-nt original idea of REST API is to use it as a way how to control remote sqlmap instance. Hence, stuff like dumping CSV locally (to that remote instance) has been removed in the design. It was just a choice to not clog the remote instance with data that most probably won't be accessed by anyone (as REST API should be the primary contact point for retrieval of results).

**Comment by badboy-nt** [comment]
then it is to say that my GUI should generate a custom process to parsing the information (json) dump and generate the csv from my program?

**Comment by stamparm** [comment]
Well, you get all the data required from that (json) dump. CSV is just one form of representing it. In case of regular sqlmap's dump, it is just a fancy way how to represent that (internally) held dump data.

**Comment by badboy-nt** [comment]
Hey @stamparm Thank you very much, I'm proceeding to make a routine to try to manipulate the json and generate the files.
