### ISSUE TITLE
How to remove duplicate URL from google dork search list

### ISSUE THREAD

**Issue by Localhost800** [sqlmapproject/sqlmap#2799]
## What's the problem (or question)?

How to remove duplicate or same URLs from the result while using -g option . 

## Do you have an idea for a solution?
No

## How can we reproduce the issue?
sqlmap.py -g

**Comment by Ekultek** [comment]
There is no way, sqlmap will not "re-scan" the same website twice though. It has cached information and parses that before it scans anything, so if the site has already been found to be vulnerable, it will output what it found instead of re-scanning the site.

**Comment by stamparm** [comment]
You have to be more clear here. You are most probably not getting the same URL, though URLs that appear to be same (same path, same parameter names, but different parameter values). Without any useful information this kind of issues tend to be closed really quickly.

**Comment by urstkj** [comment]
"/><script>alert(12)</script>

**Comment by urstkj** [comment]
<!DOCTYPE html>
<html>
<body>
<script>alert(123)</script>
</body>
</html>

**Comment by stamparm** [comment]
ping?
