### ISSUE TITLE
why cache the result of query result with "--sql-shell"

### ISSUE THREAD

**Issue by leonzhao7** [sqlmapproject/sqlmap#2802]
## What's the problem (or question)?

The query result of select query in sql-shell never changes after the first execution.

## Do you have an idea for a solution?

Get select result from remote server instead of local cache

## How can we reproduce the issue?

1. start sqlmap with --sql-shell
2. create table tbl (col varchar(8000))
3. insert into tbl(col) values('first line')
4. select col from tbl
here the result is: first line
5. insert into tbl(col) values('second line')
6. select col from tbl
Now, the result does not include 'second line', it is same as the first execution
so i guess sqlmap does make remote request when a select query was executed second time

## What are the running context details?

* Installation method (e.g. `pip`, `apt-get`, `git clone` or `zip`/`tar.gz`): download from sqlmap.org
* Client OS (e.g. `Microsoft Windows 10`): windows 7, x64, python 2.7
* Program version (`python sqlmap.py --version` or `sqlmap --version` depending on installation):  1.1.11.36#dev
* Target DBMS (e.g. `Microsoft SQL Server`): Microsoft SQL Server
* Detected WAF/IDS/IPS protection (e.g. `ModSecurity` or `unknown`): none
* SQLi techniques found by sqlmap (e.g. `error-based` and `boolean-based blind`):
* Results of manual target assessment (e.g. found that the payload `query=test' AND 4113 IN ((SELECT 'foobar'))-- qKLV` works):
* Relevant console output (if any):
* Exception traceback (if any):

**Comment by stamparm** [comment]
Well, session data is persistent across all program parts, even (as you noticed) `--sql-shell`.

Now, either I could modify it to really disregard the session data automatically OR you could just settle with the `--fresh-queries`?
