### ISSUE TITLE
missing information

### ISSUE THREAD

**Issue by orwa1902** [sqlmapproject/sqlmap#2803]
How all the pieces of this program work together and where can someone who's just taking a look on the parts can acually test it?

**Comment by stamparm** [comment]
Sorry, but it is not clear what are you asking for? You won't get any quick intro to the program's internals without getting into the code. If you want some quick intro to the internals you could take a look into https://www.slideshare.net/stamparm/ph-days-2013miroslavstamparsqlmapunderthehood

As of testing site, you can always test sqlmap against Acunetix's deliberately vulnerable link: http://testphp.vulnweb.com/artists.php?artist=1
