### ISSUE TITLE
How can a complex format of data package be tested using sqlmap?

### ISSUE THREAD

**Issue by SPuerBRead** [sqlmapproject/sqlmap#2804]
Hello，In the test injection, I had a problem like this, I don't know how to solve it
The POST data packet looks like this
`POST /pepm/lpageconn/ HTTP/1.1
Host: xxxx
Connection: keep-alive
Content-Length: 281
Accept: application/json, text/javascript, */*; q=0.01
Origin: https://xxxxxxx
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Referer: https://xxxxxx/pepm/lpage/workshop/gqtzxx?l_fragment=1&id=152893&proname=%E3%80%90%E6%B5%8B%E8%AF%95%E3%80%91cs%E9%A1%B9%E7%9B%AE%E6%B5%8B%E8%AF%95&funid=146105&funname=%E4%B8%AD%E5%AE%89%E6%B6%A6%E4%BF%A1&targetEnt=150707&respo=%E6%B2%88%E4%B8%AD%E5%8D%8E&amount=23.34&channel=0&proStageId=6&proStageFlag=15&processInsid=88802&fundOrPro=1&__title=%E8%82%A1%E6%9D%83%E6%8A%95%E8%B5%84%E8%AF%A6%E7%BB%86&__s=1&l_sign=913c5eb828ccbefe7d06186084bfbabc
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Cookie: LMSPToken=156A34DDB6A74CD6AE760D69CB80D537; JSESSIONID=w7FN95L_nRDeiDBrOLMPeY_u.jbossA; ROUTEID=.jbossA

busiNo:com.linkstec.lmspcom.workshop_whole.QueryBo&param:{"queryParam":{"1":"152893"},"templateId":"overall","insId":"projectInfoGq","opId":"p54","overrideGlobalOPCfg":null}&l_sign:bdcd0c6f07f49af27d2489cd8220372b`

Each of his packets has a signature, such as the l_sign:bdcd0c6f07f49af27d2489cd8220372b

The signature is generated according to some fields, some fields in the packet does not appear, the program will combine these fields by the base64 and MD5 to create the sign, different packet value is not the same as sign, and the parameters database request is put inside the queryParam this parameter, the format is JSON. Sqlmap can be used to test this package? Or by writing some scripts to assist sqlmap to test it?

**Comment by stamparm** [comment]
Hardly. You really do need to do some complex adjustment of parameters. Either use something like Burp (extensions) or insert code [here](https://github.com/sqlmapproject/sqlmap/blob/master/lib/request/connect.py#L1020), where `post` should contain the POST body right before it is being sent to the target
