### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Teicu** [sqlmapproject/sqlmap#2811]
Hello, not sure what happened, but I received this error right now. Has worked fine in the last days, now not anymore

> sqlmap version: 1.1.12.3#dev
> Python version: 2.7.12
> Operating system: posix
> Command line: sqlmap.py -r /Desktop/test.txt --dbs --banner --random-agent --risk=3 --level=3 --identify-waf --tamper=between,randomcase,space2comment
> Technique: UNION
> Back-end DBMS: None
> Traceback (most recent call last):
>   File "sqlmap.py", line 156, in main
>     start()
>   File "lib/controller/controller.py", line 547, in start
>     injection = checkSqlInjection(place, parameter, value)
>   File "lib/controller/checks.py", line 663, in checkSqlInjection
>     reqPayload, vector = unionTest(comment, place, parameter, value, prefix, suffix)
>   File "lib/techniques/union/test.py", line 312, in unionTest
>     validPayload, vector = _unionTestByCharBruteforce(comment, place, parameter, value, prefix, suffix)
>   File "lib/techniques/union/test.py", line 271, in _unionTestByCharBruteforce
>     count = _findUnionCharCount(comment, place, parameter, value, prefix, suffix, PAYLOAD.WHERE.ORIGINAL if isNullValue(kb.uChar) else PAYLOAD.WHERE.NEGATIVE)
>   File "lib/techniques/union/test.py", line 120, in _findUnionCharCount
>     retVal = filter(lambda _: _[1], contains)[0][0]
> IndexError: list index out of range 

Cheers

**Comment by Teicu** [comment]
I just updated and I got another error: 


> sqlmap version: 1.1.12#stable
> Python version: 2.7.12
> Operating system: posix
> Command line: sqlmap.py --update
> Technique: None
> Back-end DBMS: None
> Traceback (most recent call last):
>   File "sqlmap.py", line 154, in main
>     from lib.controller.controller import start
>   File "lib/controller/controller.py", line 69, in <module>
>     from lib.core.target import initTargetEnv
>   File "lib/core/target.py", line 65, in <module>
>     from lib.core.settings import SESSION_SQLITE_FILE
> ImportError: cannot import name SESSION_SQLITE_FILE

**Comment by stamparm** [comment]
@Teicu first one is fixed. As of update error, can you please get the clean version from repository (I am not able to reproduce). It seems that some newer version files are mixing with older version files

**Comment by Teicu** [comment]
Hi @stamparm  

 just to understand better

> [16:17:56] [CRITICAL] unhandled exception occurred in sqlmap/1.1.12.3#dev. It is recommended to retry your run with the latest development version from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'. If the exception persists, please open a new issue at 'https://github.com/sqlmapproject/sqlmap/issues/new' with the following text and any other information required to reproduce the bug. The developers will try to reproduce the bug, fix it accordingly and get back to you
> sqlmap version: 1.1.12.3#dev
> Python version: 2.7.12
> Operating system: posix
> Command line: sqlmap.py -r /Desktop/test.txt --dbs --banner --random-agent --risk=3 --level=3 --identify-waf --dbms=MySQL
> Technique: UNION
> Back-end DBMS: MySQL (identified)
> Traceback (most recent call last):
>   File "sqlmap.py", line 156, in main
>     start()
>   File "lib/controller/controller.py", line 547, in start
>     injection = checkSqlInjection(place, parameter, value)
>   File "lib/controller/checks.py", line 663, in checkSqlInjection
>     reqPayload, vector = unionTest(comment, place, parameter, value, prefix, suffix)
>   File "lib/techniques/union/test.py", line 312, in unionTest
>     validPayload, vector = _unionTestByCharBruteforce(comment, place, parameter, value, prefix, suffix)
>   File "lib/techniques/union/test.py", line 271, in _unionTestByCharBruteforce
>     count = _findUnionCharCount(comment, place, parameter, value, prefix, suffix, PAYLOAD.WHERE.ORIGINAL if isNullValue(kb.uChar) else PAYLOAD.WHERE.NEGATIVE)
>   File "lib/techniques/union/test.py", line 120, in _findUnionCharCount
>     retVal = filter(lambda _: _[1], contains)[0][0]
> IndexError: list index out of range
> 
> do you want to automatically create a new (anonymized) issue with the unhandled exception information at the official Github repository? [y/N] >

**Comment by stamparm** [comment]
@Teicu what is the question. This is fixed couple of commits ago (`1.1.12.4#dev`)

**Comment by Teicu** [comment]
I didn't' know, I'm sorry! I'm going to update right now. 

Thank you very much 

Cheers
