### ISSUE TITLE
ViewSTATE and Eventvalidation are changing at runtime

### ISSUE THREAD

**Issue by amirnsahmad** [sqlmapproject/sqlmap#2819]
Hello, 

there is a time that i am having a problem with sqlmap.
The value of ViewSTATE and EventValidation parameters change in the second request and corrupt the payload.
Example:
1st request:
__EVENTTARGET=&__EVENTARGUMENT=&__VIEWSTATE=%2FwEPDwULLTE2Mzc0MDMxNjEPFgIeCmlkQ29uY3Vyc28COxYCZg9kFgICAw9kFgICAQ9kFgYCAQ8PFgIeBFRleHQFYUNPUkVNRSAtIFJlc2lkw6puY2lhIE3DqWRpY2EgLSBFc3BlY2lhbGlkYWRlcyBDbMOtbmljYXMsIENpcsO6cmdpY2FzIGUgw4FyZWFzIGRlIEF0dWHDp8OjbyAtIDIwMThkZAILDw8WBB8BBRZSZXN1bHRhZG8gZGEgY29uc3VsdGE6HgdWaXNpYmxlZ2RkAg0PDxYCHwJnZBYIAgEPDxYCHwEFE0Rpb2dvIEZvbnRlcyBTYW50b3NkZAIDDw8WAh8BBRAwMzUuMDMxLjgzMy02MSc%2FZGQCBQ8PFgIfAQUPQ29sb3Byb2N0b2xvZ2lhZGQCBw8PFgIfAQUVSW5zY3Jpw6fDo28gRWZldGl2YWRhZGRkKDXl3k5oYIgJ%2BwMfJOW8VhtMGJ%2B%2FEixgH9vGPX7RVGM%3D&__VIEWSTATEGENERATOR=8B06EF31&__EVENTVALIDATION=%2FwEdAAMRUCQi8D8oTvju%2FELHJFiWmbVOYtG0rFS3smCexx6QWi1C5ceso0TiiR3E8KJQreKH3JBT0EProY93KBdahNoj8z0ZJJSk6kLtQyth8MFxlQ%3D%3D&ctl00%24ContentPlaceHolder1%24TextBox=XYZ

2nd request:
__EVENTTARGET=&__EVENTARGUMENT=&__VIEWSTATE=%5C%2FwEPDwULLTE2Mzc0MDMxNjEPFgIeCmlkQ29uY3Vyc28COxYCZg9kFgICAw9kFgICAQ9kFgYCAQ8PFgIeBFRleHQFYUNPUkVNRSAtIFJlc2lkw6puY2lhIE3DqWRpY2EgLSBFc3BlY2lhbGlkYWRlcyBDbMOtbmljYXMsIENpcsO6cmdpY2FzIGUgw4FyZWFzIGRlIEF0dWHDp8OjbyAtIDIwMThkZAILDw8WBB8BBRZSZXN1bHRhZG8gZGEgY29uc3VsdGE6HgdWaXNpYmxlZ2RkAg0PDxYCHwJnZBYIAgEPDxYCHwEFE0Rpb2dvIEZvbnRlcyBTYW50b3NkZAIDDw8WAh8BBQ4wMzUuMDMxLjgzMy02MWRkAgUPDxYCHwEFD0NvbG9wcm9jdG9sb2dpYWRkAgcPDxYCHwEFFUluc2NyacOnw6NvIEVmZXRpdmFkYWRkZFaQ6MTtnOfY4aRliko1%5C%2BPuMCrC%5C%2Fg77T3uHYB18GR2Aa&__VIEWSTATEGENERATOR=8B06EF31&__EVENTVALIDATION=%5C%2FwEdAANE%5C%2FhrZ1mFt%5C%2BiPPe0KtvNpHmbVOYtG0rFS3smCexx6QWi1C5ceso0TiiR3E8KJQreLAw9PBWqvToWrcbKCk4p8f7AyksNGiTRUfj5I2waW9gg%5C=%5C=&ctl00%24ContentPlaceHolder1%24CPFTextBox=XYZ

The character %5c(\) is added before the characters "%2b"(+) and "%2F"(/).

Any idea what is happening?

**Comment by stamparm** [comment]
Which version are you using as I am not able to reproduce this?

**Comment by amirnsahmad** [comment]
version: 1.1.12.7#dev

Command:
./sqlmap.py -r cpf.txt --risk=3 --level=5 --random-agent -p "ctl00%24ContentPlaceHolder1%24CPFTextBox" -v6

1st req:
[13:38:48] [TRAFFIC OUT] HTTP request [#1]:
POST /demo HTTP/1.1
Accept-language: pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3
Accept-encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
Host: formularios.famerp.br
Cookie: __utma=30068136.1747874238.1512592109.1512592109.1512592109.1; __utmb=30068136.1.10.1512592109; __utmc=30068136; __utmz=30068136.1512592109.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utmt=1
Referer: http://site.com/
Upgrade-Insecure-Requests: 1
Content-type: application/x-www-form-urlencoded
Content-length: 840
Connection: close

__EVENTTARGET=&__EVENTARGUMENT=&__VIEWSTATE=%2FwEPDwULLTE2Mzc0MDMxNjEPFgIeCmlkQ29uY3Vyc28COxYCZg9kFgICAw9kFgICAQ9kFgYCAQ8PFgIeBFRleHQFYUNPUkVNRSAtIFJlc2lkw6puY2lhIE3DqWRpY2EgLSBFc3BlY2lhbGlkYWRlcyBDbMOtbmljYXMsIENpcsO6cmdpY2FzIGUgw4FyZWFzIGRlIEF0dWHDp8OjbyAtIDIwMThkZAILDw8WBB8BBRZSZXN1bHRhZG8gZGEgY29uc3VsdGE6HgdWaXNpYmxlZ2RkAg0PDxYCHwJnZBYIAgEPDxYCHwEFE0Rpb2dvIEZvbnRlcyBTYW50b3NkZAIDDw8WAh8BBRAwMzUuMDMxLjgzMy02MSc%2FZGQCBQ8PFgIfAQUPQ29sb3Byb2N0b2xvZ2lhZGQCBw8PFgIfAQUVSW5zY3Jpw6fDo28gRWZldGl2YWRhZGRkKDXl3k5oYIgJ%2BwMfJOW8VhtMGJ%2B%2FEixgH9vGPX7RVGM%3D&__VIEWSTATEGENERATOR=8B06EF31&__EVENTVALIDATION=%2FwEdAAMRUCQi8D8oTvju%2FELHJFiWmbVOYtG0rFS3smCexx6QWi1C5ceso0TiiR3E8KJQreKH3JBT0EProY93KBdahNoj8z0ZJJSk6kLtQyth8MFxlQ%3D%3D&ctl00%24ContentPlaceHolder1%24CPFTextBox=xyz&ctl00%24ContentPlaceHolder1%24ConsultaButton=Consultar

2nd req:
[13:38:48] [TRAFFIC OUT] HTTP request [#2]:
POST /demo HTTP/1.1
Accept-language: pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3
Accept-encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
Host: formularios.famerp.br
Cookie: __utma=30068136.1747874238.1512592109.1512592109.1512592109.1; __utmb=30068136.1.10.1512592109; __utmc=30068136; __utmz=30068136.1512592109.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utmt=1
Referer: http://site.com
Upgrade-Insecure-Requests: 1
Content-type: application/x-www-form-urlencoded
Content-length: 852
Connection: close

__EVENTTARGET=&__EVENTARGUMENT=&__VIEWSTATE=%5C%2FwEPDwULLTE2Mzc0MDMxNjEPFgIeCmlkQ29uY3Vyc28COxYCZg9kFgICAw9kFgICAQ9kFgYCAQ8PFgIeBFRleHQFYUNPUkVNRSAtIFJlc2lkw6puY2lhIE3DqWRpY2EgLSBFc3BlY2lhbGlkYWRlcyBDbMOtbmljYXMsIENpcsO6cmdpY2FzIGUgw4FyZWFzIGRlIEF0dWHDp8OjbyAtIDIwMThkZAILDw8WBB8BBRZSZXN1bHRhZG8gZGEgY29uc3VsdGE6HgdWaXNpYmxlZ2RkAg0PDxYCHwJnZBYIAgEPDxYCHwEFE0Rpb2dvIEZvbnRlcyBTYW50b3NkZAIDDw8WAh8BBQ4wMzUuMDMxLjgzMy02MWRkAgUPDxYCHwEFD0NvbG9wcm9jdG9sb2dpYWRkAgcPDxYCHwEFFUluc2NyacOnw6NvIEVmZXRpdmFkYWRkZFaQ6MTtnOfY4aRliko1%5C%2BPuMCrC%5C%2Fg77T3uHYB18GR2Aa&__VIEWSTATEGENERATOR=8B06EF31&__EVENTVALIDATION=%5C%2FwEdAANE%5C%2FhrZ1mFt%5C%2BiPPe0KtvNpHmbVOYtG0rFS3smCexx6QWi1C5ceso0TiiR3E8KJQreLAw9PBWqvToWrcbKCk4p8f7AyksNGiTRUfj5I2waW9gg%5C=%5C=&ctl00%24ContentPlaceHolder1%24CPFTextBox=XYZ&ctl00%24ContentPlaceHolder1%24ConsultaButton=Consultar

**Comment by stamparm** [comment]
Unreproducible. Please checkout the latest revision. By using the `--random-agent` I am not sure that you really used the latest revision as you claim.

**Comment by M3noetius** [comment]
Happens here too 1.2.4#stable

**Comment by stamparm** [comment]
@M3noetius can you please send me a request file to `miroslav@sqlmap.org`?

**Comment by stamparm** [comment]
Now it should be fixed (@amirnsahmad provided more data privately)
