### ISSUE TITLE
Not a BUG: Sqlmap + Tamper scripts on DVWA SQLi with PHPIDS v0.6 enabled

### ISSUE THREAD

**Issue by Flavioowasp** [sqlmapproject/sqlmap#2822]
I was experimenting with DVWA and SQLinjection. SQLmap find the SQLi vuln without issues on default. Then I enabled the PHPIDS that it comes with it, trying to bypass the WAF-like behavior it offers. 

And that is where I used tamper scripts as follow: 

sqlmap -u "192.168.1.38/dvwa/vulnerabilities/sqli/?id=1&Submit=Submit" --cookie="security=low; PHPSESSID=89s12ifqjnj68mhdn8i32rgqc0" --tamper=between,chardoubleencode,charencode --dbs

I tried almost every tamper script I can find for mysql: 

tamper=between,bluecoat,charencode,charunicodeencode,concat2concatws,equaltolike,greatest,halfversionedmorekeywords,ifnull2ifisnull,modsecurityversioned,modsecurityzeroversioned,multiplespaces,nonrecursivereplacement,percentage,randomcase,securesphere,space2comment,space2hash,space2morehash,space2mysqldash,space2plus,space2randomblank,unionalltounion,unmagicquotes,versionedkeywords,versionedmorekeywords,xforwardedfor

SQLMAP does not seem to be able to find the vuln anymore: 
[WARNING] GET parameter 'id' does not seem to be injectable

Did anyone succeed to get Sqlmap working with DVWA's PHPIDS enabled? 

Thank you in advance.

**Comment by Ekultek** [comment]
You should start by figuring out what keywords activate the WAF, IE does AND cause the WAF page or does 1=1 cause it?

Once you have it figured out, start obfuscating the payload until you don’t get the WAF page anymore, for example, with the Apache generic protection wrapping an equal in a comment will bypass it (AND 1/*=*/1). Once you’ve figured out what works you can create your own script or use a multiple of the already available ones to do what you need. Also, DVWA has a security set from lowest to highest. Depending on what you have it set at, that parameter might not be injectable. Good luck.

**Comment by Flavioowasp** [comment]
Hi, First, DVWA has the 4 levels of security you mentioned, however, separately from those, there is an additional option called "PHPIDS" which acts as a WAF. So I put the security level at "low" and the PHPIDA as "active". 

So coming back to your reply, the ' character does cause the WAF page to display a message: 
"Hacking attempt detected and logged.
Have a nice day." 

I tried /* and it still causes the WAF page, with or without ' appended to it. 

1=1 or AND do not cause the WAF page. 

So I need to figure out a way to encode the ' character.

**Comment by stamparm** [comment]
Closing this down (not a sqlmap development issue), though, anyone can contribute here if he wants.

p.s. https://github.com/sqlmapproject/sqlmap/wiki/FAQ#which-tamper-script-to-use-to-bypass-a-wafidsips-protection
