### ISSUE TITLE
Missing a mandatory option

### ISSUE THREAD

**Issue by Jezze83** [sqlmapproject/sqlmap#2836]
Im using sqlmap from windows. Now i get this message everytime and it worked fine before:

e8c\sqlmapproject-sqlmap-67a3e8c>sqlmap.py -h
        ___
       __H__
 ___ ___[(]_____ ___ ___  {1.1.4.26#dev}
|_ -| . [.]     | .'| . |
|___|_  [(]_|_|_|__,|  _|
      |_|V          |_|   http://sqlmap.org

Usage: sqlmap.py [options]

sqlmap.py: error: missing a mandatory option (-d, -u, -l, -m, -r, -g, -c, -x, --
wizard, --update, --purge-output or --dependencies), use -h for basic or -hh for
 advanced help

Press Enter to continue...

What is solution for that? I know how to use sqlmap commands but this is weird.

**Comment by Ekultek** [comment]
Did you just update?

**Comment by Jezze83** [comment]
I just downloaded latest version and same message with all versions.

**Comment by Ekultek** [comment]
Try pip installing then. Or try installing it with the zip file instead of clone

**Comment by Jezze83** [comment]
I didnt cloned that. Downloaded .zip and excracted.

**Comment by Ekultek** [comment]
Then clone it

**Comment by stamparm** [comment]
@Jezze83 `1.1.4.26#dev` <- this is an ancient version (April 2017). Latest one is `1.1.12.23#dev`

**Comment by Jezze83** [comment]
I just cloned latest version with git, not work either.

**Comment by stamparm** [comment]
@Jezze83 how to reproduce this? Windows or Linux? Git or zip? Which command to run?

**Comment by Jezze83** [comment]
Windows, git and zip, sqlmap.py -h

All sqlmap options gives same result.

**Comment by stamparm** [comment]
![1](https://user-images.githubusercontent.com/921555/34183011-e9dac98a-e518-11e7-9de4-842ed3fe3041.png)

Just tried and unable to reproduce. Please find the way how to reproduce it or I'll assume that something is wrong with your environment
