### ISSUE TITLE
SQL Server 2000 dump table support 

### ISSUE THREAD

**Issue by hysia** [sqlmapproject/sqlmap#2838]
in `xml/queries.xml` LINE `197`   
`ROW_NUMBER()` is NOT support by SQL Server 2000, only support SQL Server 2005+

**Comment by stamparm** [comment]
Line in question is https://github.com/sqlmapproject/sqlmap/blob/master/xml/queries.xml#L197.

You can see that there are three different query attributes (`query`, `query2` and `query3`). `ROW_NUMBER` is part of `query3` and it is being used as is. Basically, if it works great, while if it doesn't those other two queries are used as part of "pivot dumping" where each row is being retrieved by it's "pivot" (usually some UNIQUEID-alike column), while the pivot values are being retrieved one by one by using `MIN` operator (`WHERE MIN(pivot_value) > %last_pivot_value%`).
