### ISSUE TITLE
sqlmap server mode ,requests.get('xxx/task/new'),get below error

### ISSUE THREAD

**Issue by Duanexiao** [sqlmapproject/sqlmap#2842]
requests.exceptions.ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

how can I solve this problem?

**Comment by Duanexiao** [comment]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='xxx', port=xxx): Max retries exceeded with url: /task/new (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f797bb1b950>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by stamparm** [comment]
It is not clear how you are getting this. You had a Issue template to begin with and you haven't filled anything.

**Comment by Duanexiao** [comment]
start sqlmap server:python sqlmapapi.py -s -H 0.0.0.0 -p 8080
start test:
import requests
r = requests.get('http://ip:port/new/task')

**Comment by stamparm** [comment]
This whole issue doesn't have anything to do with sqlmap. You are using `requests` module, while you have connection issues in the first place. Please use `curl` to get your connection working in the first place. Then use `requests` or any other method.

Also, you could use `python sqlmapapi.py -c -H ... -p ...` to get this working. Please don't reply to this issue with nagging before you straight things at your side
