### ISSUE TITLE
file-read sucess but file-write failed

### ISSUE THREAD

**Issue by Tex-wz** [sqlmapproject/sqlmap#2851]
## What's the problem (or question)?
`sqlmap.py -u xxx.com?id=1 --file-read="/etc/passwd"`
I can read file but I can't write file

`sqlmap.py -u xxx.com?id=1 --file-write="/etc/passwd" --file-dest="_etc_passwd"`

> [*] starting at 21:55:16
> [21:55:16] [CRITICAL] the provided local file '/etc/passwd' does not exist
> [*] shutting down at 21:55:16

I have checked my privileges : 
    privilege: ALTER
    privilege: ALTER ROUTINE
    privilege: CREATE
    privilege: CREATE ROUTINE
    privilege: CREATE TEMPORARY TABLES
    privilege: CREATE USER
    privilege: CREATE VIEW
    privilege: DELETE
    privilege: DROP
    privilege: EXECUTE
    privilege: FILE
    privilege: INDEX
    privilege: INSERT
    privilege: LOCK TABLES
    privilege: PROCESS
    privilege: REFERENCES
    privilege: RELOAD
    privilege: REPLICATION CLIENT
    privilege: REPLICATION SLAVE
    privilege: SELECT
    privilege: SHOW DATABASES
    privilege: SHOW VIEW
    privilege: SHUTDOWN
    privilege: SUPER
    privilege: UPDATE

is-dba true also.

* Installation method : zip ( download from github )
* Client OS : win10
* Program version : latest
* Target DBMS : Mysql

**Comment by stamparm** [comment]
Privileges of DBMS user are something different than OS privileges. In matter of fact, it is quite rare in todays setups to find the DBMS user (even admin) to have write privileges to anywhere on the file system (usually it is restricted only to some temporary DBMS directory locations)
