### ISSUE TITLE
ERROR RECEIVED WHILE DUMPING

### ISSUE THREAD

**Issue by AmericanY** [sqlmapproject/sqlmap#2857]
unknown web page charset '927 and'. Please report by e-mail to 'dev@sqlmap.org'

**Comment by stamparm** [comment]
Thank you. Somebody has written totally invalid charset there. Usually I write some replacement in this kind of cases, but this one doesn't deserve any replacement

**Comment by AmericanY** [comment]
I understood, it's already doesn't effect anything :)

**Comment by AmericanY** [comment]
@stamparm i think that you really need to insert that table at least for Newbie users.

http://0xd0m7.blogspot.com.eg/2016/02/understanding-tamper-option-in-sqlmap-ii.html
