### ISSUE TITLE
Writing tamper script with other languages

### ISSUE THREAD

**Issue by KINGSABRI** [sqlmapproject/sqlmap#2867]
Is there any way to support writing tamper scripts with another language? 

thanks

**Comment by klensy** [comment]
With wrapper like SWIG - why not?

**Comment by stamparm** [comment]
Nope. Only Python. Writing string replacement code is far too easy (trivial) in python to unnecessary bring another language support into it.

**Comment by KINGSABRI** [comment]
> Nope. Only Python. Writing string replacement code is far too easy (trivial) in python to unnecessary bring another language support into it.

That's right, just supporting other languages make tamper richer for people from other languages so it's easier to contribute for more ideas and needs.

if you would like to make it even easier for other languages and test it (eg. Ruby)

**Comment by KINGSABRI** [comment]
Okay, there is a simple api I've created here just in case someone has found this issue.
https://github.com/KINGSABRI/sqlmap-tamper-api
You use any language since it deals purely with JSON.

**Comment by huitc** [comment]
https://github.com/KINGSABRI/sqlmap-tamper-api
