### ISSUE TITLE
always '414'

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#2872]
It may be because of target URL appears too much columns, so the following situation arises
How can i solve this problem
(Bing translate...:kissing:

[INFO] target URL appears to have 27659 columns in query
... and then..
[DEBUG] got HTTP error code: 414 (Request-URI Too Large)   [*N times...

**Comment by huitc** [comment]
[14:36:56] [INFO] target URL appears to have 27659 columns in query

**Comment by huitc** [comment]
and sometimes maybe because this can't take any data form target database...

**Comment by huitc** [comment]
have anyway can make payload shorter?

**Comment by stamparm** [comment]
You could try `--no-cast`. If that doesn't help, you should assess your target manually (if possible). In this kind of cases no automation can help you.

**Comment by stamparm** [comment]
Update: try `--no-cast --no-escape`

**Comment by huitc** [comment]
@stamparm Can only run in old version of MySQL? If so, what is the scope of the old version?

**Comment by huitc** [comment]
@stamparm have anyway can make payload shorter?

**Comment by stamparm** [comment]
I've said to you what to do in last two comments. If that doesn't help I am not sure that anything will help
