### ISSUE TITLE
Get mistakes

### ISSUE THREAD

**Issue by JackandBlackLLL** [sqlmapproject/sqlmap#2878]
Every time I get errors when working with the result of Arachni

Ex of HTTP result Arachni: 

GET /search?q=&lang=default HTTP/1.1
Host: www.gymboree.com
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.8,he;q=0.6
X-Arachni-Scan-Seed: 4a9ce0934988133318d504f7d9c1450d
Cookie: _br_uid_2=-1839+or+1%3D1;__cfduid=d97a00d9dfab195025a23ecb0c22801e61513997976;dwac_739ededc2d1e7cf0140a2d72f4=t50RUGfvIQoEfpEzPrVo64KBsilCvzAeYgE%3D|dw-only|||USD|false|US%2FPacific|true;cqcid=cepV3uafNfq9hIDQQc3gdXbBXB;dwsecuretoken_45c10de9ad9a9ceefb3a5ac2354a4ab3=3eDwt5q5fMaYDaTMmMRdZOEnr0FsAASNaQ==;sid=t50RUGfvIQoEfpEzPrVo64KBsilCvzAeYgE;dwanonymous_45c10de9ad9a9ceefb3a5ac2354a4ab3=cepV3uafNfq9hIDQQc3gdXbBXB;dwsid=TNRbefGkb7Q-cQg_--AXzHnI-ADU9H6gWA75OUgHQWq9KRhXuYBUWldfQdjKDODTWf8-UlIuct2zCgySI_UxYw==;__ar_v4=;rkglsid=h-e3a8e6b283299b1835afa1511608150b_t-1513998263;__cq_seg=0~0.00!1~0.00!2~0.00!3~0.00!4~0.00!5~0.00!6~0.00!7~0.00!8~0.00!9~0.00;__cq_uuid=60770fb0-e78d-11e7-a45d-f1425f8c91a3;_gid=GA1.2.989225411.1513998037;_ga=GA1.2.1088525700.1513998037;_uetsid=_uet08b53979;testVersion=versionA;topassetshow=assetclose;dw_cookies_accepted=1;dw=1;optimizelyBuckets=%7B%7D;optimizelySegments=%7B%221730981023%22%3A%22direct%22%2C%221731020928%22%3A%22safari%22%2C%221733630942%22%3A%22none%22%2C%221735381005%22%3A%22false%22%7D;optimizelyEndUserId=oeu1513998033440r0.6115813062060624;dtPC=-15$198092530_786h1p-15$198288026_372h1p-15$198293360_574h1p-15$198301773_698h1p-15$198307049_415h1p-15$198315209_689h1p-15$198633464_98h1p-15$198640571_816h1p-15$198646021_742h1p-15$198668295_963h1p-15$198724838_807h1vCEEXOCDQLCXCSNXTNOCJADPHUASABRBXNJBW;rxvt=1514000524859|1513998092542;rxVisitor=1513998092538PG6IU5QQ5TDEUCG783C79BTTKGO9MAU8;dtCookie=-15$OSSH20P6KDJPFOS10RE2V1K50JPFM98V

SQLMAP:

[04:19:57] [WARNING] it appears that you have provided tainted parameter values ('_br_uid_2=-1839+or+1%3D1') with most likely leftover chars/statements from manual SQL injection test(s). Please, always use only valid parameter values so sqlmap could be able to run properly

Does this error greatly affect the result?
Is it necessary to edit the result of Arachni

**Comment by stamparm** [comment]
Yes. sqlmap can't know the valid values, hence you can get trash results (payloads are made based on VALID original values).

You should modify ` _br_uid_2=-1839+or+1%3D1` to ` _br_uid_2=1839` (or some valid value)

p.s. I would not be so sure that you are dealing here with a SQLi in the first place
