### ISSUE TITLE
how to fix this?

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#2879]
[DEBUG] declared web page charset 'utf-8'

[INFO] retrieved:
[ERROR] unable to retrieve the number of databases
[INFO] falling back to current database
[INFO] fetching current database
[INFO] resumed: \x07\x89\x04A\x07\x11\x07\x11
available databases [1]:
[*] \x89A

**Comment by klensy** [comment]
42

**Comment by huitc** [comment]
@klensy ?

**Comment by huitc** [comment]
@klensy?

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by stamparm** [comment]
Most probably a false positive. Please rerun everything with `--flush-session`. If you are not able to retrieve anything meaningful with `--banner` then you are having a false-positive (fixing it with `--flush-session` would do)
