### ISSUE TITLE
Redirect requests should show in high verbose levels

### ISSUE THREAD

**Issue by stamparm** [sqlmapproject/sqlmap#288]
```
When looking at HTTP Requests and Response, by using verbose level 6 (-v 6), sqlmap does not show the full HTTP response with the HTTP 302 Moved Temporarily.

sqlmap got a 302 redirect to 'http://removed/removed.shtml'. Do you want to follow? [Y/n] y
[14:07:02] [INFO] heuristics detected web page charset 'ascii'
[14:07:02] [TRAFFIC IN] HTTP response [#2] (302 Object Moved):
Connection: close
Content-type: text/html
Location: https://removed/removed.shtml
Cache-control: private
[14:07:02] [TRAFFIC IN] HTTP response [#2] (302 Moved Temporarily):


In the body of the first HTTP Response, the 302 temporary redirect, is the result of the SQL injection.

If I don't follow the redirection then I see the result. This is fine (to me at least), I just didn't realise or expect it at first. I expected that verbose 6 would show all of the responses, particularly those that contain the results that sqlmap is returning.
```

**Comment by mohamyass** [comment]
hi,
I execute this commande:

C:\Python27>python sqlmap\sqlmap.py -r hacme.txt -p txtUserName  --risk=3 --leve
l=3 --technique=u --dbms=MSSQL --union-cols 1-8 --union-char=UCHAR

But I receive this message: sqlmap got a 302 redirect to 'http://52.25.139.95:80/aspx/main.aspx'. Do you want to follow? [Y/n]?

Thanks,

**Comment by mohamyass** [comment]
Hi,
I have a problem when I execute this commande: 
C:\Python27>python sqlmap\sqlmap.py -r hacme.txt -p txtUserName  --risk=3 --level=3 --technique=u --dbms=MSSQL --union-cols 1-8 --union-char=UCHAR

I receive the message: sqlmap got a 302 redirect to 'http://168.0.139.90:80/aspx/main.aspx'. Do you want to follow? [Y/n]

Thanks,

**Comment by stamparm** [comment]
@mohamyass and what seems to be the issue? try Y, if it doesn't produce results, try N in next run. In most cases Y is the right choice.

**Comment by mohamyass** [comment]
Thank you stamparm. It works for both.

**Comment by diffhk** [comment]
stamparm will u please help me out on this one !? 
i tried : sqlmap -u https://www.univ-usto.dz/index.php?lang=fr --dbs but it tells me that its not injectable is there any way i can pass this or smth !?

**Comment by Vinodkpawar108** [comment]
Please help me out on this one?
i tried: sqlmap.py http://127.0.0.1/bWAPP/sqli_1.php?title=1 but it tells me that its not injectable, But over youtube in sample video for same URL it says injectable.
