### ISSUE TITLE
SQL MAP will not give me correct information received

### ISSUE THREAD

**Issue by frequencyg** [sqlmapproject/sqlmap#2881]
Hello,
Using SQLMAP to extract information outside of a table.I would wait for hours (threads 4) till the information comes out one by one (mobile phones for example) .The phones would come as for EG. (where X a  digit) XXXXX$%XX or XXXj$%!XXXX. Do you get me? Or they would have spaced between them for EG. XXX X X   XX!

**Comment by stamparm** [comment]
You had an issue request template where you could enter data without me asking the details.

What was the SQLi technique?

**Comment by frequencyg** [comment]
(newbie here). Removing threads 4 fixed my issue for like 90%,the other 10% is getting lost  due to internet issues!
