### ISSUE TITLE
Hope to be able to use the "-V" and "--eta" feature at the same time

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#2882]
Hope to be able to use the "-V" and "--eta" feature at the same time

Because sometimes you need the debug feature from '-v 2'

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by AmericanY** [comment]
Well @stamparm i saw many users requested the same, basically i have an idea of using Python Screen Split https://docs.python.org/3.5/howto/curses.html
