### ISSUE TITLE
sqlmap dump issue with charset

### ISSUE THREAD

**Issue by AmericanY** [sqlmapproject/sqlmap#2888]
Hello,

I noticed a bug with sqlmap during dump columns with `--charset` enabled which keep dumping some of the data with unicode such as `?` and `^P`.

Technique = Boolean Based Blind with tor enabled and threads 10

keep informed if i dumped the data once again, it's dump correctly without any issues which means the issue not from the database. also it's happened with many database dump.

the data which i dumping include numbers only which is `--charset="0123456789"`

Kindly inform me if there's a way to let sqlmap re-dump the stored dump but with fixing the wrongly dumped numbers ... for example

1234?6

can sqlmap re-check the dumped result and once find unicodes so it's gonna re correct it 

123456

**Comment by stamparm** [comment]
It is not clear what is happening here. Can you please restate?

How does the table dump looks like before and after

**Comment by AmericanY** [comment]
Hello,

Let's say the table include columns containing numbers only ( from 0 to 9 ) and the technique is Boolean based blind.

So i used `--charset="0123456789"` to speed up the process of dump.

The issue I'm suffering with is:

while tor enabled and using charset so i got some of dumped numbers missed ( replaced with '?' )

let say the column contain `45679821` but once i dump it so it's appear like `456?9821` which means there's one number dumped incorrectly, but if i do `--fresh-queries` and re-dumped it so it's dumped correctly.

my point here ( imagine that you do have around 100k dumped columns from table including numbers only and there's many numbers missed ) so in that case i don't see any other option than re-dump the missed numbers by re-dump the whole column itself again manually !

hope you got my point

**Comment by stamparm** [comment]
So, it is not a problem of `--charset` but the general data retrieval problem? I am not sure what would you expect here? I mean, as sqlmap can't detect whether there was a problem in data retrieval or in your defined charset (bad one?) or something totally unrelated... you could expect this kind of behavior.

So, do you have some proposition how to deal with this kind of problems? In case of 100K rows, users are too lazy to do anything more than to "automate" everything. Expecting from users to provide row numbers where error occurred is illusionary. Expecting from sqlmap to detect errors (while it already has pretty good error detection mechanisms) in its own dumping mechanism (while there could be lots of other causes) is also illusionary

**Comment by AmericanY** [comment]
My idea to fix such kind of issue.

`--validate-dump` which gonna check the existing dumped data.

while `--validate-dump="0123456789"` gonna check the dumped data if all rows dumped is include numbers only and if it's detected any non-numbers in the dumped data so it's gonna re-dump the whole columns missed again.

Scenario : 1- we already dumped the data
                 2- `--validate-dump="0123456789"` will check if all dumped data is numbers only.
                3-  redump the missed columns which include something other than numbers.

That's all.

**Comment by stamparm** [comment]
```
$ python sqlmap.py -hh | grep repair
    --repair            Redump entries having unknown character marker (?)
```
