### ISSUE TITLE
Tamper script 'requestvalidationmode.py' does not exist

### ISSUE THREAD

**Issue by angeleyecode** [sqlmapproject/sqlmap#2889]
When used used the tamper script "requestvalidationmode.py", Sqlmap says it does not exist when it is actually in the waf directory. Is this an expected behavior or I'm doing something wrong?

**Comment by stamparm** [comment]
`requestvalidationmode.py` is a waf script (directory `waf`) used during the `--identify-waf`. It is not a tamper script (directory `tamper`)
