### ISSUE TITLE
Error accessing MSSQL tables when schema contains DOMAIN\HOSTNAME

### ISSUE THREAD

**Issue by cclements** [sqlmapproject/sqlmap#2890]
Seems I am unable to pull table contents when the DB schema contains the windows server's name in DOMAIN\HOSTNAME format.  See gist for details:
https://gist.github.com/cclements/4f2e891f0137e91f030c61607fe08e0c

**Comment by stamparm** [comment]
Please retry now with updated revision and report back

**Comment by cclements** [comment]
Thanks, but I seem to have the same issue:
https://gist.github.com/cclements/5d39c071e8f3f603c33309312d0918c6

**Comment by stamparm** [comment]
Then, what should be the proper format in those kind of cases? You could just use any of those payloads and try with different combinations (e.g. without TargetDB or different positions of those brackets) until it works.

**Comment by cclements** [comment]
Looking at it some more, I'm not convinced this is a sqlmap problem.  I get similar errors using sqlcmd.  Being as this is the first time I've encountered this unusual schema name, I'm not sure it's worth worrying about.
