### ISSUE TITLE
[REQUEST] skip table from dump

### ISSUE THREAD

**Issue by r3pek** [sqlmapproject/sqlmap#2891]
## What's the problem (or question)?

I think a nice feature to have is to skip a table from a dump. Just for reference, I'm dumping a database with almost 600 tables but I only want to skip 1 or 2 which makes it a PITA to user --tables :(

## Do you have an idea for a solution?

Implement a new parameter that has the same behaviour as -X but for tables itself

## How can we reproduce the issue?

1. Get a big database to dump
2. try to dump all except just one table

**Comment by stamparm** [comment]
Done with the latest revision. Option `-X` can now be used also for exclusion of tables and databases

**Comment by AlizerUncaged** [comment]
> Done with the latest revision. Option `-X` can now be used also for exclusion of tables and databases

how do we use it? let's say i have a database named SampleDatabase and inside it is a table named SampleTable, do we just do ``-X SampleTable`` or ``-X SampleDatabase .SampleTable``

**Comment by stamparm** [comment]
@AlizerUncaged in your case, just `-X SampleTable`. it is literary looking into the provided identifier name in all enumeration attempts. there is nothing "structured" with it

**Comment by engycz** [comment]
@stamparm It doesn't work for tables with reserved names like `logs`
![obrazek](https://github.com/user-attachments/assets/9a324968-a273-47a4-893f-64e03392fe81)

if conf.exclude and re.search(conf.exclude, tbl, re.I) is not None:

Searching  \`logs\` in pattern `\Alogs\Z`
