### ISSUE TITLE
[Question] ORA-01000

### ISSUE THREAD

**Issue by b2az** [sqlmapproject/sqlmap#2893]
## What's the problem (or question)?

While pentesting an internal application sqlmap gets Data out of a ".jsp?get_id=1".
It's a Oracle database. But after dumping successfully some entrys i'm getting 500 errors.

A view on the webapp in the browser shows: 

> java.sql.SQLException: ORA-01000

## Do you have an idea for a solution?

I have no plan what is going on, but here [https://stackoverflow.com/questions/12192592/java-sql-sqlexception-ora-01000-maximum-open-cursors-exceeded](url) it says:

> ORA-01000, the maximum-open-cursors error, is an extremely common error in Oracle database development. In the context of Java, it happens when the application attempts to open more ResultSets than there are configured cursors on a database instance.

## How can we reproduce the issue?

Sadly its not possible because the Application is in a intranet.
## What are the running context details?

* Installation method (e.g. `pip`, `apt-get`, `git clone` or `zip`/`tar.gz`): preinstalled

* Client OS (e.g. `Microsoft Windows 10`): Kali2
* Program version (`python sqlmap.py --version` or `sqlmap --version` depending on installation): 1.1.12#stable
* Target DBMS (e.g. `Microsoft SQL Server`): Oracle
* SQLi techniques found by sqlmap (e.g. `error-based` and `boolean-based blind`):
`Parameter: get_id (GET)
    Type: boolean-based blind
    Title: Oracle AND boolean-based blind - WHERE or HAVING clause (CTXSYS.DRITHSX.SN)
    Payload: get_id=1 AND (SELECT (CASE WHEN (7992=7992) THEN NULL ELSE CTXSYS.DRITHSX.SN(1,7992) END) FROM DUAL) IS NULL

    Type: error-based
    Title: Oracle AND error-based - WHERE or HAVING clause (UTL_INADDR.GET_HOST_ADDRESS)
    Payload: get_id=1 AND 1537=UTL_INADDR.GET_HOST_ADDRESS(CHR(113)||CHR(106)||CHR(98)||CHR(120)||CHR(113)||(SELECT (CASE WHEN (1537=1537) THEN 1 ELSE 0 END) FROM DUAL)||CHR(113)||CHR(106)||CHR(107)||CHR(106)||CHR(113))

    Type: AND/OR time-based blind
    Title: Oracle AND time-based blind
    Payload: get_id=1 AND 8937=DBMS_PIPE.RECEIVE_MESSAGE(CHR(111)||CHR(119)||CHR(90)||CHR(70),5)`

Is it a web-application issue, or is there a sqlmap setting im missing?

Thank you in advance!

best,
b2az

**Comment by syedafzal** [comment]
Looks like you just simulated high traffic scenario for your intranet application. 
There's a delay switch which u can use to limit number of requests per unit time.

**Comment by stamparm** [comment]
As @syedafzal said, too many requests in a short period could cause this kind of behavior. In those kind of cases you should avoid usage of `--threads` and you could take a look into `--delay` option.

But, usually, this kind of behavior can be skipped by using only single-thread run
