### ISSUE TITLE
SQLmap didn't find proofed vuln.

### ISSUE THREAD

**Issue by mbauer588** [sqlmapproject/sqlmap#2896]
Hallo,

I hope my request is here right - I am not sure if it's my error by using sqlmap or if it's an error in sqlmap...

## What's the problem (or question)?
I test a page an found out, that this input leeds to a data leek: 
`1 union select password,user from users limit 1 offset 1`
 
But I am not able to get sqlmap do it's job with that info...

## What are the running context details?
to be specific it's DVWA + PHPIDS.

I try 
`--level 5 --risk 3 --technique=U`
then i add various tamper-scripts 
and many other things.

I know there is an IDS in place which block a ton of other ways to do an SQLi. Is there a way to get sqlmap run with the infos i found out or is there the fitting attack missing?

Is there a way to tell sqlmap an specific working attack or a template like 
`1 union select [FIELD],[FIELD] from [TABLE] limit 1 offset [NUMBER_OF_ROW]`

**Comment by stamparm** [comment]
You are asking too general questions.

Please run with `-t traffic.txt` and/or `-v 3` and/or `--proxy` to see what is going on. If there is an IDS in between you have some manual work to do (for start inspect the traffic file you get with the `-t traffic.txt`)

**Comment by mbauer588** [comment]
Ok, no problem... is
`sqlmap -u "http://192.168.1.52/dvwa/vulnerabilities/sqli/?id=2&Submit=Submit" --cookie="security=medium;PHPSESSID=d60aee54a7aa48467c243b55558e05f3" --dbms MySQL --level 5 --risk 3 -p id --dbs `
OK?

Or should i restrict to `--technique=U`?

As my UNION based injection sting work it would make sence to me... Your decision - with or without `--technique=U`...

**Comment by stamparm** [comment]
There is no need to restrict it with `--technique`

**Comment by mbauer588** [comment]
This post is huge so I NoPaste it... The traffic.txt is NoPasted here: https://nopaste.xyz/?331bd23240fb97c5#MDrNGfvYgKMGDF+BaGvIbZaVwhiYQqRnz34GBq5/adY=

Here you have the output of `-v 3`: https://nopaste.xyz/?e4ec13e3537afc6c#oi+RHPEUgh2g5WX4U/0D4NyfhS3Ub8q2IN3mLUWHwRo=

**Comment by stamparm** [comment]
You should inspect it. Closing this down as this is not a sqlmap's issue
