### ISSUE TITLE
always "unable to properly validate last character value"...

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#2898]
[ERROR] unable to properly validate last character value ('\xff\xff\xff')..
[ERROR] invalid character detected. retrying..
[ERROR] unable to properly validate last character value ('\xff\xff\xe9')..
[ERROR] invalid character detected. retrying..

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by stamparm** [comment]
Is it non-latin (e.g. chinese) or you have network latency problems?

**Comment by huitc** [comment]
@stamparm If it's Chinese, can't be injection?..

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by stamparm** [comment]
Do you get anything meaningful with `--banner`?

If not, then it is most probably a false-positive. Please rerun with `--flush-session` if so
