### ISSUE TITLE
How can I use sqlmap with sql injection?

### ISSUE THREAD

**Issue by xdevil68** [sqlmapproject/sqlmap#2901]
{"errorCode":"CMN0409E","errorMessage":"CMN3101E The system is unavailable due to \"java.lang.NumberFormatException: Not a valid char constructor input: 1''\".","errorMessageKey":"_ERR_GENERIC","errorMessageParam":"[Ljava.lang.Object;@65e765e7","correctiveActionMessage":"","correlationIdentifier":"-2fd24340:15e8a4c297f:-24f","exceptionData":"","exceptionType":"1","originatingCommand":"","systemMessage":"The following error occurred during processing: \"java.lang.NumberFormatException: Not a valid char constructor input: 1''\"."}
	
/*
{
	"errorCode": "CMN0409E",
	"errorMessage": "A generic error has occurred.",
	"errorMessageKey": "_ERR_GENERIC",
	"errorMessageParam": ["java.lang.NumberFormatException: Not a valid char constructor input: 1''"],
	"correctiveActionMessage": "",
	"correlationIdentifier": "-2fd24340:15e8a4c297f:-24f",
	"exceptionData": null,
	"exceptionType": "1",
	"originatingCommand": "",
	"systemMessage": "The following error occurred during processing: \"java.lang.NumberFormatException: Not a valid char constructor input: 1''\"."
}
*/
testing parameter "564206%2C695896" "-1%2C-2%2C-3%2C-4%2C-5%2C-6%2C-7"

After I tried sql injection, it showed an error like that

Parameter: page (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause

**Comment by stamparm** [comment]
This is an example of an invalid issue request. Nothing can be concluded from this. Closing this down

**Comment by xdevil68** [comment]
I can ask you some questions

2018-01-31 18:41 GMT+07:00 Miroslav Stampar <notifications@github.com>:
