### ISSUE TITLE
sqlmap can't inject - 100% Error-based heavy query blind injection

### ISSUE THREAD

**Issue by edgarolijar** [sqlmapproject/sqlmap#2909]
My payload:
`foo.php?id=1,(select(1)rlike(if((".$cmd."),if(benchmark(".$time.",md5(1)),0x28,0x28),0x28))) -- -`

1. `$time` can be a fixed value, which can be chosen by sqlmap
2. `$cmd` _must be_ nested SQL command, chosen by sqlmap
3. There must always be an error (0x28 -> "SQL Error: ... unballanced parentheses ...") to bypass other special restrictions (otherwise SQL injection won't be possible at all).
4. Error-based doesn't mean a classical error-based injection where i see e.g. password hashes and usernames in an SQL error in response body (0x28 = "("). So to be clear I'm sending a buggy SQL query and receive some static error.
5. This is the only possible way to do an injection (as i said otherwise an injection will not work at all). No useful reponse or anything else - just believe me that I know what I'm doing and it can't be done better in this case.

I can't use MySQL's function `sleep(...)` here, only heavy query:
https://stackoverflow.com/questions/45666126/strange-behaviour-of-mysql-sleep-function
Because i always need an SQL error and `sleep()` will not work if there is an SQL error, but heavy query will do.

Currently I'm using a PHP wrapper for sqlmap with some fixed `$time` value (which i figured out by trial & error).

## Question
How can i tell sqlmap to use **only** subqueries which will return true or false? Is there a simple way to tell sqlmap how to make such injection there?

**Comment by stamparm** [comment]
Nope. You have a really special case, while sqlmap has been made for a general usage. In this kind of cases I would really suggest you make a custom script (your own) just for this case (while you can take a look into e.g. xml/queries.xml to see which queries should you send in enumeration phase)
