### ISSUE TITLE
Current stable?

### ISSUE THREAD

**Issue by ilovezfs** [sqlmapproject/sqlmap#2914]
https://github.com/sqlmapproject/sqlmap/releases shows 1.2.2

https://github.com/sqlmapproject/sqlmap/releases/latest points to 1.2

**Comment by stamparm** [comment]
Not sure what are you pointing to?

Latest release is 1.2
Latest "stable" tag is: 1.2.2
Latest "dev" revision is: 1.2.2.2

**Comment by ilovezfs** [comment]
What is the difference between a latest release and a latest stable tag? Should Homebrew be shipping 1.2 or 1.2.2?

**Comment by stamparm** [comment]
Release is being done once in a year (at the beginning). "Stable" tag is being done once a month (at the beginning). I would say that it depends on the packager.

I can only say that "dev" revisions are only for the everyday users which want everything up to date, though, I can't guarantee those to be crash-free

**Comment by ilovezfs** [comment]
What would you prefer we distribute to the Homebrew users?

```
bash-4.4$ brew formula-analytics --days-ago=90 sqlmap
install events in the last 90 days for sqlmap
=================================================================
1 | sqlmap                                      | 7,875 |  99.95%
2 | sqlmap --HEAD                               |     4 |   0.05%
=================================================================
Total                                           | 7,879 |    100%
=================================================================

install_on_request events
=================================================================
1 | sqlmap                                      | 5,887 |  99.93%
2 | sqlmap --HEAD                               |     4 |   0.07%
=================================================================
Total                                           | 5,891 |    100%
=================================================================

Error: No BuildError data found!
bash-4.4$ 
```
This affects a non-trivial number of people :)

**Comment by stamparm** [comment]
I would prefer "stable" tag. That same stable tag is being pushed to the PyPI as a package (once a month), so I would say that it should be the best option.

**Comment by ilovezfs** [comment]
1.2.2 shipped! https://github.com/Homebrew/homebrew-core/pull/23743
