### ISSUE TITLE
Is there a way to save everything in one .txt?

### ISSUE THREAD

**Issue by trollmad3** [sqlmapproject/sqlmap#2916]
## What's the problem (or question)?

I did `--dump-all` and noticed its all splitted up into several files like this: 
![image](https://user-images.githubusercontent.com/7843719/35889954-3690992e-0b63-11e8-92ed-d2e0f4972c25.png) 

Is there a command that merges it all into one file?

**Comment by stamparm** [comment]
Nope. Each table has its own file as data inside is CSV formated. Though, you can use `--dump-format=SQLITE` where every table would be dumped into the same-named database (e.g. database.sqlite3)

**Comment by trollmad3** [comment]
@stamparm Thats exactly what I wanted to do. Thank you
