### ISSUE TITLE
Option to download files from the database

### ISSUE THREAD

**Issue by FailGecko9800** [sqlmapproject/sqlmap#2917]
Hi... How are you, i hope you all are well.

i am submitting this post to ask for a feature to be added to SQLMap....... Do you think you could add an option to be able to download files from the database.. it would make it easier

at the moment when i get into a database i have to use the --dump command but that just shows the information.. I would like to be able to download it..

do you think you can add it please

Thanks.. i hope you can add it :)

**Comment by stamparm** [comment]
SQLMap is an SQL injection tool. Hence, it uses SQL injection vulnerability to extract/exfiltrate/infer data from the underlying database. There is no inherent way (at least not in a generic form) which would instead of "dumping" stuff do the "download" of the whole database.
