### ISSUE TITLE
Payload from first level working only if specified level is higher?

### ISSUE THREAD

**Issue by koxu1996** [sqlmapproject/sqlmap#2918]
## What's the problem?

When I scanned request with Burp Suite, it quickly found payload `'+(select*from(select(sleep(20)))a)+'`. So I decided to check if sqlmap will find it too:

```
$ sqlmap -r request.txt -p username --dbms=mysql
...
[00:14:41] [INFO] testing 'MySQL >= 5.0.12 AND time-based blind'
[00:14:41] [WARNING] time-based comparison requires larger statistical model, please wait......
 (done)
...
[00:14:50] [CRITICAL] all tested parameters do not appear to be injectable.
...
```

I decided to set level to maximum:

```
$ sqlmap -r request.txt -p username --dbms=mysql --level=5
...
[00:20:08] [INFO] testing 'MySQL >= 5.0.12 AND time-based blind'
[00:20:31] [INFO] POST parameter 'username' appears to be 'MySQL >= 5.0.12 AND time-based blind' injectable
...
```
Success, but I wondered what minimum level was required to find this vulnerability. So I looked into `xml/payloads/time_blind.xml` and _MySQL >= 5.0.12 AND time-based blind_ appears to be payload from level 1. It's look like a bug, because it's only detected if I specify higher level.

## Context details

* Installation method: pacman
* Client OS: Arch Linux x64
* Program version:  1.2#stable
* Target DBMS: MySQL
* SQLi techniques found by sqlmap: time-based

**Comment by stamparm** [comment]
Please rerun both cases with `-v 3` to see what is happening (which payload worked in the second place). Also, there is a possibility that same payload just failed in the first run.

**Comment by koxu1996** [comment]
Level1:
![level1](https://i.imgur.com/4ugx77x.png)

Level 5:
![level5](https://i.imgur.com/AUncWgk.png)

**Comment by stamparm** [comment]
Along with payloads, with different `--level` values you are also extending the used "boundaries". This basically means that "boundaries" which are more probable to work can be found in lower levels, while boundaries which are less probable OR not turning anything more new than those in lower levels can be found in higher levels.

Just take a look into those pictures and you'll see what is going on. Boundaries `'||(...||'` used in higher levels work, while those at lower levels (which in majority of SQLi cases should work) failed. Nothing problematic here

**Comment by koxu1996** [comment]
Ok, I see.
