### ISSUE TITLE
how to bypass this waf... t.t

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#2919]
[CRITICAL] WAF/IPS/IDS identified as 'UrlScan (Microsoft)'

Is there any way to bypass it?

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by stamparm** [comment]
If well configured UrlScan is a really nice (and free) WAF. I would say that in majority of cases you won't be able to bypass it (even manually)
