### ISSUE TITLE
Python3 and async

### ISSUE THREAD

**Issue by shadowfolder** [sqlmapproject/sqlmap#2929]
Hi @stamparm is there any plans to add python3 support? Python3 support async requests, which can make sqlmap faster for Union or Error requests.

**Comment by stamparm** [comment]
async requests wouldn't speed up the process as server response times and network latency can't be "speed up". Why would anybody use "async" requests when the response time is the major bottleneck.

In short, Python3 won't be supported for some time

**Comment by shadowfolder** [comment]
Thanks for answer mate, i've asked about this, because i've seen some of people using self modification of sqlmap, which are support async requests, when you need to dump big database(millions records) and server response it's not a problem it's a good option

**Comment by stamparm** [comment]
1) I doubt that you've seen sqlmap with such feature as sqlmap is strict in order-of-data retrieval. Also, it would be really hard to implement without really good knowledge of the sqlmap internals
2) Response times are THE problem. You can use asynchronicity when you have other stuff to do inside the program - but, sqlmap doesn't have anything to do BESIDE waiting for the server to respond. Asynchronicity (compared to regular multi-threading used in sqlmap) doesn't solve the response times - it just gives you more time inside your program to do other stuff.
