### ISSUE TITLE
Json Post Data

### ISSUE THREAD

**Issue by lukeoneO** [sqlmapproject/sqlmap#2943]
Post data : `{"template":"{\"name\":\"123\"}"}`
I use python sqlmap.py -r 1.txt --random-agent --hex --threads 1 --dbs -v 3 --dbms=postgresql

Sqlmap must send payload in `{"template":"{\"name\":\"123' AND 1=1\"}"}`
but he send `{"template":"{\\ AND 4398=5276-- MLBb"name\":\"123\"}"}`

Help me please

**Comment by stamparm** [comment]
You haven't said what is the content of `1.txt`

**Comment by lukeoneO** [comment]
`
POST /ViewTemplate.aspx/saveTamplate HTTP/1.1
Host: console.salefreaks.com
Connection: keep-alive
Content-Length: 76
Accept: application/json, text/plain, */*
Origin: http://site.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML,$
Content-Type: application/json;charset=UTF-8
Referer: http://site.com/ViewTemplate.aspx
Accept-Encoding: gzip, deflate
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: rbzid=R88OaKn+nAQHOMbK1jz4R24vCti93YQv1uHbjcfnRyFbBBEkJVpn09vqRFfbEYkcT$

{"template":"{\"name\":\"123\"}"}
`

**Comment by lukeoneO** [comment]
host, origin and referer i changed)

**Comment by stamparm** [comment]
I've pushed a patch related, though.... it is only related to the "double" backslash escaping.

Now, you can't expect in your case that it will inject inside the JSON escaped data which is already inside a JSON data. So, by default (with latest patch) sqlmap will try to inject at the end of the value for `template` parameter (e.g. ....`{"template":"{\"name\":\"123\"}...<SQLi>"}`).

If you want it to inject at specific places (e.g. after the `123`) you can try to use custom injection mark (`*`) like (e.g.): `{"template":"{\"name\":\"123*\"}"}`
