### ISSUE TITLE
if I choose N...

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#2944]
for the remaining tests, do you want to include all tests for 'MySQL' extending provided risk (1) value? [Y/N]

What happens if I choose 【no】??

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by stamparm** [comment]
If you choose `N` sqlmap won't extend the number of tests toward the target. By choosing `Y` sqlmap focuses on identified DBMS (in this case MySQL) and extends the number of different payloads and boundaries just for that same DBMS. Anyway, it is recommended to choose `Y` to get higher success rate of detecting some exotic payloads.
