### ISSUE TITLE
Retrieve column with much text (ex : Article, Comments)

### ISSUE THREAD

**Issue by jammys** [sqlmapproject/sqlmap#2950]
## What's the problem (or question)?
Hello, I am experimenting this great tool and I'm facing a problem.
During a basic sql injection, when I try to get much text, for example an article, sqlmap retrieves only the first lines and put it in a bin file. 

Is there a way for an attacker to get full text in these types of columns?

## Do you have an idea for a solution?
Can we use function like SUBSTR to get the full content of the column step by step?
Or other commands already integrated in sqlmap to achieve it ?

**Comment by stamparm** [comment]
`SUBSTR`-like functions are already being used. You haven't filled issue template, so, it is not clear what seems to be the problem in the first place. This kind of issues are really different among different SQLi techniques.

Please run your case with `-v 3` or `-t traffic.txt` to see what is going on before re-raising the issue again
