### ISSUE TITLE
When testing a parameter with a "+" character in it, sqlmap does not actually inject anything into the parameter.

### ISSUE THREAD

**Issue by j90g43nklfs** [sqlmapproject/sqlmap#2953]
Hi,

It appears that sqlmap does not actually inject anything into a parameter if it contains a "+" character.

For example, I was attempting to test a potential injection point like the one below:
`python sqlmap.py -u "http://foo.bar/test" --data="parameter1=1&paramater+2=2"`

When sqlmap starts testing against "parameter1", the "+" character is replaced with a space " ". For example:
`parameter1=1%29.%29%29%2C%22%28.%27%2C&parameter 2=2`

Additionally, when sqlmap starts testing against "parameter+2", nothing is injected/changed at all. For example, every request sent is the same:
`parameter1=1&parameter+2=2`

Currently running on sqlmap 1.2.2.21#dev.

Thanks!

**Comment by stamparm** [comment]
Now, we have a chicken or the egg problem. All parameter names and values have to be urlencoded. In your case it is not clear whether `+` sign is urlencoded character for " " or it is non-encoded plus sign:

1) In case that it is urlencoded character for " " then sqlmap urldecodes it to " " and then afterwards (by using non-`+` urlencoding) encodes it to `%20`. 
2) In the other case that same character should be urlencoded to `%2b` in the first place (by providing `--data=...parameter%2b2=2`)

**Comment by lukaskuzmiak** [comment]
Hey there,

I think there's an issue connected this, using 1.2.2#stable I'm trying to run 

    sqlmap -u 'http://something' --data="txtLoginID='+and+1=1*+or+''='&txtPassword='+or+''='&cmdSubmit=Login"

For the first few heuristic requests the data being sent out (judging by -v4 output) are:

    txtLoginID=%27+and+1=1+or+%27%27=%27&txtPassword=%27+or+%27%27=%27&cmdSubmit=Login

But after the "[01:08:45] [INFO] testing if (custom) POST parameter '#1*' is dynamic" it seems SQLmap only url-encodes the payload and not the rest of the --data parameter content:

    txtLoginID=' and 1=8562 or ''='&txtPassword=' or ''='&cmdSubmit=Login
    txtLoginID=' and 1=1%27TZKzyh%3C%27%22%3EmoxmUm or ''='&txtPassword=' or ''='&cmdSubmit=Login

The + signs are gone and there are no %20s there .. In my case this breaks the request and I get HTTP 500 back.

**Comment by stamparm** [comment]
@lukaskuzmiak it should be fixed now

**Comment by lukaskuzmiak** [comment]
@stamparm yep, 1.2.3.4#dev fixes it, such a beautiful number :) Thanks!
