### ISSUE TITLE
Tables name export/dump

### ISSUE THREAD

**Issue by z3ro** [sqlmapproject/sqlmap#2955]
I wonder how to export all tables "names only" in db xxx to text file
i have about 700 table most of them repeated, i search for ideas to exlude some tables one of them to use option  -X
now the problem is the number of tables in this db which the terminal window cant view them all after fetching. 

is there any option to export only tables name then i can use option -X with not needed tables.

**Comment by stamparm** [comment]
I am really not sure what's the problem. You want to export all tables "names only"? What does that mean? What's the problem with `--tables`?

**Comment by z3ro** [comment]
hello,
database "xxx" have 700 table, the windows cmd can't view all the tables names in the window
The cmd window not fit 700 line so i cant get all of the tables names
i wish that i clear my issue

**Comment by stamparm** [comment]
You can find all table names inside the output log file. Just take a look into the directory which you get at the end of the run (e.g. `[15:13:59] [INFO] fetched data logged to text files under '/home/XXXX/.sqlmap/output/www.site.com'`). There you'll find a `log` file containing all that data, like this:

```
...
web application technology: Nginx, PHP 5.3.10
back-end DBMS: MySQL >= 5.0
Database: acuart
[8 tables]
+-----------+
| artists   |
| carts     |
| categ     |
| featured  |
| guestbook |
| pictures  |
| products  |
| users     |
+-----------+
```

**Comment by stamparm** [comment]
p.s. also, you can always increase the history size for your "cmd windows" inside its properties (non-related to sqlmap)
