### ISSUE TITLE
Eliminating false-possitive results

### ISSUE THREAD

**Issue by frequencyg** [sqlmapproject/sqlmap#2961]
Hello,
Congratulations for SQLMAP.Its an incredible tool to say the least.As a new guy i would like to ask the following

1. Why does one try detect a injection method,and then it says not injectable.And after relaunch it wont detect a single injection method>
2.What is the solution that covers all tests in once.It might be stupid but is there any way to include them all in?
3.Why does sometimes sqlmap gives me the data retrieval so slow?(server issue,bandwith issue)
Thank you very much!

**Comment by stamparm** [comment]
1) Really not sure what's the question here
2) sqlmap already covers the optimal number of cases. If you want to automatically extend it you can use higher level and/or risk values (e.g. `--level=5 --risk=3`)
3) Data retrieval can be slow for any of network/server reasons: high latency, server's congested connection pool, server's high load (e.g. multiple parallel heavy-query operations), problematic payloads (e.g. `OR` could temporary do the DoS on the server if SQLi is inside the (e.g.) `JOIN` query with huge tables), network latency (e.g. usage of ToR is inherently SLOW), network/server protection solutions (e.g. DROPing connections on sign of an attack without replying back with `RST` could cripple the scanner)
