### ISSUE TITLE
How do I resume the latest dump?

### ISSUE THREAD

**Issue by ekasyahwan** [sqlmapproject/sqlmap#2963]
How do I resume the latest dump?
example: total dump 10 and that has succeed 5
How to start from 6 to 10

**Comment by stamparm** [comment]
Easiest way is to rerun everything with same options. sqlmap shouldn't/won't do requests for which it already has results.

Though, if you want to force from entry "6" to entry "10", please use options `--start` and `--stop` (e.g. `--start=6 --stop=10`
