### ISSUE TITLE
The MySQL UDF shared library crashes MySQL on Windows

### ISSUE THREAD

**Issue by sethjackson** [sqlmapproject/sqlmap#2965]
## What's the problem (or question)?

The `sys_eval` function in the 64-bit MySQL UDF DLL crashes MySQL 5.7.21 on Windows in certain circumstances.
I've only tried a 64-bit version of MySQL and the 64-bit DLL. I'm guessing the 32-bit version
has the same problem.

## Do you have an idea for a solution?

Yes. Rebuild and re-upload the 32-bit and 64-bit MySQL UDF binaries to the repo.
Unfortunately it's currently impossible to build that code on Windows with a recent (VS 2017) toolchain.
I've created https://github.com/sqlmapproject/udfhack/pull/4 as a first step towards a working build on Windows.

Once rebuilt I was able to run the problematic commands without crashing the server.

## How can we reproduce the issue?

1. `mysql> create function sys_get returns string soname 'udf.dll';`
2. `mysql> select sys_eval('net localgroup administrators DOMAIN\User /add');`
3. `ERROR 2013 (HY000): Lost connection to MySQL server during query`

Alternatively:

1. `mysql> create function sys_eval returns string soname 'udf.dll';`
2. `mysql> select sys_eval('');`
3. `ERROR 2013 (HY000): Lost connection to MySQL server during query`

## What are the running context details?

* Windows Server 2008 R2 Standard 64-bit
* MySQL 5.7.21 64-bit
* The 64-bit MySQL UDF DLL in this [repository](https://github.com/sqlmapproject/sqlmap/blob/master/udf/mysql/windows/64/lib_mysqludf_sys.dll_) (decloaked)

**Comment by stamparm** [comment]
"`I'm guessing the 32-bit version has the same problem.`" -> just checked the 32-bit DLL version on oldish MySQL5.1.41 / WinXP 32-bit and everything works as expected

**Comment by stamparm** [comment]
Just tried the 64-bit DLL version on MySQL 5.7.21 / Windows 64-bit and everything works as expected. How to proceed without closing this down as unreproducible?

**Comment by sethjackson** [comment]
Hey @stamparm thanks for looking into this!

Sorry if my report wasn't clear.

`sys_eval` normally works however in specific cases it doesn't like the ones I gave above:

* `select sys_eval('net localgroup administrators DOMAIN\User /add');`
* `select sys_eval('');`

and will crash MySQL.

See the following screenshot:

![crash](https://user-images.githubusercontent.com/6191831/37094737-db8815d0-21e1-11e8-8505-446a49c830a7.png)

In the `net localgroup` case it appears whenever that command fails such as adding a nonexistent user or some other error condition the UDF will crash.

Again this happens with the binaries in this repository.
If I build the 64-bit version myself from source I do not experience the crash.

**Comment by stamparm** [comment]
I would guess that the popen returns `NULL` on erroneous command (https://github.com/sqlmapproject/udfhack/blob/c187c139f0665f1c29df39f31d74d976bd839c15/windows/32/lib_mysqludf_sys/lib_mysqludf_sys/lib_mysqludf_sys.c#L450), while there is no proper check for such cases. I can patch this, though I don't have a 64-bit compile environment up and running for this (though, I have 32-bit -> where I could test this all)

**Comment by sethjackson** [comment]
I don't think that is the problem. I believe the code actually works just the binaries do not contain the latest code or something.

If I build the code directly from `master` (thanks for your patch!) I do not experience the crash anymore:

![fixed](https://user-images.githubusercontent.com/6191831/37097504-a0bcd276-21e9-11e8-83f3-f47e2e617e85.png)

**Comment by stamparm** [comment]
You'll get the crash eventually. Just poke around. I would suggest you to try several: `SELECT sys_eval(NULL)`

**Comment by stamparm** [comment]
The patch has been pushed (https://github.com/sqlmapproject/udfhack/commit/3da0c0892d5b0f7e5bea1acc57017ab4b051333b). I'll have to compile it too. As said, able to compile it for 32-bit. If you could share the 64-bit version it would be great.

When I'll have both I'll push them to master@sqlmap

**Comment by sethjackson** [comment]
Ah right ok.

I can build the 64-bit version and upload.

One quick note would it be better to move the `NULL` check for the argument into `sys_eval_init` and do the `NULL` check for `popen` in `sys_eval`?

Eg.

```c
unsigned int i=0;
if(args->arg_count == 1
&& args->arg_type[i]==STRING_RESULT
&& args->args[i] != NULL){
	return 0;
}
```

This way the user gets an error message:

```
mysql> select sys_eval(NULL);
mysql> ERROR 1123 (HY000): Can't initialize function 'sys_eval'; Expected exactly one string type parameter
```

Furthere `sys_exec` will also crash if `NULL` is passed to it like so:

```
mysql> select sys_exec(NULL);
```

Here is the 64-bit binary built directly from master.

[lib_mysqludf_sys_64.zip](https://github.com/sqlmapproject/sqlmap/files/1789515/lib_mysqludf_sys_64.zip)

**Comment by stamparm** [comment]
@sethjackson can you please rebuild? I have implemented those `NULL` checks into eval/exec init functions too as you've suggested

**Comment by sethjackson** [comment]
Sure I can do that.

Also I'm building with VS 2017 and that upgrades the solution and builds against the Windows 10 SDK.

I'm assuming that will work with older systems but I'm not entirely positive.
I don't have a 64-bit Windows XP box to test on.

It does work on Sever 2008 R2 though.

**Comment by sethjackson** [comment]
Here is the 64-bit library built from master.

[lib_mysqludf_sys_64.zip](https://github.com/sqlmapproject/sqlmap/files/1789610/lib_mysqludf_sys_64.zip)

**Comment by stamparm** [comment]
For some reason I can't use this file you provided. Have you tried it yourself? I am trying it on MySQL 5.7.21 / Windows7 64-bit

**Comment by sethjackson** [comment]
Hmm. That's odd.
It has been working for me and I just downloaded the most recent zip I uploaded and tried it and it is working for me.

I've been building on Windows 10 64-bit and running the binary on Windows Server 2008 R2 64-bit.

Do you have the MSVC runtime installed (specifically the MSVC 2015 x64 runtime)?
They got installed when I ran the MySQL installer.
I think you might need them to run the DLL. Not entirely sure though.

![runtimes](https://user-images.githubusercontent.com/6191831/37103606-9d220352-21f8-11e8-93b5-6a287ad4104d.png)

**Comment by stamparm** [comment]
Lowest common denominator is being searched for (e.g. in this case Win7 64-bit with default MySQL installation -> without any new dependencies). I'll try to build it tomorrow

**Comment by sethjackson** [comment]
Ok. 

I think what I uploaded doesn't work is because my build is not targeting a lower Windows SDK version. I've fiddled around with it trying to get it to work previously with a lower SDK but was unable to. :(

**Comment by stamparm** [comment]
@sethjackson just pushed newly compiled 64-bit version (Win7, MySQL 5.7.21, VS2005). Attaching decloacked version here just in case you want to test it (though, I believe that you should not have problems with it)

[lib_mysqludf_sys.dll.zip](https://github.com/sqlmapproject/sqlmap/files/1793151/lib_mysqludf_sys.dll.zip)

**Comment by sethjackson** [comment]
Awesome thanks!
This does indeed work and I don't experience the crash with `sys_eval` anymore.

Just an FYI it appears this doesn't have the `NULL` check for `sys_get` included.
Eg. `sys_get(NULL)` will still crash MySQL but nobody should really be doing that anyways.

Thanks again!

**Comment by esabilbulbul** [comment]
As you can call the library from mysql, there should not be any problem with the library but the code itself. I suggest to check the parameters you are receiving in the function. 

this repository might help for developing UDF DLLs on Windows with MySql57 /MySQL8 
https://github.com/esabilbulbul/mysql-udf-windows

**Comment by JoanMCD** [comment]
Hello !
@sethjackson With the change to Win 64 bit I have to recompile my mysql_udf_httpget code - is works still fine with 32bit, but not with 64. And I'm not a windows programmer. It's possible to get your hole 64bit project as a new starting point ?

BR Joe
