### ISSUE TITLE
python library methods

### ISSUE THREAD

**Issue by javixeneize** [sqlmapproject/sqlmap#2968]
Hi

Im trying to call sqlmap from a python script. I am calling it via subprocess (s.call(["sqlmap", "-r", filename, "--batch", "--flush-session", "--output-dir=output" + str(i)])

I would like to know how could i call it using the sqlmap library. I have seen that there is a main() method, but it doesnt receive any parameter, so, when i call this method, i receive the expected error saying that there is a missing mandatory option

There is a method called cmdLineParser, that receives a list of arguments, so i have tried the following:

sqlmap.cmdLineParser(["-r", filename, "--batch", "--flush-session", "--output-dir=output" + str(i)])

But it doesnt run any scan

Any help on how could i run this?

Thanks

**Comment by stamparm** [comment]
sqlmap has not been designed to be run as "library" (e.g.: https://github.com/sqlmapproject/sqlmap/issues/2083#issuecomment-238138652). That being said, you have two options to run it "from outside":

1) As a subprocess (you've already tried)
or
2) Through API. See https://github.com/sqlmapproject/sqlmap/wiki/Usage#api-rest-json for details

**Comment by javixeneize** [comment]
Thanks for the answer. Running as subprocess is not very safe as it is open to command injection (https://docs.python.org/2/library/subprocess.html)

I will try with the api though

In any case, would it be a good idea to create a new method that allows sqlmap to be called as a library? I can write this if you want and raise a merge request

**Comment by stamparm** [comment]
"In any case, would it be a good idea to create a new method that allows sqlmap to be called as a library?" -> Have you read a comment I have left above? (https://github.com/sqlmapproject/sqlmap/issues/2083#issuecomment-238138652)

**Comment by javixeneize** [comment]
Sorry to insist, but i think that creating another script (sqlmaplib.py) that can receive as argv the same parameters you are sending via command line (cmdLineOptions.update(cmdLineParser().__dict__)) would be a great addition. It will not mess with the original sqlmap.py file, it will be a new one that will do exactly the same but will ease the integration

Are you ok for me to go and try progressing with this?

**Comment by stamparm** [comment]
Feel free to do it for yourself. Though, I can see that you haven't overly though about the potential problems here. For start, there is no way for you to process the program output nor user interaction (situational prompt questions). Then, you have a multiprocessing mechanism being triggered in the table post-dump processing which I am pretty sure that you'll have problems with.

Please do whatever suits your needs, though I doubt that it will be merged into the master branch

**Comment by javixeneize** [comment]
My idea is quite simple. As it is already taking the data sent by command line, i would like to modify main method, to force it to receive a list of parameters (main((sys.argv[1:])))

The only thing i need to do now is map those parameters to the right key in dict that you are using cmdLineOptions.update(cmdLineParser().__dict__)

I need to find where are you taking that dictionary from. Maybe you could help with this? 

Thanks
