### ISSUE TITLE
Asynchronous RESTful API to interact with sqlmap engine

### ISSUE THREAD

**Issue by bdamele** [sqlmapproject/sqlmap#297]
Design and develop an asynchronous RESTful API to interact with sqlmap engine. This is useful to use/call sqlmap from custom scripts, web interface, third-party tools or similar as opposed to use it from command line or wrap it as in a call similar to os.popen('sqlmap...').

This API will replace the XML-RPC service (#287).

**Comment by daremon** [comment]
Hi @stamparm 

Is there a way to check if sqlmap has finished? Neither /data nor /log seem to offer this unless I missed something.

**Comment by stamparm** [comment]
@daremon yes, there is. 

`http://127.0.0.1:8775/scan/<taskid>/status`

See example in attached picture: 

![screenshot - 06182015 - 12 00 55 am](https://cloud.githubusercontent.com/assets/921555/8219836/227ce690-154d-11e5-975d-de4651a886db.png)

After the task finishes/terminates sqlmap API `status` call manifests like this:

![screenshot - 06182015 - 12 02 01 am](https://cloud.githubusercontent.com/assets/921555/8219857/55d68780-154d-11e5-9b59-c9c2e762ef1c.png)

**Comment by daremon** [comment]
Perfect, thank you!
