### ISSUE TITLE
[feature request] dumping multiple entries of n number in case of partial union technique

### ISSUE THREAD

**Issue by zeshanjum** [sqlmapproject/sqlmap#2970]
there are cases where full union technique is not supported, instead sqlmap dumps limited number of entries, in my case it is always 100, (first 100) limited by the webpage design.
using start and stop command let sqlmap dump table by single entry at a time which is time consuming and boring. 
i think it would be much more convenient if sqlmap is able to dump table entries by multiple of 100 as in my case. dump first 100 in one go , then other hundred in another go and so on. 
what do you think? 
thank you for your time

**Comment by stamparm** [comment]
In majority of cases it is either FULL or SINGLE (aka. PARTIAL) case. Detection of multiple (but partial) cases would be doable, but the usage part would be a nightmare, especially in cases when there is no `LIMIT m,n` mechanism (e.g. in MsSQL). Even retrieval of single (offseted) row is kind of magic in such cases, but the retrieval of multiple rows would be really hard.

Too much hassle for too little gain (IMO percentage of such cases is quite low)
