### ISSUE TITLE
SQL-QUERY

### ISSUE THREAD

**Issue by AVR1234** [sqlmapproject/sqlmap#2972]
Hello, just to ask you if i use parametr --sql-query how to put directory for dump because now all dump find in file log?

**Comment by AVR1234** [comment]
Dont sorry but i dont see your answer?

**Comment by stamparm** [comment]
`--sql-query` is a general option/mechanism not being made for general dumping. Hence, results won't go into special dump directories/files as those same results can be anything. Please use `--dump` if you want to `put directory for dump`
