### ISSUE TITLE
JSON deserialization - inverted behaviour

### ISSUE THREAD

**Issue by koxu1996** [sqlmapproject/sqlmap#2974]
## What's the problem (or question)?
Today I manually found simple injection in posted JSON data, which was not detected by sqlmap.
 I couln't believe it, so I investigated problem and found out that behaviour is swapped:
- choosing to inject data inside:
![option1](https://i.imgur.com/dTO5C9N.png)
- choosing to NOT inject data inside:
![option2](https://i.imgur.com/IUdEUf3.png)

## Do you have an idea for a solution?
Inverting condition in https://github.com/sqlmapproject/sqlmap/blob/d99151ce5a59d2f3ed8cc4dce97d5c0832df50f8/lib/core/common.py#L654

## How can we reproduce the issue?
1. Create following _demo.php_:
```
<?php
$host = "localhost";
$username = "demo";
$password = "demo";
$database = "demo";

$handle = mysql_connect($host, $username, $password);
if (!$handle) {
    die('Could not connect: ' . mysql_error());
}
$db_selected = mysql_select_db($database, $handle);
if (!$db_selected) {
    die ('Could not select : ' . mysql_error());
}

$json_data = json_decode($_POST['q'], true);
$authid= (isset($json_data['authid'])) ? $json_data['authid'] : "";

$result = mysql_query("SELECT * FROM qu_g_authusers WHERE authid='$authid'");
if (!$result) {
    die();
}
$row = mysql_fetch_array($result);
echo $row['username'];
```
2. Run
```
sqlmap -u 'http://localhost/demo.php' --data='q={"authid":"ab7e3c"}' --risk=3 --dbms mysql
```
3. Choose option to inject inside JSON data

## What are the running context details?
* Installation method: pacman
* Client OS: Arch Linux x64
* Program version: 1.2.3#stable

**Comment by stamparm** [comment]
Thank you for this details report. My fault introduced with https://github.com/sqlmapproject/sqlmap/commit/5f2bb88037c67fd14195ac0f19de4284fd89e69a#diff-8faaf95371d4fbf9b3a66a8adc841167L648. Going to patch this moment.
