### ISSUE TITLE
Dump a specific columns

### ISSUE THREAD

**Issue by SoulFunk69** [sqlmapproject/sqlmap#2976]
Hello.
He's possible with sqlmap to dump only a specific columns ?

**Comment by Ekultek** [comment]
-D DB -T TABLE -C COL

**Comment by SoulFunk69** [comment]
No...

Exemple  Database: exemple
Table: exemple
[27 columns]
+---------------+--------------+
| Column        | Type         |
+---------------+--------------+
| ip            | varchar(255) |
| land_online   | varchar(50)  |
| lfd           | int(11)      |
| member        | tinyint(4)   |
| nachname      | varchar(50)  |
| ort           | varchar(50)  |
| plz           | varchar(10)  |
| posteingang   | varchar(12)  |
| rem_anmeldung | text         |
| str           | varchar(50)  |
| tel           | varchar(30)  |
| titel         | varchar(50)  |
| total         | varchar(20)  |
| transfer      | varchar(10)  |
| ts            | int(11)      |
| vnumber       | varchar(100) |
| vorname       | varchar(50)  |
+---------------+--------------+

I just want dump only vnumber,vorname,transfer by example...Possible ? 
Thanks.

**Comment by stamparm** [comment]
`--dump -D database -T table -C vnumber,vorname,transfer`

**Comment by SoulFunk69** [comment]
Thanks a lot ;-) 
A last question, the modsecurityversioned and modseczeroversioned are conciliable with Mssql base ?

**Comment by stamparm** [comment]
Those work only on MySQL (and older versions of ModSecurity)

**Comment by SoulFunk69** [comment]
Thanks for all , and  for this Fantastic Tool you're awesome developer...

**Comment by mikedesu** [comment]
attempting to pass columns separated by commas does not work...

```
-C test1,test2
```

attempts to grab a column named "test1,test2"

attempting to pass multiple column flags results in one column being enumerated before another...

```
-C test1 -C test2
```
