### ISSUE TITLE
SqlMAP Dump Problem

### ISSUE THREAD

**Issue by Comancheroo** [sqlmapproject/sqlmap#2995]
Hello,

There are no problems with small number of index tables.
When the table size is large, sqlmap dump is failing as follows.

[WARNING] large compressed response detected. Disabling compression
[WARNING] something went wrong with full UNION technique (could be because of limitation on retrieved number of entries). Falling back to partial UNION technique
[WARNING] large response detected. This could take a while
[WARNING] too large response detected. Automatically trimming it
[WARNING] the SQL query provided does not return any output
[WARNING] unable to retrieve the entries for table 'tbl' in database 'db'

I can dump it from the browser(address bar). But sqlmap unable to retrieve the entries for table.

**Comment by stamparm** [comment]
"Large compressed response detected" triggers on 50MB of total raw size of compressed result. So, basically, you are suggesting that you are expecting output with >100MB and that sqlmap should be ok with it? There are numerous cases where uncompressing of such large responses is not a good idea (e.g. some protection mechanisms are returning compression bombs in case of attack detection)

Anyway, please update to the latest revision and retry. sqlmap will disable the compression (as it did in your case), though it will retry to get it in uncompressed form.

**Comment by stamparm** [comment]
@Comancheroo ping. Have you tried to dump again with the latest revision?
