### ISSUE TITLE
How to specify an account

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#2996]
If I already know the other account and its password, how can I use the specified account to extract the database

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by huitc** [comment]
or something

**Comment by huitc** [comment]
or any other operation except that

**Comment by huitc** [comment]
Another example, --os-shell --sql-shell

**Comment by stamparm** [comment]
This is SQL injection. You can't just switch accounts whenever you want. You can try to take a look into the option `-d`, but other than that I doubt that you'll make through SQL injection. Though, you should try to expand the attack on other services and try to reuse the credentials
