### ISSUE TITLE
how to remove "sqlmap/1.2.3.34#dev (http://sqlmap.org)"

### ISSUE THREAD

**Issue by mbahmbul** [sqlmapproject/sqlmap#3001]
how can i remove sqlmap/1.2.3.34#dev (http://sqlmap.org) at the end of script attack
so the server logs don't know if i using sqlmap for pentesting his website
here is the example screenshot
![1521572102100](https://user-images.githubusercontent.com/35336254/37676619-ff760424-2caa-11e8-847c-b8654dc704dc.jpg)

**Comment by Ekultek** [comment]
Use a different user agent

**Comment by stamparm** [comment]
```
    --user-agent=AGENT  HTTP User-Agent header value
    --random-agent      Use randomly selected HTTP User-Agent header value
```
