### ISSUE TITLE
sqlmap returning blank data

### ISSUE THREAD

**Issue by xeocops** [sqlmapproject/sqlmap#3002]
## What's the problem (or question)?
when dumping data from database, sql map returning no data.... it's not NULL just empty...

## Do you have an idea for a solution?
no idea, i am a begineer..

i am using this code...
sqlmap.py -u http://www.example.com/id=xx --random-agent -D database_name -T table_name -C column_name --time-sec=30 --dump

![github](https://user-images.githubusercontent.com/37610616/37696670-647f9f24-2ca6-11e8-86e4-fd45cd9c0887.png)

**Comment by stamparm** [comment]
You have been presented with an Issue template to fill any useful data. You failed to do it.

**Comment by 4val0v** [comment]
@stamparm A similar problem occurs on different operating systems
![image](https://user-images.githubusercontent.com/11297476/37717050-90b5cb54-2d28-11e8-8a48-54a12b5fc5c6.png)
After restarting, I watch the following picture:
![image](https://user-images.githubusercontent.com/11297476/37717234-c6e54344-2d28-11e8-8232-d8d8100a3f4f.png)

This phenomenon can be found in different cases, personally I only know two such:

1. If you fix the vulnerability
2. Switch the site into development mode, this mode ignores all requests and gives one static page
___
But it is not always the case
sometimes I'm helped by the command `--flush-session` _(or find a new attack vector)_

**Comment by xeocops** [comment]
![github](https://user-images.githubusercontent.com/37610616/37750624-0c2fe908-2d5c-11e8-80ef-1a82fe7238d9.png)
@stamparm is this you are talking about... i don't know much about injection techniques.....
@4val0v do you find any solutions yet?

**Comment by xeocops** [comment]
@stamparm column is in  text format
