### ISSUE TITLE
Because there are 2 slash that cause failure?

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3004]
[INFO] checking if UDF 'sys_eval' already exist
[INFO] checking if UDF 'sys_exec' already exist
[INFO] detecting back-end DBMS version from its banner
[INFO] resumed: [[u'5.6.24']]...
[INFO] retrieving MySQL plugin directory absolute path
[INFO] resumed: [[u'C:\\Program Files\\MySQL\\MySQL Server 5.6\\lib\\plugin\\']]...
[WARNING] (remote) Table 'xo.sqlmapfile' doesn't exist
[WARNING] it looks like the file has not been written (usually occurs if the DBMS process user has no write privileges in the destination path)
[ERROR] there has been a problem uploading the shared library, it looks like the binary file has not been written on the database underlying file system
do you want to proceed anyway? Beware that the operating system takeover will fail [y/N]

C:\\Program Files\\MySQL\\MySQL Server 5.6\\lib\\plugin\\
Because there are 2 slash that cause failure?

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by stamparm** [comment]
Not sure why would "2 slash" cause the failure. You had a better probable reason in the status text: `usually occurs if the DBMS process user has no write privileges in the destination path`.

Without you having a access to the target server itself, this is hard to debug. In the other case, if you have an access there you should rerun sqlmap with `-v 3`, take a look into used payloads and try to manually use them (e.g. inside browser). Then, you should take a look into the target's filesystem to see whether there have been some changes or not. In case of no changes, you should try to manually change the target location (inside the payload itself) and see whether you had success. In case of success, you could respond back with observations and possible ways how to patch the sqlmap (if there was a problem in sqlmap in the first place)
