### ISSUE TITLE
sqlmap can not dump user table

### ISSUE THREAD

**Issue by jackpit110** [sqlmapproject/sqlmap#3006]
I know about waf and also know about blacklist
I use the latest version of sqlmap
user table have columns like ID, Username, Password, UserId
I can dump this columns from other tables like UserLog ( UserId,Username )
But when I try to dump from user table sqlmap can not do it
I use this command : -T user -C ID,Username --dump

**Comment by stamparm** [comment]
You've missed to enter anything useful. I am attaching the screenshot of a template that maybe was blocked at your side by some browser plugin.

![1](https://user-images.githubusercontent.com/921555/37907433-657ef4f2-3105-11e8-8968-5295b839e271.png)
