### ISSUE TITLE
How add [ ] for table name

### ISSUE THREAD

**Issue by jackpit110** [sqlmapproject/sqlmap#3012]
I want to add [ ] for table names
How should I can do it?
For example sqlmap try to do it like this : SELECT Username FROM Users
I want to change it to : SELECT Username FROM [Users]

**Comment by stamparm** [comment]
Have you tried to just provide it to sqlmap with `-T [Users]`? It works out of box. Though, you should use it only on MsSQL-alike DBMSes as on other DBMSes it has a totally different meaning (than escaping)
