### ISSUE TITLE
BUG csrf-token with https

### ISSUE THREAD

**Issue by z3ro** [sqlmapproject/sqlmap#3018]
C:\py>python sqlmap.py -r x.txt --csrf-token=**app_login[_token]**
        ___
       __H__
 ___ ___[)]_____ ___ ___  {1.2.2.13#dev}
|_ -| . ["]     | .'| . |
|___|_  [)]_|_|_|__,|  _|
      |_|V          |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user'
s responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not respon
sible for any misuse or damage caused by this program

[*] starting at 17:16:30

[17:16:30] [INFO] parsing HTTP request from 'x.txt'
[17:16:30] [INFO] testing connection to the target URL
sqlmap got a 301 redirect to 'https://xxxxx.frlogin'. Do you want to follow? [Y/n] n
[17:16:33] [CRITICAL] anti-CSRF token 'app_login[_token]' can't be found at 'http://xxxxxxxxxxx:80/login'. Yo
u can try to rerun by providing a valid value for option '--csrf-url'

---------------
what i notice, the project goes and request host as http not https couse that he cant found the parameter 
i tryed to set --csrf-url and same thing.

my request file:

POST /login HTTP/1.1
Host: xxxxxxxxxxx
User-Agent: Mozilla/5.0 (Windows NT 6.1; rv:59.0) Gecko/20100101 Firefox/59.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: https://xxxxxxxxxxx/login
Content-Type: application/x-www-form-urlencoded
Content-Length: 122
Cookie: _ga=GA1.2.758295336.1522399897; PHPSESSID=aguorq56n3t8b1t861n4tcl3t1
Connection: close
Upgrade-Insecure-Requests: 1
app_login[username]=aaa&app_login[password]=bbbb&app_login[_token]=JTEy-ofSi-rYRuO4T3AFMo5GY5uyGtNpMYRqvLQ-Vik

**Comment by stamparm** [comment]
What is the bug/Issue here?

You've provided HTTP URL, target redirects your request to the HTTPS one (most probably because it finds non-valid Cookie or provided details inside the POST body), you say NO to the redirect and you are finding sqlmap to be a problem here because it doesn't go to the HTTPS (while you said to it to not go there in the first place)??

Sorry, I can't understand what's the problem in the first place

**Comment by williamhana** [comment]
I found something like that nearby
Im struggling on it but the reason is anti-csrf token 

could it be like what Im thinking?
