### ISSUE TITLE
--prefix not exactly doing what it supposed to do in version 1.2.4.2#dev 

### ISSUE THREAD

**Issue by romanzaikin** [sqlmapproject/sqlmap#3025]
## What's the problem (or question)?
I have created a simple website to show my students how to use your sqlmap tool.
I have used the following simple sqlmap command:

python sqlmap.py -u "http://10.10.10.56/challenge/SQLI/api.php?username=aaa&password=bbb" --threads=2 --dbs --prefix="user_" --flush-session -p "username"

I expected that every request will start now with "user_" because I have created the following simple code in the backed to protect against users that simply just run the command without really understand what happens behind the sense:

if (strpos($_GET["username"],"user_") !== FALSE)  
             $username = str_replace("user_","",$_GET["username"]);

else       die("wrong username parameter");

So, after I run the command sqlmap wrote that there is no SQL Injection, I was surprised! how this is possible.
I have manually performed the SQL Injection in the same task and showed that indeed there is SQL Injection.
 
So, I have created the following tamper script, again nothing special just a logger:

from lib.core.enums import PRIORITY
def tamper(payload, **kwargs):
  file("payload.log","a").write(payload+"\n")
  retVal = payload
  return retVal

and I have found that the --prefix not really working!

look:

aaa**user_** AND MAKE_SET(6708=6708,5150)-- qSPF
aaa**user_** AND MAKE_SET(1852=6308,6308)-- SPFG
aaauser_ AND MAKE_SET(6708=6708,5150)-- XAeg
aaauser_ AND MAKE_SET(5956=1840,1840)-- mlmL
aaauser_ AND MAKE_SET(6708=6708,5150)-- cJGV
-5702user_ OR MAKE_SET(6990=6503,6503)-- XuxB
-1183user_ OR MAKE_SET(8981=8981,4121)-- TRmZ
-4904user_ OR MAKE_SET(2047=3578,3578)-- SAWs
-3791user_ OR MAKE_SET(8981=8981,4121)-- SfDf

it's not really start with the prefix I have entered to the command, it starts with the username parameter and only after the prefix. 

## Do you have an idea for a solution?
If you want, I can try to fix it.

## How can we reproduce the issue?
I will upload the challenges system to my github and provide a link in the next week.

**Comment by stamparm** [comment]
1)
```
$ python sqlmap.py -hh | grep prefix
    --prefix=PREFIX     Injection payload prefix string
```

2) https://github.com/sqlmapproject/sqlmap/wiki/Usage#custom-injection-payload

3) Injection payload prefix is a prefix before injection payload, but that doesn't mean that it "invalidates" or "replaces" the original value. I believe that you've misunderstood that whole concept. Prefix and suffix mechanism(s) are used for adapting the payloads to work in the first place (to fit into the injectable SQL query). In most cases those are just non-alphanumeric strings that are "patching" the context. Hence, your use case `user_` doesn't make any sense as it is more suitable to be put into the URL than into the `--prefix`.
