### ISSUE TITLE
RequestVerificationToken, Anti ~CSRF-Token

### ISSUE THREAD

**Issue by Chokrii** [sqlmapproject/sqlmap#3028]
## What's the problem (or question)?
Hi Sqlmap Team,
Hope my message find you well, i have a target protected by RequestVerificationToken, this param sent through a cookie not in Data body dose sqlmap handle this kind of case ?
i've tried couple of times but i always get Error 500 which says Token Incorrect

**Comment by stamparm** [comment]
Nope. `RequestVerificationToken` is being set by Javascript and we don't support evaluation of Javascript to find out those kind of anti-CSRF values
