### ISSUE TITLE
MS ACCESS , trouble enumerating ...anything?

### ISSUE THREAD

**Issue by SQLprodigy** [sqlmapproject/sqlmap#3033]
Hello , 

I have found injection points in in an ACCESS DBMS...

Unfortunately I can only fingerprint the back-end dbms , and cannot enumerate dbs or tables . Any tips?

SQLmap is telling me it is not possible to enumerate these things in ACCESS.. thanks

**Comment by stamparm** [comment]
In MsAccess there are no system tables (at least not readable) from where you can retrieve stored table names and column names. Hence, common tables and common column brute force search is being used. Though, in some cases, when non-standard table and column names are used it is up to you to find/search for those identifier names (and provide via `-T` and `-C`). C'est la vie
