### ISSUE TITLE
ERROR unable to retrive the table names for any database 

### ISSUE THREAD

**Issue by CarolinaDixon** [sqlmapproject/sqlmap#3034]
## What's the problem (or question)?
Sqlite | struggling with a sqli database, after using --tamper = "", I was able to get the name of the database, but still did not find the name of the tables. (ERROR unable to retrieve the table names for any database)
I could not continue after many attempts.

## Do you have an idea for a solution?

In these cases, how should we move mainly? What to try?
What commands should I use to bypass the error?

## How can we reproduce the issue?
I know very well that I'm giving little information but I had closed the session, I just wanted to know "generically" how we should "move"
Thanks, top project!
Best Regards.

**Comment by stamparm** [comment]
You really haven't provided any useful information. Not sure how to proceed here than to close it down
