### ISSUE TITLE
Sqlmap new web page charest , how i can help ?

### ISSUE THREAD

**Issue by TheArmOfLegion** [sqlmapproject/sqlmap#3045]
Hello ,
i got this : 
[WARNING] unknown web page charset 'rdbuna'+'. Please report by e-mail to 'dev@sqlmap.org'

how i can help ?

**Comment by stamparm** [comment]
As message said, you could contact us via email (`dev@sqlmap.org`). Instead, I'll reply here. In some cases charsets could be incompatible with the Python's `codecs` library, but if possible we can "adapt" the web charset to the Python's matching character encoding/charset. In this (your) case there is no matching, hence there is nothing to be done. Most probably a web developer made a mistake when making the web page itself.
