### ISSUE TITLE
sqlmap doesnt work with POST requests that contain a json

### ISSUE THREAD

**Issue by javixeneize** [sqlmapproject/sqlmap#3046]
Hi

Im running SQLMap on an application that sends a POST request. 

The parameters sent in the request are not in the typical format of id=value&id2=value2. It sends a JSON  like this:

{'id':'value', 'id2':'value2'}

What SQLMAP is trying to do here is to add the payloads out of the JSON, at the end of the parameters sent, and therefore, the application responds with a 500 error code, as the JSON is malformed

Could this be added as an ehnancement?

Thanks

**Comment by stamparm** [comment]
JSON uses double-quotes to enclose string values, not single quotes.

References:
https://www.json.org/ - `A value can be a string in double quotes, or a number, or true or false or null, or an object or an array. These structures can be nested.`
https://jsonlint.com/ - `Always use double quotes, always quotify your keys, ...`
