### ISSUE TITLE
SQLMAP missing a mandatory option!! HELP!

### ISSUE THREAD

**Issue by Zeron1997** [sqlmapproject/sqlmap#3048]
Hello GitHub,

I'm new to the forum and new with sqlmap, I hope anyone can help me with this.
I have downloaded sqlmap and python27. 

I opened up cmd to write the code for starting sql like this and get this error:
![knippie bureau](https://user-images.githubusercontent.com/38378758/38768873-642d0234-3ffa-11e8-928f-8c86fd4c334c.PNG)

also this one not work either:
![knippie bureau2](https://user-images.githubusercontent.com/38378758/38768874-68923dc6-3ffa-11e8-8d55-7d52ecba17d7.PNG)

Yesterday it worked for me I dont know how I did it but I used some command like --sqlmap-shell.
Can anyone give me the right commands to fix this I'm on windows 10 

Thank you,

**Comment by noob2noob** [comment]
Same here

**Comment by stamparm** [comment]
Unable to reproduce. Find screenshot attached. Npt sure how to help you.

![123](https://user-images.githubusercontent.com/921555/38778192-e018194a-40b5-11e8-85a8-ac1d0c33c4bd.png)

**Comment by stamparm** [comment]
p.s. usually this kind of behavior can be spotted when users copy/paste commands from Internet. In lots of cases forum software changes characters like `-`, `'` and `"` to some other similar Unicode representations

**Comment by Zeron1997** [comment]
@stamparm its not that I typed it myself. But anyway maybe you can look closer into the problem because many people got this issue. Anyway thanks

**Comment by stamparm** [comment]
You haven't typed it yourself? Then most probably I was right. If you copy pasted from somewhere on the Internet it is your fault. If not, then please explain "its not that I typed it myself".

Many people got this issue because they just know how to copy-paste invalid stuff from Internet

**Comment by stamparm** [comment]
p.s. also, it would be nice to paste those same commands here so I could really see what is going on. Raising this kind of Issues without ANY useful data usually leads to instant closing as Invalid

**Comment by drclay45454** [comment]
If you really want to solve this problem then download the python version 2.7.18 or something similar to that (mainly python 2 versions are somewhat accessible for the sqlmap ) if you are having python 3 version then this sort of message is somewhat expected " THIS IS THE ONLY MAJOR solution"
note:if  you are already having a phyton 3 version then first unistall it including all files from your drive then download the above said version
