### ISSUE TITLE
Hash bruteforce

### ISSUE THREAD

**Issue by Kuhitacop** [sqlmapproject/sqlmap#3049]
It's possible to give a hash to sqlmap and crack it? I really like the bruteforce that adds suffix to your wordlists
If not, which tool uses sqlmap to bruteforce SHA1 hashes?
I read all wiki and -hh and nothing found
Thanks!

**Comment by stamparm** [comment]
Sorry, but sqlmap can't be used as a standalone hash-cracking tool. It doesn't use any other tool as the mechanism for cracking is implemented inside.

**Comment by stamparm** [comment]
@Kuhitacop there is an experimental (hidden) option from last commit:

`--crack=HASHFILE      Load and crack hashes from a file`

**Comment by huitc** [comment]
hashcat? @Kuhitacop

**Comment by Kuhitacop** [comment]
> 
> 
> @Kuhitacop there is an experimental (hidden) option from last commit:
> 
> `--crack=HASHFILE Load and crack hashes from a file`

oh that's very nice thanks!

**Comment by huitc** [comment]
faster than hashcat? or same?
