### ISSUE TITLE
Feature request - Periodic status code summaries

### ISSUE THREAD

**Issue by ScatteredThoughts** [sqlmapproject/sqlmap#3053]
I have seen that sqlmap will warn about certain status codes which may indicate issues which can interfere with the results. It would be nice if there was an option to get a periodic summary of status codes received, by count and percentage, instead of waiting until the end of the run to see that perhaps all of the requests gave a 401, for example. This would be useful for when batch mode is used.

**Comment by stamparm** [comment]
Not sure for how long do you expect sqlmap to run if something is wrong. Usually, sqlmap stops in those kind of cases. There are already lots of options/switches that nobody uses and there should be a really good reason to implement a new one. Sorry, this doesn't look like a good reason/case.

**Comment by huitc** [comment]
Make something that can alert user (stop and show the payload, Whatever that guy has turned on `-v 3+` or not) 
 when he get `401` or other code (user-defined values)
