### ISSUE TITLE
i ran cmd as administrator i typed cd c:\Python27 and typed python.exe sqlmap.py -h why did it say access is denide and how do i fix that when i typed pip.exe why did it say Fatal error in launcher:Unable to create process using '" and how do i fix the problem     

### ISSUE THREAD

**Issue by neo1230** [sqlmapproject/sqlmap#3054]
## How can we reproduce the issue?

1.
2.
3.
4.

## What are the running context details?

* Installation method (e.g. `pip`, `apt-get`, `git clone` or `zip`/`tar.gz`):
* Client OS (e.g. `Microsoft Windows 10`)
* Program version (`python sqlmap.py --version` or `sqlmap --version` depending on installation): 
* Target DBMS (e.g. `Microsoft SQL Server`): 
* Detected WAF/IDS/IPS protection (e.g. `ModSecurity` or `unknown`):
* SQLi techniques found by sqlmap (e.g. `error-based` and `boolean-based blind`):
* Results of manual target assessment (e.g. found that the payload `query=test' AND 4113 IN ((SELECT 'foobar'))-- qKLV` works):
* Relevant console output (if any):
* Exception traceback (if any):

**Comment by neo1230** [comment]
when i type something and have finshed giving a comment why does my comment get changed 
and how do i make sure my comment doesn't get changed

**Comment by stamparm** [comment]
This all looks like a big mess. Not sure which comment needs to not get changed. Also, not sure why `pip.exe` issues are listed here. You have some fundamental problems in your Python installation in the first place. Please fix it before getting back here as this is for sqlmap issues only
