### ISSUE TITLE
SQLmap cannot dump

### ISSUE THREAD

**Issue by azams** [sqlmapproject/sqlmap#3062]
Hi, i have a case here.
I manage to do manual injection using this payload :
`(select+sleep(3)+from+dual+where+database()+like+'%%')`

and i am successfully grab the table & column name using this :
`(select+sleep(3)+from+information_schema.tables+where+(select+count(*)+from+information_schema.tables+where+table_schema='random_db_name'+and+table_name+like+'________')>0)--+`

`(select+sleep(3)+from+information_schema.columns+where+(select+count(*)+from+information_schema.columns+where+table_schema='random_db_name'+and+table_name='random_table_name'+and+column_name+like+'________')>0)--+`

All those response code is 500 and i tried to use --ignore-code=500 and --level=5 but it fails when using SQLmap..

How can i reproduce this attack in sqlmap?

**Comment by stamparm** [comment]
Not sure how 500 has any relevance to time-based SQL injection. Also, I am very skeptic about your time-based SQLi and I am doubting that it is SQLi in the first place.

My wild guess is that you've just copy pasted the payload from some GUI web assessment tool in hope that sqlmap will find the SQLi, while not being aware that it could be a false-positive in the first place.

As you claim that you are able to retrieve the table names, you should be also able to retrieve the DBMS banner itself (in this case it is MySQL's `VERSION()`). Please get back its content and put here the results (along with at least one usable payload as you've given for table names.

**Comment by azams** [comment]
Actually, sqlmap was able to detect it but it said its a false positive since it returns 500, and thats why i am using --ignore-code.

![screen shot 2018-04-25 at 01 30 19](https://user-images.githubusercontent.com/6146270/39206780-88058560-4828-11e8-963e-daf1ced0fc3d.png)

![screen shot 2018-04-25 at 01 35 55](https://user-images.githubusercontent.com/6146270/39207010-1125d5ca-4829-11e8-8855-d4d55abee24b.png)

After that i tried to verify it manually and yes, the response was delayed.

Here is my payload to retrieve the version.
(select+sleep(5)+from+dual+where+version()+like+'5.5.56-%')
and here is the payload to make sure if its the correct version.
(select+sleep(5)+from+dual+where+version()='5.5.56-mariadb')

![screen shot 2018-04-25 at 01 24 50](https://user-images.githubusercontent.com/6146270/39206825-a1f94a24-4828-11e8-871b-9a33acc83b45.png)

Btw, thanks for your response @stamparm :)

**Comment by azams** [comment]
Sorry @stamparm , i forgot to attach the payload and screenshot when i got the table name.

Here is my payload : 
`(select+sleep(5)+from+information_schema.tables+where+database()='redacted_database_name'+and+table_name+like+'sid')--+`

and here is the screenshot : 
![screen shot 2018-04-25 at 10 06 28](https://user-images.githubusercontent.com/6146270/39224328-ff421e52-4870-11e8-8c69-96671d3db965.png)

**Comment by stamparm** [comment]
Well, if you are able to run the Burp you could try to run those payloads that fail. Also, you could try to modify them in a way that could work. I really can't say what is wrong without any useful data. My first guess would be that the character `-` is filtered, but as said, I am not running the Burp at your side

**Comment by azams** [comment]
Sorry for my late reply. The character `-` is not filtered. as you can see on my screenshot, i am using it on my payload.
What kind of data do you need? i'll try my best to provide it but i will mask few things that could leak the host information.

Thanks.

**Comment by stamparm** [comment]
I've said the following `Well, if you are able to run the Burp you could try to run those payloads that fail.`. Run sqlmap with `-v 3` and retry payloads that fail (right before false-positive detected).

Also, out of all payloads only that one PARTIALLY worked. You have more than enough payloads to try. sqlmap is not an Issue here - you should investigate yourself what is going on.
