### ISSUE TITLE
Help with sql-shell

### ISSUE THREAD

**Issue by ApTemkA73** [sqlmapproject/sqlmap#3072]
Vulnerability blind:
```
Parameter: Host #1* ((custom) HEADER)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: site.ru' AND 5562=5562 AND 'xHKa'='xHKa
---
web application technology: Nginx, PHP 5.4.41
back-end DBMS: MySQL 5
```

banner:    '5.5.40-0+wheezy1'
current user:    'root@localhost'
current database:    'domains'
current user is DBA:    True

I want to fill the shell or change some data in the table, is it possible? The way to fill the shell can not find out. Mysql gives /var/lib/mysql
When using UPDATE/INSTERT writes:
[WARNING] execution of non-query SQL statements is only available when stacked queries are supported

**Comment by stamparm** [comment]
You have MySQL which inherently is not prone to stacked queries (I've seen it working in small percentages). Hence, the answer is not, you won't be able to run non-SELECT statements in your case
