### ISSUE TITLE
i got ERROR 2003 (HY000): Can't connect to MySQL server on 'localhost' (10061) 

### ISSUE THREAD

**Issue by neo1230** [sqlmapproject/sqlmap#3077]
## How can we reproduce the issue?

1.
2.
3.
4.

## What are the running context details?

* Installation method (e.g. `pip`, `apt-get`, `git clone` or `zip`/`tar.gz`):
* Client OS (e.g. `Microsoft Windows 10`)
* Program version (`python sqlmap.py --version` or `sqlmap --version` depending on installation): 
* Target DBMS (e.g. `Microsoft SQL Server`): 
* Detected WAF/IDS/IPS protection (e.g. `ModSecurity` or `unknown`):
* SQLi techniques found by sqlmap (e.g. `error-based` and `boolean-based blind`):
* Results of manual target assessment (e.g. found that the payload `query=test' AND 4113 IN ((SELECT 'foobar'))-- qKLV` works):
* Relevant console output (if any):
* Exception traceback (if any):

**Comment by stamparm** [comment]
This is neither sqlmap Issue or SQL injection. Most probably your server has misconfiguration issues OR the MySQL instance there just stopped working without automatic restart.

**Comment by neo1230** [comment]
i manged to fix that problem

**Comment by neo1230** [comment]
i manged to fix  ERROR 2003 (HY000): Can't connect to MySQL server on 'localhost' (10061) 
and now i have got ERROR 1045 (28000): Access denied for user '-root'@'localhost' (using password: YES 
and i need help fixing it and i cant apply the setttings of MySQLInstanceConfig.exe and i get an error
saying the security settings could not be applied to the datebase because the connection has
failed with the follwing error nr.1045 access denied for user 'root@local'host'(using password:yes)
if a personal firewall if runnning on your machine please make sure you have opened
the tcp port 3306 for connections. otherwise no client application can connect to the
server after you have opened the port please {retry} to apply the security settings.
if you are re-installing after you just uninstalled mysql server please note the data
directory was not removed automatically Therefore the old password from your last 
installation is still needed to connect to the server in this case please select skip
now and re-run the configuration wizard from the start menu.
