### ISSUE TITLE
redirect 301 and 302

### ISSUE THREAD

**Issue by hackdrug** [sqlmapproject/sqlmap#3082]
i am doing sqlmap attack to https, it is vulnerable to sql. then i got redirect alert 301 or 302 and asking blablabla [y/n] , after i enter y or n, it will stop the sqlmap process. how can i fix/bypass it?   thanks in advance

**Comment by stamparm** [comment]
It is fairly trivial. If you've provided URL with GET and/or POST data no matter what you answer to 301 or 302 testing should continue.

Can you please give a complete console output with that same problematic behavior?

**Comment by hackdrug** [comment]
hey men, it is weird that when i tried it again, after i enter the y or n its works again.. btw thanks for you respond. you can close this issue
