### ISSUE TITLE
Generate JSON report after sqlmap test

### ISSUE THREAD

**Issue by javixeneize** [sqlmapproject/sqlmap#3094]
Hi
sqlmap generates a text file with the request that is vulnerable to injection, the payload used etc... 

As an improvement, would it be a good idea to have an option to generate this report as a JSON file?

It should not be difficult to parse it and convert to that format

Thanks

**Comment by stamparm** [comment]
Run it through its API interface and you'll get everything served in JSON. More info can be found at https://github.com/sqlmapproject/sqlmap/wiki/Usage#api-rest-json
