### ISSUE TITLE
--dump :can‘t display the the original data, like garbled

### ISSUE THREAD

**Issue by EverChisato** [sqlmapproject/sqlmap#3097]
##The grabled in some system
When I use ths sqlmap in the **kali 2018.2(2.0)** to read the password in the SQL SERVER , the original data is encrypted with MD5 , but the result is garbled.
I run with this command:
`python sqlmap.py -u 'xxx' --dbms mssql -D xxx -T xxx -C 'adminuser,psw'  --dump `
 and I also run add the --charset=gbk and --charset=utf-8 .
but it doesn't work 

I update the sqlmap **latest** but it also doesn't work.
I also add the  `# -*- coding: utf-8 -*-`  in the file of sqlmap.py ,but it also doesn't work. 
I run this in parrot 3.11(the lastest version ), it  appear the same problem.
I download the latest version of sqlmap , and run on window xp ,it appear the same problem.
![image](https://user-images.githubusercontent.com/25126812/39966716-3dacad6c-56e3-11e8-8ee5-70557df80e4a.png)

but the Chinese  is appeared normal 
![image](https://user-images.githubusercontent.com/25126812/39966763-c2be7896-56e3-11e8-8fd1-d49dac4a12cb.png)

##The correct dispaly
However, I use the old version of kali1.08 and kali 2017.3 ，it can display the original data without the garble.

The correct pasword would be like this . It is run on windows xp with the sqlmap without python.
![image](https://user-images.githubusercontent.com/25126812/39966786-10f33696-56e4-11e8-895d-89a996e5d6cd.png)

**Comment by stamparm** [comment]
(MD5) hashes are not always encoded in plain text (hex). They are sometimes stored in binary format.

https://github.com/sqlmapproject/sqlmap/wiki/Usage#binary-content-retrieval

Rerun with `--fresh-queries --binary-fields pws`
