### ISSUE TITLE
Feature: Injection in path parameters

### ISSUE THREAD

**Issue by freetom** [sqlmapproject/sqlmap#3098]
Afaik sqlmap atm supports the injection within POST and/or GET parameters. I'd like to suggest the implementation of the support for the path parameters.

To clearify, let's see an example URL:
`www.website.com/a/b`

The previous URL contains "/a/b" as path. Depending on the implementation, the path may contain parameters that can be used by the web server upon reception to compute a response. Therefore, injections in the path are possible.

I'd suggest to add an option to indicate that we want injection on the path parameters and another option to specify the placeholder in the URL that should be replaced with the attempts of injections.

What do you think?

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/Usage#uri-injection-point
