### ISSUE TITLE
sqlmapAPI support - couple of questions

### ISSUE THREAD

**Issue by javixeneize** [sqlmapproject/sqlmap#3107]
Hi

I was referred in a different issue to use the API to retrieve the testing report in JSON format. It looks close to what i want, but i need a couple of clarifications:

1 -What i have seen is that you have to connect the api first, and then, you need to run the scan from there, but what i want to do is to automate this scan. Is there any way i can do it, like calling an endpoint to connect to the client, and another one to run the scan?

2 - On the same hand, from the client side, is there any way of being notified when the scan is finished, other than be calling the status service until it says its finished?

3 - The last one and the most important one... If i run two scans, which information will i have? Will i have both reports available, or it will only return the most recent one?

Thanks

**Comment by javixeneize** [comment]
Ok, i have it now... You need to send a post request to http://localhost:8775/scan/TASKID/start with a JSON with the option url or requestFile.

It might worth adding this to the doc for clarity. I think this feature is great

Thanks

**Comment by stamparm** [comment]
`It might worth adding this to the doc for clarity` <- not sure which part is unclear here https://github.com/sqlmapproject/sqlmap/wiki/Usage#api-rest-json? Everything is explained there. You don't have to post JSON request manually (as I can see in your case you just wanted to test the feature - hence no need for raw JSON POST) - just use the client (`-c`) feature of `sqlmapapi.py` to connect to the server (`-s`)
