### ISSUE TITLE
Precon Mechanism

### ISSUE THREAD

**Issue by akmlvl** [sqlmapproject/sqlmap#3110]
### First This is a timebased Mysql Injection (query SLEEP)
in Some cases when the request times out sqlmap automatically disables precon mechanism well that caused dumping problems for me further more not a single line is correct

![precon1](https://user-images.githubusercontent.com/16985737/40277427-ce3ad452-5c16-11e8-96ed-9f0d5de5bb6e.png)
![precon2](https://user-images.githubusercontent.com/16985737/40277430-d1fc9882-5c16-11e8-9630-c4347e9343eb.png)

### So i had to change The code to force Precon
![preconsol](https://user-images.githubusercontent.com/16985737/40277463-266be918-5c17-11e8-80a2-00111a342384.png)

### And The Data is dumped correctly Now
![yeah](https://user-images.githubusercontent.com/16985737/40277481-858ec6a4-5c17-11e8-913c-611d730e71e1.png)

### So What I'm Trying To say You can add A **--Force-precon** Switch that's all

**Comment by stamparm** [comment]
Turned off this automatic pre-connect disabling mechanism with the latest commit. That piece of code is from times when pre-connect has been in experimental phase.

Now, there are small chances that somebody will indeed have problems with the pre-connect mechanism (there is a hidden option `--disable-precon` to turn it off manually). I'll wait for further similar issues to address them (and maybe do some other patch related).
