### ISSUE TITLE
Cmd

### ISSUE THREAD

**Issue by Genetick** [sqlmapproject/sqlmap#3113]
operating system : windows 10 (fully updated)
python 2.7.13 

error when there is long text on the command line  - examples
If the entered command is long .. there is a nuisance  

1.http://prntscr.com/jkvglf
2.http://prntscr.com/jkvj5a
3.http://prntscr.com/jl34x7
4.http://prntscr.com/jl3dyn
5.http://prntscr.com/jl4tt7 (--random-agent --level --risk no use  .. after url

**Comment by Genetick** [comment]
http://prntscr.com/jl34x7

**Comment by Genetick** [comment]
http://prntscr.com/jl3dyn

**Comment by Genetick** [comment]
http://prntscr.com/jl4tt7

**Comment by stamparm** [comment]
Enclose urls with quotes
