### ISSUE TITLE
sqlmap back-and dbms is not 

### ISSUE THREAD

**Issue by BestCracker** [sqlmapproject/sqlmap#3118]
https://s9.postimg.cc/rgivda6b3/screenshot_6.png

**Comment by stamparm** [comment]
This looks strange at least, but couple of things stand out:

1) It seems that you've used dirty parameter values (with SQLi payloads inside), while you've been warned by sqlmap in numerous occasions to NOT do that. Always use non-intact value parameter values
2) DBMS looks like MySQL but there is a huge possibility that something is blocking (some of) sqlmap requests - especially in this kind of cases where "OR boolean" works, while "AND boolean" doesn't

My first question is have you even bothered to take a look into the HTTP traffic to spot what is going on? Also, you haven't provide any details (asked by you in Issue template) to improve this issue report

**Comment by stamparm** [comment]
ping?
