### ISSUE TITLE
Injection not being saved bug is still present

### ISSUE THREAD

**Issue by akmlvl** [sqlmapproject/sqlmap#3119]
don't tell me how to reproduce it cause it happens very randomly you should look at your code

**Comment by AmericanY** [comment]
same here after recent update ! please fix

**Comment by stamparm** [comment]
`don't tell me how to reproduce it cause it happens very randomly you should look at your code` <- I am really not sure how to take this seriously. It happens very randomly, you can't find a way to reproduce it, I can't find a way to reproduce it and you are using a derogative?!

**Comment by stamparm** [comment]
Somebody should give me a way to reproduce it and I'll fix it gladly.

**Comment by stamparm** [comment]
Most probably fixed with #3148
