### ISSUE TITLE
DNS leak

### ISSUE THREAD

**Issue by lathund** [sqlmapproject/sqlmap#3122]
## What's the problem (or question)?

The expected behaviour is to redirect DNS queries to the SOCKS5 proxy. 
I've tried querying the tor proxy manually (wsl) to check if it was configured correctly.
That's what makes me think something in Your implementation should be resolved.

Best regards.

## How can we reproduce the issue?

1. Start wireshark (windows)
2. Start tor (wsl)
3. Run sqlmap -u domain.com?a=1 --tor --check-tor --tor-type=SOCKS5 (wsl)
4. Check for DNS requests in wireshark (windows)

## What are the running context details?

* Installation method git clone
* Client OS Microsoft Windows 10.
* Program version Python 2.7 and Sqlmap 1.2.5.21#dev
* Sqlmap and tor running in WSL.

**Comment by stamparm** [comment]
There was a benevolent commit 6c4e9ae427fa6ae985b05f2a979edcdf062868e5 which caused this mess. No need for more explanations as it was really a bug. Thx for reporting,
