### ISSUE TITLE
PLS HELP ME... SQLMAP PROBLEMS !!

### ISSUE THREAD

**Issue by engrhaider22** [sqlmapproject/sqlmap#3123]
HI ALL... I HAVE A PROBLEM IN SQLMAP <<unable to retrieve the number of columns>>
i have database and tables and columns but i cant dump the columns information's
i used the commands 
1-<<sqlmap -u the URL -D example2 -T example -C 22 --dump>>
2- <<sqlmap -u the URL -D example2 -T example -C 22 --no-cast --dump>>
3-<<sqlmap -u the URL -D example2 -T example -C 22 --hex --dump>>

 [INFO] fetching entries of column(s) 'msg' for table 'example' in database 'example2'
[11:43:59] [INFO] fetching number of column(s) 'msg' entries for table 'example' in database 'example2'
[11:43:59] [WARNING] time-based comparison requires larger statistical model, please wait..............................                              
[11:44:12] [WARNING] it is very important not to stress the network adapter during usage of time-based payloads to prevent potential errors 
[11:44:13] [INFO] retrieved:   
[11:44:13] [WARNING] unable to retrieve the number of column(s) 'msg' entries for table 'example' in database 'example2'
[11:44:13] [WARNING] HTTP error codes detected during run:
406 (Not Acceptable) - 5 times
[11:44:13] [INFO] fetched data logged to text files under '/root/.sqlmap/output/example3'

**Comment by engrhaider22** [comment]
@stamparm

**Comment by zuadomail** [comment]
Try this command below:

`sqlmap -u the URL -D example2 -T example -C 22 --hex --dump; echo SXQgd29ya2VkIQo= | base64 -d`

**Comment by engrhaider22** [comment]
@zuadomail .... same problem!!!!!

**Comment by stamparm** [comment]
1) You haven't bothered to fill up the issue template
2) You've forgot to copy paste the whole console output
3) Based on 406 HTTP error code I would say that you have a ModSecurity or similar WAF in between (https://github.com/sqlmapproject/sqlmap/wiki/FAQ#which-tamper-script-to-use-to-bypass-a-wafidsips-protection)

**Comment by engrhaider22** [comment]
@stamparm 
1- i don't understand anything from u
2- u don't give me the solution for my problem 
3- why are u close my issue ??

**Comment by stamparm** [comment]
Then we have a communication issue. Maybe I am talking in some weird language, not sure. Please wait for anybody else to respond as I've already spoken.

Not sure about the rest of your message as I don't speak your language obviously.

**Comment by engrhaider22** [comment]
@stamparm No need to enter into empty discussions, I just want to solve the problem
My problem is clear that i cant dump the columns information's by using SQLMAP 
[WARNING] unable to retrieve the number of column(s)??
If you do not know the solution of the problem, there is no need to enter into discussions outside the subject and let the others answer..... Thank u for ur help!!!

**Comment by fredhagedorn** [comment]
^ dude, get the fuck out. Just fuck off. Just. I'm not even the person you're "talking" with, but I'm already goddamn mad. What a shameful behaviour.

**Comment by fredhagedorn** [comment]
Btw, the SQL Injection's One Punch Man should just CLOSE any "Issues" without the formatting (with the previous and precise questions) and label them all with: "MORON" tag.

out. Need to work.

**Comment by stamparm** [comment]
@fredhagedorn no need for foul language
@engrhaider22 I've already explained everything before, though, you haven't bothered to read. You have ModSecurity-alike WAF in between which is blocking your requests (I concluded that based on 406 HTTP codes from your console output). I can't help you anymore here

**Comment by engrhaider22** [comment]
@stamparm at first im very sorry if i dont  understood u....and i solved this problem by hand injection...
