### ISSUE TITLE
Is there a tutorial on the development of tamper for sqlmap?

### ISSUE THREAD

**Issue by robertofocke** [sqlmapproject/sqlmap#3125]
## What's the problem (or question)?
WAF makes analysis difficult, but if the word NOT is added to the word AND it works.
(waf entorpece en análisis y me pone en lista negra mi ip, pero resulta explotable mediante técnica boolean usando AND NOT en lugar de AND)

## Do you have an idea for a solution?
I tried to develop tamper but I did not succeed.
Is there a tutorial on the development of tamper for sqlmap?
(yo intenté hacer un tamper sin exito. Existe tutorial sobre el desarrollo de tamper en sqlmap o qué material debería leer para esto)

```
#!/usr/bin/env python
"""
Copyright (c) 2006-2018 sqlmap developers (http://sqlmap.org/)
See the file 'LICENSE' for copying permission
"""
from lib.core.enums import PRIORITY
__priority__ = PRIORITY.LOW
def tamper(payload, **kwargs):
        if payload:
                payload.replace(' AND ','+and+not+')
                return payload
```

**Comment by stamparm** [comment]
Sorry, there is no tutorial. You just need to know to write Python code (tamper scripts are in majority of cases more than trivial). Nevertheless, there are currently 57 tamper script examples which should be MORE than enough for you to learn what is going on there.

Thing that you are trying to accomplish doesn't make any sense (don't get mad at me for saying that), but here you go:

```
#!/usr/bin/env python

"""
Copyright (c) 2006-2018 sqlmap developers (http://sqlmap.org/)
See the file 'LICENSE' for copying permission
"""

from lib.core.enums import PRIORITY

__priority__ = PRIORITY.LOW

def dependencies():
    pass

def tamper(payload, **kwargs):
    return payload.replace(" AND ", " AND NOT ") if payload else payload
```
