### ISSUE TITLE
sqlmap retrieves column information backwards

### ISSUE THREAD

**Issue by thenintendofreak** [sqlmapproject/sqlmap#3126]
hi when i retrieve the columns under a table on MSSQL 2012 it retrieves the Hex info as the real info and when i run it as no cast it give me NULL

example when hexed
[14:10:29] [WARNING] there was a problem decoding value 'test@test.com' from expected hexadecimal form
unhexed retrieves null

i tried dumping it using binary fields and setting the argument as email but it wont dump it in hex form it keeps trying to decode it

so is there anyway to dump hex as itself?

thank you for your help if you need more info let me know

**Comment by stamparm** [comment]
ping?

p.s. to retrieve in pure hexadecimal format use `--binary-fields`, but without using `--hex`. As said, I am not sure what you've used of options/switches in the first place
