### ISSUE TITLE
[CRITICAL] host 'debiandev' does not exist 

### ISSUE THREAD

**Issue by TommyLemon** [sqlmapproject/sqlmap#3128]
![tim 20180531105145](https://user-images.githubusercontent.com/5738175/40758662-0d4df02c-64c1-11e8-91e8-62117468c961.png)

I executed this command as the official video shows:
![tim 20180531110105](https://user-images.githubusercontent.com/5738175/40759000-a153e5be-64c2-11e8-8a9c-6c3f5cd7daae.png)

```
python sqlmap.py -u "http://debiandev/sqlmap/mysql/get_int.php?id=1" --batch --banner
```
And then it showed me the result:
```
[CRITICAL] host 'debiandev' does not exist 
```

And I've already tried another URL as the README shows:
![tim 20180531105300](https://user-images.githubusercontent.com/5738175/40758799-a2217804-64c1-11e8-8e8a-0b227595dc22.png)

```
python sqlmap.py -u "http://172.16.120.130/sqlmap/mysql/get_int.php?id=1" --batch
```
And then it showed me this result:
```
[CRITICAL] unable to connect to the target URL. sqlmap is going to retry the requst(s)
```

Were there anything wrong with my operations?
Or both of the URLs are not available now?

**Comment by shadowfolder** [comment]
LOL AHAHA:D
P.S. This is example test urls, ofcourse it will not work!

**Comment by stamparm** [comment]
@TommyLemon those are (as @shadowfolder pointed) are test urls. You can't expect live URLs inside the manual. If you want to test something, you can try `http://testphp.vulnweb.com/listproducts.php?cat=1` (instead of that IP and debiandev)

**Comment by oceanwater701** [comment]
i have a quick question as well.....
i ran script using sqlmap.py --risk=3 --level=5 -u "url"

it then prompted me "[10:53:50] [CRITICAL] host 'url' does not exist"

why is that?

**Comment by mihirKathiria** [comment]
what if i want to test my own application from the localhost?
