### ISSUE TITLE
/usr/bin/sqlmap: Permission denied

### ISSUE THREAD

**Issue by gidsumaya** [sqlmapproject/sqlmap#3130]
~# sqlmap --update
        ___
       __H__
 ___ ___[.]_____ ___ ___  {1.2.5.24#dev}
|_ -| . ["]     | .'| . |
|___|_  [,]_|_|_|__,|  _|
      |_|V          |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting at 12:06:49

[12:06:50] [WARNING] not a git repository. It is recommended to clone the 'sqlmapproject/sqlmap' repository from GitHub (e.g. 'git clone --depth 1 https://github.com/sqlmapproject/sqlmap.git sqlmap')
do you want to try to fetch the latest 'zipball' from repository and extract it (experimental) ? [y/N] y
[12:07:16] [INFO] updated to the latest version '1.2.5.24#dev'

[*] shutting down at 12:07:16

~# sqlmap
bash: /usr/bin/sqlmap: Permission denied

cant execute sqlmap after updating to '1.2.5.24#dev'

**Comment by stamparm** [comment]
1) You've used (experimental) feature `do you want to try to fetch the latest 'zipball' from repository and extract it (experimental) ? [y/N] y`
2) I don't know what was the original setup in your case (e.g. `apt` repository, `pip` installation or similar)
3) You really haven't bothered to gather any data on the issue itself. For example, to try to find where the current location of new `sqlmap.py` is?
4) What's the OS and how did you install sqlmap in the first place

**Comment by gidsumaya** [comment]
I'm using Kali Linux, that sqlmap is pre-installed. I tried to update it because theres a new tamper script which is 0x2char.py so i tried sqlmap --update. then this happened, can you help me how to get sqlmap executable again?  

Thanks

**Comment by stamparm** [comment]
1) Please do the following: `chmod +x /usr/bin/sqlmap` and then retry `sqlmap`
2) I'll make a patch for this inside sqlmap so other users would not have any more problems like this

**Comment by stamparm** [comment]
@gidsumaya with the latest patch the problem should be gone (after the updated sqlmap is being used for `--update`) in future similar attempts. So, you can do the one last `sqlmap --update && chmod +x /usr/bin/sqlmap` to get the latest HEAD and afterwards you'll need to do just `sqlmap --update`

**Comment by gidsumaya** [comment]
sqlmap --update && chmod +x /usr/bin/sqlmap didnt work, so I tried going to directory /usr/bin/ then execute the command  chmod +x sqlmap, It's now fixed! Thanks

**Comment by Ekultek** [comment]
@gidsumaya don’t ever make a directory executable, you should do something like `sudo chown -R $(whoami): /usr/bin/sqlmap`
