### ISSUE TITLE
403 Forbideen

### ISSUE THREAD

**Issue by AmericanY** [sqlmapproject/sqlmap#3131]
`1 AND ORD(MID((SELECT IFNULL(CAST(COUNT(DISTINCT(schema_name)) AS CHAR),0x20) FROM INFORMATION_SCHEMA.SCHEMATA),1,1))>51` keep shown **You don't have permission to access**

anyone were able to bypass WAF which blocking retrieving information_schema itself  because it's blacklisted ? since it's only keep fetching the current database name only here.

**Comment by stamparm** [comment]
Blacklisting `information_schema` is a common protection mechanism, primitive in its nature, though very effective in blocking this kind of (database enumeration) requests.

**Comment by AmericanY** [comment]
@stamparm that's enough confirmation for me.
