### ISSUE TITLE
Decrypting columns

### ISSUE THREAD

**Issue by xxsyphonxx** [sqlmapproject/sqlmap#3132]
heya gang, could someone please try help on what type hash,encryption used on this database.

not the email columns i astricked them out , just the Password field, pipe charector is used .

web server operating system: Windows 8 or 2012
web application technology: ASP.NET, ASP, Microsoft IIS 8.0
back-end DBMS: MySQL >= 5.0

+---------------------------------------------+----------------------------------------------------+
| email | password |
+---------------------------------------------+----------------------------------------------------+
[00:23:33] [WARNING] console output will be trimmed to last 256 rows due to large table size
| reception@***.com | |97|113|247|53|197|67|70|203 |
| rajp@***.com.au | |33|33|174|116|158|27|19|152 |
| lynette_round@***.com | |18|36|160|109|139|77|75|147|217|186|80 |
| jipatoni@***.com | |61|41|167|111|220|82|68|210|149|247 |

Thanks in advance. 
## How can we reproduce the issue?

1.
2.
3.
4.

## What are the running context details?

* Installation method (e.g. `pip`, `apt-get`, `git clone` or `zip`/`tar.gz`):
* Client OS (e.g. `Microsoft Windows 10`)
* Program version (`python sqlmap.py --version` or `sqlmap --version` depending on installation): 
* Target DBMS (e.g. `Microsoft SQL Server`): 
* Detected WAF/IDS/IPS protection (e.g. `ModSecurity` or `unknown`):
* SQLi techniques found by sqlmap (e.g. `error-based` and `boolean-based blind`):
* Results of manual target assessment (e.g. found that the payload `query=test' AND 4113 IN ((SELECT 'foobar'))-- qKLV` works):
* Relevant console output (if any):
* Exception traceback (if any):

**Comment by stamparm** [comment]
Strange at least. As I can see, it isn't length constrained which means that it is not hash based. Also, it isn't modular in length, which means that it could be some sort of stream-based (custom?) encryption.

**Comment by Ekultek** [comment]
@stamparm ord based possibly?

**Comment by stamparm** [comment]
ORD/CHR is only a way how to encode it (presentation part). Question is which encryption mechanism has been used (seems to me like a custom stream-based encryption)

**Comment by Ekultek** [comment]
Well if @AmericanY is correct, there’s this tool for decryption. https://github.com/tfgm/sbedecoder

Never used it before so idk if it works or not, good luck

**Comment by AmericanY** [comment]
@Ekultek That's the same tool i used for decoding before :D, by the way what's the dev email for whatwaf?

**Comment by Ekultek** [comment]
@AmericanY sqlmap isn’t the place to be discussing whatwaf, the email is staysalty@protonmail.com though. For any further information please regard the whatwaf repo.

**Comment by AmericanY** [comment]
@Ekultek I Removed my comment, go ahead and remove yours. thanks for clarification

**Comment by Ekultek** [comment]
@AmericanY welcome, you can also find it [here](https://github.com/Ekultek/WhatWaf/wiki)

**Comment by xxsyphonxx** [comment]
Wow thanks alot guys, i searched and searched before i posted on couple forums and you guys came to rescue many thanks

**Comment by AmericanY** [comment]
@xxsyphonxx you welcome, kindly close your issues if you got is solved.

**Comment by stamparm** [comment]
@AmericanY how did you conclude that this is SBE? It doesn't look like SBE to me

**Comment by AmericanY** [comment]
@stamparm i faced the same issue before, so i were able to locate the source code of the input page which were responsible to decode the passwords before sending it to the back-end database. at first i thought it's `substr(md5($pass),12,20) ` but after decoding it, i were able to confirm my point.
