### ISSUE TITLE
OS Error: No such file or directory

### ISSUE THREAD

**Issue by zjestrella-r7** [sqlmapproject/sqlmap#3137]
## What's the problem (or question)?
Can anyone please help me out with the debugging / issue that is going on?  I am currently writing a script to automate the launch of sqlmapapi and run a sqlmap scan, but I am getting a weird error and cannot figure out why.

INFO:root:*[23:03:14] [INFO] Running REST-JSON API server at '127.0.0.1:8775'..
INFO:root:*[23:03:14] [INFO] Admin ID: c7c98fd5ee36989efa5887c78a1e186b
INFO:root:*[23:03:14] [DEBUG] IPC database: '/tmp/sqlmapipc-_Ioc0t'
INFO:root:*[23:03:14] [DEBUG] REST-JSON API server connected to IPC database
INFO:root:*[23:03:14] [DEBUG] Using adapter 'wsgiref' to run bottle
INFO:root:*[23:03:18] [DEBUG] Created new task: '4c6c77caf6aefe27'
INFO:root:*[23:03:18] [DEBUG] [4c6c77caf6aefe27] Requested to set options
INFO:root:*Traceback (most recent call last):
INFO:root:*  File "/python/src/sqlmap/thirdparty/bottle/bottle.py", line 935, in _inner_handle
INFO:root:*    return route.call(**args)
INFO:root:*  File "/python/src/sqlmap/thirdparty/bottle/bottle.py", line 1888, in wrapper
INFO:root:*    rv = callback(*a, **ka)
INFO:root:*  File "/python/src/sqlmap/lib/utils/api.py", line 488, in scan_start
INFO:root:*    DataStore.tasks[taskid].engine_start()
INFO:root:*  File "/python/src/sqlmap/lib/utils/api.py", line 163, in engine_start
INFO:root:*    self.process = Popen(["sqlmap", "--api", "-c", configFile], shell=False, close_fds=not IS_WIN)
INFO:root:*  File "/usr/local/lib/python2.7/subprocess.py", line 710, in __init__
INFO:root:*    errread, errwrite)
INFO:root:*  File "/usr/local/lib/python2.7/subprocess.py", line 1335, in _execute_child
INFO:root:*    raise child_exception
INFO:root:*OSError: [Errno 2] No such file or directory
## Do you have an idea for a solution?
I think it has something to do with a file not existing, but I am not too sure why the file doesn't exist.  The logs bring me to the api.py file 

## How can we reproduce the issue?
Unfortunately, you cannot reproduce the error because the infrastructure running it is not assessable by everyone.

**Comment by stamparm** [comment]
Please update to the latest revision and retry. Pushed this moment a relevant patch.

If it still fails please tell me how do you run this whole thing?

**Comment by stamparm** [comment]
It was actually a way I presumed you've run it. I tried it to in a similar way and found a real problem/bug inside.
