### ISSUE TITLE
I want to add new custom payload, how to do it?

### ISSUE THREAD

**Issue by gsdt** [sqlmapproject/sqlmap#3138]
Hi author,
I want to add some custom payload like `' and '1'='1`, and re-order them to get a faster scan.
Thank you.

**Comment by stamparm** [comment]
1) What does this mean? `' and '1'='1` is not a "custom payload". It is one of most simple payloads available.
2) sqlmap already "reorders" payloads based on DBMS heuristics. You can be pretty sure that you won't be able to do it far more "faster" than it is currently being done
3) Along with payloads, there are boundaries. I am not sure that you are aware of those? Those should be reordered too for your needs.

---

I am pretty sure that you are trying to do something without even looking into the internals. Closing this down until you read [payloads](https://github.com/sqlmapproject/sqlmap/tree/master/xml/payloads) and [boundaries](https://github.com/sqlmapproject/sqlmap/blob/master/xml/boundaries.xml). Also, run sqlmap for lots of times with `-v 3` to catch a grip what is going on. Then, please make a coherent Issue on what are you trying to accomplish.
