### ISSUE TITLE
does not work tor polipo

### ISSUE THREAD

**Issue by dark12239** [sqlmapproject/sqlmap#3139]
apt-get install tor tor-geoipdb polipo

Replace the config file polipo by the pastebin file

# gedit /etc/polipo/config

Polipo configuration file: http://pastebin.com/sRLvt0ue

Restart the services

# service tor restart

# service polipo restart

#  sqlmap -u "SITE HERE" --random-agent -v 3 --tor --check-tor --dbs --threads=5

**Comment by stamparm** [comment]
I haven't been able to reproduce this (used exact same steps), BUT... I guessed what could be the problem. Can you please retrieve the latest revision and retry it again? Also, if it still fails please copy-paste the whole sqlmap's console output here

**Comment by stamparm** [comment]
ping?
