### ISSUE TITLE
sqlmapapi unresponsive when started from Windows command prompt

### ISSUE THREAD

**Issue by codewatchorg** [sqlmapproject/sqlmap#3151]
## What's the problem (or question)?
I have observed on numerous occasions where if I start the sqlmapapi from a Windows command prompt, and then start multiple sqlmap processes via the API, it eventually becomes completely unresponsive.  On the exact same machine, if I start the API from either a Cygwin shell or a Bash for Windows shell, it never becomes unresponsive against the exact same sites/pages/parameters.

## Do you have an idea for a solution?
I have no idea why the API becomes unresponsive.

## How can we reproduce the issue?
Start sqlmapapi from a Windows command prompt and use it to launch multiple sqlmap processes against a complex website.  Continually poll the API and it should become unresponsive.

## What are the running context details?
OS: Microsoft Windows 10
Version: Multiple versions, but currently 1.1.11.16#dev
Installation: git clone

**Comment by stamparm** [comment]
Most probably an "adapter" issue. https://github.com/sqlmapproject/sqlmap/issues/1282#issuecomment-292526717

Is there a way for you to try to install some of those mentioned and report back the results? If not you'll need to wait for me to catch some time (maybe I could try tomorrow, but can't promise - because of tons of other stuff to do)

**Comment by stamparm** [comment]
Tested this moment with 50 tasks, couldn't reproduce "unresponsives". I haven't had complex site(s), but I had 50 tasks running all in the same time.

Now. Is there anything that could help here more from your side? I don't know how many tasks did you have. I don't know the size of your RAM. I don't know anything than "unresponsive".

One more thing. Each task takes cca. around 25MB of memory. As I don't know your memory configuration I can't deduce whether your SWAP got involved (due to RAM fill up)

**Comment by codewatchorg** [comment]
Sometimes this happens with just a single task, but most the time I have 5-10 tasks running.

My setup is:
Windows 10 x64
RAM: 16GB
CPU: Dual Core i7 @ 2.5ghz
Python 2.7.14

I start sqlmapapi without specifying an adapter, so just something like:
python sqlmapapi.py -s -H 10.10.10.10 -p 9090

Maybe it is a combination of options passed to the API?  Options I am typically using:
--user-agent
--referrer
--delay
--timeout
--retries
--level
--risk
--threads
--time-sec
-b
--current-db
--batch
--answers="crack=N,dict=N"

I also often pass in the DBMS backend and OS.  The sqlmap tasks themselves run and complete fine, but the API will become unresponsive where if I connect with netcat and make a simple request like "GET /scan/<task_id>/log" or "GET /scan/<task_id>/status" I will never receive a response - I've let it sit for an hour, tried again, and it's like it is just stuck.

This only happens when started via Windows (standard Windows command prompt or with Java exec).  It will work fine on the exact same machine when started under Cygwin, Bash for Windows, or one person reported starting it with PowerShell worked - waiting on details for that.

I will try to find a locally installable open source project in which I can replicate the issue.

**Comment by codewatchorg** [comment]
It is really hard to replicate.  I have been trying to track down what causes it off and on since I first encountered it probably a year ago - but I don't often start the API with anything other than Cygwin or Bash for Windows since those work fine.

Maybe one of the other adapters would fix the issue as I always just use the default.  Do you have a recommendation on an adapter to use?

**Comment by stamparm** [comment]
Try `paste`. As you are running Windows, you'll need >= Python 2.7.9 (comes with PIP package installer included):
```
1) C:\Python27\Scripts\pip.exe install paste
2) sqlmapapi.py -s -H 0.0.0.0 --adapter paste
```

Note: leaving for reference of bottle adapters https://bottlepy.org/docs/dev/deployment.html

**Comment by codewatchorg** [comment]
I can't replicate it from the Windows command prompt at the moment, but it is pretty easy to replicate with called from Runtime.exec in Java.  I wrote the Burp Suite sqlmap integration plugin at https://github.com/codewatchorg/sqlipy, and one of the features is being able to stop/start the API from within Burp Suite.

I ran the DVWA application (Damn Vulnerable Web Application) on my localhost, started Burp Suite, loaded the SQLiPy extension, then launched the API from within the extension interface.  After sending a handful (6) of requests in Burp to sqlmap through the extension it becomes unresponsive (I repeated this process and even a single instance eventually hung up).

I guess it is a limitation of launching via Java.  I am unsure of a workaround; I tried the default adapter, paste, eventlet, and rocket all with the same results.

**Comment by codewatchorg** [comment]
I am closing this as I can't reliably reproduce when launching from a Windows command prompt.  I believe I have a working solution when launching from Java (at least it has worked 4 times in a row, where before it would fail quickly every time).
