### ISSUE TITLE
Extracting Blob Data Type

### ISSUE THREAD

**Issue by eskiesirius** [sqlmapproject/sqlmap#3158]
Hi! Is there a way to extract blog values?

[WARNING] cannot properly display Unicode characters inside Windows OS command prompt (http://bugs.python.org/issue1602). All unhandled occurances will result in replacement with '?' character. Please, find proper character representation inside corresponding output files.

\n>\xe7\xb4\n\xb8%?#\xac6?\xf7P\x96\xc5;\x95+\xc69}\xad\xb2\xc7\xd4\xe4\xf2\x15\x11

Im having this kind of output.

**Comment by stamparm** [comment]
1) There is a probability that you are dealing with the false-positive. Rerun everything with `--flush-session --banner`. If you are getting junk or not getting anything else, you don't have a SQL injection
2) In case that you really have a positive, use `--binary-fields` (https://github.com/sqlmapproject/sqlmap/wiki/Usage#binary-content-retrieval)
