### ISSUE TITLE
I got <blank> data

### ISSUE THREAD

**Issue by eskiesirius** [sqlmapproject/sqlmap#3160]
I tried the --time-sec but nothing happened, any idea?

**Comment by stamparm** [comment]
There are lots and lots of possible causes and you haven't stated nothing to help to narrow down what is going on. I can only name a few:

1) WAF/IDS/IPS protection blocking queries
2) System databases and/or tables are restricted for current www user
3) Character filtering inside subqueries
4) False positive SQLi case
5) Usage of invalid (i.e. non-existing) identifier (e.g. table and/or column) names
