### ISSUE TITLE
Use GPU when cracking hashes?

### ISSUE THREAD

**Issue by shadowfolder** [sqlmapproject/sqlmap#3161]
Hi there! :) In current time sqlmap can crack only via CPU. If you can add support gpu when cracking hashes, that would be a good idea. Something like --use-gpu

**Comment by stamparm** [comment]
Usage of GPU for cracking is a whole science for itself. sqlmap does a pretty fast and clean wordlist attack on found hashes and at the end dumps uncracked hashes to the file. The whole idea was to do a clean attack on easy and obvious passwords, while letting more advanced projects (like hashcat) to do the rest.

TLDR; there won't be implementation for GPU cracking as other solutions are doing WAY more advanced stuff in this department (https://github.com/hashcat/hashcat)
