### ISSUE TITLE
How to set update eta in real time?

### ISSUE THREAD

**Issue by shadowfolder** [sqlmapproject/sqlmap#3165]
Hi there, i've noticed, that --eta is not updating dumped data in real time. It shows results after 100-200 values only, like:
100/1000
200/1000
300/1000
How i can set --eta to update in real time? Like
100/1000
101/1000
102/1000
103/1000 ?

**Comment by AmericanY** [comment]
seems that you have no background about the progress of `--eta`

well, let me inform you that `--eta` based on the threads you used.

for example in case if you are using --threads=10 is different than using --threads=1 ( same as without using --threads option as it's by default 1 thread)

so in case if you using threads=10 gonna process as 10/1000 then 20/2000 which means sqlmap wait for the each 10 threads to process and print into stdout before moving to next threads.

in case if you are not using threads option or threads=1 so it's gonna process 1/1000 then 2/1000.

take a look

https://github.com/sqlmapproject/sqlmap/issues/2777

**Comment by stamparm** [comment]
@shadowfolder please update and retry
