### ISSUE TITLE
--current-user and --passwords?

### ISSUE THREAD

**Issue by SQLprodigy** [sqlmapproject/sqlmap#3170]
These 2 switches go hand in hand.

I know the password already to the DBMS.

It seems from a pentesters standpoint I cant enumerate the password of the DBA admin using --passwords?

In MySQL dbs, where is the --current-users password stored? Why wont it enumerate?

Thanks

**Comment by stamparm** [comment]
For MySQL all DBMS passwords are stored inside system table `mysql.user` (related query: `SELECT user,password FROM mysql.user`). If the current user (in most cases some dummy non-admin query user) does not have privileges to read that same table, `--passwords` will fail.

**Comment by stamparm** [comment]
System table `mysql.user` is inside database `mysql` while the table is actually called `user` (`mysql.user` is the database+table name). If you don't have privileges you won't be able to access it. Period.
