### ISSUE TITLE
Sqlmap Font Color issue after latest update.

### ISSUE THREAD

**Issue by AmericanY** [sqlmapproject/sqlmap#3172]
Who noticed a font color issue after latest update, even the sort of running requests is not sorted as well.

example `sqlmap.py --update`

or run sqlmap against any target and see the output on console.

**Comment by AmericanY** [comment]
@stamparm ping?

**Comment by AmericanY** [comment]
even issue while dumping any data or fetching databases !

**Comment by AmericanY** [comment]
@stamparm ping?

**Comment by stamparm** [comment]
You have to provide any info. I've made some changes, but I don't know what is the issue at your side. Also, I've tested on both Linux and Windows and got the expected behavior.

**Comment by AmericanY** [comment]
@stamparm 

Indeed, the issues occurred after the latest update.

check the following pic

https://www.photobox.co.uk/my/photo/full?photo_id=500875502106

https://www.photobox.co.uk/my/photo/full?photo_id=500875502104

**Comment by stamparm** [comment]
Can you please upload pics here or to imgur? I am trying to open those photobox links on 3 mobile browsers and all I get is the front page

**Comment by AmericanY** [comment]
![capture](https://user-images.githubusercontent.com/27644047/42363272-3f0a3b78-80f7-11e8-8147-c7c14ff9696e.PNG)
![capture1](https://user-images.githubusercontent.com/27644047/42363281-478a1b56-80f7-11e8-974d-890228fb3b03.PNG)

**Comment by AmericanY** [comment]
@stamparm done

**Comment by stamparm** [comment]
Thank you for your report. Sorry for waiting. Find it fixed now.

**Comment by AmericanY** [comment]
@stamparm i see that the new update made the standard output color on console is white. which really made the looking not friendly as before. at least before it's not tired your eyes . we used on red font for errors and green for running smoothly and light white discovered vulu..
