### ISSUE TITLE
Help with that type

### ISSUE THREAD

**Issue by AmericanY** [sqlmapproject/sqlmap#3175]
```
[*] Ý\x01/9_zt^\x02\x98ÂÒ]ËÁ8, Ù\x0222^xr, ß\x0b.
[*] Ý\x00$1Zqv]\x0e\x9cÇ×XÂÍ=, Ù\x0222^xq, Ñ\x01-
[*] Ü\x01,3^{vX\x07\x98ÅÖ]ÇÈ=, Ø\x0722^xp, Ý\x04%
[*] Ý\x06/4_pw\\\x0e\x98ÆÔUÊÀ;, Ù\x0322^xr, Û\x01$
[*] Ü\x01-8[yqZ\x00\x9eÁÖ_ÃÉ=, Ø\x0122^xq, Ø\x05*
```

using  `--hex` were unable to decrypt it.

first column should be 15 or 16 digits 
second column should be date
third column should be 3 or 4 digits

**Comment by stamparm** [comment]
Use `--binary-fields` in this kind of situations (https://github.com/sqlmapproject/sqlmap/wiki/Usage#binary-content-retrieval)
