### ISSUE TITLE
[WARNING] Back-end dbms is not 

### ISSUE THREAD

**Issue by gidsumaya** [sqlmapproject/sqlmap#3176]
sqlmap command: sqlmap.py -u "https://www.example.com/search/?vuln=1" --random-agent --keep-alive --level=5 --risk=3 --dbms="DB2" --technique="B" -v 2 --tamper=overlongutf8 --all --charset="iso-8859-1" --encoding="windows=1252" --fresh-queries 

sqlmap resumed the following injection point(s) from stored session:

Parameter: filter (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: vuln=1%' AND 9266=9266 AND '%'='
    Vector: AND [INFERENCE]

[00:40:13] [WARNING] changes made by tampering scripts are not included in shown payload content(s)
[00:40:13] [INFO] testing IBM DB2
[00:40:13] [DEBUG] resuming configuration option 'code' (403)
[00:40:15] [WARNING] reflective value(s) found and filtering out
[00:40:15] [WARNING] the back-end DBMS is not IBM DB2
[00:40:15] [CRITICAL] sqlmap was not able to fingerprint the back-end database management system

I got these everytime I ran "--fresh-queries"  

Thanks.

**Comment by AmericanY** [comment]
@gidsumaya Well, looks like you are dealing with False Positive SQLI, There's nothing can be done at the moment, rerun with `--flush-session` and include `--drop-set-cookie` 

Also debug the Traffic using `-v 6` or save it to log using `-t traffic.txt` and check the traffic in/out request to determinate what's causing the issue.

also i noticed that you are using `--tamper=overlongutf8` so keep informed if you have no knowledge about how to bypass WAF so you might using a wrong tamper which leading to several issues.

try as well to fingerprint the database using `--fingerprint` and force the database type using `--dbms=`

**Comment by AmericanY** [comment]
@gidsumaya well, DEBUG it manually then, check what's going on while sqlmap confirming the back end database. using `-v 6` looks like the tamper were unable to bypass the waf since 403 error code on board. otherwise try to Turn off payload casting mechanism with `--no-cast`

**Comment by stamparm** [comment]
You are either A) having problems with the WAF, B) wrongly forcing the `--dbms="DB2"`or C) dealing with false positive

Combination of two exotic parameters here (DB2 and overlongutf8) does smell like this is something messy.

How come you know that it is: DB2 AND/OR that `overlongutf8` works in the first place in this case?

My wild guess is that you are having a false-positive here where you are pushing it to work at any means necessary.

**Comment by gidsumaya** [comment]
I always ran --flush-session for every potential vulnerable parameter I found, but It always returns the same result. If sqlmap says "boolean based blind"? do I need to expect an output here? because it's blind.

**Comment by gidsumaya** [comment]
This is from another target:
WAF: Cloudflare 
tamper scripts used: randomcase,between,space2comment,space2hash,space2mysqlblank,apostrophemask

what do you think? Thanks

![capture](https://user-images.githubusercontent.com/28594721/42516391-8be9c3ae-8490-11e8-931f-5dc86b54bd35.PNG)

**Comment by AmericanY** [comment]
@gidsumaya looks like it's a hex output for me, could you please retry with --hex ?

**Comment by stamparm** [comment]
@gidsumaya you are getting junk (false-positives). I'll remove that same payload as it is known to cause problems like this from previous Issues. Big-number theory says that if something can go wrong (by pushing number of payloads and boundaries with `--level` and `--risk` COMBINED with lots of such users) it will go wrong. The problem is that this same payload is problematic (aka weakest link in the detection engine) as lots of search engines can result "kind of injection" results when confronted with combination of `%` and some other string(s).

**Comment by stamparm** [comment]
Please pull the latest revision (`1.2.7.14#dev`) and rerun everything with `--flush-session`

**Comment by gidsumaya** [comment]
Thanks @stamparm @AmericanY

**Comment by gidsumaya** [comment]
Hi @stamparm based on my latest testing with (1.2.7.14#dev), the target shows more potential. I strongly believe that this is a positive vulnerability. because before it shows 5.x as a version and now it shows 8.x
![capture](https://user-images.githubusercontent.com/28594721/42598367-8f147d72-858e-11e8-98fd-f780de4b279e.PNG) and HTTP request changed too. from 500+ requests before to 76 requests and that is way more faster to detect. 

But everytime I run --dbs it always shows 5 number of databases but unable to retrieve.

**Comment by AmericanY** [comment]
@gidsumaya since you didn't mention what happened after sqlmap detected the number of database, so we will can't help you further more. take a look if you were warned before about WAF ISSUE.

**Comment by gidsumaya** [comment]
@AmericanY its Cloudflare WAF. but everytime I put --tamper=overlongutt8 and -v 2 it shows no error code 403, but can't retrieve anything. I think I might deal with this manually.
