### ISSUE TITLE
SQLMAP is getting redirect to a error page, while browsers are working fine.

### ISSUE THREAD

**Issue by adarshd711** [sqlmapproject/sqlmap#3181]
I am using sqlmap to inject in a registration page, where sqlmap is getting a redirect option, while opening the same registration page on browsers like chrome, firefox, no redirection is there.
Due to redirection, sqlmap is not able to inject in the param.
i even tried the --no-redirect option.

**Comment by stamparm** [comment]
Have you looked into the traffic what is going on? It is hard to tell based on these couple of sentences. Try to rerun with `--random-agent`. If it still fails, please properly debug with `--proxy`

**Comment by adarshd711** [comment]
I have tried with random-agent too.

**Comment by stamparm** [comment]
Not sure what to respond to your finger down than to close this as invalid. I've properly directed you to debug what is going on...
