### ISSUE TITLE
[FEATURE REQUEST] Dump tables in single concat strings

### ISSUE THREAD

**Issue by AntonKuzminRussia** [sqlmapproject/sqlmap#3184]
## What's the problem (or question)?
If we make full dump of table (-T tablename --dump) with many fields  by blind sqlinj, we make many burden queries for get length of every fields values. This fact make a dump time grow up. It`s very sad to look like getting a one integer value (like 1, 2, 3, or some small) pulls for itself queries for get value length.
And, how i understand, use multithreading not resolve this problem (free threads not go to other fields parse, or i wrong?). All evil in burden queries for get length of many fields.
 
## Do you have an idea for a solution?
In practice i found good speed solution - dump not all fields, but dump query with all fields concat in one string with some delimiter like CHAR(194) - SELECT CONCAT(id, char(194), xxx, char(194), ...). In this case we must make less burden queries - only for check all string length. And here will work all threads at this big string. 

I suggest add this dump mode to sqlmap how single param. If it enable, every row of target table dumps as one string one by one.

**Comment by stamparm** [comment]
sqlmap is not MySQL only tool. In MySQL you can happily concatenate (in majority of situations) any data type with any other data type. Also, in MySQL you have great functions like `CONCAT_WS` or `GROUP_CONCAT` where you can concatenate lots of row columns into a single string in a stress-free form.

In majority of other DBMSes you have to manually concatenate and manually CAST/CONVERT all row columns. Making this kind of stuff in general case is NOT SMART thing to do as all modern web servers do have some form of length constraining on input parameters. Sending heavy concatenate payload with thousands of characters inside is not smart thing to do.

Anyway, please accept my apologies for having a stress during waiting for "evil ... burden queries". It has to work for majority of DBMSes in most generic way possible. I would suggest you to implement your application/tool which will do this kind of behavior and push it to the Github. If it will work for more than one DBMS I'll gladly take a look
