### ISSUE TITLE
Previous bug/issue still exist #3176

### ISSUE THREAD

**Issue by gidsumaya** [sqlmapproject/sqlmap#3187]
sqlmap.py -u "https://www.example.com/xxx?q=&a=" --random-agent --keep-alive --level=5 --risk=3 --technique=BT --prefix="'" --suffix="--" --batch -f -v 6 --drop-set-cookie

sqlmap resumed the following injection point(s) from stored session:

Parameter: q (GET)
    Type: boolean-based blind
    Title: OR boolean-based blind - WHERE or HAVING clause
    Payload: q=-7607' OR 7073=7073--&a=0
    Vector: OR [INFERENCE]

[10:24:14] [INFO] testing MySQL
[10:24:14] [INFO] confirming MySQL
[10:24:14] [INFO] the back-end DBMS is MySQL
[10:24:14] [INFO] actively fingerprinting MySQL
[10:24:14] [INFO] executing MySQL comment injection fingerprint
web server operating system: Linux Ubuntu
web application technology: Apache, PHP 7.0.30
back-end DBMS: active fingerprint: MySQL >= 5.5 (MariaDB fork)

Everytime I rerun --flush-session to check if it is false positive. The dbms is changing from db2 to mysql to other dbmses. 

Anyways, I was able to get the banner from checking the HTTP response from **-v 6** | **X-powered-by: PHP/7.0.30-0ubuntu0.16.04.1** 

What do you think I am getting?

**Comment by stamparm** [comment]
@gidsumaya `X-powered-by: PHP/7.0.30-0ubuntu0.16.04.1` is not a DBMS banner that you would expect from `--banner`.

In this case maybe you do have a SQLi, but it could have some kind of protection mechanism that prevents anything further than the detection itself.

I am closing this down as INVALID as your claims are FALSE. This case doesn't have anything to do with #3176 as it is more than clear that you are dealing with the different target. In case of #3176 it was necessary to remove that payload mentioned there, but in this case you have a totally different payload and you don't have to forcefully use random tamper scripts AND/OR use `--dbms` to force one particular DBMS

**Comment by stamparm** [comment]
p.s. patch for #3176 was never meant to be a silver-bullet for false-positives. It was about the removal of the boundaries (WHICH are not used here) that caused lots of false-positives historically.

**Comment by stamparm** [comment]
p.p.s. one more thing. Just for the future Issues like this one:

1) If you are getting junk data, be very suspicious of false-positives
2) If you have a suspicion on false-positives rerun everything with `--flush-session --banner`. If you are not getting DBMS banner in a cleartext format you are either dealing with false-positive OR something unusable from the beginning
