### ISSUE TITLE
True - delay, false - http error

### ISSUE THREAD

**Issue by vayo8888** [sqlmapproject/sqlmap#3195]
Hello, how can i set sqlmap valid query if page have long load time (40-50 sec with code 200) and false if it got ERROR HTTP 500 after 4-5 seconds? I mean i dont want to wait this 40-50 seconds when query is true. By default sqlmap see only time-based sql injection, but manually i can count columns with simple +order+by+*--

**Comment by vayo8888** [comment]
For now on TRUE i got 504 timeout but sqlmap think this is real timeout and shutdown, dont know how to set this code to TRUE, --code=504 wont work.

**Comment by AmericanY** [comment]
@vayo8888 

1- 
![42886712-8c5dafca-8aa4-11e8-8a41-d7744d89d7c4](https://user-images.githubusercontent.com/27644047/43040854-84a74e8c-8d4f-11e8-9621-985eadea7f9c.png)



2- Don't blame `sqlmap` if you don't know how to ask your question! such a comment is really lead to ignore response for your question. `By default sqlmap see only time-based sql injection` 


3- the answer for your question is completely described here. [https://github.com/sqlmapproject/sqlmap/wiki/Usage#page-comparison](url)

4- sqlmap notified you several time about `internal server error` with `http error code 500`. kindly double check if there's a WAF protection ! that why you need to back to point `1`.

.......


@stamparm `invalid`

**Comment by vayo8888** [comment]
I can count lenght of db name with "index.php?id=3800+AND+(SELECT+LENGTH(database()))=7#" (because i know name of db from Time-based) and other information from base. So here is blind injection. But sqlmap didnt see difference between 200 and 500 codes, i trying to set --code=200, but nothin works. I try --null-connection key, but no luck.

**Comment by AmericanY** [comment]
@vayo8888 post sqlmap output here in order to check the issue you talking about.

**Comment by vayo8888** [comment]
Same white pages without any text, just different response codes.
HTTP/1.1 200 OK - True
HTTP/1.1 500 Internal Server Error - False

**Comment by vayo8888** [comment]
im try to put --code=200 --string="200 OK" but got error:
[04:54:24] [WARNING] you provided '200 OK' as the string to match, but such a string is not within the target URL raw response, sqlmap will carry on anyway

**Comment by AmericanY** [comment]
@vayo8888 

1- i noticed that you are talking about `ORDER BY` technique that you were able to use manually. so we are talking about `UNION QUERY INJECTION` NOT A `BOOLEAN` so correct it to be `--technique=U`

2- kindly confirm for me if you are dealing with any WAF protection using `--identify-waf` since i do see several `500 internal server error`

3- use `--delay=` to avoid being captured by `PROTECTION HTTP REQUEST BLOCK MECHANISM` *sometimes it's success*

4- in case if there's no string so better to use just `--code=200`

**Comment by vayo8888** [comment]
Ok, updated.
**1** - **--technique=U** - why? i didnt see any page content while getting TRUE or FALSE, just changing codes (200 and 500) so i thinks this is blind, but im trying now use only UNION.

**2** - There is no waf, codes 200 and 500 are clear TRUE and FALSE:

![](https://puu.sh/B0XXw/900534db96.png)


 **3** - Dont need this option, i also try manuall check any data (db name, table names, columns, just compare code output (just like example TRUE request: **index.php?id=3800+and+1=(SELECT+1+FROM+im_settings+WHERE+id+REGEXP+%27^[1]%27+AND+ID=1)**)

**4** - so, thats final question --code=200  - wont work

![](https://puu.sh/B0Ybg/8d5b5a8ef3.png)

**Comment by vayo8888** [comment]
little donate to btc @stamparm
Anyway thanks for the program, it saved a lot of time.

**Comment by AmericanY** [comment]
@vayo8888 

try with `--drop-set-cookie` and `--ignore-code=500`

**Comment by vayo8888** [comment]
it simple to check in chrome, just look:

![](https://puu.sh/B10g5/34378130cb.png)

![](https://puu.sh/B10ik/efbe6561e5.png)

**Comment by vayo8888** [comment]
im check with --drop-set-cookie and --ignore-code=504, same result, skip good payloads:

![](https://puu.sh/B10tx/49e927ce38.png)

**Manual check this payloads (true and false) in browser:**

![](https://puu.sh/B10us/37080ca89c.png)


![](https://puu.sh/B10w0/e5794c19fc.png)

**Comment by AmericanY** [comment]
@vayo8888 

Well, after several test from my side, I noticed the same issue from my side, reported to @stamparm . wait for an update.

**Comment by AmericanY** [comment]
@stamparm `support`

**Comment by stamparm** [comment]
@vayo8888 it is clear that cloudflare is doing its part here. Not sure why there is no warning of it after a WAF check in sqlmap. You are getting 500 for even benign requests. One more thing. This case is primitive for sqlmap to detect. Be sure that sqlmap does not need to tune it. You could send me a real URL to the miroslav@sqlmap.org if you want me to check why you haven't got the WAF warning.

**Comment by stamparm** [comment]
Just going to the URL displays a big ugly 504 Gateway timeout from Cloudflare. I am not sure why I am even trying to respond to this kind of Issues.
