### ISSUE TITLE
Blindsql guess?

### ISSUE THREAD

**Issue by bannsec** [sqlmapproject/sqlmap#3196]
Thoughts on adding a small guess to blindsql? For instance, every time I do a blind sql injection, i start seeing "information_schema" print out... It becomes a solid guess even at just "in", but i know i've got a while to wait.

Thinking if there are those common tables that we'll see a lot, and we're doing blind injection, if we notice a prefix like that, just try once to see if we're on that table. For instance:
- i
- in
- <full guess> information_schema (correct!)
- next

It would save a decent amount of time on slow injects.

**Comment by stamparm** [comment]
p.p.s. on average, sqlmap is doing 5-6 requests per character. For example, lets say that you are dumping a small database with 500 entries of something. Lets say that on average there are 7 characters per entry. That's 17500-24500 requests for dumping all useful data from that database.

Now. you are nagging about the `information_schema`? Lets say that I implement the mechanism just for you to get the `information_schema` faster. Lets say that I would need at least dump 3 characters before assuming what would be the rest of the entry. Now, sqlmap would spend 3*(5-6) requests for (known) prefix `inf` and than 15 * 1 requests for the rest `ormation_schema` PLUS at leasts 3 requests to make sure that we've hit the end. That's 33-36 requests in total VS 90-108 requests this moment. That is a considerable speed up, BUT. That's just for `information_schema`. What to do with the rest of 17500-24500 requests to dump the rest of the database? Are those 60 less requests really a speed up?

**Comment by stamparm** [comment]
p.p.p.s. one more thing. There is already a switch `--predict-output` (https://github.com/sqlmapproject/sqlmap/wiki/Usage#output-prediction) that will speed up your problematic retrieval of `information_schema`. What I was mentioning in last couple of messages is a general/generic solution which I would implement in case that somebody provides a non-dumb source of "predicting" data for a general case.

**Comment by bannsec** [comment]
Ah, was unaware of the predict-output option. That looks to do what i was mentioning.
