### ISSUE TITLE
Tamper script

### ISSUE THREAD

**Issue by SoulFunk69** [sqlmapproject/sqlmap#3200]
Hello, sorry for my poor english ! :)
I would like to know if i can use tamper script on Firebird Database ?
I seen on the list of tamper he not exist for this type db.

Thanks  ! :)

**Comment by AmericanY** [comment]
@SoulFunk69 @https://github.com/sqlmapproject/sqlmap/wiki/FAQ#which-tamper-script-to-use-to-bypass-a-wafidsips-protection

**Comment by SoulFunk69** [comment]
This link doesn't answer at my question...
I 've seen this link before and is not very util

**Comment by stamparm** [comment]
@SoulFunk69 everywhere where you don't see "Requirement" with specific DBMS could be used for Firebird. By "could" means that first you have to know how to bypass the WAF manually (https://github.com/sqlmapproject/sqlmap/wiki/FAQ#which-tamper-script-to-use-to-bypass-a-wafidsips-protection) to be able to use it.

Dummy usage of random tamper scripts won't get you anywhere. Workflow for bypassing of a protection should be top-to-bottom, where you first find the hole(s) in the protection layer AND afterwards (if it can be automatized in the first place) find a tamper script(s) that could be used in sqlmap
