### ISSUE TITLE
data mixed orders when dumping a huge table

### ISSUE THREAD

**Issue by anasbk** [sqlmapproject/sqlmap#3201]
hello,

please if anyone can help, i'm trying to dump a huge table but when dump finish i got mixed orders,
the users doesn't correspond to the password 

Type: error-based
Title: MySQL >= 5.0 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (FLOOR)

**Comment by stamparm** [comment]
I am pretty sure that you've been asked a question:

`due to huge table size do you want to remove ORDER BY clause gaining speed over consistency? [y/N]`

I am wondering have you read it, understood it and what was your answer to it?

**Comment by anasbk** [comment]
thanks for answering ! 
yes I did and i choosed y

**Comment by stamparm** [comment]
Then I am not sure what's the problem if you understood everything?

**Comment by anasbk** [comment]
my problem is that the output csv is mixed :
User1:PassUser4
User2:Passuser1
etc

**Comment by stamparm** [comment]
Please reread the whole question with understanding and come back. Until then closing this down as invalid.

**Comment by anasbk** [comment]
the questions tells that if i choose y it won't order my username from A to Z

**Comment by stamparm** [comment]
Nope. Consistency is a keyword here.

**Comment by anasbk** [comment]
mmm understood thanks a lot for yout time !
