### ISSUE TITLE
hi, [ERROR] unable to retrieve the table names for any database

### ISSUE THREAD

**Issue by hadesleejs** [sqlmapproject/sqlmap#3208]
![qq 20180815131231](https://user-images.githubusercontent.com/7189444/44132528-ed02a4ae-a08c-11e8-95ea-f0b90f6793ce.png)
when i use sqlmap with v3,it can retrieve db,but it can not retrieve tables.
![qq 20180815131513](https://user-images.githubusercontent.com/7189444/44132580-43fe7d0a-a08d-11e8-85cb-3b2ba89670b7.png)

**Comment by stamparm** [comment]
1) Retrieval of current database name requires query of a function `DATABASE()` which is in most situations not restricted by any means.
2) Retrieval of table names requires querying of system database `information_schema` which could either have restricted access from DBMS itself (e.g. query user doesn't have enough privileges) OR it could be blacklisted (as a word) from some protection mechanism (e.g. WAF). Nothing unusual
