### ISSUE TITLE
Scan with tamper script percentage.py hangs or is very slow

### ISSUE THREAD

**Issue by rischi** [sqlmapproject/sqlmap#3209]
By scanning my target with the tamper script percentage.py sqlmap hangs or is impractically slow. Scanning the same target with no or other tamper scripts works fine.

The problem is here:
/lib/core/common.py

```
def _thread(regex):
    try:
        _retVal[0] = re.sub(r"(?i)%s" % regex, REFLECTED_VALUE_MARKER, _retVal[0])
            if len(parts) > 2:
                regex = REFLECTED_REPLACEMENT_REGEX.join(parts[1:])
                _retVal[0] = re.sub(r"(?i)\b%s\b" % regex, REFLECTED_VALUE_MARKER, _retVal[0])
    except KeyboardInterrupt:
        raise
    except:
        pass

thread = threading.Thread(target=_thread, args=(regex,))
thread.daemon = True
thread.start()
thread.join(REFLECTED_REPLACEMENT_TIMEOUT)
```
The regular expression in my slow run is of the form " U.+N.+I.+L.+t.+s.+C.+O" and is applied the the HTTP response which is about 11kB. The expression runs for minutes because of it's inefficient form which causes catastrophic backtracking.

The other problem is that the safeguard
`thread.join(REFLECTED_REPLACEMENT_TIMEOUT)`
does not work. The regex thread runs until it's finished. I think this is because of the global interpreter lock (GIL) in python. During a regex match no other thread is running.

I don't know what the relation of this problem to the tamper script is. Maybe this piece of code is not used in my other test runs or the regular expression or subject to match is different.

I've used the following command line parameter to reproduce the issue:
`
python2 ./sqlmap.py -p q --method GET --drop-set-cookie --keep-alive --threads 4 -v 0 --skip-waf --ignore-redirects --current-db --level 5 --risk 3 --batch --tamper percentage.py --dbms mysql --url "<mytarget>"
`
The target must probably return a big enough response body that is partially matched by the regex so that a lot of backtracking happens.

I don't know how to improve the regex-safeguard. Maybe you can also improve the generated regular expression.

**Comment by stamparm** [comment]
Addressed with #3204. Patched with df977d93d481d2ce48ca85071cc1a47009b66bbe. Please update (to 1.2.8.2 or higher/HEAD)
