### ISSUE TITLE
decode bug?

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3213]
[DEBUG] declared web page charset 'utf-8'
+--------------------+
| password        |
+--------------------+
| q\xe7\x1c\xa2)l |
+--------------------+

and I check the The encoding type of that table is cp950 (big5?) But I tried --charset=cp950 and --charset=big5, and it didn't work out

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by stamparm** [comment]
1) `--charset`nowadays has a different usage than before (https://github.com/sqlmapproject/sqlmap/wiki/Usage has the up to date information):

$ python sqlmap.py -hh | grep -E '\-\-(encoding|charset)'
    --charset=CHARSET   Blind SQL injection charset (e.g. "0123456789abcdef")
    --encoding=ENCOD..  Character encoding used for data retrieval (e.g. GBK)

2) Your case doesn't look like the encoding problem. This seems to be more a binary-hash value (Note: it doesn't look like something mainstream as it contains only 48 bits)

3) Try to use `--binary-fields` in this kind of situations to get an usable hexadecimal representation that could be used in some other (cracking) tools

**Comment by huitc** [comment]
how?.... I don't understand.......

**Comment by huitc** [comment]
`SELECT default_character_set_name FROM information_schema.SCHEMATA`:    `cp950`
i shoud enter --encoding=`big5` / --encoding=`big-5` / --encoding=`cp950` or what? @stamparm
