### ISSUE TITLE
Tamper script for bypass Checkpoint IPS/IDPS

### ISSUE THREAD

**Issue by etmatrix** [sqlmapproject/sqlmap#3218]
Hi, can I bypass IPS/IDPS of Checkpoint Firewall? 
I'm testing a website protect by checkpoint IPS/IDPS, sqlmap detect as Generic WAF, but I can't test the website, for each query I receive a connection drop.
I'm using latest git pull from sqlmap, I have tried some tamper scripts without success.
Suggestions?
Thank you

**Comment by stamparm** [comment]
There are no known tamper scripts for this. Please research yourself and write back if you succeed.
