### ISSUE TITLE
Has a tamper helped or not?

### ISSUE THREAD

**Issue by Coolfreeze** [sqlmapproject/sqlmap#3228]
Good day to all! On one resource, with the help of 3 scanners, I found the sql injection. Take Kali linux. Option sqlmap `--identify-waf` identified waf `[CRITICAL] WAF/IPS/IDS identified as 'ModSecurity: Open Source Web Application Firewall (Trustwave)'`. Gave a command sqlmap:
`sqlmap -u 'http://www.xxxxxxx.com/home.php?printable=Y' --random-agent --flush-session --identify-waf --timeout=15 --time-sec=15 -v 2 --delay=1 --tamper=modsecurityversioned`.
Sqlmap identified `[INFO] heuristic (basic) test shows that GET parameter 'printable' might be injectable (possible DBMS: 'MySQL')
 [INFO] testing for SQL injection on GET parameter 'printable'
it looks like the back-end DBMS is 'MySQL'. Do you want to skip test payloads specific for other DBMSes? [Y/n] y
for the remaining tests, do you want to include all tests for 'MySQL' extending provided level (1) and risk (1) values? [Y/n] y`.
The result: `[WARNING] GET parameter 'printable' does not seem to be injectable
 [CRITICAL] all tested parameters do not appear to be injectable. Try to increase values for '--level'/'--risk' options if you wish to perform more tests. You can give it a go with the switch '--text-only' if the target page has a low percentage of textual content (~46.69% of page content is text). As heuristic test turned out positive you are strongly advised to continue on with the tests
 [WARNING] HTTP error codes detected during run:
404 (Not Found) - 1 times, 406 (Not Acceptable) - 492 times
 [DEBUG] too many 4xx and/or 5xx HTTP error codes could mean that some kind of protection is involved (e.g. WAF)

[*] shutting down at 17:02:20` it means that there is no injection or continue scanning with increasing level and risk?
Thank you for your advice!

**Comment by stamparm** [comment]
1) You found a "SQL injection" in other tools just because there is an error message (detected in sqlmap with `heuristic (basic) test`)
2) That tamper script doesn't help with newer versions of ModSecurity
3) If you don't like sqlmap's results please use those other tools (which just parse error messages and detect network latency issues as time-based SQLi)

**Comment by Coolfreeze** [comment]
I like sglmap, I asked a question, what could be the problem, and not condemn

**Comment by stamparm** [comment]
Just told that tamper script doesn't work and that if you like other tools you can use them independently

**Comment by BDhackers009** [comment]
you can bypass mod_security (Thrustwave) using sqlmap....but u have to make ur own custom tamper script....for that u have to know how to bypass mod_security waf manually.....
