### ISSUE TITLE
osx-missing one or more core extensions

### ISSUE THREAD

**Issue by k1pids** [sqlmapproject/sqlmap#3229]
k1pids@Unix  ~/tools/sqlmap   master ± python sqlmap.py
missing one or more core extensions ('bz2', 'gzip', 'pyexpat', 'ssl', 'sqlite3', 'zlib') most likely because current version of Python has been built without appropriate dev packages (e.g. 'libsqlite3-dev')

 ✘  k1pids@Unix  ~/tools/sqlmap   master ± sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D47

**Comment by stamparm** [comment]
With the latest commit you'll be presented with exact missing core extensions. Once you find which one is missing (e.g. `bz2`) please google for e.g. `OSX missing python bz2`

**Comment by stamparm** [comment]
ping?
