### ISSUE TITLE
SQLMAP - os-shell not working

### ISSUE THREAD

**Issue by glenncoco44** [sqlmapproject/sqlmap#3238]
## What's the problem (or question)?
when attempting to upload a shell using os-shell i am getting the following error:
[13:35:38] [INFO] the remote file '/xampp/htdocs/tmpunjgz.php' is larger (726 B) than the local file '/tmp/sqlmapuWNQxz24601/tmpsJybqv' (708B)

The user is root@localhost
DBA is true

## Do you have an idea for a solution?
I have no idea

## How can we reproduce the issue?
I can reproduce the error, it occurs every time i run it
1.
2.
3.
4.

## What are the running context details?

 SQL MAP OS: parrot linux
Database OS: Windows
DB Type: maria db

**Comment by stamparm** [comment]
Are you able to access those dropped files from web browser? What do you get in that case when you try to access http://target/tmpunjgz.php

p.s. There is a possibility that PHP is not enabled/installed in your case. Please debug on what is going on based on upper guidance

**Comment by glenncoco44** [comment]
so when i try to browse to the files, it redirects me to the homepage. Could this issue be caused by the redirect?
