### ISSUE TITLE
Web Crawl Problems

### ISSUE THREAD

**Issue by franx47** [sqlmapproject/sqlmap#324]
Hi, 

I tried to use --crawl to crawl all web directory and then use the link to test for injection, but it seems the result doesnt like as expected. Or, sometimes it found no result at all. Even with .htaccess disabled. I just dont know why SQLMap can't process crawling any further.

--crawl works good with --forms for POST method, but not with GET method (without --forms). 

I expect the result from --crawl like this: 

$ ./sqlmap.py -u "http://www.xyz.com" --crawl=5

http://www.xyz.com/ (start target)
http://www.xyz.com/contact.php (skipped)
http://www.xyz.com/about.php (skipped)
http://www.xyz.com/pages/ (skipped - trying to go deep)
http://www.xyz.com/pages/support.php (skipped)
http://www.xyz.com/pages/products/ (skipped - trying to go deep)
http://www.xyz.com/pages/products/product.php?id=10 (target found for injection testing)
http://www.xyz.com/pages/products/product.php?id=15 (target found - skipped because of same pattern with previous testing)
...

Using result from Google works very good, but I can't just rely on Google result, since Google sometimes blocked for too many same queries at short time. 

And once more, can you please change the target.txt file (contains target site), resulting from Google search. 

Eg: 
Target url,Place,Parameter,Techniques
http://www.xyz.com:80/news.php,GET,id,E
http://www.abc.com:80/product.php,GET,id,EUT
...

I think it will be more easy to check and read along with the full URL link from .csv file, like this: 
Target url,Place,Parameter,Techniques
http://www.xyz.com:80/news.php,GET,id,E (http://www.xyz.com:80/news.php?id=10)
http://www.abc.com:80/product.php,GET,aid,EUT (http://www.abc.com:80/product.php?aid=15)

The reason is sometimes injection process needs normal page to compare with the error page. If I just enter any values for id=, the injection process fails. And also, it keeps time to find injectable URL link from huge log files (inside output dir).

Thanks in advance.

**Comment by medhaniye200** [comment]
even for post method, it is the same
