### ISSUE TITLE
in the newest version its sooo slow to get the tables dumped, i tried the 0.9 version and its good... idk exacly whats the problem

### ISSUE THREAD

**Issue by thugh4cker** [sqlmapproject/sqlmap#3240]
in the newest version its soo slow to get the tables and dump them, i tried some other versions like 0.9 and its great... idk whats exactly the issue but ik that there is something wrong xD

**Comment by stamparm** [comment]
There is nothing useful in this report. Also, you just skipped the Issue template. Not sure how to proceed
