### ISSUE TITLE
Advice for tamper - xforwardedfor 

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3241]
Hopefully you can move it out from --tamper
Separate independently like --cleanup and named --fakeip

if.. ok........😅😅

Also enhance this feature, because this feature is important, it should be turned on by default when necessary

Although I used xforwardedfor and --dropsetcookie
But sometimes I still get stopped

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by huitc** [comment]
I mean, hopefully you can keep optimizing it

**Comment by stamparm** [comment]
I don't understand
