### ISSUE TITLE
last parameter

### ISSUE THREAD

**Issue by hack0mate** [sqlmapproject/sqlmap#3242]
In a new brunch sqlmap always starts from last parameter. Before he always starts from 1st one. That was more clear idea to start from 1st. Now it’s sophisticated.

Just for my taste it’s more clear than sqlmap start to search from 1st parameter than from the last. For sure I could always manually choose parameter for sqlmap but for simply uses I prefer to auto-start from the 1st parameter.

**Comment by stamparm** [comment]
![screenshot](https://user-images.githubusercontent.com/921555/45751066-7e0c4780-bc11-11e8-983a-5434a16f8201.png)

**Comment by stamparm** [comment]
![screen_get](https://user-images.githubusercontent.com/921555/45751174-dba09400-bc11-11e8-846a-7a74512abc0c.png)

![screen_post](https://user-images.githubusercontent.com/921555/45751223-068ae800-bc12-11e8-8d93-f1d1878905c0.png)

**Comment by stamparm** [comment]
![screen_json](https://user-images.githubusercontent.com/921555/45751465-b19ba180-bc12-11e8-8134-8f627f275174.png)

**Comment by stamparm** [comment]
![screen_xml](https://user-images.githubusercontent.com/921555/45751761-99785200-bc13-11e8-9832-389c0802105e.png)

**Comment by hack0mate** [comment]
Thx
