### ISSUE TITLE
Sqlmap Dont retrieve information with (whaith for 0:0:5) but With boolean-based it works hmm

### ISSUE THREAD

**Issue by Adrianh77** [sqlmapproject/sqlmap#3250]
Hi to all
I have this question 

When i Use this command
--Proxychains sqlmap -u 'www.samesite1:.com :D' -D System -T users - C password --dump --random-agent
with vulnerability : Boolean Based
I get     
HI
qwerty
1234567890
etc....

BUT¡¡
When i do exactly the same but with diferent page (Same ip)
I can't retrieve any column information 
--Proxychains sqlmap -u 'www.samesite2:.com :D' -D System -T users - C password --dump --random-agent
With Vulnerability
Microsoft SQL Server/Sybase stacked queries (comment)

Never works... BUT WHY .. I cant undesrtood ;-;
help

**Comment by stamparm** [comment]
I really don't know what are you trying to say.

When you have time-based or stacked-queries usage of mechanisms such as `proxychains` are introducing too much waiting/latency. Don't expect great results for such cases.

Please read BASICS of networking and how PROXYCHAINS work in the first place
