### ISSUE TITLE
question from null connection

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3252]
[INFO] NULL connection is supported with HEAD method ('Content-Length')
[DEBUG] heuristic check skipped because NULL connection used

What's the bad effect of skipping a heuristic check

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by stamparm** [comment]
Removing that part as it is unneeded constraint. In future heuristic check will be made even in case of NULL connections.

"Bad effect" is that basic DBMS error message parsing in such case would be turned on as (previously) it was expected at that part that there is no content being provided (as NULL connection skips the whole content in general case). Anyway, NULL connection is not being utilized in heuristic check, hence the removal of that same constraint

**Comment by huitc** [comment]
> In future heuristic check will be made even in case of NULL connections.
So now, in case of NULL connections, there is no heuristic check, is it? or?....

**Comment by stamparm** [comment]
Starting with today's revision 459e1dd there is. Previously (e.g. yesterday) there wasn't (it has been artificially constrained/disabled because of reasons stated above)

**Comment by huitc** [comment]
Speaking of  NULL connections, can you create something to help testers save more mobile data? Just like  "--null-connection" and "--no-cast"
Because sometimes I use sqlmap on my smartphone.
and i saw internet have more and more about how to use SQLMAP on smartphone, like use "SQLMAP" on android phone by [termux](https://play.google.com/store/apps/details?id=com.termux)
**I think that would be very useful.**

**Comment by huitc** [comment]
no.... if.... I really want to use my phone to run it~...... no other options?

**Comment by huitc** [comment]
https://github.com/sqlmapproject/sqlmap/issues/3404
Do you have any ideas for users who need this thing to run Sqlmap remotely. 
(pc like windows linux, and mobile phone like android(terminal?) )
thx!!

**Comment by huitc** [comment]
> [＃3404](https://github.com/sqlmapproject/sqlmap/issues/3404)
> 對於需要遠程運行Sqlmap的用戶，您有什麼想法嗎？
> （像windows linux一樣的電腦，像android（終端？）手機）
> thx !!

For Android, you can try [termux](https://wiki.termux.com/wiki/Remote_Access)!?
