### ISSUE TITLE
Sybase Multi-rows Enumeration error & not support "TOP" function

### ISSUE THREAD

**Issue by callmev2016** [sqlmapproject/sqlmap#3253]
## What's the problem (or question)?
problem 1, Multi-rows Enumeration error:
SQL:select name from dbname..sysobjects where type='U' and name>'A'
payload:ASCII(SUBSTRING((SELECT ISNULL(CONVERT(VARCHAR(4000),name),CHAR(32)) FROM dbname..sysobjects WHERE type=CHAR(85) and name>CHAR(65)),1,1))>32
excute result: NONE
off course the result is NONE, the SQL statment will return multi-rows, so the payload is incorrect.

problem 2, not support "TOP" function?:
SQL:select top 1 name from tablename where name>'A'
payload:IF(ASCII(SUBSTRING((SELECT TOP 1 ISNULL(CONVERT(VARCHAR(4000),name),CHAR(32)) FROM tablename WHERE name>CHAR(65)),1,1))>32) WAITFOR DELAY '0:0:5'--
excute result: NONE
besides,"select min(name) from tablename where name>'A'" will excute successfully.

suggest 1:
There are hundreds of tables in the database, i used param "--tables" to list the tables, but it failed with only 10/20 tables listed, excuted with param "--tables" once more time will start over and will fail again after sevral tables listed(thats why i hate Blind-SQLI).I just couldn't list tables successfully.
so , can param "--tables" support "--start" "--stop" too?that's all i need.

## How can we reproduce the issue?
the issue is pretty clear?

## What are the running context details?
sqlmap 1.2.9.33
dbms:Sybase(ASE 15.7)
SQL Injection detail:
> Parameter: CID (GET)
>     Type: boolean-based blind
>     Title: AND boolean-based blind - WHERE or HAVING clause
>     Payload: ID=3135' AND 3218=3218 AND 'bVQw'='bVQw
> 
>     Type: stacked queries
>     Title: Microsoft SQL Server/Sybase stacked queries (comment)
>     Payload: ID=3135';WAITFOR DELAY '0:0:5'--

**Comment by stamparm** [comment]
A) Because of smart-ass comments like this, I tend to automatically close such as "invalid"
B) I guess that you are trying to run `--sql-query` and/or `--sql-shell` with `select name from dbname..sysobjects where type='U' and name>'A'` WHICH you haven't mentioned anywhere
C) `SELECT TOP` is highly problematic because it returns items in non-deterministic order. This means that you can expect `SELECT TOP 1 column1 FROM table` and `SELECT TOP 1 column2 FROM table` to be from the same row

**Comment by callmev2016** [comment]
there is another problem, "--columns" works well to list columns, but "-D database -T table --dump" failed, the error information is like "can not list any columns"

**Comment by stamparm** [comment]
`there is another problem, "-D database -T table --columns" works well to list columns, but "-D database -T table --dump" failed, the error information is like "can not list any columns"` <- duplicate of #3247 (fixed 5 days ago) -> please update to the latest revision
