### ISSUE TITLE
can not connect mysql directly

### ISSUE THREAD

**Issue by Yalhu** [sqlmapproject/sqlmap#3254]
## What's the problem (or question)?

I want to connect mysql directly,but it failed: `sqlmap requires 'python-pymysql' third-party library in order to directly connect to the DBMS 'MySQL'. .... `. But I had install pymysql successfully:`Requirement already satisfied:`, both python27 and python37.

The code :`$ python sqlmap.py -d "mysql://admin:admin@192.168.21.17:3306/" -f --banner --dbs`

By the way, there is no colorful output of my git bash shell.
## Do you have an idea for a solution?

None.
## How can we reproduce the issue?

1.
2.

## What are the running context details?

* Installation method (e.g. `pip`, `apt-get`, `git clone` or `zip`/`tar.gz`):
git clone
* Client OS (e.g. `Microsoft Windows 10`):
Microsoft Windows 10
* Program version (`python sqlmap.py --version` or `sqlmap --version` depending on installation): 
1.2.9.33#dev
* Target DBMS (e.g. `Microsoft SQL Server`): 
MySQL
* Detected WAF/IDS/IPS protection (e.g. `ModSecurity` or `unknown`):unknown
* SQLi techniques found by sqlmap (e.g. `error-based` and `boolean-based blind`):
* Results of manual target assessment (e.g. found that the payload `query=test' AND 4113 IN ((SELECT 'foobar'))-- qKLV` works):
* Relevant console output (if any):
[CRITICAL] sqlmap requires 'python-pymysql' third-party library in order to directly connect to the DBMS 'MySQL'. You can download it from 'https://github.com/PyMySQL/PyMySQL'. Alternative is to use a package 'python-sqlalchemy' with support for dialect 'mysql' installed

* Exception traceback (if any):

**Comment by stamparm** [comment]
@Yalhu what do you get for:

`python -c "import pymysql; print 'OK'"`

**Comment by Yalhu** [comment]
get 'ok';
When I on python shell ,use `import pymysql`, there is no error output.

**Comment by stamparm** [comment]
Then something is wrong with your Python environment. Piece of code that is responsible for this error message can be found [here](https://github.com/sqlmapproject/sqlmap/blob/master/lib/core/common.py#L1395-L1420). Nothing different is being done than the import of `pymysql`.
