### ISSUE TITLE
My Sqlmap 'history' doesn't have anything 

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3259]
folder \.sqlmap\history\ there are the following files inside.
- os.hst
- sql.hst
- sqlmap.hst

but It's all 0kb.What am I doing wrong?
newest and older version have this problem too....

win10 64bit
'git clone' way to install it

**Comment by stamparm** [comment]
A) `os.hst` - contains history of commands run inside `--os-shell`
B) `sql.hst` - contains history of commands run inside `--sql-shell`
C) `sqlmap.hst` - contains history of commands inside `--sqlmap-shell`

I believe that it is self-explanatory why those files are empty.

**Comment by huitc** [comment]
but I used it many times, all files still 0kb.
Is that a normal situation?

**Comment by stamparm** [comment]
What have you used many times?

**Comment by huitc** [comment]
100+

**Comment by huitc** [comment]
at least 100 times

**Comment by stamparm** [comment]
But what have you used 100 times?

**Comment by huitc** [comment]
os-shell sql-shell and sqlmap-shell, I have used them all.

**Comment by stamparm** [comment]
Quality of your Issues is really low. I have to infer what the author tries to "report".

In your case most probably you want to tell that you actually used one of those switches, although you haven't stated which one.

On Windows machine you have to install pyreadline ([link](https://pypi.org/project/pyreadline/)) to have the history enabled (also to fill those files). That information could be found by running `python sqlmap.py --dependencies`)

**Comment by huitc** [comment]
but I don't understand why those files still 0kb...

**Comment by huitc** [comment]
ok thx

**Comment by huitc** [comment]
Because I used Termux before, It doesn't have this problem, so... my bad😅😅😥

**Comment by huitc** [comment]
and... If you can remind windows users to install that thing, it would be better.😃
