### ISSUE TITLE
SQLMAP gave 303 redirect error while trying to upload

### ISSUE THREAD

**Issue by depojones** [sqlmapproject/sqlmap#326]
I got the following:

"unable to retrieve any web server path"

I got the path disclosure by adding [] to the URl

/var/www/etc/etc

The response was: "Sqlmap got a 303 redirect hxxp://same-domain/different-folder/tmpudvr. Do you want to follow? Y/n

Y

Unable to upload the file to stager on /var/www/etc/etc

Am i missing something here. 

Thanks

**Comment by ghost1244** [comment]
I have the same problem but I think you have to get another more advanced software to do that 
you can actually crawl the website and see what causing that to happen
