### ISSUE TITLE
Crawl depth not recognized

### ISSUE THREAD

**Issue by nu11by73** [sqlmapproject/sqlmap#3261]
## What's the problem (or question)?
The crawl depth, even in the most recent version of sqlmap, does not recognize the depth set to crawl. instead it is defaulting back to 1.

## How can we reproduce the issue?
1. sqlmap -u url --crawl=10 --batch --forms --risk=3 --level=5

This was run in kali against a single host. Many depths were tried, none were recognized

**Comment by stamparm** [comment]
![crawl](https://user-images.githubusercontent.com/921555/46171276-59af0b80-c2a0-11e8-8827-a9433d8e0843.png)

**Comment by nu11by73** [comment]
I am still getting this error (screenshot attached). I am not sure why you aren't. Where can I go in the source code to hard code a value?

![20180927_150702](https://user-images.githubusercontent.com/35034124/46171863-682d0100-c267-11e8-98f9-cd37640d6752.jpg)

**Comment by nu11by73** [comment]
![20180927_150702](https://user-images.githubusercontent.com/35034124/46172027-f6a18280-c267-11e8-87b5-7bf65b769331.jpg)
