### ISSUE TITLE
Suggestion: Put --delay into milliseconds

### ISSUE THREAD

**Issue by elogada** [sqlmapproject/sqlmap#3269]
## What's the problem (or question)?
Perhaps it would be best to put the `--delay` argument parameter into increments of milliseconds. Currently, the `--delay` mechanism only gives increments in seconds. This would be most useful in WAF evasion, so as to avoid blacklisting.

## Do you have an idea for a solution?
If this is not possible because there is a per-second increment in the scripting language, perhaps it would be useful to create many strings at once natively, with a native 1000 requests per second so that the `--delay` mechanism would simply slow down the process.

## How can we reproduce the issue?
`man sqlmap` states that `--delay` runs in increments of seconds.

## What are the running context details?
Typically, getting blacklisted happens when a WAF faces too many requests at once, whereas the lack of a WAF has no problem with more requests. The `--delay` argument would improve WAF evasion in this case.

**Comment by stamparm** [comment]
It is not integer *per-se*. You can also use decimal number like `0.1`
