### ISSUE TITLE
Persistence of  sqlMapApi results

### ISSUE THREAD

**Issue by zhi-xing-he-yi** [sqlmapproject/sqlmap#3276]
## What's the problem (or question)?
when sqlmap server restart, the old taskId is  invalid。how to save old result in server,let us can request

## How can we reproduce the issue?

1.
2.
3.
4.

## What are the running context details?

* Installation method (e.g. `pip`, `apt-get`, `git clone` or `zip`/`tar.gz`):
* Client OS (e.g. `Microsoft Windows 10`)
* Program version (`python sqlmap.py --version` or `sqlmap --version` depending on installation): 
* Target DBMS (e.g. `Microsoft SQL Server`): 
* Detected WAF/IDS/IPS protection (e.g. `ModSecurity` or `unknown`):
* SQLi techniques found by sqlmap (e.g. `error-based` and `boolean-based blind`):
* Results of manual target assessment (e.g. found that the payload `query=test' AND 4113 IN ((SELECT 'foobar'))-- qKLV` works):
* Relevant console output (if any):
* Exception traceback (if any):

**Comment by stamparm** [comment]
There is no persistence mechanism involved in handling sqlmapapi tasks. Also, there is no plan to include this as the whole concept around it is implicitly volatile (i.e. not solid as for example sqlmap scan logs)
