### ISSUE TITLE
Proxy and IP banned

### ISSUE THREAD

**Issue by sup3rgiu** [sqlmapproject/sqlmap#3278]
Hi,
first I tried running sqlmap without any proxy and when the process finished I got the message `[WARNING] HTTP error codes detected during run: 404 (Not Found) - 3459 times`

Then I created a list of proxy and saved it in a proxy.txt file and then passed this file as `--proxy-file` parameter, however I'm getting the same WARNING, that corresponds to a banned IP.

So I was wondering if is possible to specify how often sql map should change the proxy.

Really thanks in advance!

**Comment by stamparm** [comment]
Then, you may have some other problem, like blocking of a default sqlmap user-agent (use `--random-agent`) OR you from start provided invalid testing data (e.g. some invalid junky URL)

**Comment by huitc** [comment]
try `--tor` ==?
