### ISSUE TITLE
PostgreSQL detection

### ISSUE THREAD

**Issue by Genetick** [sqlmapproject/sqlmap#3282]
Sqlmap version: 1.2.10.12
python version : 2.7.15
Operating system : Windows 10 
İssue : Netsparker Detection : PostgreSQL'i Confirmed :  os linux  ss : http://prntscr.com/l4wuy7
sqlmap not detect
please check your mail address  : hsalih1999@gmail.com

**Comment by stamparm** [comment]
You haven't provided anything useful to start the discussion in the first place

**Comment by stamparm** [comment]
Noe spotted your email in spam folxer. Will check later today

**Comment by Genetick** [comment]
Ok thank you

**Comment by stamparm** [comment]
Pull the latest revision and rerun everything.

p.s. if you want to speed it (after the update in previous step) up use `...-p query --dbms=pgsql --test-filter="::text" --level=5 --risk=3`

**Comment by Genetick** [comment]
The problem persists
how can I help you for your correction 
what information should I give you   ( traffic - url - another)

**Comment by Genetick** [comment]
http://prntscr.com/l55d96

**Comment by stamparm** [comment]
Have I said to update the sqlmap? You are using version from July. This is my last reply to you

**Comment by Genetick** [comment]
ok sorry :(

**Comment by stamparm** [comment]
Everything has been fixed with last revision. You had ONLY one job - to update. Anyway, changing this all mess to invalid so nobody would mix with a valid Issue

**Comment by Genetick** [comment]
new download here : http://prntscr.com/l55m4g
I knew I was downloading the current version 
I've been prejudiced
I'm sorry for the inconvenience
