### ISSUE TITLE
Having Problem with --os-shell

### ISSUE THREAD

**Issue by abaykan** [sqlmapproject/sqlmap#3287]
I put the `--os-shell` command and it works, the output is: 
```
[INFO] retrieved the web server document root: 'C:\xampp\htdocs'
[INFO] retrieved web server absolute paths: 'C:/xampp/htdocs/blabla/login.php'
[INFO] trying to upload the file stager on 'C:/xampp/htdocs/' via LIMIT 'LINES TERMINATED BY' method
```
But how can i select custom path for this? It's automatically trying to upload on that path.
For example, i want to try to upload in `C:/xampp/htdocs/mycustomdir`

**Comment by huitc** [comment]
try --web-root ???

**Comment by abaykan** [comment]
> try --web-root ???
`sqlmap: error: --web-root option requires an argument`

**Comment by huitc** [comment]
no...
--web-root=WEBROOT Web server document root directory (e.g. "/var/www")

**Comment by abaykan** [comment]
> no...
> --web-root=WEBROOT
> Web server document root directory (e.g. "/var/www")
> 
> _從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

It works! Thanks very much!
