### ISSUE TITLE
Please help me to fix this issue

### ISSUE THREAD

**Issue by EthicsOnly** [sqlmapproject/sqlmap#3302]
![penetration](https://user-images.githubusercontent.com/44203646/47024543-8cea0980-d17f-11e8-8fc6-066c5da871e2.png)

**Comment by huitc** [comment]
google it

**Comment by huitc** [comment]
google `sqlmap tutorial`

**Comment by EthicsOnly** [comment]
I have tried everything but not able to get the proper result

**Comment by huitc** [comment]
Then give it up

**Comment by EthicsOnly** [comment]
What is the issue with it?

**Comment by huitc** [comment]
or keep googling

**Comment by huitc** [comment]
Find and view more information about `sqlmap`

**Comment by huitc** [comment]
Listen to me, just fking googling it😃😃(😑😑

**Comment by huitc** [comment]
The pictures you provided, there are also tips!

**Comment by stamparm** [comment]
`CRITICAL` message says it all. This has nothing to do with the sqlmap.
