### ISSUE TITLE
Requestvalidationmode cookie

### ISSUE THREAD

**Issue by Chokrii** [sqlmapproject/sqlmap#3317]
Hello Team,
Does SQlmap handle requestvalidationmode as cookie not as parameter ?

**Comment by stamparm** [comment]
I believe that you've mixed something up here. Not sure what has the RequestValidationMode have with "cookie" or sqlmap? `RequestValidationMode` is a server-side mechanism.

Please elaborate what you wanted to ask in the first place

**Comment by Chokrii** [comment]
Dear Stamparam,
for example 
`parameter '__RequestVerificationToken' appears to hold anti-CSRF token. Do you want sqlmap to automatically update it in further requests? [y/N]`

i'n my case __RequestVerificationToken it's a cookie params not a post params

**Comment by stamparm** [comment]
A) `RequestValidationMode` and `__RequestVerificationToken` have nothing in common than infix `RequestV`. Period
B) sqlmap should be able to update anti-CSRF tokens (`__RequestVerificationToken` too like in your case) even from `Set-Cookie` header (like you asked in last message)

**Comment by Chokrii** [comment]
Great Thanks a lot
