### ISSUE TITLE
JSON problem

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3354]
**post:** 
`info={"list":[],"list2":[{"id":"1","number":"","name":"hey"}]}`

**it appears that provided value for POST parameter 'info (id)' is JSON deserializable. Do you want to inject inside? [y/N]**
`y`

**POST parameter 'info (id)' does not appear to be dynamic**

**sqlmap payload: (url decoded)**
`info={"list2":+[{"number":+""+ANd+5017=7953--+kJsq",+"name":+"hey"}],+"list":+[]}`

### It seems that there are a lot of extra "plus"

**Comment by stamparm** [comment]
Ctrl-C master, you haven't stated how to reproduce this. Plain --data?

**Comment by stamparm** [comment]
sqlmap did nothing wrong here. You provided JSON data inside GET or POST parameter. Value in such cases MUST be URL encoded.

Superfluously closing this down as INVALID.

**Comment by stamparm** [comment]
I am guessing what you did here. You provided POST data with some leftover `+` inside (maybe SQL injection junk from some other tool).

Anyway, I can't reproduce this with `--data='info={"list":[],"list2":[{"id":"1","number":"","name":"hey"}]}'`. 

One more sarcastic comment from you and your every next Issue will be closed down as invalid without any comment. Understood? You have a history of this kind of behavior.

**Comment by huitc** [comment]
**i showed you.... ==?**

**Not yet decoded (chrome):**
`info=%7B%22list%22%3A%5B%5D%2C%22list2%22%3A%5B%7B%22id` ......

**Decoded (notepad++):**
`info={"list":[],"list2":[{"id":"1","number":"","name":"hey"}]}`

### **Get it from the Chrome `DevTools`, and url decode by notepad++ `mime tools`**

### `SAME!?`
**so....... its bug? or? ==???**

**Comment by huitc** [comment]
you can try this:
`info=%7B%22list%22%3A%5B%5D%2C%22list2%22%3A%5B%7B%22id%22%3A%221%22%2C%22number%22%3A%22%22%2C%22name%22%3A%22hey%22%7D%5D%7D`

**Comment by huitc** [comment]
@stamparm

**Comment by stamparm** [comment]
User used unencoded '+' inside his POST data (provided via email). That same `+` represents whitespace if not encoded properly <- sqlmap, if finds one, concludes that POST format uses `+` as a whitespace. Now, all those `+` inside the final payload were whitespaces which resulted from `json.dumps` where whitespace has been added after character `,`.

Anyway, not sqlmap's fault. User should properly URL encode `+` before posting to the sqlmap (or using inside the HTTP communication).
