### ISSUE TITLE
Tamper script doesn't get full payload in case of manual injection point

### ISSUE THREAD

**Issue by jeroen-80** [sqlmapproject/sqlmap#3361]
I'm testing an app with URL like http://myapp?secret=payload_encoded, running the latest GIT version. I can decode and encode the payload. Encoding for testing is implemented in a custom sqlmap tamper script. Works well for something like -u http://myapp?secret=payload_plain -p secret --tamper=customencode.

However... The payload_plain can look like value!!action (!! seems to be a placeholder / delimiter). If I try a sqlmap using value*!!action to insert payloads after value, the tamper script only gets input payload = "value+sqlmap_magic" instead of what I expect = "value+sqlmap_magic+!!action". Obviously, thing go wrong since the server expects a fully encoded parameter but gets customencode(value) + plain action.

Is there a magic switch I'm missing or is it a bug? Thanks!

**Comment by stamparm** [comment]
I really couldn't understand a thing. Where is that custom tamper script? How to deal with this kind of issues? Please guide me

**Comment by jeroen-80** [comment]
>Where is that custom tamper script?

In /opt/sqlmap/tamper.

>How to deal with this kind of issues? Please guide me

* Target uses parameter encoding.
* To test a parameter for SQLi, I need two things: a payload generator (sqlmap) and payload encoding (custom tamper script).
* When using basic sqlmap functionality and a basic input (-u http://target?secret=aa!!123), the tamper script receives input "aa!!123' or 1=1--" and returns encode("aa!!123' or 1=1--"). Sqlmap sends out: http://target?secret=encode("aa!!123' or 1=1--"), e.g. http://target?secret=AsdfmaDBNAD. Works as expected.
* When inserting at a specific location e.g. "aa*!!123", the tamper script receives just "aa; or 1=1--" and sends out http://target?secret=encode("aa' or 1=1--")+'!!123', e.g. http://target?secret=ASDASKD!!123.
* So the issue seems to be: in case of using the '*' functionality, the parameter value after the injection point is not passed to the tamper script.

**Comment by stamparm** [comment]
Only the first part is expected to be a dynamic part of payload. Afterwards is a static suffix. Adapt your script accordingly

**Comment by stamparm** [comment]
p. s. plain_action can be customencoded() (by yourself) prior the sqlmap run.
