### ISSUE TITLE
how do i fix the url is not stable on sqlmap?

### ISSUE THREAD

**Issue by omrirubin** [sqlmapproject/sqlmap#3362]
target URL content is not stable (i.e. content differs). sqlmap will base the page comparison on a sequence matcher. If no dynamic nor injectable parameters are detected, or in case of junk results, refer to user's manual paragraph 'Page comparison'
how do you want to proceed? [(C)ontinue/(s)tring/(r)egex/(q)uit]

how do i fix that ??
anybody has an idea?

**Comment by stamparm** [comment]
Unstable content is nothing to worry about. It is fairly common, especially in ad-abundant pages.

You can't "fix" it as there is nothing to fix. It is just annoyance. sqlmap by default has a really good engine to cope with it. If you really want to be sure that it doesn't affect the sqlmap's detection mechanism (although, I doubt that is the case that you should worry about), you can use one of options/switches described at [Wiki](https://github.com/sqlmapproject/sqlmap/wiki/Usage#page-comparison)
