### ISSUE TITLE
sqlmap time request problem

### ISSUE THREAD

**Issue by mrcokito** [sqlmapproject/sqlmap#3363]
Hi, I have a website vulnerable to Blind SQL Injection.
The server returns one answer if the query is false, and another if the query is true.
The problem is that if the query is badly formed, the server returns the same answer as if the query is true. However, if the query is true it takes about 30 seconds to respond, and if it is badly formed the response is immediate.

Neither the boolean blind technique nor the boolean based blind technique work for me. 

Is there any way to tell sqlmap that if it takes more than x seconds to take it as true, and if not, take it as false?

Thank you very much in advance.

Greetings,

Carlos.

**Comment by stamparm** [comment]
It really doesn't make any sense to mix boolean-based blind with timeouts. "`...if the query is badly formed, the server returns the same answer as if the query is true`" <- sqlmap can't work that way. There has to be a clear distinction between TRUE and FALSE responses, while junk/badly formed queries must not be taken blindly as TRUE responses (junk requests should be detected as NONE - neither TRUE nor FALSE). Junk is junk. If such option would be available, where responses to junk queries along with true and original ones would be treated as TRUE, sqlmap would have a really bad day detecting such case.

TL;DR there is no such option/switch nor there is a plan to implement it (as there is no clear rationale for it)
