### ISSUE TITLE
HOW TO Compile to ".jar" file?

### ISSUE THREAD

**Issue by safebaseline** [sqlmapproject/sqlmap#3368]
HOW TO Compile to ".jar" file?

**Comment by stamparm** [comment]
If you mean Python to Jython, never done it. Also, based on quick Googling, I am pretty sure that this could be impossible for large Python projects. Everywhere there are simplistic methods to compile single `.py` files (like [here](https://www.ssec.wisc.edu/~tomw/visadtutor/compile.html))
