### ISSUE TITLE
[Question] Modification & Redistribution of the code

### ISSUE THREAD

**Issue by s0md3v** [sqlmapproject/sqlmap#3369]
Hi @stamparm ,

I am quite new to open source and I am not really sure how licenses work so I thought it would be a good idea to talk to you about it.

Well, I want to use WAF signatures from <[https://github.com/sqlmapproject/sqlmap/blob/master/waf/](https://github.com/sqlmapproject/sqlmap/blob/master/waf/)> in my project [XSStrike](https://github.com/s0md3v/XSStrike) for WAF detection. My project is licensed under GPL v3.

I will store the rules in a json file (i.e. WAF specific status codes, regex patterns for headers and source) and compare them against the target's response with a script written by me from scratch.

I will give credits to sqlmap in the README as well as project's website but the problem is that I am offering a propriety license for commercial usage just like sqlmap so I am not sure if your LICENSE allows that.

Yes, I have been through your License but English isn't my first language as well as I am not sure if copying only the signatures can restrict me from doing stuff.
That's all.

Thanks for your contribution to the open source community. sqlmap is a piece of art.
Regards,
Somdev Sanwagn

**Comment by stamparm** [comment]
1) Just add a proper reference (like you've already mentioned)
2) As of propriety license, sqlmap currently has that "commercial" part, but currently we don't utilize it (a.k.a. we don't have anyone paying for the license).
3) By googling around I've found a [comment](https://softwareengineering.stackexchange.com/a/47048) partially explaining this whole situation. You can freely use our code (it's base is GPLv2), even for commercial purposes, as long as your source code is freely available.
