### ISSUE TITLE
a suggestion about custom parameters

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3371]
About custom parameter, I think we should let the user let it know what the range value is
like `https://hey.com/index.php/zh/%INJECT HERE START%123%INJECT HERE END%`
Because sometimes you will encounter extreme situations, like this --> #3133 #3373  
Some places don't need to be escaped (url encode), but.... (or put on the wrong places)
All in all, this helps to make more accurate and targeted tests.
so...  I think it's a necessary function, and I hope you can ....😈

**Comment by stamparm** [comment]
Neither I see any benefit nor anybody would use this. Also, this looks like too messy to be used.

Implementing something just for the sake of implementation does not make any sense

**Comment by huitc** [comment]
`Neither I see any benefit nor anybody would use this.` really?......

```Because sometimes you will encounter extreme situations, like this --> #3133 #3373
Some places don't need to be escaped (url encode), but.... (or put on the wrong places)```

**Comment by huitc** [comment]
Instead, I think it's better to make it happen now
i think more and more people will come up with similar suggestions in the future, so...😈😈😉

**Comment by huitc** [comment]
@stamparm

**Comment by stamparm** [comment]
I'll wait later then as I don't see an added value in this proposition right now
