### ISSUE TITLE
I constantly get errors

### ISSUE THREAD

**Issue by JackandBlackLLL** [sqlmapproject/sqlmap#3378]
Pls help
I use sqlmap -u «https://www.xxx.com/index.php?xx=xx&xx=xx&xx=5» --cookie «XXXXXX» -p id 

GET ERRORS

[1] 1924
[2] 1925
bash: --cookie: command not found
[2]+  Done                    d=deladdress
bash: sqlmap.py: command not found
bash: -p: command not found

OR 

[1] 1942
[2] 1943
bash: --cookie: command not found

or other 

What is problem?

**Comment by JackandBlackLLL** [comment]
[4] 2664
[5] 2665
bash: --cookie: command not found
bash: sqlmap.py: command not found
bash: -p: command not found

**Comment by stamparm** [comment]
You have to enclose with quotes parameter value containing character & (in this case url). That's how all OS shells work

**Comment by JackandBlackLLL** [comment]
Can you give me example?
Bad english

I tried

sqlmap -u https://www.xxx.com/index.php?xx=xx&xx=xx&xx=5 --cookie «XXXXXX» -p id
sqlmap -u «https://www.xxx.com/index.php?xx=xx&xx=xx&xx=5» --cookie «XXXXXX» -p id
sqlmap -u «https://www.xxx.com/index.php?xx=xx&xx=xx&xx=5» -p id

I constantly get an error

-p command not found
--cookie command not found

**Comment by huitc** [comment]
`sqlmap -u "https://www.xxx.com/index.php?xx=xx&xx=xx&xx=5" -p id` try this?   ==?
