### ISSUE TITLE
queries seems to not be passed to tamper script

### ISSUE THREAD

**Issue by noraj** [sqlmapproject/sqlmap#3384]
## What's the problem (or question)?

It seems that queries listed here are never passed to tamper scripts like `randomcase`.

https://github.com/sqlmapproject/sqlmap/blob/0d2db3253903fe61f316c1040dcc52dd358ec731/xml/queries.xml#L303-L354

Resulting in keywords like `LIMIT` no case modified.

For example I can see payload like this one where `LIMIT` should be mixed case too (I used https://github.com/sqlmapproject/sqlmap/pull/3383/files#diff-315c6a7fdc5f9a0354a3e591f764d028):

```
[04:17:40] [PAYLOAD] a" AnD SuBsTr((SeLeCt CoAlEsCe(tbl_name,' ') FrOm sqlite_master WhErE type='table' LIMIT 1,1),1,1)>'\x01'-- DxSl
```

## Do you have an idea for a solution?

No sorry.

## How can we reproduce the issue?

1. use `tamper=randomcase` and `-v 4` at least
2. use a sql database where you can do a Boolean blind sqli

## What are the running context details?

* Installation method : `pacman -S` from Manjaro community repository
* Client OS : Manjaro (up-to-date rolling release)
* Program version : `1.2.10#stable`
* Target DBMS : SQLIte 3

**Comment by stamparm** [comment]
Unable to reproduce:

![screenshot](https://user-images.githubusercontent.com/921555/48943930-16ca8680-ef25-11e8-8394-31ec5a235216.png)

**Comment by huitc** [comment]
Is it because he didn't use the beta version? or? @stamparm

**Comment by stamparm** [comment]
@huitc as said, I can't reproduce the "issue". I would really need a correct revision, whole console output and used options/switches
