### ISSUE TITLE
I found something, it's very interesting and useful!? maybe.. hope you can..😈

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3385]
I think the idea of this thing is very interesting
But it needs to be improved

https://github.com/m4ll0k/Atlas
can you...?😈😈😈😈😈

**Comment by huitc** [comment]
@m4ll0k

**Comment by huitc** [comment]
? @stamparm

**Comment by stamparm** [comment]
Seen it. It could be used for heuristic check of WAF bypass, BUT, I am very skeptical about its practical value. Newbies would abuse it and do lots of nagging regarding tamper scripts "appearing to be useful".

**Comment by huitc** [comment]
about tamper, I found something that might help some users go ahead to...

bypass WebKnight, Thinkphp firewall... tamper
https://github.com/LxiaoGirl/sqlmapTamper.git

and this, like Atlas (detection)
https://github.com/3xp10it/bypass_waf

**Comment by huitc** [comment]
Can you do a function like this one ?
https://hashcat.net/wiki/doku.php?id=restore

because some task need a lot of time, but I need to move my location, or reboot...

(some task have lot of parameter to test
((now, I have a task have 20 POST parameter...

**Comment by huitc** [comment]
#1236

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/issues/3348#issuecomment-447802844

**Comment by huitc** [comment]
https://github.com/Ekultek/WhatWaf/
https://github.com/EnableSecurity/wafw00f
