### ISSUE TITLE
Problem displaying data on sqlmap

### ISSUE THREAD

**Issue by iwantaturboman** [sqlmapproject/sqlmap#3387]
## What's the problem (or question)?
I've recently updated sqlmap to 1.2.11.12 version. (I used the 1.0.10.54).
The problem is simple. On this query : 
`sqlmap.py -u www.target.com -D database -T account -C id,username,pwd --where "id=1" --dump`

On sqlmap 1.0.10.54, i retrieved something like this 
```
Database : database
Table: account
[1 entrie]
+----------+----------+----------+
|    id    | username |    pwd   |
+----------+----------+----------+
|     1    |   stam   |   parm   |
+----------+----------+----------+
```

Today, for the same query, on sqlmap 1.211.12
```
Database : database
Table: account
[3 entries]
+----------+----------+----------+
|    id    | username |    pwd   |
+----------+----------+----------+
|    parm  |   parm   |   parm   |
|    stam  |   stam   |   stam   |
|     1    |     1    |     1    |
+----------+----------+----------+
```
I don't understand why data is displayed like that ? What's the problem ?
Thanks.

## What are the running context details?

* Fresh installation from `zip`:
* Microsoft Windows 7
* Python 2.7

**Comment by stamparm** [comment]
I would really need more info. Can you please share unredacted details to `miroslav@sqlmap.org`?

**Comment by stamparm** [comment]
Fixed with https://github.com/sqlmapproject/sqlmap/commit/65f227fe6534eef78baa81f1c90ceadd442b261c

**Comment by iwantaturboman** [comment]
Thanks a lot @stamparm !!!
