### ISSUE TITLE
Problem during user-agent scans

### ISSUE THREAD

**Issue by stasinopoulos** [sqlmapproject/sqlmap#3388]
Dear @stamparm,
During a testing in the latest dev version of sqlmap (i.e. 1.2.11.16#dev), it was identified that in case that a user defines `-p User-agent` (in order to check the User-Agent Header for SQL injection), sqlmap does not testing the generated payloads in the User-Agent Header.

![1](https://user-images.githubusercontent.com/5289251/49099438-1f4ef400-f27a-11e8-9eec-032315df8fae.png)

![2](https://user-images.githubusercontent.com/5289251/49099442-22e27b00-f27a-11e8-8b13-e55c24666e5e.png)

Nevertheless, in case that the user defines the custom injection marker ('*') in the User-Agent Header, the sqlmap is testing all the generated payloads in the User-Agent Header.

![3](https://user-images.githubusercontent.com/5289251/49099487-3ee61c80-f27a-11e8-9b13-b613bf600a15.png)

![4](https://user-images.githubusercontent.com/5289251/49099496-43123a00-f27a-11e8-9ab3-5005ef8c112e.png)

**Comment by stamparm** [comment]
Not sure how to reproduce it. Just tried something like this and it worked fine:

![123](https://user-images.githubusercontent.com/921555/49117866-7e286380-f2a2-11e8-8927-a89f95a92faa.png)

Hence, please provide more details on ways to reproduce the issue

**Comment by stasinopoulos** [comment]
@stamparm the problem occurs in case that a user is parsing the request via `-r` parameter.

![screenshot 2018-11-28 at 10 46 13](https://user-images.githubusercontent.com/5289251/49139901-97a9c980-f2fb-11e8-9f01-9d54e2790cf2.png)
