### ISSUE TITLE
Skip sqlmap waf testing

### ISSUE THREAD

**Issue by johnyjin** [sqlmapproject/sqlmap#3393]
When I try to start testing with sqlmap, sqlmap will send queries like these :

> 1'tFmggO<'">AeQpzc

> 1"(,..,'(,,

And my target will response with error 500 and sqlmap will show me connection dropped

I tested my target manualy and it is okey

So how should I skip those two queries? Or in which files I can comment this lines?

Regards

**Comment by stamparm** [comment]
Those are really the most harmless payloads out of all others in sqlmap. You have bigger issues than you think. Closing this down as sqlmap won't be of a help here

**Comment by johnyjin** [comment]
I didn't say these words at all
I need some helps because I'm not programmer
So If you don't like to help, You don't need to joke me instead of helping

**Comment by stamparm** [comment]
Can you please pinpoint where did I made a joke of you? I said that those payloads are most harmless than ALL other payloads used by sqlmap. Neutralizing those won't help you in any way as sqlmap will try more evasive payloads

**Comment by huitc** [comment]
You need to know why the server will send you  "500"

**Comment by huitc** [comment]
Sometimes it's not because WAF blocks your connection.

**Comment by johnyjin** [comment]
I know why server send me error 500
It just becasue of these payloads 1'tFmggO<'">AeQpzc
SQLMap is great tools but I need to disable these payloads for now
How should I do that?

**Comment by huitc** [comment]
Which thing in this payload leads to the "500", have you found it?

**Comment by huitc** [comment]
`>` or `'` or `"` ......?

**Comment by johnyjin** [comment]
Yes
<'"> and "(,..,'(,,

**Comment by huitc** [comment]
Which or what did you use? (tamper
and... What did you enter

**Comment by johnyjin** [comment]
tamper=charencode,space2dash

**Comment by huitc** [comment]
Probably because it initially needed to test for a firewall and use something that would obviously be blocked.
right? @stamparm

**Comment by huitc** [comment]
If you want, you can use --ignore-code

**Comment by johnyjin** [comment]
What does --ignore-code do?

**Comment by huitc** [comment]
> What does --ignore-code do?

google it

**Comment by huitc** [comment]
Have you been able to continue testing because of this thing?
If it doesn't affect you, ignore it
