### ISSUE TITLE
Kerberos authentication

### ISSUE THREAD

**Issue by re8el** [sqlmapproject/sqlmap#3404]
## What's the problem (or question)?
Hi, I'm trying to authenticate using kerberos (Authorization: Negotiate) but no sucess, even setup sqlmap to use Fiddler as upstream proxy no success.

Does sqlmap support Kerberos auth? Any work arround...?

## Do you have an idea for a solution?
Nope.

## What are the running context details?
Kali rolling x64
sqlmap from git, latest version
Fiddles running on Windows10
Target webapp .Net (auth kerberos)

**Comment by stamparm** [comment]
It doesn't support kerberos. Just spent some time researching and there doesn't seem to be a remotely easy way how to do it in Python (Note: `python-kerberos` is far from plug-and-play and far from stable).

No known workarounds :(

**Comment by stamparm** [comment]
--auth-type=Negotiate
