### ISSUE TITLE
I found a bug when i use -d

### ISSUE THREAD

**Issue by peterzzzz** [sqlmapproject/sqlmap#3419]
When i use -D like this -D "XXXProduct_xxxx_V6.1" --tables
it will show fetching number of tables for database 'XXXProduct_xxxx__V6.[1]',
When  i add "." in it ,it will always add [] after "."

**Comment by stamparm** [comment]
You've skipped the Issue template.

I guess that you are using older revision than one available here in repository. Revision `1.2.12.34` or newer should not behave like described.
