### ISSUE TITLE
sqlmap.py: error: missing a mandatory option

### ISSUE THREAD

**Issue by trobanko** [sqlmapproject/sqlmap#3426]
I installed sqlmap recently, and i kept getting the error "sqlmap.py: error: missing a mandatory option" no matter what i put in -h, -u nothing works. I have used sqlmap on another machine and it works fine so i dont know why it isnt working here
![screenshot_71](https://user-images.githubusercontent.com/46400876/50725687-ff78de80-1109-11e9-9773-afe9101619f6.png)

**Comment by huitc** [comment]
What did you enter?

**Comment by trobanko** [comment]
> What did you enter?

-h

**Comment by trobanko** [comment]
> Try reinstalling it

I tried multiple times and nothing happend

> try --dependencies?

![screenshot_72](https://user-images.githubusercontent.com/46400876/50726072-7d3fe880-1110-11e9-9559-5d4da957178c.png)

**Comment by stamparm** [comment]
You are having a trouble with your Python environment setup. Something prevents argument passing to sqlmap. Also, you haven't filled issue template, hence, there is nothing to be done here.

**Comment by trobanko** [comment]
yes, i can tell i have a problem. so... how can i fix it?

**Comment by huitc** [comment]
reinstall everything 🤔🤔😏😏

**Comment by huitc** [comment]
and the system

**Comment by trobanko** [comment]
> reinstall everything 🤔🤔😏😏

I rinstalled everything multiple times

**Comment by stamparm** [comment]
@trobanko please give steps how to reproduce and I'll try to help

**Comment by stamparm** [comment]
I haven't asked you to solve it. I asked you to give me steps to reproduce.

**Comment by trobanko** [comment]
> I haven't asked you to solve it. I asked you to give me steps to reproduce.
step 1: open cmd
step 2: go the the sqlmap dir
step3: do sqlmap.py -"anything"
step4: it doesnt work

**Comment by stamparm** [comment]
Unreproducible. Goodbye

**Comment by trobanko** [comment]
Well obviously you fucking dumbass cause I am the one that has the problem not you

**Comment by huitc** [comment]
you will block him? or? 😂🤣 @stamparm

**Comment by trobanko** [comment]
> you will block him? or? 😂🤣 @stamparm

he probs will cause he is a fucking cunt

**Comment by trobanko** [comment]
yo @stamparm im fucking ur mum rn, she suddenly stopped breathing, is that normal?
