### ISSUE TITLE
Basic authentication special characters

### ISSUE THREAD

**Issue by cmaggiulli** [sqlmapproject/sqlmap#3428]
## Basic Authentication issue

Basic authentication does not work using the  `--auth-type=BASIC --auth-cred="username:password"`  flags when the username or password contains the ! (U+0021) character.  

## Reproduce

To reproduce this issue attempt to run the follolwing against any API that accepts basic authentication, and with a password contains a !

` ./sqlmap.py --random-agent=true --auth-type=BASIC --auth-cred="user123:!passwordX" -u https://basse.com/bpm/api/4.0/identities/users/joshpurge?rolesFlag=false&groupsFlag=false`

## Fix

If someone can also verify this issue I would like to issue a pull request as my first contribution to this project

**Comment by stamparm** [comment]
1) You've "forgot" to fill out the issue template. Hence, we have to do some guessing here
2) Your `-u` is not enclosed with quotes, hence, causing different problem (you have a special character `&` inside which requires such parameters to be enclosed in either single or double quotes - e.g. `-u "https://........&groupsFlag=false"`)
3) Character `!` is a special character in shell (I guess that you use bash or similar). Enclose such parameters with single quotes (e.g. `--auth-cred='user123:!passwordX'`)

p.s. this ALL doesn't have anything to do with sqlmap. Just compare results of `echo 'foo:!bar'` and `echo "foo:!bar"`
