### ISSUE TITLE
[Feature Request] AppImage

### ISSUE THREAD

**Issue by zero77** [sqlmapproject/sqlmap#3431]
Can you please provide an AppImage, this is basically just a standalone portable executable for linux, that doesn't require installation.
Thanks

There are different ways to create AppImages:

    Use Open Build Service (OBS)
    Convert existing binary packages (.deb, .rpm, …)
    Bundling your Travis CI builds as AppImages
    Run linuxdeployqt on your Qt application
    Using electron-builder for Electron-based apps
    Create an AppDir manually

Documentation:
https://docs.appimage.org/packaging-guide/ways.html
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages

**Comment by stamparm** [comment]
![123](https://user-images.githubusercontent.com/921555/50859419-9dcba500-1393-11e9-86df-c379657f7b3c.png)

**Comment by stamparm** [comment]
As I can see that this is just one of many "bulk" requests, I guess that you won't mind to close it down. Main reason is that I don't see a point in creating an AppImage on Python projects which don't have any outer (hard) dependencies. Also, current `PyPI` (piip) packaging is more than enough for anyone that requires simple installation (and monthly updates) of sqlmap
