### ISSUE TITLE
problem about `--search` by using the latest version

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3441]
i entry  `--search -T 2017,2018`, but it just searched for tables `%2017%`

`python2 sqlmap.py -r xxx.txt -v 2 --null-connection --sqlmap-shell --random-agent --tamper randomcase,xforwardedfor,varnish`
sqlmap-shell> `--hex --fresh-queries --search -T 2017,2018`
[1] as LIKE table names (default)
[2] as exact table names
`>1`
Database: xxx
[46 tables]
+--------------------------------------------------+
| xxxxxx_DAILY_LOG_2017_01         |
| xxxxxx_DAILY_LOG_2017_02         |
| xxxxxx_DAILY_LOG_2017_03         |
| xxxxxx_DAILY_LOG_2017_04         |
| xxxxxx_DAILY_LOG_2017_05         |
| xxxxxx_DAILY_LOG_2017_06         |
| xxxxxx_DAILY_LOG_2017_07         |
| xxxxxx_DAILY_LOG_2017_08         |
| xxxxxx_DAILY_LOG_2017_09         |
| xxxxxx_DAILY_LOG_2017_10         |
| xxxxxx_DAILY_LOG_2017_11         |
| xxxxxx_DAILY_LOG_2017_12         |
| xxxxxx_RAW_LOG_2017_01           |
| xxxxxx_RAW_LOG_2017_10           |
| xxxxxx_RAW_LOG_2017_11           |
| xxxxxx_RAW_LOG_2017_12           |
| Cxxxxxx_2017_08         |
| Cxxxxxx_2017_09         |
| Cxxxxxx_2017_10         |
| Cxxxxxx_2017_11         |
| Cxxxxxx_2017_12         |
| xxxxxx_2017_08         |
| xxxxxx_2017_09         |
| xxxxxx_2017_10         |
| xxxxxx_2017_11         |
| xxxxxx_2017_12         |
| xxxxxx_2017_01                   |
| xxxxxx_2017_02                   |
| xxxxxx_2017_03                   |
| xxxxxx_2017_04                   |
| xxxxxx_2017_05                   |
| xxxxxx_2017_06                   |
| xxxxxx_2017_07                   |
| xxxxxx_2017_08                   |
| xxxxxx_2017_09                   |
| xxxxxx_2017_10                   |
| xxxxxx_2017_11                   |
| xxxxxx_2017_12                   |
| xxxxxx_2017_08 |
| xxxxxx_2017_09 |
| xxxxxx_2017_10 |
| xxxxxx_2017_11 |
| xxxxxx_2017_12 |
| xxxxxx_2017_08                   |
| xxxxxx_2017_09                   |
| xxxxxx_2017_10                   |
+--------------------------------------------------+

do you want to dump tables' entries? [Y/n]

**Comment by stamparm** [comment]
Non-reproducible:

```
python sqlmap.py -u "http://testphp.vulnweb.com/artists.php?artist=1" --search -T 2017,artists -D acuart --fresh-queries
...
do you want sqlmap to consider provided table(s):
[1] as LIKE table names (default)
[2] as exact table names
> 
[23:47:36] [INFO] searching tables LIKE '2017' for database 'acuart'
[23:47:36] [INFO] fetching number of tables LIKE '2017' in database 'acuart'
[23:47:36] [WARNING] running in a single-thread mode. Please consider usage of option '--threads' for faster data retrieval
[23:47:36] [INFO] retrieved: 0
[23:47:36] [WARNING] no tables LIKE '2017' in database 'acuart'
[23:47:36] [INFO] searching tables LIKE 'artists' for database 'acuart'
[23:47:36] [INFO] used SQL query returns 1 entry
Database: acuart
[1 table]
+---------+
| artists |
+---------+

do you want to dump tables' entries? [Y/n] 
...
```
