### ISSUE TITLE
Can I use it to scan xss and csrf?

### ISSUE THREAD

**Issue by weathon** [sqlmapproject/sqlmap#3444]
Can I use it to scan xss and csrf?

**Comment by huitc** [comment]
In a way, it's OK

**Comment by stamparm** [comment]
@weathon sqlmap will warn you if something looks like XSS vulnerable, but in no way it is designed to fully test those vulnerabilities.

In short, the answer is NO. You should use web application vulnerability scanners. sqlmap is ONLY SQL injection scanner.

**Comment by weathon** [comment]
Thanks
