### ISSUE TITLE
problem about character decoding

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3448]
sqlmap detects that it is `big5`, but... it still decodes it with `utf8`

`-u "http://123.com/login.php" --data "userid=&pwd=&submit=%BDT%BB%7B"`

`[DEBUG] declared web page charset 'big5'`

`it appears that provided value for POST parameter 'submit' has boundaries. Do you want to inject inside? ('%BDT%BB*{') [y/N] N`

```
---
Parameter: userid (POST)
    Type: stacked queries
    Title: Microsoft SQL Server/Sybase stacked queries (comment)
    Payload: userid=123';WAITFOR DELAY '0:0:5'--&pwd=123&submit=%BDT%BB{
    Vector: ;IF([INFERENCE]) WAITFOR DELAY '0:0:[SLEEPTIME]'--

    Type: AND/OR time-based blind
    Title: Microsoft SQL Server/Sybase time-based blind (IF)
    Payload: userid=' WAITFOR DELAY '0:0:5'-- IiPH&pwd=&submit=%BDT%BB{
    Vector: IF([INFERENCE]) WAITFOR DELAY '0:0:[SLEEPTIME]'
---
```

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/issues/3348#issuecomment-447802844
