### ISSUE TITLE
Error Based SQLi msg update

### ISSUE THREAD

**Issue by nsonaniya2010** [sqlmapproject/sqlmap#3449]
## What's the problem (or question)?
In current, Error based messages ( specially in MySQL) following error based messages are getting captured: (under file: https://github.com/sqlmapproject/sqlmap/blob/master/xml/errors.xml ) 

```
    <dbms value="MySQL">
        <error regexp="SQL syntax.*?MySQL"/>
        <error regexp="Warning.*?\Wmysqli?_"/>
        <error regexp="MySQLSyntaxErrorException"/>
        <error regexp="valid MySQL result"/>
        <error regexp="check the manual that corresponds to your (MySQL|MariaDB) server version"/>
        <error regexp="Unknown column '[^ ]+' in 'field list'"/>
        <error regexp="MySqlClient\."/>
        <error regexp="com\.mysql\.jdbc"/>
        <error regexp="Zend_Db_(Adapter|Statement)_Mysqli_Exception"/>
        <error regexp="Pdo[./_\\]Mysql"/>
        <error regexp="MySqlException"/>
</dbms>
```
But I have encountered with one more message which is not getting captured according to SQLmap, Error based XML file.

```
Error query: SELECT * FROM abc where xyz='1''
```

## Do you have an idea for a solution?

Adding one more regular expression in 'MySQL':

```
Error query: select , re.IGNORECASE
```
Some changes could be done similar to above.

**Comment by stamparm** [comment]
Too generic. Doesn't have anything to be used for proper MySQL identification (to distinguish it from other DBMSes)
