### ISSUE TITLE
about detecting the server's SQL mode settings, to choose whether to use similar characters to bypass the WAF

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3450]
first, check the server's SQL mode settings
`SELECT @@SESSION.sql_mode`
`SELECT @@GLOBAL.sql_mode`
`SELECT @@sql_mode`
...
(You know it early

then, try to inject similar characters if permissions and other factors allow......
like `s` --> `ŝ`

[https://www.compart.com/en/unicode/search?q=s+#characters](https://www.compart.com/en/unicode/search?q=s+#characters)
[https://www.compart.com/en/unicode/search?q=Apostrophe#characters](https://www.compart.com/en/unicode/search?q=Apostrophe#characters)

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/issues/3348#issuecomment-447802844
