### ISSUE TITLE
About detecting that the response to be received is too large by using --technique U

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3451]
I wanted to dump the database table, but the contents of the table were too large, so I spent a few days dumping it (its real

I remember that there was a feature that could cut the data into small pieces to speed up and avoid the server or WAF cutting off my connection.

At least let me know how progress is going ^^'' (but i want to use -v 2... ==
https://github.com/sqlmapproject/sqlmap/issues/2777
https://github.com/sqlmapproject/sqlmap/issues/2882

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/issues/3348#issuecomment-447802844

**Comment by huitc** [comment]
==?
