### ISSUE TITLE
About some characters that cannot be decoded on Windows CMD

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3453]
If some characters cannot be decoded/detected, Sqlmap will be shutdown.

`chcp 65001`
https://blog.csdn.net/jia304349145/article/details/59706455
https://blog.csdn.net/ggggiqnypgjg/article/details/53271541
http://www.runoob.com/python/python-chinese-encoding.html
http://120.79.67.173/2018/11/14/Win10-%E5%90%84%E7%A7%8D%E7%8E%AF%E5%A2%83UTF-8%E7%BC%96%E7%A0%81%E9%85%8D%E7%BD%AE/
https://www.jianshu.com/p/609b037f9f36

do you have any idea?

**Comment by huitc** [comment]
my PC default CHCP setting is set to `950` (traditional chinese)
950: ` ??賊?`
but I still need to manually convert it to `65001` (utf8) to let it output chinese characters normally
65001: ` 名單相關 `

**Comment by DamaneDz** [comment]
type in your console chcp 720
and check again

**Comment by stamparm** [comment]
With the latest revision/commit there should be a better support for Windows/codepage/Python combo. Please retest.

I've tested against CP852 (my local) and it works pretty good. Also, if the character can't be found in current code-page (e.g. Chinese in Central-European code page), character will be replaced with `?`

**Comment by stamparm** [comment]
Done a through tests, improvements and generalization regarding this case. It should work pretty good now compared to previous revisions
