### ISSUE TITLE
Memory consumption on Windows

### ISSUE THREAD

**Issue by eastsida** [sqlmapproject/sqlmap#3459]
Hello, I have a such problem:
OS: Windows Server 2019
SqlMap: 1.3-55-g915d2bd version
Parameter: #1* (URI)

    Type: boolean-based blind
    Title: OR boolean-based blind - WHERE or HAVING clause
    Payload: https://www.hidden.com:443/-3542' OR 3912=3912 AND 'vXvf'='vXvf

    Type: AND/OR time-based blind
    Title: MySQL >= 5.0.12 OR time-based blind
    Payload: https://www.hidden.com:443/test' OR SLEEP(5) AND 'szHo'='szHo

Command: 
sqlmap.py -u https://www.hidden.com/test* --risk=3 --user-agent="Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36" --cookie="__cfduid=d3f480988168fecc8da756739062ada611547067310; PHPSESSID=hnmnm587ae28rmcqtdop9hnfl7" --headers="Host:www.hidden.com\nCache-Control:no-cache\nReferer:https://www.hidden.com/\nAccept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\nAccept-Language:en-us,en;q=0.5\nX-Scanner:Netsparker\nAccept-Encoding:gzip, deflate" --dbms=MySQL -D hidden -T User -C email,password --dump --technique=B --threads=10

passwords hashed: SHA512(128 chars length)

I left sqlmap dumping for a week or little longer and after that It consumped 17Gb of RAM
https://i.imgur.com/FoJG2a3.png
The question is what could cause this ?
Previously I left sqlmap for 3 months dumping via Time Based Blind Attack and everything was ok. And now somehow it eating a lot of memory

**Comment by stamparm** [comment]
I am slightly confused with your numbers.

* 0.1% of your RAM seems to be 76MB. That means that there should be 76*100/0.1MB = 76000MB = 74GB RAM
* 2.4% of your RAM seems to be (in the `python.exe` row) 17589MB. That means that there should be 17589*100/2.4MB = 732875.0MB = 715GB RAM

What's the final RAM size you have? Why there seems to be such huge discrepancy between those numbers?

**Comment by eastsida** [comment]
Mmm.. Seems you are reading CPU column )
https://i.imgur.com/LyN2Jar.png
Here you go

**Comment by eastsida** [comment]
Process is still running maybe there is some profiler for python ? Can I somehow attach to python process and see what caused this ?

**Comment by stamparm** [comment]
AFAIK, there is nothing out of the box that could just do the profiling of already running Python application. Though, you could download HxD (https://mh-nexus.de/en/hxd/), attach it to the running process and take a look what is going on inside. It is a RAW hexdump of the process memory space, but maybe something interesting could pop out.

Also, which version of sqlmap do you run? You are the first after couple of years that is coming out with this kind of an "issue". sqlmap should use memory offloading to temporary files (after N dumped items sqlmap should clear the memory of it and just store it to the disk)

**Comment by stamparm** [comment]
p.s. just seen the version (`1.3-55-g915d2bd`) from original Issue request.

Please try to run HxD to see if there is something interesting inside the process memory

**Comment by stamparm** [comment]
Where did you get "1.3-55-g915d2b"??? Although is suggests that it is version "1.3-55", it is not a standard version string

**Comment by eastsida** [comment]
> Where did you get "1.3-55-g915d2b"??? Although it suggests that it is version "1.3-55", it is not a standard version string
From official site that was the name of zip archive. I just don't know if its just random added symbols or some "codename" of version. Yeah it seems this is 1.3.55
Some additional info:
https://i.imgur.com/dtoquj9.png  - String search from process hacker in memory
While tried to attach pycharm, accidentally closed process. Started again it was 50mb now after 30 mins it's already 115mb. Seems i can reproduce this leak. If so is there any profilers that i can start sqlmap with command from my first post and see what's goin on ?
While i was writing now its 130mb and continue to grow, don't know if it will clear memory, but seems not.
I am not a pro at all this memory stuff. But from screen above it contains a lot of payload and vulnerable link strings. So if it's blind means a lot of requests to retrieve characters 1 per request if it stores every request in memory it's  a lot of memory needed.

**Comment by stamparm** [comment]
It shouldn't store ALL payloads inside the memory. It can store hundreds, but not gazillions.

Can you please do the process dump when it reaches couple of hundreds of megabytes? Then zip it and send it to `miroslav@sqlmap.org` ??? Or store it somewhere and send me a message about the location

**Comment by stamparm** [comment]
As you are using "Process Hacker" I can see that it has a feature "Create dump file". Choose that one, compress it and send it to me, please.

**Comment by stamparm** [comment]
I'll need some time to find out what is going on. It seems (like you noticed) that payloads are "pilling up". I have to find the cause. Will let you know if I'll need more dump(s)

**Comment by stamparm** [comment]
I believe I've found a problem. Will patch later today and let you know

**Comment by stamparm** [comment]
p.s. last commit is just a minor memory leak patch. Will patch the "bigger" one later today

**Comment by stamparm** [comment]
@eastsida you could retry now. Retrieve the latest revision and run the dump again

**Comment by eastsida** [comment]
Problem fixed, thank you. Now it's clearing memory after each string retrieval.

**Comment by stamparm** [comment]
Thank you for reporting :+1:
