### ISSUE TITLE
using WAF scripts to detect backend WAF / IPS protection and freezes

### ISSUE THREAD

**Issue by fanatos123** [sqlmapproject/sqlmap#3463]
After the last update SQLMAP  {1.3.1.83#dev}
[11:24:37] [INFO] using WAF scripts to detect backend WAF/IPS protection
[11:24:37] [DEBUG] checking for WAF/IPS product '360 Web Application Firewall (360)'
And so freezes ((((
target WAF >>> AWS WAF

**Comment by huitc** [comment]
wtf!?

**Comment by hos903** [comment]
--skip-waf will help you ..

**Comment by huitc** [comment]
Do you want this?
https://github.com/m4ll0k/Atlas

**Comment by hack0mate** [comment]
Same problem confirmed.

Please, solve it.

**Comment by stamparm** [comment]
Just reproduced. Will try to fix it ASAP (today?)

p.s. same issue - duplicate of #3467

**Comment by stamparm** [comment]
Fixed
