### ISSUE TITLE
The new version gets stuck in WAF

### ISSUE THREAD

**Issue by m1m1cat** [sqlmapproject/sqlmap#3467]
## What's the problem (or question)?
My system Wiondows X86
Pentest box based on U disk
When using pentest box to run SQLmap V1.3.1.83, it is easy to cause blockage when recognizing WAF function.

Please optimize the Carton blockage problem when WAF is encountered.

## What are the running context details?
do you want sqlmap to try to detect backend WAF/IPS?[y/n]
[warning]dropping timeout to 10 seconds (i.e'--timeout=10')
using WAF scripts to detect backend WAF/IPS protection

When the program runs here, it blockages Carton.

**Comment by stamparm** [comment]
What is "Carton blockage" ??

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/issues/3463#issuecomment-459781207

**Comment by stamparm** [comment]
Protection system is DROPing requests. Please don't open this kind of issues without a deep understanding what is going on at the other end

**Comment by stamparm** [comment]
Just reproduced. Will try to fix it ASAP (today?)
