### ISSUE TITLE
If I want to use --tor but Google search doesn't use it?

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3480]
If I want to use TOR but Google search `-g` doesn't use it?
because I can't search for anything when I use `--tor`

**Comment by stamparm** [comment]
`-g` when used with `--tor` falls back to DuckDuckGo or Bing in case that Google rejects such searches (generally it does)

p.s. not sure whether I have to repeat that you've already been repeatedly warned about opening new issues

**Comment by huitc** [comment]
can I disable it, but only for Google search?
that means that tor will still be used in other parts. @stamparm @sqlmapproject

and.. can I use multiple search engines at the same time? ^^''
