### ISSUE TITLE
I would like to give you a suggestion : In the end of scan 

### ISSUE THREAD

**Issue by SoulFunk69** [sqlmapproject/sqlmap#3481]
At the end of the scanner would it be possible to put a summary of each alert?

Exemple : [WARNING] Referer parameter 'Referer' does not seem to be injectable
[05:42:05] [CRITICAL] all tested parameters do not appear to be injectable
[05:42:05] [WARNING] HTTP error codes detected during run:
400 (Bad Request) - 4702 times, 404 (Not Found) - 1 times

[*] ending @ 05:42:05 /2019-02-09/
Found : Boolean sqli founded etcc

Thanks :)

**Comment by stamparm** [comment]
Sorry. I can't find any "new value" in your proposal. Everything what you require is already included in console output
