### ISSUE TITLE
Idea: Macro Framework for Auth Tokens

### ISSUE THREAD

**Issue by austinjdean** [sqlmapproject/sqlmap#3484]
## What's the problem (or question)?
Imagine the scenario:

**Request A** allows you to obtain an auth token based on some pre-known credentials. The token can be easily extracted from **Response A** via regex.

**Request B** requires the auth token from **Response A** as a header. If the token is expired or not present, there are strong indicators that show this in **Response B**.

If sqlmap could realize that the token has expired and automatically fetch a new one to remain authenticated without stopping retrieval, it would be a major QoL improvement.

## Do you have an idea for a solution?
Implement some kind of framework that allows the user to provide sqlmap with:
- The request to obtain a new auth token 
- The regex to extract the token from the response
- An indicator that a new token is required
- A marker for where the token should be placed in requests to the vulnerable endpoint

## How can we reproduce the issue?
n/a - this is just an idea, not an issue.

## What are the running context details?
n/a - this is just an idea, not an issue.

**Comment by stamparm** [comment]
Too many regexes/indicators/tokens/markers.... Not sure which user would jump through so many hoops. 

If workflow for this could be done to satisfy KISS principle, it could have a future (for implementation)
