### ISSUE TITLE
about some waf block sqlmap

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3486]
like this: 
`table 'test.sqlmapoutput' `
`table 'test.sqlmapfile'`
I tried to dump the table but they are always deleted
can let me choose the prefix string? ^^''

**Comment by stamparm** [comment]
With latest update:

`export SQLMAP__TAKEOVER_TABLE_PREFIX="foobar"`

will result in changing of those (auxiliary) table names to `foobaroutput` and `foobarfile`

Also, every setting can now be changed (in runtime) with this approach (`export SQLMAP__...`) from [lib/core/settings.py](https://github.com/sqlmapproject/sqlmap/blob/master/lib/core/settings.py) (e.g. `export SQLMAP__MAX_NUMBER_OF_THREADS=20`)

**Comment by huitc** [comment]
nice~

**Comment by c2xusnpq6** [comment]
Is this still working? @stamparm

**Comment by stamparm** [comment]
> Is this still working? @stamparm

@c2xusnpq6 yup. it should still work
