### ISSUE TITLE
A new error

### ISSUE THREAD

**Issue by coeus-lei** [sqlmapproject/sqlmap#3491]
02:39:30] [CRITICAL] all tested parameters do not appear to be injectable. Try to increase values for '--level'/'--risk' options if you wish to perform more tests. Please retry with the switch '--text-only' (along with --technique=BU) as this case looks like a perfect candidate (low textual content along with inability of comparison engine to detect at least one dynamic parameter). Also, you can try to rerun by providing a valid value for option '--string' as perhaps the string you have chosen does not match exclusively True responses. If you suspect that there is some kind of protection mechanism involved (e.g. WAF) maybe you could try to use option '--tamper' (e.g. '--tamper=space2comment') and/or switch '--random-agent'
[02:39:30] [WARNING] HTTP error codes detected during run:
403 (Forbidden) - 139 times

**Comment by stamparm** [comment]
What's the problem?

**Comment by coeus-lei** [comment]
status code error，， but i dont know what happened?

**Comment by stamparm** [comment]
Those are HTTP codes that server replied with. It is displayed for you for debugging purposes. In your case, something at the other end said that you are forbidden from doing testing
