### ISSUE TITLE
problem ablout --randomize

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3500]
when i type in `-u "https://test.com/test.php?email=test@test.com"` with `--randomize email`, but it can't detect that this is an email address
it will still url-encode the character `@`, and change `.com` to another character
`.com` --> `.zfo` `.obp`
if you can set that to common domain name (like `.tw` `.us`), it would be better!!

**Comment by stamparm** [comment]
`@` has to be url-encoded

**Comment by huitc** [comment]
these too... pls thx!!!!! ^^''

- 2019-06-16+09:30:54
- [{"lat":"22.45286","lon":"113.512"}]
- 113.19764350000001
- 22.2465673
