### ISSUE TITLE
How to connect local database using password in vulnerable link

### ISSUE THREAD

**Issue by chungtra** [sqlmapproject/sqlmap#3501]
Hi,

In one vulnerable URL, I can list the database tables etc, but I don't have privilege to view in the columns. There is one user with root privilege "root@localhost" with the password "root1234". Is there a way to connect with this user so that I can view the database and dump as well. 

I tried with -d parameter providing database name with username:password, but it's not connecting 

Please help.

Regards

**Comment by huitc** [comment]
`--auth-cred=AUTH..`  HTTP authentication credentials (name:password)
for mssql only?

**Comment by huitc** [comment]
`localhost` cannot use `-d` to connect...

**Comment by huitc** [comment]
check the privileges first?
```
--privileges        Enumerate DBMS users privileges
--roles             Enumerate DBMS users roles
```
and try this?
```
--common-tables     Check existence of common tables
--common-columns    Check existence of common columns
```

**Comment by chungtra** [comment]
@huitc yes, MySQL 5.3

**Comment by chungtra** [comment]
After using --users --password, I'm getting list of users:
database management system users [8]:                                                                                                                                                                             
[*] ''@'LD0085P-SPdb1'
[*] ''@'localhost'
[*] 'sdpo'@'10.25.120.96'
[*] 'sdpo'@'10.25.120.97'
[*] 'sdpo'@'localhost'
[*] 'root'@'127.0.0.1'
[*] 'root'@'localhost'
Any way to login from the root user?

**Comment by huitc** [comment]
`--current-user` and then `--roles` `-U USER`

**Comment by chungtra** [comment]
current user is : sdpo'@'10.25.120.97'
with --roles -U 'sdpo'@'10.25.120.97'
the result is: 
role: ALTER
    role: ALTER ROUTINE
    role: CREATE
    role: CREATE ROUTINE
    role: CREATE TEMPORARY TABLES
    role: CREATE USER
    role: CREATE VIEW
    role: DELETE
    role: DROP
    role: EVENT
    role: EXECUTE
    role: FILE
    role: INDEX
    role: INSERT
    role: LOCK TABLES
    role: PROCESS
    role: REFERENCES
    role: RELOAD
    role: REPLICATION CLIENT
    role: REPLICATION SLAVE
    role: SELECT
    role: SHOW DATABASES
    role: SHOW VIEW
    role: SHUTDOWN
    role: SUPER
    role: TRIGGER
    role: UPDATE

**Comment by chungtra** [comment]
Need to login with different user using their password which is root123

**Comment by huitc** [comment]
you cant do that... not mysql

**Comment by stamparm** [comment]
@chungtra it goes like this. You are on right track (`-d`), though, direct connection requires access from outside (i.e. TCP port 3306 to be opened and exposed to the outside world). In case that that is not the case, you should try to access the web server through other means and then afterwards you could try to connect to the MySQL database by using (remote) shell and running system's `mysql` command (e.g. like described [here](https://stackoverflow.com/a/5131945))

Anyway, in regular nowadays installations 3306 is closed for anyone than the `localhost` (i.e. `127.0.0.1`)
