### ISSUE TITLE
--random-agent for --mobile

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3502]
some web pages only accept requests from mobile devices
but `--random-agent` only suitable for PC or other desktop device
and `--mobile` can't do that (randomly and automatically)

and........... you can try to inject the header `X-Forwarded-For` or other similar
because some websites track and record your IP to their SQL server

https://github.com/sqlmapproject/sqlmap/blob/master/tamper/xforwardedfor.py
https://github.com/sqlmapproject/sqlmap/blob/master/tamper/varnish.py
http://airs-sec.com/2017/08/26/sqlmap%E4%B9%8BX-Forwarded-Host%E6%B3%A8%E5%85%A5/

**Comment by hos903** [comment]
Hi , you can use --user-agent=Mozilla/5.0 (Linux; U; Android 4.4.2; en-us; SCH-I535 Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30

no need to use --random-agent

**Comment by huitc** [comment]
what should I enter to use it?
i tried `--random-agent --mobile` and `--mobile`, but...

**Comment by huitc** [comment]
@stamparm
