### ISSUE TITLE
Feature request - Add an option to modify the response before SQL Map analyzes it, similar to tamper for requests

### ISSUE THREAD

**Issue by dee-see** [sqlmapproject/sqlmap#3505]
## What's the problem (or question)?
I'm running SQLMap against an API which returns encrypted responses.

## Do you have an idea for a solution?
The requests are encrypted as well and with the help of the `--tamper` switch I can get around that just fine (I know the encryption and decryption logic). If I had a switch to process the response's data before SQLMap analyzes it it would be wonderful.

At the moment, a timing-based attack can work in those scenarios, but it would be so much faster if I could use the HTTP response and benefit from other injection techniques.

Thank you very much for a great tool, if you acknowledge this as a nice-to-have feature, I'd be willing to try to implement it myself.

**Comment by stamparm** [comment]
You mean something like `--preprocess <script.py>`, where `script.py` would be some user tamper-alike script accepting similar arguments as tamper scripts? You would use it right after sqlmap gets the (raw) response (e.g. [here](https://github.com/sqlmapproject/sqlmap/blob/master/lib/request/connect.py#L1313))

**Comment by dee-see** [comment]
Yes that's exactly what I mean !

**Comment by dee-see** [comment]
If that's a feature you'd like to see in the project @stamparm I'll start working on it.

**Comment by huitc** [comment]
@dee-see I want too! nice~😆

**Comment by stamparm** [comment]
I'll do it

**Comment by stamparm** [comment]
Quick start:

```
$ mkdir /tmp/foobar

$ touch /tmp/foobar/__init__.py

$ cat > /tmp/foobar/preprocess.py << "EOF"
#!/usr/bin/env

def preprocess(page, headers=None, code=None):
    return "AAAAAAAAAAAAA" + (page or ""), headers, code
EOF

$ python sqlmap.py -u localhost/?id=1 --preprocess /tmp/foobar/preprocess.py -v 6 --batch | grep -C 2 AAAA
Content-type: text/html; charset=UTF-8

AAAAAAAAAAAAA<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
--
Content-type: text/html; charset=UTF-8

AAAAAAAAAAAAA<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
--
Content-type: text/html; charset=UTF-8

AAAAAAAAAAAAA<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
--
Content-type: text/html; charset=UTF-8

AAAAAAAAAAAAA<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
--
Content-type: text/html; charset=UTF-8

AAAAAAAAAAAAA<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
--
```

**Comment by stamparm** [comment]
p.s. https://github.com/sqlmapproject/sqlmap/wiki/Usage#preprocess-response-data

**Comment by dee-see** [comment]
That was quick! Thank you very much
