### ISSUE TITLE
Showing   invalid target url   isssue i have run this command: python sqlmap.py "http://195.144.214.10/test  --batch --tables     Please advise

### ISSUE THREAD

**Issue by abhayp-cedcoss** [sqlmapproject/sqlmap#3508]
![targeturl](https://user-images.githubusercontent.com/25762790/53678806-37efff80-3cea-11e9-8083-6a0139d6163d.png)

**Comment by huitc** [comment]
hey~!

**Comment by huitc** [comment]
python sqlmap.py `-u` "http://195.144.214.10/test --batch --tables

**Comment by huitc** [comment]
### **Target URL**
Option: `-u` or `--url`
Run sqlmap against a single target URL. This option requires a target URL in following form:
`http(s)://targeturl[:port]/[...]`

For example:
```
$ python sqlmap.py -u "http://www.target.com/vuln.php?id=1" -f --banner --dbs -\
-users
```

**Comment by huitc** [comment]
chinese?

**Comment by abhayp-cedcoss** [comment]
I don't understand what exactly you are saying please  elaborate

**Comment by huitc** [comment]
https://github.com/sqlmapproject/sqlmap/issues/3508#issuecomment-468902676

**Comment by huitc** [comment]
ok?........😅😅😑
(just.... google it: sqlmap tutorial

**Comment by abhinavsagar** [comment]
https://github.com/sqlmapproject/sqlmap/issues/3508#issuecomment-468992838

**Comment by abhinavsagar** [comment]
https://github.com/sqlmapproject/sqlmap/issues/3508#issuecomment-468902805

**Comment by abhayp-cedcoss** [comment]
python sqlmap.py -u "http://195.144.214.10/test --batch --tables

can you help me
 on this

**Comment by stamparm** [comment]
You have only one quote before the URL itself. Not sure if you are trolling.

Use `python sqlmap.py -u "http://195.144.214.10/test" --batch --tables` instead

**Comment by abhayp-cedcoss** [comment]
Sorry for that but  after running this command: python sqlmap.py -u "http://195.144.214.10/test" --batch --tables

now i am getting this error
[CRITICAL] all tested parameters do not appear to be injectable. Try to increase values for '--level'/'--risk' options if you wish to perform more tests. If you suspect that there is some kind of protection mechanism involved (e.g. WAF) maybe you could try to use option '--tamper' (e.g. '--tamper=space2comment') and/or switch '--random-agent'

**Comment by stamparm** [comment]
You have problems with basics of SQL injection and usage of sqlmap. Please Google for "SQL injection" and read everything you find. Also, this new "error" doesn't have anything to do with your original "Issue"

**Comment by ELHARAKA** [comment]
You forgot to add (") at the end of the url, your cmd must be like that:
python sqlmap.py "http://195.144.214.10/test" --batch --tables

**Comment by huitc** [comment]
> You forgot to add (") at the end of the url, your cmd must be like that:
> python sqlmap.py "http://195.144.214.10/test" --batch --tables

^^''
