### ISSUE TITLE
about `302 redirect`

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3511]
Allows user to choose to provide a new header or entire HTTP request, when cookie or session expires and displays `302 redirect` to continue the testing

like this: `sqlmap got a 302 redirect to 'https://test.com:443/account/login'. Do you want to follow? [Y/n]` --> `do you want to provide a new cookie value or edit the header to ......?`

**Comment by JavanXD** [comment]
Proxy your sqlmap traffic through **OWASP ZAP**, write an _authentication script_ and enable _Force Login_. ZAP logs you automatically in when it detects a logged out context (e.g. Status Code 302), and your _replacement_ script offers a new session to all sqlmap requests.

**Comment by huitc** [comment]
... @JavanXD
