### ISSUE TITLE
Using python package py2exe to make sqlmap.exe problem

### ISSUE THREAD

**Issue by Push55** [sqlmapproject/sqlmap#3514]
![Uploading I7V@OVFAZOF$099AMP7{DJQ.png…]()
Don't know what the problem is

**Comment by Push55** [comment]
![i7v ovfazof 099amp7 djq](https://user-images.githubusercontent.com/48205489/53742865-97a9fe80-3ed4-11e9-9e1a-fca1d4302841.png)

**Comment by stamparm** [comment]
https://stackoverflow.com/questions/45066518/nameerror-name-exit-is-not-defined

**Comment by Push55** [comment]
> https://stackoverflow.com/questions/45066518/nameerror-name-exit-is-not-defined

Okay thank you

**Comment by stamparm** [comment]
Pushed a "patch" this moment, though, you'll see it only here in HEAD for a moment. Not sure how did you come to the `py2exe` version in the first place.

**Comment by Push55** [comment]
> 不过，这一刻推了一个“补丁”，你只会在HEAD中看到它片刻。不知道你是怎么来到这个`py2exe`版本的。
I reference sqlmap.exe through a third-party c++ program.

**Comment by huitc** [comment]
@push55 Chinese?.....

**Comment by Push55** [comment]
> @Push55 Chinese?.....

yes 中国人
