### ISSUE TITLE
Not replacing CSRF token in post param

### ISSUE THREAD

**Issue by JavanXD** [sqlmapproject/sqlmap#3519]
## Version
1.3.3.8#dev

## Not replacing CSRF token in post param

`--csrf-token="MyForm:csrftoken"`is not an regular expression but we have to answer `'--csrf-token' is a regular expression? [y/N]` with 'y' to make the tests run. We have to answer with yes else if we answer with 'N' it stops and says 'anti-csrf token not found'. 

Sometimes the CSRF-Token was replaced correctly in the request and sometimes not - very strange behaviour. We reviewed/debugged the HTTP History also by using Burp as Proxy and including a delay as option. The most strange thing is that the csrf-token which is provided seems to be received correctly from the `--csrf-url` option but is not inserted in the requests #3-#45 (note that `csrftoken` is always equal to `8e8adea846994f37643f702413abc973`, which is defined in request_3.txt). Strangely `csrftoken` is replaced in the first http post request (which does not include a payload, see `[13:44:51] [TRAFFIC OUT] HTTP request [#2]`). But after that it stops immediately to replace the tokens for each request. After post request #45 the `csrftoken` replacing begins to work again.

Why is the csrftoken not replaced in the tests between #3 and #45? 

```
sqlmap -r /root/Documents/BlubWeb/request_3.txt --level 1 --risk 1 -v 5 -p "MyForm:name1" --dbms=oracle --csrf-token="MyForm:csrftoken" --csrf-url="https://blablubhost/BlubWeb/pages/blubbiblub/dosth.faces;jsessionid=Thisisasessionid" --force-ssl --skip-waf --not-string="Keine Suchergebnisse" --technique="BUSTQ" --proxy=http://127.0.0.1:8080
```
[request_3_anonymized.txt](https://github.com/sqlmapproject/sqlmap/files/2935457/request_3_anonymized.txt)
[sqlmap-log_anonymized.txt](https://github.com/sqlmapproject/sqlmap/files/2935460/sqlmap-log_anonymized.txt) (Log is from last issue but fix 8189a10 doesn't differ)

## Hotfix
```
--skip-urlencode
``` 
makes the CSRF Replacement work for all tests.

We think the tests between #3 and #45 include a character which breaks csrf replacement.

Tested together with @JoalpaLe

**Comment by stamparm** [comment]
* Last patch is for the first part `anti-csrf token not found`
* Still have to find out what is going on the second part

**Comment by stamparm** [comment]
Thank you for your report. Please retry it now.

**Comment by JavanXD** [comment]
Many thanks for the quick fix.
Runs like a charm.

In the meantime we had created workarounds with different tools
* Burp (CSRF Macro with [CPH 3.0](https://github.com/elespike/burp-cph)), 
* OWASP ZAP (urlencode POST Body with a custom proxy script) 
* and the sqlmap option `--eval`.

So many options are great, with ZAProxy being the fastest way to get there.
