### ISSUE TITLE
problem about -o

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3524]
some web pages do not support null connection, but sqlmap still uses null connection to connect to the server (when the user turn on `-o`

and sqlmap will turn `--threads` into multiple threads. is this normal? (when the user turn on `--null-connection`

**Comment by stamparm** [comment]
A) `some web pages do not support null connection, but sqlmap still uses null connection to connect to the server` <- you mean in future runs or following requests. In following requests (for same run) there should be no usage of null connection if test fails

B) `and sqlmap will turn --threads into multiple threads. is this normal? (when the user turn on --null-connection` <- I didn't understand this part

**Comment by huitc** [comment]
a) there should be no usage of null connection if test fails YES
b) when i switch on option `--null-connection`, `--threads` will become a number more than one (even if I typed `--threads 1`

**Comment by huitc** [comment]
sometimes sqlmap will detect that the target supports `--null-connection`, but it is not actually supported.
and some web servers will respond: `Method not allowed`
