### ISSUE TITLE
SQLMAP error 

### ISSUE THREAD

**Issue by laggerghost** [sqlmapproject/sqlmap#3531]
C:\Python26\sqlmap
λ sqlmap.py -u https://[REDACTED]?id=1%27 --dbs
        ___
       __H__
 ___ ___[.]_____ ___ ___  {1.3.3.17#dev}
|_ -| . ["]     | .'| . |
|___|_  [)]_|_|_|__,|  _|
      |_|V...       |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting @ 05:05:20 /2019-03-12/

[05:05:23] [WARNING] it appears that you have provided tainted parameter values ('id=1'') with most likely leftover chars/statements from manual SQL injection test(s). Please, always use only valid parameter values so sqlmap could be able to run properly
are you really sure that you want to continue (sqlmap could have problems)? [y/N] y

I DONT KNOW WHY,.. WHAT HAPPEN... after i type "y" i wait one hours. the sqlmap not execute.. What happen?

**Comment by huitc** [comment]
`-u "https://notifkos.pom.go.id/bpom-notifikasi/product_notif.php?id=1"`
and don't show the domain name you want to test the website next time.

**Comment by stamparm** [comment]
1) No real site URLs here
2) You've been kindly warned to not include junk as `%27` inside provided data
3) Your Issue request doesn't tell anything about the issue
4) You've just skipped the Issue template
