### ISSUE TITLE
a suggestion

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3533]
### If you encounter the following conditions,
- HTTP error detected ( User-defined )
or
- DBMS error detected
or
- User-defined characters detected ( like: `wrong`, `some problem` ...
or others

**can be defined by the user will be better ( `--parse-errors` too~! )**
### then
- switch to `-v 3` or other numbers
or
- switch on --parse-errors
or others

**Comment by stamparm** [comment]
Nope. This would spam the console output. I expect DBMS errors (for easier debugging), not some random stuff from web application. Please use `-t traffic.txt` for such purposes
