### ISSUE TITLE
about header "Save-Data"

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3539]
if `Save-Data` is supported by the target web server, speed up will come from the obvious saving of used bandwidth
`Save-Data: on`

https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/save-data/
https://chrome.google.com/webstore/detail/save-data-on/nholpkfnmjbinlhcfihkhiehdaohlibg

**Comment by stamparm** [comment]
As sqlmap doesn't render the page, thus not downloading media, there is no need to use this kind of approach. Based on those references, authors claim that that same header notifies the web server logic to "`reduce the number of required resources and dependencies, apply more aggressive resource compression`". There is no need to do that while retrieving only the page itself
