### ISSUE TITLE
unable to detect error message

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3540]
type `?id=1'`
`MsSQL query error: SELECT count(*) as total FROM [posts] WHERE REPLACE(REPLACE(REPLACE(CONVERT(VARCHAR(19), CONVERT(TIME, test_date, 112), 126), '-', ''), 'T', ''), ':', '') <= 20190318210052 and id =? and status<>'Hidden'`

**Comment by stamparm** [comment]
I would need an actual HTML of this error-message

**Comment by huitc** [comment]
ok wait

**Comment by huitc** [comment]
sent

**Comment by stamparm** [comment]
Generic message (web application custom message) - done a generic "patch" for it (everything until `<` and `>` will be displayed)
