### ISSUE TITLE
Postgres pg_read_server_files priv code execution.

### ISSUE THREAD

**Issue by 0x27** [sqlmapproject/sqlmap#3545]
So apparently the latest Postgres has a code execution feature if the DB user you are has the "pg_read_server_files" privilege. Could be an interesting addition?

Ref: https://medium.com/greenwolf-security/authenticated-arbitrary-command-execution-on-postgresql-9-3-latest-cd18945914d5

**Comment by stamparm** [comment]
Reference (for myself): https://github.com/Greenwolf/postgres_cmd_execution_nine_three/blob/master/postgres_cmd_execution_nine_three.rb

**Comment by stamparm** [comment]
![screenshot](https://user-images.githubusercontent.com/921555/54823947-b87e9c00-4ca9-11e9-84b7-375ec7b06ec8.png)
