### ISSUE TITLE
SQLMAP Automatic Update

### ISSUE THREAD

**Issue by AmericanY** [sqlmapproject/sqlmap#3553]
Hi @stamparm ,

I think that's will be a great in case if you added the following option which will be easier for newbies.

```
[root@A ~]# sqlmap.py -hh | grep update
    --update-on/off Turning on sqlmap automatic updates ON or OFF
```
  
Which means that each time `sqlmap` will be running so it's will check if it's updated to the latest version or not.

**Comment by huitc** [comment]
Check every time you use it?......
It's better to set it to daily or hourly?

**Comment by AmericanY** [comment]
@huitc , basically I'm talking here about newbies usage. 

Indeed it's can be set via many ways through cron job or bash profile. 

So it's will be more effective in case if the user turned on automatic update so sqlmap will be check the version upon running.

Regards,

**Comment by huitc** [comment]
🤔🤔😑

**Comment by blshkv** [comment]
This will be very unadvisable in case of any Linux distro. They install it as a system package, register all files for proper installation and discover unregistered files. 
Normally, any self modification is threaded as a malicious behaviour and should not be allowed. 

Newbies should not install any tools manually. Just learn how to use a package manager and do it right.

**Comment by stamparm** [comment]
Four things:

1) I thought of producing those version checking requests for many times, but the great thing about sqlmap is that it shouldn't produce requests to non-target sites. That way exposure to "third-parties" is avoided
2) If you haven't update sqlmap for more than a week, then you should most probably update, especially if you are using `git` version. If you are using `pip` version you should do the update per monthly basic. If you are using `yum`/`apt` version, then I am not sure what should be the correct periodicity of updates (different repos - different package releases).
3) Relying on the git/HEAD revision is not something to be done on automatic base. Main reason are the repository releases. I can't force somebody to update to the latest revision from the `git`, while the repository one is being done (e.g.) bi-monthly

...

4) Nevertheless, I could do an "educated guess" nagging message which says to update if sqlmap seems to itself like it is out-dated. Educated guess would be really simple - if older than 1month, give a small WARNING.

**Comment by stamparm** [comment]
With the latest commit you'll be presented (if sqlmap not updated for last 60 days) with the following nagging message:

![nagging](https://user-images.githubusercontent.com/921555/56135645-7b988300-5f91-11e9-9cd1-ab8c5baa0834.png)
