### ISSUE TITLE
Not working in the latest version

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3554]
I tried python2 and python3 but they didn't succeed

**Comment by stamparm** [comment]
?

What's the issue?

Python3 is still not supported. I am slowly adding "adjustments", but it won't be supported for long

**Comment by stamparm** [comment]
Also, if you have a problem with `compat`, please pull the latest revision and retry

**Comment by huitc** [comment]
https://github.com/sqlmapproject/sqlmap/issues/3555
