### ISSUE TITLE
please release a proper tar ball

### ISSUE THREAD

**Issue by blshkv** [sqlmapproject/sqlmap#3571]
I have subscribed to "release watching", however it was no notification after the last release.
I guess, that's because you tagged it, but the release process is not completed.
Could you review this process please?

**Comment by stamparm** [comment]
Can you please point to a problematic release? Tags are being done on monthly basis. Those are not releases.

Releases are being done on yearly basis. Last release was 1.3 on Jan 5 2019.

**Comment by blshkv** [comment]
It is confusing what is tag and what is a release.
If you have a look at the repology:
https://repology.org/project/sqlmap/versions
all distros do not differentiate tag and release.

Could you just release it every time? So in that example, 1.3 would be a major release (yearly) and 1.3.x postfixes/minor improvements?

**Comment by stamparm** [comment]
Sorry, sqlmap will not do releases like (e.g.) Mozilla does. There won't be release 510, 511, 512, etc.

Release philosophy in sqlmap is to make it (like ceremonial) once a year (actually, when the year starts). Everything else is just a monthly status/tag.

Tag != release. Not sure why we have to discuss this
