### ISSUE TITLE
problem about --chunk

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3577]
```
POST /qweqwe.php?qwe=qwe

(nothing~) <--1
```
but sqlmap will try to inject there `1`

**Comment by stamparm** [comment]
I don't follow. What's the issue? Please give me a content of request file, together with the expected and real traffic content.

**Comment by huitc** [comment]
https://github.com/sqlmapproject/sqlmap/issues/3583

**Comment by huitc** [comment]
It should be because the "--chunk" was not used before, but it was used later, so this problem occurred.
Google translate
