### ISSUE TITLE
about password hash cracking

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3578]
Can I call Hashcat or other software to crack the password hash?

**Comment by stamparm** [comment]
You'll get that message with temporary file containing all password hashes inside. You can call hashcat with it, but you'll need to find: 1) which hashcat `-m` to use AND 2) make sure that the content inside those password hashes is compatible with hashcat in the first place

In majority of cases, you'll just need to find the `-m` (but that's a standard procedure when running hashcat)

**Comment by huitc** [comment]
Do you have any ideas? About calling Hashcat directly.
