### ISSUE TITLE
I am stuck in "testing connection to the target URL"

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3583]
I am stuck in `testing connection to the target URL`, just because I typed `--chunk`

Did not type `--chunk`:
```
POST /api/test/test?member_id=&new_device_id=test&token_gcm=test&token_type=test&lang=tc&token=test HTTP/1.1
Referer: http://test.test.com:80/api/test/test
Host: test.test.com
Content-type: application/x-www-form-urlencoded; charset=utf-8
Accept-encoding: gzip
User-agent: okhttp/3.12.1
Content-length: 0
Connection: close
```

did:
```
POST ...
Host: test.test.com
Referer: http://test.test.com:80/api/test/test
Accept-encoding: gzip
Transfer-encoding: chunked
Content-type: application/x-www-form-urlencoded; charset=utf-8
User-agent: okhttp/3.12.1
Connection: close
```
because of this? `Transfer-encoding: chunked`? maybe

**Comment by stamparm** [comment]
You are using `--chunk` / `Transfer-encoding: chunked` while having empty POST body. That's the issue, as the server is waiting for any kind of data from sqlmap, while there is none.

I'll patch, but this is more a "support" problem than anything else
