### ISSUE TITLE
Does Sqlmap not support H2 protocol?

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3586]
`-r test.txt`
`POST /test.php h2`
and then...
```
[DEBUG] creating HTTP requests opener object

[*] ending @ 02:40:06 /2019-04-16/
```

**Comment by stamparm** [comment]
Nope. In some future it might be. It is still something being developed.

Also, all HTTP/2 sites should be able to be back compatible. Hence, just use `HTTP/1.0` instead of `h2`

**Comment by huitc** [comment]
ok

**Comment by huitc** [comment]
If I change it to this, is that okay?
`h2` --> `HTTP/2`

**Comment by huitc** [comment]
?
