### ISSUE TITLE
How can I test all the HTTP request files in a folder?

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3587]
When I have a lot of test targets, I can't solve them with `-r` and `-u`
thx!!

**Comment by stamparm** [comment]
With the latest revision you can:

A) Enlist all wanted request files one by one, separated with comma (e.g. `-r req1.txt,req2.txt,req3.txt`)

 OR

B) Just use wildcarding (e.g. `-r req*.txt`)
