### ISSUE TITLE
about --search 

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3589]
If I want to dump the entire table in the case of `--search -C`, what should I do to make it more easier to...?
 Do you have an idea?

**Comment by huitc** [comment]
Also, use `--tables` or `--columns` after `-search -D` or `-search -T`

**Comment by stamparm** [comment]
A) `--search` usage is described pretty well [here](https://github.com/sqlmapproject/sqlmap/wiki/Usage#search-for-columns-tables-or-databases) <- wiki
B) I don't get it what's this all "issue" about. You are doing a search for a given type (e.g. `-C` for column). What does the `--tables` or `--columns` have to do with the search workflow? I thought that it is pretty clear what does the search does
