### ISSUE TITLE
about options not listed on usage page

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3601]
I hope you can list the options not listed on the usage page!
thx!!

(for https://github.com/needle-wang/sqlmap-ui/issues/1#issuecomment-484984482 ha!

**Comment by stamparm** [comment]
I don't get it. What's the issue? Which usage page? Which options?

**Comment by huitc** [comment]
You mean the option `--hpp` or [`Usage` page](https://github.com/sqlmapproject/sqlmap/wiki/Usage) already lists all the options?

**Comment by stamparm** [comment]
`-hh` for sure lists all options (except experimental and/or hidden not meant to be used by regular users)
