### ISSUE TITLE
about --threads

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3605]
when i switch `--threads` to `10` and `--technique T` and `--drop-set-cookie`, sqlmap still turn it off (switch to `--threads 1?`)
but it is ok when i have switch on --drop-set-cookie, right?...
```
---
Parameter: hid (POST)
    Type: time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind (query SLEEP)
    Payload: hid=5143 AND (SELECT * FROM (SELECT(SLEEP(10)))OUJu)&sID=2446&handin_status=1
    Vector: AND (SELECT * FROM (SELECT(SLEEP([SLEEPTIME]-(IF([INFERENCE],0,[SLEEPTIME])))))[RANDSTR])
---
```
`multi-threading is considered unsafe in time-based data retrieval. Going to switch it off automatically`

**Comment by stamparm** [comment]
`--threads` is always ignored in time-based SQLi (no matter if `--drop-set-cookie` used or no). Main reason is the stability of data retrieval.
