### ISSUE TITLE
about "connection dropped or unknown HTTP status code received"

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3608]
the website I am testing will return `net::ERR_CONNECTION_RESET` (chrome) if i typed in some char it is not accepted

**Comment by huitc** [comment]
if the payload can't bypass waf (already using tamper, but can't bypass it), it will return nothing, and... sqlmap will be forced to terminate

(but some payload can bypass it)

**Comment by huitc** [comment]
and tamper between.py have some problems too? maybe?

`--tamper randomcase,varnish,xforwardedfor,between`
24) ANd 1911=4877 ANd (2402 BEtwEEN 2402 ANd 2402
`1911=4877` should be `1911 BeTwEEN 4877 AnD 4877` right? ^^''

**Comment by huitc** [comment]
So its priority should be adjusted?

**Comment by stamparm** [comment]
I really don't understand what is going on here. Please be more coherent

**Comment by huitc** [comment]
even if sqlmap received `(Nothing)` for few times, it don't need to forced termination

because some website if... :
id=1 --> code 200
id=1 or 1=1 --> code 504 Fiddler - Receive Failure
some payload can't pass, some can
and sqlmap will forced termination itself
`[Fiddler] ReadResponse() failed: The server did not return a complete response for this request. Server returned 0 bytes.`

**Comment by huitc** [comment]
how can I ignore it?

**Comment by stamparm** [comment]
Cool thing is that even if I implement something here, you'll raise another issue claiming that sqlmap never stops on some other run (because it is not able to properly distinguish what is ERROR and what is a non-ERROR response). Closing this down

**Comment by huitc** [comment]
you (sqlmap) can ask me (user) about the server responded back nothing 0b
and should i (sqlmap) keep on or not? something like that.... ^^''
