### ISSUE TITLE
How to custom a playload of sqlmap for a blind injection vulnerability?

### ISSUE THREAD

**Issue by luckywalio** [sqlmapproject/sqlmap#3611]
Hi,guys.  

I found a blind injection vulnerability. The database is SQL Server. Here is the log. 

Discovered by Scripting (Blind_Sql_Injection.script)
URL encoded GET input category was set to product%' AND 3* 2* 1=6 AND '000dCqH'!='000dCqH%

Tests performed:
product%' AND 2* 3* 8=6* 8 AND '000dCqH'!='000dCqH% => TRUE
product%' AND 2* 3* 8=6* 9 AND '000dCqH'!='000dCqH% => FALSE
product%' AND 3* 3<(2* 4) AND '000dCqH'!='000dCqH% => FALSE
product%' AND 3* 2>(1* 5) AND '000dCqH'!='000dCqH% => TRUE
product%' AND 3* 2* 0>=0 AND '000dCqH'!='000dCqH% => TRUE
product%' AND 3* 3* 9<(2* 4) AND '000dCqH'!='000dCqH% => FALSE，

But sqlmap cannot verify the exist of the blind injection vulnerability. I checked sqlmap/xml/payloads/boolean_blind.  There is no such playload type in the file boolean_blind. 

There are some similiar playload types like product') AND 7936=7936 AND ('hcfv'='hcfv in sqlmap debug information.  

How to write my custom playload code and add it to boolean_blind to make sqlmap identify the  blind injection vulnerability above. 

This is part of the boolean_blind.
<test>
<title>OR boolean-based blind - WHERE or HAVING clause</title>
<stype>1</stype>
<level>1</level>
<risk>3</risk>
<clause>1,9</clause>
<where>2</where>
<vector>OR [INFERENCE]</vector>
<request>
<payload>OR [RANDNUM]=[RANDNUM]</payload>
</request>
<response>
<comparison>OR [RANDNUM]=[RANDNUM1]</comparison>
</response>
</test>

Thanks a lot.

**Comment by stamparm** [comment]
It doesn't make any sense that this overly redundant payloads are working, while the rest of payloads inside sqlmap are not working. There is no way to just write those payloads inside `xml/payloads` as most probably something else is blocking the rest of payloads. Please spend some time in researching what is going on with those simpler payloads (i.e. why they don't work)
