### ISSUE TITLE
Can't find information on specific user

### ISSUE THREAD

**Issue by anon9346** [sqlmapproject/sqlmap#3615]
So, I have access to a database, but the problem I have is that I need the email and password from a specific user, but for some reason this is what I see when I try to get them: [img]https://i.imgur.com/DjxcTWt.png[/img] It says that the password is twitter (but that can't be because other users passwords are md5 hashed) and it doesnt show me the email either. What is the reason and can I somehow get access to those?

**Comment by fgeek** [comment]
Dump the whole table or database. Should be easier to debug. What command line did you use to get that information? Please note that not all databases are filled with correct information and there might be invalid data. You can also log all traffic and read or reproduce the http queries to see what was actually transmitted.

**Comment by anon9346** [comment]
I used: sqlmap.py -u (vuln website) --no-cast -D database -T table -C user_id,password,email --where "user_id=random number" --dump --tamper=concat2concatws

How can I read and log the traffic?

**Comment by fgeek** [comment]
```
-t TRAFFICFILE      Log all HTTP traffic into a textual file
```

**Comment by anon9346** [comment]
Still the same issue, but thanks for your help.

**Comment by stamparm** [comment]
`but that can't be because other users passwords are md5 hashed` <- so, basically, you claim that sqlmap has an Issue where somebody (most probably web dev) has written clear text data to somewhere where you expected MD5. Please, try to assess the target manually to find out what is going on as I don't see any useful data provided here
