### ISSUE TITLE
Weird table name !

### ISSUE THREAD

**Issue by bscript** [sqlmapproject/sqlmap#3616]
Hello , 

I would like to know if you have an idea why I have this weird table name : 

[*] "ITT}B{<SU><}F"
[*] "Q<^TMFPQVK\RS"
[*] "U48L"
[*] "V>Kڄ"
[*] "W M"
[*] "ߒ"

Thank you

**Comment by stamparm** [comment]
You have a (most probably) false-positive. Please update to the latest revision and rerun everything with `--flush-session`
