### ISSUE TITLE
-m BULKFILE does not set cookies

### ISSUE THREAD

**Issue by MM-DRH** [sqlmapproject/sqlmap#3636]
Hello,
I am currently testing sqlmap with bwapp.

I noticed that if I use the command -u everything works.
However, if I use -m (in the text file is only a link, which is the same as I use in -u) the cookie is not set.

Here are the following commands I used:
1) with -u
`D:\Python27\python sqlmap.py -u http://192.168.56.3/bwapp/sqli_1.php --cookie="PHPSESSID=h2hu8kgut7jl4q30k6918aure6; security_level=0" --batch --forms --level=1 --risk=1 --output-dir=D:\output -v 6`

2) with -m
`D:\Python27\python sqlmap.py -m "test.txt" --cookie="PHPSESSID=q2sfvsop9g4p1cjngqikiqjj85; security_level=0" --batch --forms --level=1 --risk=1 --output-dir=D:\output -v 6`

Short log excerpt:
1) with -u: (it set the cookie)

```
 [16:01:54] [TRAFFIC OUT] HTTP request [#1]:

GET /bwapp/sqli_1.php HTTP/1.1

Host: 192.168.56.3

Cookie: PHPSESSID=h2hu8kgut7jl4q30k6918aure6; security_level=0

Accept-encoding: gzip,deflate

Cache-control: no-cache

Accept: */*

User-agent: sqlmap/1.3.4.43#dev (http://sqlmap.org)

Connection: close


[16:01:54] [DEBUG] declared web page charset 'utf-8'
[16:01:54] [WARNING] potential CAPTCHA protection mechanism detected
```

2) with -m (don't set cookie)

```
[16:05:28] [TRAFFIC OUT] HTTP request [#1]:

GET http://192.168.56.3/bwapp/sqli_1.php HTTP/1.1

Host: 192.168.56.3

Accept-encoding: gzip,deflate

Accept: */*

Connection: close
```

Is this a bug or is my command wrong?

I'm sorry for my bad English, hope you will understand me.

I would be glad to receive an answer

Yours sincerely

[Log with -m.txt](https://github.com/sqlmapproject/sqlmap/files/3157792/Log.with.-m.txt)
[Log with -u.txt](https://github.com/sqlmapproject/sqlmap/files/3157793/Log.with.-u.txt)

**Comment by stamparm** [comment]
Only the first request (testing one) doesn't have the cookie set. Will "patch"
