### ISSUE TITLE
bug? about %inject here%

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3653]
`-u "https://www.test.us/tc#search/search/%7B%22brand%22:%22TEST%inject here%%22%7D"`

**Comment by stamparm** [comment]
sqlmap strips everything after `#` as that's the proper way how to handle such URLs. Hence, sqlmap is not able to do this kind of injection WHICH clearly provokes some other (e.g. Javascript) mechanisms when being run inside the web browser

**Comment by huitc** [comment]
okay!!😅😅😃
