### ISSUE TITLE
how to force to check 'token' param

### ISSUE THREAD

**Issue by zsdevX** [sqlmapproject/sqlmap#3656]
I got the infomation, but I really want to check the userToken

`ignoring (custom) POST parameter 'JSON userToken'`

**Comment by huitc** [comment]
try `-p userToken`?

**Comment by zsdevX** [comment]
> try `-p userToken`?

it did not work.

**Comment by stamparm** [comment]
@zsdevX please update to the latest revision and retry. This should be fixed now
