### ISSUE TITLE
bug after update sqlmap (kali)

### ISSUE THREAD

**Issue by Hisoka503** [sqlmapproject/sqlmap#3676]
i write 
git clone --depth 1 https://github.com/sqlmapproject/sqlmap.git sqlmap

then ,, 
bash: /usr/bin/sqlmap: No such file or directory

how i fix it ,,?

**Comment by huitc** [comment]
what!? really???😅😑😑

**Comment by stamparm** [comment]
@Hisoka503 I believe that you've messed something up in "preparation" period. This seems to me that you've removed installed sqlmap (e.g. `apt remove sqlmap`) and then you've just did `git clone`.

If you just want to run the latest sqlmap please do the following:

```
cd /tmp
git clone --depth 1 https://github.com/sqlmapproject/sqlmap.git sqlmap
cd sqlmap
python sqlmap.py
```

p.s. upper procedure will JUST get you up and running sqlmap, while not fixing your system issues

**Comment by hackerAasad** [comment]
I faced exactly the same problem and it was solved by doing as following:

### apt remove sqlmap
### apt-get update
### apt-get install sqlmap

**Comment by hackerAasad** [comment]
I faced exactly the same problem and it was solved by doing as following:

### apt remove sqlmap
### apt-get update
### apt-get install sqlmap

**Comment by hackerAasad** [comment]
I faced exactly the same problem and it was solved by doing as following:

### apt remove sqlmap
### apt-get update
### apt-get install sqlmap

**Comment by hackerAasad** [comment]
I faced exactly the same problem and it was solved by doing as following:

### apt remove sqlmap
### apt-get update
### apt-get install sqlmap

**Comment by hackerAasad** [comment]
I faced exactly the same problem and it was solved by doing as following:

### apt remove sqlmap
### apt-get update
### apt-get install sqlmap

**Comment by hackerAasad** [comment]
I faced exactly the same problem and it was solved by doing as following:

### apt remove sqlmap
### apt-get update
### apt-get install sqlmap

**Comment by hackerAasad** [comment]
I faced exactly the same problem and it was solved by doing as following:

### apt remove sqlmap
### apt-get update
### apt-get install sqlmap

**Comment by hackerAasad** [comment]
I faced exactly the same problem and it was solved by doing as following:

### apt remove sqlmap
### apt-get update
### apt-get install sqlmap

**Comment by HaroonAli48** [comment]
`//I am from FBI we have notice some hackers in github id"111qajsuh72h"`. Reporting agent a22
