### ISSUE TITLE
JSON post data & time out

### ISSUE THREAD

**Issue by strano666** [sqlmapproject/sqlmap#3686]
**Describe the bug**
I've run sqlmap against an URL before via `-u`, and after with `-r` because of some JSON data.
In the first case, it's all ok about connection, but in the second case i've a `connection timed out` error. There is no WAF.

**To Reproduce**
1. Run `sqlmap -u <https://host/path/?par=value> --batch --random-agent --level=3 risk=3`
2. All ok
3. Run `sqlmap -r <REQUEST FILE> --batch --random-agent --level=3 risk=3`
where < REQUEST FILE > is
```
POST /path/?par=value HTTP/1.1
Host: host
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0
Accept: */*
Accept-Language: it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: https://host/path
Content-Type: application/json; charset=UTF-8
Content-Length: 156
DNT: 1
Connection: close
Cookie: JSESSIONID=D81A4DD3D95FBE0E6A7405EC2B31A8EA
```
4. Error
`[CRITICAL] connection timed out to the target URL. sqlmap is going to retry the request(s)`

**Expected behavior**
Not timeout because the URL tested is the same of the first case.

**Running environment:**
 - sqlmap version: 1.3.5.79#dev
 - Installation method: git
 - Operating system: MacOS Mojave 10.14.4
 - Python version: Python 2.7.16

**Target details:**
 - Relevant console output
```
[12:00:55] [INFO] parsing HTTP request from '/pathto-http-request-file/sqlrequest.txt'
[12:00:55] [INFO] fetched random HTTP User-Agent header value 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/3.0.198.0 Safari/532.0' from file '/path-to-sqlmap/sqlmap/txt/user-agents.txt'
JSON data found in POST data. Do you want to process it? [Y/n/q] Y
[12:00:56] [INFO] testing connection to the target URL
[12:01:26] [CRITICAL] connection timed out to the target URL. sqlmap is going to retry the request(s)
```

**Comment by stamparm** [comment]
Basically:

1) You haven't included any of that JSON data inside the request file
2) You haven't bothered to take a look at the network level what is going on
3) I really can't see any useful information here to reproduce the "issue"

**Comment by strano666** [comment]
I forgot to include JSON data, but there was.
I have edited the post

Anyway the problem was that did not use ssl, so with `--force-ssl` the problem it is solved.

Thanks for the help.
