### ISSUE TITLE
Unknown Firewall nexusguard

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3689]
nexusguard.com

![IMG_20190521_164139](https://user-images.githubusercontent.com/20995449/58081495-c2f4dd80-7be7-11e9-8411-33bb3eb38b67.jpg)

ˋˋ`Server: 2.0.0.20.20.973a686
...

<!DOCTYPE html><html lang="en" ng-app="myApp" ng-controller="errormain"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="ie=edge"><title></title><style>    html,body,div{padding: 0; margin: 0;}</style></head><body><iframe id="autherframe" frameBorder="0" src="https://speresources.nexusguard.com/wafpage/index.html#403;104.244.73.126;4nugIQAAAAAAAAAAaPRJfqWn;403" height="100%" width="100%"></iframe><script>var doc=document,autherframe=doc.getElementById("autherframe");var frameWin=autherframe.contentWindow;var frameDoc=autherframe.contentWindow.document;var frameBody=autherframe.contentWindow.document.body;autherframe.onload=function(){this.height=window.innerHeight>600?window.innerHeight:"600px";this.scrolling=window.innerHeight>600?"no":"yes"};</script></body></html>
ˋˋˋ

ip: 104.244.73.126 (google data saver)

**Comment by stamparm** [comment]
Thank you for your report. Find it implemented now

**Comment by huitc** [comment]
### **more details:**
```
[=] signature: '2e68:RVdXu261OElCWapBYKcPk4JzWOtohM4JiUcMr2RXg1uQJbX3uhdOn9htOj+hX7AB16FcPxJPdLsXo2tLaK99n+i7c4VmkwI3FZnxtTtBeq+c36A5chW1XaTD'
```

I hope these thing can help you ^^''
