### ISSUE TITLE
tamper

### ISSUE THREAD

**Issue by bigboy606** [sqlmapproject/sqlmap#3695]
TYPE: AND/OR time-based blind
Title: MySQL 5.0.12 AND time-based blind (SELECT)
payload : lang=fr AND (SELECT * FROM (SELECT (SELECT SLEEP(10)))VqEZ)

what tamper should I use?

**Comment by stamparm** [comment]
* https://github.com/sqlmapproject/sqlmap/wiki/FAQ#which-tamper-script-to-use-to-bypass-a-wafidsips-protection
* Use `python sqlmap.py --list-tampers` to get list of all tamper scripts along with their description

**Comment by bigboy606** [comment]
I know it but I don't understand what tamper should I use in this situation
