### ISSUE TITLE
can't use touch keyboard

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3699]
press `Up Arrow` key --> `^[[A` 
(when I using `--sqlmap-shell`)

```
sqlmap-shell> ^[[A
```

**Comment by huitc** [comment]
or... just me???.... (termux

**Comment by huitc** [comment]
https://github.com/sqlmapproject/sqlmap/issues/3702

**Comment by stamparm** [comment]
Duplicate of #3702
