### ISSUE TITLE
Operating system shell functionality not yet implemented for Oracle

### ISSUE THREAD

**Issue by shademajed** [sqlmapproject/sqlmap#3721]
sqlmap.py -u "http://***********************************" --os-shel

This error comes out

[17:59:40] [INFO] the back-end DBMS is Oracle
web application technology: Apache
back-end DBMS: Oracle
[17:59:40] [CRITICAL] Operating system shell functionality not yet implemented for Oracle
[17:59:40] [WARNING] HTTP error codes detected during run:
500 (Internal Server Error) - 1 times

**Comment by stamparm** [comment]
As said, not implemented. Not sure why are you raising the issue

**Comment by shademajed** [comment]
Brother
  I know it has not been implemented but how
I stand up
send
  The Shell
Are there other orders?

**Comment by stamparm** [comment]
So, basically, you are being warned that it is not being implemented. Hence, you know that we know that it is not there. What's the issue again?
