### ISSUE TITLE
Multipart SQL Injection not work

### ISSUE THREAD

**Issue by gerardmendez** [sqlmapproject/sqlmap#3722]
I use file with -r and not work i obtain critical error

POST /recordar.php HTTP/1.1
Host: localhost
Accept-Encoding: gzip, deflate
Accept: */*
Accept-Language: en-US,en-GB;q=0.9,en;q=0.8
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Connection: close
Cache-Control: max-age=0
Referer: https://localhost/recordar.php
Content-Type: multipart/form-data; boundary=--------2124470705
Content-Length: 261
Cookie: PHPSESSID=2v63uo4pogvc4eld1hf47fdfn6

----------2124470705
Content-Disposition: form-data; name="username"

ebHrsMJU' waitfor delay'0:0:20'--
----------2124470705
Content-Disposition: form-data; name="mail"

716596
----------2124470705
Content-Disposition: form-data; name="send"

Enviar
----------2124470705--

This is my post file 

and this is sqlmap error

C:\sqlmap>sqlmap.py -u -r request.txt -p "username" --dbs
        ___
       __H__
 ___ ___[.]_____ ___ ___  {1.3.4.32#dev}
|_ -| . [,]     | .'| . |
|___|_  [,]_|_|_|__,|  _|
      |_|V...       |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting @ 08:23:30 /2019-05-27/

[08:23:31] [CRITICAL] all testable parameters you provided are not present within the given request data

[*] ending @ 08:23:31 /2019-05-27/

C:\sqlmap>

I try with sqlmap.py -u -r request.txt -p 'username'  --dbs
sqlmap.py -u -r request.txt -p username --dbs

ever the same error.

**Comment by stamparm** [comment]
You are using empty `-u` option
