### ISSUE TITLE
Error running tamper

### ISSUE THREAD

**Issue by rodraiher** [sqlmapproject/sqlmap#3729]
![image](https://user-images.githubusercontent.com/51214066/58664208-92f2bc00-8304-11e9-9645-57fdd93e1a9b.png)

running the tamper command, I got this error:

[CRITICAL] tamper script 'nonrecursivereplacement' does not exist

I found this file in the directory:
-rw-r--r-- 1 root root 1.2K Jan 14  2015 /usr/share/golismero/tools/sqlmap/tamper/nonrecursivereplacement.py

any hint?

**Comment by stamparm** [comment]
That's a custom tamper script. Please put it in (e.g.) `/tmp/nonrecursivereplacement.py` and call sqlmap with `--tamper=/tmp/nonrecursivereplacement.py`

**Comment by stamparm** [comment]
Duplicate of #3735
