### ISSUE TITLE
sqlmap returning unrecognized values

### ISSUE THREAD

**Issue by cooldsec** [sqlmapproject/sqlmap#3730]
I dump the site passwords and came that type of hash / value

login,password

admin , s\xd75y\xb6\xf9\xe7\x8f9}\xd6\xdaw\xb7[\xe3\xd6\xf9\xd7oZ\xe3\x9e5

what is it? and how to decrypt?

**Comment by stamparm** [comment]
A) `password` is clearly in binary format. Please use `--binary-fields=password --fresh-queries` next time you'll retrieve it. That way you'll get it in hexadecimal format, ready to be (maybe) cracked
B) It looks like 192-bit hash digest. My wild guess is that somebody did the PHP's `tiger192,3 (raw)` and just put it inside the database BLOB

Hence, do the A), store the (hex) hash in some text file, run the hashcat against it and pray to heavens

**Comment by cooldsec** [comment]
Thanks for help brother
