### ISSUE TITLE
 current user is DBA: False

### ISSUE THREAD

**Issue by ahmedmhmdn** [sqlmapproject/sqlmap#3733]
Hello fellas, today i decide to do some scans in one local site the function i used is {sqlmap -u "url"  --current-user --is-dba}cast everything worked smoothly then i just got current user is DBA : False i though its from the site, then i just randomly decide to run on 4-5 more with the same options and i got always same result? Am i doing something wrong or ? 
thanks in advance

**Comment by stamparm** [comment]
What's the problem? I didn't understand from the text
