### ISSUE TITLE
a feature request

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3738]
some webpage will check if the submitted content is different, and if so, update the content to the database (like profile page

**Comment by huitc** [comment]
So... how do I specify two or more different values ​​to make a request in turn?
like --randomize but more better.. (to me? I think

**Comment by stamparm** [comment]
Sorry, I couldn't understand the issue here. Can you please write some examples or anything?

**Comment by huitc** [comment]
Have you "fixed" it? ^^''
