### ISSUE TITLE
CPU usage near 100%

### ISSUE THREAD

**Issue by SecurityFlaw** [sqlmapproject/sqlmap#3760]
I think this must be checked:
![Screenshot #01](https://i.imgur.com/zlpvDU8.png)

![Screenshot #02](https://i.imgur.com/d0KbW6S.png)

**Comment by huitc** [comment]
The feature itself will use more hardware performance, isn't it?

**Comment by stamparm** [comment]
This is a joke, right? You have a hash cracking running (which you could skip when asked for). Please go and troll somewhere else
