### ISSUE TITLE
sqlmap not detecting sqli

### ISSUE THREAD

**Issue by bird-man-123** [sqlmapproject/sqlmap#3771]
I am testing a system and I have a very basic SQL injection with endpoint something like

website.com/token?id=1

I have discovered that payloads such as

website.com/token?id=1 union select 1,2,table_name from information_schema.tables limit 1 offset 1

returns a page with the title = 1, the header = 2 and the footer = table_name

so I'm guessing the SQL command looks something like

command = "select title,header,footer from table where id = " + id + ";"

If I give it the wrong number of columns or some other invalid SQL command it returns a status code 200 with a python traceback error about invalid sql.

If I were so inclined I could manually get all the information from the database, one row at a time, but I would rather automate this. However I can't seem to get sqlmap to detect this at all. It just keeps saying "all tested parameters do not appear to be injectable". Is there some flag I can give it to make it work?

Many thanks

**Comment by stamparm** [comment]
This should be fairly easy for sqlmap to detect. Something else is wrong in your case.

Please try to use:

1) `--union-cols=3`
2) `--parse-errors`
3) `-t traffic.txt`

One by one and/or combinations

As said, this should be really easy. I don't see from your report that you've tried to DEBUG it in any matter, so I am not sure how to help you here more.
