### ISSUE TITLE
about --second-order

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3774]
in usage page:
> You can manually tell sqlmap to test for this type of SQL injection by using option --second-order with the URL address or --second-req with request file for sending to the server where results are being shown.

but...
```
        techniques.add_argument("--second-url", dest="secondUrl",
                              help="Resulting page URL searched for second-order response")

        techniques.add_argument("--second-req", dest="secondReq",
                              help="Load second-order HTTP request from file")
```
https://github.com/sqlmapproject/sqlmap/blob/e355a087a4379e72f6bbcf68d16ed7b26f4d8e90/lib/parse/cmdline.py#L376

**Comment by stamparm** [comment]
What's the issue? Help is not clear enough?

**Comment by huitc** [comment]
```
        techniques.add_argument("--second-url", dest="secondUrl",
            help="Resulting page URL searched for second-order response")

        techniques.add_argument("--second-req", dest="secondReq",
            help="Load second-order HTTP request from file")
```
where is `--second-order`? ^^''
