### ISSUE TITLE
Sqlmap redirection issue

### ISSUE THREAD

**Issue by anonvirus8085** [sqlmapproject/sqlmap#3778]
When i was running sqlmap in my kali linux
Firatly its ask do you want to follow redirection and when i try to write n its automatically select yes and follow redirection.

**Comment by stamparm** [comment]
In following example it is clear that sqlmap follows the original URI when pressed `n` to follow the redirection:

![foo](https://user-images.githubusercontent.com/921555/60167257-09e77b80-9803-11e9-8960-893db0139028.png)
