### ISSUE TITLE
about --tor and --ignore-proxy

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3783]
> --ignore-proxy      Ignore system default proxy settings

why i cant use `--tor` and `--ignore-proxy` at the same time? ^^''

```
[CRITICAL] switch '--tor' is incompatible with switch '--ignore-proxy'
```

**Comment by stamparm** [comment]
Because `--tor` automatically sets the (SOCKS) proxy. Hence, setting of proxy while using the `--ignore-proxy` at the same time does not make much sense.

In plain-speak, usage of `--tor` makes `--ignore-proxy` irrelevant. Hence the warning
