### ISSUE TITLE
about --null-connection

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3787]
is it possible to use `--null-connection` in `--second-url`? ^^''

**Comment by stamparm** [comment]
A) I have a feeling that those two switches/options would/are rarely being used together
B) Currently, `--null-connection` works only against the main target URL (not the secondary)
C) There is a scenario where second-order page could be placed on another host, while null-connection is being checked only against the main one
D) All in all, now this combination is just ignored and the second-order URL is accessed as is. IMO, current situation is more than acceptable

**Comment by huitc** [comment]
ok...
