### ISSUE TITLE
about --common-xxx

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3788]
I think we can collect and analyze database names, table names, and so on retrieved by users to make `--common-xxx` better

**Comment by huitc** [comment]
Just save it to the client? or.. if you have some resources, upload those to a server?(If the user accepts) how about that??? ^^''

**Comment by stamparm** [comment]
IMO, not sure that there would be lots of users that would "share" it through sqlmap. Also, it would be kind of strange that sqlmap asks you everytime "would you like to share". For example, I would not like to share such data, at least through program's interface (maybe through a Github issue)

**Comment by huitc** [comment]
so... just save it to the client?? ^^'' ok... NICE~! (^W^))))

**Comment by stamparm** [comment]
Ok. For example, which common table names and column names are you willing to share right here, right now?

**Comment by huitc** [comment]
.
