### ISSUE TITLE
prompt keeps kicking me out of sqlmap

### ISSUE THREAD

**Issue by komer83** [sqlmapproject/sqlmap#3790]
trying to security check my website using sqlmap (for the database) using 
sqpmap -o -u http://whatevertheaddress.com 

When ever the test comes to UNION based I'm asked to select between Yes or No, but no matter what, it kicks me back to the command line. 

Using latest Kali Linux (19.03 I believe) with sqlmap 1.3.6

Thanks

**Comment by stamparm** [comment]
![eee](https://user-images.githubusercontent.com/921555/60573056-33f6eb80-9d77-11e9-8be6-23959a143871.png)

**Comment by stamparm** [comment]
It is really not clear what are you trying to report here. Also, you've just skipped the whole Issue template.
