### ISSUE TITLE
No bug - just need help.

### ISSUE THREAD

**Issue by sickboydj** [sqlmapproject/sqlmap#3803]
Hey guys. Im new to SQL and SQLMap. Im trying to find a way to dump only a couple of specific columns from a table and not the entire table.

Mysql
table_games
etc | etc  | needed | etc | etc | needed | etc |etc | needed | etc 

The table is over 100 columns and Im only interested in dumping 3 or 4 of them. (needed)

Is this possible? or Im dreaming?

Thanks !!!

**Comment by huitc** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/Usage
or
`sqlmap.py -hh`

```
sqlmap.py --dump -D xxx -T xxx -C xxx

    --dump              Dump DBMS database table entries
    --dump-all          Dump all DBMS databases tables entries

    -D DB               DBMS database to enumerate
    -T TBL              DBMS database table(s) to enumerate
    -C COL              DBMS database table column(s) to enumerate
    -X EXCLUDE          DBMS database identifier(s) to not enumerate
```

**Comment by stamparm** [comment]
As @huitc mentioned, `--dump -T table_games -C col1,col2,col3`

**Comment by huitc** [comment]
https://github.com/sqlmapproject/sqlmap/issues/3811 @sandman4812av
