### ISSUE TITLE
consider to duplicate logging to file 

### ISSUE THREAD

**Issue by aratic** [sqlmapproject/sqlmap#3807]
**Is your feature request related to a problem? Please describe.**

> nop, just at occasions, while testing a long term inject, it would be nice to have log in file AND in terminal stdout

**Describe the solution you'd like**

> to add a default FileHandler at lib/core/log.py , so everything to terminal got duplicate to a file, maybe named sqlmap_${ts}.log , maybe also consider to customize level

**Describe alternatives you've considered**

> nope

**Additional context**

> I should be able to help / prepare pull request, if this request is generally good and desired :)

**Comment by stamparm** [comment]
![bbb](https://user-images.githubusercontent.com/921555/60800183-1067e280-a175-11e9-9a8b-22d1f13b5da2.png)

There won't be stuffing of ALL console output to already well established logging of important information into the `log` file.

**Comment by aratic** [comment]
many thanks @stamparm  , found equivalnt log at Windows, 
$USER\AppData\Local\sqlmap\output\$WebSite_URL

will zip it after finished checking
