### ISSUE TITLE
about pywin32

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3808]
```
 [CRITICAL] sqlmap requires third-party module 'pywin32' in order to use Metasploit functionalities on Windows. You can download it from 'https://sourceforge.net/projects/pywin32/files/pywin32/'
```

`https://sourceforge.net/projects/pywin32/files/pywin32/` to `https://github.com/mhammond/pywin32`

**Comment by huitc** [comment]
or `pip install pywin32`

**Comment by huitc** [comment]
I installed it via `pip`, but sqlmap couldn't detect it.

**Comment by stamparm** [comment]
A) You are doing something wrong. Just installed fresh Python 2.7 and `pip install pywin32` and tried to import `win32file` (submodule from pywin32 - same one which generates the nagging error in your case). Please find attached the sample run.
B) Metasploit is still not supported by sqlmap on Windows (Issues #28 and #2285)

![test](https://user-images.githubusercontent.com/921555/60804677-51b0c000-a17e-11e9-9bb2-55e74c936512.png)

**Comment by huitc** [comment]
^^''
