### ISSUE TITLE
sqlmap dumps all data in table, but doesn't retrieve any data specify columns from that table

### ISSUE THREAD

**Issue by sandman4812av** [sqlmapproject/sqlmap#3811]
Hi
sqlmap dumps all data in table, but I want to dump specify columns in that table, but sqlmap doesn't retrieve any data
I try --hex --no-cast tamper scripts (unionalltounion, between) but no result
What can you advice for help ? 
Thanks !

**Comment by stamparm** [comment]
![2019-07-09_09-48](https://user-images.githubusercontent.com/921555/60869139-b1ff3a80-a22e-11e9-9d97-4d79eeec8af3.png)

**Comment by sandman4812av** [comment]
@stamparm can u advice anything ?
Thanks

**Comment by stamparm** [comment]
You have provided zero useful data on the Issue itself. I am not sure what to respond to all of this as I can't guess what's happening
