### ISSUE TITLE
a request about -g

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3814]
can I not use proxy (include tor) when I am searching for Google? `-g`
then my request will not be blocked..

**Comment by stamparm** [comment]
You can always try. Google has a strict blocking policy for Tor and known proxies. Not a sqlmap issue. That's why sqlmap asks you whether you want to use DuckDuckGo or Bing as a fallback

**Comment by huitc** [comment]
no.... i mean if google searching, dont use tor, just for the target(s)
