### ISSUE TITLE
problem about --technique U

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3817]
If I use "--technique U", I can't dump anything, but "--technique B" is fine.

I will tell you more details later.

**Comment by huitc** [comment]
The latest versions also have the same problem

**Comment by stamparm** [comment]
Please, take a second and look into your report. It has zero useful information. I'll just leave one example here where it works and close this one down as unreproducible:

![foo](https://user-images.githubusercontent.com/921555/61037263-fde6e680-a3ca-11e9-9498-d76e9f16004f.png)

p.s. there are literary tens of different possibilities why you had problems, while sqlmap is most likely not one of them
