### ISSUE TITLE
about usage history

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3822]
if usage history `/.sqlmap/output/` can also record `--sqlmap-shell` it would be great

**Comment by huitc** [comment]
and recent history too

**Comment by stamparm** [comment]
I couldn't reproduce this, ONLY in case of initial sqlmap run without `.sqlmap` home directory. Pushed related patch

**Comment by stamparm** [comment]
![history](https://user-images.githubusercontent.com/921555/61292841-95d13f80-a7d2-11e9-9876-a94703f1ca5a.png)

**Comment by huitc** [comment]
i mean if `/.sqlmap/output/www.test.us/target.txt` and `log` file can also record `--sqlmap-shell` it would be great
