### ISSUE TITLE
Unknown Firewall

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3827]
```
Server: qianxin-waf
or
Server: 360wzws
```
360?

http://fofa.so/result?q=server%3D%3D%22360wzws%22+%7C%7C+server%3D%3D%22qianxin-waf%22&qbase64=c2VydmVyPT0iMzYwd3p3cyIgfHwgc2VydmVyPT0icWlhbnhpbi13YWYi&full=true

**Comment by stamparm** [comment]
I can't find any "new" related server which is actually not 360. Also, that same "qianxin-waf" can be disregarded as 360 is actively being rebranded by couple of other companies
