### ISSUE TITLE
get2post and post2get

### ISSUE THREAD

**Issue by 687766616e** [sqlmapproject/sqlmap#3829]
detect that GET or POST http request can be change to a POST or GET method request or not (`$_REQUEST`

```
POST test.php?id=1 HTTP/1.1

(nothing)
```
to
```
GET test.php?id=1 HTTP/1.1

```
for who want to save his data ( or --null-connection ?

and
```
GET test.php?id=1

```
to
```
POST test.php

id=1
```
for who want to use `--chunk` but he not sure the request can change to a POST request or not

**Comment by huitc** [comment]
```
--get2post --gettopost or --g2p force
--get2post-check --gettopost-check or --g2pc check or not...
```

**Comment by stamparm** [comment]
1) considered to do this automatically, though, it would cost a single request per parameter. In case of target URLs with N parameters, this would add N requests. Now, (IMO) as this information doesn't look like something that would be used by many users, I am quite skeptical about the usability in the first place
2) also, quite skeptical that these new switches will be used by many users. Thus, I suggest the usage of [`--preprocess`](https://github.com/sqlmapproject/sqlmap/wiki/Usage#preprocess-request). One primitive example (Note: written for Python3) would look like:

```py3
#!/usr/bin/env python3

def preprocess(req):
    if '?' in req.full_url:
        parts = req.full_url.split('?', 1)
        del req.full_url
        req.full_url, req.data = parts
        req.method = "POST"
        req.data = req.data.encode()
```
