### ISSUE TITLE
How to Ignore many Code like 401-402-406-500

### ISSUE THREAD

**Issue by batuperm4t4** [sqlmapproject/sqlmap#3831]
Hallo Good People,
Wondering if I could ignore few codes in one command in sqlmap like 
--ignore-code=401,402,500 
but this command is not true, do sqlmap have another options for this ignore code?

thanks

**Comment by stamparm** [comment]
With the latest commit (revision) you'll be able to use a list of HTTP codes, like: `--ignore-code=401,402,406,500`
