### ISSUE TITLE
Fixed on 19 Entities

### ISSUE THREAD

**Issue by electroxero** [sqlmapproject/sqlmap#3833]
**Describe the bug**
The dump phase after an union-based SQL Injection is fixed on 19 entities. I'm sure there are more dbs and records because if a dump the `--current-db` i retrieve a different database from the list.

**SQLMAP Command**
`sqlmap -r /request.txt --keep-alive --technique=U --union-cols 13 -v 3 --prefix "'" --suffix "-- -" --answers="PROCESS=Y,FOLLOW=N" --random-agent --dbms mssql --dbs`

**Screenshots**
![image](https://user-images.githubusercontent.com/20456461/61377697-03996c00-a8a4-11e9-850e-2c17fc579f31.png)
![image](https://user-images.githubusercontent.com/20456461/61377783-35123780-a8a4-11e9-936e-9e0efa69d0eb.png)

**Running environment:**
 - sqlmap version [1.3.7#stable]
 - Operating system:  [ARCH AUR]

**Target details:**
```
web server operating system: Windows 8.1 or 2012 R2
web application technology: ASP.NET, Microsoft IIS 8.5
back-end DBMS: Microsoft SQL Server 2008
```

**Comment by stamparm** [comment]
0) Try to get some other meaningful data (e.g. `--banner` or `--current-user` or...) to see if there is a problem with those too
1) Try to rerun everything with `--fresh-queries`
2) Try to rerun everything with `--flush-session`
3) Try to run without `--keep-alive --union-cols ... --prefix ... --suffix`, while using `--flush-session`
4) Try to catch error messages with `--parse-errors`
5) Try to capture traffic with `--dump ... -t traffic.txt`

---

If you are not able to come to any conclusion after these steps, capture traffic with `--flush-session --batch --dbs -t traffic.txt --banner --union-cols 13 --prefix "'" --suffix "-- -"` and send the resulting `traffic.txt`, along with the console output to `miroslav@sqlmap.org`

**Comment by electroxero** [comment]
Ok interesting update is not a real bug.

The web application print an out with the php code limited to 19 inside a table, so sqlmap "think" that there are only 19 databases, but in reality there more but the output is inside a table with multiple pages.

Can I force sqlmap to limit the union query to 19?

`4' UNION ALL SELECT TOP 19 ....`

**Comment by stamparm** [comment]
* sqlmap automatically recognizes this kind of "trimming", but it seems that you have a special case (not usual several items)
* There is no such thing as "please pull out 19 by 19 items" in sqlmap in case of union SQLi
* Please update to latest revision and in every future run (for that target) use `--fresh-queries --force-partial`

p.s. sqlmap checks up to 15 rows for partial union. Please don't push me to include check for "19" as in those kind of cases web servers have MORE problems with the length of payloads than you have with your special case

**Comment by electroxero** [comment]
Great job, thank you.

But I think for managing this type of cases, you can allow the user to set the number of force-partial?

So, for example, I can set 19 it will work.

**Comment by stamparm** [comment]
So, to repeat myself:

![WTF](https://user-images.githubusercontent.com/921555/61459423-f98f7000-a96c-11e9-980b-9cecb8b878f0.png)

p.s. in gentle words, if that would be "feasible" everybody would do it
