### ISSUE TITLE
a feature request about --randomize

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3834]
if a webpage only accept `a=yes or a=no or a=notsure`
or 
`refer` must be come from `xxx.com/test.php` or `yyy.com`
or
`user-agent` can't be too old or can only use the specified value

then how do I randomize them?
Can I bypass this by loading the specified txt file from user? like `--safe-req`

**Comment by huitc** [comment]
some idea for you
```
--randomize "accept=yes,no;a=1,2,3"
--randomize-file 123.txt
```

**Comment by stamparm** [comment]
Done the `--randomize "accept=yes,no;a=1,2,3"` part. Currently will disregard the rest as it seems to me that this should be enough. If there will be more similar requests (from other users), will upgrade it more

**Comment by stamparm** [comment]
![randomize](https://user-images.githubusercontent.com/921555/61528763-e4bfe480-aa1f-11e9-9bc7-58857f6f725f.png)

**Comment by huitc** [comment]
NICE~! (^W^)))))

**Comment by huitc** [comment]
> If there will be more similar requests (from other users), will upgrade it more

ok.. ^^''
