### ISSUE TITLE
Problem with option --threads

### ISSUE THREAD

**Issue by hack0mate** [sqlmapproject/sqlmap#3837]
With the last commit when option --threads=10 in use sqlmap present the Warning: "running in a single-thread mode. Please consider usage of option '--threads' for faster data retrieval"

But the --threads=10 put on 10 threads not 1 single thread already in use.

Looks like bug warning or multithreading not working as it supposed to be.

**Comment by stamparm** [comment]
Bug warning (multi-threading itself was/is ok). Patched
