### ISSUE TITLE
add more Unknown Firewall

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3839]
https://fofa.so/library?utf8=%E2%9C%93&keyword=

`ctrl + c` find these:

- 安全审计
- 威胁情报产品
- 身份认证系统 ?
- 入侵防护
- 其他安全产品
- 反病毒
- 抗ddos ?
- 数据库审计 ?
- 安全文件传输 ?
- 安全基线 ?
- 堡垒机
- 日志分析 ?
- 大数据 ?
- 扫描器
- 安全软件
- 代理 ?
- 网关 ?
- 代理服务器
- Cms ?
- Saas平台 ?
- 安全检测平台
- 网站云防护
- Cdn
- 入侵检测
- 安全网关
- Waf
- 防火墙

**Comment by huitc** [comment]
about fofa:
https://0ut3r.space/2018/11/20/devices-search/ and search `fofa`
or
fofa.so click `查询语法` 😅

**Comment by stamparm** [comment]
It looks like we have a language barrier here. You could help me like this:

1) Search with whatever search engine potentially protected sites
2) Try to provoke the WAF (e.g. with `?id=AND 1=1 UNION ALL SELECT 1,NULL,'<script>alert("XSS")</script>',table_name FROM information_schema.tables WHERE 2>1--/**/; EXEC xp_cmdshell('cat ../../../etc/passwd')`)
3) Extract the characteristic response string (e.g. one of those you've copy-pasted above)
4) Find the WAF product name and company
5) Report back the findings (e.g. raise a new Issue with a new finding either here or at https://github.com/stamparm/identYwaf <- used by sqlmap internally for a month or so)

**Comment by huitc** [comment]
https://github.com/stamparm/identYwaf
```
You can't perform that action at this time.
```
....

**Comment by huitc** [comment]
or.. just... `WAF` for now... ^^''
...(wait)

and these:
https://github.com/TideSec/TideFinger/blob/master/cms_finger.db
...(wait)

**Comment by huitc** [comment]
360 (when you testing
```
HTTP/1.1 999 No Hacking
X-Powered-By-Yqk: zhuji.360.cn 1.0.8.8 F1W1
X-Yqk-Set: F1W1
X-Safe-Firewall: zhuji.360.cn 1.0.8.8 F1W1
```
