### ISSUE TITLE
question about --search

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3840]
What should I do if I want to search column `%p%w%d%` and `p%w%d`?
`-C "%p%w%d%"` and `--answer "do you want sqlmap to consider provided column=as exact column names"` or what?😅

**Comment by huitc** [comment]
and... what if I want to search `pos` and exclude `post`?... 😅

**Comment by stamparm** [comment]
`... --batch --search -C "%p%w%d%" --answers "consider=2"`

**Comment by huitc** [comment]
`--search -C "%p%w%d%" --answers "consider=2"` with `--tamper equaltolike.py`?
