### ISSUE TITLE
target server does not accept sqlmap built-in webshell files

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3844]
But other webshell file have no relevant questions.

So I suggest you do this:
encryption webshell file:
https://github.com/djunny/enphp

**Comment by huitc** [comment]
other webshell file: (Have been successful in the past)
https://github.com/tennc/webshell/blob/master/php/PHP%E7%AE%80%E5%8D%95%E5%B0%8F%E9%A9%AC%E6%BA%90%E7%A0%81.php
https://github.com/AntSwordProject/antSword/tree/master/shells

**Comment by stamparm** [comment]
All shell files used in sqlmap ARE prepared for a communication with the sqlmap. This basically means that there are arguments and parts of response(s) that needs to be fulfilled. There won't be changes with some random PHP files.

**Comment by huitc** [comment]
at least encrypt them? or... not?.... ^^''
