### ISSUE TITLE
a request

### ISSUE THREAD

**Issue by 687766616e** [sqlmapproject/sqlmap#3847]
Increase speed by importing multiple cookies (for `--technique ST`

**Comment by stamparm** [comment]
Not a bad idea, but:

1) Who would use it?
2) How to use it in as-easy way as possible?

---

For example, `--sessions=...  File containing multiple session cookies`. You would know that this could improve the data retrieval, but not sure who else would be aware of it. Users are inert, sticking to basic options/switches

**Comment by huitc** [comment]
1. If it does work, I think many people will use it. i think ( people who can only use `--technique TS`
2. `--sessions-file`? ^^''

**Comment by 687766616e** [comment]
or multiple proxy server? `--proxy-file`? (if login needed

**Comment by 13Em0SPVPaoq** [comment]
> Increase speed by importing multiple cookies (for `--technique ST`

for `--technique ST` and `--risk 2`

**Comment by stamparm** [comment]
closing this down. sessions usually expire after a timeout. not sure that it is feasible to put bunch of time-constrained sessions into a file and hope that others will just work

**Comment by stamparm** [comment]
p.s. there is `--live-cookies=L..  Live cookies file used for loading up-to-date values`
