### ISSUE TITLE
add no-cache no-store header

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3860]
like this?:
```
Pragma: no-cache
Cache-Control: no-cache
```
because some site use Redis or some kind like that

```
max-age=0 ?
```

**Comment by stamparm** [comment]
I am not sure what are you asking here? You want those headers to be included?

**Comment by stamparm** [comment]
http://stackoverflow.com/a/1383359

Based on that same reference, only `Cache-Control: no-cache` is used, just to invalidate potential in-between caching mechanism(s)
