### ISSUE TITLE
is this site is vulnerable?

### ISSUE THREAD

**Issue by SamirHamoud** [sqlmapproject/sqlmap#3861]
i spent too much time to attack my specific website that is protected by WAF  cloudflare but i could bypass it by --tamper="luanginx" as i was getting error code "500,404,403,400" without using it while using sqlmap but now not
i found out this site might be vulnerable for SQL injection but at the End , False Positive or my internet network requested timeout , i'm not sure!
here is my sqlmap commands : 
sqlmap.py -u "http://play-syntix.com/index.php?action=connect*" --data="username=ZAP&password=ZAP" --skip="username,password" --method "POST" --level=5 --risk=3 --random-agent --tamper="luanginx" --identify-waf --dbs --eta -o --batch --banner --flush-session --technique=BEUSTQ --random-agent --proxy "http://127.0.0.1:80" --random-agent
....................................................................................................................................................................................................
                                                   Outputs
[INFO] 'ORDER BY' technique appears to be usable. This should reduce the time needed to find the right number of query columns. Automatically extending the range for current UNION query injection technique test
[INFO] target URL appears to have 34692 columns in query
....................................................................................................................................................................................................
All i want to know
1)is [INFO] number 1&2 in Outputs are vulnerables ?
1)what is Technique i should use like {B,E,Q,S,T] ?
2)is this website is vulnerable or not ?
3)is there any mistake in my command line ?
4)is there any additional option i have to put in my command line ?
....................................................................................................................................................................................................
Note : i used OWASP ZAP to scan this website and found too many alerts for SQL Injection and other techniques & i didn't get WAF identified when i used that commands , i knew it is Cloudflare at the first time trying SQL Injection
i hope you help me and plz mr stamparm be quiet as i see you too nervous all time :D :P 
approciate that i spent only 1 month learning about SQL Injection :)
Thx <3

**Comment by huitc** [comment]
http://www.crimeflare.org:82/cfs.html good luck

**Comment by stamparm** [comment]
1) It doesn't make any sense to use `--skip="username,password"`, UNLESS you are "targeting" some header (e.g. UA) - I can't guess what you are targeting here
2) I would say that your site is not vulnerable. `target URL appears to have 34692 columns in query` is a junk finding
3) Please don't post real sites here
