### ISSUE TITLE
about --proxy

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3863]
I think if `--proxy` exclude `-g` it would be great, because if you using proxy or something like that, you always got `detected 'unusual' traffic`

`--proxy-search` `--proxy-exclude-search`?

**Comment by stamparm** [comment]
There are also regular (non-shared) proxy cases (e.g. MiTM proxy or SOCKS/SSH)

**Comment by huitc** [comment]
so you gonna do it? `--proxy-exclude-g`?

**Comment by huitc** [comment]
or?....
