### ISSUE TITLE
--form bug

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3866]
`input=%3F%3F%3F%3F%3F%3F` should be `input=%E6%9F%A5%E8%A9%A2` <-- chinese

**Comment by stamparm** [comment]
1) I don't know what's the root of this "issue"
2) Guessing that you have a problem with encoding as those chinese chars are replaced with `?`
3) Please make a proper issue where something could be either reproduced or understood

**Comment by huitc** [comment]
```
[#1] form:
POST http://www.test.us/test.php
POST data: submit=%3F%3F%3F%3F%3F%3F

webpage:
<input type="submit" name="submit" value="查詢">
```
