### ISSUE TITLE
about file compress

### ISSUE THREAD

**Issue by 687766616e** [sqlmapproject/sqlmap#3867]
my `/.sqlmap/output/log` and `session.sqlite` very heavy
`log` file 200+mb
`session.sqlite` 20+mb

So I started thinking that it would be great if some heavy files could be compressed.

**Comment by huitc** [comment]
`7z` or `tar`?

**Comment by huitc** [comment]
`--log-zip 7z`

**Comment by stamparm** [comment]
1) You can always do it yourself manually
2) Log files should be accessible as text for regular users
3) sqlite databases can't be compressed and accessible in the same time (at least not in non-commercial version)

**Comment by 687766616e** [comment]
> 1. You can always do it yourself manually

???................

**Comment by 687766616e** [comment]
ok.................. ^^''
