### ISSUE TITLE
found sqlinjection but not injectionin sql map

### ISSUE THREAD

**Issue by 0x240x23elu** [sqlmapproject/sqlmap#3869]
Hi i found injection 
with URL 

https://www.cordcutters.com/passport/process/TokenProcess.php?t=%2f%2e%2e%c0%af%2e%2e%2f%2e%2e%c0%af%2e%2e%2f%2e%2e%c0%af%2e%2e%2f%2e%2e%c0%af%2e%2e%2f%2e%2e%c0%af%2e%2e%2f%2e%2e%c0%af%2e%2e

but when i run sqlmap with command 

sqlmap -r cutc.txt --dbs -v3 --banner -p 't' --dbms=mysql --tamper=between,randomcase,space2comment --level=5 --risk=3 --random-agent --retries=2  --threads=10 "tec=BEU,bat,flu" --current-user --is-dba --parse-errors  --dummy --batch 

Response =[13:15:51] [WARNING] GET parameter 't' does not seem to be injectable
[13:15:51] [CRITICAL] all tested parameters do not appear to be injectable

How its possible .
![cut](https://user-images.githubusercontent.com/52744492/62685247-ea399a80-b9df-11e9-9453-81f224eb2646.png)

**Comment by stamparm** [comment]
1) Real site URLs are not welcome here
2) "I found injection" is not convincing
3) Something something "ExpiredSQL" is not covered with sqlmap
