### ISSUE TITLE
can't cleanup sqlmapoutput

### ISSUE THREAD

**Issue by alexintel5** [sqlmapproject/sqlmap#3870]
Hello, where (in sqlmap source files) can I change the output table name 'sqlmapoutput' result of stacked queries? The issue is I cannot do anymore --os-shell due to the table 'sqlmapoutput' has a lot of data (in my opinion) and result to 'connection timed out'. Also, I cannot --cleanup and drop this table manually all of these tries lead to time out of connection. Thanks in advance

**Comment by alexintel5** [comment]
--cleanup shows that operation was done and the table is deleted but genuinely it is not true, the table is exist

**Comment by 687766616e** [comment]
> --cleanup shows that operation was done and the table is deleted but genuinely it is not true, the table is exist

+1

**Comment by stamparm** [comment]
"Also, I cannot --cleanup and drop this table manually all of these tries lead to time out of connection" <- this doesn't make sense. All those "cleanup" commands are `DROP TABLE` and `DROP FUNCTION`. Those should not be dependent on table size. You have some other issue here

**Comment by stamparm** [comment]
"--cleanup shows that operation was done and the table is deleted but genuinely it is not true, the table is exist" <- as said, you have some other problem here. Cleanup commands are DUMB as they could be.

Please do a proper research before raising these kind of issues. You have a `-v 3`. Run it with `--cleanup` and try to run "problematic" payloads by yourself.

**Comment by alexintel5** [comment]
The issue was solved by changing default table name "sqlmapoutput" to an another one. "Those should not be dependent on table size. You have some other issue here" - you are right this table (the size is zero) can't be deleted even by DROP, TRUNCATE, DELETE command manually, lead to timeout in browser, still don't know what is the problem. But you should fix this tiny bug, if sqlmap can't delete this table there will be message

**Comment by stamparm** [comment]
With the latest commit added the following:

```
General:
...
--table-prefix=T..  Prefix used for temporary tables (default: "sqlmap")
...
```

p.s. for example, if you use `--table-prefix=foobar`, that same "output" table will be named `foobaroutput`
