### ISSUE TITLE
--ignore-code=409 doesn't work

### ISSUE THREAD

**Issue by wadim-al** [sqlmapproject/sqlmap#3877]
Tested on 1.3 release and current master 1.3.8.5#dev.
When using the --ignore-code=409 option, it still says 
[WARNING] HTTP error codes detected during run:
409 (Conflict) - 1 times

--ignore-code=401 works as indended. Did not try other codes.

OS: Windows 10
Python version: 2.7.15

**Comment by 687766616e** [comment]
dev ver?

**Comment by wadim-al** [comment]
> dev ver?

I've updated the initial post (1.3.8.5#dev)

**Comment by stamparm** [comment]
`--ignore-code` just ignores the HTTP error code to prevent anything unusual happening inside the sqlmap (e.g. abrupt program exit in between the testing procedure). That last `WARNING` message is just an (additional) info to the user to show him what was "strange" happening during the communication with the target server

**Comment by wadim-al** [comment]
The sqlmap was closed after that.

**Comment by stamparm** [comment]
Just a second to try to reproduce it...

**Comment by stamparm** [comment]
Unable to reproduce any kind of **unexpected** behavior (with and without `--ignore-code`):

![1](https://user-images.githubusercontent.com/921555/62931463-b33bfe00-bdbe-11e9-85f2-82ab8dfa4bb2.png)

![2](https://user-images.githubusercontent.com/921555/62931469-b59e5800-bdbe-11e9-817e-ada9e497c91d.png)

**Comment by stamparm** [comment]
p.s. you have some other problems, while `409` nor `--ignore-codes` are those
