### ISSUE TITLE
sqlmap oracle banner "A"

### ISSUE THREAD

**Issue by evilcode1** [sqlmapproject/sqlmap#3878]
i open i issue before but u close it :D without understand the problem u always answer ( WAF WAF WAF ) .... 
first of all when i try to attack my target i bypass the Cloudflare so i used the real ip for the websitye to inject it ... 
and this is the proof that the server does not have WAF ...
before bypass the cloudflare 👍 
https://i.postimg.cc/GLBkjqsG/Capture2.png

after bypass cloudflare 👍 
https://i.postimg.cc/nrGsCsSY/Capture.png

anyway when i try to use sqlmap on my remote server with this options : 

> python sqlmap.py --wizard -u "https://ip/ar/dataTableSearch?_=1565506334415&bRegex=false&bRegex_0=false&bRegex_1=false&bRegex_2=false&bSearchable_0=true&bSearchable_1=true&bSearchable_2=true&bSortable_0=true&bSortable_1=true&bSortable_2=true&iColumns=3&iDisplayLength=15&iDisplayStart=0&iSortCol_0=0&iSortingCols=1&mDataProp_0=0&mDataProp_1=1&mDataProp_2=2&pSecId=15&sColumns=%2C%2C&sEcho=4&sSearch=*&sSearch_0=&sSearch_1=&sSearch_2=&sSortDir_0=asc "

then i choose hard [3]
and then all [3]

i got this result : 

> web application technology: Servlet 2.4, Tomcat 5.5, JBoss 4.0.5.
> back-end DBMS: Oracle
> banner: 'A'
> multi-threading is considered unsafe in time-based data retrieval. Are you sure of your choice (breaking warranty) [y/N] N
> [17:28:37] [WARNING] time-based comparison requires larger statistical model, please wait..................... (done)
> current user:   None
> current schema (equivalent to database on Oracle):      None
> hostname:       None
> current user is DBA: False
> [17:28:50] [CRITICAL] unable to retrieve the number of database users
> 
> [*] ending @ 17:28:50 /2019-08-13/

banner A ??  what this mean and why i can't get any database ??

**Comment by stamparm** [comment]
Basically, I won't spend more than 2 minutes here.

A) In #3872 I didn't only say "WAF WAF WAF...". There is more at https://github.com/sqlmapproject/sqlmap/issues/3872#issuecomment-520785851
B) Please concentrate. If you are not able to retrieve **at least** a banner, you won't be able to retrieve anything. Banner 'A' is obviously **WRONG**.
C) Please don't open any new Issues before investing any time into researching what is going on - I'll immediately close those down as invalid. If you really think that anything can be deduced from `banner: 'A'` except that it is wrong and that you have some more research to do, then you are plain wrong
