### ISSUE TITLE
what are recommended tampers i have to be use ?

### ISSUE THREAD

**Issue by SamirHamoud** [sqlmapproject/sqlmap#3882]
Hello Sir 
Can you please tell me recommeneded tampers that could bypass WAF and other features?
 i don't need tampers for special DBMS as i used OWASP ZAP to scan my website and i got alert "SQL Injection" but DBMS type is not detected!

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/FAQ#which-tamper-script-to-use-to-bypass-a-wafips-protection
