### ISSUE TITLE
Visualization of the fetched schema within an external window - A DB diagram

### ISSUE THREAD

**Issue by f4nthomas** [sqlmapproject/sqlmap#3885]
Hello,

I was wondering about the graphical visualization (diagram) for the fetched DB schema. 

A such feature might be very useful for everyone who would like to display whole schema structure with relation arrows in some external graphical window - for example some pop-out window could open after the fetching schema which would draw all the DB's, their underlying tables, and also their columns. Maybe some more details could be also additionaly drawn within the legend at the bottom (current user, db version......whatever might help for a nice summary).  In case of larger DB's schemas, the ZOOM IN/ ZOOM OUT functions might be handy also as well. I can also imagine that it could be bind on some shortcuts also like google maps have, for example: **CTRL + mouse wheel UP** for **Zooming IN**, and **CTRL + mouse wheel DOWN** for **Zooming OUT**. 

Regarding to the launching option for the **command line:** 

It could be an additional switch for example:  
**--db-diagram** or 
**--schema-diagram** or 
**--db-visualization** or 
**--schema-visualization**

Some random picture for better imagination from google:
![image](https://user-images.githubusercontent.com/47302585/63261898-e0882080-c284-11e9-8122-df683a984f60.png)

What do you think of such feature? Thank you.

Best regards,
Tomas

**Comment by stamparm** [comment]
1) Current `--schema` doesn't fetch any relational data between tables and/or columns. For example, 99% users don't care about column `id` being a primary key or `cid` being a foreign key to `clients` table. That would just unnecessary prolong the enumeration and/or data retrieval phase
2) For this kind of visualization couple of third-party libraries would be required to use. Adding tons of new requirements for a console program (which has to evolve into the GUI as a more priority task) to display something that looks nice in regular SQL applications, IMO wouldn't have an added value in case of SQLi application. SQLi application needs to "break and enter" and not do stuff that SQL applications do (without usage of bit-by-bit data extraction)
