### ISSUE TITLE
Sql Map - Custom Injection point

### ISSUE THREAD

**Issue by jeromesheerin** [sqlmapproject/sqlmap#3889]
Hi There

During testing using the "*" as the custom injection point for my JSON data, I noticed that my cookie had the "*" included and it was valid the the active session. However it seems that sqlmap removes all occurrences of the "*" symbol from the POST request, and now my cookie is no longer valid. 

**To Reproduce**
Example of the request. As you can see the cookie has the "*" more than one, and sql map removes it 

PUT /rest/ui/workspace HTTP/1.1
Host: localhost
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: https://localhost
X-Requested-With: XMLHttpRequest
Content-Type: application/json; charset=utf-8
Application: alarmsearch
Content-Length: 303
Connection: close
Cookie: Prore=S2~AQIC5wM2LY4Sfczs8Mx-dAGvcQEjDwLzoqjQlExHaZ-*6QHE*AAJTSQACMDIAAlNLABM1MDk3Mjk4NTk4MjY4OTQzODGHY0AAJTMQACMDM*

{"id":"workspace_1565073686024","value":"{\"search\":true,\"nodesImported\":80,\"id\":\"workspace_1565073686024\",\"groupName\":\"alarmsearch:administrator_importedNodes_1565073706867;alarmsearch:administrator_selectedNodes_1565073706867\",\"date\":1566309623332,\"%workspaceName%\":\"ttttteeessstttt*\"}"}

Command Run:
./sqlmap.py -r /home/rename-workspace --headers="User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:25.0) Gecko/20100101 Firefox/25.0"  -vv  --proxy http://localhost:8080 

Variable to be replaced using injection point is
ttttteeessstttt*

**Expected behavior**
The cookie should remain intacted.

**Screenshots**

**Running environment:**
 - sqlmap version [{1.3.7.9#dev}

**Comment by 687766616e** [comment]
`%inject here%`

**Comment by 687766616e** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/Usage#uri-injection-point

**Comment by jeromesheerin** [comment]
Hi

I have tried that. Please see this output:

./sqlmap.py -r rename --headers="User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:25.0) Gecko/20100101 Firefox/25.0"  -vvv  --proxy http://localhost:8080 
        ___
       __H__
 ___ ___["]_____ ___ ___  {1.3.8.15#dev}
|_ -| . [)]     | .'| . |
|___|_  ["]_|_|_|__,|  _|
      |_|V...       |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting @ 16:28:45 /2019-08-20/

[16:28:45] [INFO] parsing HTTP request from 'rename-workspace'
[16:28:45] [DEBUG] not a valid WebScarab log data
[16:28:45] [DEBUG] cleaning up configuration parameters
[16:28:45] [DEBUG] setting the HTTP timeout
[16:28:45] [DEBUG] setting extra HTTP headers
[16:28:45] [DEBUG] setting the HTTP User-Agent header
[16:28:45] [DEBUG] setting the HTTP/SOCKS proxy for all HTTP requests
[16:28:45] [DEBUG] creating HTTP requests opener object
JSON data found in PUT data. Do you want to process it? [Y/n/q] y
[16:28:48] [INFO] testing connection to the target URL
[16:28:48] [TRAFFIC OUT] HTTP request [#1]:
PUT /rest/ui/settings/alarmsearch/workspace HTTP/1.1
Accept-language: en-US,en;q=0.5
Accept-encoding: gzip, deflate
Content-type: application/json; charset=utf-8
X-Requested-With: XMLHttpRequest
Accept: */*
User-agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Host: ieatenm5429-6.athtem.eei.ericsson.se
Referer: https://localhost
Cookie: ssocookie=ssocookie-2; amlbcookie=03; iPlanetDirectoryPro=S2~AQIC5wM2LY4Sfczs8Mx-dAGvcQEjDwLzoqjQlExHaZ-6QHE.AAJTSQACMDIAAlNLABM1MDk3Mjk4NTk4MjY4OTQzODY0AAJTMQACMDM.
X-Tor-Application: alarmsearch
Content-length: 305
Connection: close

{"id":"workspace_1565073686024","value":"{\"search\":true,\"nodesImported\":80,\"id\":\"workspace_1565073686024\",\"groupName\":\"alarmsearch:administrator_importedNodes_1565073706867;alarmsearch:administrator_selectedNodes_1565073706867\",\"date\":1566309623332,\"workspaceName\":\"%ttttteeessstttt%\"}"}



The contents of the rename file was:

PUT /rest/ui/settings/alarmsearch/workspace HTTP/1.1
Host: localhost
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: https://localhost
X-Requested-With: XMLHttpRequest
Content-Type: application/json; charset=utf-8
X-Tor-Application: alarmsearch
Content-Length: 303
Connection: close
Cookie: ssocookie=ssocookie-2; amlbcookie=03; iPlanetDirectoryPro=S2~AQIC5wM2LY4Sfczs8Mx-dAGvcQEjDwLzoqjQlExHaZ-6QHE.*AAJTSQACMDIAAlNLABM1MDk3Mjk4NTk4MjY4OTQzODY0AAJTMQACMDM.*

{"id":"workspace_1565073686024","value":"{\"search\":true,\"nodesImported\":80,\"id\":\"workspace_1565073686024\",\"groupName\":\"alarmsearch:administrator_importedNodes_1565073706867;alarmsearch:administrator_selectedNodes_1565073706867\",\"date\":1566309623332,\"workspaceName\":\"%ttttteeessstttt%\"}"}

**Comment by stamparm** [comment]
1) sqlmap will actually test both POST and cookie because of that same asterisk marker
2) To remove the confusion and "help" sqlmap, please do something like this:

```
$ cat req.txt 
POST / HTTP/1.1
Host: localhost
Cookie: id=1*

{"id": "1", "name": "foobar%inject here%"}

$ python sqlmap.py -r req.txt --batch -v 6 | grep -A 6 'Cookie: id'
Cookie: id=1*
Host: localhost
Content-type: application/json
Content-length: 29
Connection: close

{"id": "1", "name": "foobar"}
--
Cookie: id=1*; PHPSESSID=8417sg2tkdulaql29bg3hjkm22
Host: localhost
Content-type: application/json
Content-length: 29
Connection: close

{"id": "1", "name": "foobar"}
--
Cookie: id=1*; PHPSESSID=8417sg2tkdulaql29bg3hjkm22
Host: localhost
Content-type: application/json
Content-length: 27
Connection: close

{"id": "1", "name": "5925"}
--
Cookie: id=1*; PHPSESSID=8417sg2tkdulaql29bg3hjkm22
Host: localhost
Content-type: application/json
Content-length: 40
Connection: close

{"id": "1", "name": "foobar,(\"'))),)."}
--
Cookie: id=1*; PHPSESSID=8417sg2tkdulaql29bg3hjkm22
Host: localhost
Content-type: application/json
Content-length: 47
Connection: close

{"id": "1", "name": "foobar'eBmYkO<'\">iSlbBb"}
--
....
```

**Comment by jeromesheerin** [comment]
Hi

Thanks for the reply. I ended up using a proxy (Burp) to modify the request header to replace the broken cookie, with the valid cookie. There is an option to modify the request header, after sqlmap has modified it incorrectly. works like a charm. I do think sqlmap needs an improvement so that * does not automatically trigger an injection marker.
