### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by 687766616e** [sqlmapproject/sqlmap#3891]
```
sqlmap previously fingerprinted back-end DBMS as dbms1. However now it has been fingerprinted as dbms2. Please, specify which DBMS should be correct [dbms1 (default)/dbms2]
```
what if i really dont know? can i just.. test both of them? ^^'' (because i dont want to skip it

**Comment by 687766616e** [comment]
```
sqlmap previously fingerprinted back-end DBMS as dbms1. However now it has been fingerprinted as dbms2. Please, specify which DBMS should be correct. if you want to test both of them, pls type 'both '[dbms1/dbms2/[B]oth (default)]
```

**Comment by stamparm** [comment]
1) You'll need to run sqlmap (then) for two times (first time choosing first, next time choosing next)
2) In most cases, you'll have FAR more problems than just plain choosing of a DBMS in similar situations (e.g. false-positives, IPS/WAF blocking certain payloads, etc.) - problems which cause this kind of symptoms

**Comment by 687766616e** [comment]
so... you not gonna do that? `[dbms1/dbms2/[B]oth (default)]` ok.... ^^''
