### ISSUE TITLE
--csrf-token bug?

### ISSUE THREAD

**Issue by 687766616e** [sqlmapproject/sqlmap#3899]
https://regex101.com/r/gqdAfU/1
```
--csrf-token "(\_hiddena\_hiddenq\_session\_id\_v2|XSRF\-TOKEN)" --csrf-url "https://www.hidden.com.us/"

https://www.hidden.com.us/ HTML:
set-cookie: XSRF-TOKEN=hiddenasd; path=/; secure; HttpOnly
set-cookie: _hiddena_hiddenq_session_id_v2=hiddenqwe; domain=www.hidden.com.us; path=/; expires=Thu, 27 Feb 2020 01:41:22 -0000; HttpOnly
```

**Comment by stamparm** [comment]
That same anti-CSRF token has to BE USED somewhere (inside your provided request parameters). sqlmap can't guess where is the exact location for it to be incorporated inside the further requests.

Visual explanation:

![foobar](https://user-images.githubusercontent.com/921555/64170406-54fbbb80-ce50-11e9-9192-f20335a65646.png)
