### ISSUE TITLE
 unable to retrieve the number of columns

### ISSUE THREAD

**Issue by follow-at-cybers** [sqlmapproject/sqlmap#390]
sqlmap success get list of database name and list of table name but failed when retrieve columns and data from database even i use --no-cast and --hex

here's my sqlmap procees
success get the table name from database 'portal'
python.exe sqlmapupdate2\sqlmap.py -u "http://www.test.com/ind/?zqa=9&yu=view&id=696" -o --batch --retries=50 --random-agent --dbms=mysql --thread=3 -D portal --tables

result: http://pastebin.com/raw.php?i=x8E3uCBw

and this is when retrieve columns
http://pastebin.com/raw.php?i=j8RzyF0T

i have tried with --no-cast and --hex but still failed cannot get columns or data from table
is this minor bug or not ? hope i'm not wrong this time :D 
thanks

**Comment by bitcoinboom** [comment]
@follow-at-cybers hello did it work? please help me my telegram number is +6287813116267
