### ISSUE TITLE
about --hpp

### ISSUE THREAD

**Issue by 687766616e** [sqlmapproject/sqlmap#3901]
Is it possible to use feature `--hpp` on other platforms?
![page09_2](https://user-images.githubusercontent.com/20995449/63857909-1b9df880-c9d7-11e9-8e28-3e328c7f2a84.jpg)
![](https://www.owasp.org/images/5/5e/Sqli-HPP.png)

**Comment by 687766616e** [comment]
or use this reaction to determine the server environment (for sites that do not specify a server environment in response ((Google translated

**Comment by 687766616e** [comment]
and also, header name random case: `Content-Disposition` --> `Content-disposition` to bypass some old? waf

**Comment by 687766616e** [comment]
it can`filename` bypass too?

**Comment by stamparm** [comment]
You've posted a image which explains everything. Out of all mainstream platforms, ONLY IIS supports `--hpp`

**Comment by 687766616e** [comment]
oh...
