### ISSUE TITLE
requests (-u bug?

### ISSUE THREAD

**Issue by 687766616e** [sqlmapproject/sqlmap#3903]
can i use something like this: `{start}{end}` or `<test></test>` to let sqlmap know which part you want to test..

```
-u "https://test.us/test2/1---%E5%8D%B0%E5%BA%A6*--test3*-1.html"

...
[TRAFFIC OUT] HTTP request [#275]:
GET /test2/-8289%29%20UNION%20ALL%20SELECT%209347--%20ObQV--test3-1.html HTTP/1.1
...
Referer: https://test.us/test2/1---??????--test3-1.html
...
```

```
-u "https://test.us/test2/1---{start}%E5%8D%B0%E5%BA%A6{end}--{start}test3{end}-1.html"
or
-u "https://test.us/test2/1---{start1}{start2}%E5%8D%B0%E5%BA%A6{end1}--test3-1{end2}.html" for multiple targets
or --param-start "[" --param-end "]"
```

**Comment by 687766616e** [comment]
i tried to use `--prefix` and `--suffix` to do that, but...

**Comment by 687766616e** [comment]
and what if the webpage is using `--param-del="-"` to be their delimiter character?...
do you have any idea to let the webpage dont get wrong? (wait

**Comment by 687766616e** [comment]
and how can i customize the `comment` char? `--` --> `#`

**Comment by stamparm** [comment]
* Sorry, but no (to original question). You are over-complicating things, while sqlmap would not play well in such "i want this to become that" situations
* `and how can i customize the comment char? -- --> #` -> `--suffix='#'`
