### ISSUE TITLE
Getting the Exception on SQLMAP with the NTLM AUthentication.

### ISSUE THREAD

**Issue by KishanReddy85** [sqlmapproject/sqlmap#3907]
I performed the sql Injection through the NTLM Authentication but getting the exception like 
Command line: sqlmap.py -u ********************************************************* --auth-type **** --auth-cred ******************************** --dbs
Technique: None
Back-end DBMS: None
Traceback (most recent call last):
  File "sqlmap.py", line 159, in main
    init()
  File "lib/core/option.py", line 2642, in init
    _setHTTPAuthentication()
  File "lib/core/option.py", line 1273, in _setHTTPAuthentication
    from ntlm import HTTPNtlmAuthHandler

Help me with the issue

**Comment by stamparm** [comment]
You haven't copy-pasted the whole exception message. Please copy paste everything here
