### ISSUE TITLE
what are useful tampers&command lines for DataBase "IBM DB2" ?

### ISSUE THREAD

**Issue by SamirHamoud** [sqlmapproject/sqlmap#3908]
Hello Mr stamparm :
i test on some website and SQLMap fetched the back-ends is IBM DB2 but False Positive
can you tell me what useful commands & tampers might help me solving the problem ?
Thx <3

**Comment by stamparm** [comment]
Sorry, there are no useful commands here. You should assess your target manually to see what is going on. There are no silver bullets here.
