### ISSUE TITLE
Getting the Exception On SQLMAp with NTLM Authentication

### ISSUE THREAD

**Issue by KishanReddy85** [sqlmapproject/sqlmap#3913]
When i use the NTLM Authentication on SQLMAP getting the exception.

C:\sqlmap>sqlmap.py -u http://URL --auth-type NTLM --auth-cred "Domain\Username:Password" --dbs
        ___
       __H__
 ___ ___[.]_____ ___ ___  {1.3.9.1#dev}
|_ -| . [)]     | .'| . |
|___|_  ["]_|_|_|__,|  _|
      |_|V...       |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting @ 15:32:40 /2019-09-05/

[15:32:40] [CRITICAL] unhandled exception occurred in sqlmap/1.3.9.1#dev. It is recommended to retry your run with the latest development version from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'. If the exception persists, please open a new issue at 'https://github.com/sqlmapproject/sqlmap/issues/new' with the following text and any other information required to reproduce the bug. Developers will try to reproduce the bug, fix it accordingly and get back to you
Running version: 1.3.9.1#dev
Python version: 3.7.4
Operating system: Windows Version
Command line: sqlmap.py -u ********************************************************* --auth-type **** --auth-cred ******************************** --dbs
Technique: None
Back-end DBMS: None
Traceback (most recent call last):
  File "sqlmap.py", line 159, in main
    init()
  File "lib/core/option.py", line 2642, in init
    _setHTTPAuthentication()
  File "lib/core/option.py", line 1273, in _setHTTPAuthentication
    from ntlm import HTTPNtlmAuthHandler
  File "/Users/AppData/Local/Programs/Python/Python37/lib/site-packages/python_ntlm-1.1.0-py3.7.egg/ntlm/HTTPNtlmAuthHandler.py", line 110
    except socket.error, err:
                       ^
SyntaxError: invalid syntax

do you want to automatically create a new (anonymized) issue with the unhandled exception information at the official Github repository? [y/N] >

Can you help with the Issue.

**Comment by stamparm** [comment]
A) Python2 version of library (`python_ntlm`) is used inside Python3 environment
B) As I can see on official [pages](https://github.com/mullender/python-ntlm#python-3-support) "`There is work going on to port the library to python 3, you can find it in the python30 directory. (at this time it seems to work as good as the python 2 library)`"

**Comment by KishanReddy85** [comment]
I Have tried with Python 2.7 still i am unable to perform SQL injection with NTLM Authorization 
In my machine NTLM library is there still getting the NTLM library required message . below your reference

C:\Python27>python -m pip install ntlm-auth
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
******Requirement already satisfied: ntlm-auth in c:\python27\lib\site-packages (1.4.0)******

C:\sqlmap>sqlmap.py -u http://URL --auth-type NTLM --auth-cred "Domain\Username:Password" --dbs
        ___
       __H__
 ___ ___[']_____ ___ ___  {1.3.9.1#dev}
|_ -| . [']     | .'| . |
|___|_  [.]_|_|_|__,|  _|
      |_|V...       |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting @ 09:55:28 /2019-09-06/

[09:55:28] [CRITICAL] sqlmap requires Python NTLM third-party library in order to authenticate via NTLM, https://github.com/mullender/python-ntlm

[*] ending @ 09:55:28 /2019-09-06/

**Comment by stamparm** [comment]
When you run `C:\sqlmap>sqlmap.py`, you are using default Python version (I guess in your case it is the Python3). Please, run it with a call to `python.exe` located inside the Python2's `bin` installation

**Comment by KishanReddy85** [comment]
Still it is not working can you explain step by step process for NTLM Authentication.

**Comment by AjCaroline** [comment]
Is there any updated help for this? I downloaded, installed, the ntlm auth lib and sqlmap is still asking for it, could anyone help please? Thank you

**Comment by stamparm** [comment]
@AjCaroline which python version have you tried to use here? `python-ntlm` seems to be under-developed for the Python3.

the best test to see if your current setup (python + python-ntlm) is properly done:

```sh
python   # whichever one you use for calling the sqlmap
>>> from ntlm import HTTPNtlmAuthHandler
```
