### ISSUE TITLE
Choose methof for CSRF token retrieval

### ISSUE THREAD

**Issue by rsheasby** [sqlmapproject/sqlmap#3916]
I've run into an issue with an app I'm testing. In this case, a POST is required to retrieve the CSRF token. However, the CSRF url feature seems to always use GET.

A flag should be added `--csrf-method` which allows choice of HTTP method for the CSRF retrieval.

**Comment by stamparm** [comment]
```
$ python sqlmap.py -hh | grep csrf
    ...
    --csrf-method=CS..  HTTP method to use during anti-CSRF token page visit
    ...
```
