### ISSUE TITLE
How to avoid being blocked by the server?

### ISSUE THREAD

**Issue by pengyu** [sqlmapproject/sqlmap#3922]
I see this warning when I run `sqlmap -u some_url`. How to avoid the blocking from the website? Thanks.

```
there is a possibility that the target (or WAF/IPS) is dropping 'suspicious' requests
```

**Comment by stamparm** [comment]
There is no general reply to this. You should manually assess the target and see what is being blocked and what is not. Then, you could choose a proper tamper script(s) and try to re-run the sqlmap. If it still fails you should manually do the whole assessment. C'est la vie
