### ISSUE TITLE
Suggest web server document root in combination with --file-read

### ISSUE THREAD

**Issue by Techbrunch** [sqlmapproject/sqlmap#3928]
**Is your feature request related to a problem? Please describe.**

When it has been identified that the `FILE` privilege is available you often want to start reading files of the web application but you don't always know the web server document root.

If you don't know it you will need to bruteforce it which requires running sqlmap for each potential root path.

```
python sqlmap.py -r req -p id --technique U --file-read=/var/www/index.php
python sqlmap.py -r req -p id --technique U --file-read=/var/www/html/index.php
python sqlmap.py -r req -p id --technique U --file-read=/var/www/htdocs/index.php
...
```

**Describe the solution you'd like**

It would be nice to have an option for some kind of path prefix when trying to read file similar to when trying to run `--os-shell`.

```
do you want sqlmap to further try to provoke the full path disclosure? [Y/n]
[16:57:59] [WARNING] unable to automatically retrieve the web server document root
what do you want to use for writable directory?
[1] common location(s) ('/var/www/, /var/www/html, /var/www/htdocs, /usr/local/apache2/htdocs, /usr/local/www/data, /var/apache2/htdocs, /var/www/nginx-default, /srv/www/htdocs') (default)
[2] custom location(s)
[3] custom directory list file
[4] brute force search
```

Another solution would be to have an option to find the web root. You could pass it the path of a known file of the web application. sqlmap would then try to read the file by bruteforcing the web server root.

**Comment by stamparm** [comment]
Just a quick check. Have you tried `--common-files`? It should cover majority of your "needs"

**Comment by Techbrunch** [comment]
I wasn't aware of this option, I usually check the wiki when looking for options since I find it easier to read.

This sounds like a good way to solve my problem except that in this case the web root used the html suffix (`/var/html/www`) so it wasn't found.

I think adding some words would be enough to solve this issue:

```
/srv/www/htdocs/index.php
/srv/www/index.php
/usr/local/apache/index.php
/usr/local/apache2/htdocs/index.php
/usr/local/apache2/index.php
/usr/local/httpd/index.php
/usr/local/www/apache22/index.php
/usr/local/www/apache24/index.php
/usr/local/www/data/index.php
/var/apache2/htdocs/index.php
/var/www/htdocs/index.php
/var/www/html/index.php
/var/www/index.php
/var/www/nginx-default/index.php
```

To make it even better it would be nice to have the same `brute force search`capability as when trying to upload a webshell to find the webroot.

**Comment by stamparm** [comment]
With the latest commit/revision added missing entries from the list you've provided. For now I would not add a brute-force capability here as it should be a dummy check/read capability (i.e. not fan of over-complicating things if there is no need to do it)
