### ISSUE TITLE
Reading login injections from file?

### ISSUE THREAD

**Issue by haroonawanofficial** [sqlmapproject/sqlmap#3930]
I had a issue, where I wanted to use sql login injection from file so sqlmap could obtain more results

Example url:
sqlmap -u "https://www.example.com/login.php" --data="user=&pass=" --dbs

Attack Example:
sqlmap -u "https://www.example.com/login.php" --data='user= < myfilehere'  --dbs

Let me know if there is some sort of feature or workaround for this.

**Comment by 687766616e** [comment]
u want this? `-r`?

**Comment by haroonawanofficial** [comment]
No, this did not work for me. As I have this file which contain list for sql login injections. Now I want load those into parameter via sqlmap.

**Comment by stamparm** [comment]
A) What is `list for sql loging injections`?
B) @687766616e pointed you in a right direction. In your kind of cases you should use `-r` where the used request file should have a valid-formatted HTTP request. Though, there is nothing like `< myfilehere` thingy inside, so I am waiting for your reply of A)

**Comment by haroonawanofficial** [comment]
A) FIle: SQLLogin contains, list for SQL Injections for usernames and passwords :
or true--
" or true--
' or true--
") or true--
') or true--

B) Show me a working example. How SQLMAP will use this file for my test case.

C) I am expert in perl, so when I use make my own software/ or bash scripts, I tend to redirect file into my software, that is where < THINGY is in LINUX.

I need a working example for B in my case. Thank you for your time.

**Comment by haroonawanofficial** [comment]
Bash script did job, If Injected data is successful in *output.txt file results then we can use that request with SQLMAP. Make query.txt for sql login injections.
