### ISSUE TITLE
The CSRF feature does not seem to correctly replace the token

### ISSUE THREAD

**Issue by zi0Black** [sqlmapproject/sqlmap#3936]
**Describe the bug**
I don't know if I'm doing something wrong or I incurred in a BUG.

**To Reproduce**
sqlmap -u http://... --cookie "*ID=7A1008BD428....." --data "..." --csrf-token "rid" --csrf-url "http://127.0.0.1:5656" --method POST -v 7

**Screenshots**
![](https://i.imgur.com/GtQlNqR.png)

**Running environment:**
 - sqlmap/1.3.9#stable

**Comment by stamparm** [comment]
Unreproducible. I am attaching results from an example run emulating your "environment":

![foobar](https://user-images.githubusercontent.com/921555/65392652-4893c000-dd77-11e9-8630-9f4419819ffd.png)

Command line used was: `python sqlmap.py -u debiandev/sqlmap/mysql/post_int.php --data="id=1&rid=1" --csrf-token=rid --csrf-url="http://debiandev/sqlmap/mysql/post_csrf.php" -v 6`
