### ISSUE TITLE
Strengthen tamper xforwardedfor

### ISSUE THREAD

**Issue by 687766616e** [sqlmapproject/sqlmap#3940]
cloudflare:
`CF-Connecting-IP`
`True-Client-IP`
`CF-IPCountry`

google data saver:
`Via: 1.1 Chrome-Compression-Proxy`

**Comment by stamparm** [comment]
Note:

https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-

"`There's absolutely no difference between True-Client-IP and Cf-Connecting-IP besides the name of the header`"

**Comment by 687766616e** [comment]
NICE~

**Comment by 687766616e** [comment]
or... separate them? googleproxy.py and cloudflare.py ?? (sorry~😅

**Comment by 687766616e** [comment]
> or... separate them? googleproxy.py and cloudflare.py ?? (sorry~ @stamparm

if you don't want to separate them, maybe you should randomize them
sometimes cloudflare header sometimes google proxy header😅

**Comment by 687766616e** [comment]
@stamparm
