### ISSUE TITLE
custom payload file

### ISSUE THREAD

**Issue by shaolinint** [sqlmapproject/sqlmap#3941]
Hi Awesome Developer,

Kindly, is there anyway to call custom.xml payload file? If not, would be great to include such features.

My idea is that I wanted to build a list of custom payloads that only bypass authentication with all available tamper scripts.

Thank you for the great tools! You guys awesome!

**Comment by 687766616e** [comment]
`--sql-file`?

**Comment by stamparm** [comment]
It goes like this:

A) Such feature would introduce more confusion than benefits. 99% of users would use it wrongly, expecting "BETTER" results, while getting/resulting with pure junk
B) You can always TRY&trade; to change existing payloads inside `data/xml/payloads/*.xml`. sqlmap will gladly process even such trials

**Comment by deeydos** [comment]
is there any way to specify sqlmap to only test for time based injections using only this payload file:
/data/xml/payloads/time_blind.xml

i hope you will help

**Comment by stamparm** [comment]
@deeydos just use `--technique=T`. this will force the usage of ONLY time-based injections

**Comment by deeydos** [comment]
Thanks
