### ISSUE TITLE
about blank response

### ISSUE THREAD

**Issue by 687766616e** [sqlmapproject/sqlmap#3945]
wait

**Comment by 687766616e** [comment]
(google translated... sorry~😅

**Comment by stamparm** [comment]
I would need examples for both `will respond blank (nothing, 0)` and `when u asking a nonexistent data`. I really don't know what's the context here, what command(s) have you run in the first place and what are those `nonexistent data`

**Comment by 687766616e** [comment]
if the token is right, it won't resonpon nothing

**Comment by 687766616e** [comment]
> ```
> $ curl -v "http://192.168.1.1:80/login?{token}"
> *   Trying 192.168.1.1:80...
> * TCP_NODELAY set
> * Connected to 192.168.1.1 (192.168.1.1) port 80 (#0)
> > GET /login?{token} HTTP/1.1
> > Host: 192.168.1.1:80
> > User-Agent: curl/7.66.0
> > Accept: */*
> >
> * Empty reply from server
> * Connection #0 to host 192.168.1.1 left intact
> curl: (52) Empty reply from server
> $
> ```

if you need more details, just tell me~

**Comment by stamparm** [comment]
I would need more details. You've also deleted the original content of this issue (which has been created 18 days ago)

**Comment by 687766616e** [comment]
> I would need more details. You've also deleted the original content of this issue (which has been created 18 days ago)

this? 😅

> some webpage will respond blank (nothing, 0) when u asking a nonexistent data. and then sqlmap will continue to output very ugly thing
how can I ignore it? --ignore-blank?

**Comment by 687766616e** [comment]
i just edit it, I didn't delete it this time.

**Comment by 687766616e** [comment]
...😅😅

**Comment by hahahahahahahahahahahahahahahah** [comment]
if you dont want to do it, just close it (this time only~... dont close the others.....
