### ISSUE TITLE
python: can't open file 'sqlmap.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Darrow8** [sqlmapproject/sqlmap#3946]
Just installed sqlmap using both github and your website. When I ran 

`$ python sqlmap.py -h`

This errror came up: `python: can't open file 'sqlmap.py': [Errno 2] No such file or directory`

**Comment by stamparm** [comment]
You are running `python` from a random directory. Please, position your current directory into the `sqlmap` directory where `sqlmap.py` exists and then rerun your command.

**Comment by AkibButt** [comment]
AWDWADAWd

**Comment by richie4herdoonies** [comment]
so basically its the same shi. but i loooked at the directory and it contains the file this confused me... any pointers ??

**Comment by jamespio** [comment]
just remove **python** sqlmap.py -h

run `sqlmap.py -h`
