### ISSUE TITLE
use sql errors to get boolean-based blind sqli where only time-based works now

### ISSUE THREAD

**Issue by benlbroussard** [sqlmapproject/sqlmap#3963]
**Is your feature request related to a problem? Please describe.**
I've found that I can sometimes differentiate sql error vs no sql error, but not one vs zero results from a query. I've manually used this go from time-based to boolean-based blind sqli recently, but was unable to find any way to get sqlmap to play nice (tried some hefty prefix/suffix magic, but no luck). Obviously boolean is faster than time-based and can be threaded, and that's why I want this.

**Describe the solution you'd like**
It boils down to finding a sql error that will only be raised on an else case of a conditional. What I used against mysql recently was:
`' or 'a'=(select case when 
(select count(table_name) from information_schema.tables) >= 176 then 1 
else (select table_name from information_schema.tables) end)#`

The result of a subquery in a "select case when" statement must return only 1 row or a sql error is raised. I'm using the else condition to return all records in information_schema.tables, which I know will always be more than 1 row, so the else will always trigger the error.

The conditional where count(table_name) is compared to 176 was a way to binary search how many tables there were. That could be modified to compare a substring of table_name (with limiting to get only 1 row, otherwise we get the sql error for too many rows) with a regex or LIKE mask and binary search the ascii character space, character-by-character (like sqlmap usually does the blind sqli).

**Describe alternatives you've considered**
I haven't looked at oracle, mssql, db2, etc. related to this. It's perhaps a bit much, but being able to give unique strings in the results for true/false cases might be useful.

**Additional context**
My responses were either 403 or 500 HTTP codes. It was unclear to me how this was affecting the running of sqlmap, and how the --ignore-code=500 was affecting the results.

**Comment by stamparm** [comment]
So you really do believe that sqlmap is not trying to do this? This is 101 of its internal working(s).

Also, have you tried to run with `--level=5 --risk=3`. If the answer is yes, I believe that you have/had some other problems. Please take a deep look into the https://github.com/sqlmapproject/sqlmap/blob/master/data/xml/payloads/error_based.xml, especially the `<payload>`s

**Comment by benlbroussard** [comment]
When I look at the error-based tests, I see:
        <response>
            <grep>[DELIMITER_START](?P&lt;result&gt;.*?)[DELIMITER_STOP]</grep>
        </response>

I could easily be wrong, but it looks like it's grepping for a string to determine success/failure cases. I would expect that for error-based, but I'm really trying to do boolean-based blind, but my true condition returns a 403 and my false condition returns a 500. Is error-based just pulling data into a sql error message and grepping for that data (like I assumed), or will it key off of HTTP status codes?

**Comment by stamparm** [comment]
Ok. Those are just greps in `error-based` SQLi, you are right. My bad.

Take a look into these: https://github.com/sqlmapproject/sqlmap/blob/master/data/xml/payloads/boolean_blind.xml

Just a couple of notable examples (related to your case(s)):

1) `OR [RANDNUM]=(SELECT (CASE WHEN ([INFERENCE]) THEN [RANDNUM] ELSE (SELECT [RANDNUM1] UNION SELECT [RANDNUM2]) END))` - in case of TRUE it won't provoke error, in case of FALSE it provoke multiple-row comparison error
2) `OR (SELECT (CASE WHEN ([INFERENCE]) THEN NULL ELSE CAST('[RANDSTR]' AS NUMERIC) END)) IS NULL` - PgSQL one where random string is being casted to numeric in case of a FALSE result
3) `(SELECT (CASE WHEN ([INFERENCE]) THEN [ORIGVALUE] ELSE 1/(SELECT 0) END))` - again PgSQL causing division by zero in case of FALSE result
4) `(SELECT (CASE WHEN ([INFERENCE]) THEN [RANDNUM] ELSE [RANDNUM]*(SELECT [RANDNUM] UNION ALL SELECT [RANDNUM1]) END))` - MsSQL one causing error by multiplication of multiple rows in case of a FALSE result
5) `(SELECT (CASE WHEN ([INFERENCE]) THEN [RANDNUM] ELSE CAST(1 AS INT)/(SELECT 0 FROM DUAL) END) FROM DUAL)` - Oracle one causing division by zero in case of FALSE result
...

There are lots and lots of similar payloads with different boundaries/prefixes/suffixes
