### ISSUE TITLE
Add option --ignore-warnings

### ISSUE THREAD

**Issue by caperoni** [sqlmapproject/sqlmap#3964]
Could you please add an option --ignore-warnings to ignore all critical warnings like "Acces denied", "Connection refused", and all others.

**Comment by stamparm** [comment]
You mean generally HTTP codes or? What causes the trouble in your case?

Have you tried: `--ignore-code=IG..  Ignore (problematic) HTTP error code (e.g. 401)`?

Thing is that currently I am not sure whether you are referring to the HTTP error codes/replies or general connection problems/issues

**Comment by caperoni** [comment]
Yes, I mean generally ignore all http warnings.

--ignore-code=401,505, and others I already love this, but I wanna something globally, to pass over all kind of http warnings.

**Comment by stamparm** [comment]
With the latest revision you can use `--ignore-code=*` to wildcard every HTTP (error) code
