### ISSUE TITLE
Set-Cookie header not respected when performing injections

### ISSUE THREAD

**Issue by mariuszskon** [sqlmapproject/sqlmap#3968]
**Describe the bug**
sqlmap does not seem to actually listen to `Set-Cookie` headers when testing various SQL injections (although it does when running heuristics). This contradicts the wiki:

> If at any time during the communication, the web application responds with Set-Cookie headers, sqlmap will automatically use its value in all further HTTP requests as the Cookie header.

**To Reproduce**
1. Run `sqlmap -v 6 -u $TARGET_WHICH_SETS_COOKIE` 
2. See that sqlmap does not send `Cookie` header and server repeatedly sends `Set-Cookie`

**Expected behavior**
That sqlmap saves the cookies given in `Set-Cookie` headers and sends them in subsequent injection requests.

**Screenshots**

**Running environment:**
 - sqlmap version [e.g. 1.3.9#stable, 1.3.6.10#dev]
 - Installation method [e.g. apt, git]
 - Operating system: [e.g. Kali Linux, Microsoft Windows 10]
 - Python version [e.g. 2.7.16, 3.7.2]

**Target details:**
 - DBMS [e.g. MySQL]
 - PHP

**Comment by stamparm** [comment]
It goes like this. Up until now, `Set-Cookie` has been dropped in test phase. Sole purpose was to prevent "marking" of a bad session from the application and/or middleware (e.g. IPS/WAF) OR to just ignore potentially stalled sessions (e.g. OR payloads causing trouble).

Anyway, combination of this Issue request with the fact that applications which are vulnerable and behind the Cloudflare, while not being protected by the Cloudflare in the first place, resulted with the latest commit/revision when now you'll be asked whether you want to accept server `Set-cookie` - in case that you haven't declared it yourself.

**Comment by mariuszskon** [comment]
Awesome, cheers!
