### ISSUE TITLE
Missing enclosing for table with reserved name (MSSQL)

### ISSUE THREAD

**Issue by ohpe** [sqlmapproject/sqlmap#397]
I was testing a vulnerable web application based on MS SQL Server when I got this warning:

```
[WARNING] unable to retrieve the number of entries for table 'user' in database 'ecommerce_books'
```

So, I've tried to increase the verbosity level to 6 in order to see where the response failed, and I got this body result:

```
[Microsoft][SQL Server Native Client 10.0][SQL Server]Incorrect syntax near the keyword 'user'.
```

The request was:

```
GET /getBookInfo.php?id=1%20IF%28UNICODE%28SUBSTRING%28%28SELECT%20I29%20FROM%20ecommerce_books.dbo.user%29%2C1%2C1%29%29%3E1%29%20WAITFOR%20DELAY%20%270%3A0%3A5%27--
```

I’ve reproduced the request via browser, obviously, I’ve received the same error. I supposed that the problem was related to a missing escaping for the table name “user”.
In fact, by surrounding the table name by square brackets:

```
GET /getBookInfo.php?id=1%20IF%28UNICODE%28SUBSTRING%28%28SELECT%20I29%20FROM%20ecommerce_books.dbo.[user]%29%2C1%2C1%29%29%3E1%29%20WAITFOR%20DELAY%20%270%3A0%3A5%27--
```

the payload works.

So, regardless of whether it’s a good practice to don’t use reserved words as table name, if someone uses a reserved word like user as a table name your tool doesn't work properly.

**Comment by onlygilang** [comment]
you resolve my problem by using this "[]" ,. great job,.
