### ISSUE TITLE
How to inject multiple repeat parameters at once

### ISSUE THREAD

**Issue by crud-boy** [sqlmapproject/sqlmap#3975]
`sqlmap -u "www.example.com" --data="problem=1&answer=test&new_password=xxx&repeat_password=xxx"`

How to combine `new_password=xxx&repeat_password=xxx` into one injection
For example, add a parameter  `--param-group="problem,answer,new_password&repeat_password"`

Divided into 3 tests, new_password and repeat_password are combined into one test, their values are the same, eg:

New_password=xxx' or '1'='1&repeat_password=xxx' or '1'='1

**Comment by 687766616e** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/Usage#evaluate-custom-python-code-during-each-request

**Comment by stamparm** [comment]
Try with `--eval="repeat_password=new_password"`
