### ISSUE TITLE
Crawl and Connectivity issue with python3

### ISSUE THREAD

**Issue by josephmiller2000** [sqlmapproject/sqlmap#3982]
**Describe the bug**

**To Reproduce**
1. Run 'python3 sqlmap.py >>URL and usage codes'
2. See error >> unable to connect to URL

**Expected behavior**
It should connect and start checking for the SQL injection right? But it does not.

But it works fine with python 2

**Screenshots**
![Snap_Shot_00255](https://user-images.githubusercontent.com/24210340/67435043-f5788b80-f608-11e9-976f-3b13848fd583.png)

**Running environment:**
 - sqlmap version>> Latest Version >> 1.3.10.22#dev
 - Installation method [e.g. git]
 - Operating system: Linux UBUNTU 18 server version.
 - Python version >> 3.6.8 

**Target details:**
 - DBMS  >> MYSQL
 - SQLi techniques found by sqlmap [e.g. error-based and boolean-based blind]
 - WAF/IPS [if any]
 - Relevant console output [if any]
 - Exception traceback [if any]

**Comment by stamparm** [comment]
![1](https://user-images.githubusercontent.com/921555/67469134-0e566080-f64c-11e9-8e8a-c147655af16b.png)

**Comment by josephmiller2000** [comment]
You have used >> python3.7

But i have reported by using >> Python version >> 3.6.8

**Comment by stamparm** [comment]
I am attaching the run with 3.5 (this is my last message to this "Issue"):

![2](https://user-images.githubusercontent.com/921555/67481697-a52e1780-f662-11e9-9c55-385016a40d0d.png)
