### ISSUE TITLE
Cracking password 

### ISSUE THREAD

**Issue by toptuto** [sqlmapproject/sqlmap#3987]
Hello,
How can I use Hashcat , John the ripper or anything else to crack the hash password of the column that I just get from Sqlmap which Sqlmap can't crack ? Thanks

**Comment by stamparm** [comment]
1) You'll get a dump of password hashes into the temporary location (e.g. `do you want to store hashes to a temporary file for eventual further processing with other tools [y/N]` <- press `Y` here)
2) You have to run john/hashcat with proper options/switches/dictionaries to perform cracking on those hashes (e.g. if MD5 `hashcat -m 0 /tmp/sqlmaphashes-uo8mieng.txt /usr/share/wordlists/rockyou.txt`)

**Comment by toptuto** [comment]
the hash is 4111111111111111 , but when I checked hash-identifier and it not found

**Comment by stamparm** [comment]
@toptuto `4111111111111111` does look like a valid "hash" for any algorithm whatsoever
