### ISSUE TITLE
how to solve  80040e14 aNd  800a0bb9' | MSSQL |

### ISSUE THREAD

**Issue by iqmtgar** [sqlmapproject/sqlmap#3990]
hi every one
how to attack this error
Microsoft OLE DB Provider for SQL Server error '80040e14'
AND
ADODB.Recordset error '800a0bb9' 
i try other options But there is no solution
thx ^_^

**Comment by 687766616e** [comment]
google it? ^_^"

**Comment by stamparm** [comment]
`ADODB.Recordset error '800a0bb9' : Arguments are of the wrong type` <- this basically means, if sqlmap hasn't found the SQLi, that it isn't vulnerable in the first place. For example, if application expects explicit integer value, while you provide a SQLi payload, it will fail in any case of non-integer
