### ISSUE TITLE
Cracking password

### ISSUE THREAD

**Issue by toptuto** [sqlmapproject/sqlmap#3991]
Hello , after I dumped data from sqlmap that included Email and password in csv file , but the password was hash , and then I used hash-identifier , it told me that md5(mid) or mySQL , how could I crack these password directly in this file ? Thanks

**Comment by stamparm** [comment]
As others said, try to google for some of those hashes. Also, if sqlmap didn't crack any of those, there is a possibility that password(s) are hard to crack

**Comment by toptuto** [comment]
I used hashcat but it's still the same
