### ISSUE TITLE
-X with wildcard

### ISSUE THREAD

**Issue by thistehneisen** [sqlmapproject/sqlmap#3993]
**Is your feature request related to a problem? Please describe.**
Allow wildcards for exclude parameter, for example -X prefix_*

**Describe the solution you'd like**
Nothing from tables with prefix_* or *_suffix should be dumped

**Comment by stamparm** [comment]
Done. Only thing to use it is that at least character `*` or `+` has to be inside the value provided for `-X` (e.g. `-X prefix_.*` <- Note: it has to be a valid regular expression - not wildcard)
