### ISSUE TITLE
--base64 (and other function) can support CryptoJS

### ISSUE THREAD

**Issue by 687766616e** [sqlmapproject/sqlmap#3995]
if I have the key, iv and the others, how to decrypt the encrypted thing?... (don't tell me --eval... t.t

**Comment by stamparm** [comment]
Well, `--eval` is the only way 😂

I need some more info so I could help you here. Like algorithm, example of value, key and IV?

**Comment by stamparm** [comment]
Case provided by user was too specific/complex and the sole support for it inside the sqlmap wouldn't make any sense. It is far easier to manually assess the target than to tune the sqlmap (like in this case)
