### ISSUE TITLE
false positive sqlmap really there is vul yes or no ?

### ISSUE THREAD

**Issue by hackersden09** [sqlmapproject/sqlmap#4011]
WARNING: 16:56:25 - POST parameter 'UID' does not appear to be dynamic
WARNING: 16:56:27 - heuristic (basic) test shows that POST parameter 'UID' might not be injectable
INFO: 16:56:28 - testing for SQL injection on POST parameter 'UID'
INFO: 16:56:28 - testing 'AND boolean-based blind - WHERE or HAVING clause'
INFO: 16:58:38 - testing 'OR boolean-based blind - WHERE or HAVING clause'
INFO: 17:00:29 - testing 'OR boolean-based blind - WHERE or HAVING clause (NOT)'
INFO: 17:00:39 - POST parameter 'UID' appears to be 'OR boolean-based blind - WHERE or HAVING clause (NOT)' injectable (with --code=200)
INFO: 17:00:55 - testing 'MySQL >= 5.5 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (BIGINT UNSIGNED)'
INFO: 17:00:57 - testing 'MySQL >= 5.5 OR error-based - WHERE or HAVING clause (BIGINT UNSIGNED)'
INFO: 17:00:58 - testing 'MySQL >= 5.5 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (EXP)'
INFO: 17:00:59 - testing 'MySQL >= 5.5 OR error-based - WHERE or HAVING clause (EXP)'
INFO: 17:01:01 - testing 'MySQL >= 5.7.8 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (JSON_KEYS)'
INFO: 17:01:02 - testing 'MySQL >= 5.7.8 OR error-based - WHERE or HAVING clause (JSON_KEYS)'
INFO: 17:01:04 - testing 'MySQL >= 5.0 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (FLOOR)'
INFO: 17:01:05 - testing 'MySQL >= 5.0 OR error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (FLOOR)'
INFO: 17:01:06 - testing 'MySQL >= 5.1 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (EXTRACTVALUE)'
INFO: 17:01:08 - testing 'MySQL >= 5.1 OR error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (EXTRACTVALUE)'
INFO: 17:01:09 - testing 'MySQL >= 5.1 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (UPDATEXML)'
INFO: 17:01:10 - testing 'MySQL >= 5.1 OR error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (UPDATEXML)'
INFO: 17:01:12 - testing 'MySQL >= 4.1 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (FLOOR)'
INFO: 17:01:13 - testing 'MySQL >= 4.1 OR error-based - WHERE or HAVING clause (FLOOR)'
INFO: 17:01:14 - testing 'MySQL OR error-based - WHERE or HAVING clause (FLOOR)'
INFO: 17:01:16 - testing 'PostgreSQL AND error-based - WHERE or HAVING clause'
INFO: 17:01:17 - testing 'PostgreSQL OR error-based - WHERE or HAVING clause'
INFO: 17:01:19 - testing 'Microsoft SQL Server/Sybase AND error-based - WHERE or HAVING clause (IN)'
INFO: 17:01:20 - testing 'Microsoft SQL Server/Sybase OR error-based - WHERE or HAVING clause (IN)'
INFO: 17:01:21 - testing 'Microsoft SQL Server/Sybase AND error-based - WHERE or HAVING clause (CONVERT)'
INFO: 17:01:23 - testing 'Microsoft SQL Server/Sybase OR error-based - WHERE or HAVING clause (CONVERT)'
INFO: 17:01:24 - testing 'Microsoft SQL Server/Sybase AND error-based - WHERE or HAVING clause (CONCAT)'
INFO: 17:01:25 - testing 'Microsoft SQL Server/Sybase OR error-based - WHERE or HAVING clause (CONCAT)'
INFO: 17:01:27 - testing 'Oracle AND error-based - WHERE or HAVING clause (XMLType)'
INFO: 17:01:28 - testing 'Oracle OR error-based - WHERE or HAVING clause (XMLType)'
INFO: 17:01:30 - testing 'Oracle AND error-based - WHERE or HAVING clause (UTL_INADDR.GET_HOST_ADDRESS)'
INFO: 17:01:31 - testing 'Oracle OR error-based - WHERE or HAVING clause (UTL_INADDR.GET_HOST_ADDRESS)'
INFO: 17:01:32 - testing 'Oracle AND error-based - WHERE or HAVING clause (CTXSYS.DRITHSX.SN)'
INFO: 17:01:34 - testing 'Oracle OR error-based - WHERE or HAVING clause (CTXSYS.DRITHSX.SN)'
INFO: 17:01:35 - testing 'Oracle AND error-based - WHERE or HAVING clause (DBMS_UTILITY.SQLID_TO_SQLHASH)'
INFO: 17:01:36 - testing 'Oracle OR error-based - WHERE or HAVING clause (DBMS_UTILITY.SQLID_TO_SQLHASH)'
INFO: 17:01:38 - testing 'Firebird AND error-based - WHERE or HAVING clause'
INFO: 17:01:39 - testing 'Firebird OR error-based - WHERE or HAVING clause'
INFO: 17:01:40 - testing 'MySQL >= 5.1 error-based - PROCEDURE ANALYSE (EXTRACTVALUE)'
INFO: 17:01:42 - testing 'MySQL >= 5.5 error-based - Parameter replace (BIGINT UNSIGNED)'
INFO: 17:01:42 - testing 'MySQL >= 5.5 error-based - Parameter replace (EXP)'
INFO: 17:01:42 - testing 'MySQL >= 5.7.8 error-based - Parameter replace (JSON_KEYS)'
INFO: 17:01:42 - testing 'MySQL >= 5.0 error-based - Parameter replace (FLOOR)'
INFO: 17:01:42 - testing 'MySQL >= 5.1 error-based - Parameter replace (UPDATEXML)'
INFO: 17:01:42 - testing 'MySQL >= 5.1 error-based - Parameter replace (EXTRACTVALUE)'
INFO: 17:01:42 - testing 'PostgreSQL error-based - Parameter replace'
INFO: 17:01:42 - testing 'PostgreSQL error-based - Parameter replace (GENERATE_SERIES)'
INFO: 17:01:43 - testing 'Microsoft SQL Server/Sybase error-based - Parameter replace'
INFO: 17:01:43 - testing 'Microsoft SQL Server/Sybase error-based - Parameter replace (integer column)'
INFO: 17:01:43 - testing 'Oracle error-based - Parameter replace'
INFO: 17:01:43 - testing 'Firebird error-based - Parameter replace'
INFO: 17:01:43 - testing 'MySQL inline queries'
INFO: 17:01:44 - testing 'PostgreSQL inline queries'
INFO: 17:01:46 - testing 'Microsoft SQL Server/Sybase inline queries'
INFO: 17:01:47 - testing 'Oracle inline queries'
INFO: 17:01:48 - testing 'SQLite inline queries'
INFO: 17:01:50 - testing 'Firebird inline queries'
INFO: 17:01:51 - testing 'MySQL >= 5.0.12 stacked queries (comment)'
INFO: 17:01:52 - testing 'MySQL >= 5.0.12 stacked queries'
INFO: 17:01:54 - testing 'MySQL >= 5.0.12 stacked queries (query SLEEP - comment)'
INFO: 17:01:55 - testing 'MySQL >= 5.0.12 stacked queries (query SLEEP)'
INFO: 17:01:57 - testing 'MySQL < 5.0.12 stacked queries (heavy query - comment)'
INFO: 17:01:58 - testing 'MySQL < 5.0.12 stacked queries (heavy query)'
INFO: 17:01:59 - testing 'PostgreSQL > 8.1 stacked queries (comment)'
INFO: 17:02:01 - testing 'PostgreSQL > 8.1 stacked queries'
INFO: 17:02:02 - testing 'PostgreSQL stacked queries (heavy query - comment)'
INFO: 17:02:04 - testing 'PostgreSQL stacked queries (heavy query)'
INFO: 17:02:05 - testing 'PostgreSQL < 8.2 stacked queries (Glibc - comment)'
INFO: 17:02:07 - testing 'PostgreSQL < 8.2 stacked queries (Glibc)'
INFO: 17:02:08 - testing 'Microsoft SQL Server/Sybase stacked queries (comment)'
INFO: 17:02:09 - testing 'Microsoft SQL Server/Sybase stacked queries (DECLARE - comment)'
INFO: 17:02:11 - testing 'Microsoft SQL Server/Sybase stacked queries'
INFO: 17:02:12 - testing 'Microsoft SQL Server/Sybase stacked queries (DECLARE)'
INFO: 17:02:14 - testing 'Oracle stacked queries (DBMS_PIPE.RECEIVE_MESSAGE - comment)'
INFO: 17:02:15 - testing 'Oracle stacked queries (DBMS_PIPE.RECEIVE_MESSAGE)'
INFO: 17:02:17 - testing 'Oracle stacked queries (heavy query - comment)'
INFO: 17:02:18 - testing 'Oracle stacked queries (heavy query)'
INFO: 17:02:19 - testing 'Oracle stacked queries (DBMS_LOCK.SLEEP - comment)'
INFO: 17:02:21 - testing 'Oracle stacked queries (DBMS_LOCK.SLEEP)'
INFO: 17:02:22 - testing 'Oracle stacked queries (USER_LOCK.SLEEP - comment)'
INFO: 17:02:22 - testing 'Oracle stacked queries (USER_LOCK.SLEEP)'
INFO: 17:02:22 - testing 'IBM DB2 stacked queries (heavy query - comment)'
INFO: 17:02:24 - testing 'IBM DB2 stacked queries (heavy query)'
INFO: 17:02:25 - testing 'SQLite > 2.0 stacked queries (heavy query - comment)'
INFO: 17:02:26 - testing 'SQLite > 2.0 stacked queries (heavy query)'
INFO: 17:02:28 - testing 'Firebird stacked queries (heavy query - comment)'
INFO: 17:02:29 - testing 'Firebird stacked queries (heavy query)'
INFO: 17:02:31 - testing 'SAP MaxDB stacked queries (heavy query - comment)'
INFO: 17:02:32 - testing 'SAP MaxDB stacked queries (heavy query)'
INFO: 17:02:34 - testing 'HSQLDB >= 1.7.2 stacked queries (heavy query - comment)'
INFO: 17:02:35 - testing 'HSQLDB >= 1.7.2 stacked queries (heavy query)'
INFO: 17:02:36 - testing 'HSQLDB >= 2.0 stacked queries (heavy query - comment)'
INFO: 17:02:38 - testing 'HSQLDB >= 2.0 stacked queries (heavy query)'
INFO: 17:02:39 - testing 'MySQL >= 5.0.12 AND time-based blind (query SLEEP)'
INFO: 17:02:41 - testing 'MySQL >= 5.0.12 OR time-based blind (query SLEEP)'
INFO: 17:02:42 - testing 'MySQL >= 5.0.12 AND time-based blind (SLEEP)'
INFO: 17:02:43 - testing 'MySQL >= 5.0.12 OR time-based blind (SLEEP)'
INFO: 17:02:45 - testing 'MySQL >= 5.0.12 AND time-based blind (SLEEP - comment)'
INFO: 17:02:46 - testing 'MySQL >= 5.0.12 OR time-based blind (SLEEP - comment)'
INFO: 17:02:48 - testing 'MySQL >= 5.0.12 AND time-based blind (query SLEEP - comment)'
INFO: 17:02:49 - testing 'MySQL >= 5.0.12 OR time-based blind (query SLEEP - comment)'
INFO: 17:02:50 - testing 'MySQL < 5.0.12 AND time-based blind (heavy query)'
INFO: 17:02:52 - testing 'MySQL < 5.0.12 OR time-based blind (heavy query)'
INFO: 17:02:53 - testing 'MySQL < 5.0.12 AND time-based blind (heavy query - comment)'
INFO: 17:02:55 - testing 'MySQL < 5.0.12 OR time-based blind (heavy query - comment)'
INFO: 17:02:56 - testing 'MySQL >= 5.0.12 RLIKE time-based blind'
INFO: 17:02:57 - testing 'MySQL >= 5.0.12 RLIKE time-based blind (comment)'
INFO: 17:02:59 - testing 'MySQL >= 5.0.12 RLIKE time-based blind (query SLEEP)'
INFO: 17:03:00 - testing 'MySQL >= 5.0.12 RLIKE time-based blind (query SLEEP - comment)'
INFO: 17:03:02 - testing 'MySQL AND time-based blind (ELT)'
INFO: 17:03:03 - testing 'MySQL OR time-based blind (ELT)'
INFO: 17:03:04 - testing 'MySQL AND time-based blind (ELT - comment)'
INFO: 17:03:06 - testing 'MySQL OR time-based blind (ELT - comment)'
INFO: 17:03:07 - testing 'PostgreSQL > 8.1 AND time-based blind'
INFO: 17:03:08 - testing 'PostgreSQL > 8.1 OR time-based blind'
INFO: 17:03:10 - testing 'PostgreSQL > 8.1 AND time-based blind (comment)'
INFO: 17:03:11 - testing 'PostgreSQL > 8.1 OR time-based blind (comment)'
INFO: 17:03:12 - testing 'PostgreSQL AND time-based blind (heavy query)'
INFO: 17:03:14 - testing 'PostgreSQL OR time-based blind (heavy query)'
INFO: 17:03:15 - testing 'PostgreSQL AND time-based blind (heavy query - comment)'
INFO: 17:03:16 - testing 'PostgreSQL OR time-based blind (heavy query - comment)'
INFO: 17:03:18 - testing 'Microsoft SQL Server/Sybase time-based blind (IF)'
INFO: 17:03:19 - testing 'Microsoft SQL Server/Sybase time-based blind (IF - comment)'
INFO: 17:03:21 - testing 'Microsoft SQL Server/Sybase AND time-based blind (heavy query)'
INFO: 17:03:22 - testing 'Microsoft SQL Server/Sybase OR time-based blind (heavy query)'
INFO: 17:03:23 - testing 'Microsoft SQL Server/Sybase AND time-based blind (heavy query - comment)'
INFO: 17:03:25 - testing 'Microsoft SQL Server/Sybase OR time-based blind (heavy query - comment)'
INFO: 17:03:26 - testing 'Oracle AND time-based blind'
INFO: 17:03:27 - testing 'Oracle OR time-based blind'
INFO: 17:03:29 - testing 'Oracle AND time-based blind (comment)'
INFO: 17:03:30 - testing 'Oracle OR time-based blind (comment)'
INFO: 17:03:32 - testing 'Oracle AND time-based blind (heavy query)'
INFO: 17:03:33 - testing 'Oracle OR time-based blind (heavy query)'
INFO: 17:03:34 - testing 'Oracle AND time-based blind (heavy query - comment)'
INFO: 17:03:36 - testing 'Oracle OR time-based blind (heavy query - comment)'
INFO: 17:03:37 - testing 'IBM DB2 AND time-based blind (heavy query)'
INFO: 17:03:38 - testing 'IBM DB2 OR time-based blind (heavy query)'
INFO: 17:03:40 - testing 'IBM DB2 AND time-based blind (heavy query - comment)'
INFO: 17:03:41 - testing 'IBM DB2 OR time-based blind (heavy query - comment)'
INFO: 17:03:42 - testing 'SQLite > 2.0 AND time-based blind (heavy query)'
INFO: 17:03:44 - testing 'SQLite > 2.0 OR time-based blind (heavy query)'
INFO: 17:03:45 - testing 'SQLite > 2.0 AND time-based blind (heavy query - comment)'
INFO: 17:03:47 - testing 'SQLite > 2.0 OR time-based blind (heavy query - comment)'
INFO: 17:03:48 - testing 'Firebird >= 2.0 AND time-based blind (heavy query)'
INFO: 17:03:49 - testing 'Firebird >= 2.0 OR time-based blind (heavy query)'
INFO: 17:03:51 - testing 'Firebird >= 2.0 AND time-based blind (heavy query - comment)'
INFO: 17:03:52 - testing 'Firebird >= 2.0 OR time-based blind (heavy query - comment)'
INFO: 17:03:53 - testing 'SAP MaxDB AND time-based blind (heavy query)'
INFO: 17:03:55 - testing 'SAP MaxDB OR time-based blind (heavy query)'
INFO: 17:03:56 - testing 'SAP MaxDB AND time-based blind (heavy query - comment)'
INFO: 17:03:57 - testing 'SAP MaxDB OR time-based blind (heavy query - comment)'
INFO: 17:03:59 - testing 'HSQLDB >= 1.7.2 AND time-based blind (heavy query)'
INFO: 17:04:00 - testing 'HSQLDB >= 1.7.2 OR time-based blind (heavy query)'
INFO: 17:04:02 - testing 'HSQLDB >= 1.7.2 AND time-based blind (heavy query - comment)'
INFO: 17:04:03 - testing 'HSQLDB >= 1.7.2 OR time-based blind (heavy query - comment)'
INFO: 17:04:04 - testing 'HSQLDB > 2.0 AND time-based blind (heavy query)'
INFO: 17:04:06 - testing 'HSQLDB > 2.0 OR time-based blind (heavy query)'
INFO: 17:04:07 - testing 'HSQLDB > 2.0 AND time-based blind (heavy query - comment)'
INFO: 17:04:09 - testing 'HSQLDB > 2.0 OR time-based blind (heavy query - comment)'
INFO: 17:04:10 - testing 'Informix AND time-based blind (heavy query)'
INFO: 17:04:11 - testing 'Informix OR time-based blind (heavy query)'
INFO: 17:04:13 - testing 'Informix AND time-based blind (heavy query - comment)'
INFO: 17:04:14 - testing 'Informix OR time-based blind (heavy query - comment)'
INFO: 17:04:15 - testing 'MySQL >= 5.1 time-based blind (heavy query) - PROCEDURE ANALYSE (EXTRACTVALUE)'
INFO: 17:04:17 - testing 'MySQL >= 5.1 time-based blind (heavy query - comment) - PROCEDURE ANALYSE (EXTRACTVALUE)'
INFO: 17:04:18 - testing 'MySQL >= 5.0.12 time-based blind - Parameter replace'
INFO: 17:04:18 - testing 'MySQL >= 5.0.12 time-based blind - Parameter replace (substraction)'
INFO: 17:04:18 - testing 'MySQL < 5.0.12 time-based blind - Parameter replace (heavy queries)'
INFO: 17:04:18 - testing 'MySQL time-based blind - Parameter replace (bool)'
INFO: 17:04:19 - testing 'MySQL time-based blind - Parameter replace (ELT)'
INFO: 17:04:19 - testing 'MySQL time-based blind - Parameter replace (MAKE_SET)'
INFO: 17:04:19 - testing 'PostgreSQL > 8.1 time-based blind - Parameter replace'
INFO: 17:04:19 - testing 'PostgreSQL time-based blind - Parameter replace (heavy query)'
INFO: 17:04:19 - testing 'Microsoft SQL Server/Sybase time-based blind - Parameter replace (heavy queries)'
INFO: 17:04:19 - testing 'Oracle time-based blind - Parameter replace (DBMS_LOCK.SLEEP)'
INFO: 17:04:19 - testing 'Oracle time-based blind - Parameter replace (DBMS_PIPE.RECEIVE_MESSAGE)'
INFO: 17:04:19 - testing 'Oracle time-based blind - Parameter replace (heavy queries)'
INFO: 17:04:19 - testing 'SQLite > 2.0 time-based blind - Parameter replace (heavy query)'
INFO: 17:04:19 - testing 'Firebird time-based blind - Parameter replace (heavy query)'
INFO: 17:04:20 - testing 'SAP MaxDB time-based blind - Parameter replace (heavy query)'
INFO: 17:04:20 - testing 'IBM DB2 time-based blind - Parameter replace (heavy query)'
INFO: 17:04:20 - testing 'HSQLDB >= 1.7.2 time-based blind - Parameter replace (heavy query)'
INFO: 17:04:21 - testing 'HSQLDB > 2.0 time-based blind - Parameter replace (heavy query)'
INFO: 17:04:22 - testing 'Informix time-based blind - Parameter replace (heavy query)'
INFO: 17:04:23 - testing 'Generic UNION query (NULL) - 1 to 20 columns'
INFO: 17:04:23 - automatically extending ranges for UNION query injection technique tests as there is at least one other (potential) technique found
INFO: 17:04:25 - 'ORDER BY' technique appears to be usable. This should reduce the time needed to find the right number of query columns. Automatically extending the range for current UNION query injection technique test
INFO: 17:04:32 - target URL appears to have 1 column in query
WARNING: 17:04:32 - applying generic concatenation (CONCAT)
WARNING: 17:04:37 - if UNION based SQL injection is not detected, please consider and/or try to force the back-end DBMS (e.g. '--dbms=mysql') 
INFO: 17:05:03 - testing 'Generic UNION query (random number) - 1 to 20 columns'
INFO: 17:05:29 - testing 'Generic UNION query (NULL) - 21 to 40 columns'
INFO: 17:05:55 - testing 'Generic UNION query (random number) - 21 to 40 columns'
INFO: 17:06:21 - testing 'Generic UNION query (NULL) - 41 to 60 columns'
INFO: 17:06:48 - testing 'Generic UNION query (random number) - 41 to 60 columns'
INFO: 17:07:14 - testing 'Generic UNION query (NULL) - 61 to 80 columns'
INFO: 17:07:40 - testing 'Generic UNION query (random number) - 61 to 80 columns'
INFO: 17:08:06 - testing 'Generic UNION query (NULL) - 81 to 100 columns'
INFO: 17:08:31 - testing 'Generic UNION query (random number) - 81 to 100 columns'
INFO: 17:08:57 - testing 'MySQL UNION query (NULL) - 1 to 20 columns'
INFO: 17:09:23 - testing 'MySQL UNION query (random number) - 1 to 20 columns'
INFO: 17:09:48 - testing 'MySQL UNION query (NULL) - 21 to 40 columns'
INFO: 17:10:14 - testing 'MySQL UNION query (random number) - 21 to 40 columns'
INFO: 17:10:40 - testing 'MySQL UNION query (NULL) - 41 to 60 columns'
INFO: 17:11:06 - testing 'MySQL UNION query (random number) - 41 to 60 columns'
INFO: 17:11:31 - testing 'MySQL UNION query (NULL) - 61 to 80 columns'
INFO: 17:11:57 - testing 'MySQL UNION query (random number) - 61 to 80 columns'
INFO: 17:12:23 - testing 'MySQL UNION query (NULL) - 81 to 100 columns'
INFO: 17:12:49 - testing 'MySQL UNION query (random number) - 81 to 100 columns'
WARNING: 17:13:16 - in OR boolean-based injection cases, please consider usage of switch '--drop-set-cookie' if you experience any problems during data retrieval
INFO: 17:13:16 - checking if the injection point on POST parameter 'UID' is a false positive
WARNING: 17:13:51 - it appears that the character '>' is filtered by the back-end server. You are strongly advised to rerun with the '--tamper=between'
INFO: 17:13:52 - testing MySQL
WARNING: 17:13:53 - the back-end DBMS is not MySQL
INFO: 17:13:53 - testing Oracle
WARNING: 17:13:55 - the back-end DBMS is not Oracle
INFO: 17:13:55 - testing PostgreSQL
WARNING: 17:13:56 - the back-end DBMS is not PostgreSQL
INFO: 17:13:56 - testing Microsoft SQL Server
WARNING: 17:13:58 - the back-end DBMS is not Microsoft SQL Server
INFO: 17:13:58 - testing SQLite
WARNING: 17:14:00 - the back-end DBMS is not SQLite
INFO: 17:14:00 - testing Microsoft Access
WARNING: 17:14:01 - the back-end DBMS is not Microsoft Access
INFO: 17:14:01 - testing Firebird
WARNING: 17:14:03 - the back-end DBMS is not Firebird
INFO: 17:14:03 - testing SAP MaxDB
WARNING: 17:14:04 - the back-end DBMS is not SAP MaxDB
INFO: 17:14:05 - testing Sybase
WARNING: 17:14:06 - the back-end DBMS is not Sybase
INFO: 17:14:06 - testing IBM DB2
WARNING: 17:14:08 - the back-end DBMS is not IBM DB2
INFO: 17:14:08 - testing HSQLDB
WARNING: 17:14:09 - the back-end DBMS is not HSQLDB
INFO: 17:14:09 - testing H2
WARNING: 17:14:11 - the back-end DBMS is not H2
INFO: 17:14:11 - testing Informix
WARNING: 17:14:12 - the back-end DBMS is not Informix
CRITICAL: 17:14:13 - sqlmap was not able to fingerprint the back-end database management system
WARNING: 17:14:13 - HTTP error codes detected during run:
500 (Internal Server Error) - 661 times

**Comment by stamparm** [comment]
`it appears that the character '>' is filtered by the back-end server. You are strongly advised to rerun with the '--tamper=between'`
