### ISSUE TITLE
401 False Positive

### ISSUE THREAD

**Issue by electroxero** [sqlmapproject/sqlmap#4014]
**Describe the bug**
I'm trying to fuzz a login page, but the default HTTP Response code is 401. Sqlmap suggest to add a basic authentication but I cannot do that because the 401 error is hardcoded inside the PHP backend code.

**Command**
1 - 'sqlmap -r /tmp/login_page'
2 - Use marker (*)
3 - Process post data

**Screenshots**
![image](https://user-images.githubusercontent.com/20456461/69056304-f508c000-0a0f-11ea-8c9f-0adf1c34fa6f.png)

**Running environment:**
 - sqlmap 1.3.10#stable
 - Operating system: arch

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/Usage#ignore-problematic-http-error-code
