### ISSUE TITLE
Unable to retrieve page content on 401 Response Code

### ISSUE THREAD

**Issue by electroxero** [sqlmapproject/sqlmap#4015]
**Describe the bug**
I'm trying to fuzz a login page which response with 401, but sqlmap shows an error.

**To Reproduce**
1. Run 'sqlmap -r /tmp/login_page --ignore-code 401'
2. Use marker (inside JSON post data): yes
3. Parse JSON post data : yes

**Screenshots**
![image](https://user-images.githubusercontent.com/20456461/69061536-9ba58e80-0a19-11ea-8735-7b8f86fe000d.png)

**Running environment:**
 - sqlmap 1.3.10#stable
 - Operating system: arch

**Comment by stamparm** [comment]
You are pushing it here. No content at all in the first place. I've pushed a patch related to this, but I am not sure that this all will work in the first place.
