### ISSUE TITLE
where is sqlmap located?

### ISSUE THREAD

**Issue by azamet90** [sqlmapproject/sqlmap#4018]
i want to add sqlmap to burp suite co2 extension but where is it located? it was already installed on kali linux i can run it directly with sudo sqlmap command

**Comment by stamparm** [comment]
1) This is not sqlmap issue
2) Please use system commands to find sqlmap at your place (e.g. `locate sqlmap` or `find / -iname 'sqlmap*'`)
3) You have written zero useful information about your system (can't guess whether you are using Windows, Linux, etc.)

**Comment by azamet90** [comment]
>     1. This is not sqlmap issue
> 
>     2. Please use system commands to find sqlmap at your place (e.g. `locate sqlmap` or `find / -iname 'sqlmap*'`)
> 
>     3. You have written zero useful information about your system (can't guess whether you are using Windows, Linux, etc.)

but as you can see i did not post issue i did choice the blank option
