### ISSUE TITLE
websocket special procedure

### ISSUE THREAD

**Issue by e2002e** [sqlmapproject/sqlmap#4019]
Hello, the server I'm trying sqlmap on uses websocket, but it only sends the result of the input on the third call to recv(), is there a way to scroll through the results because the two firsts are generic and (I think) useless to sql injection testing

My test are to simply use ws.recv() twice before page = ws.recv() line 456 in connect.py; using enough verbosity I can see the second answer when I skip the answer once, skipping it twice I get a "[CRITICAL] connection timed out to the target URL. sqlmap is going to retry the request(s)", a massive slowdown, and no page data. 
I'm sure it yields the result on the third recv() call because I tested this:

#!/usr/bin/env python
from websocket import create_connection
ws = create_connection("remote")
ws.send('datas')
print ws.recv()
print ws.recv()
print ws.recv()

The wildchars for testable parameters needed to be enclosed in quotes, that is why i did not get any answers. Nevertheless this might be a good thing to have an option like "--skip n websocket answers" cheers

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/commit/c028fb900385b06951f2aa1354b671a1a54a2d0c
