### ISSUE TITLE
Unable to attack URLs with #

### ISSUE THREAD

**Issue by 9tail123** [sqlmapproject/sqlmap#4021]
Unable to attack URLs with #
![QQ图片20191130181837](https://user-images.githubusercontent.com/35592183/69899189-e15d4200-139d-11ea-950c-fd2451935b79.png)
Even if the parameter is marked with *
![111](https://user-images.githubusercontent.com/35592183/69899228-27b2a100-139e-11ea-8835-2dde732b24f1.png)

**Comment by stamparm** [comment]
Everything after the `#` is handled by the internal program logic (e.g. Javascript) and not directly sent to the web application. Without a runtime support (e.g. real browser), there is no way how to know what is going on parameters after the `#`. Run with a dummy `#` proves my point (where web application doesn't handle it internally):

![screenshot_2](https://user-images.githubusercontent.com/921555/69906486-4fb4fb00-13c4-11ea-8d44-59aad96a0bbe.png)
