### ISSUE TITLE
Log writing error ?

### ISSUE THREAD

**Issue by Webaba** [sqlmapproject/sqlmap#4023]
**Describe the bug**
sqlmap  produces 3 different outputs. 2 in console 1 in the log

Log  a2w*Â§rT;~32Abg3123@alXk) 
[INFO] retrieved: a2w* rT;~32Abg3123@alXk)  
and the list you get when sqlmap is done  a2w*§rT;~32Abg3123@alXk)

**To Reproduce**  
1. Dumped data with this commands 
sqlmap -u" URL " --level 5 --risk 3 --random-agent --referer="URL" "--headers=X-Requested-With: XMLHttpRequest" --batch --threads=5 --dump -D  -T  -C   --hex --null-connection

I have run it 3 times with these parameters and fresh queries

**Expected behavior**
That the right query output lands in the Log, 

**Screenshots**

![sdfsdfsdfs](https://user-images.githubusercontent.com/58381446/69910400-2bc8d800-140b-11ea-8fec-a20246df2b33.jpg)

![sdasdasdas](https://user-images.githubusercontent.com/58381446/69910412-79454500-140b-11ea-8ab4-1580ac72fc1d.jpg)

**Running environment:**
 - sqlmap version 1.3.8.13#dev
 - Installation method Download from git
 - Operating system: [Windows 7]
 - Python version [e.g.2.7]

**Target details:**
   web server operating system: Linux CentOS 6.8
   web application technology: PHP 5.3.3, PHP, Apache 2.2.15
   back-end DBMS: MySQL 5
 - SQLi techniques found by sqlmap [time-based blind, boolean-based blind]
 - WAF/IPS [if any]
 - Relevant console output 
 - Exception traceback [if any]

**Additional context**

**Comment by stamparm** [comment]
Your console has one encoding, file has other (i.e. UTF8). Also, you are running on Windows machine which inherently has problems with display of arbitrary Unicode characters

**Comment by stamparm** [comment]
p.s. file output is more relevant in such situations

**Comment by Webaba** [comment]
Thank you. good to know that the log is the relevant place to look not the console.
