### ISSUE TITLE
Payloads cannot be loaded when a large number of key value pairs are submitted

### ISSUE THREAD

**Issue by yzddmr6** [sqlmapproject/sqlmap#4027]
Payloads cannot be loaded when a large number of key value pairs are submitted.
Sometimes I will add a large number of key value pairs  in post data to bypass the waf
such as this:
```
BRzH=gcbhOylbIDdqYePoFIEuKuPFHKJoKnasETIFUJeMMdcFMDZNXlEZTZmhuQmYLpwDtYDUrpigkLBwHtkUThwnRmHmAuMcYqAnSABqcRyAkCrXVnTevNzlvVYLKufEvkJrTXGyRxhAslkqQuCCpuwiEUCgskICYJaXznrqZJymDJtoeLADUnhrHYrVScXdFvleXqGjkopgZwzXyENoFTiDBcqVQIQLcFuT&AwopHEjQR=SzuqTIvBORDsfebIYAVImKABlaYdYCWEeQrWGifZJSKrrqQXFrQfCGwlNcqBRHBnwTBUUYStVBeJgEWDKShzXxznezIQuQnzPdIseFcFwUuKKOwHOHfrBkuPxYSCGbIwKEsSnloNVjMOnahxIbcnLGGWJbHSQMyikFslSBBlJAeLkUbusEyPGAFRPaGLYIBAzDdcWnLFzYrOhlerDqGRaELwjDwKPNnpoce&AzvhrN=qVbqCekqVJSGOLBuwHEoDAgujFRkHRTVJcICPocQcLhLflrdJFtDwWoTvhntjYXPYzTgoYrmFyiShjjekPUnSsuSEAOdpMhBiPzoHDgqPepnLuXcRwuAKdygWpJdfNSSqtVBNWGpyBgwPQWEezfVnVjwjDRSCmReMjTPwBuexuiLEyslrCzlVEGshQjRICuAXNtsFWAhRcDeFokMtGYAtUVVtvIIZlHDpLHRrxQUNiNjMPxy&BBRzH=gcbhOylbIDdqYePoFIEuKuPFHKJoKnasETIFUJeMMdcFMDZNXlEZTZmhuQmYLpwDtYDUrpigkLBwHtkUThwnRmHmAuMcYqAnSABqcRyAkCrXVnTevNzlvVYLKufEvkJrTXGyRxhAslkqQuCCpuwiEUCgskICYJaXznrqZJymDJtoeLADUnhrHYrVScXdFvleXqGjkopgZwzXyENoFTiDBcqVQIQLcFuT&AwopHEjQR=SzuqTIvBORDsfebIYAVImKABlaYdYCWEeQrWGifZJSKrrqQXFrQfCGwlNcqBRHBnwTBUUYStVBeJgEWDKShzXxznezIQuQnzPdIseFcFwUuKKOwHOHfrBkuPxYSCGbIwKEsSnloNVjMOnahxIbcnLGGWJbHSQMyikFslSBBlJAeLkUbusEyPGAFRPaGLYIBAzDdcWnLFzYrOhlerDqGRaELwjDwKPNnpoce&AzvhrN=qVbqCekqVJSGOLBuwHEoDAgujFRkHRTVJcICPocQcLhLflrdJFtDwWoTvhntjYXPYzTgoYrmFyiShjjekPUnSsuSEAOdpMhBiPzoHDgqPepnLuXcRwuAKdygWpJdfNSSqtVBNWGpyBgwPQWEezfVnVjwjDRSCmReMjTPwBuexuiLEyslrCzlVEGshQjRICuAXNtsFWAhRcDeFokMtGYAtUVVtvIIZlHDpLHRrxQUNiNjMPxy
.....
```
It will increase the packet size to 100KB

But when I used the time blind method, sqlmap couldn't load the payload into the data package

![image](https://user-images.githubusercontent.com/46088090/70303178-eb69bf80-1839-11ea-915f-803d09996781.png)

this is the 1.txt
```
xxxxxxxxxxxxxxxxxxxxxx&u=9466546546*&p=as6d123asdf&xxxxxxxxxxx
```
It's always like this，so I think it may be a bug when the package is too big.

Hope it can be repaired soon.

**Comment by yzddmr6** [comment]
After my test, if the txt is more than 40KB, it will often be unrecognized.
Because the * can not be replaced with the payload

**Comment by stamparm** [comment]
![1](https://user-images.githubusercontent.com/921555/70328424-4bac3180-1839-11ea-8fb4-b6e1d207f756.png)

![2](https://user-images.githubusercontent.com/921555/70328426-4e0e8b80-1839-11ea-9de3-dd71790faa97.png)

![3](https://user-images.githubusercontent.com/921555/70328428-5070e580-1839-11ea-8757-936b3d0f9280.png)

QED

p.s. used request file [req.txt](https://github.com/sqlmapproject/sqlmap/files/3932474/req.txt)
