### ISSUE TITLE
Incorrect DBMS engine by Sqlmap. 

### ISSUE THREAD

**Issue by VinnyVir** [sqlmapproject/sqlmap#4031]
**Describe the bug**
SQL map giving incorrect DBMS enginer - it showing SQLite but actual is Microsoft SQL Server. Also on running the command for <URL> --tables , its not fetching the list of databases ( its searching from SQLite_masterdb

URL : - GET https://ussltcher8022.dan.sltc.com/CTSCore/api/Tickets/GetFiltersInformation?userId=10749

**Screenshots**
[17:50:43] [INFO] resuming back-end DBMS 'sqlite'
[17:50:43] [INFO] testing connection to the target URL
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: userId (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: userId=10749') AND 6497=6497 AND ('fNjL'='fNjL
---
[17:50:45] [INFO] the back-end DBMS is SQLite
back-end DBMS: SQLite
[17:50:45] [INFO] fetched data logged to text files under 'C:\Users\vvirmani\AppData\Local\sqlmap\output\ussltcher8022.dan.sltc.com'

*

**Comment by stamparm** [comment]
Can you please provide with the traffic file? You can get it by rerunning everything with `-u ... --flush-session -t /tmp/traffic.txt`.

**Comment by VinnyVir** [comment]
I ran into this error -  [CRITICAL] there has been a file opening error for filename '/tmp/traffic.txt'. Please check write permissions on a file and that it's not locked by another process

**Comment by stamparm** [comment]
Please use any output directory where you can write to

**Comment by VinnyVir** [comment]
[traffic.txt](https://github.com/sqlmapproject/sqlmap/files/3944916/traffic.txt)

Please find the traffic file

**Comment by VinnyVir** [comment]
[traffic1.txt](https://github.com/sqlmapproject/sqlmap/files/3945148/traffic1.txt)

Hi @stamparm , we have created another Traffic file where we have defined parameters. But SQL map says field lname and notes are not injectable. Can you suggest are do we need to include any security parameter

**Comment by stamparm** [comment]
It seems that you had false-positive from start. `--flush-session` cleared the previous session and you couldn't reproduce the "injection".
