### ISSUE TITLE
Mysql 4 : Column enumeration

### ISSUE THREAD

**Issue by eltouco72** [sqlmapproject/sqlmap#4035]
Hi,

During a pen test, I had to deal with a blind SQL injection to a Mysql 4 server.
As you know the database Information_Schema does not exists in that version therefore it is not possible to list the table names and columns name with it.

Right now, SQLmap propose a dictionnary attack to enumerate the table and also a dictionary attack to enumerate the columns name in the found tables.

But in Mysql 4 there is a trick to know the number of columns of a table and to know their names using error messages

example, let say you found the table 'client', the injection is like that :
SELECT name FROM client WHERE idClient = {inj}
with this injection 
SELECT name FROM client WHERE idClient = 1 **AND (SELECT * FROM client LIMIT 1) = (1);**
you get

ERROR 1241 (21000): Operand should contain 3 column(s)

you know the number of columns

Now it is also possible to enumerate columns name still using error message
SELECT name FROM client WHERE idClient = 1 **AND (SELECT * FROM client UNION SELECT 1%0,2,3 LIMIT 1) = (1,2,3);**

"Column 'idClient' cannot be null"

and so on, we move %0 to column 2 to know the name and so on

Source: https://websec.wordpress.com/2009/11/26/mysql-table-and-column-names-update-2/

So my proposal of improvement is that when sqlmap detects a mysql version 4 is to enumerate table name using dictionary but to use this technique to know the number of colum and their and therefore avoid the long dictionary attack.

thanks for the good work.

**Comment by stamparm** [comment]
You have so many "problems" in this proposition:

1) You have to have DBMS errors turned on in this kind of cases
2) You have to have MySQL 4 (rare beast - your referenced link is from 2009)
3) `"Column 'idClient' cannot be null"` <- even your referenced link says `this does only work if the column types have the parameter “NOT NULL”`
4)....
