### ISSUE TITLE
--csrf-token problems

### ISSUE THREAD

**Issue by hahahahahahahahahahahahahahahah** [sqlmapproject/sqlmap#4036]
can sqlmap just try few more times?......pls?
```
[ERROR] anti-CSRF token '\_\_(\w)*' can't be found at 'hidden', skipping to the next form
sqlmap-shell>
```

**Comment by hahahahahahahahahahahahahahahah** [comment]
or try until it found something?

**Comment by hahahahahahahahahahahahahahahah** [comment]
> can sqlmap just try few more times?......pls?

thx a lot!!

**Comment by radinmoradi** [comment]
در تاریخ پنجشنبه ۱۲ دسامبر ۲۰۱۹،‏ ۱۷:۲۶ hahahahahahahahahahahahahahahah <
notifications@github.com> نوشت:

**Comment by radinmoradi** [comment]
در تاریخ پنجشنبه ۱۲ دسامبر ۲۰۱۹،‏ ۱۷:۲۷ hahahahahahahahahahahahahahahah <
notifications@github.com> نوشت:

**Comment by hahahahahahahahahahahahahahahah** [comment]
> or try until it found something? thx!!
> sometimes it got 4xx by some reason,and... it's gonna shut down...i mean... wtf?...

this??? why not???
because i have another target have these kind of problem too............... just... let it try few more times... dont just.. end it.... like that................thx........

**Comment by hahahahahahahahahahahahahahahah** [comment]
wtf.............. these is wasteing time...
...
[INFO] testing 'MySQL boolean-based blind - Parameter replace (MAKE_SET)'

 [INFO] testing 'MySQL boolean-based blind - Parameter replace (MAKE_SET - original value)'                                       
 [INFO] testing 'MySQL boolean-based blind - Parameter replace (ELT)'

 [INFO] testing 'MySQL boolean-based blind - Parameter replace (ELT - original value)'                                        
    
 [INFO] testing 'MySQL boolean-based blind - Parameter replace (bool*int)'

 [INFO] testing 'MySQL boolean-based blind - Parameter replace (bool*int - original value)'

 [INFO] testing 'MySQL >= 5.0 boolean-based blind - ORDER BY, GROUP BY clause'

 [INFO] testing 'MySQL >= 5.0 boolean-based blind - ORDER BY, GROUP BY clause (original value)'

 [INFO] testing 'MySQL < 5.0 boolean-based blind - ORDER BY, GROUP BY clause'

 [INFO] testing 'MySQL < 5.0 boolean-based blind - ORDER BY, GROUP BY clause (original value)'

 [INFO] testing 'MySQL >= 5.0 boolean-based blind - Stacked queries'

 [CRITICAL] anti-CSRF token 'ci_session' can't be found at 'http://jejd.com/sheh/udud?jejeje='
                                                                

sqlmap-shell>
```
