### ISSUE TITLE
needed support

### ISSUE THREAD

**Issue by hahahahahahahahahahahahahahahah** [sqlmapproject/sqlmap#4040]
```
[WARNING] provided parameter 'path' appears to be 'hex' encoded
```
and then do nothing?...
is there something similar to `hexencode` or `--from-hex` just like `--base64` in sqlmap?

https://github.com/sqlmapproject/sqlmap/issues/25#issuecomment-278908166

**Comment by radinmoradi** [comment]
در تاریخ شنبه ۱۴ دسامبر ۲۰۱۹،‏ ۱۸:۳۰ hahahahahahahahahahahahahahahah <
notifications@github.com> نوشت:

**Comment by stamparm** [comment]
Sorry, but not. Duplicate of #25
