### ISSUE TITLE
Proper documentation for Rest-api

### ISSUE THREAD

**Issue by ashwinvin** [sqlmapproject/sqlmap#4042]
Guys Please create a proper documentation for the api.

**Comment by stamparm** [comment]
You are aware of https://github.com/sqlmapproject/sqlmap/wiki/Usage#api-rest-json ?
If answer is yes, please suggest what would you like us to properly document more

**Comment by ashwinvin** [comment]
Yes , I am aware of that . But can  you just what those status,type and value mean
eg : `"status": 1, 
            "type": 2, 
            "value": "5.1.73-0ubuntu0.10.04.1"`

**Comment by stamparm** [comment]
Looking some opened issues. Stumbled upon thee. Quick info:

* STATUS ([ref](https://github.com/sqlmapproject/sqlmap/blob/master/lib/core/enums.py#L392)):
```
0 - in progress
1 - complete
```

* TYPE ([ref](https://github.com/sqlmapproject/sqlmap/blob/master/lib/core/enums.py#L363)):

```
0 - target
1 - techniques
2 - dbms_fingerprint
3 - banner
4 - current_user
5 - current_db
6 - hostname
7 - is_dba
8 - users
9 - passwords
10 - privileges
11 - roles
12 - dbs
13 - tables
14 - columns
15 - schema
16 - count
17 - dump_table
18 - search
19 - sql_query
20 - common_tables
21 - common_columns
22 - file_read
23 - file_write
24 - os_cmd
25 - reg_read
26 - statements
```

**Comment by stamparm** [comment]
You'll be able to find this data now at the end of sqlmap [wiki](https://github.com/sqlmapproject/sqlmap/wiki/Usage) (i.e. "General codes used in response JSON data")
