### ISSUE TITLE
How can i use --sql-query = "" for update dump in sqlmap or sql-shell ?

### ISSUE THREAD

**Issue by blackhatcracker** [sqlmapproject/sqlmap#4044]
How can i use --sql-query="" for update dump in sqlmap or sql-shell... for example update email in db. what is the order ?

**Comment by stamparm** [comment]
This request does not make much sense, so I'll try to do some guessing:

1) If you thought on "refreshing" content of already dumped data, then use `--fresh-queries`
2) If you thought on running `UPDATE` statement, then you'll need to have "stacked-queries" SQLi technique available, along with the valid `UPDATE` statement (e.g. `--sql-query=UPDATE table SET password='foobar' WHERE id=0`)
