### ISSUE TITLE
default command (settings.py)

### ISSUE THREAD

**Issue by hahahahahahahahahahahahahahahah** [sqlmapproject/sqlmap#4054]
`default_command={cmd}`

example: `default_command=-v 2 --output-dir ./output/`

**Comment by stamparm** [comment]
You can use "environment override" feature (https://github.com/sqlmapproject/sqlmap/issues/678). For example, to have a default value for `--output-dir` please set the environment variable `SQLMAP_OUTPUTDIR` to (e.g.) `/tmp/output`. To override the default verbosity level please set the environment variable `SQLMAP_VERBOSE` to `2.
