### ISSUE TITLE
WAF filtering parenthesis and SQLmap heavy use of concat

### ISSUE THREAD

**Issue by eltouco72** [sqlmapproject/sqlmap#4055]
Hi,

During a pen test I had to deal with a WAF that filter parenthesis '(' and ')'
however an SQLI what possible with this
https://www.xxxxxx.com/?id=-1 union select 1,2,@@version,4,5,6,7,8

but when i ran SQLMAP it could not find the sqli beacuse of use of CONCAT() function and therefore use of parenthesis with this kind of payload
Payload: id=-6630 UNION ALL SELECT NULL,CONCAT(0x7178786271,0x79434e597a45536f5a4c695273427857546c76554854574c4f5a534f587368725142615a54456256,0x716b767a71),NULL,NULL,NULL,NULL,NULL,NULL-- mIJj

in cases where parenthesis are filtered (i could not find a way to bypass it by the way) is it possible that SQLMAP avoid using CONCAT() ?

**Comment by stamparm** [comment]
1) Any kind of sub-query (used in all cases of enumeration/dumping) in vast majority of cases requires parenthesis
2) In cases of `error-based` and `union-based` concatenation is a must, so sqlmap could be able to extract the results from web servers output

**Comment by eltouco72** [comment]
well, in my case it was not error based
I could get result as long as i don't use parenthesis in the payload, but sqlmap found it was not injectable
