### ISSUE TITLE
Documentation wiki is missing details for --answer parameter

### ISSUE THREAD

**Issue by wadim-al** [sqlmapproject/sqlmap#4061]
**Describe the bug**
Documentation wiki is missing the full list of --answer parameter values. I can't find it with googling either.

**To Reproduce**
1. Open https://github.com/sqlmapproject/sqlmap/wiki/Usage in browser
2. Search for --answers

**Expected behavior**
All possible values for the --answers parameter should be present

**Comment by stamparm** [comment]
1) There are no constraints here OTHER that the used part inside the `--answer` has to be present inside the question itself.
2) The documentation (i.e. wiki) says `...providing any part of question together with answer...`. This means that if the question is (e.g.) `it looks like the back-end DBMS is 'MySQL'. Do you want to skip test payloads specific for other DBMSes? [Y/n]` and you want to answer with `n`, you can use (e.g.) `--answer="skip test=n"`
3) In plainspeak, use any specific part (e.g. keyword or couple of words) of the question itself
