### ISSUE TITLE
Encode parameters with specific encoding

### ISSUE THREAD

**Issue by doraeric** [sqlmapproject/sqlmap#4066]
```python
quote_from_bytes('SELECT * FROM 表格'.encode('utf-8'))
# 'SELECT%20%2A%20FROM%20%E8%A1%A8%E6%A0%BC'
quote_from_bytes('SELECT * FROM 表格'.encode('big5'))
# 'SELECT%20%2A%20FROM%20%AA%ED%AE%E6'
```
Something like `curl $url --data 'id=SELECT%20%2A%20FROM%20%AA%ED%AE%E6'` will work.

When using sqlmap, it encodes requests with utf-8 even `--encoding=big5` is set.

I think the issue is similar to #25 , not sure whether they are the same.

**Comment by stamparm** [comment]
A) Hi @doraeric. I've made a related "patch", but you haven't said anything about your case, hence, I am not sure if I managed to "reconstruct" what the author wanted to say. For example, I am not sure whether you are having problems with providing `--sql-query` custom SQL queries, or in case of dumping (i.e. `--dump`) tables with non-latin names,... Also, I don't know which DBMS or technique are related to this issue
B) Anyway, please update to the latest revision and retry. If the problem "persists" please write more details (like you've been presented inside the template when creating the Issue in the first place)
