### ISSUE TITLE
POST request with "multipart/form-data" cannot test URL as injection point

### ISSUE THREAD

**Issue by nigawtester** [sqlmapproject/sqlmap#4069]
**Describe the bug**
I have a request with content type multipart/form-data. The URL itself is vulnerable to SQL injection but SQLmap tests the parameters even though I have put the injection point (*) on the URI.

**To Reproduce**
The request is similar to:
```
POST /test/id/432* HTTP/1.1
Host: example.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: multipart/form-data; boundary=---------------------------9883942161396932297395800796
Content-Length: 1629
Origin: https://example.com
Connection: close
Referer: https://example.com
Cookie: _ga=GA1.4.247801184.1578570970; _gid=GA1.4.93682711.1578570970; _ga=GA1.3.247801184.1578570970; _gid=GA1.3.93682711.1578570970; 
Upgrade-Insecure-Requests: 1

-----------------------------9883942161396932297395800796
Content-Disposition: form-data; name="test[title]"

test
-----------------------------9883942161396932297395800796

```
**Expected behavior**
Shouldn't SQLmap test the URL when I specify so? A solution I found is to change the body encoding in Burp Suite but this is not always possible as some web apps would not accept the change.

**Screenshots**

**Running environment:**
 - sqlmap version 1.3.11.2#dev

**Comment by stamparm** [comment]
Have you tried answering with `n` to a question `Multipart-like data found in POST data. Do you want to process it? [Y/n/q]`?

**Comment by nigawtester** [comment]
Hi, Give me 5 minutes to retest this as I got blocked by Cloudfront.

**Comment by nigawtester** [comment]
Yep, you are right and I am a n00b. Thank you and sorry for wasting your time. Hopefully next time I have the same issue I will find this post :)
