### ISSUE TITLE
bug? wrong http method if explicitly forced

### ISSUE THREAD

**Issue by leoTlr** [sqlmapproject/sqlmap#4070]
**Describe the bug**
`sqlmap --method=GET -u URL --data='{ "foo": "*", "bar": "*" }' --dbs`
produces POST requests 
(url has no query parameters)

tested with all 4 possibilities of [y/n]:
`custom injection marker ('*') found in POST body. Do you want to process it? [Y/n/q] y
JSON data found in POST data. Do you want to process it? [Y/n/q] y`

**Expected behavior**
Produce GET requests trying to inject with paramteters in http body instead of url query parameters

**Running environment:**
 - sqlmap version: 1.4#stable
 - Installation method: Arch community repo
 - Operating system: Linux 5.4.8
 - Python version: 3.8.1
- also tested with 1.4.1.21#dev, same behavior

Is there a workaraound?

**Comment by leoTlr** [comment]
https://github.com/sqlmapproject/sqlmap/blob/14005f476de9063be6425fabe8f28093777987c2/lib/core/target.py#L108-L109

These two lines seem to be the reason. But whats the reason for not allowing GET with body data?

**Comment by stamparm** [comment]
@leoTlr according to https://stackoverflow.com/a/983458: `So, yes, you can send a body with GET, and no, it is never useful to do so`. Anyway, will let you do it with the next commit
