### ISSUE TITLE
a delay with counter.

### ISSUE THREAD

**Issue by e2002e** [sqlmapproject/sqlmap#4071]
**Is your feature request related to a problem? Please describe.**
When facing a firewall that drops connections after a certain number of attempts

**Describe the solution you'd like**
Have an option just like --'delay' but in two parts: one is how many attempts should we do before sleeping, second is the time to sleep

**Describe alternatives you've considered**
We can't make it sleep 1 minutes every attempt when we just need to do so every 7 attempts (for instance). This would be great.
Thanks.

**Comment by stamparm** [comment]
In such cases, firewalls have a threshold (usually number of requests in a delta time). Afterwards you have an unspecified "blockage" time. Not sure why would you force the blockage in the first place, while you can do the `--delay` and try to skip it in the first place.

p.s. for example, in cloud providers once you are on the blacklist, sometimes days (or indefinitely) have to pass for you to come back to it

**Comment by e2002e** [comment]
it seems like delta time can be around a few minutes, so if we find the threshold we can avoid having our ip banned and working much faster than using the option --delay with the delta time
