### ISSUE TITLE
header Host bug

### ISSUE THREAD

**Issue by hahahahahahahahahahahahahahahah** [sqlmapproject/sqlmap#4085]
```
-u "https://1.1.1.1/test/testtest?test=1&testtes=test-te-st&tsetset=tstss" --headers "Host: www.test.com" -v 6

GET /test/testtest?test=1&testtes=test-te-st&tsetset=tstss HTTP/1.1
...
Referer: https://1.1.1.1:443/test/testtest
Host: 1.1.1.1
Connection: close
```

**Comment by hahahahahahahahahahahahahahahah** [comment]
even u using `-r` it still not working.........

**Comment by marshallthomas** [comment]
do you mind if I take a look at it?  I have experience in working with a sql database through python.  and I think I had the same error a couple years ago.

**Comment by stamparm** [comment]
Used the same command and couldn't reproduce:

![test](https://user-images.githubusercontent.com/921555/73574604-659f7480-4476-11ea-9df1-582c8aa7041c.png)

**Comment by hahahahahahahahahahahahahahahah** [comment]
ill send u detail later

**Comment by stamparm** [comment]
`--level 5` is the cause

**Comment by hahahahahahahahahahahahahahahah** [comment]
oh...

**Comment by hahahahahahahahahahahahahahahah** [comment]
@stamparm reopen this thx!! `Host: ***` is ok, but `host: ***` cant...
