### ISSUE TITLE
Is sitemap.xml scanning no longer supported?

### ISSUE THREAD

**Issue by smoyer64** [sqlmapproject/sqlmap#4089]
**Describe the bug**

The usage page at https://github.com/sqlmapproject/sqlmap/wiki/Usage includes the ability to use a sitemap to parse targets for SQLMap as shown in the following (clipped) text:

```text
  Target:
    At least one of these options has to be provided to define the
    target(s)

    -d DIRECT           Connection string for direct database connection
    -u URL, --url=URL   Target URL (e.g. "http://www.site.com/vuln.php?id=1")
    -l LOGFILE          Parse target(s) from Burp or WebScarab proxy log file
    -x SITEMAPURL       Parse target(s) from remote sitemap(.xml) file
    -m BULKFILE         Scan multiple targets given in a textual file
    -r REQUESTFILE      Load HTTP request from a file
    -g GOOGLEDORK       Process Google dork results as target URLs
    -c CONFIGFILE       Load options from a configuration INI file
```

Running the ``SQLMap`` command with the ``-hh`` switch on version 1.4 no longer lists the ``-x`` (SITEMAPURL) argument as follows:

```text
Target:
    At least one of these options has to be provided to define the
    target(s)

    -u URL, --url=URL   Target URL (e.g. "http://www.site.com/vuln.php?id=1")
    -d DIRECT           Connection string for direct database connection
    -l LOGFILE          Parse target(s) from Burp or WebScarab proxy log file
    -m BULKFILE         Scan multiple targets given in a textual file
    -r REQUESTFILE      Load HTTP request from a file
    -g GOOGLEDORK       Process Google dork results as target URLs
    -c CONFIGFILE       Load options from a configuration INI file
```

**To Reproduce**
1. Run 'sqlmap.py -hh'

**Expected behavior**

I'm hoping that the removal of the sitemap option is a regression of some sort but, if not, the wiki version of the usage documentation should match the output of the executable.

**Running environment:**
 - sqlmap version 1.4
 - Installation method: tar file from Github releases page
 - Operating system: Xubuntu Linux 18.04 LTS
 - Python version: 2.7.17

**Comment by stamparm** [comment]
1) It is indeed removed, though, it is now a standard part of `--crawl`. You are being asked in crawling mode `do you want to check for the existence of site's sitemap(.xml) [y/N]`
2) Fixed wiki with the latest revision

**Comment by smoyer64** [comment]
I found that crawl includes this capability but in one feature of the ``-x`` flag was that it forced discovery of targets in batch mode.  I can run SQLMap with ``--crawl=1 --batch`` but the default answer for the ``do you want to check for the existence of site's sitemap(.xml) [y/N]`` is "no", so I can no longer force the use of a sitemap in batch mode.  Is there a way around this that I'm missing?  I agree that providing the ``SITEMAPURL`` variable wasn't generally necessary since the sitemap is supposed to be at the root of the server but it's still useful for crawling in batch mode.

**Comment by radinmoradi** [comment]
در تاریخ سه‌شنبه ۲۸ ژانویهٔ ۲۰۲۰،‏ ۱:۱۱ Miroslav Stampar <
notifications@github.com> نوشت:

**Comment by radinmoradi** [comment]
y

در تاریخ سه‌شنبه ۲۸ ژانویهٔ ۲۰۲۰،‏ ۱۸:۰۷ مصطفی مرادی <
radinmoradi138@gmail.com> نوشت:

**Comment by radinmoradi** [comment]
در تاریخ سه‌شنبه ۲۸ ژانویهٔ ۲۰۲۰،‏ ۱۸:۰۸ مصطفی مرادی <
radinmoradi138@gmail.com> نوشت:

**Comment by smoyer64** [comment]
Solution (for those who want to use sitemap crawling in batch mode) - use the following three arguments in combination to parse the sitemap.xml file:

```text
--crawl=1 --batch --answers="sitemap=Y"
```

Note that this will also crawl starting at the page included as the target.
