### ISSUE TITLE
Typo in 'Usage' page of wiki

### ISSUE THREAD

**Issue by smoyer64** [sqlmapproject/sqlmap#4090]
**Describe the bug**

I couldn't find a convenient way to submit a PR for the wiki ... there's a typo I was going to fix which can be found (currently) on line 2364.  The following text:

```markdown
### Conduct through tests only if positive heuristic(s)
```

should read:

```markdown
### Conduct thorough tests only if positive heuristic(s)
```

**Comment by stamparm** [comment]
Done with the latest revision. Thank you for your report
