### ISSUE TITLE
Question Not Appropriate for Yes/No Response

### ISSUE THREAD

**Issue by Horridge** [sqlmapproject/sqlmap#4102]
**Describe the bug**
Happened upon this question whilst using sqlmap that requests a Yes/No response, but I believe is not a yes or no question. I believe wording needs to be updated to be more clear. 

**To Reproduce**
1. Navigate to sqlmap/lib/request/connect.py
2. Observe question, " Do you want to apply the refresh from now on (or stay on the original page)? [Y/n]"

**Expected behavior**
Question would be appropriately written for a yes/no response

**Screenshots**
N/A

**Running environment:**
 - sqlmap version 1.4.2

**Target details:**
N/A

**Additional context**
https://github.com/sqlmapproject/sqlmap/blob/master/lib/request/connect.py#L595

**Comment by stamparm** [comment]
From now on, there will be:

`got a refresh intent (redirect like response common to login pages) to '<url>'. Do you want to apply it from now on? [Y/n]`
