### ISSUE TITLE
android app user agent

### ISSUE THREAD

**Issue by hahahahahahahahahahahahahahahah** [sqlmapproject/sqlmap#4109]
Android **App** mainly uses the following types of UA: 

1. `Dalvik/2.1.0 (Linux***************)`
https://user-agents.net/applications/dalvik/versions/2-1
2. (browser UA)
3. (others (maybe next time) )

and i think
`--and-app-ua` or `--android-app`? or `--android`?????????...
`--mobile` --> `--mobile-ua`
will be better~!

**Comment by stamparm** [comment]
A) Sorry, I don't see a "special" value here to be implemented as part of sqlmap. You have a `--user-agent` option for this kind of stuff.
B) Also, you can use `SQLMAP_AGENT` to set this kind of agent for all further runs:

![ua](https://user-images.githubusercontent.com/921555/74146562-9e231900-4c01-11ea-8de9-160296b8bc11.png)

**Comment by hahahahahahahahahahahahahahahah** [comment]
some android app use user agent `Dalvik/xxxxxx......`, what do u think? add it? no?
