### ISSUE TITLE
WS-Security support

### ISSUE THREAD

**Issue by baptx** [sqlmapproject/sqlmap#4112]
There was an API testing project using WS-Security where I could not use sqlmap because a new signature needed to be generated if the HTTP request was different. I had to test SQL injection manually by generating signatures with SoapUI but it should be possible to generate a signature using command-line also.
Could a WS-Security feature be added to sqlmap?
Otherwise, is there a workaround to send a new WS-Security signature for each different request of sqlmap?

**Comment by stamparm** [comment]
1) Looking into (e.g.) https://www.soapui.org/soapui-projects/ws-security.html it doesn't look to "automatization"-friendly
2) This is case-specific, never reported as a potential feature here, thus closing this down
