### ISSUE TITLE
--double-check

### ISSUE THREAD

**Issue by hahahahahahahahahahahahahahahah** [sqlmapproject/sqlmap#4119]
double check the data is correct or not, like this: 
`--dbs`, and `--dbs --hex`
dumped: `test` and `74657374`
If the two are not the same, try again.

I just give an example. But you don't have to use that. (`--hex`

**Comment by hahahahahahahahahahahahahahahah** [comment]
I think this feature will be very useful for users with unstable networks.

**Comment by stamparm** [comment]
There is already a validation step (i.e. after inference, each char is checked literally with `...='<char>' `). There won't be thousands of more validation requests because in such case you and other users will nag that everything is slow

**Comment by hahahahahahahahahahahahahahahah** [comment]
oh ic...🤔
