### ISSUE TITLE
Clusters

### ISSUE THREAD

**Issue by ktjd123** [sqlmapproject/sqlmap#4122]
**Is your feature request related to a problem? Please describe.**
It's not about problem. It would be nice if there is clustered mode(maybe row based). since when use threaded mode on single machine there may be corrupt at value. 

since time-based blind injection is so slow to run on a machine. and most websites have IP based rate limits

**Describe the solution you'd like**
sqlmap clustered mode.

main sqlmap load-balance to clusters by request data.(maybe by row)

clusters do the request and have it as cache or save it temporary.

clusters send back to main sqlmap when fetching row is done or by some time based.

**Additional context**
Thank you. always appreciate everybody's work

**Comment by stamparm** [comment]
1) sqlmap is not "data-mining" software which should be "load-balanced"
2) if you require this kind of stuff, please do it manually (e.g. `--where` across different machines)
