### ISSUE TITLE
How to retrieve specific Data? Using WHERE 

### ISSUE THREAD

**Issue by tunkusalim** [sqlmapproject/sqlmap#4123]
for example, if the target has this data, and i want only retrieve data with **UserType** is **Admin** and skip others data with **UserType** is **User**

**Table Name: AuthUser**

UserType | Email | Password
------------ | ------------- | -------------
Admin | example@example.com | 123456
User | example@example.com | 123456
Admin | example@example.com | 123456
User | example@example.com | 123456
User | example@example.com | 123456
User | example@example.com | 123456
...

and the output result become

UserType | Email | Password
------------ | ------------- | -------------
Admin | example@example.com | 123456
Admin | example@example.com | 123456
...

someone said that you can use **--where="UserType='Admin' "** but i already tried it and its not working and cant retrieve anything.
and i tried **--sql-shell** with **SELECT UserType,Email,Password FROM AuthUser WHERE UserType='Admin'** but it is also not working, only showing **Retrieve:** for long time.

**Comment by stamparm** [comment]
A) `--where` is the proper way.
B) `but i already tried it and its not working and cant retrieve anything` <- I can't do this anything. I miss any kind of useful information

**Comment by tunkusalim** [comment]
A) if i use **--where**, is it gonna be **--where="UserType='Admin' "**? or what should i use for it?
B) ... <- it says "cant establish SSL connection" after, even if i used **--force-ssl**

**Comment by tunkusalim** [comment]
or is it possible just to skip the data with ** UserType** is **User**? so only **Admin** is retrieved

**Comment by stamparm** [comment]
A) you are most probably going to have the same problem/result (i.e. `--where="UserType!='User'`)
B) you have to properly debug this problem. as said, you haven't done anything to find out what is going on. i won't respond anymore to this issue until you do it

**Comment by tunkusalim** [comment]
so, does my command right? iam confused

> python sqlmap.py -u https://target.com/ --data "id=1" --cookie="app_cookie=abc1234" -D userDB -T AuthUser -C UserType,email,password --dump --where="UserType!='User'" --threads 5 

or is it wrong? if its wrong, what should i fix for it?
