### ISSUE TITLE
Oracle not fully supported (or too many false positives?)

### ISSUE THREAD

**Issue by llamatoes** [sqlmapproject/sqlmap#4125]
**Is your feature request related to a problem? Please describe.**
Oracle seems to not be fully supported (such as the older versions from 2006, or possibly new versions). I usually get a lot of positive heuristic tests which are false positives, or test manually when heuristics don't even detect anything. And yes, it is possible to inject manually when sqlmap can't do its job. (edit: it also always seems to find reflective values, weird)

**Describe the solution you'd like**
All versions of Oracle should be supported, or we could choose our own version if we disable automatic dbms version detection.

**Comment by stamparm** [comment]
All versions should be supported. This kind of "fuzzy" issues, where author claims that he knows "stuff", without any solid piece of information are semi-automatically being closed

**Comment by stamparm** [comment]
My last response here. "heuristic tests" are not full and/or reliable tests. They are **heuristics**
