### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by Ulalala1121** [sqlmapproject/sqlmap#4128]
Hello
when i try to inject the web i use sqlmap
I got a message
[16:56:46] [INFO] checking if the injection point on the GET parameter 'id' is a false positive
GET parameter 'id" is vulnerable. Do you want to keep testing the others (if any)? [y / n] y
sqlmap identified the following injection point (s) with a total of 862 HTTP (s) requests:
then it's written down that he's identifying it as false positive or not, right?
and what I want to ask is is my web vulnerable to SQL attacks? or only false positive?
I can see the DBMS version of SQLMAP too
oh and also my web is protected by WAF KONA

**Comment by stamparm** [comment]
You have KONA in between. Please continue the assessment manually
