### ISSUE TITLE
Unable to load request file

### ISSUE THREAD

**Issue by tbhaxor** [sqlmapproject/sqlmap#4129]
**Describe the bug**
The sqlmap couldn't find the request file. However it's there

**To Reproduce**
1. Save any request file
2. Pass the request file to sqlmap

**Expected behavior**
It should read the file and perform actions as expected

**Screenshots**

![image](https://user-images.githubusercontent.com/28386721/75711395-5b2e0000-5cec-11ea-875a-5832040acd75.png)

**Running environment:**
 - sqlmap version: 1.4#stable
 - Installation method: blackarch repository
 - Operating system: Arch Linux

**Target details:**
 ANY

**Comment by ELHARAKA** [comment]
Sometimes forgeting HTTP/1.1 will definitely cause this issue.

Eg:

"POST /login.php HTTP/1.1" = will be found
"POST /login.php" = will NOT be found

Otherwise, check your file request carefully, also some missing "/" can cause the same problem. Hope that helps.

**Comment by tbhaxor** [comment]
This is my request file
```
POST /api/user/login HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
	"username": "admin",
	"password": "admin"
}
```
When loaded in BurpSuite's repeater, its working

**Comment by stamparm** [comment]
![unrepro](https://user-images.githubusercontent.com/921555/75781438-76852380-5d5d-11ea-8d84-ce5e0723fa8f.png)

**Comment by radinmoradi** [comment]
در تاریخ سه‌شنبه ۳ مارس ۲۰۲۰،‏ ۱۷:۱۵ Miroslav Stampar <
notifications@github.com> نوشت:

**Comment by arty-hlr** [comment]
Maybe you could have added with your screenshot that the issue comes from the blackarch install and that installing from pip works for some reason.

**Comment by arty-hlr** [comment]
As reference: [this archlinux bug](https://bugs.archlinux.org/task/56287?project=0&order=id&sort=desc&string=sqlmap)

**Comment by arty-hlr** [comment]
#2472
