### ISSUE TITLE
Unable to force the back-end DBMS "InterSystems Cache"

### ISSUE THREAD

**Issue by ELHARAKA** [sqlmapproject/sqlmap#4130]
**Describe the bug**
I Can't force back-end database management system "InterSystems Cache"

**To Reproduce**
1. Run: python sqlmap.py -r target.txt --risk=3 --level=5 --flush-session --dbms="InterSystems Cache"
2. See error: [23:24:34] [CRITICAL] you provided an unsupported back-end database management system. Supported DBMSes are as follows: Altibase, Apache Derby, CrateDB, Cubrid, Firebird, FrontBase, H2, HSQLDB, IBM DB2, Informix, InterSystems Cache, Mckoi, Microsoft Access, Microsoft SQL Server, MimerSQL, MonetDB, MySQL, Oracle, PostgreSQL, Presto, SAP MaxDB, SQLite, Sybase, Vertica, eXtremeDB. If you do not know the back-end DBMS, do not provide it and sqlmap will fingerprint it for you.

**Expected behavior**
To force the back-end dbms.

**Running environment:**
 - sqlmap version: 1.4.2.42#dev
 - Installation method: git
 - Operating system: Microsoft Windows 10
 - Python version: 3.5.2

**Target details:**
 - DBMS InterSystems Cache
 - SQLi techniques found by sqlmap: OR boolean-based blind - WHERE or HAVING clause
 - WAF/IPS: NON

**Comment by ELHARAKA** [comment]
Note: I can force all the other dbms(s) such as MySQL & Microsoft Access with --dbms="MySQL" / --dbms="Microsoft Access"

**Comment by Hacklab3d-wq** [comment]
--dbms=Cache
