### ISSUE TITLE
header host

### ISSUE THREAD

**Issue by hahahahahahahahahahahahahahahah** [sqlmapproject/sqlmap#4135]
using this command: `--header "Host: xxx.com" -u "{ip}/index.php}`, I can test some cloudflare-protected site, but some how,in latest version I can't.... `[CRITICAL] page not found (404)` I tried a few different sites using `curl` and it works, but on sqlmap?... can't... so... it's a bug or? it's about me?...........

**Comment by hahahahahahahahahahahahahahahah** [comment]
```
python3 sqlmap.py --header "Host: hidden.com" -v 2 --null-connection --tor -u "{ip}/news/hidden.php?id=38" -p id --level 5 --risk 1 --delay 0.1 --time-sec 15 --unstable --sqlmap-shell --random-agent --drop-set-cookie --tamper varnish,../../hidden/hidden.py,multiplespaces
--tor --dbs -v 3
```

**Comment by stamparm** [comment]
1) You are using Tor for accessing Cloudflare sites? I would say that you have a non-sqlmap problem here
2) Please, in future provide a solid example how to reproduce the "issue"

**Comment by hahahahahahahahahahahahahahahah** [comment]
no... u don't get it... maybe next time...
