### ISSUE TITLE
How to do SQLmap on param that have value of json that has been encoded to base64 value

### ISSUE THREAD

**Issue by kd3vhck** [sqlmapproject/sqlmap#4137]
Hi guys, I want to ask a question regarding of SQL map scan.
Do we have the way to scan param JSON that has been encoded to base64?

**CASE**
GET /v/something?param=W3siaWQiOiIxMjM0NSIsInN0YXR1cyI6IlBlbmRpbmcifV0=

Normal Json before encoded:
[{"id":"12345","status":"Pending"}]

What I really want to test is the JSON inside it with ID and status param.
For example:
[{"id":"**12345***","status":"**Pending***"}]

How to do it? please help

**Comment by hahahahahahahahahahahahahahahah** [comment]
`--base64`?

**Comment by stamparm** [comment]
@kd3vhck 

1) Please update to the latest revision
2) Retry it with (e.g.) `python sqlmap.py -u "<target>/?param=W3siaWQiOiIxMjM0NSIsInN0YXR1cyI6IlBlbmRpbmcifV0=" --base64=param --answers="deserializable=y" --batch`

p.s. example run:

![test](https://user-images.githubusercontent.com/921555/76779820-43568180-67ac-11ea-9742-19c639fd5eee.png)

**Comment by fgeek** [comment]
@stamparm Would be awesome if this was documented to manual pages.

**Comment by stamparm** [comment]
@fgeek done (https://github.com/sqlmapproject/sqlmap/wiki/Usage#declare-parameters-containing-base64-encoded-data)

**Comment by stamparm** [comment]
@Phoenix1112 because you tried to injection into the "flat-array", something that sqlmap is/was not keen to do. With the latest revision, you should be able to do it

**Comment by fgeek** [comment]
> If it is in the base64 path section, how can we use it?
> 
> example: `target.com/path/W3siaWQiOiIxMjM0NSIsInN0YXR1cyI6IlBlbmRpbmcifV0=/path`

Use * or write a custom plugin.
