### ISSUE TITLE
Ok so this is more of a can u help me and maybe i can help you

### ISSUE THREAD

**Issue by devcoinfet** [sqlmapproject/sqlmap#4138]
I am used to using sqlmap for  using sql injection against things like login forms etc and for the most part it seems to work quite well. I have noticed on several occasions it will fail to parse correctly but somehow you are automating the scraping of ids of forms and parsing them I didn't bother diving in to far as this is a beast of software and very good.  Reason being I wanted to reach out and see if You had this in a certain module and could explain to me the basic logic your using and maybe I could take a look see if I can get the parsing of allot more forms working as things like selenium and phantom js are out of scope of my project id like to keep this python if possible without needs for addins.

**Comment by devcoinfet** [comment]
Reason being is I wrote my own custom vulnerability scanner and am almost complete and I'm missing post form fuzzing and its killing me I wont be selling it and will likely be open source I made it to hunt bounties and learn and help with finding things on a pen test at work etc

**Comment by stamparm** [comment]
Not sure what was this all about. Please take a look i to the source code (crawler.py and findPageForms())

**Comment by stamparm** [comment]
p.s. Please don't repeat this kind of "I could help you" fuzzy Issues here as those will be closed immediately

**Comment by devcoinfet** [comment]
ya thanks for the answer but there was 0 reason for the attitude considering if you couldnt figure out what i was saying u answered the question i asked thanks for the answer i like you wont be rude.
