### ISSUE TITLE
Proxy argument can't work

### ISSUE THREAD

**Issue by driftingdream** [sqlmapproject/sqlmap#4148]
**Describe the bug**
`sqlmap -u "http://localhost/DVWA/vulnerabilities/sqli/?id=1&Submit=Submit#" --cookie="security=low; PHPSESSID=c146a89dfe37598eb10b89af0934201d" --batch --flush-session --fresh-queries --proxy="http://127.0.0.1:8080"`
As shell command presented, I indicated the proxy location but the burp won't show anything while sqlmap worked just like normal, even when I modified 8080 port to other unworkable port the program still worked fine.
**To Reproduce**
1. Run `sqlmap -u "http://localhost/DVWA/vulnerabilities/sqli/?id=1&Submit=Submit#" --cookie="security=low; PHPSESSID=xxxxxxx" --batch --flush-session --fresh-queries --proxy="http://127.0.0.1:8080"`
2. See error
Like normal
**Expected behavior**
The proxy software should view the connection.

**Running environment:**
 - sqlmap version [1.4.3#stable]
 - Installation method [brew install sqlmap]
 - Operating system: [Mac OS]
 - Python version [3.7.7]

**Target details:**
 - DBMS [e.g. Microsoft SQL Server]
 - WAF/IPS [if any]
 - Relevant console output [if any]
 - Exception traceback [if any]

**Additional context**
I tried git clone the repository and use python3 to run the sqlmap, turning to the same result.

**Comment by driftingdream** [comment]
After posting this issue, I tried again but somehow it worked. Well, I'm confused.

**Comment by stamparm** [comment]
So, self-resolved :)
