### ISSUE TITLE
[CRITICAL] missing one or more core extensions ('bz2', 'gzip', 'ssl', 'sqlite3', 'zlib') most likely because current version of Python has been built without appropriate dev packages

### ISSUE THREAD

**Issue by qwerdi** [sqlmapproject/sqlmap#4154]
I do not speak English. I am from Belarus and speak Russian.

Sorry for the misunderstanding, i use google translator.

I downloaded sqlmap using github through git clone --depth 1 https://github.com/sqlmapproject/sqlmap.git

My version of Python is 2.7.14 and 3.7, but when I start Python it shows 
Python 2.7.14 (default, Mar 23 2020, 17:08:29)
[GCC 9.2.1 20191109] on linux2
Type "help", "copyright", "credits" or "license" for more information.

My operating system is Kali Linux.

if I write in the console "root @ root: ~ # sqlmap" I get an error ::
[16:55:32] [CRITICAL] missing one or more core extensions ('bz2', 'gzip', 'ssl', 'sqlite3', 'zlib') most likely because current version of Python has been built without appropriate dev packages

Version sqlmap 1.4.11 I do not remember exactly.

Qwerdi.

**Comment by stamparm** [comment]
You have lots of essential modules/extensions missing ('bz2', 'gzip', 'ssl', 'sqlite3', 'zlib'). Those are a "MUST" inside the Python installation. Please check your Python installation to deal with this problem.

Once you'll be able to do the following, you'll know that everything is "fixed":

```
$ python -c "import bz2; import gzip; import ssl; import sqlite3; import zlib" && echo "OK"
OK
```

**Comment by kakshafo** [comment]
The is my problem [15:00:57] [CRITICAL] missing one or more core extensions ('ssl') most likely because current version of Python has been built without appropriate dev packages please help me

**Comment by stamparm** [comment]
> The is my problem [15:00:57] [CRITICAL] missing one or more core extensions ('ssl') most likely because current version of Python has been built without appropriate dev packages please help me

https://github.com/sqlmapproject/sqlmap/issues/4154#issuecomment-604463321

**Comment by kakshafo** [comment]
> 

Not run why in termux android 👇

Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'sqlmap' is not defined

**Comment by 2d00r** [comment]
I tried to install al the modules/extension but it s always an error like this:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.10/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: dlopen failed: library "libssl.so.3" not found: needed by /data/data/com.termux/files/usr/lib/python3.10/lib-dynload/_ssl.cpython-310.so in namespace (default).

**Comment by Baban9509** [comment]
[CRITICAL] missing one or more core extensions ('ssl') most likely because current version of Python has been built without appropriate dev packages



What the solution?? Can you tell me please 🥺
