### ISSUE TITLE
[ 1 ]  <PID number> bash: --tables: command not found

### ISSUE THREAD

**Issue by Vampire420** [sqlmapproject/sqlmap#4159]
i have a problem while setting a sqlmap command:
$ sqlmap -u https://example.com/something.php?id=number --tables
[ 1 ] PID number
bash: --tables: command not found
and then i see the process of sqlmap i can stop only be restarting the terminal

**Comment by hos903** [comment]
try sqlmap -u "https://example.com/something.php?id=number" --tables

**Comment by Vampire420** [comment]
@hos903 yeah working.. thanks.. but not sure why the exactly same command (without quotes)
works a few times with no problem and then without any warning jumps --tables command not found.. any suggestions?
