### ISSUE TITLE
I need help with sqlmap

### ISSUE THREAD

**Issue by Riviver** [sqlmapproject/sqlmap#4161]
I'm getting error 400 (Bad Request), I don't know what to do. Discord: Riviver#2870
![download](https://user-images.githubusercontent.com/63429967/78947667-eb1a5300-7abd-11ea-9a49-4383e5f0a1e7.png)

**Comment by stamparm** [comment]
You haven't filled Issue template nor provided any usable data. Also, you haven't mentioned if there was a warning of WAF being detected at start of sqlmap run

**Comment by Riviver** [comment]
So what should I do?

**Comment by Riviver** [comment]
There was a waf detected in the start yes

**Comment by stamparm** [comment]
So, that's the reason for 400s. In that place you are on your own. Not a sqlmap issue

**Comment by Riviver** [comment]
where can i get help?
