### ISSUE TITLE
tamper add about modsec

### ISSUE THREAD

**Issue by hahahahahahahahahahahahahahahah** [sqlmapproject/sqlmap#4164]
https://github.com/Ekultek/WhatWaf/blob/master/content/tampers/modsec.py

https://github.com/Ekultek/WhatWaf/blob/master/content/tampers/modsecspace2comment.py

**Comment by hahahahahahahahahahahahahahahah** [comment]
I tried, and I thought that u need to use modsec(sqlmap) tamper + charencode, to bypass modsec, if u use modsec tamper only, u can't get inside...

**Comment by stamparm** [comment]
That guy blatantly stole every tamper script from sqlmap. I don't see what's the point of this issue
