### ISSUE TITLE
--disable-coloring still produces colored output

### ISSUE THREAD

**Issue by darussian777** [sqlmapproject/sqlmap#4165]
latest release sqlmap, even though --disable-coloring is set it produces ^M in the output

**Comment by stamparm** [comment]
Can you please provide full details? Command line options used together with the screenshot.

Also, you've stated that you've used `--disble-coloring`, which is a misspell which doesn't work

**Comment by stamparm** [comment]
1) Linux:

![1](https://user-images.githubusercontent.com/921555/79389953-265dcb80-7f6f-11ea-91a6-55e2b2645be8.png)

2) Windows:

![2](https://user-images.githubusercontent.com/921555/79389986-31b0f700-7f6f-11ea-9c48-c7de5d2f2eab.png)

**Comment by darussian777** [comment]
./sqlmap/sqlmap-dev/sqlmap.py --disable-coloring -u http://github.com > output 2>&1
[
![Screen Shot 2020-04-16 at 6 48 26 PM](https://user-images.githubusercontent.com/62406643/79477525-f962f480-8012-11ea-9541-e221b524f8b4.png)
](url)

**Comment by darussian777** [comment]
screenshot is generated with less. cat is able to process escape sequences, so it will not show them

**Comment by stamparm** [comment]
@darussian777 with the latest revision you'll be able to do it, even without `--disable-coloring`

**Comment by darussian777** [comment]
thanks man, cheers!
