### ISSUE TITLE
CloudFlare WAF Tamper ?

### ISSUE THREAD

**Issue by nctrl1** [sqlmapproject/sqlmap#4166]
Is there a tamper to bypass CloudFlare ? CloudFlare does not allow you to get the database and tables.

**Comment by stamparm** [comment]
Sorry, but no. Each case is specific (e.g. in some cases there is no Cloudflare protection at all, in some there is only Cloudflare blocking requests, in some cases there is a chain of Cloudflare and target's WAF, etc.). You'll have to manually find a way, if any, how to bypass it.
