### ISSUE TITLE
how to test parameter like this ? 

### ISSUE THREAD

**Issue by italy2010** [sqlmapproject/sqlmap#4168]
```

POST /settablefromemptytables HTTP/1.1
Host: 1.1.1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Content-Length: 9
Origin: http://1.1.1.1
DNT: 1
Connection: close
Referer: http://1.1.1.1/
Cookie: cons=s%3ANqUDd6JKxBKabDfr93s4BF6-gY38hytR.63acekJIBsMa2ui8EQvDepJwHkc87K31qJgTUNdLD9g; sfcon=391ec775d72aabaddb8bb7e09295eb14

{"tb":1}
```

seem burp cannot find this parameter.

**parameter is "{"tb":1}"**  and **1** is vulnerable

[23:57:47] [CRITICAL] all testable parameters you provided are not present within the given request data

**Comment by hahahahahahahahahahahahahahahah** [comment]
`--answer "json=y" -p tb` ?

**Comment by stamparm** [comment]
1) I really don't know which version of sqlmap are you running
2) sqlmap normally chews this request. Also, there is no need to use that `--answer` as sqlmap by default processes JSON data (i.e. answer is already `Y` by default)
2) Burp? This seems like a Burp's issue

**Comment by italy2010** [comment]
i use {1.4.4.2#dev} version of sqlmap.

i just copy data from burp to .txt file and used -r parameter in sqlmap for reading txt file.

**Comment by stamparm** [comment]
Then you are doing something wrong as I am not able to reproduce the issue:

![123](https://user-images.githubusercontent.com/921555/79809141-1596c680-8370-11ea-88e1-5c89d2294d8e.png)
