### ISSUE TITLE
Remove/Skip Duplicated Hashes

### ISSUE THREAD

**Issue by ELHARAKA** [sqlmapproject/sqlmap#4172]
During the password crack process, it's realy time consuming when SQLMAP crack duplicated hashes seperately which takes long hours (when using custom & huge wordlist - +3GB)

E.g:
```
[13:55:37] [INFO] recognized possible password hashes in columns 'passtest1, `passtest2`'
n
do you want to crack them via a dictionary-based attack? [Y/n/q]

[13:58:40] [INFO] using hash method 'sha1_generic_passwd'
[13:58:40] [INFO] using hash method 'md5_generic_passwd'
[13:58:40] [INFO] resuming password '1234' for hash '7110eda4d09e062aa5e4a390b0a572ac0d2c0220'
what dictionary do you want to use?
[1] default dictionary file '/mnt/c/python36/Lib/sqlmap-dev/data/txt/wordlist.tx_' (press Enter)
[2] custom dictionary file
[3] file with list of dictionary files
> 2
what's the custom dictionary's location?
> /mnt/c/python36/Lib/sqlmap-dev/data/txt/wordlist.txt
[13:58:56] [INFO] using custom dictionary
do you want to use common password suffixes? (slow!) [y/N] N
[13:58:59] [INFO] starting dictionary-based cracking (sha1_generic_passwd)
[13:58:59] [INFO] starting 2 processes
[14:22:16] [INFO] cracked password 'Aa123456' for hash '3a960464d36c1b8bad183ed57ee79c0e39953cce'
[20:08:45] [INFO] cracked password 'Aa123456' for hash '3a960464d36c1b8bad183ed57ee79c0e39953cce'
[21:04:18] [INFO] current status: Merke... /
```

It will be much better and time saving if SQLMAP check & removes the duplicated hashes before the cracking process starts

As i mentiend, the first option is to check for duplicated hashes before starting the crack process OR there is another option which is during the cracking process when SQLMAP crack some hash let's say this one "3a960464d36c1b8bad183ed57ee79c0e39953cce"

`[14:22:16] [INFO] cracked password 'Aa123456' for hash '3a960464d36c1b8bad183ed57ee79c0e39953cce'`

After cracking the first hash, let's say we have the same hash next to this one, SQLMAP should detect that this hash is previously cracked and show something like this:

`[14:22:17] [INFO] Skipping hash '3a960464d36c1b8bad183ed57ee79c0e39953cce' as it's already cracked 'Aa123456'`

Thanks to all SQLMAP Devs.

**Comment by stamparm** [comment]
Unable to reproduce. You've just made a "generalization", where claiming that sqlmap is not doing de-duplication, while in reality it is doing it. 

---

I've made a testing case with couple of dummy duplicates and couldn't reproduce the results:

![3](https://user-images.githubusercontent.com/921555/80309521-e0f29700-87d5-11ea-9ac4-9499c138f973.png)

---

p.s. please find out what's "special" about your case and report back so I could reproduce it
p.p.s. double checked the de-duplication inside the code and it looks fine. Either you are using some old version of sqlmap or there is something special about your case

**Comment by ELHARAKA** [comment]
Using the latest version, always making sure to run an update before start using sqlmap.

After trying to find out whats happening I confirm that this issue is not SQLMAP issue but the wordlist.

In order for SQLMAP to check for hash duplications, the wordlist must be a compressed text file (.TX_) while in my case i used a normal (.txt) file.

that's sounds strange but yeah that's what is it.

Thanks Stam.

**Comment by stamparm** [comment]
p.s. deduplication of wordlist costs more than the current state. Fun fact is that sqlmap didn't do a repetition of a cracked hash, BUT as the wordlist is split in different processes, duplicate entries of your wordlist appeared in different processes. Thus, `crack duplicated hashes seperately which takes long hours` is simply not true
