### ISSUE TITLE
Parsing only 3 links when there are more than 1k

### ISSUE THREAD

**Issue by KarimCool** [sqlmapproject/sqlmap#4173]
![jjj](https://user-images.githubusercontent.com/25013189/80288405-0c26a900-8738-11ea-8a80-9fa44d6f2745.PNG)

**Comment by stamparm** [comment]
I would need more information (usually I just close these kind of issues instantly as there is 0 useful information inside - also, you've just skipped filling of the issue template). There is a huge possibility that you are having same named parameters across different urls/links. sqlmap just cleans those out.

**Comment by stamparm** [comment]
at the end decided to close this one until you give anything useful

**Comment by stamparm** [comment]
You most probably have the following "problem":

![111](https://user-images.githubusercontent.com/921555/80308950-14cbbd80-87d2-11ea-9696-e443595ffc37.png)

In those kind of cases, sqlmap just cleans those targets where there are no parameters to inject. Thus, if you want to use those, you should make sqlmap "find" anything useful there. For that you have to use `--crawl` and/or `--forms`, along with `-m` so sqlmap could ACTUALLY do something with those "targets

**Comment by KarimCool** [comment]
yeah it was because my urls were invalid my bad thanks dude
