### ISSUE TITLE
Error ocurred while trying to update

### ISSUE THREAD

**Issue by AmericanY** [sqlmapproject/sqlmap#4176]
@stamparm Hello, am using `Ubuntu Server 20.04`

Steps taken:

```
cd /opt/
sudo git clone --depth 1 https://github.com/sqlmapproject/sqlmap.git A
sudo ln -s /opt/A/sqlmap.py /usr/bin/1
```

Issue:

```
1 --update
```

Output:

![image](https://user-images.githubusercontent.com/27644047/80321489-b0365000-881d-11ea-8529-376f58a2a87d.png)

Thanks in advance.

Waiting for your feedback.

**Comment by AmericanY** [comment]
https://github.com/sqlmapproject/sqlmap/issues/541

**Comment by stamparm** [comment]
1) I can't describe what you are doing without using harsh words. Thus I'll just skip it
2) Using `sudo git...` and then raising the issue that you can't update is beyond my comprehension
3) Example of what you were trying to do, but inside a non-root environment (e.g. you can do the same inside your home directory):

![123](https://user-images.githubusercontent.com/921555/80375049-eca69200-8897-11ea-8cbe-521e45258eb5.png)

4) If you want to put sqlmap inside the `/opt` I would do something as follows:

```
cd /tmp
git clone --depth 1 https://github.com/sqlmapproject/sqlmap.git
sudo mv sqlmap /opt
sudo ln -s /opt/sqlmap/sqlmap.py /usr/local/bin/sqlmap
sqlmap --update
```
