### ISSUE TITLE
Using sqlmap as python library, is that possible?

### ISSUE THREAD

**Issue by javixeneize** [sqlmapproject/sqlmap#4177]
Hi

Is it possible to use sqlmap as a python library to be called directly from other python scripts, or is it only a CLI tool?

Thanks

**Comment by stamparm** [comment]
Duplicate of #2968

**Comment by javixeneize** [comment]
Thanks. It means that it is still not available to be used as a dependency. Is this something you might consider in the future?

**Comment by stamparm** [comment]
Sorry, but no. The same thing(s) apply as in the referenced Issue
