### ISSUE TITLE
Possibility to skip urls when scanning a list of urls

### ISSUE THREAD

**Issue by KarimCool** [sqlmapproject/sqlmap#4178]
When a url gives too much errors sqlmap ask me if I want to continue or not but when you choose no it doesn't continue the scan and instead stop the process completely and I would like it to not be the case. I would like the possibility to have the option to skip the url instead so I can continue and not start over thanks

**Comment by stamparm** [comment]
You didn't write the exact message sqlmap tells you, so I had to guess to do the "patch". I hope I guessed

**Comment by KarimCool** [comment]
hm sorry i'm a beginner so I don't really know how to use the patch ?

**Comment by stamparm** [comment]
@KarimCool just pull the latest revision. I don't know anything about your installation AS you've just skipped the issue template. Now I won't do any more guessing
