### ISSUE TITLE
Does SQLMapAPI work with json body in post requests?

### ISSUE THREAD

**Issue by javixeneize** [sqlmapproject/sqlmap#4180]
Hi

I have seen that using the CLI, it automatically detects when the body you are sending is a json request, but, for the API, would it also work?

Im currently calling the API using python requests library as follows:

data = {'url': 'https://juice-shop.herokuapp.com/rest/user/login', 'data': '{"email":"test@test.com","password":"1234"}'}

requests.post(scan_url, headers=headers, data=data)

And it does not seem to work. 

Do you have any example on how should i call the API with a json body in a post request?

Thanks

**Comment by stamparm** [comment]
Have you tried to debug your case? Have you tried to actually run it inside the sqlmap?

![1234](https://user-images.githubusercontent.com/921555/80611872-7b9fdf80-8a3b-11ea-8e5d-923b92b61d51.png)

p.s. `--ignore-code=401` should be used in such cases, but I am not sure that you are targeting a right spot in this target

**Comment by javixeneize** [comment]
Hi. Yes, this is what i was saying. In the CLI it works, but in the API it doesnt return any error or any info. Is it working in the API?

On top of that, i agree this is not a feature request. Maybe it also makes sense to enable another category for questions?

Thanks

**Comment by stamparm** [comment]
My last message because the statement `In the CLI it works, but in the API it doesnt return any error or any info. Is it working in the API?` is simply not true:

![444](https://user-images.githubusercontent.com/921555/80613134-28c72780-8a3d-11ea-9c47-7bb3311d5170.png)

**Comment by javixeneize** [comment]
Hi

Sorry to bother you again, but im still having problems with the API when i send JSON data in the post

Using plain sqlmap, i use this:

python sqlmap.py -u http://localhost:8081/challenge1/loginjson --data '{"user": "javi", "password": "12345"}'

And it asks me if i want to send the request as a JSON file and it works well

Using the API, i do this:

curl  -H "Content-Type: application/json" -X POST -d '{"url": "http://localhost:8081/challenge1/loginjson", "data": {"user": "javi", "password": "12345"}, "headers": "Content-Type: application/json"}' localhost:8775/scan/fb76a1ccafc2a2d7/start

And, although the API performs the sqlmap scan, instead of sending the data as a json, it sends it as plain text

Is there any way of specifying in the curl request that this is a JSON?

Thanks
