### ISSUE TITLE
-g bug?

### ISSUE THREAD

**Issue by hahahahahahahahahahahahahahahah** [sqlmapproject/sqlmap#4182]
it should search forms, right?...
```
... -g "hidden" --form --chunk
```
```
[INFO] using search result page #1
[CRITICAL] Google has detected 'unusual' traffic from used IP address disabling further searches
no usable links found. What do you want to do?
[1] (re)try with DuckDuckGo (default)
[2] (re)try with Bing
[3] quit
>
found 17 results for your search dork expression, but none of them have GET parameters to test for SQL injection. Do you want to skip to the next result page? [Y/n] n

sqlmap-shell>
```

**Comment by fgeek** [comment]
What are you trying to do exactly? From manual:

```
    -g GOOGLEDORK       Process Google dork results as target URLs
```

**Comment by hahahahahahahahahahahahahahahah** [comment]
> What are you trying to do exactly? From manual:
> 
> ```
>     -g GOOGLEDORK       Process Google dork results as target URLs
> ```

(https://images-na.ssl-images-amazon.com/images/I/91bZCsPBqML._SY500_.jpg)[https://images-na.ssl-images-amazon.com/images/I/91bZCsPBqML._SY500_.jpg]

**Comment by stamparm** [comment]
@hahahahahahahahahahahahahahahah i did the update that should suite your needs, but i won't do anything more regarding it because of your abusive behavior toward @fgeek
