### ISSUE TITLE
Does not run in Windows

### ISSUE THREAD

**Issue by thevalo** [sqlmapproject/sqlmap#4185]
**Describe the bug**
When starting sqlmap.py through cmd (python sqlmap.py) it doesn't produce any output. When doing the same via python IDE, produces error.

**To Reproduce**
1. Run sqlmap.py through Py IDE or cmd Windows
2. See error

**Expected behavior**
To see the initial help page?

**Running environment:**
 - sqlmap version: 1.4.5
 - Installation method: git
 - Operating system: Win10 x64
 - Python version: 3.8.2 and 2.7

**Additional context**
`Traceback (most recent call last):
  File "C:\Users\X\Desktop\s\sqlmap-dev\sqlmap.py", line 42, in <module>
    from lib.core.data import logger
  File "C:\Users\X\Desktop\s\sqlmap-dev\lib\core\data.py", line 9, in <module>
    from lib.core.log import LOGGER
  File "C:\Users\X\Desktop\s\sqlmap-dev\lib\core\log.py", line 22, in <module>
    from thirdparty.ansistrm.ansistrm import ColorizingStreamHandler
  File "C:\Users\X\Desktop\s\sqlmap-dev\thirdparty\ansistrm\ansistrm.py", line 11, in <module>
    from lib.core.settings import IS_WIN
  File "C:\Users\X\Desktop\s\sqlmap-dev\lib\core\settings.py", line 252, in <module>
    IS_TTY = os.isatty(sys.stdout.fileno())
io.UnsupportedOperation: fileno`

**Comment by stamparm** [comment]
https://stackoverflow.com/a/31081957

**Comment by stamparm** [comment]
While with the latest commit the crash should be "patched", I strongly believe that you are doing something really wrong. Regular `python sqlmap.py` should do fine

**Comment by thevalo** [comment]
Issue fixed after getting the latest version from #4185 patch. Thanks.
