### ISSUE TITLE
help me:Invalid -- DBMS-cred in MSSQL?

### ISSUE THREAD

**Issue by cnokzz** [sqlmapproject/sqlmap#4186]
mssql: --dbms-cred=sa:123456  --sql-shell  error
Is MSSQL not supported？
Is there any hope to achieve this function？

**Comment by stamparm** [comment]
Related to #34 (duplicate)

Anyhow, not optimistic as MSSQL/`OPENROWSET` is not quite friendly in refactoring of that `SELECT * FROM OPENROWSET...` to a something useful for generic SQLi point of view (i.e. if column names are not known)
