### ISSUE TITLE
SqlmapAPI docker image

### ISSUE THREAD

**Issue by javixeneize** [sqlmapproject/sqlmap#4190]
Hi

Just to let you know i have built a docker image that exposes sqlmapapi, just in case you want to add it to your project, i can share the Dockerfile with you

It can be found here --> https://hub.docker.com/r/javidr/sqlmapapi

**Comment by stamparm** [comment]
Thank you. I am not planning to include it. Nevertheless, somebody Googling this kind of stuff could use it like:

```
sudo su  # if docker requires sudo privileges
docker pull javidr/sqlmapapi
docker run -it -p 8775:8775 javidr/sqlmapapi
```
