### ISSUE TITLE
 [CRITICAL] missing one or more core extensions ('ssl') most likely because current version of Python has been built without appropriate dev packages

### ISSUE THREAD

**Issue by xsser** [sqlmapproject/sqlmap#4193]
**Describe the bug**
 [CRITICAL] missing one or more core extensions ('ssl') most likely because current version of Python has been built without appropriate dev packages

**To Reproduce**
1. Run 'sqlmap'
2. See " [CRITICAL] missing one or more core extensions ('ssl') most likely because current version of Python has been built without appropriate dev packages"

**Screenshots**

**Running environment:**
 - sqlmap version [e.g. 1.4.x#dev]
 - Installation method :brew
 - Operating system: mac os
 - Python version 3.7

**Comment by stamparm** [comment]
1) Not a sqlmap bug. Your Python installation is missing `ssl` which basically prevents any kind of `HTTPS` communication.
2) Please Google for `python 3.7 mac missing ssl` to find potential workarounds

**Comment by xsser** [comment]
Thanks
