### ISSUE TITLE
I get mistakes wrong installation detected (missing modules). Visit 'https://github.com/sqlmapproject/sqlmap/#installation' for further details

### ISSUE THREAD

**Issue by jfjjjdi** [sqlmapproject/sqlmap#4195]

**Comment by fgeek** [comment]
What is the problem exactly? How did you install sqlmap?

**Comment by jfjjjdi** [comment]
> What is the problem exactly? How did you install sqlmap?

I want to run on ios, I've installed python, but when I enter ：python sqlmap-u ，I get the following mistakes “wrong installation detected (missing modules). Visit
'https://github.com/sqlmapproject/sqlmap/#installation' for further details”How to solve this problem, can't it run on the iOS system?

**Comment by fgeek** [comment]
Could you give me the censored version of full command line, thanks? You can also contact me henri+sqlmap@nerv.fi if it is easier (i'm not developer).

**Comment by stamparm** [comment]
@jfjjjdi https://stackoverflow.com/a/58280749
