### ISSUE TITLE
Add a version endpoint to SQLMap API

### ISSUE THREAD

**Issue by smoyer64** [sqlmapproject/sqlmap#4204]
**Is your feature request related to a problem? Please describe.**

I need to execute a client application on many machines and need a way to make sure the `sqlmapapi.py` server is the correct version before using some of the options (that have changed between versions).

**Describe the solution you'd like**

Please add a `/admin/version` endpoint that returns the version of SQLMap installed.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by stamparm** [comment]
`/version` is added instead of `/admin/version`

![aaa](https://user-images.githubusercontent.com/921555/82451002-b7175200-9aad-11ea-8a00-c1099d5e27b5.png)

**Comment by smoyer64** [comment]
Awesome! ... thanks so much!
