### ISSUE TITLE
-search Help

### ISSUE THREAD

**Issue by fanatos123** [sqlmapproject/sqlmap#4210]
used to search for columns -search -C mail ! Please tell me how to find in the base columns = an example of this particular TEST@MAIL.COM ?

**Comment by fanatos123** [comment]
how to search by example TEST@MAIL.COM inside columns ?

**Comment by stamparm** [comment]
A) `--where "email=TEST@MAIL.COM"` for particular column `email`
B) there is no way to do it on all columns
