### ISSUE TITLE
SQLmap not Direct Connect, even with pymysql

### ISSUE THREAD

**Issue by iii235** [sqlmapproject/sqlmap#4213]
I just downloaded pymysql and installed, but direct connect still doesn't work.

**Comment by stamparm** [comment]
0 (zero) useful information. Issue template skipped. I am not able to reproduce it:

A) Python2

![python2](https://user-images.githubusercontent.com/921555/83029789-5d75d100-a033-11ea-8fb7-46f7a00b9d7c.png)

B) Python3

![python3](https://user-images.githubusercontent.com/921555/83029801-61a1ee80-a033-11ea-8605-a05613472eec.png)

p.s. I am locking down this conversation as I know for fact that you'll reply with "but I am running on Windows and this is not what I..." <- while in the same time couldn't care less about the Issue template
