### ISSUE TITLE
Regular Expression DoS vulnerability in third-party script

### ISSUE THREAD

**Issue by IncyLiu** [sqlmapproject/sqlmap#4220]
**Describe the bug**
We are working on the [ReDoS](https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS) problem and detected a vulnerable regex from your code.

Regex `\001?\033\\]((?:.|;)*?)(\x07)\002?` in [link](https://github.com/sqlmapproject/sqlmap/tree/master/thirdparty/colorama/ansitowin32.py) takes forever to match the string
`"\u001B];;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n"`
This is because two branches in `(?:.|;)` can both match the character `;`, we suggest you to just remove the later one.

We didn’t create a pull request because we're not sure if these cases are possible to take place in your program, we also do not understand the functionality of the regex as you do. Thank you for your understanding.

**Comment by stamparm** [comment]
1) This is a thirdparty module (as you can see, the path is `thirdparty/colorama/ansitowin32.py`
2) To actually reach this piece of code, sqlmap should output the "problematic" string to the console on Win32 (highly unlikely - but I won't judge this)
3) Out of curiosity and fun, did the example you provided:

```
$ python
>>> import re
>>> import time
>>> start=time.time(); re.search("\001?\033\\]((?:.|;)*?)(\x07)\002?", "\u001B];;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n"); end=time.time()
>>> print end-start
0.000715017318726
>>> 

```

Closing this down as invalid

**Comment by stamparm** [comment]
https://github.com/tartley/colorama/issues/247
