### ISSUE TITLE
Improving --csrf-token / --csrf-url workflow

### ISSUE THREAD

**Issue by andrei-dascalu** [sqlmapproject/sqlmap#4222]
**Is your feature request related to a problem? Please describe.**
I have a situation where a website a work on uses csrf token for each request. While there is a url from where the token can be obtained, it is a POST request (in fact a page would obtain a form, including hidden field with csrf token, via an async JS POST request / ajax).
In this case, no matter what URL I provide as a csrf-url, it doesn't work:
- if I provide the front-facing URL, the field isn't there at the time of a GET request since it's loaded asynchronously
- if I provide the URL which actually contains the csrf field, it won't work because it's a POST (also, since the site uses Strict cookie policy, a POST request can't fix a session)

**Describe the solution you'd like**
It would be great if there would be a way to specify the method for the csrf-url (as well as possibly a payload to get it working). 

**Describe alternatives you've considered**
I am not sure about possible alternatives as I haven't studied the internals of sqlmap (just started using it). Some alternatives (that may or may not be realistic workarounds)
- can sqlmap load content request asynchronously following a request (as a browser)?

**Comment by stamparm** [comment]
1) `Can sqlmap load content request asynchronously following a request (as a browser)?` <- no
2) You can force the usage of `POST` with `--csrf-method=POST`
3) This whole "asynchronously" stuff would require an independent setup as Selenium or similar. Also, this currently doesn't sound too "generic" to me for implementing
4) You can do some dirty work yourself. For example, inside the `lib/request/connect.py` (e.g. [here](https://github.com/sqlmapproject/sqlmap/blob/master/lib/request/connect.py#L1114)), you can provide the `token` by usage of such "external" mechanism to sqlmap so it could use it afterwards
