### ISSUE TITLE
sqlmap: error: missing a mandatory option 

### ISSUE THREAD

**Issue by Smug23** [sqlmapproject/sqlmap#4224]
sqlmap: error: missing a mandatory option (-d, -u, -l, -m, -r, -g, -c, --list-tampers, --wizard, --update, --purge or --dependencies). Use -h for basic and -hh for advanced help

[02:57:57] [WARNING] you haven't updated sqlmap for more than 63 days!!!
OS: Linux Obuntu 20.04
Additional Notes: i have tried everything but cannot seem to get rid of this error. i cannot update as i do not have the --update as it is missing. 
installation: sudo apt install sqlmap

**Comment by stamparm** [comment]
1) This entirely depends on the `apt` package maintainer. 
2) You can just do the following to easily get rid of this all:
```
sudo apt remove sqlmap
sudo pip install sqlmap
```

This will use PyPI - regularly updated repository - instead of APT

**Comment by stamparm** [comment]
p.s. dirty trick to get rid of the message - in case that the APT has been used for the installation:

`sudo touch /usr/share/sqlmap/lib/core/settings.py`
