### ISSUE TITLE
Virus in this Repo: Trojan found by Bit Defender

### ISSUE THREAD

**Issue by TJayanth** [sqlmapproject/sqlmap#4233]
**Describe the bug**
Once cloned Virus is found in the folder Backdoors

**To Reproduce**
1. Have Bit Defender installed
2. Clone from repo
3. You can see the virus
![Trojan](https://user-images.githubusercontent.com/16999306/84600218-63720b80-ae95-11ea-9e57-721debc881ed.png)

**Expected behavior**
DId not expect sqlmap to have virus in Repo

**Screenshots**
Screenshots attached

**Running environment:**
 - sqlmap version Latest version
 - Installation method git clone --depth 1 https://github.com/sqlmapproject/sqlmap.git sqlmap-dev
 - Operating system: Microsoft Windows 10
 - Python version 3.5.2

**Additional context**
Kindly address this ASAP

**Comment by TJayanth** [comment]
![image](https://user-images.githubusercontent.com/16999306/84600646-8baf3980-ae98-11ea-8bb4-947d1c7cd5b6.png)

I am getting a lot of such things..

**Comment by stamparm** [comment]
Will address this, but it is funny that those are marked as virus(es) as they contain a PURE unusable junk if used outside the sqlmap

**Comment by stamparm** [comment]
p.s. for outsiders, those files ARE not viruses, nor sqlmap will ever contain "virus" inside. Those same files are PHP/UDFs that are used in regular sqlmap work which somebody marked as "virus", even though their content contains a PURE junk if used outside the sqlmap
