### ISSUE TITLE
[CRITICAL] unable to read file '/usr/share/sqlmap/data/xml/banner/mysql.xml'

### ISSUE THREAD

**Issue by alvaroartano** [sqlmapproject/sqlmap#4236]
I get this error. Anyone can help me please?
`[CRITICAL] unable to read file '/usr/share/sqlmap/data/xml/banner/mysql.xml'`

**Comment by stamparm** [comment]
As you've just skipped the filling of issue template, I'll need to do the guessing here.

Please uninstall your version of sqlmap (e.g. `sudo apt uninstall sqlmap` <- guessing how you could do it) and retrieve the latest monthly version with `sudo pip install sqlmap`
