### ISSUE TITLE
Direct Connection to MSSQL Does not work

### ISSUE THREAD

**Issue by ZackInMA** [sqlmapproject/sqlmap#4237]
**Describe the bug**
Attempting to connect directly to an MSSQL database, following the documentation. Receive the error message:
[22:44:30] [CRITICAL] SQLAlchemy connection issue ('InterfaceError: (pyodbc.InterfaceError) ('IM002', '[IM002] [unixODBC][Driver Manager]Data source name not found, and no default driver specified (0) (SQLDriverConnect)')')     

**To Reproduce**
1. Run:
sudo sqlmap -d mssql://sa:TheSAPassword@ServerIPv4Address:1433/DBName

2. See error
22:44:30] [CRITICAL] SQLAlchemy connection issue ('InterfaceError: (pyodbc.InterfaceError) ('IM002', '[IM002] [unixODBC][Driver Manager]Data source name not found, and no default driver specified (0) (SQLDriverConnect)')')    

**Expected behavior**
SQL Map should connect to the MS SQL DB and allow me to interact with it, query it, enumerate it,  pass OS commands to it, etc. 

**Running environment:**
 - sqlmap version 1.4.6
 - Installation method: Included with Kali
 - Operating system: Kali Linux
 - Python version 3.8.3

**Target details:**
 - DBMS: Microsoft SQL Server 2016
 - SQLi techniques found by sqlmap N/A. Using direct connection
 - WAF/IPS: none - direct connection on LAN
 - Relevant console output: see above error
 - Exception traceback: see above error

**Additional context**
```
        ___
       __H__                                                                                                                                                                        
 ___ ___[,]_____ ___ ___  {1.4.6#stable}                                                                                                                                            
|_ -| . [']     | .'| . |                                                                                                                                                           
|___|_  [(]_|_|_|__,|  _|                                                                                                                                                           
      |_|V...       |_|   http://sqlmap.org                                                                                                                                         

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting @ 22:55:46 /2020-06-17/

[22:55:46] [DEBUG] cleaning up configuration parameters
[22:55:46] [CRITICAL] SQLAlchemy connection issue ('InterfaceError: (pyodbc.InterfaceError) ('IM002', '[IM002] [unixODBC][Driver Manager]Data source name not found, and no default driver specified (0) (SQLDriverConnect)')')                                                                                                                                         

[*] ending @ 22:55:46 /2020-06-17/
```

**Comment by stamparm** [comment]
1) Fixed with last revision. Switched SQLAlchemy driver from default "buggy" `pyodbc` (Note: requires special independent fine-tuning of its configuration settings) to `pymssql`
2) Nevertheless, you'll most probably need to additionally install `pymssql` (e.g. `sudo pip install pymssql`) <- it should be clear that the module is missing if SQLAlchemy fails like `[CRITICAL] SQLAlchemy connection issue ('ImportError: No module named pymssql')`

**Comment by tappoz** [comment]
With `sqlmap=1.5.3` and `pymssql==2.1.5`

When I do:

```
python sqlmap.py \
   -d "mssql://my_db_user@my_azure_db_name:my_password@my_azure_db_name.database.windows.net:1433/MyDbName" \
   --flush-session --batch
```

Then I see:

```
[CRITICAL] SQLAlchemy connection issue ('OperationalError: (pymssql.OperationalError) (20002, b'DB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (my_azure_db_name.database.windows.net)\n')')
```
The relevant bit: `DB-Lib error message 20002, severity 9: Adaptive Server connection failed`

I tried to downgrade `pymssql` to previous versions `2.1.1` and `2.1.2` as people on the internet claims those were working, however `pip` fails to install this package on Linux Ubuntu 20.04.

How do I connect to an Azure DB (Microsoft SQL Server in the cloud) with `sqlmap`?

**Comment by stamparm** [comment]
@tappoz if you provide me with credentials and connection details, I could debug it

**Comment by tappoz** [comment]
@stamparm :pray: thank you for the help - shall I use the email on your profile to send the credentials? We may need an IP to whitelist.
