### ISSUE TITLE
Easy SQL injection ignored

### ISSUE THREAD

**Issue by pdelteil** [sqlmapproject/sqlmap#4241]
**Describe the bug**
I've found a vulnerable website of a client, using `'or'1'='1` as username allows anyone to login. I did a complete scan with sqlmap using --level =5 --risk=3 and nothing.  It makes no sense that the easiest injection is not found. 

**To Reproduce**
1. Run sqlmap -v 3 --level=3 --risk=3 -u "http://URL:PORT/login"  --data="username=a&password=a" --method POST --tamper=apostrophemask,apostrophenullencode
2. No results

**Expected behavior**
Find an injection (‘OR’1’=‘1)

**Screenshots**
NA

**Running environment:**
 - sqlmap version 1.4.6.12#dev
 - Installation method git
 - Operating system: Ubuntu
 - Python version 2.7.18rc1

**Target details:**
 - DBMS MySQL
 - SQLi techniques found by sqlmap  NONE
 - WAF/IPS NONE
 - Relevant console output NA
 - Exception traceback [if any]

**Additional context**

**Comment by stamparm** [comment]
`OR` injections are not turned on by default. You have to use higher risk level (e.g. `--risk=3`)

**Comment by pdelteil** [comment]
> `OR` injections are not turned on by default. You have to use higher risk level (e.g. `--risk=3`)

Hello there,

Like I said on the description of the issue, I was using --risk=3 and --level=5 

I will find an example I could share here.

**Comment by stamparm** [comment]
I guess you have a WAF/IPS as you've decided to use tamper scripts in the first place. Thus, it is kind of silly from you to open an Issue named "Easy SQL injection ignored".

Nevertheless, you always have mechanisms such as `-t traffic.txt`, `-v 5` and/or `--parse-errors` which you could use to actually debug what is going on before opening the unclear Issue here

**Comment by pdelteil** [comment]
> I guess you have a WAF/IPS as you've decided to use tamper scripts in the first place. Thus, it is kind of silly from you to open an Issue named "Easy SQL injection ignored".
> 
> Nevertheless, you always have mechanisms such as `-t traffic.txt`, `-v 5` and/or `--parse-errors` which you could use to actually debug what is going on before opening the unclear Issue here

Why is it silly ? 

I will create a new one when I have more info.

**Comment by pdelteil** [comment]
> I guess you have a WAF/IPS as you've decided to use tamper scripts in the first place. Thus, it is kind of silly from you to open an Issue named "Easy SQL injection ignored".
> 
> Nevertheless, you always have mechanisms such as `-t traffic.txt`, `-v 5` and/or `--parse-errors` which you could use to actually debug what is going on before opening the unclear Issue here

I think is pretty rude to point that the creation of the issue is silly. Why don't you just delete it?

**Comment by stamparm** [comment]
`I think is pretty rude to point that the creation of the issue is silly` <- sorry for being honest. After solving over 4.2k issues here, I've developed a particular set of BOFH skills. Nothing personal.
