### ISSUE TITLE
Special character on Cookie was removed by sqlmap

### ISSUE THREAD

**Issue by hmadrwx** [sqlmapproject/sqlmap#4242]
**Describe the bug**

On authenticated request, when cookie value contains special char (in this case * char), this char will be removed by sqlmap before this request being send to target, hence the cookie will become invalid and the session will be invalid as well.
On my case, I have a target that has cookie : 

![image](https://user-images.githubusercontent.com/1428975/85409403-f561ce80-b58f-11ea-90f1-7703a3dbd3d2.png)

When this request being sent by sqlmap, the * chars on this cookie was removed and become like this: Cookie: rpapp_cookie=Fe26.23b57b5d05cb2908846e32a314e42640a1a3f88f2b5ae009eed0455a274c4edf4zVA98j1VCDJ9tsxxg1n1eAt3yxKsnhOftJcFelZdBCcDeUpSZxsMGKllo2RUrY-80DGsrU7ITblgycgQiTZVRh4dfdadd292fe4e1994854c3fc5ff5abcf8b10904654aa78badbba8d8b831235d9kOQjlettBj-NBVM91KD_uSK7VAH5nwvHvEtsGuE8Xc
Notice that all * on the cookie was removed.

**To Reproduce**
1. Run 'sqlmap.py -u "testphp.vulnweb.com/artists.php?artist=1" --cookie "admin=abc*123*456**789" -v 5'
2. See traffic out (HTTP Request), cookie value will become:
Cookie: admin=abc123456789

**Expected behavior**
Cookie value is important for authenticated sql injection attack, and on some cases it will contains special characters.

**Screenshots**
![image](https://user-images.githubusercontent.com/1428975/85409142-a2881700-b58f-11ea-80d9-3f49a67b1088.png)

**Running environment:**
 - sqlmap version [1.4.6.12#dev]
 - Installation method [git]
 - Operating system: [Microsoft Windows 10]
 - Python version [2.7.13]

**Comment by sanitizer342343** [comment]
use single quote instead:
sqlmap -u "testphp.vulnweb.com/artists.php?artist=1" --cookie 'admin=abc123456**789' -v 5

**Comment by hmadrwx** [comment]
> 
> 
> use single quote instead:
> sqlmap -u "testphp.vulnweb.com/artists.php?artist=1" --cookie 'admin=abc123456**789' -v 5

![image](https://user-images.githubusercontent.com/1428975/85514727-88e5de80-b626-11ea-8aa1-19176cd4a551.png)
same results, all * was removed

**Comment by stamparm** [comment]
Next time, please read the content/questions from sqlmap:

![1](https://user-images.githubusercontent.com/921555/85516371-68a22980-b5fe-11ea-81ac-c00b398e5946.png)
