### ISSUE TITLE
fingerprinting and other non-SELECTable non-string commands appear incompatible with the "boolean-based blind" technique

### ISSUE THREAD

**Issue by ilatypov** [sqlmapproject/sqlmap#4244]
**Describe the bug**
An application under a test has a clear discriminant reaction to the manual injections of `' and 1=1 --` and `' and 1=0 --`.  Using `--technique=B` shows `POST parameter ... is vulnerable` and `confirming <DBMS type>` but stops dead in the fingerprinting which is not quite necessary but cannot be turned off.
```
[00:27:33] [CRITICAL] sqlmap was not able to fingerprint the back-end database management system
```

**To Reproduce**
1. Run the above against an app with a SQL injection exposed only via the a discriminant boolean.
2. See the error message on fingerprinting.  See the usage wiki not showing a way to turn it off.

**Expected behavior**
A way to turn off fingerprinting.

**Running environment:**
 - sqlmap version: 1.4.6#stable
 - Installation method: homebrew
 - Operating system: MacOS 10.15.5
 - Python version: 2.7.16.

**Target details:**
 - DBMS: `--dbms "IBM DB2"`.
 - SQLi techniques: `--technique=B --test-filter="AND " --prefix="' " --suffix=" --" --ignore-redirects --not-string="/Error.aspx" --drop-set-cookie --flush-session --level=5 --risk=3 --threads=10 --batch --sql-query 'CURRENT SERVER'`

 - WAF/IPS: not sure

**Additional context**
Workaround (without a clear understanding):
```diff
--- sqlmap/1.4.6/libexec/lib/controller/action.py.orig	2020-05-31 21:29:53.000000000 -0400
+++ sqlmap/1.4.6/libexec/lib/controller/action.py	2020-06-25 00:29:16.000000000 -0400
@@ -32,7 +32,7 @@
     # system to be able to go ahead with the injection
     setHandler()

-    if not Backend.getDbms() or not conf.dbmsHandler:
+    if not Backend.getDbms() and not conf.dbmsHandler:
         htmlParsed = Format.getErrorParsedDBMSes()

         errMsg = "sqlmap was not able to fingerprint the "
```

```
[00:29:49] [INFO] testing IBM DB2
[00:29:49] [INFO] confirming IBM DB2
IBM DB2
[00:29:51] [INFO] fetching SQL query output: 'CURRENT SERVER'
[00:29:51] [INFO] retrieving the length of query output
[00:29:51] [INFO] retrieved: 8
[00:30:01] [INFO] retrieved: XXXXXXXX
CURRENT SERVER: 'XXXXXXXX'
[00:30:01] [INFO] fetched data logged to text files under '/Users/USER/.sqlmap/output/SERVER.TEST'

[*] ending @ 00:30:01 /2020-06-25/
```

**Comment by stamparm** [comment]
1) `fingerprinting which is not quite necessary but cannot be turned off.` <- please, spare me. There is a case which has been extensively abused by the users where they forced some imaginary DBMS - because they had a feeling that that was it - and raised the issues because nothing worked all of a sudden
2) Please make a proper debugging before raising this kind of issues (e.g. `--parse-errors` or `-t traffic.txt`). In your case most probably dummy payload  `123=(SELECT 123 FROM SYSIBM.SYSDUMMY1)` failed. Real question is why, as `SYSIBM.SYSDUMMY1` is a default "dummy" table to be expected in IBM DB2

**Comment by stamparm** [comment]
![1](https://user-images.githubusercontent.com/921555/85712225-674d2b80-b6e8-11ea-882a-89390dfa1398.png)

**Comment by ilatypov** [comment]
Since my output differed from the above screenshot, showing the error message on fingerprinting, I can only assume that the above screenshot was obtained from an application under the test that had a weakness that was wider than just the one allowing the boolean blind injection.  That is, the "testbed" web app with IBM DB2 behind it somehow allowed to inject the non-SELECT command and read its response back. 

Perhaps, my guess is wrong, though.
