### ISSUE TITLE
Is it possible to use SQLMAP in a Flask Application

### ISSUE THREAD

**Issue by Samperfect** [sqlmapproject/sqlmap#4247]
**Is your feature request related to a problem? Please describe.**
I am a student who needs to design a web app that scans for vulnerability in a website. I want to use the SQLMAP tool but I don't know if it is possible to be used in a Flask app. Either as a library or as an API request call. 

I heard about the SQLMAP API but I don't know if I can get a better explanation of how it works. 

Any helpful reply is welcomed as this is my project and I really need quick help. 

Also, if SQLMAP won't work what other solution would you recommend?

**Comment by stamparm** [comment]
`Also, if SQLMAP won't work what other solution would you recommend?` <- please use any SQL injection tool and try to `subprocess` it. SQLMAP API might be too difficult for you
