### ISSUE TITLE
-v (verbose) help to found sqli for sqlmap? myth?

### ISSUE THREAD

**Issue by hastalamuerte** [sqlmapproject/sqlmap#4250]
Hello , thanks a lot for answering and your great product (sqlmap) 

Yesturday i found strange post on medium 
https://href.li/?https://medium.com/@vardanstres/advance-sqlmap-bypass-mod-security-bypass-bdb2e8b79bc
(read just till 2 point)
Guy tell and show on post sqli that setting a  **-v 3** helping to found injection, without verbose sqlmap *dont see sqli* 
Is it a true? i just cant go to sleep literaly , before i will know the truth))

Have a good day! sorry for stupid question

**Comment by stamparm** [comment]
Nope. `-v 3` is a **passive** option used for showing the current PAYLOAD. Nothing to do with any kind of "changes" to the request
