### ISSUE TITLE
issue with writing down cracked phpBB password

### ISSUE THREAD

**Issue by caperoni** [sqlmapproject/sqlmap#4252]
I have issue with phpBB hash password sqlmap writing down. When I passed success dictionary bruteforce attack with sqlmap the result can't be stored in session like for MD5 hashes.

For example:

For MD5 sqlmap do so `827ccb0eea8a706c4c34a16891f84e7b (12345)`

For phpBB sqlmap do `$H$9jhFmtImvHVtSb0Km7GcqviN2ObX7V/`

But need to be `$H$9jhFmtImvHVtSb0Km7GcqviN2ObX7V/ (12345)`

**Comment by stamparm** [comment]
Not sure what is going on here. You claim that sqlmap bruteforced/cracked phpBB hash? sqlmap currently does not support phpBB hash cracking. Can you please send a screenshot of your claim?

**Comment by stamparm** [comment]
...nevertheless, with the latest commit/revision I've added support for generic phpass (including PHPBB3) hash cracking
