### ISSUE TITLE
find --where is not null

### ISSUE THREAD

**Issue by ktjd123** [sqlmapproject/sqlmap#4255]
**Is your feature request related to a problem? Please describe.**
if where can remove columns with NULL value, it would be great.

**Describe the solution you'd like**
if not NULL clause

**Describe alternatives you've considered**

**Additional context**
Thank you. always appreciate your works.

**Comment by stamparm** [comment]
Not sure that I understand it. You want to A) remove entries based on `NOT NULL` evaluation of a single column or B) removal of column(s) with all `NULL` values?

If the answer is A), that is already available with `--where` as follows:

* regular run:

![regular](https://user-images.githubusercontent.com/921555/86469545-eb7f5e80-bd39-11ea-8297-686e810a3707.png)

* run with `--where=--where="name IS NOT NULL"`:

![where](https://user-images.githubusercontent.com/921555/86469577-f9cd7a80-bd39-11ea-8598-5aee5de0614f.png)

**Comment by ktjd123** [comment]
Oh the question was A) Thank you. you saved my day.
