### ISSUE TITLE
 missing a mandatory option

### ISSUE THREAD

**Issue by MASFIansary** [sqlmapproject/sqlmap#4259]
what is my mistake?
![11111](https://user-images.githubusercontent.com/68002010/86895593-85724d00-c126-11ea-97d0-7ecc01e4f4c9.JPG)

**Comment by stamparm** [comment]
You are most probably having the following problem: https://stackoverflow.com/questions/2640971/windows-is-not-passing-command-line-arguments-to-python-programs-executed-from-t
