### ISSUE TITLE
False negative: PortSwigger lab (comparing content length)

### ISSUE THREAD

**Issue by toxydose** [sqlmapproject/sqlmap#4262]
I found that sqlmap doesn't find boolean blind SQL injection from PostSwigger lab: https://portswigger.net/web-security/sql-injection/blind/lab-conditional-responses.

The vulnerable parameter is `TrackingId` in cookies which allows to enumerate password using the next cookie payload:

_`Cookie: TrackingId=<id>' and SUBSTRING((SELECT password from users where username='administrator'),1,1)='a'--; session=<session>`_

I've used --level=2 parameter to include cookies in attack:

`./sqlmap.py -r ~/sql.lab --level=2 `

When the statement is correct it should return "welcome" string in the server response so it is possible that sqlmap doesn't compare the content length between the responses.

BurpSuite was able to discover this vulnerability in the same way by comparing the server responses:

`The TrackingId cookie appears to be vulnerable to SQL injection attacks. The payloads 20167268' or '9188'='9188 and 20635559' or '3864'='3858 were each submitted in the TrackingId cookie. These two requests resulted in different responses, indicating that the input is being incorporated into a SQL query in an unsafe way.`

**Comment by stamparm** [comment]
Don't get me wrong, but I really dislike this kind of issues. Register here, use this, compare with some commercial product, while it was your fault all along.

![1](https://user-images.githubusercontent.com/921555/87546074-3d64a480-c6a9-11ea-9ec6-d7890783a03e.png)
