### ISSUE TITLE
blind Sqli Sleepy

### ISSUE THREAD

**Issue by legevole** [sqlmapproject/sqlmap#4264]
how I can get my sql server databases when payload is 1' AND (SELECT 6673 FROM (SELECT(SLEEP(5)))MgFr)  AND 'zGUx'='zGUx
how I can inject here to get databases ??

**Comment by stamparm** [comment]
sqlmap should automatically do this for you. I really don't understand what's this issue about.

Just use `python sqlmap.py -u <target..?param=1> --dbs` and you should get those DBS
