### ISSUE TITLE
all tested parameters do not appear to be injectable.

### ISSUE THREAD

**Issue by ilovedumps** [sqlmapproject/sqlmap#4265]
Hello, I ran into an issue, whenever I execute the command "sqlmap.py -u URL" it always ends up with this error: 

"[CRITICAL] all tested parameters do not appear to be injectable. Try to increase values for '--level'/'--risk' options if you wish to perform more tests. If you suspect that there is some kind of protection mechanism involved (e.g. WAF) maybe you could try to use option '--tamper' (e.g. '--tamper=space2comment') and/or switch '--random-agent'"

Any solution?

**Comment by stamparm** [comment]
Maybe try to find a target which is actually SQL injectable. One example could be http://testphp.vulnweb.com/artists.php?artist=1
