### ISSUE TITLE
Interactive blind injection for known words

### ISSUE THREAD

**Issue by d5a** [sqlmapproject/sqlmap#4272]
**Is your feature request related to a problem? Please describe.**
A Blind-Based injection can be really time consuming. 
Most of the time I recognize the word/name long before sqlmap, but there's no way to tell it sqlmap directly at runtime. 
Example: first_n___ (10), for which the word "first_name" is the most likely match. 

**Describe the solution you'd like**
Now it would be great if you could enter the letters "ame" while searching, which will be checked directly.
That way you save a lot of time, a lot of requests to the server and it's also fun. :)

**Describe alternatives you've considered**
-/-

**Additional context**
-/-

**Comment by stamparm** [comment]
A) You are not the first one with this idea. Sorry to inform you, but all previous similar attempts were turned down
B) Python has a problem with asynchronous/non-blocking user console input. By problem I mean that there is no cross-platform support for it. This means that currently there is no way to make a "flexible" mechanism which wouldn't cause program/console blocking, while just "listening" to the potential user input in the background
C) Even more, this kind of "gamification" would just result with more user issues, where a wrong user input would be blamed to the sqlmap internals
