### ISSUE TITLE
detect error hash method

### ISSUE THREAD

**Issue by sadazs** [sqlmapproject/sqlmap#4273]
my database from wordpress site but when dump table wp-user and dehash sqlmap detect with hash method 'phpass_passwd'
any way to manual hash method when dump?

**Comment by stamparm** [comment]
a) sorry, i do not understand what's the issue
b) if you wonder how to get recognized `phpass_passwd` hashes, sqlmap asks you whether you want to do it during a run:

![1](https://user-images.githubusercontent.com/921555/87930148-db7cb400-ca87-11ea-96e3-c9edc769fda0.png)
