### ISSUE TITLE
Unable to confirm the back-end DBMS   

### ISSUE THREAD

**Issue by mahmodjay** [sqlmapproject/sqlmap#4276]
What can i do when the sqlmap wasn't able to detect the back-end DBMS > ?
how can i complete the injection ?
![back-endDBMS](https://user-images.githubusercontent.com/24532001/87958068-14fcf180-ca7f-11ea-92d0-6ace3d56d5f3.png)

**Comment by mahmodjay** [comment]
@stamparm  **can u give me something to solve or to do with this** ? 
thanks for ur time .

**Comment by stamparm** [comment]
1) You are using tamper scripts, thus most probably something is interfering with the regular work of sqlmap
2) If you are not having any useful error information from the other side, we could only guess the DBMS here
3) For how to deal with the rest of WAF/IPS protected web site, you are here on your own. Without manual inspection and manual tampering on what works and what does not work, you won't do a thing here

**Comment by mahmodjay** [comment]
Thanks for the reply ,
Have a good day man .
