### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by wtzabc123** [sqlmapproject/sqlmap#4278]
[CRITICAL] all tested parameters do not appear to be injectable. Try to increase values for '--level'/'--risk' options if you wish to perform more tests. If you suspect that there is some kind of protection mechanism involved (e.g. WAF) maybe you could try to use option '--tamper' (e.g. '--tamper=space2comment')

**Comment by wtzabc123** [comment]
what should I do

**Comment by stamparm** [comment]
Then, you should focus on other parameters and/or targets. Opening an issue for maybe not having a SQLi vulnerability in the first place doesn't seem to be one of those "what should I do" ideas
