### ISSUE TITLE
[18:44:06] [WARNING] you haven't updated sqlmap for more than 112 days!!!

### ISSUE THREAD

**Issue by shahhussain305** [sqlmapproject/sqlmap#4282]
I am using sqlmap on Ubuntu 20.04 LTS. when i run the sqlmap it shows the following warning and end the tests:

[18:44:06] [WARNING] you haven't updated sqlmap for more than 112 days!!!

While I always keeping my OS updated.

Please guide me, how can i remove this issue. I have also tried to upgrade sqlmap using:

    sudo apt upgrade sqlmap

which shows that you are already using the updated version of sqlmap???

Please help.

**Comment by h4dla3** [comment]
use #sqlmap --update

https://github.com/sqlmapproject/sqlmap/wiki/Download-and-update

**Comment by stamparm** [comment]
@shahhussain305 fully aware of this "problem". It goes like this. At first, idea of this kind of "WARNING" was to "push" users to update their sqlmap installation. Now, when you install sqlmap via `git` and/or `pip` it is quite trivial to pull/update to the latest revision/version. In your case, there is a problem with APT package maintainer(s) where they haven't pulled sqlmap for more than 3 months to their repositories.

Now, I really didn't have such "scenario" in my mind when included this "nagging" mechanism. From lately this mechanism has been updated to nag only if used code-base is >180 days old, while the WARNING message is now not so annoying - "your sqlmap version is outdated"

Anyhow, until your package maintainers do not update the repository content to the latest version, you'll have this kind of a problem. Nevertheless, there is a way-around. You can always uninstall your version (e.g. `sudo apt remove sqlmap`) and just install sqlmap by some other means (e.g. `sudo pip install sqlmap` or `git clone --depth 1 https://github.com/sqlmapproject/sqlmap.git sqlmap-dev`). This should solve your problem
