### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lilcsz** [sqlmapproject/sqlmap#4296]
**Describe the bug**
HTTP Errror

**To Reproduce**
1. Run 'python3 sqlmap.py -u site.com --dbs'
2. [18:15:01] [WARNING] HTTP error codes detected during run:
403 (Forbidden) - 76 times

**Running environment:**
 - sqlmap version [e.g. 1.3.5.93#dev]
 - Installation method [git clone]
 - Operating system: [Ubuntu]
 - Python version [e.g. 3.8.3]

**Comment by stamparm** [comment]
This is not sqlmap Issue. You have to debug what is going on.

For start, try to rerun with `--random-agent` and double-check that you've entered URL correctly. Also, make sure that you are using correct cookie value (if required)

If 403 persists, rerun everything with `-t traffic.txt` or `-v5` and look into what's going on in responses. Maybe you'll find out why is server responding with `Forbidden`
