### ISSUE TITLE
about --search

### ISSUE THREAD

**Issue by 13Em0SPVPaoq** [sqlmapproject/sqlmap#4302]
--search -C password
database "test"
dbo.account1
dbo.account
dbo.accountOLD
dbo.account2019
...
...
...
...
...
...

but what if i want to dump whole table, not only columns password, and --search outputed lot of tables that found columns password inside

**Comment by stamparm** [comment]
Just press `N` when asked whether you want to automatically dump during the search process and dump those tables separately one by one. Regular use case is actually the one where user doesn't care about all of the columns, while your case is the one that you actually care.

Use the workaround described

**Comment by 13Em0SPVPaoq** [comment]
.
