### ISSUE TITLE
hey im getting an error bash : command not found,  happens to all command even for -h (help) pls let me know a solution

### ISSUE THREAD

**Issue by vampire-tacito** [sqlmapproject/sqlmap#4304]
**Describe the bug**

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**

**Running environment:**
 - sqlmap version [e.g. 1.3.5.93#dev]
 - Installation method [e.g. git]
 - Operating system: [e.g. Microsoft Windows 10]
 - Python version [e.g. 3.5.2]

**Target details:**
 - DBMS [e.g. Microsoft SQL Server]
 - SQLi techniques found by sqlmap [e.g. error-based and boolean-based blind]
 - WAF/IPS [if any]
 - Relevant console output [if any]
 - Exception traceback [if any]

**Additional context**

**Comment by victorcamposm** [comment]
check what "command not found" means in google

**Comment by vampire-tacito** [comment]
Thanks for replying, but that's my mistake. I forgot to put sqlmap before the command

**Comment by victorcamposm** [comment]
np. You can now close the issue. 
In the future, read the guidelines before submitting an issue, because that is definitely not the correct way.
https://github.com/sqlmapproject/sqlmap/blob/master/.github/CONTRIBUTING.md
