### ISSUE TITLE
Cookie contains * which causes issues for authentication

### ISSUE THREAD

**Issue by denis300** [sqlmapproject/sqlmap#4315]
**Describe the bug**
The session cookie contains a * which sqlmap removes and thinks is part of an injection point. The cookie in question is the following:

`cookie_qa=AQIC5wM2LY4SfcwojEQZhiY6znhbEBSd9ZdozoBSLYl6_Go.*AAJTSQACMDIAAlNLABQtMzIwMzU4MTk1MDM1MDA3NjY4NwACUzEAAjAx*;`

When captured with a proxy, the cookie is sent as below which doesn't include the *

`cookie_qa=AQIC5wM2LY4SfcwojEQZhiY6znhbEBSd9ZdozoBSLYl6_Go.AAJTSQACMDIAAlNLABQtMzIwMzU4MTk1MDM1MDA3NjY4NwACUzEAAjAx;`

Sqlmap doesn't ask whether the cookie is an injection point and causes a "not authorized" state for the sqlmap session.

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**

**Running environment:**
 - sqlmap version [e.g. 1.3.5.93#dev]
 - Installation method [e.g. git]
 - Operating system: [e.g. Microsoft Windows 10]
 - Python version [e.g. 3.5.2]

**Target details:**
 - DBMS [e.g. Microsoft SQL Server]
 - SQLi techniques found by sqlmap [e.g. error-based and boolean-based blind]
 - WAF/IPS [if any]
 - Relevant console output [if any]
 - Exception traceback [if any]

**Additional context**

**Comment by stamparm** [comment]
Unable to reproduce. I believe that you are either running some older version of sqlmap OR your shell/command line messed with the cookie value (i.e. `*` has a special meaning if not enclosed with quotes) which you forgot to enclose in quotes:

![1](https://user-images.githubusercontent.com/921555/91285011-f0d2b580-e78c-11ea-8cd0-1163a411f093.png)

**Comment by denis300** [comment]
Hi Miroslav,

I was actually using -r and feeding it a request file. I was expecting the
questions about the injection point but didn't receive it.

**Comment by stamparm** [comment]
Same thing with `-r`:

![2](https://user-images.githubusercontent.com/921555/91423701-29d85c00-e859-11ea-9184-c32264954890.png)

p.s. this is a perfect example of why here and there I just close these kind of tickets as invalid. You had a template, where you could fill all the info (in this case that you used the `-r`), while now we had to play a `ping-pong`. Still unreproducible
