### ISSUE TITLE
UDF so file decloaked in an unintended way

### ISSUE THREAD

**Issue by kmahyyg** [sqlmapproject/sqlmap#4321]
v.1.4.8.22#dev on ParrotSec OS from Git Installation

![image](https://user-images.githubusercontent.com/16604643/91748652-e5e7ad00-ebf2-11ea-9eda-307fd776af09.png)

Python 2.7.18 / Python 3.8.5 with PyMySQL installed from PyPi
Command: `python3 /usr/share/sqlmap/sqlmap.py -d 'mysql://root:xxxxxxx@172.16.4.10:3306/mysql' --os-shell --no-cast`

**Comment by stamparm** [comment]
You are right. My fault. Will fix today

**Comment by stamparm** [comment]
thx for reporting it. find it fixed with the latest revision
