### ISSUE TITLE
SQLMap fails to use http basic auth credentials correctly

### ISSUE THREAD

**Issue by mkauschi** [sqlmapproject/sqlmap#4322]
Hi Miroslav,
I have to reopen my bug report #4320 because I dug more into SQLMaps code and found the issue. It was introduced from version 1.3.5 to version 1.3.6. The issue is in the class lib/request/connect.py (see screenshot).

![Screenshot at 2020-09-01 11-17-19](https://user-images.githubusercontent.com/19614923/91831938-ffb1e000-ec44-11ea-8de2-66d5aaa4ecb6.png)

For some reason the Basic authentication header is of type `bytes` now. SQLMap iterates over every field in the header and deletes it first. Then it checks if the instance is of type `str` and adds it again. Because the Basic authentication header is of type `byte` it is skipped and therefore removed from the headers.

**Comment by stamparm** [comment]
@mkauschi thank you for your time :D. don't mind for it, but going to "patch" it myself

**Comment by stamparm** [comment]
once again, thank you very much. do you want me to put you into https://github.com/sqlmapproject/sqlmap/blob/master/doc/THANKS.md ?

**Comment by mkauschi** [comment]
You could do that if you like :) Manuel Kauschinger
