### ISSUE TITLE
Type confusion bug in basic.py

### ISSUE THREAD

**Issue by mkauschi** [sqlmapproject/sqlmap#4325]
Hi Miroslav,
I just found another type confusion bug in the basic.py class.

![Screenshot at 2020-09-02 16-55-37](https://user-images.githubusercontent.com/19614923/91999864-29e6c900-ed3d-11ea-8d93-2e26aed924ae.png)

In line 336 the `page` variable is checked to be of type `bytes` but in line 356 the `page.startwith()` compares against a string. This causes SQLMap to report that the target URL is not reachable (see screenshot below).

![Screenshot at 2020-09-02 16-48-05](https://user-images.githubusercontent.com/19614923/91998936-2272f000-ed3c-11ea-8fe5-7d90987c3cf2.png)
 is not reachable.

It was quite hard to find out what the issue was because the error was not handled. I would create another issue, pointing out the unhandled exception in the connect.py class, if that is okay with you.

**Comment by stamparm** [comment]
`I would create another issue, pointing out the unhandled exception in the connect.py class, if that is okay with you.` <- feel free
