### ISSUE TITLE
--csrf-token 

### ISSUE THREAD

**Issue by 13Em0SPVPaoq** [sqlmapproject/sqlmap#4331]
```
<meta name="csrf-token" content="u7KPtc1wjksCgZyoZS64c7yTXey8Asw69xZwro6c">

unable to find anti-CSRF token 'X-CSRF-TOKEN' at 'xxx'. sqlmap is going to retry the request
```
what if there's two diff name about what you send and what you received

**Comment by stamparm** [comment]
With the latest revision cases with `<meta>` are also considered. Additionally, you had to use the `--csrf-token=csrf-token` instead of `--csrf-token=X-CSRF-TOKEN` based on the content of that `<meta>`

As of your question, we currently do not support that kind of (non-common) cases
