### ISSUE TITLE
Multiple "--ignore-code"

### ISSUE THREAD

**Issue by pedroflor** [sqlmapproject/sqlmap#4332]
**Multiple "--ignore-code"**
Allow to specify more than one (1) ignore code. 

**Currently only one "ignore-code" could be specified:**
`sqlmap   -r ./req.txt --ignore-code=401`

**Desired feature**
`sqlmap   -r ./req.txt --ignore-code=401 --ignore-code=500`

**Comment by stamparm** [comment]
`--ignore-code` already accepts multiple codes separated with comma

**Comment by stamparm** [comment]
with the latest revision, even `--ignore-code=401 --ignore-code=500` should work

**Comment by pedroflor** [comment]
@stamparm, thanks for giving attention here.
I tried  the following combinations with no success:

`sqlmap -r ./req.txt --ignore-code=401,500`
Ignores code 500

`sqlmap -r ./req.txt --ignore-code=401 --ignore-code=500`
Ignores code 401 (only takes the latest argument -> 500)
