### ISSUE TITLE
SQLMap is breaking the HTTP request.

### ISSUE THREAD

**Issue by zarkones** [sqlmapproject/sqlmap#4336]
**Describe the bug**
Tool is triggering 302 response.

**Expected behavior**
Looking at Burp, the request is the same, byte by byte. (Confirmed via Comparer)
When issuing the file content trough Repeater I receive a valid response.
But when that request goes trough SQLMap it breaks somehow. Even thou they're the same.
And what I'm left with is `302 - Found`.

**Comment by stamparm** [comment]
Could you please tell me how to reproduce this as you are the only one claiming this kind of problem?

**Comment by zarkones** [comment]
@stamparm  I wasn't able to track down the problem. But it makes me think it is an issue with the end application and not with SQLMap. 

However, I've a real other issue with the tool and will open a new ticket.
