### ISSUE TITLE
SQLMap wasn't able to recognize the vulnerability.

### ISSUE THREAD

**Issue by zarkones** [sqlmapproject/sqlmap#4339]
Application that is being tested returns "400 status code" and the error message when any of the queries isn't correct.
So it is an Error based Injection, but SQLMap see them as failed requests, and it left me with this:

!["This is fine MEME...](https://miro.medium.com/max/960/1*vIsM0XEGMI8GgWy1rl2zmA.gif)

Then I added `--ignore-code=400` and...

!["I don't care MEME...](https://i.pinimg.com/736x/26/80/bd/2680bda16d45d2295a7b0e697401cb08.jpg)

And still the result was the same. Is this wanted behavior or a bug?
I confirmed trough Burp proxy that the responses where a SQL error statements.

**Comment by stamparm** [comment]
Please. DBMS errors is not a proof of (usable) SQL injection. Closing this down as invalid

**Comment by zarkones** [comment]
They're there. For every `400 status code` response I was able to modify the DB and make a request sleep for X amount of seconds.

**Comment by zarkones** [comment]
@stamparm Reopen the issue, since it's not invalid.
