### ISSUE TITLE
Add OpenCollective (or Equivelent)

### ISSUE THREAD

**Issue by HysMagus** [sqlmapproject/sqlmap#4342]
OpenCollective.com is a tool that allows for open source projects to accept sponsors, it'd be awesome to see if sqlmap could have an account on there or an equivalent to enable sponsoring of contributors. 

(If there's an alternative for sponsoring already present please add it to the readme)

**Comment by stamparm** [comment]
For sponsorship questions, our email is always opened (`dev@sqlmap.org`)
