### ISSUE TITLE
Problem with dumping certain column !

### ISSUE THREAD

**Issue by rko4all** [sqlmapproject/sqlmap#4348]
Hello There ,

Using sqlmap , I have been able to get access to a database named script . In this database there is a table called account . Now the problem is that I can dump some columns of this table and some other columns just return blank values ! For instance I can dump the column named "id" , however , I can't dump the column named holder_mail which contains e-mail addresses . Here is the command I'm using : 
`screen python sqlmap.py -u 'URL' --identify-waf --tamper=between,randomcase,space2comment -v 3 --random-agent --level 3 risk 3 -D script -T account -C holder_mail --dump`
the above command dumps blank lines . while the following works and dumps data : 
`screen python sqlmap.py -u 'URL' --identify-waf --tamper=between,randomcase,space2comment -v 3 --random-agent --level 3 risk 3 -D script -T account -C id --dump` 
Now I'm pretty sure that this is not a script problem as I have already been able to dump the same table (holder_mail) from other websites that are running the same script .
Can anyone help me and tell me what's wrong here ? I have already used --no-cast and --hex parameters but no luck there .
Any help would be appreciated .

Regards ,

**Comment by rko4all** [comment]
BTW , I forgot to mention that column holder_mail might have about 10K e-mail addresses in it . Could this be a reason why sqlmap is dumping blank output? Is this too much for sqlmap? I mean the column "id" which I successfully dumped also has 10K values in it but they are numbers like 1,2,3................10000 .

**Comment by stamparm** [comment]
1) you just skipped the issue template
2) I don't like playing guessing
3) you should try to rerun everything with `--parse-errors` in hope to find some error describing on what is going on
4) you can try to rerun with `--binary-fields=holder_mail`
5) If everything fails, you should capture the traffic (e.g. `-t traffic.txt`) and inspect on what is going on inside
