### ISSUE TITLE
How can I dump the last row of a table?

### ISSUE THREAD

**Issue by rko4all** [sqlmapproject/sqlmap#4349]
Hello There ,

Now in order to be familiar with a site's table , I need to dump the last row of a table named "account" . can you please tell me what parameters I can use to dump only the last row of a certain table? Here is the command I'm using for table dump . How should I modify it ?
`screen python sqlmap.py -u 'URL' --identify-waf --tamper=between,randomcase,space2comment -v 3 --random-agent --level 3 risk 3 -D script -T account --dump`

**Comment by stamparm** [comment]
There is no such command per-se. You can try to use the `--where` for this kind of situations.

As I don't know anything about this case of yours and you skipped the whole issue template, I have to do some guessing here. Maybe you have some ID column (e.g. `id`) inside that table and your target is MySQL. In such case, you could try (as said, I am guessing here): `--where="id=max(id)"`
