### ISSUE TITLE
H2 Boolean based injection count error

### ISSUE THREAD

**Issue by Arkango** [sqlmapproject/sqlmap#4350]
**Describe the bug**
I found a blind boolean based sql injection in H2 dbms, the H2 doesn't support the count function to count databases, tables, columns. Only bruteforce work.

**To Reproduce**
1. create vulnerable application to a blind boolean based injection with H2
2. try to dump databases, tables, columns and entries

**Expected behavior**
I wish the software skip the count operation of the entries and try to dump values.

**Screenshots**
<img width="736" alt="Schermata 2020-09-21 alle 14 53 43" src="https://user-images.githubusercontent.com/23188987/93769535-344d0200-fc1b-11ea-9a5d-4df2bd9e9c25.png">
 AND ASCII(SUBSTR((SELECT IFNULL(CAST(COUNT(*) AS LONGVARCHAR),CHAR(32)) FROM TEST.TEST),1,1))>51 AND 'lUTo'='lUTo

**Running environment:**
 - sqlmap version [1.4.8#stable]
 - Installation method [git]
 - Operating system: [Mac OS Catalina 10.15.6]
 - Python version [3.7.6]

**Target details:**
 - DBMS [H@]
 - SQLi techniques found by sqlmap [ boolean-based blind]

**Comment by stamparm** [comment]
![2](https://user-images.githubusercontent.com/921555/93787007-3e2d3000-fc30-11ea-9454-0227aeb504b5.png)

**Comment by Arkango** [comment]
ok mine work without cast so i used `--no-cast` option, but the enumeration doesn't work properly, i flushed my session and right now I don't know which DBMS is at the backend

**Comment by stamparm** [comment]
`i flushed my session and right now I don't know which DBMS is at the backend` <- this is not the problem of "enumeration". You are starting detection from start. You should closely inspect why sqlmap doesn't find/detect the SQLi again

**Comment by Arkango** [comment]
yes I'll debug it
