### ISSUE TITLE
What function used for customizing the post data in tamper script ?

### ISSUE THREAD

**Issue by malwareslayer** [sqlmapproject/sqlmap#4351]
**Is there any function that used for customizing post data ?**

I didn't find any function correlated to customizing the post data before its called by `_urllib.request.urlopen(req)`. Since the core documentation are limit, its a bit difficult until i debug entire sqlmap, i found the only way to customizing is from `conf.parameters[PLACE.POST]` and `conf.parameters[PLACE.CUSTOM_POST]`.

But the problem when implementing customizing with `conf.parameters` is, either tamper payload didn't persist into `post` variable when i try customizing new post data or all the post data replaced. Anyway i don't used `conf.parameters[PLACE.CUSTOM_POST]` since its only for asterisk mark payload.

**Do you have an idea for a solution?**

We need a new `lib.core.enums.PLACE` for easily merge `post` variable that from original `conf.data` with customizing post

Reference Source Code:
[PLACE.POST](https://github.com/sqlmapproject/sqlmap/blob/bcea050f226b48d01f7d1df5fdcc40bc14791780/lib/request/connect.py#L1015)
[PLACE.CUSTOM_POST](https://github.com/sqlmapproject/sqlmap/blob/bcea050f226b48d01f7d1df5fdcc40bc14791780/lib/request/connect.py#L1020)

**Comment by stamparm** [comment]
With the latest revision (NOTE: must update to have the intended functionality) you'll have the ability "preprocess" request. This is being done after everything is prepared by SQLMap, just before the request is being sent to the target.

You can find a "dummy" example [here](https://github.com/sqlmapproject/sqlmap/wiki/Usage#preprocess-request)
