### ISSUE TITLE
Anyway to resume the dump session?

### ISSUE THREAD

**Issue by rko4all** [sqlmapproject/sqlmap#4358]
Hello there ,

During sqlmap dump session , a network outage caused the process to stop . I can see that session.sqlite file exists . How can I resume the last dump ? I tried the -s option however it kept producing blank lines ! Is it normal ? Does it mean sqlmap is denying the check for values which it already has data on?

Regards ,

**Comment by stamparm** [comment]
A) sqlmap just takes all the (valid) values it has from the session file. There is no need for explicit usage of option `-s`.
B) there should be no blank lines if values have been already shown as valid in the previous run. Nevertheless, if I guess correctly, sqlmap probably thinks that it retrieved some blank lines. In that case you have a problem. Maybe you could do the redump of only those problematic parts with something like `--fresh-queries --where=...`, where inside the `--where` you could do some `WHERE` logic for forcing the retrieval of only those rows (e.g. `--where="id>1000"`)
