### ISSUE TITLE
Question: What happens if you send a keyboard interrupt or if the network connection errs up while in the middle of dumping columns?

### ISSUE THREAD

**Issue by target111** [sqlmapproject/sqlmap#4360]
Will they still be saved to the .sqlmap directory?

**Comment by stamparm** [comment]
A) It depends. If you press repeatedly `Ctrl-C` there is a possibility that they won't be saved. Also, if you are talking just about the column enumeration (i.e. `--columns`) most probably you won't get anything as a result (neither in console nor directory).
B) i would suggest you to check that directory to see exactly what you are getting in those kind of situations
