### ISSUE TITLE
[CRITICAL] unable to read file '/usr/share/sqlmap/data/xml/banner/mysql.xml'

### ISSUE THREAD

**Issue by z3dc0ps** [sqlmapproject/sqlmap#4362]
[CRITICAL] unable to read file '/usr/share/sqlmap/data/xml/banner/mysql.xml'
![1](https://user-images.githubusercontent.com/61974788/94509331-9b794080-0231-11eb-8610-73fe4c76f0d6.JPG)

**Comment by luiscarlos321** [comment]
Em ter, 29 de set de 2020 12:27 AM, z3dc0ps <notifications@github.com>
escreveu:

**Comment by stamparm** [comment]
Duplicate of #4236

Same advice: `Please uninstall your version of sqlmap (e.g. apt uninstall sqlmap <- guessing how you could do it) and retrieve the latest monthly version with: pip install sqlmap`
