### ISSUE TITLE
A warning issue

### ISSUE THREAD

**Issue by binhnguyen981** [sqlmapproject/sqlmap#4367]
OS: Mac 10.11.6
Python: 3.8

After running an SQLMap command, my lap shows a warning:

python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

Anyone experiencing this same issue, please help me a way to remove this warning. Thanks a lot.

**Comment by binhnguyen981** [comment]
Thank you for your help.

**Comment by GD-Dheer** [comment]
Pulling from latest master did not work for me. I still get the same warning. -  UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d ' @stamparm

**Comment by stamparm** [comment]
@GD-Dheer please retry it now with the latest revision. If that doesn't help, then I'll need to treat it as "known issue" (non-harmful, only nagging/annoying one)

**Comment by leonardo0004** [comment]
> @GD-Dheer please retry it now with the latest revision. If that doesn't help, then I'll need to treat it as "known issue" (non-harmful, only nagging/annoying one)

i use macos sierra 10.12.6 with python3.8 also have this question

**Comment by leonardo0004** [comment]
> @GD-Dheer please retry it now with the latest revision. If that doesn't help, then I'll need to treat it as "known issue" (non-harmful, only nagging/annoying one)

i use macos serria 10.12.6 with python3.8 also have this question 
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/resource_tracker.py:203: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d ' @stamparm

**Comment by stamparm** [comment]
I would gladly help, but this seems to be exclusively related to Mac, while I don't have any Macs around. Additionally, this should only be a nagging message.

If anybody is willing to track it down on his Mac why is this happening, I would be really grateful
