### ISSUE TITLE
Tamper script not working when using request file (-r) and SSL (:443 or --force-ssl argument)

### ISSUE THREAD

**Issue by maycon** [sqlmapproject/sqlmap#4368]
Hi team,

I am running the lastest version of sqlmap from git (1.4.10.3#dev) and I am stucked on the following situation:

I have HTTP request file, like the following, where I want all payload as my data:

```
POST /route/to/endpoint HTTP/1.0
Host: domain.tld

*
```

When running the SQLMap using the following command, I can intercept the request correctly:
```
$ sqlmap -r request.txt --proxy=http://burp:8080 --tamper=base64encode --skip-urlencode
```

Result:
```
POST /route/to/endpoint HTTP/1.0
Host: domain.tld

[I got the b64 encoded payload here]
```

But when I ran SQLMap using `--force-ssl` or adding :443 to the host header it looks like the tamper is been ignored:
```
$ sqlmap -r request.txt --proxy=http://burp:8080 --tamper=base64encode --skip-urlencode --force-ssl
```

Result:

```
POST /route/to/endpoint HTTP/1.0
Host: domain.tld

```

I am still looking at the source, trying to figure out what I am missing or if it's a sqlmap bug.

**Running environment:**
 - sqlmap version: 1.4.10.3#dev
 - Installation method: git
 - Operating system: Kali
 - Python version: 3.8.5

Thanks.

**Comment by stamparm** [comment]
1) Case 1:

```
$ cat req.txt 
POST / HTTP/1.0
Host: www.example.com:443

id=1
```

```
python sqlmap.py -r req.txt --proxy="http://127.0.0.1:8082" --tamper=base64encode --skip-urlencode
```

![1](https://user-images.githubusercontent.com/921555/95434955-38368f00-0952-11eb-8faf-33aa97e076ff.png)

---

2) Case 2:

```
$ cat req.txt 
POST / HTTP/1.0
Host: www.example.com

id=1
```

```
python sqlmap.py -r req.txt --proxy="http://127.0.0.1:8082" --tamper=base64encode --skip-urlencode --force-ssl
```

![3](https://user-images.githubusercontent.com/921555/95434849-0cb3a480-0952-11eb-92a8-0bb39cbc63ba.png)
