### ISSUE TITLE
Columns switch -C usage?

### ISSUE THREAD

**Issue by Luciano5441** [sqlmapproject/sqlmap#4377]
DBMS mysql < 5.0.0

Unable to enumerate columns, I'm using switch` -C column_name1`.
I got the table and column name from external investigation.
Confirmed using the common columns wordlist check:
"retrieved: column_name1"

However, I am getting error "_information_schema not available_".
When going through the existing common existence check, that works fine and dump starts. 

Can't I list the column straight away with switch -C to tell sqlmap where to look? (and without doing a existing column check?

Thanks!

**Comment by stamparm** [comment]
`information_schema` is not available in MySQL < 5. In those kind of cases you should use `--common-tables` and `--common-columns` specialized "brute" switches
