### ISSUE TITLE
about --dbms

### ISSUE THREAD

**Issue by 13Em0SPVPaoq** [sqlmapproject/sqlmap#4381]
Prioritize testing the most popular database systems?
https://db-engines.com/en/ranking
https://www.datanyze.com/market-share/databases--272/Datanyze%20Universe
https://www.datanyze.com/market-share/databases--272/Alexa%20top%201M

`mssql,mysql,access,oracle,postgresql,db2,sybase,hsql,percona,sqlite` ?

**Comment by stamparm** [comment]
Testings are already prioritized based on our own experience. Also, there are huge discrepancies in your referenced sources. In one case there is A) Oracle, MySQL, MsSQL, PostgreSQL,..., while in another there is B) MsSQL, MsAccess, MySQL, Oracle...

**Comment by 13Em0SPVPaoq** [comment]
or... what if i'm pretty sure that it's mysql or mssql, but i dont want to skip the others. what should i do? to speed up and dont skip testing of other dbms ?

**Comment by 13Em0SPVPaoq** [comment]
```
--dbms-priority 5,5,3,2,1 --dbms mysql,mssql,oracle,sqlite,postgresql
```
