### ISSUE TITLE
Add suffix to any sql query executed by --dump command

### ISSUE THREAD

**Issue by secretpwner** [sqlmapproject/sqlmap#4388]
I couldn't find what I was saying through various searches. 
So I thought it didn't exist, and I ended up writing this.

If run any sql query with 'ORDER BY idx DESC' or 'LIMIT 10', 
cannot save the result to a file (.CSV etc..)

('--where' does not run with 'ORDER BY idx DESC' and if it is run with **'--sql-shell' or '--sql-query' it cannot be saved as a file**)

To solve the problem, 
could you please add "sql query suffix" as an example and consider it to be saved as a "ex) .CSV" file, etc.?

I am sorry that I can't speak English very well, 
and thank you for always developing this.

**Comment by stamparm** [comment]
`ORDER BY` is used in a special way inside the subqueries generated by sqlmap (e.g. for using "pivoting" columns during the table dump). Thus, mixing of "yours" and `ORDER BY` values inside the sqlmap will cause trouble in the general case. 

Nevertheless, with the latest revision you'll be able to something like `--where="1=1 ORDER BY artist_id"` as a way around, but there is a good chance that it will fail
