### ISSUE TITLE
json request bug

### ISSUE THREAD

**Issue by 13Em0SPVPaoq** [sqlmapproject/sqlmap#4389]
```
GET http://www.hidden.com/?id1=1&id2={"id":"26","test":"test","search":"*"}

```
it wont show up `it appears that provided value for GET parameter 'xxx' is JSON deserializable. Do you want to inject inside? [y/N]` if there is a `*` in the request, it will ask you `custom injection marker ('*') found in option '-u'. Do you want to process it? [Y/n/q]` 
and if you press `n`, it will not show up `it appears that provided value for GET parameter 'xxx' is JSON deserializable. Do you want to inject inside? [y/N]`

**Comment by stamparm** [comment]
This is a "special" case. You have a JSON inside the parameter value - thus, it is not a standalone JSON (i.e. inside the POST body). So, sqlmap first asks whether you want to use that parameter value as is and do the dummy injection without any JSON stuff inside (if you press `Y` for `Do you want to process it? [Y/n/q]`) OR you want to ignore the custom mark and do the standard JSON deserialization.

Anyhow, in plainspeak, custom injection marker inside the parameter containing the standalone JSON is not supported.

Nevertheless, you can use the "workaround" where you do not use custom injection marker and just let the sqlmap do the JSON deserialization.
