### ISSUE TITLE
Part of cookie disappears with payload

### ISSUE THREAD

**Issue by deni** [sqlmapproject/sqlmap#4390]
**Describe the bug**
Part of cookie disappears when payload is injected.

**To Reproduce**
1. Run:
`python3 sqlmap.py -u "http://example.com/index.php" --cookie="userchl2_info={'last_book':'*','userchl2':''}" --tamper="base64encode"`
2. Resulting HTTP header:
`Cookie: userchl2_info=eydsYXN0X2Jvb2snOicnYWlmUk5XPCciPkVhWVNaYw%3D%3D','userchl2':''}`

**Expected behavior**
Correct HTTP header:
`Cookie: userchl2_info={'last_book':'eydsYXN0X2Jvb2snOicnYWlmUk5XPCciPkVhWVNaYw%3D%3D','userchl2':''}`

**Running environment:**
 - sqlmap version 1.4.10.11#dev
 - Installation method tar.gz
 - Operating system: MacOS Catalina
 - Python version 3.8.5

**Target details:**
 - DBMS MySQL

**Comment by stamparm** [comment]
Known "issue". `base64encode` tamper script is a "dumb" base64 encoder of provided values without any de-structuring capabilities. Currently there is no way how to do the Base64 encoding of JSON value inside the Cookie nor there is a plan to support it (in near future). Thus, you should do some other helper for your problem (e.g. some Burp extension or similar)
