### ISSUE TITLE
Encoded Response

### ISSUE THREAD

**Issue by kofa2002** [sqlmapproject/sqlmap#4392]
Hi i  wonder if there any option in sqlmap that let me control the reponse variable  for example , lately i was in sql inection but the serer send the response back coded with base64 so i was looking for a solution to decode it on the fly by sqlmap , i was wondering if there any feature like this or will be in the feature how to handle the response

**Comment by 13Em0SPVPaoq** [comment]
https://github.com/sqlmapproject/sqlmap/issues/3621#issuecomment-493374206

**Comment by stamparm** [comment]
`--postprocess=PO..  Use given script(s) for postprocessing (response)`

https://github.com/sqlmapproject/sqlmap/wiki/Usage#postprocess-response
