### ISSUE TITLE
Can user set the kb.customInjectionMark？

### ISSUE THREAD

**Issue by ZZMarquis** [sqlmapproject/sqlmap#4393]
I found the default kb.customInjectionMark is *，and it can't seem to be set by cmd line options and sqlmap.conf.
our normal cookie cotains *, so I want to set a more complex kb.customInjectionMark.

**Comment by stamparm** [comment]
As described in [wiki](https://github.com/sqlmapproject/sqlmap/wiki/Usage#arbitrary-injection-point), you can use Havij style marker instead: `%INJECT HERE%` or `%INJECT_HERE%`
