### ISSUE TITLE
add waf service provider

### ISSUE THREAD

**Issue by 13Em0SPVPaoq** [sqlmapproject/sqlmap#4394]
http://www.kebuke.com/?id=1%20OR%201%20LIKE%201

https://www.gtmc.com.tw/

```
GTMC WAF1 Protection

waf@nm.gtmc.com.tw
```

`GTMC WAF(\d)* Protection` or `gtmc\.com\.tw` ?

**Comment by stamparm** [comment]
Thx

**Comment by stamparm** [comment]
p.s. only thing is that same site has multiple protections on itself, including the `RST/DROP` one. Thus, there is a possibility that the regex won't be triggered by payload(s) used by sqlmap because of lack of page content
