### ISSUE TITLE
about  --csrf-token

### ISSUE THREAD

**Issue by 13Em0SPVPaoq** [sqlmapproject/sqlmap#4395]
```
set-cookie: Validate=code=9R7Q9; path=/
```

![image](https://user-images.githubusercontent.com/69357109/96953018-be420080-1522-11eb-97f5-32fd4bdf6b13.png)

`--csrf-token` will search response header `set-cookie` ?

`--csrf-token Validate` ? `--csrf-token Validate=code` ? `--csrf-token set-cookie` ? ...

**Comment by 13Em0SPVPaoq** [comment]
one more thing... 

`--safe-url` ? maybe not...

go http://hidden.com/ , you will get a `set-cookie: Validate=` , and it will `GET` a request from `/ReadValidate.ashx`

AND.... the `/ReadValidate.ashx` is the `Validate` code

like this:
![image](https://user-images.githubusercontent.com/69357109/96954130-580aad00-1525-11eb-8cc8-d695ffbe714e.png)

**Comment by 13Em0SPVPaoq** [comment]
but..... you need to enter `inputCode1`... not `Validate`...

**Comment by stamparm** [comment]
`--csrf-token` will search for "token" named by yourself everywhere on the original page or page given with `--csrf-url`. It will search in Set-cookie, javascript, page content... in all the usual places
