### ISSUE TITLE
custom sign not working

### ISSUE THREAD

**Issue by 13Em0SPVPaoq** [sqlmapproject/sqlmap#4396]
`--base64 string --base64-safe -u "xxx.com/?string=aWQ9MSomcHdkPTE"`

`aWQ9MSomcHdkPTE` = `id=1*&pwd=1`

**Comment by stamparm** [comment]
Custom sign doesn't work inside the base64 encoded value like you did here. Also, there is no plan to include it as it would over-complicate stuff while everything works out of the box now with the regular approach
