### ISSUE TITLE
Update cookie value during testing.

### ISSUE THREAD

**Issue by Luciano5441** [sqlmapproject/sqlmap#4401]
Hello,

Is there any way to update the cookie value (initially loaded from a request file) during testing?
It can be useful if there is an auto logout function after x minutes. And it is necessary to login again manually which will update the cookie value.
Pausing during testing, modifying the request file and resuming doesn't work because the request file is loaded at the beginning of the tests.

Thank you

**Comment by stamparm** [comment]
With the latest revision you'll have a new option:

`--live-cookies=L..  Live cookies file used for loading up-to-date values`

It should point to a file with fresh/up-to-date cookie values. Trick is that once you delete its content, sqlmap immediately will stop and wait for the update of its content. You can do this indefinitely number of times during a run. In your case, you can just run sqlmap in one terminal, with `--live-cookies` pointing to a file containing starting cookie value, while in another terminal you can do a periodic deletion and filling of that same file

First terminal:
![1](https://user-images.githubusercontent.com/921555/97576333-54c46500-19ee-11eb-942e-ad704c44fda4.png)

Second terminal:
![2](https://user-images.githubusercontent.com/921555/97576339-5726bf00-19ee-11eb-9905-9f883bf0929f.png)
