### ISSUE TITLE
Is there a way to continue if it breaks off in the middle of printing a lot of data?

### ISSUE THREAD

**Issue by decuple-dream** [sqlmapproject/sqlmap#4406]
Please let me know if you have any related options. The Internet connection is not good, so you have to dump it even if it keeps disconnecting. (use --force-pivoting)

**Comment by stamparm** [comment]
1) try to use `--unstable          Adjust options for unstable connections` in those kind of cases. it will raise the thresholds for those lousy hosts
2) sqlmap should gracefully continue on with the dump, even if it fails abruptly in the subsequent runs (i.e. it stores the majority of retrieved stuff inside the "session" file)
3) take a look into log files inside `/home/<user>/.local/share/sqlmap/output/`. maybe you'll find some pieces that you could use even if waiting for subsequent sqlmap run results

**Comment by decuple-dream** [comment]
It's an honor to hear from you. I'll try it out.
