### ISSUE TITLE
about json_arrayagg

### ISSUE THREAD

**Issue by 13Em0SPVPaoq** [sqlmapproject/sqlmap#4407]
https://github.com/sqlmapproject/sqlmap/issues/4403

it looks like that it can work on oracle too
https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/JSON_ARRAYAGG.html

`JSON_OBJECT` `JSON_OBJECTAGG` `JSON_ARRAY` `JSON_ARRAYAGG` `JSON_OBJECT` 🤔

**Comment by stamparm** [comment]
![1](https://user-images.githubusercontent.com/921555/97433103-42c6c180-191d-11eb-89c9-e3ce19f38dae.png)
