### ISSUE TITLE
support post while use -m

### ISSUE THREAD

**Issue by rsj123** [sqlmapproject/sqlmap#4408]
while making some testing,POST test with -m is needed.
Such as test a common bug.We need to test tons of urls with the same post information.
eg.
sqlmap -m urls.txt --data="s1=test&s2=123*"

**Comment by stamparm** [comment]
With the latest revision you'll be able to do it:

![1](https://user-images.githubusercontent.com/921555/97563401-47ee4400-19e3-11eb-8376-69b49e7b9d5a.png)
