### ISSUE TITLE
session file not working.

### ISSUE THREAD

**Issue by decuple-dream** [sqlmapproject/sqlmap#4409]
command: sqlmap -r file --dbms=mssql --random-agent .... --force-pivoting -s /Users/<user>/.local/share/sqlmap/output/<name>/session.sqlite

Hello. If the dump ends halfway even if you randomly give the session option, it starts all over again. Is there any way?

**Comment by stamparm** [comment]
1st run:

![1](https://user-images.githubusercontent.com/921555/97562510-0610ce00-19e2-11eb-8ece-8147a417113d.png)

2nd run:

![2](https://user-images.githubusercontent.com/921555/97562527-0d37dc00-19e2-11eb-9bee-f765b39d611f.png)

Session file works. It depends on your case what is retrieved AGAIN and what's not retrieved. If you have bunch of junk inside then sqlmap will most probably need to retrieve it from start.
