### ISSUE TITLE
Disable XSS tests

### ISSUE THREAD

**Issue by yzf750** [sqlmapproject/sqlmap#4414]
Hi
Is it possible to disable the XXS tests that are being performed when running sqlmap? I have had a couple of projects where the application will automatically log out the user if XSS is detected preventing sqlmap from running any further.

Thoughts???

Thanks

**Comment by stamparm** [comment]
Please update to the latest revision and use the combination of these two switches:

```
    --skip-heuristics   Skip heuristic detection of SQLi/XSS vulnerabilities
    --skip-waf          Skip heuristic detection of WAF/IPS protection
```

You will most probably need to use both as in both cases there is usage of XSS-related payloads

**Comment by yzf750** [comment]
Thanks a bunch, much appreciated.
