### ISSUE TITLE
new way to get inside a oracle db?

### ISSUE THREAD

**Issue by 13Em0SPVPaoq** [sqlmapproject/sqlmap#4420]
https://securiteam.com/securityreviews/5qp0n20o0y/

https://sites.google.com/site/cwnematod/lateral_sql_injection

**Comment by stamparm** [comment]
Went through this and the original paper here http://www.davidlitchfield.com/lateral-sql-injection.pdf. Sorry, but I don't see a practical value in it. Too much fuzz for nothing.
