### ISSUE TITLE
log directory issue

### ISSUE THREAD

**Issue by meilisong1989** [sqlmapproject/sqlmap#4432]
**Describe the bug**
 hello, Sqlmap output specifies how to set the log directory, found that -L is invalid

The log file is empty！！！

20/11/18  18:02                 0 log
20/11/18  18:03             8,192 session.sqlite
20/11/18  18:02               120 target.txt

**Comment by stamparm** [comment]
1) There is no such option `-L`
2) There is option `-l`, but it is intended to be used for a totally different reason. Please take a look [here](https://github.com/sqlmapproject/sqlmap/wiki/Usage#parse-targets-from-burp-or-webscarab-proxy-logs)
3) Maybe you wanted to use `--output-dir` instead described [here](https://github.com/sqlmapproject/sqlmap/wiki/Usage#custom-output-directory-path)
