### ISSUE TITLE
msqql unable to retrieve database "invalid sql query"

### ISSUE THREAD

**Issue by qonsol-ctl** [sqlmapproject/sqlmap#4435]
**Describe the bug**
I'm facing a  problem  in more than one target with data retrieval (All in MSsql) although I'm able to get the banner and get the database name ( must use tamper=between ) but after that i'm unable to get the tables names i debug the issue but no luck the traffic response " invalid sql query "  i tried  parse-errors but with no additional info . i think i'm missing something

**To Reproduce**
1. sqlmap -u "https://vlun.aspx?" -p ID   --tamper=between  --level=5 --risk=3 --dbms=mssql --technique=B -D databasename --tables 

2. See error
 [CRITICAL] unable to retrieve the number of database tables

**Expected behavior**
retrieved the data 

**Screenshots**

**Running environment:**
 - sqlmap version updated
 - Installation method built-in 
 - Operating system: kali linux
 - Python version 3.7

**Target details:**
 - DBMS  Microsoft SQL Server
 - SQLi techniques found by sqlmap  boolean-based blind
 - WAF/IPS None 
 - Relevant console output [if any]
 - Exception traceback [if any]

**Additional context**
i do a lot of search before i post here but nothing help ...
i dreamed of a world with automated tools and dumped users :)

**Comment by stamparm** [comment]
Please, use `-t traffic.txt` to inspect on what is going on. In request/response pair containing `invalid sql query` it should be visible on what went wrong. If you find it, please reply it here
