### ISSUE TITLE
Allow to generate parameter on custom tamper scripts

### ISSUE THREAD

**Issue by itasahobby** [sqlmapproject/sqlmap#4436]
**Is your feature request related to a problem? Please describe.**
I ran into a web that uses a csrf token inside the form, tried to create a custom tamper trying to add it to a get parameter, however inside the tamper script you can only access the payload that is appended to the parameter to inject.

**Describe the solution you'd like**
Pass a argument to tamper scripts containing request parameters

**Describe alternatives you've considered**
Thought of creating a custom proxy that does that logic and connect sqlmap to it, however that scenario is less reusable

**Additional context**

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/Usage#preprocess-request
