### ISSUE TITLE
Modify an attribute for each request?

### ISSUE THREAD

**Issue by divukman** [sqlmapproject/sqlmap#4441]
I have a requirement to test PUT and POST requests to REST endpoint. 

Our endpoint receives JSON and one of the values needs to be random unique UUID for each request.

I have tried with tampers, thinking I'd be able to do it somehow, but it does not give me access to modify each request.

Is there a way to intercept a request and modify the value(s) I need? Or to randomize them with UUID values?

**Comment by stamparm** [comment]
1) In regular situations, [--randomize](https://github.com/sqlmapproject/sqlmap/wiki/Usage#randomly-change-value-for-given-parameters) should be enough
2) If you are not able to use 1) for specific JSON value, please use [--preprocess](https://github.com/sqlmapproject/sqlmap/wiki/Usage#preprocess-request)

**Comment by divukman** [comment]
@stamparm Thanks, will try.

**Comment by divukman** [comment]
Works like a charm, thanks.
Here's an example for the reference...

```
#!/usr/bin/env python

import uuid

def preprocess(req):
    if req.data:
        whateverId = str(uuid.uuid4()) 
        strRequest = req.data.decode("utf-8")
        strRequest = strRequest.replace("UUID", whateverId)
        req.data = strRequest 
```
