### ISSUE TITLE
--vuln command

### ISSUE THREAD

**Issue by hastalamuerte** [sqlmapproject/sqlmap#4443]
I suddenly find a --vuln command.. run it without any url and etc - it made some 34 tests with localhost and write [02:47:57] [ERROR] vuln test final result: FAILED
What is it? 

Thanks for your work. Sqlmap-best

**Comment by stamparm** [comment]
Hidden switch for internal testing. It creates a temporary vulnerable page on localhost and runs a sqlmap against it. Anyhow, user should not run it because it doesn't do anything useful than testing itself
