### ISSUE TITLE
Suggestions Feature Request 

### ISSUE THREAD

**Issue by niravsikotaria** [sqlmapproject/sqlmap#4445]
Respected Developers,

First of all thanks to all developers of SQLMAP. Your script working like "Rocket" 
I like to give one suggestion in Sqlmap. When I write cmd in sqlmap Like:

Ex:
Python sqlmap.py -u www.website.com --dbs --th (after --th when I press Tab it will complete --threads)
 
this is the small suggestion in SQLMAP. I hope you will update this in the feature.

Thanks

**Comment by stamparm** [comment]
This is shell specific (not sqlmap specific) - also, installation specific. Each shell has its own specific "autocomplete" mechanism. Please google for `autocomplete` to find how to do this.
