### ISSUE TITLE
delay between X requests?

### ISSUE THREAD

**Issue by tdias25** [sqlmapproject/sqlmap#4456]
i'm running some tests on a domain that has a firewall that blocks requests after +/- 18 requests, is it possible to delay the request after X numbers of request? in this case at every 18 requests.

the firewall returns a redirect url to a google captcha

**Comment by stamparm** [comment]
I would say that the firewall has the threshold of `#requests/<time>`. In such case I would say that there is no difference between doing deliberate delay between each request AND/OR doing one large delay at every Nth request.

Thus, I would suggest you to place with the (e.g. `--delay=5`):

`--delay=DELAY       Delay in seconds between each HTTP request`
