### ISSUE TITLE
Eval bug base64

### ISSUE THREAD

**Issue by lap1nou** [sqlmapproject/sqlmap#4457]
**Describe the bug**
On the newer SQLMap version (1.4.11#stable), this command line doesn't base64 encode my cookie:
sqlmap -u http://example --cookie="cookie=" -p "cookie" --eval="import base64; authenticator=base64.b64encode(cookie.encode('utf8'))"

But on older version of SQLMap (1.2.11), it works:
python sqlmap.py -u http://example --cookie="cookie=" -p "cookie" --eval="import base64; authenticator=base64.b64encode(cookie.encode('utf8'))"

**To Reproduce**
1. Run python sqlmap.py -u http://example --cookie="cookie=" -p "cookie" --eval="import base64; authenticator=base64.b64encode(cookie.encode('utf8'))" -v6
2. See that the cookie is base64 on older version, but not on newer

**Expected behavior**
The cookie should be base64 encoded.

**Screenshots**

**Running environment:**
 - sqlmap version 1.4.11#stable and 1.2.11
 - Installation method preinstalled on Kali Linux and git for the odler version
 - Operating system: Kali Linux 2020.4
 - Python version 3.8.6 for SQLMap 1.4.11 and Python 2.7.18 for 1.2.11

**Target details:**
 - DBMS MySQL
 - SQLi techniques found by sqlmap Generic UNION query
 - WAF/IPS no
 - Relevant console output N/A
 - Exception traceback N/A

**Additional context**

**Comment by stamparm** [comment]
1) I believe that you've messed something here. Most probably that `authenticator` should be inside the provided `cookie`, but there is none in provided commands
2) There is indeed difference between runs. I've successfully reproduced it, but between Python2 and Python3 and not between sqlmap versions

![2](https://user-images.githubusercontent.com/921555/101155561-9668b100-3627-11eb-8bce-97d3e449d201.png)
---
![3](https://user-images.githubusercontent.com/921555/101155569-98cb0b00-3627-11eb-8cf3-3c36dd0b8cc8.png)

3) Will "patch" for Python3, but you had to do your own `decode()` in case of Python3

**Comment by lap1nou** [comment]
Yes I messed up example because I wanted to change the cookie name, but I didn't change it everywhere, thanks anyway.
