### ISSUE TITLE
Index error on getting logs from api

### ISSUE THREAD

**Issue by tomjshore** [sqlmapproject/sqlmap#4461]
**Describe the bug**
There seems to be an error when getting the logs from the api. 
When trying to get the logs from line 9 to 20 an error message is returned as "Invalid start or end value, must be digits"

This is because we are doing ```end < start ``` when end and start are both Strings we should be doing ```int(end) < int(start)``` 

**To Reproduce**
1. Start the api server ```python3 sqlmapapi.py -s -p 8080```
2. Run the following 
```python
import requests
new_task_response = requests.get('http://localhost:8080/task/new')
task_id = new_task_response.json()['taskid']
bad_log_response = requests.get(f'http://localhost:8080/scan/{task_id}/log/9/20')
bad_log_response.text
```

**Expected behavior**
```'{\n    "success": true,\n    "log": []\n}'```
however it returns 
```'{\n    "success": false,\n    "message": "Invalid start or end value, must be digits"\n}'```

**Screenshots**
[https://prnt.sc/vva1vp](https://prnt.sc/vva1vp)

**Running environment:**
 - sqlmap version [1.4.12#dev]
 - Installation method [git]
 - Operating system: [linux]
 - Python version [e.g. 3.8.6]

**Target details:**
N/A

**Additional context**
#4460 Made a PR to fix

**Comment by stamparm** [comment]
Thx :). Merged
