### ISSUE TITLE
error - searching for error chunk length - maybe in endless loop?

### ISSUE THREAD

**Issue by ServerRaider** [sqlmapproject/sqlmap#4464]
Seems like the search of error chunk length is in a endless loop.
Screenshot: https://i.imgur.com/dTi3lhv.jpeg

Whats the reason?
I never seen this before in sqlmap.

//EDITED:
Second Test looks like the same: https://i.imgur.com/GvWqhpT.jpeg It's just hopping between 2 values.
0x36,456
0x37,457
0x36,456
0x37,457
0x36,456
0x37,457
...

When i set the DB-NAME with -D "DB-NAME" then it works perfect.
When no DB is set it runs into an endless loop...

After some more testing of this issue, i think the website makes the problem.
Other injections with same DBMS works perfectly.
If you want, send me a private message, i can send you the website and injection point for testing.

**Comment by stamparm** [comment]
It should (most probably) be fixed with the latest revision

**Comment by ServerRaider** [comment]
I have the newest evry time.
--uptate is in my start script ;)
