### ISSUE TITLE
[!] wrong installation detected (missing modules). Visit 'https://github.com/sqlmapproject/sqlmap/#installation' for further details"

### ISSUE THREAD

**Issue by spaniel80** [sqlmapproject/sqlmap#4475]
Hello all! 

I use Windows 10. 

A month ago I downloaded the sql map and everything worked. Later I deleted the user account in Windows with map map. Now I need sql map again, I downloaded new version of python 3.9 and sql map new version. But it gives an error. I tried to use also old versions of sql map, but also give an error.

Error:
[!] wrong installation detected (missing modules). Visit 'https://github.com/sqlmapproject/sqlmap/#installation' for further details"

Picture with error:

https://imgur.com/a/JlTTItR

I have searched on google but didn’t find the answer to my question and I don’t know how to solve this.

The Best Regards!

Sharif

**Comment by ben-gooding-hub** [comment]
I have the same issue, but the entire project is there in the same directory

**Comment by ben-gooding-hub** [comment]
I had the same issue, and had to pull the latest version, so `git pull`, then `git reset --hard`

**Comment by the-toster** [comment]
I have same problem, win 11, python 3.10.5, trying zipball & git clone.
