### ISSUE TITLE
checking and adding array parameter

### ISSUE THREAD

**Issue by abejads** [sqlmapproject/sqlmap#4476]
can you add and checking parameter to array?
Like this:
id=1&page=2
to
id[]=1'&page[]=2'

sometimes i got case when i add an array to parameter and add a single quote, its vulnerable

sorry my bad english and explanation

**Comment by stamparm** [comment]
A) array parameters are already being check as is
B) regular parameters won't be automatically transformed to array parameters because you got some hits here and there. that would include extra requests for little gain/benefit
