### ISSUE TITLE
Unable to connect to target using a SOCKS5 proxy on Kali (WSL 2)

### ISSUE THREAD

**Issue by aarivex** [sqlmapproject/sqlmap#4482]
**Describe the bug**
The sqlmap build thats shipped with Kali, version 1.4.12#stable in the time I'm writing this, has connectivity issues when using a proxy, SOCKS5 in my case, to connect to the target. Weirdly, this cannot be reproduced when cloned directly from this repo.

**To Reproduce**
`sqlmap --random-agent --proxy socks5://frankfurt.perfect-privacy.com:21 --proxy-cred "<user>:<pass>" -u <host>`

**Expected behavior**
A successful connection to the specified host through the specified proxy.

**Screenshots**
![WindowsTerminal_TaI8I27VVQ](https://user-images.githubusercontent.com/18628875/102410482-e284ff80-3ff0-11eb-8771-235b16863b65.png)

**Running environment:**
 - sqlmap 1.4.12, stable
 - Kali Linux on WSL 2 (Windows Subsystem for Linux), on top on Windows 10

**Comment by stamparm** [comment]
I've found one open SOCKS5 for testing. It required large `--timeout` and `--random-agent` to work in the first place:

![1](https://user-images.githubusercontent.com/921555/102482651-d25a3800-4063-11eb-962d-bde949caa1ce.png)

**Comment by stamparm** [comment]
Another (better example):

![1](https://user-images.githubusercontent.com/921555/102483797-87412480-4065-11eb-9068-3b214e7b9ef9.png)

p.s. if you "feel" that you are having problems with provided credentials, here I can't help you as I don't have such examples to reproduce

**Comment by stamparm** [comment]
@aarivex this could be the same Issue as #4479. Please update to the latest revision and retry
