### ISSUE TITLE
When the URL carries a # symbol, the following arguments will be invalid

### ISSUE THREAD

**Issue by xcg340122** [sqlmapproject/sqlmap#4489]
The target site has been pseudo-static and the following parameters will not be detected if the URL has a # symbol
Example:https://test.com/#/home/chess?navid=9&id=0
The ID and Navid parameters could not be detected

**Comment by stamparm** [comment]
https://stackoverflow.com/a/3664324

p.s. it is up to you to get the proper URL/data being sent to the server as sqlmap does not have browser-capabilities built-in
