### ISSUE TITLE
Choosing a system architecture in os-shell in PostgreSQL 8

### ISSUE THREAD

**Issue by kobyan1** [sqlmapproject/sqlmap#4490]
I am trying to get os-shell in PostgreSQL 8.
I get to the point of choosing a system architecture.
If I try to select 32-bit I get the error:

[00:31:20] [INFO] detecting back-end DBMS version from its banner
[00:31:20] [DEBUG] performed 0 queries in 0.00 seconds
what is the back-end database management system architecture?
[1] 32-bit (default)
[2] 64-bit
> 1
[00:31:26] [CRITICAL] unsupported feature on PostgreSQL 8 (32-bit)

If I try to select 64-bit I get the error:

[00:27:00] [INFO] detecting back-end DBMS version from its banner
[00:27:00] [DEBUG] performed 0 queries in 0.00 seconds
what is the back-end database management system architecture?
[1] 32-bit (default)
[2] 64-bit
> 2
[00:27:06] [CRITICAL] unsupported feature on PostgreSQL 8 (64-bit)

Why provide a choice when one or both options are not available?

**Comment by stamparm** [comment]
1) I don't see a way how `majorVer` could be calculated as `8` as in your case, if you haven't touched the sqlmap's code [here](https://github.com/sqlmapproject/sqlmap/blob/master/plugins/dbms/postgresql/takeover.py#L53-L74)
2) As you just skipped the issue template, now I have to do guessing here. Maybe you have a Linux 64-bit target (same thing applies for other OS/bit combinations). In such case, sqlmap goes through the following [directory](https://github.com/sqlmapproject/sqlmap/tree/master/data/udf/postgresql/linux/64) and tries to find the appropriate directory. As there is no such `8` directory, there is no matching UDF to be used (same thing applies for 32-bit version)
3) As I don't like replies with `but I have this or that`, I am locking this conversation
