### ISSUE TITLE
Use new proxie for every new request and option --check-proxy

### ISSUE THREAD

**Issue by shadowzoom** [sqlmapproject/sqlmap#4496]
Today i've got with one struggle, i need to connect from new ip every new request for sucessfull sqli (because target is blocking after 2 wrong requestes)
So maybe someone already has a method for it?
Or it would be good feature for sqlmap + proxy, example:
python sqlmap.py --proxy-file=proxies.txt --grabbing-new-proxy-after-request=1 (so every new sqlmap request will grab new proxy ip from file and use it)
And for --check-proxy also woul be good like --check-tor

**Comment by stamparm** [comment]
`--proxy-freq=PRO..  Requests between change of proxy from a given list`

Example run:

![1](https://user-images.githubusercontent.com/921555/103159886-fab60500-47ce-11eb-9937-755e00a85068.png)

p.s. please do not force me into `--check-proxy` too, as I've almost dropped this feature request
