### ISSUE TITLE
???

### ISSUE THREAD

**Issue by aviranos** [sqlmapproject/sqlmap#4507]
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
==================== RESTART: C:\sqlmap\lib\core\settings.py ===================
Traceback (most recent call last):
  File "C:\sqlmap\lib\core\settings.py", line 15, in <module>
    from lib.core.enums import DBMS
ModuleNotFoundError: No module named 'lib'
>>>

**Comment by stamparm** [comment]
This really looks like a beginner's mistake. Please read carefully the following stuff before running sqlmap again:

https://github.com/sqlmapproject/sqlmap/wiki/Download-and-update
https://github.com/sqlmapproject/sqlmap/wiki/FAQ#how-do-i-execute-sqlmap
https://github.com/sqlmapproject/sqlmap/wiki/Usage

**Comment by Miroslav999** [comment]
Got the same error on windows 10, It does not repeat on Linux

**Comment by stamparm** [comment]
@Miroslav999 there is something really wrong with your installation. i am able to run that same command on Windows 10 without any problems. Also, there is a lot of Windows users running it without any problems.

i would advise you to reinstall python, re-download sqlmap and rerun it. if issue persists, please be so kind to find out what's going on

**Comment by ZEPHYRUS434** [comment]
@Miroslav999 I have the same issue and now get it solved, turns out my antivirus software killed 'settings.py'

u can check quarantined files to see if there is any file that is related to sqlmap
