### ISSUE TITLE
SRS Document

### ISSUE THREAD

**Issue by apantzar** [sqlmapproject/sqlmap#4511]
Hi, I want to try to write a Software Requirements Specification document (SRS) about sqlmap. Is there maybe already one because I want to write a SRS for a project which does not have one.
Thank you!

**Comment by stamparm** [comment]
Sorry for my ignorance, but what's the value of SRS inside a project like sqlmap?

**Comment by apantzar** [comment]
I have to write a SRS document for an open-source program for my assignment at University. I want to write about a project like sqlmap because it is one of the most widespread tools for Bug Bounty and Penetration testing.
Thank you.

**Comment by stamparm** [comment]
Aha. So, that's not meant to be included in sqlmap. Thank you for clarification.

There is no such SRS for sqlmap. Thus, you can freely do it (for your assignment purposes)
