### ISSUE TITLE
--timeout/--ignore-timeouts doesn't work with large response with JSON AUTO/json_arrayagg()

### ISSUE THREAD

**Issue by shadowzoom** [sqlmapproject/sqlmap#4527]
--ignore-timeouts and --timeout doesn't work when response is huge and there is no network lag, just need to wait untill page will load huge data (30k lines/10MB on a page response)
`python sqlmap.py --output-dir=OUT -r 07.txt --force-ssl --dbms=mssql --technique=U --random-agent --level=3 --risk=2  -v 3  -D db_name -T tbl_name -C Column1,Column2,Column3 --dump --force-pivoting --timeout 300 --time-sec=300 --ignore-timeouts`

 is giving output
```
[15:25:44] [WARNING] large response detected. This could take a while
[15:25:44] [CRITICAL] unable to connect to the target URL. sqlmap is going to retry the request(s)
```

**Comment by stamparm** [comment]
`--ignore-timeouts` or `--time-sec` won't help you here. Please use huge `--timeout` (e.g. --timeout 9999999)

**Comment by shadowzoom** [comment]
> `--ignore-timeouts` or `--time-sec` won't help you here. Please use huge `--timeout` (e.g. --timeout 9999999)

even --timeout 999999 doesnt helping and if there are more like --timeout 999999999999

**[17:11:12] [CRITICAL] invalid value used for option '--timeout' ('OverflowError: timestamp too large to convert to C _PyTime_t')**

**Comment by shadowzoom** [comment]
p.s. sqlmap running under Python 3.8.6

**Comment by stamparm** [comment]
There was a silent Python3-related bug inside. Please pull the latest revision and retry

**Comment by shadowzoom** [comment]
Working, huge thanks, you the best! <3
