### ISSUE TITLE
[CRITICAL] WAF/IPS identified as ‘’modsecurity (Trustwave)’

### ISSUE THREAD

**Issue by fr1xx0b3y** [sqlmapproject/sqlmap#4529]
Error unable to retrieve the table names for any database 

"Although I put the correct database name that's what I come up with and at the bottom I get this message" 

406 (not accepted) - 4 times 

?? How do I bypass this, I have tried a bunch of tamper scripts and --level and --risk all that. I'm still learning but any suggestions on how to pass this waf , I have looked at all other GitHub questions on the same exact issue but still no one seems to show how it might be done.

**Comment by stamparm** [comment]
1) https://github.com/sqlmapproject/sqlmap/wiki/FAQ#which-tamper-script-to-use-to-bypass-a-wafips-protection
2) If you have a ModSecurity-based WAF on the other side, you'll have a bad time
