### ISSUE TITLE
Speed up REGEXP/Parsing large responsing with Python 3?

### ISSUE THREAD

**Issue by shadowzoom** [sqlmapproject/sqlmap#4530]
When union JSON AUTO/json_arrayagg() is dumping large table (100k lines) per 1 request, regexing and parsing into csv is too slow. I see via logs that data response is already downloaded but sqlmap regexing and parsing that response is lil bit slow. It taked 20 minuts to finish (on i7, 16GB ram)
The CPU, disk usage (even ssd) is loading no more than 30-40% during that time

Some fast techinques in python 3:
https://stackoverflow.com/questions/42742810/speed-up-millions-of-regex-replacements-in-python-3/42747503#42747503
https://towardsdatascience.com/regex-performance-in-python-873bd948a0ea

**Comment by stamparm** [comment]
so, you have some specific case, where sqlmap can stall at numerous places, while you are sending me first two links that you've spotted on Google for speeding up Python regex?

restraining myself from closing this down as invalid

**Comment by stamparm** [comment]
so. i've spent more than 10 years here making everybody happy, while users are sending me first two links from Google???

**Comment by stamparm** [comment]
so, i restrained myself for 2 minutes. i think that i failed in being zen master here.

please in future do not open dumb issues where you are trying to teach me programming with two links from google results

**Comment by stamparm** [comment]
just for other watchers here on what's the issue here in the first place. sqlmap has numerous preprocessing/processing/postprocessing mechanisms. some cases are "peculiar" and as such can cause problems in any of those places. giving me no context/content AND providing me with dumb HOWTO search links is the utter disrespect toward the developer

**Comment by stamparm** [comment]
found couple of places (e.g. third-party library `chardet`) which could cause this kind of problems. will make some patches, but @shadowzoom please do not open any issues anymore as i've lost my **zen** with yourself
