### ISSUE TITLE
How to dump the records using --sql-query="" ?

### ISSUE THREAD

**Issue by anburocky3** [sqlmapproject/sqlmap#4533]
I have 1 Million record grabbed last week and I want to grab the fresh records again and this time, I have to save it in the new csv file. 

Can we achieve this in sqlmap? I can see that I can execute the my custom query using --sql-query but its just logging not create any csv file. 

Any lead on this would be helpful.

**Comment by cat-from-attic** [comment]
Hi dude, use logic query in the end something like this WHERE id>''10000"
like --sql-query="select id,username,pass from users where id>'10000'"
will dump users which id more than 10000

**Comment by stamparm** [comment]
1) you won't get a new and shinny CSV with new entries with anything else other than redoing the whole `--dump` (in combination with `--fresh-queries` or `--flush-session`)
2) if there is some "id" alike column (as @cat-from-attic mentioned), you can try to dump only those rows having greater than predefined value (e.g. with `--sql-query` or better yet with help of `--where`)

**Comment by stamparm** [comment]
`I have 1 Million record grabbed last week and I want to grab the fresh records again and this time, I have to save it in the new csv file.` <- simplest Linux commands do wonders in this kind of cases
