### ISSUE TITLE
Strange bug

### ISSUE THREAD

**Issue by mzladich** [sqlmapproject/sqlmap#4535]
Hello.

Found something strange. Maybe it’s on my side bug, need you lookup please:

My problems:

1.Usage of —skip-urlencode on macOS with Python 3.9 with works smooth. But when I tried to use this option on Windows 10 Python 3.9 or Debian Linux Python 3.9, sqlmap wants to connect to the target. I’m disappointed of that bug. Could you please checkout it.

2.Usage of -v 3 (verbosity) on macOS passed smoothly (tamper=space2plus.py) :  `)%20AND+6438=4567—%20mUBx`
On Windows 10 Python 3.9 or Debian Linux Python 3.9, sqlmap wants to show (encode) payload right: `) AND 6438=4567— mUBx
`
Like no tamper usage. Bug or I’m dumb?

**Comment by stamparm** [comment]
1) `Usage of —skip-urlencode on macOS with Python 3.9 with works smooth. But when I tried to use this option on Windows 10 Python 3.9 or Debian Linux Python 3.9, sqlmap wants to connect to the target` <- I really don't understand what's the problem? You are trying to use `--skip-urlencode` and sqlmap wants to connect to the target?! That doesn't look like a problem. Maybe you wanted to say something else here (maybe `--skip-waf` or smth similar)
2) I really don't understand this part with `space2plus`
