### ISSUE TITLE
when sqlmapapi run as a server, how can i get the sqlShell through http?

### ISSUE THREAD

**Issue by githublihaha** [sqlmapproject/sqlmap#4537]
First， I run a sqlmapapi server.
Then i will through REST HTTP to start a task.
But, when i set the sqlShell to True, it will always running. 
So, how can i get the sql-shell through REST HTTP?
Thank you !

**Comment by stamparm** [comment]
1) It goes like this `--sql-shell`/`sqlShell` requires interactive user input. It is not meant to be used "remotely"
2) You can use `--sql-query` as a workaround as `--sql-shell` is nothing more than a console input wrapper for calling `--sql-query` functionality

**Comment by githublihaha** [comment]
ok. Thank you, sir !
