### ISSUE TITLE
Is there a way to make SQLMap scan a post request that does not have a parameter in the body, but you want it to insert payloads in the body?

### ISSUE THREAD

**Issue by kelleybryant** [sqlmapproject/sqlmap#4539]
Hello - Wondering if this could be a new feature or if this currently exists.  I have a POST request with no parameters in the body.  However, the POST request lets you write sql queries in the body without have a parameter and returns data.  

Example:

**POST /blah.com
Host: blah
Accept: blah
Referer: blah
Cookie:blah

SELECT username FROM all_users ORDER by username**

**Comment by stamparm** [comment]
Hi. Sorry but the answer is no nor there is an intention to support it.

Your case is too specific/non-standard. Thus, I would suggest you to manually asses your target with (e.g.) queries that you can find in [data/xml/queries.xml](https://github.com/sqlmapproject/sqlmap/blob/master/data/xml/queries.xml)
