### ISSUE TITLE
--os-shell does not cleanup after it's done

### ISSUE THREAD

**Issue by beppe9000** [sqlmapproject/sqlmap#4543]
is it supposed to? on my windows server (apache) it does leave `tmpabc.php` files in the webroot even if I add `--cleanup`

```
[00:10:58] [INFO] cleaning up the web files uploaded
[00:10:59] [WARNING] HTTP error codes detected during run:
404 (Not Found) - 6 times
```

I get this log after command ends but the files are still there if I check the folder with windows explorer
if I use `del *tmp*.php` in the shell the files are removed, not the best command... but it means the shell can delete itself

**Comment by stamparm** [comment]
There is no way to clean it up (properly) if stacked queries are not supported. So, sqlmap will try to clean it up, but if only SELECT statements are supported you'll be left with those `tmp` files

**Comment by beppe9000** [comment]
why not append a delete command after the shell is closed ?

**Comment by stamparm** [comment]
Did it work in the first place? I am missing that info

**Comment by beppe9000** [comment]
yes, it did work for me. maybe that can be added as an argument like `--rm-shell` that works when the os is known

**Comment by stamparm** [comment]
1) went through the `--os-shell` logic again. it goes like this. there is already an automatic cleaning logic inside. it uses the backdoor to delete the uploader and backdoor itself (`del /F /Q` or `rm -f ` on those files, depending on remote system)
2) if you capture the traffic file (`-t traffic.txt`) and go through its content (particularly meta-header `URI`), you'll see those "cleaning" payloads inside
![1](https://user-images.githubusercontent.com/921555/105031027-f9d26500-5a54-11eb-9cfd-e453295dbcf4.png)
3) checked if those files (from case 2) are actually deleted:
![2](https://user-images.githubusercontent.com/921555/105031102-179fca00-5a55-11eb-86f8-40bb8cc720d2.png)
4) there is a possibility that there are leftovers either from some abrupt sqlmap exits OR if sqlmap tried to upload those files to non-docroot directory before the final success (Note: those files from the successful attempts are deleted, but not those where sqlmap failed)

**Comment by beppe9000** [comment]
I see. Most likely this is due to how I exited the shell with CTRL-C
