### ISSUE TITLE
Can this project support Hive in the future ?

### ISSUE THREAD

**Issue by svjack** [sqlmapproject/sqlmap#4546]
It seems all exists db are located in dbms dir in plugins,  But i don’t find Hive.
Can this part add support of Hive or HDFS in the future ?

**Comment by stamparm** [comment]
sorry, but nope. focus are only RDBMS:

![1](https://user-images.githubusercontent.com/921555/104907083-d2ac6280-5984-11eb-8cd9-78d4eb8c2a6e.png)
