### ISSUE TITLE
Support for Salesforce Object Query Language

### ISSUE THREAD

**Issue by Jab2870** [sqlmapproject/sqlmap#4552]
**Is your feature request related to a problem? Please describe.**

No, it's simply another database type.

**Describe the solution you'd like**

I'd like sqlmap to support this type of db

**Describe alternatives you've considered**

N/a

**Additional context**

Here is the dbms documentation:

<https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql.htm>

**Comment by stamparm** [comment]
1) Top problem is getting the testing environment. If you are able to provide it or write down instructions how to make it (I can't find an easy way to do it), maybe I could do it
2) This looks like some mix of this and that. If it supports RDBMS-alike SQL queries, then I could do the implementation (if 1) is fulfilled)
3) If 1) and 2) are flunk, then 3) is obviously a flunk. Closing this down, but will reopen if you make some effort regarding 1) and 2)
