### ISSUE TITLE
How to kill current Sqlmap as soon as --alert executed?

### ISSUE THREAD

**Issue by rohitcoder** [sqlmapproject/sqlmap#4555]
Hi There,

I am trying to kill / Skip all tests as soon as --alert executed i tried adding this bash script 
``pgrep -f sqlmap | xargs kill`` under --alert but it doesn't work.

Any idea how to implement that?

**Comment by stamparm** [comment]
1) Easiest (kills all sqlmap instances):

`python sqlmap.py -u "http://testphp.vulnweb.com/artists.php?artist=1" --batch --alert "pkill -f sqlmap.py"`

![1](https://user-images.githubusercontent.com/921555/105501544-a8301180-5cc4-11eb-8c66-0b3221e2e1f8.png)

---

2) Dirty hack for killing only the current sqlmap instance:

`python sqlmap.py -u "http://testphp.vulnweb.com/artists.php?artist=1" --batch --alert "#" --eval="from lib.core.data import kb;[exit(0) if kb.alerted else None]"`

![2](https://user-images.githubusercontent.com/921555/105502029-40c69180-5cc5-11eb-9fdc-d20497756e96.png)

**Comment by rohitcoder** [comment]
Hi @stamparm 

My Usecase is different and your suggested solution doesn't work there, i am running sqlmap.py from another python file using ``os.system()``

I am attaching my output:
![Screenshot 2021-01-22 at 8 27 37 PM](https://user-images.githubusercontent.com/17665703/105507051-ba27a980-5cf0-11eb-8c6e-4b4549129567.png)

In the above screenshot, you can see pkill command executed but the script is still running...

I am running this using python test.py

and this is test.py contents

```python
import os
os.system("python3 tools/sqlmap/sqlmap.py --batch -u TARGET_URL_HERE --alert='pkill -f sqlmap.py'")
```

**Comment by stamparm** [comment]
my last message here:

![1](https://user-images.githubusercontent.com/921555/105508142-525f6780-5ccc-11eb-84dc-69e46d72c686.png)

p.s. you should really invest some time on your side and see what's going on. I would say that you are missing `pkill`
