### ISSUE TITLE
--tamper bug with json parameter or --base64 ?

### ISSUE THREAD

**Issue by c2xusnpq6** [sqlmapproject/sqlmap#4557]
`--base64` and `json parameter` won't work with `--tamper luanginx.py`

**Comment by stamparm** [comment]
known limitation where you can't mix `--base64` with some random tamper scripts around. not sure who or why somebody should do it in the first place

**Comment by c2xusnpq6** [comment]
> 
> 
> known limitation where you can't mix `--base64` with some random tamper scripts around. not sure who or why somebody should do it in the first place

If you send `id=1' OR '1' LIKE '1`, it will show all the record. But if you send `id=1' OR '1'='1`, it won't work, and show some error detail. @stamparm And it's base64-encoded

**Comment by c2xusnpq6** [comment]
@stamparm include `id=`

**Comment by c2xusnpq6** [comment]
I want to use `luanginx` to confuse the server admin
If sqlmap have a button about randomize the testing parameter and hidden it in a lot of useless parameters, it will be very useful.
