### ISSUE TITLE
Any way to stop a BULKFILE Scan (-m) while it's still going?

### ISSUE THREAD

**Issue by laidang08** [sqlmapproject/sqlmap#4562]
I have a scan running on a bulkfile with about 800 urls total and 200 urls scanned. It's taking a long time and I do not want to lose the progress and start over.

I'm wishing for a way to stop the scan while the scan is running. You cannot type in the terminal (this is Windows 10 btw) while it is scanning. If there could be some kind of hotkey to stop it, like in hashcat, then that would be awesome, however there isn't. If there is a way to stop it without the things I previously mentioned, please tell me.

Another way that this could be solved is if there is an output file for successful urls, but I am pretty sure this is already implemented. I just forgot to put it in my command line because I didn't know if I would need it or not. The final way that this could be solved is if you could type in a command while it is running.

**Comment by stamparm** [comment]
1) there is no way to type commands inside the non-prompt blocking python input. thus, you can't expect to just type "stop" or similar
2) in title you say that you want to stop, while inside the Issue text I have a feeling that you want to skip the current url. You should be able to do everything with `Ctrl-C`. if you press Ctrl-C single time you'll be asked whether you want to skip the current processing (i.e. current payload, or current target or...), while if you press Ctrl-C multiple times in a row, sqlmap should just quit everything
