### ISSUE TITLE
--sql-query can`t parse SQL statements properly

### ISSUE THREAD

**Issue by ChenYun4164** [sqlmapproject/sqlmap#4564]
**Describe the bug**

when use `python3 sqlmap.py -d "mysql://cyun:cyun@192.168.200.1:3306/Security"   --sql-query="show grants" -v 5` 
it response like 
```
...
[INFO] fetching SQL SELECT statement query output: 'show grants'
[19:58:17] [PAYLOAD] SELECT show grants
[19:58:17] [WARNING] (remote) ProgrammingError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'show grants' at line 1
...
```
and in mysql log  i see this  `		  120 Query	SELECT show grants`

this problem also in --sql-shell

**Running environment:**
 - sqlmap version [1.5.1.44#dev]
 - Installation method [git]
 - Operating system: [Linux kali 5.9.0-kali2-amd64 #1 SMP Debian 5.9.6-1kali1 (2020-11-11) x86_64 GNU/Linux]
 - Python version [Python 3.9.1]

**Target details:**
 - DBMS [Mysql]

**Comment by stamparm** [comment]
`SHOW GRANTS` is a SQL statement which can't just be injected into some vulnerable `SELECT` statement to get its output
