### ISSUE TITLE
@thezakman you should copy-paste the complete directory name. `AppData` is just a subdirectory inside your `Users` directory

### ISSUE THREAD

**Issue by thezakman** [sqlmapproject/sqlmap#4565]
@thezakman you should copy-paste the complete directory name. `AppData` is just a subdirectory inside your `Users` directory

_Originally posted by @stamparm in https://github.com/sqlmapproject/sqlmap/issues/3754#issuecomment-770385249_

I know, I just can't accesss or see it no matter what in windows 10, i've tried all i know about windows :P

**Comment by stamparm** [comment]
I really lack any context here. Can you please do some screenshots or anything. This all looks like you've mistyped or wrongly run some commands. Closing this down, but you can attach new information here
