### ISSUE TITLE
SQLMAP --batch command not found & User input force program exit

### ISSUE THREAD

**Issue by Teng-Zheng** [sqlmapproject/sqlmap#4567]
![sqlmap](https://user-images.githubusercontent.com/54031809/106477814-770fc800-64a0-11eb-8689-8077d0835d15.png)

**Comment by stamparm** [comment]
in bash (or whatever *nix shell) you have to enclose parameters containing `&` with quotes. In your case, I guess that you haven't done that with URL (`-u`)
