### ISSUE TITLE
Blind-error based injection with like query.

### ISSUE THREAD

**Issue by anburocky3** [sqlmapproject/sqlmap#4568]
**DB:** `MSSQL`

**Problem:**
I have the following url: `www.example.com/file.aspx` which accepts the post request and the column is vulnerable. I can inject my @@version, db_name(), user and so and its working great when in manually doing these.

By the prediction, we can find like, its the query:
```sql
SELECT * FROM TABLE WHERE name LIKE '%name_value%'
```
Here: TABLE is the table_name, name is the column name, name_value is the column value.

I can inject my queries like: `name=-ravi' and 1=(@@version)--` which is displaying the version in the output.

But whenever i do the select operation inside that for example: `name=-ravi' union all select 1,table_name,3 from information_schema.tables for xml path("")--` it receives the % error.

Since we are using our query inside the like method, the ending % has the problem..

I have fixed it with  `name=-ravi%'; union all select 1,table_name,3 from information_schema.tables for xml path("")--` and it acts like stacked queries. 

Vulnerable as stack queries support.

The main problem is that, while running `sqlmap.py` it says the column is vulnerable but exits due to the waf.

**What i want:**
- Select all tables and grab the values for education purpose.
- If i can do it with stack queries, what is the best methods to do that.

**Comment by stamparm** [comment]
you have WAF. thus, this can't be classified as an issue/bug. you can try to fool around with `--prefix`/`--suffix`, but that's it. expecting sqlmap to bypass WAF without your understanding of its internal mechanisms is impossible
