### ISSUE TITLE
Can't dump colums

### ISSUE THREAD

**Issue by erikformentera** [sqlmapproject/sqlmap#4574]
Hello everyone

I am having a problem in dump tables of a dbs.
I was able to dump information_schema, but when I want to dump the dbs I can only receive the table name without any columns within these.

I had to use tamper = space2comment to dump, I tried the usual list to verify the existence of columns but nothing.

The command is as follows: sqlmap -u "xxxx" --threads 4 --risk 3 --tamper = space2comment --dump -D "XXXX" -T "XXXX"

Can someone help me?

**Comment by erikformentera** [comment]
Can anyone help me?

**Comment by stamparm** [comment]
0) So, something (WAF?) is cutting your requests. There is no silver bullet here.
1) You should manually assess the target and research by yourself what's being cut out.
2) Afterwards, armed with that knowledge of target's internals, you could try to use `--tamper`. To get the list and digest of available tamper scripts you can use `python sqlmap.py --list-tampers`.
3) Additionally, you could try to run sqlmap with `--parse-errors` or `-t traffic.txt` in search for some obvious errors coming from the target

**Comment by erikformentera** [comment]
Hi sorry
I used the tamper space2comment to dump information_schema
but i don't understand why i can't dump the entire dbs.
Can i send you the target?

Thanks.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by erikformentera** [comment]
Can i send the payload that i have used?

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
