### ISSUE TITLE
SQLmap not handling 401 response from Login Form

### ISSUE THREAD

**Issue by isiko** [sqlmapproject/sqlmap#4578]
**Describe the bug**
I have a login Form I want to test, that when wrong credentials are entered, it returns a 401 Code. Problem is, SQLMap recognizes this as "I'm not allowed to see this Page". I know from manual testing that an SQLI Attack is possible, but I would like to be able to do it with SQLMap, because its just alot less time I have to invest :). The Form I have is the "OSU CTF" Capture the Flag form from Hacker 101.

Also I saw a [Stackoverflow Post](https://security.stackexchange.com/questions/196753/sqlmap-on-login-expect-401-reponse) from 2 Years ago which seems to have the same Problem

**To Reproduce**
1. Go to the Hacker101 Capture the Flag Site
2. Launch the "OSU CTF" Application
3. put Login request into SQLMap

**Expected behavior**
SQLMap gives me the following Error
```
[22:03:16] [CRITICAL] not authorized, try to provide right HTTP authentication type and valid credentials (401)
[22:03:16] [WARNING] HTTP error codes detected during run:
401 (Unauthorized) - 1 times
```

Heres the complete output from SQLMap:
```
        ___
       __H__
 ___ ___[']_____ ___ ___  {1.5.2.14#dev}
|_ -| . [']     | .'| . |
|___|_  [)]_|_|_|__,|  _|
      |_|V...       |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting @ 22:03:13 /2021-02-13/

[22:03:13] [INFO] parsing HTTP request from '.\test.raw'
[22:03:14] [INFO] testing connection to the target URL
[22:03:16] [CRITICAL] not authorized, try to provide right HTTP authentication type and valid credentials (401)
[22:03:16] [WARNING] HTTP error codes detected during run:
401 (Unauthorized) - 1 times

[*] ending @ 22:03:16 /2021-02-13/
```

**Running environment:**
 - sqlmap version: 1.5.2.14#dev
 - Installation method: git
 - Operating system: Microsoft Windows
 - Python version: 3.8.3

**Target details:**
 - DBMS: Probably MySQL
 - Relevant console output see Expected behavior

Also, I allready tried `--ignore-code=401` but then sqlmap didn't find anything

**Comment by isiko** [comment]
Also, I allready tried `--ignore-code=401` but then sqlmap didn't find anything

**Comment by stamparm** [comment]
how to reproduce this? any kind of injection of this sort should be straightforward (with or without the fine tuning with `--ignore-code`)

will close this down as invalid if this is just one of those "ahaaaaaa" cases where user misses the whole webapp workflow

**Comment by isiko** [comment]
I tried it with the --ignore-code  parameter, with the result that splmap didn't find the Injection. To Reproduce, go to https.//ctf.hacker101.com/ctf and start the Level called "OSU CTF" (at the Moment the Second last). You will be redirected to a login forum, whose request you will save for SQLMap. After that I tried to get sqlmap to execute a SQLi attack with the following commands:
- With Data from File
  - `python.exe sqlmap.py -r FILE_NAME`
     - not authorized
  - `python.exe sqlmap.py -r FILE_NAME --batch`
     - not authorized
  - `python.exe sqlmap.py -r FILE_NAME --batch --level 4 --risk 3`
     - not authorized
  - `python.exe sqlmap.py -r FILE_NAME --batch --level 4 --risk 3 --ignore-code 401`
   - didn't find Vulnerability
- With `-u` and `-data` Parameter
  - `python.exe sqlmap.py -u URL -data "username=test&password=test2"`
     - not authorized
  - `python.exe sqlmap.py -u URL -data "username=test&password=test2" --batch`
     - not authorized
  - `python.exe sqlmap.py -u URL -data "username=test&password=test2" --batch --level 4 --risk 3`
     - not authorized
  - `python.exe sqlmap.py -u URL -data "username=test&password=test2" --batch --level 4 --risk 3 --ignore-code 401`
     - didn't find Vulnerability

**Comment by isiko** [comment]
Also, when you intercept the request you can see, that the website returns a 401 code when you entered the wrong credentials.

**Comment by stamparm** [comment]
![1](https://user-images.githubusercontent.com/921555/109136941-f23f6380-7758-11eb-8da0-89e517576852.png)

p.s. although recognized, it doesn't seem to be usable for data enumeration
