### ISSUE TITLE
two problems (sqlmap does not see * in http traffic and does not write log file)

### ISSUE THREAD

**Issue by JackandBlackLLL** [sqlmapproject/sqlmap#4580]
Hello. 
I use

```
GET /images/ite/*/106x106/4960652929974-a_1.jpg HTTP/1.1
Host: XXXXXXX
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0
Accept: image/webp,*/*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: close
Referer: https://XXXXXXX/item_list/003/
Cookie: PHPSESSID=ii90qvc40fgnoi7cn64vcg8at6; __utma=255717279.959771657.1612874126.1612874126.1612874126.1; __ut$
```

And i got

[00:06:07] [INFO] parsing HTTP request from '/root/sqlmap/req1.txt'
[00:06:07] [CRITICAL] specified file '/root/sqlmap/req1.txt' does not contain a usable HTTP request (with paramete
rs)

Previously, everything was fine and sqlmap saw the * sign, but the last time it refuses to inject the request to the specified location. 

And my next problem, i updates sqlmap to last verion and now sqlmap does not write log file.
I work with mistake and my log file every time 0 bit

Sorry for my english, pls help me.

Why do you constantly change commands, before the call command was --sqlmap-shell, now just --shell
Was it that important?

**Comment by JackandBlackLLL** [comment]
Please indicate where I can read information about the latest changes, I tried to find on your site, but there is no such

**Comment by JackandBlackLLL** [comment]
/images/ite/*/106x106/4960652929974-a_1.jpg

sorry

**Comment by JackandBlackLLL** [comment]
GET /js/js.php/1* HTTP/1.1
Host: XXXXX
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: close
Referer: XXXXXXXX
Cookie: PHPSESSID=onuj41me6nr0mtja8qdmks6an1; _ga_X4VXZQNTDM=GS1.1.1612869871.1.1.1612870459.0; _ga=GA1.2.608815031.1612869872; _gid=GA1.2.2022008011.1612869888; _gat_gtag_UA_128951830_1=1

In this case point * work

**Comment by stamparm** [comment]
`Why do you constantly change commands, before the call command was --sqlmap-shell, now just --shell
Was it that important?` <- so, basically, you are getting a nice warning to just start using `--shell` instead of `--sqlmap-shell` and that is causing you problems?

**Comment by stamparm** [comment]
`And my next problem, i updates sqlmap to last verion and now sqlmap does not write log file.`

![1](https://user-images.githubusercontent.com/921555/108066559-c852b680-705f-11eb-8b57-680aa6028c6f.png)

**Comment by stamparm** [comment]
`Previously, everything was fine and sqlmap saw the * sign, but the last time it refuses to inject the request to the specified location.` <- i tried for previous versions and this is not true:

![1](https://user-images.githubusercontent.com/921555/108067257-d0f7bc80-7060-11eb-840d-18547f36ddb4.png)

Closing this all down as invalid

**Comment by stamparm** [comment]
Please do not open similar issues with this kind of false and/or unverified claims as they will be closed instantly in a similar manner
