### ISSUE TITLE
Continue dump a previous sites

### ISSUE THREAD

**Issue by LuongPhuHoa** [sqlmapproject/sqlmap#4589]
I dumped more than 10k lines of data but accidentally close the session. How can I continue to dump that database without dump all data ?

**Comment by hos903** [comment]
you can use that :  ........... --dump -o --start=10000

**Comment by LuongPhuHoa** [comment]
> you can use that : ........... --dump -o --start=10000

But I don't know which line or table it was on.

**Comment by hos903** [comment]
you can find your last command in target.txt ,

**Comment by LuongPhuHoa** [comment]
yes, but I used --dump-all option so I don't know the table entry

**Comment by stamparm** [comment]
so, basically, you don't want to run `--dump-all`, but use a specific table name which you don't recall?? sorry, but there is no such option
