### ISSUE TITLE
SQLMap Exit code for use in Github Actions

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [sqlmapproject/sqlmap#4590]
**Is your feature request related to a problem? Please describe.**
I am using SQLMap to [test my app in Github Actions](https://github.com/aidan-plenert-macdonald/grest/blob/main/.github/workflows/build.yml#L67)

I see the [logs generating error messages](https://github.com/aidan-plenert-macdonald/grest/runs/1992801768?check_suite_focus=true), but the exit code does not reflect the failure (ie. exit with code 1)

But also, the error messages are when there isn't an injection vulnerability.

**Describe the solution you'd like**
How can I make SQLMap fail if there is a security issue?

**Comment by stamparm** [comment]
Hi @aidan-plenert-macdonald 

Currently, sqlmap returns error code `1` if it fails with some really bad failure, while returns `0` if everything wents ok (no matter if found SQLi or not found SQLi).

This is basically inline with majority of applications nowadays, which return non-`0` only if something really bad happens (internally).

Best regards

**Comment by stamparm** [comment]
p.s. if you have some "smart" suggestion, i am opened for discussion, but currently i see it as ok-ish way to detect if everything went well in the run itself
