### ISSUE TITLE
no clear password(s) found

### ISSUE THREAD

**Issue by qszx** [sqlmapproject/sqlmap#4598]
sqlmap1.5.2#stable python3.9 kali2021.1
    Type: time-based blind
    Type: error-based
    Type: boolean-based blind

[22:02:50] [INFO] testing MySQL
[22:02:50] [INFO] confirming MySQL
[22:02:54] [INFO] the back-end DBMS is MySQL
back-end DBMS: MySQL >= 5.0.0
[22:02:54] [INFO] fetching database users password hashes
[22:02:54] [INFO] resumed: 'root'
[22:02:54] [INFO] resumed: '�'
[22:02:54] [INFO] resumed: 'root'
[22:02:54] [INFO] resumed: ''
[22:02:54] [INFO] resumed: 'root'
[22:02:54] [INFO] resumed: '�'
[22:02:54] [INFO] resumed: ''
[22:02:54] [INFO] resumed: '�'
[22:02:54] [INFO] resumed: 'root'
[22:02:54] [INFO] resumed: '�'
do you want to store hashes to a temporary file for eventual further processing with other tools [y/N] N
do you want to perform a dictionary-based attack against retrieved password hashes? [Y/n/q] Y
[22:02:54] [WARNING] no clear password(s) found
database management system users password hashes:
[*] root [2]:
    password hash: NULL
    password hash: �

**Comment by c2xusnpq6** [comment]
`--tamper` problem?
try `--hex` ?

**Comment by qszx** [comment]
> `--tamper` problem?
> try `--hex` ? or `--technique EB` ?

no tamper  hex，is technique EBT

**Comment by stamparm** [comment]
1) Try using `--technique=E --parse-errors --fresh-queries` to potentially find some "problems"
2) I don't see a problem here (apart from that binary looking char). There is nothing "problematic" with lack of password hashes
3) Try to force `--technique=B --hex --passwords --fresh-queries` to potentially try to get data in pretty definite way (boolean-based blind should be pretty "safe")
4) As there is a time-based SQLi here, I suspect that maybe it was the cause for those binary looking retrievals

Anyhow, this doesn't look like an issue from sqlmap

**Comment by qszx** [comment]
> 1. Try using `--technique=E --parse-errors --fresh-queries` to potentially find some "problems"
> 2. I don't see a problem here (apart from that binary looking char). There is nothing "problematic" with lack of password hashes
> 3. Try to force `--technique=B --hex --passwords --fresh-queries` to potentially try to get data in pretty definite way (boolean-based blind should be pretty "safe")
> 4. As there is a time-based SQLi here, I suspect that maybe it was the cause for those binary looking retrievals
> 
> Anyhow, this doesn't look like an issue from sqlmap

no effect
do you want to store hashes to a temporary file for eventual further processing with other tools [y/N] N
do you want to perform a dictionary-based attack against retrieved password hashes? [Y/n/q] Y
[04:20:42] [WARNING] no clear password(s) found
database management system users password hashes:
[*]  [1]:
    password hash: NULL
[*] root [1]:
    password hash: �
