### ISSUE TITLE
Sqlmap HTTP error. 

### ISSUE THREAD

**Issue by Aspecrt** [sqlmapproject/sqlmap#4600]
While` using SQLmap to pentest a pentesting site (http://testphp.vulnweb.com/index.php) it announced being a critical, unable to retrieve page content and a warning about HTTP error codes detected during the run. (403 forbidden) - 1 times. 

![unknown](https://user-images.githubusercontent.com/72759599/110225971-75c72600-7eb8-11eb-9122-7380c1fc8afb.png)

**Comment by stamparm** [comment]
1) Unreproducible:

![1](https://user-images.githubusercontent.com/921555/110252014-b0e25b80-7f83-11eb-9446-999da8893de7.png)

2) In future, please either retry with other IP, or use `--random-agent`, or use `--ignore-code=403`
