### ISSUE TITLE
Null columns Sqlmap

### ISSUE THREAD

**Issue by Vampireexe** [sqlmapproject/sqlmap#4604]
Hello, when try to test i receive null results but i'm sure that the db is full and not empty. Can someone tell me how can config sqlmap for this kind of error?

**Comment by stamparm** [comment]
1) you haven't properly filled the issue template. there is 0 useful info here
2) not sure how you are sure. there is 0 useful info here
3) try to use different techniques (`--technique`) or `--hex` or `--no-cast`
4) maybe there are privilege problems. try to use `--parse-errors` to find out if any error pops out

**Comment by Vampireexe** [comment]
i have try this commands but the problem still.

**Comment by Vampireexe** [comment]
![screenshot error columns](https://user-images.githubusercontent.com/71180858/111151835-45564a80-8590-11eb-9fdb-c99d3584260c.png)
For privacy i have delete the path and the name of tables. Anyway this is the result of columns with Sqlmap.

**Comment by Vampireexe** [comment]
can you re-open? i don't have resolved.
