### ISSUE TITLE
Sqlmap isn't working when using nat network IP address 

### ISSUE THREAD

**Issue by ImSkaarz** [sqlmapproject/sqlmap#4610]
Hello,

I have two virtual machines that are in the same "nat network" and they have a bridge connection too. When i try this command with sqlmap (Nat network ip address) : 

"sudo python sqlmap.py -u 'http://10.0.2.7/index.php?username=test' --dump"

Sqlmap tell me that all my tested parameters do not appear to be injectable. But when i'm using the other interface of the server  (Bridge interface) :

"sudo python sqlmap.py -u 'http://192.168.1.55/index.php?username=test' --dump"

Sqlmap gives me all the informations about the database that is behind the website.

So i don't really know why this is only working on the "192.168.1.55" IP address. I tried a lot of things, i tried to disconnect the bridge interface on both machines but this change nothing. I think it can come from the apache configuration but i don't really know.

If you need more informations, source code or anything, i will give it to you !

Thanks in advance,

ImSkaarz

**Comment by stamparm** [comment]
Sorry, but this doesn't look like the sqlmap issue. You should get the same display in the browser when accessing those URLs. Also, please make a proper debugging by appending the `-t traffic.txt --parse-errors` to each run.
