### ISSUE TITLE
Amazon Redshift DBMS Not Supported Error

### ISSUE THREAD

**Issue by 0p71mu5** [sqlmapproject/sqlmap#4611]
**Describe the bug**
http://sqlmap.org/ mentions Full support for MySQL, Oracle, PostgreSQL, Microsoft SQL Server, Microsoft Access, IBM DB2, SQLite, Firebird, Sybase, SAP MaxDB, Informix, MariaDB, MemSQL, TiDB, CockroachDB, HSQLDB, H2, MonetDB, Apache Derby, **Amazon Redshift**, Vertica, Mckoi, Presto, Altibase, MimerSQL, CrateDB, Greenplum, Drizzle, Apache Ignite, Cubrid, InterSystems Cache, IRIS, eXtremeDB, FrontBase, Raima Database Manager, YugabyteDB and Virtuoso database management systems.
Here it mentions that **Amazon Redshift** DMBS is supported.

**To Reproduce**
1. Run sqlmap with `--dbms="Amazon Redshift"` flag
2. See error: `[13:40:52] [CRITICAL] you provided an unsupported back-end database management system. Supported DBMSes are as follows: Altibase, Apache Derby, CrateDB, Cubrid, Firebird, FrontBase, H2, HSQLDB, IBM DB2, Informix, InterSystems Cache, Mckoi, Microsoft Access, Microsoft SQL Server, MimerSQL, MonetDB, MySQL, Oracle, PostgreSQL, Presto, Raima Database Manager, SAP MaxDB, SQLite, Sybase, Vertica, Virtuoso, eXtremeDB. If you do not know the back-end DBMS, do not provide it and sqlmap will fingerprint it for you.`

**Running environment:**
 - sqlmap version - 1.5.3.16#dev
 - Installation method - download from http://sqlmap.org/
 - Operating system - Microsoft Windows 10
 - Python version - 3.9.1

**Comment by stamparm** [comment]
![1](https://user-images.githubusercontent.com/921555/111972028-40981600-8afd-11eb-9ad5-5107259c6fdd.png)

**Comment by stamparm** [comment]
1) it was "hidden" behind the `redshift` alias. Now, with the latest revision, you can also force it also with `amazon redshift`
2) `Amazon Redshift` is the name of the PostgreSQL fork. Thus it was not being visible in that DBMS list. With the latest revision you'll see it too in the sqlmap's listing (to be consistent with the list from the official webpage)
