### ISSUE TITLE
Single column enumeration (-C) broken for Firebird backend

### ISSUE THREAD

**Issue by ptitdoc** [sqlmapproject/sqlmap#4613]
**Describe the bug**
When using sqlmap against a firebird backend, the -C options does not work properly.

When counting the number of items in the column, the select request appends the database name FIREBIRD_MASTERDB to the column name, which does not exists in a firebird context.

The consequence is that sqlmap shows all rows as NULL.

**To Reproduce**
1. Run sqlmap with the options -C MY_COLUMN_NAME on an sql injection with a firebird backend
2. See all rows reported as NULL

**Expected behavior**
sqmap should have a positive count of rows and start enumerating all rows.

**Running environment:**
 - sqlmap version: 1.5.2
 - Installation method: pacman -S sqlmap
 - Operating system: Archlinux
 - Python version: 3.9.1

**Target details:**
 - DBMS: Firebird

**Additional context**
This problem can be avoided by retrieving the data using a select query.

It is also possible to write a tamper script to clear the invalid database name in all requests:
```
from lib.core.enums import PRIORITY

__priority__ = PRIORITY.NORMAL

def tamper(payload, **kwargs):

    retVal = payload.replace("FIREBIRD_MASTERDB.","")
    return retVal
```

**Comment by stamparm** [comment]
@ptitdoc i can't reproduce this with any technique. Additionally, it is very strange that the "meta" database name `FIREBIRD_MASTERDB` is going to the payload being sent to the other end. Furthermore, `FIREBIRD_MASTERDB` should not appear in any query for `-C` because database/schema names are skipped in such case.

![1](https://user-images.githubusercontent.com/921555/112765164-35b51800-900c-11eb-8dc8-7b5e4b6102c7.png)

![2](https://user-images.githubusercontent.com/921555/112765166-36e64500-900c-11eb-8a7f-bd6de768fdfd.png)

![3](https://user-images.githubusercontent.com/921555/112765167-377edb80-900c-11eb-834d-bead8bcd5bc3.png)

**Comment by stamparm** [comment]
Closed this down. Please give more details as I am not able to reproduce this "problem" based on given information

**Comment by stamparm** [comment]
p.s. i was able to reproduce this with `--sql-shell` and `--sql-query`, but you are not supposed to use "meta" database/schema `FIREBIRD_MASTERDB` in such cases

**Comment by stamparm** [comment]
p.p.s. with the latest revision `--sql-shell` and `--sql-query` should automatically remove that `FIREBIRD_MASTERDB` too if being used in the user's query

**Comment by ptitdoc** [comment]
Hello, I confirm that I never added FIREBIRD_MASTERDB explicitely. Also, the database name was only added for the COUNT query (the one counting the number of rows in the columns).

I also use successfully `--sql-query` to solve this issue.

**Comment by stamparm** [comment]
@ret2src I've pushed a related patch, but I am not sure that it will solve the problem. Thing is that I am not able to reproduce this in any way. Tried with different techniques and different options, on Firebird, and I am always getting proper results

**Comment by ret2src** [comment]
Maybe it's related to the version? In my case, the affected system ran Firebird 2.5.7

**Comment by stamparm** [comment]
in my case, it is `Firebird 2.0`. nonetheless, you should retry with the latest revision (i made some (maybe) related change)
