### ISSUE TITLE
SQLMap Strange Db Name

### ISSUE THREAD

**Issue by anasbousselham** [sqlmapproject/sqlmap#4628]
Hi,
When I retrieve the --dbs I have a strange name like this:
```
[*] `1\x19`
[*] `2\x02!\tp`
[*] `2`
[*] `6N\x02!`
[*] `\t j`
[*] `\t`
[*] `\tX\x7f`
[*] `\x02!`
[*] `\x02\x13BE-3Z\x10^\x03of1`
[*] `\x02\x17a1`
[*] `\x02`
[*] `\x02A`
[*] `\x02bOY%`
[*] `\x02WDn%`
[*] `\x037m`
[*] `\x03`
[*] `\x04-`
[*] `\x04`
[*] `\x05`
[*] `\x05Q`
[*] `\x06\xb9\x1fn\x7f`
[*] `\x07`
[*] `\x11`
[*] `\x13e=A"\x162l``
\x04A\x08\x04A\x04A\x83p8\x04AA\
```
I can't figure out why this happens

Thank you,

**Comment by hosxxtn-collab** [comment]
are you using a tamper  ?? you tried --text-only ?

**Comment by anasbousselham** [comment]
My req : `--random-agent --dbs --batch --threads=2 --no-cast`
My Live V : 
`[16:57:59] [INFO] retrieved: ..Q.:   ?= g) 2l ?A?      Y  SLqZA  EG !     "F !S?CQ    UR? QQ  Qa    A#IKa??!Y  ?b&        ,     bI I? 5  A??   a ? #? a   ???  A9?%?! ?.. 12201/42717 (28`
`[16:59:22] [INFO] retrieved: ..#? a   ???  A9?%?! ??? RC?AX OW ??? ?" #! A    ? ?!AQ?!) ?   ?qg?% ?? ! % TJ    *! N ?? ??    i1? AB2 $K !c?aa     ?   [# ? !? Q!AQ  Q??.. 12317/42717 (28`

**Comment by anasbousselham** [comment]
> are you using a tamper ?? you tried --text-only ?

back-end DBMS: MySQL >= 8.0.0 (TiDB fork)

**Comment by stamparm** [comment]
I would say that you are dealing with false-positive. please rerun everything with `--flush-session --banner`. if you don't get a proper banner, then you don't have anything useful here

**Comment by mfcharaf** [comment]
I'm having same problem
How can I resolve this ?
![image](https://github.com/sqlmapproject/sqlmap/assets/13279034/984ece78-1eb8-42e9-a89f-0be344165205)

**Comment by stamparm** [comment]
@mfcharaf that doesn't look too useful. you have to check yourself why are you getting junk (something blocking you or queries or there is a false-positive)
