### ISSUE TITLE
id column of session.sqlite is not human readable

### ISSUE THREAD

**Issue by noraj** [sqlmapproject/sqlmap#4631]
I wanted to know which value SQLmap was using for some parameters and decided to open the `session.sqlite` (aka hashDB) to know.

While the value are human readable, the id column is not.

![image](https://user-images.githubusercontent.com/16578570/113690570-db7f1b80-96cb-11eb-807e-b3041599d763.png)

I dig into the code to know how it was encoded, but it's not reversible since a hash is used

https://github.com/sqlmapproject/sqlmap/blob/732b9670d2b6bd8bf72df1f5b6495ac9ec13d487/lib/utils/hashdb.py#L70-L85

And no mapping is done in the documentation.

Seeing `SQLite` as a value I can deduce that `4275977625654168434` must be the dbms but even so I don't even know what the key is:

```python
>>> int(hashlib.md5(b'dbms').hexdigest(), 16) & 0x7fffffffffffffff
683624256155988182
>>> int(hashlib.md5(b'DBMS').hexdigest(), 16) & 0x7fffffffffffffff
3973525652419986998
```

So could you document a way for a human to read `session.sqlite` for example by providing a mapping between the integer hash and the human readable key?

**Comment by stamparm** [comment]
1) This "feature" is not meant to be nor reversible nor used by users. It is strictly for internal data storage
2) Key is not easily calculated as you've tried to it by yourself. It also includes the hostname, hostpath, port and something called "milestone_value" (<- if something goes wrong in the implementation, I can easily invalidate the previous session data with this "kill switch". rarely changed, but for example, if the new form of data is being stored into the hashdb, previous data can be invalidated with this "feature"). Function itself can be found [here](https://github.com/sqlmapproject/sqlmap/blob/master/lib/core/common.py#L4953-L4960)
