### ISSUE TITLE
Misconfigured https on sqlmap.org

### ISSUE THREAD

**Issue by sbrl** [sqlmapproject/sqlmap#4638]
**Describe the bug**

HTTPS appears to be misconfigured on sqlmap.org

**To Reproduce**
1. Visit <https://sqlmap.org/> in your web browser
2. See warning

**Expected behavior**
The website loads without issue

**Screenshots**
![Selection_2021-04-11_16:24:53_001_b807911](https://user-images.githubusercontent.com/9929737/114310355-77e95980-9ae2-11eb-9bc3-d52229f9a18d.png)

**Running environment:**
 - sqlmap version: none
 - Installation method: none
 - Operating system: Ubuntu 20.10
 - Python version: 3.8.6

**Target details:**
 - DBMS: none
 - SQLi techniques found by sqlmap n/a
 - WAF/IPS n/a
 - Relevant console output n/a
 - Exception traceback n/a

**Additional context**
Ref https://github.com/tldr-pages/tldr/pull/5724/files#r611204719

**Comment by stamparm** [comment]
Fixed now:
![1](https://user-images.githubusercontent.com/921555/115673925-72dfa200-a34d-11eb-9bb7-c7e912362570.png)
