### ISSUE TITLE
query

### ISSUE THREAD

**Issue by qszx** [sqlmapproject/sqlmap#4647]
SQLamp        web            db

How to query database ip

**Comment by stamparm** [comment]
Depends on the DBMS type. I would suggest you to try the `--hostname`. If that doesn't show you the information of interest, you can always try to Google the "magic" query and try to retrieve the results with the `--sql-query="...."`

**Comment by qszx** [comment]
> Depends on the DBMS type. I would suggest you to try the `--hostname`. If that doesn't show you the information of interest, you can always try to Google the "magic" query and try to retrieve the results with the `--sql-query="...."`

--hostname is internal ip, boolean-based how to query public ip
