### ISSUE TITLE
DORK is ineffective

### ISSUE THREAD

**Issue by e2002e** [sqlmapproject/sqlmap#4650]
The -g option might not be parsing google answer correctly, there is always zero results (since a few weeks), this is not a problem of busted IP that google refuses to deal with, even with no vpn there is no results.

**Comment by stamparm** [comment]
Done a dummy patch (found that `http://` version doesn't redirect to the Google Consent). I hope that it will last for some time

**Comment by e2002e** [comment]
Thank you.

Le dim. 25 avr. 2021 20:37, Miroslav Stampar ***@***.***> a
écrit :

**Comment by e2002e** [comment]
Hey, I don't think this works. I still got no answer.
There is no other solution than to complete the procedure of consenting to the terms.
In the process of redirecting to the consent page, it gives you a CONSENT=PENDING cookie, when accepted, on the plain search page, this cookie is CONSENT=YES
You cannot just pass this cookie as is, there are ids and timestamps, it's all very obscure.
I am investigating furthermore and letting you know by mail if advancing.
