### ISSUE TITLE
--prefix not apply to some payload

### ISSUE THREAD

**Issue by ChenYun4164** [sqlmapproject/sqlmap#4662]
**Describe the bug**
my target parameter must prefix with odm_user , so i use --prefix=odm_user  but some payload not correct apply it 

**To Reproduce**
`python3 sqlmap.py -r zzz -p add_value -v 3 --prefix=odm_user --technique=U --flush-session --delay 1`

**Screenshots**
these is right payload 
![image](https://user-images.githubusercontent.com/45526365/116399421-7dbd9980-a85b-11eb-81bc-bbd5662241b0.png)

but these seem incorrect
![image](https://user-images.githubusercontent.com/45526365/116399604-b198bf00-a85b-11eb-853a-e9e521811ed5.png)

**Running environment:**
 - sqlmap version [1.5.4.1#dev]
 - Installation method [git]
 - Operating system: [Linux kali 5.9.0-kali2-amd64]
 - Python version [Python 3.9.2]

**Comment by stamparm** [comment]
You are messing something up here. Most probably you wanted to use `odm_user` inside the original parameter value or smth. `--prefix` should be used (in general case) for some non-alphanumeric boundary (e.g. `'`) which splits the original value (e.g. `1`) and the useful part of the payload (e.g. `AND 2=2`).

Also, I would suggest you to use `-t traffic.txt` to actually see what is being sent to the server itself. `PAYLOAD` could be misguiding here

**Comment by ChenYun4164** [comment]
Thank you for your patience. I was wrong about the use of this option 😊
