### ISSUE TITLE
modsec tamper

### ISSUE THREAD

**Issue by c2xusnpq6** [sqlmapproject/sqlmap#4665]
new way to bypass modsec?

Fun sql injection — mod_security bypass
https://infosecwriteups.com/fun-sql-injection-mod-security-bypass-644b54b0c445

**Comment by stamparm** [comment]
Proposed method looks like a mish-mesh of everything. Also, it doesn't look like something that can be used automated via tampering (i.e. it looks like something that can be used for individual/specific payloads)
