### ISSUE TITLE
sqlmap does not work if an HTTP body contains non-English chars

### ISSUE THREAD

**Issue by Nord-1** [sqlmapproject/sqlmap#4666]
Hi all, 

I have been trying to tweak SQLMAP to detect an SQLi in a login page that contains Arabic chars.

 For example, when submitting a login request, the header of the returned page is set to "content-type: text/html; charset=utf-8". But, the HTML page itself contains Arabic chars.  Can this be the reason why sqlmap is not able to detect it?  Can the --text-only option help in this situation?

 The website is .NET with MSSQL.  I tried all tamper scripts, different timings, --hpp option...etc, but still no luck!

**Comment by stamparm** [comment]
sqlmap is used against numerous character sets and languages at the everyday basis. Please do a proper inspection (e.g. via `-t traffic.txt`) to find the real cause - as the "non-english" chars are not the reason for no detection
