### ISSUE TITLE
--identify-waf not working

### ISSUE THREAD

**Issue by akmlvl** [sqlmapproject/sqlmap#4673]
As the title says that switch does nothing

**Comment by stamparm** [comment]
You are being presented with a HUGE warning message at start (i.e. the WAF checking functionality is being done by automatism):

![1](https://user-images.githubusercontent.com/921555/117631173-406edb00-b17c-11eb-92fb-7323828f48d0.png)

**Comment by stamparm** [comment]
Removed `--identify-waf` from Wiki pages
