### ISSUE TITLE
Update row

### ISSUE THREAD

**Issue by iunass** [sqlmapproject/sqlmap#4677]
How to update columns rows ?

**Comment by stamparm** [comment]
1) Stacking has to be "usable"/detected.... So, something like this has to work: `?id=1;UPDATE...`. This usually works in cases like MsSQL and PostgreSQL
2) Then you learn about the SQL `UPDATE` statement (e.g. https://www.w3schools.com/sql/sql_update.asp)
3) Then you try to use `--sql-query="UPDATE..."`
