### ISSUE TITLE
Access Database Comment Character %16

### ISSUE THREAD

**Issue by irsdl** [sqlmapproject/sqlmap#468]
Hello
We need to have %16 for MS Access databases as %00 does not normally work specially in ASP language that terminates the string before passing it to the database query. Therefore, %16 is more generic than %00 for MS Access comment (https://www.owasp.org/index.php/Testing_for_MS_Access).

These are the lines that need to be changed:

File: lib/core/agent.py - Line 221
if Backend.getIdentifiedDbms() == DBMS.ACCESS and comment == GENERIC_SQL_COMMENT:
            comment = "%16"

File: xml/queries.xml - Line 358
comment query="%16" query2="%00"

Thanks
Soroush

**Comment by AresS31** [comment]
Exactly! And as sqlmap first checks the -- comments (even when --dbms="Microsoft Acess) it takes an eternity to find the correct payload to use when setting --level 5. Hence thanks @irsdl  for your contribution.
Best,
Alexandre
