### ISSUE TITLE
FALSE NEGATIVE STACKED QUERIES

### ISSUE THREAD

**Issue by Yorchbs** [sqlmapproject/sqlmap#4680]
SQLMAP is sending this payload: 

> [PAYLOAD] )%2B"%2B(SELECT(0)FROM+(SELECT(SLEEP(10)))OXYS)%2B"*/%2BAND%2B(4967=4967

Which is working manually with a response of 10.83 seconds of delay, but SQLMAP is not detecting it:

> [19:14:23] [INFO] testing 'MySQL >= 5.0.12 stacked queries'
> [19:14:24] [PAYLOAD] )%2B"%2B(SELECT(0)FROM+(SELECT(SLEEP(10)))OXYS)%2B"*/%2BAND%2B(4967=4967
> [19:14:24] [WARNING] time-based comparison requires larger statistical model, please wait...............
> [19:15:14] [DEBUG] SSL connection error occurred for 'PROTOCOL_TLSv1_2' ('OSError: Error')
> ............ (done)
> [19:15:38] [CRITICAL] considerable lagging has been detected in connection response(s). Please use as high value for option '--time-sec' as possible (e.g. 10 or more)
> [19:15:38] [PAYLOAD] %2B"%2B(SELECT(0)FROM+(SELECT(SLEEP(10)))OXYS)%2B"*/
> [19:15:39] [PAYLOAD] ')%2B"%2B(SELECT(0)FROM+(SELECT(SLEEP(10)))OXYS)%2B"*/%2BAND%2B('kFuQ'='kFuQ
> [19:15:42] [PAYLOAD] '%2B"%2B(SELECT(0)FROM+(SELECT(SLEEP(10)))OXYS)%2B"*/%2BAND%2B'jhsD'='jhsD
> [19:15:42] [PAYLOAD] %2B"%2B(SELECT(0)FROM+(SELECT(SLEEP(10)))OXYS)%2B"*/--%2BDMNf
> [19:15:50] [DEBUG] skipping test 'MySQL >= 5.0.12 stacked queries' because the level (3) is higher than the provided (1)

ALL the payloads sent by sqlmap are working manually, but not being detected by sqlmap, I dont know if this is am issue of SQLMAP or if it's my problem. I would be gratefully if womeone helps me or if someone confirms is an SQLMAP bug.

> --batch --random-agent --threads 10 --keep-alive --tamper space2twob --dbs --dbms MySQL --technique S -v 3 --time-sec 10

Thanks.

**Comment by stamparm** [comment]
You are basically using SQLi inside the provided sqlmap parameter values `SELECT(SLEEP(10)))`, while being warned by sqlmap to not do that. Closing as invalid
