### ISSUE TITLE
Getting this error on kali, using it on termux its working fine...

### ISSUE THREAD

**Issue by Shaduken** [sqlmapproject/sqlmap#4682]
[CRITICAL] error occurred while accessing session file '/root/.local/share/sqlmap/output/www.testphp.vulnweb.com/session.sqlite' ('OperationalError: disk I/O error'). If the problem persists please rerun with '--flush-session'

[WARNING] there has been a problem while writing to the session file ('OperationalError: no such table: storage')

ive been hanging with this last two days... does anyone know what is going on... searching around net found few comments about but so far without lucky.

Already tried rerun with --flush but keep getting the same error.

**Comment by stamparm** [comment]
1) Something is wrong with your setup. It doesn't make any sense that `termux` works, while non-`termux` doesn't.
2) Try to run sqlmap with `--purge`, then rerun everything. Maybe it will clear the problem
3) If 2) fails, fry to run everything with `--output-dir=/tmp`. Anyhow, something is messing with your "output" directory in your home directory, preventing it to do changes there

**Comment by Shaduken** [comment]
Thx bro, ill rerun again. if nothin works maybe an fresh clean need to happen, too heavy atm.
