### ISSUE TITLE
Sqlmap is mangling binary data before making HTTP requests

### ISSUE THREAD

**Issue by elliot-kaplan** [sqlmapproject/sqlmap#4698]
I'm attempting to use sqlmap to test an application that takes input over HTTPS in the form of Tag Length Value (TLV) encoded binary data. However, sqlmap is mangling certain characters before making the requests, which is rendering the test non-viable.

**Describe the bug**
Binary POST data is being mangled by sqlmap. Null bytes are removed and any character in [0x80,0xFF] is replaced by `?`.

**To Reproduce**
A minimum example of this is

```
$ sqlmap.py --proxy http://localhost:8080 -u https://example.com/ -H 'Content-Type: application/msbin1' --method POST --data "$(<teststr.bin)*xxx" --no-cast --no-escape
```
where `teststr.bin` is a binary file generated by 
```
$ python -c 'import struct; open("teststr.bin", "wb").write(b''.join(struct.pack('B', i) for i in range(0x00,0x100)))'
```

See Screenshot below for the the initial request intercepted by Burp. The null byte is removed, Any byte with value >=0x80 is replaced with "?"

**Expected behavior**
I would expect the data to be passed through unaffected. 

**Screenshots**
![image](https://user-images.githubusercontent.com/57731555/120385557-92c39780-c2f5-11eb-8a09-ea76a46667d9.png)

**Running environment:**
 - sqlmap version: 1.5.2.16#dev
 - Installation method: git
 - Operating system: Ubuntu 20.04.2 LTS \n \l
 - Python version 3.8.5

**Target details:**
N/A

**Additional context**

In other attacks l've been able to write tamper scripts like
```
def tamper(payload, **kwargs):
    output = modify(payload)
    return output.decode('iso-8859-1')
```
and have sqlmap send the proper binary data to the target.

**Comment by stamparm** [comment]
What happened?

**Comment by elliot-kaplan** [comment]
l figured out what l'd been doing wrong. l hadn't realized that l could place `*` into a raw request file (`-r /path/to/req`) and have sqlmap use that as a custom injection point.

Once l figured that out, sqlmap started making the requests that l'd been expecting.

**Comment by stamparm** [comment]
I absolutely love self-resolving Issues :)
