### ISSUE TITLE
Set number of requests during time-based comparison

### ISSUE THREAD

**Issue by electroxero** [sqlmapproject/sqlmap#4707]
# Description
Using `time-based` technique, sqlmap always perform the `time-based comparison requires larger statistical model, please wait`

I know it could be a problem set an arbitrary amount of request to perform this statistical model, but I think sometimes with a site which have a long response time could be very useful.

# Real life example
I'm working on a site that responds in 3-5 seconds, so to perform the detection I have used `--time-sec 20`.

Now sqlmap has the correct vector but every time I run it it will perform the `time-based comparison` performing too many requests and also using a lot of time to doing it.

# Possible Solution
1. Implement a flag that could allow the user to set the amount of requests to perform during the `time-based comparison`
2. If I launch sqlmap the 2d time after the detection phase, for example, save the amount of second based on the comparison already done (the same principle applied to --fresh-queries or --flush-session)

**Comment by stamparm** [comment]
There are couple of problems:

1) `--time-sec` in some cases (e.g. heavy-queries) does not do the exact delay in seconds, but the approximate
2) MySQL in some cases if you say e.g. to delay for 5 seconds will actually delay for 4.9 seconds for some strange reason
3) Statistical model is either valid or invalid. If you use some lower number of requests for making a statistical model (e.g. 5), you will get an invalid statistical model. Period
4) 5 minutes before network latency could add up to 1.0 second to the regular response, while all of a sudden the latency drops to 0.2 seconds <- models are valid only for the current run
