### ISSUE TITLE
A lot of original (non-modified) requests generated

### ISSUE THREAD

**Issue by YuriyPobezhymov** [sqlmapproject/sqlmap#4717]
**Describe the bug**
During script running with `--skip-heuristics` argument a lot of original (non-modified) requests processed.

**To Reproduce**
1. Try run lab https://portswigger.net/web-security/sql-injection/union-attacks/lab-retrieve-data-from-other-tables by clicking 'Access the lab' button.
2. Configure Burp Suite to catch traffic from lab. Another way use `-t` when run sqlmap to log traffic to the file.
3. Run script `python3 /usr/share/sqlmap/sqlmap.py -u https://ac1a1f8a1f4e67c680904391001f0006.web-security-academy.net/filter\?category\=Pets --batch --answers="extending=N" --skip-waf --skip-heuristics --random-agent --flush-session --proxy=https://127.0.0.1:8080`.
2. See HTTP history
![Screenshot_20210619_185728](https://user-images.githubusercontent.com/2714671/122648112-3bfcf100-d130-11eb-8b18-3147843f6bbe.png)

**Expected behavior**
I don't understand the purpose for those selected requests. Possibly they need to be removed.

**Running environment:**
 - sqlmap version [1.5.4#stable]
 - Installation method [included in Kali Linux already as I remember]
 - Operating system: [Kali Linux 2021.1]
 - Python version [3.9.2]

Thanks, Yuriy.

**Comment by stamparm** [comment]
Those requests are related to that "statistical model" that sqlmap requires when doing the time-based SQLi probes:

![1](https://user-images.githubusercontent.com/921555/123317880-d42f1780-d52e-11eb-9c98-97262ba21269.png)
