### ISSUE TITLE
Work properly 

### ISSUE THREAD

**Issue by Anthonymcqueen21** [sqlmapproject/sqlmap#4726]
How do i know if SQLMap is working properly and updated to spec because mine works but give the same output for some reason when i test on DVWA (Damn Vulnerable Web Application). Even when the security level is low it still tells me that the submit button is not injectable, what does that mean ?

**- Is there a command i am missing ?
- Is there something else i am missing in terms of requirements ?
- Is there something else i am missing ?**

Thank you.

**Comment by stamparm** [comment]
1) "submit button is not injectable" < this doesn't look like a valid SQL injection case in the first case. Usually some regular parameter is injectable (e.g. `id` or similar)
2) based on https://medium.com/hacker-toolbelt/dvwa-1-9-viii-blind-sql-injection-with-sqlmap-ee8d59fbdea7, DVWA seems to be injectable to `id`. Not sure about your case though
