### ISSUE TITLE
Mulipart/form-data boundary is dynamic, sqlmap however uses a static value

### ISSUE THREAD

**Issue by janKuefner** [sqlmapproject/sqlmap#4730]
The boundary of my target is dynamic. See the following excerpts from post requests collected with Burp
1.
> Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryc0JxCt7KW3UCGSlz
2.
> Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryQlyYN3AZO0nfYlvs
3.
> Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryedBd0I7wIBUsEA43

couldn't manage to catch this with the `--csrf-token` option.
Is this a case of a non typical place for the token, so that the  `--csrf-token` feature will not cover this (as stated here https://github.com/sqlmapproject/sqlmap/issues/2)
or am I doing something else horribly wrong and mysql is actually capable of managing a dynamic border?

**Comment by stamparm** [comment]
1) i don't see any problems with either using dynamic or static multipart boundaries. can't imagine a scenario where either would play any difference
2) i don't see the connection between multipart boundaries and csrf-tokens. this part is not described here

**Comment by janKuefner** [comment]
Thank you for responding! Your response made me take a closer look into my issue, so I have more information to share:
1. SQLmap states:  `[WARNING] (custom) POST parameter 'MULTIPART #1*' does not appear to be dynamic`
I do think the multipart boundaries are dynamic though, since when i do several manual injections with burp, I always get a different multipart boundary supplied by the server. Is there an option to force dynamic multipart boundaries with SQLmap? 
If i do manual injection the server shows on the webpage "thought meddasge posted".
If i do injection with SQLmap and wireshark the responses the server doesn't show that message.
2. I thought the `--csrf-token` option sets the multipart boundaries dynamic. I now guess it doesn't.

fyi: Here is the full post request (incl. injection marker) from the target page

> POST /add HTTP/1.1
> Host: testapp.us-east-1.elasticbeanstalk.com
> Content-Length: 266
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
Origin: http://testapp.us-east-1.elasticbeanstalk.com
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryXsg8tJ8LeUH7m1yO
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Referer: http://testapp.us-east-1.elasticbeanstalk.com/add
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Connection: close
> 
> ------WebKitFormBoundaryXsg8tJ8LeUH7m1yO
Content-Disposition: form-data; name="thoughtMessage"
>  
> randomJibberish*
------WebKitFormBoundaryXsg8tJ8LeUH7m1yO
Content-Disposition: form-data; name="thoughtAuthor"
>  
> myName
------WebKitFormBoundaryXsg8tJ8LeUH7m1yO--

**Comment by stamparm** [comment]
sorry, this doesn't look like sqlmap issue. `when i do several manual injections with burp, I always get a different multipart boundary supplied by the server` <- not sure what kind of argument is this
