### ISSUE TITLE
Bug command

### ISSUE THREAD

**Issue by Y4NDR1** [sqlmapproject/sqlmap#4741]
**Describe the bug**

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**

**Running environment:**
 - sqlmap version [e.g. 1.3.5.93#dev]
 - Installation method [e.g. git]
 - Operating system: [e.g. Microsoft Windows 10]
 - Python version [e.g. 3.5.2]

**Target details:**
 - DBMS [e.g. Microsoft SQL Server]
 - SQLi techniques found by sqlmap [e.g. error-based and boolean-based blind]
 - WAF/IPS [if any]
 - Relevant console output [if any]
 - Exception traceback [if any]

**Additional context**
![Screenshot_2021-07-19-06-15-59-311_com termux](https://user-images.githubusercontent.com/80796949/126085083-04469349-8896-4d01-9b96-3382bf92c123.jpg)

**Comment by stamparm** [comment]
enclose all parameters with quotes, especially if they contain `&` (e.g. `-u "http...." --dbs`)
