### ISSUE TITLE
Docs for REST API: Creating clients in different languages (docs of endpoints and accepted/returned JSON)

### ISSUE THREAD

**Issue by d4h0** [sqlmapproject/sqlmap#4746]
**Is your feature request related to a problem? Please describe.**

I'd like to integrate sqlmap into my personal tool/automatization via the REST API. The problem is, there isn't any documentation of the API (the API docs only contain information about the provided API client, and not much about the API itself).

**Describe the solution you'd like**

Ideally, there would be an API definition in a machine-readable format. Something like Swagger. In another issue one of the maintainers of this project mentioned that he will work on such a Swagger file (https://github.com/sqlmapproject/sqlmap/issues/3140#issuecomment-439057870), but, unfortunately, I can't find anything.

A swagger API definition would make it easy to generate API clients for many/most programming languages. For example with the generator from the [Open API Tools project](https://github.com/OpenAPITools/openapi-generator) completly automatically (Swagger and OpenAPI seem to be strongly related to each other).

Otherwise, something like a JSON schema file that describes the API endpoints and their input and output JSON objects would be okay, too (but then everybody needs to implement an API client generator by hand, instead of just using the Open API Tools generator).

I even would be happy with examples of the input and output JSON objects of every endpoint (especially, for the "new task" command). Then it would still be easier to implement an API client (compared to the alternatives in the next section).

**Describe alternatives you've considered**

I only see two alternatives:

1. Reading the code and trying to figure out what JSON is expected. I tried this, and it is difficult.

2. I probably could use Burp between the provided client and server to see what JSON data is provided.

Both options are tedious and error-prone, so an official solution would be greatly appreciated.

**Additional context**

Nothing. Just thanks for maintaining and improving this project. It looks like a tremendous task.

**Comment by stamparm** [comment]
For start, isn't this as simple as it gets? https://github.com/sqlmapproject/sqlmap/blob/master/lib/utils/api.py#L794-L883

**Comment by d4h0** [comment]
I wouldn't say "as simple as it gets", but I should be able to figure it out (as mentioned above).

I can get the endpoints from there easily, but not what JSON is accepted or returned (without reading and understanding the whole code that is triggered on the server. I'm not a Python programmer, btw. Syntax isn't a problem, but used libraries and functions are).

Is my assumption correct, that the `scan` endpoint expects an JSON object with keys that are equal to the `dest` argument of `parser.add_argument` ([as seen here](https://github.com/sqlmapproject/sqlmap/blob/8af87c7ea6b598e9ec9aa50ba4914572ca07c68b/lib/parse/cmdline.py#L114))?

The command line argument parser has a grouping feature, it seems. Would a group result in a key in the root JSON object to send?

So, [this](https://github.com/sqlmapproject/sqlmap/blob/8af87c7ea6b598e9ec9aa50ba4914572ca07c68b/lib/parse/cmdline.py#L124):

```python
        # Target options
        target = parser.add_argument_group("Target", "At least one of these options has to be provided to define the target(s)")

        target.add_argument("-u", "--url", dest="url",
            help="Target URL (e.g. \"http://www.site.com/vuln.php?id=1\")")
```

...would result in a request object of `{"Target": {url: "https://xy.com"}}`?

As mentioned, not really easy. And error-prone if I misunderstand some of the code (again, I'm not a Python programmer). I'm also assuming unknown JSON attributes would be just ignored by the server, instead of returning an error, which would make it difficult to notice some problems.

If there is a way to export the command line argument parser structure as a JSON structure (all groups, `dest` values, and the help texts) that would be already pretty helpful (this seems to be the most difficult part).

By the way, the `option` command isn't documented (also the `user` and `password` options). I believe documenting the API fully could help find features that aren't documented yet.

**Comment by stamparm** [comment]
`A swagger API definition would make it easy to generate API clients for many/most programming languages.` <- done with the latest revision (https://github.com/sqlmapproject/sqlmap/blob/master/sqlmapapi.yaml). I am under impression that this will be enough for you, based on your request, while I don't plan to expand this further

**Comment by d4h0** [comment]
Thank you, that helps.

I believe, the `error` keys are missing in all response objects, and, at least for the `/scan/{taskid}/start` endpoint, not all possible request properties are provided (only the "url" property is mentioned).

> I am under impression that this will be enough for you, based on your request

I'm using a statically typed programming language, and to generate (good) code for such a language, types need to be generated. This means, all input and output types (i.e. request and response) need to be known at code generation time (which isn't provided fully).

But this still is helpful, thanks again.

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/blob/master/sqlmap.conf <- for a list of options in `.../start`

**Comment by d4h0** [comment]
Nice – thank you!

This is the INI format, right?
