### ISSUE TITLE
Google Dork AutoResponse

### ISSUE THREAD

**Issue by rhyshanan** [sqlmapproject/sqlmap#4747]
Hello,

I've recently updated Sqlmap ... to version ... **sqlmapproject-sqlmap-1.5.7-7-g8af87c7**

It now prompts me to enter a response ... when before it did not

it now says:

> [22:39:20] [INFO] using search result page #1
> [22:39:31] [INFO] found 80 results for your search dork expression, all of them are testable targets
> [22:39:32] [INFO] found a total of 80 targets
> URL 1:
> GET http://www.theharmonyclub.net/page.php?id=2
> do you want to test this URL? [Y/n/q]

How can I **set an auto response**, such as:
`--answer="crack=n"`

How does it look????
`--answer="gdork=Q"`

What is the command to use please ... to set auto-response for this question ...

> do you want to test this URL? [Y/n/q]

Thank you

**Comment by stamparm** [comment]
1) `It now prompts me to enter a response ... when before it did not` <- not true. this has always been the case
2) just use `--batch` or `--batch --answer="test this URL=y"`
