### ISSUE TITLE
question: reduce amount of requests

### ISSUE THREAD

**Issue by marcelo321** [sqlmapproject/sqlmap#4757]
Hello,

This is not a feature request or problem, is more about a doubt I have.

Woudl it be possible to reduce the number of payloads sent in the detection phrase? I'm not just talking about sqlmap but more about personal projects.

Would it be possible to send a time-based polyglot payload that works in multiple insntaces in postgresql for example? would that be possible in mysql?

Asking here because I don't know which other place knows more abotu sqli explotation than here. Please close it if it doesn't apply here.

**Comment by stamparm** [comment]
Hi.

Sorry, but polyglot payloads are out of question. sqlmap requires a specific detection engine to be used for specific technique. Mixing lots of different detection engines would result with a mess (for sure).

You can always try to reduce the number of payloads by hard-setting the level and risk (e.g. `--level=1 --risk=1`), choosing specific technique (e.g. `--technique=BEU`), choosing specific DBMS (e.g. `--dbms=mysql`) or just do the test filtering (e.g. `--test-filter="BENCHMARK|FLOOR"`)

Cheers

**Comment by marcelo321** [comment]
Yeah I agree with you, this was a question to do in another tool I was thinking of, nothing to do with sqlmap, but here isn't the right place to ask about it
