### ISSUE TITLE
lib/controller/checks.py  checkFalsePositives(injection) have an error %d %d

### ISSUE THREAD

**Issue by hababy** [sqlmapproject/sqlmap#4763]
There is an injection point, the payload is "')&&SLEEP(5)&&('"
When I use --technique=T, the result is as follows
![image](https://user-images.githubusercontent.com/54878695/128491088-f1c9b206-f702-45e2-9f77-6e0f68f11247.png)

When this parameter is not applicable, the result is as follows
![image](https://user-images.githubusercontent.com/54878695/128490881-b570c136-0926-4499-a6c7-fb1db9b2ca8a.png)

![image](https://user-images.githubusercontent.com/54878695/128492650-66908038-f227-45fc-b155-32ffea212f0a.png)

I understand that there will be six verifications, this is the last verification, but this verification will trigger a sql syntax error, resulting in the injection point not being recognized

**Comment by stamparm** [comment]
this is not an error. this is deliberate request to see whether the other end will reply with error (i.e. non-TRUE reply)

**Comment by stamparm** [comment]
`resulting in the injection point not being recognized` <- do you read what you write? you have a boolean-based blind SQLi detected in your screenshot, and you write this kind of stuff. LOL

**Comment by stamparm** [comment]
`python sqlmap.py -u "http://testphp.vulnweb.com/artists.php?artist=1" --technique=T -v 3`

![Uploading 1.png…]()
