### ISSUE TITLE
--skip-urlencode does not prevent custom URLs (/param/blah) to be encoded

### ISSUE THREAD

**Issue by ringeringeraja** [sqlmapproject/sqlmap#4766]
**Describe the bug**

**To Reproduce**
1. Run sqlmap with --skip-urlencode -v6 on a custom URL 
2. See that characters remain being encoded (/param/blah'%20and%201=1)

**Expected behavior**
No URL encoding at all.

**Screenshots**

**Running environment:**
 - sqlmap version [e.g. 1.5.8#stable]
 - Installation method [git]
 - Operating system: [OpenBSD 6.9]
 - Python version [3.8.8]

My first thought was to use the --preprocess parameter to manually modify the URI, but the given example in https://github.com/sqlmapproject/sqlmap/issues/3505 looks like editing the response rather than the request. Please document it better.

**Comment by stamparm** [comment]
1) characters inside the path have to be url encoded. doing otherwise is illegal
2) furthermore, even if i do a short-circuit, python really doesn't like this kind of behavior:

![1](https://user-images.githubusercontent.com/921555/129106962-ee14b854-9c6c-485a-bbec-74c551447ac7.png)
