### ISSUE TITLE
[Microsoft][ODBC Visual FoxPro Driver] 

### ISSUE THREAD

**Issue by shadowzoom** [sqlmapproject/sqlmap#4787]
Sqlmap can't detect sqli at [Microsoft][ODBC Visual FoxPro Driver], is that normal or [Microsoft][ODBC Visual FoxPro Driver] is not supported now?

**Comment by stamparm** [comment]
`Visual FoxPro` was never supported. Isn't FoxPro dead?

![1](https://user-images.githubusercontent.com/921555/132542120-92fa9c94-f6dd-4965-90af-e91f466e8564.png)
