### ISSUE TITLE
Question: Is possible to minimize the amount of requests?

### ISSUE THREAD

**Issue by marcelo321** [sqlmapproject/sqlmap#4788]
This is just a personal question. I read all the flags a couple of times trying to find flags to try find flags that reduce the amount of requests needed for the detection phase of trying to find valid injections.

The idea is to use sqlmap in a way that it detects sqli without making tons of requests per parameter.

So I started messing with flags like: `--smart`, `-o` (which I don't really know what is does) and `--technique=`.

This is just a personal question, not a bug or feature requests. What would be the best, or at least a good one, to reduce the amount of requests needed to detect a 'possible' vulnerable injection? What would be the flags needed or configuration?

Sorry if this doesn't fit here, I didn't know where to ask this.

**Comment by stamparm** [comment]
1) Basically, same people that ask for minimum amount of requests are the same people who would nag in case of no injections found
2) You can always restrain yourself from using options `--level` or `--risk`
3) Also, you can always narrow down the `--dbms` or use a known prefix/suffix combination with `--prefix` `--suffix` if you found the SQLi before running the sqlmap
4) There is also an option to use `--test-filter` which will filter down used payloads according to your needs
