### ISSUE TITLE
Add full url in the response

### ISSUE THREAD

**Issue by marcelo321** [sqlmapproject/sqlmap#4789]
Would be possible that we have the full url in the result of the sqlmap scan?

we get like 

```
sqlmap identified the following injection point(s) with a total of 40 HTTP(s) requests:
---
Parameter: category (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: category=Lifestyle' AND 4551=4551 AND 'WJgT'='WJgT
```

Would it be possible that the host + path + parameter is there too? so the whole url of the injection?

**Comment by stamparm** [comment]
1) This would cause a mess in some cases - for example in POST/JSON/XML injection - tons of output
2) You can always use `-v 6 | grep URI` to see what are the full URIs being sent
3) Also, you can use `-t traffic.txt` to see those working URIs

**Comment by marcelo321** [comment]
Would it be possible to add to a file, both the payload and the working requests to a file? I see there is and option to log the `--output-dir`, but I want to get the results to a file of both url (get or post, doesn't matter) in a file if the target is vulnerable.

e.g

```
Vulnerable!

GET /whatever
Host: asdasd
```

I am trying to scan multiple urls and seems overcomplicated to get only an alert when sqlmap found a possible issue

**Comment by marcelo321** [comment]
Nvm, made the solution with a bash script
