### ISSUE TITLE
Improve SQLMap entries dumping performance

### ISSUE THREAD

**Issue by shelld3v** [sqlmapproject/sqlmap#4799]
**Is your feature request related to a problem? Please describe.**
I recently solved a CTF with SQLMap, but I was pretty furious with the runtime (too slow)

**Describe the solution you'd like**
While I was waiting for SQLMap brute-forcing word-by-word, I realized that I could guess most of the entries, with just 3-4 first words. For example: `ADMINS`, I knew that it must be `ADMINISTRATOR` or `ADMINISTRATION`. So I would like to see an option that the user can guess the whole word, and SQL will try if it's correct or not. Actually, I want further: SQLMap stores a huge wordlist (english words), after having 5-6 words, it will check for words that have the same prefix inside that wordlist, test all those words and if all fail, continue its normal process, otherwise: time saved!

**Comment by stamparm** [comment]
`I want further` LOL
