### ISSUE TITLE
414 Request-URI Too Long

### ISSUE THREAD

**Issue by kobyan1** [sqlmapproject/sqlmap#4803]
Sometimes, for large requests, web servers return a "414 Request-URI Too Long" response. Now the message about this code has the "DEBUG" type, so it is visible only if the verbose level is greater than 1. And this message is uninformative. It would be nice to make a message with the "WARNING" type with advice to reduce the request size (for example, exclude unnecessary parameters or reduce the number of tampers).
It would also be nice to create a parameter that is responsible for the maximum allowable request length, which by default will be very large, but upon receiving a response "414 Request-URI Too Long" will become equal to the current request length. It will be possible to reduce the number of requests by excluding those that are longer than the maximum allowable request length.

**Comment by stamparm** [comment]
you'll now get a message:
```
[11:14:04] [WARNING] request URI is marked as too long by the target. you are advised to try a switch '--no-cast' and/or '--no-escape'
```

won't do any automatic "cleaning" as in lots of cases user is the one causing this (e.g. via providing a URI containing junk inside - e.g. from automated scanners)
