### ISSUE TITLE
Problems with union_query.xml and boundaries.xml

### ISSUE THREAD

**Issue by Ymigmli** [sqlmapproject/sqlmap#4807]
Translation tool: google

**Is your feature request related to a problem? Please describe.**
union_query.xml Because all test tags have specified [GENERIC_SQL_COMMENT], union_query.xml does not call boundaries.xml, and union injection cannot be performed in # and - filtered scenarios

**Describe the solution you'd like**
I deleted the <comment>[GENERIC_SQL_COMMENT]</comment> tag，Will this cause other problems?

**Describe alternatives you've considered**
/

**Additional context**
![f709af9fb69fb8026fb744d772a546e](https://user-images.githubusercontent.com/47731874/133564851-a3408620-44a7-4a83-ad1b-2eec7e6ead3b.png)
![98efd8e963b1586b28d4fa1cf84a5f1](https://user-images.githubusercontent.com/47731874/133564869-666a8e14-f677-496f-9aa5-e01a61e19dbe.png)
![image](https://user-images.githubusercontent.com/47731874/133564905-6c6a7a9c-fd4e-41a3-83e0-b7299620a2e6.png)
![image](https://user-images.githubusercontent.com/47731874/133565011-ef9d8958-141a-4913-b62e-ee0b19fb3417.png)
![image](https://user-images.githubusercontent.com/47731874/133565084-94f27202-e7da-4f42-9d62-e854b6e974a9.png)

**Comment by Ymigmli** [comment]
Cannot enumerate the database after modification, there is no limit...

**Comment by Ymigmli** [comment]
And the group_concat function

**Comment by stamparm** [comment]
just use `--suffix` you need (e.g. `--suffix="#"`)

**Comment by stamparm** [comment]
just to describe a thing here. `UNION` SQLi is a pretty expensive technique for testing. thus, "best" and most successful suffix to use is the "generic comment" (i.e. `-- -`). suggesting to incorporate all possible suffixes/comments here is not very smart move
