### ISSUE TITLE
Db object comments

### ISSUE THREAD

**Issue by ohpe** [sqlmapproject/sqlmap#481]
Hello guys, 
I was playing with MySQL and I found an "interesting" feature.
With MySQL, and I checked also for ORACLE, MSSQL, PostgreSQL, etc.., is possible to add a comment on a database object.

For example, I can insert a comment for the table "users" in the database "company", and I can also add a comment on a specific column.
In MySQL, the comments are stored within the db "information_schema" in the tables "tables", "columns", etc. respectively.
The query is something like this:

SELECT TABLE_COMMENT 
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'company' 
AND TABLE_NAME = 'users'

I'm wondering if there is any feature in sqlmap that allows to extract these information.
(In addition to dump the entire information_schema db :-) )

Thanks

**Comment by stamparm** [comment]
Implemented for a very long time. Haven't closed this one for years :)

```
$ python sqlmap.py -hh | grep comments
    --comments          Check for DBMS comments during enumeration
```
