### ISSUE TITLE
Getting weird names of database names of mysql unknown (drizzle fork)

### ISSUE THREAD

**Issue by TonyO57** [sqlmapproject/sqlmap#4818]
![Screenshot_2021-09-23-15-42-42-27](https://user-images.githubusercontent.com/90965906/134629170-acd1bb9a-bf37-43e0-a37e-7430a64152ae.jpg)

Please help me urgently 😰😰

**Comment by stamparm** [comment]
you are either having a false positive or something is blocking your requests (i can see those 403s). please rerun everything with `--flush-session` and try from scratch

**Comment by TonyO57** [comment]
It is giving same result but without database name retrieved 
![IMG_20210930_121634](https://user-images.githubusercontent.com/90965906/135401531-f21254e0-b99d-48bd-a7ce-357af10eb470.jpg)
