### ISSUE TITLE
DNS-domain

### ISSUE THREAD

**Issue by permis20182018** [sqlmapproject/sqlmap#4831]
Hello , i just spend 4 days trying to solve that problem on Sqlmap , everytime i use --dns-domain option with time-based DB or Blind DB i got this Error : 
`[ERROR] data retrieval through DNS channel failed. Turning off DNS exfiltration support`

-I tried To use sqlmap dns Collaborator from Burpuite ===> not working the same error 
-I checked an old issue report here : [https://github.com/sqlmapproject/sqlmap/issues/3078](url) 
-i Tried my own Vps and my Own domain , i checked tcpdump Port 53 on my vps ( i use Google cloud) , i did a `dig foobar.yourdomain.com` , no problem i received the request with foobar.domain.com 
- i tried sqlmap on both my Computer , and inside my VM , i got always the same error 
- i tried previous release of sqlmap 
- i checked the firewall rules on GCP (port 53 open)
any suggestion Please 
Thanks

**Comment by stamparm** [comment]
1) DBMS has to support DNS resolution mechanisms (ab)used by sqlmap. In case of Oracle, DBMS OS does not matter, in case of MySQL, PostgreSQL and MsSQL, DBMS OS has to be Windows
2) You should check the payload being sent (e.g. via `-v 3`) and try to run it manually. Maybe you'll get some useful error message back. Also, you could try to run everything with `--parse-errors` and/or `-t traffic.txt` to search for some kind of an error

**Comment by permis20182018** [comment]
Oh i undertand now , so that depend on the DBms? , so if the server is not windows and db is mysql  it will not work ? 
Thanks for the help

**Comment by stamparm** [comment]
@permis20182018 nope. in case of MySQL only Windows platform is support for DNS exfil
