### ISSUE TITLE
Unable to retrieve database names and version backend dbms mysql drizzle unknown fork 

### ISSUE THREAD

**Issue by TonyO57** [sqlmapproject/sqlmap#4835]
Firstly i runned this command without flush session I found weird database names
![Screenshot_2021-09-23-15-42-42-27](https://user-images.githubusercontent.com/90965906/135410490-41a85027-77df-4192-b5f6-a7ca9d539347.jpg)

python sqlmap.py -u "https://www.target.com" --dbs --level=5 --risk=3 --flush-session --fresh-queries --keep-alive --time-sec=10 --tamper=varnish,between,randomcase,space2comment --random-agent --batch --banner

I used above command more than 10 times but not able to retrieve database names 
![IMG_20210930_121634](https://user-images.githubusercontent.com/90965906/135410603-91dd7640-4e71-4175-92cc-0254fd6709a7.jpg)

Please help me to fix this issue

**Comment by stamparm** [comment]
Either false-positive or something is blocking the sqlmap requests. Fixing of this would be to either rerun everything with `--flush-session` OR just to just skip usage of sqlmap against the target
