### ISSUE TITLE
missing database parameter. sqlmap is going to use the current database

### ISSUE THREAD

**Issue by MCLB961** [sqlmapproject/sqlmap#4836]
I was testing `-sql-query` in sqlmap, there is an error looks like this

```
[WARNING] missing database parameter. sqlmap is going to use the current database to enumerate table(s) columns

[INFO] fetching current database

[WARNING] reflective value(s) found and filtering out
```
my command was like this:
sqlmap -u "https://targeturl.com" -cookie="xxxx" -D xxxx -T xxx -random-agent --sql-query="select xxxxx from xxxxxco where xxxxx=xx

here in the error, the database parameter is missing but I specify the database user `-D` switch I don't know what is wrong. anyone can help me with this error. also, the query I want to select is not applicable in the current database. so the idea is how to specify the database.
thank you

**Comment by stamparm** [comment]
but why haven't you used database name in `--sql-query` from start? those are basics of SQL language.

something like: `--sql-query="select xxxxx from database_1.xxxxx`
