### ISSUE TITLE
Prediction when dumping, is it possiable? (or: automagically autofill?)

### ISSUE THREAD

**Issue by komer83** [sqlmapproject/sqlmap#4840]
Example: I already know that in database "omer" there's a table called "information" with a collumn "sex"
That collumn only have two option, male and female. Is it possiable to predict it by the length of the string?

in other words, is it possiable to do 

if sex=4 then insert "male" else "female" 

Thanks!

**Comment by stamparm** [comment]
Sorry, but no. I can see what you require, but it doesn't look like something that anybody would use it regularly
