### ISSUE TITLE
information_schema not available

### ISSUE THREAD

**Issue by kobyan1** [sqlmapproject/sqlmap#4853]
When trying to get information about the structure of the database, I get the message `[WARNING] information_schema not available, back-end DBMS is MySQL <5.0`. In this case, the DBMS version is defined as `back-end DBMS: MySQL> = 5.0.12 (MariaDB fork)`. When trying to get information from information_schema, the data is received.
SqlMap version "1.5.10.13#dev"
It works correctly on version "1.5 # stable".

Run: `sqlmap.py --url="..." -p ... --random-agent --level=5 --risk=3 --technique=BEUSTQ --threads=10 --drop-set-cookie -v 3 --beep --retries=10000 --os-shell --proxy="socks5://127.0.0.1:9050"  -D information_schema -T tables -C table_name --dump --where="table_schema='information_schema'"`

Log:
![image](https://user-images.githubusercontent.com/75282655/136700035-1b69c2eb-84be-491c-960d-8d4f321b6f43.png)

**Comment by hosxxtn-collab** [comment]
tried tamper=informationschemacomment ?

**Comment by stamparm** [comment]
@kobyan1 please get the latest revision and retry everything with `--flush-session`

**Comment by kobyan1** [comment]
> @kobyan1 please get the latest revision (I've done some changes) and retry everything with `--flush-session`

Unfortunately this did not fix the problem, but using `-f` does help

**Comment by LucaIgnatescu** [comment]
I also had this issue. Using --fingerprint helped, but the latest version still has this issue. I got the message that backend DB uses mysql>5.0.12, and then information_schema is not available since backend db is mysql<4.0

**Comment by MissisEliot** [comment]
so as not to create a separate topic
I will write the court
the same problem arises
[11:07:28] [INFO] testing MySQL
[11:07:28] [INFO] confirming MySQL
[11:07:29] [WARNING] reflective value(s) found and filtering out
[11:07:30] [INFO] the back-end DBMS is MySQL
[11:07:31] [INFO] actively fingerprinting MySQL
[11:07:39] [INFO] executing MySQL comment injection fingerprint
[11:07:40] [WARNING] unable to perform MySQL comment injection
web server operating system: Linux CentOS 6
web application technology: PHP 5.6.33, PHP, Apache 2.2.15
back-end DBMS: active fingerprint: MySQL >= 5.1.2 and < 5.1.5
[11:07:40] [INFO] fetching database names
[11:07:45] [WARNING] the SQL query provided does not return any output

tamper informationchemacomment not working 
-f not working

**Comment by stamparm** [comment]
> As I understand it, the problem occurred after commit `69900a6c6efac5c8b43fcee5d8d03dc2afb063b5`. It replaced the LooseVersion method from distutils.version.LooseVersion with pkg_resources.parse_version as LooseVersion. In the old version in the file "lib/core/common.py" `distutils.version.LooseVersion(Backend.getVersion()) >= distutils.version.LooseVersion(version)` (line 594) crashed with an error comparing int and string and fell within the except where the comparison `str(Backend.getVersion()) >= str(version)` returned 'true'. (Backend.getVersion () - "> = 5.0.12", version - "5") Now the comparison `LooseVersion(Backend.getVersion()) >= LooseVersion(version)` works without errors and returns 'false'. Therefore SqlMap thinks back-end DBMS is MySQL <5.0

thank you @kobyan1 for finding the cause of this problem
