### ISSUE TITLE
Direct connection ERROR when the password contains '@' char (i.e: P@ssw0rd)

### ISSUE THREAD

**Issue by fotodidak** [sqlmapproject/sqlmap#4870]
**Error direct connection to database when the password has '@' char in it**

**To Reproduce**
1. Run `python3 sqlmap.py -d mysql://user:'P@ssw0rd'@127.0.0.1:3306/test`
2. See error:
`[00:05:35] [CRITICAL] SQLAlchemy connection issue ('OperationalError: (MySQLdb._exceptions.OperationalError) (2005, "Unknown MySQL server host 'ssw0rd@127.0.0.1' (-2)")')`

**Expected behavior**
Succesfully connected to database directly.

**Running environment:**
 - sqlmap version **1.5.10.5#dev**
 - Download zip via HTTPS and extract
 - Operating system: Linux Slackware 14.2
 - Python version **3.9.7**

**Target details:**
 - DBMS mysql

Cannot find the clear documentation about how to 'escape' the '@' character.

**Comment by hastalamuerte** [comment]
Same trouble , test both variants , get error - 


[20:23:58] [CRITICAL] SQLAlchemy connection issue ('OperationalError: (MySQLdb._exceptions.OperationalError) (2005, "Unknown server host '321'@ip.ip.ip.132' (-2)")')

**Comment by hastalamuerte** [comment]
Test on cmd pwsh zsh . Lin win

**Comment by stamparm** [comment]
@hastalamuerte please update and retry

**Comment by hastalamuerte** [comment]
> @hastalamuerte please update and retry

1.7.1.8
-
sqlmap -d "mysql://username:'pass@321'@127.0.28.133:1433/db_name" --tables

Same error . As previous post
-
Without quotes overs the password something new 

CRITICAL] SQLAlchemy connection issue ('OperationalError: (MySQLdb._exceptions.OperationalError) (2013, "Lost connection to server at 'handshake: reading initial communication packet', system error: 104")')

**Comment by stamparm** [comment]
With last update usage of single-quotes or without should make no difference. Now, you'll be left with the latest error you got (which I believe is something unrelated to sqlmap)
