### ISSUE TITLE
--skip-urlencode not working

### ISSUE THREAD

**Issue by kobyan1** [sqlmapproject/sqlmap#4871]
1. Run
`sqlmap.py --url="..." -p ... --random-agent --level=5 --risk=3 --technique=U --threads=1 --drop-set-cookie -v 3 --beep --exclude-sysdb --os-shell -f -D ... -T ... --dump --tamper="plus2concat.py" --no-cast --proxy="http://127.0.0.1:8080" --skip-urlencode`
2. See error
_[01:14:57] [CRITICAL] unable to connect to the target URL or proxy. sqlmap is going to retry the request(s)
[01:14:57] [DEBUG] unable to connect to the target URL or proxy. sqlmap is going to retry the request
[01:14:57] [DEBUG] unable to connect to the target URL or proxy. sqlmap is going to retry the request
[01:14:57] [CRITICAL] unable to connect to the target URL or proxy_

Proxy - Burp Suite
![image](https://user-images.githubusercontent.com/75282655/138615162-c3232a50-4480-479d-8ee9-90ff1f6808b8.png)
As you can see from the screenshot, a response was received from the server.
Burp Suite is not the problem, because without it, the error remains.
No error without --skip-urlencode.

**Comment by stamparm** [comment]
can you provide a PCAP or smth to see what is going on?

**Comment by kobyan1** [comment]
The problem resolved itself
