### ISSUE TITLE
Save verbose output to file

### ISSUE THREAD

**Issue by xiaoswaii** [sqlmapproject/sqlmap#4874]
I need to save verbose output to file.

Is that any way to do it?

**Comment by aboodnour** [comment]
If you are using Linux, did you try `tee` ?
e.g.
```
sqlmap ......... | tee /tmp/output.txt
```

**Comment by stamparm** [comment]
These are basics of shell/console program running:

1) On linux, something like @aboodnour mentioned would do: `python sqlmap.py -u "http://testphp.vulnweb.com/artists.php?artist=1" -v 5 | tee /tmp/sqlmap.txt`
2) On windows, plain redirect should suffice: `sqlmap.py -u "http://testphp.vulnweb.com/artists.php?artist=1" -v 5 > sqlmap.txt`
