### ISSUE TITLE
Retry the payload when a specific response is received

### ISSUE THREAD

**Issue by aboodnour** [sqlmapproject/sqlmap#4876]
### Current Problem
I am currently testing a vulnerable website that does not process the payload each a few requests (if req no. is divisible by 3). Instead it shows a custom message that does not infer whether the payload is true or false.
A similar situation will be when you are testing a website behind a reverse-proxy and the reverse proxy decides to drop the request for some reason and show a custom error message. Currently, sqlmap will apply the set true/false identification rules but actually the request was not even sent to the backend server for processing, hence it should be resent.
I am not very sure if this behavior is frequent among other websites but I believe it'd be useful if sqlmap has a feature that supports replaying the payload when a certain response is received (The same way it does when a connection error occurs)

### Solution
Extend "connection error retries" feature to incorporate customizations that allow users to specify the response that determines if an error has occurred and resend the request in this case.

### Alternatives
The only way I thought it might make this works in sqlmap without code patching, is to intercept the request using a reverse-proxy (e.g. Burp Suite) and drop it when a certain response is received.

**Comment by stamparm** [comment]
With the latest revision, new option has been implemented:
`--retry-on=RETRYON  Retry request on regexp matching content (e.g. "drop")`

Be sure to tune up the `--retries` too if required, because by default after 3 retries, sqlmap will just stop (because there was no desired content)

**Comment by stamparm** [comment]
p.s. did some fine tuning. `--retries` will be automatically set to higher value, and sqlmap won't abruptly stop, but continue with further requests

**Comment by aboodnour** [comment]
That was unexpectedly fast! Thank you so much! 
Is there a way to sponsor this great project and its great team?
