### ISSUE TITLE
Union of multiple rows

### ISSUE THREAD

**Issue by kobyan1** [sqlmapproject/sqlmap#4877]
Sometimes full union technic does not work due to large amounts of data.
PHP then returns the error:
`Fatal error: Allowed memory size of ... bytes exhausted (tried to allocate ... bytes) in ... on line ...`.
SQLMap will then try to retrieve data using the UNION technique line by line.
But you can get not one, but several rows (using the LIMIT operator).
If you choose the number of rows received per query correctly, you can avoid the out-of-memory error and speed up the dump.

**Comment by stamparm** [comment]
There is a hidden switch `--force-partial`, which will force the retrieval of data row by row in UNION cases. There won't be an implementation for retrieval of `N` rows because of its non-generic nature across all supported DBMSes
