### ISSUE TITLE
Python 310 depreciations

### ISSUE THREAD

**Issue by dlslater36** [sqlmapproject/sqlmap#4879]
First I was getting the following error:

deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives   import distutils Traceback (most recent call last):   File "C:\Users\Ja1lb\AppData\Local\Programs\Python\Python310\sqlmap\sqlmap.py", line 43, in <module>     from lib.core.data import logger   File "C:\Users\Ja1lb\AppData\Local\Programs\Python\Python310\sqlmap\lib\core\data.py", line 8, in <module>     from lib.core.datatype import AttribDict   File "C:\Users\Ja1lb\AppData\Local\Programs\Python\Python310\sqlmap\lib\core\datatype.py", line 158, in <module>     class OrderedSet(collections.MutableSet): AttributeError: module 'collections' has no attribute 'MutableSet'

I found online that I needed to change "import distutils to import setuptools 

I also changed line 115 : if distutils.version.LooseVersion(VERSION) < distutils.version.LooseVersion("1.0"):

to: if packaging.version.LooseVersion(VERSION) < packaging.version.LooseVersion("1.0"):

also on a suggested post online.

Now I am gettiing the following error and can not find any info on how to fix:

 Traceback (most recent call last):   File "C:\Users\Ja1lb\AppData\Local\Programs\Python\Python310\sqlmap\sqlmap.py", line 43, in <module>     from lib.core.data import logger   File "C:\Users\Ja1lb\AppData\Local\Programs\Python\Python310\sqlmap\lib\core\data.py", line 8, in <module>     from lib.core.datatype import AttribDict   File "C:\Users\Ja1lb\AppData\Local\Programs\Python\Python310\sqlmap\lib\core\datatype.py", line 158, in <module>     class OrderedSet(collections.MutableSet): AttributeError: module 'collections' has no attribute 'MutableSet' 

Anyone have any ideas??

**Comment by stamparm** [comment]
Hi @dlslater36. You are doing something completely wrong. Please delete sqlmap altogether and retrieve the latest revision from this repository.

1) `collections` is not used for ages in `datatype.py`. Special compatibility class `_collections` is used (https://github.com/sqlmapproject/sqlmap/blob/master/lib/core/datatype.py#L162), which is coming from module `six` specialized in this "compatibility" problems. Thus, based on your error, you are using some ancient version
2) You are tampering with `LooseVersion`, while currently this is handled in a totally different way
3) I've just run latest sqlmap revision with python3.10 without any problems or deprecation warnings:

![1](https://user-images.githubusercontent.com/921555/139735875-ae4b09ca-b7cf-49b8-950b-4ac801064ad1.png)
