### ISSUE TITLE
[WARNING] unable to retrieve the number of column(s)

### ISSUE THREAD

**Issue by bitcoinboom** [sqlmapproject/sqlmap#4889]
Banner

https://pastebin.com/raw/uPzZtjDk

Tables Columns

https://pastebin.com/raw/qEYcYHmC

unable to retrieve the number of column(s)

https://pastebin.com/raw/8d3n4azz

PLEASE HELP ME my telegram number +6287813116267

**Comment by hosxxtn-collab** [comment]
Hi , have you tried --tamper=charunicodeencode ?

**Comment by bitcoinboom** [comment]
@hosxxtn-collab not working sir, is there a table access permission problem?

**Comment by bitcoinboom** [comment]
> Hi , have you tried --tamper=charunicodeencode ?
not working sir, is there a table access permission problem?

**Comment by hosxxtn-collab** [comment]
@bitcoinboom  yes , you have http error code 500 which means there is WAF

**Comment by bitcoinboom** [comment]
@hosxxtn-collab is the database on this website secure?

**Comment by stamparm** [comment]
Use `-t traffic.txt` and try to found out what is going on. You've provided zero useful data here

**Comment by bitcoinboom** [comment]
@stamparm -t traffic.txt contains only the payload doesn't give any problem info

**Comment by stamparm** [comment]
I would say that you have permission problems to access data from that same table
