### ISSUE TITLE
Same Version of sqlmap Differente result 

### ISSUE THREAD

**Issue by permis20182018** [sqlmapproject/sqlmap#4893]
Hello , just wonder why i get differente result with the same Url , i used Sqlmap Ver 1.5.10.20 on my phone (Termux) the injection goes properly and i get get the dbs and tables ...etc , and in the other hand i use the same Url on Ubuntu and i keep getting : `all tested parameters do not appear to be injectable. Try to increase values for '--level'/'--risk' options if you wish to perform more tests. If you suspect that there is some kind of protection mechanism involved (e.g. WAF) maybe you could try to use option '--tamper' (e.g. '--tamper=space2comment')`

**Comment by stamparm** [comment]
sorry, but there is no useful information provided here for me to do a proper triage. there is a possibility that this is happening, but there is also a HUGE possibility that you had a false-positive in that "working" case
