### ISSUE TITLE
before delete a task,  why do not delete process?  

### ISSUE THREAD

**Issue by lineuman** [sqlmapproject/sqlmap#4898]
https://github.com/sqlmapproject/sqlmap/blob/122c47146d0e242838dea39260d9ed7fa7312ac6/lib/utils/api.py#L389

before delete a task,  why do not delete process?  

i think,  should call DataStore.tasks[taskid].engine_kill(),before delete a task.

**Comment by stamparm** [comment]
1) there is explicit `kill` for tasks (https://github.com/sqlmapproject/sqlmap/blob/master/lib/utils/api.py#L537-L550)
2) `delete` removes the task from the list of tasks. explicit `engine_kill` of a process, which will most probably be terminated by itself, along with fact presented in 1), makes me indifferent
