### ISSUE TITLE
Manual scan to injection point, but SQLMap scan does not show up

### ISSUE THREAD

**Issue by laogavip** [sqlmapproject/sqlmap#4910]
The manually detected injection point format is as follows: '+(select*from(select(sleep(20)))a)+'      
However, scripts with sqlMap versions cannot automatically detect this
Sqlmap is expected to automatically detect patterns by detecting user input.

**Comment by stamparm** [comment]
oh man, that is coming from some scanner. also, it is `time-based SQLi`. not sure how you can trust that, without making some triple checks on your own
