### ISSUE TITLE
Support for nested JSON parameters

### ISSUE THREAD

**Issue by ZeeshanSultan** [sqlmapproject/sqlmap#4911]
**Is your feature request related to a problem? Please describe.**
I've been trying to use a request file with a placeholder and even though it recognizes the * placeholder and that the data is JSON. I still cannot specify it using the -p switch. Parsed JSON should have support for nested parameter specification. which we can use selectors for.

**Comment by stamparm** [comment]
where is any kind of example or useful information here? i can now write down an example which will prove otherwise, close this as invalid, all because of lack of information. also, there was an issue template which you just ignored

**Comment by stamparm** [comment]
![Uploading 1.png…]()

**Comment by stamparm** [comment]
![1](https://user-images.githubusercontent.com/921555/146782383-f55fe16f-c350-4ded-b37a-caeb0a8a5b5f.png)

**Comment by ZeeshanSultan** [comment]
Yeap i understand the lack of data. what to do if the json is as below and i want to target the param called target

{"machine": {"target": 1234, "id": 1111}, "lean": true}

**Comment by stamparm** [comment]
![1](https://user-images.githubusercontent.com/921555/148075227-7752a06a-ddd5-4988-b7af-3a40174322e2.png)
