### ISSUE TITLE
[INFO] using 'STDIN' for parsing targets list.

### ISSUE THREAD

**Issue by eakteam** [sqlmapproject/sqlmap#4920]
The program cannot run, stops for a long time at [INFO] using 'STDIN' for parsing targets list.
I'm executing it from Android device, Python 3.10.
It worked before but i don't remember in which version since it's been long time without updating it.
Any idea how to solve it ?

**Comment by stamparm** [comment]
Seems like: https://issuehunt.io/r/jakubroztocil/httpie/issues/828

**Comment by stamparm** [comment]
Basically, your terminal/console environment is screwed. With the latest revision/version, you'll be able to provide a hidden switch `--ignore-stdin`, which should bypass that problem you have

**Comment by eakteam** [comment]
Ok, thanks for that workaround, it works correctly. But any idea how to set terminal environment correctly manually ?

**Comment by eakteam** [comment]
I am using python in android (compiled and runs great) and also Android Terminal Emulatorhttps://gitlab.com/termapps/termoneplus/-/tree/master/emulatorview

**Comment by eakteam** [comment]
Or even if we want to execute it from java process like ->
```
val execBuild = ProcessBuilder(requireContext().applicationInfo.nativeLibraryDir + "/libpython3.so", "/data/data/com.eakteam.networkmanager.pro/files/sqlmap/sqlmap.py", "-u", "http://testphp.vulnweb.com/listproducts.php?cat=*", "--ignore-stdin)
execBuild.redirectErrorStream(true)
val exec: Process? = execBuild.start()
```
and get inputstream or outputstream...
Is that possible to achieve that without using `--ignore-stdin` ?

**Comment by stamparm** [comment]
@eakteam have you tried to append `--batch` too. I mean, I can imagine that sqlmap will halt on some questions

**Comment by eakteam** [comment]
@stamparm in fact requesting user input is needed and shouldn't use sqlmap default behavior... 

Just want to execute it from a simple Java process and parse `InputStream`, `ErrorStream` and `OutputStream` from spawned process
