### ISSUE TITLE
sqlmap errors

### ISSUE THREAD

**Issue by frodo763** [sqlmapproject/sqlmap#4923]
After launching sqlmap; it returns the following errors:

WARNING - parameter 'Referer' does not seem to be injectable
CRITICAL - all tested parameters do not appear to be injectable. Try to increase
values for '--level'/'risk' options if you wish to perform more tests.
WARNING - HTTP error codes detected during run:
500 (Internal Server Error) 39710 times

The command was entered as follows:
sqlmap -u "website URL" --method POST "[Copied POST Request]" --dbs - --level=4 --risk=4

**Comment by stamparm** [comment]
1) `500 (Internal Server Error) 39710 times` says more than 1000 words
2) Please run Burp (or similar) and connect sqlmap to it via `--proxy`. Then inspect all the requests / responses to see what's going on
3) `--method POST "[Copied POST Request]"` <- this is not how the POST body is being sent. Take a look here: https://github.com/sqlmapproject/sqlmap/wiki/Usage#http-data

**Comment by frodo763** [comment]
1. Can you elaborate on this
2. The environment is not allowing Burpsuite to launch
3. I ommitted the full command
