### ISSUE TITLE
sql-file & sql-shell && sql-query are not detected by the tool !!

### ISSUE THREAD

**Issue by HasanAhmad97** [sqlmapproject/sqlmap#4925]
i am trying to specify a payload with option sql-query or other that i have mention > but ! the tool is not seeing it !!

**Comment by stamparm** [comment]
![1](https://user-images.githubusercontent.com/921555/148074484-689b025b-9549-4f7e-a0f3-0e8b41f3ab75.png)

**Comment by stamparm** [comment]
p.s. if you are using Windows, there is a known issue with broken Python installations where arguments are not passed to the program. This is not an issue of sqlmap but of the installation. In such cases, user should uninstall the Python completely and reinstall it from scratch (by downloading the latest version from official Python downloads pages)
