### ISSUE TITLE
İnjection

### ISSUE THREAD

**Issue by RakSax** [sqlmapproject/sqlmap#4927]
hello, i have a problem with injection

the payload **_[0x00]_**'+(select*from(select(sleep(20)))a)+' was submitted in the PHPSESSID cookie. The application took 21780 milliseconds to respond to the request, compared with 1911 milliseconds for the original request, indicating that the injected SQL command caused a time delay.  The database appears to be MySQL.

burp was able to inject time based, but my attempts with sqlmap were in vain.

I applied prefix and tamper - However, I did not find the slightest finding with sqlmap.

how can i solve this problem ?
![indir](https://user-images.githubusercontent.com/97119211/148101406-77feb14e-a97b-40f0-a27d-d0c187f10d15.png)

**Running environment:**
 - sqlmap version [1.5.12.6#dev]
 - Installation method [Zip]
 - Operating system: [Windows 10]
 - Python version [2.7.12]

**Target details:**
 - DBMS [Mysql]
 - SQLi techniques found by Burp Suite [3 Time based]
 - WAF/IPS [no]

**Comment by stamparm** [comment]
you have to "fine tune" your SQLi detection capabilities. delay coming from such delay doesn't prove anything, especially if coming from web scanner (such as burp). try to find one delayed response for TRUE comparison (e.g. `1=1`) and one non-delayed response for FALSE comparison (e.g. `1=0`) before raising issues like this
