### ISSUE TITLE
Using tamper capabilities for --base64= injection

### ISSUE THREAD

**Issue by RakSax** [sqlmapproject/sqlmap#4928]
injection

hello i have a question

Can tamper be used for parameter in base64?

 POST parameter 'resp' is JSON deserializable. Do you want to inject inside? [y/N] y
 
 time based will inject but waf is blocking it
 
 
![indir](https://user-images.githubusercontent.com/97119211/148183383-7edd1a42-e3f2-47a0-b392-73c7eb4de711.png)

-------------------------------------------------
bug

by the way, when we do a scan with --base64="id", the -v parameter doesn't work -- I can't see payload

**Comment by RakSax** [comment]
There is base64 in the header post, how can I specify it to sqlmap 

![indir](https://user-images.githubusercontent.com/97119211/148277568-30038af5-ad06-4b95-8dd7-3f0d0b476d77.png)

**Comment by stamparm** [comment]
![1](https://user-images.githubusercontent.com/921555/148608719-aebd9976-54c8-49c8-a3a7-9fc004e25464.png)

**Comment by Gentech57** [comment]
@stamparm

**Comment by stamparm** [comment]
@Gentech57 you are aware that this is an abomination? also, I don't know what's the `Content-Type` nor anything in your case.

usually i would ignore this kind of stuff, but hey, did some changes. nonetheless, i doubt that it will work from start (mostly because of missing information on `Content-Type`)

with latest revision, this kind of stuff should work: `--data="aWQ9MQ==" --base64=POST`

**Comment by Gentech57** [comment]
> @Gentech57 you are aware that this is an abomination? also, I don't know what's the `Content-Type` nor anything in your case.
> 
> usually i would ignore this kind of stuff, but hey, did some changes. nonetheless, i doubt that it will work from start (mostly because of missing information on `Content-Type`)
> 
> with latest revision, this kind of stuff should work: `--data="aWQ9MQ==" --base64=POST`

Content-Type: application/x-www-form-urlencoded; charset=UTF-8

**Comment by stamparm** [comment]
but i don't see how this could be sent that way. `application/x-www-form-urlencoded;` users `param=value`, while you can't just urlencode everything being sent (without parameter names)

**Comment by stamparm** [comment]
![img](https://user-images.githubusercontent.com/921555/153503452-a3e82457-75ce-4c71-bfe5-1a296366b7b4.png)

**Comment by Gentech57** [comment]
> anyhow, i've switched to FAR safer `text/plain`, without any url encoding. please try it that way

it didn't work

**Comment by stamparm** [comment]
check email
