### ISSUE TITLE
Unable to locate metasploit framework installation despite being installed

### ISSUE THREAD

**Issue by BotterManTingGoes** [sqlmapproject/sqlmap#4932]
**Describe the bug**
I have installed metasploit and added it to my path and in /opt/ and in /bin yet sqlmap says 'unable to locate metasploit framework installation' when i use any command that invokes metasploit like --os-pwn

**Expected behaviour**
Launch metasploit with preset values of what was found/specified in sqlmap

**Running environment:**
 - sqlmap version 1.5.7#pip
 - Installation method git
 - Operating system: Ubuntu 20.04 (not WSL or WSL2)
 - Python version 3.8.10

**Comment by hosxxtn-collab** [comment]
Hi ,
you can specify the path where your metasploit located and use the switch --msf-path

**Comment by BotterManTingGoes** [comment]
hey hosxxtn, it just tells me that "the provided Metasploit Framework path '/opt/metasploit-framework' is not valid. The cause could be that the path does not exists or that one or more of the needed Metasploit executables within msfcli, msfconsole, msfencode and msfpayload do not exist" when they do, at least msfconsole does. and in /usr/local/bin i get the same error. Is it because they are ruby scripts name msfconsole? if so they're the only ones named msfconsole.

**Comment by hosxxtn-collab** [comment]
Hi BotterManTingGoes ,

i think the best solution is to purge metasploit sudo apt-get purge metasploit-framework  and install it again

**Comment by stamparm** [comment]
Not sure how you installed your Metasploit, but I am not able to reproduce your problem with a regular setup:

![1](https://user-images.githubusercontent.com/921555/149418256-3aa6ee22-2a85-49a3-a305-a615e7798a0b.png)

p.s. by "regular" setup I mean something like:

```sh
cd /tmp && wget https://downloads.metasploit.com/data/releases/metasploit-latest-linux-x64-installer.run && wget https://downloads.metasploit.com/data/releases/metasploit-latest-linux-x64-installer.run.sha1 && echo $(cat metasploit-latest-linux-x64-installer.run.sha1)'  'metasploit-latest-linux-x64-installer.run > metasploit-latest-linux-x64-installer.run.sha1 && shasum -c metasploit-latest-linux-x64-installer.run.sha1 && chmod +x ./metasploit-latest-linux-x64-installer.run && sudo ./metasploit-latest-linux-x64-installer.run
```
