### ISSUE TITLE
Directory not found bug

### ISSUE THREAD

**Issue by 69420plss** [sqlmapproject/sqlmap#4942]
So I was just trying some testing after 1 day BOOM I get but with this "
can't open file 'sqlmap.py': [Errno 2] No such file or directory" when I try to open it how to fix this? Some info it's on termux I'll be waiting python 4.2.1

**Comment by stamparm** [comment]
Wrong installation of sqlmap. Take a look at https://github.com/sqlmapproject/sqlmap#installation
