### ISSUE TITLE
Does every WAF/IPS dectect will give the [WAF Name] promotion?

### ISSUE THREAD

**Issue by lifengquan52** [sqlmapproject/sqlmap#4957]
Does every WAF/IPS dectect will give the [WAF Name] prompt? If sqlmap can not identify the WAF type， does sqlmap will also give the message for me when i scan？

I mean， if the website WAF/IPS detect，but don't have WAF/IPS name, it will ignore the WAF and go on?

when i scan some url, it will give me warning message:
[18:53:01] [INFO] checking if the target is protected by some kind of WAF/IPS

it does represent sqlmap have checked a WAF/IPS on the webiste? or just a checking message.
![WAF](https://user-images.githubusercontent.com/6167329/150355189-b535a4ff-7b45-4cf6-8bf5-6b7d0e46d9da.png)

By the way, sqlmap is a smart tool, when i see the verbose mode and check the report! it was smart!

**Comment by stamparm** [comment]
if any kind of "suspicious" behavior is being detected, even in case of unknown WAF/IPS, sqlmap should warn. this is not a proof that there is no WAF/IPS

**Comment by lifengquan52** [comment]
> if any kind of "suspicious" behavior is being detected, even in case of unknown WAF/IPS, sqlmap should warn. this is not a proof that there is no WAF/IPS

Thanks
@stamparm
