### ISSUE TITLE
I tried all the tamper with noting can u help me

### ISSUE THREAD

**Issue by aokil** [sqlmapproject/sqlmap#4963]
I tried all the tamper with noting can u help me
[14:17:26] [DEBUG] got HTTP error code: 403 ('Forbidden')

GET /google.php?sEcho=12&goggle=2&user=%2C&iDisplayStart=%2527&iDisplayLength=10&bomber=3&bSortable_0=true&bomber=1&bSortable_1=true&bomber=10000000146&sSortDir_0=asc&bomber=1&_=1643115718879 HTTP/1.1
Host: 192.168.1.1
Accept: application/json, text/javascript, */*; q=0.01
Accept-Encoding: gzip, deflate
Accept-Language: en-us,en;q=0.5
Cache-Control: no-cache
Connection: Keep-Alive
Cookie: PHPSESSID=8h1g7qmn6ucmg6ankcqsm9cpde
Referer: 192.168.1.1
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
X-Requested-With: XMLHttpRequest

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%27, 10' at line 5

**Comment by stamparm** [comment]
Can't help you here. Bypassing of protection is entirely the user's job to do
