### ISSUE TITLE
Data is not output from sqlite

### ISSUE THREAD

**Issue by JustiFox** [sqlmapproject/sqlmap#4965]
![image](https://user-images.githubusercontent.com/47487591/151265441-a5a253ca-f68c-4c51-a9db-9bc06c4891cc.png)

Installation method: git
Python version: 3.10.1

Target details:
DBMS: MySQL
SQLi techniques found by sqlmap: header boolean-based blind]
WAF/IPS: no

**Comment by stamparm** [comment]
This looks like false-positive (i.e. junk). Rerun everything with `--flush-session`.

**Comment by JustiFox** [comment]
This is not a false positive result, a self-written script calmly reads data from SQLITE and sqlmap does not want to, but I want to use your script because it is faster

**Comment by stamparm** [comment]
SQLi from `X-Forwarded-For`? :D 

I would like to see the script and that true-positive. Please give me more details
