### ISSUE TITLE
Speed-up time-based findings

### ISSUE THREAD

**Issue by ibrasec** [sqlmapproject/sqlmap#4967]
This is a newbie sqlmap user wondering if the process of finding the complete keyword of a database, table, column or a row using the Time-Based SQL inection technique ( i.e --technique=T ) could be made much more faster by forcing the script to look for at least the first 3 letters found before taking the decision to brute force different characters.

Normally the script will start showing us that it has successfully got the letters that are forming the keyword of the associated findings such as below:
```
[23:29:58] [INFO] retrieved: admin
```

However, sometimes it is clear for us as a human to guess the complete keyword just by knowing its first 3-4 letters,

so as example, if the currently retrieved letters are **inf** it is clear that the next letter would be **o** and if the keyword still has some more letters then the next letter would be **r** and so on until completing the word **information_schema**
```
[23:29:58] [INFO] retrieved: inf
```
i am not sure if i am correct, but i noticed that the script is just brute forcing without having the idea of guessing.

Guessing will help reducing the traffic noise of the script and speed up the process of completing the scan much faster.

**Comment by stamparm** [comment]
`--predict-output`
