### ISSUE TITLE
This is not a false positive result, a self-written script calmly reads data from SQLITE and sqlmap does not want to, but I want to use your script because it is faster

### ISSUE THREAD

**Issue by JustiFox** [sqlmapproject/sqlmap#4968]
This is not a false positive result, a self-written script calmly reads data from SQLi and sqlmap does not want to, but I want to use your script because it is faster

https://imgur.com/a/9Je9IzE

_Originally posted by @JustiFox in https://github.com/sqlmapproject/sqlmap/issues/4965#issuecomment-1024737975_

**Comment by turboman99maker** [comment]
I recognize something : are you using Acu ? :-(

**Comment by stamparm** [comment]
oh man. this doesn't look good

also, you are mentioning "self-written" script while i see an excerpt from some automated web scanning tool (Acunetix).

please, post a script to see what's going on. anything less than the script (e.g. "oh man, it was actually an Acunetix") and i'll close this down in less than a second and will instantly delete all the subsequent issues

**Comment by JustiFox** [comment]
[sqli.zip](https://github.com/sqlmapproject/sqlmap/files/7975018/sqli.zip)
@stamparm Here is the script itself, which is written in Node JS, if possible, then delete this message

**Comment by stamparm** [comment]
I need more info. Can you send URL to `miroslav@sqlmap.org`? The script itself doesn't show nor prove anything

**Comment by JustiFox** [comment]
> I need more info. Can you send URL to `miroslav@sqlmap.org`? The script itself doesn't show nor prove anything

I sent the link to your email

**Comment by stamparm** [comment]
Discussed in email
