### ISSUE TITLE
invalid runtime environment ('No module named 'plugins.dbms.raima'')

### ISSUE THREAD

**Issue by syuaibsyuaib** [sqlmapproject/sqlmap#4969]
im using python 3.10.2 then try sqlmap.py "url target". and i got error "**invalid runtime environment ('No module named 'plugins.dbms.raima'')**"

**Comment by stamparm** [comment]
can you please debug this? most probably you are using windows 10, right? is Windows AV blocking sqlmap run or smth?

**Comment by stamparm** [comment]
Installed Python3.10 on Windows 11. Running sqlmap without any problems:

<img width="953" alt="Screenshot 2022-02-01 132815" src="https://user-images.githubusercontent.com/921555/151973871-adfaef12-6e00-4977-b62d-5c6f56a0ae1e.png">

Maybe you are having trouble with this: https://www.delftstack.com/howto/python/disable-path-length-limit-python/
