### ISSUE TITLE
Empty data retrieval (<blank>)

### ISSUE THREAD

**Issue by komer83** [sqlmapproject/sqlmap#4971]
**Describe the bug**
When dumping data, it retrieving is empty i.e. <blank>. It worked without any issues before and started few days ago.

**To Reproduce**
1. Run ' sqlmap -u "http://XXXXsingle_view.php?id=390170&gid=390167" --level=5 --risk=3 --dbs --dump -D XX --threads=10 --technique=B -X users --no-cast --time-sec=20 --random-agent'
'
2. See error

**Expected behavior**
Retrieval of valid data as before, for example:
[user name][email][password hash][cookie id]

**Screenshots**

**Running environment:**
 - sqlmap version [1.6#stable]
 - Installation method [apt]
 - Operating system: [Kali Linux 5.15.0-kali3-amd64 2022-01-31]
 - Python version [2.7.18]

**Target details:**
 - DBMS [MySQL]
 - SQLi techniques found by sqlmap [boolean-based blind, time based blind]
 - WAF/IPS [none detected]

**Additional context**
Already dumped part of the database currently, several days ago it stopped dumping valid information. 
 Server detected running Ubunutu 13.04/12.04/12.10
PHP, PHP 5.3.10, Apache 2.2.22
MySQL>5.0.12

**Comment by stamparm** [comment]
man, i can't help you here without any useful information. you should for example 1) use `--proxy` and run burp in between OR 2) run sqlmap with `-t traffic.txt` so you could see what's going on in responses
