### ISSUE TITLE
How to auto search and dump ( join --search -C "pass" and dump all table, not only collumn)

### ISSUE THREAD

**Issue by PauloChoupinaIPB** [sqlmapproject/sqlmap#4985]
When i do --search -C "pass"
if i use batch it only dumps the collumn with pass

I want to dump all tables with the collum pass like

How do I do so?

**Comment by PauloChoupinaIPB** [comment]
Kinda like:

--search -C "pass" --dump -T or something?

**Comment by stamparm** [comment]
Replied in your email you've sent prior to raising this issue
