### ISSUE TITLE
Mechanism to re-authenticate when session expires

### ISSUE THREAD

**Issue by inquisb** [sqlmapproject/sqlmap#50]
Design and implement a mechanism to identify a session expire (eg. 302 to /login page, not Set-Cookie issued, etc) and automatically re-authenticate given the raw authentication request from the user.

**Comment by inquisb** [comment]
Burp's [session handling rules](http://portswigger.net/burp/help/options_sessions.html#sessionrules) can use a macro to re-authenticate hence proxying sqlmap request through Burp solve this. The reactive session termination indicator may not necessarily be a 302 redirect and even so, it may also be the hint of a successful (or false) response in a boolean-based attempt. As such I think the more consistent and generic way of implementing a similar thing in sqlmap is to rename `--safe-url` to `--safe-req` to accept a raw request file.

When this ticket is worked, share code with #739.

**Comment by stamparm** [comment]
`--safe-url`/`--safe-freq` already does this
