### ISSUE TITLE
Can I try mysql >5.0.12 payloads?

### ISSUE THREAD

**Issue by Phoenix1112** [sqlmapproject/sqlmap#5005]
hello. thanks for this project. I found a sql injection vulnerability on a website before. Later, this vulnerability was fixed. When pulling the database with sqlmap, it said that mysql version is greater than 5.0.12.

```
Title: mysql > 5.0.12
```

now i will look for sql injection vulnerability again on this target. Can I set the loads that the sqlmap program will try to be greater than 5.0.12? so when sqlmap is running, I want to focus on sql injection search only with payloads of mysql version greater than 5.0.12.  I don't want loads with mysql version less than 5.0.12 to be used by sqlmap.

How can I make a setting for it? I will be glad if you give an example configuration answer.

best regards <3

**Comment by stamparm** [comment]
```
$ sqlmap/data/xml/payloads
$ grep -iRPo "mysql [^ ]+ [\d.]+" | cut -d ':' -f 2 | sort | uniq -c | sort -n | sed 's/&gt;/>/g' | sed 's/&lt;/</g'
      3 MySQL >= 4.1
      3 MySQL < 5.0
      4 MySQL >= 5.6
      4 MySQL >= 5.7.8
      5 MySQL > 5.0.12
      7 MySQL >= 5.0
      8 MySQL >= 5.5
      8 MySQL < 5.0.12
     11 MySQL >= 5.1
     19 MySQL >= 5.0.12
```

so, basically, out of all payloads, you want to skip:
```
      3 MySQL < 5.0
      8 MySQL < 5.0.12
```

when taking into the consideration that there are **numerous** more Generic payloads, while you are also most probably forcing `--level` and `--risk` options, it is beyond my comprehension why you want to optimize your "run" by removing those 11 payloads.

without further ado, use `--test-skip=" < "` and try to enjoy it (not sure that it will make your scan faster in any way)

**Comment by Phoenix1112** [comment]
@stamparm thanks for everything <3
