### ISSUE TITLE
SQLMap crashs with 137 code (out of memory)

### ISSUE THREAD

**Issue by komer83** [sqlmapproject/sqlmap#5009]
**Describe the bug**
after ~24 hours of dumping SQLMAP quit with "zsh terminated" sqlmap (rest of command), echo $? reviles the exit code as 137 (out of memory)

**To Reproduce**
1. Run 'sqlmap -u "http://target.com" -dump -T xxx --technique=B'
2. zsh terminated sqlmap -u "

**Expected behavior**
continuing dumping

**Running environment:**
 - sqlmap version [1.6.2#stable]
 - Installation method [apt]
 - Operating system: [Kali Linux Rolling 2022.1]
 - Python version [ 3.9.10 ]

**Target details:**
 - DBMS [MySQL]
 - SQLi techniques found by sqlmap [boolean-based blind]
 - WAF/IPS [none]

**Additional context**
Running Kali with 4GB of ram with xfce4 and 1GB of swap, could not reproduce with SQLMap 1.5.9 under Ubuntu.

**Comment by stamparm** [comment]
sorry, but i have no idea how to reproduce this
