### ISSUE TITLE
Pls help this issue

### ISSUE THREAD

**Issue by Kaushal1119** [sqlmapproject/sqlmap#5011]
sqlmap.py: error: missing a mandatory option (-d, -u, -l, -m, -r, -g, -c, --wizard, --shell, --update, --purge, --list-tampers or --dependencies). Use -h for basic and -hh for advanced help.  

Pls help me troubleshoot through this.😢

**Comment by psergicv** [comment]
Do you use the latest version of sqlmap?

**Comment by stamparm** [comment]
ig that you are a windows user. there is no GUI here, just a command line tool.

1) https://www.geeksforgeeks.org/how-to-install-sqlmap-in-windows/

then after you are on that prompt, you can try

2) `sqlmap.py -u "http://testphp.vulnweb.com/artists.php?artist=1"`
