### ISSUE TITLE
How to find data in a database?

### ISSUE THREAD

**Issue by dbsnoob** [sqlmapproject/sqlmap#5035]
Hello. I know for sure that there is a column in the database that contains the value "48dx0kwq85kjnm" but i do not know the name of the table and i do not know the name of the column in which this value is located. How can i find the table and column in which this value is located using sqlmap?

DB: MySQL 5.7.19

**Comment by dbsnoob** [comment]
Of course this is not a bug. But i didn't find such a function in sqlmap.

**Comment by stamparm** [comment]
`there is a column in the database that contains the value "48dx0kwq85kjnm"` <- this basically means that it could be anywhere. there is no such option that would fine-pick all the data and search for that same column
