### ISSUE TITLE
Allow user to manually edit session data

### ISSUE THREAD

**Issue by RHScripts** [sqlmapproject/sqlmap#5037]
**Is your feature request related to a problem? Please describe.**
Sometimes, the program will incorrectly guess a character or two which messes up future operations (e.g. column name `i^` instead of `id`, type `bigind\x0520)` instead of `bigint(20)`)

**Describe the solution you'd like**
Either publicly document the format of the session data stored and loaded by sqlmap, or allow users to specify alternate formats for session data (e.g. xml)

**Describe alternatives you've considered**
The only alternative I've tried is re-running the program, which can lead to inconsistent results.

**Additional context**
Here is a sample of an affected table, after using the `--columns` command (with some column names censored)
```
+----------------------------+---------------+
| Column                     | Type          |
+----------------------------+---------------+
| i^                         |
| ****                       | datetime      |
| ********                   | bigint(11)    |
| *****************          | varchar(255)  |
| *********                  | bigind\x0520) |
| ************************** | mediumtext    |
| **********                 | varchar(255)  |
+----------------------------+---------------+
```

**Comment by stamparm** [comment]
please use `--fresh-queries` in such cases. each query results for each SQLi technique is being stored in its own way. in case of UNION SQLi, even the whole table dump is being stored inside, which can't be compared to totally different boolean-based blind SQLi. i can't comprehend the "easy" way how to provide you with the option which would allow you to fine-pick what you want.

as of session file, you can always open it inside the sqlite and try to sniff around
