### ISSUE TITLE
JSON GET Request w/ Data [BUG]

### ISSUE THREAD

**Issue by godylockz** [sqlmapproject/sqlmap#5050]
This should be an easy fix, but if you include JSON data in a GET request, SQLMAP is unable to parse the request correctly.

If there is a workaround, let me know.

```text
GET /api/getprofile HTTP/1.1
Host: <REDACTED>
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: close
Content-Type: application/json;charset=UTF-8
Content-Length: 22

{"id":"*","secret":true}
```

SQLMAP Version: latest
OS: kali

This is abnormal for data to be in a GET request, however more than likely an API can interpret JSON data from GET requests the same way POST requests are handled.

**Comment by godylockz** [comment]
> and what about: https://stackoverflow.com/a/983458 ?

From what I can tell there was an update to that response and there are plenty of cases where you can have a body in a GET request. Seems some proxies can drop the body. However with vulnerabilities such as HTTP Parameter Pollution it can be injectable in a cookie, parameter, or body. Probably more than likely targetting an API that is dependent on the content type header.

If I (or someone) submit a pull request targetting this issue, will it be rejected or do you think this could be a good change to make sqlmap more adaptable to any request being parsed from it.

**Comment by stamparm** [comment]
workaround:
![image](https://user-images.githubusercontent.com/921555/161154254-4113ea87-f64e-4a3a-aa7b-a303318cb17f.png)

**Comment by SecretUserInWhere** [comment]
[halo](javascript:alert(0))
