### ISSUE TITLE
My Sqlmap is too slow

### ISSUE THREAD

**Issue by lessims** [sqlmapproject/sqlmap#5058]
Hello everyone, when i'm fetching tables on sqlmap it's doing 1 letter by 1 letter it's really too long is there any command to make it faster ?  I'm using this command for the moment : sqlmap.py -u WEBSITE.COM -dbs --tables

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/Usage#concurrent-https-requests
