### ISSUE TITLE
Silent feature

### ISSUE THREAD

**Issue by narasimha5x5** [sqlmapproject/sqlmap#5063]
Hi there
Is it possible to add silent feature in sqlmap

Silent : Don't print whole process, print only results ( like print only Url+payload )

**Comment by narasimha5x5** [comment]
Including sqlmap banner also

**Comment by stamparm** [comment]
i won't remove banner for sure.

with `-v 0` you can get something like this:

![image](https://user-images.githubusercontent.com/921555/162621204-1528b94c-8216-483b-98e5-7ba0c0db4d16.png)
