### ISSUE TITLE
Bypassing commas with cross join

### ISSUE THREAD

**Issue by kobyan** [sqlmapproject/sqlmap#5069]
The Union method uses commas to enumerate columns.
Commas are blocked by some WAFs.
This can be bypassed with a cross join.
Instead of
`union all select null,null,...,<data>,...,null from <table>`
use
`union all select * from (select null) as <alias1> cross join (select null) as <alias2> ... cross join (select <data> from <table>) as <aliasN> ... cross join (select null ) as <aliasM>`
This technique will be useless in MySQL because it uses `concat` to concatenate strings, which requires commas.
However, it can be useful in DBMS where you can concatenate strings without using commas. For example, Microsoft SQL Server or PostgreSQL.
Please add this bypass to sqlmap

**Comment by stamparm** [comment]
this is doable for some simple stuff, thus please do a script for solving custom challenges. as of sqlmap, it extensively uses comma. for example, in case of those two DBMSes:

![1](https://user-images.githubusercontent.com/921555/163729651-d1533822-4986-4ebd-a26b-5c7cbe9fbf74.png)

![2](https://user-images.githubusercontent.com/921555/163729649-fd37abd3-5d77-45fd-b664-42c952b35a27.png)
