### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by PAULOMELO1995** [sqlmapproject/sqlmap#5082]
**Describe the bug**

**To Reproduce**
1. Run '...'
2. See error
3. The bug

**Expected behavior**

**Screenshots**

**Running environment:**
 Running version: 1.6.4.6#dev
Python version: 3.11.0a7
Operating system: Windows-10-10.0.19044-SP0
Command line: sqlmap.py -u *********************************************** --dbs
Technique: None
Back-end DBMS: None
Traceback (most recent call last):
  File "lib/core/datatype.py", line 45, in __getattr__
    return self.__getitem__(item)

**Comment by stamparm** [comment]
traceback is truncated, error message is missing completely
