### ISSUE TITLE
Mensagem de erro

### ISSUE THREAD

**Issue by PAULOMELO1995** [sqlmapproject/sqlmap#5084]
**Describe the bug**
Running version: 1.6.4.6#dev
Python version: 3.11.0a7
Operating system: Windows-10-10.0.19044-SP0
Command line: sqlmap.py -u *********************************************** --dbs
Technique: None
Back-end DBMS: None
Traceback (most recent call last):
  File "lib/core/datatype.py", line 45, in __getattr__
    return self.__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'getCurrentThreadData'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sqlmap.py", line 216, in main
    start()
    ^^^^^^^
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "lib/controller/controller.py", line 435, in start
    if not checkConnection(suppressOutput=conf.forms):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/controller/checks.py", line 1504, in checkConnection
    page, headers, _ = Request.queryPage(content=True, noteResponseTime=False)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "lib/request/connect.py", line 1524, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 925, in getPage
    if conf.retryOn and re.search(conf.retryOn, page, re.I):
       ^^^^^^^^^^^^
  File "lib/core/datatype.py", line 48, in __getattr__
    raise AttributeError("unable to access item '%s'" % item)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: unable to access item 'getCurrentThreadData'

**Comment by stamparm** [comment]
p.s. a lot of tests are done on each commit, including for Windows:

![image](https://user-images.githubusercontent.com/921555/166200527-4b2d7582-1550-41b3-9bf8-b6d9c8094256.png)
