### ISSUE TITLE
Ability to edit batch settings for multiple target list

### ISSUE THREAD

**Issue by g3ck0hacks** [sqlmapproject/sqlmap#5098]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like the ability to add options to the '--batch' command to automate it without the default settings of batch such as following redirects, continuing testing after discovering sql injection and those type of options.

example would be: "sqlmap -m bulkfile.txt --batch=insert options here

**Additional context**

I really hope to see this feature added has i have bulk file lists with 300+ targets and i do not want to sit at my computer all day so would like an option to be able to automate the process with custom settings rather than the default options

**Comment by stamparm** [comment]
"I really hope to see this feature added has i have bulk file lists with 300+ targets and i do not want to sit at my computer all day" KEK

**Comment by stamparm** [comment]
instead of spending your precious time and waiting for sqlmap to finish, you could try reading the usage manual or do some googling.

for example, https://github.com/sqlmapproject/sqlmap/wiki/Usage#set-answers-for-questions
