### ISSUE TITLE
Connection refuse by host and Waf

### ISSUE THREAD

**Issue by Vampireexe** [sqlmapproject/sqlmap#5103]
Hello can somebody help me? i have try to bypass the waf with some tamper script but without success i have need of inject the payload again because the tables seem empty with the previous inject maybe for the continue connection refuse by host by  waf.  So i wanna try again to inject the payload and retrive the tables but i have need of bypass the firewall first with a good tamper script or others solutions for bypass the waf. I have use too the proxy list and some tamper script of git hub but nothing...

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/FAQ#which-tamper-script-to-use-to-bypass-a-wafips-protection
