### ISSUE TITLE
request for friendly changelog

### ISSUE THREAD

**Issue by portno12** [sqlmapproject/sqlmap#5104]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
a friendly changelog or summary on releases page of changes between releases

**Describe alternatives you've considered**
n/a

**Additional context**
the existing changelog is ok but is just a diff of commits. a summary file or on the releases would make things easier to see at a glance what changed

**Comment by stamparm** [comment]
sorry, but too much work for nothing
