### ISSUE TITLE
CRITICAL no parmeter found...

### ISSUE THREAD

**Issue by NoseBleed11** [sqlmapproject/sqlmap#5106]
Hii dear @stamparm . i need your help .

I want to test a link for SQLi :

URL : http://213.219.38.14:3000/api
Post : {"name":"aaa","pass":"aaa"}

I wrote in the sqlmap this command:
**python3 sqlmap.py -u "http://213.219.38.14:3000/api" --data= "name=aaa&pass=aaa" --ignore-code 401**
sqlmap show me :
[CRITICAL] no parameter(s) found for testing in the provided data (e.g. GET parameter 'id' in 'www.site.com/index.php?id=1')
![Uploading צילום מסך 2022-05-13 141813.png…]()

what seems to be the problem?
so please help me :d
thanks a lot 👍
![Uploading צילום מסך 2022-05-13 141813.png…]()

**Comment by stamparm** [comment]
you've put space after the `--data= `:

![image](https://user-images.githubusercontent.com/921555/168318653-ebce0e4b-e4a9-4294-9fcd-ec4071759e6a.png)

p.s. correct syntax is:

```
python3 sqlmap.py -u "http://XXXXX/api" --data="name=aaa&pass=aaa" --ignore-code 401
```

**Comment by vincentcheri** [comment]
in the case where the forms in the page are hidden how does one go about it.
