### ISSUE TITLE
[05:55:43] [CRITICAL] all testable parameters you provided are not present within the given request data

### ISSUE THREAD

**Issue by qran253** [sqlmapproject/sqlmap#5108]
What is wrong in request ?

python3 sqlmap.py -u "http://stat.com/service.php" -p 'type' --risk="3" --level="3" --method="POST" --data='{"appFrom":"","appId":"","appName":"City","module":"install-broadcast","op":"setup","packageAppName":"ar.ity","position":"","type":"0","action":"postyyt","channelId":"cdy5e1e1a","mac":"F4:9y3:9F:F8:2A:80","marketVersion":"launcher_5.0.8","userName":"-1","version":"6.2.1"}' --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.0 Safari/537.36" --headers="Host:stat.com\nAccept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\nAccept-Encoding:gzip, deflate\nAccept-Language:en-us,en;q=0.5\nCache-Control:no-cache\nConnection:Close\nContent-Type:application/json;charset=UTF-8" --dbms="MySQL" --batch

**Comment by l3d43r** [comment]
Do not copy paste from thirdparty  apps!  it will not work!

**Comment by qran253** [comment]
I edited request body myself and do same testing but this time I get this error, and what is the wrong ?
