### ISSUE TITLE
Cloudflare Request bypass

### ISSUE THREAD

**Issue by Utku1114** [sqlmapproject/sqlmap#5112]
It seems very logical to introduce a system for sqlmap that bypasses cloudflare bot protection. This can be done very easily with packages like cloudcraper and undetected_chrome_driver, but can it really be done?

**Comment by R3d0ctober** [comment]
just use cookies

**Comment by Utku1114** [comment]
> just use cookies

Why make automatic

**Comment by R3d0ctober** [comment]
cookies bypass cloudflare

**Comment by darshan272** [comment]
How to use cookies to bypass cloudflare using sqlmap?

**Comment by stamparm** [comment]
@darshan272 maybe try to use cookies from one of such sites and pass it to the sqlmap (e.g. via `--cookies` or `-H Cookies: ...`)

![image](https://user-images.githubusercontent.com/921555/204547968-a2ccdb9e-c05b-46ad-b088-effe225cab70.png)

**Comment by decuple-dream** [comment]
@stamparm, Is this possible even when UAM mode is active? I think it is now difficult to bypass without a browser. Usually, i think when UAM mode is enabled, filtering such as injection is also enabled.
