### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Louie224** [sqlmapproject/sqlmap#5114]
hi its saying this at the bottom every time what do i do???? 

[CRITICAL] all tested parameters do not appear to be injectable. Try to increase values for '--level'/'--risk' options if you wish to perform more tests. Please retry with the switch '--text-only' (along with --technique=BU) as this case looks like a perfect candidate (low textual content along with inability of comparison engine to detect at least one dynamic parameter). If you suspect that there is some kind of protection mechanism involved (e.g. WAF) maybe you could try to use option '--tamper' (e.g. '--tamper=space2comment') and/or switch '--random-agent'
[13:56:50] [WARNING] HTTP error codes detected during run:
403 (Forbidden) - 137 times

**Comment by stamparm** [comment]
you should inspect if there is something blocking your requests. rerun everything with `-t traffic.txt` and inspect the content of `traffic.txt` file
