### ISSUE TITLE
Take into account the injection point * in http headers with the -r option

### ISSUE THREAD

**Issue by jedai47** [sqlmapproject/sqlmap#5120]
**Is your feature request related to a problem? Please describe.**
Well for now it doesnt work for me

**Describe the solution you'd like**
Well I just would like that it works

**Describe alternatives you've considered**
Only alternative is to got with --cookie or --param option

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/issues/48#issuecomment-1153890449
