### ISSUE TITLE
Upcoming Python 3.12 distutils deprecation

### ISSUE THREAD

**Issue by Zamanry** [sqlmapproject/sqlmap#5126]
**Describe the bug**
Coming Python 3.12, distutils will be deprecated. I have found distutils at `compat.py`.

**To Reproduce**
1. N/A

**Expected behavior**
sqlmap continues to work Python 3.12. A deprecation warning was announced starting in [Python 3.10](https://docs.python.org/3/whatsnew/3.10.html#distutils).

**Screenshots**
N/A

**Running environment:**
 - N/A

**Target details:**
 - N/A

**Additional context**
N/A

**Comment by stamparm** [comment]
have you actually took a good look into that [code](https://github.com/sqlmapproject/sqlmap/blob/master/lib/core/compat.py#L280-L283)? it is being activated only if the `ImportError` occurs, which should not be the case in recent Python versions (i.e. all Python3). thus, this whole ticket is invalid per se
