### ISSUE TITLE
How do I get the 'nonrecursivereplacement.py' file ?

### ISSUE THREAD

**Issue by weidu23** [sqlmapproject/sqlmap#5130]
I installed sqlmap through the homebrew tool ， the Sqlmap version is 1.6.5#stable , but in the ' file:///../sqlmap/../../tamper 'document , I cannot find the 'nonrecursivereplacement.py' file , so , I cannot use the function ?
How do I get the 'nonrecursivereplacement.py' file and use the function ?

**Comment by stamparm** [comment]
It has been deleted from the repository long ago. Nonetheless, you can still find it (e.g.) [here](https://raw.githubusercontent.com/donniewerner/sqlmapui/master/tamper/nonrecursivereplacement.py)

**Comment by weidu23** [comment]
> 它很久以前就从存储库中删除了。尽管如此，您仍然可以[在此处找到它（例如）](https://raw.githubusercontent.com/donniewerner/sqlmapui/master/tamper/nonrecursivereplacement.py)

Thanks !
