### ISSUE TITLE
Sqlmap Prompt Disappears When Pressing Backspace

### ISSUE THREAD

**Issue by oddrabbit** [sqlmapproject/sqlmap#5136]
Hi there,

When I run Sqlmap without the --batch option, and I accidentally hit backspace when I haven't written anything, the prompt goes away. This seems to happen in all version that I have tested; the most recent being 1.6.6#stable. Are we able to get a fix for this, if practical?

This is when I run it normally, as what should be expected:

![image](https://user-images.githubusercontent.com/52036269/177552537-a90ba416-b8bd-4d44-ac19-fb3ecb8d5db5.png)

And this is when I write in something and then backspace, the prompt disappears:

![image2](https://user-images.githubusercontent.com/52036269/177552595-8a1b7a19-dda0-4b0d-8ba6-52fe54a248f1.png)

Thanks.

**Comment by stamparm** [comment]
`sys.stdout.write` is combined with `input()`. that combination can lead to this kind of behavior. nonetheless, this will not change because we are using `sys.stdout.write` to do some nice formatting. thus, won't "patch" this
