### ISSUE TITLE
SQLMap Requst File Bug when parsing targets list using STDIN in Python Subprocess by Celery Worker in Linux

### ISSUE THREAD

**Issue by erikandri** [sqlmapproject/sqlmap#5145]
When i run sqlmap with a request file mode using Python Subprocess run by Python Celery Worker, it will always makes the script suddenly finish when trying to parse the target using STDIN. There is no error trace in the output it is just finish. The request file is from login page of http://testphp.vulnweb.com

Here is the request file:
===
POST /userinfo.php HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: en-US;q=0.5
Cache-Control: max-age=0
Connection: keep-alive
Content-Length: 20
Content-Type: application/x-www-form-urlencoded
DNT: 1
Host: testphp.vulnweb.com
Origin: http://testphp.vulnweb.com
Referer: http://testphp.vulnweb.com/login.php
Sec-GPC: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36

uname=test&pass=test

The command is: sqlmap.py -r (path_to_request_file) -p (param) --batch --disable-coloring --skip-waf --random-agent --dbs --tables --columns --exclude-sysdbs --output-dir=(output_directory)

Here is the screenshot of the output
![image](https://user-images.githubusercontent.com/47514419/179655899-84ac5d59-9901-451a-b701-5fb8a26ad5db.png)

**Running environment:**
 - sqlmap version 1.6.6.4#dev
 - Installation method git
 - Operating system: Linux a200b0005b81 5.4.0-105-generic #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022 x86_64 GNU/Linux
 - Python version 3.10.2

**Target details:**
 - DBMS MySQL
 - SQLi techniques found by sqlmap NOT HAPPEN
 - WAF/IPS I THINK NOT EXIST
 - Relevant console output IN SCREENSHOT ABOVE
 - Exception traceback NOT EXIST

**Additional context**
I tried the same command in my Windows 11 Terminal, it is just works fine and there is no output like "using 'STDIN' for parsing targets list" after fetch the random agent and it run perfectly until done. You can see the screenshot below
![image](https://user-images.githubusercontent.com/47514419/179657144-7f58bfc7-73c5-4057-aa02-095afd4cc14c.png)

| Run By                      | Crawl Domain | URL Full Path | Request File |
|-----------------------------|--------------|---------------|--------------|
| Terminal                    | &check;      | &check;       | &check;      |
| Subprocess                  | &check;      | &check;       | &check;      |
| Subprocess by Celery Worker | &check;      | &check;       | &cross;      |

The problem is when i start Celery Worker that will run SQLMap script via Python Subprocess that will run SQLMap Scanner with Request File mode, when it comes to parse targets list using STDIN, the script will suddenly finished without any results.

One more things, i have tried to perform the same enumerate DBs, Tables, Columns using Python Subprocess run by Python Celery Worker too in my Linux but using URL Full Path, the URL is "http://testphp.vulnweb.com/artists.php?artist=1" and it is just works fine. And i have tried to run the same SQLMap command with request file mode but just using only Python Subprocess in linux terminal without any celery worker and the script works fine.

**Comment by stamparm** [comment]
oh man. you are mixing target parsing from STDIN, with parsing of request from a request file. This will just not work. Not sure what did you expect it to do in the first place, while you had everything set via regular sqlmap command line.

p.s. STDIN is for providing lists of targets via pipe the same way as you would provide targets via option `-m`

**Comment by erikandri** [comment]
I do not parsing target using pipe like: waybackurls www.target.com | python sqlmap.py

my full command is:
cd /sqlmap && . venv/bin/activate && python sqlmap.py -r /sqli/123.txt -p uname --batch --disable-coloring --skip-waf --random-agent --dbs --tables --exclude-sysdbs --output-dir=/tmp/210722sqli_request

i do perform this SAME COMMAND on all methods: Terminal, Subprocess, Subprocess by Celery Worker.
All methods works fine except by Celery, and that will only finish if i do scan with request file mode not URL

**Comment by erikandri** [comment]
And i never know how can i send kind of piped-input like STDIN, my command does not even using that method of scanning. If it does, then how can i see what inside of the my piped-input?

**Comment by stamparm** [comment]
@erikandri you are PIPE-ing the STDIN via your subprocess call. if you run sqlmap in a regular command line, you won't get any problems. hence, that's a proof that something is wrong with your implementation
