### ISSUE TITLE
[QUESTION] Is there a way to dump or save query results into a file?

### ISSUE THREAD

**Issue by tcortega** [sqlmapproject/sqlmap#5146]
**Is your feature request related to a problem? Please describe.**
I'd like to pass a --sql-query and save the results to a file or to simply --dump it.

**Describe the solution you'd like**
Option to save results to a file

**Describe alternatives you've considered**
Saving what appears in the console, hashes come messy depending on format it was saved and it's just not that easy compared to saving it into a file.

**Additional context**
It was pretty much supposed to be a question but since I didn't have the option to do so, opened the feature request. If it already exists, please close and I would appreciate if someone commented on how to do so.

**Comment by stamparm** [comment]
![image](https://user-images.githubusercontent.com/921555/181364954-ef3faf2e-1ab7-4709-aa41-a095f305c0c6.png)
![image](https://user-images.githubusercontent.com/921555/181365020-ee1fcbdb-6353-4293-9727-ac09c2c7aa98.png)
![image](https://user-images.githubusercontent.com/921555/181365143-b3a7f830-943f-49dc-9809-2da3a3572079.png)
