### ISSUE TITLE
"Skip Test Payloads Specific for other DBMSes" appears to not work correctly.

### ISSUE THREAD

**Issue by Tib3rius** [sqlmapproject/sqlmap#5154]
**Describe the bug**
I was using SQLmap to test some parameters and it identified a PostgreSQL injection (this was ultimately incorrect but that doesn't matter). It asked if I wanted to skip test payloads for other DBMSes. I entered "n".

However, on subsequent lines (I run SQLmap with -v3) I saw the following kind of debug messages:

```
[DEBUG] skipping test 'MySQL >= 5.5 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (BIGINT UNSIGNED)' because its declared DBMS is different than identified
```

It seems that SQLmap isn't processing my answer to the question properly, because from that point on it only tried PostgreSQL payloads.

**To Reproduce**
1. Run SQLmap against a known vulnerable request.
2. When asked if you want to skip test payloads for other DBMSes enter "n".
3. Note that SQLmap seems to still skip test payloads.

**Expected behavior**
SQLmap should ignore the identified DBMS and still send other DBMS payloads.

**Running environment:**
 - sqlmap version: 1.6.7.2#dev
 - Installation method: git
 - Operating system: Kali 2021.1
 - Python version: 3.9.1

**Target details:**
 - DBMS: Oracle
 - SQLi techniques found by sqlmap: PostgreSQL OR boolean-based blind - WHERE or HAVING clause (CAST)' injectable (with --code=302) **FALSE POSITIVE**

**Comment by stamparm** [comment]
you have a very specific (erroneous) case. i've pushed a "patch", but i am afraid that you'll have to do some manual fine tuning with options/switches. for start, `--flush-session`, along with fine tuning of sqlmap run with (e.g.) `--dbms`

**Comment by Tib3rius** [comment]
Thanks @stamparm, yeah I've had to manually fine tune some others, but I'm glad I wasn't going crazy. Thanks for the patch, I'll check it out today.
