### ISSUE TITLE
Unable to detect SQLi on Mutillidae

### ISSUE THREAD

**Issue by PHBonifacio** [sqlmapproject/sqlmap#5155]
**Describe the bug**
I'm learning SQLi and practicing with mutillidae, but with one of the samples are not working properly with sqlmap.  I keep getting from sqlmap the error "unable to connect to the target URL". I can access the page via browser and BurpSuite.

**To Reproduce**

I'm using 2 VMs to test, one with Kali linux and other with Ubuntu where mutillidae is running.

1. Access the sample *Add to your blog* (OWASP 2017 -> A1. Injection -> SQLi - Insert Injection -> Add to your blog)
2. Make a post and get the header from your browser(F12). Mine is the following and is saved at header.txt:
 
```
POST /mutillidae/index.php?page=add-to-your-blog.php HTTP/1.1
Host: 10.0.2.15
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Content-Type: application/x-www-form-urlencoded
Cookie: PHPSESSID=4ifjb0aojldpkbutc23pl15rqq; showhints=1
Upgrade-Insecure-Requests: 1

csrf-token=&blog_entry=dagnb+zxbfaeghyafg&add-to-your-blog-php-submit-button=Save+Blog+Entry
```
3.  Run sqlmap -r header.txt
4. Accept the prompt options and see the error

**Expected behavior**
I was expecting to see the detection of SQLi vulnerability and try to get all database information

**Screenshots**
![image](https://user-images.githubusercontent.com/10675378/182493842-4c433ade-a9de-4412-94be-790b9fb12c0c.png)

**Running environment:**
 - sqlmap version [1.6.7.2#dev]
 - Installation method [already installed with kali and then updated manually]
 - Operating system: [Kali Linux]
 - Python version [e.g. 3.19.13]

**Target details:**
 - DBMS [mysql]
 - SQLi techniques found by sqlmap [any yet]
 - WAF/IPS [no]
 - Relevant console output [if any]
 - Exception traceback [if any]

**Additional context**
I'm also attaching the sqlmap verbose (-v 5) outup.
[sqlmap_verbose.txt](https://github.com/sqlmapproject/sqlmap/files/9246370/sqlmap_verbose.txt)

**Comment by stamparm** [comment]
csrf token is always empty because you pressed enter to get the default behavior (`N`)

**Comment by PHBonifacio** [comment]
Yes, but I'm trying to explore **blog_entry**. 

But, even choosing Y on csrf token, the error still happening.

**Comment by stamparm** [comment]
can you provide the `sqlmap_verbose` with correct values for csrf token? i would expect the application to drop the requests containing invalid (or empty) csrf token values

`But, even choosing Y on csrf token, the error still happening.` <- i can't do sightseeing here. i need something tangible

best thing would be for you to run the `-t traffic.txt` or even better dump the pcap of one such dump (e.g. via Wireshark). this all looks to me like some primitive error in usage/connection
