### ISSUE TITLE
sql map closing down

### ISSUE THREAD

**Issue by Luckydr101** [sqlmapproject/sqlmap#5157]
Hi,

I am using a windows OS and have Python2 + 3 installed. Sqlmap was working fine for me. I was even able to call it in cmd without needing to call python sqlmap.py - and it ran in terminal and did not need anything else. I recently had to alter my path. I tried adding sqlmap back to it, but now it won't run in terminal. 

I have tried to run sqlmap through the folder itself in cmd, it appears to load another cmd window showing the opening page of sqlmap. once i click any button, that window immediately shuts down. it may be the python3 separate window (I am not sure).

So now I can't run sql map through terminal in cmd or externally with python, pycharm or VS.

I have tried uninstalling and reinstalling both python and sqlmap. Still no success. I am sure there is a simple fix here, I just can't seem to find it so please help me. step by step if possible. I will really appreciate it.

**Comment by stamparm** [comment]
1) delete old sqlmap folder and all traces about sqlmap
2) uninstall python
3) download and install python from https://www.python.org/downloads/
4) get latest revision of sqlmap from https://github.com/sqlmapproject/sqlmap/archive/refs/heads/master.zip
5) unzip downloaded sqlmap to path of your choice
6) open command prompt
7) `cd` into the directory where you unzipped sqlmap's zip file
8) type `sqlmap.py -h`. you should be presented with the help output of sqlmap

**Comment by Luckydr101** [comment]
Hi,

Thank you for your email. I managed to fix it. Yes, now sqlmap.py calls
sqlmap. I am just not sure what is happening with the path but at-least it
works.


There was also an issue when i launched. It was not able to find a
“__main__” file. Fortunately i was able to create one.
