### ISSUE TITLE
The problem of SQLmap

### ISSUE THREAD

**Issue by Schira4396** [sqlmapproject/sqlmap#5159]
Sqlmap -r is unable to connect to the target url. sqlmap is going to retry the request(s). But when I specify an HTTP proxy (--proxy, like BurpSuite), it works fine, and I'm pretty sure I can access the target website. What's going on?

**Comment by stamparm** [comment]
unable to reproduce. lots and lots of users are using `-r` without any issues.

i would suggest you to either fix the request file or stick to Burp because you provided 0/zero useful information here
