### ISSUE TITLE
Is there a way to resume the attack in sqlmap?

### ISSUE THREAD

**Issue by CostyCrypto** [sqlmapproject/sqlmap#5160]
sometime you got disconnected from internet for many reasons
or like if you connect to a shell and you lose your connection when you connect again u need to start the attack from the beginning while you use --level=5 it take long time is there a way to resume the attack? to continue from where it stop?

**Comment by stamparm** [comment]
1) if sqlmap already found the injection point, it will just reuse values for working payloads
2) if sqlmap hasn't found the injection point, it MUST restart from scratch, because there can be thousands of things that could change in between (particularly, if fine tuned by the user)
