### ISSUE TITLE
Possible false negatives or false positives?

### ISSUE THREAD

**Issue by osxtest** [sqlmapproject/sqlmap#5181]
Hi! When detecting boolean-based blind SQL injection, The first request is a falseReq which sets kb.matchRatio. 

But when `kb.negativeLogic` is True, the first falseReq will be very similar to `kb.pageTemplate`. 

As a result, kb.matchRatio is set based on True response content, will this cause any false positives or false negatives?

https://github.com/sqlmapproject/sqlmap/blob/70665c5d2beece0c6b71d3677fbf690f0c3695f4/lib/controller/checks.py#L503-L509

**Comment by stamparm** [comment]
1) in case of "negative logic", everything is reversed during the comparison. Take a look here: https://github.com/sqlmapproject/sqlmap/blob/master/lib/request/comparison.py#L41-L51
2) in case of problems with your case(s), you can always try to play with `--string` or `--not-string`
