### ISSUE TITLE
SQLMap Test Results in HTML Format

### ISSUE THREAD

**Issue by srikr** [sqlmapproject/sqlmap#5186]
**Is your feature request related to a problem? Please describe.**
Currently when I run sqlmap against my Web Server I see following output in Console
```
[00:19:04] [CRITICAL] all tested parameters do not appear to be injectable
[00:19:04] [WARNING] HTTP error codes detected during run:
409 (Conflict) - 8181 times, 400 (Bad Request) - 32206 times, 404 (Not Found) - 466 times, 500 (Internal Server Error) - 39869 times, 502 (Bad Gateway) - 2 times
```

**Describe the solution you'd like**
I need a Similar Output in HTML Format mentioning the Problem, Solution, What is been Tried and What is Actual Result and Expected Results
![image](https://user-images.githubusercontent.com/49506666/193523934-82dcc2d3-5946-4ab4-85bd-6f3742ecf8c2.png)

**Describe alternatives you've considered**
Currently I don't see a better alternatives than sqlmap for SQL Injection Tests 

**Additional context**
I tried using --results-file options but that only gives request sent and response received, but it doesn't explain problems and solutions with references.

**Comment by stamparm** [comment]
sorry, but that's not supported ATM, especially for commercial products using sqlmap's output in their results

**Comment by srikr** [comment]
I am Sorry if my expectation gave a wrong impression, I mainly wanted a HTML report for us to understand what all SQL Injection Tests our Product is able to withstand and fail against each of the data inputs. Yes our product is commercial but we definitely won't publish this output anywhere, its all for internal purpose only, if thats what your concern is...

**Comment by stamparm** [comment]
yea, i have a nose for thing kind of stuff. basically, answer is no, there is no such support nor there will be particularly because of this kind of "cases". sqlmap is dual licensed, but nobody cares about that
