### ISSUE TITLE
SQLAlchemy connection issue (1045, "Access denied for user 'root'@'localhost'")

### ISSUE THREAD

**Issue by jm9azuma** [sqlmapproject/sqlmap#5188]
**Describe the bug:**
I have installed sqlmap and trying to use it to do the penetration testing to mysql database which under the Docker.  But I got failed after running below script.

**Reproduce the error:**
1. Under the folder sqlmap-dev
2. Execute the script "python sqlmap.py -d "mysql://root:12345678@localhost:3306/testingdb" -f --banner --dbs --users"
3. Error Message:  [CRITICAL] SQLAlchemy connection issue ('OperationalError: (MySQLdb.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")')

**Tried**
(1) Allow the port 3306 in firewall
(2) Used computer hostname, IP address (i.e.: 127.0.0.1) instead of localhost

**Screenshots**

**Running environment:**
 - sqlmap version 1.6.9.3#dev
 - Installation method: git clone --depth 1 https://github.com/sqlmapproject/sqlmap.git sqlmap-dev
 - Operating system: Windows 11, mysql:5.7.36
 - Python version 3.9.13

Thank you for your time to looking at my issue

**Comment by stamparm** [comment]
https://stackoverflow.com/a/25777993
