### ISSUE TITLE
skip-url-encode doesn't work if --skip=param is set before!

### ISSUE THREAD

**Issue by ggt** [sqlmapproject/sqlmap#5190]
Hi,
  Please fix this bug if you can reproduce it!

**Describe the bug**
the --skip-url-encode does not work if --skip parameter is set before it! but it work if it's set after.

**To Reproduce**
FAIL:
sqlmap -v6 -u 'https://local' --data 'jsonStream={}' --skip=User-Agent --skip-urlencode

WORK:
sqlmap -v6 -u 'https://local' --data 'jsonStream={}' --skip-urlencode --skip=User-Agent

**Expected behavior**
the skip-url-encode must be taken.

**Running environment:**
 - sqlmap/1.6.8#stable
 - Installation method "pacman"
 - Operating system: ArchLinux Up to date.
 - Python version 3.10.7

Thanks!

**Comment by stamparm** [comment]
thank you for your report
