### ISSUE TITLE
A prefix DBO is attached when extracting information_schema directly from SQL Server with the -D option.

### ISSUE THREAD

**Issue by decuple-dream** [sqlmapproject/sqlmap#5192]
**Describe the bug**
Information_schema on SQL Server.I wanted to import table_name by referring to tables.
However, the import failed, so I checked the payload with the -v3 option and found that it has a DBO prefix.

**To Reproduce**
1. -D information_schema -T tables -C table_name --dump
2. 1%' AND UNICODE(SUBSTRING((SELECT ISNULL(CAST(LTRIM(STR(COUNT(*))) AS NVARCHAR(4000)),CHAR(32)) FROM information_schema.**dbo**.tables),1,1))>51 AND 'LEtZ%'='LEtZ

So I use tamper to remove the dbo prefix, so it works normally.

**Screenshots**
<img width="727" alt="스크린샷 2022-10-08 오후 11 10 22" src="https://user-images.githubusercontent.com/67303734/194711734-61e54dff-07f4-4c48-8e49-1f8ae4ab5c5f.png">

**Running environment:**
 - sqlmap version [e.g. 1.6.9#stable]
 - Installation method [git]
 - Operating system: [Mac OS X M1]
 - Python version [e.g. 3.10.6]

**Target details:**
 - DBMS [Microsoft SQL Server]
 - SQLi techniques found by sqlmap [boolean-based blind]

**Comment by stamparm** [comment]
`information_schema` inside the MsSQL is technically a schema name, not a database name. Thus, smth like this `--dump -T "information_schema.tables"` works out of the box.

Nonetheless, with the latest commit added support for `-D information_schema -T tables` too (although, I am not happy with such decision of mine)

**Comment by decuple-dream** [comment]
awesome!
