### ISSUE TITLE
Need a xml output

### ISSUE THREAD

**Issue by noutcheu1** [sqlmapproject/sqlmap#5194]
Hello first of all I want to say thank you for these to all contributors. 
I'm  building a web platform with many security tools for pentest   but I'm a little blocked with how  can I get easily the ouput of my sqlmap result   without getting all the terminal output,
and I then thought maybe sqlmap might I have the XML output result for the best manipulation of the result 
like Nmap and Ncrack do it.
that is the example of what I'm saying
<port protocol="tcp" portid="22">
 <state state="open" reason="syn-ack" reason_ttl="56"/>
 <service name="ssh" product="OpenSSH" version="4.3" extrainfo="protocol 2.0"
          method="probed" conf="10"/>
 <script id="ssh-hostkey"
       output="1024 60:ac:4d:51:b1:cd:85:09:12:16:92:76:1d:5d:27:6e (DSA)&#xa;
               2048 2c:22:75:60:4b:c3:3b:18:a2:97:2c:96:7e:28:dc:dd (RSA)"/>
</port>
<port protocol="tcp" portid="113">
 <state state="closed" reason="reset" reason_ttl="56"/>
 <service name="auth" method="table" conf="3"/>
</port>

**Comment by stamparm** [comment]
sorry, but this is not going to be implemented in near future because of many similar "tools", including commercial, which just scrap the sqlmap's results, without reading the dual-license that sqlmap has
