### ISSUE TITLE
allow --forms to be configurable

### ISSUE THREAD

**Issue by marcelo321** [sqlmapproject/sqlmap#5195]
So as it is (please correct me if I am wrong), when you use `--forms` it will use the forms and scan for sql injection, doesn't matter if the form is to another page.

I would want to configure it, so it scans forms that are from that same website.

e.g:
`sqlmap -u https://example.com/?a=1 --forms` I don't want to scan a form that leads to `https//evil.com/whatever`, I only want to scan forms that are from the same domain, `example.com`

**Comment by stamparm** [comment]
![image](https://user-images.githubusercontent.com/921555/196149925-be231635-312f-45c2-b7a2-1604776cc8b9.png)

**Comment by stamparm** [comment]
ok. i can see one "special" case. if `--data` is given, that same-host check will be just skipped. gonna fix

**Comment by Kazz90** [comment]
Hi marcelo321
Can you write to me on me Telegram?
@kazyuk
