### ISSUE TITLE
Sqlmap requires parameters to control the running time of the tamper

### ISSUE THREAD

**Issue by Margular** [sqlmapproject/sqlmap#5203]
When I run sqlmap on portswigger's sql injection lab I found sqlmap requires parameters to control the running time of the tamper:
https://portswigger.net/web-security/sql-injection/lab-sql-injection-with-filter-bypass-via-xml-encoding

My sqlmap command:
```
sqlmap --batch --tamper htmlencode --force-ssl -v6 -r 1.request
```

sqlmap sends requests like:
```
POST /product/stock HTTP/1.1
Host: xxx.web-security-academy.net
Cookie: session=xxx
Content-length: 164

<?xml version="1.0" encoding="UTF-8"?><stockCheck><productId>1&amp;#39;TFsWsa&amp;#60;&amp;#39;&amp;#34;&amp;#62;qCHJXH</productId><storeId>1</storeId></stockCheck>
```

but what I expect is:
```
POST /product/stock HTTP/1.1
Host: xxx.web-security-academy.net
Cookie: session=xxx
Content-length: 164

<?xml version="1.0" encoding="UTF-8"?><stockCheck><productId>1&#39;TFsWsa&#60;&#39;&#34;&#62;qCHJXH</productId><storeId>1</storeId></stockCheck>
```

Can we add a parameter to make the tamper execute after xml encoding?

**Comment by stamparm** [comment]
1) you are having double-encoding problem. "running time" would not help here
2) i don't have a request file to see what you were trying to do
3) i am not sure why you tried to use `--tamper htmlencode` in the first place. i would expect problems like this at your place

**Comment by Margular** [comment]
the request file is like:
```
POST /product/stock HTTP/1.1
Host: xxx.web-security-academy.net
Cookie: session=xxx
Content-length: 164

<?xml version="1.0" encoding="UTF-8"?><stockCheck><productId>1</productId><storeId>1</storeId></stockCheck>
```

The lab is that WAF intercepts special characters and requires htmlencode encoding to bypass, so I try to use htmlencode tamper to do that, but the double encoding problem of sqlmap makes me unable to achieve my goal
