### ISSUE TITLE
scientific-notation tamper script

### ISSUE THREAD

**Issue by decuple-dream** [sqlmapproject/sqlmap#5205]
Hello! I expect to find the script through the following URL.

https://www.gosecure.net/blog/2021/10/19/a-scientific-notation-bug-in-mysql-left-aws-waf-clients-vulnerable-to-sql-injection/

Is there a similar tamper or can you add it?

Thank you! dear stamparm.

**Comment by stamparm** [comment]
Done. Thank you for pointing to it :+1:

**Comment by decuple-dream** [comment]
Your skills are almost art!
