### ISSUE TITLE
Impossible retrive data only on database 3.

### ISSUE THREAD

**Issue by Vampireexe** [sqlmapproject/sqlmap#5213]
Hello i receive the permission denied when try to retrieve data only on the database 3 of the website test, how can resolve?
![Screenshot (35)](https://user-images.githubusercontent.com/71180858/198635574-d6ecb271-42ec-4f5e-b42b-c2e69e991159.png)

**Comment by stamparm** [comment]
you are getting `command denied` from the server. this has nothing to do with the sqlmap. you should invest your time in debugging what's going on with the server (there is obviously some protection in between)
