### ISSUE TITLE
response decode error when found sequence like &#xd

### ISSUE THREAD

**Issue by drJabber** [sqlmapproject/sqlmap#5220]
**Describe the bug**
Sqlmap returns connection error if there's single character hex sequence in target response

**To Reproduce**

**Expected behavior**
decode response page correctly

The error is in 
https://github.com/sqlmapproject/sqlmap/blob/c38232113459710d1aca0366b28b58f0ace82454/lib/request/basic.py#L342
`
 page = re.sub(b"&#x([0-9a-f]{1,2});", lambda _: decodeHex(_.group(1) if len(_.group(1)) == 2 else "0%s" % _.group(1)), page)
`
I think there should be binary format in  "0%s" % _.group(1) - something like 
`
b"0%s" % _.group(1)
`

**Comment by lavafroth** [comment]
`b"0%s" % _.group(1)` doesn't work, what about `("0%s" % _.group(1)).encode()`?

**Comment by drJabber** [comment]
in python 3.8
when **val = b'D'**  code **("0%s" % val).encode()** results to **b"0b'D'"** (correct result should be b"0D")
but code **b"0%s" % val** results to correct value **b"0D"**

so may be appropriate code should be **("0%s" % x.decode()).encode()** - it also generates correct result...
