### ISSUE TITLE
Tamper "dunion" does not change payload

### ISSUE THREAD

**Issue by azazello234** [sqlmapproject/sqlmap#5224]
Hello. For testing i use this command:

`sqlmap -r "/home/request.txt" --dbs --dbms=Oracle --risk=3 --level=5 -v3 --technique=U --union-cols=15 --tamper=dunion`

The request.txt contains:
```
POST http://testphp.vulnweb.com/search.php?test=query HTTP/1.1
Host: testphp.vulnweb.com

searchFor=0*&goButton=go
```

With -v3 i see that UNION does not change to DUNION. Tested at Python 2.7 and 3.11. How to fix?

**Comment by stamparm** [comment]
works only with integers in original values, while you have a non-integer value `query`. look at https://github.com/sqlmapproject/sqlmap/blob/master/tamper/dunion.py#L22
