### ISSUE TITLE
error: missing mandatory option 

### ISSUE THREAD

**Issue by cyberweaponslab** [sqlmapproject/sqlmap#5225]
**Describe the bug**
am new bee in this penetration i clone tarball and run .py extension but showing those error in screenshot below 

**To Reproduce**
1. Run '...'
2. See error: missing mandatory option < -d -u -l -m -r . .  . --dependence >
3. for advance help --h

**Comment by stamparm** [comment]
1) there are tons of tutorials on Google on how to run sqlmap: https://gprivate.com/61oni
2) for start, you can try: `python sqlmap.py -u "http://testphp.vulnweb.com/artists.php?artist=1"`
