### ISSUE TITLE
--os-pwn and time-based methods seem to be friendly. (guess)

### ISSUE THREAD

**Issue by decuple-dream** [sqlmapproject/sqlmap#5228]
Hello stamparm. How are you? I encountered a server using PHP during a mock hack and had a weak union injection and time-based.

And I ran it with the option expecting --os-pwn, and I defaulted most of the questions.
<img width="2549" src="https://user-images.githubusercontent.com/67303734/200274695-6b162b60-f2d1-4058-aaac-294946782ffb.png">

Immediately after the query is sent using the LOAD_FILE function with the UNION technique, the next time base statement must be executed, but the time base query statement is also executed simultaneously.

Isn't this a bug?

Thank you stamparm!

sqlmap version: 1.6.10.8#dev
Installation method: brew
Operating system: mac m1
Python version: 3.10.8

**Comment by stamparm** [comment]
Not a bug, but a "feature". If the faster query fails (in your case one with UNION SQLi), the next one in line will be used as a fallback (in your case time-based blind SQLi). Anyhow, in your case the upload of a file failed as sqlmap could not retrieve the content of the file via `LOAD_FILE` by using those two SQLi techniques
