### ISSUE TITLE
unexpected output of sqlmap 

### ISSUE THREAD

**Issue by marcelo321** [sqlmapproject/sqlmap#5233]
Hi,

I am running a short bash script to test a few urls with sqlmap, the thing I don't understand why, is how sqlmap is being executed and how do I fix it to control/parse the output correctly..

```
while read line;
do
        ((loopcount++))
        echo "[*] Processing URL ${loopcount} of ${urlcount})"
        echo -e "\n\n------------------[*][*]--------------\nRunning on:\n $line!!\n----------------[*][*]--------------------\n";


        /user/sqlmap-dev/sqlmap.py -u "$line" --batch --random-agent --threads 1 --answers="follow=N" --flush-session --skip-waf | tee output-sqlmap; sleep 3s;
        

done < ${1}
```

so I simplified a bit my bash script here but basically, I have 10 different urls in a file and then I do `./script.sh file`.

instead of running each url separately, sqlmap is running every url "at the same time".

my bash script will only print:

```
------------------[*][*]--------------                                                                                                                                                                      
Running on:                                                                                                                                                                                                 
 https://sometesting.url/?a=1!!                                                                                                                                                                                   
----------------[*][*]--------------------  
```

once, and won't print it at the begging of each scan as it is supposed to do in a normal script.

Instead, sqlmap is doing the following: scanning 1 url, and then scanning the second target, third target, etc. and echoing the output in the same file, and I don't want to do that. I want to execute it 10 different times as it is intended in the bash script.

sqlmap withh scan the 10 urls like this, and won't be executed 10 different times, all the scan will be done "at once"

```
[1/?] URL:                                                                                                                                                                                                  
GET https://sometesting.url2/product?productId=7                                                                                                                   
do you want to test this URL? [Y/n/q]                                                                                                                                                                       
> Y
``` 

```
[2/?] URL:                                                                                                                                                                                                  
GET https://sometesting.url2/product?productId=7                                                                                                                   
do you want to test this URL? [Y/n/q]                                                                                                                                                                       
> Y
``` 

Why is it doing this?

Edit: I honestly don't know how this is possible, how it is scanning the second url without printing what's at the start of the while loop. I really didn't think stuff like this could happen lol. how it is scanning the 10 urls and only doing 1 print at the start of the while loop.

**Comment by stamparm** [comment]
Try to rerun with the latest revision. Thing is that sqlmap in your case detected the STDIN redirection, thus, reading everything from it as a list of URLs

Nonetheless, with the latest revision, your case should work properly

**Comment by marcelo321** [comment]
thanks, now works as expected!
