### ISSUE TITLE
Fetch specific entry

### ISSUE THREAD

**Issue by byaura** [sqlmapproject/sqlmap#5236]
Is there any command to search a specific entry in a database? for example I wanna search the word "Soccer" in a table
P.s. is not a column name
Or is there any command to get the most recent entries in a certain table?

**Comment by stamparm** [comment]
1) there is no way to search for a specific entry in a database. also, not interested into implementing it
2) as of "most recent entries" there is also no way how to do it neither in sqlmap nor in general DBMS. in general DBMS there is no way how to say to the other end "give me the most recent entries" other than to compare to some timestamp-alike column value

**Comment by byaura** [comment]
So the most recent entries are the one on the bottom? or it can be randomized?

**Comment by stamparm** [comment]
it depends on the DBMS and the SQLi technique. for example, in some cases, explicit `ORDER BY` is used by the sqlmap on arbitrary column to be able to properly retrieve all column values for different rows in a consistent way (i.e. to properly combine column values with proper rows)

that being said, i would not expect the last entry to be the "freshest" in the general case
