### ISSUE TITLE
Not using union attack

### ISSUE THREAD

**Issue by sercanyeniyurt** [sqlmapproject/sqlmap#5237]
Hello, I am using the union method in my sql injection test.

I can get results when I do the following test manually;

https://[target]/getkey.php?userid=1200211221'+union+select+1,2,3,4,5,(select+CONCAT_WS(0x203a20,USER(),DATABASE(),VERSION()) ),7--+-KhCE

Result : root@localhost : webcms : 5.6.35-log

However, when I test the same test in sqlmap by adding only the union technique (--technique=U), no findings are found.

** SQLMAP Result : "all tested parameters do not appear to be injectable. Try to increase values for '--level'/'--risk' options if you wish to perform more tests. Rerun without providing the option '--technique'"

Am I doing something wrong?

**Comment by stamparm** [comment]
1) for start, don't force the union technique in the detection phase with the `--technique`. if sqlmap is able to use all techniques during the detection phase, there is a bigger chance of success to find the UNION SQLi, particularly if some other technique is found too (e.g. boolean based blind)
2) there is always a logic explanation to this kind of cases. rerun everything with `-t traffic.txt` and inspect the HTTP traffic inside
