### ISSUE TITLE
Entries not updating

### ISSUE THREAD

**Issue by byaura** [sqlmapproject/sqlmap#5241]
Hey I tried sqlmap on my database and I realised when I dump a table the first time it dumps correctly but if I add more entries to the database and dump again sqlmap doesn't update that entries or even fetch them. Does this even make sense? I tried on a different database and it worked correctly meaning that it did update that table when adding more entries.
Ps. I didn't opened a bug report cause it's probablly not a bug

**Comment by stamparm** [comment]
sqlmap uses "stored session" database for retrieved data. in your case, sqlmap just presented to you what has been already retrieved before

please use `--fresh-queries` to re-fetch the content
