### ISSUE TITLE
hi, need help, how i change columns value 

### ISSUE THREAD

**Issue by Ismail100BTC** [sqlmapproject/sqlmap#5250]
**DBMS is Microsoft SQL Server**
I'm trying to change the values in the columns, but it doesn't work.

`--sql-query="update my_table set my_colum = replace(path, 'oldstring', 'newstring')"`

`--sql-query="UPDATE my_table SET my_colum = 'newstring'"`

I've tried some of these commands, and the result is always 'NULL'

This is the result
UPDATE **my_table** SET **my_colum**='newstring' where account LIKE 'oldstring': '**NULL**'

**Comment by Ismail100BTC** [comment]
Is there a way to do that,

**Comment by stamparm** [comment]
`NULL` is a normal response for `UPDATE` statements. you should redo one more `--sql-query` with `SELECT` to see whether it worked
