### ISSUE TITLE
Question: Sqlmap exits after finding a injectable parameter and skips rest of other params when --batch used

### ISSUE THREAD

**Issue by mai1x9** [sqlmapproject/sqlmap#5254]
How to let sqlmap continue scanning for all parameters present in json (for post) or query params (for get) without exiting. 
Currently sqlmap exists as soon as it finds out sql injection for one of the parameter and skips for rest of them. When `--batch` is used, the default answer is `N`, and hence it does not look for other parameters. I want to use `--batch`, but want sqlmap to continue scanning for other parameters too.

Any idea, on how to use `--answer` in order to scan all params.

Question asked by sqlmap, 
> (custom) POST parameter 'JSON profile' is vulnerable. Do you want to keep testing the others (if any)? [y/N] N

When `--batch` used, it fills default `N`, However, I want to run all other params and answer must be `y`. How can i achieve it by using non interactive mode `--batch` or by `--answers`

**Comment by mai1x9** [comment]
> https://github.com/sqlmapproject/sqlmap/wiki/Usage#set-answers-for-questions

@stamparm I got the point, but what is the keyword that should be passed for answers.
does `--answers='vulnerable=Y' work. ?

**Comment by stamparm** [comment]
have you tried anything? any distinguishable part of the question should work
