### ISSUE TITLE
JSON output without server mode

### ISSUE THREAD

**Issue by kmcquade** [sqlmapproject/sqlmap#5259]
Hi, big fan of SQLMap here. Thanks for all of your work on it over such a long period of time!

It would be really great if SQLMap could output JSON without having to use server mode. This would help it so that SQLMap could be used in by calling it as a function, like in a Python library, rather than having a complicated sequence of `subprocess.run` and whatnot to start the server and then manage it with the client separately with a mess of `requests.get`. I could just run it with the command line mode, but the JSON output is really useful and the command line stdout doesn't provide that granular level of data that the server mode does.

I've tried that alternative solution but it gets very messy and it would be cleaner if it was from SQLMap directly.

**Comment by stamparm** [comment]
this was already requested numerous times by lurkers wanting to just include the sqlmap into their "tools". as before, without going into dubious explanations, closing this down
