### ISSUE TITLE
sqlmapapi multithreading error

### ISSUE THREAD

**Issue by samy8888** [sqlmapproject/sqlmap#5262]
I encountered an error when using sqlmapapi

    self.cursor.execute(statement, arguments)
sqlite3.ProgrammingError: Recursive use of cursors not allowed.

This error occurs when there are more than 50 task threads

I have referred to a lot of information and can not fully solve

**Comment by samy8888** [comment]
@stamparm

**Comment by stamparm** [comment]
I hope that the latest revision/commit should fix the issue

p.s. based on https://stackoverflow.com/a/26630550
