### ISSUE TITLE
unable to retrieve the number of entries for table

### ISSUE THREAD

**Issue by louissanchez84** [sqlmapproject/sqlmap#5270]
**Describe the bug**
Running time-based blind MySQL >= 5.0.12 RLIKE time-based blind

**To Reproduce**
1. Run 'sqlmap -u 'http://10.129.229.152:8080/doCreate' --data='title=test&reason=test' --level=5 --risk=3 --cookie='JSESSIONID=285DDDEB436B0BC31AEFAC971440B166' -dbms='MySQL 8.0.30'' --no-cast --random-agent -D support --tables tickets --dump --flush-session
2. See error "[00:10:57] [WARNING] unable to retrieve the number of entries for table 'tickets' in database 'support'"

**Expected behavior**
To be able dump table 

**Running environment:**
 - sqlmap version 1.6.11#stable
 - Installation method debian package manager
 - Operating system: kali
 - Python 3.10.8

**Target details:**
 - MySQL 8.0.30
 - SQLi techniques found by sqlmap time-based blind MySQL >= 5.0.12 RLIKE time-based blind

**Comment by stamparm** [comment]
High chance of either false-positive or something blocking your attempts. Retry everything with `--flush-session` and try to do an actual **debugging of the problem** before raising this kind of issues (e.g. via `-t traffic.txt`)
