### ISSUE TITLE
Add option to ignore xp_cmdshell and DBA check when using --os-shell

### ISSUE THREAD

**Issue by tcortega** [sqlmapproject/sqlmap#5291]
I have a recurring problem when I attempt to use the --os-shell command, knowing that the xp_cmdshell is available and the user is DBA, where when doing the checks, the connection just times out.

I'd like to be able to use an argument, such as -f or --force, to ignore these checks, since in this context they don't really matter to me.

**Comment by stamparm** [comment]
1) you haven't posted any kind of console output, so it is really hard to guess what's going on in your case
2) AFAICK, `IS_SRVROLEMEMBER('sysadmin','<username>')=1` should be used in MsSQL checks for DBA. it doesn't make any sense why it should "time out"
3) you can try to put `return True` [here](https://github.com/sqlmapproject/sqlmap/blob/master/plugins/generic/users.py#L77) for testing purposes
