### ISSUE TITLE
Database names are displayed incorrectly

### ISSUE THREAD

**Issue by 12553240Kj** [sqlmapproject/sqlmap#5294]
Good afternoon. Can you tell me what can be done? When using --no-cast, the base is displayed, in this form. 

`web application technology: Apache, Servlet 3.1, JSP, JSP 2.3
back-end DBMS: MySQL >= 5.0.12 (MariaDB fork)
available databases [4]:
[*] `user_addre\u0435`
[*] information_schema
[*] mysql
[*] performance_schema`

When using -hex like this:

`web application technology: Apache, Servlet 3.1, JSP, JSP 2.3
back-end DBMS: MySQL >= 5.0.12 (MariaDB fork)
available databases [1]:
[*] `6?6E666F726D6174696F6E57736265956D61``

If I specify iso-8859-1 encoding. It still doesn't display correctly.

`web application technology: Apache, Servlet 3.1, JSP, JSP 2.3
back-end DBMS: MySQL >= 5.0.12 (MariaDB fork)
available databases [5]:
[*] `physical_addreе`
[*] information_schema
[*] mysql
[*] performance_schema
[*] user_address_reports`

But another database appears. Which was not the case in the first two cases.
Can you tell me which is the right command? For the databases to display correctly?

**Comment by jvgassel** [comment]
What is the exact command you use with the iso-8859-1 encoding? (without the url ofcourse)

**Comment by stamparm** [comment]
you haven't stated the used SQLi technique. I can guess that it is either time-based or stack-based SQLi.

based on your results, I would say that something went wrong during the data retrieval (not related to encoding) as hexadecimal result is also wrong

thus, please retry with either `--flush-session` or `--fresh-queries`, while forcing the `--time-sec` (e.g. `--time-sec=10`)
