### ISSUE TITLE
data extraction problem

### ISSUE THREAD

**Issue by REtoolsx** [sqlmapproject/sqlmap#5295]
data extraction problem because session expired

While logging on to an application and pulling data in an injection detection that we have determined, after the session is terminated, it continues to pull

Let's say there are 10 tables in the database, we pulled 2 tables, while pulling the rest, the session ended and took an empty table, and when we renew the session, it pulled all the tables. The reason is that it continues to pull data when the session ends

thank you

![dump](https://user-images.githubusercontent.com/123335736/213945392-ae4de666-420c-42dd-949b-165e2829589a.png)

**Comment by stamparm** [comment]
for start, I would suggest you to use `--live-cookies` for this specific case https://github.com/sqlmapproject/sqlmap/wiki/Usage#http-cookie-header and fill the file (in some arbitrary way) with fresh session cookie

**Comment by stamparm** [comment]
New switch implemented:
`--abort-on-empty    Abort data retrieval on empty results`

![image](https://user-images.githubusercontent.com/921555/214082347-b2fd0bea-1f17-4ce3-9115-97546f35d24f.png)

**Comment by REtoolsx** [comment]
> New switch implemented: `--abort-on-empty Abort data retrieval on empty results`

nice feature works well but there is a problem

for example there are 2 table names USERS and LOG

 While user(s) were getting the table name, the session ended (USER)?S and the table name was pulled  , 

marks the last data it was pulling as complete when the connection is lost

and starts pulling other data - 

can it be fixed?

**Comment by stamparm** [comment]
are you sure in your claim on `and starts pulling other data -` ???

![image](https://user-images.githubusercontent.com/921555/214256120-c9668824-b22f-47fa-84e1-c3441d25fa71.png)

have you tried the switch?

**Comment by REtoolsx** [comment]
command :  sqlmap.py -r "test.txt" --level 3 --risk 3 --technique="T" --dbms="MYSQL" --force-ssl -D dbname --tables --time-sec 4 --abort-on-empty

session ends when pulling data --abort-on-empty activates but marks the last pulled data as completed

a table name pull that is not yet completed is seen as complete due to session termination and starts pulling other table names



![table name](https://user-images.githubusercontent.com/123335736/214267878-2f02813b-4e38-42c1-aa68-406bc05e0ed0.png)
![tablo2](https://user-images.githubusercontent.com/123335736/214267895-dfa2e7ba-d92e-4abc-8426-be4af23bfff5.png)
