### ISSUE TITLE
Parse 403 responses

### ISSUE THREAD

**Issue by UrfinJuice11** [sqlmapproject/sqlmap#5309]
Some JSON API is vulnerable to Error-based injection (at least to XPATH injection). I have confirmed it manually and able to retrieve data from database in clear text.
But the error message with fruitful data is recieved in a "403 Forbidden" packet body. If trying to use sqlmap, it simply ignores these messages and shows 
`[DEBUG] got HTTP error code: 403 ('Forbidden')` 

Tried to play with --code, --ignore-code, --parse-errors - no result.

Is there any option or method to make sqlmap parse 403 responses?

**Comment by stamparm** [comment]
please give me a break with this kind of issues.

![image](https://user-images.githubusercontent.com/921555/217214607-7ce426de-fcf4-4b5d-ac74-2544db084fde.png)

1) that `DEBUG` message doesn't mean anything than to inform you on the `403` HTTP code. please don't run sqlmap with `-v 3` and you'll be "safe" from such dangerous messages
2) you haven't even done any kind of proper debugging before raising this issue (e.g. `-t traffic.txt` to see the traffic going in and out). you also skipped the template altogether
3) and the LAST part, which is like WTF of them all, is `Error-based injection (at least to XPATH injection`
