### ISSUE TITLE
sqlmap sleep time count

### ISSUE THREAD

**Issue by mahmedeng2010** [sqlmapproject/sqlmap#5312]
i have target from manual testing ,i have found the target response to sleep time but the response after 3 multiply the number i put
for example  
when i put the payload :  'select (sleep (1))'          the read response will be  3
when i put the payload ;  'select (sleep (2))'         the read response will be  6

what is the option for that in sqlmap ?

**Comment by stamparm** [comment]
sqlmap doesn't care about the (exact) sleep time value. if there is a delay, sqlmap will recognize it.
