### ISSUE TITLE
Can not inject in a known vulnerable website

### ISSUE THREAD

**Issue by henryyds** [sqlmapproject/sqlmap#5315]
Hello, as someone mentioned previously I have the same issue like #1829. I relied every mean but it always said that is not injectable. 
To make it simplified, I copied exactly the same command of your previous answer with changes since I am using the Mac

sqlmap -u 'http://demo.testfire.net/bank/login.aspx' --data='uid=1&passw=2' --batch --level=3 --risk=3 --batch --drop-set-cookie
...

and the result is: all tested parameters do not appear to be injectable. Try to increase values for 

My code was:
sqlmap --dump-all -u "http://testfire.net/login.jsp" --data "uid=%27%3B%23&passw=21131313&btnSubmit=Login" --level 4 --risk 3 --batch --drop-set-cookie
The result is the same.

Does it mean the website have more limitations now? I am not sure if the website has changed their settings so that sqlmap cant work for that website anymore.
The previous website is http://demo.testfire.net/bank/login.aspx
The website I am using is http://testfire.net/index.jsp
Not sure if they are exactly the same but 99% likely.

**Comment by stamparm** [comment]
closing because of this:
![image](https://user-images.githubusercontent.com/921555/218301895-52e57fb9-f4e0-412a-8e29-e05582952e30.png)

please, do your own research before raising this kind of issues. this has nothing to do with sqlmap - you just want somebody to do your job

**Comment by henryyds** [comment]
> 

What do you mean? I said I ran the code and it tells me the website is not injectable. What research could I have done?

**Comment by stamparm** [comment]
ok. then it is not injectable by sqlmap. case closed

**Comment by stamparm** [comment]
by doing your own research means that you are able to do anything more than just to run some automation tool and immediately open issues on github when you are not satisfied with results.

try to inject it on your own for start

**Comment by stamparm** [comment]
it goes like this. sqlmap unfortunately cannot enumerate things on this site - although, with the latest revision it can find the SQLi itself:

![image](https://user-images.githubusercontent.com/921555/218322780-21a044ce-c68d-4a4c-af8a-dde93f9b9002.png)

problem is that for some reason, authors decided to LOWER-case all the strings sent to that site. while Apache Derby doesn't have the capability to "escape strings" (i.e. somehow send a safe-to-evaluate string values - e.g. 0x3132... like in MySQL), this is totally screwing the sqlmap's capabilities for that same site
