### ISSUE TITLE
Dictionary or interaction for blind injection-based enumeration

### ISSUE THREAD

**Issue by kijube** [sqlmapproject/sqlmap#5316]
**Is your feature request related to a problem? Please describe.**
Blind injection takes quite some time, especially when enumerating column/table names where a person can likely guess the correct value. For example, when the injection has revealed `accou` one might be able to guess that the table name is actually `accounts`. While this might not always be the case, I feel like it could significantly speed up blind injection.

**Describe the solution you'd like**
To me, there are two alternatives (which are not necessarily exclusive):
- the user can at any point of the injection interact with it and enter a value for that they guess (if it is not correct, sqlmap just continues like it always does)
- the user can provide a wordlist of probable values that sqlmap can try if there is significant overlap (like if `accou` has been revealed so far and `accounts` is in the wordlist (just need some threshold))

**Comment by stamparm** [comment]
you are most probably like 100th user discovering this "idea". and i am most probably closing this down for 100th time.

there is no async interaction in python command line during a program run. either there is a block and everything stops, or there is a program run without waiting for user input

**Comment by kijube** [comment]
I provided a second option which does NOT require any interaction. Even my first option can be implemented in a different way. If you still don't think it provides any value then so be it, but you don't have to be rude about this.
