### ISSUE TITLE
__VIEWSTATE and __EVENTVALIDATION  problem 

### ISSUE THREAD

**Issue by ahmadsahimdova** [sqlmapproject/sqlmap#5321]
I tried manually payload works but when sqlmap __EVENTVALIDATION and __VIEWSTATE change payload does not work.
help pls
wor and not change __VIEWSTATE and __EVENTVALIDATION
https://i.postimg.cc/hv142stv/work.png

not work sqlmap change  __VIEWSTATE and __EVENTVALIDATION
https://i.postimg.cc/kXx33ZX7/no-work.png

**Comment by stamparm** [comment]
1) you totally failed to properly fill the issue template
2) in case that you are providing a valid request file or `--data`, sqlmap should ask you the following question:

`do you want to automatically adjust the value of '....'? [y/N]`

for both `__VIEWSTATE` and `__EVENTVALIDATION`
