### ISSUE TITLE
sqlmap form data still i can see empty

### ISSUE THREAD

**Issue by fako3221** [sqlmapproject/sqlmap#5347]
i am scanning my website 

`sqlmap -u http://127.0.0.1/form --forms --random-agent -p "user" --data="password=NotEmpty" --batch -t logtraffic.txt
`
yet if i go and open log traffic.txt I get

`    VIEWSTATE=FilledWithCorrectValue&VIEWSTATEGENERATOR=FilledWithCorrectValue&user=filledwithValue&password=
`
why doesn't password get filled. I am using python version 3.10 and also latest sqlmap version from website. I am on windows, please give me ideas thank you

**Comment by stamparm** [comment]
because `--forms` is taking stuff from the web page itself, not using your provided data. you should not mix `--forms` and `--data`. just fill the `--data` the way you would fill the form inside the tested page
