### ISSUE TITLE
sqlmap --data for form data

### ISSUE THREAD

**Issue by noname29** [sqlmapproject/sqlmap#5352]
i am scanning my website

     sqlmap -u http://127.0.0.1/form --forms --random-agent -p "user" --data="password=NotEmpty" --batch -t logtraffic.txt 

yet if i go and open log traffic.txt, I get

     VIEWSTATE=FilledWithCorrectValue&VIEWSTATEGENERATOR=FilledWithCorrectValue&user=filledwithValue&password=

why doesn't password get filled. I am using python version 3.10 and also latest sqlmap version from website. I am on windows, 

I know that forms is taking stuff from the web page itself, not using my provided data. I should not mix --forms and --data.
Should I just fill the --data the way you would fill the form inside the tested page, so does that mean, I need to use data like this ? 

     --data="VIEWSTATE=FilledWithCorrectValue&VIEWSTATEGENERATOR=FilledWithCorrectValue&user=filledwithValue&password=NotEmpty"

Please give an example is possible. 

Thank you in advance

**Comment by stamparm** [comment]
don't mix `--data` and `--forms` (as i've said you before). AFAICS, you should just remove `--forms` and use `-u` and `--data`. 

not sure what is complicated here. `--forms` is to be used when you don't know which forms nor which data to provide to the site (i.e. generic search for forms). you already have all the stuff as i can see with `-u` and `--data`
