### ISSUE TITLE
Second URL intermediate tamper

### ISSUE THREAD

**Issue by raulsf6** [sqlmapproject/sqlmap#5353]
So, I was dealing with this second order injection where:

1- I launch the payload to an endpoint with a POST request, that endpoint answers OK and an identifier.
2- Results are showed in another endpoint launching a GET request, let's say example.com/identifier.

It would be great if there was a possibility to keep that identifier from the first petition and set it in the second one. This way I could replace the identifier with the correct value.

Maybe something like an intermediate tamper between the first petition and the second one could be the solution?

**Comment by stamparm** [comment]
1) that would be overcomplicated for regular users (i.e. it would never be used)
2) you can just do temporary dirty changes inside the sqlmap code just to suite your current needs
