### ISSUE TITLE
receive blank and error text table name

### ISSUE THREAD

**Issue by mamoru-69** [sqlmapproject/sqlmap#5365]
**Describe the bug**

**To Reproduce**
1. Run '`sqlmap.py -u https://web/login/ --data="user=a&pass=a" -D dbname --tables  --batch --random-agent`'
2. Error Name Table with blank and android\x07\xc3d_?en>

**Expected behavior**

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/38677903/225552443-8ed6d92f-32c2-4d03-9d3d-f974c51c2ede.png)

**Running environment:**
 - sqlmap version 1.7.3.1#dev
 - Installation method pip
 - Operating system: Microsoft Windows 10
 - Python version 3.10.4

**Target details:**
 - DBMS Microsoft SQL Server 2019

 - Relevant console output [if any]
 - Exception traceback [if any]

**Additional context**
Sorry, my English is bad

**Comment by stamparm** [comment]
you skipped information on SQLi type. if this is time-based blind, try to use higher value for `--time-sec` (e.g. `--time-sec=10`). if this is boolean-based blind, try to use `--string`

**Comment by mamoru-69** [comment]
> you skipped information on SQLi type. if this is time-based blind, try to use higher value for `--time-sec` (e.g. `--time-sec=10`). if this is boolean-based blind, try to use `--string`

Like this 
`sqlmap.py -u website.com --data="data=a&data1=a" --dbms=mssql -D database --tables --string --time-sec=10 --batch --random-agent`

**Comment by mamoru-69** [comment]
> you skipped information on SQLi type. if this is time-based blind, try to use higher value for `--time-sec` (e.g. `--time-sec=10`). if this is boolean-based blind, try to use `--string`

Thank's @stamparm Working good!
