### ISSUE TITLE
Cannot scan only header

### ISSUE THREAD

**Issue by ertygiq** [sqlmapproject/sqlmap#5376]
**Describe the bug**
I'm trying to run sqlmap and scan only single HTTP-header value. 
My `req.txt` file has the following content:
```
GET /?sdtgqpzb=aargudvl HTTP/1.1
Host: localhost
X-Foo: *
Connection: close

```
As you can see I added the cache buster query-parameter. 
When I run sqlmap though proxy (`python3 sqlmap.py -r req.txt --batch --proxy http://127.0.0.1:8080       `), I can see that after scanning `X-Foo` header, sqlmap scans `sdtgqpzb` parameter value.
How can I prevent this?

**Running environment:**
 - sqlmap version 1.7.1.11#dev

**Target details:**
 - localhost

**Comment by stamparm** [comment]
yea, who reads questions nowadays:

![image](https://user-images.githubusercontent.com/921555/228846168-363c12ba-239a-4549-a76a-c79a17c50082.png)

there are two paths:

1) press `n` here ^^ and press `<Enter>`
OR
2) use `--answers "process=n"` if you use `--batch`
