### ISSUE TITLE
port will add automatically to the http request

### ISSUE THREAD

**Issue by inVains** [sqlmapproject/sqlmap#5379]
**Describe the bug**
When perform a request, port (for http is 80) will add automatically to the http raw request.
I can tell from an upstream proxy log. The below one is from sqlmap while the other is from browser.
![image](https://user-images.githubusercontent.com/2282229/228877147-39177339-4d1c-46ec-8304-f3a58c8576f0.png)

Some site just response differently with/without the ":80".
I have try in Burpsuite and it really matters for this site. :(
![image](https://user-images.githubusercontent.com/2282229/228877857-778cf8b5-81fa-465b-8c8b-833b023cce5a.png)
![image](https://user-images.githubusercontent.com/2282229/228878096-53a6d9d1-0b9b-4a09-a03e-a03630515788.png)

I have try -u with URL:
`sqlmap.py --proxy=http://127.0.0.1:10809 -u "http://example.com/74*/id/8254.html" -v 6`
or -r with a request file:
```
GET http://example.com/74*/id/8253.html HTTP/1.1\n
Host: example.com
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cookie: PHPSESSID=dhamjd1fop10gq2197s7v309tv; Hm_lvt_11b8bc3714737eaf4e676e3a0b255640=1680137685; Hm_lpvt_11b8bc3714737eaf4e676e3a0b255640=1680180772
Connection: close
```
no luck.
is there any option I missed?
thanks.

**Running environment:**
 - sqlmap version [1.7.3#pip]
 - Installation method [e.g. pip]
 - Operating system: [Microsoft Windows 10]
 - Python version [3.10.0]

**Comment by stamparm** [comment]
it is not clear whether you want `:80` to be appended by sqlmap or you noticed sqlmap to be doing it?!

i can see that you did couple of screenshots, but it is not clear who is doing what

**Comment by inVains** [comment]
> it is not clear whether you want `:80` to be appended by sqlmap or you noticed sqlmap to be doing it?!
> 
> i can see that you did couple of screenshots, but it is not clear who is doing what

I noticed sqlmap doing it automatically while I do not want it to. 😁

**Comment by stamparm** [comment]
req.txt:

```
GET http://localhost/?id=74*/id/8253.html HTTP/1.1
Host: localhost
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cookie: PHPSESSID=dhamjd1fop10gq2197s7v309tv; Hm_lvt_11b8bc3714737eaf4e676e3a0b255640=1680137685; Hm_lpvt_11b8bc3714737eaf4e676e3a0b255640=1680180772
Connection: close
```

result:

![image](https://user-images.githubusercontent.com/921555/229375224-3355052a-3a43-4619-9fb9-2b1cab13b8b8.png)

wireshark:

![image](https://user-images.githubusercontent.com/921555/229375288-80e5f187-0e0a-4ffe-a2cc-34d6d55ffad5.png)

**Comment by stamparm** [comment]
so, i am not able to reproduce your problem

**Comment by inVains** [comment]
It seems to happen only when sqlmap using a http proxy (while using socks5 proxy is ok) directly to my local proxy (V2Ray: https://github.com/2dust/v2rayN).
When using http proxy, is there any deep check about the proxy type or method in sqlmap?

I have some test already with different client( sqlmap & curl) and different local proxy (v2ray & burp suite & fiddler classic).
result seems confusing.
trying to read the code...
thanks.

request:
`curl.exe -v --proxy http://127.0.0.1:8080 http://testphp.vulnweb.com/product.php?pic=6`
`sqlmap.exe -v 6 --proxy=http://127.0.0.1:8080 -u "http://testphp.vulnweb.com/product.php?pic=6"`

result:
1.  sqlmap vs curl using the same V2Ray proxy. both return 200, but sqlmap adding a port after hostname.
(log from v2ray)
![image](https://user-images.githubusercontent.com/2282229/230261855-c39ddd5e-56bf-4f1d-b7d8-9700af0d7682.png)

3. sqlmap vs curl using the same burp suite proxy(same result with fiddler). both return 200, and neither adding an port.
![image](https://user-images.githubusercontent.com/2282229/230262341-9b594fa8-a14f-4a34-9867-9657a0b020e0.png)
![image](https://user-images.githubusercontent.com/2282229/230262372-e15df3a7-1b5e-4afd-ba47-274082edca0a.png)

4. sqlmap using proxy chain manually like: sqlmap->burp suite->V2Ray ->target. return 200, and not adding an port.
![image](https://user-images.githubusercontent.com/2282229/230263181-5a08241f-3f57-460b-b167-5a21b3bbbb82.png)

**Comment by inVains** [comment]
below codes set the url default port to 443 for https/wss and to 80 for others. and lead urllib to request with url with port.

https://github.com/sqlmapproject/sqlmap/blob/4dd362cb2ce61ed2558749edaac2a2be239c3e9b/lib/core/common.py#L1772
![image](https://user-images.githubusercontent.com/2282229/230304200-c8df4eca-5aa5-4414-aafe-50162cbc4d4a.png)
