### ISSUE TITLE
[CRITICAL] page not found (404)

### ISSUE THREAD

**Issue by binis** [sqlmapproject/sqlmap#538]
Hi, I have this problem too "[CRITICAL] page not found (404)"
I use the version of sqlmap/1.0-dev-dd87233
./sqlmap.py --url=http://www.hidden.com/programme_*_1

sqlmap/1.0-dev-dd87233 - automatic SQL injection and database takeover tool
http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting at 23:58:18

custom injection marking character ('*') found in option '-u'. Do you want to process it? [Y/n/q] y
[23:58:23] [INFO] resuming back-end DBMS 'mysql'
[23:58:23] [INFO] testing connection to the target URL
[23:58:24] [CRITICAL] page not found (404)
it is not recommended to continue in this kind of cases. Do you want to quit and make sure that everything is set up properly? [Y/n]

if I go, I get to enter the database but I can not do anything, I always have this error 404 or forbidden.

Thank you in advance for your help

**Comment by mikelty** [comment]
this can also be caused by automatically escaping a forward slash with a backward slash before it in the URL.
