### ISSUE TITLE
AttributeError: module 'inspect' has no attribute 'getargspec'

### ISSUE THREAD

**Issue by vomanc** [sqlmapproject/sqlmap#5381]
sqlmap 1.7.3.6#dev
Python 3.11.2

sqlmap-dev/lib/core/option.py, line 915
AttributeError: module 'inspect' has no attribute 'getargspec'

python 3.11.2 no longer uses the "getargspec"

**Comment by R-Rothrock** [comment]
I was thinking about adding an issue about, this, as `getargspec` was removed in Python 3.11. I'll send them a pull request as an attempt to fix the problem.

**Comment by stamparm** [comment]
![image](https://user-images.githubusercontent.com/921555/230008039-f530095b-98c4-4969-9a20-db00f41fd105.png)

![image](https://user-images.githubusercontent.com/921555/230008118-d9dcbd02-c7ed-45a5-849a-b497555bece1.png)

![image](https://user-images.githubusercontent.com/921555/230008807-ec41f40d-7502-4ed8-b1b4-1684f137b6c3.png)

and some more "proof":

![image](https://user-images.githubusercontent.com/921555/230009061-dbacc72d-e85d-4913-a215-9879271a9c9f.png)

**Comment by stamparm** [comment]
@vomanc try now with latest revision

**Comment by vomanc** [comment]
@stamparm, everything is correct now. Thank you
