### ISSUE TITLE
--csrf-url replacing url string with case in-sensitive.

### ISSUE THREAD

**Issue by roriau0422** [sqlmapproject/sqlmap#5388]
The GET parameter query 'formToken=xxxxxxxxxxxxx' is a case-sensitive parameter. However, when I use the 'csrf-url' and 'csrf-token' options, the parameter becomes 'formtoken' (case-insensitive), and the request goes wrong.

Sqlmap version: 1.7.3.4#dev
OS: Windows 11

**Comment by agarwalutkarsh554** [comment]
Based on the information provided, it seems that you are facing an issue with case sensitivity of the GET parameter 'formToken' while using sqlmap with 'csrf-url' and 'csrf-token' options.

Sqlmap uses various techniques to bypass web application security measures such as CSRF tokens. One such technique is to use the 'csrf-url' and 'csrf-token' options to automate the process of retrieving and submitting CSRF tokens. However, in your case, it seems that the value of the 'formToken' parameter is being changed to 'formtoken' while using these options, which is causing the request to fail.

To fix this issue, you can try specifying the case-sensitive parameter value explicitly in the command line using the '--data' option. For example, you can try the following command:

`sqlmap -u "http://example.com/page.php?formToken=xxxxxxxxxxxxx" --data "formToken=xxxxxxxxxxxxx" --csrf-url "http://example.com/csrf.php" --csrf-token "csrf_token"
`
This command explicitly specifies the value of the 'formToken' parameter as 'xxxxxxxxxxxxx' using the '--data' option, which should bypass the case sensitivity issue.

**Comment by stamparm** [comment]
![image](https://user-images.githubusercontent.com/921555/231162235-50b9a9b4-b3fb-4197-b01e-97afa0e4ac7e.png)
