### ISSUE TITLE
error --os-pwn 

### ISSUE THREAD

**Issue by mamoru-69** [sqlmapproject/sqlmap#5391]
#Support
can this be overcome?

web server operating system: **Windows 10 or 11 or 2019 or 2022 or 2016**
web application technology: **ASP.NET, Microsoft IIS 10.0**
back-end DBMS: **Microsoft SQL Server 2019**

`sqlmap -u https://website/ --data="data1=a&data2=a" --dbs --os-pwn  --random-agent --time-sec=10 --parse-errors
`

![Untitled](https://user-images.githubusercontent.com/38677903/231311062-c9c798e7-6adf-4a7e-b6eb-911dcd5fcbf1.png)

**Comment by stamparm** [comment]
it all says in the program's output. not sure why you raise this kind of issues
