### ISSUE TITLE
Missing Support for TLSv1.3

### ISSUE THREAD

**Issue by shelklas** [sqlmapproject/sqlmap#5392]
**Describe the bug**
When attempting to use sqlmap on an endpoint that exclusively supports TLSv1.3, the connection will fail and sqlmap will return an error indicating: `[CRITICAL] can't establish SSL connection`. Increasing the verbosity, the error appears to be rooted in sqlmap attempting to utilize TLS versions below TLSv1.3.

The debug messages contained the following errors:
```bash
[DEBUG] SSL connection error occurred for 'PROTOCOL_TLSv1_2' ('SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:997)')
[DEBUG] SSL connection error occurred for 'PROTOCOL_TLSv1_1' ('SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:997)')
[DEBUG] SSL connection error occurred for 'PROTOCOL_TLSv1' ('SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:997)')
```

Since none of these protocols are supported by the server, sqlmap cannot establish a connection. Proxying these requests through Burp or another proxy would resolve this issue temporally. sqlmap should support this protocol by default.

**To Reproduce**
1. Attempt to run sqlmap against a web application that only utilizes the TLSv1.3 protocol.
2. See error `[CRITICAL] can't establish SSL connection`.

**Screenshots**
Checking the permitted TLS protocols by endpoint:
<img width="361" alt="tls_config" src="https://user-images.githubusercontent.com/10224584/231902213-0626e96c-a0af-4f0e-9f69-5f7d1665aeeb.png">

Running sqlmap against the endpoint elicits an error:
<img width="1156" alt="windows_error_screen" src="https://user-images.githubusercontent.com/10224584/231902224-daac77d0-bc86-4928-b165-eb6d705ddfa8.png">

**Running environment:**
 - sqlmap version: 1.7.4.7#dev
 - Installation method: pip and github
 - Operating system: Microsoft Windows 11, Kali 2022.1
 - Python version: Python 3.10.8

**Additional context**
The reason this bug is occurring is due to the `httpshandler.py` file:
https://github.com/sqlmapproject/sqlmap/blob/60bb973c114e2bfb5463e9e1f4069081f356a092/lib/request/httpshandler.py#L30

This line indicates that only the following protocols are permitted:
`"PROTOCOL_TLSv1_2", "PROTOCOL_TLSv1_1", "PROTOCOL_TLSv1", "PROTOCOL_SSLv3", "PROTOCOL_SSLv23", "PROTOCOL_SSLv2"`.

With the latest SSL library, TLSv1.3 does not have a dedicated PROTOCOL constant, instead it is recommended to use `ssl.PROTOCOL_TLS`. Using this constant will attempt to select the highest protocol version that both the client and server support. In addition, both SSL and TLS are supported with this constant.

Adding support for TLSv1.3 will require some larger modification of the HTTPS handler.

**Comment by stamparm** [comment]
please try it now with the latest revision

**Comment by shelklas** [comment]
Although the patch resolves the issue for most endpoints, it introduces an undesirable side-effect due to the utilization of the `PROTOCOL_TLS_CLIENT` constant. This constant also enables `ssl.CERT_REQUIRED` and `SSLContext.check_hostname`, which will restrict sqlmap from scanning endpoints that present unknown, self-signed, expired, or otherwise invalid certificates. This includes certificates that have a mismatched Subject Name or Subject Alternative Name.

To address this issue, I created a patch that will allow sqlmap to accept these certificates. The patch has undergone testing against an endpoint that utilized TLSv1.3 with Python 3.11, Python 3.10, and Python 2.7, and no issues were encountered during testing. I also tested this patch against a server that supports TLSv1.2 to validate backwards compatibility.

**Comment by sg552** [comment]
> please try it now with the latest revision

Latest version ( 2023.10.13 ) still got this error.

python: 3.11  ,  WSL under windows 10 . 

any idea?

**Comment by akmlvl** [comment]
> Although the patch resolves the issue for most endpoints, it introduces an undesirable side-effect due to the utilization of the `PROTOCOL_TLS_CLIENT` constant. This constant also enables `ssl.CERT_REQUIRED` and `SSLContext.check_hostname`, which will restrict sqlmap from scanning endpoints that present unknown, self-signed, expired, or otherwise invalid certificates. This includes certificates that have a mismatched Subject Name or Subject Alternative Name.
> 
> To address this issue, I created a patch that will allow sqlmap to accept these certificates. The patch has undergone testing against an endpoint that utilized TLSv1.3 with Python 3.11, Python 3.10, and Python 2.7, and no issues were encountered during testing. I also tested this patch against a server that supports TLSv1.2 to validate backwards compatibility.

Maybe post the patch here ?

**Comment by stamparm** [comment]
@shelklas i find this to not me true. just checked with python3.11. at this place https://github.com/sqlmapproject/sqlmap/blob/master/lib/request/httpshandler.py#L86, i get the following:

```
result.context.verify_mode
  <VerifyMode.CERT_NONE: 0>
protocol
  <_SSLMethod.PROTOCOL_TLS_CLIENT: 16>
result.context.check_hostname
  False
```

that's caused by the following: https://github.com/sqlmapproject/sqlmap/blob/master/lib/request/httpshandler.py#L74-L75
