### ISSUE TITLE
BUG，testing if (custom) POST parameter '#1*' is dynamic broken down！

### ISSUE THREAD

**Issue by Deep0** [sqlmapproject/sqlmap#5403]
**Describe the bug**
The WAF is bypassed by using dirty data, but the data packet sql.txt is very large, and it is stuck when running with sqlmap, and no data is transmitted when it is stuck.

**To Reproduce**
1. Run  python3 sqlmap.py -r sql.txt 
2. See error
<img width="812" alt="图片" src="https://user-images.githubusercontent.com/25843151/233020453-b909f540-a59b-492c-9c9e-f49455d229c0.png">

**Expected behavior**
When sqlmap runs to [INFO] testing if (custom) POST parameter '#1*' is dynamic, it gets stuck and does not transfer data.

**Screenshots**
<img width="812" alt="图片" src="https://user-images.githubusercontent.com/25843151/233020453-b909f540-a59b-492c-9c9e-f49455d229c0.png">

**Running environment:**
 - sqlmap version [1.7.4.8#dev]
 - Installation method [git clone ]
 - Operating system: [Microsoft Windows 11]
 - Python version [3.11.2]

**Additional context**
Yes.

**Comment by stamparm** [comment]
can't help you here. there must be a reason at the HTTP level why it got stuck.

you could run everything with `-t traffic.txt` or `-v 6` and inspect what is being sent and when.

also, you could try to use `--proxy` and see the current status of the request and whether it got sent in the first place

as a last thing, you could try to run `wireshark` and check whether something just dropped the connection in between (e.g. WAFs tend to do that)
