### ISSUE TITLE
is it possible to sqli a url, which may injectable? 

### ISSUE THREAD

**Issue by sg552** [sqlmapproject/sqlmap#5406]
I have a URL, which looks like: 

```
POST /v1/api/user/resetUserPassword
```
this api only accept 1 parameter: email

and response looks like: 

- 200 when parameter is valid, and everything is OK in backend,  e.g. `e.g. `email=iamgood@a.com`, return body looks like:

```
{"operation":"/resetUserPassword","status":"OK","statusCode":200,"info":"Email sent to iamgood@gmail.com","errors":null}
```

- 403 when parameter is valid, however record not found in database, e.g. `email=email-not-found@a.com`, return body looks like:

```
{"operation":"https://mysite.com/api/user/resetUserPassword","status":"FORBIDDEN","statusCode":403,"info":null,"errors":{"timestamp":"2023-04-22T22:56:12.048+00:00","exceptionMessage":null}}
```

- 400 when parameter is not valid and triggered a SQL error in server, e.g. `email=abc@a.com'`, return body is blank

I am sure in the 3rd case, passing a `email=abc@a.com'` parameter will cause a SQL error, but how to make it injectable using SQLMAP? 

I tried these commands but all failed : 

- sql -u '...' --code=200
- sql -u '...' --code=200 --ignore-code=403
- sql -u '...' --code=403

So my question is : is this case, is the parameter `email` injectable ?thank you so much!

**Comment by stamparm** [comment]
sqlmap should able to automatically distinguish these kind of responses. that being said, i believe that you are not dealing with the SQLi.

i would suggest you to expand your "tests" and try stuff like `email=abc@a.com' OR '1'='1` AND `email=abc@a.com' OR '1'='0`
