### ISSUE TITLE
Add support for cypher injection

### ISSUE THREAD

**Issue by sectroyer** [sqlmapproject/sqlmap#5407]
Hello.
I recently played around with cypher injection. In my case sqlmap was able to detect "sql" injection and printed sample payload. However It wasn't able to do much about. I think it shouldn't be hard to add "basic support". To just print dbms (in my case it was neo4j), labels and keys. Queries I did manually had different syntax than sql but aren't very hard to craft so I think it should be possible to automate it with sqlmap?

**Comment by stamparm** [comment]
cypher is not RDBMS/SQL query language. it uses its own language (https://neo4j.com/developer/cypher/).

sqlmap is able to support only RDBMS systems supporting SQL language

**Comment by mmajchrowicz-afine** [comment]
I case somebody needs it in the future:
https://github.com/sectroyer/cyphermap
