### ISSUE TITLE
How to rule out false positive results

### ISSUE THREAD

**Issue by xXs1d6p01nt7Xx** [sqlmapproject/sqlmap#5408]
I am working on a bug bounty and I am able to access : do you want to use common column existence check? [y/N/q] y
which common columns (wordlist) file do you want to use?
[1] default '/usr/share/sqlmap/data/txt/common-columns.txt' (press Enter)
[2] custom

at this point I use default list and it retrieves words, then it goes as far as building columns and tables. The bounty team suspects this is a false positive but my only problem with this is that it builds tables and columns. I used --flush and got the same results numerous times.  It lists if numeric or non-numeric. What are the chances that this is a false positive?

**Comment by stamparm** [comment]
if you get something normal, in some small numbers (e.g. <10), then most probably you have a true-positive
if you get tons of results with `--common-XXX` switches, then most probably you have false-positive (i.e. JUNK)

you should rerun your stuff with `-v 3` and see which payloads sqlmap is trying to send. then use one of those payloads, and try to distinguish whether you get the similar or totally different result when you put a table/column that sqlmap finds OR when you put some random junk

**Comment by xXs1d6p01nt7Xx** [comment]
I am able to pivot from column to any table that sqlmap built, but I have to prove this without accessing customer PII.
