### ISSUE TITLE
GETTING ERROR WHEN UPDATING SQLMAP

### ISSUE THREAD

**Issue by hack0day** [sqlmapproject/sqlmap#541]
python ./sqlmap.py --update

```
sqlmap/1.0-dev-18d9e1d - automatic SQL injection and database takeover tool
http://sqlmap.org
```

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting at 23:10:47

[23:10:47] [INFO] updating sqlmap to the latest development version from the GitHub repository
[23:10:47] [INFO] update in progress .
[23:10:48] [ERROR] update could not be completed ('From git github com sqlmapproject sqlmap branch HEAD FETCH_HEAD error Your local changes to the following files would be overwritten by merge txt common columns txt Please commit your changes or stash them before you can merge Aborting')
[23:10:48] [INFO] for Linux platform it's required to install a standard 'git' package (e.g.: 'sudo apt-get install git')

[*] shutting down at 23:10:48

**Comment by dustfeather** [comment]
I have the same error even after fresh cloning.
Running git pull manually works fine and it doesn't bother me to do it, but it's annoying to see that error every time I run sqlmap.

**Comment by stamparm** [comment]
@dustfeather and what exact error do you get? If you are getting the one that says that your changes will be overwritten then its kind of complicated from sqlmap to FORCE the overwrite of your changes

**Comment by dustfeather** [comment]
[17:04:34] [INFO] updating sqlmap to the latest development version from the GitHub repository
[17:04:34] [INFO] update in progress .
[17:04:35] [ERROR] update could not be completed ('fatal Not a git repository or any of the parent directories git')
[17:04:35] [INFO] for Linux platform it's required to install a standard 'git' package (e.g.: 'sudo apt-get install git')

**Comment by giveen** [comment]
Are you doing this from a Windows platform? I'm assuming that the --update command invokes a git request, which will not work with Windows.

or if you are on linux, make sure to add git package.

**Comment by stamparm** [comment]
This is happening as the user has not done the git clone from the
beginning. I.e. he has downloaded the ZIP version which does not support
the git pull.

I'll update the error message accordingly.

**Comment by dustfeather** [comment]
@giveen The error I pasted earlier is from Kali Linux, I do have git installed, and I don't run the default sqlmap installation Kali comes with, it's a fresh clone.
I hope that answers your questions.

**Comment by giveen** [comment]
@dustfeather it does. I see that @stamparm already answered the question. I was just throwing out ideas.

**Comment by stamparm** [comment]
@dustfeather message `updating sqlmap to the latest development` appears in situations when there is a `.git` directory inside the `sqlmap`, but INVALID one. Can you please list the content of your `sqlmap/.git` directory? One reason that comes to my mind is that you've deleted its content because of its size

**Comment by dustfeather** [comment]
I don't have a space problem, and I didn't delete anything, I told you, that error appears even after fresh repo cloning. :)

**Comment by stamparm** [comment]
@dustfeather ok. can you please run the following commands and report back what's going on?

```
cd /tmp
git clone https://github.com/sqlmapproject/sqlmap.git sqlmap
cd sqlmap
python sqlmap.py --update
```

p.s. if you still have problems please tell me which distro are you using so I could (try to) reproduce the behavior

![123](https://cloud.githubusercontent.com/assets/921555/10630538/7bfe1454-77d7-11e5-8423-ec834749b01d.png)

**Comment by dustfeather** [comment]
Running `python sqlmap.py --update` works, but if I run:
```bash
cd ~
ln -s /usr/share/sqlmap/sqlmap.py sqlmap
./sqlmap
```
It doesn't work, `/usr/share` is just an example, it doesn't matter in what location I clone the repo.
My distro is Kali 2.0, but with freshly cloned repo, not the default installation.
Thanks.

**Comment by stamparm** [comment]
@dustfeather <- that's the way I like it :). Great comment on an Issue. Help a lot

**Comment by stamparm** [comment]
@dustfeather please retry with the latest revision

**Comment by dustfeather** [comment]
Works like a charm, thanks a lot for fixing that :)
