### ISSUE TITLE
DNS exfiltration issue with null bytes MSSQL

### ISSUE THREAD

**Issue by brenocss** [sqlmapproject/sqlmap#5411]
**Describe the bug**

When performing DNS exfiltration on MS SQL, some responses come in the UTF16 format. SQLmap is not properly handling this case and having trouble pulling the next queries since it "thinks" that the tables, columns, and database have these null bytes characters.

**To Reproduce**
Exfil dns 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/57222005/236657125-f8597a02-93bc-4d3b-ac9e-8c6145fa0716.png)

**Running environment:**
 - {1.7.5#stable}
 - pip
 - ubuntu
  - Python 3.10.6

**Target details:**
 - MSSQL
  - SQLi techniques DNS

**Additional context**
I made this "quick fix" for my case, but it will certainly break in other cases.
```diff
@@ -97,6 +97,10 @@ def dnsUse(payload, expression):
             output = decodeDbmsHexValue(output) if conf.hexConvert else output

             kb.dnsMode = False
+            try:
+                output = output.replace('\x00', "")
+            except:
+                pass
```

**Comment by brenocss** [comment]
shoudn't this be only applied when db is mssql?

**Comment by stamparm** [comment]
@brenocss not the same commit has been done
