### ISSUE TITLE
injection problem

### ISSUE THREAD

**Issue by REtoolsx** [sqlmapproject/sqlmap#5415]
I have an injection problem with sqlmap

my sqlmap command :  sqlmap.py -r ".txt" --level 3 --risk 3 -v 3 --force-ssl --dbms="MYSQL" --tamper=escapequotes

found sql
https://prnt.sc/hX04Tf_F-tkx

sqlmap result : (custom) POST parameter '#1*' does not seem to be injectable

how can i fix this please tell me if i am using sqlmap tool wrong

**Running environment:**
 - sqlmap version [1.7.5 stable]
 - Installation method [zip]
 - Operating system: [Windows 11]
 - Python version [3.8]

**Target details:**
 - DBMS [MYSQL]
 - WAF/IPS [no)

**Comment by REtoolsx** [comment]
another injection problem ,, a different app : https://prnt.sc/7g0RILp-07gW

**Comment by stamparm** [comment]
that's not proof of "usable" SQLi. i would say that you have some character escaping going on here (AFAIK, you already tried to bypass it with a tamper script). sqlmap Issues is not meant to be dealing with sqlmap bugs, not user problems. please try to bypass the escaping manually
