### ISSUE TITLE
password field has bad encoding

### ISSUE THREAD

**Issue by badr-elmazaz** [sqlmapproject/sqlmap#5418]
**Describe the bug**
Im trying to dumping a database, but in password field I receive bad characters, I tried with all combinations: with and without --hex, --binary-fields and so on

**To Reproduce**
1. Run 'sqlmap -r login_request.req --batch --force-ssl -D test -T users -C email,password,username  --dump --encoding=utf-8 --hex --binary-fields=password
'
2. I receive passwords like: ÉÀyK -  •Œ6\x7f) - 4ÅîŸ (hex=34C385C3AEC5B8)

**Running environment:**
{1.7.2#stable} 

**Target details:**
 MySQL >= 5.0.12 AND time-based blind (query SLEEP)

**Additional context**

**Comment by stamparm** [comment]
either

1) password hash is stored in binary format in that field
OR
2) you have a false-positive finding
OR
3) you have a big latency in your connection requests toward the target

if you are able to retrieve other fields without any problems, then most probably you have a 1) or 3). in case of 3) you could try to force the bigger delay (e.g. `--time-sec=10`)
