### ISSUE TITLE
Use SQLmap in java

### ISSUE THREAD

**Issue by TheMostofTheMost** [sqlmapproject/sqlmap#5419]
Hello!
I cant find way to use SQLmap in java. Many libraries are outdated.

How to use sqlmap using java?

**Comment by grips1** [comment]
WDYM? sqlmap doesn't seem to have a Java API.

**Comment by stamparm** [comment]
> Hello! I cant find way to use SQLmap in java. Many libraries are outdated.
> 
> How to use sqlmap using java?

not sure what is going on here. "many libraries are outdated", while you want to use "SQLmap in java". please, try to use some other SQLi tool as sqlmap is not meant to be run "in java"
