### ISSUE TITLE
Weird 403

### ISSUE THREAD

**Issue by M-Tofla** [sqlmapproject/sqlmap#5423]
Hi @stamparm 

i got 200 on burp but 403 on sqlmap

when i check with -v 6 on sqlmap, then copy the request to burp, yeah i got 403.
so i check again, that different on User-agent
if using capital on A in "agent" = 200 ( User-Agent )
if using lower on a in "agent" = 403 ( User-agent )

i see sqlmap request using lower on A in agent, 

when i using --header with a capial on it, its still going low in request

sorry for weird question

Thank you

![User-agent](https://github.com/sqlmapproject/sqlmap/assets/45419019/13d1e505-7674-425c-8a2c-39ad078fc9d7)

**Comment by REtoolsx** [comment]
There's one more place you missed

https://prnt.sc/lEiepN5DvgQ5

**Comment by M-Tofla** [comment]
Thank you for answer but the problem is on capital

![1](https://github.com/sqlmapproject/sqlmap/assets/45419019/3f4439cb-e83d-48f9-8907-eca979fc08fa)

**Comment by M-Tofla** [comment]
> There's one more place you missed
> 
> https://prnt.sc/lEiepN5DvgQ5

and sorry, that got eraser from paint editing

**Comment by stamparm** [comment]
actually, sqlmap is sending upper case version, but it displays it differently in `-v 6`:

![image](https://github.com/sqlmapproject/sqlmap/assets/921555/14421e09-9d3f-45bb-8319-5a42a1598d29)

**Comment by stamparm** [comment]
@M-Tofla please retry now `-v 6` with latest revision. It should show a proper case of header names

**Comment by M-Tofla** [comment]
Hi @stamparm 

Its fixed, no 403 again, 

Thank you
![Fixed](https://github.com/sqlmapproject/sqlmap/assets/45419019/d821abba-9112-4bb7-b0f4-0945c29c64b4)
