### ISSUE TITLE
H2 Database is not being recognized -- SQL Syntax Error

### ISSUE THREAD

**Issue by ahmadzuhd** [sqlmapproject/sqlmap#5431]
For H2 Databases hosted with Spring boot Application, i have tried make different types of enumerations but failed at the stage of identifying the database type. I'm using H2 2.1.214 (2022-06-13) 

I have the following vulnerable API for testing.. the parameter to is vulnerable:
`sqlmap --flush-session --method=GET -p to -b -v 3  -u "http://localhost:8000/rates?from=USD&to=EUR"`

checking the verbose results from the command, i can see that sqlmap executes a Union injection to identify that the database is H2. It adds the below SQL statement, which is seems to be not working with the current H2 database i have 
 
```
[14:25:19] [INFO] testing H2
[14:25:19] [PAYLOAD] NIS' UNION ALL SELECT NULL,'qzxvq'||(SELECT (CASE WHEN (ZERO() IS 0) THEN 1 ELSE 0 END))||'qxqpq',NULL,NULL-- pqSH
[14:25:19] [DEBUG] performed 1 query in 0.03 seconds
[14:25:19] [WARNING] the back-end DBMS is not H2
```

I have manually applied the command to the H2 data as in the screenshot below and it shows a syntax error:

<img width="1320" alt="Screenshot 2023-06-03 at 2 37 18 PM" src="https://github.com/sqlmapproject/sqlmap/assets/23163198/692e8801-4d45-4b78-920c-24f8f5ca9fee">

It is clear from the screenshot the error:

```
Syntax error in SQL statement "SELECT * FROM CURRENCYEXCHANGE where tocurrency ='USD' UNION ALL SELECT NULL,'qzxvq'||(SELECT (CASE WHEN (ZERO() IS [*]0) THEN 1 ELSE 0 END))||'qxqpq',NULL,NULL-- pqSH"; expected "NOT, OF, JSON, NULL, DISTINCT, TRUE, FALSE, UNKNOWN"; SQL statement:
SELECT * FROM CURRENCYEXCHANGE where tocurrency ='USD' UNION ALL SELECT NULL,'qzxvq'||(SELECT (CASE WHEN (ZERO() IS 0) THEN 1 ELSE 0 END))||'qxqpq',NULL,NULL-- pqSH [42001-214] 42001/42001 [(Help)](https://h2database.com/javadoc/org/h2/api/ErrorCode.html#c42001)
```

So i think there is a problem in the command that should identify the H2 database

**Comment by stamparm** [comment]
`ZERO()` should be a regular H2 function (see http://www.h2database.com/html/functions.html#zero)

As you already have an ready to be used SQL query interface, you could do a proper debugging and report back what's the problem

**Comment by ahmadzuhd** [comment]
yes zero() is supported, however it seems that IS couldn't be used like this ..


`SELECT * FROM CURRENCYEXCHANGE where ZERO() is 0`

```
Syntax error in SQL statement "SELECT * FROM CURRENCYEXCHANGE where ZERO() is [*]0"; expected "NOT, OF, JSON, NULL, DISTINCT, TRUE, FALSE, UNKNOWN"; SQL statement:
SELECT * FROM CURRENCYEXCHANGE where ZERO() is 0 [42001-214] 42001/42001 [(Help)](https://h2database.com/javadoc/org/h2/api/ErrorCode.html#c42001)
```


While this SQL command was executes successfully

`SELECT * FROM CURRENCYEXCHANGE where ZERO() = 0`

**Comment by ahmadzuhd** [comment]
I have made the change my local "plugins/dbms/h2/fingerprint.py" .. And the Database is now identified correctly and i can do different kinds of enumerations.

https://github.com/sqlmapproject/sqlmap/blob/8466a89ed395c84d06a5ee319a827f87256a82f4/plugins/dbms/h2/fingerprint.py#L90

`        result = inject.checkBooleanExpression("ZERO() = 0")`

**Comment by stamparm** [comment]
pretty sure that this worked when i implemented it. nonetheless, will do proposed changes
