### ISSUE TITLE
Saving the schema to a separate file

### ISSUE THREAD

**Issue by kobyan1** [sqlmapproject/sqlmap#5432]
Now in sqlmap it is possible to get the database schema (--schema).
But this scheme is output to the console and saved in the log file.
The scheme is large, so it often does not fit completely into the console, and the log file is constantly updated, so it is also not convenient to look at the scheme there.

Therefore, it would be nice if the scheme was saved in a separate file

**Comment by stamparm** [comment]
won't fill garbage output files. sorry
