### ISSUE TITLE
-R argument scanning wrong port

### ISSUE THREAD

**Issue by Gino-Tonic** [sqlmapproject/sqlmap#5433]
Trying to work on port 31410 from a .txt file, using the -r argument SQLmap 
sqlmap -r req.txt

Returns this error on a different port:
[11:47:42] [INFO] parsing HTTP request from 'req.txt'
[11:47:42] [CRITICAL] invalid target URL port (314104)

SQLmap works corretly on the port when running directly from the commandline. 
Sqlmap 'http://IPADDR:31410/case4.php' -X POST --data-raw '{"id":1}' --batch

The req.txt file:

HTTP / HTTP/1.0
Host: IPADDR:31410/case4.php

{
  "data": [{
    "id": "1"
  }]
}

**Comment by stamparm** [comment]
![image](https://github.com/sqlmapproject/sqlmap/assets/921555/23f870d3-fa0a-48db-a640-80b2db6029da)

**Comment by Gino-Tonic** [comment]
![sqlmap_port_error2](https://github.com/sqlmapproject/sqlmap/assets/133790287/649b1aed-d70c-43a4-b1ba-d0c28f739d60)

**Comment by stamparm** [comment]
you are doing cat, then nano for whatever reason, then sqlmap. ignoring
this whole mess

**Comment by Gino-Tonic** [comment]
Sry about that - meant no offense, just trying to help out... All the best and thanks for a great tool!
