### ISSUE TITLE
Wrong payloads in stacked queries

### ISSUE THREAD

**Issue by kobyan** [sqlmapproject/sqlmap#5437]
In checking for stacked queries injection, there are payloads that contain errors in SQL syntax.
Example - ` [PAYLOAD] 1);SELECT PG_SLEEP(5) AND (2707=2707`
`[PAYLOAD] 1');SELECT COUNT(*) FROM GENERATE_SERIES(1,5000000) AND ('UnRe'='UnRe`
You cannot use AND in the SELECT or FROM part of the SQL query, so such a query will fail with an error in the DBMS.
It would be more correct here to use WHERE instead of AND
`1);SELECT PG_SLEEP(5) WHERE (2707=2707`
`1');SELECT COUNT(*) FROM GENERATE_SERIES(1,5000000) WHERE ('UnRe'='UnRe`

**Comment by stamparm** [comment]
oh please. sqlmap is generating payloads based on "vectors" and "boundaries". i am fully aware that some of those are "junky", but majority is pretty much fine. this is not science
