### ISSUE TITLE
SqlMap is not able to recognise cookies if the value is on new line.

### ISSUE THREAD

**Issue by urakesh661** [sqlmapproject/sqlmap#5441]
Hi,

I would like to bring your attention towards below behaviour:

Suppose if a request is in below format in a file where value of connect.sid parameter for cookie header is in new line,then sqlmap is not able to recognise it and thinks that the user is not logged in, whereas it works fine when cookie parameter is in the same line:

**Request where Sqlmap doesn't consider the cookie value:**

POST /profile HTTP/1.1
Host: localhost:4000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0)
Gecko/20100101 Firefox/114.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/$
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Content-Length: 109
Origin: http://localhost:4000
Connection: close
Referer: http://localhost:4000/profile
Cookie: 
connect.sid=s%3AYoTJiL8n06kgek1kzOIADp0FNS1QTP0S.Y%2BuJDaXHwSCr%2BZyVzR$
Upgrade-Insecure-Requests: 1

**Request where Sqlmap  considers the cookie value:**

POST /profile HTTP/1.1
Host: localhost:4000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0)
Gecko/20100101 Firefox/114.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/$
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Content-Length: 109
Origin: http://localhost:4000
Connection: close
Referer: http://localhost:4000/profile
Cookie: connect.sid=s%3AYoTJiL8n06kgek1kzOIADp0FNS1QTP0S.Y%2BuJDaXHwSCr%2BZyVzR$
Upgrade-Insecure-Requests: 1

Due to this the user will be considered as unauthenticated and may not be able to run the scan in correct way until the formatting is corrected.

Please have a look at this.

Thanks

**Comment by stamparm** [comment]
how can newline be inside the HTTP header is beyond my comprehension

**Comment by nu11secur1ty** [comment]
Good question :)

> how can newline be inside the HTTP header is beyond my comprehension
