### ISSUE TITLE
Multiple techniques but don't know which one it is using

### ISSUE THREAD

**Issue by jedai47** [sqlmapproject/sqlmap#5442]
**Is your feature request related to a problem? Please describe.**
 I'm frustrated when sqlmap finds multiples techniques for ex: boolean-based blind and time-based blind but then when i begin to dump i dont know which one it is using

**Describe the solution you'd like**
Just a line that says sqlmap is using technique of type: XYZ

**Describe alternatives you've considered**
None

**Additional context**
Specially to use the faster technique for data retrieval

**Comment by stamparm** [comment]
sqlmap is always using from fastest (usable) to slowest (usable) technique
