### ISSUE TITLE
Is it possible to find out the real ip address of a website where we can pull the database with sqlmap?

### ISSUE THREAD

**Issue by Phoenix1112** [sqlmapproject/sqlmap#5449]
hi. I think one of the greatest projects in the world is sqlmap.. thanks for this project..  As the title suggests, I can pull a site's database with sqlmap. but the website ip address is as important to me as the database. Is there a command where I can find the ip address of the target site with sqlmap?

**Comment by stamparm** [comment]
just do `ping <hostname>` from a command prompt (e.g. `ping www.google.com`)

**Comment by stamparm** [comment]
not sure that you'll be able to do it with sqlmap. if you have a **working** SQL injection, you can try to use `--hostname`
