### ISSUE TITLE
Adding parameters to tamper scripts 

### ISSUE THREAD

**Issue by kaleb-c0d3** [sqlmapproject/sqlmap#5452]
Hi! Is there a way to pass parameters to the tamper scripts from the command line?

I've wrote some tampers in the past (a loooong time ago I was one of the people that worked with it), and want to feed the script with some specific parameters for each test case. Tried to add any custom parameter and catch it later using like 'sys.argv', but the param parser is kicking me out because "sqlmap.py: error: no such option: --tamper-param-1".

I can manage it by editing the script by hand for each scenario, but it could be very useful to have something along the line like:

`python ./sqlmap.py -u '......' --tamper="awsometamper" --tamper-param-1="true" --tamper-param-2="/tmp/something.out"` 

Thank you very much in advance.

**Comment by stamparm** [comment]
with latest revision:
![image](https://github.com/sqlmapproject/sqlmap/assets/921555/3fb40d15-ce80-452a-9a3e-7363f1722b45)
