### ISSUE TITLE
sqlmap freezing in big request file

### ISSUE THREAD

**Issue by shadowzoom** [sqlmapproject/sqlmap#5455]
Hi there, sqlmap can't process injection in big request file. I have a request file which contains 235922 characters (it's big because of one of parameter __VIEWSTATE, without __VIEWSTATE request is not valid, so sadly i need to include it)
Any tips or fix how to process with sqlmap this big request file? Tried on Win,LInux - result is the same, sqlmap can't process it

**Comment by stamparm** [comment]
not sure what to do here. you can send such request file to me privately so i could try to reproduce it

**Comment by cameron-brown2** [comment]
I have this exact same issue, what was the solution if this issue has been closed?
