### ISSUE TITLE
add --string-hex to verify string when it is true

### ISSUE THREAD

**Issue by Heyholiday067** [sqlmapproject/sqlmap#5456]
**Is your feature request related to a problem? Please describe.**
Sometimes the respone is not all ascii printable characters,so use  --string to verfiy the condition is not enough,maybe we use something like this,ex:--string-hex "00000000" is better for boolean-based injection

**Describe the solution you'd like**
add an option --string-hex

**Describe alternatives you've considered**
i havent think that

**Additional context**
if we have --string-hex,--not-string-hex needs to be added too.

**Comment by stamparm** [comment]
sqlmap internally uses unicode to store the retrieved page content. I can see tons of problems in making your `...hex` options working in such conditions. Additionally, I don't see an added value when comparing with hundreds of more options you already have inside (e.g. you have `--code` which could help you in your case; also, I can't imagine a case when you can't at least get two straight ASCII chars for usage inside the `--string` or `--not-string`)
