### ISSUE TITLE
"Help" SQLMap blind SQL exfiltration by giving it hints/dictionary words.

### ISSUE THREAD

**Issue by JPaulMora** [sqlmapproject/sqlmap#5457]
**Is your feature request related to a problem? Please describe.**
Blind SQL can be really slow, at most every character will take up to 8 requests to the server.

**Describe the solution you'd like**
After 5 or so letters in a word, it's easy to try and infer what word is it, either let the user input a letter/string to test or let me specify a dictionary file. Below a few examples:

Website is called "Top Sales":
[14:25:28] [INFO] retrieved: 19
[14:36:45] [INFO] retrieved: top____es_c_stomers 13/19 (68%)

You can guess the db prefix is `top_sales` and the following word is `customers`.

**Describe alternatives you've considered**
Pretty much this

**Additional context**
There's some "universal" words in databases, such as "user"/"users", "ip_address" and such that could be easily extracted with this method.

**Comment by pak0s** [comment]
Have you tried `--predict-output'?

**Comment by stamparm** [comment]
yea, `--predict-output` should be THE switch, but still... users are trivializing the problem of bit inference. if you use a HUGE dictionary with lots of words, sqlmap won't be able to automagically faster things up. it could make some Markov chain (as in `--predict-output`), but it would still need to do LOTS of requests toward the target
