### ISSUE TITLE
POST PARAMETER MIGHT BE INJECTABLE BUT STILL CANT

### ISSUE THREAD

**Issue by WalterinoZ** [sqlmapproject/sqlmap#5471]
Hello, i dont know why it keep saying to use --level / --risk i but i did use it and still doesnt work

py sqlmap.py -u "http://xxxxxxxx/forpemain/LosagantiData(1).php" --cookie='PHPSESSIONID=hv9i5pir8ltom0t31qns6pvr3u' --data "exampleInputEmail1=omgwow@gmail.com&exampleInputname1=1&AboutIngpo=test" -p "exampleInputname1" --dbms "Microsoft SQL Server" --random-agent --level 5 --risk 3 --batch

i did test on his change bio data system, it showing this when you fill the exampleInputname1 form with ' < this symbol

Warning
: odbc_exec(): SQL error: [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near 'test'., SQL state 37000 in SQLExecDirect in
C:\xampp\htdocs\forpemain\LosagantiData(1).php
on line
63

**this text only show if you login:**
Warning: Undefined array key "exampleInputEmail1" in C:\xampp\htdocs\forpemain\LosagantiData(1).php on line 16
Warning: Undefined array key "exampleInputname1" in C:\xampp\htdocs\forpemain\LosagantiData(1).php on line 17
Warning: Undefined array key "AboutIngpo" in C:\xampp\htdocs\forpemain\LosagantiData(1).php on line 18

**this text/error only show if you not login:**
Warning: Undefined array key "username" in C:\xampp\htdocs\forpemain\LosagantiData(1).php on line 9
Warning: Undefined array key "exampleInputEmail1" in C:\xampp\htdocs\forpemain\LosagantiData(1).php on line 16
Warning: Undefined array key "exampleInputname1" in C:\xampp\htdocs\forpemain\LosagantiData(1).php on line 17
Warning: Undefined array key "AboutIngpo" in C:\xampp\htdocs\forpemain\LosagantiData(1).php on line 18

so what should i do to make it work from this vuln ? sorry if grammar sucks, thankyou!

**Comment by stamparm** [comment]
sql error is not a proof of SQL injection. you should manually assess the target and check whether SQLi exists in the first place (e.g. `1 AND 1=1`)
