### ISSUE TITLE
How to make SQLMAP keep the user-provided column names without adding backticks `column` to the query.

### ISSUE THREAD

**Issue by GhostKiller79** [sqlmapproject/sqlmap#5476]
When I want to dump data from columns id, username, phone, and password, SQLMAP always adds backticks ` ` to the password column, which unintentionally causes an error in the query. Is there any way to fix this?

![image](https://github.com/sqlmapproject/sqlmap/assets/130434339/cd4a3320-aa52-4e4d-b88d-9865888d2c57)

**Comment by stamparm** [comment]
that column name sneaked into the `keywords.txt`. try with latest revision
