### ISSUE TITLE
ASK, how to random header X-Forwarded-For?

### ISSUE THREAD

**Issue by ng4pw** [sqlmapproject/sqlmap#5480]
how to random ip using header X-Forwarded-For?
what command?

**Comment by ng4pw** [comment]
solved using this

`--eval='import random;X-Forwarded-For=X-Forwarded-For.replace(133713371337, ".".join(str(random.randint(0, 255)) for _ in range(4)))' `

**Comment by stamparm** [comment]
you also have `--tamper=xforwardedfor`
