### ISSUE TITLE
Use wordlists for initial guesses of database / table names during time-based SQL injections

### ISSUE THREAD

**Issue by beamjinn32704** [sqlmapproject/sqlmap#5482]
Recently the websites I've been (legally) using sqlmap on have required time-based blind SQL injections, and I've found that often times when sqlmap is trying to find the name of a database, table, or column name, it will go through the process of finding the name character by character, even though it's often apparent after a few characters are guessed that the name will be a common one like "usernames" or a default one like "information_schema" (which, having relatively longer names, can take sqlmap a while to find).

Due to this, I was wondering if it was possible to allow sqlmap to use wordlists (either by default or adding it as an option for a user to choose) of common database, table, and column names that sqlmap can guess before going through the long process of manually finding the strings it's looking for character by character.
Alternatively, instead of having sqlmap guess names using wordlists from the very beginning, sqlmap could instead guess a few characters of a name, find the names in a wordlist that match those initial characters, and guess those.

**Comment by stamparm** [comment]
do you know how sqlmap "finds" those names from the other side? if you think that it does character by character "guessing" then you are wrong. waiting for your reply

**Comment by stamparm** [comment]
to help you, it uses binary search. in binary search your idea is useless (i.e. in 6-7 requests sqlmap tries to find the current character). additionally, there were hundreds of **same idea** makers as yours in previous ten years
