### ISSUE TITLE
question about level flag

### ISSUE THREAD

**Issue by marcelo321** [sqlmapproject/sqlmap#5484]
lvl 2 flag tests for params and HTTP cookies, lvl 3 test for those and also user agent/referer.

Would it be possible to configure sqlmap to test parameters and user agent/referer? but avoiding http cookies? That's because some apps have a lot of cookies and would make the scans much slower, but I do want to scan for user agent and referer as those are only 2 added insertion points to scan.

In summary, would be possible to run flag 4 and 1, without including others below? is it something like that possible?

Maybe I am missing the point that each level increases also the test for every parameter and injection point. But I am not sure from the wiki or public videos out there.

edit: Something like `--level 2 --skip="cookies"` would work to add more test in the injection points, but to skip cookies testing?

**Comment by stamparm** [comment]
update to the latest revision and try to run with `--param-exclude=cookie`

**Comment by stamparm** [comment]
p.s. not **cookies** but **cookie**

**Comment by marcelo321** [comment]
so `sqlmap -u url --level 3 --param-exclude=cookie` would make sqlmap to not scan cookies, right?

**Comment by stamparm** [comment]
seems that `--skip=cookie` always worked, so there was no actual need for any patching (i made patch for `--param-exclude` which uses regular expressions for exclusion of parameters)
