### ISSUE TITLE
A way to add in a custom header to the CSFR-TOKEN request when using the --csfr-url option

### ISSUE THREAD

**Issue by DootMan** [sqlmapproject/sqlmap#5486]
I'm currently trying to bypass CSRF for a bug bounty, the site in question is using OWASP CSRFGuard. I can get SQLmap to request the CSRF token, but the site won't let me access the token without a specific header included in the request.

**Comment by stamparm** [comment]
you could try to use https://github.com/sqlmapproject/sqlmap/wiki/Usage#preprocess-request
