### ISSUE TITLE
base64

### ISSUE THREAD

**Issue by REtoolsx** [sqlmapproject/sqlmap#5488]
base64 detection not working

example request : 
GET /done?data=dGNraW1saWs9MTExMTExMTEmZmlyc3ROYW1lPWhha2slQzQlQjEmbGFzdE5hbWU9YWxrYW4mcGhvbmU9NTU1NTUmYmFua2lkPTEmdHJhbnNhY3Rpb25pZD0xMTExJmFtb3VudD0wMDAmdGltZW91dHBheT0xNjkxODY4MzA3JnNpdGVfaWQ9MCZyZXR1cm51cmw9aHR0cA== HTTP/2

my sqlmap command : sqlmap.py -r "req.txt" --level 3 --risk 3 -v 3 --force-ssl --base64=data

sqlmap version : 1.7.8.2
python : Python 3.9.7
os : windows & kali tested

**Comment by stamparm** [comment]
it detects it and injects inside, but it is not able to inject into separate parts of it (i.e. you have multiple parameters inside)

**Comment by REtoolsx** [comment]
> it detects it and injects inside, but it is not able to inject into separate parts of it (i.e. you have multiple parameters inside)


how can i do this, how can i do experiments according to the parameter i want

would something like this work?

custom injection *

base64 decoded :
tckimlik=11111111*&firstName=hakk%C4%B1&lastName=alkan&phone=55555&bankid=1&transactionid=1111&amount=000&timeoutpay=1691868307&site_id=0&returnurl=http

base64 encoded : 
dGNraW1saWs9MTExMTExMTEqJmZpcnN0TmFtZT1oYWtrJUM0JUIxJmxhc3ROYW1lPWFsa2FuJnBob25lPTU1NTU1JmJhbmtpZD0xJnRyYW5zYWN0aW9uaWQ9MTExMSZhbW91bnQ9MDAwJnRpbWVvdXRwYXk9MTY5MTg2ODMwNyZzaXRlX2lkPTAmcmV0dXJudXJsPWh0dHA=

Or I can enter data normally.

/done?data=tckimlik=11111111*&firstName=hakk%C4%B1&lastName=alkan&phone=55555&bankid=1&transactionid=1111&amount=000&timeoutpay=1691868307&site_id=0&returnurl=http

--tamper=base64encode


how can i run the test
Do you have any suggestions ?

**Comment by stamparm** [comment]
with latest revision you'll be able to put a single injection mark into that "pre-base64" encoded data, as you've tried in your first example in your previous message

**Comment by REtoolsx** [comment]
it worked.
