### ISSUE TITLE
There was an error detecting SQL injection with sqlmap

### ISSUE THREAD

**Issue by Mr-x2020** [sqlmapproject/sqlmap#5495]
With the help of an ACUNETix scanner, I found a SQL injection vulnerability. I tried to dump the database with SQLmap, but I couldn't. It took me three days to figure out why it wasn't detecting SQLi. I tried all SQLmap tampers and made up tampers, but they also didn't work.
So I decided to try another tool to dump DB called Ghauri and succeeded. In dumping the whole database.
Eventually, I found out that the problem was in sqlmap itself

![image](https://github.com/sqlmapproject/sqlmap/assets/65666323/b85e9165-bd84-4fe5-810d-3db449d7db72)

**Comment by stamparm** [comment]
duplicate of #5494
