### ISSUE TITLE
Is sqlmap dumping the database or not?

### ISSUE THREAD

**Issue by kuzan0** [sqlmapproject/sqlmap#5498]
Hello, I tried to dump the database, and get this result:

![ss-github](https://github.com/sqlmapproject/sqlmap/assets/142709443/e0c823fc-28d4-4419-af24-5f25194650c4)

I've had sqlmap running since yesterday, but no data retrieval appears on the terminal, only a time out.
Based on my experience, if the target site time out, the task will be stopped automatically after a few tries, but it didn't from yesterday running and i'm not using any - --retries, -ignore-timeouts, or --timeout options.

There are no WAF detected. I also had no trouble retrieving database, table, and column names. So the issue is only when dumping. The table has 1 million records, are these too large so sqlmap require more time to process, is that the case?

Sorry for my bad english.

Thank you.

**Comment by stamparm** [comment]
could be that the output is huge. nonetheless, sqlmap explicitly says that it will try "partial UNION technique", which should retrieve entries one by one

you can try to force partial UNION technique with:

1) `--force-partial` (<- hidden switch)
OR
2) try to set `--timeout` to some big value (e.g. `--timeout=3600`)
OR
3) try to force some non-UNION technique if there is one available to you (e.g. `--technique=E`)
