### ISSUE TITLE
Add --timer feature 

### ISSUE THREAD

**Issue by mIKEEE2023** [sqlmapproject/sqlmap#5502]
First of all lemme thank you for this awesome project.
Now, my problem is when I run bulk urls sometimes it get's stuck on url for long time (like 8 or 9 hours), and the reason is the delay between request is so high for example it tries one attack at 14:00 and the other one at 14:20 so usually it takes forever to complete.

I tried all kind of settings before like --time-sec --retries --technique, none of them worked.
my suggestion is to create a --timer feature to stop the app or go to next target after a  certain amount of time.

like --timer=20,next (go to next after checking for 20 minutes) or --timer=20,stop (close the program after 20 minutes).
It's easy to implement but it's pretty useful

**Comment by System88888** [comment]
长期大量收WebShell，联系🛩TG：@System88888

**Comment by stamparm** [comment]
`--time-limit=TIM..  Run with a time limit in seconds (e.g. 3600)`
