### ISSUE TITLE
base64 post

### ISSUE THREAD

**Issue by REtoolsx** [sqlmapproject/sqlmap#5504]
base64 post data

W3sibmFtZSI6InNpdGUtdXNlcm5hbWUiLCJ2YWx1ZSI6Ik5haG9zIn0seyJuYW1lIjoic2l0ZS1mdWxsbmFtZSIsInZhbHVlIjoiQW5vbnkifSx7Im5hbWUiOiJjYzMtaWRlbnRpdHkiLCJ2YWx1ZSI6IjExNDEifSx7Im5hbWUiOiJHYW1lciIsInZhbHVlIjoiMSJ9LHsibmFtZSI6InNpdGUtdXNlcklEIiwidmFsdWUiOiIyMDIzMDg1MTQ3ODc5In0seyJuYW1lIjoic2l0ZS1kYXRhIiwidmFsdWUiOiIifSx7Im5hbWUiOiJzaXRlLWxvZyIsInZhbHVlIjoiMTY1NjcxOTM5In0seyJuYW1lIjoic2l0ZS1kYyIsInZhbHVlIjoiMTIxIn0seyJuYW1lIjoic2l0ZS1yZXR1cm5VcmwiLCJ2YWx1ZSI6ImFIUjBjSE02THk5bllXMWxjbk4wZGk1amIyMHZkSEk9In1d

example of base64 post decoded form: 

 [{"name":"site-username","value":"Nahos"},{"name":"site-fullname","value":"Anony"},{"name":"cc3-identity","value":"1141"},{"name":"Gamer","value":"1"},{"name":"site-userID","value":"2023085147879"},{"name":"site-data","value":""},{"name":"site-log","value":"165671939"},{"name":"site-dc","value":"121"},{"name":"site-returnUrl","value":"aHR0cHM6Ly9nYW1lcnN0di5jb20vdHI="}]
 
 https://prnt.sc/9eNx6jRMCYSX

I have a base64 POST data, and I want to apply a custom injection to the value fields in this area, just like in this example. Can we implement this, please? Just like in this example: https://github.com/sqlmapproject/sqlmap/issues/5488

thank you

**Comment by stamparm** [comment]
when you say thank you that implies that somebody at the other side HAS to do something. in future gonna close this kind of requests (as you are just not giving me a chance to discuss the problem)

**Comment by stamparm** [comment]
![image](https://github.com/sqlmapproject/sqlmap/assets/921555/915bd3b8-70d3-45b0-b580-f1d95324787e)

![image](https://github.com/sqlmapproject/sqlmap/assets/921555/abcfd8a3-bb33-4a64-b697-101302b6840d)
