### ISSUE TITLE
Help !

### ISSUE THREAD

**Issue by houssxxtn** [sqlmapproject/sqlmap#5505]
Hi and thank you for the awesome project ,

im dealing with a target where the url look this

https://www.target.com/grid/index.php?params=0,8579,0,0,0,0,0,0,0,11101,0,0,0,0,2,1,0,0-0-0,0,0,100,0,0,0,0,0,0,0,1,1,0,3

each value of params is a parameter but they are all sent in one query , they are just seperated with a comma 

how to proceed with this , for example i want to scan params[1] and params[2]

thank you

**Comment by stamparm** [comment]
this is a special case. won't implement special support for it, as it would break other regular cases.

you can try to put a custom injection marker (`*`) at places where you would like sqlmap to try to inject
