### ISSUE TITLE
only test forms on the specified host

### ISSUE THREAD

**Issue by marcelo321** [sqlmapproject/sqlmap#5512]
Right now as I understand it, when providing the `--forms` flag, sqlmap will parse any form and test for sql injection. This can become an issue if the form is to another host that isn't really related to the host we are testing.

Would it be possible to test forms only on the host that is already scanning?

Would it be possible that if we are testing on webapp.com, that only scans forms on *.webapp.com? so all subdomains are accepted but anotherdomain.com isn't?

Let me know!

**Comment by stamparm** [comment]
it is already checking for the same host name. double checked in both code and in some dummy example i've done on my host
