### ISSUE TITLE
can not inject in user-agent

### ISSUE THREAD

**Issue by gjmhmm8** [sqlmapproject/sqlmap#5515]
select * from news where id=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.62

**Comment by stamparm** [comment]
i don't understand what's going on here. this looks like a poor/invalid way to show a SQL statement
