### ISSUE TITLE
Support for Informix

### ISSUE THREAD

**Issue by Wolftein** [sqlmapproject/sqlmap#552]
Add support for Informix [...ODBC Driver].

**Comment by fgeek** [comment]
Does someone have test instances, which I could use to create support for this?

**Comment by stamparm** [comment]
We have the same problem :)))

**Comment by stamparm** [comment]
https://www14.software.ibm.com/webapp/iwm/web/reg/download.do?source=swg-informixfpd&S_PKG=dl

**Comment by schrepfler** [comment]
What kind of things are needed for this to come into place a part of a test system?

**Comment by stamparm** [comment]
![a2](https://cloud.githubusercontent.com/assets/921555/18834434/1446a912-83f6-11e6-8f30-4ac6d765a861.png)
