### ISSUE TITLE
base64 post

### ISSUE THREAD

**Issue by REtoolsx** [sqlmapproject/sqlmap#5520]
https://github.com/sqlmapproject/sqlmap/issues/5504

I'm experiencing issues with sqlmap when it automatically sends base64 POST data. I have problems with quotation marks and OR SQL tests

example 

post base64decoded :

[{"name":"site-username","value":"Nahos"},{"name":"site-fullname","value":"Anony"},{"name":"cc3-identity","value":"1141"},{"name":"Gamer","value":"1"},{"name":"site-userID","value":"2023085147879"},{"name":"site-data","value":""},{"name":"site-log","value":"165671939"},{"name":"site-dc","value":"121"},{"name":"site-returnUrl","value":"aHR0cHM6Ly9nYW1lcnN0di5jb20vdHI="}]

base64encoded : 

W3sibmFtZSI6InNpdGUtdXNlcm5hbWUiLCJ2YWx1ZSI6Ik5haG9zIn0seyJuYW1lIjoic2l0ZS1mdWxsbmFtZSIsInZhbHVlIjoiQW5vbnkifSx7Im5hbWUiOiJjYzMtaWRlbnRpdHkiLCJ2YWx1ZSI6IjExNDEifSx7Im5hbWUiOiJHYW1lciIsInZhbHVlIjoiMSJ9LHsibmFtZSI6InNpdGUtdXNlcklEIiwidmFsdWUiOiIyMDIzMDg1MTQ3ODc5In0seyJuYW1lIjoic2l0ZS1kYXRhIiwidmFsdWUiOiIifSx7Im5hbWUiOiJzaXRlLWxvZyIsInZhbHVlIjoiMTY1NjcxOTM5In0seyJuYW1lIjoic2l0ZS1kYyIsInZhbHVlIjoiMTIxIn0seyJuYW1lIjoic2l0ZS1yZXR1cm5VcmwiLCJ2YWx1ZSI6ImFIUjBjSE02THk5bllXMWxjbk4wZGk1amIyMHZkSEk9In1d

request header :

Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: tr-TR,tr;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
 -----------------------------------------------------------------
response header :
Content-Type: text/html; charset=UTF-8
X-Powered-By: PHP/5.6.40
body:
 {"valid" : 0 , "validCode" : 10 , "validTitle" : "Hata var!" , "validMessage" : "Tüm alanların doldurulması zorunludur!" , "validClass" : "error"}
 
my sqlmap command :  used --data custom injection

sqlmap.py -u "example.com" --method=POST --data='[{"name":"site-username","value":"Nahos*"},{"name":"site-fullname","value":"Anony"},{"name":"cc3-identity","value":"1141"},{"name":"Gamer","value":"1"},{"name":"site-userID","value":"2023085147879"},{"name":"site-data","value":""},{"name":"site-log","value":"165671939"},{"name":"site-dc","value":"121"},{"name":"site-returnUrl","value":"aHR0cHM6Ly9nYW1lcnN0di5jb20vdHI="}]' --headers="User-Agent: mozilla/5.0 (windows nt 10.0; win64; x64; rv:109.0) gecko/20100101 firefox/117.0\nCookie: Cookie: _ga_J9MMBGFEYL=GS1.1.1693852773.18.0.1693852773.0.0.0; _ga=GA1.2.1815644791.1686354176; cf_clearance=v4FgztCv77k1h_QGqOKyx7pAxlb6ckIO7hBApM0Lo4c-1693852778-0-1-faf121e2.386d32c.adf07e02-0.2.1693852778; anothercookie=0fYSaoiQNqjZehsSZJwEq%2Bd6yzKt9ZTcGFOosWGMltC9amLux9OZqv8lIBrv44M8tUfQyq5b3EFUO64YHkd%2BUHj%2Fo6qrr47Skn0DR9Ry0S4%3D; _gid=GA1.2.55906791.1693852774;\nAccept: application/json, text/javascript, */*; q=0.01\nAccept-Language: tr-TR,tr;q=0.8,en-US;q=0.5,en;q=0.3\nAccept-Encoding: gzip, deflate, br\nContent-Type: application/x-www-form-urlencoded; charset=UTF-8\nX-Requested-With: XMLHttpRequest"  --level 3 --risk 3 -v 6 --force-ssl --dbms="MYSQL" --preprocess=base64prepro.py

request sent by sqlmap :
AND sql test
base64encoded:

JTI3JTVCJTdCbmFtZSUzQXNpdGUtdXNlcm5hbWUlMkN2YWx1ZSUzQU5haG9zJTI5JTI5JTIwQU5EJTIwMTMyOSUzRDI3MjklMjBBTkQlMjAlMjglMjgyNjEzJTNEMjYxMyU3RCUyQyU3Qm5hbWUlM0FzaXRlLWZ1bGxuYW1lJTJDdmFsdWUlM0FBbm9ueSU3RCUyQyU3Qm5hbWUlM0FjYzMtaWRlbnRpdHklMkN2YWx1ZSUzQTExNDElN0QlMkMlN0JuYW1lJTNBR2FtZXIlMkN2YWx1ZSUzQTElN0QlMkMlN0JuYW1lJTNBc2l0ZS11c2VySUQlMkN2YWx1ZSUzQTIwMjMwODUxNDc4NzklN0QlMkMlN0JuYW1lJTNBc2l0ZS1kYXRhJTJDdmFsdWUlM0ElN0QlMkMlN0JuYW1lJTNBc2l0ZS1sb2clMkN2YWx1ZSUzQTE2NTY3MTkzOSU3RCUyQyU3Qm5hbWUlM0FzaXRlLWRjJTJDdmFsdWUlM0ExMjElN0QlMkMlN0JuYW1lJTNBc2l0ZS1yZXR1cm5VcmwlMkN2YWx1ZSUzQWFIUjBjSE02THk5bllXMWxjbk4wZGk1amIyMHZkSEk9JTdEJTVEJTI3

base64decoded:
'[{name:site-username,value:Nahos))) AND 9644=9952 AND (((3474=3474},{name:site-fullname,value:Anony},{name:cc3-identity,value:1141},{name:Gamer,value:1},{name:site-userID,value:2023085147879},{name:site-data,value:},{name:site-log,value:165671939},{name:site-dc,value:121},{name:site-returnUrl,value:aHR0cHM6Ly9nYW1lcnN0di5jb20vdHI=}]'
-----------------------------------------------------------------------------

request sent by sqlmap :
OR sql test
base64encoded:

JTI3JTVCJTdCLTEyODMlMjklMjklMjBPUiUyMDg4ODQlM0Q0MjI2JTIwQU5EJTIwJTI4JTI4NjcwNiUzRDY3MDYlN0QlMkMlN0JuYW1lJTNBc2l0ZS1mdWxsbmFtZSUyQ3ZhbHVlJTNBQW5vbnklN0QlMkMlN0JuYW1lJTNBY2MzLWlkZW50aXR5JTJDdmFsdWUlM0ExMTQxJTdEJTJDJTdCbmFtZSUzQUdhbWVyJTJDdmFsdWUlM0ExJTdEJTJDJTdCbmFtZSUzQXNpdGUtdXNlcklEJTJDdmFsdWUlM0EyMDIzMDg1MTQ3ODc5JTdEJTJDJTdCbmFtZSUzQXNpdGUtZGF0YSUyQ3ZhbHVlJTNBJTdEJTJDJTdCbmFtZSUzQXNpdGUtbG9nJTJDdmFsdWUlM0ExNjU2NzE5MzklN0QlMkMlN0JuYW1lJTNBc2l0ZS1kYyUyQ3ZhbHVlJTNBMTIxJTdEJTJDJTdCbmFtZSUzQXNpdGUtcmV0dXJuVXJsJTJDdmFsdWUlM0FhSFIwY0hNNkx5OW5ZVzFsY25OMGRpNWpiMjB2ZEhJPSU3RCU1RCUyNw==

base64decoded:
'[{-1283)) OR 8884=4226 AND ((6706=6706},{name:site-fullname,value:Anony},{name:cc3-identity,value:1141},{name:Gamer,value:1},{name:site-userID,value:2023085147879},{name:site-data,value:},{name:site-log,value:165671939},{name:site-dc,value:121},{name:site-returnUrl,value:aHR0cHM6Ly9nYW1lcnN0di5jb20vdHI=}]'

"There are a total of 2 issues:

    There is an issue with the quotation marks at the beginning and the end, so I can't properly retrieve the response content.
        Screenshot for the 1st issue: https://prnt.sc/YeB-RI67_lYz

    During OR SQL tests, it exits from the custom injection test field.
        Screenshot for the 2nd issue: https://prnt.sc/tqP-vQPcWE9m"
        
 Could you help me to successfully perform a test?

**Comment by REtoolsx** [comment]
And I forgot to mention, the third issue is that --data=("-") (removes the double quotation marks within the data I provided)

**Comment by stamparm** [comment]
1) i don't see your base64prepro script. something is putting those quotes around and i don't see what it is
2) in future please fill the issue template properly

thank you

**Comment by REtoolsx** [comment]
> 1. i don't see your base64prepro script. something is putting those quotes around and i don't see what it is

base64prepro.py 

#!/usr/bin/env python

import base64

def preprocess(req):
    if req.data:
        req.data = base64.b64encode(req.data)
