### ISSUE TITLE
Error base code request add new injection code

### ISSUE THREAD

**Issue by justtrader2023** [sqlmapproject/sqlmap#5523]
can you add below error base checking bug in sqlmap 
as another application detect it on server i test but in sqlmap it don't detect them ever can u add please 

        "order": 1,
        "regex": REGEX_XPATH,
        "title": "MySQL >= 5.1 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (EXTRACTVALUE)",
        "payloads": [
            "AND EXTRACTVALUE(0,CONCAT(0x7e,0x72306f746833783439))",
            "AND EXTRACTVALUE(0,CONCAT_WS(0x28, 0x7e,0x72306f746833783439))",
        ],
    },

    {
        "back_end": "MySQL",
        "version": ">=5.1",
        "order": 3,
        "regex": REGEX_XPATH,
        "title": "MySQL >= 5.1 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (UPDATEXML)",
        "payloads": [
            "AND UPDATEXML(0,CONCAT(0x7e,0x72306f746833783439),0)",
            "AND UPDATEXML(0,CONCAT_WS(0x28, 0x7e,0x72306f746833783439),0)",

**Comment by stamparm** [comment]
i don't see the difference between those payloads and those already in https://github.com/sqlmapproject/sqlmap/blob/master/data/xml/payloads/error_based.xml. please invest some time in finding out what's happening in the first place (e.g. through inspection of traffic). here i have to play a guessing game
