### ISSUE TITLE
bad base64 post data 

### ISSUE THREAD

**Issue by REtoolsx** [sqlmapproject/sqlmap#5524]
```
1. While performing SQL tests, the --data(") removes the quotation marks from the data part in AND and OR tests.

2. In OR tests, it exits the custom injection area I specified and disrupts the structure.

3. When running the --data='(")' SQLmap data parameter, it continues to process the quotation marks at the beginning and end.
```
--------------------------------------------------------------------------------

> base64prepro.py : 
> #!/usr/bin/env python
> 
> import base64
> 
> def preprocess(req):
>     if req.data:
>         req.data = base64.b64encode(req.data)

---------------------------------------------------------------------------------

>  my sqlmap command :
>  sqlmap.py -u "example.com" --method=POST --data='[{"name":"site-username","value":"Nahos*"},{"name":"site-fullname","value":"Anony"},{"name":"cc3-identity","value":"1141"},{"name":"Gamer","value":"1"},{"name":"site-userID","value":"2023085147879"},{"name":"site-data","value":""},{"name":"site-log","value":"165671939"},{"name":"site-dc","value":"121"},{"name":"site-returnUrl","value":"aHR0cHM6Ly9nYW1lcnN0di5jb20vdHI="}]' --headers="User-Agent: mozilla/5.0 (windows nt 10.0; win64; x64; rv:109.0) gecko/20100101 firefox/117.0\nCookie: Cookie: _ga_J9MMBGFEYL=GS1.1.1693852773.18.0.1693852773.0.0.0; _ga=GA1.2.1815644791.1686354176; cf_clearance=v4FgztCv77k1h_QGqOKyx7pAxlb6ckIO7hBApM0Lo4c-1693852778-0-1-faf121e2.386d32c.adf07e02-0.2.1693852778; anothercookie=0fYSaoiQNqjZehsSZJwEq%2Bd6yzKt9ZTcGFOosWGMltC9amLux9OZqv8lIBrv44M8tUfQyq5b3EFUO64YHkd%2BUHj%2Fo6qrr47Skn0DR9Ry0S4%3D; _gid=GA1.2.55906791.1693852774;\nAccept: application/json, text/javascript, /; q=0.01\nAccept-Language: tr-TR,tr;q=0.8,en-US;q=0.5,en;q=0.3\nAccept-Encoding: gzip, deflate, br\nContent-Type: application/x-www-form-urlencoded; charset=UTF-8\nX-Requested-With: XMLHttpRequest" --level 3 --risk 3 -v 6 --force-ssl --dbms="MYSQL" --preprocess=base64prepro.py

------------------------------------------------------------------------------

 An example of a single AND query in SQLmap :
 https://prnt.sc/YeB-RI67_lYz
- Quotation marks are present at the beginning and end.
- Other double quotation marks (") within the query have been removed.
------------------------------------------------------------------------------

One example of an OR test in SQLmap :
https://prnt.sc/tqP-vQPcWE9m
-It has exited the area where I provided the custom injection point(*) and the OR queries have disrupted the structure
- Other double quotation marks (") within the query have been removed.
- Quotation marks are present at the beginning and end.

------------------------------------------------------------------------------

original request base64post data (decoded) :

[{"name":"site-username","value":"Nahos"},{"name":"site-fullname","value":"Anony"},{"name":"cc3-identity","value":"1141"},{"name":"Gamer","value":"1"},{"name":"site-userID","value":"2023085147879"},{"name":"site-data","value":""},{"name":"site-log","value":"165671939"},{"name":"site-dc","value":"121"},{"name":"site-returnUrl","value":"aHR0cHM6Ly9nYW1lcnN0di5jb20vdHI="}]

encoded: 

W3sibmFtZSI6InNpdGUtdXNlcm5hbWUiLCJ2YWx1ZSI6Ik5haG9zIn0seyJuYW1lIjoic2l0ZS1mdWxsbmFtZSIsInZhbHVlIjoiQW5vbnkifSx7Im5hbWUiOiJjYzMtaWRlbnRpdHkiLCJ2YWx1ZSI6IjExNDEifSx7Im5hbWUiOiJHYW1lciIsInZhbHVlIjoiMSJ9LHsibmFtZSI6InNpdGUtdXNlcklEIiwidmFsdWUiOiIyMDIzMDg1MTQ3ODc5In0seyJuYW1lIjoic2l0ZS1kYXRhIiwidmFsdWUiOiIifSx7Im5hbWUiOiJzaXRlLWxvZyIsInZhbHVlIjoiMTY1NjcxOTM5In0seyJuYW1lIjoic2l0ZS1kYyIsInZhbHVlIjoiMTIxIn0seyJuYW1lIjoic2l0ZS1yZXR1cm5VcmwiLCJ2YWx1ZSI6ImFIUjBjSE02THk5bllXMWxjbk4wZGk1amIyMHZkSEk9In1d

Okay, I understand. No thanks will be given until the issue is resolved. Please remain calm,
I hope this time, I have prepared it properly.

**Comment by stamparm** [comment]
not in a mood. thank you for you thank you. please don't open any more issues because of shitty remarks as `No thanks will be given until the issue is resolved`

blocking you for smirky behaviour

**Comment by stamparm** [comment]
thank for your understanding. i have tolerance for smug people like yourself.

everything containing Base64 inside issue texts in the following month, even from different user will just be deleted/ignored/closed

thank you man. byez
