### ISSUE TITLE
[!] wrong installation detected (missing modules). Visit 'https://github.com/sqlmapproject/sqlmap/#installation' for further details

### ISSUE THREAD

**Issue by hayasugihayato** [sqlmapproject/sqlmap#5528]
**Describe the bug**
I can not run Sqlmap on Windows 11 with Python  3.8.10.

**To Reproduce**
1. Run 'python sqlmap.py'
2. See error

**Running environment:**
 - sqlmap version [1.7.9.2#dev]
 - Installation method [git clone]
 - Operating system: [Microsoft Windows 11 22621.2134]
 - Python version [3.8.10]

**Additional context**
My friend and I can not run Sqlmap on Windows 11, but it can work on Windows Server 2016 Datacenter(Python 3.8.6).

**Comment by System88888** [comment]
长期大量收WebShell，联系🛩TG：@System88888
​

**Comment by stamparm** [comment]
as an error message says, your python installation is faulty. regular modules are missing. try to go to python downloads page and download some other version. uninstall old version and install new one

**Comment by arccos324** [comment]
> as an error message says, your python installation is faulty. regular modules are missing. try to go to python downloads page and download some other version. uninstall old version and install new one

Sorry to bother you. I use Win11 with python3.13.3 which is the latest version I can download on www.python.org but I still encountered the same problem. It says "[!] wrong installation detected (missing modules). Visit 'https://github.com/sqlmapproject/sqlmap/#installation' for further details."

**Comment by stamparm** [comment]
@arccos324 that error is happening when basic files of sqlmap are missing. to be more precise, this [file](https://github.com/sqlmapproject/sqlmap/blob/master/lib/utils/versioncheck.py) is missing from your installation, which means that most probably other files are missing too. other problem could be the bad python installation, where python is not able to properly use the main directory of the program (`sqlmap`) as the main point for all the imports (<- that's not normal python behavior)

**Comment by arccos324** [comment]
Thanks a lot.






-rwx-
***@***.***






---Original---
From: "Miroslav ***@***.***&gt;
Date: Sun, Apr 27, 2025 04:24 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [sqlmapproject/sqlmap] [!] wrong installation detected (missingmodules). Visit 'https://github.com/sqlmapproject/sqlmap/#installation' forfurther details (Issue #5528)


 stamparm left a comment (sqlmapproject/sqlmap#5528)
 
@arccos324 that error is happening when basic files of sqlmap are missing. to be more precise, this file is missing from your installation, which means that most probably other files are missing too. other problem could be the bad python installation, where python is not able to properly use the main directory of the program (sqlmap) as the main point for all the imports (<- that's not normal python behavior)
