### ISSUE TITLE
How to test websocket ? ( wss ) 

### ISSUE THREAD

**Issue by iamyates** [sqlmapproject/sqlmap#5530]
**Is your feature request related to a problem? Please describe.**
How  to test websocket endpoint? I checked the doc and found no result. 

I checked the source code, and the history prs, there are websocket related PRs. 

**Describe the solution you'd like**
Give an example how to test websocket endpoint.

**Describe alternatives you've considered**
If sqlmap not support websocket, I would like to create a proxy to do that. ( convert ws to http service )

**Additional context**

**Comment by System88888** [comment]
长期大量收WebShell，联系🛩TG：@System88888

**Comment by stamparm** [comment]
it should be similar to regular URL usage, like: `python sqlmap.py -u wss://foobar.com`. have you tried it?
