### ISSUE TITLE
How can I query the number of times a taskid has been scanned? 

### ISSUE THREAD

**Issue by HuiJing-C** [sqlmapproject/sqlmap#5532]
Because there is a requirement to calculate the number of scans per task, but I can only find usage methods such as how to create and view tasks

**How can I query the number of times a taskid has been scanned?** For example, I would like to know how many shooting ranges have been tested for the task with taskid=123

**Comment by HuiJing-C** [comment]
I have found a way now to call the scan/taskid/log, retrieve the logs, and extract the actual scan logs from them. However, I am unable to determine which ones are the actual scan logs. Is it a log that starts with **testing**?

**Comment by stamparm** [comment]
sqlmapapi's task id has not be meant to be run multiple times for different scans. this won't be change (for your case)
