### ISSUE TITLE
SQLMap  will not run in parallel regardless of the --threads flag

### ISSUE THREAD

**Issue by vijayee** [sqlmapproject/sqlmap#5534]
**Describe the bug**
I cannot get sqlmap to send requests in parallel. They run sequentially no matter what I set the thread count to be. 

**To Reproduce**
1. Run `python3 sqlmap.py --drop-set-cookie --time-sec=60, --timeout=90 --level=5 --risk=3 --threads=8 -p username,password -u http://localhost:3000/?username=absolom&password=chinchilla -method POST`

**Expected behavior**
I would expect that with a `--threads` flag greater than 1 multiple http requests would be sent in parallel

**Running environment:**
 - sqlmap version 1.7.6
 - Installation method git clone
 - Operating system: Ubuntu 22.04
 - Python version 3.10.4

**Comment by stamparm** [comment]
you just skipped the issue template. now, we are playing guessing game. i don't know anything about your case (e.g. which SQLi techniques are usable)
