### ISSUE TITLE
Redirect should stay in domain scope in -batch mode

### ISSUE THREAD

**Issue by Loqova** [sqlmapproject/sqlmap#5536]
When using the `-batch` option in SQLmap it should stay at least in the domain scope. I noticed that when my domain redirects (302) to for example some Azure or other (third party) domain, it shouldn't proceed but however answers yes to all following requests.

It could be as simple as checking if the whole URL part before the first path `/` is the same. Or at least an (default) option should be to stay in the domain scope or to even define a domain scope such as `--scope=www.example.com`, `--scope=www.example.com,test.example.com` or `--scope=*.example.com`

**Comment by stamparm** [comment]
it should work now. though, `--scope` accepts only regular expressions (something like `--scope=target.com` should be fine)
