### ISSUE TITLE
Option to use sitemaps (and crawling) in -batch mode

### ISSUE THREAD

**Issue by Loqova** [sqlmapproject/sqlmap#5537]
In batch mode the following question `do you want to check for the existence of site's sitemap(.xml) [y/N]` is answered with no. However, I would like an option to answer yes to this question in batch mode. Also, I would like to do this **in addition to** crawling. So not, in favor of crawling when enabled.

**Comment by U53RW4R3** [comment]
This isn't a bug. There's a feature for that. Use `--batch --answers=sitemap=Y`. This will help you to automate the issue you're having. Always refer to the manual.

**Comment by stamparm** [comment]
thx @U53RW4R3
