### ISSUE TITLE
I have some doubts when looking at the source code of tamper’s space2comment.py

### ISSUE THREAD

**Issue by Decemberus** [sqlmapproject/sqlmap#5538]
When I read the source code, I come across a problem I want to solve. What is the use of setting a firstspace variable when I comment out the code related to firstspace without affecting the associated output
In space2comment.py , 
```
            if not firstspace:
                if payload[i].isspace():
                    firstspace = True
                    retVal += "/**/"
                    continue
```
I don't understand what the "firstspace" variable means

**Comment by stamparm** [comment]
up to "firstpace", no single nor double quotes are being checked for (e.g. line `elif payload[i] == '"'` is skipped up to firstspace). "firstspace" is a dummy indicator that we are outside the user variable space, inside a SQL. then afterwards, checking for quotes is extremely important

it is dumb, and prone to errors (e.g. if the original value has space inside), but works in 99% of cases

**Comment by Decemberus** [comment]
Many thanks for your replying
