### ISSUE TITLE
Can the blind sqlmap algorithm search for characters by equality comparison?

### ISSUE THREAD

**Issue by 0xdu** [sqlmapproject/sqlmap#5543]
The current blind algorithm is binary search. It use operator `<` or `>`  to find character. In some cases, the `>` character is filtered, which causes blind sqlmap to not work. It will work if using equality comparison.

For example  application filter character `>`: 
- the inject query: `unicode('a') > 64`. After filter, the query is `unicode('a')  64`, and this query is syntax error.
- If the inject query: `unicode('a') = 97`. After filter, the query is `unicode('a')  = 97` and it is oke.

So, Can the blind algorithm support search for characters by equality comparison?

**Comment by stamparm** [comment]
for those cases you should use `--tamper=between`. i also believe that you are warned by sqlmap to use this in such cases
