### ISSUE TITLE
 subprocess.Popen中定义 stdin 似乎与我的-r 请求命令相互冲突

### ISSUE THREAD

**Issue by zasufe** [sqlmapproject/sqlmap#5545]
**Describe the bug**
sqlmap  1.7 stable
python3.10.10
我尝试用以下代码 用来执行sqlmap 注入命令

def run(self, cmd):
        process = subprocess.Popen(cmd,
                                   stdout=subprocess.PIPE,
                                   stderr=subprocess.PIPE,
                                   # stdin=subprocess.PIPE,
                                   encoding='utf-8',
                                   universal_newlines=True)
        set_fd_nonblocking(process.stdout.fileno())
        set_fd_nonblocking(process.stderr.fileno())
        Thread(target=self.stdout, args=(process,), daemon=False).start()
        Thread(target=self.stderr, args=(process,), daemon=False).start()

**To Reproduce**
我的测试命令是
   command = ['python3', '/home/tools/sqlmap.py', '-r',  '/home/a.txt']
![image](https://github.com/sqlmapproject/sqlmap/assets/49631859/f4c3facc-c47b-4089-a1a1-e3c84bd027a8)
如果不带
**Expected behavior**
我遇到的问题是：
1.如果Popen里包含了stdin=subprocess.PIPE，程序就永远卡在   [INFO] using 'STDIN' for parsing targets list
2.如果#stdin=subprocess.PIPE  不定义stdin， 可以运行，但是确提示要终端输入交互内容
![image](https://github.com/sqlmapproject/sqlmap/assets/49631859/81b3abbe-a0a4-4e70-891b-ac1a3c5d24ce)

我的困难是 我程序封装在docker 里，不定义 stdin  我没有办法输入内容，有没有什么解决方案

**Comment by stamparm** [comment]
use (hidden) switch `--ignore-stdin`
