### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Pengyuan-yue** [sqlmapproject/sqlmap#5559]
[!] wrong installation detected (missing modules). Visit 'https://github.com/sqlmapproject/sqlmap/#installation' for further details
这个东西怎么解决，windows 10环境，python 3.11

**Comment by stamparm** [comment]
whole directory structure or a runtime is simply wrong. you should have something like directory `sqlmap` with the whole content of the https://github.com/sqlmapproject/sqlmap.

in your case, a basic module `lib.utils.versioncheck` is just not there

download https://github.com/sqlmapproject/sqlmap/zipball/master, unzip, change directory to embedded sqlmap directory and run sqlmap from within

**Comment by Pengyuan-yue** [comment]
thanks a lot
