### ISSUE TITLE
HOW TO INJECT IN HEADER IF THE HEADER VALUE IS BASE 64 

### ISSUE THREAD

**Issue by sabir789** [sqlmapproject/sqlmap#5564]
HI,
    I am trying to inject in header but i am field please first see the request you will be understand 

GET / HTTP/1.1
Host: example.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0
Authorization: Basic YWRtaW46YWRtaW4=

i want to inject in "Authorization: Basic YWRtaW46YWRtaW4=" header 
this is the value of Authorization basic header "YWRtaW46YWRtaW4=" if i decode this it will be looking like this username:password

the first is username input the second is password input which i give him through UI mean in browser.

PLZ answer to this when you have free time.

THANKS,

**Comment by stamparm** [comment]
sorry, but currently there is no easy way to do this. also, at this moment there won't be an implementation to support this as I don't see it as something used by more than 1 person
