### ISSUE TITLE
Please support SQL injection for openGauss database

### ISSUE THREAD

**Issue by VBPush** [sqlmapproject/sqlmap#5571]
**Describe the solution you'd like**
Please support SQL injection for openGauss database.

openGauss:
https://opengauss.org/en/download/

**Comment by stamparm** [comment]
Not easy to install and have an usable connector (i.e. way to inject into this DBMS from web app or similar).

Anyhow, installed it in Docker, tried all PostgreSQL queries and concluded that this one should be supported out of the box. Just made some cosmetic changes with the last commit
