### ISSUE TITLE
sometime sqlmap payload not worked in request

### ISSUE THREAD

**Issue by Deep0** [sqlmapproject/sqlmap#5575]
**Describe the bug**
the payload can't inject the request body.
**To Reproduce**
for example , run sqlmap -r sql.txt 
then, look the proxy request ,the body not have the payload  in some request.

**Running environment:**
 - sqlmap version [ 1.7.11.3#dev]
 - Installation method [git]
 - Operating system: [Mac M1]
 - Python version [3.11.2]

**Target details:**
 - DBMS [Oracle]
 - SQLi techniques found by sqlmap [ time-based and boolean-based blind]

**Additional context**
So,emm, i don't know how can i take it.

**Comment by stamparm** [comment]
so, playing a guessing game. will pass
