### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by Bebekburn** [sqlmapproject/sqlmap#5581]
Hi there is a virus in the plugin dbms msssqlserver in filesystem.py, so i can't donwload when my antivirus is on. So what solution can you help with? Thankyou

**Comment by stamparm** [comment]
there is no virus inside. AV vendors started to mark sqlmap python files as "sqlinject":

![image](https://github.com/sqlmapproject/sqlmap/assets/921555/9e67c76c-d4df-40a2-9b0b-605b77f5c2de)

**Comment by stamparm** [comment]
interestingly, there are not many similar cases:

![image](https://github.com/sqlmapproject/sqlmap/assets/921555/c0c0fadf-0e17-41f7-94c2-487b5b1627ae)

**Comment by stamparm** [comment]
with the latest revision this should be "patched":

![image](https://github.com/sqlmapproject/sqlmap/assets/921555/359f4eb8-8778-442e-bcbb-bdd927f32eda)
