### ISSUE TITLE
Sqlmap invalid syntax error

### ISSUE THREAD

**Issue by leighp20** [sqlmapproject/sqlmap#5583]
**Describe the bug**
Sqlmap invalid syntax error

**To Reproduce**
sqlmap --tamper so-tamper.py --url http://TARGET_MACHINE:5000/challenge4/signup --data "username=admin&password=asd"

**Expected behavior**
For the script to run

**Screenshots**
![sqlmap20](https://github.com/sqlmapproject/sqlmap/assets/106348626/26fb41b2-14f9-405a-89c2-5bea577045fb)

**From tryhackme room SQL Injection Lab Task 7**

**Comment by stamparm** [comment]
first time to hear about "so-tamper". not part of regular tamper scripts
