### ISSUE TITLE
Accept suggestions from user for faster guessing instead of plane bruteforce

### ISSUE THREAD

**Issue by Amit0617** [sqlmapproject/sqlmap#5589]
**Is your feature request related to a problem? Please describe.**
Whenever `--dump` is requested it takes a **lot of time** to find each letter of a word that's very obvious given the blind guesswork.

**Describe the solution you'd like**
I want that - user can suggest letters from the context of the website or just what a word could be from the initial few letters then it just has to verify the user's suggestion.
For example, the following is an example of CTF where in the last line of the image I was able to guess that it would be "Utterly adorable" from the context of the website just after "Utte" part shown on screen.
![2023-12-23_22-37](https://github.com/sqlmapproject/sqlmap/assets/71893015/ea6990ab-0536-432a-bd7d-b077a76bf2f7)
but I was required to wait until it guessed all of that itself.
**Describe alternatives you've considered**
Probably, a more high-tech solution could be that it makes use of AI to guess the word itself (like Gboard in the Android does) and verifies whether they are correct or wrong(instead of just bruteforcing).

**Comment by blackboxbandit** [comment]
Have you tried
` --predict-output` and fill the `txt/common-outputs.txt `with common output

**Comment by Amit0617** [comment]
I was particularly asking for the case when it is already running.
I guess having a `txt` file with just all English dictionary words can help.

**Comment by stamparm** [comment]
this is like 20th request in 10 years for the same feature. not new idea. python doesn't have the mechanism (for all OS-es) to run and wait for the user input.

p.s. also, you just think that this would go in such easy way (as you would need to press the key at the exactly precise moment and sqlmap would need to validate all those chars)
