### ISSUE TITLE
sqlmap --update something wrong problem

### ISSUE THREAD

**Issue by exp0l0zzz** [sqlmapproject/sqlmap#5595]
Recently, I have noticed that the update function of sqlmap will delete all sqlmap files in the current folder after interruption, which is very painful for situations where backups are not made in a timely manner。

**Comment by stamparm** [comment]
current folder? `sqlmap --update`? missing lots of information. not sure what's the issue here

**Comment by exp0l0zzz** [comment]
In Windows system, you can try adding multiple files to the sqlmap folder and perform sqlmap -- upload. After a while, if you interrupt, you will find that the folder will be completely emptied, which is unreasonable

**Comment by stamparm** [comment]
doesn't make sense why would you interrupt the update process. in all systems and programs ever, you are implicitly/explicitly warned to not disrupt the "updates"

**Comment by exp0l0zzz** [comment]
> 没有意义为什么要中断更新过程。在所有系统和程序中，都会隐式/明确警告您不要破坏“更新”

Moreover, sometimes when I test, I generate data package files in the folder, which can damage my data files

**Comment by stamparm** [comment]
1) sqlmap should not be storing anything inside `sqlmap` folder that is not code
2) it is always choosing some user directory
3) that being said, you are most probably doing something really wrong
