### ISSUE TITLE
About SQL injection under special circumstances

### ISSUE THREAD

**Issue by Baikeryoyo** [sqlmapproject/sqlmap#5600]
In special cases, passing parameters is directly using SQL statements through specific parameters.
Taking a CVE as an example, its payload is as follows:
```
filter_tag=1%29%22+union%09select * from (select 123)a1 join (select 2)a2 join (select 3)a3 join (select 2)a4 join (select 2)a5 join (select 2)a6 join ( select database())a7 join (select 2)a8 join (select 2)a9 join (select 2)a10 join (select 2)a11 join (select 2)a12 join (select 2)a13 join (select 2)a14 join ( select 2)a15 join (select 2)a16 join (select user())a17 join (select 2)a18 join (select user())a19 join (select 123)a20 join (select 2)a21 join (select 2)a22 join(select 2)a23%23
```
In fact, when reproducing it, I found that many CVEs have similar situations. Most of them are included in specific statements or parameters, and this special payload cannot be directly tested to the injection point through sqlmap. For this reason, I I checked the wiki documents and searched a lot on Google, but I couldn't solve this problem.
It is not difficult for us to find that it contains select user() with specific parameters. In fact, this [select user()] is what I want to put in sqlmap.
But sqlmap will only test on 1 with filter_tag=1
Even if --prefix and --suffix are added, it is difficult to solve various complex problems in the actual environment.
Many times, I have constructed the payload and hope to use sqlmap to automatically fill in various statements for sqlmap utilization.
Therefore, I hope sqlmap can add similar parameters,
You can customize the payload settings, and then sqlmap fills in the corresponding statements to complete various operations.

**Comment by stamparm** [comment]
sorry, but this is junk. if you need to use such exotic payloads, maybe something else is being done here (e.g. bypass of WAF) or smth. exotic payloads are usable for automation in exactly 0.01% of cases
