### ISSUE TITLE
Issue with generated payload

### ISSUE THREAD

**Issue by us4g1** [sqlmapproject/sqlmap#5605]
**Describe the bug**
Contains an extra %, when the payload is tested it doesn't work

**To Reproduce**
1.  `sqlmap -u 'http://localhost:3000/rest/user/login' --data="email=admin@juice-sh.op&password=test" --level 5 --risk 3 -f --banner --ignore-code 401 --dbms='sqlite'`
2.  Output: `Payload: email=admin@juice-sh.op%' OR NOT 3179=3179-- nTJX&password=test`

**Expected behavior**
Output: `Payload: email=admin@juice-sh.op' OR NOT 3179=3179-- nTJX&password=test`
Expected output to be without the %

**Running environment:**
 - sqlmap version: 1.8.1.4#dev
 - Installation method [e.g. pip]
 - Win11 WSL2
 - Python 3.10.12

**Target details:**
 - SQLITE JUICESHOP
 - SQLi techniques found by sqlmap: boolean-based blind

**Additional context**
Trying to solve the juiceshop login page challenge with sqlmap, I do not understand why the generated payload has the %, it works without it. When I use a different email e.g email=admin@juice-sh.dn it doesn't have the %, why is this the case?

**Comment by stamparm** [comment]
not sure if this is a joke. that's just one of many payloads being sent:

![image](https://github.com/sqlmapproject/sqlmap/assets/921555/5ecba4b7-00f9-40d2-ae53-d5cd893c2709)

please don't open this kind of issues any more
