### ISSUE TITLE
sqlmap dumping into csv in the wrong order

### ISSUE THREAD

**Issue by us4g1** [sqlmapproject/sqlmap#5606]
**Describe the bug**
This is tested with juiceshop v16
The things retrieved by sqlmap is correct but in the wrong order
Screenshot of juiceshop.sqlite
![image](https://github.com/sqlmapproject/sqlmap/assets/156511161/ed5ca034-7e81-48db-8a66-880bcd68a6cb)
Screenshot of the csv generated by sqlmap
![image](https://github.com/sqlmapproject/sqlmap/assets/156511161/612f09f9-b3db-47a9-99f1-41229545fcb4)

**To Reproduce**
1. Run 'python3 sqlmap.py -u 'http://localhost:3000/rest/user/login' --data="email=test@test.com&password=test" --level 5 --risk 3 -f --banner --ignore-code 401 --dbms='sqlite' --technique=B -T Users  -dump --fresh-queries --batch'

**Running environment:**
 - sqlmap version: 1.8.1.4#dev and 1.8 #stable
 - Win11 WSL2
 - Python 3.10.12

**Target details:**
 - DBMS: sqlite  3.44.2
 - SQLi techniques found by sqlmap [boolean-based blind]

**Comment by stamparm** [comment]
so, you opened https://github.com/sqlmapproject/sqlmap/issues/5605, SQLi automagically worked, and you left that issue opened??

there is no "correct order" in table dumps. sqlmap retrieves entries as DBMS gives them back, without any particular order

**Comment by smolbun** [comment]
Its not an issue with sqlite browser, have a look at the csv generated from sqlmap. For admin, the id, password..etc is wrong, the data does not correlate at all.

**Comment by smolbun** [comment]
Correct me if I'm wrong, but the row for the admin user does not correlate to it's id ,role ,password..etc.

**Comment by stamparm** [comment]
aha. you were not clear in your issue text. column values do not correlate between each other in rows.

have you been asked during the run whether you want to use `ORDER BY` ???

**Comment by stamparm** [comment]
also, i am missing which techniques were available (you skipped the template questions)
