### ISSUE TITLE
Does it support the use of "python 3.12"

### ISSUE THREAD

**Issue by Ms-yin** [sqlmapproject/sqlmap#5610]
When I use Python 11, I can start sqlmap; But when I use Python 12, it prompts "wrong installation detected (missing modules). Visit" https://github.com/sqlmapproject/sqlmap/#installation "For further details"

![1705463979215](https://github.com/sqlmapproject/sqlmap/assets/102912352/ff7aae25-04c4-4712-bff4-202293b42b50)

**Comment by stamparm** [comment]
![image](https://github.com/sqlmapproject/sqlmap/assets/921555/a4ac798f-95d1-4a2e-a539-11086db434ff)
