### ISSUE TITLE
Cannot stablish a direct connection; using authentication with password, but sqlmap returns "(using password: NO)"

### ISSUE THREAD

**Issue by pintoferreira** [sqlmapproject/sqlmap#5612]
**Describe the bug**

I'm trying to use sqlmap (a wonderful tool, by the way) with -d in order to access a certain MySQL database. I followed the correct order of the variables, including the password, but sqlmap doesn't authenticate and seems to not being able to recognize that the user (i.e, me) is using password. How to fix this?

**To Reproduce**
1. Run 'python3 sqlmap.py -u 'mysql://user:pass@host:port/database''
2. See error: "[CRITICAL] SQLAlchemy connection issue ('OperationalError: (MySQLdb.OperationalError) (1045, "Access denied for user 'username'@'host' (**using password: NO**)")')"

**Expected behavior**
I should have access to the database, and then execute other sqlmap commands.

**Running environment:**
 - sqlmap version: 1.7.9.2#dev
 - Installation method: git clone https://github.com/sqlmapproject/sqlmap.git
 - Operating system: Mint
 - Python version: 3.10.12

**Target details:**
 - DBMS: MySQL

**Comment by stamparm** [comment]
i think that you used double quotes, along with `$...` in password. this expands to empty string value

try to use single quotes instead

also, try to use `echo python sqlmap.py -d ...` to see exactly what is passed to the sqlmap from your arguments
