### ISSUE TITLE
[Improvement] - Add option to inject into parameters if parameter is encoded in base64

### ISSUE THREAD

**Issue by ggt** [sqlmapproject/sqlmap#5622]
**Is your feature request related to a problem? Please describe.**
No

Hi, it should be cool to inject into parameters if they are encoded into base64 and content type of:

- Parameters and values
- Json
- Arrays
- Urls

Thanks!

**Comment by Mengter8** [comment]
good

**Comment by ggt** [comment]
I know but this should be by default in the scan of parameter is base64
encoded.

**Comment by stamparm** [comment]
too general request. also, you haven't inspected the current capabilities (e.g. https://github.com/sqlmapproject/sqlmap/issues/4137)
