### ISSUE TITLE
How to use the port in the request packet when SQLMAP performs testing connection to the target URL probe？

### ISSUE THREAD

**Issue by VBPush** [sqlmapproject/sqlmap#5623]
**Describe the bug**
Why does SQLMAP not use the specified port in the request packet when performing a site probe operation?

**To Reproduce**
1. For example, if I call a POST request packet with the -r parameter, the structure looks like this:
**-----------------------**
POST /xxxxx HTTP/1.1
Content-Type: text/html
Host: 127.0.0.1:9988

key=1*
**-----------------------**

2.The default SQL injection probe is performed on the request package(--current-db --batch)

3.After execution, a 404 error was returned during the "testing connection to the target URL" operation, and the request was captured through the proxy parameter. It was found that the probe request packet did not carry the port carried in my request packet (9988 in the example above), so the system could not be accessed normally

**Expected behavior**
When you perform the "testing connection to the target URL" operation, you can carry a valid port for detection.

**Screenshots**
![image](https://github.com/sqlmapproject/sqlmap/assets/140361823/a496ff3d-6881-462e-a425-8b91c44c048c)
![image](https://github.com/sqlmapproject/sqlmap/assets/140361823/3a674d20-0bbc-4fa8-ae1e-afcecd27f9a0)

**Running environment:**
 - sqlmap version [e.g. 1.8#stable]
 - Installation method [e.g. github]
 - Operating system: [e.g. Microsoft Windows 11]
 - Python version [e.g. 3.11.2]

**Additional context**
This error does not occur when converting the POST request packet into a test request of the form [-u "http://x.x.x.x:port" --data "key=1* "].

**Comment by stamparm** [comment]
not able to reproduce. testing connection goes to the valid port in my tests:

![image](https://github.com/sqlmapproject/sqlmap/assets/921555/e198643a-98ac-4202-ab4c-4da9f4be3420)
