### ISSUE TITLE
all tested parameters do not appear to be injectable. Try to increase values for '--level'/'--risk'

### ISSUE THREAD

**Issue by hammadiqbal189** [sqlmapproject/sqlmap#5634]
Hello,
I Faceing this issue in Sqlmap in kali linux. I am learing from tutorial but got this error
`sqlmap -u 'https://192.168.1.105/assets/presets/default/css/color.php?color=20c986&secondColor=575AEC' --dbs --dump --batch`

> all tested parameters do not appear to be injectable. Try to increase values for '--level'/'--risk' options if you wish to perform more tests. If you suspect that there is some kind of protection mechanism involved (e.g. WAF) maybe you could try to use option '--tamper' (e.g. '--tamper=space2comment') and/or switch '--random-agent'

What is my problem? or this is bug

Thank you.

**Comment by stamparm** [comment]
maybe there is no SQL injection? not sure why are you opening issues here if you haven't done a proper debugging/testing
