### ISSUE TITLE
A Payload was detected but an error was reported indicating that the database could not be recognized.

### ISSUE THREAD

**Issue by VBPush** [sqlmapproject/sqlmap#5639]
Hello author, I had a problem while testing with the latest version of SQLMAP(1.8#stable).
As shown in the following figure, why SQLMAP, after running an injectable Payload, reports an error [sqlmap was not able to fingerprint the back-end database management system] and exits?

![image](https://github.com/sqlmapproject/sqlmap/assets/140361823/9cfeef36-ddf7-4649-85af-3c7deb5a7fef)

I retest the payload, in the form of request packets, to make sure that delayed injection can be triggered normally.

**Comment by stamparm** [comment]
either A) false positive, thus, rerun with `--flush-session` OR B) you have some WAF/filter in between

you should be suspicious with cases with ONLY stacked queries (or generally payloads with time delays)

try to properly debug what's going (e.g. try to manually use propose payloads) on and report back
