### ISSUE TITLE
Ignored exception in thirdparty.colorama

### ISSUE THREAD

**Issue by kobyan** [sqlmapproject/sqlmap#5642]
**Describe the bug**
Hello!
I came across a bug where sqlmap stops working.
This is most likely due to the Code Page of console.
With the default Code Page, sqlmap works correctly, but the passed parameters are perceived as unreadable characters.
To avoid this, I changed the Code Page to UTF-8 (chcp 65001). After this, sqlmap began to interrupt.
The last message that is shown in the logs is
```
[02:24:27] [WARNING] you provided 'Exception ignored in: <thirdparty.colorama.ansitowin32.StreamWrapper object at 0x000000EAB9699070>
PermissionError:
```
**To Reproduce**
1. Run
```
 chcp 65001
sqlmap.py --url="<url>" -p <param> --level=5 --risk=3 --technique=BEU --threads=1 --drop-set-cookie -v 3 --beep --exclude-sysdb --os-shell --random-agent --schema --proxy="socks5://127.0.0.1:9150" --dbms="MySQL" --union-cols=5 --tamper="unionalltounion.py,randomcase+schema.py" --string="<string in UTF-8>" --delay=17 --no-logging
```
2. See error

**Screenshots**
![image](https://github.com/sqlmapproject/sqlmap/assets/23655860/d070f750-d631-492a-83b1-a9ef40bd7cbb)

**Running environment:**
 - sqlmap version 1.8.2.1
 - Operating system: Microsoft Windows 8.1
 - Python version 3.12.2

**Comment by stamparm** [comment]
seems like a general environment problem than the sqlmap one

try to use:
`--disable-coloring  Disable console output coloring`

**Comment by kobyan** [comment]
That helped. Thank you
