### ISSUE TITLE
Improve partial union injection

### ISSUE THREAD

**Issue by kobyan** [sqlmapproject/sqlmap#5655]
Now sqlmap supports full union query in injection and row-by-row union injection.
However, sometimes there may be too much data in the table and the full union request fails on the server side, and retrieving data row by row takes a very long time. In this case, it makes sense to try to receive data in batches.
For example,
Here is the full union request:
```
<valid_vuln_param_value> UNION ALL SELECT <concat_columns>,<some_NULLs> FROM <table>-- -
```
Here's the row-by-row query:
```
<valid_vuln_param_value> UNION ALL SELECT (SELECT <concat_columns> FROM <table> LIMIT <counter>,1),<some_NULLs>-- -
```
And here's the batch-by-batch query:
```
<invalid_vuln_param_value> UNION ALL SELECT <concat_columns>,<some_NULLs> FROM <table> LIMIT <batch_counter>,<batch_size>-- -
```
This will reduce the number of requests sent to the server and reduce the time required to receive data.

<invalid_vuln_param_value> will allow to ensure that valid response does not affect the LIMIT in the injection.
<batch_counter> is a counter for receiving data, it starts at 1 (or with the --start parameter) and after each request increases by <batch_size> until it exceeds the number of rows in the table (or the --stop parameter).
To parse the response from the server, can use the same as for a full union request

**Comment by stamparm** [comment]
there is a hidden switch `--force-partial`:

![image](https://github.com/sqlmapproject/sqlmap/assets/921555/a568b287-5dd3-4933-95cd-67426bc6e1e3)

**Comment by kobyan** [comment]
> there is a hidden switch `--force-partial`:
> 
> ![image](https://private-user-images.githubusercontent.com/921555/310597102-a568b287-5dd3-4933-95cd-67426bc6e1e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NDc2ODcsIm5iZiI6MTcwOTc0NzM4NywicGF0aCI6Ii85MjE1NTUvMzEwNTk3MTAyLWE1NjhiMjg3LTVkZDMtNDkzMy05NWNkLTY3NDI2YmM2ZTFlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxNzQ5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGM4NGQyOGRhYjk1NzFlM2ZiMjE3ODYxNDE3OTFlNGUyZmEwNDU1ZTZiNzExZjNjNTcxMWYzNTBlZTBmNWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aXa73BJHfaJiAiJ4DE-eaQ6uLshaOmPkgDRb8uWG-HM)

This switch causes row-by-row union injection. I want to get several thousand rows per request at once, not just one

**Comment by stamparm** [comment]
Across all supported DBMSes? I'll leave it on your `I want`

**Comment by 99smith** [comment]
> there is a hidden switch `--force-partial`:
> 
> ![image](https://private-user-images.githubusercontent.com/921555/310597102-a568b287-5dd3-4933-95cd-67426bc6e1e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTkxNjgsIm5iZiI6MTcxMDMxODg2OCwicGF0aCI6Ii85MjE1NTUvMzEwNTk3MTAyLWE1NjhiMjg3LTVkZDMtNDkzMy05NWNkLTY3NDI2YmM2ZTFlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QwODM0MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmJiMzQxN2M5ZTE1NjM4ZTExOTBhZGQ5ZWQxMDg4MWYxZmY0ZTdiMTBlYTljM2IwNWYyYzNhZGUwNmYzMzBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.afdFn70H9yL7F4NDlR3d0O3v647t7DOlJNns4mfA8ZY)

Hi @stamparm -- Sorry, I am new here .. I am not able to understand why do we have hidden switches , shouldn't these mentioned in sqlmap wiki usage.

**Comment by stamparm** [comment]
@99smith there are "hidden" switches that have been made for specific user cases. In case that there is a general need for any of those options/switches, I tend to un-hide them over time

**Comment by stamparm** [comment]
@99smith to answer you why are they "hidden"? because sqlmap already has tons of options/switches. putting low-usage options/switches would just introduce unnecessary noise
