### ISSUE TITLE
Missing Documentation for '-r' Parameter in sqlmap

### ISSUE THREAD

**Issue by kerszl** [sqlmapproject/sqlmap#5656]
Hello

Describe the bug
The help documentation does not list the "-r" parameter, which is commonly used to read and parse a request from a text file. This parameter is crucial for automating and simplifying the process of sending requests, especially when dealing with complex or lengthy request headers and data.

To Reproduce

    Run sqlmap --help or look into the official documentation to find the description of the "-r" parameter.
    Notice the absence of the "-r" parameter in the help output or documentation.

Expected behavior
The "-r" parameter should be documented in the help output and official documentation. This parameter allows users to easily import requests from a file, facilitating testing against web applications by specifying all request details, including headers, cookies, and POST data, in a single, easily editable file. Its documentation is essential for new users and for reference purposes.

Running environment:

    sqlmap version [1.8.2#stable]
    Installation method [from repository Kali]
    Operating system: [Linux kali2023 6.6.9-amd64]
    Python version [3.11.8]

Target details:

    DBMS [e.g. Microsoft SQL Server]
    SQLi techniques found by sqlmap [e.g. error-based and boolean-based blind]
    WAF/IPS [if any]
    Relevant console output [if any]
    Exception traceback [if any]

Additional context
The "-r" parameter is a fundamental feature for conducting thorough and efficient SQL injection tests. Its omission in the help documentation may hinder the usability of sqlmap for beginners or users migrating from other tools, who rely on the help command or official documentation to understand the available functionalities.

**Comment by lap1nou** [comment]
Hello @kerszl,

I think it's documented, you need to use the larger help argument:
```
sqlmap -hh
```

Regards.

**Comment by kerszl** [comment]
Thanx. you're right.

**Comment by kerszl** [comment]
case solved. Thanks
