### ISSUE TITLE
Can I add a new payload method ？

### ISSUE THREAD

**Issue by VBPush** [sqlmapproject/sqlmap#5660]
**Is your feature request related to a problem? Please describe.**
I encountered a unique SQL injection vulnerability in the process of testing, the effective injection method of this vulnerability is [sql=1WAITFOR+DELAY+'0:0:2'--].It can be found that 1 is not followed by ', ", %20(+)......

If any symbol is added to the end of the 1, the payload is invalid.

sql=1WAITFOR+DELAY+'0:0:2'--     **√**
sql=1'(")WAITFOR+DELAY+'0:0:2'--          **×**
sql=1%20(+)WAITFOR+DELAY+'0:0:2'--      **×**

**Describe the solution you'd like**
Can some new, unsigned (including whitespace) payload methods be added to enable this type of vulnerability to be tested properly?

**Additional context**
![image](https://github.com/sqlmapproject/sqlmap/assets/140361823/2a14bc70-62c2-46e0-9f5c-24c882fe60d7)
![image](https://github.com/sqlmapproject/sqlmap/assets/140361823/bba37591-9c83-43dd-b8f2-e62cd1be78de)
![image](https://github.com/sqlmapproject/sqlmap/assets/140361823/08151915-bad9-4b20-a8b3-36792490a351)

**Comment by stamparm** [comment]
so, something is blocking original payload. thus, i can bet that further payloads (i.e. enumeration) will be blocked too

thus, there will be no "new payload" to be included just for that first step

you can always make yourself a tamper script. change some simple one, like https://github.com/sqlmapproject/sqlmap/blob/master/tamper/sleep2getlock.py to do a dummy replace of `1 WAITFOR` with `1WAITFOR`
