### ISSUE TITLE
I have this issue, the empty value or <blank> how can I retrieve that  

### ISSUE THREAD

**Issue by lekosbelas** [sqlmapproject/sqlmap#5666]
I know there is not latin word as username and that's probably why it doesn't show. How can it be seen? Is it possible?

`sqlmap  -r /tmp/rec12.txt -p id --thread 10 -T kullanicilar -C email, id, password, username --dump --time-sec 20 --pivot-column username
`
<img width="686" alt="Screenshot 2024-03-29 at 01 18 35" src="https://github.com/sqlmapproject/sqlmap/assets/35641898/b99620f7-9447-4c26-a003-c9fa4db140df">

`sqlmap  -r /tmp/rec12.txt -p id --thread 10 -T kullanicilar -C email, id, password, username --dump --time-sec 20                                        `
<img width="675" alt="Screenshot 2024-03-29 at 01 19 07" src="https://github.com/sqlmapproject/sqlmap/assets/35641898/44574a1d-b647-4693-8799-d0ad5320fd38">

**---
Parameter: id (GET)
    Type: boolean-based blind
    Title: OR boolean-based blind - WHERE or HAVING clause
    Payload: id=-9527 OR 5845=5845&param=card&adet=1
---**

**Comment by stamparm** [comment]
Basically, you played with `--pivot-column`, and got different results. Play a bit more. Use something better than the VARCHAR/string based column.

You have tons of options and switches to play around. Try `--hex` or try to find another SQLi technique (that OR based doesn't look too friendly - something is enforcing you to use that one)

**Comment by lekosbelas** [comment]
> Basically, you played with `--pivot-column`, and got different results. Play a bit more. Use something better than the VARCHAR/string based column.
> 
> You have tons of options and switches to play around. Try `--hex` or try to find another SQLi technique (that OR based doesn't look too friendly - something is enforcing you to use that one)

what to use something better than VARCHAR/string based column? I don't how to change it, can you please tell me that?

**Comment by stamparm** [comment]
try to use different column names for pivoting. `VARCHAR/string` are the basics of the basics. those are column types having characters inside, compared to e.g. `INT` having digits inside. sorry to say, but you should really learn basics of SQL or programming before running these kind of tools

**Comment by lekosbelas** [comment]
I used to know SQL. I was working on my own database years ago. Don't remember anything honestly.
