### ISSUE TITLE
payload found only when using `--technique=T`

### ISSUE THREAD

**Issue by godbout** [sqlmapproject/sqlmap#5672]
apologies if i'm missing something obvious, but i can't understand this. by default one of my `sqlmap` command can't find any payload, although a parameter happens to be injectable. just by adding the `--technique=T`, the payload is found. but the docs say that by default sqlmap uses all the techniques, so `T` is included. hence, why the different results? i haven't specified anything else regarding time-based injections, all the other parameters stay the same between the two runs.

thanks! hopefully will learn something today.

**Comment by stamparm** [comment]
yup. strange.

there are maybe couple of things that could go wrong:

1) there was one technique (e.g. boolean-based blind) (maybe unusable - FP) which misdirected sqlmap to pick a specific pair of wrong boundaries (prefix/suffix). in such case, all further techniques would use those wrong boundaries
2) first N non-time based SQLi requests are collected for statistical analysis of delays (for time-based SQLi). maybe something was blocking/filtering (e.g.) boolean-based blind SQLi, which introduced uncertainties into the statistical model

apart from those two reasons ^^, ATM i can't think of anything else (obvious)

**Comment by godbout** [comment]
nice, thanks for the quick answer. clarifying that i'm not misunderstanding something, just a lack of knowledge from my part. back to it!
