### ISSUE TITLE
May I ask where the payload below will ultimately be assembled into SQL? Please give an example

### ISSUE THREAD

**Issue by dean2021** [sqlmapproject/sqlmap#5673]
May I ask where the payload below will ultimately be assembled into SQL? Please give an example
```
1]-(SELECT 0 WHERE 7350=7350;SELECT PG_SLEEP(5)--
```

**Comment by stamparm** [comment]
sorry, but i don't understand the question nor the markation `bug report`. where is the bug?

you are asking where in code sqlmap is assembling such payload(s) or what?
