### ISSUE TITLE
[!] wrong installation detected (missing modules). Visit 'https://github.com/sqlmapproject/sqlmap/#installation' for further details

### ISSUE THREAD

**Issue by Joker2020-cmd** [sqlmapproject/sqlmap#5674]
**Describe the bug**

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**

**Running environment:**
 - sqlmap version [e.g. 1.7.2.12#dev]
 - Installation method [e.g. pip]
 - Operating system: [e.g. Microsoft Windows 11]
 - Python version [e.g. 3.11.2]

**Target details:**
 - DBMS [e.g. Microsoft SQL Server]
 - SQLi techniques found by sqlmap [e.g. error-based and boolean-based blind]
 - WAF/IPS [if any]
 - Relevant console output [if any]
 - Exception traceback [if any]

**Additional context**

**Comment by stamparm** [comment]
1) download https://github.com/sqlmapproject/sqlmap/archive/refs/heads/master.zip
2) unzip it
3) run sqlmap.py
4) ???
