### ISSUE TITLE
union-based injection

### ISSUE THREAD

**Issue by supra-x9** [sqlmapproject/sqlmap#5675]
I had a problem while performing union based sql injection, this problem is that there is no string expression in the response corresponding to the payload.

I solved this problem by taking the ascii characters and then combining them,

it cannot be detected with the normal union-based technique, is there a sqlmap command for me to detect it with ascii

![original](https://github.com/sqlmapproject/sqlmap/assets/166237279/7bf54e5c-bfe9-40d6-b2d2-be8f29db7e58)
![union ascıı](https://github.com/sqlmapproject/sqlmap/assets/166237279/9abc6f7a-0d9b-454c-98e2-b6f957185ece)
original response :  5,70
ascıı response : 534655465251  : 5.7.43

**Comment by supra-x9** [comment]
> I had a problem while performing union based sql injection, this problem is that there is no string expression in the response corresponding to the payload.
> 
> I solved this problem by taking the ascii characters and then combining them,
> 
> is there any way to use this for sqlmap

it cannot be detected with the normal union-based technique, is there a sqlmap command for me to detect it with ascii
> 
> ![original](https://private-user-images.githubusercontent.com/166237279/320221509-7bf54e5c-bfe9-40d6-b2d2-be8f29db7e58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MjM3NzAsIm5iZiI6MTcxMjQyMzQ3MCwicGF0aCI6Ii8xNjYyMzcyNzkvMzIwMjIxNTA5LTdiZjU0ZTVjLWJmZTktNDBkNi1iMmQyLWJlOGYyOWRiN2U1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNlQxNzExMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGJkMzEyNWQ1NWM0MjI5Yzk3MDdiYWJmYzVjMzZiMTU3ZmQyZWNiZDIwYmU0YmM4NDIzOGI5Zjk0Yzc3MDJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h3DbUAniDsAEvjA5NRaBq9NZntwS61uf8Xm1YKL9O0M) ![union ascıı](https://private-user-images.githubusercontent.com/166237279/320221512-9abc6f7a-0d9b-454c-98e2-b6f957185ece.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MjM3NzAsIm5iZiI6MTcxMjQyMzQ3MCwicGF0aCI6Ii8xNjYyMzcyNzkvMzIwMjIxNTEyLTlhYmM2ZjdhLTBkOWItNDU0Yy05OGUyLWI2Zjk1NzE4NWVjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNlQxNzExMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmMyNjY1MWNmMzllMDYyNWY2YjJhYTc2M2Q0NWJhZTEyZTg2MWNhZWI2NzI5MWI5YjIxOGY5MjZiZjhlYTdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5LyP0KnU4-xitQ0__XjwdRj9s6mVOoMcINlGlHaL-Y0) original response : 5,70 ascıı response : 534655465251 : 5.7.43

**Comment by supra-x9** [comment]
I tried the non-hex method and it worked but sqlmap cannot detect it, how do I run it by entering more specific command

payload :  aderts'--%0AUNION--%0AALL--%0ASELECT--%0ANUlL,NUlL,SUBSTRING(version(),1,1),NUlL,NUlL,NUlL,NUlL,NUlL,NUlL,NUlL,NUlL,NUlL,NUlL-- -

the results are as follows :
1,1 : ₺ 5,00
2,1 : ₺ 
3,1 : ₺ 7,00
4,1 : ₺ 
5,1 : ₺ 4,00
6,1 : ₺ 3,00
![Ekran görüntüsü 2024-04-06 225906](https://github.com/sqlmapproject/sqlmap/assets/166237279/bf97f7c1-07fa-4afa-bb30-2babe5cdb83d)
![Ekran görüntüsü 2024-04-06 230054](https://github.com/sqlmapproject/sqlmap/assets/166237279/2b0db7a9-f3bb-4493-895d-e2462748ca78)
![Ekran görüntüsü 2024-04-06 225733](https://github.com/sqlmapproject/sqlmap/assets/166237279/9b09f386-87ad-4ec4-9348-650d0fd5f5ed)

**Comment by stamparm** [comment]
why would page return ASCII code for the response? i see this as a special case. not sure why this should be implemented inside the sqlmap core

you also have `--postprocess=PO..  Use given script(s) for postprocessing (response)` which you could potentially use to process the response and convert those ASCII codes to a regular text
