### ISSUE TITLE
anti-CSRF token 'XSRF-TOKEN' can't be found at 

### ISSUE THREAD

**Issue by SummusFortunaeDictator** [sqlmapproject/sqlmap#5676]
sqlmap -r xx.txt --dbs

anti-CSRF token 'XSRF-TOKEN' can't be found at

**Comment by stamparm** [comment]
missing anything useful here. how to debug this? can you please rerun with `-t traffic.txt` and try to find the `XSRF-TOKEN` inside the traffic file?
