### ISSUE TITLE
How to extract database contents quickly

### ISSUE THREAD

**Issue by yusufalbashar** [sqlmapproject/sqlmap#5683]
**Is your feature request related to a problem? Please describe.**
[INFO] retrieved: ..E.B1N.B.B.B.b?B.I.B.B.B.F.B0N.Q..
[INFO] retrieved: ..E.B1N.B.B.B.b?B.I.B.B.B.F.B0N.Q..
[INFO] retrieved: ..E.B1N.B.B.B.b?B.I.B.B.B.F.B0N.Q..
[INFO] retrieved: ..E.B1N.B.B.B.b?B.I.B.B.B.F.B0N.Q..
[INFO] retrieved: ..E.B1N.B.B.B.b?B.I.B.B.B.F.B0N.Q.. 14384/147147 (10%)

**Describe the solution you'd like**
What is the reason
[INFO] retrieved: ..E.B1N.B.B.B.b?B.I.B.B.B.F.B0N.Q.. 14384/147147 (10%)
What is the way to solve this problem so that it tests normally letter by letter?

**Comment by stamparm** [comment]
seems like pure junk (maybe a false-positive detection). rerun everything with `--flush-session`
