### ISSUE TITLE
cant fetch the tables from the database 

### ISSUE THREAD

**Issue by Boss130555** [sqlmapproject/sqlmap#5689]
my database name is called "jams" i find the vulnerability and find the database name i.e jams
in sqlmap i entered the command like this " sqlmap -u https://jams-jnnce.in --crawl 3 --batch level 5 risk 3 -D jams --tables " but it taking so much and much time fetch a single table what can i do ?
it showing increasing time delay 1 seconds after 1 seconds please help out  from this please?

**Comment by stamparm** [comment]
can you please tell me what's exactly the useful information given here? i mean, let yourself into my position and say what would you do

**Comment by tanaydin** [comment]
@Boss130555 , you can increase the verbosity with "-v" argument, like...

`sqlmap -u https://jams-jnnce.in/ --crawl 3 --batch level 5 risk 3 -D jams --tables -v 6`

and see exactly which point it's doing wrong or bootleneck.
