### ISSUE TITLE
Output As JSON Without API Mode

### ISSUE THREAD

**Issue by nik-ngp** [sqlmapproject/sqlmap#5691]
**Is your feature request related to a problem? Please describe.**
I have a use case where I need JSON output of SQLMAP, usually I'd fire it up in API mode and problem solved, however, my specific use case prevents me to use it in an API mode. 

**Describe the solution you'd like**
I'd appreciate if I can run SQLMAP from my terminal, maybe in a silent mode or something where by the end of it I'd get the output printed in the terminal in a JSON fromat.

**Describe alternatives you've considered**
As mentioned, first thing that came to my mind was using it in API mode, however, after further consideration I came to realize I cannot "afford" having an API due to the nature of what I am building.

Related issue, however, distinct from this one: https://github.com/sqlmapproject/sqlmap/issues/3094

**Comment by stamparm** [comment]
yea. there have been similar requests. in majority of cases, requester was some integration programmer which would use the sqlmap in their "cloud" platform. in all cases, sqlmap's double license is just ignored. hence, this kind of requests are just closed and ignored

**Comment by nik-ngp** [comment]
Mr. Stampar. I by all means am not building a cloud platform. I'm trying to streamline pentesting efforts in the company that I work at. It's purely for internal use. We aren't a cyber-security company.

**Comment by stamparm** [comment]
` I came to realize I cannot "afford" having an API due to the nature of what I am building.` <- aha. so, you are doing a `streamline pentesting efforts in the company that I work at` for `purely internal use`, but API is not good enough

oooookkkkkk. byez
