### ISSUE TITLE
Assistance Needed with Sqlmap Security Product

### ISSUE THREAD

**Issue by aryater2212** [sqlmapproject/sqlmap#5695]
Dear Stamp,

I hope this email finds you well. I am writing to seek assistance regarding an issue I encountered while using the Sqlmap security product.

During my usage of the Sqlmap security product, I identified and confirmed two injection types. The first type is boolean-based blind with DBMS set to MySQL, and the second type is time-based blind.

Following this, I submitted a request to Sqlmap to obtain databases (denoted by --dbs) using time-based blind injection. I received a response for the --dbs request, and it successfully listed all databases. However, when I attempted to retrieve tables (denoted by --tables), I encountered an obstacle.

The --tables request seems to be repeating the content of one table byte, such as "action," for all tables. This repetition fills up the response with the number of tables present, but it does not provide the actual table names or information. I have been unable to identify the root cause of this issue, and I would greatly appreciate your assistance in resolving it.

Could you please provide guidance on how to troubleshoot and resolve this issue? Additionally, if there are any specific configurations or adjustments that need to be made, please let me know.

Thank you very much for your attention to this matter. I look forward to your prompt response and assistance.

![1](https://github.com/sqlmapproject/sqlmap/assets/167961932/78534a21-60a3-4407-a720-4c427b9415cc)
![2](https://github.com/sqlmapproject/sqlmap/assets/167961932/fbf6761f-cb84-44b6-8c4c-6685a9a70192)
Best regards,

**Comment by stamparm** [comment]
you should run sqlmap with `-v 3` and try to find whether some of payloads are wrong during the retrieval of those table names

**Comment by aryater2212** [comment]
Alright, I'll give it a try. Thanks for your response, just wait for me to
check if there are any payloads that are wrong during the retrieval of
these table names.
