### ISSUE TITLE
SQLMAP wasn't able to detect PostgreSQL

### ISSUE THREAD

**Issue by whlpentest** [sqlmapproject/sqlmap#5697]
Hi,
Sqlmap ver: 1.8.4.5#dev did not detect PostgreSQL time based despite successful manual testing in Burp Suite with this payload:
```
{"id":"'and(select'1'from/**/pg_sleep(5))::text>'"}
```
my sqlmap command : 

```
python3 sqlmap.py -r raw --timeout 60 --threads 10 --flush-session -p Id -v 3 --dbms=PostgreSQL --technique=T --level 5 --risk 4  --random-agent --tamper=space2comment
```
I have already play with `--suffix "'"` and `--prefix="::text>'"`

**Comment by stamparm** [comment]
too bad man. i would spend some time in proper debugging on what's going on. like, if you know how to run Burp, maybe you could capture some requests from sqlmap via `--proxy` and try to replay? anyhow, really sorry that you are not able to use sqlmap in intended way
