### ISSUE TITLE
Csrf-token not set when data in json format.

### ISSUE THREAD

**Issue by white-abaddon** [sqlmapproject/sqlmap#5698]
`sqlmap --method=POST -u https://blabla.com/ --data='email=username@example.com&password=password&captchaToken=token' -p email  --proxy=http://127.0.0.1:8080 --csrf-token "captchaToken" --csrf-url="http://127.0.0.1:8000/token/get/" --abort-code 429`

According to this command, the captchaToken is fetched from localhost and updated in the captchaToken field within the JSON data. However, a problem arises when the data is in JSON format, such as --data={"email": "username@example.com", "password": "password", "captchaToken": ""}. This command is unable to update the captchaToken from localhost.

`sudo docker run \
    --network="host" \
    pentest-tool/sqlmap \
    --method=POST \
    -u https://blabla.com \
    --data='{"email": "username@example.com", "password": "password", "captchaToken": ""}' \
    -p email \
    -H "User-Agent: L" \
    -H "Referer: https://blabla.com/" \
    -H "Origin: https://blabla.com" \
    -H "Content-Type: application/json" \
    --delay=10 \
    --skip-heuristics \
    --skip-waf \
    --technique=BT \
    --ignore-code 401 \
    --abort-code 429 \
    --proxy=http://127.0.0.1:8080 \
    --csrf-token "captchaToken" \
    --csrf-url="http://127.0.0.1:8000/token/get/"`

**Comment by stamparm** [comment]
and what's the format of returned `http://127.0.0.1:8000/token/get/` ? i have to know what and how to parse

**Comment by stamparm** [comment]
@white-abaddon try now

**Comment by stamparm** [comment]
`Everthing working fine by my side i mean captcha token is fetched by sqlmap.` <- while everything is working on my side. somebody's side is screwed. i basically emulated everything you said

**Comment by stamparm** [comment]
proof from my side that i haven't "screwed":

![image](https://github.com/sqlmapproject/sqlmap/assets/921555/a590764f-188e-4804-921f-ab07206ebb08)

**Comment by stamparm** [comment]
you changed the UA and I am not sure that you are using the latest revision

**Comment by stamparm** [comment]
you are running `1.8.4.1#dev` for the whole time

**Comment by stamparm** [comment]
my guess is that you are running `sqlmap --update` inside some docker container which doesn't persist with the update(s). now, we are ping-ponging here, where you claim that you are using the latest revision, while I can see that the version you have run with `--update` was 1.8.4.1#dev (<- where i would expect that you would ATM have latest 1.8.4.6#dev as you explicitly said that you already **updated**)

**Comment by stamparm** [comment]
won't spend 1 more minute here. closed this whole conversation. by the way, if you say that `By the way i already update my sqlmap after your last commit` then you should be really sure about your claim before doing this whole ping-pong here
