### ISSUE TITLE
Threading won't work when dumping data.

### ISSUE THREAD

**Issue by Maxdha** [sqlmapproject/sqlmap#5705]
**Describe the bug**
Whenever I'm dumping table or db names with the --threading option, it works correctly. However, dumping data from a table always feels single threaded.. It's like one query every 0.5 second.

![image](https://github.com/sqlmapproject/sqlmap/assets/41434187/1ea1cbdf-f35e-4ede-95eb-05f778849ab1)

**Running environment:**
 - 1.8.5.4#dev]
 - Operating system: Windows 10

**Target details:**
 - DBMS: microsoft sql server
 - SQLi techniques found by sqlmap: Microsoft SQL Server/Sybase AND error-based - WHERE or HAVING clause (IN)

**Comment by stamparm** [comment]
"feels". LOL

made couple of debug prints, where first integer is integer ID, where the value afterwards is the retrieved value(s):
![image](https://github.com/sqlmapproject/sqlmap/assets/921555/922c29f4-9306-4762-834b-f550e2c5101a)

it **felt** multi-threaded for sure

**Comment by stamparm** [comment]
this is 5705th issue. i pretty much single-handedly covered each and every one of them. i have no idea why people like to open so much junk based on "feel". is it kind of disrespectful to just push junk without yourself not doing anything to help me?!

do some basic debugging on your own side, be damn sure that there is a bug report before opening "bug report" (to not piss me off). if your best argument is "feels", then FFS
