### ISSUE TITLE
sqlmap will not save half dumped data in CSV File???

### ISSUE THREAD

**Issue by soloh4cker** [sqlmapproject/sqlmap#5712]
**Is your feature request related to a problem? Please describe.**
The target I am working on is Boolean based blind injection vulnerable. Since I got the database, tables, columns names I am trying to `--dump` data present in the table. Now the problem is this injection technique is time consuming for larger database. Lets say there are 10000 rows (data) present in the columns I am trying to dump. After spending 2-3 hours I dumped 5000 rows and I dont want to continue further so I pressed ctrl+C and stopped the attack. Since, I stopped the attack in the middle or it was not completely finished, sqlmap will not save the output in csv file!!! Also, the current output of 5000 rows is also not in table format in terminal window. Therefore, either I have to waste another 2-3 hours sorting this data in table format or it is useless data for me!!! 

**Describe the solution you'd like**
I would suggest two options for the solution here. Any of them will work I guess!
(1) Force sqlmap to show output in table format in terminal window (image attached) so we can copy paste to a txt file at least. 
(2) Save the current dumped data in csv file as usual even when user pressed ctrl+C or anyhow attack is stopped in the middle. 

**Describe alternatives you've considered**
N/A

**Additional context**
(1) Image of current output format in `--dump`
(2) Image of current output format in `--dump`
(3) Image of output I want to be in format (table format) when attack stopped in the middle. Or save it in csv file!
![Output result 1](https://github.com/sqlmapproject/sqlmap/assets/69952922/bd7f701a-33b4-44b6-b50e-1e7d72b624bd)
![Output result 2](https://github.com/sqlmapproject/sqlmap/assets/69952922/45916e77-5a05-4ba5-890c-168b4fc68b4b)
![I_want_this_format](https://github.com/sqlmapproject/sqlmap/assets/69952922/fb437111-f929-41db-a919-f558830eeb65)

**Comment by stamparm** [comment]
`sqlmap will not save the output in csv file!!! ` <- this is not true. even if you stop it in a normal way, and being dumb user which will press Ctrl-C for more than once, you'll get the CSV file. 

Proof that you are plain wrong here:

![image](https://github.com/sqlmapproject/sqlmap/assets/921555/493007cc-4dfe-402d-93b0-908d5b3e946f)
![image](https://github.com/sqlmapproject/sqlmap/assets/921555/5b975815-1cc0-4ce2-b155-c16130b2856e)
