### ISSUE TITLE
SQLAlchemy connection issue ('ModuleNotFoundError: No module named 'MySQLdb'')

### ISSUE THREAD

**Issue by TuAgT** [sqlmapproject/sqlmap#5714]
**Describe the bug**

SQLAlchemy connection issue ('ModuleNotFoundError: No module named 'MySQLdb'')
**To Reproduce**
1. pipx install sqlmap
2. sqlmap -d "mysql+pymysql://root:root@127.0.0.1:3306/information_schema"
<img width="874" alt="image" src="https://github.com/sqlmapproject/sqlmap/assets/37065019/26c1035c-36f5-479c-97ab-40a4840d5dec">

3. pipx runpip sqlmap  install PyMySQL
4. sqlmap -d "mysql+pymysql://root:root@127.0.0.1:3306/information_schema"
<img width="880" alt="image" src="https://github.com/sqlmapproject/sqlmap/assets/37065019/eaede30d-900e-4e0b-b0a5-aae040f11a82">
5. pipx runpip sqlmap  install SQLAlchemy 
6. sqlmap -d "mysql://root:root@127.0.0.1:3306/information_schema"
<img width="877" alt="image" src="https://github.com/sqlmapproject/sqlmap/assets/37065019/7f9d3220-b18c-4d99-9920-be43f8ff78e1">

**Expected behavior**

**Screenshots**

**Running environment:**
 - sqlmap version 1.8.5
 - Installation method `pipx install sqlmap`
 - Operating system: macOS Sonoma 14.4.1
 - Python version 3.12

**Target details:**
 - DBMS mysql5.5

**Additional context**

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting @ 23:03:02 /2024-05-16/

[23:03:03] [CRITICAL] SQLAlchemy connection issue ('ModuleNotFoundError: No module named 'MySQLdb'')

[*] ending @ 23:03:03 /2024-05-16/

**docker-compose.yml**
```
services:
  db:
    image: mysql:5.5
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
```

**Comment by stamparm** [comment]
![image](https://github.com/sqlmapproject/sqlmap/assets/921555/3aaa2e3b-695a-49f8-a222-e04bc752c036)
![image](https://github.com/sqlmapproject/sqlmap/assets/921555/888c8840-6ff0-4f34-b7eb-87f3ffe2c017)

**Comment by stamparm** [comment]
so, created everything from scratch. please, forgive me to not put links to letmegooglethatforyou in sqlmap output, especially in your case

so, TL;DR, this worked:

```
docker-compose up

virtualenv testsql
source testsql/bin/activate
python -m pip install sqlalchemy
python sqlmap.py -d "mysql://root:root@127.0.0.1:3306/information_schema"
python -m pip install pymysql
python sqlmap.py -d "mysql://root:root@127.0.0.1:3306/information_schema"
```

now, step by step, with some pictures:

![image](https://github.com/sqlmapproject/sqlmap/assets/921555/b516bd8a-cc1a-428a-9ad6-d8a2a2b8b674)

literary first Google result shows this:

![image](https://github.com/sqlmapproject/sqlmap/assets/921555/b02c2841-f894-4e0f-bac5-4aa2229c759d)

![image](https://github.com/sqlmapproject/sqlmap/assets/921555/fe919e6b-b567-4aaa-a76f-c34f5d50cb96)
