### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by idkwhattonamemyaccount** [sqlmapproject/sqlmap#5723]
soo im in a situation where the request data is something like this:
user=XXXXX&pass=12345&check=check_login.php?username=XXXXX&password=12345

how do i make sqlmap to inject in "username=**XXXXX**" (the one in check_login.php)? i tried using -p username but it didnt work

**Comment by stamparm** [comment]
` user=XXXXX&pass=12345&check=check_login.php?username=XXXXX*&password=12345`
