### ISSUE TITLE
custom payload

### ISSUE THREAD

**Issue by GameOFGame** [sqlmapproject/sqlmap#5726]
There is an sql injection that I cannot detect with sqlmap 
I tried sqlmap at --level 5 --risk 3 but could not detect it

I found the injection specifically through this payload : 
' OR  '2521'='2521  (true)
' OR  '2521'='2522 (false) 
I tested using the burp suite tool, it reacts specifically to this load

https://prnt.sc/Z7MLjnZzUOr5
https://prnt.sc/KjEkuJYW908C

is there any way to use this custom payload in sqlmap

**Comment by stamparm** [comment]
not convinced:

![image](https://github.com/sqlmapproject/sqlmap/assets/921555/6cf75a09-d379-41e7-b11c-8932e9d91e8e)

nonetheless, you can try to use `--risk=3` to turn on the `OR boolean-based blind` payloads
