### ISSUE TITLE
More error-based payloads

### ISSUE THREAD

**Issue by kobyan** [sqlmapproject/sqlmap#5728]
Hello

I noticed that currently there are no options in error-based payloads when the vulnerable parameter is inserted into the SQL query as a table name. (clause - 7)
Example:
Vulnerable request - `http://<host>/<something.php>?table=<param>`
SQL query that executes in the DBMS - 
```
SELECT *
FROM <param>
WHERE <some filters>
```

In this case, you can implement an Error-based SQL injection of the form `<param> <alias1>, (select <payload>) <alias2>`. As a result, the DBMS server will try to execute the command and will return the <payload> query result as an error.
I tested this on GTID_SUBSET and UPDATEXML payload for MySQL, but this should work for other payloads as well

**Comment by kobyan** [comment]
Boolean-based injection is also possible for those DBMS in which comma separated join is equivalent to inner join. (For example MySQL)
`<param> <alias1>, (select <something> where <payload>) <alias2>`

**Comment by stamparm** [comment]
AFAICS, these type of boundary/payload is found by sqlmap out-of-the-box for those kind of cases:

```
    Title: MySQL >= 5.0 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (FLOOR)
    Payload: table=users WHERE 1920=1920 AND (SELECT 6134 FROM(SELECT COUNT(*),CONCAT(0x717a6b7a71,(SELECT (ELT(6134=6134,1))),0x71626a7871,FLOOR(RAND(0)*2))x FROM INFORMATION_SCHEMA.PLUGINS GROUP BY x)a)-- BBLK
```

basically, that existing `WHERE [RANDINT]=[RANDINT]` bypasses the need for any kind of intervention on those cases

**Comment by kobyan** [comment]
> AFAICS, these type of boundary/payload is found by sqlmap out-of-the-box for those kind of cases:
> 
> ```
>     Title: MySQL >= 5.0 AND error-based - WHERE, HAVING, ORDER BY or GROUP BY clause (FLOOR)
>     Payload: table=users WHERE 1920=1920 AND (SELECT 6134 FROM(SELECT COUNT(*),CONCAT(0x717a6b7a71,(SELECT (ELT(6134=6134,1))),0x71626a7871,FLOOR(RAND(0)*2))x FROM INFORMATION_SCHEMA.PLUGINS GROUP BY x)a)-- BBLK
> ```
> 
> basically, that existing `WHERE [RANDNUM]=[RANDNUM]` bypasses the need for any kind of intervention on those cases

This payload only works if the WHERE condition in the original SQL query is on the same line as the table name parameter, but this is not always the case. If there is a line break in the SQL query after the table name parameter, then the line comment (--) will not help and the query will end up with 2 WHERE blocks.
```
SELECT *
FROM users WHERE 1920=1920 AND (<payload>)-- BBLK
WHERE <some filters>
```
This will prevent the injection from working.

**Comment by stamparm** [comment]
With latest revision you'll have that. I am not planning to expand it to more payloads as there is absolutely no need for that. Only thing for discussion is whether something other than FLOOR would be better for MySQL coverage
