### ISSUE TITLE
Error: missing a mandatory option

### ISSUE THREAD

**Issue by edindrug** [sqlmapproject/sqlmap#5730]
Hello, sorry if already answered but I couldn't find any info.
The problem occurs when I make a bash script to run sqlmap and move it to /usr/bin so I can use it freely.

There is no error when accessing it straight from it's installation path -> ~/Programs/sqlmap-dev/sqlmap.py -u site.com

But when I try to use my script, which is basically: 

#! /bin/bash
python3 ~/Programs/sqlmap-dev/sqlmap.py

and move it to the bin folder or even try to execute it from the .sh path it gives me the  "Error: missing a mandatory option".

Thanks.

**Comment by stamparm** [comment]
this is pure junk:

````
#! /bin/bash
python3 ~/Programs/sqlmap-dev/sqlmap.py
```

it is not passing any arguments to the sqlmap. those are literary the basics
