### ISSUE TITLE
Enhancing Inline Query Detection

### ISSUE THREAD

**Issue by DelvinBa** [sqlmapproject/sqlmap#5733]
I tested thirty different SQL injection cases using sqlmap. The tool was very effective in detecting various types of SQL injections, except for inline queries, where it failed to detect any. One of the test cases involved the vulnerable web application "bWAPP", specifically the file "sqli_11.php". The SQL code in this test case is as follows:

$entry = sqli($_POST["entry"]);
$owner = $_SESSION["login"];

```
if ($entry == "") {
    $message = "<font color='red'>Enter text</font>";
} else {
    $sql = "INSERT INTO blog (date, entry, owner) VALUES (now(), '" . $entry . "', '" . $owner . "')";
}
```

A successful SQL injection payload using the inline query technique for this scenario was:

 ` ’ , (select (password) from users limit 0,1) -- `   

I noticed that the number of payloads for inline query techniques is significantly lower compared to other SQL injection methods. To enhance detection of inline queries, it would be beneficial to include a wider variety of payloads.

**Comment by stamparm** [comment]
how is this inline query SQLi is beyond my comprehension?! "inline" SQLi is literary "inline SQL injection". you are using some dummy SELECT query to insert something into the INSERT column. also, you are expecting the output of such action to your output

please, don't raise this kind of "bug reports" any more

**Comment by DelvinBa** [comment]
It seems there was a misunderstanding on my part regarding inline query detection; I understood it to refer to subqueries in any SQL statement, which led me to classify it as such. However, it appears this is not the case. Inline queries are not listed and explained on your techniques page, and it would be helpful to include your definition there to avoid such misunderstandings. I searched for “Inline query” attacks in various SQL injection literature but could not find any references under that name. Does your definition of inline queries strictly refer to subqueries within the FROM clause of a SELECT statement?

Additionally, the attack I mentioned remains a valid one, as demonstrated in three different test cases I conducted, which sqlmap failed to detect. It involves a subquery attack within an INSERT or UPDATE statement. This type of attack is discussed in multiple sources, including Justin Clarke’s “SQL Injection Attacks and Defense, 2nd Edition” in the chapter “Injecting into Insert queries,” and the article available at https://www.researchgate.net/publication/262536173_Classification_of_SQL_Injection_Attacks. It allows insertion of data from other tables into the displayed table on a web interface.

Perhaps this type of attack technique should be further examined to consider whether it should be integrated into the tool or not. Maybe you could 

P.S. I found your response to be quite dismissive and unfriendly. It seems obvious to you that I misclassified an attack, but stating that such issues should not be opened in the future goes against the spirit of open-source. When someone wants to help or improve an open-source project, I would encourage them to continue doing so in the future, even if their bug report is somehow incorrect. I hope we can continue this discussion in a more constructive manner. Thank you.

**Comment by stamparm** [comment]
unfriendly you say. imagine handling >5000 handled issues where people pushing "misunderstandings" are all handled in a friendly manner. hard to imagine
