### ISSUE TITLE
Problem with data retrieval, empty ( Results with  [INFO] retrieved: ' ')

### ISSUE THREAD

**Issue by ghost** [sqlmapproject/sqlmap#5734]
Hello, sorry for the inconvenience. 
I'm not used to opening this but I'm totally confused even reading the documentation. I don't understand

When I try to dump the database, here are the results I get. Some results are in 
[01:36:02] [INFO] retrieved: ''

I've tested other tools outside sqlmap, and I don't have this problem I manage to get all the information and not an empty info retrieved as if there was nothing in it.

I wonder if this isn't a compatibility problem between the database and sqlmap? 
Thank you if you take the time to answer me, I'm sorry if it's a silly question.
Good day/evening

![TEST](https://github.com/sqlmapproject/sqlmap/assets/170562894/6a5522b0-b2de-4619-968e-4b196472ba71)

**Comment by stamparm** [comment]
who knows. there can be lots of related problems here. you just skipped the template, so i have to guess here

maybe something is blocking your requests. if this is a time-based SQLi, maybe there is a yuge latency. maybe there is a problem with "ORDER BY". lots of guessing here

rerun everything with `--parse-errors -t traffic.txt` and inspect the content of the resulting `traffic.txt`
