### ISSUE TITLE
Add CSV Export for --sql-query Results and Sponsor Marks for GitHub Accounts

### ISSUE THREAD

**Issue by Imran-imtiaz48** [sqlmapproject/sqlmap#5739]
I hope you're doing well. I'm reaching out with a feature request, and I understand it might require a $1 sponsor.

I would like to suggest the addition of sponsor marks to future GitHub accounts.

I've noticed a discrepancy between the results of -D DB -T TB -C A,B --dump and --sql-query="SELECT A,B FROM DB.TB". The latter simply saves to the output and log file.

Currently, I would like to save the results to a CSV file when the -D option is not available in SQLMAP (version detection failed, which I'm trying to debug) or when using the ORDER BY syntax (with --sql-query).

Thank you for your consideration.

**Comment by stamparm** [comment]
this would all look like mess:

1) names of the columns in such CSV file would be unknown (you can't just say "put A and B" as you should know that "SELECT 1,2" or "SELECT MAX(id) FROM users" would not have column names)
2) `--dump` has a nice structured output in form of a filename and a location. filename is based on the table name. in case of "SELECT 1,2" I would need to put some shitty value there, and everything would be a mess inside the output directory
