### ISSUE TITLE
Host website does not exist error

### ISSUE THREAD

**Issue by kingsley-developer** [sqlmapproject/sqlmap#5741]
**Describe the bug**
Host doesn't exist

**
1. I ran python sqlmap -u urlname --level=1 --risk=1 on Kali Linux machine

2. It gave me error saying host doesnt exist but the host exist

Note: I am having good internet connection, and i have python installed as well as Git. So what is the solution.

**Comment by stamparm** [comment]
how to debug this "bug report"? i would bet that the issue is trivial, but i have zero useful details
