### ISSUE TITLE
Error 403 pls help me

### ISSUE THREAD

**Issue by sn1ln** [sqlmapproject/sqlmap#5743]
![image](https://github.com/sqlmapproject/sqlmap/assets/111247116/9a5e5bf7-4f31-49b9-86b9-7ede0562c467)
I am sending a request to the page (It costs cloudflare)
I searched for different options on the Internet to solve this problem, but I did not find it, I substituted cookies __cf_bm, the page that I want to open opens without authorization.

**Comment by stamparm** [comment]
this is not a "bug report". you have something that is blocking sqlmap. do your own work

1) for start, you can try to use `--random-agent`
2) you can also try to browse to that same page from browser and copy-paste all the cookies being passed (go to browser's DevTools and copy-as-curl would be the best option)
