### ISSUE TITLE
WARNING] cannot properly display (some) Unicode characters inside your terminal ('cp437')

### ISSUE THREAD

**Issue by rikou2** [sqlmapproject/sqlmap#5745]
why when i dump this DB i received results like this any help please ???

[10:04:30] [INFO] the back-end DBMS is MySQL
[10:04:30] [INFO] fetching banner
web application technology: Apache, PHP 5.5.38
back-end DBMS: MySQL >= 5.0.12
[10:04:30] [INFO] fetching columns for table 'user_details' in database 'ttttttttttt'
[10:04:32] [INFO] fetching entries for table 'user_details' in database 'ttttttttttttttt'
Database: tttttttt
Table: user_details
[1212 entries]
+---------+------------------------------------------+---------------------------+
| hotelid | password                                 | username                  |
+---------+------------------------------------------+---------------------------+
[10:04:36] [WARNING] console output will be trimmed to last 256 rows due to large table size
| 963     | \xc9\xf4\xea\xa8\x07Z\x96                | wonkyxml                  |
| 964     | 5\x9d\x11w\x0c\xa0U                      | wonkystablesxml           |
| 965     | sf\xa5\x1e)O                             | carseldinepalmsxml        |
| 966     | ;\x9d.\xec\x08N                          | retreatsvicxml            |
[10:04:36] [WARNING] cannot properly display (some) Unicode characters inside your terminal ('cp437') environment. All unhandled occurrences will result in replacement with '?' character. Please, find proper character representation inside corresponding output files
| \xa7s\x13\x94?                           | walpolewrxml              |
| 968     | \xdaH\xb4\xd2U\x82                       | archerxml                 |
| 969     | `0\x14,F\x8e                             | balnarringxml             |
| 970     | p\xfd/\xe3\x05Q                          | staplehousexml            |
| 971     | \xeaI\xd1\xe7\t]                         | sleeprestxml              |
| 972     | `\xeb\xc2f\x04\xd1                       | dalbymixml                |
| 973     | \xc9\xf4\x1bb\x14\xf6\x84                | alburycentralxml          |
| 974     | \\\x9c\x18!\xbdE?                        | staplehousexml            |
| 975     | \xc9d\x98\xac*\x88\xaf                   | cityviewmotelxml          |
| 976     | \xbcY8XG\x9a                             | crossleyxml               |
| 977     | p\xf5\x0eB\x05\xc4                       | argylexml                 |
| 978     | _c\xeb1\x18\x8e                          | minersretreatxml          |
| 979     | \x89\xd5\xc7S6\x88                       | blazingxml                |
| 980     | \xbc\xb9\x96\xc3#\x9d                    | renzellaxml               |
| 981     | `? N                                    | amoravillaxml             |
| 982     | _H\x8d\xcb\x05*                          | kadinavillagexml          |
| 983     | [\xe0\xe4#\x15\xb8                       | braemarxml                |
| 984     | \xb6w)2\x1b\xc8                          | manjimupxml               |
| 985     | `\xa1\xa4a\xa58                          | caribbeanxml              |
| 986     | _\xfeu\xc7\xd0%                          | kohronghillxml            |
| 987     | {v\xf0>\x1aF                             | branxtonhsexml            |
| 988     | [g\x19(\xd1$                             | bucubejixml               |
| 989     | ?bR6                                     | intercontinentalmxml      |
| 990     | \xeaU\xae(B3                             | hotelnanathamelxml        |

**Comment by stamparm** [comment]
password column in your case looks like it is in a password digest form. thus, you have to use:

`--binary-fields=..  Result fields having binary values (e.g. "digest")`

e.g. `--binary-fields=password --fresh-queries`
