### ISSUE TITLE
pip install sqlmap - No Module named "sqlmap"

### ISSUE THREAD

**Issue by jacksonjapy** [sqlmapproject/sqlmap#5746]
When I use pip to install version 1.8.6 of sqlmap, a "No Module named 'sqlmap' " exception occurs.
![sqlmap](https://github.com/user-attachments/assets/94c3fba3-a6ca-4396-bb33-ed0ff324f456)

**Comment by stamparm** [comment]
Fixed. You can first uninstall the old package, then install the new one; or just update to the latest version:

![image](https://github.com/user-attachments/assets/6fb99d48-b028-4bd7-acaf-53ff6c6542bd)

**Comment by fitwilliamx12** [comment]
@stamparm thank you bro for saving my life !
