### ISSUE TITLE
What command to use in case the target is active on specific proxy?

### ISSUE THREAD

**Issue by anonhunter** [sqlmapproject/sqlmap#5752]
Hi
Can anyone tell me,
how to scan a target that is only active on specific proxy?
it returns with an error, Connection Timed out to the target URL.
since My system is connected through the proxy already and target is live in my system.
Please help
<img width="823" alt="Screenshot 2024-07-18 at 12 49 06 PM" src="https://github.com/user-attachments/assets/ac1c448c-dbbf-4863-a2c1-b03907936764">

**Comment by stamparm** [comment]
you are being blocked. most probably instantly. use different `--proxy` hosts. you can also try:

`--proxy-file=PRO..  Load proxy list from a file`

it is kind of problematic that you missed filling the template and missed providing which options/switches did you use. closing this down as invalid
