### ISSUE TITLE
Specifying Specific Injection Types and Techniques

### ISSUE THREAD

**Issue by agx47** [sqlmapproject/sqlmap#5766]
I'm just wondering if SQLMap has the option to directly use a specific type and title. I know there are types like technique b, U, etc., but I'm not sure if you can specify something like a title :

MySQL RLIKE boolean-based blind - WHERE, HAVING, ORDER BY, or GROUP BY clause
WHERE, HAVING, ORDER BY, or GROUP BY clause 
directly. Sorry for the trouble; I'm kind of new to SQLMap.

**Comment by stamparm** [comment]
`--test-filter=TE..  Select tests by payloads and/or titles (e.g. ROW)`

**Comment by agx47** [comment]
thank you man
