### ISSUE TITLE
--search function feature

### ISSUE THREAD

**Issue by icenaive** [sqlmapproject/sqlmap#5770]
Hi，
Is it possible to use --search and only dump 2 or multiple found columns and not dump single column?

Example: --search -C --first_col col1,col2 --second_col col3,col4

Only dump when found  first_col1 and second_col - without dumping found alone?

Thanks and hope my question is not confusing

**Comment by icenaive** [comment]
The col of first_col and second_col must match only one col but not all COL, that is, col1 and col3. col1,col4; col2,col3; col2,col4; This will help with automated search requirements. Thank you

**Comment by stamparm** [comment]
oh man. this looks like something i would not implement.

maybe you can try to help yourself with (not sure though, as really couldn't comprehend):

`--where=DUMPWHERE   Use WHERE condition while table dumping`
