### ISSUE TITLE
Unable to get a SQLite db output because of multiple targets mode

### ISSUE THREAD

**Issue by vijayee** [sqlmapproject/sqlmap#5773]
**Describe the bug**
I'm unable to get a sqlite db output from sqlmap due to it always being in multiple targets mode which appears to require csv output. 
There is a line of code that always is triggered regardless of the number of targets specified in the command.
This is line 1783 in option.py where `conf.stdinPipe` is always set evaluating it to true.
```
    if any((conf.googleDork, conf.logFile, conf.bulkFile, conf.forms, conf.crawlDepth, conf.stdinPipe)):
        conf.multipleTargets = True

```

**To Reproduce**
`python3 sqlmap.py  --drop-set-cookie --threads=2 --level=5 --risk=3 --technique=U -p "username,password" -u "http://localhost:3000/?username=absolom&password=chinchillareque" -method POST  --dump-format=SQLITE`

**Expected behavior**
I would expect the end result to be output to a db file rather than a csv file

**Running environment:**
 - sqlmap version 1.8
 - git
 - Ubuntu 22.04
 - python  3.10.12

**Target details:**
 - Postgres
 - locals webserver nodejs/express
 - WAF/IPS  : none
 ```[
12:23:43] [INFO] testing URL 'http://localhost:3000/?username=absolom&password=chinchillareque'
[12:23:43] [WARNING] detected empty POST body
[12:23:43] [INFO] using '/home/victor/.local/share/sqlmap/output/results-08282024_1223pm.csv' as the CSV results file in multiple targets mode`
``

**Comment by stamparm** [comment]
I guess that you guessed that for some reason sqlmap thinks that your STDIN is being redirected through PIPE to sqlmap. Especially in Linux/Ubuntu, it is hard to imagine that that could be happening out of the blue (i.e. without any reasonable explanation)

Anyhow, you can try to "override" such behavior with (hidden switch) `--ignore-stdin`.

**Comment by vijayee** [comment]
This worked quite well. Thanks for your help @stamparm
