### ISSUE TITLE
MANDATORY

### ISSUE THREAD

**Issue by Twonss2** [sqlmapproject/sqlmap#5775]
"sqlmap.py -u siteadı.com --dbs"komutunu kullanıyorum fakat şu hatayı veriyor lütfen yardım :
sqlmap.py: error: missing a mandatory option (-d, -u, -l, -m, -r, -g, -c, -x, --
wizard, --update, --purge-output or --dependencies), use -h for basic or -hh for
advanced help 
i always get this mistake when i open sqlmap on phyton (dont judge me i am noob)

**Comment by stamparm** [comment]
try: `python sqlmap.py -u http://testphp.vulnweb.com/artists.php?artist=1`

if that doesn't work, then most probably you have some issues with the python installation. try to reinstall to some other version and retry
