### ISSUE TITLE
Failure Hosting SQLMap API with Gunicorn

### ISSUE THREAD

**Issue by techonair** [sqlmapproject/sqlmap#5779]
I tried to host the SQLMap API on my Ubuntu server using this command

>>> gunicorn --bind 127.0.0.1:8775 --workers 5 --worker-class gevent --timeout 300 --access-logfile - --error-logfile - sqlmapapi:main

I tried other files bottle.py and api.py but I am getting Internal Server Error.

But when I am running it with the below command it works
>>> python sqlmapapi.py -s

Not sure what's a good solution to this problem

![image_2024_09_13T05_47_01_107Z-1.png](https://github.com/user-attachments/assets/ee61f221-1837-44f0-9f6b-c68f54cae3a4)

**Comment by stamparm** [comment]
sqlmapapi was not meant to be run like this. if you need it, good for you, but there was absolutely no need for this.

to make things worse, there is even an option to run it via gunicorn:

```
--adapter=ADAPTER     Server (bottle) adapter to use (default "wsgiref")
```

For example:
![image](https://github.com/user-attachments/assets/72fbb983-6a9a-41eb-a65e-dfcbf9bc45b1)
