### ISSUE TITLE
Wrong Data Retrive MSSQL

### ISSUE THREAD

**Issue by manoshi2010** [sqlmapproject/sqlmap#5785]
i try to use --hex --no-cast but same problem 
![s](https://github.com/user-attachments/assets/614828ba-f411-4d0a-ab05-f04cef45d23f)

any idea how can i fix it

**Comment by hos903** [comment]
hi , have you tried the swith --binary-fields ? i think it should help

**Comment by stamparm** [comment]
you should use `--binary-fields` in such situations. `encpass` is clearly some encrypted/hashed version of the password

**Comment by stamparm** [comment]
let me show you how to read documentation:

https://github.com/sqlmapproject/sqlmap/wiki/Usage#binary-content-retrieval

![image](https://github.com/user-attachments/assets/e1e0dfb4-aacf-4b02-928c-6f8186ef268a)
