### ISSUE TITLE
Dictionary time-based payload enumeration

### ISSUE THREAD

**Issue by TheLensta** [sqlmapproject/sqlmap#5788]
I apologize if this feature request has already been submitted, I understand the likelihood is very high.

**Is your feature request related to a problem? Please describe.**
Time-based payload enumeration can be very slow, a possible method to speed up the process might be to use underlying dictionary approaches to the attack with a fallback to brute force.

**Describe the solution you'd like**
I'm not an expert on how the enumeration process works but I assume that all possible characters are tested and response times are checked to determine a candidate character which is then added to the enumerated string. I was thinking that a dictionary approach might be able to speed this process up by selecting a presumed candidate character first then testing other characters, whilst this is happening continuously calculate the likelihood that the presumed character is correct and if it breaches a likelihood threshold skip the rest of the current character tests, add the presumed character and start the next character.

If it is not apparent that the presumed character is correct fallback to a brute force method on the current character (both could be happening at the same time so there's no restart on the character).

**Describe alternatives you've considered**
I am not experienced enough to know any alternatives right now

**Additional context**
Not applicable.

**Comment by stamparm** [comment]
1) seems trivial, but it is not. sqlmap doesn't just test all characters. it uses something like the "binary-search" per each character. thus, it is not 256 requests per character place, but 6-7 on average.
2) for dictionary based approach, there is already something like that, but it is "shitty" IMHO. you can't just use 1GB knowledge base and speed up the time-based SQLi. inference based on such knowledge base also requires (you won't believe) network REQUESTS
3) such feature is called `--predict-output` in sqlmap. it relies on the https://github.com/sqlmapproject/sqlmap/blob/master/data/txt/common-outputs.txt, but at the end you won't get much of a speed up, as maybe it will sound strange, but majority of database content which appears to be **interesting to the user** is actually unique (i.e. not part of such knowledge bases)
