### ISSUE TITLE
Not A bug Seeking help plz !

### ISSUE THREAD

**Issue by agx47** [sqlmapproject/sqlmap#5789]
Hey, I found this payload works on the target like this:

www.example.com/'XOR(SELECT(0)FROM(SELECT(SLEEP(9)))a)XOR'Z

The payload is: 'XOR(SELECT(0)FROM(SELECT(SLEEP(9)))a)XOR'Z

I tried using SQLMap, but I didn't get the injection. I used all the risk levels and tamper scripts I know, with and without tamper:

--technique --random-agent --risk=3 --level=5

Is there a way to tell SQLMap to use this payload directly: 'XOR(SELECT(0)FROM(SELECT(SLEEP(9)))a)XOR'Z? Any idea how I can do this?

**Comment by stamparm** [comment]
1) nope. also, that payload comes, if not mistaken from Burp. I am not fan of their payloads and their "time-based" SQLi detection. I would suggest you to play with that payload and try to run with both `SLEEP(9)` and `SLEEP(0)`. there are some WAFs which will make DROPs, fooling the Burp to think that it is a time-based SQLi there
2) i won't implement that payload, as even if it works, there is a reason why other payloads would not work. sqlmap has thousands of other payloads, where, if sqlmap payloads are blocked, and this one really works, then you have something in between which will prevent you to extract any kind of information from the DB
3) for appropriately run sqlmap against such target, you should run it with `-u "http://www.example.com/*"`, so sqlmap would try to inject into the URI itself
