### ISSUE TITLE
output folder doesnt exist.

### ISSUE THREAD

**Issue by KornineQ** [sqlmapproject/sqlmap#5792]
for exampel it says
[21:40:52] [INFO] fetched data logged to text files under 'C:\Users\dumbfurrygay\AppData\Local\sqlmap\output\example.com'     
but that doesnt exist????

**Comment by hos903** [comment]
Hi , its a hidden folder you need to change the settings and show hidden files and folders , otherwise you can directly access to the folder by entering the folder path on a browser

**Comment by KornineQ** [comment]
There is issue i cannot even access them directly
