### ISSUE TITLE
How i can handle this SQL to get into database

### ISSUE THREAD

**Issue by Lightingers** [sqlmapproject/sqlmap#5793]
Example URL:
https://www.xxxxxxx.de/denk/search.php?autocomplete=true

I got this URL. And this URL shows the following SQL error:
![Untitled](https://github.com/user-attachments/assets/6ab3d355-9ebc-44cb-8c76-9b6ccecc5fb4)

If I remove "true" at the end, I get a white page (https://www.xxxxxxx.de/denk/search.php?autocomplete=XXX)
But if I append any letter or number to the parameter, I get this SQL error like in the screen above.

**sqlmap command:**
sqlmap.py -u "https://www.xxxxxxxx.de/denk/search.php?autocomplete=" -p "autocomplete" --technique=BEUSTQ --level=5 --risk=3 --random-agent --threads=10 --timeout=60 --dbms=mysql --flush-session

[20:49:45] [WARNING] GET parameter 'autocomplete' does not seem to be injectable
[20:49:45] [CRITICAL] all tested parameters do not appear to be injectable. As heuristic test turned out positive you are strongly advised to continue on with the tests

What is my mistake? If you need more details, please write here. Im new here on github.
Thank you very much!

**Comment by stamparm** [comment]
sqlmap always warns you to use **VALID** values. thus, why would you use this is beyond my comprehension:

![image](https://github.com/user-attachments/assets/78136a7c-1636-4b7e-b6cb-1de340afbb8b)

**Comment by Lightingers** [comment]
I found the URL with valid values = status http 200

**Comment by stamparm** [comment]
HTTP code 200 doesn't mean that the parameter is "valid". It means that the web page can process the request.

You have to use a valid "term=XXX" (if term=a results with something meaningful, other than dummy 200, then use that one)

**Comment by Lightingers** [comment]
> HTTP code 200 doesn't mean that the parameter is "valid". It means that the web page can process the request.
> 
> You have to use a valid "term=XXX" (if term=a results with something meaningful, other than dummy 200, then use that one)

Sorry, I didn't explain what exactly is output when I put a letter or number in the value for the "term" parameter. A valid value is given and I also get valid output, not dummy values ​​or anything else. If I put a ' or ", I don't get an error. The error only occurs if the parameter is empty.

Here is an example with the search "a" in the parameter term:
![Untitle33d](https://github.com/user-attachments/assets/a823c74a-c72d-4859-81f9-194a61c0aab2)
