### ISSUE TITLE
Improve boolean blind injection

### ISSUE THREAD

**Issue by Strongys90** [sqlmapproject/sqlmap#5797]
About a year ago a new open source tool came out called hakuin https://github.com/pruzko/hakuin made for faster boolean blind data extraction. it is extremely quick.
Hakuin, a new open-source framework that leverages Machine Learning and statistics to optimize BSQLI. Hakuin uses probabilistic language models trained on millions of tables and columns extracted from Stack Exchange questions to infer DB schemas. To infer DB content, it utilizes several strategies including adaptive language models and opportunistic string guessing. Compared to the state-of-the-art (SOTA) BSQLI tools, Hakuin is about 6x faster on DB schemas, up to 3.2x faster on normal DB columns, and up to 26x faster on columns with limited values.

Just a suggestion to rework boolean blind injection methodology in sqlmap taking it from hakuin to make data extracting from boolean based injection faster.

**Comment by stamparm** [comment]
oh man, i really gave it a shot, but this "hk" is a total mess. i am not able to run it even after 10 minutes of coping with it
