### ISSUE TITLE
Some bugs with common tables and columns check

### ISSUE THREAD

**Issue by kobyan** [sqlmapproject/sqlmap#5798]
1. If the common tables check is performed without a schema name (in the current schema), then the log will output the table names with None as the schema name
```
[INFO] fetched tables: 'None.news', 'None.usuario'
```
2. If several table names are specified for column definition (-T news,usuario --columns), then in the definition method via information_schema sqlmap tries to get columns first for one table, then for the next one, but in the common columns check method sqlmap tries to check columns for the table `news,usuario`
```
[PAYLOAD] -6177'Or exisTs(SeleCT rid fROm **redacted**.`news,usuario`)aND'1'='1
```

**Comment by stamparm** [comment]
thank you for reporting it
