### ISSUE TITLE
SQLMap Tamper Full Body Request.

### ISSUE THREAD

**Issue by alicangnll** [sqlmapproject/sqlmap#5803]
Hello,

I want to develop new tamper for SQLMap. I need HTTP Body values but i can just get payload value. How can i get full HTTP Body? Or can you add this option?

![image](https://github.com/user-attachments/assets/2884d6c6-e9cd-4ecd-a2de-2cc350bd1af6)

**Comment by stamparm** [comment]
just went through options. seems like a total mess to include. POST body would not even be usable in your case (in tamper script) as it would be unknown for it before the processing of the payload itself (that same payload you are getting right now)
