### ISSUE TITLE
weird output from available databases

### ISSUE THREAD

**Issue by SolanaDeveloperr** [sqlmapproject/sqlmap#5814]
sqlmap is giving me weird outputs.

![image](https://github.com/user-attachments/assets/10d3e558-8012-4056-8606-efc91861051e)

**Comment by stamparm** [comment]
either 1) you have a false-positive or 2) you have something in between messing with responses (e.g. WAF) or 3) you have a time-based SQLi with unstable connection

i would suggest you to restart everything with `--flush-session`. after that, if you are not able to at least get anything useful with `--banner`, you have an unusable target
