### ISSUE TITLE
How to disable some functions when listing data in sqlmap, such as ord

### ISSUE THREAD

**Issue by hackd0g** [sqlmapproject/sqlmap#5823]
**Is your feature request related to a problem? Please describe.**

When injecting dabase(), if there is an ord function, the data cannot be output correctly

**Describe the solution you'd like**

ORD(MID((HEX(IFNULL(CAST(DATABASE()/**/AS/**/NCHAR),0x20))),1,1))>1

I want to have a function that disables a function. For example, if I want to disable the ord function, then the statement becomes

MID((HEX(IFNULL(CAST(DATABASE()/**/AS/**/NCHAR),0x20))),1,1)='d'

**Describe alternatives you've considered**

**Additional context**

**Comment by stamparm** [comment]
there is no such thing in sqlmap as sequential "inferring" by ASCII char table. TL;DR: you are trying to make hundreds of requests per character, and sqlmap doesn't support that
