### ISSUE TITLE
Add option for disable analyzing table dump for possible password hashes

### ISSUE THREAD

**Issue by kobyan** [sqlmapproject/sqlmap#5827]
For large tables, analyzing table dump for possible password hashes takes a lot of time, and it is not always needed. Therefore, it would be good if it could be disabled by a parameter, or ask the user whether this analysis is needed, as is done for store hashes to a temporary file or crack them

**Comment by stamparm** [comment]
with latest revision:
`--disable-hashing   Disable hash analysis on table dumps`
