### ISSUE TITLE
Add multithreading support for common tables and columns existence checks

### ISSUE THREAD

**Issue by kobyan** [sqlmapproject/sqlmap#5829]
Currently common tables and columns existence checks are done in one thread and therefore they are very slow. Please add multithreading to this functionality.

**Comment by stamparm** [comment]
this is implemented for ages. you are even asked during the run (if you haven't used `--threads`) that it is going to be slow, and that you can enter number of threads manually:

![image](https://github.com/user-attachments/assets/d214c8fb-37c5-4f5d-bb25-64fa43d20506)
