### ISSUE TITLE
The NULL problem in columns

### ISSUE THREAD

**Issue by CATSDANC** [sqlmapproject/sqlmap#5830]
Hi, I ran into such a problem, the data from the table is being unloaded incorrectly, some columns have NULL when dumped.

`+-----+---------+---------------+---------+------------+---------------------+-------------+
| id  | columns 1 | columns 2 | columns 3| columns 4 | columns 5          | columns 6  |
+-----+---------+---------------+---------+------------+---------------------+-------------+
| 1   | 103     | 25            | NULL    | NULL       | 2020-03-11 21:11:18 | NULL        |
| 5   | 103     | 26            | NULL    | NULL       | 2020-03-11 21:11:41 | NULL        |
| 19  | 4       | 133           | NULL    | NULL       | 2021-02-18 17:07:07 | <blank>     |
| 23  | 3       | 12            | NULL    | NULL       | 2021-03-30 18:00:03 | <blank>     |
| 43  | 99      | 33            | NULL    | NULL       | 2020-08-01 00:53:38 | g4rvhaxnusq 

I have used a lot of Tamper, but nothing helps, in some cases columns 3 gives the result -  
`\x1a÷\x8d\x85\x11e\x91ÁÕ\x14\x89D\x94bEBB®°NÙ\x16kj°çQQ\x13`Âµ´y`

I'm using -v 3, but there are no error messages, what could be wrong? The columns are definitely not empty.

**Comment by stamparm** [comment]
1) if you have WAF, i can't help
2) if you get junk everywhere, you could have false-positive
3) if you are having binary columns, you should use https://github.com/sqlmapproject/sqlmap/wiki/Usage#binary-content-retrieval

**Comment by lekosbelas** [comment]
They can be NULL columns or binary columns
