### ISSUE TITLE
Unable to retrieve the table names for any database in MYSQL

### ISSUE THREAD

**Issue by Ako0ri** [sqlmapproject/sqlmap#587]
Hi
SQLMap give me 8 database And I can dump tables,columns and any data from 6 databases like mysql
But I have 2 database like site_class and site_classfield and when I try to get table names It give me this error :
Unable to retrieve the table names for any database
What can I do?! Please help me
Regards

**Comment by sonali97** [comment]
Hi all,
I am having a trouble in listing the trove database tables inside MySQL, kindly help me if anyone knows the resolution.

**Comment by cankaptan1976** [comment]
Hi Dear,

If you make it clarify i'm sure than someone will go ahead for help

Can you give more details ?
