### ISSUE TITLE
Unable to find vulnerable url in crawl mode

### ISSUE THREAD

**Issue by sagakrypto** [sqlmapproject/sqlmap#604]
Hello! There. Recently i was testing a website for sql injection so i started to crawl the whole website using code sqlmap.py -u http://www.website.com/ --crawl=2, after crawling the whole website it starts testing for sql injection in each of the crawled url. After scanning few urls it ends up with " SQL injection vulnerability has already been detected against 'www.website.com'. Do you want to skip further tests involving it. The problem here is i can't identify which of the url is vulnerable. Please help.

**Comment by hahahahahahahahahahahahahahahah** [comment]
> Hello! Stamparm, thanks for your quick response but the log file is empty with 0 byte size. On running crawl mode in sqlmap the crawled urls are stored in .csv files which is also empty.

yeah!! windows dont have logs.....

**Comment by AbdulConsole** [comment]
### If You Are On Termux.

cat ~/.local/share/sqlmap/output/www.target.com/log
