### ISSUE TITLE
Pressing Y or enter closes SQLMap

### ISSUE THREAD

**Issue by daemeonzane** [sqlmapproject/sqlmap#645]
![researchmaterials](https://f.cloud.github.com/assets/3394996/2454161/c2cc5c12-aee6-11e3-9f84-30a2147989d2.jpg)

As seen in this picture (IP's and UR:'s edited for security), upon hitting enter to accept the default Y answer, SQLMap closes. I have had this issue for 48 hours, and ran a few updates, etc, to ensure it was not an issue fixed in a newer version, to no avail. Any time that SQLMap queries me for any type of answer or user input, it is rejected and the software stops.

**Comment by Gazzty** [comment]
I know this was years ago, but I had the same issue. This seems to happen when you have an & sign in the URL. To solve it I just put the URL in between quotes e.g. sqlmap -u "www.google.com/user=123&pass=456".
