### ISSUE TITLE
sqlmap fetching users problem

### ISSUE THREAD

**Issue by anasri** [sqlmapproject/sqlmap#649]
Hi Guys

I have problem with grabbing users from tables with sqlmap 

I tried to inject with Havij and its ok but with sqlmap i only get 4 users 

[REDACTED]

idmore  tp  username     password
9999    1   9999    9379745858
99  2   99  91
0   3   admin   123

please check and my issue .

**Comment by hysia** [comment]
You‘r  waste  time, Try Google first!
