### ISSUE TITLE
[Feature Request] Flush single query cache

### ISSUE THREAD

**Issue by steelbrain** [sqlmapproject/sqlmap#689]
Currently, It's possible to flush the session files completely. I would be more than happy to have a feature by which we can clear cache for a single query executed via `--sql-query`.

**Comment by Rex-0x7CB** [comment]
`--fresh-queries` starts dumping the data as a fresh query however, it also starts to dump the entire schema of the table. It can take a long time in case of a time-based blind SQL injection specially where the table has a lot of columns.

For example, `python sqlmap.py -u "https://example.com/login" --data="username=CvtKev&password=b2" --level=5 --risk=2 --dump --dbms=MySQL -p "username" --threads=5 -T userInformation --where="userID=2"` would trigger sqlmap to download the name of all the columns in the table before actually downloading the data. This gets tedious when working with a time-based blind injection.

It'd be great if we can simply delete one entry from the cache and proceed with the regular dump.
I'm open to other ideas. Let me know your thoughts.

**Comment by stamparm** [comment]
@Rex-0x7CB if you are dealing with invalid dump values containing `?` inside, you could try to use `--repair` instead of the `--fresh-queries`. I am giving this option because I don't know what kind of values were the problem in the first place in your case
