### ISSUE TITLE
Support for -E alongside --search

### ISSUE THREAD

**Issue by inquisb** [sqlmapproject/sqlmap#7]
Add support to search for a specific row in the table given its content snippet (LIKE '%value of -E%')

**Comment by stamparm** [comment]
Currently able to do it with `--where` (https://github.com/sqlmapproject/sqlmap/wiki/Usage#dump-database-table-entries). For example: `--where="name LIKE '%admin%'"`. Also, in case of `-E` there would be a requirement to either: A) use also `-C` that would hold a specific column name or B) to search through all column names. This way, with `--where` it is a straightforward solution for similar behavior
