### ISSUE TITLE
please use ~/.sqlmap for output by default

### ISSUE THREAD

**Issue by blshkv** [sqlmapproject/sqlmap#746]
The current logic of the default location is not clear. For root user, sqlmap writes to "systempath/output" directory. For regular users it will still try to write to that directory if it exists, and will switch to /tmp directory because it's not writable.

I suggest to use $home/.sqlmap by default. The software should not write to random directories on the file system, this is not distro-friendly. Also, /tmp directory is mounted to RAM usually which means all results will be gone after a reboot.

Thank you.

**Comment by kalirami1986** [comment]
Is it possible to configure the sqlmap's output directory to another
path?

**Comment by blshkv** [comment]
yes, in sqlmap.conf:
```
outputDir = 
```
