### ISSUE TITLE
Option to ignore empty cells

### ISSUE THREAD

**Issue by roo7break** [sqlmapproject/sqlmap#75]
An option to check a column/table/database for being empty or not would be useful to speed up enumeration.

**Comment by iGeek098** [comment]
can it be optional

i was pentesting  a sqlite which contained cells that has null as default and it retrieves THE WHOLE table as null , don't know it it's related but debug says (skipping as column appears to be empty)

**Comment by stamparm** [comment]
@iGeek098 has that column had any non-NULL entries? I am not sure that the `DEFAULT NULL` caused the problem in your case. What's the content of the whole table?

**Comment by iGeek098** [comment]
I edited a part of the code (it was making a count(%Column name%) before starting an if it's zero it makes all entries NULLs)

and no all of them were nulls

but after i commented the code that checks switch count()//sql query// and it returned the entries correctly
