### ISSUE TITLE
Add support for socks proxy

### ISSUE THREAD

**Issue by stamparm** [sqlmapproject/sqlmap#91]

**Comment by doraeric** [comment]
Will all_proxy with socks scheme be support?

It only works with http and https scheme now

**Comment by stamparm** [comment]
@doraeric you can find it implemented (support for `all_proxy`) with the latest revision

**Comment by doraeric** [comment]
Thanks!

Actually, I have traced the code, `urllib.request.ProxyHandler.proxies` will return a dict of environment variables ended with '_proxy' after converting to lower case by default.
Thanks anyway!
